### ISSUE TITLE
no email sent to reset password if it has offended character no longer allowed?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1002]
My summer student couldn't remember her password. She went to change it but when she put in her email no email was sent. I'm pretty sure the account and one of the now forbidden characters in it.  Her email the account is under is 7.gaurisharma@gmail.com

**Comment by camallen** [comment]
This is a backend data migration issue, looking into it now.

**Comment by camallen** [comment]
@mschwamb should be fixed now - reopen if not.

**Comment by mschwamb** [comment]
Thanks @camallen I will let you know
