### ISSUE TITLE
Chrome reports zooniverse.org has a weak security config

### ISSUE THREAD

**Issue by ttfnrob** [zooniverse/Panoptes-Front-End#1005]
Chrome 43 (Mac 10.10) reports a weak security for zooniverse.org due to outdated security settings.

<img width="389" alt="screen shot 2015-07-08 at 10 54 10 am" src="https://cloud.githubusercontent.com/assets/83192/8568449/9f515354-2565-11e5-81b0-4daf93dcd727.png">

**Comment by camallen** [comment]
@ttfnrob thanks, we're working on fixing this.

**Comment by astopy** [comment]
I blame Google.

**Comment by ttfnrob** [comment]
Oh yes, forgot to say: BOO!

**Comment by mrniaboc** [comment]
It's about time you got back to work! Where have you been?

**Comment by chrissnyder** [comment]
Definitely a Chrome bug. Should report that to someone...

**Comment by edpaget** [comment]
Is this just about using a SHA1 finger print?

**Comment by edpaget** [comment]
Turns out it is.
