### ISSUE TITLE
Add text explaining about non-Zooniverse projects

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#1007]
For projects that are not yet Zooniverse-approved (such as Monople Quest) we need to make that clear in thee footer by adding some text. Something like:

"This project has been built using the Zooniverse Project Builder but is not yet an official Zooniverse project. Queries and issues relating to this project directed at the Zooniverse Team may not receive any response."

**Comment by DarrenMcRoy** [comment]
I'd like that.

**Comment by aliburchard** [comment]
+1

**Comment by chrislintott** [comment]
@chrissnyder Can we prioritize this please?

**Comment by DarrenMcRoy** [comment]
I have zero objections to Grant's text; it's perfect.

**Comment by edpaget** [comment]
Should this be in the footer of every page of the project or just the landing page?

**Comment by chrislintott** [comment]
I think it makes sense in every page.
