### ISSUE TITLE
when you favorite and then click again to unfavorite an an image the heart is still pink

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1015]
for me it was then unclear if I unfavorited the image since it stayed pink the whole time

**Comment by vrooje** [comment]
Wait, it goes pink?

I was coming here to post an issue about favoriting images from Talk and the heart never changing color at all. I've never had a pink one...

**Comment by yshish** [comment]
For me, it sometimes works and sometimes doesn't.

2015-07-13 13:36 GMT+02:00 Brooke Simmons <notifications@github.com>:

**Comment by mschwamb** [comment]
It goes pink on Talk. Had assumed it did that system wide now.

**Comment by mschwamb** [comment]
My issue has been solved with other commits addressing favorites so closing this specific ticket I made
