### ISSUE TITLE
All of the help content, research page, education page, faq page content disappeared from Planet Four Terrains

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1022]
I'm not seeing any of the content that we had on the site. It was there earlier today. I'm pretty sure I didn't do anything to delete it. Can someone help? Do you see the same thing?

**Comment by mschwamb** [comment]
The project builder is blank on all of those pages - the help content looks like it's there in the locked screen but the help button doesn't work now on the site along with all the missing content

![screen shot 2015-07-10 at 2 00 27 am](https://cloud.githubusercontent.com/assets/753325/8602907/824b23d2-26a7-11e5-9d39-8a3f2c1df494.png)

**Comment by mschwamb** [comment]
@chrissnyder and @edpaget what happened?  Can you help? It can't be one of the science team accidentally deleting everything get the help is intact but not showing.

**Comment by mschwamb** [comment]
Whales project is the same way ccing @aliburchard

**Comment by mschwamb** [comment]
And the whales project too - only one that looks okay is Galaxy Zoo Bar Lengths

**Comment by edpaget** [comment]
Sorry I was deploying a change that needed the front and backends to be in sync and the front end deploy is taking a lot longer than I anticipated. It'll be deployed out soon and the pages will be back.

**Comment by mschwamb** [comment]
but this impact the help buttons, so for my project pretty much a person coming in right now doesn't know how to do the project - maybe they'll hit the guide link maybe not. If classifications are still being collected, can you give me the rough times this stated and ended, so if we see something funky in the data reduction we can remove/ignore those classifications

**Comment by edpaget** [comment]
Sure this would have started at 12:50 Central US Time. I'll close the issue when it's resolved.

**Comment by mschwamb** [comment]
It's nearly 3 am in the morning for me, so I'm going to try and go back to bed. @edpaget  if you don't mind  checking that me entering the project builder to check what happened doesn't overwrite what's being redeployed (i imagine it won't) for P4 Terrains  once it's deployed I'd appreciate it.

**Comment by mschwamb** [comment]
Couldn't sleep - I saw this got closed and the content is back, but the help boxes don't work - getting 'TypeError: this.context.router is undefined' in the browser - is that to be expected @aweiksnar and @edpaget ?

**Comment by edpaget** [comment]
I'm not getting the same error anymore try clearing your cache?

**Comment by edpaget** [comment]
Ah nevermind looks like the deploy alex and I did was just overridden.

**Comment by edpaget** [comment]
@mschwamb should be set again.

**Comment by mschwamb** [comment]
@edpaget yep now it works. thanks.
