### ISSUE TITLE
results and education pages showing even if there is no content on it

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1025]
The latest update now makes pages you have no text on show up

https://www.zooniverse.org/#/projects/vrooje/galaxy-zoo-bar-lengths/education
https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/results

Can you please make the behavior what it was before where if there is no text the pages disappear?

**Comment by edpaget** [comment]
This has been done.

**Comment by mschwamb** [comment]
Thanks @edpaget
