### ISSUE TITLE
Added two people one after each other to a collection and it lists the same first person twice 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1027]
![screen shot 2015-07-10 at 8 41 52 pm](https://cloud.githubusercontent.com/assets/753325/8619517/5e79ba56-274a-11e5-8b24-863da6275fc9.png)

until I moved somewhere else and come back - then it's fine and has the correct people list

![screen shot 2015-07-10 at 9 30 09 pm](https://cloud.githubusercontent.com/assets/753325/8619605/eaec5b7e-274a-11e5-9f4e-d12179386afe.png)

**Comment by mschwamb** [comment]
Not sure if this is exactly the same thing as above.  I added two more people to that collection as viewers 
in one go and it repeated Cam and Chris' name instead of the people I wanted. Moving back to another tab and back then I did see the names of the people I added

![screen shot 2015-08-30 at 9 17 28 am](https://cloud.githubusercontent.com/assets/753325/9565297/7f59ec42-4ef9-11e5-9117-ed0b070256c5.png)

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
