### ISSUE TITLE
My stats/Ribbon doesn't show correct data

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1028]
A few problems with My stats:
- It doesn't show all projects I've been participated in. There are only 4 of them instead of cca 17. 
- The ribbon shows only one project, the one I've been most active in (Plankton Portal).
- When you compare the number from my ribbon (under the cursor) with the number displayed in the image of Plankton Portal (listed below), they're different. The bottom one shows only the first three figures from the number in the ribbon.

Here is a [screen shot](https://lh3.googleusercontent.com/-__J5YAonLXc/VZ_zY-Ap2YI/AAAAAAAAIGw/5prqZmg5gN8/s0-Ic42/ysh_2015-07-10.jpg).

**Comment by edpaget** [comment]
We're still in the process of importing those classifications and they will show up when the import is done.

**Comment by camallen** [comment]
If you classify on a project they will show up too.

**Comment by yshish** [comment]
Well, other projects did appear in the list after classifying but the number display is still wrong. I mean, the whole number doesn't fit into the image so you can see only its first three figure, others are obscured. Bigger numbers as 148 000 appear as 148! (Check out the screen shots*).

There is no total count displayed anywhere.

*Here is my current ribbon display - 7 projects listed but only two colours displayed in the ribbon. From the first [screen shot](https://lh3.googleusercontent.com/-1I4qialLRaE/VaORgGpk9XI/AAAAAAAAIHQ/5OgyLSiXs7Q/s0-Ic42/ysh_2015-07-13x.jpg) we can tell that the purple colour is for the Plankton Portal which pops-up when hoovering over it with the cursor. But the second [screen shot](https://lh3.googleusercontent.com/-c-czIJRFKgA/VaORe0bU4wI/AAAAAAAAIHI/nsU6Ojxyowo/s0-Ic42/ysh_2015-07-13y.jpg) shows that we can't tell what is the grey colour for. Nothing pops-up. 

Why any of the other projects doesn't display in the ribbon? Shall I wait longer for some more import or is there an issue? (I think that at least the wrong number display has nothing to do with the importing process.)

**Comment by vrooje** [comment]
Quick note: if GZ has finished importing then I'm having an issue too. They're not all wrong, and in fact I'm now seeing what I think are correct classifications where the old profile page was wrong, but my GZ classification count is low by about a factor of 5.

**Comment by edpaget** [comment]
@vrooje I don't think they're done importing, but if classifying on GZ now those should be recorded to the new backend

**Comment by camallen** [comment]
@vrooje - thanks you found a bug in the import code. I've fixed this and re-imported your details, any chance you can check quickly?

**Comment by vrooje** [comment]
Yep! That looks like the right number now.

**Comment by camallen** [comment]
Can you classify on gz for me and test it again, i think I've found a problem.

**Comment by vrooje** [comment]
Whoa, yeah, I did 3 classifications on GZ and instead of going up by 3 it went *down* by 77...

**Comment by vrooje** [comment]
Whoa, yeah, I did 3 classifications on GZ and instead of going up by 3 it went *down* by 77...

**Comment by JeanTate** [comment]
Not sure where things are up to re importing projects and data, but Snapshot Supernova does not show up in my stats (I did, indeed, do some classifications there). While it's a 'retired' project, so is Ice Hunters (which does show up).

**Comment by vrooje** [comment]
Hmm, Snapshot Supernova doesn't show up for me either.

**Comment by camallen** [comment]
Yeah - it's one we have to setup as well. There's an issue with the current setup to work with legacy project counts, https://github.com/zooniverse/Panoptes/issues/1103. I've stopped data migrations till i get this fixed and will restart them again when done (including snapshot supernova - https://github.com/zooniverse/Panoptes/issues/1122).

**Comment by DarrenMcRoy** [comment]
Updating this to note that the stats page is still only displaying the first three numbers--my 1234 classifications in Chicago Wildlife Watch display at "123."

This is a fairly big issue as it can make it look like we are only registering 10% (or 1%, or 0.1%!) of classifications.

**Comment by brian-c** [comment]
@DarrenMcRoy the number display should be fixed when the next deploy is finished, sorry about that.

Are all the import issues resolved now?

**Comment by DarrenMcRoy** [comment]
@brian-c Cam is still working on this: https://github.com/zooniverse/Panoptes/issues/1103

To quote him, "I need to rework the internals and import the data again."

**Comment by chrissnyder** [comment]
Checking in on this again. Anyone have other import count issues that are out there?

Looks to be correct to me, judging by my own counts

![](https://i.imgur.com/SjwbXe7.png)

**Comment by JeanTate** [comment]
"Galaxy Zoo" is only that from when Talk started, right? It doesn't include
any classifications/stats from the older iterations, does it (e.g. the
original, Supernova)?

Snapshot Supernova shows as an image without a count (stat); the main site
is still blank, perhaps that's why?

**Comment by chrissnyder** [comment]
Yea, it would only display stats from projects launched post September 2012 (thereabouts anyway).

Snapshot Supernova might be a special case as we were on an early version of the current system.

**Comment by JeanTate** [comment]
Thanks.

I think that the 'forgetfulness' of the stats, wrt earlier projects, is
important to point out. I know a lot of us 'oldbie' GZooites are proud of
what we did 'back then' and many do not understand why today's Zooniverse
seems to have forgotten about all those millions of 'old clicks'.

Re Snapshot Supernova: if the stats cannot be displayed, I think it would
be better to leave the project out (and somewhere note why); alternatively
perhaps "coming soon" instead of a number?

Hope this helps,
JT

**Comment by edpaget** [comment]
It should include whatever status the old zooniverse home had.

**Comment by parrish** [comment]
Pretty sure this is sorted out now
