### ISSUE TITLE
Adding the toolbar that you can use when making a Talk post in the private message window

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1031]
Right now someone has to add themselves the syntax for making links and bolding word when writing a private message. In the Talk when you write a new post there is  tool bar that will add in the markdown if clicked. This toolbar should also be above the private message editor

I'm asking to add this:

![screen shot 2015-07-11 at 8 07 48 am](https://cloud.githubusercontent.com/assets/753325/8631206/fa7513b6-27a3-11e5-8014-f509ba9e8960.png)

to this

![screen shot 2015-07-11 at 8 02 30 am](https://cloud.githubusercontent.com/assets/753325/8631208/04814366-27a4-11e5-84b9-43929129efa2.png)

**Comment by aweiksnar** [comment]
closed in  #1199
