### ISSUE TITLE
Links and Markdown don't work in private messages

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1032]
If you write a url out in a private message  it doesn't become a automatic link like it does in Talk posts. Also when you write in markdown in a private message reply it doesn't work at all

Being able to add links both straight by writing it out and using markdown is pretty important for private messages. Many times volunteers are asking in a private message for help on thread or want to report an issue going on in a thread.

**Comment by DarrenMcRoy** [comment]
I'm closing #902 in favor of this more general one.

Direct messages currently only support blocks of text.

Normal post functionality should be added to them.

**Comment by mschwamb** [comment]
@DarrenMcRoy This was a very specific behavior/issue. I think you want to keep your previous ticket open

**Comment by DarrenMcRoy** [comment]
Nah. My issue was just about paragraph breaks... unnecessarily specific. If markdown functionality is added, then graf breaks should start working too!

In fact, I think PMs should just have identical functionality to all other posts. Any reason why not?

**Comment by mschwamb** [comment]
I know there's lot of high priority tickets. Is this something that could be in Sprint 2 ? I think getting the formatting of the private messages  easier to read with lines breaks and ability to add usable links would be really helpful for the more veteran volunteers using the new Talk and message each other and science teams frequently.
