### ISSUE TITLE
Size of the private message text box is extremely small

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1033]
low in the queue, The current reply box for a private message is not very user friendly in terms of size. It's only big enough to view one or two lines. I'm constantly resizing it

Can it be made longer by default? 

Below is what size it looks like for me on Firefox

![screen shot 2015-07-11 at 8 07 48 am](https://cloud.githubusercontent.com/assets/753325/8631289/8292481c-27a5-11e5-8f86-557e533b837c.png)

![screen shot 2015-07-11 at 8 02 30 am](https://cloud.githubusercontent.com/assets/753325/8631296/ac523158-27a5-11e5-86d8-8d264ce5f82c.png)

![screen shot 2015-07-11 at 8 19 45 am](https://cloud.githubusercontent.com/assets/753325/8631298/aeef08e6-27a5-11e5-924f-aae9b305d8af.png)

**Comment by DarrenMcRoy** [comment]
+1. Have the default be small is odd, and not everyone is going to know that you can stretch to expand.

**Comment by mschwamb** [comment]
@aweiksnar  This wasn't fixed if you you're in a reply thread 

![screen shot 2015-07-17 at 9 54 43 am](https://cloud.githubusercontent.com/assets/753325/8739134/5d170036-2c6a-11e5-94cb-b20901a95525.png)

- looks great on the inbox area. Can you reopen and eventually do that with the replies?

**Comment by aweiksnar** [comment]
@mschwamb Sure thing- I'll have that change up soon, I've been kinda waiting on updating those since they'll become markdown inputs similar to comments

**Comment by mschwamb** [comment]
Cool - thanks
