### ISSUE TITLE
Stuck in private message thread 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1034]
When you click on the new message envelope icon on the top bar, it takes you to your inbox. If you click on the message thread with the new message, you got the private message thread between you and the other user but then there's no way to go back into the mailbox other than by clicking the envelope icon on the top right

I think there should be some link on top of the message thread that can take you back to your mailbox

**Comment by chrissnyder** [comment]
Agreed. A simple "Back to Inbox" link at the top would work.
