### ISSUE TITLE
When you look at your inbox, the date listed is for the original thread not when it was last updated

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1036]
In your inbox, you have a list of private message threads. It now says X days ago. The X it is reporting is for the first message in the thread, not the time since the last post. It would be helpful especially if it also listed the time since the last reply/last time updated

**Comment by DarrenMcRoy** [comment]
Agreed as well.

**Comment by vrooje** [comment]
+1
