### ISSUE TITLE
Adding ability for moderators to lock Non-Note board discussion threads on Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1039]
Right now you can lock a message board and make it write only by admins, but currently not a specific thread. This feature has been used by moderators  in boards on previous Talks to end arguments between volunteers and end discussion on things that more than already played out and are just rehashing rather than civil conversation. It's not a frequent thing, but it would be helpful if this existed.

**Comment by DarrenMcRoy** [comment]
This is basic forum functionality and should exist ASAP.
