### ISSUE TITLE
Ribbons should only show live/retired projects rather than all projects including private and in beta projects? 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1040]
low in the queue and more of a question - My ribbon shows projects that aren't live or are private-  I think the ribbon should only be for live/retired projects  - though maybe that doesn't matter if the ribbons are private

**Comment by CKrawczyk** [comment]
Or there could be a 2nd ribbon for the private/not live projects.

**Comment by vrooje** [comment]
If/when we give users the option of displaying a ribbon below their avatars, I agree non-live & non-public projects should either not be included or should all be lumped together into 1 gray bar, or similar. (I can think of cases where people will *only* classify on private projects so I wouldn't want to deprive them of a ribbon if they want to show it when asking questions on Zoo Talk... but also I don't think it's a huge issue.)

**Comment by eatyourgreens** [comment]
I'm pretty sure the home page ribbon now only shows live projects you've classified on.
