### ISSUE TITLE
If you click on a user profile and then user collections you lose the rest of the navigation bar

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1041]
You kind of get stuck in the person's collection and have to hit the back button to get back to their user profile- I'm not sure if there's an easy way to keep the navigation bar 

 the screen shots might help explain better

on the user profile - on the message tab

![screen shot 2015-07-11 at 9 17 26 am](https://cloud.githubusercontent.com/assets/753325/8631618/e8ce3480-27ad-11e5-850c-179346017a5f.png)

going from messages to recent posts via the navigation menu

![screen shot 2015-07-11 at 9 17 24 am](https://cloud.githubusercontent.com/assets/753325/8631624/1b14e2f4-27ae-11e5-9512-f388e8fc09be.png)

Now when you click on the collections tab for that user  - there's no way to go back to recent posts unless  I click the browser back button

![screen shot 2015-07-11 at 9 17 30 am](https://cloud.githubusercontent.com/assets/753325/8631620/fb666784-27ad-11e5-8fab-e957cfe16848.png)

**Comment by edpaget** [comment]
I this works as intended.

**Comment by alexbfree** [comment]
this is now fixed by #2804
