### ISSUE TITLE
Add filters to view collections that correspond to a specific project

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1042]
Now that all collections are displayed globally for a user, if I just wanted my collections that include subjects related to a specific project, I have to find it through my numerous collections. I think it would be very handy to be able to filter by project so that collections that have a subject added from a specific project show up in a search

**Comment by DarrenMcRoy** [comment]
@edpaget question ... will the sorting mechanism that is being developed for projects work well for collections, too?

**Comment by chrissnyder** [comment]
We would need to somehow attach a collection to a given project, but project-focused collections have come up a lot, so we'll be exploring ways to make them more useful in a project-context.

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
