### ISSUE TITLE
Putting the csv dump links in a separate data section of the project builder

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1045]
low in the queue - I keep getting confused and having to remember where the links are to download the data. Could the two data dump links be put into a separate section/tab on the project builder?  Looking at the navigation links if I haven't been to the project builder in a while, I wouldn't intuitively think that project details is where I would go to get csvs of the classification database and the subject data. I think putting them in their own section would be useful especially for team members of a project who didn't really build the site but are helping with data analysis

**Comment by mkosmala** [comment]
+1 
I also find the current location unintuitive. (But yes, low in the queue.)

**Comment by vrooje** [comment]
Yes, eventually I'd like a "Data & Stats" page where you could see your project analytics and download the data. (Somehow it makes sense to me that these would be in the same place, but I could be talked out of that too.)

**Comment by aliburchard** [comment]
Yup, low in the queue, but I like the "data and stats" page.

**Comment by mschwamb** [comment]
Now that there is the Talk data, it would be really nice if there was a separate Data Export Tab. Eventually people who build a project will only go for data exports, and probably not very often given the time it takes to get classifications. It's not very intuitive that it's under the project details, so I think a separate tab in the project builder  would be useful for research teams
