### ISSUE TITLE
Gracefully handling  trying to go to a restricted access Talk board while non-logged in -

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1047]
low in the queue - Talk should gracefully handle trying to go to a restricted access board or thread while non-logged in or for an account that doesn't have access - currently get a bunch of errors/json spit out

![screen shot 2015-07-13 at 10 02 28 am](https://cloud.githubusercontent.com/assets/753325/8641379/dc3c5162-2946-11e5-8c5b-cbfc486282ac.png)

**Comment by mschwamb** [comment]
Also then it had trouble letting me sign in at that point the loging box gave this after I typed in my username and password  'TypeError: Cannot read property 'page' of undefined'  - I had to navigate to another page to get the sign in box to not throw the error

**Comment by DarrenMcRoy** [comment]
I just rant into this, and yeah, ew. Would be nice to clean that up.
