### ISSUE TITLE
The list of translators is missing

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1049]
Will you display the list of translators somewhere? Will you add new translators? (There are some volunteers currently translating the PW texts.)

**Comment by mschwamb** [comment]
There will be some more translation effort going on in Taiwan, so it would be great if there was a new acknowledgement page for translators in the near future cc @chrislintott

**Comment by chrissnyder** [comment]
Consolidating discussion in #1747
