### ISSUE TITLE
"Not allowed to create this Comment" on Talk

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1052]
Just got this error message on [a post on Zoo Talk](https://www.zooniverse.org/#/talk/18/549):

![screen shot 2015-07-13 at 17 40 14](https://cloud.githubusercontent.com/assets/2357126/8655045/7635601c-2986-11e5-9f60-024d601dfab2.jpg)

I'd just loaded the thread so it shouldn't have been a timeout, and I reloaded the page, pasted the exact same text, submitted, and it all went fine. Not sure what happened but I thought I should flag it.

**Comment by DarrenMcRoy** [comment]
That's oddly unspecific. @aweiksnar -- any idea what could have happened? Not to pull attention away from the sprint, but in case it's something obvious... ?

**Comment by mschwamb** [comment]
I got that as well - if I tried to subject it again it wouldn't work. I reloaded the page and it worked fine. I had posted in a previous thread right before it. It was a note thread, but it looks like @vrooje's was. 

![screen shot 2015-07-25 at 3 30 52 pm](https://cloud.githubusercontent.com/assets/753325/8888502/96674d5e-32e2-11e5-8ae8-6dad57f2b213.png)

**Comment by aweiksnar** [comment]
It seems like this has been sorted? Error-handling should at least now deliver more descriptive messages here

**Comment by mschwamb** [comment]
Thanks @aweiksnar for looking into it. I haven't seen this error message again.  It might be the same thing as the tokens issues #1318 . I'll reopen if it pops up again.

**Comment by mschwamb** [comment]
Whoops - had thought i had created this issue. @vrooje did. So I'll let her close this. Sorry about that.

**Comment by vrooje** [comment]
Alas, I have just gotten this again, on [Zooniverse Talk](https://www.zooniverse.org/#/talk/18/115?scrollToLastComment=true&page=2)...

![screen shot 2015-08-20 at 17 17 42](https://cloud.githubusercontent.com/assets/2357126/9388785/8db2299a-475f-11e5-938f-450ab812c9b1.jpg)

**Comment by parrish** [comment]
Just wanted to double check if this is still an issue?

**Comment by vrooje** [comment]
Not for a while... let's try closing it again and seeing what happens...

**Comment by DarrenMcRoy** [comment]
Oof, unfortunately, I have to reopen this.

Just hit this.

![screen shot 2015-09-21 at 11 08 18 am](https://cloud.githubusercontent.com/assets/8987864/9997256/d0335190-6050-11e5-9c01-b4005bd4c27d.png)

Here's the console log:

![screen shot 2015-09-21 at 11 09 14 am](https://cloud.githubusercontent.com/assets/8987864/9997288/ef4e5fac-6050-11e5-8666-48d59732aa5c.png)

Is that helpful?

**Comment by DarrenMcRoy** [comment]
OH wait. I think I know what happened. I logged out briefly in another tab.

Maybe that error message could be updated to say that the person may be logged out?

**Comment by parrish** [comment]
Can't unfortunately.  Logging out invalidates the authentication token.  That's the same as having invalid credentials so we really can't tell the difference.

**Comment by DarrenMcRoy** [comment]
Can we at least message it better? I mean, that's not even grammatically correct.

How about:

"Sorry, you don't have posting rights here. You may not be logged in, or you may not have the permissions to post in this space. Please check your login and/or leave your comment elsewhere on Talk."

**Comment by parrish** [comment]
Right now the site is giving back the message from the API.  I imagine site-wide error messaging would be on the to-do list.

**Comment by vrooje** [comment]
Just got this myself and I hadn't logged out and back in or changed accounts in other tabs etc.

**Comment by DarrenMcRoy** [comment]
This should probably be reopened -- just had a chat with @aweiksnar after finding it myself.

**Comment by parrish** [comment]
On the odd time that I've seen this happen, the talk-client was sending a different bearer token than the api-client.  Maybe it should just use the token from that client?

**Comment by aweiksnar** [comment]
A very likely fix for this has been deployed, please update here if problems continue

**Comment by DarrenMcRoy** [comment]
Will close it and reopen it if anything happens. Good work Alex!

**Comment by yshish** [comment]
I have just experienced the *not allowed to create this Comment* on the Whales Talk :(

**Comment by yshish** [comment]
And again..

![bc](https://lh3.googleusercontent.com/-zR06kgKlkrY/VoQKUQHGSgI/AAAAAAAAIrU/17XITU2QCRA/s912-Ic42/ysh_2015-12-30_17-27-33.jpg)

**Comment by yshish** [comment]
I got it again, while trying to post a comment on Western Shield.

![screenshot](https://lh3.googleusercontent.com/-y0Sts4V0ccw/VxODZAOwY1I/AAAAAAAAI1A/fjTw6k1Vf80eQCXT20HyNuLHOAGNvFxJgCCo/s800-Ic42/Screenshot_2016-04-17_14-32-29.png)

**Comment by yshish** [comment]
I've just experienced the *Not allowed to created this comment* error again, while trying to submit a personal message. 

Screenshot:
![](https://lh3.googleusercontent.com/-QiIR2JKNRgI/VyjxexDQB4I/AAAAAAAAI4U/GCvxz9ipPYwaqqaWsMTZvR30TGFBxCL8gCCo/s912/ysh_2016-05-03_19-50-43.png)

**Comment by parrish** [comment]
Just an update on this issue.  I've added some extra logging to try to track this down.

Hoping to make some progress here shortly.

**Comment by parrish** [comment]
I'm pretty sure we resolved this with zooniverse/panoptes-javascript-client#45.  Happy to revisit if it reappears again.
