### ISSUE TITLE
Panoptes - allow a user to temporarily 'hide' lines / objects they have drawn on a image.

### ISSUE THREAD

**Issue by Capella05** [zooniverse/Panoptes-Front-End#1053]
As a future improvement would it be possible to add an additional button that allows a user to toggle between the original image they have been given to classify, and their input?

When classifying on 'GZ: Bars' I am finding it very difficult to determine if the lines I have drawn are accurate to the galactic bar itself, as my input is masking the feature itself. I have found myself deleting the lines I have drawn just to get a second look!

Functionality wise, it would not be too dissimilar to the invert toggle button.

**Comment by vrooje** [comment]
This is related to/similar to #204 and #648 - clearly it's a feature that everyone will find really useful!

The other reason to add this feature is that when marks are very close together it's sometimes impossible to mark where you need to if there's another mark adjacent. Workarounds include drawing elsewhere and then moving the new mark, but that's pretty awkward and it would be better to just hide the other marks and draw the new one in a blank space.

**Comment by chrissnyder** [comment]
:+1: On the radar.

**Comment by vrooje** [comment]
Bumping this - this is going to be a big problem for the disaster relief stuff, exemplified by this image:
![screen shot 2016-03-12 at 5 01 59 pm](https://cloud.githubusercontent.com/assets/2357126/13726272/ddeff2aa-e874-11e5-8958-edf696bc84a3.jpg)

If I've already marked e.g. structural damage with a rectangle I can't add a different marking inside the rectangle without drawing it outside first and then dragging it in. The only action possible within a previously-drawn shape is to select that shape, even if I have a different marking tool selected. That's a huge limit on how people can classify.

We are supposed to release this project imminently and I know this is going to be a big obstacle. How can we coordinate to come up with a solution here? Is anyone actively working on this?

Tagging @saschaishikawa @itsravenous @brian-c @chrislintott @aliburchard @mrniaboc ... others?

**Comment by aliburchard** [comment]
Yes, this is definitely an obstacle, and I'd love to see it fixed. I'm not sure how hard it is to fix, but it certainly comes up in projects trying to mark things that are close together.

**Comment by chowjunfat** [comment]
Ditto to Capella05 on Galaxy Zoo Bars.

I find the handles on the measuring bars really get in the way of making accurate observations. Once one has placed both measuring bars one is unable to see the result as it is obscured by the handles on the ends of the bars and by the X handle at the centre of the bar. The lines one has actually placed only become visible after hitting done, at which point it is impossible to do anything about the measurements. You could just preserve the handles function but remove their graphic cue, anyone using the software for 5 minutes would not need the handles anyway as the interface is really intuitive. This would give a more rewarding experience for classifiers and make the process faster and more accurate. You needn't even do away with them all together just stick in a button "obscure handles".

**Comment by trouille** [comment]
@vrooje How did the use of 'hide previous marks' do in the Ecuador PRN? We're wondering whether to use it in oldWeather-OCR and what the feedback from volunteers is on UX? 

Can this issue be closed because 'hide previous marks exists'? Or is there a different functionality requested here that I'm missing?

**Comment by vrooje** [comment]
I think the new feature definitely closes this, so I'll do that -- but I'm not sure it's exactly the same as the issue @chowjunfat raises above. As far as I understand it that's about making *only* the lines visible while actively editing the mark (not while it's just selected, but while the mouse is down on it). I think that would be useful too and perhaps it should be broken out into a separate issue.

**Comment by vrooje** [comment]
Oh! hah, sorry @trouille, forgot to actually answer your question! I didn't actually hear any direct feedback on the feature while running PRN, but maybe that's a good thing as it perhaps means nobody had problems with it. We didn't have time to set up Geordi to track usage of it though, so I'm afraid I don't have a lot of data here.
