### ISSUE TITLE
Display name can't be added at registration

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1054]
Shouldn't users be able to (optionally) set their display name at registration?! 
I asked my team to create Zooniverse accounts, was confused when only their usernames showed up in my project. Now I have to ask them to go back and sign-in and then click 'settings' and then enter a name in 'display name'. Too many clicks.

**Comment by AdrianEvans** [comment]
Why not just have the credited name be the same as the display name?

Not looking forward to trying to get the gang to log in and do this

**Comment by chrissnyder** [comment]
This is a fair question. Display name used to be the current "login" field, and so credited name was the place for a real name that could be used in publications, etc.

@camallen @edpaget Is this credited_name used for anything anymore, and if not, can it be removed?

**Comment by camallen** [comment]
My understanding was display_name is what shows up as per @mkosmala's comment [here](https://github.com/zooniverse/Panoptes-Front-End/issues/1054#issue-94848877) whereas credited name is what will be used when crediting work in acknowledgements / papers, so you can put your academic / full title name combination in there.

**Comment by edpaget** [comment]
Yeah people may not want their 'Real Name' displayed on the site, but still want it used to credit them in published papers, so those two fields will be kept separate always. I don't want to reveal users' identities without their knowledge. 

I think we have the credited name appear as part of the registration form to reinforce the idea to new volunteers that they are participating in 'Real Science' and that the results of volunteering will appear in scientific publications. 

We don't have display_name on the form to reduce the number of fields people have to fill out to sign up. Most people probably won't bother to set a name separate from their login name, people working on projects are probably a special case.

**Comment by mkosmala** [comment]
I think the reasoning here make good sense. However, my use case (and likely others) involves non-technically-sophisticated and overly busy collaborators, who I want to have proper display names for the project. But asking them to make a login and then do a bunch of additional steps to create a display name, too, is a non-starter. (To give you an idea, one of my collaborators is overwhelmed by the idea of just registering. -sigh-)

**Comment by edpaget** [comment]
Super sorry, but I think we need to optimize for volunteers registering rather than project collaborators since they will undoubtedly outnumber people creating projects by a huge factor. 

In the future, we'll hook into Google+ and Facebook logins (among others), so those details could be automatically imported from those platforms. 

I'm going to close this, but other people feel free to reopen if you think there's a compelling case for adding another field to the registration form.

**Comment by AdrianEvans** [comment]
How about having it setup so that when a owner adds, team members it shoots them an email linking to a form where it is made clear that it would be useful for them to edit their Setup?
