### ISSUE TITLE
GZ Bars: Talk - unable to search for hashtags that include certain special characters

### ISSUE THREAD

**Issue by Capella05** [zooniverse/Panoptes-Front-End#1055]
One of the hashtags we are using on GZ Bars: Talk is #no_bar. If I try to view this collection, I get the following error:

![image](https://cloud.githubusercontent.com/assets/5954184/8671208/236fd016-2a1b-11e5-9248-ade869c0287f.png)

This only appears to be happening with this particular hashtag - I can search for #no-bars with no errors.

To recreate:

- Click on the #no_bar hashtag on the right hand side on the GZ Bars: Talk [homepage](https://www.zooniverse.org/#/projects/vrooje/galaxy-zoo-bar-lengths/talk)
- Error occurs immediately
- Chrome Version 43.0.2357.132 m, Windows 8. I have not tried recreating it in a different browser, or with additional special characters.

**Comment by aweiksnar** [comment]
Looks like this is all set now!
