### ISSUE TITLE
Personal stats should be accessible directly from drop-down menu

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1056]
People love their classification ribbon but it currently takes a mouseover, click, click, then a wait to get to it. It would be good to eliminate a click and I think a "My Stats" option in the profile/settings menu would get a lot of use.

**Comment by Capella05** [comment]
@vrooje  - I loved the idea you had on GZ:bars where it was displayed under a users avatar. Easy access and just one click to expand it 

I have found a lot of new classifiers / volunteers expecting some form of 'certificate of participation' when taking part. It is very common amongst online MOOC's - perhaps this could be the Zooniverse version?

**Comment by chrissnyder** [comment]
I 100% agree with the sentiment, but disagree with the solution.

At the moment, the profile page is not very useful, just a list of the most recent comment you've made, then links to other useful in the various tabs. The profile is due for a complete reorganization pretty soon that will increase visibility of your stats, amongst other things.

Seeing as how this issue might not be specifically addressed as specified, closing.

**Comment by vrooje** [comment]
Just a note for a future discussion that I had another avid classifier, whom I met offline, bring up the "certificate" idea independently very recently, and he expressed a similar sentiment to @Capella05 that just printing out the ribbon & stats page might fill that need without having to officially be a certificate.
