### ISSUE TITLE
Export Talk data on request

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1057]
In addition to exporting subject and classification data, we should also be able to download Talk data for our projects. @VVH has also pointed out that exporting Talk data would be particularly handy for humanities projects.

**Comment by camallen** [comment]
@vrooje you probably want to raise for discussion on the [talk api repo](https://github.com/zooniverse/Talk-Api).

**Comment by vrooje** [comment]
Right, of course, thanks -- zooniverse/Talk-Api#47

**Comment by parrish** [comment]
(closing to move the discussion to the other issue)
