### ISSUE TITLE
Favorites not working from Talk

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1058]
This apparently isn't broken for everyone, but it isn't working for me -- I don't seem to be able to favorite subjects from Talk. I tried this subject:

![screen shot 2015-07-14 at 16 04 13](https://cloud.githubusercontent.com/assets/2357126/8676632/971a6946-2a42-11e5-8971-93a5f6fd7e27.jpg)

And although I clearly clicked the button, the heart icon never changed, and that subject isn't in my favorites collection when I check it later. This has happened with several subjects now.

**Comment by mschwamb** [comment]
I wonder if it is because you've got multiple images in the subject. Can you favorite a subject from Planet Four Terrains Talk ?

**Comment by vrooje** [comment]
Nope, that doesn't work either. Here's my console (the last 2 messages are the ones that pop up when I try to favorite):

![screen shot 2015-07-15 at 16 09 12](https://cloud.githubusercontent.com/assets/2357126/8701821/039fb1a6-2b0c-11e5-9786-233ea1b6bab3.jpg)

**Comment by aweiksnar** [comment]
@vrooje I believe this may have been an issue for collections that were created more than ~3 weeks ago when the favorites flag was added to the api. It should be fixed now - I just did some testing and was able to favorite a GZ bars subject.

Would you be able to try favoriting a subject again to confirm?

**Comment by yshish** [comment]
It doesn't work for me either (Whales)

When I click on the button, it starts loading but nothing happens. The heart doesn't change its colour to red and the image doesn't appear in my collection

![](https://lh3.googleusercontent.com/-a91sWTESX6I/VbFyQEAxH0I/AAAAAAAAINE/O74z9_ulKTQ/s800-Ic42/ysh_2015-07-24.jpg)

**Comment by vrooje** [comment]
Ah, the favorite and collect buttons are back and the collect button seems to be working well, but I'm getting the same error as @yshish when I try to favorite.

**Comment by mschwamb** [comment]
The heart doesn't change color for my either anymore. Can't tell if it's in my favorites since the pagination isn't working for me

**Comment by mschwamb** [comment]
Also looks like favoriting isn't working from the classification interface as well anymore. At least in the collection I expected it go to into nothing new is added

**Comment by mschwamb** [comment]
Though only for Planet Four: Terrains working elsewhere. I opened a separate ticket since it might not be the same thing #1356

**Comment by aweiksnar** [comment]
I believe this was addressed in #1356. Working for me now, everyone else?

**Comment by vrooje** [comment]
Works for me now as well. I'm going to close this - please re-open if you see this issue pop up again!
