### ISSUE TITLE
"Volunteers can choose which workflow they work on" check box is broken

### ISSUE THREAD

**Issue by frankvitaleiv** [zooniverse/Panoptes-Front-End#1060]
When you check the "Volunteers can choose which workflow they work on" box and then navigate to another aspect of Panoptes, the box resets and volunteers are not given an option of what workflow to work on when they click directly on the "Classify" tab.  Instead, users are randomly assigned a different workflow for each subject they see.  Refreshing the Project Builder edit screen, or going directly from the Project Details page to the project itself, does not resolve the issue.

**Comment by aliburchard** [comment]
Looks like this is a recurrence of #771? Which may or may not relate to back-end issue https://github.com/zooniverse/Panoptes/issues/1017

**Comment by camallen** [comment]
For reference it seems the state checkbox button isn't updating based on the returned configuration button which looks like it's working ok and coming back form the server ok.
