### ISSUE TITLE
Media uploader box still displays the previously uploaded image after upload is complete

### ISSUE THREAD

**Issue by frankvitaleiv** [zooniverse/Panoptes-Front-End#1061]
After uploading an image to Media the preview of the image still displays in the grey upload area.  The area will still upload new images, and then display the most recently uploaded image.  It might be helpful to have it revert back to normal after each upload, as a sort of confirmation.

![capture](https://cloud.githubusercontent.com/assets/13336025/8678964/ac0be386-2a4f-11e5-8636-56afeebc6935.JPG)

**Comment by vrooje** [comment]
+1

**Comment by mkosmala** [comment]
+2

**Comment by aliburchard** [comment]
+1

**Comment by chrissnyder** [comment]
Looks to be an out-of-date issue? Can someone confirm that I'm not missing something here?

**Comment by eatyourgreens** [comment]
I think @rogerhutchings fixed this.
