### ISSUE TITLE
Request: Ability to delete, rename, and add text tabs

### ISSUE THREAD

**Issue by frankvitaleiv** [zooniverse/Panoptes-Front-End#1062]
The FAQ, Results, and Education tabs that display to users are all pages to display Markdown text.  The ability to delete, add, and rename these tabs might be helpful for some projects, so that they do not have to find a work-around to add more text (such as the Planet Four: Terrains Spotter's Guide, http://terrains-guide.planetfour.org/)

Renaming might also resolve #352

**Comment by mschwamb** [comment]
Yes, the Spotter's guide for Terrains is a work around since we were one of the projects planning to launch with the new system -adding space/ability for a spotter's guide is in as issue #269

**Comment by mkosmala** [comment]
+1

**Comment by chrissnyder** [comment]
Definitely on our radar.
