### ISSUE TITLE
Panoptes Talk - no auto logoff

### ISSUE THREAD

**Issue by Capella05** [zooniverse/Panoptes-Front-End#1063]
On the previous versions of the GZ Forum / Talk, users would be logged* off when not active for 'x' amount of time.

Does not seem to be happening any-more - as much as I would *love* to see people classifying and chatting about bars for over 24hrs in a single stretch - I think it is unlikely. 

Sorry if this is a duplicate issue.

* viewed as inactive

**Comment by JeanTate** [comment]
ZT has logged me off, automatically, many times in the past few days. I do not know if this is by design or because of 're-boots'. In any case, I very much prefer the option of 'stay permanently logged on', as is the case (at least in RGZ Talk) ...

**Comment by Capella05** [comment]
That would mean you ended your session (eg. closed your browser) - some people don't. I am now looking at a user that has been logged on to GZ Bars: Talk  - for over 36 hrs - without posting.

I have no problem with being permanently 'logged on' - but if I have no active sessions - I would hope I was displayed as being off line.

**Comment by edpaget** [comment]
@Capella05 do you mean users are showing up as active on the sidebar?

**Comment by Capella05** [comment]
Yes - this particular user has been logged on as active for over 36 hrs.

**Comment by edpaget** [comment]
Yeah that's what it is. We're using a persistent connection to the notification server to determine if a user is 'active' on site. I've moved this issue over to corresponding piece of software

**Comment by Capella05** [comment]
Cheers - thanks for looking into it!

**Comment by parrish** [comment]
Also, for what it's worth, if a user remains connected (even if they're not actively classifying), they'll stay active in that list.  Users that haven't responded to the connection within 30 seconds are no longer active.
