### ISSUE TITLE
Zooniverse.org and all projects loading blank in iOS

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1069]
Just tried to load https://www.zooniverse.org/#/projects/vrooje/galaxy-zoo-bar-lengths/talk/subjects/465079 in Safari for iOS and it came up blank. Tried backing out to just the talk link, just the project link, and then just Zooniverse.org, in Safari and Chrome. All loaded blank. Is this just me? I sort of feel like we'd have noticed this before. I've tried it on my phone and tablet. My phone is still running iOS 7, but my iPad is on iOS 8.

In chrome the "https" came up in gold and crossed out. Could this be related to the security certificate issue?

**Comment by JeanTate** [comment]
Not just you (I think); I cannot get any of these pages on my iPad either (though Z blog and Daily Z load OK, but they're based on WP) ...

**Comment by mschwamb** [comment]
If it helps I checked the preview site at end of May/early June and it did work on my ipad isO8, but do get the same thing everyone else is seeing now.

**Comment by camallen** [comment]
Looks like this is a wider problem on safari generally I got this on my mac: 10.10.4 using safari: Version 8.0.7 (10600.7.12)
![screen shot 2015-07-15 at 10 16 06](https://cloud.githubusercontent.com/assets/295329/8695047/c572e05a-2ada-11e5-811f-15517f027c5d.png)

pinging @brian-c

**Comment by edpaget** [comment]
Fixed by #1076
