### ISSUE TITLE
I want to be a 'scientist', too!

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1074]
I'm a project 'owner', and I assume that this gives me the powers of all the other roles: 'collaborator', 'scientist', 'moderator', etc. 

But: I want to be labeled 'scientist' instead of (or in addition to) 'owner' on Talk. 

And: I'm not sure all 'owner's should be all things by default. I can imagine someone setting up a citizen science project (as a contractor, perhaps) for a group of researchers, but not being a 'scientist' with that group. Or not wanting to be a 'moderator'. 

I think the solution is to allow each team member to be 'owner' OR 'collaborator', and then also be (or not be) each of the other roles.

**Comment by mschwamb** [comment]
I thought this was already the case. I'm owner on my project and I have the scientist label, but also have the moderator capabilities. 

See [here](https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/10/8?page=1&comment=1196)

That's not the case for your project?

**Comment by mkosmala** [comment]
@mschwamb Huh, interesting. So, as my project isn't live yet, I can't see what I'll be labeled as in Talk. I had assumed I'd just be labeled 'owner', since that's what's on my 'research' tab. Looking at the Terrains 'research' tab, I see you're both 'owner' and 'researcher'. How did you get the 'researcher' label? I don't have any options (that I'm aware of) for adding that to myself.
See: https://www.zooniverse.org/#/projects/kosmala/season-spotter-questions/research

**Comment by camallen** [comment]
@mkosmala you need to setup a notes board using the talk moderator controls, https://www.zooniverse.org/#/projects/kosmala/season-spotter-questions/talk

**Comment by mschwamb** [comment]
By default owner is everything is my understanding so your project should list you as everything internally. You should be able to create Talk even if you're still in beta and/or private is my guess. I've tried when the site was public but not live and was able to create a Talk

**Comment by mschwamb** [comment]
Though I'm using the project builder, not sure if it's different if you're using the api directly.

**Comment by mschwamb** [comment]
Actually, I think it might from @chrissnyder's updates to how that info is presented. Because in my new private projects I'm just listed as owner as well. But Terrains was made before that. If I had those projects public, I'd want to be listed as scientist/research too.

**Comment by DarrenMcRoy** [comment]
@mkosmala -- please contact me if you have any difficulties setting up the boards!

I believe that by default, project owners appear as researchers.

**Comment by mkosmala** [comment]
@camallen @DarrenMcRoy I don't appear to have moderator controls. 

Sorry guys, it looks like all these issues are due to me setting up my project via the API instead of the project builder. (My toy projects I built in the project builder are all fine.)

@camallen @edpaget : I seem to keep running into these sorts of problems with my API-built projects. Maybe if you guys can port the Season Spotter beta over to production from demo, it would solve a lot of problems (including https://github.com/zooniverse/Panoptes/issues/1100). Is this possible to do quickly? (I need to work on it today.)

**Comment by camallen** [comment]
@mkosmala I don't think that will fix the issue in https://github.com/zooniverse/Panoptes/issues/1100. Add me a s collborator and i'll have a look and port it if need be.

**Comment by aweiksnar** [comment]
Ah my mistake - I read this issue as wanting the title 'scientist' in your avatar

**Comment by mschwamb** [comment]
I think this is something with new projects ?

On Terrains:

![screen shot 2015-07-15 at 10 37 15 pm](https://cloud.githubusercontent.com/assets/753325/8701056/443d0e4e-2b42-11e5-9021-8abd24980379.png)

On the private boulder project for my student

![screen shot 2015-07-15 at 10 37 38 pm](https://cloud.githubusercontent.com/assets/753325/8701066/4f0d5608-2b42-11e5-912a-ac8885742b8b.png)

I only show up as owner on the private boulder one on the science page

**Comment by mschwamb** [comment]
I have the same request for a new project that I'm working on with collaborators. It just says owner under my name. It would be really nice if it identified the owner as also part of the research team and say scientist as well

**Comment by chrissnyder** [comment]
I've read this issue a couple times and I can't quite figure out what the issue is.

- For the owner to not have other roles (re: contractor, agency, etc), I think that's a use case that's pretty far in our future. Don't think we should worry about that now.
- Is it just having a decision of what label you are tagged as throughout the project? This feels like a where we aren't going to be able to please everyone without some unnecessarily complicated solution.
- Should be just list off every role you have on the team page/Talk?

**Comment by mkosmala** [comment]
@chrissnyder: I think there are 2 issues. How people are labeled in Talk. And how they're labeled on the "research" tab / team page.

I originally opened the issue for how I was labeled on Talk. But that issue is solved, I think. I am currently labeled as "researcher" in Talk, which is what I wanted (rather than "owner"). 

However, it would be nice to be listed as more than just "owner" on the "research" tab -- my preference would be "owner, researcher, moderator". 
![team](https://cloud.githubusercontent.com/assets/1066340/10472628/86093466-71f0-11e5-88e6-23e5b2db27a6.png)
So yes, I think every roll should be listed on the "research" tab (where space is not at a premium). 

I don't know what logic is currently being used to label people in Talk. It seems there is just one label per person (which I think is good), so is there a hierarchy? zooniverse_team > researcher > moderator -- or something similar? This works fine for my project. For some projects, maybe it makes sense for people to designate a "primary role" for each team member. For example, I am a "moderator," but I'm primarily a "researcher". I wouldn't worry about doing this, though, if it's not an issue for anyone.

**Comment by mschwamb** [comment]
I have a very similar sentiment to  @mkosmala . Mainly I don't want people to not think I'm part of the research/science team because I don't have the researcher tag on the research page. 

I'm fine with Talk's current hierarchy and the volunteers get because of the researcher label I get the research team, but it's mainly for other people including scientists in my field to know I'm involved in the project in a science capacity and not just consulting or something else. I'm not sure it's clear what an owner is especially when other people will have researcher and moderator listed. 

I get your point @chrissnyder about how to please everyone, if there was a team page where I could fill out in more detail then I'd be fine leaving it as owner, because i could be listed on the research team section of the team page.

**Comment by aliburchard** [comment]
I agree with listing all the rolls on the 'research' tab.
