### ISSUE TITLE
linux firefox reporting y values as ints for drawing tools but x is a float

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1077]
I think this would be a front end issue, My summer student is using project 264 to mark boulders in some original planet four images. I noticed in a few of her classifications, but not all that the y positions become strangely ints. I could see that happening for one or two markings but more than 4 in the same subject seems a bit suspicious, so I looked. It seems to be when she classified in linux she got ints for y but when in windows everything was fine and all float. I classified with mac firefox and I floats for both x and y position

Looks like it's a firefox linux verus windows

when she classified with Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0",

{"task":"T0","value":[{"x":141.39999389648438,"y":500,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":296.3999938964844,"y":640,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":310.3999938964844,"y":631,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":353.3999938964844,"y":572,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":374.3999938964844,"y":573,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":395.3999938964844,"y":500,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":426.3999938964844,"y":498,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":409.3999938964844,"y":359,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":353.3999938964844,"y":137,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":326.3999938964844,"y":113,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":224.39999389648438,"y":219,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":189.39999389648438,"y":185,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":199.39999389648438,"y":169,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":200.39999389648438,"y":181,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":170.39999389648438,"y":191,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":258.3999938964844,"y":193,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":212.39999389648438,"y":267,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"}],"task_label":"Mark the boulders you see in the image"}]

But then other classifications are okay with "user_agent":"Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"

 [{"task":"T0","value":[{"x":376.4844825471618,"y":7.116082797394854,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":222.13144466686373,"y":20.808853924110828,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":228.35535748461783,"y":25.78804342473483,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":223.37622723041451,"y":59.39757255394676,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":161.137099052875,"y":70.60074893035075,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":279.3914425902001,"y":80.55912793159872,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":279.3914425902001,"y":27.032840799890817,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":398.89056869107606,"y":89.2727095576907,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":430.0101327798458,"y":106.69987280987468,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":351.588831276146,"y":89.2727095576907,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":377.7292651107124,"y":94.25189905831473,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":666.5188198544961,"y":558.5613199915019,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":510.9209994106472,"y":211.2628523229785,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"},{"x":97.65318831178463,"y":173.91893106829855,"tool":0,"frame":0,"details":[],"tool_label":"Boulder"}],"task_label":"Mark the boulders you see in the image"}]

**Comment by mschwamb** [comment]
Should note, the tool is the point tool

**Comment by edpaget** [comment]
I am unable to duplicate this on Debian 8 or on Ubuntu 14.04. What specific Linux distribution is she using?

**Comment by brian-c** [comment]
Are the numbers wrong? JSON doesn't have ints, just floats. If they're coming through as integer values, the subject is probably just scaled so that that's how the math happens to work out.

**Comment by mschwamb** [comment]
scientific linux older distribution - I can get the exact distribution later today. I don't know if the values are correct I need to write a plotting code, which will take me a day to get to. I'll get you the browser and linux version today.

**Comment by edpaget** [comment]
Closing as I am still unable to duplicate.
