### ISSUE TITLE
Accessing refs from PromiseRenderer

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#108]
Placing forms inside a PromiseRenderer would be a common use case for me, but I like to place ref attributes on things and then grab their dom node values on submit.

Is this something you have run into as well?

**Comment by brian-c** [comment]
The handler of a PromiseRenderer is a function that is called outside the parent component's render. `@getDOMNode().querySelector` still works, but if you really needs refs you've gotta go the super long way and build a whole sub component.

There's a function at handle-input-change.coffee that might be useful to you. Bind it to a resource and set that as the `onChange` handler of an input and it'll figure out how to update the resource when the input changes based on its `name` and `type` attributes. Then you can just `.save` the resource on form submit.

**Comment by aweiksnar** [comment]
Ah okay cool. handle-input-change or JS selectors should do the job. I was using PromiseToSetState for this, but PromiseRenderer seems to do enough extra work to make it worth working around ref usage
