### ISSUE TITLE
Request: command-line subject uploader

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1086]
I know enhancements to uploading subjects is in future plans right now, but just wanted to formally request a command-line subject uploader (for unix-based systems). My subjects are all on a remote machine -- perhaps not an uncommon situation (Snapshot Serengeti was also this way) -- so I can't use the project builder. Writing my own for now...

**Comment by chrissnyder** [comment]
We've got the nascent beginnings of one at https://github.com/zooniverse/panoptes-subject-uploader. Regardless, development of any CLI won't happen in this repo.
