### ISSUE TITLE
External link not saving (help!)

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1088]
I enter an external link:

![projbuild](https://cloud.githubusercontent.com/assets/1066340/8706351/56d8d000-2afd-11e5-8f30-020a81f35b09.png)

But it doesn't show up on the project:

![projview](https://cloud.githubusercontent.com/assets/1066340/8706354/5a40e688-2afd-11e5-98a7-22c82277e198.png)

Question: there is a pink border around the link and its title when I enter it. Does that mean something? Note that a pink border also appears around the example link, which also doesn't show up.

**Comment by vrooje** [comment]
The pink border means it didn't save correctly. I've had this a couple of times and then tried again and it turned green (which means all saved fine) -- though that was in other text boxes, not the link boxes specifically.

**Comment by mkosmala** [comment]
@vrooje Good to know what it means. But no idea why it won't save. (And I've spent *a lot* of time trying to get it to do so...)

**Comment by vrooje** [comment]
Also, might help to note that I added an external link to GZ Bars about 2 hours ago and all went smoothly, so either it's a new problem or a project/link-specific one.

**Comment by mkosmala** [comment]
Yep. I can add external links in other projects. It's a flaky issue.

**Comment by edpaget** [comment]
@mkosmala this should be fixed now. It was a a result of a database inconsistency due to changing the language settings. I'm going to make fixing those a goal my next sprint.

**Comment by mkosmala** [comment]
Thanks!

**Comment by mkosmala** [comment]
@edpaget Fixed in that project. But not fixed in its sister project "Season Spotter Image Marking". I'm still getting the pink did-not-save problem in that one.

**Comment by edpaget** [comment]
Should be fixed now.

**Comment by mkosmala** [comment]
Yep, thanks!
