### ISSUE TITLE
Help box doesn't clear for tasks without help text

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1090]
In a workflow, I have multiple tasks. If I click on Task A, which has help text, that help text shows up in the help text box. If I then click on Task B, which does not have help text, the help text for Task A remains in the help text box.

**Comment by edpaget** [comment]
Is this in the editor?

**Comment by mkosmala** [comment]
Sorry, yes. This happens in the project builder.

**Comment by edpaget** [comment]
Is it still happening for you? I'm so far unable to duplicate.

**Comment by mkosmala** [comment]
Yes. Try project 18 (Season Spotter BASIC Beta1). I just added you as collaborator. 
Go to workflow 1-4_SimpleSingleCrops. Click task "Is there snow?" You'll see the help text in the help box. Now click task "How sure are you that the crop is grass or hay?" which doesn't have any help text. You'll see the snow help text still in the box.

**Comment by edpaget** [comment]
Thanks helped me duplicate it :+1:
