### ISSUE TITLE
Media uploader page: inconvenient when uploading many images

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1092]
The upload "drag-and-drop" area is at the bottom of the media uploader page, but the newly added images pop up to the top. That means I have to keep scrolling up and down. Might be better to put the most recently added image at the bottom, next to the "drag-and-drop" box, or else put the "drag-and-drop" box at the top.

**Comment by vrooje** [comment]
I like the idea of the drag-and-drop box being at the top and possibly being a bit smaller so you can see both it and the image library at the same time.

**Comment by mschwamb** [comment]
@eatyourgreens would moving the drag and drop area be just moving lines 68-85 to line 35 in https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/media-area/media-area-view.jsx ? If it's just moving lines around, I could try a pull request

**Comment by eatyourgreens** [comment]
@mschwamb I'm not sure. I think moving those lines up to line 35 might break the component, but it's hard to tell just looking at the code.
