### ISSUE TITLE
Update text on subject uploader page

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1095]
Can we add a sentence below the existing help text at the top of the uploader page that reads: "You can upload up to 10,000 subjects. We recommend uploading subjects in batches of 1,000 - 5,000 at a time."

This partially addresses #861, and should be done regardless of what happens in #316.

Related to https://github.com/zooniverse/Panoptes/issues/1120

*note that I made up that 1,000-5,000 number, and have no idea what optimum is. I think we need to put *something* there right now because this is a major source of confusion, but @camallen @brian-c @vrooje @mschwamb might have a better sense of appropriate batch size.

**Comment by camallen** [comment]
@aliburchard do you want to write this text, somwhere [around here](https://github.com/zooniverse/Panoptes-Front-End/blob/254ca4774a872b2e3079e0e171067bf8d0d90fd4/app/pages/lab/subject-set.cjsx#L130) i think maybe.

**Comment by vrooje** [comment]
Last time I was uploading subjects I was advised to keep it to 500ish at a time. I've done 1,000 before but never pushed beyond that.

**Comment by camallen** [comment]
That advice was before a fix to a backend end point to speed it up see, https://github.com/zooniverse/Panoptes-Front-End/issues/461#issuecomment-112480820. I haven't load tested it completely but i suspect it's a non-linear increase in response times. So really it comes down to what we think the client can reasonably complete. I'd agree with Ali that 1-5K is reasonable but we should probably test it more.

**Comment by aliburchard** [comment]
Sure. Having never done a pull request for a real, live project before, let me make sure I've got this down. I should clone the specific branch you pointed me to, make changes to my copy, commit the changes to my copy, and then submit a pull request to push them back to the branch, right?

**Comment by mkosmala** [comment]
I'll be uploading today and tomorrow. I'll let you know what I find out...

**Comment by chrissnyder** [comment]
Closed via #1099
