### ISSUE TITLE
Urgent: increase media uploads cap to 30

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1098]
For Season Spotter Mark Images (project 348), I need about 30 images for the help. They're small (~100KB). Our beta results indicated that we need more examples for some of the questions. 

Is this back-end or front-end? (@camallen @edpaget @brian-c)

**Comment by vrooje** [comment]
I ran out of spaces too just for the GZ Bars help images. Ended up hosting them separately, but I fully agree it would be great if that weren't necessary.

**Comment by edpaget** [comment]
It might be a bit of both.

**Comment by mkosmala** [comment]
Thanks!
