### ISSUE TITLE
Already seen label pops up when you get to the summary and can hit the Talk or Next button

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1109]
Now when I classify an image once I submit the classification the orange already seen banner shows up. I think this shouldn't happen. I found it confusing, and I think other volunteers will. I  think they make it it as the system thinking I classified it before but didn't tell them  ahead of time.

![screen shot 2015-07-17 at 9 36 32 am](https://cloud.githubusercontent.com/assets/753325/8738943/1014b23a-2c68-11e5-987e-079d2e02eae5.png)

The orange label is not there when I classify the image to start with

**Comment by aliburchard** [comment]
Yes! Wasn't sure if this was still happening, but it drives me crazy.

**Comment by frankvitaleiv** [comment]
Also occurring with Wildebeest Watch (to an unsuspecting DHOxSS volunteer)

**Comment by chrissnyder** [comment]
Agree all this shouldn't be happening. We'll be taking care of it shortly.

**Comment by vrooje** [comment]
Huh. I found this kind of reassuring, like, "yes, you're not seeing a duplicate, you just did this, move along now". But I am obviously in the minority!

I suppose the behavior I'd prefer is, if someone clicks over to Talk from a subject end-of-classification, then posts on Talk, then clicks back to Classify, they just get a new subject.

**Comment by eatyourgreens** [comment]
+1 to what @vrooje said. I find this reassuring as visual confirmation that I've submitted a classification.

**Comment by mschwamb** [comment]
I found it  kept drawing my eye away especially with the orange color.The summary page already confirms the classification was submitted, so for me it's not adding anything.

**Comment by edpaget** [comment]
Maybe it should just say 'Classified' if people want some kind of confirmation? I think it's odd that it says 'Already seen'

**Comment by chrissnyder** [comment]
I worry that we are communicating something similar like we did on Space Warps, where we are only telling you about something after-the-fact on purpose, which isn't the case at all.

Maybe it's a problem with the workflow confirmation being too subtle? It already exists, it just doesn't stand out, especially if the workflow is long. http://i.imgur.com/8hrqMRB.png

**Comment by mschwamb** [comment]
I agree with @chrissnyder . That's my original fear when I saw the tag (see at the first post in the discussion). I think the fact it says Thanks! to me acknowledges that the submission happened. I've never received feedback on the projects I've been involved in that people were concerned that their classifications weren't received or successfully submitted. No feedback during the beta test on Terrains mentioned anything like that. So I'm not sure the current confirmation with the 'Thanks...' needs to be changed. But however you all decide to go I think the orange label popping up shouldn't be the visual queue that submission was successful.

**Comment by edpaget** [comment]
Cool I'll try to get the already seen tag removed tomorrow.
