### ISSUE TITLE
Getting ReferenceError: user is not defined on Talk when trying to post after classifying in the interface as  non-logged to logged in

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1110]
Only thing different is that I classified a few images non-logged in. The interface reminded me to log in so I did and then I can't post in Talk I get this

![screen shot 2015-07-17 at 9 29 42 am](https://cloud.githubusercontent.com/assets/753325/8738781/8381fad6-2c66-11e5-8f6a-f648549f930d.png)

I'm definitely logged in, I can see I have a new message in my inbox. 

Trying logging out and back in and refreshing the page. Doesn't change the message it still wouldn't go away

**Comment by aweiksnar** [comment]
There were a bunch of user changes today, I'll have a fix in for this in soon

**Comment by mschwamb** [comment]
Just realized it's  all subject pages doesn't matter that it's coming from the classification interface

**Comment by chrissnyder** [comment]
Damn, missed one :cry:
