### ISSUE TITLE
Changing 'user' to 'participant' on Talk ?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1114]
Really really  Low in the queue,  I noticed that Panoptes Talk uses the word user and Talk 2.0 uses participant. I really like using the word 'participant' Personally I try to catch myself before using the word 'user'  since we all think of the volunteers as collaborators, so maybe participant would be good to use there as well. 
![screen shot 2015-07-17 at 11 14 39 am](https://cloud.githubusercontent.com/assets/753325/8740029/08293722-2c76-11e5-8ed5-9a036d2d922c.png)

![screen shot 2015-07-17 at 11 14 32 am](https://cloud.githubusercontent.com/assets/753325/8740033/1585fa5e-2c76-11e5-94f7-28f5a338f309.png)

**Comment by aliburchard** [comment]
+1. I find myself using "user" but feeling like it indicates a sense of hierarchy or distance. I like "participant"

**Comment by vrooje** [comment]
I like this too.

**Comment by mschwamb** [comment]
@aweiksnar I noticed it still stays user on the invidual board https://www.zooniverse.org/#/talk/13 and https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/9 - do I need to clear my cache to see that? Everywhere else I see participant. Thanks for making the change

**Comment by aweiksnar** [comment]
@mschwamb Thanks I missed that one - I'll get that in today!
