### ISSUE TITLE
Scientist Names instead of usernames on research page

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1117]
The style would look better if instead of just using the usernames of the team the api pulled the real name from the database and used that.

Also it isn't clear how these are sorted - perhaps by status, owner, collaborator etc, but perhaps with owner and then alpha by surname

**Comment by vrooje** [comment]
+1 to both of these.

**Comment by mkosmala** [comment]
@AdrianEvans The "display name" does show up on the research page. But you have to know to go and set it. Note that is different from the "credited name". I find this confusing and unintuitive, and had the same confusion as you. If you go to your "settings", you can set your "display name". 

See also issue #1054

**Comment by chrissnyder** [comment]
As noted, the page does use display name, so closing.

However, that doesn't absolve us the terrible discoverability and messaging around the credited/display name fields. We'll look into changing how that is exposed to both volunteers and scientists.
