### ISSUE TITLE
Enforce closure of polygons

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#1118]
Currently the polygon tool acts like a polyline and polygon tool at the same time. Behaviour is dependent on the closure of the line segments.

Although this adds flexibility it would be great to have polygon closure enforceable.

Currently, people can move on without closing a polygon, which might generate errors. More so as the polygon in subsequent workflows will not be rendered as a polygon but as an (open) polyline. Consequently the last vertices would not intersect with the subject, raising no alarm on part of the user.

Being able to enforce polygon closure before moving to a next task would resolve this issue.

**Comment by chrissnyder** [comment]
Ah, polygon's automatically close if you switch drawing subtasks, but looks like they don't if you move on to the next task. Definitely a bug, or at least inconsistent behavior.
