### ISSUE TITLE
FAQ text won't save for collaborator

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1119]
My collaborator cannot save text entered into the FAQ text box. It turns pink, And as soon as he navigates away from the Zooniverse site, the text is gone.

I can save text into the FAQ box, however. 

(And yes, we've tried it with me logged out to make sure there isn't some sort of conflict between people editing.)

Bug?

**Comment by AdrianEvans** [comment]
I had this in chrome yesterday. Closed all other windows logged out and back in. This fixed it.

**Comment by mkosmala** [comment]
My collaborator tried all the closing, logging out, etc. But still couldn't save.

**Comment by AdrianEvans** [comment]
Do you have the OS and browser details and I'll see if I can get a collaborator to duplicate the bug. Do they have tester or expert privilege etc could be something to do with a conflict there

**Comment by mkosmala** [comment]
Mac and Chrome. Only 'collaborator'.

**Comment by mschwamb** [comment]
Are they clicking somewhere on the page before leaving. I noticed the autosaver needs you have clicked somewhere else sometimes to activate. If he writes the text and then clicks on faq above the text box it might work.

**Comment by mkosmala** [comment]
Yep, @mschwamb, we've tried that.

**Comment by mschwamb** [comment]
One other thing, that might help to try/check. Checking everyone body is not logged in to the project builder or editing that page. If you and them are on the FAQ the project builder picks the newest person to enter as having control and so if that's not them, when they try to save the saving will fail.

**Comment by mkosmala** [comment]
Yep, we tried that, too. It's only him and me and I was logged out. Thanks for the ideas, though, @mschwamb

**Comment by camallen** [comment]
@mkosmala get him to clear his cache and reload the site. For reference there is no hierarchy of users that are chosen over other users when editing content.

**Comment by mkosmala** [comment]
This is definitely a BUG! A permissions one, perhaps. My collaborator writes:

> On my Mac, running OS X 10.9.5, I get the pink flag in Chrome 43.x, Safari 7.x, & Firefox 38.x. In my PC, running Win 7 SP1, I get the same pink flag in IE 11.x and Chrome 43.x, & Firefox 37.x. I even tried Chrome and the native browser on my Android phone — same pink flag in both cases.  I tried this in SS Questions, SS Marking, and even your “Collaborators" project.
>
> So, saving from my account fails in five browser families across three operating systems in three different projects.  Sounds like a permissions problem to me. In fact, I am able to edit pretty much any field except the FAQ.  It must be a bug.

Additionally, we have tried the reverse. He created a project and I tried to edit the FAQ. I was unable to. Pink border. Not saved.

**Comment by edpaget** [comment]
A fix for this should be deployed soonish.

**Comment by edpaget** [comment]
@mkosmala this fix should be live and I'm able to edit projects I collaborate on. Let me know if you still see the error.

**Comment by neonedu** [comment]
Looks like that did it -- I'm now able to save edits (green flag) the FAQ in question.
