### ISSUE TITLE
Link to a comment from another discussion thread doesn't work properly

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1121]
I wanted to send someone a link to a comment from another discussion thread but it doesn't work properly for me. 

When I open the link in the new tab (or copy it into my comment and then click on it), it loads the discussion but doesn't take me to the correct page and doesn't highlight the linked comment anyhow.

When I stay on the page with the linked comment and click on the link, it does appear highlighted as expected.

**Comment by mschwamb** [comment]
Duplicate - see ticket #1046
