### ISSUE TITLE
Making the name of the Talk boards have hyperlnk blue so people know they are links

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1123]
I'm not sure if there's been a graphic designer pass through Talk yet. I noticed one volunteer on P4T that couldn't figure out how to get to different boards. He/she was just writing in the introduce yourself thread. I suggested asking questions in other threads and they said they didn't know how to get there.

I looked and saw that all other links are the blue color but the Help, Research Chat, that are the links to the full board and list of conversations don't have that color. You have to mouseover to see a light blue change to know their hyperlinks. Would it be better if all the hyperlinks were changed to the lighter blue or the dark blue including the titles of the boards so it's clear for less web savvy people that you click to enter the board?

![screen shot 2015-07-18 at 9 06 25 am](https://cloud.githubusercontent.com/assets/753325/8759736/806efeca-2d2e-11e5-90f9-2d7af7690886.png)

**Comment by aweiksnar** [comment]
Closing via #1555, These now mimic github issue hover/clickable states. This page will likely be receive a design update in the near future too
