### ISSUE TITLE
Adding subject set id number and workflow id numbers  to the project builder

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1124]
The csv dumps list workflow id and subject set ids as numbers, but those numbers aren't listed anywhere in the project builder. Could they be list somewhere?  I prefer the numbers in the csv file, so I would not like to see that change, just somewhere list the numeric id number

**Comment by mschwamb** [comment]
Especially if you have to break the upload into multiple smaller chunks that you are uploaded into one subject set, to do the sanity check to that one isn't uploading a batch a second time in a subject set it would be nice to have the filename you uploaded also listed with the subject id in the project builder list.

**Comment by camallen** [comment]
Just noting you can find these numbers in address bar of the browser. Agree they could be more visible on the page itself. 

We don't store the names of the manifest anywhere server side so i don't think we'll be able to show the link you're asking for. Others may have a better idea to handle this.

**Comment by chrissnyder** [comment]
@srallen A simple label at the top of the workflow/subject set editor with the name - id of each would do the trick here.

**Comment by mschwamb** [comment]
@camallen for the filename I mean the original fileame of the subject listed inside the manifest csv and also stored (I believe it's always stored server side in the associated subject metadata). Sorry for the confusion on that.
