### ISSUE TITLE
When you log out the project builder taking you to the nicer page asking you to sign in or return to project

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1125]
low in the queue - when you log out while in the project builder you get taken to this
![screen shot 2015-07-18 at 3 25 41 pm](https://cloud.githubusercontent.com/assets/753325/8760778/cc7bb8ac-2d61-11e5-99b5-e776a403441b.png)

I think it should take you back to the same page you go to if you click the project builder linker not logged in. I think it looks more polished
 
![screen shot 2015-07-18 at 3 25 53 pm](https://cloud.githubusercontent.com/assets/753325/8760780/e591e44c-2d61-11e5-8ac2-4ff482fed435.png)

**Comment by chrissnyder** [comment]
@mschwamb's solution looks good to me.
