### ISSUE TITLE
Subject preview doesn't refresh correctly

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1127]
If I click on Subject Set X and then click (the eyeball) to preview image A, I see image A. If I then close the preview of that image by clicking the 'X' in the upper right, then immediately click on Subject Set Y, and click to preview image B, I get shown image A (and NOT image B, as expected). 

Note that if I then close this preview (by clicking upper-right 'X') and then immediately click the same eyeball button for image B, I do get shown image B. 

The wrong image only gets shown for the first preview upon switching Subject Sets.

I'm on Firefox.

**Comment by srallen** [comment]
@mkosmala, is this still an issue for you? I haven't been able to replicate it in either Chrome or Firefox.

**Comment by mkosmala** [comment]
If you can't replicate it, I'd considered it fixed. I haven't been building projects since July, and there have been many code updates since then...
