### ISSUE TITLE
if you try to add to a collection that doesn't exist there is no error 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1129]
When you try to add to a collection that doesn't exist by typing it's name in the box and hit add. the window just closes, but nothing got and added and no collection gets created. Maybe it should return back that there is no collection with that name?

**Comment by chrissnyder** [comment]
Sounds like this is the same error as https://github.com/zooniverse/Panoptes-Front-End/issues/1129

**Comment by mschwamb** [comment]
This is #1129.... was that comment meant for another ticket?

**Comment by chrissnyder** [comment]
Oops, yea, edited.

**Comment by mschwamb** [comment]
1130 is trying to add an image to a collection but using the lower part of the collection area where it says to make a new collection and that collection name actually already exists. It looks like everything worked fine, but it didn't. Does that make sense @chrissnyder ?

**Comment by chrissnyder** [comment]
I understand the difference, but I'm linking the two because I think they are both symptoms of the same problem.

**Comment by mschwamb** [comment]
gotcha. let me know in the future if I should put something like this and the other ticket in one issue.
