### ISSUE TITLE
Tried to create a collection with the same name as one I already had-  no error appeared and doesn't add image to collection

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1130]
if you try an create a collection with the name of one you have. no error is returned back. the window just closes. Also the subject is not added to the collection

**Comment by mschwamb** [comment]
Note this was in the classification interface, hitting the collect button

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829

**Comment by mschwamb** [comment]
@parrish I think this is something that should get fixed eventually if possible
