### ISSUE TITLE
Add a visible scroll bar to the username search

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1132]
Related to #1131 You can scroll in searches to see more but it's not obvious to the user see ticket  #1120 - Example looking for @chrissnyder - he's the last to come up in the search, but you have to scroll to find him. Scrolling works, but it looks from the design that are no more options. Adding a visible scroll bar would be helpful to know that there are more choices to go through 

![screen shot 2015-07-19 at 5 59 17 pm](https://cloud.githubusercontent.com/assets/753325/8765473/092459b0-2e40-11e5-988c-15f32f3f233d.png)

After scrolling 

![screen shot 2015-07-19 at 5 59 20 pm](https://cloud.githubusercontent.com/assets/753325/8765475/13af0826-2e40-11e5-810b-47c72cdd87b8.png)

**Comment by khufkens** [comment]
btw. is there any way to change the handle I use in a project to my full name instead of the abbreviation. I can't seem to change this in my profile, yet Margaret and Chris are both listed under their full name as my collaborators.

https://www.zooniverse.org/#/projects/khufkens/jungle-rhythms/research

**Comment by mschwamb** [comment]
@khufkens sign in click on your username on the top right, the dropdown menu should have profile -go to profile - first item is display name - change that to whatever you want to show on the project science page and also it's what will show on Talk (your username will bellow it on Talk)

**Comment by khufkens** [comment]
The field is unresponsive! After messing with it it's stuck at khuss now!

**Comment by edpaget** [comment]
Isn't this just a Mac thing? OS X hides scroll bars by default, and they appear on my computer.

**Comment by mschwamb** [comment]
@edpaget hadn't really noticed until you mentioned it.  if you don't 100% know the person's name then how do you know there are more search options. It caused confusion in #1120 - I guess in other webforms I've either known there's more and to scrolled or there's a indication there's more the list. Anyway to force the drop down menu scroll bar to appear for macs or make it clearer there are more search results?

**Comment by edpaget** [comment]
You can force the scroll bars to appear in your preferences: https://support.apple.com/kb/PH18803?locale=en_US

**Comment by mschwamb** [comment]
Thanks. But it does really look the search box is finished when you view it on a mac. Maybe there isn't an easy fix to make the browser show the scroll bar for those two windows on a mac.  If you don't think that's a problem or its a  won't fix item, feel free to close the ticket @edpaget

**Comment by edpaget** [comment]
So there doesn't appear to be a way to force the scroll bar to show on OS X, and I don't want to hack something that will mess up Windows/Linux users where the scroll bars do show. @heathv any ideas for how 'more content' could be communicated?

**Comment by khufkens** [comment]
maybe just list:
"Add another (scroll for more content)" or change this dynamically if applicable.
in the header?

**Comment by heathv** [comment]
Can we control the height of the drop-down? If as of now it shows 5 rows when opens, could we change it to only show 4.5 thus creating 'the cut-off effect?' [Here's an (old) article I found about it](http://www.uie.com/brainsparks/2006/08/02/utilizing-the-cut-off-look-to-encourage-users-to-scroll/)

Essentially if the text at the bottom of the search result gets cut off it subtly hints for users to scroll.

**Comment by khufkens** [comment]
like the cut-off effect, this should provide a visual clue.
