### ISSUE TITLE
Team changed science to research and now my help has a problem link that I can't fix unless I take the site down

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1134]
Woke up this morning to see all the links to the science page on Planet Four: Terrains don't work because there is no science page anymore. It's been renamed Research personally I'd rather it called About because I think Research is confusing when there is a results page. Anyway, now all links don't work because there is no science page. I have links to the science page everywhere on Planet Four: Terrains and now have to fix it on Talk and on the FAQ, Help, etc. 

I can't edit my help unless I take the site down. Can the development team fix the science link in the help so I don't have to take the site down?

**Comment by mschwamb** [comment]
The Apply for Beta button is still active  for my project, so I'm concerned about bringing the site down to make the change and not being able to get it back to be visible on my own.

**Comment by aliburchard** [comment]
You'll need to ping @camallen or @edpaget to bring the site back live after you take it down. 

You *can* however make changes to the FAQ or other pages while the project is live, just not to the workflow text/popup help text.

**Comment by mschwamb** [comment]
Thanks @aliburchard. I made the change everywhere else. I'll wait to see if @camallen and @edpaget have a moment for me to bring down the site, make the change, and get the site back up.

**Comment by camallen** [comment]
@mschwamb what links are actually broken? your site looks ok.

**Comment by mschwamb** [comment]
Thanks for the reply @camallen  Sorry for the delay. I was asleep (pesky time zone difference) - click on the help box and scroll all the way down, I have a link to a science page. That doesn't work science in some recent commit science-case was changed to research so my link there goes to a no longer existing page. 

It's located all the way at the bottom of the help box text in the interface I have 'Looking for More Examples? Want to Learn More About the Features Above?Check out our Spotter's guide, Science Page, and FAQ.'  That Science Page link if you click it doesn't work. That's what needs changing

**Comment by mschwamb** [comment]
And apparently our press release is going out today or tomorrow. @camallen if you can help today that would be fantastic. It sounds like from Ali I can make the change, by taking the site off of live, but I need you put it back visible on the Zooniverse pages

**Comment by camallen** [comment]
@mschwamb make the changes, then reset to live and let me know. I'll reset the launch status when done.

**Comment by mschwamb** [comment]
@camallen - change is made and it's back to live . can reset the launch status? Thanks

**Comment by camallen** [comment]
Done.

**Comment by camallen** [comment]
changes look good to me, closing.

**Comment by mschwamb** [comment]
Thanks very much @camallen
