### ISSUE TITLE
Error in deleting large subject set

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1135]
I'm getting an error (a red zero) when trying to delete subject sets with more than a couple thousand subjects. (Worked OK for one with 500 subjects.) 

![screenshot](https://cloud.githubusercontent.com/assets/1066340/8768656/4a683f16-2e56-11e5-803d-4f710cb359ed.png)

May be related to https://github.com/zooniverse/Panoptes/issues/1121

**Comment by mkosmala** [comment]
Actually, these subject sets did eventually delete. Maybe it's just that it takes so long that the interface times out waiting for the back-end to respond?

**Comment by camallen** [comment]
This will be fixed by zooniverse/Panoptes#1121
