### ISSUE TITLE
Why am I getting "No queue defined for user" errors?!

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1138]
@brian-c @camallen Why would I be getting "no queue defined for user" errors? I have lots of subjects in several subject sets hooked up to several workflows. I do have a few workflows with empty subject sets. Would these throw this sort of error?! I need to have some empty workflows for now.
![screenshot](https://cloud.githubusercontent.com/assets/1066340/8780617/290c2d3c-2ed8-11e5-853e-77080e5420bf.png)

**Comment by edpaget** [comment]
Yes empty workflows with empty subject sets would throw this kind of error.

**Comment by edpaget** [comment]
What are you using the empty workflows/sets for?

**Comment by mkosmala** [comment]
Placeholders. Since we can't change workflows while live, but can add subjects later, I'm going to have some empty subject sets (and workflows) in the meantime, while I only add some of our subjects at a time. (See https://github.com/zooniverse/Panoptes/issues/1147) 

What's the best immediate solution? (We launch tomorrow!) 

Also, what's going to happen when some workflows/subject sets are completely retired and others aren't? Is that also going to throw this error?

**Comment by mkosmala** [comment]
Also tagging @aliburchard so she's aware of this wrt giving advice to science teams on subsetting data.

**Comment by edpaget** [comment]
You can just create a subject set but not connect it to a workflow.

**Comment by edpaget** [comment]
You can also ask us to make a project not live to make changes. It'll just briefly disappear from the front page, but we'll then reenable it as soon as you're finished changes.

**Comment by camallen** [comment]
@mkosmala I assume this is because you won't be around to update the project? If so then as a workaround just put some subjects into the empty subject_sets. 

Re finished subject_sets : workflows, we return data but mark it as finished for the workflow or already seen for the user. Panoptes will always return a subject when you request one (unless there are none like what you are seeing).

**Comment by mkosmala** [comment]
@camallen Mainly, I just don't want to "unlive" it. But sounds like the way to go here is to unhook empty subject sets from workflows. Am I right, @edpaget, that that will prevent the error? I'll have workflows with no subject sets, but any workflow that does have a subject set will also have subjects.

**Comment by edpaget** [comment]
You'll also need to delete the workflows without subject sets. (though maybe this makes an argument for a feature to set workflows as active for a project @camallen ?)

There are really no consequences to making a project not 'live' (at least for now while we're working directly with project authors like you) except that classifications won't count towards retirement for the period of time it's not-live.

**Comment by mkosmala** [comment]
Hmm... I definitely don't want to delete workflows. (They take too long to build.) 
My only other choice is to add a subject? Yuck. 

So I'll add 1 subject to each workflow I want to be empty and set retirement count to 1. Any way I can retire them before the project goes live? (Can we make it live and then I can retire them and then go unlive?)

**Comment by mkosmala** [comment]
Related question: if I have a workflow that has two subject sets, and one of the subject sets has subjects, but the other is empty, will the error be thrown?

**Comment by edpaget** [comment]
No it shouldn't throw an error in that case.

**Comment by mkosmala** [comment]
Okay, I've got a plan now. Thanks.

**Comment by aliburchard** [comment]
huh, @mkosmala I'm not totally sure I follow your plan for this. We still recommend splitting subjects into smaller sets (so you can handle activation and retirement issues more modularly). And you could have an empty placeholder subject set hooked to a workflow as long as all the other subject sets hooked to it have subjects -- but no, if you have a workflow that *only* has empty subject sets that will definitely be a problem.

**Comment by aliburchard** [comment]
Also, @mkosmala, just note that if you set the retirement to 1 for your workflows, and then want to add images later to make that workflow live, you'll have to ask us to "un-live" your project to change the retirement rules. We just arent' currently set up to have live and un-live workflows within a single project.

**Comment by mkosmala** [comment]
@aliburchard Basically, we have a lot of really similar workflows with slightly different wording depending on the images. So, for example, we ask about flowers on trees in one workflow and flowers on shrubs in another workflow. Because I'm only using a subset of the data, I don't have images that cover all the different vegetation types to start with. So I'm not using all the workflows right now. (As an analogy: imagine you wanted to ask questions about different species in Snapshot. For cheetahs, you want to know if they're sideways so you can see their spots. For lions, you want to know if they're male or female. Etc. But since your first upload may not include, say, a caracal, your workflow for caracal is empty to start with.)

@aliburchard Also, yes, I know about un-living my project. Will be very fast to up the retirement rule, so the project won't be offline long. I didn't see any other better short-term solution.

**Comment by aliburchard** [comment]
iiiiiinteresting. That makes a lot of sense, and I hadn't really thought about that approach.
