### ISSUE TITLE
Wide subjects display wider than browser window, forcing scrolling

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1142]
Can we force scaling of subjects so that they fit in the browser window? I don't love having to scroll down to see the questions, but it's manageable. Having to scroll left-right to see the whole subject is downright unfriendly. Related: #218
![screenshot](https://cloud.githubusercontent.com/assets/1066340/8782763/9abe11ae-2ee5-11e5-865d-09afecfc6158.png)

**Comment by chrissnyder** [comment]
I can't find the commit, but this behavior shouldn't happen anymore. If it does, please do reopen.
