### ISSUE TITLE
"No subjects available for workflow" error when user has seen all available subjects

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1145]
When there are still active subjects, but a particular user has seen them all, the user is presented with a "Error: No subjects available for workflow X". Can we change this to something nicer, like "you have seen all available subjects"?

**Comment by edpaget** [comment]
This is a bug. It should keep showing the user subjects with the 'Already Seen' flag.

**Comment by chrislintott** [comment]
I’m not convinced that’s the right behaviour - I think if someone has done everything, shouldn’t we say thanks and move them on. @edpaget, is that doable?

**Comment by chrissnyder** [comment]
Doable, sure, but also not how Panoptes was designed so it'd require a workaround.

I also don't think it's incorrect in the first place. This essentially emulates how Snapshot works, in that we keep serving subjects regardless of the state of the project to allow for continued engagement or educational use cases. It's important to keep in mind that users won't run into the Ouroboros-style "you did all active subjects" problem. When they get this message, they will literally have done everything.

An argument could definitely be made that the "already seen" flag is too subtle and should be much more  prominent. But that's a different discussion.

**Comment by camallen** [comment]
I may be wrong but i think this was a bug that was solved by https://github.com/zooniverse/Panoptes/pull/1175.

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes/pull/1175
