### ISSUE TITLE
I need a Talk board removed

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1149]
In project "Season Spotter Questions", I didn't realize that the board associated with individual subjects was created automatically. So I created one. (Oops.) And now I realize that there's no way to delete a board. Could someone delete the one titled "Specific Images" for me, please?

**Comment by aweiksnar** [comment]
If you click into the board and open the 'moderator controls' you can then click this button:
<img width="183" alt="screen shot 2015-07-20 at 8 49 10 pm" src="https://cloud.githubusercontent.com/assets/4039480/8791467/dc5c9c44-2f20-11e5-9b3e-875bb8f1294f.png"> 
to delete the board

**Comment by mkosmala** [comment]
Oh perfect! Thanks, @aweiksnar.
