### ISSUE TITLE
If you use the navigation bar on the side of Talk to go from one project Talk to another strange things happen

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1151]
The top part of the website changes to the other project but the talk discussions don't 

Went from GZ Bars Talk to P4T  Talk  - the GZ Bars discussion boards are present, but everything else says Planet Four: Terrains Talk

![screen shot 2015-07-21 at 4 30 55 pm](https://cloud.githubusercontent.com/assets/753325/8796309/5e7e7d00-2fc6-11e5-98b1-2a9b62d50994.png)

If I do the reverse - P4: Terrains boards show up on Galaxy Zoo: Bars Talk

![screen shot 2015-07-21 at 4 30 48 pm](https://cloud.githubusercontent.com/assets/753325/8796324/776dd05e-2fc6-11e5-99a0-229dffa203e6.png)

**Comment by mkosmala** [comment]
I've run into this, too.

**Comment by mschwamb** [comment]
Is it is just me, or is the same thing happening again. I moved to GZ: Bars talk from P4: Terrains Talk and it changes the postnames and title of boards, but subs in my name and avatar from where I am listed on P4: Terrains talk frontpage. 

I'm using the latest version of fifrefox on Mac. 

![screen shot 2015-11-21 at 11 57 13 pm](https://cloud.githubusercontent.com/assets/753325/11319266/ec4dd54a-90ab-11e5-90b5-a6d75b5af0ef.png)

**Comment by mschwamb** [comment]
@aweiksnar is this happening for you as well? Maybe the patch you put in for this got removed by another pull request at some point?

**Comment by camallen** [comment]
confirming i've seen this, looks like only some state is updated on the project change event but not the board owner / poster / avatars.

**Comment by aweiksnar** [comment]
@mschwamb Yeah looks like the patch may have been overridden so the latest comment users aren't updating

**Comment by mschwamb** [comment]
@aweiksnar this is still happening, but it now takes you to the projects front page, but to the bottom of the landing page so it's a bit confusing/disorienting

**Comment by trouille** [comment]
@mschwamb I definitely recreate that it takes you to the bottom of the new project's landing page (which we should fix). But I'm not able to recreate the other error you've listed in this thread. Likely I'm just missing something. Could you provide a recent screenshot so I'm sure I understand? Thanks!

**Comment by mschwamb** [comment]
It's an evolving ticket. It got fixed, got closed then it broke again so I reopened it and then the behavior you mentioned happened so I added it to this ticket. As Alex was continuing to work on it. The comment from Dec 29, 2015 is the most relevant. But since it was impacting the same button I've kept it in the same ticket.

**Comment by mschwamb** [comment]
I believe in December when the link paths/formats changed it caused the issue where it goes to the front page of the project, but my guess is the issue where Talk transforms partly still exists if the landing page issue gets fixed.

**Comment by mschwamb** [comment]
This hasn't worked since correctly since November and then fully broke when the links/redirection  got changed over.  Perhaps this functionality should be removed. Especially now that it doesn't take you to the other project's talk but instead to its front page and only includes the project builder projects not custom or older previous projects.

**Comment by alexbfree** [comment]
just linking this to #2253 in case i can address it there

**Comment by mschwamb** [comment]
addressed in https://github.com/zooniverse/Panoptes-Front-End/pull/2619
