### ISSUE TITLE
Multiple files per subject: uploads assign wrong mime-type to uploaded image

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#1152]
Just discovered this, with @camallen, while using zooniverse/panoptes-subject-uploader but I think the same bug exists in PFE too, on this line.
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/partials/subject-uploader.cjsx#L69

The subject.locations array in the API response is not guaranteed to be in the same order as the local files array, so matching on array index can associate the wrong local file with a newly created subject location.

Here's an example. curl https://panoptes-uploads.zooniverse.org/staging/subject_location/d270cd76-dada-42c9-af05-2d1a8aaeb5b5.jpeg brings back an uploaded text file, instead of an image.

I'm looking at how to fix this in the subject uploader, but thought I'd flag it here in case it has caused problems where subjects have multiple images associated.

**Comment by eatyourgreens** [comment]
Looking at this more closely, it might be that Panoptes sends the locations back in the wrong order. See zooniverse/Panoptes#1159

**Comment by chrissnyder** [comment]
For Mammoth Bats, we are using the mime type as the identifier. Works there, but not in the general case.

https://github.com/zooniverse/mammoth-bats/blob/master/app/pages/classify/classify.cjsx#L72

**Comment by eatyourgreens** [comment]
Reversing the returned locations fixed this for Wellcome, so I suspect it is a Panoptes issue.
https://github.com/zooniverse/panoptes-subject-uploader/blob/text-subjects/lib/panoptes-subject-uploader.iced#L139

I was find that the 'text/plain' file was actually a jpeg and vice-versa for the 'image/jpeg' file.

**Comment by eatyourgreens** [comment]
Tested this with a manifest containing a single subject, with one .png and one .jpg image. The upload failed with a 403 error from S3. Checking the content-type headers, PFE is attempting to PUT the jpeg to the png S3 URL. Presumably the content type mismatch generates the error.

**Comment by brian-c** [comment]
Wait, is the back end actually changing the order of subject locations? That should be fixed.

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/issues/1159 - yeah the backend returns them in the order retrieved from the db which in my local testing was reverse id order (so straight reversed like @eatyourgreens experienced).

**Comment by eatyourgreens** [comment]
Yeah, the order that comes back can't be guaranteed, so matching by array index is dangerous.

I think @edpaget is right in [this comment] (http://github.com/zooniverse/Panoptes/issues/1159#issuecomment-123309598) The front-end should map local files to S3 locations by mime-type, not array index.

**Comment by camallen** [comment]
I'm pretty sure we can guarantee to return them in the order that they are received in.

**Comment by brian-c** [comment]
Arrays are expected to maintain order, we should try not to break that. This could break Disc Detectives-style flipbook-y animations if all the images aren't the same format.

**Comment by eatyourgreens** [comment]
True that. Some of the Wildebeest Watch slideshows have wildebeest walking backwards and the clock counting down, which would be this bug.

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes/pull/1188
