### ISSUE TITLE
Invalid emails allowed on signup

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#1155]
Seems the format test isn't quite thorough enough:

![screen shot 2015-07-21 at 13 39 06](https://cloud.githubusercontent.com/assets/295329/8800836/fcdde3d2-2fad-11e5-8036-cf105bdeab62.png)

**Comment by edpaget** [comment]
Won't that fail when it's submitted? Fully validating emails is [super difficult](http://www.ex-parrot.com/pdw/Mail-RFC822-Address.html).

**Comment by camallen** [comment]
Just found a user with a busted email, will check devise validations.

**Comment by camallen** [comment]
So it looks like devise allows this email with `Devise.email_regexp => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/`. See [this](https://github.com/plataformatec/devise/wiki/How-to:-Use-a-custom-email-validator-with-Devise).

Any thoughts on adding an extra validator on that field to check for this? Reading the docs we might be excluding some email formats and there's no gaurantee that the email is valid anyway. I wonder if we should just rescue the failed welcome email and mark as invalid_email on the user model.

**Comment by edpaget** [comment]
That'd be fine with me. Typically the only effective way to validate emails is to send one with a link and ask people to click the link.

**Comment by aweiksnar** [comment]
Pretty sure the regex in that perl article is a stereogram
