### ISSUE TITLE
Request: Two-step confirmation for deleting workflows

### ISSUE THREAD

**Issue by frankvitaleiv** [zooniverse/Panoptes-Front-End#1156]
Currently if you hit "delete workflow" there is no pop-up to say "no" and cancel the action.  Could this be implemented, similar to the confirmation window for deleting a subject set?

**Comment by aliburchard** [comment]
YES please!

**Comment by rogerhutchings** [comment]
fixed via bab6d4af66f693acfe5076c3d48299d1da896b48
