### ISSUE TITLE
New Season Spotter projects don't show up in Talk sidebar

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1159]
The new Season Spotter projects don't show up in the Talk sidebar.

**Comment by DarrenMcRoy** [comment]
I'd still also really like to add Zooniverse Talk at the top of that list as well.

If community building is a priority, and Zooniverse Talk is where that's supposed to eventually happen, and we're training people to navigate using that sidebar, there's no reason not to have it in that sidebar.

**Comment by yshish** [comment]
As for the Side bar, I can't see any option there except the 'Jump to a
project' one, since they all display in white text on white background.

Screen shot:




2015-07-21 17:01 GMT+02:00 DarrenMcRoy <notifications@github.com>:

**Comment by DarrenMcRoy** [comment]
This is an issue that always seems to be specific you you, @yshish -- something with how your browser is set up, right? :-) Something with how text colors need to be defined?

**Comment by yshish** [comment]
Using a dark profile on Ubuntu, but have no problems with other sites but
Zooniverse. It happens in Firefox only.
Somewhere on Zooniverse the text colour is set up the way I can see it but
somewhere it isn't.

Do you think I can help it by setting something in the Firefox?

2015-07-21 17:14 GMT+02:00 DarrenMcRoy <notifications@github.com>:

**Comment by mkosmala** [comment]
Hey, we still can only see the 4 original Panoptes projects in the "Jump to a project" sidebar.

**Comment by vrooje** [comment]
AnnoTate also doesn't show up on the sidebar. It's not great that the sidebar is one-directional for traffic coming from there or from Season Spotter...

**Comment by DarrenMcRoy** [comment]
@aweiksnar ... I know we're going to be changing that sidebar eventually, but...

**Comment by aweiksnar** [comment]
I've updated the sidebar to show projects that are `launch_approved` for non-logged-in users, and for logged in users it'll show projects that they've participated in. Let me know if that works for everyone. 
The sidebar will be likely be changed to a more robust solution on the next redesign

**Comment by CKrawczyk** [comment]
@aweiksnar The sidebar now says "Error retrieving projects list" for me.

![screen shot 2015-09-14 at 4 01 04 pm](https://cloud.githubusercontent.com/assets/6557526/9853148/1646501c-5afa-11e5-979d-f145cf331256.png)

**Comment by aweiksnar** [comment]
@CKrawczyk Yeah @DarrenMcRoy noticed the the same. I'll look into it now. Seems to only happen to select users

**Comment by edpaget** [comment]
@aweiksnar it could be users that have a preference for a project they aren't allowed to see

**Comment by edpaget** [comment]
The same problem happened on the email preference page

**Comment by DarrenMcRoy** [comment]
Also, I got a report from a user this morning that she is seeing (only) a beta project, which probably shouldn't be visible there?

"In the Panoptes Talk you can jump to another project's Talk. But when I click there I only get Snapshots at Sea which is a project that is still in beta. I don't get the other 4 live projects."

**Comment by mrniaboc** [comment]
All I see are these projects...

![image](https://cloud.githubusercontent.com/assets/5321335/9858209/51e31926-5b17-11e5-927b-47d0a45a43f0.png)

**Comment by mschwamb** [comment]
No logged in, I see a different list on Zooniverse wide Talk (which doesn't have all the projects but has a different list of four)

![screen shot 2015-09-15 at 6 31 01 am](https://cloud.githubusercontent.com/assets/753325/9863538/776960e0-5b73-11e5-9e1a-cc493e2faf05.png)

**Comment by mschwamb** [comment]
Logged in on Planet Four: Terrains I see this error:

**Comment by mschwamb** [comment]
whoops hit close instead of comment....sorry.

**Comment by DarrenMcRoy** [comment]
I strongly believe that this should display all active Zooniverse projects (with Panoptes Talks) that you have classified on.

No betas, no public projects. And it should, by default, have a top link to the Zooniverse Talk. So even if you haven't classified on any Panoptes projects, the sidebar won't be empty.

So not this:

![screen shot 2015-09-17 at 10 00 30 am](https://cloud.githubusercontent.com/assets/8987864/9936676/c1ce8a74-5d22-11e5-9067-3e7d3097c196.png)


![screen shot 2015-09-17 at 10 00 38 am](https://cloud.githubusercontent.com/assets/8987864/9936668/bd45d4da-5d22-11e5-8cc6-fde19bfebbcc.png)

**Comment by aweiksnar** [comment]
I've got a PR up here #1561 that includes populating that with zooniverse talk + PFE projects

**Comment by DarrenMcRoy** [comment]
Yay!!

**Comment by aweiksnar** [comment]
Closed in  #1604
