### ISSUE TITLE
Keep accidentally hitting the profile link when trying to get to most recent thread on Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1160]
Maybe it's just me, but I keep hitting the profile link rather than the discussion thread title on the Talk front preview page (ie https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk) . Is anyone else doing that?  I seem to now always click a bit left and then I'm at the user profile rather than the talk thread. 

![screen shot 2015-07-21 at 11 06 38 pm](https://cloud.githubusercontent.com/assets/753325/8804227/b333896c-2ffd-11e5-9ab4-098b654ad794.png)

Maybe there is some small styling and or spacing that can be done - maybe this is one for @heathv ?

**Comment by DarrenMcRoy** [comment]
+1, I would really like some styling on that "most recent post," in addition to having it, you know, take you to the most recent post.

It would be nice even if it just said "Most recent post by..." somewhere. Definitely interested in @heathv 's thoughts.

**Comment by mschwamb** [comment]
Doing this every time I go to a thread even though I should know better.  I think it's because I'm so used to the first thing being the talk discussion link. @aweiksnar what about swapping the order so the talk thread title goes first?

**Comment by mschwamb** [comment]
Closing this since it's a moot point, and the new format has been around long enough to be accepted.
