### ISSUE TITLE
How do I set a picture for my Zooniverse account?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1161]
I don't see it in either 'profile' or 'settings'... Somewhere else?

**Comment by brian-c** [comment]
https://www.zooniverse.org/#/settings/profile

**Comment by mkosmala** [comment]
Oh wait! I found it. "Settings" has a little left-hand menu, where I can choose "Customize Profile" that allows for an avatar.

**Comment by mkosmala** [comment]
Thanks, @brian-c! Found it the same time you posted, it looks like.
