### ISSUE TITLE
Request for email notification from Talk

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1163]
A moderator requests that there be some sort of email notification option in Talk, so we can know when there is activity. I agree with her that this would be awesome. 

For moderators it would be nice to have email options for: "a new discussion was made", "5 new comments were made on existing discussions", that sort of thing.

For regular users, it would probably be nice to allow them to get email notification when someone replies to a comment of theirs and/or someone comments on a discussion they started. Sorta like what other social media sites do.

**Comment by mkosmala** [comment]
Related: #381

**Comment by DarrenMcRoy** [comment]
There is an extensive notification system being worked on...

**Comment by aweiksnar** [comment]
Closing via the latest Talk-Api notifications updates
