### ISSUE TITLE
Urgent: Users keep seeing "already seen" and "retired" image

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1165]
@brian-c I have a workflow with just one subject (see https://github.com/zooniverse/Panoptes-Front-End/issues/1138 for why). A logged-in user keeps seeing this one subject frequently ("about every 3-6 classifications"). There are 3 other workflows that have ~20,000 subjects total in this project. We should not be showing "already seen" subjects, when there are so many others that haven't been seen yet! 

Related: https://github.com/zooniverse/Panoptes/issues/830

**Comment by mkosmala** [comment]
I've had multiple users complaining about this now.

**Comment by edpaget** [comment]
Yeah we can't do anything about this as long as you have the workflow with only one subject.

**Comment by mkosmala** [comment]
@edpaget But this is going to be an issue for every project that gets near retirement. There are always going to be some workflows that finish before others. Why can't the front end simply not show these images?

**Comment by mkosmala** [comment]
@edpaget For now, because it's such a problem in my project, we're going to have to delete the workflow. But I want it SAVED to another project before it's deleted, so I can recreate it. (I would do it myself, but since the workflow is locked, I can't even view all the questions and related help.) How should we proceed?

**Comment by edpaget** [comment]
Share the names of the workflows with me, and I'll copy them to a new project.
