### ISSUE TITLE
Request for thumbnails in Talk next to discussions on 'Notes' board

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1166]
Can we have thumbnails in Talk on the Notes board, so we can preview the images that people are discussing?

**Comment by DarrenMcRoy** [comment]
Ah, you mean, in the list of discussions, that you can see before clicking in?

That might be a really good idea, but it's probably not near-term...

**Comment by mkosmala** [comment]
Yep. Requested by the users. I think they're used to it from the old Talk.

**Comment by tfmorris** [comment]
Below is what the index page looks like currently.  Independent of what any previous implementation did, this implementation doesn't provided much useful information.

![image](https://cloud.githubusercontent.com/assets/82178/8814161/7c910658-2fd7-11e5-9ebc-33cf6f6d721e.png)

**Comment by DarrenMcRoy** [comment]
This would probably be really useful... @aweiksnar @parrish @chrissnyder is this a feasible thing for PFE2? How hard would this be to implement? I don't have great perspective on it.

**Comment by vrooje** [comment]
+100

**Comment by vrooje** [comment]
Also might suggest for a long-term solution that if we're going to do this we should make actual thumbnails instead of just loading the full-bandwidth images very small.

**Comment by tfmorris** [comment]
You definitely want real thumbnails.  Also, you probably want roll the necessary information up into the top level API response.  From my glance at the network traffic, it looks like it would currently require a separate API call for each conversation to get the image URL (and then the GET for the image/thumbnail too), which is a lot of extra requests to add.

**Comment by DarrenMcRoy** [comment]
I need to get an idea from a developer how feasible this all is.

I agree that it would be extremely, extremely useful, but it sounds like a major undertaking.

**Comment by parrish** [comment]
@edpaget @camallen Are generated thumbnails for uploaded subjects on the roadmap yet?

**Comment by camallen** [comment]
Nope but two thoughts: 

1. We could provide another signed URL for the client to put to during the upload  process?
2. Or a data processing task where we add thumbnail locations after a creation timeout period to give the client time to upload?

I can see problems with point 1 on the client.

**Comment by parrish** [comment]
Agreed.  On the other hand, sometimes it might be necessary (e.g. videos)

This issue is roadblocked until we have actual thumbnails to use as the network load gets pretty insane otherwise.

**Comment by camallen** [comment]
Just throwing this out there as an idea. What if we just have a server that resizes the orginial subject images on demand and serves them via the CDN? Ala http://stackoverflow.com/questions/12985397/using-aws-s3-for-photo-storage

That we we don't need need to worry about manually creating them but we can get the required sizes on demand. Thoughts?

**Comment by parrish** [comment]
Clever thought.  Bonus, AWS Lambda supports imagemagick: https://forums.aws.amazon.com/message.jspa?messageID=583910

So we wouldn't even need a full server behind it.  I'll take a look at this soon.

**Comment by chrissnyder** [comment]
Was going to bring up Lambda here, as it's tailor made for this sort of thing.

**Comment by parrish** [comment]
Yep.  I've been meaning to check it out again lately.  I'll pick this up today or tomorrow.

**Comment by camallen** [comment]
Yeah lambda looks good, i assume this would mean we'd end up paying for storage as well as opposed to just running the server. Both sound like good options.

**Comment by DarrenMcRoy** [comment]
Given the importance of this, would it be a candidate for the PFE2?

**Comment by parrish** [comment]
It's a bit too early to set timelines yet.  We'll explore our options and report back

**Comment by tfmorris** [comment]
Cool.  Thanks guys!
