### ISSUE TITLE
Users keep seeing "retired" images

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1169]
I want to leave this up here as an issue, because it's going to be a problem for any project with multiple workflows when users do not choose which workflow to work on. 

Whenever a project with multiple workflows retires all the subjects from one workflow, but not the other(s) -- and this will always happen for a project with more than one workflow -- then users will get a high fraction of images marked "retired". Getting these images is a real disincentive for users, and will likely keep projects that are nearing completion from finishing as quickly as they would otherwise. 

Depending on the subject serving algorithm, this may be a bigger problem for projects with unbalanced workflows -- i.e. an uneven number of subjects for different workflows. I would expect such projects to be common.

I don't know whether the solution is in the back-end (not serving the retired images) or in the front-end (not showing retiring images, even if they're served). But just saying, "that's how it is" is going to create a bad user experience. @aliburchard @DarrenMcRoy @chrislintott

**Comment by edpaget** [comment]
For what it worth, I agree that we should fix that behaviour, but there isn't a quick solution that we were going to be able to get out to help your project. 

I think we should just add an 'active' state to workflows and let project authors activate/deactivate workflows within projects, and the front-end will only select from active workflows. When all a workflow's subjects are finished, we'll mark it as inactive. 

There are couple things to figure out though: 

+ How to let project owners/collaborators/testers preview inactive workflows
+ If people can muck with their inactive workflows while a project is live
+ If there's a good way to reactive workflows when more subjects are added or if that'll need to be manual thing for now.

**Comment by mkosmala** [comment]
@edpaget Fair enough on timeline. And I like your general solution.

**Comment by mkosmala** [comment]
FWIW, a user just mentioned that she had this problem on Whales as Individuals, too.

**Comment by chrislintott** [comment]
@camallen - is everything we need on the backend to support Ed’s solution done?

**Comment by camallen** [comment]
@chrislintott - @edpaget's solution has been in panoptes for a while (https://github.com/zooniverse/Panoptes/pull/1171) but probably not wired up for the front end.

**Comment by edpaget** [comment]
It should be wired up to the front-end in a basic sense: https://github.com/zooniverse/Panoptes-Front-End/pull/1210

I haven't figured out how to expose the active/inactive workflow states to project owners since it seems like reactivating a workflow might require an approval step.

**Comment by AdrianEvans** [comment]
We only have one workflow but have this same problem - have a user that almost stopped recently because he thought he'd classified all the subjects - he's actually only done less than 1/3.

**Comment by camallen** [comment]
@AdrianEvans that sounds like a different error. you say you've got 1 workflow that is still active and a logged in user is seeing retired images?

**Comment by AdrianEvans** [comment]
@camallen actually I'm confused - the images are retired but rather already seen by that particular user

**Comment by camallen** [comment]
@AdrianEvans i'll PM you.

**Comment by chrissnyder** [comment]
There's been a lot of changes to subject selection since Aug. 4. Is this still a problem?

**Comment by AdrianEvans** [comment]
I've put the question to our talk board to see what is happening - will
post with replies (or not) tomorrow

**Comment by AdrianEvans** [comment]
from replies on fossilfinder talk this appears to be resolved - thanks!

**Comment by chrissnyder** [comment]
Great!
