### ISSUE TITLE
Add "or email address" to sign-in field

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1170]
The sign-in field should say "Username or email address" instead of "user name."

Could even say "Username, display name, or email address," but the first is fine.

This will stop people from emailing us because they have "lost their user name."

**Comment by mschwamb** [comment]
The lost pasword takes an email address Why not make just make it say on sign in box 'forget your username and password?' for the forgotten password form make it  send both username and password there if it doesn't already
