### ISSUE TITLE
Line tool: length and direction determined by vertices mid point not the end point / end point selection

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#1171]
This is somewhat confusing: Both the length and the direction of the line tool are determined by the midpoint between the end points of the vertices, rather than governed by the beginning and end point as you would expect. This gives some strange user feedback.

In addition, it would be nice to have a two click feature for the line tool similar to how polygon segments are created. This could speed up workflows in certain user cases.

**Comment by vrooje** [comment]
I've gotten used to the line tool behavior and I rather like it now. The point-to-point behavior would be particularly useful if we had a line segment tool (which I may lobby for someday).

**Comment by khufkens** [comment]
I'm suggesting this because for small line segments the current behaviour is a pain and point-to-point behaviour would alleviate this. Over small distances the relative angle becomes a tricky thing to handle, making this action considerably slower / potentially frustrating.

**Comment by vrooje** [comment]
Agreed, drawing short lines is not easy.

**Comment by khufkens** [comment]
Which becomes problematic when you need to annotate the pencil lines in something like this. There are not many of those in my dataset, but they are of high scientific value as it tells you something about flushes of flowering etc.

![r1066149_c_9_4](https://cloud.githubusercontent.com/assets/1354258/8825936/980804f8-3050-11e5-8079-54229d31bb60.png)

**Comment by vrooje** [comment]
That specific problem is also related to #648.
