### ISSUE TITLE
Bug: Wide subjects don't display completely

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1172]
Subjects which have a high width to height ratio (and are not tiny), don't display completely. Part of the left side of the image gets cut off (and the user has to scroll to see part of the right side). 

A user reports this here:
https://www.zooniverse.org/#/projects/kosmala/season-spotter-questions/talk/62/926?page=1

And I can reproduce it.

(related #1142)

**Comment by brian-c** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1113645 strikes again. Just a moment.
