### ISSUE TITLE
Image alignment in markdown?

### ISSUE THREAD

**Issue by neonedu** [zooniverse/Panoptes-Front-End#1178]
Is there a known way to set the alignment of images displayed in markdown-driven images such as Research, Education, & FAQ? I've attempted a couple of the more common markdown workarounds, e.g. inline HTML and CSS selectors, but it would appear that the md processor ignores them.

**Comment by chrissnyder** [comment]
Not at the moment, no. Possible we'll add something in the future to allow
this.

**Comment by chrissnyder** [comment]
Closing in favor of https://github.com/zooniverse-ui/markdownz/issues/23
