### ISSUE TITLE
Update production API endpoint URL

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#1179]
The Panoptes API is now mirrored through CloudFront at https://www.zooniverse.org/api/. This URL should be faster for users than connecting directly to panoptes.zooniverse.org.

We need to test it extensively before we actually start using it to make sure CloudFront doesn't cause any issues. Caching is already disabled, so that shouldn't cause any problems. The thing that's most likely to cause problems is that CF doesn't pass along all HTTP headers, we have to whitelist specific ones. Accept, Origin, and Authorization are already whitelisted, but if there are any others that PFE depends on I'll need to add them to the list.

**Comment by chrissnyder** [comment]
Content-Type and Content-Length for subject uploads?

**Comment by edpaget** [comment]
Those don't go to the API.

**Comment by camallen** [comment]
Works well for the get requests I just tested (only a subset of end points)!

I assume the non-api end points (login / token exchange, etc) are not running via CloudFront and we still have to use the old panoptes.zooniverse.org url?

**Comment by astopy** [comment]
What are the URLs for those?

**Comment by astopy** [comment]
The login/authentication endpoints should be working via www.zooniverse.org <http://www.zooniverse.org/> now too.

**Comment by camallen** [comment]
Yep, just tested login and that works ok. I get a 404 on `/users/sign_out` via post though.

**Comment by astopy** [comment]
@brian-c Would you be able to deploy a copy of this in a folder under www.zooniverse.org somewhere to see if that gets around the Access-Control-Allow-Origin issue we were having?

**Comment by brian-c** [comment]
Deployed to https://www.zooniverse.org/temp. Looks fine over here.

**Comment by astopy** [comment]
Closed by #1312.
