### ISSUE TITLE
Export to Fusion Tables_enable data use by more people

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#1180]
@ggdhines: Sarah (my co-org on the digital humanities summer school) and I were wondering if you could export data from individual tasks as csvs, instead blobs for the whole workflow. This would enable people to relatively easily create tables of their data and use simple joins to query across them instead of having to parse the json, which is a little bit of a barrier for newbies.

If you wanted to go even easier, an 'export to Fusion Tables' https://developers.google.com/fusiontables/ button would enable users to do data analysis without any prior query language experience at all.

**Comment by ggdhines** [comment]
By data do you mean the raw classifications or the aggregations? Either way, currently exporting to JSON is the only supported way.

**Comment by VVH** [comment]
Yes, this is an enhancement request! As in, for the future. Both raw and aggregation as people could do interesting things with both.

**Comment by ggdhines** [comment]
Sorry - when you mentioned your co-org I thought this was something you wanted for this week. @aliburchard and I are very much in favour of this but this is a long term goal. Fusion Tables is an interesting option.
