### ISSUE TITLE
Non-existent sub-tasks appearing for drawing tool

### ISSUE THREAD

**Issue by frankvitaleiv** [zooniverse/Panoptes-Front-End#1181]
When designing a drawing task, we opened the sub-task screen, added a sub-task, and then immediately deleted it and closed the sub-task screen.  However, when viewing the workflow, the old sub-task appeared, and did not disappear until we went back into the workflow builder screen and viewed the workflow a second time.  It seems like there is a lag between changing the workflow and the change appearing.  We're not sure if anything can actually be done about this, but it's worth knowing.

**Comment by chrissnyder** [comment]
I don't know if this is something endemic of a larger issue or just a super edge case. Might've just seen API trouble at the time and this could be closed?

**Comment by brian-c** [comment]
I can't reproduce this behavior, can you @chrissnyder?

**Comment by chrissnyder** [comment]
Nope. Chalking this up to an API issue at the time. Will reopen in the problem shows up again.
