### ISSUE TITLE
Clicking on project links from stats page goes to "dummy" site for Ouro projects

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1186]
From the stats page, if you've worked on an Ouroboros project and click on it, it takes you to the "Panoptes dummy page" instead of to the real project.

I.E., if you click on Chicago Wildlife Watch, it takes you to https://www.zooniverse.org/#/projects/zooniverse/chicago-wildlife-watch instead of http://www.chicagowildlifewatch.org.

This could be very confusing for users! :-)

**Comment by DarrenMcRoy** [comment]
This has been a cause of confusion for a few users, so it'd be nice to fix. Just FYI that I've received multiple reports of folks tripping over this. :-)

**Comment by chrislintott** [comment]
Should we just put a holding page up for now?

**Comment by camallen** [comment]
this should probably just work like the projects page cards [here](https://github.com/zooniverse/Panoptes-Front-End/blob/e5c902b3ea5f6ea7c1c9a576010aaec518642f25/app/pages/projects.cjsx#L34).
