### ISSUE TITLE
Deleting a disucssion pops me out to Talk main

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1187]
If I delete a discussion, I get sent to the main Talk page, rather than the board (or even project) that I was in. Should probably default to going back to the board.

**Comment by edpaget** [comment]
This just got fixed in https://github.com/zooniverse/Panoptes-Front-End/pull/1176

**Comment by edpaget** [comment]
It'll be deployed in a few minutes

**Comment by mkosmala** [comment]
Wow, you guys are fast!
