### ISSUE TITLE
help window width IE

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1191]
The window width for the help box in internet explorer is crazy wide - full window width. This has caused some testers to try to use the back button to exit the help as it looks like a full page - obviously this screws things up.

This was based on a user with windows 7...
I've replicated this on windows 8 version 11 - a very common combination

**Comment by AdrianEvans** [comment]
just tested - the #1193 is fixed but the help box width is still erroneous

**Comment by edpaget** [comment]
It usually takes some time between when an issue is closed and code is deployed.

**Comment by edpaget** [comment]
Looks like it's fixed for me in IE11. Let me know if you still see issues.

**Comment by AdrianEvans** [comment]
AHH, tis now better - awesome sauce!
