### ISSUE TITLE
IE project front page descriptions cut off

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1193]
visibility of the description isn't good - not centred as in chrome and is way off the page to the left

seems to be on all projects I've checked

![image](https://cloud.githubusercontent.com/assets/10448680/8839580/b5056342-30ce-11e5-8904-5cb042c6b768.png)

**Comment by edpaget** [comment]
@AdrianEvans what version of IE is this in?

**Comment by AdrianEvans** [comment]
11 on Windows 8. Same on win 7 with version 10
