### ISSUE TITLE
Username search - issues with case sensitivity

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1194]
I feel like there is an existing issue floating around along these lines, but couldn't find it. 

I'm trying to add a user, AndrewB, to a project. I know he created his name with those specific capitalizations, and I know that while usernames are no longer case sensitive for creation (you can't have two different usernames of andrewb and AndrewB), it's confusing that when I type in AndrewB, only andrewb is available. 

To make things more confusing, there *is* a username down the list (not visible in the screen shot) of AndrewbB ...it's got an extra letter in there, but why are the cases kept for some names and not others?

<img width="1280" alt="screen shot 2015-07-23 at 12 10 20" src="https://cloud.githubusercontent.com/assets/6217406/8848975/d0ca5514-3133-11e5-951e-c7dcf412c75d.png">

**Comment by edpaget** [comment]
User search is case insensitive. It shouldn't matter what you put in.

As far as I can tell case is preserved when you register for an account. I just signed up as 'EdPaget0' and my username shows as correctly cased in the interface and was saved to the database with the correct case.

Is it possible AndrewB just signed up with lowercase letter and miscommunicated that to you?

**Comment by aliburchard** [comment]
he definitely signed up as AndrewB on demo while names were case sensitive (I couldn't add him as a collaborator with the name "andrewb"). Maybe that got changed magically in the migration to production? 

Since nothing is broken, I'll go ahead and close this, assuming his name got changed in the migration or something.

**Comment by edpaget** [comment]
We didn't migrate from staging -> production.

**Comment by aliburchard** [comment]
Ah,  @camallen migrated the specific project (retinas) over to production,
but I suppose the users just had to sign up in two separate places (demo &
real home), so maybe he used lowercase then. Either way, should be fine...

On Fri, Jul 24, 2015 at 3:59 PM, Edward Paget <notifications@github.com>
wrote:

> We didn't migrate from staging -> production.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes-Front-End/issues/1194#issuecomment-124551127>
> .
>



-- 
Alexandra Swanson, Ph.D.
Ecology & Citizen Science Postdoc
The Zooniverse
University of Oxford
