### ISSUE TITLE
Recording 'Gold Standard' data 

### ISSUE THREAD

**Issue by ttfnrob** [zooniverse/Panoptes-Front-End#12]
Project owners need a way to enter 'gold standard mode' - this may be covered elsewhere, but such classifications should be recorded as such in the annotation so that the metadata is available on the raw classifications for the consensus engine and Milkbot

**Comment by aliburchard** [comment]
Out of curiosity -- will "gold mode" be implemented for Panoptes launch?

**Comment by brian-c** [comment]
Not for May. Issue is here: #116.
