### ISSUE TITLE
Getting not allowed to create message in private talk message and then inbox giving error

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1201]
Tried to reply to a private message and got this error that 'not allowed to create message' or something similar. Then I couldn't get to my inbox. Had this error Error: not allowed to index? this Conversation(id: integer, title: string, created_at: datetime, updated_at: datetime)

But in a separate window open, I went to my inbox and everything looked okay. Everything succeeded or at least the message shows up in the private message thread and I can access my mailbox. Signing out and signing back in cleared the errors. Though not sure if the person I was talking to is getting notified they have a private message or not

**Comment by aweiksnar** [comment]
Perhaps this was an anomaly - I haven't experienced / seen  any other private messaging issues since opened. Is this still happening?

**Comment by mschwamb** [comment]
Haven't seen it since, but I also haven't gotten many private messages. @aweiksnar if you want to close it, I can reopen if I encounter it again.

**Comment by aweiksnar** [comment]
Thanks!
