### ISSUE TITLE
Changing the image used to denote Planet Four on the Zooniverse home page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1204]
low in the queue, Question maybe for @DarrenMcRoy or @heathv  - Would it be possible to get a picture that looks more like Mars for Planet Four on the list of projects rather than a zoom-in of a spider. I think by looking at the projects for all the others, you get an idea of what the project looks like. But for Planet Four, I think it's the only one that you don't really know it's about Mars when looking at the image. The image that was used on the Old Zooniverse home page would be great if that could be used instead. Thanks

**Comment by DarrenMcRoy** [comment]
The image on the old home page was too small; it would get distorted. Do you have an image you want? Send it to me and I can crop and replace it. :-)

**Comment by mschwamb** [comment]
Thanks @DarrenMcRoy I'll send you something over the weekend

**Comment by mschwamb** [comment]
How about this http://www.nasa.gov/images/content/49589main_MM_Image_Feature_85_high.jpg or if you need lower resolution http://www.nasa.gov/multimedia/imagegallery/image_feature_85.html ?

**Comment by DarrenMcRoy** [comment]
Done!
