### ISSUE TITLE
Sign out API sessions via DELETE method

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#1205]
From  #1179 - Seems the cloudfront API proxy isn't allowing the "X-HTTP-Method-Override:'DELETE'" header through and probably shouldn't.

[Here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/api/auth.coffee#L242) should use a straight DELETE and not try to replicate Rails form delete submission override. This was probably me being stupid and advising brian to use the delete override method for some reason.

**Comment by brian-c** [comment]
I believe this'll break the tests, since Phantom won't send bodies with DELETEs.

**Comment by edpaget** [comment]
I think you can send the CSRF token as a header `X-CSRF-Token` I'll see if this has changed in more recent rails versions.
