### ISSUE TITLE
Redirect Users from the home page

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes-Front-End#1208]
Signed in Users shouldn't see the home page when they visit zooniverse.org, we should redirect them to a page that's has more useful info for them (maybe stats/profile feed)?

**Comment by vrooje** [comment]
Ooh! Yes, I'd love a page with classification count and ribbon, most recent project(s), never tried project(s), recent comments & replies to comments...

**Comment by DarrenMcRoy** [comment]
I agree 100%, this is HUGE for community-building and for making people

I want a page where users see their projects, recommended projects, newest  projects, their ribbon, replies to their comments, new threads that they might be interested in, popular threads (especially in ZooTalk), announcements, maybe "most upvoted comments..." ... really awesome if it's customizable, to boot...

All the things that will make a person feel like a Zooite and get them to explore the site at large, get them involved with the community, get them invested in the Zooniverse as an overall concept.

This will be an large project, I imagine, and probably involve design from @heathv to start (?), but from the perspective of my Sloan goals it's one of the most important. (@trouille)

**Comment by edpaget** [comment]
Yeah I agree a page like that would be sweet, but I think there's an intermediate step we can take, until we have that page ready.

**Comment by vrooje** [comment]
Agreed. I don't always have a sense of what's a quick add with major impact. Would:
  - member since [date]
  - classification count
  - ribbon
  - threads commented on, ordered by most recent update

be possible without a huge amount of work?

In the longer term I think this would be a great place for a "new since last visit" list of threads, but my understanding is we're not quite there yet.

**Comment by chrislintott** [comment]
Closing this for now because I think we need a larger discussion that won't be well constrained to a single github issue.

**Comment by edpaget** [comment]
@chrislintott I opened this issue, because I thought there might just be something small we could do right away, like redirect to the projects page or their stats page, while we worked on a better home page for volunteers.
