### ISSUE TITLE
Planet Four terrains redirect link stopped working

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/Panoptes-Front-End#1215]
We had a redirect from terrains.planetfour.org to https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains working which stopped working now. Could this be fixed rather soon? We have a NASA press release out now (http://www.jpl.nasa.gov/news/news.php?feature=4664) with a broken link, which is rather bad for getting new users.

**Comment by edpaget** [comment]
@michaelaye that redirect is working for me.

**Comment by michaelaye** [comment]
ah, phew, it's only not working in Safari then (OSX 10.10.4, Safari 8.0.7)

**Comment by edpaget** [comment]
Confirmed by @saschaishikawa. Looks like it's an outstanding bug in Safari https://bugs.webkit.org/show_bug.cgi?id=24175

**Comment by mschwamb** [comment]
Missed this  and had created https://github.com/zooniverse/MarsZoo/issues/146#issuecomment-124640682 I can't replicate it either

**Comment by edpaget** [comment]
Yeah there's not really anything we can do about this. Safari ignores the part of the URL after the '#' in redirects.

**Comment by michaelaye** [comment]
That's okay. But still weird that @mschwamb can't replicate, while @saschaishikawa could.
