### ISSUE TITLE
Adding something like the bottom bar from Talk 2.0 to Panoptes Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1218]
I think it can be a bit overwhelming when going to Talk since if you're not been to a Zooniverse project you might not know what Talk is. I liked the banner at the bottom of Talk 2.0 that said ' Talk is a place for citizen scientists to observe, collect, share, and discuss data from Zooniverse projects' - Maybe something like that could go somewhere ?

**Comment by aweiksnar** [comment]
I see no reason not to add this. @DarrenMcRoy do you have a short one-liner that you'd like for this?

**Comment by DarrenMcRoy** [comment]
Proposed:

*Talk is a place for Zooniverse volunteers and researchers to discuss their projects, collect and share data, and work together to make new discoveries.*

Any objections?

**Comment by DarrenMcRoy** [comment]
After posting in general, nobody objected, and Grant and Jordan like it, so, that should be good to go, @aweiksnar!

**Comment by aweiksnar** [comment]
Cool thanks @DarrenMcRoy, will add in soon :100:
