### ISSUE TITLE
Making the subject smaller in the Talk note discussions and subject pages

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1219]
I'm finding the subject takes up a lot of room and that you have to scroll to get down to the actual discussion parts of the thread and the subject page. I think it would be really helpful if the subject was made as large as is currently being using in 2.0 and then you could click to get enlarged version (and maybe in the future later a magnifying glass feature)

![7767b158-1fde-11e5-9f06-4ee11a8284e5](https://cloud.githubusercontent.com/assets/753325/8887222/5a839e46-32ab-11e5-8603-a7e6c6550baf.png)

![screen shot 2015-07-25 at 8 59 09 am](https://cloud.githubusercontent.com/assets/753325/8887238/e5f90d76-32ab-11e5-896c-8c5504816f2e.png)

Compared to Talk 2.0 

![screen shot 2015-07-25 at 9 03 41 am](https://cloud.githubusercontent.com/assets/753325/8887247/3aa9687a-32ac-11e5-8086-071bb15fe0d1.png)

**Comment by aliburchard** [comment]
+1

**Comment by vrooje** [comment]
Yeah, given that we don't limit the pixel size of uploaded subjects it makes sense to me to force a limit for formatting purposes in Talk, but link to the full-size version.

**Comment by mschwamb** [comment]
@aweiksnar  Can this be reopened? 

The subject image page size hasn't changed find it still too big that I still have to scroll to see any comment in the notes discussion from a volunteer on Talk.

on the subject page  - the size didn't change so you have to scroll significantly to see the image 

![screen shot 2015-07-30 at 7 15 32 pm](https://cloud.githubusercontent.com/assets/753325/8981982/708b5c0e-36ef-11e5-902d-ab664381f9ab.png)

I also found that the new size for on the notes page didn't make a much of a difference in visibility of a person's text. It's definitely a bit better but I still need to scroll significantly to see a volunteer's comment  I think the images needs to be even smaller. 

Can the subject preview be made the same size as is currently on Talk 2.0 (like http://talk.planetfour.org/#/subjects/APF0001mop) and allow for a button or a click to view the fullsize preview (like what the project builder has you click an icon and the image preview shows up)

**Comment by chrislintott** [comment]
@aweiksnar Are you happy to look again at this at some point? (cc @chrissnyder)

**Comment by aweiksnar** [comment]
@chrislintott Yeah I initially changed the subjects to be max-width of 650px in discussions, and 800px for the subject page. I'll reopen this now and close after making those numbers a bit smaller

**Comment by chrissnyder** [comment]
Also worth noting that we will be overhauling the subjects page itself in the near future, so we shouldn't play with this too much until then because it will all likely change (see #1271)
