### ISSUE TITLE
Link button and profile links to specific Talk posts are no longer working

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1220]
This was working earlier, but seems to not work today. If you try and go to a post from a volunteer's profile, it doesn't take you to that post anymore. It takes you somewhere else in the thread. 

Example: 
![screen shot 2015-07-25 at 11 00 30 am](https://cloud.githubusercontent.com/assets/753325/8887625/d4f13574-32bc-11e5-9749-f6663c264d43.png)

https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/10/8?page=3&comment=614 
Says it's page 3, but it's actually on first 1 and the link doesn't work

**Comment by mschwamb** [comment]
Same thing for the Talk Search

**Comment by aweiksnar** [comment]
closed in #1248
