### ISSUE TITLE
Pinned Talk thread shows up as most updated post when there is a newer non-pinned thread

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1223]
Not sure what's going on but you can see this on Planet Four: Terrains Talk 
![screen shot 2015-07-25 at 12 03 27 pm](https://cloud.githubusercontent.com/assets/753325/8887810/52fdce34-32c5-11e5-9a7f-1bca01606689.png)

![screen shot 2015-07-25 at 12 05 39 pm](https://cloud.githubusercontent.com/assets/753325/8887819/83e39a74-32c5-11e5-9c16-b9edd868a5bb.png)

**Comment by mschwamb** [comment]
Might be the pinning, it might be because those two new posts are threads started from the subject pages, not threads made be creating a discussion in the message board

**Comment by DarrenMcRoy** [comment]
yshish has some more detail about this in a Talk post: https://www.zooniverse.org/#/talk/17/107?page=10&comment=2974

Adding to PFE2 in lieu of reopening #873 yet again.
