### ISSUE TITLE
When you have a drawing task with a question task associated after it, the summary only reports the drawing part

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1224]
Working on test project as a demo and the task is to draw a circle on the image and then answer a multiple choice question associated with that marking, the summary after the classification is submitted only lists the information about the marker

![screen shot 2015-07-25 at 3 05 20 pm](https://cloud.githubusercontent.com/assets/753325/8888455/382c4b56-32e0-11e5-8543-7554ed77e546.png)

![screen shot 2015-07-25 at 3 17 29 pm](https://cloud.githubusercontent.com/assets/753325/8888457/5b7d0924-32e0-11e5-92ef-908e0cfaa520.png)

**Comment by eatyourgreens** [comment]
Did this get fixed? The multiple choice answer is in the summary, but it's reported as it would be in the classification (the array index of the selected answer): `details: { value: 3 }`

**Comment by mschwamb** [comment]
@eatyourgreens still happening 

<img width="1079" alt="screen shot 2017-11-09 at 7 54 01 am" src="https://user-images.githubusercontent.com/753325/32621265-5448f910-c523-11e7-95db-e23d325eac48.png">

**Comment by mschwamb** [comment]
Yes, the multiple choice answer is in the summary, but it's reported as the array index of the selected answer, which doesn't mean anything to a volunteer who's classifying. This should be spelled out in the same words as the buttons on the classification interface have for the multiple choice bit.

**Comment by mrniaboc** [comment]
Should we even have the classification summaries any more? So many projects decide against having it and many people who do use it report that their volunteers get frustrated when they see the summary and can't correct their classification.

**Comment by eatyourgreens** [comment]
This would be handy for checking your transcription on a drawing/transcribing project like Decoding the Civil War, or SCOTUS Notes.

**Comment by eatyourgreens** [comment]
NB, in the case of a transcription project, you probably want to see this summary before you submit the classification, so that you can review and correct your answers.

**Comment by mschwamb** [comment]
@eatyourgreens currently If you see the summary you're not able to go back and edit your answer.

**Comment by eatyourgreens** [comment]
Related Talk discussion for context: https://www.zooniverse.org/talk/18/497047?comment=1109798

**Comment by eatyourgreens** [comment]
Turns out the drawing task summary just renders each mark as JSON, which isn't very useful.
https://github.com/zooniverse/Panoptes-Front-End/blob/a216b7fb98f8897065c5fc2b9c0f9b6e6685edbb/app/classifier/tasks/drawing/summary.cjsx#L50-L51

**Comment by eatyourgreens** [comment]
Should be fixed by #4707.
