### ISSUE TITLE
Making it more explciit where favorites are located

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1225]
I've seen more than one comment about not being able to find favorites. I realized to me, it's not very intuitive that when you favorite that it goes into a collection under your accounts collections. Especially since using the heart is a different functionality that adding to a collection. What about adding 'Favorites' to the dropdown account menu and then it would take you to your collections page with an added favorites tab to just list your collections of favorites?

**Comment by mschwamb** [comment]
Thought I'd mentioned this in  case it's helpful,  someone on Planet Four: Talk asked today about how to find their favorites.

**Comment by edpaget** [comment]
On it. Going to add a 'Favorites' tab to the collections page.

**Comment by mschwamb** [comment]
Thanks @edpaget . Would it also be worth adding a link to the drop down profile menu as well, so if people go there they would get directed to to the new tab on the collections page? I'm not sure everyone knows that favorites are actually just a special type of collection

**Comment by edpaget** [comment]
Sure that sounds like a good idea as well.
