### ISSUE TITLE
Not signed in popup appears when changing password

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#1227]
When you submit the change password form, you get the 'not signed in' popup, even though you obviously are

**Comment by camallen** [comment]
@rogerhutchings when you submit the reset password you don't get signed in automatically.The popup is to prompt the user to sign in again with their new reset password. Is this the behaviour that you're seeing?

**Comment by rogerhutchings** [comment]
Weird - I just created a new account to test this out. No, what happens is that you get the 'not signed in' message for a second, then you're automatically logged back in anyway. Different to what I got first time, but still not what you're describing

**Comment by eatyourgreens** [comment]
@camallen submitting a change from your settings https://www.zooniverse.org/#/settings briefly shows 'You are not signed in' after submission.

**Comment by camallen** [comment]
@rogerhutchings sorry, misread your original post. I thought you were resetting via email. Please ignore the noise from me. 

I can reproduce the behaviour described.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/api/auth.coffee#L190
A workaround to keep your session alive?

**Comment by chrissnyder** [comment]
Yea, the auth code signs you out, then back in if your session would be invalidated, resulting in the behavior everyone sees. Not sure how to solve that otherwise from the front end?

**Comment by parrish** [comment]
Yeah, I think this is okay.  It does log you out/ back in.  I don't think that's a problem.
