### ISSUE TITLE
Talk: nested replies are illegible

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#1228]
Since opacity multiplies, nested replies become illegible pretty quickly in a threaded conversation.
![panoptes-talk](https://cloud.githubusercontent.com/assets/59547/8904506/ccb55c86-3457-11e5-8744-290d793ccfd4.jpg)

**Comment by DarrenMcRoy** [comment]
Related to #888 in terms of overall improvement of reply functionality.
