### ISSUE TITLE
Capture HTML traffic from talk.zooniverse.org?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1233]
I had forgotten the new talk URL, and typed http://talk.zooniverse.org/ as a guess. This turns out to be the Ouroboros Talk API, and gives a JSON response. I think that other users might also guess at this URL - so maybe we should ensure that HTML requests made to this URL get captured and redirected to https://www.zooniverse.org/#/talk ? Also maybe we should redirect from https://www.zooniverse.org/talk as well ? 

At the very least, the URL should do something sensible when visited in a browser rather than just returning JSON.

(I realize this suggestion is partly an ouroboros suggestion, but figured it was better to start the discussion in this repo rather than the Ouroboros one as there are more eyes on it).

**Comment by edpaget** [comment]
It's actually https://github.com/zooniverse/Talk-Api that's running there.

**Comment by aweiksnar** [comment]
closed in https://github.com/zooniverse/Talk-Api/commit/fca1ba0de76aefef9453ee64f4597e079682b4cb
