### ISSUE TITLE
Talk: 'Collections' hard to find; also not grouped by project

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1234]
From the Season Spotter boards:
> Hi Margaret! I'm a moderator on PenguinWatch.
> My collections are designed to help anyone looking for info on certain features. Of course, the collections really help me with my moderating tasks.
> So:
> * finding 'collections' on this project took some doing because the word is not immediately visible. I had to wander around with my mouse in 'the hope of'. Collections can be so useful for info, and increase one's sense of continuation with a project. 'Collect' should be easier to find.
> * as far as I could make out I either see my collection, or all collections from many projects. What I want to see is other collections on this project.
>
> Collect is not the same as 'favourite'. I'd suggest that 'collect' goes on the top bar.
>
> Best wishes, Joan (AvastMH)

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
