### ISSUE TITLE
Users don't like scrolling down to see questions

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1236]
When subjects are wide, it forces the questions down below the subjects, requiring users to scroll. They don't like that. 

(From Season Spotter Talk boards:)
> Please consider revising page design for these side by side images. If you rearrange the question and answer sufficiently, I will not have to scroll down to enter an answer, and then scroll back up to see photos for the next question. It would simply be more convenient if I did not have to scroll up and down.

I know this is a result of automatic layout so that project display on multiple devices and screens. But it's something to look at / think about at some point, since it's not ideal.

**Comment by edpaget** [comment]
Since we have the 'thumbnail' resizer is there any reason we could just download a smaller image based on the screen resolution?

**Comment by brian-c** [comment]
I've actually got a couple ideas I want to try for this, the easiest is just to only drop the questions down in portrait-orientated viewport or when the image are is smaller than the questions area.
