### ISSUE TITLE
"Already seen" banner appears on return from Talk

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1239]
Perhaps this is as intended, but it confused a user:
* User classifies a subject
* User clicks Talk to comment on the subject
* User clicks browser 'back' button to go back to classifying
* User sees the image again at the "done" stage (with the classification summary and the 'Talk' and 'Next' buttons), but the image has an "Already seen" banner on it

The presence of the "Already seen" banner confused the user, as she was expecting to come back to a page that looked the same as the one she left.

**Comment by edpaget** [comment]
@brian-c @aweiksnar would it be reasonable to advance to the next subject after a user clicks the 'Talk' button?

**Comment by aweiksnar** [comment]
I think that would be cool, since the only other UI action to take at that point is to click next

**Comment by brian-c** [comment]
Sounds good to me.
