### ISSUE TITLE
Integrate Google Tag Manager with Panoptes

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#124]
.. and potentially add some custom event tracking too. @brian-c  and myself to discuss.

**Comment by camallen** [comment]
@brian-c is this getting added in? Pretty sure @mrniaboc would like to have some visibility into usage.

**Comment by mrniaboc** [comment]
Yes. I would love that.

**Comment by alexbfree** [comment]
OK basic tracking is added in https://github.com/zooniverse/Panoptes-Front-End/pull/522

Please leave this ticket open as we should do more than just basic tracking, need to consider custom events, etc...

**Comment by chrissnyder** [comment]
Closing not because I disagree that we should do additional tracking, but they should be addressed in their own issues/PRs.
