### ISSUE TITLE
Problems loading Talk / problems signing in..

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1241]
I was just having problems to load the Talk properly (only the top menu appeared a few times) and to sing in.

After a while the Talk loaded without the Talk Sidebar but it didn't allow me to sign in (I haven't signed out before, just closed the browser tab which usually does sign me in the next time automatically, but not this time). It said Error 0 on the password although it was a correct one.

Screen shots:
![x](https://lh3.googleusercontent.com/-NFRq2EqMBKc/VbZOU_NFiiI/AAAAAAAAIN8/3Sf3aE1Ighg/s0-Ic42/ysh_2015-07-27_17-19-11.jpg)
![](https://lh3.googleusercontent.com/-FsklD5by3LI/VbZOfAx7EQI/AAAAAAAAIOM/C5KjdfGPz84/s0-Ic42/ysh_2015-07-27_17-20-41.jpg)
![](https://lh3.googleusercontent.com/-Cg01vPA2q5I/VbZOd2s0_zI/AAAAAAAAIOE/frfvvCtckbM/s0-Ic42/ysh_2015-07-27_17-26-55.jpg)

I tried it a few times, reloading didn't help. After I give it up, and opened the browser again, it loaded properly and automatically signed me in without problems.

**Comment by DarrenMcRoy** [comment]
The ops team is aware and working on this. It's a back-end issue, so probably doesn't go here in front-end. Thanks for letting us know! :-)
