### ISSUE TITLE
All comments in a "Notes" thread should be treated as linked to subject?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1250]
So, with regards to how "Notes" works, since the entire thread is always devoted to a single subject, it occurs to me that all posts in those threads should probably be treated as posts "about" the subject.

For instance, if you saw this subject, you'd think there was only one post about it: https://www.zooniverse.org/#/projects/tedcheese/whales-as-individuals/talk/subjects/481016

But if you go to the actual Notes thread, you see that there are many people talking about it: https://www.zooniverse.org/#/projects/tedcheese/whales-as-individuals/talk/31/163?page=1&comment=265

I think that if you leave a hashtag in a Notes thread, or talk about it at all,  it should automatically attach to the image at the top, the same way that it does on old Talk 140-character comments.

This may be partially resolved by overhauling the Subject page view, but I want to be sure that hashtags are getting attached from Notes threads as well. Yes?

**Comment by DarrenMcRoy** [comment]
After discussing with @aweiksnar and @chrissnyder today, this is on hold.

**Comment by parrish** [comment]
Fixed via zooniverse/Talk-Api#74
