### ISSUE TITLE
moderation: "destroy" post --> "delete"

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1251]
Suggested wording change in the moderator controls on Talk.

**Comment by mschwamb** [comment]
@edpaget did this get lost in a subsequent merge or the change isn't live? I noticed it still says destroy for the button

**Comment by aweiksnar** [comment]
@mschwamb That was just for the confirmation message. I'll place a PR now to change the button delete text as well

**Comment by mschwamb** [comment]
Thanks @aweiksnar
