### ISSUE TITLE
moderation: delete and ignore buttons not working

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1252]
Our GZ Bars moderators have tried using the delete and ignore buttons on the moderator controls for a reported post, and neither seems to be working... or if they are there's no indication of it.

![screen shot 2015-07-28 at 13 43 13](https://cloud.githubusercontent.com/assets/2357126/8931549/1183a4c6-352f-11e5-8802-f7fdbfd7730f.jpg)

**Comment by mschwamb** [comment]
Getting the same thing in Terrains.

**Comment by vrooje** [comment]
I now get a confirmation window when trying to delete a post, but am getting a 401 with either that or the Ignore button.

![screen shot 2015-08-05 at 14 35 20](https://cloud.githubusercontent.com/assets/2357126/9086907/64bddcdc-3b7f-11e5-81b6-26f1f0372768.jpg)

**Comment by parrish** [comment]
This should be fixed now.  I'll wait for @vrooje to verify before closing though

**Comment by vrooje** [comment]
Yep - seems to be working now! Both delete and ignore.

There's another bug related to this -- but I'll post it as a separate issue. Thanks!

**Comment by parrish** [comment]
Cool
