### ISSUE TITLE
The "need help" button isn't showing in the interface anymore!!! URGENT

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#1253]
The need help button has dropped of the interface as of yesterday (as far as I can tell). This is messing up some people's workflow I imagine. I had complaints from my test users as well.

I'm not sure how to flag things urgent, so sorry for the all caps title.

![screenshot from 2015-07-28 09 25 03](https://cloud.githubusercontent.com/assets/1354258/8932399/ea942350-350a-11e5-82d6-c18aaf326f61.png)

**Comment by khufkens** [comment]
Ok, seems like the system has eaten my help comments (when going in and out of beta?). The interface also doesn't update properly anymore in the workflow section. The help text of one action sticks across changing tasks, but luckily does not propagate to the final interface. Not sure what is up but it seems rather ugly.

**Comment by vrooje** [comment]
It's not just you. Mine is missing from the project builder too, and I have a live project so I couldn't have edited it (and I didn't change my status).

**Comment by khufkens** [comment]
Any way to bump this up the queue? If this is systemic then this is truly messing things up. Also a good reminder to back up all my text on the interface.

**Comment by edpaget** [comment]
Yes I am working on it now.

**Comment by khufkens** [comment]
Thanks Edward! Any chance of recovering the text? If so I hold of on rewriting things.

**Comment by edpaget** [comment]
Your text isn't lost. The translation module is just failing to add it to workflow resource when you request it.

**Comment by edpaget** [comment]
@khufkens. I'm seeing help text on your project now. Can you?

**Comment by edpaget** [comment]
Also super sorry, but it looks like since you edited the workflow the old help text was overwritten.

**Comment by khufkens** [comment]
Don't worry about it, had to adjust it anyway...
