### ISSUE TITLE
new screenshot for Details - Collaborators on How to Build a Project

### ISSUE THREAD

**Issue by lfortson** [zooniverse/Panoptes-Front-End#1254]
The current screenshot shows "scientist" as one of the collaborator options; this should now be "researcher" as the descriptive text indicates.

**Comment by mschwamb** [comment]
Also Science Case became Research Page so those screenshots should be updated as well

**Comment by DarrenMcRoy** [comment]
Screenshots obtained. Will work with @edpaget on Monday to get them uploaded.
