### ISSUE TITLE
Nicer error message when data exports are not ready

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1257]
Right now you get an XML error page if your data exports aren't ready. But I wouldn't know what to make of that if I were an average user. 

Also, exports are relatively slow. My export with 16,000 subjects took ~30 minutes. So it might be better to suggest people might need to wait "several minutes" instead of "a few seconds".

**Comment by mkosmala** [comment]
Just a follow-up: when you request an export, the little link to the right says "requested X minutes ago" (for example). Mine said "requested 30 minutes ago" and when I clicked on it, I got a download! But it wasn't the export requested 30 minutes ago, it was the one requested 6 days ago. (I hadn't gotten an email yet, so I should have known...) Hopefully a pretty easy fix to the wording...

**Comment by mschwamb** [comment]
My suggestion in #989 is to remove the csv link until it's finished

**Comment by vrooje** [comment]
Alternate possibility: keep the "requested X minutes ago" text, but add "exported Y [min/hrs/days] ago" and link the classification file to *that*.

**Comment by aliburchard** [comment]
I really like @vrooje's suggestion - I often hit the link to export before remembering that I could just use the previously exported link. Having that distinction explicit (with two different links) might help.

**Comment by chrislintott** [comment]
I like this too.
