### ISSUE TITLE
Solar Stormwatch missing on publications page

### ISSUE THREAD

**Issue by willettk** [zooniverse/Panoptes-Front-End#1258]
The 4 papers for Solar Stormwatch appear on https://www.zooniverse.org/#/about/publications, but the title of the project is missing for some reason.

**Comment by chrislintott** [comment]
@mrniaboc Something you could look at?

**Comment by eatyourgreens** [comment]
That page is making an API call for `projects?slug=zooniverse/solar-stormwatch` and gets an empty array back, so maybe something to do with the project privacy settings in Panoptes?

**Comment by camallen** [comment]
@eatyourgreens sounds like a bug in panoptes api response if that's the correct slug. @edpaget thoughts?

**Comment by camallen** [comment]
this is working now...not sure what was up

**Comment by edpaget** [comment]
@camallen Someone had set Solar Stormwatch to be private.
