### ISSUE TITLE
Linked images from the Talk button are from Snapshot Supernova

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1264]
I've classified enough Planet Four: Terrains images for those to show up, but I only get Snapshot Supernova images when I click on the button in Talk 

![screen shot 2015-07-29 at 6 18 19 am](https://cloud.githubusercontent.com/assets/753325/8945421/d7c037aa-35b9-11e5-9b0e-63b1dfc841a0.png)

**Comment by vrooje** [comment]
Is this the same issue as reported in #854?

**Comment by mschwamb** [comment]
yep - still showing

**Comment by edpaget** [comment]
This is caused by https://github.com/zooniverse/Panoptes-Front-End/issues/1266#issuecomment-125923328

**Comment by edpaget** [comment]
Whoops didn't mean to close
