### ISSUE TITLE
Setting up Zooniverse home for translated versions of the site

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1265]
Future plan, but maybe something that over the next few months could be implemented - Had a meeting with the ASIAA outreach office and @chrislintott yesterday. Came up about having Zooniverse home having a drop down menu where you would select the language and those projects that were translated would show

**Comment by vrooje** [comment]
I like that.

**Comment by chrissnyder** [comment]
Definitely something we want to do, but might be awhile.

**Comment by mkosmala** [comment]
@chrissnyder I know language translation has been a "future plan" for a while (also #472). How "future" is this currently? It would be great to be able to have Jungle Rhythms in French (as the subjects are actually IN French). And we've been talking about translating Season Spotter. But no sense in doing it if it's not exposed on the volunteer front end. (We can make do without Project Builder access to translation on the back-end, but the volunteers need to be able to select the appropriate language on the project front-end, like @mschwamb describes.)

**Comment by chrissnyder** [comment]
I wouldn't bet on it anytime in the next 6 months. There's a lot of underlying work we haven't done to make PFE translatable, and there's still questions about how to expose text for translation, Talk integration, etc.
