### ISSUE TITLE
Profile page where user can see *all* subjects they've classified?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1266]
This is being discussed on Zoo Talk [here](https://www.zooniverse.org/#/talk/18/1048?page=1&scrollToLastComment=true) and I think it's a good idea to let users see all the subjects they've previously classified.

**Comment by camallen** [comment]
@edpaget any reason we don't create recents in the classification lifecycle? Seems it exists but was never wired up as per [here](https://github.com/zooniverse/Panoptes/blob/dc255329cd19f3ebdfaf6771f8dc4b4540e91efc/lib/classification_lifecycle.rb#L92).

**Comment by edpaget** [comment]
Nope I think that was an error not-wiring it up on my part. We should probably run a rake migration to create those for current projects.

**Comment by DarrenMcRoy** [comment]
Bringing this back up, wondering if it's something we're considering.

We still don't have a Recents page, and that seems like it might be high priority given how useful that feature has been in Ouro projects.

**Comment by parrish** [comment]
Pretty sure this is going to be tabled indefinitely.  Happy to revisit if it gets designed at some point in the future.
