### ISSUE TITLE
Add some version of "tag groups"; ability to auto-populate collection with hashtags

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1267]
On Ouroboros Talk we can save a search as a "collection" which is really just an auto-updating subject search based on hashtags. I thought this was a great feature and would at some point love to see it on Panoptes Talk too.

**Comment by aliburchard** [comment]
+1. a lot of +1.

**Comment by DarrenMcRoy** [comment]
We've talked in the past about having a way to improve the process of collecting stuff. I think at least getting back to where we were would indeed be a big plus. :-)

**Comment by vrooje** [comment]
Should clarify I see this as an enhancement that I think the researchers and very keen volunteers will love (if Ouroboros Talk is anything to go by), but I have no idea what priority it should get because I don't know how big an ask this is from a dev standpoint.

**Comment by chrislintott** [comment]
Can you point us to people using it? I’d got the impression this was a feature noone made use of.

**Comment by vrooje** [comment]
I use it to keep track of bulgeless tags, and we also used it with volunteers who were tagging NGC, UGC etc. objects in GZ. For the former case I'd like to have been able to curate it a bit better, but it's still useful.

**Comment by DarrenMcRoy** [comment]
I use it to keep track of things that have been recommended for the Daily Zooniverse (#dailyzoo), or in place of searches in order to actually pull up relevant objects (for instance, creating a "coyote" tag group instead of trying to search for "coyote.") It's been pretty critical since it has been basically the only use of hashtags that has actually worked properly.

It might be less critical if it becomes possible to return a list of subjects with a hashtag by searching that hashtag (and perhaps then to auto-create a collection out of those results?) but we don't have that right now, either -- and even in that scenario, we lose the auto-populate option, which is nice, but perhaps not critical.

**Comment by yshish** [comment]
It's being massively used in the Chimps by the moderators. Each animal type is getting collected this way there (but the search doesn't work there so we have no other option to keep the video examples together)

**Comment by mschwamb** [comment]
Is there still going to be the 500 subject limit?  Someone on Planet Four was using it to keep track of images identified as having boulders, but noticed that his collection wasn't getting any bigger after a certain period of time. I think makes those collections were  not very helpful once you hit the limit. 

On using the hashtags for science, I never used groups, I would ask for a dump of zooniverse id for all subjects that had that associated hashtag or was in a collection that was marked with that hashtag. I never used the tag groups

**Comment by edpaget** [comment]
No collections are totally uncapped, and we will work to maintain them that way.

**Comment by mschwamb** [comment]
Sorry Forgot to reference the [link](http://talk.planetfour.org/#/boards/BPF0000005/discussions/DPF0000kyu) to the Planet Four Talk discussion about group hashtags in my previous reply.  I should note other than that person, I've never seen the group tag used on projects I've been involved with.

**Comment by parrish** [comment]
I think we have two good options to support this

- Use the new tag search interface to add subjects to a collection
- Provide a mini-tag search in the collection edit view.

From a data scale and design perspective, I don't think we're going to be providing automagically updating collections like the previous talks.

**Comment by DarrenMcRoy** [comment]
> I don't think we're going to be providing automagically updating collections like the previous talks.

I think it would be a huge mistake to not have auto-populating collections, especially if we can add the capability for "or" collections as well as "and" collections. That was *really* strongly requested by our user base. They love the tag groups; their biggest problem was that you could only populate with "stuff tagged a and b," not "stuff tagged a OR b," which was tremendously limiting.

Perhaps a better hashtag search (can you search by "or?") solves this in part, but please be aware that tag groups were an extremely popular feature that solved many critical use cases.

Why can we not support this further? Why force people to continually manually import newly tagged items, over and over again, if they want to maintain a collection of "all things tagged as x?"

**Comment by parrish** [comment]
> From a data scale and design perspective, I don't think we're going to be providing automagically updating collections like the previous talks.

I'll go into more detail on why this is a bad idea.

- data scale:
  - With millions of subjects and tens (hundreds?) of thousands of tags, performing complex combinations of boolean logic isn't going to happen in Panoptes' architecture.
- design perspective:
  - When do we update the collection?
    - Every time a tag is added or removed, we iterate over every tag group and update it -- we can't filter them since we have to perform the boolean query to know if it needs to update.
    - On a schedule (daily?) we update every tag group.
  - How do we store the collection contents?
    - As a table?
      - Lots of it would end up being thrown away and recreated on an update -- that's a problem.
    - As embedded objects?
      - Row size would end up crippling performance unless we set fairly restrictive limits on collection size.

In reality, we'd be looking at setting up and maintaining a different type of database to support this feature (~$600 / year).

From a usability perspective:
  - It's a confusing concept -- most users don't use it.  **Only 0.25% of users who create collections create tag groups.**
  - Users that have used it typically don't keep up with how the collection is changing

Alternatively....

We can add a subject search that can filter by tags to the collection editor.  Simple to build, use, understand, support, and maintain.  The only difference is that the collection doesn't update without user intervention.

If we're supporting this, that's how we'll have to approach it.

**Comment by DarrenMcRoy** [comment]
Would the subject search use "or" parameters? (To use an example on the boards, it's common for tags to get separated. Can you search for "blue-ford or blueford or ford-blue or fordblue"?

Would you be able to search for "subjects tagged x excluding subjects already in this collection?"

**Comment by parrish** [comment]
I see that as something of a duplicate issue.  Autocompleting tags will help form consensus on similar tags.

Tag search won't provide boolean logic however.

**Comment by mschwamb** [comment]
Also getting the list of popular tags on the subject pages will help reinforce popular ones.

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829

**Comment by vrooje** [comment]
I never quite understood the automagically updating collections until @parrish explained it as a saved search on subjects; I think that is much clearer messaging about that feature and if messaging it that way also allows us to offer it in such a way that it doesn't put a load on the architecture, I think that's great.

**Comment by DarrenMcRoy** [comment]
It's true that one of the major purposes of them on the old Talk was a workaround for the fact that Search didn't work well enough.

**Comment by parrish** [comment]
> It's true that one of the major purposes of them on the old Talk was a workaround for the fact that Search didn't work well enough.

Not at all.  The motivations were:
  - "Hey, this would be cool to do"
  - A researcher could put out a request like "Hey, if you see things like this, tag them with #whatever"
  - A user is interested in subsets of the data like blue ellipticals, green blobs, etc.

Collections in general were motivated by use cases like the green peas and voorwerpies.  Instead of having to constantly update a thread with images of a certain type, it was supposed to facilitate a conversation around a group of images.

In general, I think that's the case we're trying to optimize for, rather than building a list of every barred spiral galaxy, or every wildebeest.

**Comment by DarrenMcRoy** [comment]
> A researcher could put out a request like "Hey, if you see things like this, tag them with #whatever"
> A user is interested in subsets of the data like blue ellipticals, green blobs, etc.

Yes, and they were used for both of those things quite a bit. But they were also used to get around the buggy search. :-)

**Comment by vrooje** [comment]
So are we thinking we'll have a "save this search" type thing for subjects, and the ability to translate that to a (static) collection, and possibly the ability to update/overwrite a collection upon request?

I think that would be really useful... but I'm just trying to understand. (Thanks)

**Comment by parrish** [comment]
At least right now, we're not.

It's something that we'll likely support through other means later on for purposes of project building, but building collections for Talk like that isn't on the agenda.
