### ISSUE TITLE
Add several features to subject page

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1271]
(Referencing #1020 and #914, and closing them in favor of this issue.)

Here's my requested feature list for what should be on the subject page, as per our Talk discussion earlier today (7/29/15). Please add your own thoughts... what do you like, what don't you, what's critical, what's impossible, etc. Thank you! :smiley: 

- The image (click to view at full size) and its subject number.
- A hover-over magnifier for the image.
- All hashtags currently attached to the subject, plus the number of times they have been mentioned (e.g., #penguin x2, egg, #dailyzoo x3)
- “The image appears in X collections,” click to show them; “this image has been favorited by X users,” click to show them. Similar to Twitter fav/retweet counts, click to show.
- Other stats about the image: number of times classified, is it retired, maybe even eventually involving Alex’s consensus tools.
- Comments from the Notes thread attached to the subject (otherwise, “nobody has yet left a note on this subject.) Perhaps the 5 or so most recent comments, with the ability to “show more.” Link to the Notes thread, where all comments in the thread are attached to the image.
- Separate from the Notes thread, other discussions/posts mentioning the image or using it as a linked image (both? Or just comments using linked image?)
- Ability to add a note or a discussion (exists already), with explanation for what each of these are (doesn’t yet).
- Links to the image’s subject page on any other Talks, if the project is attached to multiple projects. (Would solve the problem of #1020, perhaps.)
- Related images? (if possible to determine with an algorithm somehow?)
- Options to share a subject on social media.
- If we are going to “onboard” people upon their first visit to Talk, perhaps with a quick one or two-slide onboarding explaining where it is you’ve just landed and welcoming you to start contributing. (This would appear regardless of how you first entered Talk.)

**Comment by vrooje** [comment]
To me the essentials here are:
  - Basic introduction to Talk for those new to Talk (maybe just a dismissable banner)
  - the image & subject number (obviously)
  - associated hashtags (maybe word cloud style, but I'm not convinced of this)
  - associated collections
  - retired flag if it applies
  - linked comments (all, or at least paginate with well more than 5 per page) displayed so that newcomers can't help but see these before they comment themselves
  - linked discussions
  - other linked projects

Cool to have:
  - favorites count
  - completeness (n_classifications/retirement_limit)
  - social media buttons
  - zoom on subject image
  - "notify researchers" button for moderators, once that feature is implemented across Talk

Sure, but not an immediate priority:
  - visualization of consensus
  - Related images

In addition to the above it might be cool to tell people whether (and when) they classified the subject themselves.

**Comment by chrissnyder** [comment]
Let's not assign a deadline until we have a better grip on what we are implementing.

That said, I think I entirely agree with @vrooje, including everything in the Cool To Have section.

I don't have an idea on how far along a consensus API for subjects is, and related images is a trickier problem.

**Comment by DarrenMcRoy** [comment]
Thanks, Brooke. I really like the last idea of "have I classified this subject?", that'd be an awesome flag.

One thing: I'm not sure that the "notify researchers" is a necessary thing for subject pages. It's more of a flag for comments, no? If there's an interesting subject, there's going to be comments about it, and a researcher's attention could be brought just as easily to those comments. That's the only one from your list that doesn't seem necessary to me. Everything else is :+1:

Chris, that's fine. I only added it to the sprint because we said in the meeting that we'd pick one for the PFE3 sprint. but yeah, let's be sure we have a good grip. Brooke's list aligns quite closely with mine.

**Comment by vrooje** [comment]
Yeah, I'm just imagining a moderator reading the comments on the subject page, thinking *oh, I should flag that for the researchers*, and having to click through to the comment thread before doing so. That last click seems unnecessary, especially as the first thing I would do as a researcher is to check the subject page anyway.

On the word cloud vs count of tags, I'm skeptical of either. For projects that are conducting rare object searches, this would amplify false positives, which we don't want. And quantifying the tags as "votes" implies to me a weight given to these tags relative to the main classifications that they generally won't have. If 99 people tag a Space Warps subject as a lens and 1 as no_lens, that doesn't mean the science team will call it a lens with 99% confidence. I'd rather the tag listings be complete but not proportional.

**Comment by DarrenMcRoy** [comment]
But tags ARE weighted in the metadata when there are more of them. I didn't know either until @parrish told me when we were building Chimp & See. (At least, it was that way on the old Talk; I assume nothing has changed.) It's not as simple as your 99%, but to my knowledge, it's still that way. It's independent from the main classifications, of course, but for instance we've been using it in C&S to emphasize that a subject tagged #dodge 10 times and #billy once will let the science team know that it's more likely that the chimp is Dodge, since individual IDs are outside of the basic classification system.

And, ideally, you wouldn't need to click through to the comment to flag it. Ideally, you could flag, report, and even reply to the comment from anywhere that it appeared. Any reason why not?

**Comment by parrish** [comment]
> tags ARE weighted

They currently aren't sorted.  We can certainly add that though

**Comment by DarrenMcRoy** [comment]
Well, at the moment, they don't even display on the subject page. But I assume that, at the very least, when they do, yes, they'd be sorted by weight. I just thought it would be nice to make that clear, and give people more info, by adding a little number next to each. But I could be talked out of that if there's a fear it could damage the science case.

**Comment by DarrenMcRoy** [comment]
I've shared this page with @jwbmartin, incidentally, as we move towards being able to start fleshing out the subject page. :-)

**Comment by mschwamb** [comment]
Maybe to add something in and then have to change it when a design is implemented is more time, but if the graphical redesign isn't going to be for some time, I ask the development team to consider adding some minimal basic functionality into the subject pages that everyone agrees should be added (hashtags, collections, list of associated discussions seem to be on that list) in the meantime.

**Comment by DarrenMcRoy** [comment]
@mschwamb The major redesign of the subject page is a near-term priority and I believe development on it is about to begin. So I think we're steering clear of too many short-term fixes unless they move towards the overall rebuild!

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1828
