### ISSUE TITLE
Request: ability to "backup" a project

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1273]
It would be nice to be able to "save" a project in some form (to recover from accidental deletions of project parts by owners or collaborators -- see #1253 for example). Even if it were just a text dump of the JSON for the project, content pages, and associated workflows, it could save folks a lot of time and sadness. Could be an export (e.g. of JSON text) or just be a "backup" saved in Panoptes space (sorta like GitHub saves snapshots of repos as "releases").

**Comment by mkosmala** [comment]
Related: 
https://github.com/zooniverse/Panoptes-Front-End/issues/931
https://github.com/zooniverse/Panoptes/issues/1045
https://github.com/zooniverse/Panoptes/issues/1129

**Comment by aliburchard** [comment]
Definitely! @camallen and @astopy and I talked earlier about about a "revert to last version" -- I suspect this fits in with that functionality.

**Comment by vrooje** [comment]
+1, definitely. That issue with the help text not showing made me realize I was depending too much on database backups. I'd like to keep my own too...

**Comment by chrissnyder** [comment]
More of a backend request, but keeping this open for the required UI to go along with it.

**Comment by camallen** [comment]
FYI - We have a json project / worfklow dumper from https://github.com/zooniverse/Panoptes/issues/887 & https://github.com/zooniverse/Panoptes/pull/913. So it's really a matter of creating an export / import OR a versioning mechanism that uses this on a project.

@mkosmala I suggest you open up a backend issue that starts the discussion about how best to implement this.
