### ISSUE TITLE
Request: progress bars

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1275]
I was sure this was in the issues somewhere, but I couldn't find it... It would be wonderful to have "progress" bars like exist for many of the existing Zooniverse projects. It would be nice feedback for the users and additional motivation when they've almost finished. 

Of course since project teams can add more subjects, it might be necessary to have multiple bars like we have for Snapshot Serengeti -- one per "season".

**Comment by camallen** [comment]
Slightly related to this, https://github.com/zooniverse/Panoptes/issues/986

**Comment by mschwamb** [comment]
I think if implemented this should be an optional feature to show on the front page. I think progress bars work well if a project is very popular, but on slower projects that might discouraging. Planet Four has been at 90% completion for 2 months, so for Planet Four it's better to not show that but for a fast classification project like Snapshot Serengeti I can see how this could be very handy

**Comment by vrooje** [comment]
Suggest we define progress not by number of subjects retired, but by n_classifications/(n_subjects * retirement_limit).

**Comment by chrissnyder** [comment]
This is progress bars for projects, not workflows, right? Though I guess workflows would be useful too.

**Comment by mschwamb** [comment]
This has been implemented with the new project landing page.
