### ISSUE TITLE
showing specific metadata on Talk but not in the classification interface?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1281]
Not sure if this is the right repo for this question. Currently there are two choices for your metadata, you can hide metadata from being shown in the interface with a symbol in front of a column, but does that mean then that data doesn't show on Talk. Volunteers for Planet Four: Terrains would like to know what full frame CTX image the data came from. We could add the link in the metadata but we wouldn't want that show in the interface. Only in Talk . Does that functionality currently exist or could that be added in the future?

**Comment by chrissnyder** [comment]
This starts to get into the realm of me thinking we are handling metadata incorrectly. If everywhere we want to display metadata, we are displaying it differently, then I'm not sure what usefulness metadata is a a single collection of things.

Is the core problem that we just want to avoid displaying things within the classifier, and then everything should be displayed everywhere else? Or are there other use cases that might exist?

**Comment by eatyourgreens** [comment]
@chrissnyder Are we getting into the realm of distinguishing between metadata that's used to manage the subjects, and metadata that's used to describe them? Administrative metadata vs. descriptive metadata if I remember my museum terminology correctly. Anyway, one set is needed by the science team, to analyse classifications, while the other is needed by the classifiers, to help in classification.

**Comment by vrooje** [comment]
I like that framework @eatyourgreens, and I'd add a third category that @mschwamb describes (here and in #285): metadata that should not be available in-classification, but which the classifiers can use after classification for value-added follow-up.

**Comment by chrissnyder** [comment]
@eatyourgreens Sort of. As Brooke mentions, there's a third category too.

I worry that there's inevitably going to be more use cases that folks want because we are going down the road of treating metadata differently in one place than in another.

**Comment by edpaget** [comment]
TBH I don't we should be in the business of managing data for science teams (unless we get dedicated time to work on things like that), which is why I haven't wanted to add hidden fields or extra things to exports. All data connected to a subject should be visible always and if science teams don't want users to see particular data, just don't upload it with subjects. 

Also won't giving users more data in the classification task let them make better classifications?

**Comment by mschwamb** [comment]
@edpaget  To answer your question, no. Wisdom of crowds currently only works if the viewpoints are independent.  Since you don't know who clicked on the metadata button data button or force everyone to click the button you can't be sure that the added information didn't allow them to find a source on Talk or get added information through google. if the data is a simulation or not, people respond differently if they think they're being tested. On Talk you want to make sure people know they're discussing a simulation especially if volunteers are doing their own follow-up investigations .

Inherently the database is managing stuff for the science teams, and I think it should be. I've relied on the database metadata on past projects all the time in analysis especially if I wasn't the one who created the subjects. The best and fastest way has been to get the info from the Mongo database dumps or in the csv files produced. 

if we're expecting that science teams store the rest of the info associated with the subjects elsewhere, in 3 or 10 months later if they lost the file that had that information per subject, you might lose the capability for actually getting science out of the data. Having the option that the team can uploaded information associated with the subject in the database helps ensure that the data will be useful, especially if the person who made the subject data leaves the project or has less time to help (which happens a lot with the short time grad students and postdocs are in 1 place).

Talk is a different beast, and it's used to try and engage people more and explore the data. There you do want the metadata to show that would bias your classification, but on Talk helps people go beyond the classification interface. The majority of current projects show metadata on Talk that they don't show in the interface, Galaxy Zoo, Planet Four, Planet Hunters do this all the time. An example would be a link to the full frame HiRISE image on Planet Four or simulation or not ID on Planet Hunters.

I agree the development team shouldn't have to do more work on this beyond basic functionality.  I think if you could have only two types of metadata it would satisfy the use cases that are already on the majority of Ouroboros projects: metadata either doesn't show in the classification but in Talk or the metadata shows everywhere. 

If you wanted to add the third category of private on both Talk and classification interface for science team analysis persons that would be great but could be lived without if its too much effort.

**Comment by edpaget** [comment]
> Wisdom of crowds currently only works if the viewpoints are independent. Since you don't know who clicked on the metadata button data button or force everyone to click the button you can't be sure that the added information didn't allow them to find a source on Talk or get added information through google

We have no idea if that's happening anyway or the kind of the outside knowledge volunteers bring to the project or if they totally wasted while they're classifying. The whole point of crowdsourcing is that the behaviour of one user is statistically balanced out by having multiple people classifying. 

Also if the issue is just knowing if someone clicked the metadata button that would utterly trivial to record, way easier that figuring out how manage arbitrary metadata visibility. 

> if we're expecting that science teams store the rest of the info associated with the subjects elsewhere, in 3 or 10 months later

I have no idea why this isn't a reasonable expectation.

**Comment by mschwamb** [comment]
@edpaget  it's done on other Zooniverse projects all the time where data is shown on Talk and not in the interface, so if this frequent use case even if you don't agree with my reasoning. Especially simulation or not. I think it should in Panoptes. If the development team can't for whatever reason add this capability in, then  I'll publish a list on the Planet Four blog that people can use for conversion. For my analysis I can't have the CTX id listed in the classification interface.

**Comment by vrooje** [comment]
There's all kinds of ways to bias a user with metadata. If a Galaxy Zoo user can see galaxy coordinates before finishing a classification they can look up a previously existing morphological classification from another project. If that affects their classification and part of our science is getting an independent classification to compare to existing data, then we'll be biased. Worse, I'm not sure how we could effectively track that. We could track their clicking of the metadata button and maybe whether they've highlighted certain text, but our action based on that would probably be to reject the classification, which would mean we've wasted people's time (including the devs).

On the other hand, *after* the classification is submitted it's possible that letting people use that information could bring up new information about rare objects, or outliers. The volunteers are pretty amazing at that stuff -- Planet Hunters is a great example. So it can be really helpful to have this balance.

The issues described in the first bit above are already taken care of by what we have now. The next bit is an enhancement, I think.

**Comment by mschwamb** [comment]
@vrooje has said this way better and succinctly than I've been able to.

Okay, so the current state is if you use the symbol in the manifest that the column is completely hidden and if it's not then it's available everywhere including the classification interface. The enhancement that  I'm asking for is in the future, if there can either be a third type of metadata where it's visible on Talk but the classification interface or change the way secret data is handled so that always shows on Talk but not in the classification interface 

@vrooje I tried to figure this out with Kitteh Zoo and when I hit the metadata button the subjects like this [one ](https://www.zooniverse.org/#/projects/vrooje/kitteh-zoo/talk/subjects/458021) in Talk and the interface and when I hit the metdata button nothing comes up. Not sure if that's related to having hidden data or not. I don't know of any other projects using that

**Comment by vrooje** [comment]
Hmm, the Kitteh Zoo thing is a bug -- I've reported it. I haven't added the hidden column to the actual metadata yet so that shouldn't be related.

**Comment by mkosmala** [comment]
@edpaget I'm in general agreement about Zooniverse not managing science team metadata, but we do need at least ONE piece of metadata in common, so we can ```JOIN``` (or whatever) the classifications with the science team metadata, even if it's not uploaded with the subjects. In our case, we're using filenames, but the problem is that the filenames have information in them that we don't want users to see. The workaround is to give each image file a random identifier and have a lookup table. But that's a lot of extra work...

**Comment by vrooje** [comment]
I agree with @mkosmala in principle, but I also think that the data analysis step will be the most challenging for a lot of project builders (e.g. in subjects where joining tables is restricted to dinner parties). By giving people the option of providing ~all their metadata up front, we remove a future barrier to researchers making best use of their classifications. And that will only be possible for a lot of people if some or all of the metadata can be proprietary.

**Comment by eatyourgreens** [comment]
New territory for us, but I guess data gathering projects where volunteers upload subjects via the API won't have an external dataset, initially. I don't think they should manage that data through panoptes - better to export the subjects and manage them elsewhere. However, they're likely to have metadata that's included with the upload, but would bias classifications.

Orchid Observers has a bunch of subject metadata from the photo upload form, which we hide from classifiers (eg. the photographer's identification of the species.)

**Comment by chrislintott** [comment]
Just to summarise the specific request here : 

- It would be good to specify : 1. Metadata never to be shown to the user. 2. Metadata always available (on the classification page). 3. Metadata only visible on Talk.

That’s consistent with what we’ve done on other projects, and it’s important.

**Comment by mschwamb** [comment]
I have a use case for this for this - so I thought I'd mention it here. A new project I'm working on with collaborators (early stages not expecting a launch  anytime soon - 3 months is likely the timeline) where we would be showing known examples of the thing we're asking people to search for. We would want to make sure it's clear on Talk that for those subjects people didn't think they discovered something new when it's not new,  but we don't want people to know in the classification interface before the classification is submitted since  it's a test sample for detection efficiency.

**Comment by mschwamb** [comment]
Thank you @parrish!
