### ISSUE TITLE
menu wrap/rollover on smaller screens is a little pants

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1282]
when the top menus roll around they are rather close to the site logo - I'd suggest having it indented so they are justified to the research menu - example below:

![image](https://cloud.githubusercontent.com/assets/10448680/8979276/6cd4cc5c-36a0-11e5-88ae-8bd73aa4553f.png)

**Comment by mkosmala** [comment]
+1

**Comment by eatyourgreens** [comment]
Closing this because a redesign is in the works.
