### ISSUE TITLE
Updating Visability page to warn about that if you take a live project back to development that the Zooniverse team has to make the project visable again on Zooniverse home

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1283]
Currently if you have an approved project builder project that's now live and need to take it down to make a change (moving it back to development) and then make it back live, the project doesn't show on Zooniverse home anymore after you do this. It needs the approval state reset by the development team . No where in the project builder does it mention this. I think it would be worth a sentence so it's clear that you'll need to apply for live status again/talk to the development team to get back on Zooniverse home.

**Comment by aliburchard** [comment]
Good point. @mschwamb  - can you identify where in the current help text that would make the most sense to a project builder, and we'll add that sentence in?

**Comment by mschwamb** [comment]
Right above in the project builder where you have the switches for live and development I think would be a good place to have a line about this.

Also adding  what is the preferred mode for contacting the team. Is there a switch and you all get an email and will be in touch to see if it's a minor change and the site can go back up or if it's an added workflow with I would imagine requires a beta. I posted on github. Because right now a typo in the help will bring down the project ,in the future I imagine the site will only go down for major changes. 

I presume this also would need to go in the [policies](https://www.zooniverse.org/#/lab-policies)  where it talks about Zooniverse approved projects.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
