### ISSUE TITLE
Pagination broken in collections

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1284]
If I hit the next button it takes me to the top of the page, but the page is still the first page. If instead I manually change the number of the page to the next one it works and then the next and back buttons work.

**Comment by mschwamb** [comment]
Happens in Firefox and Chrome. I haven't tested further than that. If it helps it looks like it's grabbing NaN for the page number https://www.zooniverse.org/#/collections/AlbertII/what-is-that?page=NaN

**Comment by mschwamb** [comment]
Forgot to mention this is when you're viewing the subjects in a  specific collection (see above link)

**Comment by mschwamb** [comment]
Noticed this again when trying to find the favorited image. It happens in the favorites page as well. I presume since their exactly the same as a collection

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes-Front-End/pull/1527

**Comment by mschwamb** [comment]
@chrissnyder Is this feature that addresses this deployed? I see the Talk sidebar fix is in and visible, but I still get this issue when paging through a collection.

**Comment by chrissnyder** [comment]
Definitely not fixed. Will put a PR in shortly.
