### ISSUE TITLE
Having the focus change to the top of the page when you move to the next or different page in the collections tab

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1285]
lower in the queue - If you advance to a different page from the collections tab (https://www.zooniverse.org/#/collections) , it takes you to the next page but the browser in Firefox and Chrome (didn't try beyond that) keeps you at the bottom of the page. The focus should be set to the top so you can scroll down through the list

**Comment by edpaget** [comment]
We should change this to an infinite scroll thing anyway along with the project page.

**Comment by DarrenMcRoy** [comment]
I approve of infinite-scroll.

**Comment by eatyourgreens** [comment]
Not a big fan of infinite scroll myself. Nomensa have [a good discussion of the pros and cons] (http://www.nomensa.com/blog/2015/infinite-scrolling-probably-not-good-idea-your-website).
It tends to bury content that is several pages in, since noone ever scrolls down that far to find it.

**Comment by DarrenMcRoy** [comment]
Well, hopefully both the Projects and Collections page will soon have improved looks and sorting mechanisms than the current firehose, yes?

**Comment by mschwamb** [comment]
As someone who lives in Asia, if infinite scroll increases the download time, I'd suggest maybe not going that route. It already takes a noticeable bit of time for all the previews of the subjects and images to download for me.. Not asking for that to be shortened (it's a consequence on a lot of US based websites of being hosted on the Virgina farm), but if one option would increase the download time versus another for those far from the farm then maybe it's worth picking the shorter download speed

**Comment by mschwamb** [comment]
looks like this was recently fixed. Or it's working for me  in Firefox now that the pagination fully works in collections. so closing
