### ISSUE TITLE
user info and other formatting change/removed on preview of collections in collections tab after you move from the first page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1286]
when you move pages in the collections tab the username gets removed - it shows if you got to https://www.zooniverse.org/#/collections but then if you move around on the different pages that bit disappears

![screen shot 2015-07-30 at 7 51 13 pm](https://cloud.githubusercontent.com/assets/753325/8982521/edda7ff0-36f4-11e5-8bfc-83e80499d815.png)

moved to page 2 

![screen shot 2015-07-30 at 7 51 24 pm](https://cloud.githubusercontent.com/assets/753325/8982504/a085f9be-36f4-11e5-8b55-de2a324f03cb.png)

moved back to page 1

![screen shot 2015-07-30 at 7 51 33 pm](https://cloud.githubusercontent.com/assets/753325/8982508/af698bc6-36f4-11e5-989e-c89d02be4882.png)

**Comment by mschwamb** [comment]
Now it looks like the user info has completely disappeared. First few collections on the collections tab 

![214987ee-5eb1-11e5-8fff-fe2b3df4e25d](https://cloud.githubusercontent.com/assets/753325/10115051/1b01b324-642f-11e5-86df-4c98895917e9.png)

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
