### ISSUE TITLE
No one can post on Talk on a subjects page from the classification interface getting different errors in different browsers

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1299]
@aweiksnar and @chrissnyder  -  wanted to let you know about this. It looks like it was working earlier today. 

Just saw this on P4T  from a volunteer

'BUG - Can't post Comments for Subjects. After pushing 'Add your Comment' button get 'e is undefined' in red at bottom left of screen. Am using Windows 7 Starter and Firefox. I'd also signed out and signed in again to make sure.' 

I can repeat it on two browsers with a different OS

Mac Chrome I see 'Cannot read property 'id' of undefined'

In firefox on mac  I get 'e is undefined'

None of my posts are showing from the Notes page. But I can post on other the discussion boards. 

Also if you post the note to not the notes board then it does successfully post. But the default to Notes is not working.

**Comment by mschwamb** [comment]
If it helps. Earliest report of this is 12pm my time in Taiwan 

https://www.zooniverse.org/#/projects/mschwamb/mschwamb/planet-four-terrains/talk/8/120?page=4&comment=3292

**Comment by mschwamb** [comment]
Weird the link doesn't work even though that's what Talk spits out when I hit link. You can find the usernames and the posts [here](https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/8/120?page=4)

**Comment by camallen** [comment]
@mschwamb just remove the duplicate mschwamb link, we're working on a fix.

**Comment by mschwamb** [comment]
@camallen thanks

**Comment by mschwamb** [comment]
Thanks @edpaget @eatyourgreens and @camallen
