### ISSUE TITLE
metadata not showing in Kitteh Zoo

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1300]
The subject metadata for Kitteh Zoo is not showing, either on the [subject uploader/status page](https://www.zooniverse.org/#/lab/4/subject-set/6) or in the classification interface.

It seems to be showing fine on other projects, so is there just something weird about Kitteh Zoo?

It's important that the metadata show because that's where the required attributions are (all the photos are Creative Commons and require attribution).

**Comment by eatyourgreens** [comment]
Just had a quick look at this. It's trying to parse the metadata as markdown and dying with `state.src.replace is not a function` on the `subject_id` field.
