### ISSUE TITLE
Volunteers reporting Error: Access Token has expired  while classifying and posting on Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1318]
Not sure if this is just a windows thing. I haven't been able to replicate it. Two volunteers say they get this issue where they were classifying for awhile and posting on Talk and then they get a 'Error: Access Token has expired.' Then they can't do anything, and they say that logging out and logging back in fixes the issue.

Configurations that have experienced this:

Widows Vista with Google Chrome (Version 44.0.2403.125 m)
Windows 7 Starter and Firefox.

https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/8/120?comment=3385
https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/8/120?comment=3414

**Comment by mschwamb** [comment]
I was able to replicated it or at least it just happened for me.  I've had the page open all day in a tab not doing anything in Talk window. It still says I'm logged in and everything. But posting throws the error.  Reloading the page sorted the issue. The behavior doesn't happen in Talk 2.0 but I'm not sure if it's something that is changeable in this version

**Comment by edpaget** [comment]
Yeah the tokens you gets have a limited lifetime, we need to put something in place to reload them when that error occurs (or change the lifetime for the Panoptes-Front-End page).

**Comment by camallen** [comment]
There's a token [refresh call](https://github.com/zooniverse/Panoptes-Front-End/blob/3006a951dd7ae7d0247c5af5ecab2197de7b4159/app/api/auth.coffee#L65) that may not be getting scheduled properly..

**Comment by DarrenMcRoy** [comment]
A couple of people [commenting about "tokens" here as well](https://www.zooniverse.org/#/projects/vrooje/galaxy-zoo-bar-lengths/talk/20/1698?comment=3572).

**Comment by chrissnyder** [comment]
Consolidating discussion to https://github.com/zooniverse/Panoptes/issues/694
