### ISSUE TITLE
About us pages text has become small and hard to read

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1328]
I noticed the about us pages text has gotten really small and oddly formatted at least in OS X Firefox and Chrome. The Contact us page has some strange line formatting

![screen shot 2015-08-05 at 4 44 00 am](https://cloud.githubusercontent.com/assets/753325/9072274/ccdd7ab4-3b2c-11e5-9b8e-403546a6ce6d.png)

![screen shot 2015-08-05 at 4 44 33 am](https://cloud.githubusercontent.com/assets/753325/9072286/d50e867e-3b2c-11e5-90f0-2adb264072fe.png)

**Comment by vrooje** [comment]
Looks the same as #1287 - not sure if this is best handled by @brian-c or someone else?
