### ISSUE TITLE
"Not allowed to create this role" when adding a collaborator

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#1331]
I just tried to add @vvh to AnnoTate as a collaborator, and got the error `Error: not allowed to create this Role` in the front end.

The console had a 401 error for loading a resource from https://talk.zooniverse.org/roles, and a 400 error from https://panoptes.zooniverse.org/api/project_roles

After refreshing, it looks like she had actually been added.

**Comment by rogerhutchings** [comment]
Second attempt, trying to add @camallen:

![screen shot 2015-08-05 at 10 01 18](https://cloud.githubusercontent.com/assets/2725841/9082147/ddbe5858-3b59-11e5-903f-66befe61d978.png)

**Comment by chrissnyder** [comment]
I haven't been able to replicate this in awhile. Something we fixed along the way? Anyone else still getting this?

**Comment by edpaget** [comment]
This can still happen in certain circumstances.

**Comment by chrissnyder** [comment]
Roger that, let's get it fixed then.

**Comment by edpaget** [comment]
@chrissnyder its not something that's easy to fix. The problem is how roles are divided between Talk and Panoptes. When you create a project in Panoptes, a background worker is set to create the related 'admin' Talk role for the project's owner. If they visit the roles page before that role is created then they will get the above error when it tries to create the corresponding talk roles.

**Comment by edpaget** [comment]
Though thinking about it further the page could just check to see if the talk 'admin' role has been created and be disabled until it happens.

**Comment by parrish** [comment]
What's the delay like on the background job running?  Should be only a *really* brief window when this is possible.

**Comment by edpaget** [comment]
I think most of the problems where times when sidekiq was enormously busy. It really shouldn't (and doesn't seem to) happen all that often.

**Comment by aliburchard** [comment]
I still get this a lot (and worth asking @vrooje maybe @mrniaboc @mkosmala). It seems to stem from 2 things: 1) a long delay in the system offering up potential matches when you type in a username, and 2) the system not letting you add someone when you've typed in their exact username. You have to select one of the options from the dropdown menu that the system offers up. You can't just type in someone's exact username and have it accept what you've typed into the search bar (if that makes any sense?).

**Comment by mrniaboc** [comment]
Yeah, this is a really problem when adding people with short usernames.
Since it is most likely that people make their usernames as short as
possible in many cases, we should really see about fixing this.

**Comment by edpaget** [comment]
That seems like an entirely different problem.

**Comment by DarrenMcRoy** [comment]
Well there's definitely something weird about short usernames (for instance, mine). Didn't we run into that before, @edpaget ?

**Comment by edpaget** [comment]
Yes https://github.com/zooniverse/Panoptes/issues/1230

As far as I can tell there are two issues here: 

* Delay in setting up the proper permissions for talk roles
* Users expecting to be able to set roles by only typing a username into the search without selecting a user.

**Comment by chrissnyder** [comment]
Correct. The issue being discussed is just the delay in setting up permissions. The username search UI is something else entirely.

**Comment by mrniaboc** [comment]
Sorry guys. I misread the situation.

**Comment by parrish** [comment]
So what's the verdict?  Just check if the role exists when rendering the UI?  We could add a message like "Your project account status is still being setup" or something like that.

**Comment by chrissnyder** [comment]
Yes, that seems like a good solution to me.
