### ISSUE TITLE
Record what people have read

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Panoptes-Front-End#1335]
For all sorts of research reasons it would be good to record what threads people have clicked on to read, rather than just what they've commented on.

**Comment by parrish** [comment]
I'm not opposed to logging it, but providing read-tracking in the UI for all comments/discussions/etc. is not a healthy feature to support.

If we're happy just leaving it at that, then I'll add it.

**Comment by alexbfree** [comment]
this seems like a good candidate for Geordi logging. @amyrebecca we should add this to the list of things to log in PFE when we integrate Geordi
