### ISSUE TITLE
Not all thumbnails are generating on the Notes board

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1338]
Looking through the Planet Four: Terrains Notes and the Whales as Individuals board, not all thumbnails are generating:

https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/29
https://www.zooniverse.org/#/projects/tedcheese/whales-as-individuals/talk/31

This is true for all live projects, actually.

There are a few subjects that just aren't generating thumbnails properly. Any idea?

EDIT: It's particularly bad on Season Spotter projects.

https://www.zooniverse.org/#/projects/kosmala/season-spotter-questions/talk/62?page=1
https://www.zooniverse.org/#/projects/kosmala/season-spotter-image-marking/talk/66

**Comment by mschwamb** [comment]
Does it have something to do with replies. That once someone else has replied on that thread the thumbnail then disappears? It all the cases on Planet Four is appears to be when someone has replied/posted in the notes thread beyond the initial post that created that the thread.

**Comment by mschwamb** [comment]
@aweiksnar Following the above, I was able to replicate the issue. It's something to do with replies. Once a reply/posting after the initial creation of the Talk notes post. Once a second post comes in, the update on the threads page removes the thumbnail.

**Comment by vrooje** [comment]
Same on GZ Bars - only the Notes threads with 1 post have thumbnails.

**Comment by mschwamb** [comment]
The patch for this looks great. I'm seeing thumbnails with replies.

**Comment by aweiksnar** [comment]
Great! thanks for testing @mschwamb
