### ISSUE TITLE
How to we switch a project from beta_requested to beta_approved

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#1341]
When we do a review of a beta_requested project and decide it's legit, there should be a way for people like myself, @chrislintott, and @aliburchard to click a button and switch it to beta_approved.

Also, do we have a beta_rejected flag?

**Comment by edpaget** [comment]
I think this brings up a point about administor functions. Do we want them to be integrated into the main site, or some sort of separate zoo-operations/administration page.

**Comment by chrissnyder** [comment]
Fixed.
