### ISSUE TITLE
Ability to filter collections

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1343]
Maybe this is already captured somewhere as a future requirement, but just in case:

The Collections page is hard to use.
Ideally I think there should be some tabs or buttons to allow you to switch between your own collections, popular collections, recent collections.... And also perhaps a dropdown to filter by project.

**Comment by mschwamb** [comment]
related to  #1042 which suggests  filters for different projects

**Comment by parrish** [comment]
Mostly implemented
