### ISSUE TITLE
should we replace the "summary of classification" page?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1345]
I'm posing it as a question for discussion purposes, but I think we *should* at some point replace or change the current behavior of displaying a summary of what a classifier has just input immediately after they click "Done".

While I like the idea of communicating *you've provided this info, thank you*, I think it quickly becomes wasted space (most people stop reading it), and can also be frustrating for users who might like to change a classification, but see the summary at the exact moment the summary can no longer help them. (I'm not sure whether this might drive people away if they lack confidence.) We've seen this question many times before #1342 was posted, but that issue makes it clear it will continue to be an FAQ for new projects too.

I propose the following as a first pass at an alternative:

  - Instead of the summary, we display a "thanks" message, and
    - the latest (or most upvoted, or whatever) comments on the subject, if any exist
    - "click 'Talk' to join the (start a) discussion, or click 'Next' to keep classifying."
  - If we think it's important to give users an overview of what they've done so far, we add a "preview" button near the favorite/metadata buttons that shows the classification summary to that point. That way a user can check it just before clicking "Done" and change it if they wish.

Thoughts?

**Comment by AdrianEvans** [comment]
My proposal would be that the page stays but it serves a different function. The national geo ghengis khan did something nice. After each subject they classified they got to see the pooled results of all previous classifications done on that subject by other users. This was based on some research about learning behavior

"After completing a maximum of five tags for a given image tile, and before proceeding to the next randomly selected image tile, participants are shown all tags for that geospatial location previously generated by preceding participants. This provides incremental points of reference to evaluate one's own assessment against that of other peer participants (Fig. 1b). The timing of the anonymous feedback cues was chosen carefully, being presented only after one's tags were committed. This was to avoid the unstable nature of social influence observed in other online markets [15], while still taking advantage of what Krumme et al. [16] recently observed as the informational role cues can play in influencing ones behavior."

15. Salganik MJ, Dodds PS, Watts DJ (2006) Experimental study of inequality and unpredictability in an artificial cultural market. science 311:854–856. doi: 10.1126/science.1121066

16. Krumme C, Cebrian M, Pickard G, Pentland S (2012) Quantifying social influence in an online cultural market. PloS one 7:e33785. doi: 10.1371/journal.pone.0033785

**Comment by chrissnyder** [comment]
Couple other points of consideration:

- @drphilmarshall's #383 need for speed style interface, which is heavily in favor of reducing the amount of busy work necessary to jump from subject to subject. This style also paid dividends on chimpandsee.org, where the initial filter takes just one click to move on.
- @DarrenMcRoy consistently passes along feedback from volunteers that they would really like to have some assurance they are doing the task right. This is born out in surveys as well that @mrniaboc might have data on. This solution to this typically is having a set of expertly pre-classified subjects available for viewing, but might also be showing previous users classifications as well.

**Comment by aliburchard** [comment]
I'm totally (totally totally) in favor of replacing the current content or getting rid of this stage altogether. I like all of the above ideas more than the current display.  I also *really* like the idea of skipping it altogether to increase the sort of addictive rhythm of classification, but also realize that we need (or typically want) to give folks a chance to go to "talk" after every classification.

**Comment by chrislintott** [comment]
Another vote for making this page more interesting. 

Chris

**Comment by DarrenMcRoy** [comment]
The proposed "interventions" doc that I wrote for @trouille opens the question of perhaps using summary pages for a variety of interventions (Planet Hunters-style) rather than using pop-ups that directly interrupt the classification process. We should discuss this further when we have that chat!

**Comment by AdrianEvans** [comment]
@chrissnyder re comment about speed style interface - perhaps the feedback only happens for the first few images to help the learning curve.

**Comment by chrissnyder** [comment]
Closing for cleanliness, but we'll refer back to this issue when we go to revamping the classification screen.
