### ISSUE TITLE
repeats across pages in the project list

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1348]
Looking through the project list in Admin Mode, I'm seeing multiple projects repeating on different pages. I don't think they're duplicates with different project IDs; I saw Seafloor Explorer and @vvh's Pugs project a few times, for example. It made me think the list was being re-sorted each time I clicked to a new page of the list.

**Comment by chrissnyder** [comment]
I seem to recall this being an issue that was taken care of, but I can't find the commit on Panoptes.

Looks alright to me flipping through project pages. Same with you @vrooje ?

**Comment by vrooje** [comment]
Same with me; no repeats after about 10 pages. Will close and we can reopen if it pops back up...
