### ISSUE TITLE
Problems loading Talk, Error: 0

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1352]
Still getting error 0 while trying to load the Talk.

![](https://lh3.googleusercontent.com/-Pw7X7Q5Op4M/VcPGeCDuHOI/AAAAAAAAISA/YTs3pqgIzDY/s0-Ic42/Screenshot_2015-08-06_22-37-11.png)

![](https://lh3.googleusercontent.com/-s07QGnQ7Z-U/VcPGesmvvXI/AAAAAAAAISE/1ZorzltMkkA/s0-Ic42/Screenshot_2015-08-06_22-37-54.png)

**Comment by edpaget** [comment]
Looks like it's back up.

**Comment by yshish** [comment]
It's back with much much more errors.
