### ISSUE TITLE
collection subject duplication bug

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1355]
Saw this on Planet Four: Terrains talk from a Window 7 Firefox user. I can't seem to replicate the issue (also pagination issue is reported in #1284 :

PRIVATE COLLECTION BUG.
Hi Meg,
I'm having trouble building up my private collection. I think I'm doing my side correctly, i.e with the first subject, let's say it's a spider, I open the 'Add Subject to Collection', tick Private, write Spider in the 'Or Create a new Collection' box and click the 'Add Collection' button. Then say I come accross a crater that I like so I do the same and write Crater in the 'Or Create a new Collection' box. Now I get another nice spider image so I again open 'Add Subject to Collection' but this time, because I've already started a "Spider" collection I click the triangle in the 'Collection Name' box and see 2 names, Spider and Crater, so I click Spider then 'Add'. I've created numerous Collections with several subjects in each.
So now I want to look at my collection of, let's say, Spiders. I hold my cursor over my name, top right, and click 'Collections' in the drop down menu. A window comes up with rayperry Collections and there are my 10 different collection, so I click on 'Spider' and expect to see the 2 subjects which I saved into my 'Spider' collection BUT, now here's the BUG, the programe spews out 2 pages of collected subject, subjects from my other nine collections but I can't see any Spider images. I go to the bottom of the page and click on 'next' , to see if the image is on the next page but get no response.
I'm using Windows 7 Starter with Firefox.

Rgds
Ray
The BUG is that the programme is not sorting

**Comment by mschwamb** [comment]
I've encountered another volunteer claiming that  when they add an image to a collection from Classify then it also gets added to all of their collections, so I now have lots of duplicates. I'm not sure if there is a display issue or an issue with adding the image to a collection. I haven't been able to confidently repeat it, but I don't have many collections. These two volunteers do have 2 or more non-favorite  collections from my understanding.

**Comment by mschwamb** [comment]
I thought I'd pass this along, what I've learned over the past several week. This bug appears to impact all collections.  I haven't been able to replicate this, but the two volunteers that have are pretty well versed in how to the new platform works so I take their word for it. One of them sent me a detailed explanation of how they can recreate this bug. You can find that description [here](https://dl.dropboxusercontent.com/u/56971802/Collections%20Bug%20ex%20PlanetFourTerrains.pdf)

At least these two volunteers on Planet Four: Terrains  have stopped making collections, because they said they were having significant difficult find subjects that put into specific collections or it was difficult to peruse with the duplicate subjects from other collections showing up.

**Comment by mschwamb** [comment]
Another volunteer with a different browser on Planet Four: Terrains finds the same issue. [Here's](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/8/9413/?comment=18553) the Talk link to the new report. Perhaps it's the api?

**Comment by saschaishikawa** [comment]
Tried replicating this for 20+ subjects on IE11 running Win7. Created 3 separate collections, but haven't found anything.

**Comment by mschwamb** [comment]
This might be the view issue https://github.com/zooniverse/Panoptes/issues/1314

**Comment by mschwamb** [comment]
I definitely see a lot of collections from the same user where the same front image is repeating . Maybe addressing the view api issue will sort this. I can definitely message or point you to the three volunteers who reported this, if that would be helpful.

**Comment by chrissnyder** [comment]
@mschwamb That'd be great if you could put Sascha in touch with them.

**Comment by mschwamb** [comment]
@saschaishikawa what's your Zooniverse username again, so I can key you into the discussion where I'm @-ing the three users so you can either email them or they can private message you?

**Comment by mschwamb** [comment]
@saschaishikawa you've got emails connecting you to two volunteers who experienced this bug

**Comment by camallen** [comment]
pretty sure this will be closed by #1886 - that was adding the subject to all found collections in the collection search field not just the selected ones.

**Comment by mschwamb** [comment]
Yeah  #1886  has fixed it. I've confirmed with one of the volunteers who reported this.
