### ISSUE TITLE
Favoriting not working in the classification interface for only select projects

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1356]
Hitting the favorite button in the interface, doesn't seem to do anything anymore. Getting error Error: Could not find collection with id='378' in the console - Related to  #1058

**Comment by mschwamb** [comment]
Interestingly it's not all projects. I can't favorite on Planet Four: Terrains, but had no trouble with WW, Season Spotters, or GZ: Bars

**Comment by mschwamb** [comment]
So I now get the heart filled in pink. But I could not find the subject in my favorites collections

![screen shot 2015-08-30 at 9 13 30 am](https://cloud.githubusercontent.com/assets/753325/9565271/c24a3d6a-4ef7-11e5-8e33-dee16b896d7c.png)

I added you both to the collection I would believe the image should be in

**Comment by edpaget** [comment]
This looks like an API issue if you visit: https://www.zooniverse.org/#/collections/mschwamb/favorites-17?page=1&page_size=30 you should see the subject as the last one on the list. Somethings wrong with how the response is being paged. I've opena  separate issue:

**Comment by mschwamb** [comment]
Thanks @edpaget . Yeah my last page doesn't show that image (or any page), but I can see the subject from your link.
