### ISSUE TITLE
WW: Can't play/display image sequence  from the Talk

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1358]
When I want to play the image sequence in the Talk, nothing happens. I can't even display them one by one: https://www.zooniverse.org/#/projects/aliburchard/wildebeest-watch/talk/30/1496?comment=3681

(Sorry if repeating, I haven't found it among the issues)

**Comment by eatyourgreens** [comment]
Are all the photos for that subject the same? @aliburchard 
https://panoptes-uploads.zooniverse.org/production/subject_location/00c83969-37cc-48ef-9370-769a3232b729.jpeg
https://panoptes-uploads.zooniverse.org/production/subject_location/271bdb3f-460f-462b-9099-f5b71007eb11.jpeg

**Comment by yshish** [comment]
Oh, it would explain why it seems not to be working. I've just tried another image sequence and it is working without troubles:]

**Comment by aliburchard** [comment]
Hmmm now I've gotta figure out why the subject has three identical images!
