### ISSUE TITLE
How could we support custom stylesheets per project ID on PFE? (and maybe custom JS bindings too?)

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1360]
Just had a brief discussion with @eatyourgreens and @camallen , thought we should start a thread on this.

For projects such as Snapshot Serengeti, there is a need to maintain a branded site identity once the project moves to Panoptes - and we can expect to have other clients in future that want a custom styled site.

One of the things that will be important is keeping the user's experience within one site - so that they don't have to reload a whole other site when switching between talk & classify, for example. For this reason it seems to make sense to have the application exist within the zooniverse.org server (rather than a separate server running a subset of PFE code).

It seems to be that the obvious way to do this is to have something on the server side, around the point where HTML is rendered, which in pseudocode does something like this:

```
if 'custom-css/<this-project-id>.css' exists
  render standard panoptes stylesheet first
  render "<link href="custom-css/<this-project-id>.css" rel="stylesheet">
else
  render standard panoptes stylesheet only
end if
```

A similar approach could be used with JS files too.

I haven't yet learnt much about what templating infrastructure we have to support something like this, but I gather that react doesn't support controller-view templating in the usual way.

I'm interested to start the discussion and also to learn a bit more about what we do/don't have in terms of ability to support templating or template variation per project.

Copying in @edpaget and @brian-c who I am sure would be interested to contribute to this discussion...

**Comment by brian-c** [comment]
I'm opposed to project-specific code in the repo. If a team can't build what they need with our tools, they're free to build a custom project.

**Comment by camallen** [comment]
@brian-c - could it be done technically? I'd be interested in understanding a solution irrespective of actually deploying it.

**Comment by aweiksnar** [comment]
Related discussion in #295 too

**Comment by brian-c** [comment]
Yeah, I think we could just add something like `{<link type="style" href={project.config.css_file} /> if project.config.css_file?}`.

**Comment by chrissnyder** [comment]
I'm with Brian that I don't think project-specific code has any place in this repo. And the more I think about it, the less I'm convinced this really needs to exist in the first place. 

Mostly I'm struggling to find a use-case. Why would we build a custom project that can be built using the project builder? Isn't the entire point of the builder is so we don't have to build those types of projects anymore?

If and when we need to add on functionality, features flags can get us pretty far. I'd need to see a scenario where we are making incremental improvements to the classifier that couldn't be done using features flags.

And when a project comes along that simply cannot be built using the standard toolset, and requires too much customization to be realistically built into PFE, then like Brian said, we are free to build a custom project.

All that said, there's likely a lot work we can do to make individual modules re-useable across even custom projects, as there's little reason why a classification model can't be abstracted out and used by both projects and PFE. https://github.com/zooniverse-ui is the beginnings of this. And maybe one day our code is modular enough to extract the entire project page component itself, which would the original problem anyway.

**Comment by alexbfree** [comment]
I can see the point about not wanting to support project-specific code for custom JavaScript - after all, it could get messy. But what is the harm in supporting custom CSS? A lot of platforms do this. For example, mailchimp, wordpress.com. Also this doesn't have to be something in the repo, just a "hook" or plugin point and a text box in the UI or upload button where people can attach their own CSS....

**Comment by brian-c** [comment]
- Our own CSS still needs a lot of work.

- As we improve our stuff, we will change something that someone depends on.

- It'd be easy to totally break the classifier and not realize it. There's some delicate stuff in there that needs to line up, and its not possible to keep people from overriding anything thanks to `!important`.

- MySpace?

**Comment by alexbfree** [comment]
- if they break it, it's their fault? 
- First step of any troubleshooter would say "Disable your custom CSS; did your problem go away....?" This is fairly standard approach for things like Wordpress (disable all your plugins and turn them on one by one) and even Google Chrome (do you still have a problem when all extensions are disabled).
- I don't think "users might break it" is a good enough reason to have a uniform look and feel for all Zooniverse projects from here on in. A platform should embrace creativity, and allow people some flexibility to innovate. That's one place great ideas can come from....

**Comment by chrislintott** [comment]
‘Users might break it’ is a valid reason not to allow something if we’re not able to provide support for people who have broken it and don’t understand why it’s broken…

**Comment by alexbfree** [comment]
Like I said, step 1 of support would be "turn off your custom theme". If fixed, then *it's not our problem" would be our next response....

Also @edpaget it's all very well saying they can build/run their own project if they want to customize, but that requires a lot more development skill than just having a web designer.

**Comment by edpaget** [comment]
@alexbfree yes, but I don't see why we should support people custom skinning the site? I said if someone _really_ wants to make a custom skinned interface they can. They could teach themselves how to modify our code (which is publicly available) or pay someone to do it for them. I don't see why we should support anything beyond that since it will be extra development effort on our part; both to create it and to make sure we don't break custom stylesheets once they're introduced.

**Comment by chrissnyder** [comment]
Unlikely to happen from our side. Highly unlikely to happen for project builders. Maybe we'll get to themeing one day.

**Comment by duhaime** [comment]
@eatyourgreens @srallen @mcbouslog @rogerhutchings @camallen I wanted to pick this thread up for a moment if that'd be alright!

What if users could upload a custom CSS file to the Panoptes backend, and that data were delivered on one of the project-specific API routes (say `/api/projects/id`) and conditionally loaded into the client pre-render?

If that behavior were supported, users who were patient could keep tinkering with their CSS and re-saving it to the supported Zooniverse server (e.g.), then refreshing until things looked good.

This kind of flexibility would be really tremendous for organizations that want to make some small styling changes without hosting a custom Panoptes stack...

Would your team have any interest in entertaining client and server pull requests along these lines?

**Comment by srallen** [comment]
@duhaime Thank you for your suggestion. Currently, Panoptes-Front-End is in a legacy state, meaning we are only doing bug and security patch fixes for it. Our current effort is in a new app that will support the main Zooniverse site. With this rebuild, we are using CSS in JS styled-components which support theming. At the moment, we have implemented a dark theme. Any future additional themes will be built by us for several reasons, including compliance with government accessibility standards.

Supporting custom CSS and possibly JS requires a development effort and maintenance that we do not have the capacity to support. In addition, it open us open to security vulnerabilities. As noted previously, though, it is open source and Panoptes is an API, so if you have a project that has strict requirements on styling, you're welcome to fork the project and/or build your own custom client app.

**Comment by duhaime** [comment]
@srallen many thanks for your fast reply. Just to check, can one run a custom client and store the data in the main, Zooniverse-hosted Panoptes server instance? If so, that'd be of great interest to the team I'm working with...

**Comment by srallen** [comment]
Yes, since Panoptes is a REST API, you can build new clients to work with it. We have built custom client apps for specific projects such as: https://github.com/zooniverse/anti-slavery-manuscripts
And we're aware of other teams making forks of PFE itself. 

However, it should be noted that we have conventions for annotation formats that Panoptes as an API doesn't validate on, so if you do build your own client app and POST annotations to Panoptes, we cannot guarantee that everything will work if you deviate from convention, like downstream aggregation.

**Comment by duhaime** [comment]
Awesome, thanks very much for your response. We may end up exploring this option...

**Comment by camallen** [comment]
> @srallen many thanks for your fast reply. Just to check, can one run a custom client and store the data in the main, Zooniverse-hosted Panoptes server instance? If so, that'd be of great interest to the team I'm working with...

If you do go down this route, please do let us know your plans and implementation details ahead of time.

**Comment by duhaime** [comment]
@camallen thanks for the heads up. I'll bring this information back to the folks at Yale's DHLab and will follow up if we want a custom front-end...
