### ISSUE TITLE
survey task questions "require" option not working

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1362]
I'm building Gorongosa at https://www.zooniverse.org/survey-editor/#/lab/593/workflow/338 and want to make two questions on the species viewer *not required*

I have indicated in the questions.csv that these should be optional by setting the "required" column value to "N", but the "identify" button is not available until these questions have been answered.

@brian-c is this missing a toggle of some sort?

**Comment by brian-c** [comment]
Fixed by ece7149e4c5dda0c21ad8fb2a543182da1ffc142.
