### ISSUE TITLE
Having a third tab on the collections page for collections shared with you that you don't own

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1367]
A volunteer is having trouble with collections so he added me as a collaborator and I'm now trying to find it. It would be nice if like google docs, there could be the my collections section and then separate tab for collections shared with you so it's easy to find them. Otherwise one needs to have the link or search through all the collections on the Zooniverse collection page

**Comment by mschwamb** [comment]
The collection was private, so the only way I can access is going to the person's collections list in their profile. I think an area for collections shared with you would be extremely helpful

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
