### ISSUE TITLE
Adding mouseover description of info, favorite, and collect buttons on Talk

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1368]
The icon button on the post editor have mouseover descriptions. The favorite, info, and collection buttons below the subject image look similar in style but don't have mouseover descriptions. At least on Talk I think it would be helpful if they had mouseovers like the rest of the button icons on Talk do. 

![screen shot 2015-08-10 at 8 28 50 am](https://cloud.githubusercontent.com/assets/753325/9157697/05845da4-3f3a-11e5-9338-c4387a23d508.png)

**Comment by vrooje** [comment]
I agree it would be useful if these had mouseovers.
