### ISSUE TITLE
Making the notes subboard activated on Talk creation rather than owner having to hit the button?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1370]
Currently on Talk, if you build new project you have to go into Talk and activate the notes board by hitting the button 'Activate the Talk Subject Comments Board' otherwise all the side discussions go into the other boards created. Should this now be default behavior instead of requiring the project owner to hit that button?

**Comment by parrish** [comment]
IMO, I'd say this step should be part of the project builder.

**Comment by vrooje** [comment]
In Kitteh Zoo the board exists and the pinned post on it says "First Step: Create This Board" (or similar) with instructions on how to do it, but that's buried pretty far in the site and I'm not surprised not everyone is seeing it.

**Comment by parrish** [comment]
Fair point (I hadn't noticed it).  Maybe we could default it and then add a step later to rename it?

**Comment by mschwamb** [comment]
@vrooje - I hadn't checked the boards of Kitteh Zoo Talk. It's not listed as a step in the [How To)[https://www.zooniverse.org/#/lab-how-to] to make Kitteh Zoo. I think people might miss if they don't check out the Talk (especially for people that don't know what it is).  Maybe that could be added to the text. I made a separate issue for it See  #1369

**Comment by aweiksnar** [comment]
Closing this up since it's now part of the project builder via #1464
