### ISSUE TITLE
All projects not showing in email preferences

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#1384]
When I look at my email settings, I can only see options for about half of all the projects I've taken part in. There is also a weird error about a project id that doesn't seem to retrieve a real project.

![image](https://cloud.githubusercontent.com/assets/5321335/9202233/c9c714b8-4048-11e5-90b9-77cc7667e6c3.png)

**Comment by DarrenMcRoy** [comment]
I think that it's like the stats: it only currently retrieves a project that you've classified on since the migration.

**Comment by DarrenMcRoy** [comment]
(Related to #1028 then?)

**Comment by camallen** [comment]
Sounds like it's only getting the first page of preferences for grant. The other one will be a deleted project, will have to do some work on how we return these from the api.

**Comment by mschwamb** [comment]
Related to this -  I have the button checked to 'Get email updates from the Projects you classify on' but Planet Four is showing up as unchecked for me (so it would look like I'm not signed up for newsletters even though I want them). If you have that checked shouldn't it by default check all of the boxes below in the Project email preferences? (let me know if I should open a separate ticket)

![screen shot 2015-08-12 at 2 43 06 am](https://cloud.githubusercontent.com/assets/753325/9206759/4b197dc8-409c-11e5-8a6b-a334a2a9acce.png)

**Comment by DarrenMcRoy** [comment]
@mschwamb I covered something similar here: https://github.com/zooniverse/Panoptes/issues/1247 -- not that I'd expect you to have found it. Not sure if it's the right repo; it seemed like a possible back-end issue?

**Comment by vrooje** [comment]
Just to add I'm seeing this too... missing a bunch of projects (and the new Panoptes projects are unchecked).

**Comment by mschwamb** [comment]
I decided not to open a new ticket, but use this one. For me all the Panoptes projects are now missing from the list. 

![screen shot 2015-08-30 at 7 11 54 am](https://cloud.githubusercontent.com/assets/753325/9564852/842e9744-4ee6-11e5-83d8-3447ae3cb0c5.png)

**Comment by edpaget** [comment]
Yes this is two issues. One is that the migration to import email preferences/classification counts failed ~3/4 of the way there and I can't debug the failure until I am back in the adler. 

The other issue is that the list of projects needs to be paged somehow since there are more project than are retrieved at once.

**Comment by chrissnyder** [comment]
Migration looks to be finished if my list is any indication. Pagination is not.

**Comment by edpaget** [comment]
Yeah we could just request 50 project preferences for now, and worry about pagination later.

**Comment by srallen** [comment]
Added pagination in #1693.
