### ISSUE TITLE
moderation: weirdness with record of deleted posts

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1385]
In testing the delete functionality on Talk moderator controls, I noticed that every time you delete a post the moderation controls link to a completely different post afterward (perhaps because the old post is gone?).

Before:

![screen shot 2015-08-11 at 17 56 32](https://cloud.githubusercontent.com/assets/2357126/9204069/d6e14272-4052-11e5-8d78-9da751a3759d.jpg)

After (the above deleted post, and a different one, also on the GZ Bar Lengths boards; I just didn't get a screenshot of it):

![screen shot 2015-08-11 at 17 57 16](https://cloud.githubusercontent.com/assets/2357126/9204082/e8d73716-4052-11e5-83aa-a75acfc42841.jpg)

My report comment is still the same, but the post linked to is on a different board for a different project.

**Comment by parrish** [comment]
I'm not sure, I can't seem to reproduce it.

@aweiksnar is it possible for that view to somehow drop the moderation section from the request?

**Comment by aweiksnar** [comment]
@parrish Just from the destroy?

**Comment by parrish** [comment]
After the destroy, it requests /moderations again.  I can't imagine why it would be displaying reported comments from other sections unless that param got dropped somehow.

**Comment by aweiksnar** [comment]
Ah good call, It does call that from `componentWillReceiveProps`, so perhaps it loses `@props.section` there somehow. I'll see if I can clean that up, but also am having a hard time reproducing

**Comment by parrish** [comment]
I do consistently see a warning for child keys:

`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of PromiseRenderer`

and once (can't reproduce) I got a setState during render invariant violation.

**Comment by vrooje** [comment]
Is there anything I should do to try and help reproduce this? I've asked the GZ Bars mods whether they can. I've so far done it once for a post on a mods-only board, and once for a public post.

**Comment by vrooje** [comment]
Update: One of our mods has deleted a post as well and when I go to moderation controls I see *that* post linking to the same P4T post as the others. (Not sure what she sees.)

**Comment by chrissnyder** [comment]
Still an issue?

**Comment by vrooje** [comment]
Still an issue for me... the screenshots above are still what shows up when I check deleted posts on GZ Bar Lengths. Should I try it again with a new test thread?

**Comment by chrissnyder** [comment]
If you would please. Might be a legacy thing on how reports were
saved/displayed at that time.

**Comment by parrish** [comment]
At least as far as I can tell, it seems to be working correctly.

**Comment by vrooje** [comment]
Alas.

First I did:

![screen shot 2015-10-12 at 16 53 04](https://cloud.githubusercontent.com/assets/2357126/10430909/148be2fa-7102-11e5-92cc-3488be826fde.jpg)

Then reported it: 

![screen shot 2015-10-12 at 16 53 48](https://cloud.githubusercontent.com/assets/2357126/10430908/148b7b4e-7102-11e5-800f-5c2abf7b9d75.jpg)

Then deleted it, and viewed the deleted tab:

![screen shot 2015-10-12 at 16 54 30](https://cloud.githubusercontent.com/assets/2357126/10430910/148c9cc2-7102-11e5-947a-71bc4ffce383.jpg)

**Comment by parrish** [comment]
I'm guessing that was the only comment in that discussion.  In which case, it's going to actually delete the comment and the discussion.

**Comment by parrish** [comment]
Also, there is a bug here.

<img width="763" alt="screen shot 2015-10-12 at 10 18 58 am" src="https://cloud.githubusercontent.com/assets/122990/10431458/c8fb0942-70ca-11e5-96fe-ef51a57af05a.png">


<img width="758" alt="screen shot 2015-10-12 at 10 19 30 am" src="https://cloud.githubusercontent.com/assets/122990/10431463/ce2b9364-70ca-11e5-8c90-a87d42b67e0f.png">

<img width="1003" alt="screen shot 2015-10-12 at 10 20 25 am" src="https://cloud.githubusercontent.com/assets/122990/10431478/e2548012-70ca-11e5-9260-4a8531fcbf01.png">


It appears the view is requesting `/comments/` and not displaying the deleted comment correctly.  I'll fix that.

**Comment by parrish** [comment]
PR in #1742

**Comment by vrooje** [comment]
Yes, sorry I didn't clarify that before. I feel like I also found this
before for a multi-comment discussion, but I haven't tested that recently.
Will do so and report back later.

**Comment by vrooje** [comment]
hurray!
