### ISSUE TITLE
Leave label highlighted for drawing tools

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#139]
When I select a drawing tool, it should stay "lit up" so I know which tool I'm drawing with. When I choose a different tool, the previous one should be un-highlighted and the new one highlighted. See Seafloor Explorer for an example of how this should look.

**Comment by chrissnyder** [comment]
Now that I've actually had a chance to play with the tools, isn't this how they work currently?

**Comment by mkosmala** [comment]
Yep. This has been done.
