### ISSUE TITLE
Closed moderator reports are not listed under the closed tab

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1395]
I ignored two reports, one a test and the other that looked like an accidental click for someone. They show up as dealt with and ignored on the All and Ignored tab, but they are missing from the Closed tab. To me it sounds likes all things dealt with would show in the Closed tab. If that's for listing all deleted posts, then I think a more descriptive title would be helpful for that tab.

**Comment by vrooje** [comment]
That's weird -- on GZ Bar Lengths I can see both ignored and deleted posts (including those affected by #1385) in the "Closed" tab.

**Comment by mschwamb** [comment]
Weird  - just checked again just in case something changed - I don't see anything in closed. No deleted posts though so that's a difference. Only ignored. 

![screen shot 2015-08-12 at 11 28 06 pm](https://cloud.githubusercontent.com/assets/753325/9228177/e9bfc9b6-4149-11e5-8bf5-db75e880758c.png)

**Comment by parrish** [comment]
Actually, that's intentional.  "Closed" is probably not the best label there -- it basically just means that the moderation target has been destroyed.  "Ignored" could be transitioned from ignored to closed, so it's presented separately.

I think this is just a different manifestation of #1385.

@aweiksnar: on closed moderations, the target will be null.  In those cases, it looks like a request is being made to /comments -- the first result of which is being displayed as the moderation target.

I'm not sure what we should be displaying for closed moderations since the target won't always exist.  Maybe we should hang onto an embedded copy of the deleted object or something?

**Comment by mschwamb** [comment]
'Deleted' would be better than 'Closed' for a tab title. Closed to me means it has been handled versus open which is in need of attention.

**Comment by aweiksnar** [comment]
Yeah, hopefully deleting comments will be an extreme case. Darren mentioned that if we need to make a case against a specific user they could be helpful to have as evidence, but perhaps we could display : `Deleted comment  _____ by _______ for  _____ reason there` as a record of that transaction.

Also up for reworking the sorting labels.

**Comment by mschwamb** [comment]
I can only comment on my experience. For the projects I've been involved in, the mods make the decisions on banning so that the science team is separate from that process though usually informed. Normally it's fine, but if it does need to go higher in the rare case such as someone appealing the banning or people trying to go around the ban or continuing outside of Talk it helps to be able to provide evidence that the mods acted reasonably and so that the Zooniverse team can catch up on what has been going on. I've had this happen in a  1 or 2 instances in the past 5 years where @chrislintott  had to get involved. It was helpful to be able to send conversations and posts. So if there is a way to save a copy of the reported post in case it's deleted by the author or deleted by a mod I think that would be useful if it's not too much work.

**Comment by vrooje** [comment]
While it certainly doesn't save any dev time (sadly), I agree with Meg here. There have in the past been situations where a record of deletions has been or would have been very useful, and they're often the extreme outliers where you actually do need evidence.

**Comment by parrish** [comment]
I've created an issue for this: zooniverse/Talk-Api#57

**Comment by mschwamb** [comment]
cool - that sorts the other stuff in this ticket  then. If y'all can change closed to 'deleted' I think that would make it much clearer and that would make it clear what you meant for that tab.
