### ISSUE TITLE
hashtags not showing up as hyperlinks anymore on Talk in any conversations or threads

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1397]
See https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/29/1871 
I'm not sure if they're being tabulated for the Talk main page side bar, but on Planet Four: Terrains talk hashtags are no long hyperlinks to a search of all subjects and conversations labeled that way

**Comment by aweiksnar** [comment]
Fixed in latest markdownz@1.0.4
