### ISSUE TITLE
Labeling Zooniverse project researchers on Zooniverse Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1400]
I'm finding it awkward if I post something on Zooniverse Talk, since on first glance it looks like a volunteer posted it. When I post something about my project on Zooniverse Talk or reply it doesn't look like it's coming from someone involved in a Zooniverse hosted project, especially to new volunteers viewing Zooniverse Talk.  

What about having a different label than Zooniverse team for people who are the research teams for projects that are live- what about 'project researcher' or something like that in grey similar to what shows up on the project talks? That way all four groups in the Zooniverse community are easily identifiable, Zooniverse team, mods, project research teams, and volunteers.

**Comment by parrish** [comment]
For what it's worth, this would be easy to add should we decide to do it.

**Comment by mschwamb** [comment]
The criteria could be live projects or Zooniverse approved - whatever you decide. For the time being I signing my few posts with Planet Four and Planet Four: Terrains science team, but having my avatar and other project research teams flagged as being different from the volunteers I think would be useful to make the distinction clear and acknowledge that researchers are a component in addition to the Zooniverse core team and volunteers in the Zooniverse collaboration.

**Comment by chrislintott** [comment]
I'd prefer we didn't introduce another role we have to maintain. Does marking 'owner of a live project' work?

**Comment by mschwamb** [comment]
Maybe, but then it's the same issue for someone who's on the science team but not the project owner.  Anyway, maybe this isn't an issue. I post very infrequently. It just felt odd to post something and it not be apparent I have a different relationship with the Zooniverse since I'm working on an approved project. 

Perhaps Zooniverse Wide Talk isn't going to have research teams on there frequently and that Zooniverse Talk is really only for volunteers, new project builders needing help, and Zooniverse team.

**Comment by parrish** [comment]
Going to close this as tabled indefinitely.
