### ISSUE TITLE
subject classification duplicates

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1402]
I've just had a look at my classifications export from my most recent workflow version (180)225.305. One user @djsimister has classified 180 subjects - this raised an eyebrow since there are only 150 subjects linked to that workflow. Analysis of the data shows that the user has only actually classified 104 subjects but has classified some of them multiple times - for example my subject 602944 has been classified 5 times by the user. There are many others that the user has classified more than once, in fact just 52 have only been seen once by the user.

I'm afraid I don't know the user so I can not get direct feedback in this case for impact on UX.

I'm assuming that this isn't supposed to happen...

I have found a potential way in which this can occur. If you are logged out and refresh the browser, the subject is refreshed. When you log back in the subject does not refresh and you can make a classification, even if this is a subject that you have already seen. This I think is because the website does not refresh, the data related to >if the subject has already been classified by that user< isn't queried and so the 'already seen' banner and blanking out of the workflow doesn't happen.

**Comment by camallen** [comment]
I think this is mostly caused by https://github.com/zooniverse/Panoptes/issues/1069 but I the subjects to classify should be refreshed on a login event.

**Comment by AdrianEvans** [comment]
yes, that is the same problem being reported. Should probably close this.  will create a new issue for the login-refresh issue
