### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#141]
Have we got GA tracking codes in PFE yet? @mrniaboc?

**Comment by brian-c** [comment]
Note about Google Tag Manager here: #124

Do we need both?

**Comment by camallen** [comment]
Probably not - i think we ran out of custom GA codes so we've switched to using 1 with custom tag tracking. @mrniaboc how are we tracking new projects now we've run out of new GA codes?
