### ISSUE TITLE
Most recent posts if stickied not showing up on Talk as the most recent thread on the project talk front page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1411]
I noticed this morning that Planet Four: Terrains talk is saying that posts I made 14 days ago are the most recent when there are more recent posts made on the stickied thread. The  behavior is working fine on the Notes board. 

![screen shot 2015-08-14 at 9 10 56 am](https://cloud.githubusercontent.com/assets/753325/9266471/07f676ca-4274-11e5-9c1b-39812e86ff33.png)

Then if you look at the boards the stickied threads were updated but not showing on Talk as the most recent. This was fine yesterday. Did something change in the Talk api? 

![screen shot 2015-08-14 at 9 10 50 am](https://cloud.githubusercontent.com/assets/753325/9266475/151e986e-4274-11e5-9547-9439510ac2b1.png)

**Comment by mschwamb** [comment]
Looks related a thread I started 2 days ago now shows on Page 3 of Chat well below a lot of posts from weeks ago

![screen shot 2015-08-14 at 4 49 25 pm](https://cloud.githubusercontent.com/assets/753325/9270465/98ee9060-42a4-11e5-96d4-f0ec0a96fa16.png)

**Comment by mschwamb** [comment]
Closing since this behavior seems to have stopped.

**Comment by DarrenMcRoy** [comment]
Yes, I think this got fixed, just the issue was never closed. Thanks!
