### ISSUE TITLE
Moving the Talk red lock to the left hand side for locked boards

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1412]
I've been on the boards a few times today and it took my until now to realize the lock symbol was there. If it's easy to do, could the red lock be moved to the left hand side, since that's where you look for the board name that's where your eye is drawn. I've missed the symbol on the right side, I think most people will as well. 

![screen shot 2015-08-14 at 4 13 47 pm](https://cloud.githubusercontent.com/assets/753325/9269847/bbf20b6e-429f-11e5-8c11-479553eb6368.png)

**Comment by mschwamb** [comment]
Just realized the board was white instead of grey... still think it would help if the lock was on the right since I missed the color change. There is something that denotes it's different so do feel free to close if you disagree with me.

**Comment by chrissnyder** [comment]
100% agree with you, but closing for the same reason as #1280 (though that one was fixed).
