### ISSUE TITLE
Merging admin and moderator readable board types ?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1413]
When making a board private you can have the ability to let moderators read and write or admins to read and write?  Is admin the  project owner and Zooniverse team? Is the research team considered admin? 

That was a source of confusion making private boards when we made the P4: Terrains talk for the mods and the science team to talk.  Edit -  Maybe it's worth only having three types moderator/admin, team, and public 

![screen shot 2015-08-14 at 4 30 40 pm](https://cloud.githubusercontent.com/assets/753325/9270127/e092fdd2-42a1-11e5-9277-9443ad32bc02.png)

**Comment by aweiksnar** [comment]
@mschwamb Do you think if I added something like 'Collaborators will be given full admin access on talk' to this line [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/collaborators.cjsx#L21) it would help explain the distinction?

**Comment by mschwamb** [comment]
A help button to explain would be useful. The confusing but was who is admins. The mods have the same list I do for the type of boards, so our confusion at the start when building the private board the science team and they could see was, will we create a board we can't access

**Comment by mschwamb** [comment]
Forgot to say I think a line in the project builder will help,and that should be added, but the moderators don't see the project builder so making it clear to them and so they can't make boards they can't access or delete if made accidentally would be helpful.

**Comment by aweiksnar** [comment]
Yeah that makes sense, I'll probably just make that list only show roles that are less-than-or-equal-to a users role

**Comment by mschwamb** [comment]
Yeah that would help a lot with the mod  confusion. 

Though I think on the research team/project owner side I'm still not sure in which format a Zooniverse team labeled account could see the private board. Is is admin? Or do they have access to all types? In case I or the mods wanted to ask them to join a conversation of the private tema board for example

**Comment by aweiksnar** [comment]
The heirarchy is `admin -> moderator -> team -> everyone` in that users can access anything that is to the right of them there. I'll work on making that more clear on the site

**Comment by mschwamb** [comment]
Cool - thanks for clarifying. A line on the project builder talk section/ page where you add people  I think would help clear that up. 

And also allow roles to only make private  boards that are accessible to less than or equal to their status on Talk would sort this ticket.
