### ISSUE TITLE
Mention ability to mark hashtags on the text that appears before you write a comment on a subject page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1419]
On Talk 2.0 it says 'Say something, or mark with a #hashtag' and I think that was useful in clueing people in how Talk works and that hashtags exist.

![screen shot 2015-08-15 at 8 28 29 am](https://cloud.githubusercontent.com/assets/753325/9286522/1abcf388-4328-11e5-80b2-7bca2026b5e8.png)

Can you do something similar on the default text that appears in the text box before you write a comment on a subject page?  It's a minor change, but I think it would be a big help in directing people how to use Talk and use hashtags. 

![screen shot 2015-08-15 at 8 27 42 am](https://cloud.githubusercontent.com/assets/753325/9286529/3e862b22-4328-11e5-99a8-a0623fec42ef.png)

**Comment by DarrenMcRoy** [comment]
Related to the overhaul of the subject page in general.

**Comment by vrooje** [comment]
I think this would be useful.
