### ISSUE TITLE
Increasing the number of popular hashtags listed on Talk sidebar

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1420]
Current Talk lists a small number of popular hash tags.  There's a lot of variety in hashtags and I think the current display, is showing too little. Currently on Planet Four: Terrains there are 10 on the list (I know there are many more hashtags being used).  Previous  version of Talk  listed 20 and I found that really useful because it allowed for easier searching for examples and such, because I could peruse the list to see what people were using. I'm finding that really hard to do with just the 10 . I'm having to use the search instead to try and found out what the hashtag is first and then search for it while writing a blog post right now. I think it would help if the 10 were increased 20 to match what was on Talk 2.0 

Planet Four: Terrains Talk
![screen shot 2015-08-15 at 5 59 30 pm 2](https://cloud.githubusercontent.com/assets/753325/9288393/97cd948c-4377-11e5-9f2d-0f50520ae77f.png)

Planet Four Talk 

![screen shot 2015-08-15 at 5 58 12 pm 2](https://cloud.githubusercontent.com/assets/753325/9288394/9c54ec08-4377-11e5-9ab8-9dd3a26f445f.png)

**Comment by yshish** [comment]
I second this. Moreover, I think the old list was better because of using the columns. It looks like very messy now.
