### ISSUE TITLE
GZ:Bars mods board is broken & breaks the site

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1422]
Attempting to access the GZ: Bars moderator-only board breaks the entire site; the board does not load and all links cease to work.

**Comment by mschwamb** [comment]
I had the same thing happen for a second. But all boards and links weren't accessible. I was trying to get to the a moderator only board. I was non-logged in and had the page open for a very long. I didn't check the console but after logging in the links and such worked again.

**Comment by mschwamb** [comment]
Just had it happen again after i signed out. If the console is helpful. I signed out for my inbox where i was looking at a private conversation and logged out from there and happened to hit the Zooniverse Talk button then none of the links worked
![screen shot 2015-08-18 at 2 33 42 pm](https://cloud.githubusercontent.com/assets/753325/9323750/7c5dd4b4-45b6-11e5-92a2-53095d81db4a.png)
![screen shot 2015-08-18 at 2 33 47 pm](https://cloud.githubusercontent.com/assets/753325/9323761/8e5e388e-45b6-11e5-9777-a50eaa30da94.png)

**Comment by chrissnyder** [comment]
Looks to be fixed. Reopen if not.
