### ISSUE TITLE
Board list latest-post summary: show content snippet

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1426]
On a given Talk's home page I think the content summaries of each board (showing the title of the board and the title of the most recently-updated thread) work really well. When the same summary is applied to each Talk sub-board's display, though, it means the title of each post is mentioned twice:

![screen shot 2015-08-18 at 13 47 37](https://cloud.githubusercontent.com/assets/2357126/9330290/42c65bb4-45b0-11e5-929b-29c07b0b6d70.jpg)

I think it would be more informative if the most-recently-updated line went 1 level deeper and displayed a snippet of the text (not including quoted lines that start with ">") of the most-recently-updated comment.

Apologies if this has been mentioned before.

**Comment by aweiksnar** [comment]
It doesn't look `markdown-it` supports plain-text rendering, which would be what we'd need here. I'll see about extending it sometime in the future. In the meantime I'll get rid of those redundant titles

**Comment by DarrenMcRoy** [comment]
Thanks, Alex... Be sure to keep the link to the most recent post, name of the poster, and time of post. :-)

**Comment by vrooje** [comment]
If the snippet isn't possible, we could add info on who started the thread?
