### ISSUE TITLE
Next task not being picked up correctly

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Panoptes-Front-End#1429]
I am making a demo for @chrislintott to use this week at the LSST meeting. The workflow is "question: yes/no, if yes: mark, if no: next". This was working for a while, but then I tweaked the text in the questions and the help boxes, and now the conditional logic is ignored. This seems like a bug, to me!

Here's the demo: 

http://demo.zooniverse.org/panoptes-front-end/#/projects/drphilmarshall/deblendinspector

Feel free to make yourselves collaborators so you can help fix this (or ask me and Ill add you). Thanks!

**Comment by chrislintott** [comment]
@brian-c Can you take a look? Demo is on Thursday.

**Comment by drphilmarshall** [comment]
I just made you a collaborator, @brian-c I hope your Zooniverse ID is the same as your GitHub ID! :-)
