### ISSUE TITLE
Where will logo appear

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#143]
Related to #97, where will the square project avatars show up? I assume it will appear somewhere on the main classify screen, yes?

Also, we have a logo design that includes both the avatar and the project name:
https://drive.google.com/file/d/0Bxc_8RhRnC8daHFyQVBlSjBwc00/view?usp=sharing

We'd really like to be able to use this somewhere. Thoughts?

**Comment by brian-c** [comment]
The avatar currently appears in the projects navigation and on the projects listing page. You can include custom images pretty much anywhere in the content using Markdown.
