### ISSUE TITLE
Make cursor appear below reply in comment box

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1435]
For flow purposes, so that to reply, you just hit reply and start typing, the cursor should appear in the box below the quoted text when you do a reply.

Currently:

![screen shot 2015-08-18 at 6 55 05 pm](https://cloud.githubusercontent.com/assets/8987864/9345834/ceec5a24-45da-11e5-9056-7de4f633649c.png)

Ideally:

![screen shot 2015-08-18 at 6 56 23 pm](https://cloud.githubusercontent.com/assets/8987864/9345843/d93a23b2-45da-11e5-94ae-9cb6f787260a.png)

**Comment by mschwamb** [comment]
That would also sort the issue of having to scroll through replies of replies which has been the other part that was making replies difficult to use.

**Comment by mschwamb** [comment]
@aweiksnar and @parrish  I'm loving the new reply setup you've made - it's really great - thanks!
