### ISSUE TITLE
background image instruction wrong

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1447]
text reads ...To add an image, either drag and drop or right click to open your file viewer...

should say left click

**Comment by vrooje** [comment]
@AdrianEvans Are you on Windows or Mac?

**Comment by AdrianEvans** [comment]
Windows

**Comment by vrooje** [comment]
Great -- left click works on both Mac and Windows. @ggdhines @camallen etc does it also work in Linux? If so this is an easy text change...

**Comment by edpaget** [comment]
Left click works on Linux as well.
