### ISSUE TITLE
email subscriptions

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#145]
@brian-c can you add a check box to the registration window that means people will be able to opt-in (or preferably have to actively opt-out) of newsletters? It should be connected to 'global_email_communication'.

**Comment by camallen** [comment]
I hate it when sites opt me in automatically.

**Comment by brian-c** [comment]
@camallen is `global_email_communication` already a property users have?

**Comment by camallen** [comment]
yep - they have 2 fields, 1 for the zooniverse and per project ones:
t.boolean  "global_email_communication"
t.boolean  "project_email_communication"

**Comment by brian-c** [comment]
I get a 422 trying to PUT that.

**Comment by camallen** [comment]
Did you try posting it in to `/users/sign_up`, i.e. when creating a user?

**Comment by camallen** [comment]
i agree that you should be able to update it via the user as well. Looking into that.

**Comment by brian-c** [comment]
Works fine on post.

**Comment by camallen** [comment]
I'm adding a PR for PUT on a user so we can update them after sign up.

**Comment by camallen** [comment]
closed via #671
