### ISSUE TITLE
Sometimes I can't see moderator-only boards on a project I own

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1452]
Sometimes I go to Talk after having my project open for a while and I can't see the Mods Only board. When I refresh it shows up again.

Is this related to #1052?

**Comment by parrish** [comment]
Just wanted to double check if this is still an issue?

**Comment by vrooje** [comment]
I haven't seen it in a while... I'll close this and re-open it if it happens again.
