### ISSUE TITLE
Deleting the only post on a thread via moderator tools leaves empty thread behind

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1453]
Both the empty threads here had 1 post that was deleted (each by a different mod) in the moderation control panel.

![screen shot 2015-08-22 at 18 15 50](https://cloud.githubusercontent.com/assets/2357126/9425055/6c55f91a-48fa-11e5-97f4-a81acf1fae16.jpg)

In order to delete the whole thread I have to make a new post and delete that post as the author (not as a mod), which works fine.

(Totally as an aside, the mods board is really, really useful for testing this and discussing those tests and new features and stuff. So a slightly random thanks for that :+1: )

**Comment by parrish** [comment]
Yep, this was a bug.  This will be closed when zooniverse/Talk-Api@9f287c041f39c2 deploys
