### ISSUE TITLE
Deleting a post via moderation tools leaves empty line on board summary

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1454]
![screen shot 2015-08-22 at 18 14 41](https://cloud.githubusercontent.com/assets/2357126/9425074/f802437e-48fa-11e5-9879-711bdb8348ae.jpg)

Not sure if this will be resolved with #1453 or whether it's separate.

**Comment by parrish** [comment]
Same bug, should be fixed in a few minutes
