### ISSUE TITLE
request to allow one to edit a Talk url in the address bar and be able to go there

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1456]
I noticed that if I'm on a subject page in mac Firefox and Chrome (haven't tried Safari) such as this one

https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/subjects/484083

if I go up to the address in the browser and edit the last part so that the subject number say to 485115  and hit enter nothing happens it stays on subject 484083

if it's not too much trouble is it possible to allow the site to then load the subject page for  484083

I use the Talk subject pages to debug my weighting scheme and look at small list of interesting subjects brought up in Talk discussions since I don't have the full list of images on my work computer or laptop.  So it would be helpful if it is possible if I can just edit the subject id rather than having to copy the link and make a new tab.

 I think other research teams and volunteers might find this useful as well. I understand if this is a won't fix issue.

**Comment by vrooje** [comment]
I have this issue as well with the new subject not loading when I type it in, but if I try again without retyping (click in the address bar again and just hit enter again) the new subject *does* load.

**Comment by aliburchard** [comment]
I've had the same thing happen as Brooke did.

On Monday, August 24, 2015, Brooke Simmons <notifications@github.com> wrote:

> I have this issue as well with the new subject not loading when I type it
> in, but if I try again without retyping (click in the address bar again and
> just hit enter again) the new subject *does* load.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes-Front-End/issues/1456#issuecomment-134067167>
> .
>


-- 
Sent from my moderately intelligent phone.

**Comment by aweiksnar** [comment]
@mschwamb I believe this has been resolved. I just tested out with the steps you mentioned and it looks all good now

**Comment by mschwamb** [comment]
@aweiksnar yep it is. thanks.

**Comment by aweiksnar** [comment]
Great!
