### ISSUE TITLE
one zooniverse team member has two green bars showing

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1458]
Noticed that @kellinora has two green zooniverse team identifying bars appear with her avatar but others like @DarrenMcRoy have one

![screen shot 2015-08-24 at 7 38 47 pm](https://cloud.githubusercontent.com/assets/753325/9439305/511e52d8-4a98-11e5-95f4-244cca307b3d.png)

**Comment by mschwamb** [comment]
I noticed the same thing on Anno.Talk as well, but for a different Zooniverse core team member

![screen shot 2015-09-02 at 8 25 35 am](https://cloud.githubusercontent.com/assets/753325/9620390/48c6e7de-514c-11e5-95d0-a0df49a3e87d.png)

**Comment by parrish** [comment]
Fixed.  They had both zooniverse-admin and zooniverse-team roles (which report identically in the UI).
