### ISSUE TITLE
Collections and Favorites tabs from "Profile" page

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1460]
So, from your profile, you can see four tabs. Clicking "Recent Comments" or "Your Stats" opens those items while preserving all four tabs:

![screen shot 2015-08-24 at 12 41 59 pm](https://cloud.githubusercontent.com/assets/8987864/9447545/9a91ce8a-4a5d-11e5-914a-4f80d141666d.png)

But if you click either "collections" or "favorites," you lose those other two tabs, because you're sent to the "collections/favorites" page.

![screen shot 2015-08-24 at 12 44 29 pm](https://cloud.githubusercontent.com/assets/8987864/9447611/ef3ddcc6-4a5d-11e5-8712-2f33aef1f5bc.png)

It's somewhat weird behavior for two of those tabs to open below, and for two of them to... not be tabs at all, but send you to an entirely different page. Yeah?

**Comment by chrissnyder** [comment]
Agreed, but it's currently working as intended. Let's discuss this within the context of the broader design of the profile section.
