### ISSUE TITLE
Content for Talk page on project builder

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1465]
For @aweiksnar, as requested:

---

“Talk” is the name for the discussion boards attached to your project. On your Talk, volunteers will be able to discuss your project and subjects with each other, as well as with you and your project’s researchers. Maintaining a vibrant and active Talk is important for keeping your volunteers engaged with your project. Conversations on Talk also can lead to additional research discoveries.

You can use this page to set up the initial Talk boards for your project. We highly recommend first activating the default subject-discussion board, which hosts a single dedicated conversation for each subject. After that, you can add additional boards, where each board will host conversation about a general topic. Example boards might include: “Announcements,” “Project Discussion,” “Questions for the Research Team,” or “Technical Support.”

**Comment by aweiksnar** [comment]
Thanks! I'll add this to the top of that page
