### ISSUE TITLE
Order of Project Cards on Zooniverse projects page

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1467]
What determines the order projects are shown on the Zooniverse projects page? 

It would be really really great if we could have Season Spotter Questions and Season Spotter Image Marking next to each other...

**Comment by DarrenMcRoy** [comment]
Right now, it's manual, so we could probably do that manually. There's a project in the works to enable a new look (and a sorting mechanism) for that page, but I'm not sure what the status is on that...

**Comment by chrislintott** [comment]
Let's make this change; it makes no sense for the two to be apart. Assigning @chrissnyder who can delegate...

**Comment by mkosmala** [comment]
@chrissnyder: Season Spotter project cards are still separated. Can we get them together? Thanks.

**Comment by edpaget** [comment]
Working on it
