### ISSUE TITLE
Duplicate active participants on Talk sidebar?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1468]
@Capella05 mentioned that she'd seen herself and other users listed multiple times on the participants list of the Talk sidebar, when the site was fairly busy (~45 people online). Is that because the list is actively changing and people's positions are shifting or is it a different bug?

**Comment by parrish** [comment]
I think this may have been a bug that was fixed in the real time system.  Please re-raise this issue if it crops up again though.
