### ISSUE TITLE
When you ^S a subject, showing the id number only

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1482]
Currently if I do ^S491950 it gives [mschwamb/planet-four-terrains - Subject 491950](https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/subjects/491950) - if possible would it be possible to just make the subject number appear automatically as the link text?  I'm finding the longer string very clunky in conversations.

**Comment by brian-c** [comment]
I suggest we shouldn't be modifying user-entered content at all. Just show what they typed and link the text they entered where appropriate. This'll make the syntax more discoverable to other users, too.

**Comment by mschwamb** [comment]
The long link text does I think interrupts the flow of the sentence and the formatting since it often gets bumped to the next line.  If it's possible to cut it down to 'Subject 491950' I think it would be easier to read as well. 

![screen shot 2015-09-22 at 8 32 11 am](https://cloud.githubusercontent.com/assets/753325/10008889/2ca790ce-6107-11e5-81cc-477043e55dc4.png)

**Comment by mschwamb** [comment]
Slightly better example 
![screen shot 2015-09-22 at 8 57 33 am](https://cloud.githubusercontent.com/assets/753325/10008952/0fb185aa-6108-11e5-939e-be71103d4f11.png)

**Comment by aweiksnar** [comment]
Closed in zooniverse-ui/markdownz@2.4.0
