### ISSUE TITLE
Sort alphabetically project list in email preference in account settings

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1489]
I noticed the project subscription list is not in a weird order, so you have to search for the project you want to uncheck or check. It would be easier if it was in alphabetical order. 

![screen shot 2015-08-30 at 7 05 56 am](https://cloud.githubusercontent.com/assets/753325/9564847/1ee874f4-4ee6-11e5-8f12-4ec39f977135.png)

**Comment by parrish** [comment]
Actually, this would need to be opened on zooniverse/Panoptes -- it doesn't allow that to be sorted.

**Comment by mschwamb** [comment]
When this issue is sorted on the backend, a change on the front end to call the sort will be needed - see Cam's comment in #2455

**Comment by mschwamb** [comment]
The backend now supports this. Could someone add the sorting feature ? Thanks

**Comment by mschwamb** [comment]
@eatyourgreens - was this deployed? I don't see them sorted alphabetically in my profile 

<img width="386" alt="screen shot 2017-01-08 at 8 12 47 am" src="https://cloud.githubusercontent.com/assets/753325/21750519/76be6276-d57a-11e6-878c-9972f3f7a47f.png">

**Comment by eatyourgreens** [comment]
@mschwamb Yep, it's been deployed but see [Cam's comment](https://github.com/zooniverse/Panoptes-Front-End/pull/3366#issuecomment-270384941) about Panoptes needing an update to support this.

**Comment by mschwamb** [comment]
oh. I thought the panoptes update happened. Thanks
