### ISSUE TITLE
Turn off the message ' You're receiving notifications from this discussion because you've joined it' if you have 'When discussions I'm participating in are updated' set to never in preferences

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1490]
I'm not sure show feasible, but I have a request for the user interface part of the new notifications system. 

I comment on a lot of threads, so I don't want an email digest of when other people reply. I turned off the email notification on 'When discussions I'm participating in are updated.' I do want to be able to follow some threads and get emails about those, so I would like to have 'When discussions I'm following are updated' in the profile set to Daily or Weekly. 

But it says for every thread I participate in that I'm subscribed because I participated even though I'm not really following it since I said no to getting the emails. it makes it difficult to follow a thread especially if I've commented on it. I have to hit the unsubscribe button and then subscribe and then it says I'm following because 'You're receiving notifications because you've subscribed to this discussion'

It would be less confusing and very helpful if I've set the 'When discussions I'm participating in are updated' to Never that it hides the messages about being subscribed because I'm participating and allow a subscribe button so I can subscribe by following.  I imagine there might be many moderators, volunteers, and research teams keen to see this.

**Comment by parrish** [comment]
Yeah, that would be confusing at the moment.  There's another setting on the subscriptions for enabled/disabled aside from the never email digest level.  That's because you can disable the email, but still have in-app notifications.

There will be an option to actually disable the notification once that's out.

Maybe a text change in the interim would make sense?

**Comment by mschwamb** [comment]
A text change would be helpful.

 Though not sure if that will helps with the part about if you want to keep in-app notifications for everything you reply to, but want to received emails from apps you follow (where you want to follow from a discussion you've commented in). You'd still currently have to unfollow and refollow as I described above.

**Comment by parrish** [comment]
Is this better, or equally confusing?

> You're receiving notifications from this discussion because you've joined it (never email)

**Comment by mschwamb** [comment]
Something like that I think will help because I definitely did a double check on my email settings after seeing it the first time. What about: 'You're receiving notifications (never by email) from this discussion because you've joined it' ? But @parrish your suggestion is fine. 

Though I think it's still confusing how if you want weekly emails for threads you participate in, but want daily emails for a subset of interesting that you have to unsubscribe to subscribe again with a different behavior. Maybe there could be a separate button for subscribing to the interesting posts email?

**Comment by parrish** [comment]
Yeah, it's tricky to communicate that in the UI.  I basically just mimicked the behavior of the subscribe button in GitHub

![subscribe](https://cloud.githubusercontent.com/assets/122990/9694003/7bba12fe-531a-11e5-9455-41ef67041810.gif)

**Comment by mschwamb** [comment]
Right,  but even with the text change (which helps with the confusion about whether or not I'm getting an email) It's super confusing to unfollow and follow again for a thread your commented on so I get an email if I don't want to have emails from every conversation I participate in.

Github is different. It's all the same behavior if I subscribe because I was mentioned or started it or I subscribe because I'm interested in the github issue discussion I get individual emails. There's no setting as far as I can tell to change the email behavior to digest for one type versus another. It's whether I want email and web, web only, email only. Am I wrong on that? 

Where as Talk allows different types of digest modes, so I don't think on subscribe/unsubscribe button makes sense at least from my user experience.  So I don't get why can't their be two subscribe/unsubscribe buttons if you have different email settings for  'When discussions I'm participating in are updated' and 'When discussions I'm following are updated'

**Comment by mschwamb** [comment]
@parrish ignore what I said above. sorry about that -  playing around github I  finally get that's see how it works. I didn't understand how it works. I  think then it's fine to do leave it as is with a clarifier you're not getting email from the autosubscribe with 'you're receiving notifications (never by email) from this discussion because you've joined it'

But I think there needs to be somewhere in Talk that it tells you how this works. I think most people are more familiar with facebook and twitter and it's you follow, mute, or unfollow - not this behavior. Maybe a Talk help page or some kind of help button on where the email notifications settings are?
