### ISSUE TITLE
Profile menu and touch devices

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1495]
I tried zooniverse.org using a touch device and noticed that once I click on my user name to get to my Profile page (the top right menu), it stays opened forever, no matter where I go.. 

At first I thought it happens on the touch device only, but when I came back to my computer, I figured out that I'm actually wrong. I'm used to go to my Profile page by hovering over my name and choosing from the menu which disappear when I go with the cursor away(when the page loads, it's closed already). 

When I click with the mouse on my name instead of just hovering over it, the menu stays displayed too, as well as when I'm using the touch device. The only way to close it is to click on my name again. But this is not obvious on the touch device because there I need to first click on the name again - the menu is still opened(!) and then to click elsewhere to make the menu disappear, since I don't have a cursor but a finger. It's not very intuitive. The menu doesn't close after clicking on the name until I try to click to another button after. 

Hope it's clear :) Here is a [screenshot](https://lh3.googleusercontent.com/-zFD3Odd_iKw/VeSH8UYhYHI/AAAAAAAAIbw/U81vTjxZc8s/s0-Ic42/Screenshot_2015-08-31-16-57-57.png) of the menu I'm talking about (opened in the top right corner)

**Comment by brian-c** [comment]
Anybody (@srallen, @aweiksnar) mind if I switch this control to pop up on click instead of on hover?

We should probably avoid activating important stuff on hover anyway. It's pretty hard to predict how that works across touch devices.

**Comment by aweiksnar** [comment]
Yeah I'm definitely in favor of this being clickable

**Comment by srallen** [comment]
Yeah I'm fine with click.

**Comment by edpaget** [comment]
This happened right?

**Comment by brian-c** [comment]
Nope, sorry, we got stuck on accessibility stuff and then I rewrote the library. Soon!

**Comment by chrissnyder** [comment]
Just for organization, assigning to @brian-c
