### ISSUE TITLE
No classifications being recorded for Whales as Individuals

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes-Front-End#1496]
@aliburchard @camallen Happy Monday! hope you are both well. I've just realized something is very wrong with Whales as Individuals. The last recorded classification in a new export is 7/29. A lesser issue, too, see below from Talk.

Thanks,
Ted

Begin forwarded message:

From: no-reply@zooniverse.org
Subject: Zooniverse Talk Notifications
Date: August 31, 2015 at 8:05:21 AM PDT
To: teo@cheesemans.com

Zooniverse Talk Notifications

Mentions

Whales as Individuals

You were mentioned by ElisabethB in Only training images ?
For the past couple of days now I've only had training images to classify. No box drawing whatsoever.
Is this normal ? @tedcheese

less than a minute ago
View on talk

**Comment by brian-c** [comment]
Looks like workflow 84 "Fluke finder - uncropped" is set to `active: false`. I don't think that setting is exposed in the interface, is it set automatically somewhere @camallen?

**Comment by tedcheese** [comment]
Is this the same for workflow 9? It does not appear that this has been recording data either.

**Comment by edpaget** [comment]
The classificaitons made were saved in the Database. I've switched your workflows to be active.

**Comment by edpaget** [comment]
I'm not sure why nothing exported for Workflow 9. The most recent classification when I checked was from about 10 minutes ago.

**Comment by tedcheese** [comment]
Thanks Ed. Classifications now are happy, it seems, just exported them and we seem to have been getting ~ 600/day through August.

Still though when I export subject data, I think I'm getting old data. When I sum the column classifications_by_workflow I get 30798 classifications. Yet there are > 68500 classifications in the classification export. Or is the subject data listing only completed classifications? Thanks :)

**Comment by camallen** [comment]
@tedcheese we only count classifications for live worfklows.
