### ISSUE TITLE
can't delete subtasks

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1498]
The add task button leads to confusion - not sure if I click the close button if it will save changes (perhaps this should be a 'done' button)

so clicked add task....
This adds a second sub-task. There is no way to delete this second subtask. The only way at present appears to be to bite the bullet and delete the entire task from scratch.

I'm sure there used to be a x that you could click but....

win10/7 chrome/explorer

**Comment by vrooje** [comment]
I'm having this too in OS X/chrome and @Capella05 reported it [here](https://www.zooniverse.org/talk/18/115/?comment=6302) as well. At the moment it doesn't seem possible to delete sub-tasks... I thought I remembered being able to before.
