### ISSUE TITLE
Help text too wide for screen

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#150]
I have Safari full screen. The left hand edge of this image is the edge of the screen:

![screen shot 2015-03-18 at 14 36 44](https://cloud.githubusercontent.com/assets/428423/6710996/4af30474-cd7c-11e4-8b4e-b2331e97e28c.png)

**Comment by brian-c** [comment]
I've moved help content into a popup instead of a tooltip for now.
