### ISSUE TITLE
Interesting threads/subjects and discussions needed attention notifications for the research team

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1506]
Might be nice to have the ability for moderators and research team member to be able to alert the research team to interesting discussions and subjects as well as discussions that need their reply. Since the notification system is in place, I think one thing that could be very handy is if you're a mod or part of the research team you could hit a button and then like the other notifications, the research team (depending on how their subscribed) would get a digest email with links to these discussion threads.

**Comment by parrish** [comment]
What about just @-mentioning them?

**Comment by mschwamb** [comment]
Good point, but if you're got six people in your team I thought that might a bit much to @-mention all of them. No super strong opinion since there is some to alert people/draw them into a conversation, so I'll close.

**Comment by parrish** [comment]
Actually, you just raised an interesting idea though.  I wonder if role mentions would be a good idea?  e.g. @moderators, @scientists, @-team, etc. -- GitHub implements @-team (without the -) to mention your team.

Could possibly be annoying too.  Thoughts?

**Comment by mschwamb** [comment]
The @moderators is a great idea. Especially useful if you want to start a private message with them. My bet is people won't @ them on 99.9% of  board discussions because you don't want the other person you're in conflict with to know (hence private reporting). In few of the small number of times there have been conflicts the mods dealt in the past I've given the usernames of the mods so someone could message them since they didn't know all their usernames ( at least on my projects, the mods tend to be watching but don't necessarily post very frequently). So if that could be implemented even just on private messages I think that would be handy. Not sure where you'd tell people they could do that though ?

I could see @scientists getting annoying since if  people start adopting that into frequent use, that's why I was thinking of a separate button like report. Though maybe there won't be frequent posts to need this  type or alert so @ individually people is okay (reason I closed it after your reply).

**Comment by parrish** [comment]
Hmm... that's worth a thought.  I'll bring it up at the standup tomorrow since it would require excluding those account names as well.

**Comment by vrooje** [comment]
@parrish I love this idea.

**Comment by parrish** [comment]
Preference for this notification could be managed separately from direct mention notifications.  That ought to minimize the annoyance level.

@edpaget @aweiksnar  What are your thoughts on doing group/team mentions in Talk?

Short version is that @-admins, @-moderators, @-team, etc. (without hyphens) would expand into mentions for everybody with roles on that section of talk.  It would involve restricting those names in Panoptes.

**Comment by edpaget** [comment]
That sounds good to me. It'd be similar to the @zooniverse/owners mentions here.

**Comment by aweiksnar** [comment]
:+1: Yeah I think it'd be awesome to try out. I could see overzealous volunteers abusing it, but since users can throttle their email frequencies it'd be in their control to decide how often they want to be pinged

**Comment by aweiksnar** [comment]
We should see about reserving those usernames in panoptes too, looks like a couple might be accounts already

**Comment by parrish** [comment]
This is in production now.
