### ISSUE TITLE
Removing line about not being an official Zooniverse project from Anno.Tate Talk site?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1507]
I'm not sure where this goes, so I thought I should mention it here since the Anno.Tate Talk is the one from the Panotpes Front End. I noticed that Anno.Tate talk has on the  bottom the message that shows for projects in beta and those made with the project builder but not officially granted approval from the Zooniverse 

'This project has been built using the Zooniverse Project Builder but is not yet an official Zooniverse project. Queries and issues relating to this project directed at the Zooniverse Team may not receive any response.'  

![screen shot 2015-09-02 at 8 27 04 am](https://cloud.githubusercontent.com/assets/753325/9620469/12c7a924-514d-11e5-892c-2308407a9f0b.png)

I think that should be removed somehow since it is an official  Zooniverse project. 
cc @VVH  @chrissnyder

**Comment by edpaget** [comment]
This has been done.
