### ISSUE TITLE
Out of band preload user's seen set in cellect

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#151]
If a user is signed in request the worfklow resource for stargazing on page load / after they sign in. This will pay the load cost before they ask for a subject from cellect.

**Comment by brian-c** [comment]
This is just `GET /api/workflows/1` on sign-in, right?

**Comment by parrish** [comment]
Cellect also has an endpoint to preload user data at /workflows/:workflow_id/users/:user_id

Panoptes could hit that asynchronously whenever a user logs in

**Comment by parrish** [comment]
Here's the client method for that: https://github.com/zooniverse/Cellect/blob/master/lib/cellect/client/connection.rb#L32-L34

**Comment by camallen** [comment]
@brian-c yep, this is a more general pattern than just stargazing but yep. 

@parrish - you'd have to know which workflow they are going to work on, so the easiest way is to just do it when the request a project workflow(s) which is how it's setup [here](https://github.com/zooniverse/Panoptes/blob/9ec330948024a0da8d99230079b3cf5ef37711d0/app/controllers/api/v1/workflows_controller.rb#L10)

**Comment by parrish** [comment]
That'll work!

**Comment by camallen** [comment]
@brian-c - we can come up with a more general solution that probably just loads all their workflow seen set for a project after stargazing, i.e. via the get `/workflows?project_id=x` call.

**Comment by brian-c** [comment]
This is in place, so I'll close this. We can open a new one when we've got a strategy for doing this more generally.
