### ISSUE TITLE
Need Planet Four: Terrains to receive Zooniverse approval again to get back on the front page and remove the this is not an appoved Zooniverse project wording at the bottom

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1515]
I had to take the site down to fix the help since it used the hash format  to refer to other pages (like the Research and FAQ) and to add the ability to open a new tab for the spotters guide. I made the changes. I checked them, so all I need is for the status to be changed. Thanks very much.

**Comment by edpaget** [comment]
Done

**Comment by mschwamb** [comment]
Muchas gracias @edpaget !!
