### ISSUE TITLE
Adding Zooniverse markdown specifics like the +tab+ to the project builder markdown help

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1517]
If possible, it would be really helpful to add the +tab+ syntax for making links open in new tabs and any other syntax specific to the Zooniverse markdown listed on the project builder help as an addition to the generic markdown tutorial currently linked

![screen shot 2015-09-03 at 9 06 10 am](https://cloud.githubusercontent.com/assets/753325/9648435/1a2445b4-521b-11e5-97c3-6f3d95ba78a3.png)

**Comment by chrissnyder** [comment]
Good idea.

@DarrenMcRoy Can you do this and issue a PR to https://github.com/zooniverse-ui/markdownz? We'll make a separate page to point people to after the text is ready.

**Comment by aweiksnar** [comment]
The helptext actually lives in PFE
- https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/lib/markdown-help.cjsx
- https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/comment-help.cjsx

**Comment by DarrenMcRoy** [comment]
Update: Working with @aweiksnar tomorrow to develop a beginner-friendly guide to all Markdown and Zooniverse-flavored Markdown capabilities (to replace the current link to http://markdownlivepreview.com/).

This can be linked from the Talk comment box as well as from the Project Builder, so we have a single location where everyone can figure out how to do whatever they need to do with Zooniverse-flavored Markdown. :-)

**Comment by chrissnyder** [comment]
Hold on this. I'd like it to be the first task for new dev (coming soon!)

**Comment by DarrenMcRoy** [comment]
Okay. I've done a bit of advance legwork for them, though. :-)

Here's a list of all the Markdown features that we'll want to explain.

https://docs.google.com/document/d/1I2KapyYtwY-ebRd8WLm0k_iw68Dkk4mViEJbIjsb19c/edit
