### ISSUE TITLE
Project Talk Board Recent Comments Pages listing Notes from all other Zooniverse projects

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1518]
If I hit the Recent Comments Links from a P4 discussion board. I though it might show a list of recent comments from that board, but instead it's showing recent Notes  from all of the project Talks combined.  Is that the intended behavior?

![screen shot 2015-09-03 at 9 13 10 am](https://cloud.githubusercontent.com/assets/753325/9648518/233be156-521c-11e5-9a18-162a96ac7d55.png)

![screen shot 2015-09-03 at 9 15 21 am](https://cloud.githubusercontent.com/assets/753325/9648548/840b2c1c-521c-11e5-8571-6754cd5f895d.png)

**Comment by parrish** [comment]
The fix is in place for this now -- I'll get the data updated as soon as the deploy is out
