### ISSUE TITLE
Cannot post reply to Talk question

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes-Front-End#1520]
Trying to reply to https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/talk/27/2770%3Fcomment=5911#/projects/tedcheese/whales-as-individuals/talk/27/2770?comment=5911

with 
Is it still the case for you that you're only getting the older greyscale cropped images, none of the new uncropped images? (We resolved one bug that I hoped would nail this). Thanks!

> In reply to ElisabethB's comment: 
> Any news on this bug ?
-----------------
I keep getting
Internal Server Error

screen shot attached (I think)
<img width="1086" alt="screen shot 2015-09-03 at 10 08 53 am" src="https://cloud.githubusercontent.com/assets/7146233/9652456/35bd8f98-5224-11e5-9831-aa35a34065d6.png">

**Comment by parrish** [comment]
@tedcheese I'm fairly certain this should be resolved for you.  We did have some issues yesterday while dealing with an upgrade.  Please reopen this if it's still an issue.

**Comment by tedcheese** [comment]
Hi Parrish,

Sorry, I'm still getting the same issue

<img width="1002" alt="screen shot 2015-09-04 at 4 57 21 am" src="https://cloud.githubusercontent.com/assets/7146233/9675080/9386ccd2-52c1-11e5-912f-f89f6c740e93.png">

**Comment by tedcheese** [comment]
Ironic to not be able to reply to a bug report because of a bug

**Comment by tedcheese** [comment]
@aliburchard @parrish I don't seem to be able to reopen this issue, -- a permissions issue?

**Comment by parrish** [comment]
Yep. It's permissions.

I saw an error come through on the API right before you posted here, so I've got something to go on.  I haven't been able to reproduce it, so this is certainly helpful.

I'll report back when I find something.

**Comment by tedcheese** [comment]
thank you :)

**Comment by parrish** [comment]
Okay, I think I actually tracked it down.

During that upgrade the other day there were a few issues with the URL's not getting built/redirecting correctly.

The URL you posted:

https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/talk/27/2770%3Fcomment=5911#/projects/tedcheese/whales-as-individuals/talk/27/2770?comment=5911

shows how the information was mangled.

The correct URL is:

https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/talk/27/2770?comment=5911&page=1

Apparently, Chrome isn't repairing the first URL in the same way other browsers are, so it's loading the page with incorrect data.

If you restart your browser (and don't visit that first link anymore), it should work.

The error that you were seeing did actually help track down a weird edge-case bug too.

Let me know if that fixes things for you

**Comment by tedcheese** [comment]
Yes works now! :)  Thank you
