### ISSUE TITLE
Paging through collections breaks

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1521]
This doesn't seem exactly the same as #1284 but I'm not completely sure.

Just tried paging back and forth through a collection. Going from page 1-->2-->3 worked fine, but then when I tried to go back I ended up with a "Not found" because I was apparently directed to:

https://www.zooniverse.org/collections/vrooje/not-a-bar-but-kinda-looks-like-one/page=3?page=2

**Comment by edpaget** [comment]
This is caused by https://github.com/rackt/react-router/issues/1148 I'm looking into fixing it now.

**Comment by edpaget** [comment]
My PR has been merged int React-Router just waiting for them to release.
