### ISSUE TITLE
Recents on a Talk Board including posts from other projects

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1522]
Looking at https://www.zooniverse.org/projects/vrooje/galaxy-zoo-bar-lengths/talk/recents/32/ , I see posts from not just that board for that project but also from other projects.

What's perhaps more disconcerting is that clicking on those other threads from that page goes to subject & discussion pages still branded as GZ Bar Lengths Talk, when they are clearly not.

![screen shot 2015-09-03 at 11 55 55](https://cloud.githubusercontent.com/assets/2357126/9656770/e664b7e6-5232-11e5-908a-ff3dc5c99f3a.jpg)

I have no idea what project this is from.

**Comment by camallen** [comment]
looks like a dup of #1518 and it's annotate for reference.

**Comment by vrooje** [comment]
Ah! Yes, so it is, apologies. Will close this.
