### ISSUE TITLE
Comment box style in Firefox

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes-Front-End#1524]
![screenshot](https://cloud.githubusercontent.com/assets/122990/9667334/c250a870-5240-11e5-9070-facb561103ad.jpg)

Yay.

I'll take a look at it, but am open to suggestions

**Comment by parrish** [comment]
And, it's not affecting any other environment other than production....

**Comment by edpaget** [comment]
Maybe that issue with nib Brian and Alex were describing on Slack? A redeploy may fix?

**Comment by parrish** [comment]
Yep, I'm rebuilding the image to pickup the [new stylus release](https://github.com/stylus/stylus/releases/tag/0.52.2)

**Comment by parrish** [comment]
Fixed after updating stylus.  Deployed now.
