### ISSUE TITLE
On Planet Four: Terrains Talk Most recent threads now in the discussion board showing at the top are from two months ago 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1528]
I don't know what happened but for all of Planet Four discussion boards are now listing posts from 2 months ago on top and recent posts in the last few days and month are someone buried in the middle

[This thread](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/8/2205/?comment=4576&page=1)  should be near the top of help, but it's not. Stuff from 2 months ago is now listed there. I can't find these recent discussions without using the search. 

![screen shot 2015-09-04 at 9 03 35 am](https://cloud.githubusercontent.com/assets/753325/9674461/e0f8adec-52e3-11e5-9866-33d1e3548b83.png)

The [recent comments list](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/recents/8/)  looks okay for the Help thread, but you can't find any recent discussions from the boards directly. It looks like  no one has posted in 2 months.

![screen shot 2015-09-04 at 9 07 20 am](https://cloud.githubusercontent.com/assets/753325/9674509/71153184-52e4-11e5-9c04-e5ee8f7caaf1.png)

All the other Talks look okay. So what happened? I've noticed this happen once more before.

**Comment by parrish** [comment]
Ah, I see what happened.  A data migration had accidentally caused all the discussions to be update the 'updated_at' timestamp.  It'll be fixed shortly.

**Comment by parrish** [comment]
Should be sorted now.

**Comment by mschwamb** [comment]
Thanks @parrish on all levels :-)
