### ISSUE TITLE
Volunteers and Classifications counters break when going back to home page

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#153]
If you stay on the classify page for a few minutes and do a few classifications, after clicking Snapshot Supernova on the top left to go back to the home page the counters sometimes show the wrong numbers/don't update any more.

**Comment by edpaget** [comment]
sorry about that guys.

**Comment by brian-c** [comment]
Oops, I attached that commit to the wrong issue.
