### ISSUE TITLE
Talk data dump button doesn't reset in the project builder after making the request

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1530]
Not sure if I hit the button more than one after it succeeded the first time.  

![screen shot 2015-09-04 at 1 16 22 pm](https://cloud.githubusercontent.com/assets/753325/9677065/afc3c7ba-5307-11e5-9711-5afa19a6028c.png)

Tried to logging in and back out and that didn't see to change anything.

**Comment by parrish** [comment]
Yep, only one can be requested per day.

That'll make more sense once I update the text on zooniverse/Talk-Api#67

**Comment by mschwamb** [comment]
It would be helpful if the project builder said that since other team members can hit the button, but I presume the request is once. 

![screen shot 2015-09-05 at 9 49 28 am](https://cloud.githubusercontent.com/assets/753325/9697127/7af254be-53b3-11e5-8129-7ab1e6db18a0.png)

@parrish should I reopen this or add a new ticket

**Comment by parrish** [comment]
Pull request here: #1537
