### ISSUE TITLE
Pagination broken on Talk searches - can't go beyond the first page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1533]
You can only retrieve the first page of results. If you try and go to the next page of the search results it just returns back 'not found'

**Comment by mschwamb** [comment]
This is on the project talks. And apparently when you got o the next page the 'not found' page is on the Zooniverse wide Talk

![screen shot 2015-09-07 at 11 02 36 am](https://cloud.githubusercontent.com/assets/753325/9708545/019ceaea-5550-11e5-81c9-8f471d0d7fb6.png)

**Comment by parrish** [comment]
Looks like it's something broken with the router?

The next page is trying to route to https://talk.zooniverse.org/boards/search

**Comment by aweiksnar** [comment]
@parrish yeah I've been looking into this one this morning - the paginator is duplicating one of the query params when changing pages. That function was changed when we moved away from hashed urls. Should have a patch to send sometime today

**Comment by edpaget** [comment]
@aweiksnar It could be due to the react-router bug I patched on Thursday. https://github.com/rackt/react-router/pull/1816 Don't know if you want to pull down my branch and see if that fixes it. If so I'll try to figure out a way a to distribute the patch until they merge it.

**Comment by aweiksnar** [comment]
@edpaget I just swapped `props.path` with `location.pathname` [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/search.cjsx#L88) and it fixes it. Could be the same thing, since it was leaving that query param on as part of the path
