### ISSUE TITLE
Workflow-84 is not appearing on Whales as Individuals

### ISSUE THREAD

**Issue by tedcheese** [zooniverse/Panoptes-Front-End#1541]
I thought there was an open issue for this, but I cannot find it. Since the end of Aug, workflow-84, 'Fluke finder-uncropped' has not been showing up; only workflow-9 images are displayed. What is wrong?

See:
https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/talk/27/2770

Thanks, Ted

**Comment by aliburchard** [comment]
Might all of those subjects have been retired?

**Comment by tedcheese** [comment]
I wish :(  Only 300 of them are retired

**Comment by edpaget** [comment]
@tedcheese My counts are showing that all of Workflow 84's subjects are retired.

**Comment by tedcheese** [comment]
Very strange... the data export I just did shows only 1057 of workflow 9 retired and only 330 of workflow 84 retired. Is there something wrong with the subject data I'm getting? (was going to attach csv but that's not supported)

**Comment by tedcheese** [comment]
That leaves 1506 un-retired...

**Comment by edpaget** [comment]
Yeah something is going wrong with your exports. I will open and issue and look into it, but the count I have from your workflow has 1836 Subjects retired.

**Comment by tedcheese** [comment]
Oh, okay thank you. Should I wait to upload new subjects?

**Comment by edpaget** [comment]
Go for let me know when you do an I'll reactivate the workflow.

**Comment by tedcheese** [comment]
great, will do tonight, will let you know. Thanks :)

**Comment by tedcheese** [comment]
Thank you @edpaget --- I've uploaded 1583 new subjects into a new set -- uncropped-MBWW. Please do reactivate!

**Comment by tedcheese** [comment]
Question, if I delete a subject set, does the data on that set remain such that all subject and classification exports are cumulative?

**Comment by edpaget** [comment]
It is reactivated. 

Doing that won't delete classifications or subjects from the database, but I'm not sure how it will work with the exports since we haven't tested for that case.

**Comment by tedcheese** [comment]
Thank you! :)

**Comment by tedcheese** [comment]
@edpaget is there an issue open about the classification and subject exports not being up to date? When I do a subject export, I'm still not getting updated data.

Separately, since I cannot see the status of data, can you tell me how we are for progress on subjects on workflows 9 and 84? I'm not seeing any of the workflow 84 subjects up; maybe they're already all retired already but given I just uploaded them four days ago, I'd be surprised! Thanks :)

**Comment by camallen** [comment]
@tedcheese - https://github.com/zooniverse/Panoptes/issues/1351 

Did you delete the / any subject set? That would break our subjects export and it's not necessary. to not serve data from a subject set for a workflow you just need to unlink the subject set from the workflow in the project builder, see "Associated Subject Sets" section on your workflow (docs here https://www.zooniverse.org/lab-how-to).

**Comment by camallen** [comment]
Also workflows 9 =1375, 84 = 331 retired subjects.

**Comment by edpaget** [comment]
@tedcheese I'll be working on something this week that should fix the export issue.

**Comment by tedcheese** [comment]
Thank you @camallen and @edpaget. If there's only 331 retired subjects in workflow 84, then there must be a problem where this workflow is not being served up. I believe I have deleted some subject sets, given that I previously was up against the 10,000 subject limit (which I understand has been raised some for this project, not sure to what level).

**Comment by tedcheese** [comment]
@brian-c @chrissnyder this remains unresolved. The data export shows me that only 331 of workflow 84 are retired and 436 of workflow 9 are retired. Apparently I am not receiving the full data export... or images aren't being served up. Either way, the data remains unusable to me, a bit stuck in a standstill, and I can't really add more data until this is resolved. Thank you,

**Comment by edpaget** [comment]
@tedcheese I am still working on this, but was out sick for part of this week.

**Comment by tedcheese** [comment]
Thanks @edpaget. Hope you're feeling better. Maybe for the short term could you provide a data export? My collaborator Diego just mentioned that the export is only containing about 10% of subject data.

**Comment by aliburchard** [comment]
@edpaget is the export stuff you're working on contained in another issue? If so, I think we've resolved Ted's specific issue and can close this thread.

**Comment by camallen** [comment]
@aliburchard ed's work will be in the panoptes repo. I'm going to close this then, please reopen if needed.
