### ISSUE TITLE
Workflow with newly added images not re-displaying

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1545]
Somewhat related to #1541. Wildebeest Watch was out of images for one of the workflows. I added more subjects to that workflow. But the workflow still does not appear as an option on the landing page.

I suspect that the worfklow got flagged as "complete" or "inactive" when all the subjects were retired, to avoid the issues that Margaret raised a while back. However, given that adding to an existing subject set is the only thing you can do without taking the project off "live," it makes sense that an expanded subject set should automatically refresh the workflow flag, so the workflow appears again automatically on the landing page.

In the meanwhile, @edpaget is this something you could manually activate?

**Comment by edpaget** [comment]
Yes I will manually activate it

**Comment by edpaget** [comment]
What's the id?

**Comment by aliburchard** [comment]
https://www.zooniverse.org/lab/6/workflow/6/ (so project 6 and workflow 6?) thanks!

**Comment by edpaget** [comment]
Would adding a toggle for the activated state in the front-end be acceptable or should reactivation happen automatically?

**Comment by chrissnyder** [comment]
Pinging @aliburchard for thoughts
