### ISSUE TITLE
Taking a really long time for the Notes board to display

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1546]
A volunteer noticed that the Notes board on P4: Terrains seems to be taking much longer than normal to load. I noticed that as well. It does load though, but it takes 30s to show something. After 30s, then you see the list of threads and the thumbanails. It was faster than that before.  I thought I'd mention it. Is this related to https://github.com/zooniverse/MarsZoo/issues/151 ?

**Comment by aweiksnar** [comment]
Looks to be good now, @mschwamb reopen if you disagree

**Comment by mschwamb** [comment]
Thanks fr the reply @aweiksnar . I think it's still slow on P4 Terrains Notes board  but okay on the other boards and other projects' Talk. Not sure what happened. Before AnnoTate launched is was faster for that board to load. Checking Whales and GZ Bars, their notes threads are more responsive. Not sure what''s the specific difference.

**Comment by aweiksnar** [comment]
@mschwamb I'm seeing load times of 4-4.5 seconds on that page

**Comment by mschwamb** [comment]
I'm at  30s, maybe something with the distance and servers to Taiwan? I'll close since you don't see it taking a long time to load.

**Comment by aweiksnar** [comment]
Ah weird, sorry that it's taking so long!

**Comment by camallen** [comment]
@mschwamb we should probably check this out. Can you send some screen shots of the network queries from the web browser console? e.g. http://code.tutsplus.com/articles/chrome-dev-tools-networking-and-the-console--net-28167

**Comment by mschwamb** [comment]
![screen shot 2015-09-11 at 10 50 53 pm](https://cloud.githubusercontent.com/assets/753325/9817813/b0b6603a-58d7-11e5-8c81-23980bfff0cc.png)
