### ISSUE TITLE
clarity of questions

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes-Front-End#155]
I understand that the scientists will have complete control over the wording of their questions but we need to strongly encourage the scientists to make clear why each question matters very clear. For example, in Snapshot Supernova, the first question asks if the candidate is properly centered. Why does this matter? Why could a supernova not be in (say) the top right hand corner of a image. Or if there is something in the top right hand corner - why could it not be a SN? The last question asks is the candidate part of a larger structure? Again, why does this matter? We need to encourage the science teams to use the help option at each step to explain why the volunteers are being asked a certain question.

**Comment by mkosmala** [comment]
I think this is just one of many things that Zooniverse has gotten good at doing that won't be common knowledge to new science teams. If possible, y'all should write up a "best practices" document for scientists to use when making new projects.

**Comment by karenlmasters** [comment]
I think it would be good to allow for feedback on project design very explicitly in the interface. That may already exist (sorry if it doesn't and I don't know that!).

**Comment by vrooje** [comment]
I've added some related help text to the document @aliburchard created in #300 so that it explicitly recommends the researcher tell the volunteers why they are being asked to do the task.

**Comment by chrissnyder** [comment]
Looks to be a number of different points being addressed here, and I think the help text added directly addresses the original question.
