### ISSUE TITLE
Classifications not saving/moving to next

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1550]
This is specifically for retinas (https://www.zooniverse.org/projects/zooniverse/field-of-vision/classify/?workflow=162), but clicking "done" is broken. Specifically, it seems to save the classification and displays the subject *without* the cropping (so it zooms back and displays the original subject), but does not advance to a new subject or move to the first task associated with a new subject.

This is happening in Chrome, Safari, and Firefox.

see:
<img width="1280" alt="screen shot 2015-09-11 at 14 16 00" src="https://cloud.githubusercontent.com/assets/6217406/9824005/b01418c2-588f-11e5-8de1-4b10f58bcde6.png">

@brian-c or @eatyourgreens could one of you take a look? thanks!

**Comment by brian-c** [comment]
Crap, sorry, I got this.
