### ISSUE TITLE
Sub-task pop up box does not show up on IE 11

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#1557]
This issues was reported in this talk thread https://www.zooniverse.org/talk/13/4176/

"The pop-up box does not come up in my web browser - which is internet explorer 11 (on a windows OS - windows 7). Its probably not an OS issue as I just tried google chrome now and I can see the pop-up box on that (now that I know to expect one !)"

**Comment by srallen** [comment]
Fixed in zooniverse-ui/modal-form#10. Version just needs to be updated for PFE.

**Comment by srallen** [comment]
Version bumped.
