### ISSUE TITLE
Aggregation?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1558]
Hi @ggdhines, I was wondering where aggregation stands for:
(1) simple question trees
(2) points
(3) polygons

Back in July, it looked like aggregation for simple question trees was just about done. Do you have a production-ready script for that now? 

I've got 6,000+ retired subjects now and will be doing aggregation over the next few months. It would be nice to not need to reinvent the wheel. If you've only got partial scripts (Python?) for some aggregation tasks, I'd still be happy to use them.

**Comment by ggdhines** [comment]
See email to you.
