### ISSUE TITLE
Comment deleted from moderator controls not really deleted...

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1560]
I'm not sure what happened here. I tried to delete this comment, and it sort of deleted, but not really...

See last comment of this discussion:
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/62/1787/

**Comment by parrish** [comment]
Oh funny.  It's still showing the comment focus.  I'll get it fixed shortly.
