### ISSUE TITLE
Everytime you post in a notes thread it copies the subject

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1572]
@parrish and @aweiksnar I think a change in the api to make sure notes comments are associated with the subject now causes each post in a notes thread  (after the original post) to post the subject image with the reply

![screen shot 2015-09-17 at 6 17 55 am](https://cloud.githubusercontent.com/assets/753325/9920114/f6f98876-5d03-11e5-99ad-c02878cb2c85.png)

See https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/8/4820/

**Comment by parrish** [comment]
Yep. That would be a side effect of that change. I'll fix it tomorrow
