### ISSUE TITLE
Referencing metadata fields in Classification / Help text

### ISSUE THREAD

**Issue by bruggsy** [zooniverse/Panoptes-Front-End#1573]
Wondering if it's possible to reference metadata fields in the instructions or help for classifications. Something like typing {{metadata_field}} and having it be replaced with whatever value that field has for the displayed subject.

**Comment by chrissnyder** [comment]
Not at the moment, but that's a really good idea.

**Comment by vrooje** [comment]
Excellent idea.

**Comment by parrish** [comment]
I'm going to close this for now.  I think the use-case was covered when per-workflow tutorials were introduced.

**Comment by vrooje** [comment]
I thought this was only a bit about tutorials, but also about being able to have a workflow with a question task like:

"Do you see any {{//species_guess}} in this image?"

where "//species_guess" is a pre-classification guess about what's in the specific image and the user is being asked to verify. (For example.)
