### ISSUE TITLE
data exporter broken?

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1576]
the csv downloader doesn't seem to be working at the moment - is it just me? The last "classification data is ready" email I had was on the 11th despite making data requests more recently than then - the file that is available on the export page at "Most recent data available requested" always just links back to the same file from the 11th.

**Comment by camallen** [comment]
The latest export is still running.

**Comment by mschwamb** [comment]
@camallen would it be worth a line on the project builder saying the export could take over an hour, so people have an idea of how long it would take?
