### ISSUE TITLE
Feature Request: Arrow tool

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1579]
In a recent workshop, we realized we'd like the ability to mark a feature off screen. Would be great to have a variation on the line segment tool that has an arrow at the end.

**Comment by chrislintott** [comment]
I don't think this is wontfix. I think it's a low priority, but at some point would be very useful.

**Comment by brian-c** [comment]
We already have a line tool, which inherently has a direction. Can we just add a way to indicate that?

**Comment by chrislintott** [comment]
Would that work in cases where we’re not doing anything meaningful with a direction.

Do we record first and last points? Could for now we just instruct people which way to draw?

**Comment by aliburchard** [comment]
I think instructing people which way to draw, and preserving order of points in the data out, is a great solution.
