### ISSUE TITLE
Linking an image to a comment

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes-Front-End#1581]
![linked-image](https://cloud.githubusercontent.com/assets/122990/9940669/da8024ba-5d36-11e5-81ac-f8cb0698cfa1.gif)

It feels like a non-obvious step to find the image, hover it, then select it.

I think we should either add some text explaining this or (ideally) automatically select the image.

@aweiksnar Thoughts?

**Comment by parrish** [comment]
Also, @DarrenMcRoy have you heard any complaints/feedback about this?

**Comment by DarrenMcRoy** [comment]
Nobody has brought it up that I know of.

But it might be cool that if you link an image, or mention an ID, the tool suggests that you use that as a linked image.

**Comment by DarrenMcRoy** [comment]
How would you theoretically do it otherwise? Willing to defer on the UX to you if you think there's a better way.

**Comment by parrish** [comment]
A couple ideas to improve it:
  - prompt the user to click the image to select (instead of hover, discover the button, then click it)
  - select the image as soon as it is found (by typing in the search box) -- click clear to remove it
  - add a button to search instead of requiring the user to hit enter (button also implies enter as an option)
  - autocomplete search results
  - pre-populate with multiple recently seen / favorited / collected subjects

**Comment by aweiksnar** [comment]
Yeah agree all-around here. I may play with this in a modal too

**Comment by DarrenMcRoy** [comment]
Semi-urgent: Image linking appears to have completely broken. Did we change something? @aweiksnar @parrish 

![screen shot 2015-09-18 at 10 43 55 am](https://cloud.githubusercontent.com/assets/8987864/9963661/fb48094a-5df1-11e5-9794-3a8233918f75.png)

![screen shot 2015-09-18 at 10 44 06 am](https://cloud.githubusercontent.com/assets/8987864/9963669/00b3e73c-5df2-11e5-8fa5-9035c4d6fb9e.png)

**Comment by parrish** [comment]
Sort of.  If you select a recent subject, it's posting with the recent id instead of the subject id.

**Comment by parrish** [comment]
@aweiksnar That code hasn't changed, but maybe the API did?  Should we just follow the links from the recents to get the subjects?  We can get the subjects via an include, but I don't know how the api client exposes included/linked records.

**Comment by aweiksnar** [comment]
@parrish Just issued a PR with that. Working for me on everything except 'kitteh zoo' subjects, for which the api recents links are to subjects in a different project

**Comment by parrish** [comment]
Cool, thanks.  A couple things.

Has that ever worked?  Or did the API just change the response?

I can't seem to access included records via json-api-client (it's requesting them again).  Am I missing something or should I create an issue for that?

**Comment by parrish** [comment]
@DarrenMcRoy Should be fixed now

**Comment by DarrenMcRoy** [comment]
Thanks guys!

**Comment by aweiksnar** [comment]
@parrish Yeah I've definitely attached linked subjects in that manner in the past. 

I think the accessing resources issue may be related to this https://github.com/zooniverse/json-api-client/pull/12 . I do get back `linked` resources in the api response, but I don't believe they're currently exposed in the client

**Comment by DarrenMcRoy** [comment]
@aweiksnar @parrish I don't know if this is a related issue, but I suspect so...

The first post in every single thread right now is displaying a Snapshot Supernova image as the linked image. whoops?

**Comment by parrish** [comment]
What?  Can you link to something?

**Comment by DarrenMcRoy** [comment]
Pick a thread, any thread.

https://www.zooniverse.org/talk/13/6628/
https://www.zooniverse.org/talk/13/6312/
https://www.zooniverse.org/talk/13/5535/

![screen shot 2015-09-18 at 12 49 10 pm](https://cloud.githubusercontent.com/assets/8987864/9966598/6d917e8a-5e03-11e5-820d-3ca903cdd8bd.png)
![screen shot 2015-09-18 at 12 49 05 pm](https://cloud.githubusercontent.com/assets/8987864/9966599/6d921836-5e03-11e5-9546-6ba8ccf358f5.png)
![screen shot 2015-09-18 at 12 48 59 pm](https://cloud.githubusercontent.com/assets/8987864/9966597/6d8e9904-5e03-11e5-9d0c-49280fa010c3.png)

Goes for individual project Talks, too.

**Comment by parrish** [comment]
#1590 fixes it
