### ISSUE TITLE
Should only certified projects show up as your landing-page recent projects?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1584]
I personally believe that the Zooniverse landing page should only show the last four **certified/official Zooniverse projects** that a person has classified in, for a couple of reasons:

- It's sort of a form of promotion. We are suggesting activity to a returning user, appearing on our front page under our banner logo. We should suggest that such activity be directed towards projects with science goals.

and:

- Public/beta projects can look ugly -- bad names, missing avatars, etc. Is that really what we want to present people with upon arriving -- even if they just happened to test it quickly as a beta?

Was discussing before in Slack with @chrislintott and @jwbmartin but @edpaget was less keen, so... discuss?

**Comment by jwbmartin** [comment]
Official projects are our bread and butter so I do feel like they should take precendent. As I also mentioned on Slack, it might also be nice if it recommended similar projects to the ones a user has already explored. But I also have plans to redesign the landing page at some point in the near future to make it a bit more engaging.

**Comment by edpaget** [comment]
This would require extra server support to make it possible (sorting user project counts by project type).

**Comment by chrissnyder** [comment]
I see the point, but I also don't want us getting lost in the weeds before we tackle a larger redesign. Let's punt to later.

**Comment by jwbmartin** [comment]
Might not be a bad idea to table it for a bit because I am going to come in and shake things up once I get settled in.

**Comment by edpaget** [comment]
:scream:
