### ISSUE TITLE
Only 2 projects listed with change projects button

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1596]
![screen shot 2015-09-19 at 8 54 54 am](https://cloud.githubusercontent.com/assets/753325/9973810/47d65a90-5eac-11e5-9caa-0e130f093576.png)

**Comment by mschwamb** [comment]
Logged-in or not doesn't change what's listed

**Comment by CKrawczyk** [comment]
I am seeing the exact same thing.

**Comment by aweiksnar** [comment]
Closed in #1604
