### ISSUE TITLE
Allowing project teams to specify the image used on on the Zooniverse home project list card

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1597]
Currently only the avatar picture becomes the image on the card shown on the Zooniverse projects page. Since it's a much larger image region and not circular like the avatar circle for project builder projects, would it be possible to have a spot in the project builder where one could upload an image specifically for the project page placard ?

**Comment by vrooje** [comment]
I think this would be useful.

**Comment by mschwamb** [comment]
Apparently a duplicate of  #232
