### ISSUE TITLE
Weird formating error with text font and flowing off the page in certain Talk replies

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1599]
I've been seeing weird formatting  popping up in certain posts on Talk - not sure how it's allowed or happening, since I though the Zooniverse flavor of markdown doesn't have fonts.  Mainly it's that it goes off the page horizontally making it  hard to read when it does happen. 

It might be when the person is on their tablet since they've mentioned they use both a tablet and a computer when classifying on Planet Four

An example:
https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/29/3494/?comment=6783

![screen shot 2015-09-19 at 10 08 13 am](https://cloud.githubusercontent.com/assets/753325/9974149/783759a0-5eb6-11e5-8003-c49c0bba9b88.png)
![screen shot 2015-09-19 at 10 08 17 am](https://cloud.githubusercontent.com/assets/753325/9974150/7879126e-5eb6-11e5-8f51-bb34d43af079.png)

**Comment by eatyourgreens** [comment]
Noting here, for posterity, that you can trigger this by starting a comment with four spaces. Four spaces of indentation creates a code block in Markdown, so Talk is displaying these comments as code. See this Talk conversation: 

A simple fix would be to trim leading whitespace from comments before parsing them as Markdown.

**Comment by eatyourgreens** [comment]
#7106 fixes this properly (both the monospaced font and the text wrapping.)
