### ISSUE TITLE
Snapshot Supernova poject live but missing Talk boards and background

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1601]
Not sure if this the right place to post this, I noticed [Snapshot Supernova](https://www.zooniverse.org/projects/zooniverse/snapshot-supernova/talk/) is back live. It's Talk boards aren't configured. Also there's new background like the original. Thought I'd mention it

**Comment by edpaget** [comment]
Yeah ideally this is a place for bug reports/feature requests about the software. Project questions seem like they belong on Zooniverse Talk instead.
