### ISSUE TITLE
Found an image that can't be linked and breaks linking

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1605]
I saw someone discussing Subject 873609 here:

https://www.zooniverse.org/projects/zooniverse/wildcam-gorongosa/talk/79/2129/?scrollToLastComment=true&page=1

But when I tried to make a comment linking to it -- searching for the image, then selecting it -- I couldn't select the image. Not only that, after trying, I couldn't select any other images, either.

This might not be an issue confined to just one image, either. Any idea what's going on here? @aweiksnar and @parrish -- try making a comment with that image linked -- any luck?

**Comment by parrish** [comment]
Yeah, it's not just that subject.

Searching for the subject: https://www.zooniverse.org/api/subjects?id=873610

Selecting the subject: https://www.zooniverse.org/api/subjects/873610/subject

Looks like it's trying to access it as if it is a recent.

**Comment by DarrenMcRoy** [comment]
Ah, yeah, it looks like you can only really select images that are recents.

I can access images that I've recently classified, but nothing that i haven't.

**Comment by parrish** [comment]
PR in #1606
