### ISSUE TITLE
Interface customization

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#161]
I'm wondering which, if any, of the following will be customizable by science teams?
* font for questions
* font color for questions
* button colors for questions

These last two may be especially important because they lie directly on top of the background, and so, for example, a science team could not choose a light-colored background if the font for the questions will always be white.

**Comment by brian-c** [comment]
Fonts will not be customizable.

Drawing tools will have a color which will be reflected somehow on the tool (I think it currently colors the tool's icon).

It is important that we don't allow users to customize things in ways that will limit our ability to iterate on design. The existing layouts were not done by the current designer and might change significantly before (and no doubt after) launch.

**Comment by mkosmala** [comment]
"It is important that we don't allow users to customize things in ways that will limit our ability to iterate on design. The existing layouts were not done by the current designer and might change significantly before (and no doubt after) launch."

What does "iterate on design" mean? What does it mean that existing layouts were not done by the current designer? And by launch, you mean Panoptes launch or launch of individual projects? Sorry, I just don't understand the second paragraph.

Also, sorry, I meant the "Back" and "Next" buttons, which are currently gray and green respectively. Also not customizable?

**Comment by chrissnyder** [comment]
Quick question from myself who is entirely out of the loop, is this project primarily working through the API at an external URL, or is it entirely built within the project builder? And as a followup, if it's just consuming the API, what's the benefit for trying to stick your content into the fields provided?

**Comment by mkosmala** [comment]
@chrissnyder It is not built entirely within the project builder, because the project builder isn't far enough along yet. I am working mostly with the API. Not sure what you mean by an "external URL". 

Also not sure what you mean by "trying to stick your content into the fields provided". What fields are you referring to?

**Comment by chrissnyder** [comment]
External URL as in the site itself doesn't live on zooniverse.org.

Sorry, I confused this issue with #163, but the logic sort of follows. If you aren't building the site within the project builder, then couldn't you make the buttons whatever color/font you want?

**Comment by chrislintott** [comment]
Margaret and I just talked - let’s chat, Chris, Brian.

**Comment by mkosmala** [comment]
@chrissnyder Just talked with @chrislintott and sorted out the confusion. 

So, while I'm using the API to build the project, I'm hoping to use Pantoptes-FrontEnd as the volunteer viewer. Basically, I'd be happy to use the project builder, but I want to launch sooner than we could if I had to wait for that to be finished. Hoping to have our project live on zooniverse.org and use the FrontEnd just as Snapshot Supernova is. 

And... @chrislintott beat me to a response. He'll fill in the details.

**Comment by chrissnyder** [comment]
Ah that makes sense. Sorry for the added confusion.
