### ISSUE TITLE
Document needed: So you're a Zooniverse project. Now what?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1611]
We should probably have some kind of short document that we give to newly approved projects that outlines the basic resources Zooniverse projects have access to (where the GitHub repos are/bug reports, that sending newsletters is possible, the Zooscientists mailing list and blog and teams FB group, etc). 

This need not be as lengthy or involved as any documentation produced as a result of the Best Practices for Engagement meeting, but could include some of the highlights.

**Comment by DarrenMcRoy** [comment]
Actually, I think this could be folded into the Resources section of the Best Practices document -- what do you think, @vrooje?
