### ISSUE TITLE
Talk link doesn't work from Favorites page

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1619]
There's a link to Talk from a favorites collection -- https://www.zooniverse.org/collections/dzm/favorites-aliburchard-wildebeest-watch/ -- but the link is greyed-out and doesn't work.

Might be a design discussion, or something that we intend to implement later, but right now it's something that looks broken.

**Comment by mschwamb** [comment]
Talk is greyed out for all collections. See closed ticket #885
