### ISSUE TITLE
Build image dimensions-setting into Zoo-flavored Markdown

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1620]
Per a conversation with @aweiksnar -- being able to set the dimensions of images (sizes) is quite important for our users. It's been requested since the very beginning of this Talk development (the BOTID), and the coding @parrish did for Chimp & See made the whole ChimpID process possible.

(To quote from DaringFireball: "As of this writing, Markdown has no syntax for specifying the dimensions of an image; if this is important to you, you can simply use regular HTML <img> tags.")

Alex says this isn't too hard to build in. Not sure if we can borrow from what Michael did on the old Talk for C&S?

(Also, Michael made it possible to hyperlink images, too -- including resized images -- which was also nice and fairly important.)

**Comment by parrish** [comment]
I had checked once upon a time and the markdown parser we were using supported the format.  Not 100% about what we're using now.

**Comment by parrish** [comment]
Yep, there's a plugin for it.  I'll send a PR soon.

**Comment by parrish** [comment]
Pull request here: zooniverse-ui/markdownz#19
