### ISSUE TITLE
Admin Status for experimental features

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1622]
@brian-c can we tweak the way that admin status works such that any collaborator on an approved *project* can add the experimental feature?

I'm running into this issue because I'm working with a few projects to build camera trap survey tasks. There are two issues:
1) I'd like the other researchers (not me) to be the project owners. This is partly for display purposes - I don't want their projects, once live or approved, to fall under "aliburchard/..." because I'm only tangentially associated. But this is also in part because these other research teams often *start* building a project with the standard tools and then approach me for the filtering task later. Currently I need to create a new project and start over with all the existing project info & assets.

2) I'd like the other researchers to be able to add the camera task. This isn't normally an issue, but one of the more recent collaborators seems to keep "losing" the survey task, and has to wait for me to add it back in. 

I guess the overarching question is: can we wire up experimental tools such that *we approve certain projects for certain tools and that all collaborators on that project are able to use the specific tool?*

**Comment by brian-c** [comment]
Yes, we should have a general way for people to opt in to experimental features. We've got a couple ideas floating around in the issues, I forget if we ever decided on the best one.

**Comment by camallen** [comment]
Per project features enabled key i think that is admin restricted ala [here](https://github.com/zooniverse/Panoptes/blob/f4c3e7eb4d4cea32f2b0397198b5d940ed5cdb96/app/controllers/api/v1/projects_controller.rb#L154). 

Would it make more sense to be per project or per workflow?

**Comment by aliburchard** [comment]
@camallen good question.  I'm inclined to say that enabling experimental features should be per project -   per workflow feels a bit heavy handed. Also, when I'm building a new project, sometimes I'll make a few different workflows to try and decide on which is the best order of tasks, etc, and I recommend this to project builders as well. Having to authorize a team per workflow seems like it would be time consuming.

@brian-c I do recall the discussion but I don't think there was a final consensus on the best way forward. I would personally vote for us authorizing certain project IDs to have access to specific tools. So, we can Project X has access to the filtering task, but not the cropping task, and anyone working on Project X can add the filtering task.

**Comment by CKrawczyk** [comment]
I also think per project would make the most sense for this.  As a side note, how do we expect projects to request experimental tools?  Is it going to be a button in the editor that the use can just switch on (perhaps with a pop up message saying these tools are experimental and may be buggy etc...) or some other type of request.

**Comment by camallen** [comment]
@CKrawczyk - i think we can evolve this over time. Most likely contact us (email?) and put your case forward and an admin user can enable the relevant tasks. Our aim is to build tools and release them to the project builder when we can so i assume the tools won't be experimental for too long.

**Comment by aliburchard** [comment]
This is growing increasingly urgent from my perspective. I have a lot of projects using the filtering survey feature, and it requires me to not only initiate the task, but pre-populate the task data or else the task seems to disappear (see #1695). I'd really like to be able to authorize the *project* ID for using experimental features.

@brian-c @camallen @chrislintott can we bump this up the priority list?

**Comment by camallen** [comment]
I've got a PR for the backend in https://github.com/zooniverse/Panoptes/issues/1385. It's a per project,  admin only setting for an array of tools names that the front end can use to wire up features.

**Comment by chrissnyder** [comment]
@aliburchard Believe this was done? Could we close this?

**Comment by camallen** [comment]
I don't think there is a front-end admin panel area to update this?

**Comment by aliburchard** [comment]
@chrissnyder we are still waiting on a place in the front end for this. I think @edpaget is working on it (either on the zooniverse admin page or on the projects data export page).

**Comment by chrissnyder** [comment]
PR open for it at https://github.com/zooniverse/Panoptes-Front-End/pull/1739

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes-Front-End/pull/1739
