### ISSUE TITLE
Open public workflows for *viewing*

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1623]
I'd like to be able to share what a workflow looks like "under the hood" with other people, but not allow them to edit anything. This came up in the recent best practices meeting as a great way to help new project builders understand how what their putting into the workflow editor translates into actual projects. (For example, you can say "want to build a project like Kitteh Zoo? Explore the project builder for this project!" Or for any other public project, really.) 

In discussion with @camallen, it sounds like this would best be done _not_ by adding a new role, but by changing the checks on the front end. Right now the front end asks if you have a collaborator/owner role before displaying anything on the project builder page for a site. @brian-c could we change that check to just apply to the buttons? Thus allowing any public project to be viewable through the project builder interface?

Would love thoughts from anyone (@chrissnyder @vrooje @edpaget @mrniaboc) about reasons why we might instead want this to be a role instead of making it standard behavior for all public projects.

**Comment by brian-c** [comment]
I don't think we need a special role, since anyone who can classify can see the project and workflow (in the classification interface).

We could allow viewing, but the editor is still disabled for live projects, so nobody'd be able to see very much.

The project builder needs design work like crazy. That'd probably be a good time to implement a read-only view.

**Comment by aliburchard** [comment]
Good point about the editor being disabled...

How trivial would it be to allow viewing on projects? My impression is that it's an easy change, but I don't really know these things.

**Comment by vrooje** [comment]
I'd really like for anyone to be able to see a diagram of a workflow, quite possibly using @CKrawczyk's [workflow editor](https://github.com/CKrawczyk/workflow_editor_react). 

I agree that workflows are already public, so it's just a matter of letting someone see the overview.

**Comment by alexbfree** [comment]
I second @vrooje's suggestion (in fact I was going to suggest something similar but saw she already had). I think it would be hugely useful to have some UI which visualises the branching structure of a workflow and its questions, both for workflow editors themselves, and for people who want to build a new project "like" an existing one.

**Comment by CKrawczyk** [comment]
I agree with @vrooje.  In the coming weeks I will work on making a "view" mode (i.e. read only mode) for my workflow editor and try hooking it up to PFE via a "visualize workflow" button.

**Comment by alexbfree** [comment]
It's worth noting that the Visualize this workflow button is now available even when a workflow is edit-locked. It's greyed out but still clickable.

That said I still think we should make the workflow fully viewable (e.g. to copy and paste text etc)

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
