### ISSUE TITLE
Some hashtags not using up as links on Talk (perhaps due to length?)

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1626]
I noticed this [post](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/10/58/?comment=13500) and screenshot below

There are clear hashtags but they are not hyperlinked. Is it because they are too long?

![screen shot 2015-09-23 at 11 56 24 pm](https://cloud.githubusercontent.com/assets/753325/10050443/eec6119c-624e-11e5-9c59-db420f06cdb9.png)

**Comment by aweiksnar** [comment]
Doesn't look like any are showing up. Thanks for ticketing

**Comment by mschwamb** [comment]
Is it something with the markdown and the change to linking format for ^S. Look at how this hashtag shows up url blue before the subject links and then after the subject mentions the hashtag isn't hyperlink blue. 
![screen shot 2015-09-24 at 1 43 31 pm](https://cloud.githubusercontent.com/assets/753325/10066151/72184c86-62c2-11e5-9d16-dfc15eb34c21.png)

**Comment by mschwamb** [comment]
Though maybe he added the other hashtag in after the issue? This volunteer likes to go back and add more hashtags to his comments and finds.

**Comment by aweiksnar** [comment]
Yeah I made a change to the lookahead to try fix URLs with anchors in them and it ended up having unintended repercussions that our tests didn't catch. I'm working on a fix and it should be in today

**Comment by aweiksnar** [comment]
Just added a PR - https://github.com/zooniverse-ui/markdownz/pull/20
