### ISSUE TITLE
Talk thread supposedly only postable by Zooniverse team members, but I can hit reply and shows textbox

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1627]
I saw this new [Zooniverse Technical Issue Announcements Thread](https://www.zooniverse.org/talk/17/8212/?scrollToLastComment=true&page=1) has been made and it says in there that it is only writeable by accounts with Zooniverse team green stripes, but reply buttons and a text box exist for me. I didn't try to post. Nothing alerts the reader in this thread that's it's ready-only. I think there should be some way of highlighting that and also removing the reply button for accounts where the status to post is less than that needed. 

![screen shot 2015-09-24 at 8 23 02 am](https://cloud.githubusercontent.com/assets/753325/10062480/881d418a-6295-11e5-83b0-ed0e6d6d3962.png)

![screen shot 2015-09-24 at 8 15 29 am](https://cloud.githubusercontent.com/assets/753325/10062466/74096cd2-6295-11e5-9d90-c62abac9fd34.png)

**Comment by DarrenMcRoy** [comment]
Yeah, I believe there's nothing yet to indicate that you can't post in a permission-locked thread. I agree that in such a thread, the box should not appear. Old Talk had that.

**Comment by mschwamb** [comment]
Turns out the thread wasn't locked. Since that's a separate issue I'll close this.
