### ISSUE TITLE
Where do 'introduction' and 'guide' show up?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#163]
Where does the Project attribute 'introduction' show up in the volunteer interface?
Where does the Project attribute 'guide' show up in the volunteer interface?

**Comment by brian-c** [comment]
The `introduction` shows up on the project home page under the description and call to action.

@edpaget what was your intention for `guide`? I've only ever seen it as null. Should it be removed?

**Comment by camallen** [comment]
Probably are more in depth set of text about how to contribute to the project. Does the front-end have any use case for more detailed information about the project and how it works?

**Comment by edpaget** [comment]
@brian-c I had thought it was supposed to be examples similar to the Spotter's guide in SpaceWarps or Galaxy Zoo. We can definitely remove it if you have another way you're showing that info.
