### ISSUE TITLE
Add structure to lab homepage 

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1630]
I'd like to split up projects I see on my www.zooniverse.lab page so that projects are displayed under headings reflecting whether I own them or am a collaborator. 

I'm a collaborator on a dozen or so researcher-led projects, and right now they are jumbled up with projects I own. It's confusing, and I'm never sure if I'm going to break *brooke's* kitteh zoo or my pretend copy of kitteh zoo.

I'd really like to have projects I own grouped together under one heading (e.g. "Projects you own") and projects I just collaborate on under another (e.g. "Projects you collaborate on"). @brian-c @chrissnyder @edpaget how trivial is this to do?

**Comment by alexbfree** [comment]
Relates to #1632 which I just raised - perhaps a solution for the two issues could be designed together.

**Comment by vrooje** [comment]
+1, this would really help me too.

**Comment by mschwamb** [comment]
Also I don't notice if anyone has this, but every time I go to the project builder lab page, my projects are in a different order.

**Comment by mschwamb** [comment]
looks like this was just implemented - looks great.

**Comment by aliburchard** [comment]
it really does look great! closing this.

**Comment by vrooje** [comment]
Yay!
