### ISSUE TITLE
Secondary subtasks on a drawing task are off the page / not reachable

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1631]
I created a drawing task with 4 subtasks. Only the first question is visible, because the balloon has a fixed size with no scrollbar. Also I am not sure if there is supposed to be a button at the bottom of the balloon, because I can't see beyond the first question.

A less critical but related issue, is that the balloon defaults to position below the drawn box. If you draw from top-left to bottom-right, as most Westerners will, this pretty much guarantees you will have to scroll the page down to see what that balloon you saw a brief flash of, was.

![screenshot](https://cloud.githubusercontent.com/assets/1473244/10070882/5965b4ea-62ad-11e5-97a7-1f37f208b891.png)

**Comment by alexbfree** [comment]
Looking at the code, I think it may have been @brian-c or @chrissnyder who coded this feature? If that is correct, could one of you clarify how this is supposed to work? Is this indeed a bug or am I using the feature in a way other than it was intended?

**Comment by srallen** [comment]
I was seeing this when I started to take a look at #1557 and thought it was just an IE bug. The sub-task is using [zooniverse-ui/modal-form](https://github.com/zooniverse-ui/modal-form), but I haven't had the time yet to finish debugging what is going on. The sub-task modal should be getting dynamically calculated left and top positioning (which wasn't happening at all in IE11) based on the position of the mark. What browser were you using when you saw this?

**Comment by alexbfree** [comment]
@srallen It seems to be present in Chrome, Safari and Firefox on OSX.

**Comment by alexbfree** [comment]
An update: Just discussed this at length with @brooke and @aliburchard in #mico-experiments on Slack... We think that extending the balloon is probably the wrong thing to do. Either we need to break subtasks into a sequence of balloons (or move the question to the main question area).... Or in fact, we think an even better option is to limit the maximum number of selectable options (effectively, limiting the number of rows) across all subtasks, to something like 6,7,or 8. So for example you could have 3 two-option questions, or one 8-option question, but really if you have any more options than that, it's an overcomplicated task, and shouldn't be allowed even despite the fact it doesn't fit.

So maybe the real solution here is to limit creation/saving of subtasks if adding a subtask or subtask option would take the number of rows too high.

Something like this:
1 subtask -> max selectable options across all subtasks = 8
2 subtasks -> max selectable options across all subtasks = 7
3 subtasks -> max selectable options across all subtasks = 6

I have done some quick mockups using Chrome Inspector to show that these limits would work.

![one subtask - limit 8](https://cloud.githubusercontent.com/assets/1473244/10078681/aaca014e-62dd-11e5-8d05-2572cb8e117c.png)
![two subtasks - limit 7](https://cloud.githubusercontent.com/assets/1473244/10078682/aacc5eb2-62dd-11e5-8802-2865b4f73160.png)
![three subtasks - limit 6](https://cloud.githubusercontent.com/assets/1473244/10078680/aac9ce86-62dd-11e5-9545-fa5ab6f4146b.png)

**Comment by alexbfree** [comment]
PS @srallen if you want to look at this in action, try looking at `"Main workflow"` in `alexbfree/serengeti-sleuth` project

**Comment by brian-c** [comment]
Moved to zooniverse-ui/modal-form#8 and zooniverse-ui/modal-form#9.

**Comment by alexbfree** [comment]
@brian-c Those linked tickets address the bug that means the questions don't show; but not the larger design question as I raised in the 5pm comment. I think we should keep this ticket open to consider the bigger design question of whether it even makes sense to allow so many subtask options....

**Comment by chrissnyder** [comment]
I strongly disagree that we should impose Zooniverse-style workflow restrictions on the project builder. That is what the review step before launch is for, where we can vet that a project isn't doing something stupid.

If a team decides internally that they want to have 20 options under a sub task, then I don't see why we should disallow them from doing so. Maybe it'll be a small project where they know that everyone who will be classifying on a huge monitor.

Certain restrictions come into play eventually, where we don't want them crashing their browser, or sending back a massive JSON object to the server, but that's a different concern, and not one I'm overly concerned about now.

**Comment by alexbfree** [comment]
@chrissnyder I'm persuaded by your argument, provided we fix the bug that prevents the subtasks displaying (as the linked tickets will). 

@aliburchard @vrooje any comment?

**Comment by aliburchard** [comment]
I agree we should fix the bug. I more or less agree with @chrissnyder, with the caveat that we have always intended this to be an opinionated piece of software, and it's surprisingly hard to communicate what we (the collective zooniverse) has learned about building effective projects, and that I think some of that communication should happen in the builder itself. Part of my feeling on this arises because we don't yet have a way for projects to go out to community review if we think they are not yet ready to email to our beta list - thus putting the onus on us to provide personalized suggestions and reviews. 

However, I agree that instead of forcing zooniverse-style workflow restrictions, we should be opinionated with our help and messaging. This came up in the best-practices workshop -- this is a point that would be perfect for a pop-up message saying "are you sure you want to add more than X subtasks? aggregating data from sub-tasks is really tricky. have a look at these other projects for examples of workflows that get around using lots of subtasks.

**Comment by vrooje** [comment]
Agreed with @aliburchard -- this would be a good example of where we can insert warnings (but not necessarily restrictions) and intervene with project builders to explain why what they're trying to do is usually a bad idea, but let them make the final decision.

**Comment by alexbfree** [comment]
@srallen @brian-c @chrissnyder (sorry I'm not sure which person fixed this in the end). I think this was basically fixed, except that I see a warning is now added inline within the balloon. Ironically the vertical height taken up by this warning is re-introducing the problem, making the OK button and bottom question un-completable.... 

![screenshot](https://cloud.githubusercontent.com/assets/1473244/10544830/855cdea8-741d-11e5-9baa-d3b7ce2457b4.png)

Could we display the warning in a secondary alert or similar only when there is a problem rather than wasting valuable space in the balloon? Maybe when you try and click next, and haven't completed all subtask required questions - the balloon pops open?

Either that, or increase the allowed vertical height for the balloon by (required message height * number of required subtasks)....

**Comment by vrooje** [comment]
Also, separately from project design issues, is there a way to make sure the same amount (hopefully all, if the questions aren't too long) of the subtask window shows on the screen no matter where the drawing is on the subject image? Right now if it's at the bottom of the image it will often fall off the scrollable part of the screen even if there are just a few options.

**Comment by alexbfree** [comment]
@vrooje I noticed that too - also if you draw a big box that goes a long way outside of the image your balloon can appear in strange places! I wonder if we should constrain box drawing to snap to the edges of the image and not allow any box bigger than that...

**Comment by alexbfree** [comment]
We've been having some further discussions on this on #beta-review and later on #subtask-discussion on Slack. Some level of agreement (myself, @DarrenMcRoy and @vrooje at least) that we do need to fix it so that the amount of the popup window that's accessible doesn't vary depending on browser size, where you draw the mark, or the length/requiredness of the questions... it should always be all accessible.

We're also agreed there is a good workflow design issue, which needs addressing, but we shouldn't discourage bad design by having things break without warning....

**Comment by DarrenMcRoy** [comment]
In case anyone wasn't aware, this became an issue that received a ton of commentary with the Faces of the World beta. Although we're passing on that project right now, it still revealed that this is an issue that can pop up with Project Builder projects.

**Comment by alexbfree** [comment]
So @chrissnyder do you think we can push to get this issue fixed on that basis? Just asking you because I'm not sure who's the best person to work on this, you can redirect if needed.....

**Comment by brian-c** [comment]
I'll get to work on this when I'm back in Thursday.

**Comment by alexbfree** [comment]
Brilliant thanks @brian-c .
