### ISSUE TITLE
Talk conversations on subject board linking to other subjects' discussions

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1634]
From the P4 Terrains moderator:

"Just classified 489888 then added #dustdevil in talk. When I clicked enter my comment came up attached to 489982 - checking back it's also on 489888. Strange!"

And if you click on the second discussion listed https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/subjects/489982 it takes you to https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/29/3050/?comment=5940 which is a note for  Subject 489888 on the title but says Subject 489982 underneath it 

![screen shot 2015-09-24 at 10 08 15 pm](https://cloud.githubusercontent.com/assets/753325/10075527/ccbb9c24-6308-11e5-91a8-85194e962b64.png)

**Comment by parrish** [comment]
Yeah, that's pretty funky.

It assigned the focus of the discussion to 489888 and so all the other comments are also focused on it.

The first comment (yours) was assigned a different focus (489982).

@aweiksnar Any idea how this happened?

The setup would be a discussion created with `focus_id: 489888` and Meg's comment created with `focus_id: 489982`

**Comment by aweiksnar** [comment]
@parrish I'll look into this one today

**Comment by parrish** [comment]
I haven't seen this bug in the wild.  Has this still been happening?

**Comment by mschwamb** [comment]
Only that time. I think I recall it was a day when Talk was abnormally slow. Closing. I'll reopen if I see it again.
