### ISSUE TITLE
Sticking the subject allowance and total number of subjects already uploaded in the project builder

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1635]
Currently there's no way for a research team to quickly know the total number of subjects uploaded in that project for all subject sets combined (without manually clicking on each subject or downloading the subject manifest). Also there's no way on the project builder at present to  learn what the current cap on subjects they have uploaded is  in order to contact the Zooniverse development team for an increase of the subjects limit before they starting trying to upload a new batch of data. 

Currently I have to keep track of the cap separately in my notes, but I think it would be helpful to have in the project builder somewhere it lists the total number of subjects uploaded for the project and the current subject limit for researchers before they try to upload 6000 subjects but only have a cap to add an additional 2000.

**Comment by camallen** [comment]
We've now got some stats on the project home page, https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/
![image](https://cloud.githubusercontent.com/assets/295329/10098330/788d8160-6378-11e5-82cf-38b1c17482e7.png)

I agree, we should probably put some messaging about user subject limits in the project builder. I'll look into that.

**Comment by aliburchard** [comment]
This is a brilliant idea.
