### ISSUE TITLE
Can't search by hashtag on Talk, returning back a string search of all content when you click on hashtag link

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1648]
When you click on the hyperlink for a Talk hashtag it takes you to a search result, but that search isn't actually doing any search by the hashtag it returns back any comment when the text minus the # of the hashtag is present. For example if you click on the '#ice' hashtag from the side bar of P4: Terrains talk the search results include these responses which don't have any hashtags.

![screen shot 2015-09-26 at 7 12 24 am](https://cloud.githubusercontent.com/assets/753325/10114579/c7696d32-6425-11e5-9d21-600a8ae6361a.png)

![screen shot 2015-09-26 at 7 10 36 am](https://cloud.githubusercontent.com/assets/753325/10114585/f2dfbf7a-6425-11e5-9d1b-b38d2d7788c0.png)

Also other Talk posts that have hashtags which include part of the word are returned rather than the exact '#ice' hashtag

![screen shot 2015-09-26 at 7 09 51 am](https://cloud.githubusercontent.com/assets/753325/10114598/21091ba8-6426-11e5-96f9-89500c874de8.png)

Advanced users use the hashtag search to do their own reviews and vetting of subjects flagged by other volunteers. I use the hashtag search to find examples and to find what hashtags are useful to get images we use for data quality checks.  It's harder to sift through the results when other content is in there. 

Would it be possible that when you click on the hashtag hyperlink it returns back only results with the hashtag and also allow in the Talk search that if the string starts with the pound sign it indicates you're searching for hashtags and not a string search?

Searching by clicking on the '#mound' and this was returned in the search

![screen shot 2015-09-26 at 7 13 23 am](https://cloud.githubusercontent.com/assets/753325/10114573/a58d88c4-6425-11e5-98ef-5a0877634788.png)

**Comment by mschwamb** [comment]
@parrish I was wondering if this was an Talk api request/feature. If so, do you prefer I post a issue in that repo?

**Comment by parrish** [comment]
Right now the tag links are just using the regular search.  Here's a bit about how tags factor into the results:

- results are returned in order of relevance
- tags are more heavily weighted towards relevance than regular text
- queries are [stemmed](https://en.wikipedia.org/wiki/Stemming), so non-exact matches will show up

All that said, Talk-Api provides an api for finding tagged subjects by exact match: zooniverse/Talk-Api#55:

> Most popular tags for subjects on a project:
> GET /tags/popular?taggable_type=Subject&section=project-123
> 
> Most popular tags for a specific subject:
> GET /tags/popular?taggable_type=Subject&taggable_id=123
> 
> Subjects by most common tag usage -- find all subjects with a tag, ordered by most usages
> GET /tags/popular?name=whatever&taggable_type=Subject

Since it is a different resource, a separate interface would need to be built out in the front end.

I probably won't be able to get to this for at least a couple weeks though.

**Comment by DarrenMcRoy** [comment]
An overall refined search-results page was also one of the five Talk priorities we identified a while back, but it has been considered secondary to a refined subject page.

**Comment by parrish** [comment]
Honestly, I consider the tag search to be entirely separate from search (different use cases).  If we do present it from the same page, then it should be a distinct view of some sort.

**Comment by DarrenMcRoy** [comment]
> If we do present it from the same page, then it should be a distinct view of some sort.

I like this, although Twitter doesn't really do it this way. You can search by a word, which will bring back all examples of the word, including hashtags, or by a hashtag, which will bring back exclusively the hashtags.

I'm good having a unique view, though -- hence, as above, the reference to a "refined search-results page." :-)

**Comment by chrissnyder** [comment]
@parrish Thanks for the input. I don't consider this a ToDo, just trying to figure out the space.

**Comment by mschwamb** [comment]
Whether to add this capability in is a decision for the core team and development team, but I do consider this a core functionality of Talk that's missing in the Panoptes version.

Here's my perspective as a researcher who uses Talk.  The behavior on previous Talks has been that you click on a hashtag it searches for the hashtag.  I use this all the time on the previous versions of Talk once the projects are more than a few months old. I use it to get examples  for blogs and actually had my summer student using this on P4 talk earlier in the year to find a sample of 30 images for her to mark boulders in by hand especially since it has the option of returning back a subject list. We did a separate review of all images for a different aspect (and I used the full Talk metadata), but to get a quick sample of images the hashtag search has been an incredibly handy feature. 

The ability for search for strings didn't work as well on previous versions of Talk, but the hashtag search was being used often in Talk 2.0 at least on the projects I've been involved with and especially with advanced users who are active on Talk but no longer engaged in classifying because they have evolved beyond the classification interface task. The super users, use the hashag search on previous version of Talk to be able to find subjects of interest to vet or collect. I believe this is one of the ways the Planet Hunters super users  find other people's planet candidates to then go verify and has resulted in many papers. 

So I think it has become an expected feature. If you click on a hashtag on Talk 2.0 it brings you to this url search http://talk.planetfour.org/#/search?tags[fans]=true and if you search for a term one of the options it to select it to be refined to a hashtag. 

![screen shot 2015-10-10 at 1 23 34 am](https://cloud.githubusercontent.com/assets/753325/10400898/2bcf6826-6eee-11e5-983b-9f4acca3f1b0.png)

I've had  3 volunteers who now participate now on Planet Four: Terrains who are active (and still are)  on Planet Four message me saying something was wrong and they couldn't search by hashtag shortly after launch.  I didn't realize until now that you actually couldn't since the examples I tested did bring up hashtags, I thought it was just confined at the moment to returning back posts at the moment rather than being able to return back a list of subjects.

**Comment by parrish** [comment]
> I do consider this a core functionality of Talk that's missing in the Panoptes version

Me too.  It's on the list

**Comment by mschwamb** [comment]
Thanks very much @parrish

**Comment by parrish** [comment]
I felt like a change of pace, so I've got a start on this.  https://github.com/parrish/Panoptes-Front-End/tree/tag-search

Shouldn't be too much more work past this point (just style, linking, and tweaking it).

**Comment by mschwamb** [comment]
Wow! Cool. Thanks. If there's a way to filter to subjects associated with tags that would be great, but having any capability to search on tags is fantastic.

**Comment by parrish** [comment]
PR in #1743.

> I'm linking project popular tags to this (subjects tagged with #tagname)
> Non-project popular tags still link to text search.
> I *think* that's probably the right thing to do.

**Comment by mschwamb** [comment]
Amazing! Thanks @parrish. I noticed one bug. It  returns one subject per page and I think the text 'Your search returned 241 tags.' you meant subjects instead of days. 

Other suggested improvements are including subject id and also allowing that  you cant click it to get to the subject page. Should I open those up as separate tickets on the front end rather than reopen this ticket?

**Comment by parrish** [comment]
Subject link fixed here: zooniverse/Panoptes-Front-End#1751

Single results fixed here zooniverse/Talk-Api@0fd4d2a9766746
