### ISSUE TITLE
Can't favorite or add an image to a collection for subjects in someone else's collection

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1652]
If you're viewing other people's collections on the Collect Page, the favorite and add to collections buttons disappeared. I think people will peruse collections and want to be able to favorite a striking subject they noticed or add the subject to a collection they're make of one type of feature they found on a project. If possible, can the favorite and collect buttons be added back to the thumbnails viewed in collections

![screen shot 2015-09-27 at 4 33 57 am](https://cloud.githubusercontent.com/assets/753325/10119746/d3dbd706-64d1-11e5-9c06-8822748aa75e.png)

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
