### ISSUE TITLE
<H2>, <H1> heading markdown button not generating the proper markdown

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1653]
When you hit the heading button is 

generates #//  with_your_text_in_the_middle  ##

The '//' is preventing it from generating the header properly 

![screen shot 2015-09-27 at 12 23 27 pm](https://cloud.githubusercontent.com/assets/753325/10121196/c8ca78e0-6512-11e5-8d41-78a605f00c0f.png)
![screen shot 2015-09-27 at 12 23 30 pm](https://cloud.githubusercontent.com/assets/753325/10121195/c8ca4d20-6512-11e5-9b25-37d823043ab3.png)

**Comment by aweiksnar** [comment]
Fixed in zooniverse-ui/markdownz@3.0.1
