### ISSUE TITLE
The role labels, user avatars and comment details (date, time) are not showing on the subject page

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1655]
The role labels, user avatars and comment details (date, time) are not showing on the subject page. Tested on Gorongosa and Whales, using Firefox on Ubuntu, and then on Chrome on Yoga tablet. Both the same results.

Like here: https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/talk/subjects/481016

![screenshot_2015-09-27_18-46-21](https://cloud.githubusercontent.com/assets/7211888/10124035/5ea12706-654a-11e5-8b80-52f431cadb6f.png)
![screenshot_2015-09-27_18-47-15](https://cloud.githubusercontent.com/assets/7211888/10124030/540b6e14-654a-11e5-9feb-a277c376e24c.png)

**Comment by aweiksnar** [comment]
They've never appeared here, but could definitely be added. I wonder if this issue could be part of the discussion in #1271
