### ISSUE TITLE
beta project link bug

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#1657]
The link sent in an automated email when a project requests beta is a bit weird. It still works, but there is duplication of the path.

E.g. https://www.zooniverse.org/projects/pszmt1/faces-of-the-world#/projects/pszmt1/faces-of-the-world

**Comment by camallen** [comment]
for reference, the email contains this link, https://www.zooniverse.org/#/projects/pszmt1/faces-of-the-world

**Comment by edpaget** [comment]
This is a Panoptes backend-issue.

**Comment by camallen** [comment]
the email contains the correct link just with an anchor tag...the front end should reconstruct the url correctly, no?

**Comment by edpaget** [comment]
It depends on the browser.

**Comment by edpaget** [comment]
Anyway, the porblme is that the it's not the correct link if it has the anchor tag.
