### ISSUE TITLE
Why is there 'This step is required. If you’re not allowed to continue, make sure it’s complete.' text ?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1666]
I'm a bit confused why there is this text now and that it's not optional to remove it. I can understand for some projects this is needed, but for the two I'm working one, one live and the other in development with the project builder I'm using a decision tree where everything is required so it's kind of redundant because the submit button won't activate until they've selected an option. I find the text adds more clutter to the classification interface for my projects since it's not needed for my decision tree. 

Also custom projects that force the decision tree don't have it, so I'm not sure how helpful it is. I'm sure there's a reason to have it for some projects, like those that have some optional tasks. 

 What about only displaying it if some tasks are not required or allow the builder to decide if they want text like this?

**Comment by brian-c** [comment]
If the text exists only on some required tasks, then users are either going to see two required tasks that look different or a required and a non-required task that look the same.

**Comment by aliburchard** [comment]
I'm not really thrilled about this suddenly appearing on all of the projects main tasks either. It's not on our custom projects, which reflect our ideal project designs. I understand we it's on the sub-tasks as a stop-gap measure (because we can't stop people from breaking the interface on sub-tasks), but it feels really heavy-handed on the main interface -- I think the grayed-out-ness of the "next" button makes the point... would be curious on thoughts from @vrooje @mrniaboc @kosmala @chrislintott and other project builders...

**Comment by mrniaboc** [comment]
I don't mind it too much. It does help with some possible confusion I would
imagine.

**Comment by vrooje** [comment]
I was confused by this too. I remember there were issues with sub-tasks being required and preventing people from moving on, but I thought those were solved by other means. 

It just doesn't seem like this new wording meshes with our design principles. We've gone from directing people to answer with design alone to using 14 words to say "Required"... meanwhile we advise people to keep their questions short to reduce cognitive load on the volunteer.

I think this needs a re-think.

**Comment by mschwamb** [comment]
I agree with @vrooje and @aliburchard  I find it cluttering and that  it's drags your attention down below the multiple choice question. 

I didn't have anyone complaining in my beta or now for my decision tree about not knowing how to move forward to the next subject. I feel like we're directing volunteers, when the design should be doing it. The custom projects don't have this, so why is this needed here? If it's been requested is possible to make this optional so the project builder can decide.

**Comment by vrooje** [comment]
If it's felt that some text is necessary, why not change the text in the button itself? e.g.:

![screen shot 2015-09-29 at 16 09 55](https://cloud.githubusercontent.com/assets/2357126/10168433/a3056792-66c4-11e5-8a76-2de870345a09.jpg)

**Comment by aliburchard** [comment]
ooh! I like that!!

**Comment by vrooje** [comment]
@brian-c what would you think about re-opening this?

**Comment by mkosmala** [comment]
Just wanted to add my 2 cents to the "This step required" text: I really dislike it. 
(And I like @vrooje's much more elegant solution...)

**Comment by aliburchard** [comment]
Can we go ahead and remove this text from the main workflow (or everything, if you can't keep it on sub-tasks)? Project owners really really really don't like it, and it seems like a trivial thing to remove.

**Comment by vrooje** [comment]
I agree with @aliburchard that it would be great to remove this from the main workflow but keep it on sub-tasks so that #1563 won't be compromised... at least until we can figure out a more elegant global solution.

**Comment by mkosmala** [comment]
Pretty please!

**Comment by mschwamb** [comment]
I'm not sure if I understood this conversation correctly. Was the text supposed to be removed at the moment from main tasks? Because it still shows up on all my projects tasks. Maybe it hasn't been deployed.

**Comment by mschwamb** [comment]
@brian-c I might have misunderstood the conversation. So I thought I'd check. To confirm, the 'This step is required. If you’re not allowed to continue, make sure it’s complete.'  is still supposed to be showing in main tasks? I have no subtasks on Planet Four: Terrains, and see the message there and other a few other projects. Thanks.

**Comment by brian-c** [comment]
The text has been removed from the drawing sub-tasks, not main tasks.

**Comment by vrooje** [comment]
Oh! I thought we were going to go the other way with that?

**Comment by brian-c** [comment]
Ugh, yeah, looks like I misread.

**Comment by aliburchard** [comment]
there is no facepalm or sad penguin emoji on github, sadly.

**Comment by mschwamb** [comment]
issue was sorted with pull requests already implemented
