### ISSUE TITLE
Error when setting retirment limit using front-end

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#1669]
I get a "422 (Unprocessable Entity)" when I try to change the retirement limit for a project using the front-end:

<img width="1420" alt="screen shot 2015-09-29 at 5 13 51 pm" src="https://cloud.githubusercontent.com/assets/6557526/10170591/8b7ce0ec-66cd-11e5-820a-c51f48301cba.png">

I see the same error in both Firefox and Chrome.

**Comment by edpaget** [comment]
Can you look at the response body in the Network panel?

**Comment by CKrawczyk** [comment]
The response is:

{"errors":[{"message":"{\"retirement\"=\u003e\"contains additional properties [\\\"classification_count\\\"] outside of the schema when none are allowed\"}"}]}

**Comment by edpaget** [comment]
Looks like the front-end is sending back retirement criteria incorrectly.

**Comment by CKrawczyk** [comment]
I was playing around with this today and I noticed that I get the same error message when trying to change the retirement limit directly with the API:

```js
workflow.update({'retirement.classification_count.count': 10}).save()
```
gives
```js
Error: {"retirement"=>"contains additional properties [\"classification_count\"] outside of the schema when none are allowed"}
```
Is the API expecting this limit to be set in a different way?  Or could this be a bug in the API that is preventing this limit from being set?

**Comment by camallen** [comment]
what does the network payload look like, the api is expecting something like 
`{ workflows: { retirement: { criteria: "classification_count",  options: { count: 10 } } } }`

**Comment by CKrawczyk** [comment]
the network payload is
```js
{workflows: {retirement: {classification_count: {count: 10}}}}
```
OK, I see the issue now, the workflow is retrieved in a different format than the one it expects to take in.

**Comment by edpaget** [comment]
This was fixed via https://github.com/zooniverse/Panoptes/pull/1402
