### ISSUE TITLE
Typo in moderating plane - 'ignoreing' --> 'ignoring'

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1675]
![screen shot 2015-10-01 at 6 51 59 am](https://cloud.githubusercontent.com/assets/753325/10208911/5225d032-6809-11e5-92f7-0992691df3ab.png)

**Comment by aweiksnar** [comment]
Is this an older message? The moderation buttons do not attach a message anymore if not one is not supplied

**Comment by mschwamb** [comment]
yep it's older, so I'll close this. I missed that. Though I can't seem to find a time stamp for when it was reported. Is that visible somewhere?

**Comment by aweiksnar** [comment]
Not currently, but that info is available. I'll put up an issue so I don't forget
