### ISSUE TITLE
Adding in recommended pixel size of the subject image to the project builder

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1677]
I was trying to remember if it was something around 800 x600 pixels for a new project so we didn't make something too big, but can't find that text in any of the guides. It might be handy to add it into the subject set help text.

**Comment by chrissnyder** [comment]
The initial recommendation was because the task input area would swing down to below the subject image. The shouldn't occur anymore on a typical desktop screen size. Is this still needed or desired with that in mind?

**Comment by mschwamb** [comment]
Mainly we wanted to create something that looked fine in resolution, wouldn't be too big in size for loading,  and yes wouldn't bump the task input area. 

So are subjects being resized automatically now? Did that change from launch? Is it documented when that change was needs. It might need to be mentioned for those clicks that came before that  in case there are any differences in user behavior. I did see a bunch of people on P4T Talk asking if something changed about image size, and the subject looked about the same for me so I didn't inquire further.

**Comment by chrissnyder** [comment]
The images are left as-is, but huge images won't cause the task area to
move below the subject. The change is documented somewhere in the git
history, but I couldn't find it in my minute of looking.

The image size in bytes is constrained, which is noted in the project
builder, which I think is enough here. If someone wants to upload some
seriously misproportioned images, I don't see why I should stop them.

When it comes around if they ask to become a Zooniverse project, then we
can have that additional conversation.

**Comment by mschwamb** [comment]
Fine by me.
