### ISSUE TITLE
Getting incorrect values reported back for how many subjects I have left to upload on new project

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1678]
For my new project that I am an owner on I uploaded 8 images and added in the Kitteh Zoo examples, That's it. It says 

'The project has 38 uploaded subjects. You have uploaded 2763 subjects from an allowance of 10000. We recommend uploading subjects in batches of 500 - 1,000 at a time.'

Is it grabbed from P4: Terrains?

I definitely uploaded over 2000 images while testing P4: Terrains, but this is a different project.

**Comment by camallen** [comment]
subject limits are per user...not per project.

**Comment by mschwamb** [comment]
Ah. Thanks @camallen. Didn't know that. Is that stated somewhere? Might be worth adding in a line in the project builder to remind that.

**Comment by camallen** [comment]
I thought this text "You have uploaded 2763 subjects from an allowance of 10000." not saying anything about projects conveyed it..suggested text changes?

**Comment by mschwamb** [comment]
Found the line where I was getting per project.  [Building policies](https://www.zooniverse.org/lab-policies/)  - 'There is a limit of 10,000 subjects per project '  So that needs to be changed

**Comment by camallen** [comment]
Feel free to fork the repo, modify the text and submit a PR. It's pretty easy but understand if you don't want to try. See Pull requests - https://guides.github.com/activities/contributing-to-open-source/

**Comment by mschwamb** [comment]
Thanks @camallen . I'm not Zooniverse core team, so I'm not supposed to make those decisions or direct edits to what text gets changed to what on a policy page.  Probably @chrislintott  or @aliburchard should make that edit.

**Comment by camallen** [comment]
It's just a text change to some code that we would accept or deny. All our code is open source so anyone can contribute to the project.
