### ISSUE TITLE
Does JSON-API-Client return objects with circular references?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#168]
@brian-c I'm requesting some subjects by workflow_id, and getting back the expected Resource objects. But when I serialize them to save in local storage, JSON.stringify complains that they contain circular references? I couldn't spot any, but I wanted to check there weren't any in there by design...

**Comment by rogerhutchings** [comment]
I could probably use something like [json-stringify-safe](https://github.com/isaacs/) if so

**Comment by brian-c** [comment]
`resource._type._resourcesCache[resource.id] === resource`. I'll add a `toJSON` method to skip over underscore-prefixed keys.

**Comment by brian-c** [comment]
Fixed in the client lib.
