### ISSUE TITLE
"This comment has been deleted" comments

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1681]
Do regular users see comments that have been deleted as comments that say "This comment has been deleted" or just moderators?

**Comment by aweiksnar** [comment]
That will appear for all users

**Comment by mkosmala** [comment]
Can we hide the comments that have been deleted? They're rather unsightly. Plus sometimes we get lots of deleted comments in a row, which looks really weird.

**Comment by aweiksnar** [comment]
The reasoning for this choice was that so comments after deleted comments wouldn't appear completely out of the blue if they were in response to the deleted comment

**Comment by mkosmala** [comment]
Hmm... that makes sense, too. But we have many deleted comments that were just because someone accidentally submitted a comment twice (or more) in a row. And none where someone replied to a comment and then that comment was deleted...

**Comment by aweiksnar** [comment]
If you are a moderator on that talk you can report them and then delete from the moderator-controls 'view reported comments' page and it will do a hard delete

**Comment by mkosmala** [comment]
Oh. Hmm... that's a lot of work. Let me see if I can think of a nice way to take into account both needing to keep some deleted comments and wanting to be rid of others...

**Comment by mkosmala** [comment]
@chrissnyder Actually, once a comment has been deleted, I can no longer report it... So I don't have a way to hard-delete "deleted" comments. Re-open this?

**Comment by chrissnyder** [comment]
Not sure I agree there is a problem here. Leaving a "this comment has been
deleted" placeholder is pretty common behavior across other discussion
platforms, and for good reason.

It is a bit weird that mods can't delete those comments, but I also don't
think it's a good idea to encourage mods to hard-delete every comment that
someone has deleted themselves.

**Comment by mkosmala** [comment]
On new projects, there can be more deleted comments than regular ones, as people learn the interface. It makes the boards look really ugly and discourages conversation. See, for example:
https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/62/1787?comment=3886&page=1

Tagging @DarrenMcRoy and @aliburchard who have been on Talk boards of multiple projects and have a broader view of the subject.

**Comment by DarrenMcRoy** [comment]
It's important to have a record of a comment that has been deleted, for volunteers and for us. However, currently, the deleted comments take up as much space as a regular one, and also look exactly like a regular one. (Heck, I could submit a comment that says "this comment has been deleted" and it would look identical to a deleted comment!)

I think the solution here is to change the look of a deleted comment to a thin line, perhaps grayed out, that doesn't take up much space, hides the avatar, etc. Something like how this forum hides a comment that was so offensive that the user (apologies for the name and the very dumb discussion in the first place; just went looking for an example) was banned for posting it:

![screen shot 2015-10-08 at 3 53 08 pm](https://cloud.githubusercontent.com/assets/8987864/10379642/f9753f1e-6dd4-11e5-84a1-89728617c651.png)

That way, there's a record of a deleted post, but it doesn't take up a ton of space and can't be conflated with an actual comment.

Thoughts?

**Comment by chrissnyder** [comment]
Yea that's pretty gross. Thinking more about reddit, which follows that
exact behavior, they also use less vertical space per comment, so it's
quite as devastating to the experience. They also put all comments on one
page.

**Comment by mschwamb** [comment]
I don't see many deleted posts on P4T so it hasn't been an issue for my project.Though if you modify this, keeping in the username of who deleted the comet is useful. Sometimes when there are disagreements on the boards and the rare namecalling happens, I've seen someone posts a comment then deletes it and the other person in the argument is riled up, but by looking at the discussion thread you couldn't tell me and at who. So leaving in the username would at least give the mods a hint as to what happened. 

Also currently you can edit a deleted comet and rewrite something there, so if you do make a mistake you can currently write something in there to make it less ugly (not sure if that's intended or not).

Was this duplicate text from a slow connection or Talk taking too long to post? Maybe then to stop them being so frequent would be to think about would be Talk rejecting a duplicate post from the same person. If you post the same thing with 2 minutes in the thread, it will return back like listservs do with this is the same as above. did you really want to post this?

**Comment by mkosmala** [comment]
Yes! Most of our deleted comments are from Talk taking too long to post and the user submitting duplicate comments. So rejecting duplicate consecutive posts would solve our frequent deleted comment problem. 

And a smaller/grayed-out deleted comment design would look nice for the fewer cases when a comment needs to be deleted. (In our case, the only comment needing deletion was a rogue astro comment that was accidentally posted in the wrong project!)

**Comment by mschwamb** [comment]
Those are from August, so the speed of Talk. If I recall correctly there were a few days were Talk was a bit slower to respond, but since then it's seemed okay at least from Taiwan (but everything's generally a bit slower here in load times because of most of the internet being hosted at the Virgina AWS farm)

Maybe the simple solution that will help cut down on them would be to just not let you post again until the api has returned whether or not the post has been successful since the urge is you don't see it so I should post again?

**Comment by vrooje** [comment]
I think the record of a post having been deleted is important, and I like the idea of compressing the display of that somehow. In GZ Bar Lengths this doesn't happen very often, though.

**Comment by mkosmala** [comment]
+1 to @mschwamb's most recent comment. We still have duplicate postings happening for some people.

Sounds like the consensus is:
1. refuse duplicate posts in succession
2. compressing (and maybe dimming) the display of deleted comments, so that there's a record of that comment, but it doesn't take up a lot of space.

**Comment by mschwamb** [comment]
I think the simplest solution will be to remove the text box when you hit the submit button and make it reappear after successful of the post so there doesn't have to be comparison of text. I think that would solve the issue.

**Comment by parrish** [comment]
I think the slowness of the app was just the Panoptes API crapping out during heavy traffic (which also broke Talk).

Disabling the submit button while the submit is running is good though, I'll create a separate issue for that.

**Comment by mkosmala** [comment]
@parrish Thoughts on a smaller/dimmer display for deleted comments, as well?

**Comment by parrish** [comment]
The height of the comment is pretty well constrained by the user avatar.  No reason why we couldn't add a style to fade it out a bit.

**Comment by DarrenMcRoy** [comment]
Why can't we just remove the avatar for a deleted comment so that it's not talking up all that vertical space?

This may be related to overall Talk redesign, incidentally...

**Comment by mschwamb** [comment]
We want the avatar. Especially when there are been a few times in the rare disputes on Talk people have in the past made a rude or bad comment directed towards the person there were in a fight with and then the other person (person B)  read it and was upset about. By the time the mods or I saw it, person A decided delete the original post so it was confusing what happened. Having the avatar keeps a record  even if you can't see the text you know something was said.

**Comment by DarrenMcRoy** [comment]
Sure. But why do you need the avatar and not just the username? The username is just as good at identifying Person A, isn't it? Without taking up a bunch of vertical space?

**Comment by mschwamb** [comment]
The avatar has become a quick way to identify who the user is. So I think it's become a standard for identificaton so any post or removed post should have that plus the username. 

Either way, the deleted comment is already pretty small, removing the avatar isn't going to make it much smaller.

![screen shot 2015-10-14 at 4 50 21 pm](https://cloud.githubusercontent.com/assets/753325/10489242/1f9b5bd8-7294-11e5-8e9b-9363ba236ac4.png)

As you said this is probably at this point in the hands of the graphic design pass.

**Comment by parrish** [comment]
I just added a PR for some visual changes.  I think it's a decent compromise.

<img width="940" alt="deleted_comment" src="https://cloud.githubusercontent.com/assets/122990/10491778/f2e630b6-726d-11e5-9de1-fdc9ff59abd1.png">

**Comment by DarrenMcRoy** [comment]
I'll take it. :+1: I figure we'll look at it more in-depth as we look at all Talk styling. Thanks, @parrish !
