### ISSUE TITLE
400 error on classification post

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#1685]
I noticed this when working on another issue, but I'm seeing in the console:

`POST https://www.zooniverse.org/api/classifications 400 (Bad Request)`
`Uncaught (in promise) Error: Validation failed: Gold standard can not be set to false(…)`

when submitting a classification. Seeing it in both latest version of Chrome and Firefox in OS X Yosemite.

**Comment by brian-c** [comment]
WOW, thanks. Gonna patch this real quick and figure out what's up.

**Comment by brian-c** [comment]
Just patched it up and merged it myself. That was a big deal, thanks for catching that.
