### ISSUE TITLE
Format request for subject exports

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1688]
In the subject exports, can we please have all the metadata as columns as opposed to bundled up as JSON in a single column? Since the metadata all have to be entered as key:value pairs anyway, it should be pretty simple to do this. It would make the files smaller (by not having to repeat the key names for every row) and make them easier to handle by science teams (as we won't have to parse the JSON).

**Comment by edpaget** [comment]
Yes I am working on this. It's also not a front-end issue.
