### ISSUE TITLE
Text preview on zooniverse Talk crushed the Talk side bar.

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1691]
I noticed that if I go to Zooniverse Talk it loads and then board list now crushes the Talk side bar. If I zoom out I can get it reappear but if I refresh the browser it just does the same thing, 

![screen shot 2015-10-02 at 10 19 10 am](https://cloud.githubusercontent.com/assets/753325/10238217/61b49f42-68ef-11e5-8dfb-a02e54192ac0.png)

I'm using Firefox 40.0.03 on OS 10.10.5

**Comment by aweiksnar** [comment]
Thanks for reporting! Just posted a PR to fix
