### ISSUE TITLE
"experimental" tasks disappear from workflow when not populated with task data

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1695]
I have a researcher who wants to build a camera survey project. Since this is an experimental feature, I have to add the filtering task to the workflow. However, when my collaborator goes to work on the task a few days later, the survey task that I have added has disappeared. This is proving to be a logistical nightmare, given that we can't coordinate him populating the project *immediately* after I add the task (time zones and well, reality). 

When can we expect #1622 to be resolved? I'd really like to prioritize this.

**Comment by chrissnyder** [comment]
Looks to be added with https://github.com/zooniverse/Panoptes/issues/1385?

**Comment by aliburchard** [comment]
no longer an issue.
