### ISSUE TITLE
should not be able to save nameless workflow

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1696]
This originated months ago, but can't find the original issue. I'm able to delete the name of a workflow, but save it, such that it appears as a tiny, narrow bar on the left-hand side, that easily goes unnoticed. 
I think we need to disallow saving a workflow name as empty.
<img width="1280" alt="screen shot 2015-10-04 at 17 00 51" src="https://cloud.githubusercontent.com/assets/6217406/10270767/a576665e-6ab9-11e5-8832-19a73b903529.png">

**Comment by camallen** [comment]
This is a backend issue, i've got a PR in.
