### ISSUE TITLE
Autoscaling down images that are too big that are in a comment posted on the Talk Subject page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1700]
Example [here] (https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/subjects/490275/)

![screen shot 2015-10-05 at 9 42 38 pm](https://cloud.githubusercontent.com/assets/753325/10281903/3f274534-6baa-11e5-8481-7eba3d98d850.png)

**Comment by itsravenous** [comment]
This would be fixed by a `max-width: 100%` rule, but is there a preference as to whether this is confined to the `.talk-module` component? I would normally have such a rule in my "base" styles as I find there are very few cases where I don't want this behaviour. I can submit a PR either way.
