### ISSUE TITLE
Ability to specify in the project builder who in the project team get project related Zooniverse emails

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1703]
It might be helpful if a research team could specify in the project builder if all or some of the team would be designated to receive Zooniverse team emails relating to the project in case something arises in the future like new aggregation features, beta test feedback, or platform issues or updates that need to be communicated.

**Comment by camallen** [comment]
In most cases wouldn't this just be the project owner?

**Comment by mschwamb** [comment]
Depends on the team I think. On both projects I'm building, I'm not the PI but I am the owner since I started the project in the project builder, so it would be nice if the PI also go this information.   I could see teams where the person doing the data analysis is not the person who is the project owner also wanting information.

**Comment by mkosmala** [comment]
+1 

Another case: a project gets started by one person, that person leaves, and a new person takes over as lead project manager.

**Comment by CKrawczyk** [comment]
+1

I know I have started work on some projects here at UoP because I know how to use the project builder, not because I am on the research team.

**Comment by vrooje** [comment]
+1 as well.

**Comment by mkosmala** [comment]
@camallen points out in #2346 that adding a "communications" role might be a simple and elegant way to address this issue.

**Comment by camallen** [comment]
perhaps something like which will default to the owner.
```
user_name 

[X] Collaborator
[ ] Expert
[ ] ...
[X] Communications
```

**Comment by vrooje** [comment]
+1

**Comment by aliburchard** [comment]
+1 to communications role

**Comment by donnytree** [comment]
I would just like to add that we really need this functionality. We need to be able to designate the person or persons who receive email communications for our project Treeversity, https://www.zooniverse.org/projects/friedmaw/treeversity/classify, and in our case, it is not the project owner. Having a communications role would be great since there is no way to change the project owner and as @mkosala points out, that person may leave at some point. Thank you!

**Comment by mschwamb** [comment]
I had to forward the most recent emails to three different email addresses to cover the relevant people on my projects who needed to know about updates. It would be really handy if we could have this enabled and select which team members got emails from the Zooniverse rather than just the project owner.

**Comment by mschwamb** [comment]
I still think this really important and an issue when the PI is project owner but not doing the actual day to day stuff. Seems like easy to add a check box or something in the backend to select who should get communications rather than only having it go to the project owner.

**Comment by mkosmala** [comment]
+1   Still important!

**Comment by camallen** [comment]
This will need backend support before the UI can do anthing https://github.com/zooniverse/Panoptes/issues/2524 feel free to comment there as well.

**Comment by mschwamb** [comment]
Looks like the backend now accommodates this so the front end can be modified to have the communications role set.
