### ISSUE TITLE
Zooming on iPad force resets the zooniverse platform - Webkit issue?

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#1704]
Zooming in on a pantoptes page resets the interface on an iPad. I'm not sure if this is widespread (project specific - as I don't own an iPad).

https://www.zooniverse.org/projects/kosmala/season-spotter-questions/talk/58/10505/?scrollToLastComment=true&page=1

**Comment by mkosmala** [comment]
I just tried to replicate and couldn't. :-( Have asked the volunteer for info the browser and OS version she's running.

**Comment by mkosmala** [comment]
This issue is apparently intermittent -- the user can't reproduce it reliably either. She's going to pay attention to exactly the conditions next time it does...

**Comment by chrissnyder** [comment]
Thanks for the followup @mkosmala. If and when the steps to reproduce this is found out, let us know and we'll get it taken care of.

**Comment by parrish** [comment]
Can't replicate either.
