### ISSUE TITLE
Flipping the chronology on the subject page so the most recent comment shows up first or posting a few most recent comments on the top

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1706]
Checking a subject page every notes post from different notes threads are individually posted in chronological order with oldest first, but since people quickly glance at this, they don't see if the research team corrects terminology or something recently posted.

Although it is paginated, I don't think people will read through the entire discussion when classifying. Notes as I see it is for people to quickly comment on a subject. So I see the behavior as more of a quick glance at comments and then writing in the box and going back to classify the next image. 

With the 140 character comments on the previous version of Talk, the posts had the most recent listed first, and I found that helpful because if someone said 'there's tar- life on Mars', I could write 'no, the dark matches are X. Read more here', and the next person classifying and on Talk would see that. 

If you don't want to completely flip the order, would it be possible to post the 2-5 most recent comments, and then the rest in order from oldest to newest?

Example [here](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/subjects/490275/)

**Comment by aweiksnar** [comment]
:+1: I like this suggestion - Will add it in tomorrow

**Comment by mschwamb** [comment]
Cool. Thanks @aweiksnar
