### ISSUE TITLE
Workflow editor does not load

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#1708]
I tried to view the workflow editor page today and got the following error:
```js
Uncaught (in promise) TypeError: a.makeHref is not a function(…)
```
Same error in chrome and firefox.
<img width="1412" alt="screen shot 2015-10-07 at 9 59 17 am" src="https://cloud.githubusercontent.com/assets/6557526/10333292/b938c52e-6cda-11e5-9503-c8bd0ed41d46.png">

**Comment by camallen** [comment]
@CKrawczyk can you try out my PR to see if it fixes your issue?

**Comment by CKrawczyk** [comment]
Just tried it and it works.
