### ISSUE TITLE
Error in retrieving one of multiple workflows

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#171]
Not sure if this is a Front-End or API issue, but suspecting it's Front-End, so posting here, with a heads-up to @camallen and @edpaget.

I have a project, built via the API, with multiple workflows. When I view the project at 
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Spotter20
all my workflows are listed. Some of these workflows have associated subject sets. One of these is Workflow 439. When I click on the text for Workflow 439, however, I get an error message saying that there are no subjects available for a different workflow!

In particular, the URL bar reads
```
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Spotter20/classify?workflow=439
```
And the error I get on the Front-End is:
```
Error: No subjects available for workflow 442
```
I've checked via the API and Workflow 439 is, in fact, hooked up to Subject Set 709, which has 5 subjects ("set_member_subjects_count" = 5). Workflow 442 has only its default expert subject set (702), which is empty.

Upon further investigation, I note that when I click on *any* of my workflows, I always get the error that no subjects are available for Workflow 442.

**Comment by camallen** [comment]
Can you make the project visible to us? I.e. `private=false`. That way we can debug it.

**Comment by mkosmala** [comment]
I can try...

**Comment by mkosmala** [comment]
I made a new identical project with private=false. It's here:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Spotter21

**Comment by camallen** [comment]
Seems like the fron end should be using `worfklow_id`: http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Spotter21/classify?workflow_id=456

**Comment by mkosmala** [comment]
I still get this error if I try to change it to "workflow_id" in my browser bar. Will that not work?

**Comment by camallen** [comment]
Did you try a hard reload? http://refreshyourcache.com/en/cache/

**Comment by mkosmala** [comment]
I have now. Looks good!

**Comment by brian-c** [comment]
The front end doesn't use the `_id` suffix. https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L60

This sounds like a props-changing bug. I'll look into it.

**Comment by mkosmala** [comment]
@brian-c This is working really nicely now.
