### ISSUE TITLE
Upgrade to react v0.14

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#1714]
http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by aweiksnar** [comment]
Branch is named `react14`

**Comment by aweiksnar** [comment]
Todo 
- [ ] fix minor button labels
- [ ] account menu closing on change pages

**Comment by parrish** [comment]
Took a stab at closing the account menu on selection: https://gist.github.com/parrish/b6cdff519e3edafcb2dc

It's probably better (less hacky at least) to setup a prop on the modal for open/closed that can override the state.

**Comment by brian-c** [comment]
The account menu should close automatically when it detects a `locationchange` event.

https://github.com/zooniverse-ui/modal-form/blob/master/base.js#L39

**Comment by aweiksnar** [comment]
I just added a listener to dispatch the locationchange event on history changes here cf42108
