### ISSUE TITLE
Some redirects of hashed URLs not working

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1716]
![screen shot 2015-10-08 at 13 41 54](https://cloud.githubusercontent.com/assets/2357126/10366791/a89412f6-6dc4-11e5-8c75-e407be72e774.jpg)

(this should have gone to a subject page)

**Comment by camallen** [comment]
where did you get the url?

**Comment by vrooje** [comment]
It was linked to from an older Talk post.

**Comment by mkosmala** [comment]
All the project URLs have changed. See https://github.com/zooniverse/Panoptes/issues/1416

**Comment by edpaget** [comment]
Ah yeah it appears the redirect isn't working as intended. I'll fix.
