### ISSUE TITLE
extra quote mark added to the end of the search string of a hashtag search when you click on the hashtag from a search results

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1721]
Looks like an errant quote mark gets added when you click on a hashtag hyperlink from a Talk search

Search hashtag spiders - https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/search/?query=spiders

then click on hashtag #spld  from the first response and you get this - not the quotation mark at the end

![screen shot 2015-10-09 at 9 49 36 am](https://cloud.githubusercontent.com/assets/753325/10384296/8c152d7a-6e6b-11e5-9457-8b9ea7c6a1de.png)

**Comment by aweiksnar** [comment]
Closed in zooniverse-ui/markdownz@3.0.2
