### ISSUE TITLE
Checking the number of rows in the manifest file and not starting the upload if it's above some limit

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1723]
I should know better, but since I didn't need the speed, I was doing an upload in one go for 6000 subjects. I was told that should be fine, but I might want to break it up for speed. The upload failed past the 2000 mark. If it's not possible to upload in bigger than a certain size on the web in one go or is strongly recommended to not to do what I did, then can the project builder read the manifest file first and check the number of lines and return an error saying too many subjects at one time?

**Comment by mschwamb** [comment]
I think it would project scientists from doing stupid things that we should probably thing more about when we upload. I don't know what's actually uploaded and not uploaded. so I'm starting from the beginning again in a new subject set.

**Comment by mschwamb** [comment]
Related to #316

**Comment by camallen** [comment]
@mschwamb you can use subject exports to figure out what was uploaded so you don't have to re-upload all the data again.

**Comment by chrissnyder** [comment]
Same response as https://github.com/zooniverse/Panoptes-Front-End/issues/1724

> Eh, I understand the motivation, but there's also a ton of places in the project builder where somebody could do silly things that we don't explicitly save them from. Issues like this will be addressed more holistically when we start more intensely redesigning the builder.
