### ISSUE TITLE
Not letting a project builder create a recursive loop by selecting the current workflow task as the next task

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1724]
I'm setting up a new project, and  it's my first time doing more than one step in the decision tree for months. I accidentally set up a recursive loop. Apparently in the drop down menu for 'Next Task', you can select the task you are on.  I'm on 'Is the field crowded?' and I can select it in the drop down menu.

It took me a second to realize what happened, when I kept getting the question and not the talk prompt or the other question in  the decision tree. I think the step you're on should be removed from that list, so other people don't select when building a project . 

![screen shot 2015-10-09 at 2 18 59 pm](https://cloud.githubusercontent.com/assets/753325/10387245/6f5782f6-6e92-11e5-9646-9efd0648fdb8.png)

**Comment by chrissnyder** [comment]
Eh, I understand the motivation, but there's also a ton of places in the project builder where somebody could do silly things that we don't explicitly save them from. Issues like this will be addressed more holistically when we start more intensely redesigning the builder.
