### ISSUE TITLE
? help button in the project builder doesn't seem to do anything anymore

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1726]
I was trying to see if there was a way to change the font size in markdown, I don't want it to be a H4 I just want the text to be H4 size but not bold. When I hit the help button in the FAQ and research, the help button doesn't bring up the pop up with the link to a markdown tutorial. 

I've checked in two different projects and firefox and chrome on mac (latest versions)

**Comment by chrissnyder** [comment]
@aweiksnar Seems like markdownz isn't able to access React. After clicking the ?, I see the following in the console

![](https://i.imgur.com/XAnsNDL.png)
