### ISSUE TITLE
Having a preview button for the help and the task text

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1727]
I've been playing around with the markdown formatting of this one question since we want to have a note above the actual task prompt  and every time I make a tweak I have to get to that part of the decision to check it out, it would be nice if there was a preview button so I could see if the markdown was formatted correctly

**Comment by mschwamb** [comment]
I'm currnently spending alot of time trying to format the help. It's particularly frustrating when I'm trying to format the help for the 4th question in the decision tree, since I have to get there each time I make a chance to see what it looks like I have to hit reload on the browser and go through the decision tree.  A preview button like the research page would be really helpful.

**Comment by CKrawczyk** [comment]
When my [workflow visualization](https://github.com/zooniverse/Panoptes-Front-End/pull/18080) tool get merged in you will be able to preview the help text for all tasks on one page (along with the full tree structure of the project).

**Comment by mschwamb** [comment]
I'm sure workflow visualization will be helpful, but I still need to see what it looks like formatted in the interface with the images in the interface, so having a preview button would still be helpful.

**Comment by mschwamb** [comment]
Thanks  @CKrawczyk - since it's now merged I'm closing this.
