### ISSUE TITLE
How are subjects listed in the project builder in the subject set uploader view?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1728]
It seems to be random ordered. I was trying to use it to check I wasn't uploading the same batch twice but couldn't find the last image of each batch. It's not the first or the last image as far as i can tell.

**Comment by camallen** [comment]
It's not random, it'll be the serialized response order from the api that defaults to the subject insert order (i'm pretty sure). I don't think the front end guarantees that subjects are uploaded (and finished) in order from the manifest though I think it tries.

**Comment by chrissnyder** [comment]
The front-end processes a manifest in the order given. Not sure how the auto-generated manifest order is received, maybe by filename? Might vary by system. Probably the beset answer we'll be able to give here.

**Comment by mschwamb** [comment]
Not sure if there's a way, but as I'm currently uploading 13 blocks of 500 subjects, it would be nice if there was a way to double check I uploaded block 5 before I upload 6 without having to download the csv after each upload. I guess in reality it's better to uploaded more than a a few thousand subjects with a script, but I didn't seem like there's a Zooniverse approved software tool yet to do that. Is there one?

**Comment by CKrawczyk** [comment]
There is an upload script that can be found here: https://github.com/zooniverse/panoptes-subject-uploader/tree/text-subjects (note: use the `text-subjects` branch or you will get a login error).
