### ISSUE TITLE
URL and usernames

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1729]
Just bringing up the idea that the project urls change again - it would be great to be able to embed URL's so for ours it is just fossilfinder.org

as it stands it would look much better if the usernames of the individuals who created the project were dropped from the url (it would just mean ensuring that project titles are unique)

**Comment by chrissnyder** [comment]
Custom URLs is definitely on our list of things to support.

Point taken on the verbose URLs. Something we'll look into as well.

**Comment by aliburchard** [comment]
Maybe this is something that could be implemented in the launch process? With the idea that projects that have gone through the approval process and are launched as a sponsored Zooniverse project can now be 'standalone' projects not tied to their owner's name? This would also stop a bunch of project names being 'grabbed up' (intentionally or not) by projects that are never finished or launched.

**Comment by camallen** [comment]
The api scopes projects to owners (groups / users) so we allow duplicate project names via this combination. This was a conscious design choice, think `/owner_name/test` and `/other_owner/test`. I don't think we should restrict the project name to be unique for the whole of the zooniverse.

> as it stands it would look much better if the usernames of the individuals who created the project were dropped from the url (it would just mean ensuring that project titles are unique)

I'm not sure why this is aesthetically more pleasing than having owner names..

**Comment by aliburchard** [comment]
I think that names of Zooniverse sponsored, launched, official, whatever you want to call them projects should be unique. It would be weird (and confusing) to have two completely unrelated Galaxy Zoos or Snapshot Serengetis promoted on Zoo Home. But I don't think we need to enforce uniqueness until we get to that stage.

Re: individual names inside the project url - to me it feels like it detracts from the projects official status. It's like, Ali's play attempt at building a zooniverse project, instead of a real zooniverse project. Switching ownership to Zooniverse is one fix, but I find shorter urls more appealing - they're just much easier to type, remember, and share.

**Comment by camallen** [comment]
> I think that names of Zooniverse sponsored, launched, official, whatever you want to call them projects should be unique. 

We can enforce this by review process and without a hard restriction via the API. 

Re the latter, i thought this was why we built panoptes so anyone can build a project. It's up to the review process to determine a projects "legitimacy" and thus the decision to sponsor a project or not. If you really want unique url's via `zooniverse.org/project_name` the we'll have to change the api to support this and understand the consequences (noting that i strongly disagree with this). 

Finally, custom URLs on the other hand are something we want to support long term.

**Comment by AdrianEvans** [comment]
For me it's
https://www.zooniverse.org/projects/adrianevans/fossil-finder
vs
https://www.zooniverse.org/projects/fossil-finder

Not only is this clearly more aesthetically pleasing, it is easier for a
user to remember

I get the problem of people trying to use the same project name. Your
example of test is good but it might be a better idea to push for users to
not be flippant in project name choice. it is easy to code to check if the
project name is unique - in the same way this is done for usernames.

You also have to think about protecting project branding - would I be
pleased if 'other_owner/fossil-finder' appeared - no. So even if owner
isn't dropped from the URL, unique project names should still be a thing.

**Comment by parrish** [comment]
For better or wore, we're definitely stuck with the current url structure for the time being.
