### ISSUE TITLE
Remove headings in builder when not needed

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1730]
The words "Label URL" are confusing when you haven't yet used the "Add a link" button. They are the headers for a table that doesn't yet exist so we should hide them until we have added at least one link...

![screenshot](https://cloud.githubusercontent.com/assets/1473244/10392308/c10df2ac-6e7d-11e5-9db0-42a229bdde88.png)

**Comment by alexbfree** [comment]
@chrissnyder why feature request? isn't this just a UI glitch? guess it doesn't really matter what it's tagged as.

**Comment by chrissnyder** [comment]
For better or worse, it's "working as intended" currently and does not result in a blatantly broken site (which would warrant the bug label). Pretty much everything else I classify as feature request.
