### ISSUE TITLE
getting a  [object XMLHttpRequest] error on the project builder upload

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1738]
Has happened three different instances now. three different batches I've tried to upload. Was fine for most of the day doing these small batches of 500. I logged out and back in to try and see if that solved the issue. 

I can confirm the subjects are in the directory and I can open the file. Manifest file is autogenerated by my script that divided the subjects into 500 block directories. No difference from the successful ones. 

![screen shot 2015-10-10 at 2 48 33 am](https://cloud.githubusercontent.com/assets/753325/10402696/7de3f02c-6ef9-11e5-8feb-e23cf91421f2.png)

Is it something with my harddrive causing issues?

**Comment by mschwamb** [comment]
A complete reboot seemed to be the only thing that fixed it. If I'm doing something wrong, please let me know.

**Comment by mschwamb** [comment]
Fixed it for a short period of time - got output as I paused 

    [object XMLHttpRequest]
    Error: PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_set_member_subjects_on_subject_id_and_subject_set_id" DETAIL: Key (subject_id, subject_set_id)=(1047665, 2384) already exists. : INSERT INTO "set_member_subjects" ("subject_set_id","subject_id","random","created_at","updated_at") VALUES (2384,1047665,0.475028648543378,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047427,0.455507227293331,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047547,0.388134507714092,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047188,0.239488897144547,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047554,0.58237908124435,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047389,0.456867694992676,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047211,0.949373926142154,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047655,0.281614927921338,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047783,0.389749398887401,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047228,0.334249263699065,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047696,0.24229188345592,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047508,0.47452330809107,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047142,0.75145169972403,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047741,0.504590357000611,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047085,0.726470962868002,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047324,0.639382397561933,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047406,0.270198144222712,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047161,0.963329678715423,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047206,0.630762379487558,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047255,0.344113981277134,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047569,0.00255506676336037,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047587,0.314557396105618,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047081,0.941763165731406,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047267,0.823341368778339,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047652,0.800454066682605,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047364,0.656303548562564,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047717,0.842441554319143,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047438,0.48213255087457,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047674,0.380290632893196,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047377,0.709169412185626,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047733,0.00690144122627123,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047132,0.672001043103342,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047278,0.584026525616934,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047536,0.906056508989848,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047285,0.313778066081068,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047681,0.665577230115775,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047068,0.28292276358442,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047172,0.796062522627718,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047318,0.725628192580689,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047618,0.852843266935972,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047770,0.678697298688681,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047661,0.392172945466806,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047622,0.311202518511308,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047339,0.417888542639426,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047708,0.507270338201409,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047105,0.892699068925084,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047194,0.10602856741498,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047542,0.256056599190228,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047297,0.628425516966026,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047475,0.0155756109437366,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047127,0.519158975260945,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047668,0.245258590349419,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047755,0.577756270289287,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047356,0.862266774392158,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047658,0.475729763386891,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047704,0.535339346622115,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047773,0.600896863892408,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047235,0.753208001930494,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047291,0.505846243702192,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047633,0.828309512429825,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047101,0.625156101770223,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047109,0.381004849682815,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047397,0.669042373744764,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047123,0.25714419464004,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047064,0.312843534067211,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047148,0.964534735937902,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047073,0.970159581504588,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047151,0.350293162599226,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047312,0.937707823570662,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047678,0.308473552910863,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047249,0.424234152045713,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047638,0.0935038887241233,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047329,0.742160641610255,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047077,0.0592191966042855,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047092,0.10688657081148,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047097,0.577517299045132,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047693,0.479659510148655,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047465,0.666214445960179,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047722,0.736214250883036,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047274,0.414068797839362,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047531,0.709395428335268,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047169,0.43128510109668,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047644,0.864015345288898,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047525,0.83383736209337,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047201,0.707636590350311,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047599,0.302282618179784,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047684,0.665003419835974,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047280,0.337307223909281,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047307,0.363941010935125,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047457,0.421180554365701,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047137,0.174570776490192,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047221,0.00224583518633537,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047671,0.68029459569782,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047689,0.25989183022752,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047745,0.495502845841482,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047113,0.627032816657705,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047698,0.860110192455459,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047448,0.0337308713520955,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047649,0.740323303871411,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047729,0.944383074360362,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047117,0.543007011072322,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047242,0.187098086233838,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047759,0.12248293425271,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047261,0.0700618684838353,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047687,0.391699945036005,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047484,0.657662524238905,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047165,0.489578366413817,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047750,0.478339835159704,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047344,0.293906012383774,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047736,0.764243354817383,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047059,0.517643863148293,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047647,0.136527274174153,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047216,0.86986020393221,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047765,0.568420806375355,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047155,0.612510728406733,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047183,0.542421654552496,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047517,0.95920234844144,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047301,0.722492134677339,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047349,0.760797089233102,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047371,0.991308383284763,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047176,0.998422022517992,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047562,0.249880419522852,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047499,0.086286405761907,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047088,0.000950221898739611,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047713,0.870796509976413,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047628,0.421597324844564,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047334,0.512613831375057,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047577,0.974887806363966,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047610,0.351584516716436,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480'),(2384,1047701,0.10322001626716,'2015-10-09 19:09:30.345370','2015-10-09 19:09:30.345480') RETURNING id

**Comment by chrissnyder** [comment]
Woah, bizzare that Postgres errors are coming all the way through.

**Comment by mschwamb** [comment]
Sorry I don't know what I did to break it. Been doing the same thing all day. uploading a directory with 501 subjects in it. first 0-7 were fine, 8 started having issues. and now everytime it uploads a few and starts this error

**Comment by mschwamb** [comment]
@chrissnyder is it possible to get a dump of the subject csv? Now I don't know what's in and not, and I already requested a data dump in a 24 hour period. I hit the button again, earlier, but I presume it's not doing anything.

**Comment by mschwamb** [comment]
If the subject set is broken beyond repair, you can remove it.   I made a separate subject set for this, so it's not the one live on P4: Terrains. It's subject set 2384 'p4_terrains_manifest2' 

If you need to delete it, I can wait until I get to Oxford to upload data and we'll deal if we're close to P4:Terrains being out of data after my WIRED talk when/if it happens. I was trying to be proactive.

**Comment by camallen** [comment]
Not sure what is going on here..the subjects should be uniquely identified by the upload process. The only thing i can think off is duplicate subject ID's being in the links array for the subject set. @mschwamb I'd like to debug this with you in oxford to figure it out.

**Comment by mschwamb** [comment]
Okay. I won't touch anything until then.

**Comment by parrish** [comment]
Pretty sure this got sorted out.

**Comment by mschwamb** [comment]
Not really. The root cause still happens for random reasons when I upload batches of 250 subjects at a time. Pretty much every download I have to go back through a remedy the multiple chunks that had failures uploading where this happens.
