### ISSUE TITLE
Project edit link error

### ISSUE THREAD

**Issue by perry** [zooniverse/Panoptes-Front-End#174]
Clicking the edit link for a project of mine on `http://demo.zooniverse.org/panoptes-front-end/#/build` causes the following error:

```
Uncaught (in promise) TypeError: Cannot read property 'replace' of null 
Error: Invariant Violation: unmountComponent(): Can only unmount a mounted component. 
Uncaught (in promise) Error: Invariant Violation: receiveComponent(...): Can only update a mounted component.
```

after this, any link on the page returns the following when clicked

```
Uncaught Error: Invariant Violation: unmountComponent(): Can only unmount a mounted component.
```

The project IDs are `141` and `195`.

`141` does not have any subjects or workflows.
`195` has subjects, but no workflows.

**Comment by brian-c** [comment]
Closing, the #/build component has been replaced by #/lab.
