### ISSUE TITLE
A place on Zooniverse home to acknowledge translators of Ouroboros and eventually Panoptes projects

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1747]
The previous translators page on Zooniverse home disappeared with the new platform. Could there be a place in Zooniverse home were all the previous translators and future could be acknowledged?

 Also currently if you were looking at Zooniverse home you wouldn't know there is a translation effort ongoing for Ouroboros projects. Maybe on this acknowledgements could be how to contact the Zooniverse team if you're interested in helping translate?

**Comment by chrissnyder** [comment]
For sure.

@DarrenMcRoy Somewhere, there exists a copy of the document that lists off all translators that have contributed to various projects. Could you pull that together along with some copy for this page? Plop the results in here and reassign to @saschaishikawa when it's ready to be added to the site.

**Comment by rogerhutchings** [comment]
superseded by #2526
