### ISSUE TITLE
Getting an email when you've been added as a collaborator or expert to a project 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1749]
Currently you can add anyone to your project and unless you're actively using the project builder you wouldn't know you've been added. I think it would be helpful in the future if when you add someone that an autoemail saying you've been added to which project and how to access it and the project builder would be helpful.  Especially for private projects being built, having it sent the link out to the project would be helpful.

**Comment by aliburchard** [comment]
Ooh, I like that idea.

**Comment by vrooje** [comment]
Agreed.

**Comment by zwolf** [comment]
This is being resolved alongside Panoptes/1790. Current copy, as cobbled by me, is found below. Let me know if you'd like to see anything change. cc: @camallen / @mrniaboc 

> You have been added to the Zooniverse project <% project.display_name %> in the following roles: <%= roles.join(" and ") %> 
> 
> Visit <\a href="zooniverse.org/projects/<% project.slug %>"><% project.display_name %></a> to get started.
> 
> Thanks,
> 
> The Zooniverse Team

**Comment by mschwamb** [comment]
@zwolf great. Thanks. 

 I'd add in a contact email for the Zooniverse team  in case someone were added in incorrectly they can report it.  

Also I found that I have to send a project builder link to my collaborators because half my collaborators are really only editing say the about page so don't learn how to get to the specific project builder page from the lab page from Zooniverse home. Having a link to the project builder front page for the project (ie  https://www.zooniverse.org/lab/###) if your status is collaborator would be good as well I think/

**Comment by mschwamb** [comment]
@zwolf it looks like this was addressed in  Panoptes PR 1855 ? Should this be closed?

**Comment by mschwamb** [comment]
Looks like this was added in as an email got generated, but it looks like it went to the project owner (me), but not the collaborator who was added.

**Comment by zwolf** [comment]
Closed by https://github.com/zooniverse/Panoptes/pull/2068
