### ISSUE TITLE
Request for weekly generated and emailed classification files

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1752]
Would it be possible to have raw classifications (and possibly aggregate classifications) created every week and then emailed to us, like we already have for Snapshot Serengeti?

**Comment by khufkens** [comment]
I would like to second this. It would be nice to get a weekly update which I can then use to automate the generation of my summary statistics - which would be pushed to the results page.

**Comment by chrissnyder** [comment]
We'll look into it

**Comment by mkosmala** [comment]
Actually, I just realized this should be a back-end task. Moving it over to https://github.com/zooniverse/Panoptes/issues/1431
