### ISSUE TITLE
top-level Zooniverse Data page

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1757]
We maintain a publications page. I think we should also maintain a data page where we link to data produced by our projects, along with the license(s) for using that data.

**Comment by aliburchard** [comment]
YES!!! That's brilliant, and would make our data products so easily accessible!

**Comment by alexbfree** [comment]
+1 !

**Comment by DarrenMcRoy** [comment]
I like that idea!

**Comment by chrislintott** [comment]
I think a lightweight one that points to the individual data pages is a good idea.

**Comment by vrooje** [comment]
We were just discussing this recently again, so this is definitely not stale...
