### ISSUE TITLE
Spotter's Guide

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#1768]
I'm going to get started on the Spotter's Guide feature soon. The goal is to make something like Planet Four Terrains's guide (http://terrains-guide.planetfour.org/) available without leaving the classification interface.

Some ways we've done this in the past:

- Galaxy Zoo has a simple popup full of example images. http://www.galaxyzoo.org/#/classify

- Bat Detective has samples organized into tabs, always available under the classification interface. http://www.batdetective.org/#!/classify

- Gorongosa's guide is a separate part of the site, but it's linked from the relevant animal in the classification interface. http://www.wildcamgorongosa.org/#/classify

- SpaceWarps has a slide-over guide, but it just contains links to another part of the site. http://spacewarps.org/#/classify

- Chimp&See has a slide-over nested field guide. http://www.chimpandsee.org/#/classify

I think something like Chimp&See's is the way to go, ~~but I know @chrislintott had things he'd change about it. Could you comment?~~ @aliburchard, @chrissnyder, thoughts?

@jwbmartin, anything more you'll need to get started thinking about design?

**Comment by chrissnyder** [comment]
I have a high preference for models like Bat Detective/Chimp & See, where the spotter's guide is available on the same page as the classification interface. Bonus points for being able to see the guide and the subject at the same time.

How do you envision the data model? Just a fat block of markdownz, or explicitly separate out different sub groupings of content?

**Comment by brian-c** [comment]
Most projects have a single level of nesting, so I think we should go with that.

From `[{title: 'Markdown', content: 'More markdown'}...]`we can render a menu screen of titles and link them to the appropriate content, Chimp&See-style.

**Comment by vrooje** [comment]
Definitely prefer something that doesn't require leaving the classification interface. I like the Chimp & See and the Space Warps models. I also like the Penguin Watch style guide.

Will all projects need a nested menu though? I suspect there will be some that give general further details and examples without needing much more so it would be nice not to require a menu-content structure for each project. (Sorry, I know that might be too general.)

**Comment by aprajita** [comment]
With Space Warps we had 2 versions of the SG - the quick spotter's guide that appeared on the right hand screen (that could also be hidden) and a full guide on a separate area. The full guide could also be accessed by clicking on the images in the quick spotter's guide. 

It's certainly very helpful for the users to have this quick check function with some selection of images in the interface, as well as the more detailed help/description elsewhere. 

Is it no possible to include a Spotter's Guide in Panoptes?
If so, how do I provide content for it in the project builder?

Many thanks
Aprajita.

**Comment by brian-c** [comment]
@aprajita Still working on it. This issue will close when the guide is available.

**Comment by aprajita** [comment]
thanks @brian-c, look forward to it. we'd like to launch new space warps projects early next year so do let us know when this is available. 

Just a quick question, is a field guide the same as a spotter's guide?

**Comment by brian-c** [comment]
The field guide (same as spotter's guide) is available behind an admin flag. @aprajita what project would you like it enabled for?

**Comment by aprajita** [comment]
Hi @brian-c Thanks - there's a demo project we are trying out 
 https://www.zooniverse.org/projects/aprajita/swdemo/classify/
let me know if I should add you as a collaborator.
