### ISSUE TITLE
Implementing the multi-person private messaging capability on the Front End?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1769]
@parrish - If I recall correctly there is the ability in the backend to send a private message privately to more than one person is finished. It doesn't look like it is implemented on the front end, The form only allows adding one name in the inbox. Thought I'd mention it as a reminder.  Feel free to close as you see fit.

**Comment by parrish** [comment]
I think it's more an issue of "should we" here.  I think having the moderator/admin/team boards help a lot with the motivation for this.

I think we'll probably sit and think on this one for a bit.  I'd like to get some input from @chrislintott too -- he's been fairly opinionated about this.

**Comment by mschwamb** [comment]
No problem. No strong opinions, so feel free to close or mark as will not fix in the meantime.

**Comment by parrish** [comment]
It's definitely not "won't fix."  Considering the API already supports this, it's certainly an option.

It's really just a question of whether or not we want to encourage this kind of private conversation.

**Comment by aweiksnar** [comment]
Agree with what @parrish added here, The frontend would be easy to integrate this as well. I think we started with 1-on-1 conversations with the thought that private boards / open discussions would likely be better homes for group discussion

**Comment by vrooje** [comment]
I think multi-person PMing encourages cliquishness, which I'd prefer to avoid.

**Comment by eatyourgreens** [comment]
Bumping this, and re-opening, since it's been requested on Talk. https://www.zooniverse.org/talk/14/342985

**Comment by eatyourgreens** [comment]
Looks like the messaging components support this, but it should probably limit the number of recipients to something small. This is for the case where you want to quickly ping two or three people about something, rather than start a discussion with a long-term group.

**Comment by mschwamb** [comment]
yeah I think it would be helpful especially if you're messaging the Talk moderators. Currently I have to do this all in email

**Comment by eatyourgreens** [comment]
I thought we'd set up aliases for the team, and moderators. Is that only for mentioning them in posts, not private messages?

**Comment by vrooje** [comment]
As far as I know it's only for boards. When I'm the project owner I work
around the non-multiple-PMs by setting up a team-only board and using that
to keep in touch with everyone at once (forcing a notification by using the
@s), but being able to PM a few people at once would be really useful in
other cases.

**Comment by eatyourgreens** [comment]
[From `PMason` on ZooTalk](https://www.zooniverse.org/talk/14/342985?comment=573023)
>This would be handy - for example to coordinate a group of volunteers that were working on some aspect of a project such as building a group collection or gathering specific images for the team to improve the Field guide.
In the past I had to send multiple copies of messages to the group members individually.

**Comment by eatyourgreens** [comment]
Consensus seems to be that this is useful, but limit it to maybe 5 people or less? For larger groups, you should be setting up private discussion boards.

**Comment by vrooje** [comment]
5 seems a decent number... definitely wouldn't want it to go any higher than that, but if a project had a lot of moderators that would likely include them all, I think.

**Comment by mschwamb** [comment]
I still think this would be good, because effectively I don't use Talk messaging when talk to the moderators since I have more than one and can't include them both in the conversation at once for example.  I can see what not to do this since email exists

**Comment by camallen** [comment]
This is already supported via a private talk board that can be setup from talk page in the lab.
