### ISSUE TITLE
Owners can't set themselves as experts (and thus can't enter gold standard data)

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1770]
I feel like we fixed a similar issue previously. When I go to the collaborators page for a project that I own, under the "project owner" heading, all I get is text saying "you are the project owner." I can assign other people roles of collaborator, expert, researcher, moderator, tester, etc, but not myself. I think this is a high priority, as it affects gold standard data entry as well as how project owners appear on talk.

**Comment by edpaget** [comment]
Owners count as experts (at least on the backend).

**Comment by aliburchard** [comment]
Hrmmmm I don't think that's wise. I am the project owner on a lot of projects that I know very little about, mostly because I was needed to set up the experimental tool. Or because, like @mschwamb and @CKrawczyk, @vrooje and @mkosmala, I'm familiar with the project builder and wanted to give someone a leg up on the process. I shouldn't be labeled as a researcher, expert, or anything but owner on any of those preojcts. I think we really need owners to be able to assign themselves only the labels that apply on any given project.

**Comment by edpaget** [comment]
You have to deliberately be in expert mode to trigger it, so don't turn expert mode on for yourself if you're an owner and not an expert.

**Comment by aliburchard** [comment]
Do project owners inherently get *all* project labels by default as well? I can open as a different issue, but we really need to be able to assign owners the appropriate labels on projects.

**Comment by vrooje** [comment]
I think it would be good to have owners get to decide what displays on the Research page, but I also think they should have access to all features. As long as they can't accidentally be counted as an expert when they weren't trying to be, I think that's fine.

**Comment by edpaget** [comment]
I think we shouldn't use roles as a label. Owners can do whatever on projects and they will should always be able to do so. 

Instead of label users based on roles, there should just be a freeform field you can fill in next to users with roles to give them whatever title you want. Otherwise we're never going to make everyone happy.

**Comment by vrooje** [comment]
I like that.

**Comment by aliburchard** [comment]
Oh that's a really interesting idea - I *love* the idea of not using 'roles' as 'labels'.

Can we actually work that into the front end displays on talk/research pages? I know redesigns are in the works, but don't have a good sense of the mechanics needed to implement that...

**Comment by brian-c** [comment]
@edpaget are you saying that the back end should return project owners' roles as including "expert", or that any time the front end is checking for expert status, it should also look for "owner"? The former is preferable if we're not going to allow owners to mark themselves as experts.

**Comment by edpaget** [comment]
It should check for owner as well. The backend looks for either owner or expert when it get 'expert' mode classifications.
