### ISSUE TITLE
Noticing a siginficant lag time to load Notes board 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1777]
I noticed this is Taiwan and it's still happening while I visit the UK, so I don't think it's my length of connection to the Virginia Amazon farm. I notice it takes a good 30 or more (if I'm in Taiwan) for the notes first page to load. Is there a way to index to make that speed up?
screenshot of it loading
![screen shot 2015-10-16 at 3 46 10 am](https://cloud.githubusercontent.com/assets/753325/10532798/159ce3b4-73ba-11e5-8bda-cc7607d5de78.png)

**Comment by aweiksnar** [comment]
@mschwamb I did notice this earlier today, but it seems to be loading more efficiently now. Same for you or still happening?

**Comment by mschwamb** [comment]
@aweiksnar yes it's gotten faster. But it was  slow earlier this week.

**Comment by mschwamb** [comment]
Looks fine now. So I'll close and reopen if I see it again.
