### ISSUE TITLE
Making it harder to delete a talk board/thread?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1778]
I accidentally deleted the wrong private moderator thread (no real harm done, just kept the test thread instead and deleted the thread with a single post reporting the possible issue). Right now Talk confirms with a yes/no question. Should it make you type in the name of the board? Definitely on me for doing something without triple checking, but thought I'd mention it for @aweiksnar and @parrish to decide.

**Comment by parrish** [comment]
Oops.
