### ISSUE TITLE
Allow admins to edit all projects

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#1780]
It'd be great if there was a UI for admins to edit any arbitrary projects. I was thinking specifically so that I can add collaborators to Zooniverse-owned projects without having to log in as zooniverse, but it'd probably make sense to just let admins use the whole project builder UI for every project.

**Comment by chrissnyder** [comment]
Is this not the case now?

**Comment by astopy** [comment]
Not that I can find. There’s limited editing on the admin page, but no way to edit other people’s projects via /lab/.

**Comment by chrissnyder** [comment]
I think we do have to add a check for admins on a project-specific lab url, like https://www.zooniverse.org/lab/21 for Galaxy Zoo. Looks like it just checks for owner/collaborator status currently.

**Comment by chrislintott** [comment]
What’s the use case for this? I’d be very reluctant to modify other people’s projects.

**Comment by astopy** [comment]
We normally wouldn’t need to edit other people’s projects and obviously we wouldn’t ever want to change things without the user’s permission unless we really have to, but there are any number of edge cases where it would be useful to have a UI for it. For example, if we want to look at a user’s project in the project builder while providing tech support, or if we need to remove objectionable content, or if we need to fix any major mistakes in a project we’re promoting but can’t get in touch with the owner.

It’s not like we can’t already edit this stuff — if we really need to we can just change anything we want in the database — but ideally we don’t want to have to edit things by hand in the backend like that, because there’s a bigger risk of mistakes happening (especially if it’s an emergency and we’re in a hurry). Turning on the project builder for admins immediately gives us a full UI to do anything we’d need to do.

**Comment by mrniaboc** [comment]
+11 for this

**Comment by alexbfree** [comment]
OK there seems to be some disagreement about whether this is a feature request or a bug - see #2150 .

I note there was some discussion on this on this internally, zoo staff can check https://zooniverse.slack.com/archives/general/p1462873464000780

**Comment by chrislintott** [comment]
I've finally decided this is allowed, though admins should use their power sparingly. Make it so.

**Comment by alexbfree** [comment]
to whoever implements this, there is some background reading on the usecases in the RFC: https://github.com/zooniverse/rfc/issues/4
