### ISSUE TITLE
If you move a thread, it doesn't automatically change the location listed in the top of the page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1790]
I moved a thread to a new board just created, and when I did the location part that has the different links on the top of the page didn't update, so for a second I wasn't sure if it had moved the thread. Moving back to Zooniverse Talk and the new board confirmed the thread had moved. 

Not sure what solution would be helpful, but perhaps if you get directed to the new location of the thread after moving it that would help. 

Talking about this text:
![screen shot 2015-10-19 at 3 14 12 am](https://cloud.githubusercontent.com/assets/753325/10572736/7bd445de-7610-11e5-8871-b847872146ad.png)

**Comment by DarrenMcRoy** [comment]
I noticed the other day that moving itself had broken. At least that's back, but yes, this would still be an issue.

**Comment by aweiksnar** [comment]
Thread moving is correctly updating the breadcrumbs for me. Is there a specific set of steps I need to take in order to replicate this case? I tested firefox/chrome with both zoo-talk and project-talk threads

**Comment by mschwamb** [comment]
Strange .... it worked now.... hmm.. maybe I imagined it... Closing. If I see it again, I'll reopen it.
