### ISSUE TITLE
Username and password appear in plaintext of URL after logging into Panoptes

### ISSUE THREAD

**Issue by willettk** [zooniverse/Panoptes-Front-End#1791]
A colleague was working on the classification interface with Panoptes and saw their username and password as plaintext in the URL bar. They had some security concerns about this, especially the password - is this expected behavior for Panoptes?

(screenshot below truncated)

![screen shot 2015-09-08 at 9 55 39 am](https://cloud.githubusercontent.com/assets/2285931/10577166/1cbe6288-7669-11e5-99ca-42d4a70f02d6.png)

**Comment by camallen** [comment]
@willettk thanks for reporting..that is an issue. Pretty sure we know what this is..i'll have a look.

**Comment by camallen** [comment]
I can't replicate this..@willettk can you provide more context?

**Comment by brian-c** [comment]
Last time this happened I think there was a browser plugin interfering with forms' submit events' `preventDefault` method. There's probably an auth form somewhere without a `method="POST"` attribute.

**Comment by willettk** [comment]
I don't have context beyond this; he couldn't recall where he was in
building the project. It's not high-priority for me, but seems to be
something we should log in case it happens to other users.

**Comment by camallen** [comment]
@brian-c sign in form has the method declared [here](https://github.com/zooniverse/Panoptes-Front-End/blob/0d3616c21d961a1b1980d792f576202ea9f779da/app/partials/sign-in-form.cjsx#L28). Browser plugin could be it, @willettk can you get them to test it sign in via the browsers Incognito mode?

**Comment by willettk** [comment]
Sure - I'll report back what he says.

**Comment by willettk** [comment]
Main user reports that he cannot replicate the problem. I'm fine with closing this.

**Comment by camallen** [comment]
please reopen if it's still an issue.
