### ISSUE TITLE
Request for Talk email notifications for new discussions

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1793]
It would be great to be able to receive email notifications for all new Talk discussions for a particular project. This would be particularly helpful for new science teams to monitor the Talk boards -- especially at project launch. If we could monitor and respond to discussions in real time without having to sit on the Talk boards, it would save the science teams (and their moderators) a lot of time AND increase user engagement.

**Comment by DarrenMcRoy** [comment]
I think this would be useful for some users as well as a part of building out what the Notifications email contains and looks like, as well.

**Comment by mschwamb** [comment]
I think for large spikes it's better to not get flooded by email, especially with the large number of notes boards.. If there's a press release and hundreds of posts being made individual emails would be excessive. 

If this feature is added, it should be by default off and only turned on if needed.

**Comment by mkosmala** [comment]
Agreed that it should be default-off. I don't think *most* people want that much email. But it would be super useful for some people some of the time.

**Comment by parrish** [comment]
I considered it -- the user is basically subscribing to a board.

I backed off on implementing it since it's probably only useful to team members (and fewer would prefer it enabled).

I would probably set this up as an opt-in "Subscribe to new discussions in the board" type thing and *definitely* default "never" for email

**Comment by vrooje** [comment]
Agree on the option, and on opting in, and probably digest by default if opted in, perhaps even with an explicit warning that the "immediately" option might generate a *lot* of email.

**Comment by parrish** [comment]
This is currently implemented.
