### ISSUE TITLE
User is seeing Sunspotter twice in stats (with different classification counts)

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1797]
Any idea what might be causing this?

![tne9kw7](https://cloud.githubusercontent.com/assets/8987864/10584202/6e53fd28-7656-11e5-8752-9ecd8e7c18c6.jpg)

User @Panasko is showing Sunspotter twice, once with 12,699 and once with 12,365. Thoughts?

**Comment by chrissnyder** [comment]
@camallen Migration error?

**Comment by camallen** [comment]
Yep, i'm on it.

**Comment by chrissnyder** [comment]
@DarrenMcRoy Can you see if the issue was resolved?

**Comment by DarrenMcRoy** [comment]
[Confirmed fixed!](https://www.zooniverse.org/talk/17/12069/?comment=26869)
