### ISSUE TITLE
Making the  'Get Started On a Project Now' list to rotate though the list of Zooniverse projects or a specific subset?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1798]
Currently the list of projects at the end of the front page of the Zooniverse home page has hardcoded in to show the first four projects that launched with the project builder. Should it switch through a select subset of projects or all the Zooniverse approved projects 

Referring to this:

![screen shot 2015-10-19 at 12 14 34 pm](https://cloud.githubusercontent.com/assets/753325/10585071/4e588142-765b-11e5-9af8-7c420b885866.png)

**Comment by DarrenMcRoy** [comment]
I would like this to be eventually something decided upon by the volunteers, but in the meantime, I'd be up for making it our four most recently released projects (i.e,, the top four appearing on the Projects list).

**Comment by chrissnyder** [comment]
Will eventually be entirely replaced by some sort of personalized experience. We aren't quite in a position to do anything right now on this, but will soon.
