### ISSUE TITLE
Having the larger image view show up in a pop-up window in Talk?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1799]
I like the new  full image view button. It currently takes you to a new page and tab (on Firefox Mac version). I think it should open a popup subwindow like the behavior when you hit the metadata button. I think the main behavior is to  quickly look at it and then go back to the discussion. It's currently the only button that takes you away from the talk page

![screen shot 2015-10-19 at 12 23 35 pm](https://cloud.githubusercontent.com/assets/753325/10585309/4753a4b6-765c-11e5-849a-93ee0bf0a20a.png)

**Comment by chrissnyder** [comment]
Eventually perhaps, but this was just launched, so let's table the discussion for now.
