### ISSUE TITLE
Adding the Talk sidebar to the subject page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1803]
This would help with the range of hashtags and help keep the popular sample in use, where without having that people are now using many hashtags to describe the same features because they aren't being provided with suggestions. They only time you see the hashtag list is on the boards and front page. Having it on the subject pages would help teach terminology developing in the Talk community. 

This might fall under the subject page revamp, but if this is not being implemented in the near term, I think adding in the Talk side bar, would be extremely useful in the interim.

**Comment by parrish** [comment]
(Ignore the previous reference, got the issue number wrong)

I'm going to be consolidating issues around the subject and collection pages shortly.  This will be on the list

**Comment by mschwamb** [comment]
Sounds good. Thanks @parrish
