### ISSUE TITLE
on some project Talks, researchers have two stripes

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1806]
I'm not sure if this is a bug or a difference between projects with Talk created before launch of the new Zoooniverse api and new Talk and those created after. 

Noticed this when I was checking something on Talk compared to Fossil Finder Talk 

![screen shot 2015-10-20 at 4 04 30 am](https://cloud.githubusercontent.com/assets/753325/10604180/4daa8a32-76e8-11e5-94ea-ea0c51398287.png)

On P4: Terrains talk the research team has one  stripe.

**Comment by chrissnyder** [comment]
No idea. @camallen ?

**Comment by DarrenMcRoy** [comment]
I'm guessing this has to do with project owner permissions being labeled as "researcher" (a decision we made to keep things simple) -- and then them again being marked as researchers?

**Comment by mschwamb** [comment]
@DarrenMcRoy it's present for other members of the science team for that project, not just the project owner

**Comment by camallen** [comment]
@chrissnyder that user has 3 talk roles on the project (talk section), 2 that map to the researcher label [here](https://github.com/zooniverse/Panoptes-Front-End/blob/cc70e95a4f0cf6e3fd5a48713befe71d9dcfa820/app/talk/lib/display-roles.cjsx#L7). We should probably just map the uniq roles to their label and not the name in those methods on render so it only shows once.

```JSON
{
    "roles": [
        {
            "href": "/roles/498",
            "links": {
                "user": "...."
            },
            "created_at": "2015-07-07T11:07:55.704Z",
            "id": "498",
            "is_shown": true,
            "name": "admin",
            "section": "project-275",
            "updated_at": "2015-07-07T11:07:55.704Z",
            "user_id": "...."
        },
        {
            "href": "/roles/725",
            "links": {
                "user": "...."
            },
            "created_at": "2015-07-16T06:59:28.449Z",
            "id": "725",
            "is_shown": true,
            "name": "scientist",
            "section": "project-275",
            "updated_at": "2015-07-16T06:59:28.449Z",
            "user_id": "...."
        },
        {
            "href": "/roles/724",
            "links": {
                "user": "...."
            },
            "created_at": "2015-07-16T06:59:28.329Z",
            "id": "724",
            "is_shown": true,
            "name": "team",
            "section": "project-275",
            "updated_at": "2015-07-16T06:59:28.329Z",
            "user_id": "...."
        }
    ]
}
```
