### ISSUE TITLE
Subject set dissappears from workflow

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#1807]
From the talk board (https://www.zooniverse.org/talk/18/12990/?comment=25547):

> HI, I have been trialing different options for my project which is aimed at classifying wildlife in images taken on automated cameras. Initially I had it set up to classify each photo, but as photos are taken in sets of three it made more sense to have the user see all three shots at once. So I uploaded a small image data set (18 photos 6 subject sets) with the manifest set with the three photos per subject. Unfortunately every now and then the system seems to crash and a message will suddenly come up saying "Error: no subject set is associated with this workflow". This has happened in the middle of testers classifying images and also when the tester first logs in and starts the classification process. I have double checked that the correct set of images are associated with the workflow and it seems to work fine and then sometime later it does the same thing without me having made any changes to the project. Any ideas?

Has anyone else seen this behavior?  Also I am not sure if this a front-end or back-end issue.

**Comment by chrissnyder** [comment]
The only times I've seen this occur is right after I've made changes to the project that causes the API to rebuild the subject queues. Don't think I've ever seen it happen if I gave it a bit of time to build them (say 15 minutes). Sounds like this person waited that long in any case?

**Comment by camallen** [comment]
This should only happen when there is a workflow without subject sets attached. By default the system will select an active workflow at random (it's an option that can be overridden in the project builder).

<img width="223" alt="screen shot 2015-10-21 at 09 01 16" src="https://cloud.githubusercontent.com/assets/295329/10630931/6563fe34-77d2-11e5-8d1f-d07321335572.png">

So if that project has multiple *active* worklfows and one has no linked sets then this error will happen intermittently. Best bet is to deactivate the workflow (though looking at the project builder it doesn't seem to have an option for this, we should add this as the [api supports it](https://github.com/zooniverse/Panoptes/blob/a97548fe8d967e2662acf86ac2f139507d70bb7f/app/schemas/workflow_update_schema.rb#L20)) or remove it if it's and empty placeholder. Finally if this is not the case then i'll need some more details to debug.

**Comment by srallen** [comment]
Lab interface allows activation/deactivation of workflows.
