### ISSUE TITLE
Subject metadata hyperlink

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#181]
We want to allow our users to go to a link based on the image shown. I'm thinking the best way to do this is to provide a URL in the subject metadata. Would it be possible to have this URL automatically become a hyperlink, perhaps through Markdown or some other sort of tag?

**Comment by twhyntie** [comment]
:+1: This would be super-useful for us too. Looking [here](https://github.com/zooniverse/Panoptes-Front-End/blob/6512c5cdc25f0b3073d35c28e4b880cf9a27a86e/app/components/subject-viewer.cjsx)  - if there was a way for the subject display to wrap a hyperlink (with `target="_blank"` to open a new tab) around the `<img class="subject">` tag in line 41, based on the presence of a `url` column in the metadata, that would be great (the workflow task would need to tell the user to click on the image and why they'd want to do that, as I can't see an easy way to customise this in the code).

**Comment by vrooje** [comment]
Would it be better, or at least acceptable, to have the URL show up on the
post-classification page as a link or button option in addition to "Next"
and "Discuss"? For many research applications I'm wondering if having a
link to an external page during the classification could present issues of
bias that aren't easy to correct for in the data reduction.

**Comment by twhyntie** [comment]
@vrooje No, not if (for example) the link is to a high-res version of the image being classified (this is being mooted as a workaround for zoom functionality for first release).

A health warning for project builders about the risks of bias in the help text/user guide would be good though :-)

**Comment by vrooje** [comment]
Right, have just seen the other issue on that. Good point on the zoom
feature.

**Comment by mkosmala** [comment]
@twhyntie @vrooje I'll point out that as much as you might try to reduce bias, motivated users are always going to try to use extra information, if possible. We have Snapshot Serengeti volunteers who download nighttime images to alter their brightness and contrast in programs on their computer. This works! You can see animals better by playing around with those controls. But we figured it was too much to include that sort of thing in the SS interface.

**Comment by vrooje** [comment]
Definitely, but we should force them to hack it on the assumption that the vast majority of users won't :) I think a warning label to research teams is a good idea.

**Comment by twhyntie** [comment]
@mkosmala That's cool! :-) But isn't this a bit different? The extra information you're referring to is fundamentally embedded in the image, and your volunteers have spotted a way to extract maximal information from your data. They should probably get a publication credit :-)

This issue is about volunteering (so to speak) additional metadata that might introduce bias. If it's possible to turn it off, that would be great.

**Comment by mkosmala** [comment]
I guess I'm just thinking about zoom. If we could zoom in the interface, users could "extract maximal information" fairly easily. Instead, we want to link to the original image because zoom is not currently supported. So it won't be quite as easy, but it should satisfy the motivated users. 

I can see that offsite metadata might influence user choices on the site, and it's worth a warning to project builders. Yes.
