### ISSUE TITLE
Favorites say they are public but really they are private 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1812]
Not sure if this front end or backend since it might just be appearance. 

![screen shot 2015-10-21 at 3 50 48 am](https://cloud.githubusercontent.com/assets/753325/10632019/54c1f728-77a7-11e5-8620-c5ae502d9edc.png)

As far as I can tell favorite collections are private by default, but if you look the properties of a default public collection it says it is public, though I can't see it in my list of collections or user profile. Is this the intended behavior?

When I go to https://www.zooniverse.org/favorites/mschwamb/ it says 'No Collections Found'

**Comment by camallen** [comment]
@mschwamb looks like an API bug. Can you PM me the details of a public collection you have? I'll look into it.

**Comment by mschwamb** [comment]
@camallen in your inbox.

**Comment by camallen** [comment]
this is a false positive, the private value is actually null but the check box defaults to public, thus masquerading as public. I'll get a PR together for this.
