### ISSUE TITLE
Unsubscribe button has broken

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1814]
https://www.zooniverse.org/unsubscribe

The button to unsubscribe appears to have become unclickable (tested in two browsers).

**Comment by camallen** [comment]
Just tested, did you enter a valid email address e.g. test@test.com. The button will only be active with a valid email.

**Comment by DarrenMcRoy** [comment]
Whelp, I was a dolt. It's fine.
