### ISSUE TITLE
Deleted post still shows as most recent post

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1823]
A comment that has been deleted shouldn't show up as the most recent.

![screen shot 2015-10-22 at 10 25 53 am](https://cloud.githubusercontent.com/assets/8987864/10669661/6027c600-78a7-11e5-967f-c9a57e586a8f.png)
![screen shot 2015-10-22 at 10 26 04 am](https://cloud.githubusercontent.com/assets/8987864/10669663/6306c5b0-78a7-11e5-8f61-99760052ceef.png)
![screen shot 2015-10-22 at 10 26 12 am](https://cloud.githubusercontent.com/assets/8987864/10669664/65ef841a-78a7-11e5-9694-507c833ebd4d.png)

**Comment by parrish** [comment]
Yep.  I don't think that's a problem.

**Comment by DarrenMcRoy** [comment]
... seems to me like it shouldn't happen? People care about the most recent *relevant* post, not something deleted.

**Comment by parrish** [comment]
¯\_(ツ)_/¯

Deleted posts seem relevant to me

**Comment by DarrenMcRoy** [comment]
Open to others' thoughts about how this should look.

**Comment by mschwamb** [comment]
I don't think it happens enough to worry about it.

**Comment by CKrawczyk** [comment]
Like @DarrenMcRoy I found this behavior a bit strange, but it not that big a deal for me.
