### ISSUE TITLE
Ability to generate list of all tags used sorted by frequency

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1824]
There is an [extensive discussion going on on ZooTalk](https://www.zooniverse.org/talk/14/12851/?page=1) with several users requesting a tool to generate a complete list of all tags used on a project, orderable by frequency (and perhaps also alphabetically) that is more extensive than the current "popular tags" list.

The idea behind it seems to be that it will help volunteers to get a better idea of what tags are being used and to avoid duplicating tags. I know that we're going to add autocomplete at some point, but this seems to be quite strongly requested. (They'd like it in V2 Talk as well, although I don't know if we can do that.)

To quote one user: "What I'm really assuming is that such functionality, to list all the tags, already exists somewhere beneath the surface. And just asking for it to be made visible."

**Comment by parrish** [comment]
Tag data export is already available to project owners.  If they choose to share that, then they can.
