### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by parrish** [zooniverse/Panoptes-Front-End#1828]
- [x] Talk sidebar (including popular tags for the subject) #1830
  - [x] Focused comments and discussions #1831
  - [x] Mentions  #1832
  - [x] Collections #1833

**Comment by mschwamb** [comment]
@parrish For your consideration. I think listing tags associated with the subject should be on that list. I use that and the collections hyperlinks alot on previous iterations of Talk.

**Comment by parrish** [comment]
Whoops.  Missed that one.

**Comment by chrissnyder** [comment]
:+1:

**Comment by parrish** [comment]
@aweiksnar I'm going to self assign one of these and see where I get to today.  Happy to talk through these tomorrow too.

We should probably also look for ways to abstract the focus (subject/collection) since there's a lot of overlap.

**Comment by aweiksnar** [comment]
Cool sounds good to me (also thanks for organizing these :v:) Yeah let's chat a bit more during stand-up tomorrow

**Comment by mschwamb** [comment]
Cool @parrish . Thanks. Adding in the list of hashtags would be amazing. Looking forward to seeing the updated subject pages. They'll be incredibly useful.
