### ISSUE TITLE
Drawing tools don't work on iPad

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#184]
I can't draw ellipses, polygons, or points on Safari on my iPad. Nothing happens when I try to do so.

**Comment by brian-c** [comment]
Possibly React's touch event system not getting hooked up right. Also might have to do something like `(e) -> e = e.touches?[0] ? e` in various mouse event handlers.

**Comment by CKrawczyk** [comment]
There is a smiler issue on Android as well: I can draw points and polygons (don't require tap and drag), but not lines or ellipses (require tap and drag).
