### ISSUE TITLE
PMs in inbox displaying out of order

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1845]
Private messages have started displaying in the order of the first message, not the order of the most recent.

**Comment by DarrenMcRoy** [comment]
Still happening... here's a visual example.

![screen shot 2015-11-13 at 2 29 17 pm](https://cloud.githubusercontent.com/assets/8987864/11156688/03e144f2-8a13-11e5-9633-dbc3a17d7cc8.png)

**Comment by mschwamb** [comment]
I'm getting that too. Especially that sometimes I read the message start replying get distracted save the reply in a text file and come back later. @aweiksnar is this something you can look at whenever you have free time in the new year?

**Comment by mschwamb** [comment]
I just noticed it's after you read the new reply in the message thread, that it goes back down into the order the first message was received.

**Comment by parrish** [comment]
Working as intended.  (Unread, last_updated)
