### ISSUE TITLE
Changing the size and location of the subject image on the subjects page?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1848]
This might be more on the eventual graphic redesign but thought it was worth bringing this up to @parrish and @aweiksnar  for your consideration and general discussion while you're updating and adding stuff to the subject pages

Currently the way the subject image is displayed you  have to scroll down to where you can input text. The size of the image is great for seeing lots of detail, but on my 13 inch screen I don't have much of that image visible when I write a post on the subject page, especially if there are other posts visible 

I'm not saying the subject page has to be organized the same way as in previous versions, but I find the location of the subject image in the top left corner on Talk 2.0 allowed being able to look at everything else about the subject and still see the subject image when starting a new thread or adding the 140 character comment equivalent of a note.

In panoptes talk  there is a smaller thumbnail, but  you can't see much detail, I think it would be need to be maybe twice the size to be useful for discerning features (maybe that's a possible solution to this). 

Some screen shots for comparison to try and explain my point. 

![screen shot 2015-10-23 at 2 32 49 am](https://cloud.githubusercontent.com/assets/753325/10682561/f442344c-792e-11e5-8f06-4ec2d8ed0d6b.png)

![screen shot 2015-10-23 at 2 11 38 am](https://cloud.githubusercontent.com/assets/753325/10682576/19a1c14e-792f-11e5-99b1-4b6259261218.png)

![screen shot 2015-10-23 at 2 38 41 am](https://cloud.githubusercontent.com/assets/753325/10682594/3dcd75d6-792f-11e5-8cb7-fa4b4bdb9c32.png)

**Comment by alexbfree** [comment]
looping in designer @jwbmartin

**Comment by aliburchard** [comment]
Agreed!

**Comment by parrish** [comment]
Yep, agree that we should get it above the fold.  I'm punting stylistic and layout changes until after we can work through a wireframe though.

**Comment by jwbmartin** [comment]
Hmm interesting. These are definitely good things to consider as I move forward with the subject page wireframes.
