### ISSUE TITLE
footer on "zooniverse.org" pages not scaling properly

### ISSUE THREAD

**Issue by lfortson** [zooniverse/Panoptes-Front-End#1849]
Resizing the browser window causes the footer columns to move "off-screen".
See attached screenshot which is on the /lab page but this is true for all
pages on
https://www.zooniverse.org

running Safari Version 8.0.8 

<img width="1135" alt="footer-scale" src="https://cloud.githubusercontent.com/assets/1714816/10693857/896d7352-7960-11e5-8f6e-a7d004a3cb28.png">

**Comment by aweiksnar** [comment]
Closed in  #1872
