### ISSUE TITLE
"Discuss" vs. "Talk"

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#185]
On the interface, the tab says "Discuss", but at the end of the workflows, the button says "Talk". Can this be made consistent?

**Comment by chrissnyder** [comment]
@mrniaboc @DarrenMcRoy Thoughts on this? Been a recurring issue for us and would be great to arrive at a decision here.

**Comment by brian-c** [comment]
I really think we should stop using "Talk" to refer to certain sections on the site. It made more sense when Talk itself was a separate site, but now that discussion happens in context, we should use language that reflects that: "Join the discussion" vs. "Go to Talk", etc.

**Comment by DarrenMcRoy** [comment]
I agree with Brian that we should generally change the branding to "Discuss" since Talk is no longer its own area.

But I wonder about place where Talk IS still its own area, like the Zooniverse Talk? Perhaps we keep the branding for that one area? Or do we try to dump the "Talk" name altogether?

**Comment by vrooje** [comment]
$0.02: I prefer Discuss throughout.

**Comment by mrniaboc** [comment]
Very much agree that we should go for one or the other, but I don't see why it shouldn't be 'Talk'. That's what we all call it in house. It's what all the super-users call it. I see the point about making it sound like a separate area, but that is not tied to the name. That is a language issue. I.e. 'Go to Talk' vs 'Talk about this'.

**Comment by DarrenMcRoy** [comment]
I've been moving more and more towards "Discuss." I'm even up for using that as the name for the new Talk: the new Talk is "Zooniverse Discuss." Been using that name in all the new writing so far.

But I share Grant's concern about changing a successful branding.

**Comment by vrooje** [comment]
I prefer Discuss slightly because it's got more of a community feel to it, but it's only a slight preference. I like Talk as the brand too.

**Comment by aweiksnar** [comment]
For the buttons, We could do something like ":globe_with_meridians: Talk" for zooniverse talk and ":milky_way: Talk" for projects.

I kinda like "Talk" because it seems to work better as a noun

**Comment by chrissnyder** [comment]
Looks like we are split down the middle. Pinging @chrislintott

**Comment by DarrenMcRoy** [comment]
We never really solved this, did we? It seems more and more like we're leading back towards "Talk."

Which I am fine with, but let's say for sure?

**Comment by edpaget** [comment]
We really shouldn't call it discuss because it's pronounced the same way as https://disqus.com/

**Comment by DarrenMcRoy** [comment]
I'd be fine with calling the Zooniverse talk ZooTalk and labeling it as such.

**Comment by mrniaboc** [comment]
I still think we should just call it "Talk" as that is what everyone calls
it. We call it that. The volunteers call it that. The researchers call it
that. Why change?

**Comment by DarrenMcRoy** [comment]
It seems like "Talk" is winning out.

Does anyone have any further strong objections to using "Talk," and labeling the hub talk as "ZooTalk?"

**Comment by vrooje** [comment]
No strong objections, though I think I prefer "Zoo Talk" with a space :)

**Comment by edpaget** [comment]
Why not just do Talk and call the link with the project Project Talk (or Planet 4 Talk or similar) that way we don't loose the main navigation links all being direct action verbs.

**Comment by DarrenMcRoy** [comment]
Hm, I like ZooTalk without a space. Seems like a "brand."

Zoo Talk sounds like where you go to talk about zoos; ZooTalk sounds like a stylish truncation.

Just my two cents.

**Comment by chrislintott** [comment]
Hate camel case. But agree ‘Talk’ is important.

C

**Comment by DarrenMcRoy** [comment]
@edpaget I think it would be good for the central Talk to have some type of unique name, since "Talk" is the overall system.

**Comment by DarrenMcRoy** [comment]
I guess I could live with Zoo Talk for first-release.
