### ISSUE TITLE
Publications page needs additional field: open-access link

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1850]
Not all journals (etc) our researchers submit to will be open-access, but all our publications should be accessible to everyone. Mostly researchers get around this by having open-access versions somewhere on the web (arXiv for physics, but other solutions exist for other fields). Sometimes they're identical, but more often they're slightly different re: typesetting and such.

We should have a field for an open-access version of every publication, so we don't have to choose between linking to the official publication and linking to an open-access version.

**Comment by DarrenMcRoy** [comment]
+1

**Comment by aliburchard** [comment]
ooh, excellent point!!

**Comment by chrislintott** [comment]
Could @mrniaboc have a look and report on anything that currently is not linked to an open access version?
