### ISSUE TITLE
New talk comment is indented in new talk, which could be confusing

### ISSUE THREAD

**Issue by crowston** [zooniverse/Panoptes-Front-End#1852]
In the new talk (e.g., Fossil Finder), the box for a new comment is indented compared to the existing comments, which might confuse a user into believing that the new comment is a reply to the previous comment rather than just being added to the list of comments.

**Comment by crowston** [comment]
Screen shot:
![untitled](https://cloud.githubusercontent.com/assets/1709163/10698065/0cbab4ce-797d-11e5-8ff0-56438ab27bb0.gif)

**Comment by aweiksnar** [comment]
Duplicate of #1776
