### ISSUE TITLE
Clearing the notifications list if you're read them all

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1862]
With the notifications, my list of things in there doesn't clear if I've read them or  hit the mark them all as read. So I'm not sure how I would know what's new and old when I go there the next time. I like the github way where when you click set all as read, the notifications then disappear the next time you go to the notifications. Is that something that could be added? I think it would help make the notifications more useful. 

In case it's a bug and the behavior is supposed to clear the notifications list on the notifications page, I'm on the latest version of firefox on mac

**Comment by parrish** [comment]
This should be behaving as intended.  When leaving the notifications page, it marks that page as read.  The "mark all as read" button will mark all pages as read.

**Comment by mschwamb** [comment]
That doesn't actually solve the issue I'm talking about, so I'm reopening.  There's no way to tell when what are new posts in the notifications page. After hitting 'mark all as read' that only turns off the counter on the notifications link to tell you, you have new notifications, but if there's  a new notification unless I can remember how many it said on the front page of Talk, I never know where the new notifications end and the old notifications begin. I'm asking for something like github where when you click 'mark as read' it will either clear the list or put some line or something so you can differentiate between old and new.

**Comment by mschwamb** [comment]
At least for me, I can't tell where there are new and old notifications begin and end.

<img width="1125" alt="screen shot 2016-03-29 at 6 40 53 am" src="https://cloud.githubusercontent.com/assets/753325/14092423/4d66c99a-f579-11e5-9d9f-101c99f661fb.png">

**Comment by mschwamb** [comment]
Or perhaps if it's easier could the white Talk background was added to the Notifications page.  That would make it a lot easier to see the highlighting for new notifications. I just spotted the blue highlight on the edge of the notification post  when I was deleting the screen shot. I've completed missed seeing the blue highlighting since notifications launched.
