### ISSUE TITLE
When you click edit on Zooniverse wide Talk focus moves to the new comment box not the comment you're editing

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1866]
This works fine on the project Talks. When you click edit, it keeps you focused on the comment edit box, but on Zooniverse wide Talk when you click edit the focus is moved down and you are automatically scrolled down to the new comment box. 

At least for me on  Mac Firefox

**Comment by chrissnyder** [comment]
Can't replicate this here. What comment/thread do you see this in?

**Comment by mschwamb** [comment]
@chrissnyder Weird... I was able to replicate it multiple times when I reported it. Can't do it now. It was in this [thread](https://www.zooniverse.org/talk/14/12851/) I'll reopen if I encounter it again.

**Comment by chrissnyder** [comment]
No worries, let us know if you can replicate it again.

**Comment by mschwamb** [comment]
So I think I figured it out. If the post you're editing is the last on in the thread then the focus moves to the bottom to new post box. If the post you want to edit is in the middle of the list of posts it says focused on that post.

**Comment by chrissnyder** [comment]
I think this more a function of the editing interface changes the vertical size of the discussion. So on long discussions, this can be jarring because the page will appear to scroll up when you click edit.

Will have a fix in shortly.
