### ISSUE TITLE
Some way of indicating a project when sending a PM

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1868]
Something requested for Talk: in V2 Talk, PMs would indicate which project they were sent from. This probably isn't possible in V3 Talk as so, since you don't have to (actually can't) be on a specific project when you send a PM.

However, the cross-project moderators say that they found that indicator of what project a message was sent from to be extremely helpful, as they now often get messages that assume they know what project the person is talking about.

Would it be possible to resolve this somehow? Any ideas? Perhaps some sort of drop-down to select the project you're talking about... or would that become too long very quickly? Any ideas?

**Comment by yshish** [comment]
As for the 'too long drop-down to select', I've got another idea: Could it be possible to make it as an autocompleting the name of the project after someone starts typing it (but it would probably need some example/Help how to use it). Not sure whether it could work even if you start with a word in the middle of the name (I'm afraid it won't be very useful if it wasn't possible). So for Wildcam Gorongosa, if you started typing *Goro...* it would offer you *Wildcam Gorongosa* 

Could this be possible?

**Comment by DarrenMcRoy** [comment]
To take the other side, this might be considered a really unnecessary feature when we could instead train people to just write the exact same thing, the name of the project they're talking about, in the "subject' line.

Maybe this is solvable by adding a note that says "If you are messaging about a specific project, please mention the project?"

**Comment by aweiksnar** [comment]
> To take the other side, this might be considered a really unnecessary feature when we could instead train people to just write the exact same thing, the name of the project they're talking about, in the "subject' line.

Yep I'd definitely agree with this. Adding a UI to populate the subject line or even linking private messages to projects in the api feels like it'd be extraneous here. I'd rather put the dev time elsewhere if it's ok with everyone

**Comment by eatyourgreens** [comment]
Re-opening this for @alexbfree now that we have the ability to send PMs from specific projects.

**Comment by alexbfree** [comment]
@eatyourgreens and I discussed this a bit (see https://zooniverse.slack.com/archives/general/p1465311829000085 and https://zooniverse.slack.com/archives/dev/p1470647316000554), I think there is something we can do here so am reopening.

We should tag messages by project, like Ouroboros does:
![screenshot 2016-08-08 10 20 15](https://cloud.githubusercontent.com/assets/1473244/17475517/50c245dc-5d53-11e6-9b8e-678c1d92da06.png)

Not sure if messages have a place we can add this metadata but we should look into it. 

We could have a general tag for Zoo-wide/non-project messages - or just absence of tabs.

**Comment by alexbfree** [comment]
i am unlikely to have any bandwidth for this so anyone else can feel free to jump in

**Comment by parrish** [comment]
Talk doesn't support this, nor do I think it should.  If moderators want to have project-specific conversations in private, they should use a private board for it.

**Comment by eatyourgreens** [comment]
This was more about mods having some indication of where a PM came from when a volunteer PMs them asking for help, for example.

At the moment, you can't easily figure out which projects requests came from, particularly if you have a busy inbox.

Personally, I'd be fine with prefixing the project name to the subject line when the message is sent from the message form within a project.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
