### ISSUE TITLE
Giving Planet Four: Terrains Zooniverse project status again

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1871]
I just pushed the new data live on the site. To do that I had to take the project to development from live. It's back to live state, but I can't hit the button to request launch. When you have a chance you reset the state of the project back to live so it's back on Zooniverse projects page and removes the warning text on the bottom saying it's not an Zooniverse approved. Thanks!

**Comment by camallen** [comment]
done

**Comment by mschwamb** [comment]
Thanks @camallen
