### ISSUE TITLE
Display images/thumbnails in search results

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1875]
This is almost certainly covered by some other issue, but when searching, even by a hashtag, you can't see any previews of the images/subjects you might be looking for.

For instance, when I'm currently hunting for DailyZoo candidates by searching the "dailyzoo" hashtag, I have to manually click into each comment before I can see even a thumbnail of the image.

Having some sort of preview would be extremely valuable.

**Comment by mschwamb** [comment]
I noticed this when searching for a previous ticket  I thought I already wrote.  @DarrenMcRoy I think this is already sorted with the tag search capability  e.g. https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/craters ?

**Comment by camallen** [comment]
just noting that tag search works and provides a preview but plain search doesn't https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/search?query=crater
