### ISSUE TITLE
Reference images on hover or inline for radio buttons task

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#1876]
The Glitch Detective project would like to be able to have reference images for radio button selections either inline or on hover. For now, they will be adding the content the help modal, but ideally would like a quick reference image for the types of glitches in the radio button selection itself. 

I'm thinking something like what Chimp&See does in the species selection step (image on hover) or what the survey task does (image inline). This may be unnecessary if we use the Chimp&See style spotters guide as discussed in #1768.

**Comment by CKrawczyk** [comment]
You can add images to the answers for questions using markdown.  I have done this the [Galaxy Zoo for Outreach](https://www.zooniverse.org/projects/klmasters/galaxy-zoo-for-schools-outreach/classify/) project with no issues.

**Comment by srallen** [comment]
Yep, and that was experimented with, but a concern that came up is that they have a list of 8 options, so the radio button list with the images would be very long especially on small screens. The survey task when filtered has images inline and the button options are displayed in columns, so reduces the vertical height. Alternatively, an on hover like Chimp&See would keep a long list compact too.
