### ISSUE TITLE
Multiple users experiencing repeats (in WildCam)

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1878]
Several users have complained that they are seeing the same images repeated on WildCam Gorongosa. It's been mentioned since September; [here's a thread about it, with several people confirming that it's still an issue](https://www.zooniverse.org/projects/zooniverse/wildcam-gorongosa/talk/79/7125/).

I feel like this has been discussed here before, but I'm not sure where we ended on it.

**Comment by camallen** [comment]
this isn't a zooniverse front end issue, move it to the wildcam repo, https://github.com/zooniverse/wildcam-gorongosa. 

Basically if users have done all the 224010 then the api will show it to them again. it will mark the response with already_seen / retired but not sure the UI is displaying these marks and letting the users move on. Can we get a science team member to reduce the data to check for dups?

**Comment by DarrenMcRoy** [comment]
Moved to https://github.com/zooniverse/wildcam-gorongosa/issues/192.
