### ISSUE TITLE
User having issue with classification export

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1882]
[A user on Talk writes](https://www.zooniverse.org/talk/18/14837/?scrollToLastComment=true&page=1) that "when I requested a new classification export I have been sent a link to the following text, rather than a CSV file:"

... and then there's a bunch of gibberish code with an error and "The request signature we calculated does not match the signature you provided. Check your key and signing method."

[Full report here](https://www.zooniverse.org/talk/18/14837/?scrollToLastComment=true&page=1). Any idea why this guy can't export classifications?

**Comment by camallen** [comment]
@DarrenMcRoy this is most likely the same issue as reported here, https://github.com/zooniverse/Panoptes/issues/1204

**Comment by DarrenMcRoy** [comment]
So it's a known issue that we haven't had a chance to patch yet? It looks like https://github.com/zooniverse/Panoptes/pull/1310 should have fixed that, but maybe didn't quite?

**Comment by camallen** [comment]
This should be fixed. it really depends on how long data processing takes and when the click the link in the email.

**Comment by srallen** [comment]
Closing as fixed
