### ISSUE TITLE
Don't send two notifications for one post

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1883]
Just noticed that if someone replies to a thread I've posted in AND mentions my username in it, I get two (2) notifications for the same post.

No need; adds clutter, and looks like the post was accidentally made twice.

**Comment by mschwamb** [comment]
I encounter the same thing. It can be lived with, but it looks more like a bug in the backend when you see it repeat.

**Comment by mschwamb** [comment]
I just got this again. Is this something that you can adjust @parrish when you have time?

<img width="1182" alt="screen shot 2016-05-22 at 8 40 00 am" src="https://cloud.githubusercontent.com/assets/753325/15451510/f4fd595e-1ff8-11e6-8764-5750700ebfb7.png">

**Comment by mschwamb** [comment]
hit this today cc @parrish

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
