### ISSUE TITLE
Adding the full list of popular hashtags to the side bar on the Talk subject pages

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1884]
One thing that the moderators are noticing is more variability in hashtags because people don't have any guides of what the collective lexicon is becoming. I know autocompletion is in the works which would help, but also having the same list of the popular hashtags  that shows on the front page of Talk show up on the subject page sidebar. I think it give people words to chose from if they want to hashtag which  think has been a big help in previous version of Talk.

**Comment by mschwamb** [comment]
@parrish Any chance this could be added to the subject pages whenever there is time? I think we're finding lots of variety in hashtags and people not seeing what the core group of active Talk volunteers has settled on for descriptions

**Comment by DarrenMcRoy** [comment]
There was loads of talk about this a couple of weeks ago. Volunteers REALLY want it. +100.

**Comment by mschwamb** [comment]
This is the last thing I think is missing from the Talk subject pages is the full list of most popular hashtags. It's been a concern for the mods at least on Planet Four: Terrains that many different tags are being used for the same thing. Having the list of most popular as well helps show people what are the most common being used. It was very helpful on Planet Four that this most frequent used tags were shown on on side so you could refer to it when making a Talk comment on a subject page. 

Any chance in the new year this could be added?

**Comment by aliburchard** [comment]
+1! @aweiksnar who would be the person to handle this?

**Comment by aliburchard** [comment]
And by that, I should say @mcbouslog are you the person to handle this? Alex, we miss you!

**Comment by mcbouslog** [comment]
I'm far from a replacement for Alex, but I'd love to help if I can.  I'll take a closer look this week to see if it's within my technical abilities, and run by Laura as well.  I'll post a follow-up comment as soon as I know more.  Thanks,

**Comment by parrish** [comment]
I think the issue with this (and why it's not being implemented yet) is that it's not a good UI decision.

Also, the API won't return an unlimited number of results -- which is necessary for performance reasons.

If we set up pagination on the list, then this could work.  The blocker for that is that we'd need to modify [the paginator](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/lib/paginator.cjsx) to accept a custom pagination param since we're paginating multiple things on the same page.

**Comment by mschwamb** [comment]
Sorry @parrish by 'full list' I mean what's already implemented on the talk front page (not adding in pagination or anything - whatever that query/api call that already is implemented). 

I mean what's on the right in this image. 

<img width="1075" alt="screen shot 2016-01-06 at 2 54 49 am" src="https://cloud.githubusercontent.com/assets/753325/12137902/88feabb4-b422-11e5-963d-d103f8054def.png">

**Comment by mschwamb** [comment]
Currently on the subject pages on the tags people have made for the subject show, but on Talk 2 there was also a part that should what's on the right in the post above, so that people had a guide of the types of things people were tagging. I think it was really useful if that isn't an API/UI or speed issue.

**Comment by mschwamb** [comment]
In case this useful - The subject came up in conversations with moderators on Comet Hunters about there being lot of variants of hashtags around for the same phenomenon , and I think having a list of what most people are using on the subject page  will help guide new volunteers when they write a hashtag if they're a new to Talk.
