### ISSUE TITLE
Hover text for returning to edit says "preview" instead of "edit"

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1885]
When you click the "preview" button on a comment, the button changes to a pencil that you can use to return to editing mode, but the hovertext still says "preview" (it should say "edit.")

Can't manage to screenshot it, but should be replicable.

**Comment by aweiksnar** [comment]
Updated in markdownz `3.1.4`  & `4.0.1`
