### ISSUE TITLE
topnav bar overflows in admin mode

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1887]
This is on my laptop with my browser at full width:
![screen shot 2015-11-02 at 16 48 04](https://cloud.githubusercontent.com/assets/2357126/10889793/ee2f99c2-818b-11e5-9e72-dfddb848b690.jpg)

It seems like things could all fit on one row, right? It does when I'm not in Admin mode.

Obviously I can live with this and it affects very few people; just flagging it in case it's a quick fix.

**Comment by srallen** [comment]
Navigation has been redesigned
