### ISSUE TITLE
Removing project owner from the recommended projects displayed on Zooniverse front page for logged in users

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1888]
I think the project owner shouldn't be listed on the project recommendations. It becomes eventually clear if you've got one that's a Zooniverse custom build, but I think otherwise it's a bit confusing,

 Also I think it allows for differentiating custom builds from project builder projects. If they're being treated the same, then it might be good to remove the thing that can identify which is which. 

Screenshot of the prompt I'm talking about:

![screen shot 2015-11-04 at 11 03 29 am](https://cloud.githubusercontent.com/assets/753325/10928529/5d43021e-82e4-11e5-9fa5-849f4879ffec.png)

**Comment by simoneduca** [comment]
Outdated, closing.
