### ISSUE TITLE
Workflow appearance on landing page

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#189]
@brian-c I'm working on exactly what the two-project solution looks like. We're going to have a totally custom landing page with two buttons that go directly to 'classify' in the two projects. 

Now, once a user is in classify in, say, Project A, and they click the "Project A" word/tab in the upper left, what happens? If we don't do anything special, they'll go to the 'landing page' for Project A. 

Question 1: Is it (easily) possible to override where this link goes so that instead of Project A's landing page, it goes to our custom landing page?

Assuming the answer to Question 1 is 'no', then we'll have to create content for the 'landing pages' of Projects A and B, with links between them and back to the custom landing page. That's fine. But leads to:

Question 2: Can we have a single button on the project landing page that goes to 'classify' without specifying workflow (and so get a random workflow)? 

Right now there's a button for each workflow on the project landing page. But I don't want users to have the option of choosing different workflows.

**Comment by mkosmala** [comment]
Can I get this addressed by milestone first-release?

**Comment by brian-c** [comment]
@edpaget can we get project-level arbitrary settings ("user_chooses_workflow", in this case) in for first release? I think you said I might be able to store stuff like this in the project's metadata.

**Comment by edpaget** [comment]
Yes. I'll add a "configuration" hash to the project resource, where you can store things like this.

**Comment by mkosmala** [comment]
Oh wow, did this get addressed? I now have a "Get started!" button instead of 10 workflow buttons...

**Comment by brian-c** [comment]
Yes, there should also be a "User chooses workflow" checkbox on the project details Lab page.

This will close automatically when that commit is merged.

**Comment by brian-c** [comment]
Ah, just realized I pushed from this branch for project listing/viewing workaround this morning. So I guess it works! I'll get it merged in.

**Comment by mkosmala** [comment]
How is the single-button vs. user-chooses-workflow toggled? I want the former when I launch, but the latter is super useful for debugging my workflows...

**Comment by brian-c** [comment]
A project's `configuration` property is a hash, and that hash's `user_chooses_workflow` property is a boolean.

**Comment by mkosmala** [comment]
Cool, thanks.
