### ISSUE TITLE
Spotter's Guide: include designated collections

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1893]
On GZ Bar Lengths I'm curating a [collection of confusing subjects](https://www.zooniverse.org/collections/vrooje/not-a-bar-but-kinda-looks-like-one/), with the intent that this might be used to help people with their classifications. But it's a bit hard to reach everyone with the collection alone.

It would be great if we could show subjects from specific collections (approved by project owners/collaborators) in the spotter's guide. 

I think it would be incredibly useful for live or near-live projects like crisis response, and also for Snapshot Supernova/other SGL-type projects (in fact I remember @rscalzo did something similar in SS using his own specific hashtags, on the Talk we were using then).

@brian-c how feasible would something like this be? (also cc @trouille @chrislintott)

**Comment by chrislintott** [comment]
I think while this would be nice, an editor for the field guide would allow team members to add whatever images they like. I find it hard to imagine a team (even in fast moving projects) not wanting to vet what appears in the guide.
