### ISSUE TITLE
subjects added to favorites/collections going to the wrong place

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1894]
I've been curating a specific collection on GZ Bar Lengths, but when I checked it tonight there were subjects in there that definitely should not be there, that I had in fact added to my favorites but somehow ended up there. In my project-specific favorites it looked like mostly the same subjects were there too, but these collections aren't meant to be duplicates of each other. I tried to clean these up and move some of the subjects from the collection to my project-specific favorites, but they weren't showing up on refresh.

Eventually I found them:
![screen shot 2015-11-07 at 02 46 26](https://cloud.githubusercontent.com/assets/2357126/11013219/81483710-84fb-11e5-8fc5-1af6957ce77b.jpg)

Oops... there are galaxies in my Wildcam Gorongosa favorites. (There's also 1 subject from WG.)

Not exactly sure what's up here, but something is definitely up.

**Comment by camallen** [comment]
this should have been fixed by #1886, any chance you can test again?

**Comment by vrooje** [comment]
Just tested, and favoriting/unfavoriting this galaxy from [this subjects page](https://www.zooniverse.org/projects/vrooje/galaxy-zoo-bar-lengths/talk/subjects/465188/) still adds to/removes from my Wildcam Gorongosa favorites. 

When I click from that subject page to go to the Subject Notes thread in GZ Bar Lengths, it actually takes me to the Notes thread as a Zooniverse Talk page instead of a project Talk page, and I can't favorite it at all:
![screen shot 2015-11-09 at 10 49 57](https://cloud.githubusercontent.com/assets/2357126/11031961/1549dbbe-86d0-11e5-91ee-6933e924859b.jpg)

**Comment by camallen** [comment]
This is a breaking change in the API layer due to https://github.com/zooniverse/Panoptes/pull/1453, i'll get a fix for this asap.
