### ISSUE TITLE
Workflow 'help' key

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#190]
As @brian-c explained in #70, each workflow task can have a "help" key that gives more info when the user clicks on the help ("Need some help?") button.

Since the value for the "help" key is in markdown, I could include images, which might be useful in some cases. Will images in help be supported on the front end? (i.e. if I include images in my help markdown, will they be displayed?)

**Comment by brian-c** [comment]
Yes, we'll make sure images in Help text are displayed.

As far as uploading/hosting/selecting images, we'll have to see what happens with zooniverse/Panoptes#443.
