### ISSUE TITLE
Is it possible to disable the "Thanks! Your classification" page/step

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#1902]
Hi there

I'm building a trial Space Warps site with the Project Builder, I just wondered if there was a way to disable the  "Thanks! Your classification" page/step. As you may know SW is designed to be a fast scroll through larger numbers of images and this page would slow the classification down. If there is an option to disable this, how can I do that?

Many thanks
Aprajita.

**Comment by chrislintott** [comment]
This is on our to do list!

C

**Comment by aprajita** [comment]
Thanks Chris, who should I chat to in zoo town about the other front-end
things or should I turn each query into an issue?
Thanks
Aprajita.

**Comment by chrislintott** [comment]
Separate issues would be helpful

C

**Comment by srallen** [comment]
Hide classification summary is an experimental feature that can be requested to be turned on.
