### ISSUE TITLE
Unable to make new collections

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1908]
If you try and make a new collection and add a  subject to it, there are no errors thrown in the console that I could see, but no collection is made, nothing new shows in my collections list. This was brought up by a Planet Four: Terrains volunteer, and I get the same behavior.

**Comment by camallen** [comment]
@aweiksnar i've got an API PR that will fix this but the messaging should probably be better on create failure.

**Comment by aweiksnar** [comment]
Awesome, thanks. Yeah in agreement on the create failure messaging

**Comment by mschwamb** [comment]
I still can't make collections. Tried in Chrome and Firefox. Should I move this to a backend issue. Reopening for now.

**Comment by camallen** [comment]
Deploys have been borked for a few days...it'll be out soon.

**Comment by mschwamb** [comment]
Thanks @camallen . I'll close and reopen if it's still happening in if a few day.
