### ISSUE TITLE
Unable to create a new subject set

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#191]
Hello,

I'm trying to create a new subject set in a project I've created at: http://demo.zooniverse.org/panoptes-front-end - and I'm having trouble.

* I can't seem to upload a manifest in `csv` or `tsv` format - dragging and dropping files doesn't work ("0 manifests" displayed) and nor does clicking and selecting the `csv` or `tsv` file. That said, I don't know what format is required for the manifest - so does Panoptes check this before adding the manifest file to the subject set? From [this](https://github.com/zooniverse/Panoptes-Front-End/blob/a3447200a38f366ff5f1f72fc1c96c6f09339b5d/app/pages/new-project/subjects.cjsx) I can see the metadata headers but adding these to the first row of the CSV file, i.e.

```
'filenames', 'timestamps', 'coord[0]', 'coord[1]', 'rotation', 'coords_type'
F03-W0098_1360731795-672575_k00000.png, 0, 0, 0, 0, 0
[...]
```
etc. doesn't seem to help. Do the timestamps etc. have to be a certain format too? I've used 0 placeholder values for now as these metadata values aren't needed for my project.

* The image files (.png) can be added by dragging and dropping or selecting via the file dialog, but then I can't upload them - presumably because the manifest is absent?

Many thanks, Tom

**Comment by arfon** [comment]
I'm also struggling with this. I'm selecting a CSV file as shown below:

![screen shot 2015-04-14 at 10 41 53 am](https://cloud.githubusercontent.com/assets/4483/7140772/ec0261c2-e292-11e4-846b-a0269ecd3714.png)

I get the following errors:

![screen shot 2015-04-14 at 10 39 47 am](https://cloud.githubusercontent.com/assets/4483/7140780/f65ec980-e292-11e4-8dbd-3b9a46632f9c.png)

/ cc @brian-c @chrislintott

**Comment by brian-c** [comment]
I _believe_ both these issues will be fixed in the workflow-editor branch. Try it here: http://demo.zooniverse.org/panoptes-front-end/workflow-editor/#/lab

**Comment by arfon** [comment]
Thanks @brian-c. This is slightly better but I'm now getting an error about the images not being present. (See my earlier post for the directory structure)

![screen shot 2015-04-14 at 11 06 08 am](https://cloud.githubusercontent.com/assets/4483/7141317/5ed0270e-e296-11e4-8616-1922c16698ad.png)

**Comment by arfon** [comment]
Ah, OK I figured it out. I had to manually select each image also?

**Comment by brian-c** [comment]
@arfon Are you dropping the manifest and the images (so, six files total) into the box? Any console errors?

**Comment by arfon** [comment]
No, I just dropped the manifest file (which I now understand was a mistake :smile:)

**Comment by twhyntie** [comment]
Thanks all. Unfortunately http://demo.zooniverse.org/panoptes-front-end/workflow-editor/#/lab isn't working for me - I'm unable to upload with drag-and-drop or the manual click-to-upload-via-the-dialog for me with the following CSV file (metadata fields improvised from @arfon's example):

```
filename, known_rogue
F03-W0098_1360731795-672575_k00000.png, yes
F03-W0098_1360733494-244841_k00000.png, no
F03-W0098_1360734483-625143_k00000.png, no
F03-W0098_1360742010-482154_k00000.png, yes
F03-W0098_1360742414-117229_k00000.png, yes
```
Tried in Firefox, Chrome and IE11 but the manifest just doesn't apppear. Is it that they're `png` images? The image files upload OK still. I've tried creating a fresh project too.

**Comment by twhyntie** [comment]
I've added my test subject set (`csv` file and `png` images) [here](http://pprc.qmul.ac.uk/~whyntie/subjectset.tar) if that helps - in case there's a line ending/encoding problem...

**Comment by brian-c** [comment]
@twhyntie Your files worked fine for me. Are you on Windows? I've had some trouble with Windows hiding the .csv file extension.

**Comment by twhyntie** [comment]
@brian-c Ah. Yes. I am on Windows 7. I've just tested with my Xubuntu 14.04 VM and it works, and I can save my subject set and assign it to a workflow (the editor for which, by the way, is looking _awesome_!)

However, when I test it [here](http://demo.zooniverse.org/panoptes-front-end/#/projects/twhyntie_lsc/Monopole+Quest+-+Timepix+Test+001) and [here](http://demo.zooniverse.org/panoptes-front-end/workflow-editor/#/projects/twhyntie_lsc/Timepix+test+002) I get the:

`Error: Cellect is unavailable`

error message... but I guess this is related to another issue.

Given that most schools will use Windows machines to access the front end, how much of a problem is this to solve?

**Comment by twhyntie** [comment]
_Update_: yup, the Cellect problem was the same as [#207](https://github.com/zooniverse/Panoptes-Front-End/issues/207). The workflow and subject set are now working on Linux and looking pretty sweet.
