### ISSUE TITLE
Page zoom broken for subject images in Chrome/Firefox

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#1917]
Browser page zoom should enlarge the page text and images, like this screenshot from Safari.
![panoptes-zoom-1](https://cloud.githubusercontent.com/assets/59547/11243156/5a50e970-8dfe-11e5-98c9-39d8c444fe70.jpg)

Zooming in on Chrome/Firefox, the page text enlarges but the subject image stays the same size
![panoptes-zoom-broken](https://cloud.githubusercontent.com/assets/59547/11243194/8e600a20-8dfe-11e5-940e-c3ca7881bf88.jpg)

**Comment by aliburchard** [comment]
This would be nice to fix -- and provide a free alternative to building a whole zoom tool for certain pfe projects.

**Comment by itsravenous** [comment]
I think this is down to the `max-height: 90vh` rule on `.classifier .subject`. This means that the original `img` tag - and thus the SVG element which uses its size to determine its own - won't zoom much when viewing "tall" subjects. Checking a project with "wide" images - e.g. Snapshot Supernova - you can zoom a fair way in before hitting the height constraint. I guess the `max-height` is there to ensure the entire image is always visible.

I can't tell from your screenshots quite whether the above is the problem in this case (can't see the bottom of the viewport)  -what dyou reckon?

**Comment by eatyourgreens** [comment]
Could be. Try comparing the page zoom with these two subjects.
Portrait: https://www.zooniverse.org/projects/eatyourgreens/diagnosis-london/classify/
Landscape: https://www.zooniverse.org/projects/tedcheese/whales-as-individuals/classify/

**Comment by itsravenous** [comment]
Yep, Whale flukes are happy to zoom, yellowed paper not so much. Disabling the max-height rule allows the Diagnosis London images to zoom.

**Comment by eatyourgreens** [comment]
Closed by #2199
