### ISSUE TITLE
Helpful button on Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1921]
Feel free to mark as do not fix and close but I found people were using the thumbsup as a like button rather than just a helpful button, and now it's a helpful button. Maybe this for the human behavior computation or the sociologists , but since Talk is more than just a help I'm not sure why it's now forcing the behavior that people identify what's 'helpful' rather than what could also be interesting? 

Maybe this doesn't matter since there is no sorting based on this yet. I just found it odd being there that there's now a helpful button given the design of Talk, and partly promotes Talk as just being a help board when it's way more than that. I think it takes away from emphasizing Talk as another tool for exploring the data.

**Comment by aweiksnar** [comment]
Yeah this was a big request from the experiments team. If you get additional resistance from volunteers definitely let us know and perhaps we can implement it as a #tag

**Comment by mschwamb** [comment]
Thanks @aweiksnar. 

I don't think there will be much resistance, but  I think it makes it look like Talk is a more help forum for new people coming to the site when it it's way more useful and powerful  than that. I'm not sure the button will be used since most of the conversations become about what's in images and opinions and how does one weight that as 'helpful'. 

The marking tool isn't working post on the Help boards could have a reply that would be 'helpful'. I don't think that Talk works the way a helpful assessment will be used in any significant frequency. The button has been pretty underused on Talk from what I've seen. Maybe in a few months if it's not used by more than a few percent of active users you can consider if it's worth  modifying it again?

**Comment by aweiksnar** [comment]
I'm certainly in agreement with you here. Definitely open to chat ideas for improving / changing this at some point. Maybe something similar to how slack implements emoji reactions would be better

**Comment by mschwamb** [comment]
Cool. I'll bring it up in a few months if I see it's not being used and I continue to have the same reaction against it that I have right now.
