### ISSUE TITLE
Moving the box to add images in the meda section of thep project builder to the top of page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1922]
I assembled a help with all my images over the past few days, and realized I had to keep scrolling every time I uploaded an image to upload the next once I had the help images for the first question or two of the decision tree in place. Putting the add box on the top in the project builder would make it a bit easier for the user I think. 

I'm referring to the 'Select Files' box. 

![screen shot 2015-11-19 at 12 59 46 pm](https://cloud.githubusercontent.com/assets/753325/11262720/b54bce3e-8ebd-11e5-8838-800fdbb4b5b3.png)

**Comment by aliburchard** [comment]
Yes! I run into this problem a lot while assembling help guidance.  @jwbmartin something to keep in mind while working up the redesign?

**Comment by mschwamb** [comment]
this was fixed in a PR already
