### ISSUE TITLE
subject upload - "Validation failed: display name has already been taken"

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#1923]
trying to add more subjects
"validation failed: display name has already been taken" appears next to the 'new subject set' button

I've tried on a second computer with the same result and, of course, different browsers

Nothing has changed at my end since I uploaded the last subject set

please help!

**Comment by camallen** [comment]
Sounds like you have duplicate subject set names in your project. Have you tried renaming it?

**Comment by AdrianEvans** [comment]
Thanks. Just double checked, they all have unique names - presumably it would have flagged that when I tried to create a subject the last time.

Could it be that there is a limit on the maximum number of subject sets? I currently have 15..

**Comment by camallen** [comment]
Nope re limits. also that error message is specific to creating a new subject set. Can you provide screen shots?

**Comment by AdrianEvans** [comment]
![image](https://cloud.githubusercontent.com/assets/10448680/11267579/059136c8-8ea4-11e5-9cb0-90bf03b52009.png)

**Comment by camallen** [comment]
any chance you can rename your "untitled subject set" to something else?

**Comment by AdrianEvans** [comment]
I'll try that - also just added you as a collaborator so feel free to check the problem out

**Comment by AdrianEvans** [comment]
OK - we're all laughing now. It seems that it wouldn't work because new subject sets are called untitled subject set and because I had one called that it wouldn't move forward.

So we're golden. 

In the face of this i'm just going to suggest that the default entry in the subject name should have some random data so this can never happen again. Either that or have text saying the subject set name must be changed.

cheers

**Comment by camallen** [comment]
can you open a new issue outlining (and linking) the above but requesting for a timestamp be appended (should be uniq)?
