### ISSUE TITLE
Unclear that the word icon is something you click on get to the Zooniverse blog and daily Zooniverse

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1925]
in case the feedback is useful, I noticed that there was now an Earth image on the top navigation bar. It wasn't at all obvious until I saw a post about it on Talk that it was something other than an image. When you mouseover nothing happens (at least on Mac Firefox). You have to click it to get the link for the Zooniverse blog and the Daily Zooniverse. I think many people will mistake it for what I did, especially if it doesn't have a mouseover effect that drops the menu

![screen shot 2015-11-19 at 11 12 35 pm](https://cloud.githubusercontent.com/assets/753325/11274316/2090e076-8f13-11e5-9de4-e4ab3c639459.png)

**Comment by mrniaboc** [comment]
I actually quite like the look of it, even if the context is perhaps missing. I guess it at least might intrigue people enough to click on it. I imagine some people may think it is for changing the language of the site?

**Comment by srallen** [comment]
Maybe an icon like this could be used instead?: http://fortawesome.github.io/Font-Awesome/icon/external-link/

**Comment by aweiksnar** [comment]
I've got a PR open to add some hover text titled "Other Links" over it

**Comment by mschwamb** [comment]
I'm finding that I pass over the little hover text without noticing it since the Earth doesn't light up when hovering like when I move my mouse over the text for any of the other navigation links.  If you're going to leave as this, is there anyway for it light up or have the menu drop down over hover like on Galaxy Zoo.. That would at least indicate it's something like the other navigation buttons.

**Comment by mschwamb** [comment]
There's a talk thread here with other [opinions](https://www.zooniverse.org/talk/17/18023/?scrollToLastComment=true&page=1). Also,  I'm not sure what external links for the Zooniverse would be if I wasn't involved in projects and know two blogs exists, so maybe Blogs would be better?  If y'all think this will work and people click it feel free to close.

**Comment by mschwamb** [comment]
not relevant  anymore with the new navigation bar
