### ISSUE TITLE
Request: subject manager

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#1929]
The project builder tells me how many subjects I have in the system. But I can only account for about 75% of them based on my current live projects. That means the other 25% are ghost subjects that I've likely uploaded and then deleted. But I have no idea where they are now. Could we get some sort of management tool in the project builder to help us know how our subjects are distributed? It would also be nice to have a "purge" button to permanently delete subjects that we don't want and aren't tied to any live project.

Related: Do subjects in projects that I am a collaborator on count towards my limit? 
And: Is it the person who uploads the subjects that gets charged with them or is it the project owner?

**Comment by mschwamb** [comment]
@mkosmala  it's based on your user account. total number you've uploaded (not what your collaborators have uploaded) and that tally includes subjects you've deleted.  only the person doing the uploading is charged is my understanding.

**Comment by camallen** [comment]
Linked to https://github.com/zooniverse/Panoptes/issues/1193 & https://github.com/zooniverse/Panoptes/issues/1120

> Related: Do subjects in projects that I am a collaborator on count towards my limit?

Yes, if you upload them, no if you don't.

> And: Is it the person who uploads the subjects that gets charged with them or is it the project owner?

The uploader.

**Comment by aliburchard** [comment]
While we don't want to try and tackle an entire data management system for researchers, I think it's clear that we need *some* more support for subject upload and management, including duplication checking (right now this is really really difficult for researchers to do based on the failure rates of uploads and manually downloading the subject exports) and hard deletes of "test" subject sets. Flagging this issue for conversation with @brian-c and @chrislintott this week.

**Comment by mkosmala** [comment]
Agreed with having at least a minimal manager. I've been asked repeatedly for my (bad) code that can upload subjects in large batches of thousands at a time. (Bad because it has exactly zero fault-tolerance. I keep hoping someone will code in some error-checking...) 

But yes, we need:

1. a way to upload several thousand images at a time
2. a duplicates-checker would be awesome, but might be cpu-expensive on your side? (maybe not? compare hashes?)
3. a summarizer to let us know how many subjects are associated with each subject set AND how many subjects are uploaded but not associated with any subject set (bonus points: how many subjects are associated with each workflow and, of those, how many have been retired)

**Comment by aliburchard** [comment]
@mkosmala this is really helpful. So, I think we are trying to compile a comprehensive list of 1) issues and 2) functionality needs surrounding subject upload and management. If you or @mschwamb @vrooje @khufkens and other project builders would be willing to weigh in on this issue, that would help us start brainstorming.

**Comment by mschwamb** [comment]
@aliburchard do you want us weighing in on both 1 and 2 or just specifically on this ticket?

**Comment by aliburchard** [comment]
@mschwamb I'd like to collect both on this issue -- I think that the list of desired features/functionality will grow out of some of the problems we're having with the current system. Instead of just making quick fixes to some of the current quirks, I want to figure out what a proper redesign is.

**Comment by mkosmala** [comment]
Issues:

1. Too hard to upload many files. Need to be able to upload 1,000's at a time, not necessarily all in one folder.
2. Too hard to upload very few files (it should be possible to upload files without needing a manifest. Whenever I demo Panoptes, at least 50% of the time used is spent trying to upload.)
3. I have ~10K orphan subjects. (I think.) I would like to be able to hard-delete them, because no one needs them. Others might want to assign orphaned subjects to new subject sets.

Functionality:

1. An flexible uploader. This may be web-browser based. But it could also be a downloadable app.
2. Upload without manifest. For demos, it would be so much nicer if I could drag and drop three images onto the site, without the need for a manifest. The Project Builder should be able to auto-generate a simple manifest with each file's filename as its only metadata.
3. Duplicates checker. I haven't needed this, but it's clear it would be useful to others.
4. Summarizer of some sort that would let me quickly know the statuses of my subject sets and workflows, without having to download a file and write a summarizing script myself.
5. A way to manage orphan subjects. (Orphan=not associated with a subject set.) Right now, these are lost for purposes of assigning them to subject sets or hard-deleting them. They are "soft" deleted, but taking up space that you guys pay for and taking up room in project makers' quotas. I can imaging a use-case where someone wants to assign a subject to another subject set. Right now they have to "soft" delete the subject and then re-upload it. If I were splitting a large subject set into two smaller ones, that would be very inefficient.

**Comment by mschwamb** [comment]
@aliburchard I'll send you an email.

**Comment by camallen** [comment]
@mkosmala just letting you know that point 2 already exists.

**Comment by mkosmala** [comment]
@camallen Cool! Is this new? I demoed in early/mid December, and had to create a manifest then...

**Comment by marten** [comment]
As far as I know you could always drag/drop a bunch of images and just upload those straight to a subject set?

**Comment by vrooje** [comment]
I think it wasn't always supported, but it was implemented close to launch? @brian-c could clarify.

- Duplicate checking would be great, even if it was just based on checking filenames in the subject metadata. A one-off duplicate check on existing subjects would be good, as would a check vs the manifest as part of the upload process. "Warning! A subject with filenames ("x.jpg","y.jpg") already exists. Do you really want to create the new subject? [Yes] [No] [Apply to All Duplicates]" etc.
- I would also like to be able to drop in a manifest and have PFE check it against an existing subject set (or sets) and tell me which subjects are missing.
- I'd love for PFE to break up my huge upload queue into batches for me so I can drop 10K subjects in and walk away without worrying I'll seize the server.
- I understand our reasons for not wanting to delete subjects if they've had any classifications or are associated with any other projects, but I am not clear whether it would be okay from a Zooniverse data management standpoint to delete the orphan subjects @mkosmala has described.
- A subject dashboard that sits at a level above the project lab pages would be good. I'd like to be able to see thumbnails, associated projects, classification counts by project, retirement status etc, and sort+filter by various things. ("Show me all retired subjects", etc.)
- I'd like to be able to update subject metadata and especially toggle the privacy setting of individual columns, but this is a lower priority.

**Comment by khufkens** [comment]
Uploading 1000+ subjects is still cumbersome indeed, but I use a hack by @mkosmala. The orphan subject issue is something that bothers me conceptually, but should be a larger issue on the server side than the user end (Although I don't like the clutter, it's Zooniverse disk space - which costs money).

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
