### ISSUE TITLE
being able to scale images in markdown

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1930]
I'm battling trying to get a figure I've made down to the right size so that it fits on the research page. I have to upload , add it, preview it, then resize, and then repeat. It would be nice if there was the ability in the markdown to scale the image so I can adjust it that way rather than physically making the image smaller.  I thought this existed for Talk, but I can't find out in traditional markdown how to do this so I presume it's in the Zooniverse flavor of the markdown. 

if there's isn't someone going to make a markdown tutorial of the added features in zooniverse markdown any time soon,  would it help if I made that and did a pull request? (see #1517)

**Comment by camallen** [comment]
@mschwamb in talk it's not markdown but a different image tag src location, e.g. https://thumbnails.zooniverse.org/100x999/panoptes-uploads.zooniverse.org/production/subject_location/73c03491-09f0-4857-800d-7d6042b0a146.png. Note: these rescaling URL's will only work on images uploaded via the project builder, externally hosted images won't work (for lots of reasons).

**Comment by mschwamb** [comment]
Thanks @camallen. I wasn't referring to that though. I was thinking and 
maybe I just imagined this, that there was some Talk discussion I saw 
where it was mentioned this has been added to the markdown for 
externally hosted images. I could be recalling this totally incorrectly.

I'm asking for rescaling of images uploaded in the media section of the 
project builder to be able to scale through the image insertion command. 
I spent more than an hour uploading and then having to manually resize 
the image and then upload again to get the right size that would fit 
within the browser window.

**Comment by camallen** [comment]
cool. Just for reference then, if it's uploaded through the project builder you can use thumbnails server URL to resize the image on the fly, no need to upload again and again. Just upload once, get the original image src and feed into the thumbnails service to get the desired scaling right. Then insert the thumbs URL into the markdown (if you can).

**Comment by mschwamb** [comment]
Ah cool. that's exactly what I was looking for.  thanks! helpful in for the future. Maybe worth sticking in the research page help or on the media page. I could try and draft something and do a pull request later this week if you think that's a good idea @camallen

**Comment by camallen** [comment]
yeah not sure where this is best doc'd but any docs are welcome.

**Comment by DarrenMcRoy** [comment]
Does the same markdown that lets us rescale images in Talk let you rescale images in the project builder?

**Comment by mschwamb** [comment]
It's the same markdown I believe. Is there a zooniverse markdown  format in talk that rescales an image? @DarrenMcRoy maybe I saw a post by you mentioning this?

**Comment by DarrenMcRoy** [comment]
[![one](IMGURLHERE =200x)](IMGURLHERE)

Change the "200" to suit whatever size you need... I think that specifically adjusts the height.

You can also adjust both height and width to skew an image, but I forget exactly how (and you'd rarely want to). @parrish -- remind me?

**Comment by parrish** [comment]
It's `=<width>x<height>`

E.g.

- `=200x300` is 200px width, 300px height
- `=200x` is 200px width, auto height
- `=x300` is 300px height, auto width

**Comment by DarrenMcRoy** [comment]
Thanks!! *saves this time*

**Comment by mschwamb** [comment]
Thanks @DarrenMcRoy and @parrish I presume it's using the thumbnail service @camallen mentioned. It would be really helpful if that and the ability to open a link in a new tab were in the project builder markdown help. Is someone writing the help or if I have time should I come up with something  and make the pull request?

**Comment by DarrenMcRoy** [comment]
Not only am I writing it, Meg, I was told I should coordinate with you on it. Shoot me an email! :-)

**Comment by mschwamb** [comment]
answered so closing
