### ISSUE TITLE
Preview doesn't work properly - not showing the full length of the text when it's longer than the visible text field

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1932]
When the text is longer than the height of the text field, the preview doesn't show the text as it will display after submitting but only its part which is visible during typing - the text field dimensions remains the same as during typing - so you have to scroll the text inside the box to see it all.

I think this was working before.. Not sure when it broke.

**Comment by DarrenMcRoy** [comment]
+1 -- the preview should show the entire height of the post without scrolling (or without making the text box super large before you click "preview").
