### ISSUE TITLE
Don't let users pick a workflow if it does not have an associated subject set

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#1933]
It might be useful if the front end checks if a workflow has an associated subject set before it is added to the list of choices volunteers can pick from when "Volunteers can choose which workflow they work on" is checked.  That way users will only be able to pick from workflows that would not instantly give an error message if the project builder forgot to link a subject set.

Also related to [this talk post](https://www.zooniverse.org/talk/18/18584/?scrollToLastComment=true&page=1) as a way to "hide" a workflow.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
