### ISSUE TITLE
Add "x" button to project builder tutorial

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1935]
@brian-c -- currently the only way to exit the tutorial is to click through the whole thing. There are many circumstances in which you might just want to X out of it... Can we add the X in the top right that appears in all other slide tutorials?

**Comment by mschwamb** [comment]
that or click on the screen someone else.I think having the x and keeping the tutorial open even if you click elsewhere on the screen like most of the Ouroboros project tutorials would be great

**Comment by aliburchard** [comment]
+1! This has been an issue for me as well.

**Comment by camallen** [comment]
Clicking on the screen elsewhere already works for me. Pretty sure this is consistent with modals on the web.

**Comment by mschwamb** [comment]
We want people to actually go through the tutorial (yes you can hit the x), but hitting anywhere accidentally on the screen I think makes it very easy to skip it, so I would like to see what's implemented on most projects which is the box doesn't go away until you complete it or hit the x. 

But either way all  on that point previous projects like Chimp and See and the custom panoptes project Wildcam Gorongosa have an x, so why not be consistent with current live projects?

**Comment by eatyourgreens** [comment]
The tutorial modal isn't keyboard accessible at the moment either, so you can't close it with the `esc` key. I'll open a separate issue about the keyboard problems.

**Comment by brian-c** [comment]
Changing behavior to that described in #1967.

**Comment by mschwamb** [comment]
Thanks @brian-c
