### ISSUE TITLE
Url with tilde (~) not displaying properly 

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#1937]
Chrome Version 46.0.2490.86 (64-bit)

Example: the value of `Luna URL` is displayed with superscript (see image)

![screen shot 2015-11-24 at 11 42 08](https://cloud.githubusercontent.com/assets/8989606/11366302/4eb2cf3e-92a4-11e5-9bfd-bbe71d93834a.png)

It should be displayed like this instead:

`http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~325312~126435:To-Avery-Copley-and-Robert-Key-`

Possible cause: url is not encoded properly before been displayed.

**Comment by eatyourgreens** [comment]
I'm pretty sure that this is happening because the URL is being parsed as Markdown. The metadata box should probably skip the Markdown parser on URLs and filenames.

**Comment by simoneduca** [comment]
That makes sense (see below).

![screen shot 2015-11-30 at 16 54 56](https://cloud.githubusercontent.com/assets/8989606/11478151/462e9d82-9783-11e5-84ad-da854310d744.png)

**Comment by brian-c** [comment]
Metadata values are parsed mainly to auto-link URLs. This is probably a problem in markdown-it's URL detection.

**Comment by aweiksnar** [comment]
Yeah it looks like the the [markdown-it-sub](https://github.com/markdown-it/markdown-it-sub) package is parsing those
