### ISSUE TITLE
Project builder crashing in filter task creation

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1940]
@brian-c the colorado corridors team reports that the project builder is crashing when they are uploading csv files. THey are running Windows 8, trying both Chrome and Firefox. I can't reproduce on Mac. I've managed to upload their same csvs just fine.

![screen shot 2015-11-25 at 14 56 36](https://cloud.githubusercontent.com/assets/6217406/11400356/d0597f02-9384-11e5-8afd-d88ec7f7e114.png)

**Comment by aliburchard** [comment]
We're getting reports that this is happening from other project builders too. It boils down to the project builder uploading a csv with *some* wrong data, but the project builder crashes, and it crashes pretty completely. Sometimes you click on a workflow to edit and it just pulls up a blank screen. Other times, it acts like your csvs uploaded fine, but the classification interface gives you the spinning gyroscope of doom. There are no error reports, no indication of what might be wrong.

**Comment by srallen** [comment]
Survey task has gotten some TLC since this.
