### ISSUE TITLE
Issues with Snapshot Serengeti landing page in Panoptes

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#1941]
i.e. https://www.zooniverse.org/projects/zooniverse/snapshot-serengeti
- The statistics show zeros. We should either hide this section or make it show correct stats for ouroboros (or link to somewhere else that does)
- The "About" section is blank. We should fill it in or remove it.
- The "Talk" section goes to a blank Panoptes Serengeti talk board with no boards. We should either hide this link, or better still make it go to http://talk.snapshotserengeti.org/

Also after fixing this we should check if other Ouroboros projects linked from PFE Zoo homepage also have similar issues, and fix those too.

**Comment by aliburchard** [comment]
For the "about" page I'd vote to either remove it or redirect to http://www.snapshotserengeti.org/#/about

**Comment by eatyourgreens** [comment]
I'm pretty sure this landing page isn't linked from anywhere. If it is, that would be a bug.

**Comment by alexbfree** [comment]
Sorry I'd assumed that the project homepage sent you here. I see it does not. 

In that case, this is still a bug, just a *much* lower priority one. If this start page ever gets used, these issues would need to be addressed.

I wonder why this page even exists?

**Comment by alexbfree** [comment]
These seem to exist for all Ouroboros projects
e.g. https://www.zooniverse.org/projects/zooniverse/galaxy-zoo
https://www.zooniverse.org/projects/zooniverse/planet-four
https://www.zooniverse.org/projects/zooniverse/old-weather
etc

**Comment by mschwamb** [comment]
If this is helpful, I vaguely  remember at launch the project cards on the  Zooniverse home project list were linking to these for non-paoptes projects and that it was addressed i think a week or two later.

**Comment by srallen** [comment]
I'm pretty sure these only exist so that they have a project card on the projects page, but since a redirect is in place, then users won't find these. No one should be linked to or directed to these.
