### ISSUE TITLE
Moving the slide tutorial box upward so it's not partially off the screen for smaller displays 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1942]
@brian-c - the slide tutorial is really great. It was turned on for a project I'm currently building. The one issue we're having with it, is that the box appears on the screen too low at least for a 13 inch laptop screen. I

If it's your first time seeing it the next button does pop up above the bottom (since the site scrolls automatically) but the rest of the box is still blocked

![screen shot 2015-11-26 at 7 08 26 am](https://cloud.githubusercontent.com/assets/753325/11411611/92854cb4-940c-11e5-806c-d3ba0c6ff906.png)

If it's not your first time seeing the tutorial and you hit the tutorial button, then your screen doesn't move and the next button is cutoff

![screen shot 2015-11-25 at 9 04 59 am](https://cloud.githubusercontent.com/assets/753325/11411565/1ec98506-940c-11e5-86df-3a678c6ece36.png)

I get the same behavior in OSX chrome and firefox 

Is there anyway you could fix that, by making the center of the box be in the center or the top of the box start at the top of the screen? cc @chrislintott

**Comment by marten** [comment]
This is also an issue for mobile devices, @brian-c was going to look at it so that we can have this fixed for Stargazing Live.

**Comment by brian-c** [comment]
PR open at zooniverse-ui/modal-form#14 should take care of this.

**Comment by mschwamb** [comment]
Since the PR mentioned is merged, and the issue is sorted for me. I'm closing.
