### ISSUE TITLE
Feedback on the slide tutorial button in the main classification interface

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1943]
I thought I would pass this forward. We have the slide tutorial active as an experimental feature in the project builder for the Comet Hunters project I'm building. I've demoed the site with it on to the other members of the Comet Hunter steam. 

They had a real hard time finding how to restart the tutorial. They kept passing over the graduate hat but not long enough to see the mouse over 'tutorial'. These are people who don't frequent Zoonvierse projects. I didn't find the icon very intuitive at first either, but since it was the only thing different I figured out quickly that was the tutorial button. 

Since there is space next to the Help button on the right, a more obvious choice might be a button with the text 'Tutorial' to make it explicit  like many of the custom projects have.

cc @brian-c @chrislintott 

![screen shot 2015-11-26 at 7 52 38 am](https://cloud.githubusercontent.com/assets/753325/11412121/8ac706b4-9413-11e5-86fc-72bf04771d35.png)

**Comment by mschwamb** [comment]
@brian-c Would you be able and willing if at all possible to change the hat to a tutorial button with text next to the help button? I have done some internal beta testing  at my institute and got the same response as above  that when the person accidentally hit and got rid of the tutorial, they couldn't figure out how to get it back from the current setup. 

We were hoping to launch the project before the 20th. I applied for beta test for the project. If you don't have time or there are other development priorities, I fully understand.

**Comment by brian-c** [comment]
I'm opposed to a "Tutorial"-labelled button at the same level as Back and Next. That line has become a dumping ground for classification-level actions, but its primary role should be navigating the workflow. Cc: @jwbmartin, something to think about in your redesign.

I've got a PR open that changes the icon to the more familiar question mark in a circle and moves it over to the right of the "Next" button. Visually breaking up the aligned right side should make it easier to find.

**Comment by mschwamb** [comment]
I agree with not having additional text buttons on the line next to the 'next/done' 'back buttons'.  I was thinking more to the left or right of the help button which is one level above. 

Why not put it next to the help button though? I watched people circle there and then hit help and realize that didn't start the tutorial. 

Happy to test out and walk into random people's office tomorrow and see how they do with this change. Thanks for making any chance to help address this.

**Comment by mschwamb** [comment]
@brian-c People still aren't  identifying the question button as the one that restarts the tutorial. I gotten two people in the beta test form comments and one on Talk saying either they couldn't figure out how to get back to the tutorial or asking for a more visible button. I've confirmed these were all posted well after the change you made went live.

 I also went around to a few offices here at my institute as well. From what I can see they're not really looking at the next/done back button level because it's so small and that their eye is going towards the help button. I see they mouse hover over there. When I point out the icon, they tell me they didn't see it. 

What about either:
- making the icon a bit bigger and moving the question mark icon button up to the right or left of the help button on the line above 
- or having a button with the text 'tutorial' next to the help button?

**Comment by mschwamb** [comment]
hey @brian-c we're going to launch Weds with the tutorial functionality as is, but the beta test feedback did show that people were still having trouble figuring out where the tutorial restart button was. Basically the help button distracts and the never see the question mark or it took them a long time to find it when I walked into people's offices. If you're willing to make changes based on this, that would be great. I think people really are focusing on the help button line since the next and done buttons are greyed out so they miss the question mark icon.

**Comment by aliburchard** [comment]
I agree that putting the tutorial button next to the "Need some help" button and labeling it very obviously as a tutorial would be much more intuitive. Where it is now is very hard to discern.  And I find the choice between "Need some help?" and a small "?" confusing. On Snapshot, Kelp, and C&S (just to name a few) we type out the word "Tutorial".

**Comment by mschwamb** [comment]
@brian-c a quick note to say the current solution is working fine if you want to close this.
