### ISSUE TITLE
make point markers smaller

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1944]
The point tool is really big, making it difficult to place two points very close to each other. A quick and dirty solution would be to reduce the size of marker. That might also increase the precision of the tool - right now, the crosshairs are so big that it's difficult to place the marker very precisely - you aren't quite sure which pixel is in the middle. 

This is a bit of an issue for a recently built project trying to count wildebeest from aerial photos, but I think it's cropped up previously as well. 
![Uploading Screen Shot 2015-11-27 at 16.07.07.png…]()

@brian-c it seems like it should be a super easy change in the codebase? A more elegant long-term solution suggested by @eatyourgreens is to add a menu where project builders can choose the marker size (much like they choose colour).

**Comment by srallen** [comment]
A small point tool option now exists.
