### ISSUE TITLE
top menu should never fade if new notifications exist

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1946]
If I go directly to a project rather than Zoo Home, the topnav Zooniverse menubar loads as partially faded. I get that, because there's also a project-specific menu, but it makes it very hard to see when I have new messages.

![screen shot 2015-11-29 at 15 01 57](https://cloud.githubusercontent.com/assets/2357126/11460877/9f56654a-96aa-11e5-89a8-5164f48c9850.jpg)

Is it possible to force the message icon to stay "lit" when there are new notifications?

**Comment by itsravenous** [comment]
We could move the logic for fetching notifications from the talk page component to a generic lib, and call that from the main header component. This would also allow us to put an unread count "badge" on the "Notifications" nav item.

**Comment by srallen** [comment]
Header design has been redone since this was opened.
