### ISSUE TITLE
Having a project team page 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1947]
Related to #568

All that describes the research team is the  sidebar. All the custom projects have team pages. Why can't there be a markdown page for the team where the researchers if they choose can have more details about themselves and their actual roles on the projects. I imagine this would also be helpful for review for Zooniverse status since it would provide information on the research team whereas all you have now are usernames.

If it's about space why not have research tab become about and be a dropdown menu with links to the research page and the team page?

**Comment by aliburchard** [comment]
I am all for adding an optional "team" page where we add profile images/information. I think it lends a lot to the credibility of the project, and doesn't really fit on the "research" page. We have this page on custom zooniverse projects for this very reason -- don't we want PFE projects to mimic all the good things from custom Zooniverse projects?

**Comment by DarrenMcRoy** [comment]
Absolutely.

In addition, I think that the sidebar should be curateable. Just because you have someone added as a collaborator doesn't necessarily mean that you want them showing up to the public.

**Comment by mschwamb** [comment]
@DarrenMcRoy  I haven't yet encountered a case beyond building a project when an issue comes up then needs a Zooniverse development person to take a look at the project, but the person can be unadded fairly quickly. I don't think that feature needs to be added soon, but having a team page would be nice to have as a markdown page and likely doing review would be easier since you can learn more about the team and verify the info.

**Comment by aliburchard** [comment]
+1 to Darren's suggestion. I'm a "collaborator" on a dozen or more projects just to help with project builder navigation, but don't think that always means I should appear on the project "team" sidebar.

**Comment by mschwamb** [comment]
I thought it  worth mentioning it was a comment (albeit from one person) as a recommendation in the beta test for a project I'm working on. They said it would be nice to know more about the background of the science team.

**Comment by chrislintott** [comment]
I agree we should add this.

**Comment by mschwamb** [comment]
Addressed by https://github.com/zooniverse/Panoptes-Front-End/pull/258
