### ISSUE TITLE
Image size and shape look fine on Research page in firefox but then overflows the boundary line in Chrome and Safari depending on size of window

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1948]
I'm finding that an image that I added that looks fine in Firefox overflows the line separating the research team part from the research page text in Chrome and Safari depending on the size of the window. Not sure if there's a way for the image to resize based on the screen. When you make a window smaller in firefox is has the scrollbars for you to use. Chrome and Safari I think try to resize everything

in firefox 

![screen shot 2015-11-30 at 3 10 26 pm](https://cloud.githubusercontent.com/assets/753325/11465552/b260511c-9774-11e5-8359-502558e09909.png)

in a smaller window in chrome
<img width="849" alt="screenshot" src="https://cloud.githubusercontent.com/assets/753325/11465520/752b4cac-9774-11e5-9d7d-f2c8c2bc45c5.png">

**Comment by itsravenous** [comment]
Implicit `min-width` strikes again! For what it's worth, I see the issue in Firefox as well as Chrome. Quick fix would be to add `min-width: 0` to `.column` in `layout.styl` - I'll test and see if that causes issues elsewhere though.
