### ISSUE TITLE
Slide tutorial keyboard issues

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#1953]
Couple of small issues with the slide tutorial:
- you can tab/shift-tab and shift focus back to the underlying web page. Modals should capture focus until they are closed.
- if you focus the 'Continue' button and hit space/enter, the slide changes but focus doesn't jump to the button on the visible slide.
- when the modal closes, focus doesn't return to the previously active element (eg. the tutorial button) and seems to be lost.
- maybe focus the continue button when the box first opens?
- you can tab to the hidden 'Let's Go' button, at which point the display goes weird and unreadable.
  ![panoptes-slideshow](https://cloud.githubusercontent.com/assets/59547/11471472/be9c3066-975d-11e5-9c6b-4853bd72a39c.jpg)

**Comment by camallen** [comment]
linking in #2857

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.

**Comment by eatyourgreens** [comment]
This still needs looking at.

**Comment by eatyourgreens** [comment]
Closing this as it was mostly caused by react-swipe, which we've removed.
