### ISSUE TITLE
Add out of data message for Panoptes projects

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1956]
With Galaxy Zoo: Bar Lengths now out of data, the Classify page is delivering:

"Error: No workflows for project 3"

![screen shot 2015-11-30 at 3 02 09 pm](https://cloud.githubusercontent.com/assets/8987864/11486714/642bed42-9780-11e5-9ee7-6fb8637db75a.png)

Can we change this message? I'm happy to write text, but does it need to cover all events where there might be no workflows? Or can I write a message specific to being out of data?

(Also, related: Can we put GZ:BL to the back of the Projects page?)

**Comment by mschwamb** [comment]
@DarrenMcRoy wrong image....?

also might be better to have the discussion in #1050?

**Comment by brian-c** [comment]
Projects should never run out of data, they should be getting back subjects flagged 'retired'.

I think "no workflows" here is a different error though. Are we sure it's because all subjects are retired? I'd expect "no subjects" in that case.

**Comment by DarrenMcRoy** [comment]
Had the wrong image initially; fixed it.

Meg said that Galaxy Zoo: Bar Lengths was finished...

**Comment by camallen** [comment]
Its because the data has finished and deactivated the workflow. Pfe only looks for active workflows. We need to signal a completed flag instead of inactive (api issue exists), so testing workflows can remain hidden. 

Brian, any chance we can hack a ui message for launch approved projects with no active workflows till we get this sorted at the api?

**Comment by brian-c** [comment]
Couldn't we just reactivate the workflow?

**Comment by DarrenMcRoy** [comment]
Then users would be seeing an endless stream of images flagged "retired," and no messaging that the project has been completed, right? I can only imagine the bug reports...

**Comment by camallen** [comment]
@brian-c we have, there are some slightly out of sync counters which is causing any the workflow to deactivate on next retire event. 

@DarrenMcRoy yes, that is how the new system will work. Agree we need some more messaging around signaling a project is out of data so you won't have to answer a million emails.

**Comment by DarrenMcRoy** [comment]
> Agree we need some more messaging around signaling a project is out of data

So the issue title still applies, then. :-)

**Comment by mschwamb** [comment]
um I have nothing to do with Galaxy Zoo: Bars. So not sure where you're getting @DarrenMcRoy that I said the project is finished. Maybe you mean someone else?

**Comment by camallen** [comment]
@DarrenMcRoy see the api issue, the front end will require some signal that the data is finished. https://github.com/zooniverse/Panoptes/issues/1403

**Comment by DarrenMcRoy** [comment]
-- My bad! It was @vrooje, not you, Meg. Sorry!!

**Comment by camallen** [comment]
I'm pretty sure we've handled the root of this issue. Feel free to re-open if not.
