### ISSUE TITLE
When you hit play, should the animation end on your first image?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1957]
So if you hit play and let the animation run if you have multiple images associated with the subject when the animation ends it stops on the last image.

I think it should end on the first. That would help people who like me who are using the play button for showing an inverted color image of the image we're asking people to review. I imagine that people using it to look for motion won't care since it's the differences between the images that the volunteers are assessing.

**Comment by aliburchard** [comment]
I think the current behavior is that it ends on whichever image it started on. I've just tried this with wildebeest watch. I would be fine with it always ending on the first image though.

**Comment by mschwamb** [comment]
looks like you can now specify the number of plays of the flip book so that likely sorts this. - closing
