### ISSUE TITLE
Add customizable message box for PFE projects

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1958]
A feature that has been tossed around for a while, recently brought up again by @chrislintott -- we should have some sort of open text box, ideally somewhere on *both the home landing page and in the classification interface*, that allows for research teams to deliver an announcement or a message.

Sort of like a static intervention that appears consistently (maybe is hideable by the user?) that the project owner could change/update within the Project Builder.

This could be used for everything from announcing challenges to displaying paused/completed messages to inviting people to search for and tag a particularly important object... the potential uses are legion.

Thoughts?

**Comment by brian-c** [comment]
Closed by #2308
