### ISSUE TITLE
completed banner results link broken

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#1961]
Linked to #1959, the results link is relative from the hosting page and leads to 404's. E.g. https://www.zooniverse.org/projects/vrooje/galaxy-zoo-bar-lengths/classify/results from the link on the classify page.

**Comment by brian-c** [comment]
Guhhh! Anybody (@zooniverse/developers) know why trailing slashes are set up as optional instead of redirecting to non-slashed routes like they used to? Any risk in me setting that back to how it was?

**Comment by parrish** [comment]
I just followed convention.  Pretty sure that was started by Ed or @aweiksnar.  Maybe something to do with the #/ changes?

**Comment by DarrenMcRoy** [comment]
It looks like this banner has now been completely pulled from the site, so we're back to no indication of retired data...

**Comment by vrooje** [comment]
I wouldn't be bothered if everyone read Talk so knew GZ:Bar Lengths was
done, but we are still collecting classifications at the rate of hundreds a
day. It's good the "retired" ribbon is up, but I'm a bit concerned
newer people don't know what that means.

**Comment by brian-c** [comment]
The original implementation had major issues. I will get back on this today.

**Comment by mschwamb** [comment]
I agree with @vrooje that I don't think people really understand what 'retired' or 'already seen' banners really mean. A more direct message would be better. 

@vrooje Would it also help to remove Bars from the front page projects and sub in one of other new/relaunched projects?

**Comment by DarrenMcRoy** [comment]
I'd definitely like it removed from the front landing page, and also moved way further back on the list of projects. The Zoominar today will also be in part about the projects page, I think, so hopefully we can also discuss putting "paused/retired project" flags on the project cards!

**Comment by camallen** [comment]
removed from the landing page, done.

**Comment by vrooje** [comment]
Thanks for the removal - I also agree it would be interesting to highlight
projects that have succeeded in collecting all their classifications -
though maybe this should be a separate section of zoohome rather than
keeping the icons active with a banner? As we complete more projects *and*
have more active projects at any given time, putting everything together
is going to become untenable.

**Comment by srallen** [comment]
Original issue is fixed. Discussion about retired or already seen banners on subject image should be opened in a new issue.
