### ISSUE TITLE
bcc-ing individual core team and Zooniverse director email addresses from the beta test email sent to project teams/making a listserv for that so project owners don't have emails for everyone to email to that over team@zooniverse.org 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1964]
In my application for project project review, I got a confirmation email. It  has Chris L, Laura T, Grant, Ali, and Darren's emails in it as well as an email to the team. Since you ask on the policy page to email team@zooniverse.org  you might want to BCC those additional emails or set up a listserv rather than giving those emails out.

**Comment by camallen** [comment]
@mrniaboc this seems like a good idea, perhaps a review@ alias that we can use?

**Comment by mschwamb** [comment]
I think that would be a good idea and also direct people what email to contact if there are any further inquiries. There was no mention in the email of who I should contact if I needed to discuss things further.

**Comment by mschwamb** [comment]
I think this would be a good idea to have an email alias especially since you don't provide emails on the Zooniverse team page and you an alias as the contact email for other questions. I think review@ would be good, because then on the Contact Page there could be a note about where to email that if an owner has specific questions about their project which is review.  Like for this situation: https://www.zooniverse.org/talk/18/139104?comment=242027

**Comment by camallen** [comment]
+1 @mrniaboc

**Comment by mschwamb** [comment]
@chrislintott do you have any thoughts on a review@ email alias?
