### ISSUE TITLE
Moderator banners not showing up in Talk

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#1968]
I've tried to add user @bootneckbs as a mod on AnnoTate several times. He shows up as a mod when I look at the collaborators tab, but there's no label for him in the project itself when you look on AnnoTate Talk. One for @aweiksnar I think.

**Comment by camallen** [comment]
Looks like talk admin roles weren't setup right on project create (perhaps not via the api). I've fixed this and re-applied the mod role for bootneckbs. @VVH can you please verify they have the right role?

**Comment by VVH** [comment]
This is all good, thanks @camallen
