### ISSUE TITLE
Figure out URLs

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#197]
- No spaces!
- No question marks.
- Just IDs?
- Who cares?

**Comment by vrooje** [comment]
I think a URL that's decodable by humans and gives contextual information is helpful in some situations, so I'd prefer that a name be used (stripped of question marks, &s, etc) instead of an ID.

**Comment by edpaget** [comment]
I agree with @vrooje. If there's any way to make the urls be understandable by humans it'd be better than not, but if it ends up being too difficult I don't think it's the biggest deal.

**Comment by astopy** [comment]
Isn't it fairly standard to just slugify the page title (appending/incrementing a number at the end in the case of duplicates)?

**Comment by aliburchard** [comment]
I second the suggestion of letting people name a project appropriately (perhaps including a question mark), and then stripping the spaces/question marks/special characters for the url, so that the url that they share has a tangible connection to the project. Maybe this only matters for full on Zooniverse supported projects?

**Comment by vrooje** [comment]
It definitely matters for publicised projects, but I'm thinking
particularly of the private or beta projects where word might spread within
the networks of the project owners. For Facebook etc it doesn't matter, but
if they're emailing people or even tweeting it's just nice to have a
readable URL. Makes it seem more legitimate. Like a blog:
http://blog.snapshotserengeti.org/2012/12/14/we-need-an-i-dont-know-button
is informative so you know what you're clicking on before you get there,
unlike whatever the id-based permalink for that post is.

**Comment by aweiksnar** [comment]
For non-project pages, I'd be for loosely following rails' style (resource/id) and then changing it up later as needed

**Comment by brian-c** [comment]
@edpaget Want go ahead and add a filterable `slug` field to projects and users? Do you know how that'll get on with non-Latin display names?

**Comment by mschwamb** [comment]
Is the username that owns the project going to be in the permanent url or is that a temporary thing until the project goes through the Zooniverse approval process?

**Comment by aliburchard** [comment]
@edpaget @brian-c can we slugify the urls for first release? I think a lot of projects will want multi-word names (case in point - almost if not all of our zooniverse projects have 2 word names).
