### ISSUE TITLE
Same post shows up twice under subject page mentions if you made an edit to it?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#1970]
I noticed that this subject page has the same comment twice. It has different time stamps but on the Help board there is only one version of it. is it possible when you updating a comment it listed twice?

![screen shot 2015-12-03 at 5 16 29 am](https://cloud.githubusercontent.com/assets/753325/11564256/385bf866-9a13-11e5-9320-8b46c6b1bf88.png)

https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/subjects/1070870

**Comment by trouille** [comment]
I haven't been able to recreate this error. @mschwamb Have you seen this happen again? Thanks!

**Comment by mschwamb** [comment]
Not lately, and I couldn't trigger it. So I'll close the ticket and reopen if it occurs again.

**Comment by parrish** [comment]
This can still occur.
