### ISSUE TITLE
After using the preview button and submitting the post, it doesn't come back to the writing mode

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#1972]
When you use the preview button, and submit your post, the text field stays in the preview mode for the next comment too. So it looks like you aren't allowed to type any more. It shouldn't stay in the preview mode for the next post but should return to the writing mode automatically.

**Comment by itsravenous** [comment]
The comment boxes use [markdownz](https://www.npmjs.com/package/markdownz) for their editor, which doesn't expose its preview state for manipulation. Looking into what needs to happen to change that.

**Comment by itsravenous** [comment]
Markdownz issue sorted and merged, just need to wait for #1981 as markdownz depends on React 0.14
