### ISSUE TITLE
Video: svg drawing layer prevents clicking on play controls

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#1976]
The SVG marking surface completely overlays the underlying video element in the subject viewer, preventing anyone from clicking on the video play controls.

Solution is probably to ditch the native video controls and add our own custom controls, in the subject tools area, using the Media API.

Suggested custom controls: Play/pause toggle, scrubber bar, volume controls?

Maybe look at https://github.com/zackperdue/React-Video-Player

**Comment by trouille** [comment]
Add ability to change the play back speed, i.e., show video at 1/4 and 1/2 slower speeds, as in http://demo.zooniverse.org/bats-staging/#/classify

**Comment by eatyourgreens** [comment]
Added a set of radio buttons to toggle between playback speeds. Needs some styling, though.
