### ISSUE TITLE
Free drawing tool (or non-straight line). 

### ISSUE THREAD

**Issue by karenlmasters** [zooniverse/Panoptes-Front-End#198]
I think this is in the works, but I just wanted to say how keen I am to have a free drawing or a non-straight line tool. :)

**Comment by VVH** [comment]
I was playing around with the polygon tool the other day and this is what it can do ! [KittyKitty] (https://s3.amazonaws.com/uploads.hipchat.com/41383/774409/MiC2KR2XSaP7KR3/Screen%20Shot%202015-04-16%20at%2014.44.12.png)

**Comment by simensta** [comment]
Also, checkout this sandbox for the tools in the works: http://demo.zooniverse.org/panoptes-front-end/#/dev/classifier

**Comment by mschwamb** [comment]
Looks like this is closed by #3374
