### ISSUE TITLE
Project state: classifications finished but Talk still active

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#1983]
Though we have finished classifications for GZ Bar Lengths so we've been removed from active project lists (#1956), we've also been removed from the "change projects" options on Talk, so it has been [reported](https://www.zooniverse.org/projects/vrooje/galaxy-zoo-bar-lengths/talk/214/18834/?scrollToLastComment=true&page=1) that it's now very hard for volunteers to find our project.

I'm planning on using Talk to keep volunteers in the loop on how the research phase is progressing and even invite their collaboration, so I'd like to keep the project visible in _some_ way even if it's not trying to recruit new members. 

How can we accomplish this?
Tagging @brian-c @mrniaboc @DarrenMcRoy to start...

**Comment by mrniaboc** [comment]
Time for a retired projects list on the site?

**Comment by mschwamb** [comment]
There's also some paused projects like Milky Way Project and Seafloor Explorer currently in the project list, so they might also be better placed in a retired projects list with GZ: Bars

**Comment by DarrenMcRoy** [comment]
I've long said that I'd love four tabs on the Projects page: Active, Paused, Retired, Beta.

Or the equivalent. I think @jwbmartin is taking that into consideration in her wireframes.
