### ISSUE TITLE
Make it more difficult to delete a workflow

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1990]
I've had some comments that it's a little too easy to accidentally delete one's entire workflow. Someone building a project here at the Adler accidentally deleted their workflow and had to rebuild it from scratch, and there's also [this comment](https://www.zooniverse.org/talk/18/115/?comment=40111) suggesting they've had a similar problem.

Can we make it so you have to progress through a stronger "warning" stage before deleting a workflow?

**Comment by aliburchard** [comment]
+1!

**Comment by brian-c** [comment]
Closed by #2038.
