### ISSUE TITLE
Add Old Weather: Whaling to Projects page

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#1993]
Those two projects need to be added. Whaling can go at the back for now with the other Scribe projects, but if Shakespeare's World is strong performance-wise, it can go near the top!

**Comment by camallen** [comment]
Shakespeare's world is already on there.

**Comment by DarrenMcRoy** [comment]
Ah. My bad. I missed it.

Are we sticking with the Ø icons for AnnoTate and SW? We really did come to a decision to move away from those.

**Comment by rogerhutchings** [comment]
Currently down for maintenance anyway.
