### ISSUE TITLE
Add "quick start" guide to project building

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#1996]
@mrniaboc and I edited Chris Doogue's "quick start" guide to project building, since we've discovered that many folks don't read the entire tutorial. The text for the page is here: https://docs.google.com/document/d/1d2f23-w_fQWEilegD_xwUoGJmjDOwFm9PqrwGRdDEkM/edit

Can we add a page (e.g. zooniverse.org/lab-quick-start) with a link from zooniverse.org/lab?

**Comment by mschwamb** [comment]
Might also be handy to add it as a link on the 'Need some help?' section of the project builder

**Comment by aliburchard** [comment]
+1 to that too!

**Comment by eatyourgreens** [comment]
@aliburchard did this ever get done?

**Comment by simoneduca** [comment]
@eatyourgreens I think @BNewing has some updates on this.

**Comment by BNewing** [comment]
Ali left me this repo: https://github.com/aliburchard/ProjectBuilderDocumentation

I'm working on updating it and rewording it a little and then I'll put it on the site! @hrspiers would you be up for reading the draft once I've finished?

**Comment by hrspiers** [comment]
Yes of course @BNewing - let me know when you are ready for me to have a look!

**Comment by BNewing** [comment]
Thank you @hrspiers!

**Comment by BNewing** [comment]
https://github.com/zooniverse/Panoptes-Front-End/pull/3189 link to the pull request I've started. Will take a bit more work before the first draft is ready though!

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
