### ISSUE TITLE
If you make a minor change and add more data after a beta test taking the project off live  you have to reapply for review before applying for launch

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2003]
That process is confusing for me since now I have to hit both buttons to request launch since switching back development to make the minor help changes wiped the review status the project had. 

If a project applied for beta and was approved what about as long as it applied for beta once it can then activate the apply for full launch so that for minor changes teams can make them and not have to hit both buttons which is confusing and not in the project policy instructions.

**Comment by mschwamb** [comment]
cc @mrniaboc and @aliburchard 

Note I'll have to do this for Comet Hunters request to launch since we've lost the approved review status

**Comment by mrniaboc** [comment]
Yes, this is bugging me. Once you have been through beta_approved you
should be able to request launch after making changes.

**Comment by aliburchard** [comment]
Agreed. Since we'll be reviewing any project that requests launch, we can make the decision then whether or not it needs a second round of beta testing

**Comment by mschwamb** [comment]
We made the site private since we were changing the cover of things so the instructions were going to be wrong for a period of time, I didn't think of a fast and easy otherwise to do and formally end the beta and not have that go on the feedback form, since I figured y'all look it over when assessing. 

Maybe once you hit review once the apply for launch button can be wired to be accessible?

**Comment by mschwamb** [comment]
closing because you can now make edits to a workflow without changing the live project status.
