### ISSUE TITLE
Commenting on a subject 'Notes' not working in Shakespeare's World_possibly a Talk/PFE issue

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#2007]
One for @aweiksnar, @parrish and maybe @simoneduca to look into. Not sure if more widespread. If you try to submit a comment on an image the site just hangs. See: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/20871?comment=42960

**Comment by aweiksnar** [comment]
@VVH PR up here - #2007
