### ISSUE TITLE
Can't see anything you're typing in the tags line on the project details page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2010]
You can't see any of the text you type in the line for tags in the project builder now at least for Firefox. It definitely wasn't like that a few months ago. I can't see any text and if I have a typo and hit delete it deletes the text and the tag before

**Comment by CKrawczyk** [comment]
I can reproduce this issue on both firefox and chrome.  This only seems to be broken in the production branch, the tag input field works as expected in the preview branch.

**Comment by camallen** [comment]
most likely related to the react 14 upgrade.. @aweiksnar ?

**Comment by eatyourgreens** [comment]
I've just rebased a feature branch to react14 and can reproduce this bug on preview too.

**Comment by eatyourgreens** [comment]
I've been playing around with this, this morning, and I think #2015 will fix it.
