### ISSUE TITLE
Is there really supposed to be a 20 image media limit?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2012]
The project building guide says you're limited to 20 images. I have way 25 or so currently for Comet Hunters with no problem. All but 2 are really necessary. 

Is it really supposed to be limited to 20 and there's no check in place or should that text be changed?  Or Or s the limit much higher than that or there is no check? 

cc @aliburchard

**Comment by aliburchard** [comment]
Sorry for only seeing this now @mschwamb. I am all in favor of a much higher a limit, especially because I think we want to encourage more help pictures and less help text. Sounds like the text in the project builder is wrong and needs changing.

**Comment by mschwamb** [comment]
@ aliburchard  It's actually  not in the project builder. It's in the project building tutorial you made.  There's no text about a limit on the media page at all. It was the first time I had seen any mention of a limit for the media content (non-subject).

 I'm now on about 25 images uploaded on the media page it didn't complain.. There's no text referring to a limit on the media page itself  the project builder. I caught it while reading through the tutorial and polices text  since for me Comet Hunters is a more formal launch through the system than P4: Terrains and I wanted to make sure I didn't miss anything I needed to provide you with for Zooniverse review. 

Maybe putting some text on the project builder would be good. I would do a pull request, but I didn't know what to put.
