### ISSUE TITLE
When you take a project to off live mode/put in private having a message or page saying we're dong construction or maintenance right now

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2013]
Especially with a beta test, I found people keep coming in the week after it was sent out. Mainly these are people who are really interested in the project. So if I take it off live, they just get a white screen. same thing happens currently if you need to add a new subject set after launching. 

It would be nice if didn't look there was something wrong with the site since there's no real way for people to know the beta test is done and the team might be making some tweaks and making other changes to address the user feedback.

**Comment by mschwamb** [comment]
Linked to #1792  - when it's private people who did the beta test and come back it will look the site broke rather than is just private

**Comment by aliburchard** [comment]
@mschwamb I agree that we should come up with a better response for folks trying to access private projects. In the meanwhile for your project, would making it "public" be okay? Presumably while your project is "private" the only people who can view it are those with usernames you've explicitly added via the "collaborators" page. Or are you setting it to private only to hide it from people classifying while it's being changed?

**Comment by camallen** [comment]
don't make it private, we just need a better way of messaging, i.e. https://github.com/zooniverse/Panoptes/issues/1403

**Comment by mschwamb** [comment]
I think this is sorted as current messaging says 'you might not access to the site' so I think it's clearer. Closing.
