### ISSUE TITLE
mini-ztm branch: dropdowns are hidden behind project cards

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2017]
On http://preview.zooniverse.org/panoptes-front-end/miniztm/?env=production#/projects/ we now see the Search and Project dropdowns hiding behind the main project cards.Probably fixable with CSS.

**Comment by amyrebecca** [comment]
this was just a stray overflow: hidden, not something much scarier like a z-index or stacking order thing

**Comment by alexbfree** [comment]
Thanks! :-)
