### ISSUE TITLE
mini-ztm branch: pagination broken

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2018]
See http://preview.zooniverse.org/panoptes-front-end/miniztm/?env=production#/projects/

If you have All Disciplines active, and click through to 2nd page, you still get the 1st 20 cards.

**Comment by alexbfree** [comment]
@amyrebecca did some initial investigation into this and found that the correct pagination values are being passed to the API so this suggests that there is an issue with pagination in the backend when a sort is active.

**Comment by camallen** [comment]
anything to reproduce? i.e. click on this page on the branch and click these buttons, etc.

**Comment by alexbfree** [comment]
As I say, go to link above. Just click through to 2nd page, you will see it hasn't advanced (showing 1-20 instead of 21-40

**Comment by camallen** [comment]
sorry - which link? Not seeing any, is this deployed?

**Comment by alexbfree** [comment]
Yes - as mentioned in the first comment on this ticket http://preview.zooniverse.org/panoptes-front-end/miniztm/?env=production#/projects/

**Comment by alexbfree** [comment]
Notes from Sarah
* some debugging can be done in console using `zooAPI` which is using the json-api-client:https://github.com/zooniverse/json-api-client/
* PFE uses json-api-client. panoptes-javascript-client is a fork of json-api-client and the panoptes specific code merged together (and also rewritten in ES6)

**Comment by eatyourgreens** [comment]
Shouldn't the URL for page 2 bee something like http://preview.zooniverse.org/panoptes-front-end/miniztm/?env=production&page=2#/projects/ rather than http://preview.zooniverse.org/panoptes-front-end/miniztm/?env=production#/projects/?include=avatar&launch_approved=true&page=2

The `include` and `launch_approved` query params probably shouldn't be there, I'd guess.

**Comment by alexbfree** [comment]
Yeah I agree. The URL seems to get pretty over-complicated. 
If you start at `http://preview.zooniverse.org/panoptes-front-end/miniztm/?env=production` then click to Projects then Page 2, you end up with `http://preview.zooniverse.org/panoptes-front-end/miniztm/?env=production#/projects/?include=avatar&launch_approved=true&page=2` which is overkill I think!

However even the simpler http://preview.zooniverse.org/panoptes-front-end/miniztm/?page=2&env=production#/projects/ doesn't seem to work

**Comment by eatyourgreens** [comment]
Maybe an obvious question, but it looks like miniztm was forked from master in August (I have no idea how this has happened) https://github.com/zooniverse/Panoptes-Front-End/compare/miniztm

So, does it have the latest fixes for pagination, since then?

API calls for page 2 look fine, by the way.

**Comment by alexbfree** [comment]
well that would be weird. i thought it was created last week along with the channel.

**Comment by alexbfree** [comment]
perhaps this will all be sorted out by the merge and #2021 then. I think somewhere along the line we assumed we'd broken it, but maybe it never worked on this branch.

**Comment by camallen** [comment]
I tested the api calls (use network tab in browser and click pagination links), they look fine and testing the returned expected data. However the UI wasn't updating though so most likely a render / state error.

Also the `launch_approved` is req'd and pretty sure the `include` is as well as we only want the launched projects on the home page. Searching I'd argue shouldn't but we can figure that out later.

**Comment by eatyourgreens** [comment]
Yeah, but odd that they're being added to the URL. Page 2 on the zooniverse site is just https://www.zooniverse.org/projects?page=2. Worth checking that the pagination code on this branch is up-to-date.

**Comment by alexbfree** [comment]
Thanks for checking that Cam. Seems most likely that this is just a problem due to old code.

**Comment by amyrebecca** [comment]
yeah i'm not sure what was going on but the code in the branch was just non-functional. i've fixed it now and also prevented a bunch of nonsense cruft from getting in the URL, now all you'll see is the page, the sort, and the filter (if either are non-default)

**Comment by alexbfree** [comment]
Thanks! :-)
