### ISSUE TITLE
mini-ztm branch: need to consolidate discipline pages

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2019]
Move "grouped by discipline" page under "all disciplines" filter of main project page (and show small discipline icon next to each title)

**Comment by amyrebecca** [comment]
there is such a substantial difference between the markup generated for the normal view vs. the grouped view that i wonder if it shouldn't be a separate route anyways? maybe we could do something like /projects/list and /projects/grouped because then we can use react-router to load in different markup at the page level rather than switching between two chunks of markup in our page itself

**Comment by amyrebecca** [comment]
/projects/grouped/?by=discipline or something along those lines

**Comment by alexbfree** [comment]
Don't worry about this one @amyrebecca , since I wrote the discipline page (with Coleman), I'm happy to take care of it myself. Let me know when you and Brian have aligned your various changes and I will give you a PR into the project-page branch to include, prior to main PR merge.

**Comment by amyrebecca** [comment]
Sounds good, we'll be meeting tomorrow at 10am about this stuff

**Comment by amyrebecca** [comment]
@alexbfree Some of the changes Brian has requested are fairly major (including breaking the dependency between the projects page (and the projects discipline view, presumably) and OwnedCardList. I'm not sure if your work will be completely compatible with this, so I wanted to give you a heads-up.

**Comment by alexbfree** [comment]
OK having some investigation on this, i have a plan, but I no longer think this is a must have for project page launch.

I think the right thing to do is to introduce a "by discipline" sort order into the dropdown, which is on by default, and then to make all/most sort orders show little subheadings for each group of projects - for the "by discipline" order this would be the discipline name e.g. "Biology". For Launch Date it might be "Last month" etc, for "most in need of help" it might be "Less than 20% complete" ... etc

However, since those pieces of info are not in the project resource that comes back, we probably need to change the API to achieve this... so I'm going to close this ticket and create new ones for this.
