### ISSUE TITLE
mini-ztm branch: rebase code to react-14, new master code etc

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2021]
We need to rebase the mini-ztm branch to master & react-14.

Once this and issues #2018 #2017 #2019 #2020 are fixed, we can merge miniztm to master and deploy to prod.

**Comment by alexbfree** [comment]
per Jim's comment on #2018 it may be that miniztm is actually hugely out of date, apparently was forked in August, not in December.

**Comment by eatyourgreens** [comment]
Here's branch that's forked from the latest master. http://preview.zooniverse.org/panoptes-front-end/video-custom-controls/ Pagination works on the home page there, so perhaps a clean fork from master will fix #2018

**Comment by srallen** [comment]
Agreed. A clean branch from master is probably the way to go given the divergence. @alexbfree, instead of trying to fix and clean up the miniztm branch, could pull down the latest and make a new clean branch and just move in the new features there?

**Comment by alexbfree** [comment]
i agree that makes sense. whoever gets to this ticket first (which might be me but might be someone else) should definitely do that. thanks for checking Jim.

**Comment by amyrebecca** [comment]
This has been a huge hassle but I'm basically there; the branch is called project-page in git

**Comment by alexbfree** [comment]
Well done for enduring the pain on this one Amy, thanks!
