### ISSUE TITLE
Currently no way to reset the tutorial so if you change something for beta test that it forces everyone to resee it

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2022]
Not sure if this a front end or back end issue, but I noticed that having changed some wording in the tutorial before launch of a project, there's no way to say hay we're launching now reforce everyone to watch the tutorial who came for the beta

**Comment by alexbfree** [comment]
perhaps one way we could fix this (if tracking "has seen tutorial" for every user and every workflow would be too tricky, would be to have a "skip tutorial" button

**Comment by camallen** [comment]
It's very much a user preference to not see the tutorial again, we should respect their wishes. I can hack the data to remove the record that users have seen the beta tutorial. Long term we should think about recording launch / beta state for the tutorial completion key to avoid this issue.

**Comment by mschwamb** [comment]
I agree @camallen that volunteers should not see the tutorial again unless the team made changes to it, and the only time I see that is launch or a relaunch. 

 The PI changed the colors of our subjects (we had red and now magenta lines in the image) and we simplified terminology so it would be good for launch if we made everyone see it again or at least on previous custom projects this was sorted by clearing the classification database right before launch. 

I just noticed some stragglers already on from the beta classifying again (as the site is live and waiting for Zooniverse approval) and realized they wouldn't get the tutorial again. 

It's only 150 people, but if you're comfortable and time to clear stuff in the database such that people would see the tutorial again that would be great. If not, we can live with it.

I believe we're launching tomorrow ( @mrniaboc can confirm that)

**Comment by camallen** [comment]
done on my end, all users have had their tutorial pref reverted.

**Comment by eatyourgreens** [comment]
Is the tutorial resource versioned? If so, maybe record the version that
they've done in the user project preferences, instead of a simple done/not
done flag. Then it can be shown to them again if there's a newer version
than the one they've seen.

On Tuesday, 15 December 2015, Campbell Allen <notifications@github.com>
wrote:

> done on my end, all users have had their tutorial pref reverted.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes-Front-End/issues/2022#issuecomment-164736328>
> .
>


-- 
--
James O'Donnell
email: jim@zooniverse.org
mobile: 07811 771 352
twitter: @pekingspring

**Comment by camallen** [comment]
it's just a setting in the `UserProjectPreference#preferences` hash, e.g. `preferences: {"tutorial_completed_at": date_time}` i assume something like could become `beta_tutorial_completed_at`. Basically append the launch / beta state if available and match to the project state.

**Comment by mschwamb** [comment]
Thanks very much @camallen
