### ISSUE TITLE
Small CSS issue with vertical alignment on new project cards

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2023]
The new project cards (which look *much* better BTW!) have a couple of small issues with vertical text alignment of titles:
1) When not hovered over and the title spreads onto two lines, the text is not vertically centred.
2) Regardless of whether two lines or one line, when hovered, the vertical alignment of the title seems off/not centred.

![wrong alignment of two-line titles](https://cloud.githubusercontent.com/assets/1473244/11807231/71892450-a310-11e5-9033-5c9f4adea90e.png)

![showing issue exists on hover with single line titles too](https://cloud.githubusercontent.com/assets/1473244/11807236/7bb89a78-a310-11e5-82bb-0b27973ca2a0.png)

I may come back and fix this myself; for now just logging it.

**Comment by srallen** [comment]
Pinging @jwbmartin to double check the design with her.
