### ISSUE TITLE
Filter Task: alphabetize vertically instead of horizontally?

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2024]
@eatyourgreens and I noticed recently that while our original custom camera trap projects -- Snapshot Serengeti and Chicago WIldlife Watch -- sort the species list in columns and _then_ rows, PFE sorts the species in rows first. 

Vertically:
![screen shot 2015-12-15 at 11 52 18](https://cloud.githubusercontent.com/assets/6217406/11809950/74cff64a-a322-11e5-9cf2-703a0152f190.png)

Horizontally:
![screen shot 2015-12-15 at 11 52 43](https://cloud.githubusercontent.com/assets/6217406/11809956/7ef249b6-a322-11e5-9488-b3fdb1239d79.png)

I personally find the vertical sorting much more intuitive, and think we should be consistent across projects. With a lot of PFE camera trap projects getting close to launching (especially USA WW), I think this is a decision to make *soon* in order to maintain consistency. That being said, Wildcam Gorongosa is our only horizontally sorted project, and I don't know what a change to PFE would mean for that interface.

Really curious to hear from @trouille, @amyrebecca, and @srallen for thoughts on sorting for USAWW, and from @jwbmartin @brian-c @mrniaboc @vrooje @chrislintott or anyone else who might have thoughts on whether it's better to sort vertically v horizontally.

**Comment by srallen** [comment]
@aliburchard At least for WildCam, a change on PFE won't mean any changes for it The survey task code is literally copied, which is bad practice, but what we had time for when building. In the process of development, a couple of new features were added specific for WildCam. One specifically is the linking to the field guide in the interface. Going forward, we either have to maintain very similar task components in two places or figure out how to merge in that feature into PFE and modularize the component so they're in sync with each other.

As for vertical v horizontal, I think we should probably go with one or the other, but I think while the newer projects are different from the older that we could do some A/B testing or survey of volunteers to find out what works better? If we find that horizontal works better, then we can at least have a reason why it's different from older projects.

**Comment by brian-c** [comment]
In terms of scanning the list, stacking the items vertically is probably preferable.

They flow horizontally right now to avoid having to scroll down and up to read the list in order (same reason you don't see newspaper-style column layouts on screen). But that'll only happen with large numbers of choices.

**Comment by mrniaboc** [comment]
vertical++

**Comment by vrooje** [comment]
I prefer the vertical too for this specific application. Mostly I'd expect
to prefer reading L-R then vertically, but in this case it looks more
newspaper-style so that's what seems natural to me.

How could we tell from an AB split whether one worked better?
Classification speed of new classifiers? (I agree we could also just ask
the volunteers.)

**Comment by camallen** [comment]
My two cents, i always expect the list to be sorted vertically. I find wildcam harder to find what i'm looking for.

**Comment by DarrenMcRoy** [comment]
Also vote vertical. Just reads more intuitively to go down each column -- like reading a newspaper.

**Comment by jwbmartin** [comment]
Vertical +++

**Comment by amyrebecca** [comment]
vertical is the obvious right thing to do imo, but it makes me sad because
horizontally then vertically is so much easier to do. time to play with
flex box :P

On Tue, Dec 15, 2015 at 11:06 AM, Jordan W Martin <notifications@github.com>
wrote:

> Vertical +++
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes-Front-End/issues/2024#issuecomment-164828868>
> .
>



-- 

SPACE IS FREAKING AWESOME

**Comment by CKrawczyk** [comment]
vertical++

**Comment by aliburchard** [comment]
Vertically it is! (@brian-c really interesting point about scrolling for long lists though.)

I'm assuming we want to change this before launching WWW, since a change in ordering after the project has launched isn't ideal. @amyrebecca is this something you can take on since you're adding some functionality for WWW?

**Comment by aliburchard** [comment]
@amyrebecca out of curiosity, is this being incorporated into the flexible survey task? I didn't see it, but not sure if I'm looking at the latest code. I do think it's a bad idea to launch the project knowing this change is needed and will be incorporated into the final survey tool. It won't change the output, but I think giving folks a reasonably big interface change after project launch isn't ideal. Thoughts?
