### ISSUE TITLE
Design touch ups

### ISSUE THREAD

**Issue by jwbmartin** [zooniverse/Panoptes-Front-End#2027]
@amyrebecca you're going to hate me buuuuttt I think your original idea of have the projects filter down as they search instead of the drop down would be better. I'm just not a fan of having the drop down cover up content.

Anyways, here is what I had in mind as far as touch ups for the projects page. The buttons got distorted to demonstrate how I imagined they would align so if the button size/padding needs to come down a bit to make it work I think that will be ok?
<img width="1189" alt="projects_page_touchups" src="https://cloud.githubusercontent.com/assets/14332849/11816994/8f700e40-a318-11e5-8126-966244d041fa.png">

**Comment by DarrenMcRoy** [comment]
Oh, I LIKE that.

**Comment by jwbmartin** [comment]
Should/Can I create arrow icons that we can add to our font set @srallen?

**Comment by jwbmartin** [comment]
Well, I made some nice looking arrows that we could make into a font to use for the slider if you feel like working your magic @srallen 
[Arrows.zip](https://github.com/zooniverse/Panoptes-Front-End/files/62960/Arrows.zip)

**Comment by srallen** [comment]
@jwbmartin FontAwesome is being pulled in too for more standard icons. Would one of the FontAwesome directional icons work? https://fortawesome.github.io/Font-Awesome/icons/

**Comment by jwbmartin** [comment]
@srallen Ah! chevron-left chevron-right!

**Comment by aliburchard** [comment]
This looks so good!

**Comment by srallen** [comment]
Projects page has been redesigned.
