### ISSUE TITLE
mini-ztm branch: Accessibility issues with filmstrip

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2030]
the issues detailed in https://github.com/zooniverse-ui/filmstrip/issues/1 need to be fixed before this is launched.

**Comment by amyrebecca** [comment]
These have been resolved in this repo, the filmstrip in zooniverse-ui still needs to be backfilled with those changes.

**Comment by alexbfree** [comment]
@amyrebecca do we have an issue for that in filmstrip component @amyrebecca ? If so can you link it here? If not, can you create one? Thanks
