### ISSUE TITLE
Create "workflow display text" in addition to "workflow title"?

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2031]
Right now the "workflow title" does double duty - it's what volunteers see on the buttons, but also how we identify which classifications belong where in the classification export. This creates a couple of issues.  

First, the text you want to display for a workflow for volunteers is often much longer than you need returned in the classification export (e.g. "Mark shadows and the rising/setting sun" for display vs. "shadows" in the export).

Second, if you have a project with only one _active_ workflow of several existing workflows (e.g. Snapshots at Sea) you might want the button to say "Get Started!" instead of this: 
![screen shot 2015-12-16 at 11 32 18](https://cloud.githubusercontent.com/assets/6217406/11839825/b5bcfdb2-a3e8-11e5-9c6e-82495a53e28c.png)

But changing the Workflow Title to "Get Started!" will cause issues in the classification export because we are going to launch the second workflow once the first workflow is finished, and would have to then rename that to "Get Started!". 

Thoughts?

**Comment by aliburchard** [comment]
Hmm. All this being said, we do also record Workflow ID in the classification export, so it's not impossible to link classifications back to the proper workflow even if multiple workflow titles are identical, but it is one additional step, and would require project owners to manually go back to the project builder and figure out which Workflow ID belongs to which workflow (I couldn't tell you what my workflow numbers are off the top of my head).

**Comment by camallen** [comment]
can you untick the "Volunteers can choose which workflow they work on" box for the 1 workflow scenario to get the Get started text?

**Comment by aliburchard** [comment]
@camallen you are a genius. 

Okay, so that fixes my main issue. BUT I still think there might be value in having more concise output, but not sure.

**Comment by aliburchard** [comment]
@mschwamb realize this issue duplicated your now-closed #268. I still like the idea of having separate display text in order to streamline classification data outputs.
