### ISSUE TITLE
Tutorial for Space Warps Demo

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#2033]
I see there is a tutorial & tutorial button coded in this repo and others have made issues regarding the tutorial, but I can't seem to figure out how to enable it in the front-end project builder. Is there a way to switch this feature on? the demo project is 
https://www.zooniverse.org/projects/aprajita/swdemo/classify?workflow=960
thanks!

**Comment by trouille** [comment]
@aprajita If you temporarily add me as a collaborator and send me a quick email as a heads up, I can turn on the tutorial functionality for you. It's an experimental feature that currently requires admin access to turn on.

**Comment by aprajita** [comment]
Thanks @trouille - what's your zooID @trouille as well?

**Comment by aprajita** [comment]
Hi @trouille 

I added you as a collaborator - please let me know if you can see it.

Thanks!

**Comment by aprajita** [comment]
Thanks for enabling this Laura
