### ISSUE TITLE
Space Warps Demo: Syntax error for uploading Gold Standard Data

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#2034]
Hi

I am trying to reproduce the SpaceWarps feedback messages in the test panoptes sw site and am having difficulty.

I don't quite understand the syntax for the Gold Standard Data upload available in the Project Builder...

Is there any explanatory text other than the format shown in the accompanying help box? 

If i understand correctly subjects is a list of all the already uploaded subjects in the dataset that are to be used as gold standard. The task T1, T2 etc refer to the different tasks, but I don't understand what '3' means in the first annotation. 

How do I make the feedback conditional on a mark being placed?

i.e. for spacewarps I only have one task, but how do i include the following:
If this is a training image containing a lens 
(i) the user marks the image I want to say something like  "well done you spotted a lens"
(ii) the user doesn't mark the image I want to say "you missed a lens"
If the training iamge is a 'dud' i.e. blank field, 
(i) if the user doesnt mark the image I want to say  "well done this image doesn't contain a lens"
(ii) if the user marks the image i want to say "this image doesn not contain a lens, you may have marked a false positive, see the help pages..."

For the demo I am just trying to select a few of the test subjects into gold standard data to test the feedback system. If there's any clarification you could give me that would be very helpful.

Is it possible to specify the x,y location for where the feedback message should appear on the subject/screen.

Thanks
Aprajita.

**Comment by camallen** [comment]
@aliburchard @mrniaboc has anyone setup the GS feedback data yet?

**Comment by aliburchard** [comment]
not that I'm aware of -- I think the feedback is hardcoded?

**Comment by camallen** [comment]
more specifically the upload that @aprajita needs help with? I know there is an import tool for it but haven't played with the csv format.

**Comment by aprajita** [comment]
Marten pointed me to the Classification feedback PR 
https://github.com/zooniverse/Panoptes-Front-End/pull/1934
for more info. 

For Nero, we will add the training subject flag to the metadata (as was done for the original spacewarps) used as gold standard data. Could we also include the success and miss feedback messages in the metadata for the training images? This has the advantage that we can provide tailored feedback according to different lens configurations (as we did for previous SW).

If that's not possible, when you say the feedback is hardcoded do you mean I should send some example text or that the messages are already fixed.

thanks
Aprajita.

**Comment by eatyourgreens** [comment]
Closing this in favour of #2834
