### ISSUE TITLE
New tutorial button pushes the toggle  (& collection button in Firefox) into a werid spot

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2036]
@brian-c small fix we need.  The newTutorial button looks great and it very clear. Strange thing happened, it moved the toggles for multiple images in a subject and the collection button  into a weird spot for FIrefox and just moved the toggle for Chrome and Safari.  Can you or someelse adjust that? Not a huge deal since we've got the play button working fine

Looks like from non-logged in that is just slid the toggle to the right - looks different in fire fox than chrome

Firefox:

![screen shot 2015-12-17 at 9 01 15 am](https://cloud.githubusercontent.com/assets/753325/11858522/73f6eb30-a49d-11e5-9834-f54b2fbdabdc.png)

Chrome:

![screen shot 2015-12-17 at 9 06 48 am](https://cloud.githubusercontent.com/assets/753325/11858542/937546fa-a49d-11e5-81b6-693c0fe5de33.png)

Safari:

![screen shot 2015-12-17 at 9 08 21 am](https://cloud.githubusercontent.com/assets/753325/11858598/e6e321fe-a49d-11e5-8217-26f0fd8d47a4.png)

Here's what it used to look like: 

![comet_hunters_blinking4](https://cloud.githubusercontent.com/assets/753325/11858639/2dfedde4-a49e-11e5-907b-b1926e08c1d4.gif)

So it's only in Firefox that the collection button is impacted and the toggle is on two lines. The toggle used to in the middle, however you want to adjust this fine by us  and I'll update the tutorial if need be

**Comment by eatyourgreens** [comment]
This is a stray inline style from the new video player controls. I'll have a look.

**Comment by mschwamb** [comment]
Thanks @eatyourgreens very much appreciate it!

**Comment by mschwamb** [comment]
thanks @eatyourgreens and @aweiksnar for getting to this today!
