### ISSUE TITLE
Missing URL for the media server...

### ISSUE THREAD

**Issue by casco** [zooniverse/Panoptes-Front-End#2041]
I got  Panoptes-Front-End to work with a local Panoptes server. Editing all properties of new projects works ok.

However, when uploading media and subject sets, the URL of the media server seems to be missing

[Log] Uploading example-icon.jpg => https://project_attached_image/5a18607e-04cd-41f6-a887-0d7e596f6dd4.jpeg (main.js, line 9662)

I do not find a specific property for that in config.coffee . Is it somewhere else?

**Comment by srallen** [comment]
We use S3 as the static media server and the response from creating the media will have the URL to use for media upload.
