### ISSUE TITLE
"Please register" pop-up may be losing volunteers after 5 classifications

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2049]
When an unregistered volunteer starts classifying a project, after 5 classifications, s/he gets a pop-up asking her/him to (1) log in; (2) register; or (3) continue unregistered. It's clear that *something* is happening after 5 classifications -- either users are logging in and registering OR they're leaving the project because they've been interrupted. 

We can see the pattern of unregistered users "disappearing" from a visual of Season Spotter user contributions: https://seasonspotter.wordpress.com/2015/11/30/season-spotters-unregistered-volunteers/

More investigation is needed to determine whether users are leaving the site or are actually registering. This is especially relevant for new projects, which get a lot of one-time attention. If the pop-up is causing people to leave, it may want to be reconsidered.

**Comment by camallen** [comment]
Pinging @mrniaboc @alexbfree something for tracking events / Geordi ? Also @mkosmala you should have the IP of the users in the classification metadata, if they just log in then you can link them on this data (note it's not perfect) and there is also a session ID [here](https://github.com/zooniverse/Panoptes-Front-End/blob/7affa994c3bf781c2aae685db93bcd43b6a07ae0/app/classifier/index.cjsx#L325) which should not reset on login.

**Comment by mkosmala** [comment]
@camallen Yes, agreed, it can be done that way. I just don't have time to do it!

**Comment by camallen** [comment]
Cool - just outlining the data we have for you.

**Comment by aliburchard** [comment]
That sounds like a *really* fun analysis/paper to do for citizen science interface design... not like any of us has tons of time on our hands, but I'd certainly be interested in working in it. At some point. @mkosmala @mrniaboc @chrislintott what sorts of journals would that be appropriate for as a small bite-sized paper?

**Comment by mkosmala** [comment]
@aliburchard I bet Andrea Wiggins would have a good answer for you on that.

**Comment by alexbfree** [comment]
Hi, this is definitely something we can easily track with Geordi. As it happens I am just adding some improved IP tracking to Geordi this week and have been looking for an way into adding Geordi tracking to Panoptes. I'll add this to my to-do list.

**Comment by alexbfree** [comment]
Just to let you know, the latest version of Geordi now tracks IP address for every single event, both while logged in and while not logged in, this should make it easy to see whether not-logged-in people are sticking around. @amyrebecca and I will be adding Geordi tracking to the classification interface and talk interface for Project Builder projects over the coming weeks, so we should be able to answer your question soon.

**Comment by srallen** [comment]
Sign in prompt is an animation below the subject viewer now.
