### ISSUE TITLE
Home page - near term

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes-Front-End#205]
I wish there was a way to tag everybody for this issue...

Consider this the place to have discussions on what will show up on zooniverse.org when we launch Panoptes. While there has been many ideas bantered about, please keep this scoped to realistic goals that we can achieve in this milestone.

@heathv Please reference any design work you do on the homepage here.

We chatted about this two weeks ago in Chicago, and while I don't want to put words in anyones mouth, here is what I took out of that discussion:

A logged in user simply goes to their profile page (comments on, please see #59). 

A non-logged in user sees a couple things, in order down the page

- Intro to the Zooniverse - large banner image with some brief copy attempting to explain who we are and what we are all about. Call to action should be about creating an account and getting started classifying on a project. 
- Zooniverse Live - In a perfect world, I'd love to simply port ZooLive into this space. Realistically, some way of communicating that stuff is actually happening in the Zooniverse. Feed from Daily Zoo, subject/user/classification counts, whatever.
- Projects - A brief listing, probably a curated one, of various projects built on Panoptes.
- Project Builder - Reference the project builder and message that if you have an idea for a project, you can use our platform to create it.
- Footer - Various links that we have to put somewhere.

Worth mentioning that nothing has been built yet and it's all up in the air.

**Comment by chrislintott** [comment]
Additions from me :

1. A view for beta projects as well as the full on project list
1b. The inclusion of the other live Zooniverse projects (not just Panoptes) 
2. Login. 
3. Whatever content from the CSA site is worth saving.

**Comment by chrissnyder** [comment]
1. The way I currently imagine it, these would live on the project list page. I've opened #206 to discuss concerns there.
2. Already handled via the popup and is available sitewide.
3. I've asked @DarrenMcRoy to do an audit on what content we have available. Will be opening another issue to discuss what other content we'd like to have, outside of what already exists (if any).

**Comment by chrislintott** [comment]
I will take on the task of looking at the CSA content.

Chris

**Comment by vrooje** [comment]
In case it's useful, I've moved the notes I took during the ZooTM unconference session on Zoo Home to [this separate Google Doc](https://docs.google.com/document/d/1OmDSkMiRqrS1vN_u7C3y_4hgDqKgoJD8Zhg6qwNVlRg/edit?usp=sharing).

The doc is mostly looking farther down the line but I've put in bold the things we talked about as potentially more immediate. They were:

Zooniverse Live - including live running classification count (total, from all projects)
Classify from a simple project on Zoo Home ("free sample")
Featured projects
Zooniverse 101
...plus some things specifically for project builders.

There's some overlap with what's already above, but I figured it was worth listing this even though I probably don't have a great grasp of a realistic scope here.

**Comment by srallen** [comment]
How would a featured project be determined? Curated manually or possibly by a boolean value on the project?

**Comment by camallen** [comment]
@srallen check out these proposed states for determing the approved, beta playground projects: https://github.com/zooniverse/Panoptes-Front-End/issues/240#issuecomment-98984793

Comments and thoughts welcome.

**Comment by srallen** [comment]
I've added some rough content and styles in the [homepage] (https://github.com/zooniverse/Panoptes-Front-End/tree/homepage) branch. I've hard coded in some 'featured' projects including pulling in a random one's project stats and its classification interface that @vrooje suggested at the ZooTM. 

@brian-c, I'm thinking about trying out [this port of chart.js to React] (http://jhudson8.github.io/react-chartjs/index.html) for Zoo Live or for featured project stats. Any thoughts about it?

**Comment by camallen** [comment]
Just putting this out there, http://www.highcharts.com/ (it's free for non-commercial sites) and https://www.npmjs.com/package/react-highcharts

**Comment by heathv** [comment]
[Click here for the ZooHome file I'm working off of.](https://assets.adobe.com/link/9d18796d-f589-4600-64c6-e3614f6d684d?) Click "extract" in the top left to get a 1:1 view of the file. In general I'm flushing out the structure and working towards updates to the style guide.

##### General Notes
+ Generally working with structure here, also trying to work out an updated style guide.
+ Colors (as of now) experimental only.
+ The link above is to the file I'm working on directly, so stuff will change as I save.

**Comment by aweiksnar** [comment]
Wow looks fantastic

**Comment by mrniaboc** [comment]
I think that the main landing page looks good at the moment, with a simple welcome statement about what we do and a call-to-action button. It would be great to have different ways of sorting the projects (by genre, popularity, date of creation etc), also I think we need a page like www.zooniverse.org/me for volunteers who are logged in. I think we should definitely keep a count of total registered volunteers on there too!

Finally, are we sticking with the term 'lab' for the project builder? I'm not a huge fan of that. It is science-specific, and doesn't really explain what it is at all. I think something like 'build' would make much more sense (especially since most of us refer to that area as the 'project builder').

**Comment by mrniaboc** [comment]
Sorry @chrissnyder. Just read #206 regarding project list filtering. I guess that can wait until after launch.

**Comment by mrniaboc** [comment]
We also need to have a publications page!

**Comment by VVH** [comment]
Hey all and @heathv in particular, I know it's late to be piping up, but the home page image doesn't feel quite right to me. Somehow the inclusion of a mac and an Iphone (or similar) suggests that you need to have expensive and high-powered gadgets to participate. I don't have any alternative design ideas off the top of my head and I'm no designer, but I wonder if you had any other contender images?

**Comment by heathv** [comment]
That image is placeholder. The idea is to have that be a changing featured image or video—ideally from a project.
