### ISSUE TITLE
No back button on final classification

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#2050]
If a classification, yes no style, is the last action you are presented a DONE button upon which you get to the next screen where there is the NEXT button to go to the next classification. However, if you made a mistake you can not go back, as there only is a talk button no back button (to correct a mistake).

Would it be possible to get a back button, as there is also a double confirmation going on anyway (as the first DONE, is not the final answer).

**Comment by aliburchard** [comment]
Hey Koen - Once you hit "done" and can see the classification summary, you've already submitted the classification, so going back isn't possible. 

Though I might be misunderstanding what you're talking about -- can you add a screenshot of an example?

**Comment by khufkens** [comment]
So why show the frame where you have to press next?

I now noticed that you aren't presented with a back button on annotations either. It would make sense if you are allowed to review and make corrections. Now the summary only rubs it in your face if you misclassified something, with no option to correct it!

So I would switch the done button for a next one and make the next button a done button. This would make more sense to me.

**Comment by aliburchard** [comment]
Can you send a screenshot of the page you have an issue with? I'm not sure I follow you when you say "I now noticed that you aren't presented with a back button on annotations either."

**Comment by khufkens** [comment]
Hi Ali,
Here is an example, with the back and done buttons visible (you can go back one step).

<img width="1198" alt="screen shot 2016-01-04 at 22 01 53" src="https://cloud.githubusercontent.com/assets/1354258/12100388/e8bafc46-b32e-11e5-8ad0-c90fc3942f2c.png">

However, once you hit done it is officially submitted. This gives you no chance to review your classification, the summary is there for 'show'. There is no way to go back and correct things if you have overlooked something. The summary gives a way to step back, which is good way to reconsider. However, there is no way back as it's already filed!

<img width="1190" alt="screen shot 2016-01-04 at 22 02 09" src="https://cloud.githubusercontent.com/assets/1354258/12100427/337d61c4-b32f-11e5-916f-34db776cbb4e.png">

It's a conceptual issue I guess.

**Comment by aliburchard** [comment]
Hey Koen - 
Yeah, okay, I completely agree with you that the summary page is frustrating. We are working on improving it for cases where there is gold standard data (so you can see how your answer compared to an expert), but I don't think we have come up with a good solution for the vast majority of classifications, where, as you point out, all you see is a reminder of what you've done. 

The critical reason we have this step is because we need to give volunteers a way to access "talk" (but not until after they've submitted the classification). We've found a workaround for "one-step" workflows (see https://www.zooniverse.org/projects/tedcheese/snapshots-at-sea/classify), but I don't think we have a good solution for more complex workflows just yet.

**Comment by mschwamb** [comment]
accidentally closed

**Comment by richwiseman** [comment]
> The critical reason we have this step is because we need to give volunteers a way to access "talk" (but not until after they've submitted the classification). We've found a workaround for "one-step" workflows (see https://www.zooniverse.org/projects/tedcheese/snapshots-at-sea/classify), but I don't think we have a good solution for more complex workflows just yet.

We were wondering how you implement the workaround? We have a really simple task with just one step, and would also like to remove the confirmation screen, ours is a text box though rather than radio buttons

**Comment by camallen** [comment]
@richwiseman we've got a mechanism that we can turn on that modifies the summary screen behaviour, e.g. https://www.zooniverse.org/projects/tedcheese/snapshots-at-sea/classify

**Comment by eatyourgreens** [comment]
Closing this because hiding the summary is an option now for projects.
