### ISSUE TITLE
Track down setState on unmounted ProjectLinker

### ISSUE THREAD

**Issue by itsravenous** [zooniverse/Panoptes-Front-End#2055]
`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the ProjectLinker component.`

Probably introduced by #2054.

**Comment by itsravenous** [comment]
@eatyourgreens I've copied the warning above from [your comment](https://github.com/zooniverse/Panoptes-Front-End/pull/2054#issuecomment-166851060). I get the same warning except it references `ProjectClassifyPage`. This is when I click "Done & Talk". This makes sense to me as that button is a `<Link>`, so the unmounting of the classify page component will be immediate. I think the `setState` that's occuring will be the saved classification, but I'll try and investigate a bit more in the new year.

**Comment by srallen** [comment]
Not sure if this is still an issue, but we've doing lots of refactoring and updating since last year.
