### ISSUE TITLE
Zooniverse.org doesn't display content on Safari in Private browsing

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#2058]
Issue:
* Accessing zooniverse.org in Safari in Private browsing on OSX causes the content to fail to load.
* Header and footer show, but main content is blank.
* User can Sign In normally, after which the website works more-or-less normally.

Analysis:
* When attempting to load zooniverse.org in Safari in Private browsing (and not logged in), the following error is logged on the console: `QuotaExceedError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota`
* Ostensibly, this is because Safari in Private browsing lacks access to the `localStorage` feature, even though it's available in the global namespace. More details: http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an

Notes:
* Tested on Safari 9 on OSX

**Comment by brian-c** [comment]
Looks like some calls to `sessionStorage.setItem` in the [session module](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/lib/session.coffee) are causing this.

Can anyone (@camtell me why we need to pull in the whole `crypto` module to hash a random number?

**Comment by brian-c** [comment]
Looks like some calls to `sessionStorage.setItem` in the [session module](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/lib/session.coffee) are causing this.

Can anyone (@camallen, @marten) tell me why we need to pull in the whole `crypto` module to hash a random number with the date? Does this need to be a special format?

**Comment by camallen** [comment]
@brian-c i think we can get away with a non-cyrptographic hash here but we will need to avoid collisions so this property can be used independent of another prop (e.g. login) to id the browser session in data exports, etc so `Math.random` won't cut it. Any standard JS for MD5 / SHA* hashes that will be in all our supported platforms?

**Comment by eatyourgreens** [comment]
I think there's a JavaScript implementation of SHA1 in
https://github.com/zooniverse/Diaries/blob/master/app/lib/oauth.js if
that's of any use?

On Monday, 28 December 2015, Campbell Allen <notifications@github.com>
wrote:

> @brian-c <https://github.com/brian-c> i think we can get away with a
> non-cyrptographic hash here but we will need to avoid collisions so this
> property can be used independent of another prop (e.g. login) to id the
> browser session in data exports, etc so Math.random won't cut it. Any
> standard JS for MD5 / SHA* hashes that will be in all our supported
> platforms?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes-Front-End/issues/2058#issuecomment-167641176>
> .
>


-- 
--
James O'Donnell
email: jim@zooniverse.org
mobile: 07811 771 352
twitter: @pekingspring

**Comment by camallen** [comment]
@eatyourgreens yep thanks, that `binb2hex` function looks similar to what we're currently doing but with a different hash alg. Also, is that code being used in the app?

**Comment by eatyourgreens** [comment]
@camallen yep, war diaries uses it to sign some Yahoo API calls in order to
get around rate-limiting on their anonymous endpoint.

On Tuesday, 29 December 2015, Campbell Allen <notifications@github.com>
wrote:

> @eatyourgreens <https://github.com/eatyourgreens> yep thanks, that
> binb2hex function looks similar to what we're currently doing but with a
> different hash alg. Also, is that code being used in the app?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zooniverse/Panoptes-Front-End/issues/2058#issuecomment-167769616>
> .
>


-- 
--
James O'Donnell
email: jim@zooniverse.org
mobile: 07811 771 352
twitter: @pekingspring
