### ISSUE TITLE
When you click on the hashtag on a subject notes thread it doesn't search for the hashtag it does a text string search

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2065]
For example on this post https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/29/24752?page=1&scrollToLastComment=true

if I click on the pancakesindepressions hashtag it takes me to 

https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/search?query=pancakesindepressions

instead of returning the subjects back marked with the same hashtag (https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/pancakesindepressions) 

This used to work before. I'm not sure when it changed

**Comment by alexbfree** [comment]
duplicated by #2104
