### ISSUE TITLE
Cellect is unavailable :(

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#207]
![image](https://cloud.githubusercontent.com/assets/6482891/7248734/125c73c4-e80d-11e4-9e08-8a84eafde2f1.png)

**Comment by camallen** [comment]
Not sure why Cellect keeps dying, i'll investigate.

**Comment by camallen** [comment]
Seems cellect couldn't get any more DB connections and is most likely related to this issue, https://github.com/zooniverse/cellect_panoptes/issues/24.

Closing for now as we're trying out a different solution [here](https://github.com/zooniverse/Panoptes/pull/747)
