### ISSUE TITLE
disable "apply for review" when projects are fully launched to zoo home

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2074]
Just noticed that project owners on launched projects sometimes hit "apply for review" even though their project is live because the button isn't grayed out, whereas the "apply for launch" is grayed out.

This doesn't make much sense!

<img width="1280" alt="screen shot 2016-01-05 at 06 43 39" src="https://cloud.githubusercontent.com/assets/6217406/12109203/d15210c8-b377-11e5-924e-7dc091566384.png">

**Comment by mschwamb** [comment]
I can check all the 3 boxes in P4: Terrains and it would allow me to hit the  Apply for Review button even though the project is launch approved
