### ISSUE TITLE
Add tool that allows project owners to create subject sets out of already uploaded subjects

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2075]
As per discussions with @camallen, we could create a one-off script for this to launch "round 2" of Snapshots at Sea, but this will be needed repeatedly for any sort of collaborative filtering style project.

In Snapshots at Sea, for example, we are aggregating data from the first workflow to decide which images have animals in them and thus need to be fed into the second workflow. Thus we need to create a new subject set out of _already_ uploaded subjects. I think the ideal way to do this would be to upload a csv that provides the Zooniverse Subject IDs to create a new subject set from.

@brian-c @camallen are there two parts to this? a backend script to create the subject set out of the csv and a front-end button that allows the uploading of the csv?

**Comment by camallen** [comment]
this can just use the subject ids -> subject set links like the uploader already does [here](https://github.com/zooniverse/Panoptes-Front-End/blob/fe34696a172a663b8ce52f63867b1f201722169b/app/partials/subject-uploader.cjsx#L94). 

We could do a csv with SubjectSetID : SubjectID to allow multiple assignment in 1 upload. I haven't fully load tested this end point but it's pretty fast, that said linking thousands of subjects will take some time...so there should probably be some best practice docs around this (like we do for batching subject uploads).

**Comment by alexbfree** [comment]
I like this idea. A good model for this would be the Wordpress Media Uploader: 
https://mikejolley.files.wordpress.com/2015/07/screen-shot-2012-12-21-at-07-35-09.png
https://lorelle.files.wordpress.com/2012/12/new_media_uploader_selecting_images_across_posts_for_gallery.png

**Comment by CKrawczyk** [comment]
+1 for making this a UI feature.  The project I am working on with Karen would be much easier if we could upload all the images at once and make the various subjects sets as needed.

**Comment by simoneduca** [comment]
@aliburchard isn't this exactly what we also need for WGE, i.e. allowing teachers to create subsets?

**Comment by alexbfree** [comment]
A further advantage of using the media library model, like wordpress, is that this could be a good candidate to be a standalone UI component under the new https://github.com/zooniverse-ui

**Comment by chrislintott** [comment]
+1 from me too, especially if they could do so from publicly available subject sets they don’t necessarily own

**Comment by aliburchard** [comment]
+1 and yup @simoneduca this would feed directly into the educator portal subject set/assignments...

**Comment by mschwamb** [comment]
Adding a use case to this. We're using clones of the main P4: T workflow for P4:T gold standard data review. Currently a dev has had to create the  gold standard subject set from the previously uploaded images for us. It would be really nice if I could upload a csv file with the subject ids into a subject set linked to the gold standard workflow

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
