### ISSUE TITLE
issues with new vertical sorting

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2085]
@amyrebecca @brian-c looks like vertical sorting went into effect for all projects using the original camera survey task (in response to #2024), but there seem to be some issues with distributing species among the columns (whatever code determines the appropriate #choices per column seems to be wonky):

see: 
https://www.zooniverse.org/projects/aliburchard/camera-catalogue/classify
https://www.zooniverse.org/projects/aliburchard/emammal/classify

and more, but can't actually get on Zooniverse just now.

In the camera-catalogue project, for example, instead of the list running off the page, you have to scroll right to see the other choices, which I wouldn't have guessed.

**Comment by brian-c** [comment]
Not sure how you ended up doing this @amyrebecca. Seems like there should be a way to do it with flexbox, but if you end up needing to manually re-sort the items here's the function that does it in Serengeti:

https://github.com/zooniverse/Serengeti/blob/master/app/lib/columnize.coffee

**Comment by amyrebecca** [comment]
I was able to use flexbox for this! The only problem with the flexbox implementation is a browser bug where i can't use max-height properly and have to set height instead.

The fact that it's affecting the regular survey task is just my mistake and I've already merged a PR for it. In general we'll have to talk about really really long lists of options and how they should scroll. There's not really a good way to handle that and also provide columns. Given the option, flexbox will just make a reallllllly long single-column list, so you have to restrict the height; and once the height is restricted, you're stuck scrolling to the right to get options that don't fit.

**Comment by aliburchard** [comment]
following up as per our chat the other day. Is it possible (perhaps using the code Brian suggested above) to create your own function to bypass the flexbox bug? If you write a function that counts the # of choices and distributes those choices evenly across three columns and calculates the #choices per column? Then you just hand that number back to flexbox.

**Comment by aliburchard** [comment]
Just thinking more about this -- wondering if @brian-c has any insights into possible workarounds for this?

**Comment by brian-c** [comment]
I messed around with some flexbox today and it seems like the only way to force a certain number of columns is to divide the number of items and try to calculate a height manually, which sorta defeats the point. I'd probably just go with the function to reorder the items.

**Comment by aliburchard** [comment]
Yay!!!!!!! thanks @amyrebecca and @brian-c !!
