### ISSUE TITLE
Project classify page calling the same resources multiple times

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#2090]
Project classify page calls workflows twice, once for active and other for not. Is this required?

<img width="730" alt="screen shot 2016-01-09 at 19 29 55" src="https://cloud.githubusercontent.com/assets/295329/12217945/e0494586-b707-11e5-9127-906668979c8e.png">
Note the image has the preflight OPTIONS and the GET so it's listed as 4 times.

**Comment by camallen** [comment]
So i've done a bit more debugging and it looks like the workflow calls above are due to the way we fetch a specified workflow (if a query param, ignoring active flags) OR we fetch a random active one. We could just do one of the other in this case, not both as it currently does. 

Also i've found the classify page is behaving somewhat strangely that is causing the same API request to be fired multiple times. It seems that it tries to render the summary page on classification start (i.e. no annotations on the first task), which fires the user roles and gold_standard promises. It then renders all the tasks (not just the active one) which again fires the user roles promise, this repeats for each progression through the interface. Finally on summary it renders the summary page which calls user_roles and gold_standard again. All this is resulting in multiple duplicated queries to the API that could have been stored state at the start or at least cached at the API client layer.

Thoughts?

**Comment by simoneduca** [comment]
@camallen Not sure I can reproduce. Did it happen on submitting a classification (pressing 'Next')?

**Comment by camallen** [comment]
PM'ing you a logging patch

**Comment by simoneduca** [comment]
This is a screenshot showing Cam's description above (2nd paragraph)

![screen shot 2016-01-11 at 12 19 11](https://cloud.githubusercontent.com/assets/8989606/12233269/b82bdf94-b85d-11e5-81eb-04a556f0fc73.png)

**Comment by camallen** [comment]
closed by #2096
