### ISSUE TITLE
Expert feedback is too subtle

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#2093]
The difference between the user view

![screen shot 2016-01-11 at 10 53 12](https://cloud.githubusercontent.com/assets/8989606/12231750/b1f3abd6-b851-11e5-9897-2e9fbf6c6a31.png)

and the expert feedback view is pretty subtle.

![screen shot 2016-01-11 at 10 53 20](https://cloud.githubusercontent.com/assets/8989606/12231853/545d41ca-b852-11e5-99dd-2552800f1afe.png)

This may prevent users from making the most of this feature.

**Comment by aliburchard** [comment]
Can I say that the "Keep at it, all classifications are useful!" makes me think I've gotten it wrong no matter what? (Or does it say something different if you get it right?)

Also, with the above feedback, it's not clear what the comparison is between mine and the experts, as they aren't displayed simultaneously.

**Comment by CKrawczyk** [comment]
@aliburchard the text does change depending on if you agreed with the expert.  Also I agree with @simoneduca the change is very subtle and hard to pick out.  Might be nice to add two columns inside the summary showing "what I said" and "what the expert said."

**Comment by simoneduca** [comment]
@aliburchard in the screenshot above, user and expert disagreed. If they agreed, the text would have been 'Keep up the good work!'.
@CKrawczyk I agree, that sounds good. I'll have a go at that :)

**Comment by brian-c** [comment]
Please don't mess with this before Stargazing is over. I'm overriding it in the hardcode-stargazing-feedback branch.

**Comment by simoneduca** [comment]
Sorry I missed that branch! Sure no problem.

**Comment by aliburchard** [comment]
@brian-c that makes sense, thanks :)

**Comment by srallen** [comment]
We're moving to a more generalized feedback using metadata, so styling should be addressed with that feature.
