### ISSUE TITLE
viewing subject info in project builder should show hidden values

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2095]
When viewing subjects and info in the project builder, if I'm a collaborator, I'd like to be able to see the _full_ set of values, with the ones that will be hidden from public view marked in some way.

This just came up because I thought some essential columns were missing from a gold-standard dataset in the pulsar SGL project, but in fact the project builder is just showing what the classifiers will, so the only way I can see all the columns is to download the subject export. (I don't have the original manifest because I'm a collaborator, not the project owner.)

**Comment by chrislintott** [comment]
If we do this, it should be obvious which are hidden. Otherwise it won’t be clear to project builders what their audience will see.

**Comment by vrooje** [comment]
This still hasn't been addressed, right? And it's important enough that I'd like to keep this open.

**Comment by CKrawczyk** [comment]
This came up again during the GZ move to Panoptes, keeping this open.
