### ISSUE TITLE
Slide tutorial: close button is inaccessible on small screens

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#2100]
When the viewport height is smaller than the height of the slide tutorial form element, the close button can get positioned above the top of the page, and can't be reached by scrolling upwards.

Also: why is the slide tutorial using a form? It doesn't contain any form input elements or submit any data.

**Comment by alexbfree** [comment]
I noticed a similar issue on iPhone 4 / iOS 9.2 - The close button and part of the tutorial window is off the right hand side of the screen and can't be reached.

**Comment by srallen** [comment]
Fixed in #2303
