### ISSUE TITLE
Links on hashtags in talk are not quite right

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2104]
I noticed in Pulsar Hunters that the automatically-generated links on a hashtag such as #candidate in people's posts look like this:
https://www.zooniverse.org/projects/zooniverse/pulsar-hunters/talk/search?query=candidate
when they should look like this
https://www.zooniverse.org/projects/zooniverse/pulsar-hunters/talk/tags/candidate
as in the Popular Tags sidebar
(otherwise you end up including posts that contain the word "candidate" not solely the hashtag "#candidate")
should be a quick fix but just logging it for now.

**Comment by mschwamb** [comment]
already open as
#2065 
#2066

**Comment by alexbfree** [comment]
same as #2065. #2066 is slightly different.

**Comment by mschwamb** [comment]
@amyrebecca is this fix live?  I'm currently  still getting the same wrong behavior?

**Comment by mschwamb** [comment]
This isn't fixed so I'm reopening. It a feature I use on a frequent enough basis on Talk, and many advanced users on Talk use.

For example if I click on #crater on the second post from the top  in https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/29/2694?comment=6033&page=1

it performs a text search (https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/search?query=crater) and the not the desired  tag search (https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/crater)

**Comment by srallen** [comment]
@amyrebecca, I believe [zooniverse-ui/markdownz](https://github.com/zooniverse-ui/markdownz) still needs a version bump on npm so the fix can show up in PFE.

**Comment by mschwamb** [comment]
It's still triggering the text search and not the hashtag search for me.

**Comment by mschwamb** [comment]
Is there any chance someone could fix this in the coming week? It's been broken for 2 months now. I use this feature pretty frequently.

**Comment by srallen** [comment]
@amyrebecca could you version bump the markdownz package on npm? I see that @aweiksnar has added you and @mcbouslog as collaborators so either of you should be able to do that.

**Comment by mschwamb** [comment]
@parrish is this something you might be able to help with? This has been going on since December that when you click on a hashtag on any of the Talk comments it takes you to the text search and not the tag search.

**Comment by parrish** [comment]
Yeah.  zooniverse-ui/markdownz#30 should probably fix this, but it was never released.

Apparently @amyrebecca and @mcbouslog are the only two current team members with [permissions](https://www.npmjs.com/package/markdownz/access) to publish that package.

Mind bumping the version, releasing it, and setting a minimum version to match in the [package.json](https://github.com/zooniverse/Panoptes-Front-End/blob/master/package.json)

**Comment by mschwamb** [comment]
@mcbouslog and @amyrebecca can you publish the package or can someone enable permissions for someone with time to bump this? This is in my opinion a fairly significant functionality in Talk that's been missing for three months, and that's why I'm pestering about this. Thanks.

**Comment by chrislintott** [comment]
Should now be sorted.

**Comment by alexbfree** [comment]
(once https://github.com/zooniverse-ui/markdownz/pull/31 is merged & deployed, right?)

**Comment by brian-c** [comment]
The relevant PR was zooniverse-ui/markdownz#30, published today as v4.0.3. Will be updated automatically with the next PFE deploy.

**Comment by eatyourgreens** [comment]
I just kicked off a manual deploy from Jenkins but I think it's still using v4.0.2.

**Comment by mschwamb** [comment]
Thanks!
