### ISSUE TITLE
When we show "already seen" banner we should also offer a "skip" button

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2108]
It seems silly that to see the next subject, users have to go through the whole workflow (or force reload the page, but only power users will realise that). Not only is it inconvenient to the user, that means we collect multiple classifications from the same user for the same image, which could distort results in sorts of ways.

**Comment by mschwamb** [comment]
I don't think we should  have  a skip button. if you get an already seen, it means you're done with the data (minus the current bug on the backend that might be fixed now). I think there should be a more apparent banner that you're done with the project here's somethings you can do (go to Talk, join this project that needs help, etc). 

If you want to peruse the data, talk is just as good as a skip button, and that's where I direct super users who have finished classifying the current live set of data.

**Comment by aliburchard** [comment]
I also don't think we should have a skip button. If the queueing is working properly, you should only be getting "already seen" images if you've gone through every single unretired image, so there's no real point in going through the workflow to get to the next image. However, I do think we should take repeat classifications into consideration in the data out. We can track them based on the user ID and timestamp; maybe marking them as 'already seen' in the raw classification data to make it easier for researchers to exclude, and then excluding them from the aggregations as well (@ggdhines?)

**Comment by mschwamb** [comment]
I'm pretty sure the backend does flag repeat classification in the raw output already. Is that correct @camallen ?

**Comment by camallen** [comment]
yep - we record that any "duplicates" (i.e. we know they have seen them before) will be marked as such, [code here](https://github.com/zooniverse/Panoptes/blob/b81d2dbfa423d4c9020717ff879e435ec3e29be5/lib/classification_lifecycle.rb#L127).

**Comment by chrislintott** [comment]
Closing as won't fix for now.
