### ISSUE TITLE
Connection of questions

### ISSUE THREAD

**Issue by AlexLoosIDMT** [zooniverse/Panoptes-Front-End#2117]
It should be possible to "connect" questions. E.g.: 1st question: "How many objects do you see?" => 2nd question: "Mark all objects with a rectangle" => These two questions should be connected.    Maximum allowed number of rectangles should be the answer of question 1.

**Comment by chrislintott** [comment]
@brian-c Something to consider if you’re fiddling with the code to allow min/max setting.

**Comment by brian-c** [comment]
Min and max are in place.

For one task to know about the answer given by the user in another task's annotation would require some arbitrary logic, which we are in no position to support right now.
