### ISSUE TITLE
toggling "Private project" off and then on does not remove it from the "Projects" page

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#212]
As expected, when I make a project "public" it gets added to the "projects" page and I can access the API without an authorization token. When I make the same project "private" again it stays on the "projects" page, although the API needs the authorization token as expected.  I expect the project should also be removed from the "projects" page if it is made private by the owner.

**Comment by camallen** [comment]
Hi Coleman, are you still logged in when this happens? A user can access all "public" projects as well as "owned" projects on this page when logged in.

**Comment by CKrawczyk** [comment]
Oh yeah, it only happens when I am logged in.  Thanks for the clarification.
