### ISSUE TITLE
Make the whole annotation pipeline more efficient

### ISSUE THREAD

**Issue by AlexLoosIDMT** [zooniverse/Panoptes-Front-End#2120]
The whole workflow should be more efficient. After one task is fulfilled, the next task should pop up immediately without having to press "next" (but one should be able to go back to the previous task to redo or refine the annotation, though). Often too many clicks are required in order to annotate an image. I think the user experience would be better if, for instance, after a face was marked with a rectangle the next task (e.g."Mark the left eye") pops up automatically without having to press "Next" all the time.

**Comment by aliburchard** [comment]
How would this work when 1) there are multiple annotations possible on an image and 2) the user makes a mistake in drawing and needs to delete an annotation?

**Comment by AlexLoosIDMT** [comment]
Imagine the task is to mark all faces as well as facial features (eyes, mouth) within an image. An efficient annotation pipeline would be as follows:

Click "new face" and draw rectangle. Then it's required to annotate both eyes and the mouth. This could be done without having to press any buttons because it's mandatory. These objects (face and facial markers) are "connected" (See issue #2119 ). Thus by selecting a face it can be moved and the marker points are moved accordingly (since those points are connected to the face rectangle). Of course a face and according facial feature points can also be deleted. Then, click "next face" if there are any more faces.

**Comment by srallen** [comment]
Generalizing this will be difficult and I think we'd need more clear examples and use cases to be able to implement features.
