### ISSUE TITLE
Allow text-fields for answers

### ISSUE THREAD

**Issue by AlexLoosIDMT** [zooniverse/Panoptes-Front-End#2121]
Maybe it would be helpful not only to have multiple-choice answers but also text-fields. For example if the task is to annotate the name of a previously detected individual, it might be tedious to selet 1 out ouf 1000 individuals. A text-field (possibly with additional search suggestions) would be much more convenient.

**Comment by CKrawczyk** [comment]
A text-field task is already in the works and is being tested out.  It will become available for use once it is ready.

**Comment by srallen** [comment]
Text field task is done.
