### ISSUE TITLE
Add zooming functionality

### ISSUE THREAD

**Issue by AlexLoosIDMT** [zooniverse/Panoptes-Front-End#2122]
It might be good to add a zooming-function since sometimes objects might be too small to draw a rectangle around them.

**Comment by CKrawczyk** [comment]
A crop/zoom tool is also in the works and be tested out.

**Comment by chrislintott** [comment]
In general though, it’s a bad idea to allow zooming. If your subjects require inspection on that scale, unless the context is needed, we recommend you chop large images into many smaller ones each at the required resolution for the task. This allows you to be sure each user has seen the same image.

**Comment by srallen** [comment]
Pan and zoom is an experimental feature.
