### ISSUE TITLE
bug: coordinates outside of image frame

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#2125]
We're going through the first tranche of Fossilfinder data and we perplexed to see coordinates for use of the point tool falling outside of the image. At first we thought that it could be something to do with image size as seen but quickly realised that negative numbers wouldn't make sense at all. And we also thought that perhaps users could click and mark areas of the webpage outside of the image area. It seems to be neither of those things.

A user can click a point on the image with the drawing point tool, where it will drop the marker. But then they can drag this marker outside of the image field. It disappears but on completion the summary page shows that this marker is still registers and when you click on more it shows the coordinates to be outside of the frame. This is not uncommon - we have a few thousand examples in our database.

Could a check be put in place to ensure that markers outside of the coordinate system of an image are discarded? Presumably users are dragging the markers off the image when they have changed their mind in these cases, rather than clicking on the x to delete the marker.

**Comment by aliburchard** [comment]
@brian-c is this a quick fix? It's possible to find these post-hoc with sophisticated analysis, but not ideal. I'd much rather prevent the creation of points off the subject.

**Comment by AdrianEvans** [comment]
<img width="1031" alt="click_coords" src="https://cloud.githubusercontent.com/assets/10448680/12819757/3b5cb740-cb54-11e5-81a7-31f8eb95a05d.png">

Image shows accumulated clicks by coordinate to show the nature of the problem

**Comment by aliburchard** [comment]
@brian-c can we add this to the "easy" to-do list? Or, if it's not an easy fix, is this something that anyone else might need to address @itsravenous @saschaishikawa @eatyourgreens @simensta in any of your marking projects?

**Comment by brian-c** [comment]
This is probably an easy fix for the point tool, but it'll be way harder for the rest of them. I'd really love to know why people are dragging marks off the image instead of using the delete button. That's completely bizarre to me.

**Comment by aliburchard** [comment]
We think it's to "cancel" or "escape" from the marking tool (instead of finishing it and hitting the little "x" to delete it)

**Comment by chrislintott** [comment]
Rather than fix this on the tool, could we tell aggregation to ignore these points?

C

**Comment by AdrianEvans** [comment]
There's no doubt that this is an easy fix in the way of either automatically removing them in your aggregation or even in pre-processing at our end. HOWEVER, we should consider the user experience. 

Take the below for example - dragged of the side and the user can not retrieve or cancel the point and the back button is obscured - forcing a random assignment and a confirmation.

For us this also means a waisted retirement.
 

<img width="1026" alt="zoo-click-issue" src="https://cloud.githubusercontent.com/assets/10448680/13348977/e6c40dd8-dc87-11e5-9483-e991f449abd2.png">

p.s. we're currently out in Kenya picking some of the stuff up that the users have found. We've started putting daily updates on youtube.

https://www.youtube.com/watch?v=0KLDvk1v4jA

**Comment by camallen** [comment]
@AdrianEvans the volunteers would love to see those videos, are you posting them to talk / the blog?

**Comment by AdrianEvans** [comment]
@camallen yes we are! - it would be cool too if there were somewhere wider where you guys could help distribute - zoo blog or something

**Comment by camallen** [comment]
pinging @mrniaboc

**Comment by CKrawczyk** [comment]
@chrislintott the only issue I see with cutting these points at aggregation is now a project can place a min and max limit on the type of each drawing tool.  This means users could be in the situation where all the points they have drawn are off screen, they have hit the max limit for that type of tool, and have no way to remove the points they have drawn.

**Comment by brian-c** [comment]
I just realized: this should actually be a pretty straightforward thing to solve for all tools, if we only look at their bounding boxes.

It wouldn't be a perfect solution (e.g. the corner of a circle's bounding box might be over the subject even when the circle itself is not) but I bet it'd be good enough for these cases.

And then maybe the first time a user a drags a shape off the subject, we could pop up a little "Hey, use the delete button!" warning.

**Comment by aliburchard** [comment]
Especially if a pretty good solution is easy to implement, I think it's worth stopping people from making "off image" markings instead of relying on cleaning up in aggregation (especially with the points coleman raises).

**Comment by chrislintott** [comment]
I like these ideas @brian-c

C
