### ISSUE TITLE
Dropdown/selection task

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2128]
Create dropdown/selection task for PFE.
@brian-c, @simensta

**Comment by mcbouslog** [comment]
hey guys, i've got an update on the dropdown task:

-the answers/dropdowns are now an array of objects (changed from object of objects)
-annotation.value is also now an array of strings (i think the simplest form possible, changed from object of objects, more similar to other tasks)
-the task has been renamed to dropdown
-the editor has been reworked, and Jordan is currently reviewing as well for possible improvements/rewording

if possible we'd love to show the Notes for Nature (NfN) team the dropdown and multiple texts tasks by Friday (even though the multi-text task will be replaced with combo task), so i'm thinking i could deploy to preview the dropdown and multi-text task branches combined into a new branch? but please let me know if there's a better way to demo experimental tasks before they're ready for prime-time (even as experimental tasks).

open issues i still need to address or pass on, but not worrying about for demo to NfN team:
-update headings to turn green/red as properly saved to api
-if same dropdown/option entered with different capitalization duplicate entry error/message not thrown
-consider required attribute on dropdown by dropdown basis
-test edge cases, general review and refactor

**Comment by brian-c** [comment]
- The annotation's value should actually be an array of each selected option's index to be consistent with the other tasks.

- `answersOrder` isn't relevant, since those are an array now.

- "Answers" isn't really the right term here. "Menus" maybe?

Now that we (almost) have a combo task, any thoughts on just making "Dropdown menu" a rendering option of the `single`-type task, and then grouping a set of those with the combo task? Are we making more work for ourselves by having two tasks with nearly identical output?

**Comment by mcbouslog** [comment]
Hey guys, quick update:

(TLDR - I'd like to do some bigger refactoring of the dropdown task, stay tuned for updates)

-Brian - great notes, thanks! I've implemented all except renaming 'answers' to 'menus' simply out of procrastination, but completely agree
-combo task - also completely agree on this, which gets to...

Major Refactoring - after actually trying to build and use this dropdown task for a demo earlier this week, I realized there are a few issues and the actual use of the task may be very different than I was originally thinking. Here are a few notes I plan to incorporate into a bigger refactoring of the task:

1. pre-populated common dropdown options, i.e. Months, Countries, States, Counties
2. conditional dropdowns - if USA is selected, a States/Province dropdown would only have US states as options
3. refactor in light of combo task - reorder not necessary, if not conditional dropdowns only allow one dropdown (a subsequent dropdown can be added to the single view via the combo task)

Those are just the bigger notes off the top of my head, but other issues may arise as I work on those noted above. No action/feedback necessary from you at the moment, just wanted to let you know where things are at.

**Comment by mcbouslog** [comment]
finally! an update on the new and improved dropdown task (currently branch [select-task](https://github.com/mcbouslog/Panoptes-Front-End/tree/select-task) on my forked PFE). Although the branch will be updated more frequently, a relatively updated deployed-preview-branch is [https://preview.zooniverse.org/panoptes-front-end/select-task/](https://preview.zooniverse.org/panoptes-front-end/select-task):

Notes:
- I've purposefully made the value and label the same (for now, subject to discussion), presuming we want annotations to be a pure as possible. However, there's a valid argument to be made if someone's using this dropdown task they may prefer convenience and functionality (i.e. value of 2 for label February) over pure transcription. Ideally, the task would handle either cases.
- My React keys are all sorts of crazy. I'm missing the underlying concept; explanation (or good reference to) and key suggestions welcomed/encouraged!

Remaining To Dos:
- [ ] Preset conditional answer (i.e. if adding States, need to know what country)
- [ ] Complete preset options (Countries, States [US, Mexico, Canada at minimum], Counties [US]
- [ ] Indent list of dropdowns based on conditionality
- [ ] Handle options as value/label objects

**Comment by brian-c** [comment]
I think this task should be more flexible. If we're going to allow menus to depend on each other, we should take go all the way and not have a fixed set of menus at the start. That'll also keep us from having to lump things together like "State/province", which is fine in that context but might not make sense in the future.

Can I suggest something like:

- The task has an array of `menus`.
- Each menu has a `label` and many `options`.
- Each menu may have a boolean `required`, forcing the user to pick something before their annotation is considered complete.
- Each menu may have a boolean `allow_other`, allowing the user to enter a value not in the array of options.
- Each option has a `label`, and optionally has an array of `menus` (ad infinitum).

```js
var exampleTask = {
  type: 'menus',
  menus: [{
    label: 'Country',
    required: true,
    options: [{
      label: 'Canada'
      menus: [{
        label: 'Province'
        options: [{
          label: 'British Columbia'
        }, {
          label: 'Nova Scotia'
        }]
      }]
    }, {
      label: 'USA',
      menus: [{
        label: 'State',
        options [{
          label: 'Washington'
        }, {
          label: 'Maine'
        }]
      }]
    }]
  }, {
    label: 'Snack',
    allow_other: true,
    options: [{
      label: 'Poutine'
    }, {
      label: 'Chips',
      menus: [{
        label: 'Potato'
      }, {
        label: 'Corn'
      }]
    }]
  }]
};
```

The annotation should only reference the human-readable strings from the task, not duplicate them. That keeps the task as the single source of truth for rendering its UI and the annotation as the source of truth for its state. It also keeps the annotations lean (there'll be way more annotations than tasks).

So what if:

- The annotation's `value` is an array.
- Each item in the value corresponds to a root-level item in the task's `menus`.
- Each item in the value has an `option`.
- The option is `null` if the user did not choose anything from the corresponding menu.
- If the option is a number, it is the index of the selected option in the corresponding menu.
- If the option is a string, it is the text the user entered (the task has `allow_other` set).

```js
var exampleAnnotation: {
  value: [{
    option: 0, // Canada
    menus: [{
      option: 1 // Nova Scotia
    }]
  }, {
    option: 'Something else' // Because `allow_other` is set
  }]
};
```

**Comment by eatyourgreens** [comment]
Would it make sense to seperate label from value for each option too? In case we ever support translation of the labels in future.

**Comment by mcbouslog** [comment]
the following is some additional background info and clarification on the task. this will hopefully help guide us in how the task is structured.

the purpose of the dropdown task is to have a volunteer select an annotation from a set of researcher pre-defined options. optionally, but likely often, a researcher can allow a volunteer to enter/create an annotation if it is not included in the pre-defined options (or there aren't options). additional conditional dropdowns can be created as needed. the benefits of a dropdown task include (but aren't limited to) convenience/ease-of-use for volunteers and streamlining annotation quality.

examples of the dropdown task usage would be:
- Mapping Historic Skies - dropdown of planets to select from
- Notes from Nature - select country, state and county noted on specimen label

structuring the original/root dropdown is fairly straightforward, something along the lines of:
```
type: 'dropdown'
instruction: "Select something..."
selects: [{
  title: "Planet"
  options: [
    {value: 'Mercury', label: 'Mercury'}, 
    {value: 'Venus', label: 'Venus'}, 
    {value: 'Earth', label: 'Earth'}
  ]
}]
```
things get fun with conditional dropdowns. the scenario may be, like with Notes from Nature specimens, that we'd want to collect country, state and county if possible. we know most of our subjects are from the US and Mexico, which we'll populate the related state and some of county options for, however, there may be specimens from other countries, in which case we'd still want volunteers to annotate state and county, though we won't be providing pre-defined options.

so our root dropdown is country, with a conditional dropdown of state, which has a conditional dropdown of county. regardless of what we provide pre-defined options for, we'll want volunteers to see and annotate (including if nothing present) all three attributes. here's a tree for this conditionally related set of dropdowns (with a few layers added for extra fun):

- country
  - state
    - county
    - city
      - street

so with the Planets dropdown task above as a starting reference, i think the cleanest way to structure a conditionally related `selects` property is as follows (imagine the options as objects with value and label keys):
```
selects: [
        {
          title: "Country"
          options: ['USA', 'Canada', 'Mexico']
        },
        {
          title: "State"
          allowCreate: true
          condition: 0
          options: {
            0: {
              0: ['Hawaii', 'Idaho', 'Illinois'],
              2: ['Durango','Hidalgo']
            }
          }
        },
        {
          title: "County"
          allowCreate: true
          condition: 1
          options: {
            0: {
              0: ['Kalau', 'Maui'],
              2: ['Cook', 'Lake', 'Will']
            },
            2: {
              0: ['DurCount1', 'DurCount2'],
              1: ['HidCount1', 'HidCount2', 'HidCount3']
            }
          }
        },
        {
          title: "City"
          allowCreate: true
          condition: 1
          options: {
            0: {
              2: ['Chicago', 'Springfield'],
              1: ['Boise', 'Idaho Falls'],
              0: ['Honolulu', 'Kailua']
            }
          }
        },
        {
          title: "Street"
          allowCreate: true
          condition: 3
          options: {
            2: {
              0: ['Lake Shore Drive', 'Wacker Drive'],
              1: ['Springfield Avenue]
            },
            0: {
              0: ['Cool Honolulu Road'],
              1: ['Sweet Kailua Street', 'Other Kailua Street']
            }
          }
        }
      ]
```
while the root options are straight-forward, a conditional select options property is an object with parent conditional answer index keys whose values are conditional answer index keys, which finally will be tied to values that are an array of this select's options. it's the easiest way i found to tackle the multiple conditions that determine what a nested dropdown's options should be, but i'm not sure optimal solution.

the annotation.value would be an array, with indexes if a pre-defined option is selected, or string if answer was added by volunteer (due to not an option or no options). so based on my example above, a specimen from Nice Boise Street, Boise, Idaho would have the annotation.value of:
```
[0, 1, 'Ada County', 0, 'Nice Boise Street']
```

@brian-c - as we discussed in Slack rgd your suggested structure, there might be an issue when you have say 100 countries and only 3 have pre-defined states; the remaining 97 would still need an empty `State` menu, and i'm not sure how we'd nest County, City or Street for countries without pre-defined states (or counties or streets)?

if a researcher wants to have multiple NOT conditional dropdowns in one task/view (year-month-day*), the combo task should be used, not a single dropdown task (*yes i know days are conditional on month, but for simplicity/example sake i'm ignoring that).

yikes this is long, thanks for reading!!!

**Comment by brian-c** [comment]
Alright, I get the idea behind this now. I think I'm still a bit confused about the relationship between `condition` and `options`. The third select ("County") has the condition `1`, so it'll only be available after a state is chosen. Then its options have a path like `0.0[0]`, mapping to USA/Hawaii/Kalau. But the fifth select ("Street") has the condition `3` ("City"), and its `0` option implies Hawaii and that option's `0` array implies Honolulu. So is each select's "root" option based on the value of the select two conditions up? (Does that question make sense?)

**Comment by mcbouslog** [comment]
yes great question. and i think the answer is yes - each select's options root key depends on the answer/option index two levels up. i've noted what the Street options keys/indexes refer to in parentheses as follows:
```
options: {
            2 (Illinois): {
              0 (Chicago): ['Lake Shore Drive', 'Wacker Drive'],
              1 (Springfield): ['Springfield Avenue]
            },
            0 (Hawaii): {
              0 (Honolulu): ['Cool Honolulu Road'],
              1 (Kailua): ['Sweet Kailua Street', 'Other Kailua Street']
            }
          }
```
thank goodness for React state, it made it easy to walk up and down the related conditional selects, given just the one level-up condition, so actual options are populated dynamically based on what's selected using the following code:
```
  getOptions: (i) ->
    {selects} = @props.task
    select = selects[i]

    ### original/first select scenario, no conditions to worry about...
    if select.options.length?
      return select.options

    ### conditional select scenario, conditions and possibly parent conditions to worry about...
    return select.options[@getCondParentAnswer(i)]?[@state.answerIndexes[select.condition]]

  getCondParentAnswer: (i) ->
    {selects} = @props.task

    if selects[selects[i].condition].condition?
      return @state.answerIndexes[selects[selects[i].condition].condition]

    ### if condition is the original/first select, there is no parent condition, but to keep conditional selects formatted similarly, will set root key as 0, but could be anything (i.e. 'first', 'blerg', 'baloney')...
    return 0
```

**Comment by brian-c** [comment]
In your big example above, how would I define options for streets in Mexico?

**Comment by mcbouslog** [comment]
good point, that'd be a problem with the current setup of options root keys as numeric indexes, as first a Mexican city for either state would need to be added, which would make the 'City' options:
```
options: {
            0: {
              2: ['Chicago', 'Springfield'],
              1: ['Boise', 'Idaho Falls'],
              0 (Hawaii): ['Honolulu', 'Kailua']
            },
            2 (Mexico): {
              0 (Durango): ['city1', 'city2'], 
              1 (Hidalgo): ['city3', 'city4']
            }
          }
```
and then a street option from Durango (via whichever city), would want the same Street options root key as Hawaii, which is obviously just one example of an general underlying issue.

originally, and maybe i should go back to it, i was defining conditional select's options' root keys as the related parent option/answer string, which while would fix this issue noted, doesn't necessarily mean this general structure is the best way to go.

**Comment by brian-c** [comment]
Here's something like yours but each set of options is keyed by a list of values starting at the first select and ending at the current `condition`. Is this sorta what you meant?

```js
{
  selects: [{
    label: 'Country',
    condition: null,
    options: {
      '*': ['Mexico', 'USA']
    }
  }, {
    label: 'State',
    condition: 0,
    allow_create: true,
    options: {
      '0': ['Durango', 'Hidalgo'],
      '1': ['Hawaii', 'Illinois']
    }
  }, {
    label: 'City',
    condition: 1,
    options: {
      '0;0': ['Durango City', 'Durangoville'],
      '0;1': ['Hidalgo City', 'Hidalgoville'],
      '1;0': ['Hawaii City', 'Hawaiiville'],
      '1;1': ['Illinois City', 'Illinoisville']
    }
  }, {
    label: 'Favorite bird',
    condition: 1
    options: {
      '0;0': ['Durangolian redbird'],
      '0;1': ['Hidalgonese bluebird'],
      '1;0': ['Hawaiian greenbird'],
      '1;1': ['Illinois vulture']
      '0;*': ['Mexican cool bird'] // State was added
      '1;*': ['The majestic bald eagle'] // State was added
    }
  }, {
    label: 'Street',
    condition: 2,
    options: {
      '1;1;0': ['Lake Shore Drive']
    }
  }]
}
```

**Comment by mcbouslog** [comment]
yes that's similar to what i was suggesting but i think even better. i'll run with that and post once i have an updated branch. thanks!

**Comment by mcbouslog** [comment]
the latest: (currently branch [select-task](https://github.com/mcbouslog/Panoptes-Front-End/tree/select-task) on my forked PFE). Although the branch will be updated more frequently, a relatively updated deployed-preview-branch is [https://preview.zooniverse.org/panoptes-front-end/select-task/](https://preview.zooniverse.org/panoptes-front-end/select-task):

this version includes:
- ability to handle options as array of strings or array of objects with value and label
- annotation.value is an array of options indexes or a string if created answer

items i'm still cleaning up or need review:
- see comments for TODOs
- React keys (currently inconsistent, best practice?)
- general code clean-up/refactor

items on hold:
- wiring CSV import to handle options of objects with value and label
- presets

i'll post this for now and revisit this afternoon...

**Comment by brian-c** [comment]
> ability to handle options as array of strings or array of objects with value and label

I think we should pick one right way to handle this. `{value, label}` is more flexible (especially in terms of reordering items), so I'd go with that. One downside: we have to get the `value` strings from somewhere, and I don't think it should be the scientist's responsibility to define it (I'm fond of `Math.random().toString(16).split('.')[1]` to generate reasonably unique random strings). It's also inconsistent with the rest of the tasks, but really probably better in the long run.

> annotation.value is an array of options indexes or a string if created answer

If we switch to using `{value, label}` pairs, the annotation will record the `value` of the selected option, so now we have no way of distinguishing selection of an existing option vs. typing something in. So maybe we'd store the list like `[{value: "xyz", option: true}, {value: "I typed this in.", option: false}]`?
