### ISSUE TITLE
Add multiple field support for text task

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2129]
Add multiple field support for text task.
@brian-c @simensta

**Comment by simensta** [comment]
Todos:
- [ ] change annotation.value to an array of objects
- [ ] updating ability to require answer on a text-box by text-box basis
- [ ] depreciating `/app/classifier/tasks/text/index.cjsx` (i.e. the text tool that renders a single text box) in favor of a single text tool that can render one or more text boxes.

**Comment by brian-c** [comment]
Before anybody gets too deep into this, I'm experimenting with building a combo-task like we talked about that'll allow ganging up any number of tasks into one. Seems to be working well, I'll keep you posted here.

**Comment by mcbouslog** [comment]
PR #2137 added combo task, which allows multiple single text tasks that can be displayed within one combo task, eliminating need for multiple field text task.
