### ISSUE TITLE
Add pan and zoom feature

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2130]
Add pan and zoom feature.
@brian-c @simensta

**Comment by mschwamb** [comment]
#2122 partly a duplicate

**Comment by simensta** [comment]
@brian-c, @eatyourgreens, @mcbouslog: 
There is now a [staging branch with Pan & Zoom](https://preview.zooniverse.org/panoptes-front-end/pan-zoom) functionality under the dev classifier. 

Operate Pan & Zoom via Keyboard:
1. `tab` to focus the subject `<img>`.
2. While the `<img>` is in focus, use keys `-` and `+` to zoom and the arrow keys to pan.

Operate Pan via Trackpad:
1. Click the multiple arrows button to engage panning. While panning is enabled, you can use the trackpad to move the subject image. Panning by trackpad is not enabled by default to avoid conflicts with drawing tasks. 

Todos:
- [ ] Conditionally display Pan & Zoom, if enabled under the Admin panel.

- [ ] Test with mouse

**Comment by simensta** [comment]
@aliburchard: Pan & Zoom would enable users to access and delete misplaced marks that fall outside the viewport (as described in #2125).

**Comment by simensta** [comment]
This is now an admin-enabled tool.
