### ISSUE TITLE
Loading cover never disappears for video subjects in Firefox

### ISSUE THREAD

**Issue by itsravenous** [zooniverse/Panoptes-Front-End#2135]
E.g. on [Mammoth Bats](https://www.zooniverse.org/projects/zooniverse/mammoth-bats/classify). It seems the `canplaythrough` event isn't being fired, meaning `SubjectViewer#handleLoad` (which removes the loading cover) never gets called. Works fine in Chrome.

Update: OK, it does disappear once you've clicked play, but this is definitely has potential to confuse users.

(If it helps: Ubuntu 15.10, Firefox 43.0.4)

**Comment by eatyourgreens** [comment]
Hmmm, I'm finding that the `canplay` event doesn't fire in Firefox either. Looks like it only downloads the first frame of the video. The loading frame does go away if you somehow push the play button.
