### ISSUE TITLE
Custom projects don't get listed in the Talks navigation bar

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2138]
Projects like Shakespeare's World and  Wildcam Gorongosa  don't show up in the Talk navigation side bar
<img width="250" alt="screen shot 2016-01-24 at 8 58 22 pm" src="https://cloud.githubusercontent.com/assets/753325/12536479/a8b0008e-c2e1-11e5-9491-b861c71198ae.png">

**Comment by trouille** [comment]
Also, when you click on one of those projects, it shoots you to the bottom of the landing page, rather than the top or to Talk. Let's choose a better landing spot.

**Comment by mschwamb** [comment]
@trouille that's reported in #1151

**Comment by parrish** [comment]
Took a look at this because I thought for sure this would be a simple fix.

Apparently, Panoptes doesn't differentiate between projects with off-site urls and projects without .org talk (e.g. Ouroboros projects). 😦 

I'll create a separate issue for this in Panoptes.
