### ISSUE TITLE
Flip Done & Done&Talk buttons for skipped summary page

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2139]
I think we should switch the placement of done and done&talk to be consistent with our other PFE projects.

Our standard PFE project has "talk" on the left and "next" on the right for the final screen someone sees:
![screen shot 2016-01-25 at 11 16 30](https://cloud.githubusercontent.com/assets/6217406/12549449/37867fb8-c355-11e5-809b-eb7027d384aa.png)

Whereas the skipped summary final screen has "done" on the left and "done & talk" on the right.
![screen shot 2016-01-25 at 11 16 02](https://cloud.githubusercontent.com/assets/6217406/12549459/4c752398-c355-11e5-8390-e4cb7f84fc26.png)

**Comment by brian-c** [comment]
Closed by #2189

**Comment by aliburchard** [comment]
Yay! Thank you!!
