### ISSUE TITLE
field guide - create field guide doesn't work right away

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2140]
Have to reload the page before the fields visible to edit.

**Comment by trouille** [comment]
Semi-related to this issue - The field guide remains even after you remove it (e.g., for Mammoth Bats, https://www.zooniverse.org/lab/378/, which Brian you're a collaborator on), I decided best to remove the field guide functionality (by un-clicking the choice on the admin project-status page), and so you don't see the field guide as a tab option anymore in the Project Editor, but the field guide icon still shows up on the project site itself - https://www.zooniverse.org/projects/zooniverse/mammoth-bats/

**Comment by brian-c** [comment]
@trouille I just added your issue to my list-o'-quick-things, will close this when done. Thanks.
