### ISSUE TITLE
When you sign out while on your personal stats and sign in as a different user, the message shows wrong username

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2142]
When you sign out while on your personal stats (ribbon) and sign in again as a different user, the message says wrong username. 
For example, signed in as XXX I am looking at my ribbon stats, then I sign out and sign in again but as user yshish. But a message saying: *Sorry, we can’t show you stats for yshish.* appears although it should rather say *Sorry, we can’t show you stats for XXX.* instead, as I'm on the page for XXX's stats at the moment. Don't you think? Here is a screenshot (check out the URL and the name I'm signed in for and compare it with the name used in the message)

![](https://lh3.googleusercontent.com/-B4Hbi9ZpZ8s/VqZ2n7tDYOI/AAAAAAAAItg/Txzwz5GBsH0/s0-Ic42/ysh_2016-01-25_20-06-29.jpg)

**Comment by srallen** [comment]
Fixed in #2273
