### ISSUE TITLE
Disallow (or make work) special characters in project titles

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#215]
Certain things in project titles break the project url.

(Couldn't figure out why my project called "Where am I going?" didn't work until @camallen came over and roared angrily.) If possible, would be great to have that flexibility. But otherwise, we need to not allow people to enter project titles with names that will break the system.

**Comment by camallen** [comment]
I categorically did not roar, it was more a guffaw.

**Comment by brian-c** [comment]
Ah, yeah, sorry. This is an issue with URLs in general, and we can't really change how those work. Like, a question mark really _means_ something there. Nothing we can do about it. Sad.

Re-moving this to URL discussion in #197.

**Comment by chrissnyder** [comment]
As a differing opinion, why are we using display names for projects in the URL? Wouldn't a slug suffice and not put users in the situation of having to know what the valid character set for a name is?
