### ISSUE TITLE
Admins cannot access projects they do not own or collaborate on in Project Builder

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2150]
This is something that came up in a recent call with Laura/Alex/Cam/Adam/Amy.

There are actually several use cases for this (some of these are just off the top of my head):
- Assigning a correct Project Discipline or other label (per the new Discipline-based project filtering)
- Generating a data export for research purposes (either for ourselves or external researcher)
- Admin may need to check workflow configuration for debugging
- Developer fixing an HTML/Formatting error on one of a project's pages, without having to bug project owner
- Quickly updating some critical error on a launched project
- ....

**Comment by camallen** [comment]
looks like a dup of #1780

**Comment by mschwamb** [comment]
Why does an admin page need to be added for assigning the appropriate discipline?. Can't that be checked during the review stage and confirmed when the project applies for Zooniverse approved status? If the tag is changed to a drop down menu there would be a limited set of options.  It seems to me there would be no need to have an admin to go into a project builder and  change that value

**Comment by alexbfree** [comment]
thanks for linking @camallen . Had completely forgotten about raising this ticket. Linking in @brian-c who just made a comment over on #2586 suggesting this should be possible.

**Comment by alexbfree** [comment]
quoting @brian-c from #2586:

>I'd be in favor of fixing the lab page for admins over duplicating functionality. It probably checking if the user is an owner or collaborator, and it just needs to check if they're an admin.
>
>Admins in admin-mode can just about anything, in case of emergencies.

Looks like that would make this a bug then, not a feature enhancement

**Comment by mschwamb** [comment]
@alexbfree you've seen #1780?

**Comment by alexbfree** [comment]
Thanks @mschwamb, seems we need to have some internal discussion on this to get our strategy lined up. Watch this space!

**Comment by mschwamb** [comment]
I think is solved by what closed #1780?

**Comment by srallen** [comment]
Yes, I think this can close.
