### ISSUE TITLE
Ability to add external researchers as "hidden" collaborators to a project

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2151]
Along with #2150 this came up in a call this week with Cam/Adam/Amy/Laura and myself.

There is a need for Zooniverse staff, or external researchers doing meta-studies, to be able to access a project in the project builder, especially the Exports page. 

However their access should be read-only, and they should still have to apply for the role and it be granted by the project owner.

Their involvement in the project should be "hidden" - they wouldn't be listed as part of the project. Perhaps they would still have a flash "external researcher" by their names in Talk tho.

Another use case might be for Zooniverse developers to be able to access the project (e.g. while adding analytics tracking) without actually being part of the project.

This ticket implicitly implies:
- Readonly mode for viewing a project in project builder.
  (that could be broken off into a separate ticket if necessary)

**Comment by camallen** [comment]
this will need some api work to provide an attribute on project_roles to have a hidden option.
