### ISSUE TITLE
Ability to export collections and favourites data for a project

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2152]
This came up in a MICO meeting last week - it should be possible to export all public collections for a project from the Exports page. (this would be usable by researchers with the access in #2151 as well as project collaborators).

**Comment by camallen** [comment]
project aren't necessarily tied to a project. I can create a birds collection and collect birds across all zooniverse projects.

**Comment by chrislintott** [comment]
@camallen Can people add subjects from a private project to a public collection?

**Comment by camallen** [comment]
i think so yes.
