### ISSUE TITLE
Ability to export Geordi analytics dump for a project from Exports page

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2153]
Soon we will be adding Geordi to the Project Builder, we also need to add something to the Exports page  to allow a geordi analytics dump for that project to be exported. This would be used by people with the access described in #2151 and is similar to #2152 .

**Comment by chrislintott** [comment]
We need to think through which bits of Geordi data we want to make public; until we do I don’t think we should think about building an Exports page.

Chris
