### ISSUE TITLE
is there supposed to be a link to Dev Classifier on the bottom Zooniverse navigation bar?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2159]
Logged in or not I noticed there is now a Dev Classifier link that goes to a page that says loading classifier but doesn't do anything.  The link goes to  https://www.zooniverse.org/dev/classifier

<img width="1105" alt="screen shot 2016-01-29 at 9 39 31 pm" src="https://cloud.githubusercontent.com/assets/753325/12677032/31417c64-c6d1-11e5-8fe6-3d5b8337a847.png">

**Comment by brian-c** [comment]
Wow, g:eyes:d catch, thanks.
