### ISSUE TITLE
Bug when posting a new post in Zoo-wide talk

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2163]
I just tried to post a new post in troubleshooting board. I got a red message and then when i tried again, a never ending spinner. 

![screenshot 2016-01-29 16 12 47](https://cloud.githubusercontent.com/assets/1473244/12680743/55f7ad72-c6a3-11e5-9ebc-af455d04fac9.png)

**Comment by brian-c** [comment]
I got the same behavior on production, not on staging though.

Your posts are in fact coming through, by the way.

**Comment by eatyourgreens** [comment]
I couldn't reproduce this, but when I went to delete my test discussion, I got
`Uncaught (in promise) TypeError: Cannot read property 'page' of undefined(…)`
after pressing the delete button. The discussion was deleted, so I guess it tries to re-render a discussion that no longer exists.

**Comment by eatyourgreens** [comment]
@alexbfree you might want to delete these, as they're now showing up at the top of the Talk recents page.
![image](https://cloud.githubusercontent.com/assets/59547/12681658/8119b578-c6a7-11e5-9d72-7fa44ab5bec0.png)

**Comment by alexbfree** [comment]
thanks. btw sorry for the delay on response to these tickets, it seems my github notifications weren't coming through properly. fixed now.
