### ISSUE TITLE
Recent comments should have "none" message when no comments exist

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2165]
When you click Recent Comments on a project which has no comments (even if it has boards) then the spinner just spins forever 
![screenshot 2016-01-29 16 19 35](https://cloud.githubusercontent.com/assets/1473244/12680947/2ff518c0-c6a4-11e5-9c52-56baf4f7a627.png)

**Comment by srallen** [comment]
Doesn't appear to be an issue any longer. Closing.
