### ISSUE TITLE
If a project is private the Talk comments probably shouldn't show up in a user's public profile 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2168]
I've noticed this before and keep forgeting to put in a ticket. Current Example I have is from @alexbfree https://www.zooniverse.org/users/alexbfree - the most recent comments are from a non-public project. Probably profiles should only show comments from public projects. The links don't actually go to the Talk page it just links back to the profile page, but you can still see the content of the comments on the profile just not the context. 

<img width="1074" alt="screen shot 2016-02-01 at 8 09 01 am" src="https://cloud.githubusercontent.com/assets/753325/12706240/2ce0bf36-c8bb-11e5-9ffb-548d2113920d.png">

If you click on any of those links it goes to the profile page and not to the message board presumably  because it's a private project.

**Comment by alexbfree** [comment]
@chrislintott I think this covers the issue you mentioned to me on Slack, I will investigate it under this ticket.

**Comment by alexbfree** [comment]
Actually thinking about it the issue @chrislintott mentioned was a bit different: that was about public collections being able to receive subjects from private projects. I think it's all part of the same private vs public content question, so I will look at content privacy and visibility as a whole.
