### ISSUE TITLE
Hiding custom projects

### ISSUE THREAD

**Issue by perry** [zooniverse/Panoptes-Front-End#217]
We'll need to be able to hide public custom projects (eg. Old Weather, Tate) from appearing here, as they are likely to contain custom workflows that will not be supported in PFE.

**Comment by brian-c** [comment]
@chrislintott vetted/promoted custom projects should still appear on zooniverse.org, right?

I'm thinking we can handle this with two project-level options:

- `"redirect": "https://www.ancientlives.org/"` would point to the external URL and redirect when a user tries to load that project

- `custom_workflow` would disable the workflow editor UI.

@edpaget Is this a reasonable use of the project config field?

**Comment by edpaget** [comment]
Yeah I think that's fine.

**Comment by edpaget** [comment]
I'll try to have a PR in for this by the end of today.
