### ISSUE TITLE
Delete own post not working in Talk

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2171]
I tried to delete my own post, it appeared to work, but when I went back to the board, the thread was still there. In the end @marten had to use moderator controls to delete the post, which worked.

**Comment by camallen** [comment]
any chance you can debug this in dev tools to see the network traffic to the delete request?

**Comment by eatyourgreens** [comment]
I just created a test discussion on the Troubleshooting board, then deleted it successfully using the delete button on my test comment. Any ideas on how to reproduce this?

**Comment by eatyourgreens** [comment]
Looks like there's a case where deleting the only comment from a thread breaks the paginator, so the discussion doesn't re-render. Should be fixed by #2175 

By the way, it might be better to test this by posting test comments to staging Talk.

**Comment by alexbfree** [comment]
Sorry for the delay in reviewing this; I didn't get the notification as I only fixed my github notifications after this was assigned. Looks good, thanks for fixing.
