### ISSUE TITLE
Something horribly wrong on panoptes  - the live site including projects and talks are now old versions or something else

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2179]
It looks like something horribly happened on Panoptes. The Front page doesn't load the four projects on the bottom it says:
Error: Could not find projects with ids='11,6,3,17'

Planet Four: Terrains avatar is gone and it says there are no Talk boards.

Zooniverse Talk all the boards are gone and two old ones with posts from 2 months ago exists

Comet Hunters doesn't even load non-logged in, not sure if that is because it's reverted to a pre-launch state

There are weird beta test/development projects on the projects page.

Did somehow the development version get switched to the live version?

**Comment by brian-c** [comment]
Issue in a new library is causing the production site to connect to the staging server. Should be fixed in two minutes, sorry.

**Comment by mschwamb** [comment]
thanks @brian-c . @mrniaboc just sent a newsletter for Planet Four: Terrains. Maybe he wasn't aware there was an issue going on,  so it would be good to get people on the real site rather than the really old staging version as soon as possible.

**Comment by brian-c** [comment]
It's fixed now.

**Comment by mschwamb** [comment]
Thanks @brian-c

**Comment by mschwamb** [comment]
Your or @astopy might want to update the[ status page](https://status.zooniverse.org/issue/ee36a779-d606-4d32-a481-768aef97e501) - it would be nice if there was a IFTT way to trigger something on social media when there's a positing or new issue on the new status site. Still by habit, social media is the first place I check, might be the same for many volunteers. 

Thanks again for sorting this @brian-c
