### ISSUE TITLE
Image sizing

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#218]
How do I size my images/subjects to guarantee that the questions don't end up under the image -- at least for most standard screen sizes?

**Comment by mkosmala** [comment]
For example, images with these sizes allow the questions to stay to the right:
1296x960
640x360

But images with these sizes force the questions to the bottom:
1280x720
2592x960

(Note that 640x360 has the same dimensions as 1280x720)

**Comment by mkosmala** [comment]
It looks to me like the image is resized only according to height. But note that this is a problem for short, very wide images. Not only do the questions fall to the bottom, but also the image doesn't entirely fit on the screen. See, for example:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Alpha6/classify?workflow=589

**Comment by brian-c** [comment]
The current implementation hands as much layout off to the browser as possible, there are a few parameters we can fiddle with though. #160 will probably help with wide-short images (that's what was used for Stargazing), but I'll need to go through and clean it up a bit before it's merged.

In the future it would be nice to have a function that takes an image size and a viewport size and figures out the best layout, but "best layout" is subjective on a few different levels. I hope that seeing more projects will help us define what this should be.

A subject image should never extend past the viewport, that sounds like a bug. What browser does that happen in? Can you make a screenshot? Thanks.

**Comment by brian-c** [comment]
Ah, sorry! To answer your question: The current implementation wants to show as much detail of the original image as possible, so it will drop the workflow before it shrinks the image horizontally. To prevent the workflow from dropping, you'll need to use narrower subject images.

**Comment by mkosmala** [comment]
Yes, I know I need narrower subjects, but I don't really know how narrow. What I've decided to do for now is see whether an image is fatter or thinner than a 1.35:1 ratio (which seems to work well). If it's fatter (wide and short), then I resize it to make it 720 px wide. Unfortunately, I have images of arbitrary size to deal with, so I need a rule for resizing them, rather than trying them all out by hand.

As for the image extending past the viewport, this happens in Firefox 37.0.2. Here's a screenshot:
https://drive.google.com/file/d/0Bxc_8RhRnC8dTENWTkdaa1p4UUk/view

**Comment by chrissnyder** [comment]
Feels like we need to arrive at an actual rule of thumb here, especially if a science team is going so far as to pre-process image merely to suit the idiosyncrasies of how the classifier behaves.

**Comment by aliburchard** [comment]
A rule of thumb would be great here -- right now I'm working with the whale project to try and optimize image resizing for this as well.

**Comment by brian-c** [comment]
We can't specify a window size or aspect ratio our users are going to be viewing the site at, so I really don't think it makes sense to define a rule of thumb for image dimensions. And any rule of thumb we set would be obsoleted by future improvements to the page layout.

I agree that the automatic layout of the classification page can be improved a lot. I don't think it's bad enough to be a blocking issue though.

My rule of thumb would be: Crop to keep as much resolution/information as is useful to classify, and keep it under ~300KB.
