### ISSUE TITLE
crop-tool shows the cropped image overlaying the original image

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#2180]
After selecting an area with the crop tool, only the SVGImage is updated, not the underlying image rendered in the [FrameViewer](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/frame-viewer.cjsx#L52). In other words, after cropping an image, the user sees the cropped image overlaying the original image.

**Comment by eatyourgreens** [comment]
Have you got a link to a test case for this? @aliburchard checked the crop task on the retinas project, and it seemed to be working fine.

**Comment by simensta** [comment]
@eatyourgreens: checkout the second task at https://www.zooniverse.org/projects/asimenstad/bell-demo/classify.

**Comment by eatyourgreens** [comment]
Cheers. Looks like `SubjectViewer.overlayStyle` was lost somewhere. The SVG image is supposed to completely cover the underlying HTML image.
https://github.com/zooniverse/Panoptes-Front-End/pull/1965/files#diff-a8671c6b3d2d9b11be38f376f0947342L113

**Comment by eatyourgreens** [comment]
oh, and I should probably ping @itsravenous about this too.
