### ISSUE TITLE
Can you please add the subject set id to the assoicated subject sets list in the workflow editor

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2182]
I'm working on parsing some info from the subject csv dump for the Comet Hunters PI, but we only want it live data. It would be nice if I could scan the list of subject sets live and see the ids rather than having to go one through on their subject set page to get that id since it's what I have to use to parse what subjects belong to which subjects sets

**Comment by camallen** [comment]
@mschwamb do you mean here on the project lab workflow page? 

![image](https://cloud.githubusercontent.com/assets/295329/12812031/27017a50-cb28-11e5-98f9-a2c1d690fcfb.png)

**Comment by mschwamb** [comment]
yes @camallen . I have 4 or 5 subsets hooked up on comet hunters and so it would save the time to see the id  # so I could confirm with the subject csv that a subject was live on the site and not test data or something else. The subject csv only has the subject_set id as a number (which is fine).

**Comment by camallen** [comment]
If you add the subject id to the text [in this line](https://github.com/zooniverse/Panoptes-Front-End/blob/ff886855bfa79e1c25a68f45893f9a2321bf8911/app/pages/lab/workflow.cjsx#L321) you could PR it.

**Comment by mschwamb** [comment]
Thanks @camallen . I would have never figured out on my own where to make a change.  I'll make a pull request in a few days for this.
