### ISSUE TITLE
Was the button where you show the flipbook version of subjects with multiple images supposed to go away in Talk?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2183]
There was a button that appeared where you could hit it and see the other images associated with the subject one after the other. Now it's gone. Only the play button remains. Was that supposed to happen?   I thought it might be handy Talk feature. Maybe a question for @eatyourgreens .

**Comment by eatyourgreens** [comment]
Hi Meg, it was taken out in response to #2169. @itsravenous was working on that feature. Maybe you, him and @alexbfree should have a chat about how it should work in Talk?

**Comment by itsravenous** [comment]
I think if it were to return (I agree it's a useful tool in Talk) there'd need to be some expectation management regarding layout. Because the layout settings for the "show all frames" view are set per -workflow, they're not accessible from talk. So if frames are large-ish (say 650px, obviously it depends on the available screen/viewport width) then they would just stack underneath each other, even if in a workflow the layout is set to a grid of three (which while classifying would mean the frames are shrunk to fit that grid three per row).

**Comment by camallen** [comment]
we could use the subject thumbnails service in talk to get specified image sizes.

**Comment by itsravenous** [comment]
But how do we decide what size those thumbs should be? Mightn't it vary depending on the project? Or are you suggesting users could control that from the SubjectViewer via some sort of UI?

**Comment by camallen** [comment]
maybe a function of view port...not sure? I'm saying we can use a subject URL to get a specific img size if we need.

**Comment by itsravenous** [comment]
Cool. I feel that one rule for everyone might not work, so I think a UI would be appropriate (small, medium, fullsize buttons, maybe?). That said, I don't want to clutter the talk interface if this isn't a widely needed feature. Maybe we start out just showing the default size and see how that works for users? @alexbfree @mschwamb what dyou reckon?

**Comment by mschwamb** [comment]
@itsravenous  I thought it was nifty there was a view you could see all of the images by scrolling rather than animated or having to click. I thought it worked fine as is, with just scrolling from one subject to another. I think you could leave the default size Talk had (which is what it was doing) for now, and see. I don't think the extra button was cluttering anything. I'm not sure how used the feature will be, but I thought it was a nice addition to Talk's functionality, and I could see uses of it for volunteers who are doing their own investigations. 

 So I think if you can hide the button if there is only one image associated with the subject, then the feature was fine as implemented on Talk. I wouldn't add it to the classification interface, but I think it's a great addition to Talk. 

 It might not work for everything as is, but if a science team members wants something more than they'll ask for the feature and that can be assessed later whether to implement that or not. Anyway that's my science team perspective, if it's helpful.

**Comment by itsravenous** [comment]
Thanks for the feedback @mschwamb.

Since you mentioned it, this *is* going to be used in the classification interface, initially for "side by side" comparison workflows on certain projects.

**Comment by mschwamb** [comment]
@itsravenous as someone with a launched project with multiple images per subject, I would ask that there be a side by side task rather than having this feature turn on in the classification interface for all projects that have more than one subject, so that I don't have to go through and show there's no difference in user behavior between the new and the old classification interface. Also that view isn't needed at least for my science in the classification interface.

Anyway, if you wanted to make that feature available in Talk though as is, that would be great. But I understand if not.

**Comment by itsravenous** [comment]
@mschwamb by default the button is hidden until enabled on a workflow under "Multi-image options". You can choose whether to always just show the animation, just show separate frames, or allow users to choose (in which case the button appears and the default view is the animation). So hopefully no worries on this affecting your existing projects.

I'll wait for input from a few others here but it sounds like this could be useful in talk. @eatyourgreens @brooke @brian-c?

**Comment by eatyourgreens** [comment]
Fairly sure this was fixed somewhere along the line.

**Comment by brooke** [comment]
@itsravenous I am not the brooke you're looking for
