### ISSUE TITLE
Crop tool expands image beyond original in IE

### ISSUE THREAD

**Issue by itsravenous** [zooniverse/Panoptes-Front-End#2185]
Tested in IE 10/11:

![iecrop](https://cloud.githubusercontent.com/assets/1737376/12825026/286bd43c-cb6c-11e5-8a60-bbf336128231.gif)

Inspection shows the `<image>` element grows beyond the bounds of the `<svg>` element - I don't know why this should be. It's possible this bug was introduced by #1965 but I can't find the origin crop tool branch to verify that. @brian-c ?

**Comment by eatyourgreens** [comment]
Have a look at the SVG zoom on operationwardiary.org Might be as simple as adding `overflow:hidden` to the svg element.

**Comment by itsravenous** [comment]
@eatyourgreens you're right!
