### ISSUE TITLE
Roadmapping

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2187]
We've talked on slack a bit about roadmapping for a while now. Since I'm at Mozilla's Working Open Science Workshop and we're building roadmaps for open science projects, I thought I'd try and set up a rough outline of ours here, so everyone can see what we're actively tackling. Not sure if this is the most useful approach, if it's too detailed, or what. I'll try to add links to actual issues as well. Please feel free to edit/comment/whatever. Just getting this started!
### Short Term - Easy things to tackle now
- [x] swap talk/talk&done
- [x] hide back button
- [ ] delete auto appearing task
- [x] announcement
- [x] min-max markings
- [x] add structure to lab page
- [ ] link to “quick start” help guide
### Medium Term/ slightly more difficult

fine marking
custom pages
add subject sets to live projects
### Hard things that need thinking about

fix summary page (brian/jim/ali to brainstorm what this might look like)
subject management/uploader/support (ali to come up with list of desired functionality)
versioning (needs a bigger conversation)

**Comment by mschwamb** [comment]
Fixing and finishing the features for collections

**Comment by aliburchard** [comment]
Excellent point -- I need to have a proper look through the talk related issues as I'm not as familiar with them as I am with the project builder issues. I wont have a chance to do this in the immediate future, but I will put it on my list.

**Comment by mschwamb** [comment]
I'd also say adding a research team markdown page to projects and adding in the capability for metadata that shows up on Talk and not in the classification interface is a highly desirable feature that the custom projects have but doesn't exist in the project builder projects.

**Comment by srallen** [comment]
Using github's new projects feature would be the best place for this.
