### ISSUE TITLE
Unable to classify - Cellect down?

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#219]
Hello,

Trying to classify subjects in my project, I get:

`Error: Couldn't find SubjectQueue with [WHERE "subject_queues"."user_id" = 1846 AND "subject_queues"."workflow_id" = 627]`

Also while editing a workflow, clicking the **Reload Cellect** button gives `There was an error reloading cellect`.

Is Cellect down?

Cheers, Tom

**Comment by camallen** [comment]
Hi @twhyntie - we're trying out a different solution for subject selection. There are some integration issues that I hope to have sorted very soon. You won't need to reload cellect for this solution so that button will error out (we will remove it if the solution works).

**Comment by twhyntie** [comment]
Hi @camallen - thanks, and apologies, I didn't realise there was integration work ongoing. Could you please let me know when it's ready via this issue?

**Comment by camallen** [comment]
Will do - it's actually a backend issue that we're testing it out on staging / demo and you're seeing it in the front end.

**Comment by mkosmala** [comment]
Adding myself to this issue so I get alerted when this is resolved, as well.

**Comment by camallen** [comment]
PR submitted, https://github.com/zooniverse/Panoptes/pull/749

**Comment by camallen** [comment]
another issue still to fix, PR coming soon.

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/pull/751

**Comment by camallen** [comment]
This should be fixed now

**Comment by edpaget** [comment]
Fixed-ish
