### ISSUE TITLE
Error deleting workflow on PFE project

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2192]
The owners of Colorado Corridors project tried to delete an old workflow (in order to clean up the project). Now the workflow still appears as "Untitled Workflow" but the page is blank. If you go to https://www.zooniverse.org/lab/75/workflow/126 you see:
![screen shot 2016-02-08 at 11 43 10](https://cloud.githubusercontent.com/assets/6217406/12884919/65783ce0-ce59-11e5-9411-83a7146abc51.png)

@brian-c any ideas?

**Comment by srallen** [comment]
Gonna close this as the bug is quite old and may not be able to replicate.
