### ISSUE TITLE
Talk links breaking as GA code being inserted oddly

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2200]
[This Panoptes Talk thread](https://www.zooniverse.org/talk/18/16884?comment=76650&page=1) has a user trying to link to an Ouroboros Talk thread, and the link is formatted correctly in the post, but the actual link that tries to complete has some GA code in the wrong place in the link. The user linked to:

http://talk.asteroidzoo.org/#/boards/BAZ0000001/discussions/DAZ000070l?page=4&comment_id=56b865a0f724d764370041c2

but the page that attempts to load is:

http://talk.asteroidzoo.org/&_ga=1.203108369.1257499081.1450219232#/boards/BAZ0000001/discussions/DAZ000070l?page=4&comment_id=56b865a0f724d764370041c2

the actual GA code changes with each click. If I manually move the &_ga... bit to the end of the URL everything loads fine.

This didn't happen when I tried an external link.

**Comment by camallen** [comment]
This is a GA tracking code error inserting before the hash fragment which is causing problems hosting out of s3.

**Comment by eatyourgreens** [comment]
There's a missing `?` in that URL. Should be `/?_ga=' etc etc. Or add the `_ga` query param at the end of the URL, with the other query params.

**Comment by camallen** [comment]
fixed to changes in the GTM setup (using hash fragment as a delimiter).

**Comment by camallen** [comment]
Reverted changes and Google Tag Manager(GTM) is now breaking some links again. Investigating the requirement for the GTM properties, hopefully will have a fix soon.

**Comment by eatyourgreens** [comment]
Couple of tests with changes to the format of those URLs:

Move Talk parameters into the query string
http://talk.asteroidzoo.org/?page=4&comment_id=56b865a0f724d764370041c2&_ga=1.203108369.1257499081.1450219232#/boards/BAZ0000001/discussions/DAZ000070l

Move Google code to the end of the fragment identifier
http://talk.asteroidzoo.org/#/boards/BAZ0000001/discussions/DAZ000070l?page=4&comment_id=56b865a0f724d764370041c2&_ga=1.203108369.1257499081.1450219232

URL-encode the Talk parameters in the fragment identifier
http://talk.asteroidzoo.org/#/boards/BAZ0000001/discussions/DAZ000070l%3Fpage%3D4%26comment_id%3D56b865a0f724d764370041c2

**Comment by camallen** [comment]
i tried moving the code to the end of the fragment identifier, it broke other from sites links e.g. https://www.zooniverse.org/_ga=1.201654353.1742812019.1455191116#_ga=1.201654353.1742812019.1455191116

**Comment by camallen** [comment]
i have no idea why it put 2 ga codes in there either...

**Comment by alexbfree** [comment]
at least it's the same code!
my guess would be when they try to parse the _ga code back out, they don't expect the fragment ID to have # and &

**Comment by alexbfree** [comment]
i think that "Move Talk parameters into the query string" is the best solution of @eatyourgreens 3 tests - it should work both in GTM parsing and in our code. but we'll need to confirm that of course.

**Comment by eatyourgreens** [comment]
@camallen I think that's @edpaget's redirect from zooniverse.org/#{something} to zooniverse.org/something. Or react-router doing the same thing.

**Comment by alexbfree** [comment]
we should probably move this ticket to https://github.com/zooniverse/Talk

**Comment by camallen** [comment]
it's not a talk thing. it's from GTM and will affect all our sites that have cross-domain tracking. moving this thread is pointless.

**Comment by camallen** [comment]
@eatyourgreens yes - you're right! Try this, https://www.zooniverse.org/#admin

**Comment by eatyourgreens** [comment]
@alexbfree note that the first link takes you to the beginning of the discussion, rather than the specified comment on page 4.

**Comment by alexbfree** [comment]
I have raised this issue with Google, let's see what happens. 

I revise what I said above, i think the best fix is just to have the URL become
http://talk.asteroidzoo.org/?_ga=1.203108369.1257499081.1450219232#/boards/BAZ0000001/discussions/DAZ000070l?page=4&comment_id=56b865a0f724d764370041c2`

https://code.google.com/p/analytics-issues/issues/detail?id=876

**Comment by MvGulik** [comment]
I see that Google is taking its time in responding back. :(

Anyway ... There is a optional user-workaround around this problem. To make these kind of links work as generally expected, instead of ending in a 404.

Although ... this workaround is working because it seems to stop the ga code from being inserted. Witch is why I drop this here, and not directly in the Zooniverse forum itself.

Workaround:
Change: "...\<zooniverse-related-hostname>/#/<other-stuff>..."
To: "...\<zooniverse-related-hostname>/?#/<other-stuff>..."
(*or, add a '?' sign before the '#' sign.*)

**Comment by srallen** [comment]
Just noting here that issue is still unresolved with Google.
