### ISSUE TITLE
On the How To page, markdown overflows its boxes

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2202]
https://www.zooniverse.org/lab-how-to

![screenshot 2016-02-11 15 48 36](https://cloud.githubusercontent.com/assets/1473244/12981083/15602a3a-d0d7-11e5-854d-570a3be7e467.png)
![screenshot 2016-02-11 15 48 47](https://cloud.githubusercontent.com/assets/1473244/12981082/155feff2-d0d7-11e5-8b97-b98fb1e8f2e4.png)

**Comment by srallen** [comment]
Fixed in #2271
