### ISSUE TITLE
Weird Planet Four: Talk discussions showing up on other project Panoptes Talks

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2210]
@parrish I wasn't sure where this should go. I thought this might be the right place. Description of the issue reported [here](https://www.zooniverse.org/talk/17/39300?page=1&scrollToLastComment=true). I noticed this involves one of my projects. I presume it means the Talk database is fine and that it's just some weird linking issues?

**Comment by mschwamb** [comment]
Same thing on Comet Hunters talk as well, when you move to page 3 it goes to Planet Four: Terrains https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/8?page=3

**Comment by mschwamb** [comment]
Looks like this issue is still happening with posts from @VVH wondering why there's images of a planet or moon showing up in Shakespeare's World - https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/29/21111?page=1&scrollToLastComment=true

**Comment by parrish** [comment]
Should be the same issue as zooniverse/Panoptes#1680
