### ISSUE TITLE
Allow drag and drop of images into Talk

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#2216]
@rogerhutchings and I were chatting about this today and I don't see any previous requests here, so pinging @brian-c and @srallen as not sure who is across Talk atm. If I want to upload an image to Talk I have to use markdown, put something up on imgur and then link to it. Do you guys think a Github-like drag and drop feature could be implemented in the next 3-6 months?

**Comment by srallen** [comment]
Before we discuss implementing a feature like this, there's a preliminary question of whether or not we want to host an arbitrary number of images or not for Talk. What Github does is upload it to a cloud storage that I'm presuming they manage for Github user accounts.

**Comment by mschwamb** [comment]
This would be a nice feature. I know that the volunteers on my projects have gotten around it by using dropbox and wrote a guide for new users, but yes dragging and dropping would be nice, but I can see the issues about how and when to restrict the size of the images stored from talk discussions.

**Comment by alexbfree** [comment]
Since we already allow arbitrary number of images to be uploaded via the Media page, isn't this just a UX issue, not an addition of new capability?
(having said that, I can't be entirely sure what is available in media upload feature, since the media uploader seems to have issues at the moment, have raised #2217)

**Comment by vrooje** [comment]
I don't think we should try or even enable ourselves to become an image repository for all our volunteers... I'd rather just suggest people find a place to store images and show them how to include them via markdown. Imgur is really easy to use and provides a markdown link you can just copy and paste.

**Comment by srallen** [comment]
I agree with @vrooje. I don't think we should host images for Talk. However, we could potentially still add a drag and drop feature that hooks into an imgur upload assuming they have an API for that.

**Comment by alexbfree** [comment]
+1 to Sarah's suggestion - all the UX convenience with none of the hosting responsibility :-)

Yes I guess it's not quite the same as media upload since that is just for project owners not all Talk users.

**Comment by chrislintott** [comment]
I think adding the ability to host images would make us more vulnerable to spam, which would cause problems for our moderators. The upload via the media page seems different as those images aren't immediately available. 

I'm going to close this without fixing, but I think we should write a clear guide to how to store images elsewhere (e.g. Flickr).
