### ISSUE TITLE
Media upload page seems to be broken

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2217]
I am not sure if there particular requirements I may not be aware of, but I have tried adding various images to the Media page on a project I own, i do not think the image is not added, no success or error message is given, so it's hard to be sure, but it does not appear on the page and when I tried embedding the image via markdown after doing so, i got a broken image icon. So it doesn't seem to be there. 

Possible clues in JS console:
```
Adding 1 files
Adding media timedpics23.jpg
Creating resource for timedpics23.jpg, image/jpeg
GET https://www.zooniverse.org/api/projects/1441/attached_images?page_size=200 404 (Not Found)
Uncaught (in promise) Error: No attached_images exists for project #1441(…)i.handleError @ main.dc42badf32053ef455673547078cff2c.js:36
Uploading timedpics23.jpg => https://zooniverse-static.s3.amazonaws.com/panoptes-uploads.zooniverse.org/…V4ls6VSWOyW7fw%3D&response-content-type=image%2Fjpeg&x-amz-acl=public-read
Success! timedpics23.jpg
No longer pendingFiles: timedpics23.jpg
```
I see success and error in the console, so it's not exactly clear what happened, this needs to be investigated further.

**Comment by vrooje** [comment]
Weird, this is working for me. Used it several times yesterday and today on 2 different projects.

**Comment by alexbfree** [comment]
@vrooje maybe it's browser/platform specific? what browser version/OS are you using?

**Comment by alexbfree** [comment]
@vrooje also could you provide me a known working image that you are successfully able to upload, so I can be sure that it's not the image?

**Comment by alexbfree** [comment]
OK even weirder, it's all working fine now. And the images I uploaded previously *did* actually upload, despite errors and not showing up. So  whatever it was was just a temporary glitch.

Closing.

**Comment by srallen** [comment]
I just tried to upload an image for a tutorial and am seeing these errors in the console:

`POST https://www.zooniverse.org/api/tutorials/18/attached_images 401 (Unauthorized)`
`TypeError: Cannot read property 'error' of null(…)`
`PUT https://www.zooniverse.org/api/tutorials/18 401 (Unauthorized)`
`Uncaught (in promise) TypeError: Cannot read property 'error' of null(…)`

Possibly related to the reported [Promise error with the json-api-client](https://github.com/zooniverse/json-api-client/issues/27).

**Comment by vrooje** [comment]
I do see the uploaded image not showing up in PFE until I refresh - that happened with e.g. [this image](https://panoptes-uploads.zooniverse.org/production/project_attached_image/d0518249-ff71-4d1a-82fe-b250a666af81.png) that I uploaded today.

(In case you need a working example)

**Comment by mschwamb** [comment]
@vrooje that's a known issue #1912

**Comment by vrooje** [comment]
@mschwamb thanks for finding that :) it's easy enough to work around so I don't worry about it anymore. Oops.

**Comment by alexbfree** [comment]
OK so putting aside my initial issue (which went away), and Brooke's issue (which is covered in #1912),  can we close this ticket, or is there still an issue you are seeing @srallen ?

**Comment by srallen** [comment]
Aside from the behavior in #1912, I can upload a media file today. I'm not sure why I was experiencing 401s on Friday, but this can reopen if anyone else reports it.
