### ISSUE TITLE
Research page on projects: list of team members should include profile links

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2218]
Currently the team list on a project's Research page doesn't link to each user's Zooniverse profile page, so if a team member has their Real Name field filled in (which I do) you can't see their username and thus can't use the team list as a way to contact them. Can we fix this? I'd like to be able to tell people they can always contact a project owner via the Research page.

**Comment by mschwamb** [comment]
Also might be something to think about for #1947

**Comment by mschwamb** [comment]
The search for private messages uses usernames, but the research page only lists username if there is no display name. So on Planet Four: Terrains it shows 'Meg Schwamb' for me, but a volunteer would need to message mschwamb. To make it easier for volunteers to message moderators and the research team, can the username always be displayed even if there is a display name on the research page  as well.

**Comment by simoneduca** [comment]
Just to be clear @mschwamb: would you like to display both names, if the user has provided the "Real Name"?
![screen shot 2016-11-09 at 16 22 15](https://cloud.githubusercontent.com/assets/8989606/20145738/1ef9ecaa-a699-11e6-8ff1-6221ddc85c7e.png)

**Comment by mschwamb** [comment]
I'd probably go with showing user name and display name, because real name is more for published papers. And display name is what is also shown on Talk.
