### ISSUE TITLE
White Zooniverse avatar /Zooiverse front page link doesn't show  on Firefox 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2225]
Question maybe for @jwbmartin? I noticed that now the Zooniverse avatar only shows up on the front page only, and  any where else it's been removed. I thought I remembered a white version of the avatar used to show up.  Maybe it's supposed to be that way and not be there. I thought I'd ask, just in case. 

<img width="1098" alt="screen shot 2016-02-23 at 4 02 24 pm" src="https://cloud.githubusercontent.com/assets/753325/13245265/fb2edc32-da46-11e5-97b0-f07d0b3844c9.png">
<img width="1093" alt="screen shot 2016-02-23 at 3 54 34 pm" src="https://cloud.githubusercontent.com/assets/753325/13245271/fe408c90-da46-11e5-980f-7efffa366971.png">
<img width="1090" alt="screen shot 2016-02-23 at 3 54 21 pm" src="https://cloud.githubusercontent.com/assets/753325/13245275/000a2f4a-da47-11e5-8f7e-dd1f202573b6.png">

**Comment by srallen** [comment]
@mschwamb I think this is a browser based bug. I'm seeing it fine in Chrome on OS X. What browser and OS do you see this happening?

**Comment by mschwamb** [comment]
@srallen That didn't even cross my mind to check. Ah I just checked Chrome and see it. It's missing from Firefox I'm using version 44.0.2 on Mac - so it's a firefox bug

**Comment by mschwamb** [comment]
I updated the ticket to reflect that it's a firefox bug with the display of the icon for the Zooniverse home link.

**Comment by srallen** [comment]
Thanks @mschwamb

**Comment by brian-c** [comment]
I'm seeing weird behavior in Chrome Canary (although not in the release version), too. It looks like if I load the page from `/` and browse around, the logo behaves as expected, but if I load from `/lab`, the `<use>` element has no width or height, which would imply that it can't find the link. I suspect this has to do with the new `<base>` tag implementation.

**Comment by mschwamb** [comment]
Looks like that just came back on Firefox so closing .
