### ISSUE TITLE
Question: Have we made it easy for researchers to find out from classification exports *when* a subject was retired?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2228]
I've just been doing some analysis on Ouroboros Mongo data for Serengeti, specifically the classifications dump, and noticed that it's remarkably hard to work out exactly which classifications "count" and which ones should be disregarded because they happened after an already retired subject was reactivated (which often happens when we want to keep a site active but have no data). You can't immediately tell from the data we have, when a subject was retired or which classification caused it to retire.

The main reason this is difficult is because we do not log the current retirement-or-not status along with the classification record, nor do we have any timestamp or classification ID on the subject record at the time when we update it with the retire_reason.

I thought I would ask the question, do we do anything in Panoptes DB to avoid this becoming an issue in future on Panoptes projects? Do we store the current retirements status against each classification? Or add metadata to the classification that causes retirement? Or track when a subject is retired for a workflow? Any of the above would mean that this kind of analysis of Panoptes data ends up being much simpler than it is on Ouroboros...

**Comment by camallen** [comment]
>I thought I would ask the question, do we do anything in Panoptes DB to avoid this becoming an issue in future on Panoptes projects? 

Yes

>Do we store the current retirements status against each classification? 

No the retirement status is traced per subject : workflow and records the datetime of retirement.

>Or add metadata to the classification that causes retirement? 

No, use the lookup on the SubjectWorkflowCount or the classifications dump.

> Or track when a subject is retired for a workflow? 

Yes, see above.

**Comment by marten** [comment]
I'm closing this, seems to be answered and doesn't really have anything to do with PFE.
