### ISSUE TITLE
Team member info on GUI

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#223]
The backend allows for team_members to each have a name, bio, institution, and twitter handle. Where do these things show up on the front end?

**Comment by chrissnyder** [comment]
Probably already know the answer, but the sidebar on the Science page.

**Comment by edpaget** [comment]
Actually they're not used at all and that field will be removed.

**Comment by mkosmala** [comment]
@edpaget Which field(s) will be removed from the back-end? 
And @chrissnyder, none of those things shows up on the sidebar on the Science page. Is there another issue open requesting that this happen?

**Comment by edpaget** [comment]
The team_members field. It's going to be replaced with more freeform pages.
