### ISSUE TITLE
Refactor project page as shown in project-listing-stub branch

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2230]
@brian-c had some suggestions for #2149 that included refactoring the project page to stop depending on OwnedCardList as part of subsetting that component, since the needs for the Projects page and Collections views have diverged.

Sample code is in the project-listing-stub branch 1a3212c4fcdfff4c0100f2f5f8de71009b9e9790

**Comment by alexbfree** [comment]
@amyrebecca I think this ticket is done, right, we can close it? Please re-open if I'm wrong.
