### ISSUE TITLE
[project page branch] Usability of filmstrip component on mobile is bad

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2232]
@brian-c noticed this one when reviewing #2149 

The filmstrip layout is a little whack on mobile. Probably an easy to fix with `flex-wrap`. Maybe normal `overflow: auto` might be appropriate too?

**Comment by alexbfree** [comment]
@brian-c @eatyourgreens any thoughts on whether this is still true, or can we close this? Try latest at https://project-page-states.pfe-preview.zooniverse.org/projects?env=production

**Comment by brian-c** [comment]
Still seems pretty rough to me. You can only see two disciplines at a time, and the scroll arrows don't seem to land in any expected spot. We've basically tried to re-implement scrolling here, which is really really hard to do well. I'd utilize what the browser gives us.

Layout still seems a bit wonky, too.

<img width="578" alt="screen shot 2016-04-12 at 12 27 33 pm" src="https://cloud.githubusercontent.com/assets/464389/14469407/0afda48e-00aa-11e6-9ebc-13939541c13e.png">

**Comment by eatyourgreens** [comment]
This is next on my list of things to look at.

**Comment by alexbfree** [comment]
closing as this is now addressed by #2435
