### ISSUE TITLE
[project page branch] Possibly make filmstrip respond to swipe events on mobile

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2233]
@brian-c notes in reviewing #2149 

My instinct when I see a component like this is to swipe it. The react-swipe component might be useful here.

**Comment by eatyourgreens** [comment]
I suspect the answer on small screens is to abandon scrolling and style this as a menu that expands when active, otherwise contracts to just showing the selected option. 

Swipe might be useful on tablets or Windows touch screens.

**Comment by eatyourgreens** [comment]
Fixed in #2435 and #2443 by allowing the filmstrip to scroll.
