### ISSUE TITLE
push filmstrip changes back to zooniverse-ui

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2236]
The filmstrip component has changed considerably since it was brought in from the other repository for #2149 , those changes need to be backported in case we need this component in a custom project.

**Comment by alexbfree** [comment]
@amyrebecca @srallen Is this still a valid ticket? I vaguely remember hearing mention that maybe the filmstrip wouldn't be a separate component after all, but not sure what the conclusion was.
