### ISSUE TITLE
Api 500 error breaks internal error handling

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#2237]
Looks like 500 errors don't have a body or something, nothing of interest in the console either.

![image](https://cloud.githubusercontent.com/assets/295329/13354186/61a58230-dc91-11e5-9e49-4612f4ffa1be.png)

**Comment by rogerhutchings** [comment]
Related: #950

**Comment by camallen** [comment]
work is being done to fix this.
