### ISSUE TITLE
Number of "Registered Volunteers" is considerably off

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#2240]
My current project shows these stats at the bottom of the main page. Grabbed a classification dump and verified that I have only 22 unique users classifying on my project. The number shown is very similar to the number of subject images... could they be related somehow? 

![wonkyprojectnumbers_crop](https://cloud.githubusercontent.com/assets/7946684/13408039/33f8dd5c-def1-11e5-9516-b4085e560034.png)

**Comment by camallen** [comment]
This is a known api bug. Can you provide a date to start counting classifications from for the project? I'll fix this tomorrow.

**Comment by melaniebeck** [comment]
I should have known that you guys knew about this one already! I created this project on 3 Feb.

**Comment by camallen** [comment]
Not when you created it but when you start counting classifications from, I.e. launch date?

**Comment by melaniebeck** [comment]
I started classifying the same day.

**Comment by camallen** [comment]
updated @melaniebeck - better?

![image](https://cloud.githubusercontent.com/assets/295329/13425503/1fb1adfc-df9f-11e5-99b0-02965d48bad5.png)
