### ISSUE TITLE
project builder: need better identification of image columns in manifest

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2242]
In a new subject set I'm uploading, each subject has 2 jpg images, and the manifest has an additional column giving the original filename of the tif image from which the main jpg was generated. For half the subjects the string is e.g. `blah/blah_modified_blah.tif`, and for the other half it's `blah/blah_modfromjpg_blah.tif`. When I drop the manifest and a subject with the correct 2 jpgs from the `modified` half, the project builder recognizes the subject. When I do the same with a `modfromjpg` subject, it doesn't. But it does work if I change the manifest so that part of the string says `modfromjqpg`.

Seems to me like the search for an image filename in the string columns of the manifest checks the whole filename and not just the suffix?

**Comment by eatyourgreens** [comment]
@vrooje is this still a problem? the check includes the `.` character but I'm not sure if it's being parsed correctly.
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/subject-set.cjsx#L18

**Comment by vrooje** [comment]
I haven't actually tried it in a while - need me to run some tests?
