### ISSUE TITLE
Personal stats doesn't increase the numbers for weeks

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2243]
(I haven't found such an issue anywhere..)
A PW volunteer, username: 141Dial34, has just reported that the personal stats on the Zooniverse profile page doesn't increase the numbers for weeks. It has been stuck on the same number even when the user keeps classifying and is always signed in. Can you look at it please?

I've asked whether it is a problem for PW only or for more projects. Waiting for an answer:
http://talk.penguinwatch.org/#/boards/BPZ0000001/discussions/DPZ00001w5?page=11&comment_id=56d4ed17d37555733e000566

**Comment by camallen** [comment]
I have their count at 698 classifications and last updated at 23rd Feb 2016. Does this sound about right?

**Comment by yshish** [comment]
Well, the user seems to be active these days on PW. Will make sure. Thanks!

**Comment by yshish** [comment]
Well, here are two answers from 141Dial34:

>Yes ,I see 698, & yes I have classified since then.I also changed browsers(have windows Vista) from chrome to Opera which has given me grief viewing videos in some sites -maybe this is my problem.I honestly dont mind the number not changing as long as it doesnt hurt your project stats.

>well what ever he did fixed it as it is now ticking over again.Yes it was 698 & I thought it was from changing browsers from chrome to Opera which has given me some grief with not being able to play videos at some sites.Thanks..

**Comment by camallen** [comment]
So it's working again? Note we didn't do anything. Please close if this is all sorted.

**Comment by yshish** [comment]
It was told to be working but I've just received a message that it's stuck again. So I won't close this issue yet.

**Comment by yshish** [comment]
The user says: 
>3 days ago it started working again & now stuck at 773. All other projects are working correctly. I just phoned someone & gave my details so they could sign in & do Penguin watch & it worked- the stats changed.So it must be me! They had firefox. I will change browsers again...back to Chrome...
Opera deleted & Chrome installed & stats work just fine.Ty for you efforts.

@camallen Shall I close the issue now?

**Comment by camallen** [comment]
Go for it
