### ISSUE TITLE
Fix vertical sorting in survey task

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2245]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

I think this may be already addressed and deployed per #2024 and #2085.
@amyrebecca is it correct that these are "done"  now?

@aliburchard Can you confirm if there is anything left to do here or do we have what we need?

**Comment by brian-c** [comment]
Working on this now.

**Comment by alexbfree** [comment]
Great news, thanks @brian-c ! :-)
