### ISSUE TITLE
Ensure we have a way to mark "fire" and "Nothing Here" 

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2246]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

This may be possible with @brian-c's new Combo Task.

**Comment by eatyourgreens** [comment]
Is @wgranger looking at this now?

**Comment by wgranger** [comment]
@eatyourgreens Yep, I've done a bit of work on this already. Hope to have a PR up soon.

**Comment by alexbfree** [comment]
just noticed the title is not too clear so i improved the wording.

**Comment by wgranger** [comment]
What is "fire" referring to?

**Comment by wgranger** [comment]
Closed with #2914
