### ISSUE TITLE
Custom Pages Mechanism

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2247]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

The ability to add an arbitrary number of extra named pages (e.g. About, Team, etc) in the builder which appear under a dropdown menu item at the end.

**Comment by mschwamb** [comment]
related to #1947

**Comment by alexbfree** [comment]
and #568

**Comment by brian-c** [comment]
Got started on this in the custom-pages branch, put it down when the navigation changed. Probably still something salvageable in there!
