### ISSUE TITLE
Ability for Zooniverse staff project builders to use black-on-white text in project pages

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2248]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

@aliburchard has specified that this is a must have for the move, as the current pages (being white on a photographic background) are too hard to read.

We need to either be able to force black text on a white background, or else have a very basic means to style pages. This doesn't need to be available in the project builder for all users.

@brian-c and @aliburchard and maybe @chrislintott probably need to discuss/agree the way forward for this.

**Comment by marten** [comment]
I say we just change the default style for everyone, to either a flat white background or a slightly translucent white. I'd also like to put in a max-width on the content area while we're at it.

**Comment by alexbfree** [comment]
good ideas Marten. We could also look at increasing line spacing to improve readability too.

**Comment by alexbfree** [comment]
I suppose one thing about using the plain white style on all the project pages is, where do we draw the line? do we lose the "background image for a project" completely? Will there be a smooth transition from backgrounded project homepage to white project pages? I guess this ties into #2249 which Grant is going to discuss with Jordan.

**Comment by marten** [comment]
We'd keep the background for the header and you'd still see it behind the homepage and the classify page.

**Comment by aliburchard** [comment]
Definitely need to keep the background for landing pages! Not sure about the classify pages, since it's often cluttered (great one for @jwbmartin and @mrniaboc).

For the text/about pages: maybe slightly translucent white background with max width over...the image? OR just white all around like the talk pages.

**Comment by jwbmartin** [comment]
Hey all as far as project builder things I have been playing around with some things. I have a few rough ideas to increase legibility below. Let me know what you think.

![classify_page-01](https://cloud.githubusercontent.com/assets/14332849/13467429/dc10dc06-e063-11e5-9c09-a9d4d4177af9.png)

![2b833914-b47c-11e5-8018-8f7f77873894](https://cloud.githubusercontent.com/assets/14332849/13467432/de7bbba0-e063-11e5-9c92-57cac8d66c01.JPG)

**Comment by alexbfree** [comment]
@jwbmartin Nice work! I especially like the first screenshot! 

Only one small tweak i would make, the Option buttons have the same grey as the background grey - maybe something brighter or darker would make them stand out more?

The second one looks good too, I assume that would fit into the same grey box as in the first screenshot. I wonder about maybe having some column/sidebars or maybe just more visual/graphic elements? The current Snapshot Serengeti pages are quite good I think - especially the icon-based submenu http://www.snapshotserengeti.org/#/about

**Comment by aliburchard** [comment]
@jwbmartin I'm loving it!

**Comment by alexbfree** [comment]
This is probably going to be addressed by #2331

**Comment by alexbfree** [comment]
@aliburchard In terms of the requirement for more readable text prior to porting Serengeti, has #2374 addressed the essentials? Can we close this ticket or is there more to do here?

**Comment by aliburchard** [comment]
yup, this addresses making the text readable.
