### ISSUE TITLE
How to specify a single-column "introduction"

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#225]
I have a short introduction that ends up being split into two even shorter columns. It looks bad:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Test10

How do I specify my 'introduction' so that it forms a narrower centered single column like in Snapshot Supernova?

**Comment by brian-c** [comment]
The columns thing doesn't work very well; will update.

**Comment by twhyntie** [comment]
Has this been merged/implemented? I'm still getting three columns in my projects...

**Comment by brian-c** [comment]
Looks like automatic deploys are being weird. I just did it manually.

**Comment by twhyntie** [comment]
Yup, that's working now. Thanks!
