### ISSUE TITLE
Import text content from Snapshot Serengeti into new Snapshot Serengeti PFE project

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2250]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

This will wait until #2247 is in place and will probably be done by Ali.

**Comment by alexbfree** [comment]
Thanks @camallen I didn't know that. Do you have the URL / do you know who owns it?

The task will need to remain open for now to track the text content migration, but i'll update the description.

**Comment by camallen** [comment]
https://www.zooniverse.org/projects/zooniverse/snapshot-serengeti

**Comment by alexbfree** [comment]
OK. Neither Ali nor I have got access to this project in Project Builder. @adam or @camallen we need one of you to add us both as collaborators please!

**Comment by alexbfree** [comment]
We have access now. Thanks @astopy
