### ISSUE TITLE
Improvements to Search page (like Ouroboros) 

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2252]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

There must be a search page which clearly delineates subjects from posts.
ideally it should allow to search posts OR subjects OR both. Possibly collections too.

posts should show snippets and subjects should show thumbnails - rather than the current page which shows everything big

tag filtering is nice to have

no strong views on "load more" vs pagination... there are pros and cons of both.

It must show results filtered to just the context of the current project 
- as with the project collections page #2804, there should be a way to remove the project filter and search the wider zooniverse for same search term.

**Comment by trouille** [comment]
The OldWeather mods (randi was the point of contact) listed these features for improving search in Talk:

- If you are at the top level it should search everything.
- If you are in a board it should only search the board.
- If you are in a discussion it should only search the discussion.
(This is particularly important if you are searching something like a geographical location or the definition of a word. You do not always want to find every occurrence.)
- If you are a moderator it should search hidden boards accessible to moderators.

I've posted them here so you have them in mind @alexbfree As we decide what are good ideas broadly for search in Talk, let's include these in the conversation as well.
