### ISSUE TITLE
Ensuring Preservation of Project Context

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2253]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

All views of text and subject content need to be, by default, filtered to Snapshot Serengeti content (or whatever project you are currently viewing the Talk for). 
At the moment this is true for hashtags and boards/threads, but not for collections, recents, and in some cases search results. 

We acknowledged the desire to make Zooniverse community more open and not completely hide other Talk content, therefore we propose an "on-by-default" filter for the current project which can be removed.

We decided that Collections should *not* be limited to only hold and only show subjects for the current project - however we agreed that for usability reasons, if technically doable, we would like to be able to filter lists of collections to only show collections that apply to the current project, or view all.

In general we agreed that for "minimum acceptable" filtering to maintain project context should be best effort - if we have technical difficulties in doing it at this stage we should just do as much as we can for now.

This will also be helped by fixing #2212.

This ticket strongly overlaps with #2252 and #2251 and they may end up getting developed in tandem.

**Comment by alexbfree** [comment]
Notes to self:

There are actually two recents pages right now:

1. project-specific e.g. `https://www.zooniverse.org/projects/aliburchard/wildebeest-watch/talk/recents`
2. user-specific e.g. `https://www.zooniverse.org/users/alexbfree`

Both use the same API endpoint (e.g. `https://talk.zooniverse.org/comments?sort=-created_at&page_size=20&section=project-6`) so shouldn't be too hard to unify. 
Right now, the project-specific one has a checkbox that includes/excludes subject comments. This adds/removes the subject_default=false endpoint from the When included, images are shown inline to the posts.  

Talk API doesn't seem to have a means to retrieve only subject posts, it can only retrieve all posts, or all non-subject posts. In the short term might be able to work around this by just getting the combined response and parsing it, but probably should modify the API slightly so you can specify the opposite of `subject_default=false` ie. subjects only. This would also allow separate paging/load more of subject vs. of posts.

Navigationally, will need to ensure the user's profile maintains some sense of current project context.
Currently this is outside of project context (per its URL) so will probably need to build a small tracking object in local storage or similar to keep track of current project ID. This would allow filters to be included (and enabled by default) on the recents page, as well adding nav options to return to the project's nav menus...

**Comment by eatyourgreens** [comment]
In terms of the site's information architecture, surely the way to preserve project context would be to use the URL? Eg. put project-specific user stuff under `/project_name/user/user_name`.

**Comment by alexbfree** [comment]
@eatyourgreens The problem is that some URLs don't have that, e.g. 
https://www.zooniverse.org/users/alexbfree
https://www.zooniverse.org/collections/alexbfree
https://www.zooniverse.org/favorites/alexbfree
... and yet, when visited from Project Talk, those pages need to maintain context.

Rather than change the URLs of those pages (which I don't think we can do because you still need to be able to access collections, favourites and user profiles/user recent comments in a Zoo-wide context) I am leaning towards passing the context as URL parameters.

Either that, or we have two alternative routes for these pages - with and without project context. But I favour the former, do you agree?

**Comment by eatyourgreens** [comment]
I'm saying create new routes in the router config, maybe still pointing to the same components wherever that's possible. That seems the simplest solution. So zooniverse.org/users/alexbfree has your global preferences and stats, but zooniverse.org/projects/zooniverse/snapshot-serengeti/users/alexbfree has info specific to Snapshot Serengeti.

URL parameters would work too, but you'll still need to think about your IA because either way you're creating new URLs, and links to those URLs somewhere.

**Comment by alexbfree** [comment]
yeah i'm not completely settled on which is the best approach. One thing I would like to ensure is that regardless of how you arrive at the user profile, recents, collections, or favorites page, it doesn't lose your context. Am also considering adding a context object to the top level pages in react (@amyrebecca's idea for the Geordi into Panoptes stuff) which would mean the current project, workflow, user, subject are always available

**Comment by alexbfree** [comment]
Noting another issue where we are seeing issues with project context being lost - see #1877 / #2068. This could be fixed independently, or as part of this wider effort. The only links that should ever remove your project context are (i) the "Talk" link at the very top of the page (ii) a specific link to a Zoo-wide talk thread or post and (iii) when you deliberately remove the yet-to-be-implemented project scope filter that this ticket's feature will introduce.

**Comment by alexbfree** [comment]
now starting to work on this

**Comment by alexbfree** [comment]
have developed a solution for collections and favourites, just need to link it up with recents and user profiles, then update all the links out from project talk to go to the new URLs

**Comment by alexbfree** [comment]
Addressed by #2804 - awaiting merge.
