### ISSUE TITLE
Project-specific navigation help for moving between "old" and "new" Serengeti

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2254]
One of the tasks we identified for enabling the move of Snapshot Serengeti to Panoptes.

Once we are in a world where there are two Talks (old & new), and two types of collection, and two types of subject view, we need to make sure that every page has a clear navigation to "the other type". Users _will_ get confused.
- Old Talk should have banners/obvious links pointing to, and encouraging, people to use the new Talk (possibly a Globally Featured Discussion?)
- Panoptes collections page should have a link to "view your legacy collections" in old.snapshotserengeti.org
- Panoptes talk pages should have a link to "search for older Snapshot Serengeti Talk posts and content" which would just link to the old search page

Also once this is done, all boards on Old Talk should be locked. Though subject comments and collection editing is probably still fine.

**Comment by mkosmala** [comment]
@aliburchard I don't know if this is a good spot to put this, but I saw this issue and it raised alarm bells. If we port Snapshot Serengeti, we lose language translation. I was chatting with Jarrett the other day about this. He doesn't want to port Floating Forests for the same reason.

**Comment by aliburchard** [comment]
Hey, yup, was going to initiate an email conversation about this soon. We really need to start moving Ouroboros projects to Panoptes, because the old projects are very difficult to maintain and we simply don't have capacity. There are many benefits to the move, but I'll flag this as a concern. 

What languages has SS been translated to so far?

**Comment by srallen** [comment]
A few features are being discussed in this issue. If it's still important and needs comment, they should be reopened and as separate issues.
