### ISSUE TITLE
update help text for survey task questions.csv

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2256]
Now that the survey tasks are combined, we need to update the help text to reflect the addition of include and exclude columns, and to reflect that the csv accepts or requires ; instead of c between possible answers.

*not sure how the "question sets" for making "one of these questions" required is handled; I'm okay leaving that out of the docs if we want to keep it as a hidden feature because it's really confusing.

**Comment by aliburchard** [comment]
@amyrebecca (or maybe @brian-c ) can you also please clarify the additional changes made to formatting for these csvs? We're having a lot of issues with projects trying to launch. It looks like the reference photos for the "image" column now need semicolons as well, but maybe also the headers for the characteristics file?

Are there any other changes to the required formatting?

**Comment by aliburchard** [comment]
@chrislintott good news is that this seems to be the only lingering *incorrect* in-line help text on the editor because @marten very kindly helped me edit the markdown for the others.  

@mcbouslog - we'll probably want to revisit some of the help text with the fancy new editor -- wondering if you'd be game to tackle this in the process? (Maybe we can do it all together when I'm in Chicago next month? Because I'm not actually leaving, no matter how hard I try...)

**Comment by mcbouslog** [comment]
Definitely want revisit the help text, and I'd be happy to help! If I can't get to sooner, while you're in Chicago would be a great time to work on together.

**Comment by aliburchard** [comment]
sweeeeet!!
