### ISSUE TITLE
How do I pass an avatar and background image?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#226]
Not sure if this is a front-end or back-end issue, so tagging @camallen and @edpaget here, too. 

In creating a project, I pass the names of files containing an avatar and a background image. I don't get any errors. But the avatar and background image don't show up on the front-end.
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Test10

Am I supposed to be passing something other than a file name? A URL? If so, how do I upload the files so that I have a URL to pass to the project creator?

**Comment by edpaget** [comment]
Yeah right now those are just URLs. I'm going to have that changed by the time of the launch see zooniverse/Panoptes#443

**Comment by mkosmala** [comment]
Right. Okay. What's the projected time of launch? (And can I use external URLs in the meantime? Want to run a beta ASAP...)

**Comment by twhyntie** [comment]
[UI] Just to check, there's no way to set the project avatar via the UI at the moment, right? i.e. I should see everything greyed out like this: 
![avatar-ui](https://cloud.githubusercontent.com/assets/1625332/7436694/f4227adc-f047-11e4-858b-7bc6f08bb315.JPG)
(The clue being the `TODO`)

**Comment by twhyntie** [comment]
...and the same for the background image:
![background-ui](https://cloud.githubusercontent.com/assets/1625332/7436759/761f4fc4-f048-11e4-85ee-a6c792575578.JPG)

**Comment by aliburchard** [comment]
@mkosmala @edpaget can we close this issue or is there still missing functionality?
