### ISSUE TITLE
Feature request: Projects page per user

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2261]
In the same way that any user can view other users' public collections, it would be nice if they could view others projects.

At the moment a URL such as https://www.zooniverse.org/projects/alexbfree/ gets 404 not found.

I think it would be fairly easy to serve up a version of https://www.zooniverse.org/lab when such a URL is visited, filtered by the user specified from the URL rather than the current user - and hide any edit/create links.

**Comment by mschwamb** [comment]
personally on a science team side, In slightly dislike  that my username is the project url as it's a team effort I just happened to be the one who started the project and got project owner, so if there is going to happen I'd like to see the projects someone has not just be the ones an account owns, but the ones they're list on the research page for as collaborators, tester, moderators, etc.

**Comment by alexbfree** [comment]
Hi @mschwamb. I had something similar in mind; the current Lab page breaks it down into your own projects and "collaborator projects" - the user project page would need to do something similar to at least separate ones that that user built from ones they are a collaborator on. 

I agree with your observation that giving a single user credit for a project is not perfect - but I don't see anything changing on that front soon as the project ownership is pretty well baked into the code. Perhaps team management might be something looked at down the line - then a team could own a project. But I wouldn't hold your breath!

**Comment by camallen** [comment]
user groups (teams) can own a project, no one has set it up like that though.

**Comment by alexbfree** [comment]
@camallen when you say "no-one has it set up like that" do you mean the API supports it but the project builder doesn't, or do you mean we allow people to do it but no-one has used this feature?

**Comment by camallen** [comment]
the api supports it but the ui interface hasn't set it up this way, hence no one has built a group owned project yet. Think organizations on github.
