### ISSUE TITLE
Add Project Builder support for external CSVs

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2264]
This just came up in conversation with @camallen , @marten and myself.

At the moment if you have a CSV file to create a subject set from external images, you have to either SSH into a Panoptes instance and run a rake task, or run a Jenkins job. It would be nice to be able to just add your manifest file directly to the subject set builder.

Creating this ticket so that I or whoever gets to it first can add this feature

**Comment by eatyourgreens** [comment]
Pinging @simensta since she talked about this on the front-end hangout yesterday.

**Comment by aliburchard** [comment]
+1! (This way I could create new subject sets for Wildcam Gorongosa without having to bug Marten...)

**Comment by srallen** [comment]
I also have an open issue to add this feature into the [panoptes-subject-uploader](https://github.com/zooniverse/panoptes-subject-uploader/issues/7)

**Comment by eatyourgreens** [comment]
Fixed by the python client, right?
