### ISSUE TITLE
getting blank page for Zooniverse.org while using Safari on Snow Leopard 10.6.8 

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2269]
User KateTaylor2 is getting a blank page for Zooniverse.org while using Safari on Snow Leopard 10.6.8. It never works. She hasn't tried any other browser. She has no access to the list of Zooniverse projects due to it.

**Comment by eatyourgreens** [comment]
I'm afraid we don't support Safari version 5, which is the version on Snow Leopard, any more. The home page could be better at showing an error message, rather than just a blank page, when the browser isn't supported.

**Comment by camallen** [comment]
Don't we do some reporting via [here](https://github.com/zooniverse/Panoptes-Front-End/blob/fc5a014b72aaeabc95867aae3e94634a4f982538/views/index.ejs#L30)? 

@yshish can you get them to install Chrome / Firefox and try again?

**Comment by yshish** [comment]
@camallen Thanks. I'm going to ask her..

**Comment by srallen** [comment]
Closing as the browser is older than what we support.
