### ISSUE TITLE
Unable to assign a subject set to a workflow

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#227]
Hello again,

New error now - when I try to assign a subject set to a workflow by ticking the box next to the subject set name and then save the workflow, I get the error message:

`param is missing or the value is empty: workflows`

When I view the project "Classify" I get the error:

`Error: No subjects available for workflow 806`

Again, probably a **Panoptes** issue but I'm only dealing with the Front End...

Thanks again, Tom

**Comment by edpaget** [comment]
@twhyntie This is just a UI Error. The subject set is added when you tick the box as opposed to when you hit save. There's a bug that causes the save button to become active again.

**Comment by twhyntie** [comment]
@edpaget 

Tried again (ignoring the save button) with a new workflow and subject set (but same project) - trying to classify now gives:

`Error: No subjects available for workflow 808`

Also - deleting a workflow appears to delete the subject set too; don't know if that's related, so won't raise a separate issue for now...

Cheers, Tom

**Comment by edpaget** [comment]
Sorry I think that may be an issue with our experimental new subject selection stuff. I'll hopefully have that addressed by tomorrow. In the meantime can you recreate your workflow and subject set and post a link to the project?

**Comment by twhyntie** [comment]
@edpaget Thanks - the project is [here](http://demo.zooniverse.org/panoptes-front-end/#/projects/twhyntie_lsc/Monopole%20Quest%20-%20Timepix%20Test%20001) (I think I've made it public). I've recreated the workflow and subject set as requested.

**Comment by twhyntie** [comment]
@edpaget Update - in case it helps, in testing whether the "making it public" worked, I signed out... and can now do the classifications with the recreated workflow and subject set. Signing in and trying again I get the `No subjects available...` error. So I guess the error is related to this new-fangled user queue thingy? :-)

Thanks again, Tom

**Comment by edpaget** [comment]
@camallen I think this behavior is due to not properly handling the case where there's no seen_subjects for a user. This is spec my most recent PR [here](https://github.com/edpaget/Panoptes/blob/hatmb-subject-sets/spec/models/set_member_subject_spec.rb#L73-L80) and resolved [here](https://github.com/edpaget/Panoptes/blob/hatmb-subject-sets/app/models/set_member_subject.rb#L48). I can extract it or we can wait until that PR is ready to merge

**Comment by edpaget** [comment]
@twhyntie this should be fixed. You still have to reload the page once, but I'm most of the way through fixing that problem.

**Comment by twhyntie** [comment]
Yup, works, lovely jubbly. Thanks!
