### ISSUE TITLE
Project builder hangs when viewing subject

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2272]
I've uploaded a subject to a project, and then try to view it by pressing the "eye" icon. I get a pop-up with a spinning planet and no way to close the pop-up.
![screenshot](https://cloud.githubusercontent.com/assets/1066340/13650542/2d505882-e611-11e5-8633-8e3782b49b83.png)

**Comment by camallen** [comment]
Can you retry after reloading the page?

**Comment by mkosmala** [comment]
When page is reloaded, the image shows up and I get a closing 'X'. The above issue happened immediately after subject upload.

**Comment by camallen** [comment]
Its a known issue, basically the put fires but no subsequent get req runs to get a new SRC URL for the subject image.

**Comment by mkosmala** [comment]
Oh, okay. I *did* search for the issue before posting, but didn't find it.

**Comment by mschwamb** [comment]
If it helps I reported it in #981

**Comment by mkosmala** [comment]
okeydoke.
