### ISSUE TITLE
ability to specify which subjects should be gold standard subjects for experts to review

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2274]
For Planet Four: Terrains I want to do something similar to how we're confirming and checking the accuracy of the citizen science approach, but having the science team classify a subset of the subjects. It looks like you can only classify as an expert and get what's currently live and is whatever their subject queue has in it. The subjects I need the experts to review will be retired as well. 

I think a feature enabling a csv to be uploaded specifying the subject ids for existing subjects for  gold standard classifications would be handy. 

cc @aliburchard

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
