### ISSUE TITLE
Small UX issue with media uploader

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2276]
I may be able to take a look at this myself later, but am just making a note for now, whoever gets to it first can tackle it....

I noticed that when you drag/drop a file or files over the image upload box, you lose "drop focus" if you hover over an existing image within the set - this means that when you drop images on an existing set, you can accidentally just load the image up in the browser instead of uploading it.

I think it should be fairly easy to tweak the CSS classes such that the "drop focus" is active regardless whether you hover over the container or an element within it.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
