### ISSUE TITLE
UX: Add a panacea save button to Project Builder pages? Enable return-to-save on text fields?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2277]
As we all know, the Project Builder saves each text field automatically when you lose focus from that field.

However, this can sometimes create a confusing user experience where the user doesn't have an obvious means to save other than clicking on a "blank area" of screen. It's not immediately evident how to preserve your changes.

For example, when you want to create an empty subject set, ready for importing externally-hosted subjects, there is no obvious place to click after entering your title.

I suggest we do either one or both of:
1. Allow user to to trigger save in a field by pressing return (obviously this wouldn't work for multi-line fields)
2. Provide a "save" button at bottom of every page. It wouldn't need to actually do anything except perhaps a visual change or message from clicked>"saving">"saved" but it would give the user peace of mind and a cleaner user experience.

**Comment by mschwamb** [comment]
I've found it a bit confusing at first see ticket #581

**Comment by srallen** [comment]
Closing in favor of #2895
