### ISSUE TITLE
Bug: Number of subjects in subject set not shown correctly after uploading subjects via rake task

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2279]
After uploading via the rake subject:import task, all my subject sets contain the correct subjects, and pagination is correct, but the message at the top of the list says this set contains zero subjects.

![screenshot 2016-03-10 19 54 10](https://cloud.githubusercontent.com/assets/1473244/13682534/129b4878-e6fa-11e5-99d2-943387ce6a97.png)

The number stays at zero when I move to the next page.

**Comment by srallen** [comment]
This is a known issue, fyi: #2124

**Comment by alexbfree** [comment]
closing as duplicate of #2124
