### ISSUE TITLE
Bug: Issue when creating more than one subject set - incorrect save ordering?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2281]
A minor UX bug, which will often be hit if adding several blank sets at once (e.g. for "external subject" imports)

Steps to reproduce:

1. Click "New subject set"
2. Click into the subject set name. Delete the text that's there and overtype "Untitled subject set" but don't click anywhere or lose focus yet.
3. Ensuring it is the very next thing you click, click New subject set button again.

You will see this error:
![screenshot 2016-03-11 15 42 09](https://cloud.githubusercontent.com/assets/1473244/13707087/e6a3120e-e79f-11e5-90e6-418150c96072.png)
even though the subject set has saved OK.

Possibly an issue with the way the subject set name is read from the form, not saved before it is checked even though focus is lost.

Could be alleviated / be hit less often if #2277 is done.

**Comment by alexbfree** [comment]
possibly related: #2752

**Comment by camallen** [comment]
this is dup of #1924 the default name is the same one and subject set names are uniq for projects in the API.

**Comment by alexbfree** [comment]
ok closing as dup
