### ISSUE TITLE
Ability to empty a subject set

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2282]
Very low priority this one, but it could be useful in certain circumstances, especially when working with subject sets containing external subjects.

Something I found myself doing a lot is regenerating subject sets to fix/improve metadata, tweak subject set content etc. At the moment the only way to do this is to completely delete the subject set and create a new one.

If there was an "empty this set" option, perhaps a button next to "delete this set", it would mean that you could re-run import tasks etc against the same subject set ID, without needing to jump through all those hoops.

**Comment by eatyourgreens** [comment]
For tasks like this, you might be better off writing scripts to update your subjects via the Panoptes API, rather than dropping the subject set and importing again:
http://docs.panoptes.apiary.io/#reference/subjects
http://docs.panoptes.apiary.io/#reference/subject-set

**Comment by alexbfree** [comment]
That's an idea. but i suspect delete-and-reupload is probably quicker, given it's not always the same change each time. That said, it would probably be a useful exercise for me to write some scripts against the subject API, so thanks for the tip. 

I think delete-all is still a useful prospect, there are probably other scenarios where users might like this.

But there are many more important ideas. Happy to consign this to the "one day, maybe" bucket :-)

**Comment by camallen** [comment]
any reason why you just wouldn't delete the subject set and start again? It does the exactly empty functionality you want.

**Comment by alexbfree** [comment]
@camallen If you have to do that for multiple subject sets (because you realise you missed a metadata column off all your CSVs) for example it's a real pain. Because not only do you then have to create new subject sets, you then have to update all your rake import commands to use new subject set IDs. At least if you could empty the sets, you could re-run the same import commands without having to go through the exercise of looking up every subject set ID and editing every import command.

**Comment by eatyourgreens** [comment]
Going to close this, since we're moving towards managing subject sets with zooniverse/panoptes-cli
