### ISSUE TITLE
Survey task (filter task): Exclude column doesn't work

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2283]
@amyrebecca @brian-c this column doesn't seem to be working. I'm trying to build an example project and documentation for researchers that demonstrates the new survey task, but excluding Human from specific questions (in this case "how many") seems to just shuffle the order of the questions.

![screen shot 2016-03-11 at 17 27 41](https://cloud.githubusercontent.com/assets/6217406/13710141/8e027882-e7af-11e5-882a-b90a0e0f1230.png)
![screen shot 2016-03-11 at 17 27 09](https://cloud.githubusercontent.com/assets/6217406/13710143/8e0654ac-e7af-11e5-854c-15addb40e048.png)

It could be that uploading a new questions csv with exclude doesn't overwrite previous csvs, but if that's the case 1) Is there any way to change that, or 2) if builders need to delete all survey data and reload all four csvs when they make any changes, I need to message that very clearly. 

@brian-c you're a collaborator on this project (https://www.zooniverse.org/lab/2083) - and @amyrebecca if you give me your zooniverse name I'll add you too. Thanks!

**Comment by aliburchard** [comment]
@mcbouslog this is something we might want to keep an eye on. If the csv uploader doesn't rewrite all existing workflow data, this might still be an issue.

**Comment by mcbouslog** [comment]
I believe the recent editor refactor (#2894) fixed this, but please report if issue again noted.
