### ISSUE TITLE
Be consistent in format for way of listing users on the collaborators page in project builder 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2284]
If there is a display name it shows that, otherwise it shows the username. It's hard to tell which is which if the user doesn't have a displayname. It would be helpful if both were showed on the page. Especially since you need to add new collaborators by username now and not displayname.  'Michael Aye' is the displayname. Rest in this case are usernames. It would be helpful if both displayname and username show up. 

<img width="816" alt="screen shot 2016-03-13 at 11 00 07 am" src="https://cloud.githubusercontent.com/assets/753325/13726606/d7f2c2f6-e90a-11e5-9b26-d5b71efbe333.png">

**Comment by aliburchard** [comment]
Love this. Perhaps one in bold and one in parentheses or italicized?

**Comment by camallen** [comment]
we should always default to the login name and not the display name.

**Comment by mschwamb** [comment]
I don't have a strong preference, but I do think if you're not going to have that search then the research pages need to be fixed to show username and display name. The research page only shows my display name https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/research

**Comment by alexbfree** [comment]
Just adding a link to #2288 - when one of us cleans up this display we may want to tackle both at the same time. We could also consider showing the avatar for each user.

**Comment by vrooje** [comment]
Avatar + username + display name would be really helpful for people verifying they've added the correct person! But I agree username should always show.

**Comment by mschwamb** [comment]
This was added to the public team page for a project, any chance this could be added to inside the project builder? It would help that you've added the correct person especially if the displayname is a first and last name

**Comment by mschwamb** [comment]
Any chance the same kind of formatting  that's on the team page that include  both display name and username could be done on the collaborators page in the project builder?  Especially to know you're adding the right person to your project.
