### ISSUE TITLE
favorite, collections, and metadata button shifted over from edge of image in classification interface

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2285]
@brian-c  it looks like a recent change creates extra space that pushes over the task text and tools on all projects. I think it's also causing the image to display a bit smaller than it would normally would if the edge of the collection button lined up with the edge of the image  Can someone look into that?

<img width="1143" alt="screen shot 2016-03-13 at 4 50 37 pm" src="https://cloud.githubusercontent.com/assets/753325/13727804/3a1bd928-e93c-11e5-83a5-95bc3e609f78.png">

<img width="1133" alt="screen shot 2016-03-13 at 4 50 15 pm" src="https://cloud.githubusercontent.com/assets/753325/13727805/3bc14b82-e93c-11e5-9544-7fe574b5be9c.png">

same thing in chrome and happens whether you're logged in or not

<img width="1118" alt="screen shot 2016-03-13 at 4 53 45 pm" src="https://cloud.githubusercontent.com/assets/753325/13727808/4a745840-e93c-11e5-9733-eed7a79bce8f.png">

**Comment by eatyourgreens** [comment]
I think this must have been introduced with the zoom feature in #2199. I should be able to fix it tomorrow.

**Comment by mschwamb** [comment]
hey @eatyourgreens and @brian-c Yeah that fixed it in other browsers but  caused another issue now the image overflows the box and blocks part of the task text in firefox and the responses and tools are on top of the image which means people in firefox don't know exactly know what to do since they can't read the text. This is only a firefox issue. Looks fine in Chrome and Safari

![Uploading Screen Shot 2016-03-16 at 10.14.25 AM.png…]()
<img width="1140" alt="screen shot 2016-03-16 at 10 14 12 am" src="https://cloud.githubusercontent.com/assets/753325/13800054/0f7aa7d2-eb60-11e5-955f-5d4b7d2d0322.png">

**Comment by alexbfree** [comment]
Thanks Meg, I am looking into this now. We think it might be caused by a recent change #2302. Will update soon.

**Comment by alexbfree** [comment]
This is deployed now on Zooniverse.org. Let us know if there are any further issues.

**Comment by mschwamb** [comment]
Thanks very much @alexbfree. Looks back to normal on Firefox.
