### ISSUE TITLE
polyline tool

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#2286]
Hi guys,

Hoping that you might consider adding a polyline tool as an option. We're thinking of building a workflow that involves drawing river systems and geological boundaries and the polygon tool can be used but is very messy.

Any thoughts?

thanks

**Comment by vrooje** [comment]
We have a curve tool already implemented but it has to be enabled by an admin - is this for Fossil Finder or a new project?

**Comment by vrooje** [comment]
PS: I've added you to an in-progress private project I'm working on that uses the tool so you can see if it would suit... should be in your zooniverse.org/lab project menu.

**Comment by CKrawczyk** [comment]
@vrooje If you are talking about the bezier curve tool it is not behind an admin flag, it is available for any project to use.

**Comment by vrooje** [comment]
Even better!

**Comment by AdrianEvans** [comment]
I've played with the bezier tool. The implementation is good for closed
objects since as with the polygon tool you click on the first point to
close the tool.

What would be neat is if a double click would also end that instance of
tool use so another could be started. I've found that if I want to label
multiple curvilinear features - think river channels from high altitude
ground imaging. the only way to do this is to re-click on the tool button.
This could work

A REALLY cool option would be a freehand tool that followed the cursor once
the left button is clicked and held until it is let go. I wonder if this is
possible at all?

**Comment by vrooje** [comment]
> A REALLY cool option would be a freehand tool that followed the cursor once
> the left button is clicked and held until it is let go. I wonder if this is
> possible at all?

This exists now, right? The spiral-arm drawing tool in Galaxy Zoo 3D drew polygons but also, if you held the left-mouse down, it drew freehand.

**Comment by eatyourgreens** [comment]
I'm closing this because Etch-A-Cell uses freehand drawing.

As a side note: I also wonder if this type of task is easier with a touchscreen and stylus than a mouse eg. on a Microsoft Surface with their nifty electronic pen.
