### ISSUE TITLE
Add usernames to the research pages

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2288]
The search for private messages uses usernames, but the research page only lists username if there is no display name. So on Planet Four: Terrains it shows 'Meg Schwamb' for me, but a volunteer would need to message mschwamb.  To make it easier for volunteers to message moderators and the research team, can the username always be displayed even if there is a display name on the research page

**Comment by alexbfree** [comment]
Maybe an even better option here might be to have a little "message this person" link next to each name; or perhaps better still, the name is clickable and it takes you to that user's profile (from where you can message them)

**Comment by mschwamb** [comment]
I like the cleanness in the simplicity of the current design of the research page, so I'd rather see a link to profile than have a button for messaging a researcher. But that's only my personal preference/style.

**Comment by alexbfree** [comment]
Yes, I agree, click to go to profile it best.

**Comment by vrooje** [comment]
duplicate of #2218

**Comment by mschwamb** [comment]
closing to add to #2218
