### ISSUE TITLE
Can't create new discussion

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2289]
Trying to create documentation for the survey task but am getting this error: 

![screen shot 2016-03-14 at 12 09 37](https://cloud.githubusercontent.com/assets/6217406/13744124/ba30247e-e9dd-11e5-891c-02a73f94813c.png)

**Comment by aliburchard** [comment]
Update: the board is created, but I have to refresh the page to see that it was successful.

**Comment by trouille** [comment]
@aliburchard I was trying to recreate this error in WI Wildlife Watch (public) and also in Gravity Spy (not yet public), but wasn't able to. In both those, we can create new discussions with no errors and without having to click refresh.

**Comment by aliburchard** [comment]
Nope, hasn't happened again, so I'll close for now.
