### ISSUE TITLE
No subjects error on Chrome on Mac

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#229]
Not sure if this is front-end or back-end, so including @camallen and @edpaget.

I have a tester who is getting the error message
```
Error: No subjects available for workflow 804.
```
when she clicks on the "4_ComplexAMOS" workflow for this project:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season%20Spotter%20Test15

But she only gets it on her Mac when she's using Chrome. She's tested it on five browser-OS combos and sent me the following:

Mac OSX 10.10.2:
**1.  Google Chrome 42.0.2311.90 ->error**
2. Safari 8.0.3 ->works fine

PC Windows 7:
1. Google Chrome 42.0.2311.90 ->works fine
2. Safari 10.0.9200 ->works fine
3. Firefox 24.6.0 -> works fine

**Comment by edpaget** [comment]
This is related to #227

**Comment by camallen** [comment]
@mkosmala was the user logged in on all the different browser combinations?

**Comment by twhyntie** [comment]
Hi @mkosmala - as @edpaget notes, I see the same error (independent of OS/browser) when I'm logged in (see [#227](https://github.com/zooniverse/Panoptes-Front-End/issues/227)). When I'm logged out it's fine... is this the same/similar issue?

**Comment by mkosmala** [comment]
@camallen She says she gets the error whether or not she's logged in on Chrome on Mac.

**Comment by camallen** [comment]
@mkosmala just tested on mac chrome and it worked for non-logged in users. Still failing for logged in users though, a fix is coming.

**Comment by edpaget** [comment]
@mkosmala this should be working now for logged in users. Unfortunately you still need to refresh the page once. I'm working on fixing that and it should be ready later today.

**Comment by twhyntie** [comment]
Works for me now, thanks :-)

**Comment by mkosmala** [comment]
Works for my tester now!
