### ISSUE TITLE
UX: Subject Set List should be in alphabetical order

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2291]
Currently if you have more than a few subject sets it can be hard to find the one you want. The current ordering seems to be fairly arbitrary; alphabetical would be more useful.

![screenshot 2016-03-15 11 05 12](https://cloud.githubusercontent.com/assets/1473244/13775708/0cdfde9c-ea9e-11e5-98e6-f4a8bb5cc563.png)

**Comment by alexbfree** [comment]
After the Panoptes fix, the list within the Workflow editor is now sorted correctly, but the list on the left sidebar is still randomly ordered; looks like the subject sets are retrieved for the left sidebar by a separate call to which we are not passing the sort parameter - so this can be fixed in front-end by adding that parameter. keeping ticket open for now until we've fixed in both places.

**Comment by rogerhutchings** [comment]
They're sorted now, with the caveat that a newly-created set gets added to the bottom.
