### ISSUE TITLE
API call to store a crop of an image on AWS

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2298]

**Comment by eatyourgreens** [comment]
@amyrebecca check out zooniverse/static-crop. It might be exactly what you need for this: a cropping service for images we host eg. https://imgproc.zooniverse.org/crop?w=150&h=150&x=300&y=175&u=panoptes-uploads.zooniverse.org/production/subject_location/90a3b642-55e2-4583-a4fb-2f0abeb5b285.jpeg

**Comment by amyrebecca** [comment]
whoa! thank you :) this sounds pretty much ideal
