### ISSUE TITLE
Adding frontend exception notifications

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes-Front-End#2306]
I know they're usually pretty noisy due to errors that happen when people have weird plugins installed. However, having this in place (e.g. Honeybadger) is probably still beneficial just looking at the overall error rate, is that goes up significantly it's a good indication that broke something.

Should we add this?

**Comment by srallen** [comment]
I think this is a good idea. +1 from me.

**Comment by rogerhutchings** [comment]
#350
