### ISSUE TITLE
Ability to re-order Links in Product Builder

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2307]
Something I just noticed while adding a new link to the project builder... noting it here until I or someone else gets to it.

Right now there is no way to re-order the links to external pages, for example if you want to add a new one at the start.

The workarounds are either to copy and paste the text "downwards" from cell to cell, freeing up space at  the top, or to delete all links and add new ones.

The former has the disadvantage that bad links will temporarily be saved (due to autosave).
The latter has the disadvantage that the URLs are lost and you have to temporarily paste them elsewhere.

We should add a little drag icon to each row so you can re-order.

Not high priority in the grand scheme of things, but important for the usability of that feature.

**Comment by srallen** [comment]
This should be as simple as adding [zooniverse-ui/drag-reorderable](https://github.com/zooniverse-ui/drag-reorderable) for the link array. Similar to how it works for the workflows in the sidebar.
