### ISSUE TITLE
Panoptes demo - thanks!

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#231]
Not an issue _per se_, but I've just showed one of the test projects to the [MoEDAL](http://moedal.web.cern.ch/) software team and they're hugely impressed :-) ([slides](http://indico.cern.ch/event/390747/contribution/4/material/slides/0.pdf))

The new workflow editor and drawing tools went down particularly well - thanks so much everyone!

(cc @chrislintott )

**Comment by camallen** [comment]
:clap:

**Comment by karenlmasters** [comment]
Adding to this, we tried out using "Galaxy Zoo for Year 5" today with some real Year 5 students (5th Grade) and it went pretty well. :)
