### ISSUE TITLE
Avatar and background do not show in the project builder at upload 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2317]
Possibly related to #1065 - When I load an avatar and a background image, they upload successfully, but it looks like the upload failed as the window for the images remain blank. Only refreshing the pages shows the avatar and background after upload. I'm using Firefox on Mac version 45.0

**Comment by alexbfree** [comment]
I've seen the same issue on Chrome

**Comment by camallen** [comment]
This is the same as https://github.com/zooniverse/Panoptes-Front-End/issues/981#issuecomment-118775406. The resource is uploaded via a PUT but never refreshed to use the GET resource URL's. An automated state refresh after success on upload would fix them.

**Comment by mschwamb** [comment]
Thanks @camallen . I imagine for someone who's not worked with the platform before, their first thought would be that something is wrong and the upload wasn't successful. If it's an easy fix I think it would go a long way to helping new project builders since adding a background and avatar are the first things I do when starting a new project and I imagine that's similar to other project builders.

**Comment by camallen** [comment]
Agree re the user experience and most likely not that hard to fix. @alexbfree any thoughts on updating the component data after success on the PUT?

**Comment by mschwamb** [comment]
I've hit this again and had to re-remember  this bug exists for a demo project I needed to construct. I think this is pretty confusing to new project builders. It seems like a simple fix that would go a long way for new project builders.

**Comment by mschwamb** [comment]
I ran into this demoing the project  builder and had to gloss over this bug by quickly reloading the page when I added the background img so people looking over my shoulder could see the background img was there. Backgrounds and avatars  are one of the first things people add to a project while trying it out and the expectation is that if the upload is successful, it will show you the background in the greyed box as there is no other message for successful upload. When you see the gray box and not your image, you think something went wrong, and this is the first thing project owners are likely doing when they start in the project builders

This seems like an easy fix that would make a  difference for the experience of new users with the project builder   cc @srallen
