### ISSUE TITLE
Request for image other than the 'avatar' for Projects page

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#232]
The avatar that gets used for projects gets used on the Projects page. But what looks good in a small little square image does not necessarily look good when you chop off the lower half and blow it up. Note that for the Zooniverse logo it's fine. But it won't be fine generally. I think the avatar I'm using for project "Season Spotter Test15" looks pretty bad when you chop off the lower half. (Also, I could use a higher-res image to get rid of the blockiness, but do you really want a high-res image for the little icon that gets used when a user is actually in a project?) Alternatively, if you don't want to allow a different image here, could you at least use the whole image and buffer it on either side with some whitespace?

**Comment by mschwamb** [comment]
Since it's a much larger image region and not circular like the avatar circle for project builder projects, would it be possible to have a spot in the project builder where one could upload an image specifically for the project page placard ?

**Comment by mkosmala** [comment]
+1

**Comment by simoneduca** [comment]
Closing this as it's now possible to upload a project avatar in the project builder.
