### ISSUE TITLE
Season Spotter Questions statistics are not updating correctly

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2321]
I did 5 classifications on Season Spotter Questions several minutes ago. But the "Classifications" ticker on the project home page incremented by only 2.

**Comment by mkosmala** [comment]
Hmm, I can't recreate this. Closing it now and will reopen if it happens again.

**Comment by camallen** [comment]
@mkosmala those stats can get out of sync, it's related to how we count things in the api. I've got to overhaul the whole thing soon.
