### ISSUE TITLE
Using External APIs

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#2324]
I'm wondering what might be the best way to store information in preparation for making a call to an external API. Initially, I was thinking of adding a property to the workflow resource that would identify which API would be used, but this wouldn't be robust enough. Chances are we will be making calls to other APIs in the future, so it would be nice to have a place to store this information.

It's possible that a separate summary resource might be needed that would collect information from a classification in preparation for sending it to an external API.

**Comment by camallen** [comment]
@wgranger what will this call do? Send classification data from the UI to the external party? Or just pull data into the UI?

**Comment by wgranger** [comment]
This particular call will take information from a classification and construct a query string that will link to the World Wide Telescope API. A user would be able to access this link at the end of a classification. However, the option to link to this API will only appear if the Panoptes API knows that this project allows access to another API.

**Comment by camallen** [comment]
Sounds like it's just a flag on the workflow configuration / project configuration json objects that the UI can use to turn on the link creation.

Just be careful about updating these as you have to include the whole representation, i.e. you can do a partial update.

**Comment by wgranger** [comment]
So, in thinking about this, it looks like there are a couple items missing from the backend. In the classification configuration, it would be nice to have a classification_summary item, which is a string that defaults to null. 

We could also use the same classification_summary item in the workflow configuration to help us identify which kind of API we will be using for the API call. This will help us remain flexible

**Comment by camallen** [comment]
I'm really not getting what we're trying to do on this. 

Couldn't the client / frontend just submit a classification to our api (using the current format) and then create the secondary data payload you need for the external api?

**Comment by amyrebecca** [comment]
You're right, the classifications won't change at all. What we need is just a field on the workflow and (optionally, but preferably) on the classification to instruct the front-end to use an extra react component to display the links, which we've already written the code to do. We want people who are designing workflows to be able to set a flag to show WWT links, and it would make our lives way easier if that were also on the classification since we're already displaying the classification summary at the time we need to draw the links.

**Comment by camallen** [comment]
I'd use the workflow configuration object to specify the workflow is using the external api and you can add data to the classification metadata object (it's mostly a free form json object) see [here](https://github.com/zooniverse/Panoptes/blob/6237b1df643c8464ecb1cab868088a2bb3ada083/app/schemas/classification_create_schema.rb#L16)
