### ISSUE TITLE
simple stats page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2326]
I found for checking whether Planet Four: Terrains was close to running out of data, I was calling for the subjects and annotations csv file when  I wanted the number of subjects completed in the subject set and how many classifications per day.  I think it would be really handy to have some stats like Ouroboros projects have without having to download the subject csvs and classifications. 

What about having a page in the project builder that had stats that ran once a day/ looked at current project counters?  Number of registered users for the project, and then for each work flow: the number of total classifications and number of classifications per day for the past N days. For each subject set: whether its live or not, how many subjects are in there and how subjects are retired and % completion for each workflow. 

The Ouroboros stats graphs are really nice, but even being able to get the classifications numbers per day would be helpful for managing a project and help new science teams figure out how their project is progressing. I could see this for now being a query that runs once a day and stores the number is structure with those values being reported on the stats page. 

cc @aliburchard , @mrniaboc , and @chrislintott

**Comment by camallen** [comment]
this has been on the radar for a while, @CKrawczyk any progress on this?

**Comment by CKrawczyk** [comment]
I have been getting new images ready for GZ and this project has fallen on the back burner.  I will pick it back up next week.  Some more work needs to go into presenting the graphs for long running project (the hourly view for becomes difficult to navigate).  I also want to add the plotted time interval as a URL parameter for easier sharing of stats information.  To give a sneak peak:

![screen shot 2016-03-18 at 2 43 57 pm](https://cloud.githubusercontent.com/assets/6557526/13881232/ef98fb30-ed17-11e5-9fef-d8b0246e1d87.png)

Note: the big gap in the plot from mid-Jan to the start of Feb is due to the stats server not collecting classification data (not an issue with the main site).

**Comment by mschwamb** [comment]
Looks really nice and super handy. I hope part or all of this is implemented in the coming weeks. 

 @CKrawczyk  one suggestion. It would be nice if it you could also report or have a drop  down menu for the builder to be able to check the percentage complete and needed classifications per subject set as well for the top circle graphs. It would be nice to check and see if we're through 20% of the new data just uploaded to the site. The numbers and graphs are useful for the full dataset, but if I upload new subjects in preparation for being out of data, it seems like that circle plot would change and the percentage complete would go down.

**Comment by aliburchard** [comment]
!!! omg @CKrawczyk this is so freaking exciting. You can't tease with us pictures of such awesomeness. That's like making kids wait for Christmas presents.

(I jest, of course; this is so cool and I'm excited to play with it once it's live!)

**Comment by camallen** [comment]
@CKrawczyk looking neat, like it!

**Comment by CKrawczyk** [comment]
@mschwamb I am not sure if the info can be split by subject set seeing as a single subject set can belong to many workflows.  The current stats are split by workflow (see below).  @camallen is there an easy way to get the stats for a subject set within a particular workflow?

![screen shot 2016-03-18 at 3 47 51 pm](https://cloud.githubusercontent.com/assets/6557526/13883345/d835b89e-ed20-11e5-946a-3b5d798f0d51.png)

**Comment by camallen** [comment]
I don't think so the way we've currently set it up. Probably out of scope for getting a basic stats page up and running but something to think about.

**Comment by mschwamb** [comment]
Having  anything to gauge completion and when a newsletter should get sent to bump the classification rate  without having to download the csvs would be extremely helpful, so as is this is extremely helpful as is. 

The one thing I find hard about the Ouroboros version of the stats page is that unless you have a completion bar on the front page, you need to know where you completeness was when you uploaded the new data to then calculate how complete you're actually through the new data since % complete is counted with all data previously classified. So hopefully it can be considered for a version 2.0

Another suggestion, it might be nice if the stats page also told you what subject sets were live for each workflow in some section if that's doable.

**Comment by CKrawczyk** [comment]
@mschwamb I can add the subject set list easy enough as long as we are OK with exposing the subject set names on a public page.  I don't really see this being an issue, but since this would be the first page to expose the workflow and subject set names to non-collaborators I thought I would bring it up.

**Comment by camallen** [comment]
@CKrawczyk adding the retired counts to the subject set via https://github.com/zooniverse/Panoptes/issues/986 will allow some better reporting on this.

**Comment by mschwamb** [comment]
@CKrawczyk  Maybe that's a question for @chrislintott, @mrniaboc, and @aliburchard.  the stats page is going to be public as in a link  or semi public like the Ouroboros version where you have to know the right url to view it?  I had assumed it was through the project builder or that only certain accounts would be able to view it like private talk boards.

**Comment by CKrawczyk** [comment]
The page I am building now will be the public one with a link along side the other project links (e.g. classify, about, results, etc...).  There is also talk about building a private stats page that is only visible to collaborators to track things that should not be public facing.

**Comment by mschwamb** [comment]
Oh. The additional suggestions I'm asking for were for a stats page for researchers/collaborators only.  I didn't realize there was a public stats page being made. Apologies for my confusion. 

I'd suggest not including workflow names to be on a public facing page if there's only one workflow as that's not readily apparent to the project builder anywhere that it's going to get displayed on the project website since only when there is more than one and you can allow volunteers to choose  which workflow does the workflow names get displayed on the landing page. 

Perhaps something to also consider -  as a research team person once I  understood the demo stats page is a public one, the first thing I got uncomfortable seeing on the demo page was the retirement threshold. I'm not sure why since it's not a secret on my projects we've mentioned it in blogs and in papers. 

Perhaps I should close this ticket and open a new one for a private stats page with the completion rate per subject set per workflow?

**Comment by camallen** [comment]
Public projects should have public stats in my opinion. As a contributor to a project i would like to see this information. Thoughts @mrniaboc ?

**Comment by mschwamb** [comment]
To be clear I'm not saying there shouldn't be a public stats page,that's a call for the Zooniverse core team. I'm suggesting that certain pieces of information like subject set names or workflow names (if they're not already public on the landing page) perhaps not be on a public page. .

**Comment by trouille** [comment]
@CKrawczyk A number of projects in the works (like the Notes from Nature revamp) will have public workflows linked to a single Talk. In talking with those research teams, it would be useful to show the classification stats (i.e., per day/month/etc) for the whole site (as you currently do it), but also by workflow. In terms of UI, the only change would be to add a drop-down menu listing the workflow names and 'all'. It'd make sense to place that just above the drop-down selection for classifications per 'day/month/etc.'.

**Comment by CKrawczyk** [comment]
@trouille Once the stats api is updated to filter counts by workflow I will add that drop-down menu in.
