### ISSUE TITLE
Change tab on project nav to say 'Results' instead of 'Result' 

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#2328]
The singular doesn't sound right.

I tried to fix this myself. Found the text for the nav buttons in /project/index.cjsx, but it actually says 'Results'! This freaked me out, so I gave up.

**Comment by mschwamb** [comment]
Yes that would be great!

**Comment by brian-c** [comment]
The results page title is auto-generated on the back end and stored on project creation.

Once we implement custom pages (#2247) page titles will be editable. Not sure what the timeframe is on that.

@camallen, thoughts on changing the default in the meantime? And maybe mass-updating the existing ones?

**Comment by camallen** [comment]
Yeah - we can update the ones that have been previously created. Pretty sure the defaults are coming from [here though](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/results.cjsx#L12)

**Comment by brian-c** [comment]
You're totally right, I had no idea pages were created there. Will update.

**Comment by alexbfree** [comment]
Looks like this is fixed and working on zooniverse.org now.
