### ISSUE TITLE
'Description' appearance not Markdown on Projects page

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#233]
The 'description' of a project appears on the project's landing page, where it can be rendered in Markdown for a nice appearance. However, this 'description' also appears under the project avatar on the Projects page. But the Markdown is not parsed here, and so Markdown characters are displayed (which is ugly). See, for example, project "Season Spotter Test15". Can you please remove the Markdown from the 'description' text before displaying it on the Projects page?

**Comment by brian-c** [comment]
`description` should not actually be rendering Markdown, since it can appear elsewhere on the site.

**Comment by mkosmala** [comment]
Ah, okay. So my 'description' should be **plain text** and not Markdown. Right?

**Comment by brian-c** [comment]
Correct.

**Comment by mkosmala** [comment]
Hmm... If I can't do Markdown for 'description', then I lose that two-part text that you see on many Zooniverse landing pages (such as Floating Forests, Penguin Watch, Chimp & See, among others). Big flashy first line and then smaller byline. I really like the way that looks and was hoping to do it for my project. See the difference between:
*with* markdown: 
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Test28
*without* markdown:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season+Spotter+Test30

**Comment by brian-c** [comment]
Sorry, the description is displayed across the site. Allowing Markdown would allow images and arbitrary formatting, which could mess with the layout in places we wouldn't expect it.

**Comment by mkosmala** [comment]
Hmmmm..... I'm going to push a bit on this. Without Markdown, you're telling science teams that they can't really do much customization on the landing page for their project. The 'description' is the big major area for this landing page and I could definitely see people wanting to put pictures, large logos, and other things here. (Or just text of two different sizes....) 

Two possibilities, both of which I would think are pretty quick code-ups:
1) Keep the appearance on the landing page as Markdown and strip Markdown syntax from 'description' for use in other places on the site. (I'm sure someone's already written Markdown-to-plaintext converter code somewhere.); or 
2) Add another property to Projects, so that 'description' is plaintext and 'frontpage' or whatever you want to call it is rendered in Markdown in place of 'description' on the landing page.

**Comment by aliburchard** [comment]
I think @mkosmala makes a valid point. The description page without anything but plain text just doesn't look good and isn't compelling. And I think the need to distinguish between a "heading" "subheading" "text" at the very least is apparent from looking at the landing pages of so many of our projects.

But @brian-c has a good point with not wanting people to go all willy nilly with crazy markdown, images, and stuff that we have to parse in other places later.

As a compromise, what if we simply allowed for two different text styles (e.g. Heading/Text) on the landing pages? We could break the "description into two separate fields that way, and each would be entered as plain text, but formatted by us as a heading vs text?

**Comment by brian-c** [comment]
Will revisit this later. Might just end up being that we don't show `description` on the project landing page. `introduction` is Markdown.

**Comment by mkosmala** [comment]
I would be fine with two different text styles for the landing page as @aliburchard suggests. 

But I guarantee that project creators are going to want to have a lot of control over how their landing page looks. I don't think prohibiting text above the "get started" button is going to work as a solution. And I think it's reasonable that people would want to put images and hyperlinks on that landing page, too. Look at the existing Zooniverse project landing pages. People will want to at least approximate the way those look. The landing page is how a project differentiates itself from other projects and gets people motivated to start classifying. It's really important. @chrislintott thoughts?

In fact, @brian-c, I need a hyperlink on the landing page so that I can link between the two projects I have for Season Spotter as part of the two-project solution. I had hoped to do that in the 'description' text, as the 'introduction' text is so small and marginalized on the page. 

And at the very least, I really want to be able to have two text styles above the "get started" button -- which is the case for many existing Zooniverse projects -- by first release.
