### ISSUE TITLE
Suddenly, subjects are not displaying in Talk

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2337]
Subjects normally display fine in the Notes section of Season Spotter Questions Talk. But today they're not there:
![talk_no_image](https://cloud.githubusercontent.com/assets/1066340/13966241/ce475fde-f047-11e5-80d7-75de28150449.png)

No subject is. Even old posts (say, > 20 days) that previously had subjects displaying no longer display subjects.

Note that the images still show up in the table of contents. Just not in the posts themselves:
![talk_index](https://cloud.githubusercontent.com/assets/1066340/13966351/5a6ae45e-f048-11e5-82ad-932d75c9a5d3.png)

**Comment by eatyourgreens** [comment]
This was fixed by #2338
