### ISSUE TITLE
Right and left margins for 'help' text

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#234]
This isn't high priority, but it would be nice to have some left and right margins (whitespace) for the help pop-ups. For Snapshot Supernovae, this was this case. But for projects I'm building on Panoptes right now, the text goes all the way to the edges of the pop-up box and it looks cluttered. See, for example, the help pop-up here:
http://demo.zooniverse.org/panoptes-front-end/#/projects/mkosmala/Season%20Spotter%20Test15/classify?workflow=805

**Comment by rogerhutchings** [comment]
![screen shot 2015-05-01 at 10 05 01](https://cloud.githubusercontent.com/assets/2725841/7428503/91391236-efe9-11e4-94c4-bf17910da269.png)
