### ISSUE TITLE
Errors on npm start - cannot find module

### ISSUE THREAD

**Issue by MorayM** [zooniverse/Panoptes-Front-End#2340]
I'm following the installation instructions in readme.md but am getting errors at stage 2, running `npm start`:

    > panoptes@0.0.2 start /home/[usr]/panoptes-front-end
    > ./bin/serve.sh
    
    module.js:339
        throw err;
        ^
    
    Error: Cannot find the module 'core-util-is'
        at Function.Module._resolveFilename (module.js:337:15)
        at Function.Module._load (module.js:287:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (/home/[usr]/panoptes-front-end/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_duplex.js:39:12)
        at Module._compile (module.js:435:26)
        at Object.Module._extensions..js (module.js:442:10)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:311:12)
        at Module.require (module.js 366:17)

I've tried manually installing core-util-is to panoptes-front-end, browserify and through2 but with no luck. I'm using node 4.2.3 and npm 2.14.7 on Linux 3.19.0-49-generic.

**Comment by brian-c** [comment]
Might have been an error during install. Try a `rm -rf ./node_modules; npm install` and then `npm start`.

**Comment by MorayM** [comment]
Yes, I've tried that a few times. I've also tried manually installing browserify globally (the browserify docs recommend this). I've attached the npm-debug.log for this error if that is any help.
[npm-debug.log.txt](https://github.com/zooniverse/Panoptes-Front-End/files/187667/npm-debug.log.txt)

**Comment by CKrawczyk** [comment]
It might be a node version conflict, try using node v0.12.9 and npm version v2.9.1 ([nvm](https://github.com/creationix/nvm) can be used to help switch between various node versions).

**Comment by MorayM** [comment]
Still the same error I'm afraid. I took the node/npm versions from the root packages.json file, should I be using 0.12.9 and 2.9.1 instead?

**Comment by CKrawczyk** [comment]
That is the version I am using on my Mac, since it is now specified in the package.json I should upgrade on my end...

**Comment by MorayM** [comment]
In the end it was quicker to ditch the VM and spin up a new one! It seems to be running fine now. I moved from 14.04 to 15.10 in the new VM which might have had something to do with it?
