### ISSUE TITLE
File uploads to S3 fail in Internet Explorer

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#2342]
The PUT request to S3 returns 403 in IE11 (screenshot attached.) This seems to be a known bug in IE: the signed URL fails because the Content-Type header isn't present. https://forums.aws.amazon.com/thread.jspa?messageID=704692
![image](https://cloud.githubusercontent.com/assets/59547/14015762/555c9630-f1b3-11e5-9493-afbacae3d60c.png)

**Comment by alexbfree** [comment]
just adding notes from slack: @srallen suggested this fix should help us in terms of adding the content type https://github.com/zooniverse/Panoptes-Front-End/pull/523

**Comment by alexbfree** [comment]
see also talk thread https://www.zooniverse.org/talk/17/45764?comment=91176

**Comment by eatyourgreens** [comment]
I can upload from IE11 on my Mac if I add the Content-Type header to the PUT request. PR should be up shortly, allowing headers to be specified for that XHR object.

**Comment by alexbfree** [comment]
Reviewed code and tested on IE11 and in Chrome. Working nicely on media upload, avatar upload, background upload and subject upload. Nice job @eatyourgreens
