### ISSUE TITLE
Q: Who is notified after beta review?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2346]
Is it just the project owner or all the collaborators? For one project I'm advising, the key players are *not* the project owner, and an email to the owner might not be acted upon. If it's just the project owner who gets notified, is there a straightforward way to change who the project owner is?

**Comment by alexbfree** [comment]
Not sure but @mrniaboc will know.

**Comment by aliburchard** [comment]
It's just the project owner who is notified. Currently the only way to change ownership of a project is to ask @camallen or @marten to do it :-/

**Comment by camallen** [comment]
@mkosmala we can change the project owner but it'll break the url's for the project and that is bad.

**Comment by mkosmala** [comment]
Okay, for this project, I'll just bug y'all once we get to this point. 

But maybe something to consider for sometime-in-the-future is being able to change who is the "corresponding" person (or people) on projects. And the ability to change the "corresponding" person -- especially for projects that have long lives and might be run by multiple people in succession. (And probably the ability to CC other team members on important email notifications...)

**Comment by camallen** [comment]
@mkosmala do you see this as a role a collaborator could have that can be granted via the UI? 
```
user_name 

[X] Collaborator
[ ] Expert
[ ] ...
[X] Communications

```

**Comment by mschwamb** [comment]
Related to #1703 - It would be nice to specify who gets correspondences from the Zooniverse. I've been forwarding the emails I get to my project PIs. It would be nice if you could set in the project builder who gets official emails so multiple people can.

**Comment by camallen** [comment]
closing in favour of #1703, thanks @mschwamb
