### ISSUE TITLE
I can't classify on my project if logged in

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#235]
If I'm logged into Panoptes and try to classify on my project, I receive this error: 

"Error: No queue defined for user. Building one now, please try again."

However, if I am not logged in, I can classify. I wonder if this is because as the owner I am an expert and I don't have anything in my expert queue? But I should be able to classify in the regular non-expert mode as well. Not sure if this is for @brian-c or @camallen

**Comment by camallen** [comment]
@aliburchard this should be fixed in this PR https://github.com/zooniverse/Panoptes/pull/757

**Comment by twhyntie** [comment]
@aliburchard I get the same error message the first time I try it - then after hitting refresh in the browser it works. (But as @camallen says, this should be fixed by that PR.)
