### ISSUE TITLE
Auto-complete for adding collaborators doesn't work well

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2350]
I've been told this is a known issue, but I couldn't find it anywhere, and wanted to make sure it was documented. 

If you try to add someone as a collaborator and start typing their user name, you won't necessarily find the user name with only a partial name. For example, if you want to add @aliburchard, and you start writing 'alibu', you don't get the full 'aliburchard'. Instead you get 5 other possibilities. And with just 'ali' or 'alib', you get only the single user name that matches exactly. This makes it hard to find people unless you know their entire user name. In which case, why bother having auto-complete at all?

**Comment by srallen** [comment]
This would be a back end issue. If it's not resolve, the issue can reopen on zooniverse/Panoptes
