### ISSUE TITLE
Counts on a project's homepage are inaccurate

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2354]
The project https://www.zooniverse.org/projects/alexbfree/snapshot-serengeti-computer-vision/ has just launched in beta.

Currently the project stats at https://www.zooniverse.org/projects/alexbfree/snapshot-serengeti-computer-vision/home say that there are 1663 classifications recorded, and 36 subjects retired.

![screenshot 2016-03-30 18 12 39](https://cloud.githubusercontent.com/assets/1473244/14150907/3cba198c-f6a3-11e5-8601-3469b6bb5f73.png)

I know that there are only 66 subjects and the retirement limit is 25... 25x66 = 1650 so if this number of classifications were accurate, then all subjects would be retired.

Also, the number of subjects is saying 185 when there are only 66. Could this be counting subjects that no longer exist, that were used in previous versions of the workflow?

**Comment by mschwamb** [comment]
This might be related to https://github.com/zooniverse/Panoptes/issues/1745

**Comment by alexbfree** [comment]
I think you're right @mschwamb . In fact now all the subjects have been retired, but no out of data message is showing. 

![screenshot 2016-03-31 09 27 21](https://cloud.githubusercontent.com/assets/1473244/14169968/d56baf4a-f722-11e5-8eec-868e6303bc37.png)

**Comment by alexbfree** [comment]
I've narrowed this down a bit, it seems to be a problem with the API response.  

The `project` API endpoint is returning 185, which doesn't correspond to what the `workflow` response returns of 66. I will raise a Panoptes API ticket.

**Comment by alexbfree** [comment]
Scratch that. The project is correct to return 185 (There are 119 subjects from other subject sets that are not active in this workflow... 119+66=185). The problem is that the UI should not be using the Project's subject count, it should be using the active workflow's subject count.

**Comment by alexbfree** [comment]
OK so I think to fix this we need to change 
https://github.com/zooniverse/Panoptes-Front-End/blob/332ec617c6941639f9d25da8c96eec40a2355741/app/pages/project/metadata.cjsx#L30
to say something like `project.(active workflow).subject_count`

**Comment by alexbfree** [comment]
I'm developing a fix here. https://github.com/zooniverse/Panoptes-Front-End/compare/master...alexbfree:subjects-count-fix?expand=1 
 I can get the right number out, just need to figure out the best way to display it on screen. 
Also wondering if maybe active_subjects should be a calculated field (or whatever the equivalent of that is in react land) of the project...

**Comment by eatyourgreens** [comment]
I can't seem to comment on that diff, but just use Array.reduce to calculate your running total on the workflows array: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

```coffeescript
count = workflows.reduce (a, b) ->
   a.subject_count + b.subject_count
console.log count, 'subjects across all workflows'
```

**Comment by alexbfree** [comment]
Good tip - thanks @eatyourgreens !

**Comment by alexbfree** [comment]
Actually by that returns a workflow, need to do .subjects_count on the result. Also by the time you have accounted for empty array possibility and coffeescript syntax needs you end up with something much more ugly:
```
count = workflows
          .reduce (
            (a, b) ->
              a.subjects_count + b.subjects_coun
            -> 0
          )
          .subjects_count
console.log 'Total Active Subjects: ', count
```
I think it's arguable as to whether that is actually better than the original.

**Comment by eatyourgreens** [comment]
My bad, it should be `a + b.subjects.count`, shouldn't it?

**Comment by alexbfree** [comment]
i'm going to leave it as the original version for now, i think it's more readable/maintainable.

**Comment by alexbfree** [comment]
anyway to return to my previous question https://github.com/zooniverse/Panoptes-Front-End/issues/2354#issuecomment-203903657 (and i'm just noting this in the ticket to myself and anyone in particular, not directly to you Jim):

I figure there are three options
1) figure out a way to get the active workflows inline (is there a way to call that get('workflows') synchronously?)
2) update the page after loading, once the `then` has completed (need to figure out how to do that with React)
3) solve this differently by making the `active_subject_count` directly available from the project (presumably this would need to come from the API response, and need a change in Panoptes itself? unless there is someplace in PFE to put model-specific methods?)

Will ask around as I have no idea which of these approaches is the preferred or easiest approach...

**Comment by eatyourgreens** [comment]
D'oh, I forgot to pass an initial value to reduce.
`count = workflows.reduce ((count, workflow) -> count + workflow.subjects_count), 0`
sums `subjects_count` for your workflows array and gives you the total.

**Comment by eatyourgreens** [comment]
Here's a quick pass at a component that counts subjects on mount then displays the result.
https://gist.github.com/eatyourgreens/8efa3b51d62c270b9581b7814aa27a8b

**Comment by alexbfree** [comment]
Thanks Jim that's very kind of you! exactly what i needed

**Comment by alexbfree** [comment]
Just to answer my own question above, it turns out the preferred option is

4. use a state variable to hold your result. Render will run when state updates

**Comment by alexbfree** [comment]
another note to self: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/finished-banner.cjsx#L27 is also useful reference

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/issues/1482, just wondering if anyone saw this ticket for the api?

**Comment by alexbfree** [comment]
Thanks @camallen it does look like that might fix it, will put this on hold and wait for that ticket to close before re-testing this

**Comment by srallen** [comment]
Lots of back end API work has been done on this. Closing.
