### ISSUE TITLE
Making the 'visualize this workflow' button in the workflow part of the project builder not locked when you have a live workflow

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2355]
Perhaps one for @CKrawczyk Having the 'visualize this workflow' button be available when a workflow is locked and live would be helpful for data analysis and research team discussions. We were talking about data reduction for Comet Hunters this week and the PI was doing a classification to remind himself about how we ordered the questions. I think the ability to pull up the visualization for discussions, talks, etc would be really useful if it's possible

**Comment by alexbfree** [comment]
Good point! I think this is part of a more general problem with the way that the workflow is disabled when live. Really everything should be available in a read-only manner, it's really only editing that we need to block. My suggestion would be that we need to update the workflow page to isolate and block its edit functionality, but not its read functionality.

**Comment by aliburchard** [comment]
It's actually available when the project is locked/live. It appears gray, but you can still click on it.

**Comment by mschwamb** [comment]
The grey signals not accessible, so I don't think that's  intuitive to know you can click the button with the workflow locked and that my project would be okay if I did. Maybe the coloring of the button can be changed so that it's very apparent you can can click on it even if the workflow is locked.

**Comment by CKrawczyk** [comment]
I looked into how to make this not be grey when a project is live, but I see no obvious way of doing it.  I am not really sure how the greyed out style is being applied to that page in the first place.  Maybe somebody with more PFE experience can help with this.

**Comment by aliburchard** [comment]
Yeah - that needs a bit of an overhaul. Related to the need for a conversation about what we should allow projects to do while "live" (e.g. we need to enable linking subject sets on live projects).

**Comment by CKrawczyk** [comment]
To give some context, the opacity is being set directly on the element of the "columns-container" not in the css via class name, this makes it impossible to override the opacity of just one element inside of the column (even using an `!important`).  This would need to be externalized into the css to allow changes to be made on an element-by-element basis.

**Comment by mschwamb** [comment]
fixed by #3517
