### ISSUE TITLE
'visualize this workflow'  task overlap when viewing it

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2356]
Not sure if i should have hit sort task nodes, but when I hit the visualize this workflow The third task shows up on top of the 2nd in the display of the decision tree blocking the 2nd question/task completely 

I'm on a 13-inch mac using the current release of Firefox

<img width="1148" alt="screen shot 2016-03-30 at 6 56 22 pm" src="https://cloud.githubusercontent.com/assets/753325/14159378/1de962aa-f708-11e5-929a-dfe0c8462bc6.png">

cc @CKrawczyk

**Comment by CKrawczyk** [comment]
It looks like the issue is Task 3 has no input (no line leading into the dot on the left), that means no question leads into it so the code does not know how to position in on the page.  The code currently can only auto-position tasks that have an input.  You should still be able to click and drag the node to a new position (click and drag the title the top part of the node).

**Comment by mschwamb** [comment]
Task 3 has input as it shows up in the classification interface. Task 2 is a yes or no question and required. Both answers go to Task 3

**Comment by mschwamb** [comment]
It's was not  clear  to me in the project builder that I can click and drag or modify any of what's being displayed. Maybe it only needs some help text?

**Comment by CKrawczyk** [comment]
Could you add me as a collaborator on the project so I can see what is causing this to happen?  My zooniverse username is cmk24.

**Comment by mschwamb** [comment]
I'm on travel. When i get back I'll add you on and message you here.

**Comment by mschwamb** [comment]
@CKrawczyk I've added you to the project as a collaborator so you can see what's happening. There's only one workflow currently and it is live.

**Comment by CKrawczyk** [comment]
OK, I see where the bug is.  The second option for Task 1 has `next: ""`, I did not know next could end up as an empty string (usual it does not exist if it leads to the end of the workflow), I will update the code to handle this.
