### ISSUE TITLE
Film Strip Left/Right arrows

### ISSUE THREAD

**Issue by jwbmartin** [zooniverse/Panoptes-Front-End#2359]
Change the < and > to chevron-right chevron-left from Font Awesome, please?

**Comment by alexbfree** [comment]
@srallen I may be wrong but I think to do this we need to explicitly add those two icons to the zoofont ... do you know how to do this?

**Comment by srallen** [comment]
@alexbfree No it's a part of [font awesome](https://fortawesome.github.io/Font-Awesome/) which we're already using. What needs to happen is that they need to be added in the markup: `<i className="fa fa-chevron-left"></i>`

**Comment by alexbfree** [comment]
Ah ok. For some reason i thought our font was branched off font-awesome or something. thanks.

**Comment by alexbfree** [comment]
OK fixed this here. https://github.com/zooniverse/Panoptes-Front-End/commit/1918b3382107037ac47593312fe15be0a99bd6d0

(Sorry, meant to do that as a PR but accidentally committed directly to project-page branch instead of my own branch. Hopefully uncontroversial though. Have tested and it works.)
