### ISSUE TITLE
Workflow specs: default "next" no longer works

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#236]
Not sure if this is back-end or front-end, so tagging @camallen and @edpaget.

Originally, if you specified a "next" as part of of a question, the workflow would proceed on to the next question no matter what the user answered. But now, the default "next" is no longer working. So if I don't specify a "next" for each answer, the workflow ends. 

For example:
```
   "question1": {
      "type": "single",
      "question": "Is the swallow laden?",
      "answers": [
         {"value": "yes",
          "label": "Yes" },
         {"value": "no",
          "label": "No" }
      ],
      "next": "question2"
   },
   "question2": {
      "type": "single",
      "question": "What is the swallow's provenance?",
      "answers": [
         {"value": "african",
          "label": "African" },
         {"value": "european",
          "label": "European" }
      ],
      "next": null
   }
```
According to the docs, this workflow should ask 'question1' first and then ask 'question2' regardless of whether the user chooses 'yes' or 'no' to 'question1'. However, as currently implemented, only 'question1' gets asked at all. Then the workflow terminates.

Is this a bug, or have the specs changed to require a "next" for each **answer** to each question?

**Comment by brian-c** [comment]
Change in spec for simpler editor interface, sorry. I'll update the docs.
