### ISSUE TITLE
Most of the projects vanish in Admin mode

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#2360]
Admin mode should show something like 2,000 projects at the moment, but only shows 3 pages of projects.

I'm guessing every project needs a discipline before it will show up now, or needs to be live and approved?

**Comment by alexbfree** [comment]
My guess we are showing the projects the user is allowed to see rather than checking for admin

**Comment by camallen** [comment]
Seems to be working for me from https://www.zooniverse.org/projects
![image](https://cloud.githubusercontent.com/assets/295329/14245075/b1dcc956-fa56-11e5-9647-971f341a05df.png)

**Comment by eatyourgreens** [comment]
@camallen this is for the new projects page PR. Might be something to do with adding the option to filter by discipline.

**Comment by camallen** [comment]
Aha, make sense @eatyourgreens ! most likely not passing the `admin=true` param then, see the request above.

**Comment by eatyourgreens** [comment]
Fixed by #2403
