### ISSUE TITLE
Add discipline tagging capability to Admin project settings page

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2363]
There is a need for admins to be able to apply discipline tags to projects (as currently you have to be a collaborator or nag project owners/collaborators to do it) - we should add the same new dropdown/tag field that's in the Project Builder following the merge of the new project page, to the Admin Project Settings page 
( https://www.zooniverse.org/admin/project_status/username/projectname )

**Comment by alexbfree** [comment]
PR is ready (#2586)

Can be tested at http://discipline-filter-from-admin-page.pfe-preview.zooniverse.org/

**Comment by srallen** [comment]
Don't think this is necessary as this is probably not a regular task we will be doing for project builders. If it does need to be done by one of us, we can do via API directly or get to lab page using admin mode.
