### ISSUE TITLE
Really hard to tell anything changed in the classification summary when you hit  show expert classification

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2364]
I found it really hard to figure out that the expert classification was showing and what had actually changed on the screen to show my the expert classification when I hit the button. Maybe a color change for the expert classification results to highlight the difference?

<img width="1126" alt="screen shot 2016-04-01 at 2 47 00 am" src="https://cloud.githubusercontent.com/assets/753325/14188155/404b8b6e-f7b9-11e5-97cc-b0cc1a67ba7e.png">

<img width="1114" alt="screen shot 2016-04-01 at 2 47 06 am" src="https://cloud.githubusercontent.com/assets/753325/14188156/41abb36c-f7b9-11e5-8340-666519d91bbf.png">

**Comment by alexbfree** [comment]
I've had the same thought before. I think we should show both classifications side by side, with headings "Your classification", "Expert classification" - would make it easier to see any differences

**Comment by mschwamb** [comment]
The fact there is an expert classification doesn't stand out. With a quick look, the summary looks exactly like that for a subject without any expert/gold standard data. 

<img width="1127" alt="screen shot 2016-09-16 at 11 15 18 am" src="https://cloud.githubusercontent.com/assets/753325/18601670/f88c1a66-7bff-11e6-9aca-0f39731d1165.png">

I nearly passed it by in the new version of the Milky Way Project.  This seems important that a volunteer not miss seeing the actual gold standard classification to see what they should have marked/answered.

At minimum can the text size/coloring be changed to highlight there is something special about this subject's  summary page?

It seems like this should be like Planet Hunters and that once you hit submit the next thing is that the interface show by default show you gold standard data classification. Here a volunteer can opt of seeing it, but perhaps that's a different issue/discussion.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
