### ISSUE TITLE
[project page branch] "Current Page" state not shown correctly

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2373]
When we originally designed this, the current page state is supposed to be shown like this (in this example we are currently filtered to just look at History projects):

![screenshot 2016-04-01 15 24 06](https://cloud.githubusercontent.com/assets/1473244/14209812/e70ec9a2-f81d-11e5-8755-61893ed89422.png)

(This correct behaviour can still be seen on https://preview.zooniverse.org/panoptes-front-end/miniztm/#/projects and miniztm branch)

What we have now is this

![screenshot 2016-04-01 15 23 07](https://cloud.githubusercontent.com/assets/1473244/14209815/ee05a7b2-f81d-11e5-8bb8-405131d5279d.png)

Tasks:

1. Ensure All Disciplines is only blue background when it's active, white other times
2. Ensure each Discipline's colour stays when it's focussed, not just on hover
3. Remove the blue highlight square box around the panel on :focus

UPDATE:
On latest version at https://project-page.pfe-preview.zooniverse.org/?env=production, we see slightly different behaviour:

* Active elements are now keeping their colour, so task 2 no longer needed.
* All Disciplines is highlighting blue only when clicked, but not keeping its blue when active, which it should.

Re: the blue highlight square, see discussion with @eatyourgreens below, where I suggest an alternative solution.

**Comment by eatyourgreens** [comment]
@alexbfree the blue highlight is the OSX focus indicator, showing which element is focussed to receive keyboard input. It can be turned off in the OSX accessibility settings.

I'm not sure if it can be overridden with CSS, since it's an OS setting. If it can, then it should be replaced with our own styling to indicate which element has focus.

**Comment by alexbfree** [comment]
@eatyourgreens it can be overridden with CSS, for example:
```
.filmstrip--disciplines__discipline-card:active,
.filmstrip--disciplines__discipline-card:focus {
    outline: none;
}
```

I understand your point on the need to keep it for accessibility... perhaps this instead:

```
.filmstrip--disciplines__discipline-card:focus, .filmstrip--disciplines__discipline-card:active {
    outline: none;
    box-shadow: 0 0 3px 2px #3B99FC;
}
```

I do think we should do something as it looks v unsightly and spoils the design.

Happy to implement this if you agree.

**Comment by eatyourgreens** [comment]
Looks like it's this line here: https://github.com/zooniverse/Panoptes-Front-End/blob/project-page/css/filmstrip.styl#L20

I'd change the background colour to indicate focus. Usually I'd apply the same styles that apply on hover, since you're indicating a similar state in terms of interaction with the control.

**Comment by alexbfree** [comment]
@eatyourgreens I am not sure if we are quite on the same page. To clarify this, I think there are four different types of effect at work here, let's enumerate them. 

1. `:hover` - happens when you hover mouse over a square. The background colour should change to coloured instead of white, and text changes accordingly. Currently working correctly
2. `:active` (CSS sense) - happens briefly when you click. Currently showing as blue square outline and I think needs changing
3. active (in the sense of our class suffix `--active`) - the currently active filter - stays highlighted to show what you are currently filtering on. As with hover, the background colour changes to coloured instead of white, and text changes accordingly. Currently working correctly.
4. `:focus` - when the item has focus in the accessibility sense. Currently showing as blue outline. We need to indicate this, but we also need to distinguish it from 3.

In light of this, when you say
>I'd change the background colour to indicate focus.
how should we change the background colour so the user can tell the difference between the active filter and the active focus(accessibility wise)?

**Comment by eatyourgreens** [comment]
@alexbfree applying the same styles for `:hover` and `:focus` is [fairly standard practice](http://www.bbc.co.uk/guidelines/futuremedia/accessibility/mobile/design/visible-focus). Is the problem here that the active state isn't visually different from the hover state? If not, use the `:hover` background colour for `:focus`.

**Comment by alexbfree** [comment]
I agree we should apply the same style for :hover and :focus (1 and 4 in my enumeration).
I am saying we need to differentiate "active filter" (3, currently denoted by coloured background) from "active keyboard focus" (4, currently denoted by blue box). I don't think 1,3 and 4 can all be the same.

For example:

* Click on Biology
* Tab to move keyboard focus over adjoining discipline, Climate

We need to be able to tell the difference between the currently active filter (Biology) and the currently focussed-but-ready-to-click filter, Climate. If we just set background colour for both, you can no longer tell what's active vs what's about to be active once you click.

**Comment by eatyourgreens** [comment]
Ah right. To be honest, active and hover should not be the same either eg.
- click on Biology
- hover over Climate

**Comment by alexbfree** [comment]
OK How about this as a solution:

For `:hover`, and `:focus` (1 and 4):
![screenshot 2016-04-12 15 03 58](https://cloud.githubusercontent.com/assets/1473244/14462631/e109be4a-00bf-11e6-9dc5-ed15fb15bcd5.png)
```
.filmstrip--disciplines ul .filmstrip--disciplines__discipline-card--discipline-biology:hover,
.filmstrip--disciplines ul .filmstrip--disciplines__discipline-card--discipline-biology:focus {
    color: #18807f;
    background-color: white;
    outline: none;
    box-shadow: 0 0 3px 2px #18807f;
}
```

For `:active` and `--active` (2 and 3):
![screenshot 2016-04-12 15 06 49](https://cloud.githubusercontent.com/assets/1473244/14462710/3830f026-00c0-11e6-89fb-0bd9166846d7.png)
```
.filmstrip--disciplines ul .filmstrip--disciplines__discipline-card--discipline-biology:active,
.filmstrip--disciplines ul .filmstrip--disciplines__discipline-card--discipline-biology.filmstrip--disciplines__discipline-card--active {
    background-color: #18807f;
    color: white;
    outline: none;
}
```

(example is just for one discipline, would have to replicate for the others)

**Comment by eatyourgreens** [comment]
:+1: looks good!

**Comment by alexbfree** [comment]
Great, glad we got to the bottom of that! Will implement soon. If I can just figure out these darn rebases.

**Comment by jwbmartin** [comment]
Hold on. Why are we doing early 2000's Microsoft design?

**Comment by jwbmartin** [comment]
I don't understand why it has a drop shadow instead of a stroke?

**Comment by jwbmartin** [comment]
Actually I just don't understand what we are discussing in general because active and hover should just be the same.

**Comment by srallen** [comment]
Just clarified what the discussion is with @jwbmartin. @alexbfree, she'd like a solid color border to indicate focus and hover rather than a box shadow. This is so the flat design is consistent.

**Comment by alexbfree** [comment]
Thanks @srallen for talking it through with Jordan.

@jwbmartin The `box-shadow: 0 0 3px 2px #18807f;` wasn't my creation, it mimics the focus rectangles you already get in OSX and other browsers.

I will update the above solution with a solid border version

**Comment by alexbfree** [comment]
OK have updated https://github.com/zooniverse/Panoptes-Front-End/issues/2373#issuecomment-208924769 . Look OK to you @jwbmartin ?

**Comment by alexbfree** [comment]
OK I have implemented this now. See https://project-page-states.pfe-preview.zooniverse.org/projects?env=production . @eatyourgreens @jwbmartin @srallen Let me know if you're happy with that.

**Comment by eatyourgreens** [comment]
Looks good to me :+1: Nice clear differentiation between hovering/focusing a button and clicking/activating it.

**Comment by jwbmartin** [comment]
I dig it

**Comment by mschwamb** [comment]
I noticed this issue and was curious so took a look. I'm not sure where to stick this so I'll put it here. Apologies if it should go elsewhere. 

The scroll bar project looks great. One thing to consider is that some of the current projects (mainly ones I'm involved in) are not really astronomy and I'm not sure there is a box for them. For example Moon Zoo, Planet Four and Planet Four: Terrains are really more planetary science. Planetary science versus astronomy can be a fuzzy line.  You can get away with it if you really want to call it Astronomy, but previously instead of Astronomy, Space was used for the Subject heading on Zooniverse home.  

![zooniverse](https://cloud.githubusercontent.com/assets/753325/14471354/c58be056-0120-11e6-8ed2-c051d807fcfb.png)

**Comment by CKrawczyk** [comment]
This is causing "double" focus on firefox:
![screen shot 2016-04-13 at 1 44 58 pm](https://cloud.githubusercontent.com/assets/6557526/14493573/08816f72-017e-11e6-92f2-733942f36829.png)

**Comment by srallen** [comment]
Thanks @CKrawczyk. I've noted that in #2418

**Comment by eatyourgreens** [comment]
Closed by #2418

**Comment by alexbfree** [comment]
@mschwamb Thanks for your suggestion. We had some discussions about the categorisations when we assigned them, and @mrniaboc helped us come up with the final categorisation. I don't think we'd want separate "Astronomy" and "Planetary Science" categories, but I would support for renaming the current "Astronomy" category to "Space" (as indeed it was on the old zooniverse.org) so as to be more all-encompassing. @mrniaboc what do you think?

**Comment by alexbfree** [comment]
@mschwamb we have now implemented this suggestion, you'll see "Space" in the new project page when it launches

**Comment by mschwamb** [comment]
Looks great. Thanks @alexbfree for considering my suggestion.
