### ISSUE TITLE
[project page branch] "Showing x-y of z" is missing

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2375]
Not sure if it's intentional, but the counters from the top of the projects list are missing (these is present on zooniverse production and on https://preview.zooniverse.org/panoptes-front-end/miniztm/#/projects which is what we had at the end of miniZTM week)

![screenshot 2016-04-01 18 08 15](https://cloud.githubusercontent.com/assets/1473244/14214545/7f02a028-f835-11e5-8959-28728d40a7ae.png)

It seems that this is parts of owned-card-list that hasn't made it across: 
https://github.com/zooniverse/Panoptes-Front-End/blob/project-page/app/components/owned-card-list.cjsx#L74

**Comment by eatyourgreens** [comment]
Fixed by #2404
