### ISSUE TITLE
Add recent comments and notifications link to talk side bar on all Talk discussions

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2378]
I find that I got to the recent comments link scroll and find a discussion or post I should reply to and then get back to scrolling through the recent comments for other places to reply. Right now you click on recent comments and then the comment you want to reply to, you're then stuck and can't get back to the recent comments thread from there. I always have to click back to the main Talk front page to get the recent comments link to appear. 

It would help if that could appear in all discussion threads on the side bar, so that I could click back to see more of the recent discussion rather than always have to click back to the Talk front page and then the recent comments link

<img width="1110" alt="screen shot 2016-04-02 at 5 52 47 pm" src="https://cloud.githubusercontent.com/assets/753325/14225621/e8919ffa-f8fb-11e5-95de-e1eccadc71ec.png">

<img width="1139" alt="screen shot 2016-04-02 at 5 53 03 pm" src="https://cloud.githubusercontent.com/assets/753325/14225624/ef243ddc-f8fb-11e5-9948-13b9ceb85986.png">

**Comment by mschwamb** [comment]
Just had a newsletter go out  on Comet Hunters where there's a spike I'm awake for and I'm finding I'm spending  alot of time after posting jumping back to the Talk front page to get back to the  Recent Comments button after writing a reply

**Comment by parrish** [comment]
Right now the "recent comments" link is contextual:
  - From the board list, it shows all recent comments
  - From a board it shows recent comments in the board

So adding it to the discussion wouldn't really make sense with that paradigm.

It's something we're looking to address on the next design pass.

**Comment by alexbfree** [comment]
linking to #2251 so I can potentially factor this into the design

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
