### ISSUE TITLE
Survey task - choices display suddenly misbehaving

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2380]
@amyrebecca @brian-c This is a new issue, which I imagine was introduced with vertical sorting, but the thumbnails are now displaying way too early on the survey tasks, meaning that the text is often split across two lines for some choices and not others. I assume there's normally some threshold at which point the icons display, say, when <15 species are available.  Now they are displaying when way more species are available (for western shield and camera trap test, this is before anything has even been filtered.

![screen shot 2016-04-04 at 14 43 09](https://cloud.githubusercontent.com/assets/6217406/14249900/e95c6b9e-fa73-11e5-98df-7e97a20ffafd.png)

![screen shot 2016-04-04 at 14 46 18](https://cloud.githubusercontent.com/assets/6217406/14249922/0407ba5c-fa74-11e5-97ea-f09a329d98ed.png)

This is a new issue that only appeared in the last few days. I think it might also be compounded by the subjects appearing massive again, thus limiting the amount of screen real estate available to the choices list itself.   For example, on WWW, we see the text split across lines and the subjects enormous from the start
![screen shot 2016-04-04 at 14 48 17](https://cloud.githubusercontent.com/assets/6217406/14250135/f468713a-fa74-11e5-9571-0b346f11a311.png)

and then displaying icons with too many choices still left exacerbates this
![screen shot 2016-04-04 at 14 51 21](https://cloud.githubusercontent.com/assets/6217406/14250153/0712aa8a-fa75-11e5-843e-afa8acdbbeca.png)

**Comment by aliburchard** [comment]
@eatyourgreens pointed out this is probably largely to do with the whatsizethumbnails variable in https://github.com/zooniverse/Panoptes-Front-End/pull/2257/files --
So I suspect that's part of it (since Camera trap test and western shield previously didn't display icons until there was some filtering), but I seem to recall that we had small icons displaying with three columns before.

**Comment by mrniaboc** [comment]
This is relatively important, as there is one survey task project that is waiting to launch.

**Comment by aliburchard** [comment]
@brian-c I think something might not be quite right with the new logic for splitting columns. Looking at the old behavior, I *think* icons should appear when the choices are split across 2 columns, which I think should kick in at <=20 choices. In https://www.zooniverse.org/projects/aliburchard/toledo-zoo-wild-shots/classify (below), there are <20 choices, but they're split across 3 column still and the icons are appearing.

![screen shot 2016-04-06 at 10 16 21](https://cloud.githubusercontent.com/assets/6217406/14313568/2f945d7a-fbea-11e5-91f5-106a9c63b06a.png)

**Comment by eatyourgreens** [comment]
Maybe these two checks should be `< 21` (or `<= 20`)?
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/survey/chooser.cjsx#L32
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/survey/chooser.cjsx#L40

**Comment by aliburchard** [comment]
Yeah - I think if they are both the same (whether it's <21 or <=20), we should be okay.

**Comment by brian-c** [comment]
My bad! Just merged in a fix.
