### ISSUE TITLE
subjects displaying too large again

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2382]
This seems to come and go, but pretty sure we decided against requiring projects to limit the pixel widths of their images, and that until a few weeks or months ago, we set a limit on the size of the subject viewer.

For example, in WWW, the images fill so much of the screen, it forces off both menu bars (and also now forces the classifier into a small enough space that it splits text across lines). Related to #2380.

![screen shot 2016-04-04 at 15 40 55](https://cloud.githubusercontent.com/assets/6217406/14251595/a59437a4-fa7b-11e5-94e6-1837c2e4342d.png)

**Comment by mrniaboc** [comment]
Yeah, the formatting of the text when it is split like that look rubbish!

**Comment by eatyourgreens** [comment]
I don't think we've ever had a maximum width on subjects, only a maximum height. Looks like WWW has very wide images compared to say, Snapshots at Sea or Fossil Finders, and that's what's causing the problem.

**Comment by aliburchard** [comment]
how hard would it be to set a max width as a function of screen size? (perhaps along the lines of how the display changes when you're on a phone or tablet?)

**Comment by aliburchard** [comment]
also, I think the max height is still a bit too big, as it's forcing both menu bars off the screen

**Comment by eatyourgreens** [comment]
I've always assumed that was intentional eg. https://www.zooniverse.org/projects/aliburchard/wildebeest-watch/classify scrolls down to move both navigation bars off the top of the screen.

**Comment by aliburchard** [comment]
huh, @eatyourgreens that doesn't happen to me on wildebeest watch for some reason -- my default view is this:

![screen shot 2016-04-04 at 16 19 13](https://cloud.githubusercontent.com/assets/6217406/14253076/f68905da-fa81-11e5-83a9-0cc7dfaadc4c.png)

**Comment by eatyourgreens** [comment]
Here's my 15-inch laptop screen.

![image](https://cloud.githubusercontent.com/assets/59547/14253160/4c348932-fa82-11e5-8fa9-27d54eb359f7.png)

I suspect that your monitor is showing the wildebeest subjects at full size, but having problems with the WWW photos because they're humongous (which is a technical term.)

So we haven't accounted for the case where a subject set is loaded with very large images?

**Comment by srallen** [comment]
I would suggest us setting a max-width on the `content-container` class rather than on the subject viewer.

**Comment by aliburchard** [comment]
omg tabs. so. many. tabs.

**Comment by eatyourgreens** [comment]
TIL: Chrome have fixed page zoom so you can simulate a large monitor by hitting cmd-minus a couple of times on a laptop.

**Comment by eatyourgreens** [comment]
@aliburchard as far as I can tell, fromn playing around with the viewport size in Chrome, there's a maximum width set on that right-hand task area. The subject photo then expands to fill any remaining space on the screen, up to its uploaded size (which is around 900px for the wildebeest project but 1900px for the WWW photos.)

If I'm right, then limiting the width of the subject photo won't change the size of the task area ie. the task won't expand to fill any space created by the smaller subject. So maybe we need to make the task area bigger to accommodate survey tasks with long text in the choices? I'm not sure how that will impact on other tasks, like drawing or multiple choice questions.

**Comment by brian-c** [comment]
Task area width has been increased in #2383. We will never win this completely, long-term. Sometimes text wraps.

**Comment by eatyourgreens** [comment]
Yeah, I think a lot of this has to do with asking people to upload sensibly-sized subject images, and write sensible text for the choices.

@aliburchard any objections to my merging the fix?

**Comment by aliburchard** [comment]
sounds good from my perspective. (To encourage more sensible image sizes, we might need to provide guidelines on *how* to resample, as I made it up with wildebeest watch, and now the images are really tiny even on massive screens.)

**Comment by srallen** [comment]
To be fair the WWW team did ask me about image size and scale guidelines a while ago and I told them we didn't have a max-width on the subject viewer, but also suggested to size down really huge images if it made sense. I think what I told them was too generalized. We probably should have a guideline.

**Comment by eatyourgreens** [comment]
Closed by #2383
