### ISSUE TITLE
dropdown task - options import

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2385]
Continues #2376...

I've edited this issue to focus on the dropdown task options import.
See Issue #2507 for discussion related to the dropdown task preset options.

@brian-c, @simensta

**Comment by aliburchard** [comment]
I don't know what your plans for error handling on csv upload are (or if you plan to expose the csv import to non-developer project builders), but the current approach for camera survey tasks has been a bit of a nightmare, as the uploads fail silently and then break in mysterious ways. After several hours of tweaking and deleting and then re-uploading all the survey data, sometimes they work again (or sometimes I have ask Brian to help), but my first thought when I hear "csv import" is: ![](http://vignette4.wikia.nocookie.net/random-ness/images/9/9f/Darth_vader_no.gif/revision/latest?cb=20120616003315)

**Comment by mcbouslog** [comment]
haha - love the gif! Brian has a similar cringe every time I mention we'd like to incorporate CSV import into the dropdown task. In a different iteration of the dropdown task I did have it working*, and since it'd just be used to get the labels for options (i.e. one column of a csv, don't care about column heading, simpler use than within survey task) it seemed to be ok. I'll coordinate with you and others to test out before officially incorporating.

**Comment by aliburchard** [comment]
Ha, I thought he might, given that I bug him all too often when I'm at my wit's end with the csv uploads. 

Short of the long: I think graceful fails would go a long way to making a csv importer be more user friendly, but I currently spend a ridiculous amount of my time trying to help project builders through this process, which isn't effective in the long run (and makes me unfun to be around, just ask Marten), so it's worth bearing in mind as you build that.

**Comment by mcbouslog** [comment]
my branch with CSV import of options in the dropdown task is [here](https://dropdown-csv-import.pfe-preview.zooniverse.org/). click the pencil/edit button of a dropdown to bring up the modal where you add options, which includes CSV import.

@aliburchard, @brian-c, @simensta - no rush, but want to try out and let me know what you think? the help modal text likely needs to be rewritten, but hopefully this is on the right track?

when adding an option in general, an alert is triggered if a user clicks the add option button and the input is blank, the option label is a duplicate or they haven't selected the related condition. these alerts are also triggered when adding options via CSV, but i've added code where if any of those alerts are triggered 3 times it stops adding options (3 strikes = out). not sure if that's the best way to handle that (UI/UX-wise and actual related code-wise), but that's the current setup.

**Comment by mcbouslog** [comment]
@aliburchard , @brian-c , or @simensta - any feedback on the dropdown task CSV import functionality? let me know what you think when you get a chance. thanks,

**Comment by simensta** [comment]
@mcbouslog -- nice work on this feature! A few comments:
- _Dropdown Editor_: After I enter options for a dropdown question, I do not see those options when I revisit the dropdown editor at a later time. Is there a place to see previously added options?
- _Dropdown on Classify page_: When an answer to an upstream dropdown makes a dependent dropdown irrelevant, it would be nice to give an ui-indicator that the user is not expected to fill out that dependent dropdown menu.

**Comment by brian-c** [comment]
Regarding CSV imports: Are there plans for the CSV to include more than one column? If not, it's really just a text file, which doesn't need to be parsed. And if that's the case, I think a simple copy-pastable textarea would be simpler than a file upload.

**Comment by mcbouslog** [comment]
A simple copy-paste sounds good to me - no plans for anything other than one column. 

I'm picturing the most often use case as a science team member with an Excel or CSV file with a list of the options they want to add to the dropdown task. So is the idea they would copy the related cells, then paste into a textarea, then click apply? Then the textarea content would be iterated through based on regExp and each label/cell would be added as an option? I think I can picture how this would work, but want to confirm before proceeding.

**Comment by brian-c** [comment]
I think that sounds right. No need for a regex though, each line is an option right?

**Comment by mcbouslog** [comment]
so there are currently two methods to importing option labels on the table:

1) csv file import - click [here for staged branch](https://dropdown-csv-import.pfe-preview.zooniverse.org/), [here for code](https://github.com/mcbouslog/Panoptes-Front-End/tree/dropdown-csv-import)
2) textarea copy-paste - click [here for staged branch](https://dropdown-textarea-import.pfe-preview.zooniverse.org/), [here for code](https://github.com/mcbouslog/Panoptes-Front-End/tree/dropdown-textarea-import)

the textarea copy-paste is very nicely simpler code (thanks Brian for recommending!), thereby what i think we'd want to go with, but i'm not sure i've explained how to use it well or provided the optimal UI so a researcher would know what to do.

please try one of the staged branches, or if you only have time for one try [2) linked here again](https://dropdown-textarea-import.pfe-preview.zooniverse.org/), and attempt to add dropdown options via import (after enabling access to the dropdown task via admin if necessary). i think i've added @brian-c and @simensta to a test project (NfN task test) with the dropdown task available, @aliburchard - what's your Zooniverse ID on preview/staging - 'aliburchard'?

@eatyourgreens - no worries if not interested in this, just thought i'd mention in case.

let me know what you think. thanks!

**Comment by aliburchard** [comment]
@mcbouslog yup, i'm aliburchard on staging. Sorry, just catching up on github stuff now - does this still need testing on staging? If so, point me in the right direction.

**Comment by mcbouslog** [comment]
brief update - had a good conversation regarding this on Slack with Ali, updating accordingly and hope to have a new version within a day or two...
