### ISSUE TITLE
User can click "done" at any time to skip rest of workflow

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#239]
I hope this is a bug and not a feature. Currently for single-choice questions, before a user selects an answer, the green button says "done". And if the user clicks it, s/he finishes the workflow without answering that question or any remaining ones. Once the user selects a radio-button, the green button text changes to "next" (if there are more questions) and the user cannot UN-select his/her choice.

**Comment by twhyntie** [comment]
@mkosmala Are you ticking "Required" for the tasks? I think this greys out the "Done" button...

**Comment by mkosmala** [comment]
My understanding was that required=1 is the default for single-choice questions. Tell me if I'm wrong.

**Comment by twhyntie** [comment]
@mkosmala Are you using the new workflow editor? That's where I've started from. The default state of the "Required" tick box is unticked. So I guess this will default to `required=0` when new questions are added to a workflow.
For me (using the workflow editor) this seems reasonable.

**Comment by mkosmala** [comment]
@twhyntie. I think that's exactly right. Since @brian-c has written the UI, it seems the JSON specs have wandered a bit from when they were written several months ago.

**Comment by brian-c** [comment]
Yep, `required` now applies to single and multiple types. Should also note that it's now a boolean.

**Comment by twhyntie** [comment]
@mkosmala Out of interest, are you creating workflows by some other mechanism then?

**Comment by twhyntie** [comment]
@mkosmala Oh yes, I should probably have read the whole of the second post :-)

**Comment by mkosmala** [comment]
@twhyntie Not your fault. I edited my second comment while you were replying to it.
@brian-c If required is now boolean, does that mean we can't require, say, at least 2 answers for 'multiple' questions? (This is a hypothetical. I don't have need of it.) Also, do I need to put 'required' on my 'drawing' questions?

**Comment by chrissnyder** [comment]
Sounds like the original issue was resolved. Closing.
