### ISSUE TITLE
Roles on Talk are now white andinvisible on the list of recent discussions and on the individual discussion pages itself

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2391]
Looks like the  pull request by @marten to make the faq and research pages more visible have now made all of the Talk roles vanish as they are now white text on white background instead of grey/black or white background. Looks like all the text is still there it's just now white which is making it invisible.

I think this is important to fix soon if possible as now you can't tell who is a researcher or moderator. 

<img width="764" alt="screen shot 2016-04-05 at 9 50 18 pm" src="https://cloud.githubusercontent.com/assets/753325/14306109/a03a3936-fb78-11e5-895b-b747dc07e464.png">

<img width="759" alt="screen shot 2016-04-05 at 9 50 07 pm" src="https://cloud.githubusercontent.com/assets/753325/14306121/b9412016-fb78-11e5-833c-79993c96d488.png">

Highlighting with my mouse
<img width="746" alt="screen shot 2016-04-05 at 9 50 10 pm" src="https://cloud.githubusercontent.com/assets/753325/14306116/aa9d2e92-fb78-11e5-96cb-9fbedba67040.png">

**Comment by mschwamb** [comment]
sorry I think it might be @alexbfree's pull request that did this

**Comment by mschwamb** [comment]
Interestingly Zooniverse team appears to be fine on Zooniverse Talk

<img width="822" alt="screen shot 2016-04-05 at 9 56 53 pm" src="https://cloud.githubusercontent.com/assets/753325/14306194/70a69614-fb79-11e5-8645-f48868d48538.png">

**Comment by mschwamb** [comment]
Saw there's a pull request to deal with this - thanks @marten and @eatyourgreens . I can close if it looks visible to me and the Comet Hunters' moderator who pointed it out.

**Comment by mschwamb** [comment]
Maybe I misread the pull request - Thanks very much @eatyourgreens!

**Comment by eatyourgreens** [comment]
Should be fixed on the live server now, @mschwamb

**Comment by mschwamb** [comment]
Thanks. Looks great from moderator and researcher. It might make the Zooniverse team label hard to read now. Thanks for fixing this. 
<img width="793" alt="screen shot 2016-04-06 at 3 57 03 am" src="https://cloud.githubusercontent.com/assets/753325/14314399/c7f7b88a-fbab-11e5-9b59-4d14f78d45c7.png">

<img width="781" alt="screen shot 2016-04-06 at 3 58 24 am" src="https://cloud.githubusercontent.com/assets/753325/14314412/e0c9f53a-fbab-11e5-9745-ff985f04d196.png">

So maybe a slightly different shade of green for that?
