### ISSUE TITLE
Field guide should not show on the landing page of a project 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2397]
At least in Firefox the field guide shows up on the landing page of a project with an active field guide. I think that's a bit confusing as you're not sure what you're supposed to click or go to. 

<img width="1146" alt="screen shot 2016-04-07 at 7 03 09 am" src="https://cloud.githubusercontent.com/assets/753325/14353706/2317a75a-fc8f-11e5-87e3-88fb0f451b38.png">

**Comment by brian-c** [comment]
This is as intended, the field guide is available anywhere in the project.

**Comment by mschwamb** [comment]
I get the having the field guide showing up everywhere else on a project website , but I find it odd to have it show on the landing page. Other previous custom Zooniverse projects with site guides have a clean landing page. My thinking is that if you're new and checking out the project, you have no idea the task but you would have the ability to review the field guide without even knowing what the task of the project is, and that the landing page should as minimal as possible to get people straight in to classify and into then task.

**Comment by chrislintott** [comment]
I agree with Meg, though I think it’s a low priority fix.
