### ISSUE TITLE
Image extends well beyond the browser window on research page in Firefox but looks okay in Chrome

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2398]
Chrome
<img width="1280" alt="screen shot 2016-04-07 at 7 07 19 am" src="https://cloud.githubusercontent.com/assets/753325/14353759/66c026d0-fc8f-11e5-81df-e67f502521ec.png">

Firefox
<img width="1280" alt="screen shot 2016-04-07 at 7 06 35 am" src="https://cloud.githubusercontent.com/assets/753325/14353760/6a0d2de2-fc8f-11e5-9284-550368510633.png">

**Comment by camallen** [comment]
looks like this is hard coded into the html with width / heigh specified

`<img src="https://panoptes-uploads.zooniverse.org/production/project_attached_image/8be069ea-fbd5-4adf-b677-85fdb584269a.png" alt="Map of WA.png" width="2500" height="500">`

**Comment by mschwamb** [comment]
Not sure if it's the same thing here as well, but in Firefox parts of the FAQ are also unreadable with the black text on the image background 

<img width="1153" alt="screen shot 2016-04-07 at 7 26 37 am" src="https://cloud.githubusercontent.com/assets/753325/14354443/29a43400-fc92-11e5-8dae-9bcf077f8eec.png">

**Comment by srallen** [comment]
Images aren't overflowing anymore.
