### ISSUE TITLE
Add "beta" switch to projects

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#240]
With appropriate warnings about changing things once the project is public.

**Comment by mkosmala** [comment]
@brian-c  Hey, I was wondering about this. Where beta tests run? On demo.zooniverse.org? Is all that happens behind the scenes for running a beta test is that "private" gets switched from 'true' to 'false'?

**Comment by brian-c** [comment]
I believe there are three flags on projects that affect discovery, `private`, `beta`, and `approved`.

- `{"private": true}` projects are available only to users with roles.

- `{"private": false, "beta": true}` projects will be available from a special list of beta projects, where users will be informed that their data will probably be thrown out.

- `{"private": false, "approved": true}` projects will be listed in the main list (home page, or /projects or something).

@edpaget Do I have all that right?

**Comment by edpaget** [comment]
I think we'd only have ones that have `{"private": false, "beta": true, "approved": true}` show up on the list of beta projects.

**Comment by aliburchard** [comment]
@brian-c @edpaget @camallen I'm a bit confused as to how this private tag maps to the states we defined/discuss in issue zooniverse/panoptes #445 -- we had started a discussion of defining "private" in this google doc (https://docs.google.com/document/d/1EQ6hm-wsE6dhmA1G67uqenq8c8VxMf_brcjFSyTXSYo/edit), but I don't know if it was ever resolved.

But what we did decide that there were two axes that projects exist on. One is the "small," non-zooniverse approved project vs. the "full" zooniverse approved project. The other axis is "playground" vs. "live," at which point classifications matter and aggregation can happen. Beta is a stage that projects go through if they want to be full on Zooniverse approved projects.

So, is there going to be a "live" vs. "playground" flag as well to indicate that a project has transitioned from the building stage to the collecting classifications stage? 

And can a project is "private" but "live", so that a research team can produce classifications and aggregate data, but the project is only visible to certain people? (Sounds like there are education cases for this.)

**Comment by vrooje** [comment]
"Private" but "live" also has applications for humanitarian projects (we've
been approached about this).

**Comment by edpaget** [comment]
@aliburchard from what I understood projects will always collect classifications (there's not a reason to complicate the backend by having to decide whether or not to save classifications). The distinction between a "playground" vs. "data collecting" project is purely a UI thing that will cause the Panoptes site to warn the user about changes to the Workflow.

**Comment by camallen** [comment]
@edpaget we need to save that "playground / live" state somewhere.

**Comment by brian-c** [comment]
So as far as how we're going to display this in the UI, does this make sense?

- **Private** `private: true, beta: false, approved: false`, Only collaborators can see it (start initial development)

- **Playground** `private: false, beta: false, approved: false`, Anyone with the URL can see it (share with friends, classrooms, iterate on the workflow, etc.)

- **Beta awaiting approval** `private: false, beta: true, approved: false`, Same as playground, but we get a notification and someone vets it, (or doesn't and contacts the owner)

- **Approved beta** `private: false, beta: true, approved: true`, Shown to beta testers

- **Approved** `private: false, beta: false, approved: true`, Listed publicly, maybe workflows no longer editable?

**Comment by camallen** [comment]
Why is it only approved projects have locked workflows?

@brian-c, @aliburchard what about users that want to have small private / playground projects and want to use the aggregation, they happily set up a project, think they're done and send a link to get people classifying. Classifications roll in for a while. Then after a bit they decide to / accidentally change their workflow and the version changes and the previous classifications won't automatically work in the aggregation engine and their work seems to have disappeared without any obvious warnings.

To me it sounds like the user has to enter their project to "research / science mode" and that way projects have a state field (as per #766) that the UI can use to lock workflows, etc. 

@edpaget also raised an interesting point about subject retirement and when classifications should start counting to it. Perhaps using a project state field to turn on retirement counts.

**Comment by aliburchard** [comment]
@edpaget and @brian-c I don't think the private, beta, and approved tags are enough to specify a project, and I think @camallen 's example scenario above is precisely why we need a "live" mode. 

@brian-c I'm not sure I agree with playground vs. private. I think that whether a project is "private" is completely disconnected to it's development stage. I know @vrooje has some specific use cases for projects that are in full on "live" mode but need to be restricted somehow.

**Comment by aliburchard** [comment]
Another thought: would it be possible to add "volunteer" to project roles so that "live" projects could still be completely "private"? Since "private" projects are only viewable to people with project roles?

**Comment by edpaget** [comment]
At the moment the tester, scientist, and moderator roles, don't grant an permissions beyond being able to see a project. I can add a similar one called volunteer as well.

**Comment by brian-c** [comment]
I'm cool with whatever, but please keep in mind:

- We need the best solution for like, 90% of cases. We're not going to please everyone.

- We need to make it clear to the project creator exactly what's happening.

@aliburchard can you give a more complete description of what you think project stages and options should be?

**Comment by brian-c** [comment]
Everyone's a volunteer. I don't think we need a special volunteer role.

**Comment by edpaget** [comment]
@brian-c I think that's just for people who are classifier-only on private projects, since the other roles have connotations.

**Comment by brian-c** [comment]
Wouldn't that just be a non-private, non-beta project, and you'd share the URL with the people who need it? "Playground" in my steps above.

**Comment by edpaget** [comment]
I think there are valid reasons to want it to be totally private. For instance you have pictures of people taken not in a public place. Keeping your project private will keep those subjects private as well.

**Comment by brian-c** [comment]
I guess I just don't think that's one of the cases we should be concerned with right now. Isn't that also why we're working on making Panoptes easy to self-host?

**Comment by aliburchard** [comment]
@brian-c @edpaget it's a critical use case for educators.

**Comment by edpaget** [comment]
Yeah it's a trivially simple change though on my end though, so I'll just do it there. Up to you if you want to to add it to the Front-End (and support for it already exists with the Tester, Scientist, and Moderator roles).

**Comment by aliburchard** [comment]
As far as clarifying stages, requested above: First, I think that it's critical we consider two axes of the project stage. 1) is what stage of development it's in (playground vs live) and 2) is who has access to a project. These two axes are independent, such that being a "live" project has nothing to do with who can see the project. @chrislintott might be able to articulate this distinction better.

Following up with proposed stages momentarily

**Comment by brian-c** [comment]
Are educators a priority for first release?

Like I said, I'm fine building whatever we come up with, but let's really pin it down here.

**Comment by aliburchard** [comment]
I think the issue is who can see a project (i.e. "private") is completely divorced from the stage of development. So the "live" tag I think is really important. Adding a "volunteer" role I think is an easy fix to the issue of private-live projects.

**Comment by aliburchard** [comment]
proposed stages:

For small projects that never desire to go through the zooniverse process, the stages look like this:
**playground:** a project in development. Can be: private = T *or* F, beta = F, approved = F, live = F *or* private = F, beta = F, approved = F, live = F

**science mode:** (or "live, small project, whatever you want to call it) would be private = T *or* F, beta = F, approved = F, live = **T**

Note that when a project switches from *live = F* to *live = T* is when project builders should be warned about changing the interface.

For projects wanting to go through the Zooniverse approval process, you'd have the same playground stage as above, but also the beta and approval stages.  I suspect all projects desiring Zooniverse approval will not be "private." 

I'm unclear as to whether the "beta" tag indicates that a project has requested a beta test or whether it has completed a beta test? As far as I understand, we need to apply some basic (perhaps automated) checks to a project before allowing it to go out to the Beta list (i.e. the description and science case fields are filled out). 

Perhaps something like:
**Beta awaiting approval** private = F, beta = T, approved = F, live = F (the project builders have requested to go to beta)
**Approved Beta** private = F, beta = T, approved = T, live = F (the project has been beta tested and any changes made) but is not yet live on the Zooniverse page
**Approved** private = F, beta = T, approved = T, live = T - the project is Zooniverse approved and listed publicly. We should be opinionated about workflow changes at this point.

**Comment by chrissnyder** [comment]
I've always found the Google Drive visibility range to be pretty perfect for almost any use case:

- Only I can see it
- Only collaborators can see it
- Only those with the link can see it
- Anyone can see it

On project lifecycle, what does the "beta" stage in the proposed above process accomplish? Betas typically fulfill two goals for two: one is to establish whether or not users can do the task, and two to find and iron out any technical issues. If a projects wishes to be vetted by us, shouldn't they already know the answer to the first question? And the second one is by-definition already answered by virtue of it being built on the platform.

**Comment by edpaget** [comment]
They might not have a group of people to try out their project. Beta signals to our tester community they should give it a try, since we still need to know if people can do the task and if the task is asking the right questions.

**Comment by twhyntie** [comment]
With my educator hat on, the value for us is getting students designing and refining the workflows in order to do better science. My impression is that this is covered by playground, beta, etc. (i. e. the development axis.)

Regarding private projects, isn't there a more fundamental problem with hosting sensitive data on this Panoptes instance? Wouldn't that place an unfair security burden on the Panoptes team? My worry would be that if private is an option users would quite literally be lulled into a false sense of security and upload sensitive data to an S3 bucket that ultimately the Zooniverse would be responsible for. In this situation I think a self-hosted instance would be far more appropriate.

**Comment by aliburchard** [comment]
@twhyntie the most common use case I've encountered for private projects was from educators who envisioned classrooms building projects that included pictures of students. I think that a very clear statement about liability on our part (perhaps about inherent vulnerability of putting stuff online, and discouraging people from putting very sensitive material online) removes the weight of **responsibility**. By making a project private, only authorized people can access the URL, but we're not guaranteeing that someone committed couldn't get to that data eventually.

**Comment by twhyntie** [comment]
@aliburchard OK. Pictures of students have to be handled very, very carefully. A flavour of the legal implications/procedures (for the UK at least) can be found e.g. [here](http://www.actnow.org.uk/media/articles/Guidance_Note_on_use_of_images.pdf). For example, Panoptes would need some way of tracking the parental consent for every subject featuring a picture of a student. And I'm sure a statement about liability could be written and implemented, but I'd strongly recommend seeking legal advice on how it would hold up in the worst case scenario.

Don't get me wrong - I think such use cases could be really interesting and would certainly enhance the relevance for participating students. In fact the legal and ethical implications of data collection featuring people offers a wealth of teaching opportunities and an insight into How Science Works (which features on many curricula). We just need to make sure we do everything to protect those who are under 18 and minimise risk wherever possible.

(For context - I work as a scientist based in a school, and one of the reasons we're working with @chrislintott et al. to advise on issues of this nature.)

**Comment by camallen** [comment]
@aliburchard responding to this comment, https://github.com/zooniverse/Panoptes-Front-End/issues/240#issuecomment-97866518

My understanding of the 'live' attribute is used to turn the project to "science mode" and be used to warn / protect against changes in the UI. I.e. i've setup my workflows, data seems to be flowing and i'm happy with the project and task set. I then "launch" my project to "science mode" and thus protect against workflow changes.

In my mind projects progress from "playground (live=f)" to "science mode(live=t)" at all times and **we should be opinionated about workflow changes at this point** but users can still change their settings.

Projects can then be in the following states:
**Beta awaiting approval** private = F, beta = T, approved = F, live = T (the project builders have requested to go to beta)
**Approved Beta** private = F, beta = T, approved = T, live = T the project has been beta tested and any changes made and perhaps lives on the approved beta projects page
**Sponsored** private = F, beta = T, approved = T, live = T the project is Zooniverse approved and listed publicly. 

What do you think?

**Comment by aliburchard** [comment]
Yup, agree with all of that. And (if I'm understanding properly) following the above stages, if the science team needs to make changes to the interface after beta, they would take the project "out" of science mode (i.e.. toggle to Live = F), make those changes, and then re-enter science mode after the workflow changes have been made?

**Comment by chrislintott** [comment]
I agree with @camallen's proposed states and suggest for now that any change to a workflow restarts the approval process. That might be unworkable in the long-term, but let's deal with that if and when we get there.

For projects which are not intended to go through the Zooniverse process, I think for now we can be very simple. As @aliburchard has :

playground: a project in development. Can be: private = T or F, beta = F, approved = F, live = F 

As all classifications are saved, then that will also work for a 'final' version of a private (educator or scientist) workflow which is ready for classifications. I think in the long run we'll want to be more intelligent than attaching classifications to each iteration of a workflow, but that's where we are now so people can just live with having those classifications separate.

**Comment by vrooje** [comment]
Related question: does changing the help text only count as changing the
workflow, either for purposes of loss of existing classifications or for
approval process?

**Comment by chrislintott** [comment]
Talked this through with @aliburchard and we think we have the definitive answer. There are six states that matter (!) with the following flags : 

![screen shot 2015-05-04 at 20 39 39](https://cloud.githubusercontent.com/assets/423607/7468594/80d4b6f4-f302-11e4-8184-1366ecfe5509.png)

Playground: Researcher is building a project, perhaps sharing with collaborators. Classifications are viewable and saved. 
Playground —> Beta: Researcher requests that the Zooniverse review and approve project for beta testing by setting Beta = T and Lock = T. Zooniverse reviews project and approves for Beta by setting Beta-approved = T. Project is now displayed on Beta page. Researchers decide when Beta is finished.

Note that beta is a flag set by the user and beta-approved by us. 

To make changes to project following Beta, researcher selects a “Make Changes” option. This sets Beta and Beta-approved = F (requiring that the project go through Beta/approval process again after changes have been made).


Beta —> Launch: When satisfied with results/interface, researchers select “Launch!” (This sets Launch = T and Beta = F; Beta-approved = T to indicate that the project has been through beta process).  Zooniverse reviews project and approves for home page by setting Launch-approved = T.

Flags
Private: If Private = T, only people with project roles and zooniverse team can view project. If Private = F, url is sharable and visible with anyone.
Beta: If Beta = T, project available for display on Beta page. If Beta = F, project unavailable for display on Beta page.
Beta-approved: If Beta-approved = T (and Beta = T), display on Beta page. 
Launch: If Launch = T, project is available for Zoo-home iff Launch-approved = T 
Launch-approved: If Launch-approved = T, project is on Zoo home
Lock: If Lock = F, any collaborator can make changes. If Lock = T, only the project owner can make changes.

All clear?

**Comment by chrislintott** [comment]
And @vrooje - no, I think all text apart from the main workflow can be altered without forcing a new set of classifications.

**Comment by camallen** [comment]
@vrooje changing the workflow text modifies the minor value of the *worklow version*, which is a key comprised of `workflow_model_version.workflow_text_version`. 

We can then decide which of these values we should aggregate on. I.e. I don't care about text changes but I do care about task changes so version "1.X" OR i care about task and text changes so version "1.1" only.

**Comment by vrooje** [comment]
Ah, so the scary warning message on the interface about loss of existing
classifications is referring to the aggregated product(s), not the raw
classifications. Cool.

**Comment by aliburchard** [comment]
@vrooje are you talking about the warning that pops up when making changes to a "public" project? I think that text needs updating (primarily because it has nothing to do with the project being private vs public, but also because it results in a new workflow version which affects aggregation, but doesn't delete previous classifications).

**Comment by camallen** [comment]
Agree we could probably word that better. 

We **never** delete completed classification and we're currently including all the classifications in the dumps.

**Comment by camallen** [comment]
@chrislintott @aliburchard in response to https://github.com/zooniverse/Panoptes-Front-End/issues/240#issuecomment-98984793

Those states look good. Will there be some time limit / classification count needed to progress from a "locked beta" to "request launch". I assume that a lot of people when approved for zoo wide beta will just want to launch.

**Comment by mkosmala** [comment]
@camallen beat me to it. @chrislintott @aliburchard: I was also going to say that I would expect a normal progression might be:
1. I build a project
2. I request beta approval
3. I run a beta test
4. I fix some workflows and feel that a second full beta test is unnecessary
5. I request launch approval

**Comment by aliburchard** [comment]
@mkosmala I think @chrislintott and I decided that right now, as it's a pretty manual process, the Zooniverse will decide whether the project really needs a second beta, or can be launched after making minor changes raised by the first beta (we have no way of knowing how major or minor the changes were without reviewing the project). But we should have a way to say "yup, beta changes were minor, go ahead and launch" vs. "this person totally broke the project trying to fix after beta comments."

**Comment by mkosmala** [comment]
@aliburchard Sounds good!

**Comment by vrooje** [comment]
That table is really helpful. Just so I'm clear: the vertically listed states are a mix of user-set and Zooniverse-set, correct? I think I understand that the states {private, beta, launch, lock} are set by the user, and {beta-approved, launch-approved} are set by the Zooniverse, correct? Or is the lock setting an automatic setting once the user selects "beta" (or if the project is "Live Non-Zooniverse")?

**Comment by camallen** [comment]
Lock would be set by the backend when you request a "beta" or "launch". The UI can then use this field to warn users about changes. Any changes after these events sets `lock = F`.

**Comment by mkosmala** [comment]
@camallen And the user would also need to be able to set ```lock = T``` himself/herself to create a "Live Non-Zooniverse" project, according to the table above.

**Comment by camallen** [comment]
@mkosmala good point. Playground mode will need to allow the lock field to be set by the UI with a button like "Go Live".

**Comment by brian-c** [comment]
I _think_ I've distilled this down to some kinda UI.

Deployed here for feedback (there's a new "Visibility" tab section for each project): http://demo.zooniverse.org/panoptes-front-end/project-mode-switching/#/lab

I'm sure I've misunderstood things, but is this close to what people are expecting?

**Comment by camallen** [comment]
@brian-c looks good! What is the backend field for launch? I think this is the only thing attribute missing in the backend.

**Comment by brian-c** [comment]
Thanks @camallen, I'm thinking fields will be `private`, `live` (i.e. not-"lock" in the table above), `beta`, `beta_approved`, (read-only) `launch`, and `launch_approved` (read-only). I wouldn't make any changes until we figure out this UI though.

Also: I assume when a beta or launched project unchecks "live" they'll lose beta or launch status and have to go through the process again, correct?

**Comment by edpaget** [comment]
@brian-c might want to mention that a project has to be live before classifications are counted towards retiring a subject, maybe 'activates retirement rules'.

**Comment by brian-c** [comment]
Just pushed a new version after talking with @chrislintott.
