### ISSUE TITLE
If too long display name gets cut off by Talk comment box 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2409]
<img width="1129" alt="screen shot 2016-04-09 at 8 56 14 pm" src="https://cloud.githubusercontent.com/assets/753325/14408012/2608f9c4-fe96-11e5-863f-24d2f01f2121.png">

**Comment by alexbfree** [comment]
Anyone have thoughts on a solution to this? Maybe replace any characters after a certain length with `...` - with a hover tooltip showing the full username? (also, it can still be clicked to reveal the full username on the user's profile)

**Comment by alexbfree** [comment]
seems like the ellipsis approach is the best practice so we should go with that http://ux.stackexchange.com/questions/28109/truncating-long-text-labels-best-practices

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.

**Comment by mschwamb** [comment]
@jelliotartz I think this should be addressed in some way, but as it is a minor issue I'm not sure why I'd have to keep commenting on it for it to be left as an issue when there is a redesign or time to make a small fix change like this.
