### ISSUE TITLE
Windows 10 - Chrome no markers can be drawn

### ISSUE THREAD

**Issue by khufkens** [zooniverse/Panoptes-Front-End#2410]
A user flagged an issue with drawing polygons on Windows 10 using Google Chrome.

He wasn't able to draw anything, even after restarting. Can't verify the bug (no access to W10). Everything seems fine on OSX and Linux using Chrome.

**Comment by brian-c** [comment]
Polygons seem okay to me in Windows 10/Chrome 49. Maybe a plugin issue?

**Comment by khufkens** [comment]
Thanks, consider this closed. Probably a user end issue of sorts.
