### ISSUE TITLE
Installation/setup issues

### ISSUE THREAD

**Issue by Crentist** [zooniverse/Panoptes-Front-End#2413]
Hello there!
For the last couple of weeks I've been trying to run Panoptes (backend+frontend), and I've encountered some resistance :).
I'm able to run the backend with no trouble (as far as I know), and I can also run the frontend (`npm start`) and connect to my own backend. But whenever I try to run `npm run stage-branch` (or any other script, for that matter) I get an error I can't quite figure out.

> 
> vendor.dbcc3cdc67cabb411d2273b09a69ac44.js:
> 
>  209585 bytes gzipped
> main.5f208a8a9a596b41945a7ab1458ec3df.js: 329468 bytes gzipped
> main.043605833795ce4755a2bd6fd89efdda.css: 20920 bytes gzipped
> Local: ./build
> Bucket: zooniverse-static
> Prefix: preview.zooniverse.org/panoptes-front-end/master 
> /home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:30
>             throw err;
>             ^
> 
> TypeError: Cannot read property 'Contents' of null
>   at Response.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/publisssh/lib/publish.iced:120:16)
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:353:18)
>   at Request.callListeners (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:595:14)
>   at Request.transition (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:21:10)
>   at AcceptorStateMachine.runTo (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:14:12)
>   at /home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:26:10
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:37:9)
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:597:12)
>   at Request.callListeners (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:595:14)
>   at Request.transition (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:21:10)
>   at AcceptorStateMachine.runTo (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:14:12)
>   at /home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:26:10
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:37:9)
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:597:12)
>   at Request.callListeners (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
>   at callNextListener (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
>   at Request.RESET_RETRY_STATE (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/event_listeners.js:359:9)
>   at Request.callListeners (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:101:18)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:595:14)
>   at Request.transition (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:21:10)
>   at AcceptorStateMachine.runTo (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:14:12)
>   at /home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:26:10
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:37:9)
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:597:12)
>   at Request.callListeners (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:595:14)
>   at Request.transition (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:21:10)
>   at AcceptorStateMachine.runTo (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:14:12)
>   at /home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:26:10
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:37:9)
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:597:12)
>   at Request.callListeners (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:595:14)
>   at Request.transition (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:21:10)
>   at AcceptorStateMachine.runTo (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:14:12)
>   at /home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:26:10
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:37:9)
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:597:12)
>   at Request.callListeners (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
>   at Request.emit (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:595:14)
>   at Request.transition (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:21:10)
>   at AcceptorStateMachine.runTo (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:14:12)
>   at /home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/state_machine.js:26:10
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:37:9)
>   at Request.<anonymous> (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/request.js:597:12)
>   at Request.callListeners (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
>   at callNextListener (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
>   at IncomingMessage.onEnd (/home/crentist/Panoptes/Panoptes-Front-End/node_modules/aws-sdk/lib/event_listeners.js:207:11)
>   at emitNone (events.js:85:20)
>   at IncomingMessage.emit (events.js:179:7)
>   at endReadableNT (_stream_readable.js:913:12)
>   at _combinedTickCallback (node.js:383:13)
>   at process._tickDomainCallback (node.js:431:11)
> 
> 
> npm ERR! Linux 4.2.0-27-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "stage"
> npm ERR! node v5.9.1
> npm ERR! npm  v3.7.3
> npm ERR! code ELIFECYCLE
> npm ERR! panoptes@0.0.2 stage: `export DEPLOY_SUBDIR=${DEPLOY_SUBDIR:-panoptes-front-end}; export NODE_ENV=staging; npm run build && publisssh ./build "zooniverse-static/preview.zooniverse.org/$DEPLOY_SUBDIR"`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the panoptes@0.0.2 stage script 'export DEPLOY_SUBDIR=${DEPLOY_SUBDIR:-panoptes-front-end}; export NODE_ENV=staging; npm run build && publisssh ./build "zooniverse-static/preview.zooniverse.org/$DEPLOY_SUBDIR"'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the panoptes package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     export DEPLOY_SUBDIR=${DEPLOY_SUBDIR:-panoptes-front-end}; export NODE_ENV=staging; npm run build && publisssh ./build "zooniverse-static/preview.zooniverse.org/$DEPLOY_SUBDIR"
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs panoptes
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls panoptes
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/crentist/Panoptes/Panoptes-Front-End/npm-debug.log
> 
> npm ERR! Linux 4.2.0-27-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "stage-branch"
> npm ERR! node v5.9.1
> npm ERR! npm  v3.7.3
> npm ERR! code ELIFECYCLE
> npm ERR! panoptes@0.0.2 stage-branch: `export DEPLOY_SUBDIR="panoptes-front-end/$(git symbolic-ref --short HEAD)"; npm run stage`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the panoptes@0.0.2 stage-branch script 'export DEPLOY_SUBDIR="panoptes-front-end/$(git symbolic-ref --short HEAD)"; npm run stage'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the panoptes package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     export DEPLOY_SUBDIR="panoptes-front-end/$(git symbolic-ref --short HEAD)"; npm run stage

I'm not even sure what this is supossed to do, but since the site seems to run without it, I left it aside.
Which brings me to my second issue: I can't upload any media (avatars, subjects, background images, etc). From what I can gather, you upload media to an Amazon S3 Bucket, and since I have my own, I'd like to use it, but I can't find anywhere in the config files (or anywhere in the code) where to change this. This also seems to be related to my first issue, but I can't figure it out.
Anyway, the error I get when trying to upload is this one

![erroruploadingpanoptes](https://cloud.githubusercontent.com/assets/7231917/14429557/4711b61c-ffd4-11e5-8b27-15e30ee71643.png)

I'm running everything in a VM with Ubuntu 14.04, and I use Google Chrome. Let me know if you need any more details. Any help is greatly appreciated. Cheers!

**Comment by camallen** [comment]
Hey @Crentist the stage branch deploys the code, you won't have access to this but you could change the details for your own deployment if needed.

The second issue is an api issue, probably best to open an issue on that repo (https://github.com/zooniverse/Panoptes/)

**Comment by Crentist** [comment]
Thanks @camallen, will do!
