### ISSUE TITLE
[project page branch] Clicking 'All Disciplines' doesn't remove active filter

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2419]

**Comment by srallen** [comment]
This seems to only be broken using the dev db. It works with production.

**Comment by eatyourgreens** [comment]
@srallen Are you looking at https://project-page.pfe-preview.zooniverse.org/projects?env=production
This bug only appears if the discipline is the only parameter in the query string. Try clicking on the 'Projects' link, then reproducing it.

**Comment by srallen** [comment]
Ah, I see. Thanks.

**Comment by alexbfree** [comment]
fixed by #2436
