### ISSUE TITLE
Researcher/Moderator label on Notifiications is now just a grey box 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2420]
Might be for @eatyourgreens since you fixed it elsewhere. On Talk notifications the researcher and mod labels just show up as a dark grey box

<img width="1132" alt="screen shot 2016-04-13 at 3 03 04 am" src="https://cloud.githubusercontent.com/assets/753325/14472231/c0ab98a2-0124-11e6-8ba7-cbdcf6c0270c.png">

**Comment by alexbfree** [comment]
This could be my fault due to https://github.com/zooniverse/Panoptes-Front-End/pull/2374. I'll take a look if no-one beats me to it.

**Comment by mschwamb** [comment]
@alexbfree could you take a look whenever you get a free moment? thanks

**Comment by mschwamb** [comment]
This is fixed so I'm closing. Not sure what PR addressed this.
