### ISSUE TITLE
Tool tip task not working

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2422]
@simensta Trying to use the tool-tip task (i.e., the sub-task on a marking task) on this project on either Chrome or Firefox on a Mac OSX 10.9.5. If I remember correctly, you created this tool, so I thought best to direct this question to you.

When I click on question (see image here), nothing happens. Can you take a look and see what might be causing this? I was able to use this tool a month or so ago with no problem. 

I've added you as a collaborator on the project so you can try as well. https://www.zooniverse.org/lab/2501/workflow/1758

<img width="820" alt="tool-tip-error" src="https://cloud.githubusercontent.com/assets/4975655/14480952/b36b448e-00f3-11e6-9b6e-b348acd8155f.png">

**Comment by simensta** [comment]
I will take a look at this first thing today.
