### ISSUE TITLE
[project page branch] Proper handling of zero-result discipline filters

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2423]
As @srallen pointed out, when you click the Humanitarian filter there are no projects. There was one when we first coded this, but it has since been archived/removed.

Also you get an ugly output
![screenshot 2016-04-13 10 00 24](https://cloud.githubusercontent.com/assets/1473244/14488145/943db11c-015e-11e6-83fc-faaf5ff1db5c.png)

We need to design a better solution, which may include one or some combination of:

1. Clean up the display when there are no results.
2. When no results are found, remove the filter from the filmstrip and revert back to All Disciplines
3. Find some way to pre-emptively remove filters we know to be empty (if we can find a way to do this without running every filter query! Maybe add support at back end to provide a list of "currently active discipines"?)

Whatever solution we come up with should account for the fact that getting zero results could happen on any of the queries. Though we could possibly rely on hardcoding our knowledge of what exists in the short term.

**Comment by alexbfree** [comment]
Note, the linked PR #2425 implements 1, but not 2 or 3, so we need to keep this ticket open after that PR is merged.

**Comment by srallen** [comment]
For the sake of getting the project page done for now, probably the most simplest thing to do now is to comment out this line: https://github.com/zooniverse/Panoptes-Front-End/blob/project-page/app/components/disciplines.cjsx#L8

A more dynamic approach could come in a later PR.

**Comment by alexbfree** [comment]
@srallen I agree with the pragmatic approach @srallen . Will do that now.

**Comment by alexbfree** [comment]
Short term fix was committed in https://github.com/zooniverse/Panoptes-Front-End/pull/2432
