### ISSUE TITLE
[project page branch] Decide default sort order and set it

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2424]
Per #2417, even though we have removed default sort from the dropdown, it is still in effect when you first arrive on the page. Need to do something about this, either updating backend to return a more sensible order, or activating one of the more useful sorts by default.

This is more of a To-Do than a bug, just noting it here so we don't forget. Not a blocker for launch.

**Comment by camallen** [comment]
@alexbfree the backend has a "sensible" project sort order (via the `launch_approved` and `beta_approved` query params), [code here](https://github.com/zooniverse/Panoptes/blob/6237b1df643c8464ecb1cab868088a2bb3ada083/app/controllers/api/v1/projects_controller.rb#L55). 

![image](https://cloud.githubusercontent.com/assets/295329/14489557/d9e6c706-0165-11e6-9b81-2df4a4e3d19f.png)

The results may not be what you expect but the sort order is specified and configurable.

**Comment by eatyourgreens** [comment]
Default sort order is set in the front-end here, I think, as activity descending:
https://github.com/zooniverse/Panoptes-Front-End/blob/project-page/app/components/project-card-list.cjsx#L188

**Comment by eatyourgreens** [comment]
@alexbfree I've started a branch for the sort issues: https://github.com/zooniverse/Panoptes-Front-End/tree/project-page-sort

**Comment by alexbfree** [comment]
@camallen I don't disagree that that is theoretically sensible, but in practice the actual data is coming up in a much more arbitrary order (perhaps this is a data issue?) . I've no strong views whether we address this front end or back end or both, but the current default order we're actually getting with the production data isn't useful. 

There was some discussion on slack https://zooniverse.slack.com/archives/dev/p1459518622000517 where we basically agreed that for whatever reason current project order isn't coming up in a predictable or useful order (see grant's screenshot).

**Comment by alexbfree** [comment]
@eatyourgreens which sort issues exactly? Do I need to move the sort changes in https://github.com/zooniverse/Panoptes-Front-End/pull/2417 over there?

**Comment by eatyourgreens** [comment]
@alexbfree I'm confused. Isn't #2417 already merged into that branch?

**Comment by camallen** [comment]
my point is the current default sort order is not a code issue and not related to the front end at all (unless to specify the sort order), instead some data wrangling in the api layer.

**Comment by eatyourgreens** [comment]
See my comment above. The default sort order is `-activity` and it's set in `project-card-list.cjsx`. I can change that line on the `project-page-sort` branch. I just need to know what the default sort order should be.

**Comment by eatyourgreens** [comment]
@camallen when you have a moment, could you take a look at https://project-page-sort.pfe-preview.zooniverse.org/projects?env=production Some of the sort options, like 'Most Recently Launched', are returning projects in an unexpected order.

**Comment by camallen** [comment]
@eatyourgreens launch_date won't be set for all those projects. we could set them and it'll work.

**Comment by alexbfree** [comment]
@eatyourgreens Re your "I'm confused" comment. Sorry, you are correct, it is indeed already merged. Just was a bit confused what your new branch might before. But I get it now, have added it to the milestone as well. Thanks for doing those.

**Comment by alexbfree** [comment]
@camallen fixing the launch dates sounds like the way to go. How do we do that?

**Comment by alexbfree** [comment]
@eatyourgreens thanks for the pointer re default sort order. I think we should get @chrislintott to weigh in but I would say that either Most Recently Launched or Most Help Needed would be best. I think Most Popular or Most Active (or Most Recently Updated) are less useful because it just drives more traffic to projects that already have lots/are already active, and may end up having a side effect of hiding new undiscovered projects....

**Comment by mrniaboc** [comment]
After chatting with Cam and Marten earlier today, implementing sensible launch dates in the db should be easy enough. What I need Is to save the timestamp of the first time the launch-approved checkbox is ticked.

For default sort order I'd be tempted to say it should be what we talked about originally, with a list of projects we (or the volunteers) deem worthy of extra promotion, above the fold. E.g. rewarding results, Talk activity, social media promotion, blog posts, or supporting projects that really need the help.

**Comment by alexbfree** [comment]
@mrniaboc just to clarify, which of the above orders do you mean when you say "what we talked about originally"?

**Comment by alexbfree** [comment]
>with a list of projects we (or the volunteers) deem worthy of extra promotion, above the fold
I love this idea! Maybe we could use the same concept we have in Talk boards where "Sticky" threads always appear at the top... We could allow admins to set a "sticky" flag for a project and have the flagged projects appear first (possibly with some sort of "star" marking or coloured flash?). We should do that enhancement separately though, not as part of this ticket

**Comment by alexbfree** [comment]
Just clarified verbally with Grant - he is happy for us to go with Most Recently Launched (but is very keen we soon add promoted projects!)

Given we seem to all agree that's a good order (provided dates fixed at back end, which Cam is taking care of) I think we should just go with Most Recently Launched, unless Chris has a different preference (Even if he does, we can always change it later).

**Comment by chrislintott** [comment]
Fine by me but being able to add stuff to the top of the list is going to be urgent.

**Comment by alexbfree** [comment]
OK @chrislintott thanks I will create a ticket for that.

**Comment by alexbfree** [comment]
Created a PR to change order to launch date. 
https://github.com/zooniverse/Panoptes-Front-End/pull/2439/files

in light of that, removing this ticket from the must-fix list

**Comment by alexbfree** [comment]
OK I have created a feature request for the promoted project feature -> #2440

**Comment by camallen** [comment]
@eatyourgreens FYI - the launch dates have been fixed in the api and the 'Most Recently Launched' sorts are working now.

**Comment by alexbfree** [comment]
OK i think given Cam's comment and the existence of #2440 ticket we can close this one. If anyone disagrees please re-open
