### ISSUE TITLE
Remove pre-populated “Expert Set for Untitled Workflow”?

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#243]
I find this really confusing. As soon as you create a new general workflow, the "expert set for untitled workflow" appears under the subject set. If you rename your only workflow immediately after clicking “New Workflow", the only subject set remains as “expert set for untitled workflow.”  

I believe that we are requiring projects (approved projects?) to have gold-standard data, but at the base level, gold standard data will be randomly sampled from the overall subject set. Also, while I can see use cases for experts uploading entirely separate subject sets for expert review, primarily they will be selected specific images from the existing subject set that they want to add to their queue, so I feel like this pre-populated field is unnecessary.

**Comment by brian-c** [comment]
I agree this is confusing. @edpaget is there a technical reason this has to be the way it is?

**Comment by edpaget** [comment]
I can dig up the issue where we talked about it, but as I understood, we needed all the experts to see the same subset of project subjects, and that was the best way to accomplish it. We can stop it from being automatically created if we don't need it for all workflows, but projects that wanted gold standard stuff would have to choose them later then.

**Comment by brian-c** [comment]
We can just link a subject set as the expert set after the fact, right?

**Comment by edpaget** [comment]
Yeah

**Comment by aliburchard** [comment]
I actually don't think that all experts necessarily need to see the same subject set, though it is helpful if there is overlap, as sometimes experts can be wrong. In Snapshot Serengeti, we engaged ~5 different experts to do 4,300 images; only 100 or so were viewed by multiple experts. @vrooje @kosmala @ggdhines and any other science folks -- thoughts on this?

**Comment by vrooje** [comment]
There are definitely optimists and pessimists within the Galaxy Zoo expert
set - which we know because we had 8 classifiers each classify the same
~900 subjects. That was slightly overkill for that question, though. I
think a subset could be viewed by all, but I wouldn't necessarily count on
experts to do more than 100 classifications apiece on a regular basis.

**Comment by edpaget** [comment]
moved to: https://github.com/zooniverse/Panoptes/issues/805
