### ISSUE TITLE
Filmstrip arrows don't work as expected after using the keyboard to navigate

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#2433]
When you use the keyboard to tab to the last item in the filmstrip the left arrow can't be clicked to move the back to the start.  To get the left arrow to work the right arrow must be clicked.  The activation of these buttons should be tied to the current view of the filmstrip.

**Comment by alexbfree** [comment]
I removed this from the milestone since I don't think it needs to be a blocker for launching the new project page (since there are work arounds, and somebody using a mixture of keyboard and mouse would be unusual)

Good spot though Coleman.. it's a tricky one. Will take a look

**Comment by eatyourgreens** [comment]
Looks like the filmstrip implements its own scrolling behaviour here, storing the scroll position in a state variable which will be 0 until you press the right arrow button.
https://github.com/zooniverse/Panoptes-Front-End/blob/project-page/app/components/filmstrip.cjsx#L46-L59

**Comment by eatyourgreens** [comment]
I find the left/right scroll buttons don't work properly in IE11 either. The solution for these issues is probably to enable horizontal scrolling for all viewport widths, not just widths less than 1024px, wire up the left/right buttons to change `scrollLeft` on the filmstrip element, and get rid of the `state.scrollPos` variable.

**Comment by CKrawczyk** [comment]
I like the idea of enabling horizontal scrolling for all widths, that would make multi-finger swipe with mac trackpads work as well.

**Comment by eatyourgreens** [comment]
:+1: from me after playing around with the filmstrip on a Surface Pro. Downside is that the horizontal scrollbar might appear in Edge.

**Comment by eatyourgreens** [comment]
Here's horizontal scrolling turned on for all viewports:
https://project-page-css-fixes.pfe-preview.zooniverse.org/?env=production

👍  totally fixes this bug by  using `element.scrollLeft` instead of storing the scroll position in component state.
:-1: scrollbars appear whenever the filmstrip scrolls left or right.

**Comment by CKrawczyk** [comment]
Looking good, but something odd is happening with the scroll position when you click on the filters.  Try scrolling to the end and clicking any category, the scroll position tries to "jump" back to the starting position.  This does not happen if the arrows are used to move to the end of the list instead of the scroll bar.

**Comment by eatyourgreens** [comment]
@CKrawczyk should be fixed now.
