### ISSUE TITLE
Ability for Admins to promote certain projects to top of projects page

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2440]
Following discussions on #2424 this enhancement is is clearly an important requirement. @chrislintott and @mrniaboc have both said so.

(It will not be present at first launch of new project page but will be needed soon after)

Here is my first attempt at a spec (feel free to suggest changes!)
- On Admin screen, admins should be able to flag a project as Promoted or not.
- Probably moderators/project owners shouldn't have this right, only Zooniverse staff (it's a property of the homepage, not the project)
- Let's follow the pattern established by Talk - like making threads sticky.
- Any projects that are promoted, should appear at the top of the list, in all sort orders.
- WIthin the "promoted" items, the same sort order should be used as is currently selected.
- A small mark, star or highlight could be added to each promoted item to show why it's at the top of the list (thoughts @jwbmartin?)

Open questions:
-  Should the promoted projects be delineated from the rest by a horizontal rule?
- Should we have a maximum number of promoted projects (one line worth?) or should we support pagination? Should they be paginated as part of the main list (I think so) or separately?
- What support do we need for this at the backend (Thoughts @camallen ?)

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
