### ISSUE TITLE
Suggestion -  Make the new project scroll bar loop back around when you get to edges

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2446]
hey @alexbfree and others  - Space category looks great. Thanks. I was trying out the new project page scroll bar, and have a suggestion. Since you have to scroll through once to see all the options, I had tried to go back around when I hit the edge but hitting the right arrow button again - Maybe it would be helpful/useful if the film strip is a continuous loop so when you get to the edge you can go back the beginning rather than have to scroll all the way left again to reach the beginning

**Comment by alexbfree** [comment]
That is a good point, having "ends" is not particularly useful. Not sure how easy it would be to implement though. Maybe @amyrebecca or @eatyourgreens have some thoughts.

**Comment by mschwamb** [comment]
Also not sure if you want other feedback @alexbfree . In case this is helpful:  I'm finding the different colors applied when you select a category lit bit confusing/strange given the flow of the rest of the Zooniverse site since there's already a difference in fill and outline between hovering and non-hovering and selected and non-selected. I personally find the yellow/gold on white for History and Literature a little bit hard on the eyes when hovering. Looks great, beyond those minor things I noticed.

**Comment by alexbfree** [comment]
Thanks @mschwamb . What would make it less confusing? We came up with that solution because we need to allow people to change focus with their keyboard (tab) for accessibility reasons, but we also need to show the current filter in effect. So we do have two different states to represent.

Sharing this with our designer @jwbmartin for consideration in future design updates.

**Comment by mschwamb** [comment]
Mainly I wouldn't do a different color for each subject. I'd have them all have the same color/design change on select versus hover versus non-selected/not-hovered. When you hover you get an outline (and could go a shade darker) and the solid fill when selected. I don't get the color change. So for example, apply all behavior for the medicine box to all of the subjects.

**Comment by alexbfree** [comment]
OK. I think the colours have been pretty popular with most people we've shown it to, but i definitely see your point on the hover of yellow/white and gold/white. We will think about what to do about that!

**Comment by mschwamb** [comment]
Definitely a personal taste thing. Changing the yellow/gold to something else would be great if it's doable.

**Comment by alexbfree** [comment]
Adding a link to #2373 for ease of finding related discussion

**Comment by alexbfree** [comment]
>if it's doable
Definitely do-able, the challenge is whether to fix just those two colours (if that can be done without them jarring with the rest) or whether to rethink the design. It's a design challenge rather than a technical one. Will ponder!

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
