### ISSUE TITLE
Manifest file example in Project Builder Guide  has talk hashtag code in it 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2447]
In the [how to guide ](https://www.zooniverse.org/lab-how-to) the hashtag for the hidden private metadata is being converted/shown as a talk url 

<img width="1033" alt="screen shot 2016-04-15 at 10 17 54 am" src="https://cloud.githubusercontent.com/assets/753325/14549586/8ff84cde-02f3-11e6-8970-296f53e94a5a.png">

Maybe to get around it, the file could be stored somewhere and a new project owner could download the example. This might be one for @aliburchard or @mrniaboc

**Comment by alexbfree** [comment]
possibly related to #2260?

**Comment by mschwamb** [comment]
That ticket looks to be live and working I had tried earlier this morning to write a url out with a hashtag and the Talk preview saw it as a url hyperlink, but this wasn't fixed so maybe it's an interplay between the code markdown?

**Comment by mschwamb** [comment]
This is now fixed so I'm closing it
