### ISSUE TITLE
Relationship between "task" bit on left and task editor on right is unclear

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#245]
It's not really clear that all of the tools on the right fall under the "task" section on the left hand side.  Perhaps this could be solved with some different colors for Workflow/Task/Subject sections, or some sort of background colour-blocking that clarifies this stuff on the right falls under the "task" section on the left.

**Comment by brian-c** [comment]
Yep, design here could use improvement.
