### ISSUE TITLE
Collections, Add to collection, List limit ?

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#2454]
Simple question. As I seem to be missing some entries in the "Add to Collection" drop-down list, that I think should be there.

Is there some limit to the number of collection entries that are shown in the "Add to Collection" drop-down list ?

---

-- Seem there is a limit of 20.
-- some FIFO seem to be in play.

Guess I answered my own question.
Presuming its intentional.
Ditching ticket.

**Comment by camallen** [comment]
For reference, the collections drop down is paged by default (20) and will update with new data on the search box text input change (i.e. type into the collection name drop down box). Also there is a default sort order on the non-filtered response too (what you're interpreting as FIFO).

**Comment by MvGulik** [comment]
(*Aha, thanks.*)
