### ISSUE TITLE
sort collections by alphabetical order on user collections profile page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2455]
Otherwise I think if the list gets more than a page you have to search all the pages to find and view your collection. Currently it's not in alphabetical order and I'm not sure what order it is in. 

<img width="1091" alt="screen shot 2016-04-16 at 3 15 32 pm" src="https://cloud.githubusercontent.com/assets/753325/14579711/4332f66c-03e6-11e6-9b64-2e72bf900fc7.png">

**Comment by mschwamb** [comment]
@camallen should this be a backend issue?

**Comment by camallen** [comment]
@mschwamb once that PR is merged / deployed then the front end should just add a sort param to fix this.

**Comment by mschwamb** [comment]
Thanks @camallen. I presume a similar thing for https://github.com/zooniverse/Panoptes/issues/2077 ?

**Comment by camallen** [comment]
@mschwamb once the backend supports these sort orders the front end will need the relevant query params on them.

**Comment by mschwamb** [comment]
The backend now supports this. Could someone add the sorting feature ? Thanks
