### ISSUE TITLE
Collections, User collection's-page, Page-navigation, Wrong URL.

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#2456]
On the pages showing all the collections of a particular user. The page-navigation links for that user collection are missing the user-name part.

Ergo:
Instead of using: "```https://www.zooniverse.org/collections/<username>?page=N```"
Its using: "```https://www.zooniverse.org/collections?page=N```"

_\*Unsubscribed\*_

**Comment by camallen** [comment]
@alexbfree will your collections PR fix this?

**Comment by alexbfree** [comment]
Yes it should. Linking it for testing #2670 .

**Comment by MvGulik** [comment]
Seems fixed. cq: Back to working as expected.

Presuming ok to close.
Closing.
