### ISSUE TITLE
Adding in a slideshow view for collection images

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2457]
I'm working on identifying the target regions we're going to request be imaging with the high resolution camera, and since there's a good number of subject images I wanted to share with the rest of the Planet Four: Terrains team I'm making a collection. But the team stills need to go click on each thumbnail to see a larger version, which is repetitive, and necessary because the team will want to see the full resolution image rather than the thumbnail. It would be nice if there was a slideshow view where it you could show the larger image and keep advancing to see the next image in the collection with a link below if you want to go to the Talk subject page of the subject image.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
