### ISSUE TITLE
Adding ablity for team members to create collections by uploading a csv of subject ids

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2459]
I'm currently having to manually create a collection of 145 subjects so I can share with the Planet Four: Terrains team. it would be nice eventually in the future to be able to create collections for review, examples, etc by being able to upload from the project builder a list of subjects.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.

**Comment by mschwamb** [comment]
I haven't commented because collections weren't being worked on. I still think this is useful.

**Comment by srallen** [comment]
@mschwamb this can be done programmatically using the python client.

For the UI, we're planning on an implementation that won't involve CSV upload but use preexisting subject sets and/or collections.
