### ISSUE TITLE
Editing a typo in a hashtag in my post gives me PG::UniqueViolation Error

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2462]
I was editing a typo in a hashtag in my post in Western Shield Talk. It gives me such an error:

![screenshot](https://lh3.googleusercontent.com/-3cNZ1nJOkmA/VxNxC9teRDI/AAAAAAAAI0o/iHb47oEpel0xzd401u0zSL1V-mCh3OergCCo/s912-Ic42/ysh_2016-04-17_13-03-37.jpg)

So I removed the hashtag completely and then it worked. But I guess I am not supposed to get it.

**Comment by parrish** [comment]
This will be deployed in an hour or so
