### ISSUE TITLE
Talk hashtag search results show same subjects on two different pages in the search results

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2463]
Page 9 and 10 have same subject Subject 488303 on both pages in Firefox on Mac.  

https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders?page=9
https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders?page=10

<img width="1280" alt="screen shot 2016-04-19 at 1 10 28 am" src="https://cloud.githubusercontent.com/assets/753325/14612774/8ea008c4-05cb-11e6-91ad-b1e8f348dab7.png">

Full screen shots of each page results are below (but long to scroll through)

![fireshot capture 15 - planet four_ t__ - https___www zooniverse org_project](https://cloud.githubusercontent.com/assets/753325/14612785/a5b5820a-05cb-11e6-9ec9-d74a4b8b8291.png)
![fireshot capture 16 - planet four_ t__ - https___www zooniverse org_project](https://cloud.githubusercontent.com/assets/753325/14612787/a739dc0c-05cb-11e6-971e-3be3702f0034.png)

**Comment by mschwamb** [comment]
That subject is also showing on page 11 of the search too.

**Comment by mschwamb** [comment]
@parrish is this a bug in the API? I thought it was in the display on the front end

**Comment by parrish** [comment]
Yeah, it was a bug in the way the results were ordered in the api.

Results with the same popularity ranking where being returned in a random order.  zooniverse/talk-api@6a79aed will give them a predictable order when the ranks are tied, which will fix pagination.
