### ISSUE TITLE
Ability to do multiple tag searches in Talk

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2465]
The preview display of subjects in the tag search is really handy. I've been perusing it to look for additional candidates for targeting with the high resolution Mars Reconnaissance Orbiter camera. I found I've also wanted to look at images that have been tagged with two tags. It would be nice if the api and the front end had that feature so that one could scroll through the previews of the subjects.

**Comment by camallen** [comment]
@mschwamb you should be able to via a URL `https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders,crater` but agree the UI could allow this multiple selection.

**Comment by mschwamb** [comment]
@camallen It looks like it's doing an  or on the  logic instead of an and

**Comment by camallen** [comment]
Right my mistake on the and request, i don't think the talk api supports this currently.

**Comment by parrish** [comment]
Yep.  We've chosen to not complicate things with boolean logic around tags at all.
