### ISSUE TITLE
If you are perusing a talk search tag list and not on page 1 and then click on side tag list - the returned page says its on not 1

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2466]
I'm finding if I'm page 5 say of the tag search for spiders 

https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders and get to page 5

https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders?page=5 and then decide I want to go to one of the other hashtags on the side bar (say channels)

If you click channels on the right side you get the url https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/channels but if you look at the bottom it says you're on page 5

I think it is loading not a page 1 because if I go to page 41 of spiders  (https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders?page=41) and then go to baby spiders and the site says 'No tags found.' when there are tags, but there are (but only 34 pages)

<img width="1104" alt="screen shot 2016-04-19 at 11 38 58 am" src="https://cloud.githubusercontent.com/assets/753325/14627077/7f095926-0623-11e6-9f01-e8f13aae4ba6.png">

**Comment by mschwamb** [comment]
This was using Firefox 45.0.2 on Mac

**Comment by mschwamb** [comment]
I hit this again today - it makes but when clicking on a different tag link on the subject listed in the search return -  @parrish is this the right place to post this?

**Comment by parrish** [comment]
Fix is ready to go.

Sorry I didn't see this earlier.  Mentioning or assigning to me is a good way to catch my attention.

**Comment by mschwamb** [comment]
Many Thanks
