### ISSUE TITLE
Enable "new workflow" button and make workflow editor disabled only for active workflows

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2468]
Related to #274, but wtih more clarity. Basically, if a new workflow is added on a Launch=True project, it is inactive by default. Only Zooniverse admins can "activate" the workflow via the admin panel, so we have a review process built in.

By only disabling the workflow editor for *active* workflows on a live project, folks could build new workflows on existing projects more easily. Since the review process is implicit in the workflow activation, it's also minimal risk.

**Comment by srallen** [comment]
@aliburchard project owners can now manage workflow visibility in the project visibility tab and only active workflows are disabled from editing. Can this issue close or is there more to address?

**Comment by aliburchard** [comment]
think that covers it!
