### ISSUE TITLE
Field Guide obscuring projects on mobile

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2469]
The field guide appears automatically upon going to the landing site, and you can't close it out even as you try to navigate within the project. It obscures the classification interface, landing page, talk...everything. This is on iphone 5.

![img_1062](https://cloud.githubusercontent.com/assets/6217406/14643669/320032a2-0647-11e6-8566-ff340f57355d.PNG)

**Comment by aliburchard** [comment]
Hey @brian-c just wondering if you had any thoughts on how easy a fix this is? It's an issue for all projects with a field guide on mobile devices. I also know western shield has plans to do a press push soon, but I think they should wait until this is fixed.

**Comment by brian-c** [comment]
Shouldn't be hard at all. I'm fixing some bugs today, should be able to get to this real soon.

**Comment by brian-c** [comment]
Fixed in the react-pullout lib, will come out in next deploy.

**Comment by aliburchard** [comment]
yay! thanks :)
