### ISSUE TITLE
Associating subject set with workflow not working

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#247]
I've uploaded a partial subject set, but associating my workflow with the subject set doesn't seem to be working.

When I try to tick the subject set's checkbox in the workflow editor, it doesn't actually check, but the Save button becomes clickable. If I click it, I get:
param is missing or the value is empty: workflows

and the console says:
Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.     vendor.df77d795af1f41f945667cc44fef7875.js:14 
panoptes-staging.zooniverse.org/api/workflows/945:1 PUT https://panoptes-staging.zooniverse.org/api/workflows/945 422 (Unprocessable Entity)

**Comment by brian-c** [comment]
This is going to be screwed up until zooniverse/Panoptes#764 is fixed, will investigate then.

**Comment by edpaget** [comment]
I'll fix this shortly then.

**Comment by vrooje** [comment]
This is still weird - I can change which subject sets are associated with a workflow but for existing users it doesn't update (for new users it does).

**Comment by chrissnyder** [comment]
Likely outdated.
