### ISSUE TITLE
Display of choices wonky on mobile for survey tasks

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2471]
any row where a column got two lines now has black spaces above and below the one-line columns. presumably, the cell with the "choice" inside should expand for all columns in those rows.

![img_1063](https://cloud.githubusercontent.com/assets/6217406/14644070/a8cf92aa-0648-11e6-828f-6bb2a7bfad59.PNG)

**Comment by aliburchard** [comment]
@brian-c any chance of fixing this? Instead of black spaces, the buttons for each column in the row should expand.

**Comment by brian-c** [comment]
I've got a fix in mind, just need to make sure it doesn't break anything else.

Should have more later today.

**Comment by aliburchard** [comment]
Awesome, thanks!
