### ISSUE TITLE
We need Live, Paused, and Finished sections on the projects page

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#2475]
On the new projects page, hiving things like Pulsar Hunters appear at the top of the 'most help needed' results makes no sense

![image](https://cloud.githubusercontent.com/assets/5321335/14675850/d13c11ae-0702-11e6-97f8-5abb18d79349.png)

It's time we created sections for paused and finished projects. @marten did you have any luck implementing those tags in the backend?

@alexbfree @amyrebecca any thoughts on how quickly this could be implemented?

**Comment by alexbfree** [comment]
Let's consider what the design should be... 
We need to decide whether we are:

1. adding a secondary filter, perhaps a dropdown, which combines with the current discipline filter & sort order to only show All - Live - Paused - Finished projects
2. modifying the way in which the project cards appear, based on their live/paused/finished status, but still showing them in the list
3. modifying the ordering of the list / creating grouping within it, such that each page of results shows a Live section, a Paused section, and a Finished section (with the related consideration - how will pagination work here)
4. Creating some meta level tabs around the project page such that you first choose whether to look at Live, Paused or Finished projects before doing any filtering/searching/browsing
5. some other option?

From an API perspective we probably need the backend to:

1. support an additional query parameter "state" (or whatever we call it) on projects queries
1. return the project state along with each project's data in queries

From a data perspective we need to ensure the state is set correctly on every project. And we might need to add some "holding" projects for some archived projects that don't currently show up.

**Comment by alexbfree** [comment]
BTW @marten maybe could you also investigate why Pulsar Hunters has a completeness closer to zero? I would have expected 100% or maybe 90% based on our recent discussion of completeness and how it is calculated...

**Comment by alexbfree** [comment]
Some possibly related Panoptes API tickets:
https://github.com/zooniverse/Panoptes/issues/1403
https://github.com/zooniverse/Panoptes/issues/1558

**Comment by parrish** [comment]
Closed by zooniverse/panoptes#1791

**Comment by alexbfree** [comment]
Closing this ticket seems premature - even if the API now supports it, we'll need to implement this in the UI.

**Comment by alexbfree** [comment]
@jwbmartin do you have design ideas for how this could be implemented?

**Comment by srallen** [comment]
@simensta and I worked a bit on the UI part of this during the April miniZTM. We haven't had time to get back to it, yet.

**Comment by srallen** [comment]
Done in #3085
