### ISSUE TITLE
Project search on Zooniverse home projects page returns back includes projects not on the approved Zooniverse project list

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2476]
I'm not sure if this is intended as a feature or not. When you type in the search box on the projects page it returns back back included in the list those that are public but not Zooniverse approved in additional ton the Zooniverse approved projects that show on the projects page.

![fireshot capture 17 - projects zooniverse - https___www zooniverse org_projects](https://cloud.githubusercontent.com/assets/753325/14677648/f3d27234-0744-11e6-81fd-98f6d7eb3e71.png)

**Comment by srallen** [comment]
@mschwamb thanks for catching this. Fixed in #2478
