### ISSUE TITLE
Not receiving notifications due to Error: couldn't find project with id=592

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2479]
I have checked my Project email preferences settings to figure out why I'm not receiving any notifications connected to Western Shield - Camera Watch project (no notifications when I receive a personal message nor when someone replies to my Talk comment). It says there's an error: Couldn't find project with id=592. Could you look at it please?

It would be nice if the red mark on the envelope displayed even without reloading the page. When switching between the classification and the Talk the top bar doesn't get reloaded so when someone sent me  a PM the mark doesn't appear unless I open the project in a new browser tab or reload the page manually. It is time consuming when waiting for a reply.

![](https://lh3.googleusercontent.com/-My9NgJD6WLc/VxfsG4twaDI/AAAAAAAAI1Y/fFPUhfHLMlUzC9nm7zWw-Bq4Nd6KQVhbwCCo/s912-Ic42/ysh_2016-04-20_22-45-55.jpg)

**Comment by mschwamb** [comment]
I think I'm having a similar issue. I didn't get a message for a private message sent and I also have a project that says  'error could not find project with='

**Comment by alexbfree** [comment]
I have a similar error in my email prefs:
`Error: Could not find project with id='1332'`

Not sure if I am missing notifications or not: 
![screenshot 2016-04-25 17 09 37](https://cloud.githubusercontent.com/assets/1473244/14790285/84a5f8b4-0b08-11e6-9a50-f6a43c451f11.png)

**Comment by alexbfree** [comment]
My guess is that projects are being deleted but their corresponding email prefs are orphaned and left hanging around.

**Comment by mschwamb** [comment]
Also stuff's not popping up in my notifications page in Talk. 
example [this new comment](https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/211/44624?comment=102189) is in the same thread as a [previous post](https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/211/44624?comment=101729)  that shows up in my notifications page, but not this new comment doesn't at all now. 

<img width="1119" alt="screen shot 2016-04-27 at 12 19 24 pm" src="https://cloud.githubusercontent.com/assets/753325/14841692/f9e36326-0c72-11e6-9ddc-fb6521a22ed0.png">


<img width="1058" alt="screen shot 2016-04-27 at 12 24 31 pm" src="https://cloud.githubusercontent.com/assets/753325/14841698/0f3009f0-0c73-11e6-96a9-2b831df60c0b.png">

**Comment by camallen** [comment]
This won't be due to the missing project preference (most likely a public now private project). More likely a talk notifications issue, pinging @parrish

**Comment by parrish** [comment]
@camallen It looks like that sidekiq upgrade is pretty botched.  I'll be rolling back to fix this.

**Comment by parrish** [comment]
https://app.honeybadger.io/projects/43180/faults/29542148 for reference.

**Comment by camallen** [comment]
thanks for the update @parrish - perhaps related to hard limits on the redis pool? https://github.com/zooniverse/Talk-Api/blob/master/config/initializers/sidekiq.rb#L10

**Comment by parrish** [comment]
Possibly, but that would mean it's not releasing connections properly.  Either way, the surest fix is to rollback and look for a maintained alternative to Sidetiq I think.

**Comment by camallen** [comment]
let us know if you find something decent. I've had a quick look but didn't find anything quite like the API of sidetiq.

**Comment by camallen** [comment]
also just in case https://github.com/mperham/sidekiq/blob/master/4.0-Upgrade.md

> Jobs are now fetched from Redis in parallel, making Sidekiq more resilient to high network latency. This means that Sidekiq requires more Redis connections per process. You must have a minimum of concurrency + 2 connections in your pool or Sidekiq will exit. When in doubt, let Sidekiq size the connection pool for you.

**Comment by parrish** [comment]
Good call.  Turns out the connection pool size wasn't allowing for the extra internal connections: https://github.com/zooniverse/Talk-Api/commit/de16f9bbd552a632c67da8d5b7d62e5071e2c0c4#diff-fd9e64e4a154ab77edea808fa4285141R8

**Comment by parrish** [comment]
It should be fixed now.
