### ISSUE TITLE
Request: a citable / DOIable version of the project

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2480]
It would be super awesome if there was an automated way to take the elements that make up a Panoptes project -- all the meta content, the workflows, etc. (but maybe not the subjects themselves) --and form some sort of text repository that could be archived (on GitHub or FigShare or wherever) and receive its own DOI. 

I am working on an NSF annual review and Season Spotter is definitely a _product_ that I can report, but it's not easy to cite. When I write up a paper, I'd also like to be able to point the project so that others could reproduce the project if necessary. 

The current interface allows me to dump workflows and workflow contents, but not in a way that is easy to human-read and that isn't (as far as I know) easily importable to create a new project. And there is no easy way to dump all my meta content. (The FAQ, Research page, etc.) 

The implementation would likely be related to backing up and duplicating projects (#1273 and #931). It looks like functionality is there on the back-end (https://github.com/zooniverse/Panoptes/issues/887 and https://github.com/zooniverse/Panoptes/pull/913). Just need a nice way to do it on the front-end.

**Comment by camallen** [comment]
@mkosmala not sure we can create a DOI link to a working site. As you point out we could create an export of the api data (in JSON) that could be linked to / DOI'd and you right there is not a good way to visualise / render this data dump though in a browser.

You could look at creating an offline archive of the site using wget or a similar copy tool to create this though.

**Comment by mkosmala** [comment]
I just brought it up because the trend in academia right now is to have all materials and data be archived and with a DOI pointer. So my guess is that as time goes on, more independent Panoptes project creators are going to want to be able to point to their archived project when publishing. For Snapshot Serengeti, for example, I archived a snapshot of the code and created a DOI for it: http://dx.doi.org/10.6084/m9.figshare.1397518

With Panoptes projects, there isn't a similar code base. So it would be nice to have a way to export all the text and logic in one fell swoop and stick a DOI on it.

**Comment by camallen** [comment]
For sure. Agree it'd be nice to have but pretty low on priorities.

Linking in this api issue, https://github.com/zooniverse/Panoptes/issues/1523. If we can create a URL that loads a particular workflow / content version of a site then this would probably suffice for a reproducible DOI.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
