### ISSUE TITLE
hide-previous-marks breaks if you use "back" to visit a previous task

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2482]
I made a 2-task workflow with T1 = question, and T2 = marking. I enabled hide-previous-marks for the marking task. In testing the workflow I noticed that if I drew some marks during T2, hid them, then went back to T1, then after I returned to T2 the checkbox for hide-previous-marks was still checked, but it was also greyed out, and the marker count was missing. If I make more marks the box becomes clickable, but then showing/hiding marks never uncovers the previous marks. This was true whether I changed my answer to T1 or not, and it was true whether I enabled hide-previous-marks for T1 or not.

I think that if I go Back to a previous task and change an answer, my markings on the Next task will be erased, right? But if I don't change my answer, they won't? In which case I think the hidden marks should be preserved and shown when I go forward again.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
