### ISSUE TITLE
Settings, Email, Project email preferences, no projects message.

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#2483]
At the user Settings page (email tab),
the displayed message at the "*Project email preferences*" part,
when there are no associated projects yet,
could, eventually, use a nicer user-friendly message.

![image](https://cloud.githubusercontent.com/assets/666868/14762201/f2cfd386-0974-11e6-88a0-326ca961c205.png)

Local stuff: Chrome, Desktop, Windows, 1024x768.

_\*Unsubscribed\*_

**Comment by wgranger** [comment]
@trouille
