### ISSUE TITLE
Not receiving email notifications for Talk

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#2485]
Haven't changed my settings, double checked and have still got 'Send me an email when...' categories all set to immediately. Last notification in my inbox came April 12th.

**Comment by yshish** [comment]
Similar to this one? https://github.com/zooniverse/Panoptes-Front-End/issues/2479

**Comment by mschwamb** [comment]
I commented in #2479 but I'll do it here as well. I had a similar issue a few days ago. I got a private message, but not notification email as was set up in my preferences

**Comment by camallen** [comment]
pinging @parrish

**Comment by parrish** [comment]
Duplicates #2479
