### ISSUE TITLE
Long Project names being cut off on projects page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2487]
Planetary Response Network and Rescue Global Ecuador Earthquake 2016 is being cut off on the projects page project card

<img width="1140" alt="screen shot 2016-04-26 at 1 11 22 am" src="https://cloud.githubusercontent.com/assets/753325/14792421/ae7ac3ec-0b4c-11e6-8aa1-c699c01a80f2.png">

**Comment by jwbmartin** [comment]
I think we need to start limiting the length of names, honestly. Maybe are just getting to be ridiculously long.

**Comment by parrish** [comment]
Yeah.  I'm going to close this in favor of sensible naming.
