### ISSUE TITLE
Unable to comment subjects/create discussions on Western Shield Camera Watch

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2490]
Getting various errors when trying to comment a subject/create a discussion.

 1. At first it didn't load the text field area for typing a comment at all. Screenshot:
![](https://lh3.googleusercontent.com/-1Hklo5s-irE/Vx5kB1_pb9I/AAAAAAAAI2I/578mBiVa-z8-ykPPhvz2Cpcd-GQezvV2gCCo/s0/ysh_2016-04-25_20-06-49.png)

 2. Then it loaded the text field area but after clicking on the *Add your comment* button it showed *"Cannot read property 'error' of null"*. Screenshot:
![](https://lh3.googleusercontent.com/-RNjeM8TTx9g/Vx5kB0YkIWI/AAAAAAAAI2M/Io_EbxyRytkkB_aMFsLRWUMwzAWJ7KtXwCCo/s0/ysh_2016-04-25_20-08-00.png)

 3. After clicking on the *Add your comment* button again, the error message changed to *"not allowed to create this Discussion"*. Screenshot:
![](https://lh3.googleusercontent.com/-NmPKCggydWM/Vx5kBx-2fxI/AAAAAAAAI2Q/YamFKaOmv5UORd5fTlqd5kuuqPzOPXDDgCCo/s0/ysh_2016-04-25_20-08-20.png)

 4. After reloading the page I got to the step 1 = the text field area didn't load at all. Screenshot:
![](https://lh3.googleusercontent.com/-f5nngDAKWBM/Vx5kCK7CDOI/AAAAAAAAI2U/4h1IGCqQOqon5Aq17MVMGQXldiRLb3OmwCCo/s0/ysh_2016-04-25_20-08-48.png)

**Comment by parrish** [comment]
I'm pretty sure we resolved this with zooniverse/panoptes-javascript-client#45.  Happy to revisit if this comes up again.
