### ISSUE TITLE
It seems that my classifications aren't being recorded (param is missing)

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2491]
I noticed some seriously looking errors after finishing a classifications on Western Shield Camera Watch
Screenshot:
![](https://lh3.googleusercontent.com/-HwqEZwGr6EE/Vx5l-Nc1xPI/AAAAAAAAI2s/w_lGIKIJo089tOxdxRajhXTURaOrsI7mgCCo/s0/ysh_2016-04-25_20-44-32.png)

Does it mean that my classifications aren't being recorded? (But the counter is counting..)

**Comment by camallen** [comment]
@yshish that does not look good, i can't reproduce on my end. Is this still happening?

**Comment by yshish** [comment]
Yes, it is still happening. But the classification counter hasn't stopped counting. 

Working on Chromium Version 45.0.2454.101 Ubuntu 15.04 (64-bit).

**Comment by eatyourgreens** [comment]
@camallen I've seen this before, but can't remember where. Classifications that failed to post correctly get saved locally and posted again with incomplete metadata. Related to https://github.com/zooniverse/panoptes-javascript-client/issues/25 (the api client doesn't pass back the 422 status code.)

**Comment by camallen** [comment]
@yshish try incongnito mode / another browser to see if it's still an issue. Not sure how some broken classifications got built and stored to localstorage...do they ever expire?

**Comment by eatyourgreens** [comment]
@camallen I _think_ those failed classifications will try to resend forever. I don't see anything in the javascript to expire them. https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L287-L303

**Comment by yshish** [comment]
I tried Firefox and got some error which looks different to me (just can't tell whether it is related to it or not).
![](https://lh3.googleusercontent.com/-7cycBf6iUxA/Vx_Q24wsvHI/AAAAAAAAI3E/lbeNCZjKoTUKdL3g8v6wyuiZ77yUzcw4ACCo/s0/Screenshot_2016-04-26_22-26-46.png)

I tried incognito mode in Chromium and got some errors which look different too.
![](https://lh3.googleusercontent.com/-NcjNU4bOk7I/Vx_RvlCT5iI/AAAAAAAAI3Y/d1yi7OxHakg7Vm_dqZqcj8zph2BCGho5wCCo/s0/ysh_2016-04-26_22-33-05.png)

I'm sorry if it isn't helpful. Can you tell?

**Comment by yshish** [comment]
Ej, I switched the links for the browsers in my previous post! 0:]

**Comment by eatyourgreens** [comment]
Thanks @yshish that's helpful. It looks like you have also come across #2158 which is a different error, but one that doesn't affect saving your classifications.

**Comment by camallen** [comment]
it looks like those classifications are being submitted just fine. Seems that at some point there were broken classifications that are now stuck trying to resubmit. Any thoughts on this @brian-c @eatyourgreens ?

@yshish you can clear them out of local storage but could keep them around for the moment? They may be useful for debugging.

**Comment by yshish** [comment]
@camallen Not sure what you're asking for. Please, could you give me steps for dummies?

**Comment by brian-c** [comment]
@yshish: `copy(JSON.stringify(JSON.parse(localStorage.getItem('failed-classifications')), null, 2))` will copy the failed classifications to the clipboard. I have a feeling these are malformed classifications from when the queue feature was still in development. If you paste the result here, I'll see if I can cook something up to fix them all, and then they'll save as normal next time you classify.

**Comment by eatyourgreens** [comment]
@brian-c @camallen I think this line is the problem:
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L270

The case I'm thinking of is the situation we had yesterday, where network requests are slow. Could `@state.classification` change before the response comes back, in which case the queued classification will be a new, unfinished classification, not the classification that was POSTed to Panoptes.

**Comment by yshish** [comment]
@brian-c  Is this what you wanted??

[
  null,
  {
    "annotations": [
      {
        "value": null,
        "task": "init"
      }
    ],
    "metadata": {
      "workflow_version": "6.20",
      "started_at": "2015-12-26T16:26:41.067Z",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36",
      "user_language": "en",
      "utc_offset": "-3600",
      "subject_dimensions": [
        {
          "naturalWidth": 960,
          "naturalHeight": 640,
          "clientWidth": 820,
          "clientHeight": 547
        }
      ]
    },
    "links": {
      "project": "14",
      "workflow": "427",
      "subjects": [
        "1312407"
      ]
    }
  },
  {
    "annotations": [
      {
        "value": null,
        "task": "init"
      }
    ],
    "metadata": {
      "workflow_version": "6.20",
      "started_at": "2015-12-26T16:27:11.351Z",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36",
      "user_language": "en",
      "utc_offset": "-3600",
      "subject_dimensions": [
        {
          "naturalWidth": 960,
          "naturalHeight": 640,
          "clientWidth": 820,
          "clientHeight": 547
        }
      ]
    },
    "links": {
      "project": "14",
      "workflow": "427",
      "subjects": [
        "1307222"
      ]
    }
  },
  {
    "annotations": [
      {
        "value": 0,
        "task": "init"
      }
    ],
    "metadata": {
      "workflow_version": "6.20",
      "started_at": "2015-12-26T16:27:52.761Z",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36",
      "user_language": "en",
      "utc_offset": "-3600",
      "subject_dimensions": [
        {
          "naturalWidth": 960,
          "naturalHeight": 640,
          "clientWidth": 820,
          "clientHeight": 547
        }
      ]
    },
    "links": {
      "project": "14",
      "workflow": "427",
      "subjects": [
        "1310363"
      ]
    }
  },
  {
    "annotations": [
      {
        "value": null,
        "task": "init"
      }
    ],
    "metadata": {
      "workflow_version": "6.20",
      "started_at": "2015-12-26T16:27:59.963Z",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36",
      "user_language": "en",
      "utc_offset": "-3600",
      "subject_dimensions": [
        {
          "naturalWidth": 960,
          "naturalHeight": 640,
          "clientWidth": 820,
          "clientHeight": 547
        }
      ]
    },
    "links": {
      "project": "14",
      "workflow": "427",
      "subjects": [
        "1312893"
      ]
    }
  },
  {
    "annotations": [
      {
        "value": null,
        "task": "init"
      }
    ],
    "metadata": {
      "workflow_version": "6.20",
      "started_at": "2015-12-26T16:28:08.490Z",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36",
      "user_language": "en",
      "utc_offset": "-3600",
      "subject_dimensions": [
        {
          "naturalWidth": 960,
          "naturalHeight": 640,
          "clientWidth": 820,
          "clientHeight": 547
        }
      ]
    },
    "links": {
      "project": "14",
      "workflow": "427",
      "subjects": [
        "1313269"
      ]
    }
  },
  {
    "annotations": [
      {
        "value": null,
        "task": "init"
      }
    ],
    "metadata": {
      "workflow_version": "6.20",
      "started_at": "2015-12-26T16:28:12.525Z",
      "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36",
      "user_language": "en",
      "utc_offset": "-3600",
      "subject_dimensions": [
        {
          "naturalWidth": 960,
          "naturalHeight": 640,
          "clientWidth": 820,
          "clientHeight": 547
        }
      ]
    },
    "links": {
      "project": "14",
      "workflow": "427",
      "subjects": [
        "1310490"
      ]
    }
  },
  null,
  null
]

**Comment by brian-c** [comment]
@yshish Perfect, thanks. Unfortunately it looks like @eatyourgreens's hypothesis is probably correct, and we've lost six of your classifications for Snapshots at Sea. Truly sorry for that. I'll have a fix up for this bug in just a minute.

**Comment by chrislintott** [comment]
Do we have estimates for whether this is a widespread problem? Ie could many classifications be lost? It sounds like it’s only where network connections are very slow.

**Comment by brian-c** [comment]
This was probably very rare, occurring in the case that the classification save call failed following a long delay (busy server) after the server already provided a new subject to classify (responsive server).
