### ISSUE TITLE
camera survey details window opens up too big for screen

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2501]
<img width="1258" alt="screen shot 2016-04-27 at 10 03 08" src="https://cloud.githubusercontent.com/assets/6217406/14847214/5515ac68-0c5f-11e6-95ab-82f8afefd5bd.png">

requiring volunteers to scroll down to submit their classification. Is there any way to shrink that to force the popup to fit on at least laptop/tablet screens? maybe forcing a max height on the reference photo? 

It's occasionally an issue on other projects, but I also realize that the descriptions on western shield are really long, so maybe it's simply a matter of asking them to reduce their reference text.

**Comment by srallen** [comment]
@aliburchard We can take a look at possibly limiting the height, but since this is a user submitted field, we can't absolutely guarantee this won't happen. We should also probably have a recommend length in the editor too.

**Comment by aliburchard** [comment]
+1 to a recommended length. It's probably harder in the editor since this is actually submitted via csv, but we can suggest a length in the help text, at the very least.

@mcbouslog - can we add "adding a suggested word count" to the list of survey task improvements? (we just need to figure out what it is.)

**Comment by mcbouslog** [comment]
absolutely! #2686

**Comment by jwbmartin** [comment]
Working on creating new template ideas for Project Builder projects so a lot of this will change so I'll be closing a lot of issues about this.
