### ISSUE TITLE
'Required' not enforced for "details" questions

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#251]
It would be nice to be able to require an answer in the "details" pop-ups.

**Comment by aliburchard** [comment]
Similarly, with the drawing tasks, there's no "require" option. Is that intentional? (And if so, why can we "require" a question but not a drawing task?)

**Comment by simoneduca** [comment]
I think the refactor mostly takes care of this. Will create a new issue, should the need arise.
