### ISSUE TITLE
Allow project owner to specify what order the work flow buttons for mutiple workflows show on the landing page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2510]
Currently if you have multiple workflows the buttons on the landing page are determined by the order of creation, but there may be a time where one wants to promote one over the other and switch the order. Currently there is no way to do that. The order the workflows show on the landing page should be customizable . Like for Comet Hunters well want to prioritize the Hype Suprime-Cam data, so it would be nice if I can put the HSC workflow button above the current workflow on Comet Hunters when we finally add in our second workflow

<img width="1196" alt="screen shot 2016-04-29 at 10 02 16 pm" src="https://cloud.githubusercontent.com/assets/753325/14918510/e3c26fe8-0e56-11e6-99aa-fda0b7e9dbf5.png">

Order is in creation order 
<img width="216" alt="screen shot 2016-04-29 at 10 07 15 pm" src="https://cloud.githubusercontent.com/assets/753325/14918520/f0a246de-0e56-11e6-89a9-67348983e256.png">

**Comment by camallen** [comment]
@brian-c, something we could add to the project configuration json object?

**Comment by aliburchard** [comment]
+1!

**Comment by mschwamb** [comment]
@camallen even having this as something that could be set in the backend at the moment would be helpful for me even if I can't set it in the project builder myself.

**Comment by camallen** [comment]
@mschwamb we could add it in but the front end would need to respect it and wire up the interface accordingly.

**Comment by mschwamb** [comment]
can the default workflow option that now exists in the project builder  be used to make this happen. It seems like you'd want to feature the default as the top choice if there are multiple workflows to choose between. 

Currently when you select default workflow all that happens that if you click on classify without choosing a button the landing page you get the workflow that was selected as default on the first go

**Comment by brian-c** [comment]
Will get started on this today.

**Comment by mschwamb** [comment]
Thanks @brian-c .Much appreciated. If we can have this for the June 12th airing of the sky at night episode that will feature Comet Hunters that  would be really helpful as the show will be featuring the second workflow we're about to launch and that way we could place it as the first choice/option on the landing page. lf not, we can definitely deal without it.

**Comment by mschwamb** [comment]
@brian-c any chance this will be ready for Sunday night UK time for the first airing of  the Sky at Night episode?
