### ISSUE TITLE
Make the delete this task button look like the other buttons

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2513]
I was having a hard time finding the delete this task button. The rest of the buttons are bigger and blue or have grey on the workflow builder in the project builder. It might help if you could make the button look similar to the other delete this workflow button if you're not doing a significant redesign any time soon. 

![fireshot capture 19 - edit hsc comet hunters _ - https___www zooniverse org_lab_2575_workflow_1818](https://cloud.githubusercontent.com/assets/753325/14934639/e10e57c4-0ee9-11e6-814e-bd598780d02c.png)

**Comment by aliburchard** [comment]
yes please! Both for tasks and workflow. I think redesign for the project builder is a ways off, so this would be great in the meanwhile.

**Comment by brian-c** [comment]
Not sure if it matters, but this was deliberate. Destructive actions should be hard to do.

**Comment by aliburchard** [comment]
I think there's a difference between being "hard to discover" vs "hard to actually (esp accidentally) do." I think users should be able to easily see that they can delete a workflow and task, but that it should require deliberate intent to do so.

**Comment by mschwamb** [comment]
@brian-c it was more that the delete task button  didn't look like the delete workflow button which to me is a bit more visible but less noticeable as the blue buttons.  I had a hard time finding the white on white I think I was thinking maybe it could be grey like the delete workflow button. agree that it shouldn't look like the blue buttons

**Comment by CKrawczyk** [comment]
Ah, put the wrong style in my PR, let me switch that around.

**Comment by alexbfree** [comment]
We could consider putting it next to the Add Task button. It would make more sense there. 

I agree with Ali, it shouldn't be hard to find, just hard to complete the operation accidentally. We could just pop up an "are you sure?" confirmation upon click, to address this.

**Comment by mschwamb** [comment]
moving the button might be helpful as well.
