### ISSUE TITLE
Usernames can't have spaces, but users not told that

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2514]
I just had someone contact me who was having trouble signing up for a Zooniverse account. We finally diagnosed that they were trying to create a username with a space in it. It would be nice to be told that either initially or else with a little pop-up once someone entered a space-containing username. Perhaps  best of all would be to not even accept spaces as a valid character in the user name box....

**Comment by camallen** [comment]
@mkosmala we already to message this on zooniverse.org, was it an old project?
![image](https://cloud.githubusercontent.com/assets/295329/14980178/e2befde4-111e-11e6-9168-484cbb5779ae.png)

**Comment by mkosmala** [comment]
Oh, huh. Yeah, I see that. I guess the person didn't notice. sigh.
