### ISSUE TITLE
Ability to "clear all marks" when annotating a subject

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2515]
It would be useful if when drawing marks, there was a way to start again. At the moment if you get into a mess it can be hard to correct it. A "reset" button or "clear all" would be a good convention we could follow here I think.

Here is an example of a user requesting this on Talk:
https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/talk/357/46939

**Comment by alexbfree** [comment]
Additional note: This becomes really important on mobile. It's really easy to draw boxes you can't easily remove, and so starting again should be an option. We are seeing weirdly wrong boxes coming through and i think this is why (users don't know the workaround of reloading and getting a different subject).

**Comment by mschwamb** [comment]
@alexbfree  What about instead having a generic restart classification button rather than make it only specific to markings/drawing tasks?

**Comment by alexbfree** [comment]
There is already a back button. I think it's only drawing tasks that have this problem of not being easy to "undo"

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
