### ISSUE TITLE
We should add a page about translators/ambassadors

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#2526]
We should really at least have a place where we list the names of all the people who have done translation work for us.

**Comment by mschwamb** [comment]
duplicate of #1747

**Comment by trouille** [comment]
@mrniaboc Following Meg's thread to the duplicate issue, do you know where to get the content for this? I.e., the list of translators who have contributed?

**Comment by BNewing** [comment]
Would it be useful to add translating for the Zooniverse onto the volunteering page as a way of volunteering with us?
