### ISSUE TITLE
geordi-logging general interface

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2529]
- [x] Top menu nav links
- [x] Footer menu nav links
- [x] Submenu clicks
    - [x] Project menu nav links
    - [x] About menu nav links
    - [x] Collect menu nav links
    - [x] Globe menu nav links
    - [x] User menu nav links
- [x] Clicks within collections
    - [x] view-collection
    - [x] view-favorite
    - [x] settings-collection
    - [x] settings-favorite (doesn't appear to exist)
    - [x] collab-favorite (doesn't appear to exist)
    - [x] collab-collection
- [x] send message screen
    - [x] username-search
    - [x] send-message
- [x] sign in / sign out
    - [x] login
    - [x] logout
- [x] registration form
    - [x] register
- [x] please register popup
    - [x] please-register
    - [x] register-no-thanks
    - [x] register-sign-in
    - [x] register-register

**Comment by alexbfree** [comment]
+1 !! looks like you've been busy @amyrebecca !

**Comment by amyrebecca** [comment]
several of these have been broken by subsequent merges :/

**Comment by alexbfree** [comment]
Let's have me do a QA cycle before we merge the PR & close these tickets.
