### ISSUE TITLE
"View/Preview" tab from the workflow editor

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#253]
As I'm creating tasks, I'm constantly trying to see what those changes look like and how they affect the workflow. Right now, I keep having to do this by going up to "the lab" link, then selecting my current project from my list of projects and then clicking View. And then going back to "the lab" for that particular process. Could we add a tab that opens the "View Project" link directly from the editor? I realize you'll still need to save changes to a task to have them display, but I think that's fine.

**Comment by mrniaboc** [comment]
This is absolutely required.

**Comment by chrissnyder** [comment]
I disagree this is required. It would definitely be an improvement over what we have now, but I don't think that's an appropriate criteria for first release.

**Comment by brian-c** [comment]
I'm already working on this @chrissnyder. It'll be a while.

Should have assigned myself, sorry.

**Comment by chrissnyder** [comment]
Oh cool! Looking forward to see it.

Given that it will be awhile though, moving the milestone target to the all-encompassing "future plans".

**Comment by mkosmala** [comment]
Just really playing with the project builder for the first time. And I REALLY REALLY REALLY need a preview button. I don't even know how a non-Zooite would find the project to view -- it's really not obvious. Is it hard to just have a button at the bottom of the project builder page that opens a new browser page with the interface for the project appearing there? (WordPress-style)

**Comment by vrooje** [comment]
+100

**Comment by aliburchard** [comment]
All this has to be is a link that opens the project url in a new tab, right? Instead of making project builders right click on "build a project" and select "open in a new tab" and then click on "view" for the project they want. 

Being able to see what your project looks like as you are making changes is *absolutely critical* for project builders. The researchers building these projects have never (for the most part) built a project before, and so being able to see what adding tasks, reordering workflows, etc does is vital to building a project. Right now it's an enormous faff to do that, and I think ti will continue to be one of the biggest complaints we get about the builder.

A proper "preview" interface where you can classify and view changes without saving them would be nice, but that's icing. All we need is an intuitive way for users to quickly be able to see how the changes they're making in the project builder affect the actual project. I think this should be marked as PFE sprint 1 @chrissnyder - especially if it's just a link that opens in a new tab.

**Comment by mrniaboc** [comment]
This is the first piece of feedback that has come from almost  every single
person building a project. I think it's safe to say it's a priority.

**Comment by chrissnyder** [comment]
I don't disagree this is super important, but I have little concept of how much work it would be to implement and I fear I've already overshot what is possible to deliver in the first sprint (with an arbitrary end date set for the 17th).

@brian-c Given you have started this, would you be comfortable if we moved this up if I removed all the issues surrounding tools from the sprint? Again, I have zero concept if these are equivalent.

**Comment by brian-c** [comment]
Yeah, I'll make having a simple implementation of this my priority today.
