### ISSUE TITLE
tool-tip task with text box: focus should go straight to text box

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2530]
On Astronomy Rewind (formerly known as oldAstronomy), we use the tool-tip task to transcribe axis values. When you click on the location you want to transcribe, and then the text box pops up, it would reduce the number of clicks you have to do if your cursor went straight into the text box and you could start typing. 

@simensta @eatyourgreens @mcbouslog Is this something already being worked on as part of the accessibility work from last week's miniZTM? 

Thanks!

![tool-tip-functionality](https://cloud.githubusercontent.com/assets/4975655/15048577/c4274700-12af-11e6-9c0f-73374002cf0d.png)

**Comment by simensta** [comment]
@trouille, this should be taken care of as soon as PR #2508 is merged 😄

**Comment by trouille** [comment]
Great!
