### ISSUE TITLE
geordi-logging classification interface

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2531]
- [x] scroll down on project home
- [x] get started button
- [x] view subject
- [x] task interaction events
    - [x] draw
    - [x] drag
    - [x] resize
    - [x] delete
    - [x] select-option
    - [x] task-end
- [x] help with this task button
- [x] subtask answer click
- [x] subtask "ok" click
- [x] step completion button
- [x] exit to talk at end of task
- [x] cog menu
    - [x] classify-cog
    - [x] demo-mode-on
    - [x] demo-mode-off
    - [x] gold-standard-mode-on
    - [x] gold-standard-mode-off
    - [x] demo-mode-query
    - [x] gold-standard-mode-query
- [x] "classify" event when next pressed at end of task

**Comment by alexbfree** [comment]
Let's have me do a QA cycle before we merge the PR & close these tickets.

**Comment by srallen** [comment]
PR is merged.
