### ISSUE TITLE
geordi-logging Talk interface

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#2532]
- [x] talk-view event
- [x] enter key/ search button
- [x] back button
- [x] subject metadata
- [x] subject favorite
- [x] subject unfavorite
- [x] add to collection button
       - [x] add-to-collection
       - [x] make-collection-private
       - [x] make-collection-public
       - [x] add-collection
       - [x] search-collection
- [x] subject image button
- [ ] toolbar clicks
- [x] add comment button
- [x] notifications link
- [x] participant click
- [x] change projects button
- [x] hashtag clicks
- [x] subject name link click
- [x] subscribe to thread button
- [x] unsubscribe from thread button
- [x] edit post title button
- [x] insert linked image button
- [x] click on image to link it button
- [x] post links
       - [x] like-post
       - [x] reply-post
       - [x] link-post
       - [x] report-post
       - [x] edit-post
       - [x] delete-post
- [x] update comment button
- [x] pagination clicks
- [x] New discussion button
- [x] discussion title click
- [x] profile click under a post title
- [x] time click under a post
- [x] Recent Comments click
- [x] Breadcrumb click

**Comment by wgranger** [comment]
Note: accessing the buttons for "toolbar clicks" is hidden in Markdown and not in PFE.

**Comment by alexbfree** [comment]
Let's have me do a QA cycle before we merge the PR & close these tickets.
