### ISSUE TITLE
Need to strip images from tool labels when using in classification summary

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2536]
As you can see in this screenshot from https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/, we end up with something rather ugly 

![screenshot 2016-05-06 12 09 45](https://cloud.githubusercontent.com/assets/1473244/15071449/8fd53c62-1383-11e6-876c-7cc2fb4685a1.png)

We could render the image, but TBH i think just stripping them out would be better

Any project that uses images in labels, will suffer the same issue. Her is another: https://www.zooniverse.org/projects/klmasters/galaxy-zoo-for-schools-outreach/classify

**Comment by alexbfree** [comment]
While we're in there, let's clean up the text a bit:

How about:
`Animal facing to the left (2 rectangles)`
rather than
`rectangle Animal facing to the left (2)`

**Comment by alexbfree** [comment]
OK I found a few minutes, i have a fix for this... PR here https://github.com/zooniverse/Panoptes-Front-End/pull/2560/files

**Comment by alexbfree** [comment]
A note about the fix: it requires you to specify your links like this:

```
![](https://panoptes-uploads.zooniverse.org/production/project_attached_image/9caf156d-5952-45f1-8787-81451ac4eb7f.png)
```
not this:
```
![animal_facing_left_1.png](https://panoptes-uploads.zooniverse.org/production/project_attached_image/9caf156d-5952-45f1-8787-81451ac4eb7f.png)
```
or you will still see the filename (ie link text) in the label

**Comment by eatyourgreens** [comment]
@alexbfree so remove any alt text from the images? I'm not sure about that.

**Comment by alexbfree** [comment]
@eatyourgreens No - we are entirely removing the images.

Removing the link label ensures that nothing survives of the images - which is what we want in this context. (without that, the image link in full markdown gets replaced with just the link label)

**Comment by alexbfree** [comment]
@eatyourgreens you can try it out here on this dummy project > https://cleanup-drawing-summary.pfe-preview.zooniverse.org/projects/alexbfree/untitled-project-5-10-2016-4-22-18-pm/classify

**Comment by eatyourgreens** [comment]
I understand, but your markdown example will render as `<img alt="" src="https://panoptes-uploads.zooniverse.org/production/project_attached_image/9caf156d-5952-45f1-8787-81451ac4eb7f.png">` in places where the image is rendered as HTML ie. in the classification questions.

**Comment by alexbfree** [comment]
Oh wait, i just realised what you mean. the hover text will still be wiped where the image *is* rendered. 

Not sure what to do about this!!

**Comment by alexbfree** [comment]
ok, right. with you now.

**Comment by eatyourgreens** [comment]
That text is also picked up by cut-and-paste, and read out by VoiceOver, so removing it might not be a good idea.

**Comment by alexbfree** [comment]
OK, I guess we will have to manually delete the image link from the label, before the text is passed to the markdown-stripper library.

**Comment by alexbfree** [comment]
on the bright side that means i can fix without changing the live project

**Comment by alexbfree** [comment]
OK, PR is updated with a new version that doesn't require blank link labels. @eatyourgreens would you be able to review/merge the PR?
