### ISSUE TITLE
Change "set-up details" button text

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#254]
Perhaps to "Add a sub-task"? And then we'll explain what a sub-task is in the help text.

**Comment by twhyntie** [comment]
Yes please - I don't actually know what a sub-task is :-)

**Comment by aliburchard** [comment]
Can we change this for first release? Even just "add a question" or "add a sub-task" because "set up details" doesn't seem to make sense. @brian-c?

**Comment by chrissnyder** [comment]
Looks to be changed.
