### ISSUE TITLE
It's too hard to delete drawn shapes on mobile

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2540]
It's easy to draw and adjust shapes on mobile, but very hard to delete them. The click target is too small for a finger, and you can end up drawing another box by mistake.

Once thing that would help would be a "Clear all" button per #2515 - but also we need to think about having a "Delete last drawn mark" button or similar. Or moving the delete X away from the shape on a small screen.

**Comment by amyrebecca** [comment]
if we ever are able to move to redux, this is where having time-traveling state would be nice, we would have an "undo" button for free!

**Comment by srallen** [comment]
Delete button position was adjusted in #2816.
