### ISSUE TITLE
Hashtags make spaces between them and neighbouring words disappear

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2541]
Using # symbol makes the space between the hashtag and the neighbouring word disappear. When you use two hashtags in a row, then they appear as a single tag with no space between.

Screenshot:
![](https://lh3.googleusercontent.com/-KPsTUGoZn7E/Vy3G02mdU3I/AAAAAAAAI4s/mr_kzqD2vyElLrXG_dlwTKWfARyekFR3QCCo/s0/ysh_2016-05-07_12-34-21.png)

**Comment by yshish** [comment]
And another problem related to that - when you write "!" symbol and then write a hashtag, since it removes the space from before the "#" symbol, it behaves like if you wanted to put an image there and the results are bad:

screenshot (look just below the cursor):
![](https://lh3.googleusercontent.com/-JdsNc2HaJ74/VzNerdl6yQI/AAAAAAAAI5I/UdbAhXT2glI0KUWJeNSabLntWqjto6upACCo/s0/ysh_2016-05-09_06-25-45.png)

**Comment by yshish** [comment]
Not sure but I guess that such hashtags are not included in the Search, are they?

**Comment by mschwamb** [comment]
I've just run into  this.  Example [here](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/sct). I could see the text box autocomplete the two hashtags together as I hit submit  - it then only links them to the tag search for the first hashtag. 

I'm concerned this means we're loosing the recording in the Talk database one or both of the hashtags, which would partially research teams ability to search for interesting and rare combinations by looking for multiple hashtags on Talk. 

@parrish would this be something you could look at or is this a markdown issue and need to go that repo?

**Comment by parrish** [comment]
It looks like the markdown parser is just consuming the space when it renders (it's actually still there).

Everything's working normally other than when it renders them as links:  [Comment data](https://talk.zooniverse.org/comments/105421) and [created tags](https://talk.zooniverse.org/tags?comment_id=105421)

I'll see about fixing it today.

**Comment by mschwamb** [comment]
Thanks @parrish
