### ISSUE TITLE
A new collection doesn't appear in the list for adding a new subject

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2542]
I've created a new collection (called *Spot Quenda*) today with a single subject in it. After a couple of hours I wanted to add a new subject from the classification page but this collection was missing in the list of all my collections. So I went to the Talk page to try it from there but I haven't found the collection in the list either. So I went to my Profile page to check all my collections to make sure it has been created and I did found it there. 

I think this happened before with another of my collections as I created it twice and then found both of them there. One is called *Questions-Answers* and the second one is called *Questions/Answers*. Only the second one appears in the list of my collections.

Can you explain that? There may be even more collections which don't appear in the list but it is not easy to make sure with such a big number of them... especially when collections from other projects appear in the same list as the collections of the project I'm just participating in.

**Comment by MvGulik** [comment]
Considering your having more than 20 collections (at this moment, June 07). Your probable running into the fact that the "add subject to collection" - "collections drop-down list" will only show 20 collections.
Source Ref Issue: #2454

Workaround: Type in a 4 character part of the collection-title your looking for.
-- *At least 4 character, as anything less will return an empty search result.*
-- *None case-sensitive search btw.*

Real issue: Lacking some collection's user-level documentation describing the less then general-intuitive behaviors.

**Comment by camallen** [comment]
For ref - we match on 3 char variants but in some cases you'll need more chars. The add to collection UX for more than 20 collections is meant to flow like the gif below. 

What can we do to make the typing part more intuitive? Some placeholder text?

![add_to_collections](https://cloud.githubusercontent.com/assets/295329/15855990/d357b2ea-2caa-11e6-9449-f257ab905f81.gif)

**Comment by yshish** [comment]
Ah, OK. Thanks for explaining.

Hm, what about adding a symbol of a magnifier or putting something like *'Search for the collection'* text in the text field instead of just *Collection Name*?

**Comment by MvGulik** [comment]
> What can we do to make the typing part more intuitive? Some placeholder text?

I don't think that that search-box has the space to drop any none cryptically help text in it. (*Cryptic to those that start using it for the first time of course.*)

Next would be to add some small print. Like perhaps "_Limited to showing 20 collection at one's_", and "_Type to search (at least 3 characters)_"

Final solution would be to just have some [?] icon, which would open op a whole new space for useful information. :)

-- Magnifier-icon: +

**Comment by MvGulik** [comment]
If its possible to detect that there where more than 20 collection entries (*at the UI level*), this could be used to trigger some related feedback action.
-- Different info text in search-field. (*probably easy to miss by the user.*)
-- Additional info/feedback entry in the drop-down list. (*might give an additional option to do something when the user clicks on it.*)

*Remember that, until a user start having more than 20 collections (*as owner and/or collaborator*) the default perceived behavior of the drop-down list is that it displays all user related collections.*

Still think the "[?] icon" or "small print" option are the better solutions.
