### ISSUE TITLE
Grid drawing task

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2545]
Replicate functionality of OldWeather Angular component

**Comment by wgranger** [comment]
<img width="1004" alt="screen shot 2016-05-27 at 1 37 55 pm" src="https://cloud.githubusercontent.com/assets/14099077/15617940/eb4d9c0e-2410-11e6-9826-bdc9c2b14819.png">

This is the state of the grid tool as it exists now. Basically, a user will mark out the headers and then will be able to save that template into a row. Currently, the user can switch between cells and rows. I'm still playing around with making the rows work more intuitively. My current challenges include:

- Should users be able to drag a drawn row? I think so, but this will be a bit challenging with the way we have rendering operating independently from annotations.

- Should a user be able to place an entire grid based on a past annotation? Again, this would be nice, but would take a bit more dev time.

**Comment by srallen** [comment]
@wgranger can this closed since #2770 is merged? In the future can you include a `fixed` or `closed` message along with the issue number so it auto-closes.

**Comment by wgranger** [comment]
@srallen Yep. Thanks for the heads up and advice. This should be good to be closed.
