### ISSUE TITLE
Change "close" to "save" on sub-task pop-up

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#255]
Right now as you add a sub-task, you can only "close" or "add task" within the pop-up. The process on the main workflow editor is to "save changes" and I think it's confusing that "close" means "save this task instead of "cancel" and that "add task" means "save this task and add another" instead of "save this new task." Can we re-word?

**Comment by chrissnyder** [comment]
Looks to be taken care of with a combination of the help text and the recent auto-save feature Brian added.
