### ISSUE TITLE
Generate subject sets for Workflow 2

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#2552]

**Comment by amyrebecca** [comment]
generate subjects even for high-confidence results

**Comment by trouille** [comment]
A starting thought for what we'd want to include in the manifest.csv file for workflow2 subjects. 

subject_id,image_name,ship_name,logbook_pagenumber,cells_row_number,cells_column_number,#confidence
1,farragut-p70-r4-c6.jpg,farragut,70,4,6,0.9
2,farragut-p70-r4-c7.jpg,farragut,70,4,7,0.1

![farragut-p70-r4-c6](https://cloud.githubusercontent.com/assets/4975655/15193541/00d0b88e-1784-11e6-930e-fced149d8d20.jpg)
![farragut-p70-r4-c7](https://cloud.githubusercontent.com/assets/4975655/15193542/00d1fadc-1784-11e6-84a6-1d10d3551b69.jpg)

**Comment by srallen** [comment]
Can reopen if still need.
