### ISSUE TITLE
Moving the hide previous marks so that one doesn't have to scroll down to hit the submit button on certain projects 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2562]
With a normal interface where you've got like four responses and a reasonable but a bit longer amount of text that  if there's multiple drawing tools the hide previous marks now pushes the submit button off my 13-inch mac screen. It gets a bit annoying having to scroll up and down upon each subject review. 

It seems like moving 'Hide previous marks' to under the subject would help or moving it to be on the same line as the help button would save a line and make more project interface fit within the normal small range displays for laptops

example is https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/classify

<img width="1146" alt="screen shot 2016-05-10 at 12 27 26 pm" src="https://cloud.githubusercontent.com/assets/753325/15164662/042d4a52-16ac-11e6-9b69-4871099c35d0.png">

After that point I'd have to scroll

**Comment by alexbfree** [comment]
You're right that this could help.
Another idea would be to have "need some help" and "hide previous marks" side by side.

Having said that I wonder if we should have a more general solution. 

Perhaps we should consider having the back/next/submit toolbar always present, on a non-scrolling fixed toolbar at the bottom...

**Comment by alexbfree** [comment]
I do think it's true we are wasting a lot of vertical space between help button, previous marks, and tutorial button... 

Tagging @brian-c @srallen @jwbmartin to see what thoughts people have....

**Comment by srallen** [comment]
Maybe we could implement a show/hide button to collapse certain areas (defaulted to show at first), but ultimately I'll defer to @jwbmartin since this seems to be more of a design issue.

**Comment by mschwamb** [comment]
same issue on the new milky way project you have to scroll on a 13-inch screen to see there is a tutorial button. Since the the tutorial button is below the 'done' button I doubt people will see it. 

It seems like it would be easy to move hide previous marks to under the subject image or to the left or right of the 'need some help with this task'

<img width="1129" alt="screen shot 2016-09-15 at 7 49 06 am" src="https://cloud.githubusercontent.com/assets/753325/18560916/56bca7a0-7b19-11e6-855e-15a04971be8f.png">

**Comment by mschwamb** [comment]
I'm assuming this is being addressed in the classifier redesign and can be closed?

**Comment by srallen** [comment]
I'll at-mention @beckyrother to make sure she knows about this toggle. Only certain drawing task projects have this enabled.

**Comment by beckyrother** [comment]
Thanks for the heads up, I've made a note of it for the redesign. This issue can be closed @srallen 👍
