### ISSUE TITLE
Replace oldWeather-OCR talk with existing oldWeather.org Talk

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2567]
Can we take https://www.zooniverse.org/projects/zooniverse/old-weather/talk/ and use it in place of https://www.zooniverse.org/projects/trouille/oldweather-ocr/talk? 

Both oldweather.org and whaling.oldweather.org feed into this same Talk. Best if oldWeather-OCR did as well.

**Comment by srallen** [comment]
Probably could be solved with org level talk. Sounds like a backend issue.
