### ISSUE TITLE
Create subject sets for dates and lat/long pairs

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2568]
In workflow1, in addition to gridding out the logbook, volunteers will put rectangles around any dates and any lat/long pairs. 

For workflow2, in which volunteers will be transcribing, among the subject set that will include all the individual cells from the logbook, we could include the rectangles with dates or lat/lon pairs. The volunteers would also transcribe these. These (the dates + lat/lon transcriptions) will not feed into the OCR component of this project.

**Comment by srallen** [comment]
Can reopen when needed.
