### ISSUE TITLE
Survey tool bugs in Internet Explorer

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2569]
- [ ] Filter selections pop up in upper-left hand corner of the screen, and options appear blurry

<img width="1139" alt="junk" src="https://cloud.githubusercontent.com/assets/4975655/15197097/3393fc2a-1795-11e6-8094-c2938fabb66e.png">

**Comment by trouille** [comment]
@aliburchard You may already have issues out for these. Link them here or feel free to close this issue if it's already covered elsewhere.

**Comment by aliburchard** [comment]
@trouille nope, but this is similar to what we're seeing here: https://github.com/zooniverse/Panoptes-Front-End/issues/2471 - would be great to get them both fixed!

**Comment by simensta** [comment]
@trouille: which version of Internet Explorer?

**Comment by trouille** [comment]
<img width="365" alt="junk" src="https://cloud.githubusercontent.com/assets/4975655/15590881/8d264768-235f-11e6-96ef-bd8564b6a8de.png">
