### ISSUE TITLE
Subject uploader functionality

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#257]
A few things I think would be *really* useful for project builders/have questions about:

* Can we allow users to drag a folder with images and file manifest into the the "drop" area instead of having to select all the images
* If the answer to the above is "yes," what happens when the folder they drag in has sub-folders? From my understanding, folders with sub-folders is how many of our projects give us data. We don't have to accommodate that, but I suspect it will be a really common request.
* Are we going to support a file selection approach so that folks don't have to drag and drop? (It kind of works right now, but only if the manifest extension is visible and there are no extra files in the directory. If that's planned behavior, we can add help text.)

**Comment by brian-c** [comment]
Let's say no to the first two points for now. I've barely got regular file selection working.

I don't quite understand your third point. Clicking in the upload-area should bring up a file selection box, and from there you should be able to select manifests and images with the appropriate extension.

**Comment by twhyntie** [comment]
@brian-c Re. the third point, I get the file selection box as below:

![subject-set_upload-dialog](https://cloud.githubusercontent.com/assets/1625332/7476715/5419c57e-f347-11e4-9f12-585abb535967.JPG)

(I can switch between "All Types" and "Image Files".)

However I can only select one file at a time with this dialog as implemented. Is there a way of enabling multiple file selections?

**Comment by camallen** [comment]
@twhyntie even when using the ctrl + click key combo?

**Comment by twhyntie** [comment]
@camallen Yup. Ctrl + click (and Shift + Click) doesn't work (Windows 7, Firefox). For C++ dialogs you'd be looking at something like the [OpenFileDialog.Multiselect](https://msdn.microsoft.com/en-us/library/system.windows.forms.openfiledialog.multiselect%28v=vs.110%29.aspx) - how is the dialog implemented here?

**Comment by twhyntie** [comment]
(ICYMI, multiple file selection solved in [#280](https://github.com/zooniverse/Panoptes-Front-End/issues/280).)
