### ISSUE TITLE
Field guide bugs in Internet Explorer

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2570]
- [ ] It is not possible to scroll when viewing the Field Guide. The scroll bar is hidden and the up/down arrows only scroll the main page.
- [x] The “Field Guide” tab is almost impossible to see because it doesn’t have the light background like it does when viewed with other browsers.

<img width="629" alt="fieldguidelost" src="https://cloud.githubusercontent.com/assets/4975655/15197524/7783a096-1797-11e6-972f-d87320182827.png">

**Comment by srallen** [comment]
Background color is fixed in #2726
