### ISSUE TITLE
Update team page

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#2578]
Related to #2575, we have lots of new people! Let's get the team page updated. @mcbouslog, @amyrebecca, @zwolf, @wgranger could you write up a short 2-3 sentence bio and pick out a nice photo for a mugshot? @mrniaboc do you know who else may be missing?

**Comment by alexbfree** [comment]
Also @dwright04. And maybe @melaniebeck.

**Comment by alexbfree** [comment]
OK @amyrebecca @zwolf @mcbouslog @wgranger @dwright04 @melaniebeck please send me your image and text (use https://www.zooniverse.org/about/team for guidance on length) and I will update

**Comment by alexbfree** [comment]
Adding user bios and profile text here. Will code this once I have them all.

From Mark:

> Mark is a front-end web developer for the Zooniverse team at the Adler Planetarium. Joining in November 2015 from a career in accounting, he’s thrilled to focus his number crunching to 1’s and 0’s and is constantly inspired and humbled by the power of programming, citizen science and coffee.

![mark](https://cloud.githubusercontent.com/assets/1473244/16156976/829b5440-34ae-11e6-91fb-d234044141ad.jpg)

**Comment by melaniebeck** [comment]
Sorry I'm behind on all this stuff, Alex!

Melanie is a PhD astrophysics student at the University of Minnesota and a
collaborator on the Galaxy Zoo team. She has been working on incorporating
machine learning algorithms in conjunction with volunteer votes to classify
galaxy morphologies. This will make Galaxy Zoo more efficient for upcoming
astronomical surveys which will uncover billions of never before seen
galaxies!

**Comment by srallen** [comment]
@melaniebeck do you have a particular photo of yourself that you'd like us to use for the team page?

**Comment by eatyourgreens** [comment]
Searching my phone now for any photos taken in the pub.

**Comment by srallen** [comment]
Still need photos and bios from @amyrebecca, @zwolf, @dwright04

**Comment by zwolf** [comment]
Sent mine over to you via email.

**Comment by srallen** [comment]
@BNewing Could you send a photo and bio for our team page? See above for examples.

**Comment by mschwamb** [comment]
@srallen if it's not too much trouble can I also get updated. I've moved positions and institutions. I'm now an assistant scientist at Gemini Observatory in Hilo, Hawaii.  I might cause more issues if I try to update the source code myself.  

Taipei-> Hilo 

Meg is a planetary scientist and astronomer involved in the Zooniverse's Planet Four, Planet Four: Terrains, and Comet Hunters projects. She also serves as project scientist for Comet Hunters. She studies small bodies in the Solar System, exoplanets, and Mars. Meg has a fondness for baking, soccer, and champagne.

Feel free to say no and make me do it.

**Comment by alexbfree** [comment]
@melaniebeck can you shorten yours please? It needs to fit on three lines:
![screenshot 2016-08-11 12 50 31](https://cloud.githubusercontent.com/assets/1473244/17587795/48c01dc0-5fc2-11e6-81b5-c6740228f008.png)

Also, we still need an image.

**Comment by alexbfree** [comment]
Still need profiles and images from @dwright04 @amyrebecca @BNewing

**Comment by camallen** [comment]
@alexbfree #2872

**Comment by alexbfree** [comment]
thanks cam, will look

**Comment by alexbfree** [comment]
can close this now, addressed via #2886

**Comment by melaniebeck** [comment]
Now with more shortness:
A PhD student at the University of Minnesota, Melanie works on combining
machine learning with volunteer votes for classification tasks on the
Galaxy Zoo project with the goal of classifying *billions* of galaxies that
future telescopes will see.

As for image, is it a terrible burden to black-and-white and crop it
yourself? If not, I can doctor it up in a couple hours after some meetings
this morning.

**Comment by alexbfree** [comment]
OK @melaniebeck that's fine - am updating yours and adapting your github image, as part of #2886.

**Comment by beckyrother** [comment]
@srallen Since there's been some changes to the team recently, can I reopen this issue? 

Please remove Michael Parrish and Jordan (and anyone else I'm not aware of) and add Sam and me. 

Thanks!

**Comment by srallen** [comment]
@beckyrother, Ok, we can do that. Thanks for the reminder. We need head shots and short 3-4 sentence bios from you and @snblickhan

**Comment by snblickhan** [comment]
@beckyrother @srallen Here's my headshot!

![bio_photo](https://cloud.githubusercontent.com/assets/25958358/24001877/3d5190d4-0a2d-11e7-81d7-1a9fd27ace7d.jpg)

**Comment by beckyrother** [comment]
Thanks @snblickhan! Here it is in black and white @srallen 
![sam-bw](https://cloud.githubusercontent.com/assets/1392130/24002456/b1a80d48-0a58-11e7-8b47-e2caf333e951.jpg)

**Comment by beckyrother** [comment]
Here's mine:
![becky-bw](https://cloud.githubusercontent.com/assets/1392130/24003959/dae919a0-0a5c-11e7-9af1-d337d3250794.jpg)

Becky joined the Zooniverse team as designer in 2017. With a background in mobile apps and product design and a degree in journalism, she's excited to use her powers for good with the Zooniverse team. 

my twitter is @beckyrother
