### ISSUE TITLE
Column headers in export CSVs are missing quotes, creating parsing issues with standard csv libraries

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2579]
I was writing a script to parse the subjects exports file generated by PFE. I was having issues where I couldn't correctly reference the fields of the data. It turns out the problem is that the CSV file doesn't have quotes around the column names in the header line. CSV parsers such as [csv](https://www.npmjs.com/package/csv) and [fast-csv](https://www.npmjs.com/package/csv) which can automatically read the header line when you specify `headers` to `true` expect the header line to be strings, or else the header line ends up undefine, the rows end up with keys equal to their values, and the csv parsing doesn't advance properly.

By simply changing the source CSV file to have quotes around the header line column names, all these problems went away, so I think PFE export should change to avoid other people having this pain.

Instead of 
`subject_id,project_id,workflow_ids,subject_set_id,metadata,locations,classifications_by_workflow,retired_in_workflow`
the header line should be
`"subject_id","project_id","workflow_ids","subject_set_id","metadata","locations","classifications_by_workflow","retired_in_workflow"`.

We should check all our export CSVs as well to ensure that no string value is exported without quotes.

**Comment by srallen** [comment]
@alexbfree This is a Panoptes issue. A recent change to CSV exports just got merged there, so probably want to open this there.

**Comment by eatyourgreens** [comment]
If it's of any help, here's the Javascript I use to parse a CSV file with the `csv` package.
https://github.com/eatyourgreens/wellcome-subject-uploader/blob/master/process-csv.js#L169-L171
```javascript
var parser = csv.parse({columns: true}, function(err, data){
  data.forEach( processLine );
});
```

The first two lines of my CSV file look like this (headers aren't quoted) and the CSV parses without errors.
```csv
File prefix,TITLE,,Title,AUTHOR,Author,Date,PUBLISHER,BOROUGH,LICENSE INFO
b19783280,[Report of the Medical Officer of Health for Acton] [electronic resource],[Report of the Medical Officer of Health for Acton] [electronic resource],[Report of the Medical Officer of Health for Acton] ,,,Annual report; 1893,"Acton (London, England). Local Board.","Acton (London, England)",
```

**Comment by aliburchard** [comment]
ooh @alexbfree will these csv parsers be generalizable? (i.e. can we run them on any (or at least some) project(s)?)

**Comment by alexbfree** [comment]
@aliburchard I wrote it for a specific task but happy to share my code. PM me

**Comment by alexbfree** [comment]
@eatyourgreens Thanks. Already solved it for my specific case, but would like to save others some pain.

**Comment by alexbfree** [comment]
Thanks @srallen. Have moved this to https://github.com/zooniverse/Panoptes/issues/1803 . 

Closing.

**Comment by aliburchard** [comment]
Ah, Alex, sadly I don't have the skills to run your code (nor do most project builders). Thanks though. Would be great if you can make your code publicly available on https://github.com/zooniverse/data-digging though, for folks who can make use of it.
