### ISSUE TITLE
Classification submitted; new workflow loads but new subject doesn't

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#258]
This has happened to me 3 times today so I'm now sure I'm not imagining it or pressing the wrong thing:

I'll finish a classification and click Next, at which point the workflow resets to the first question as expected, but the subject does not reset. Even if I let it sit for a while in hopes it's just taking time to load, the previous subject is always displayed. If I classify it again it will finish correctly and load a new subject.

I'd estimate this is happening once every 20 classifications or so. Is this related to the duplicate subject bug?

**Comment by camallen** [comment]
There was a recent issue with the backend (DB connections) that may have caused this. Can you reproduce now?

**Comment by vrooje** [comment]
Will let you know, but note the first time I noticed was over an hour ago
(I just thought I had imagined it)...

**Comment by camallen** [comment]
ok - fair point.

**Comment by brian-c** [comment]
@vrooje How many subjects are loaded?

@camallen Can you determine if all @vrooje's classifications are for different subjects? It sounds like this  is just picking the same subject twice in a row.

**Comment by camallen** [comment]
@brian-c I had a look at this earlier, as i was seeing it. The subject queue wasn't depopulating the seens subjects properly. [This PR](https://github.com/zooniverse/Panoptes/pull/781) shoud have fixed it. New subjects need to be classied though to update the queue. Looks like that code isn't runnning though.

@edpaget seems the latest builds aren't deploying properly. https://panoptes-staging.zooniverse.org/commit_id.txt vs https://github.com/zooniverse/Panoptes/commits/master, can you check this out?

**Comment by vrooje** [comment]
Note I haven't seen this bug in 24 hours.

**Comment by edpaget** [comment]
Cool I think this was due to our database issues.
