### ISSUE TITLE
Labelled date ranges on stats page

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2588]
@CKrawczyk and I discussed this idea, raising it as a ticket here as suggested.

For each graph, it would be nice to label the date range endpoints in words - either as a title, or as markers on the slider.

When you adjust the slider, the dates should update.

Optionally you could also label the "maximum possible dates" (ends of the slider).

**Comment by srallen** [comment]
For some reason this didn't close with #2683. Closing...
