### ISSUE TITLE
Page navigation request inconsistency

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#259]
This is a weird issue only observed on my account. 

Steps to reproduce:
  1. Make a fresh page request on '#/projects'
  2. Click on another page link (#/ or #/discuss)
  3. Click on '#/projects' link
  4. Error is rendered to screen in place of projects, with 'beta' and 'approved' params set to false in the request:
    - `Error: There was a problem on the server. https://panoptes-staging.zooniverse.org/api/projects?beta=false&approved=false → 500`

I tested this a bit with @brian-c and he agreed it was strange. So far only reproducible on my main account, but with consistency. If anyone else witnesses similiar behavior please leave a note.

**Comment by brian-c** [comment]
This is really weird. Accounts, "brian-c", "brian-testing", and "alex3" are fine, but "alex" can't seem to load `/projects?beta=false&approved=false` twice.

Possibly something @edpaget and @camallen can look at?

**Comment by edpaget** [comment]
This is really odd. It doesn't look like there were any errors logged on our end for that request either.

**Comment by chrissnyder** [comment]
@aweiksnar Does this still occur?

**Comment by aweiksnar** [comment]
I lost ownership of the "alex" username during the last users migration, so this may be challenging to reproduce. Feel free to close if you'd like and we can always re-open if it comes up again. My new panoptes account has been good

**Comment by chrissnyder** [comment]
Roger that.
