### ISSUE TITLE
Stats page completion plot is incorrect if you don't keep all your previous subject sets active

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2591]
This might be a backend issue.  Because I don't have completed subject sets still checked on Comet Hunters I get a completed count that is higher than the  number of available subjects which makes the plot on the stats page say that Comet Hunters is 100% complete and out of data when it's not. 

This might be more of a backend issue, but basically unless a project owner keeps everything checked then the completion plot isn't useful at all. Perhaps instead it can do the count for the live subject sets and do the query on retired versus live and show that in the plot

cc @CKrawczyk @camallen

**Comment by aliburchard** [comment]
I think this is a failure to message properly on our part, but we know that if you unlink subject sets from workflows then the counters are wrong, so I've been telling everyone to keep all subject sets linked. What's the intention behind delinking subject sets? @camallen thinking we either need to more clearly message the relationship between subjects, subject sets, and workflows or else change the way we calculate stats...

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/issues/1804

Agree, I think we should fix the counters

**Comment by aliburchard** [comment]
yay! that makes more sense and is how people intuitively want to use the subject set linking.

**Comment by mschwamb** [comment]
thanks

**Comment by srallen** [comment]
This looks fixed.

**Comment by mschwamb** [comment]
Re-opening - A temp band-aid solution was implemented. Comet Hunters still says 100% complete one of the workflows  because I thinks unchecked and beta test classifications.  All that was added was a note to see the ETC might be wrong. Currently it makes the stats page not helpful and I still need to compute the completion number myself. I think the backend might now have the feature but the stats page hasn't been updated.

**Comment by CKrawczyk** [comment]
@camallen is there a value on the backend that would be more accurate for this than `workflow.classifications_count` (i.e. classification count for live subject sets in a workflow)?

**Comment by camallen** [comment]
I think we need to change the workflow completeness metric to only use the current linked set state instead of the global counts, e.g. [here](https://github.com/zooniverse/Panoptes/blob/4f4fcd6398a1cf1a0d92483057b28827f53e6cca/app/workers/calculate_project_completeness_worker.rb#L32) should figure out how many of the current set is retired instead of taking the whole workflow lifetime count OR we change the count to be the active count and add a new `lifetime_retired_subjects_count` for the total count. That way the value is precomputed (might be a little difficult though).

**Comment by mschwamb** [comment]
see #3145
