### ISSUE TITLE
having buttons to return you to the default graph window preview sizes on the new stats page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2592]
When you intially go the stats page it has preset window sizes for the graphs below. Once you move them around there's no  way to easily go back to that default view. Reloading the page doesn't reset the graph view. Moving away to another link on the page and coming back does seem to do this. I think it would be nice if there was a quick way to go back to a default view.

**Comment by CKrawczyk** [comment]
Good idea.  

Just so you understand what is happening, when you change the graph's position the URL updates with this information so you can send links to specific sections of the graph.  Another way to get back to the default view is to remove everything after `/stats` in the URL.

**Comment by mschwamb** [comment]
Thanks. I didn't realize it was updating the url, neat feature. In case I haven't said it,  the stats page looks great @CKrawczyk

**Comment by alexbfree** [comment]
I didn't realise that either @CKrawczyk . Smart! I wonder if it might even be worth emphasising that by having a "Share" button that can grab the current URL and put it into the copy buffer..

**Comment by mschwamb** [comment]
Looks like the ticket was left open. As the feature is implemented,  I'm closing my ticket.
