### ISSUE TITLE
subject uploader doesn't match uploaded files

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#260]
Moved from Panoptes/#778 - The drop area says I've got 0 manifests and 2 files selected, though note that nothing is actively selected for upload. Also, I actually have uploaded 1 manifest and 4 files at this point. 

![screen shot 2015-05-01 at 11 47 19](https://cloud.githubusercontent.com/assets/6217406/7433905/ee3ab25c-f02d-11e4-8cbe-43b971e93984.png)

**Comment by brian-c** [comment]
What are the names of the files you've selected?

**Comment by aliburchard** [comment]
I don't have *any* files selected currently, and don't see any way to view the currently imported subjects or manifest. The names of the files that have already been uploaded are something like beestie1.jpg etc.

**Comment by twhyntie** [comment]
@aliburchard Out of interest, are you doing this on Windows? When I try to upload `CSV` manifests on Windows 7 it fails to recognise them (a problem with Windows and file extensions - see [#191](https://github.com/zooniverse/Panoptes-Front-End/issues/191)) and I see what you see - 0 manifests uploaded. The images upload OK.

When I use Firefox in Linux (Xubuntu), the manifest uploads fine and I'm able to confirm the lists match (though as you say there's no way to check the individual files match, which would be useful).

**Comment by aliburchard** [comment]
@twhyntie nope, I'm on a mac. I'm getting this weird mismatch outside of trying to upload photos. I've just gone to view my subject set (with the intention of selecting more photos for upload), and that's what I see...

**Comment by twhyntie** [comment]
@aliburchard Yeah, I think I have this problem too (Linux). When I first upload the manifest, I see this:

![subject-manifest-upload_pre-subject-upload](https://cloud.githubusercontent.com/assets/1625332/7441095/2d84a6e6-f0d0-11e4-93cb-e7c56f208f8f.JPG)

Once I have selected the images in the manifest, I get this:

![subject-manifest-upload_post-subject-upload](https://cloud.githubusercontent.com/assets/1625332/7441100/5a20b712-f0d0-11e4-8d2e-5ce297e01444.JPG)

I then upload the subject set by clicking on the _Upload 11 new subjects_ button.

When I leave the subject set and come back to it, I then see this:

![subject-manifest-upload_return-to-subject-set](https://cloud.githubusercontent.com/assets/1625332/7441108/d1bee4ec-f0d0-11e4-958a-8eab0d36bf38.JPG)

i.e. I only have the option to delete the 11 files in the subject set and no way of editing them.

**Comment by brian-c** [comment]
This is a UI issue, discussed in #263.
