### ISSUE TITLE
Dashboard: recent classifications not updating

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2603]
It seems the 'recent classifications' count isn't working. It hasn't changed for Snapshot Wisconsin in the last hour (stayed at ~3K), while the classification count has gone from 39K to over 44K.

<img width="1048" alt="junk" src="https://cloud.githubusercontent.com/assets/4975655/15337361/eae5e5f0-1c40-11e6-8532-1a3b8500da36.png">

**Comment by CKrawczyk** [comment]
That is strange.  I am pulling this number directly from the project's API, @camallen any ideas?  Relevant code on the back end (I think): https://github.com/zooniverse/Panoptes/blob/master/app/workers/calculate_project_activity_worker.rb#L22

**Comment by camallen** [comment]
Yeah - it only runs [every day at midnight](https://github.com/zooniverse/Panoptes/blob/94b27a1ed55655f33c1202e1eb9b8e7e021cd7cd/app/workers/calculate_activity_worker.rb#L9), what is the optimum schedule for this?

**Comment by trouille** [comment]
I'm wondering whether that number is needed or just going to be confusing without a caption describing when it's updated and the time over which it's compiled (which seems like unnecessary clutter). Maybe remove, since the same information is in the graph of classification counts below? @aliburchard What do you think?

**Comment by aliburchard** [comment]
Hm, I feel like a small "last updated at" bit of text wouldn't be too much. I don't see where that number is reported elsewhere on the page, and think it's useful for project owners to be able to see.

**Comment by mschwamb** [comment]
@CKrawczyk  what about making that value the number of classifications from the previous day (the second to last bar on the histogram plot? It would be consistent with what's displayed on the stats page. It's  the number I'd want to know as a researcher.  

It seems close to that value already  but maybe different time frames than what's reported on the stats page. Currently Recent Classifications has 1777 classification on Planet Four: Terrains and the histogram plot has 1536 for the previous day.

**Comment by srallen** [comment]
@CKrawczyk I think this one can close too?

**Comment by CKrawczyk** [comment]
Yep.
