### ISSUE TITLE
some expected names not coming up in recommended mentions?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2606]
Love the new autosuggestion/complete of mentions and hashtags on Talk. I'm not sure if this is a bug or not, but I was surprised that when I wrote this, zookeeper wasn't suggested which seemed odd. Thought I'd mention it @parrish - feel free to close/make will not fix

<img width="1060" alt="screen shot 2016-05-18 at 10 11 09 am" src="https://cloud.githubusercontent.com/assets/753325/15345401/2bffe68a-1ce1-11e6-8366-54bc5c6178a5.png">

<img width="1082" alt="screen shot 2016-05-18 at 10 10 06 am" src="https://cloud.githubusercontent.com/assets/753325/15345413/3e4a81a6-1ce1-11e6-8c85-0af01f9678df.png">

**Comment by parrish** [comment]
Thanks!

I'll look into this.  The way it works (from #2580), is that it finds users from

> 1. Frequently mentioned users
> 2. Frequently messaged users
> 3. Group names (e.g. moderator, researcher, admin)
> 4. All users

Unfortunately, the "All users" results aren't ordered by anything right now -- it's a quirky database performance issue.  That's most likely the culprit, so I'll keep working on it.

**Comment by parrish** [comment]
This will probably be improved by zooniverse/Talk-Api@bf6c3d6

**Comment by parrish** [comment]
Results should be improved now.
