### ISSUE TITLE
Usability problems with removing drawn boxes in a drawing task [User reported from Computer Vision: Serengeti]

### ISSUE THREAD

**Issue by inaspin** [zooniverse/Panoptes-Front-End#2607]
I am noticing that the "X" function to remove the box placed around the animal is getting in the way - mostly with the ostriches, and particularly those that are further away from the camera. Any chance of getting it moved so it appears nearer the centre of the top line, or at the bottom RH corner where feet are likely to be obscured anyway by the ground cover?

Hope I did this right!    This refers originally to Subject 1983499

**Comment by alexbfree** [comment]
Originally reported on Talk https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/talk/115/54036?comment=107388&page=1

Thanks for reporting this @inaspin !

**Comment by srallen** [comment]
@wgranger this is related to the open PR for moving the drawing mark delete button.

**Comment by wgranger** [comment]
Closed with #2816
