### ISSUE TITLE
Most popular hastags repeating with duplicates on the sidebar

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2608]
@parrish looks like something changed on the sorting of the hashtags - now duplicates are showing on each projects popular hashtag bar:

edgeofswisscheese and swisscheese are duplicated on Planet Four: Terrains

<img width="295" alt="screen shot 2016-05-18 at 2 03 43 pm" src="https://cloud.githubusercontent.com/assets/753325/15348985/9cfea89c-1d01-11e6-9c40-5cdb8d5848c3.png">

Comet Hunters tail and overlap shows up a few times

<img width="324" alt="screen shot 2016-05-18 at 2 02 19 pm" src="https://cloud.githubusercontent.com/assets/753325/15348982/9594f962-1d01-11e6-898b-b1dc6619ac7e.png">

**Comment by parrish** [comment]
Will verify after deploy is out

**Comment by parrish** [comment]
It's fixed now.

**Comment by mschwamb** [comment]
Looks good to me - thanks @parrish
