### ISSUE TITLE
Find a way to improve image padding on project pages without breaking emoji

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2609]
This is mainly a note to self - but if anyone else wants to jump in feel free.

https://github.com/zooniverse/Panoptes-Front-End/pull/2374 as well as its main goal of white backgrounds, introduced a slight tweak to add more padding around images, improving readability

This had to be reverted because it had a side effect on emoji - see https://github.com/zooniverse/Panoptes-Front-End/pull/2389

Ideally we need to attach a class or something to emoji, so that they can remain unaffected but other images still get the benefit of this extra padding to enhance readability.

Low, low priority!

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
