### ISSUE TITLE
Warn about Deleting Annotations on Back button

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#2611]
It can be unclear to the user that once the back button is hit, the annotations for the current task will be lost. This is especially surprising in back-to-back drawing tasks, when I user goes back to adjust a mark from a previous task, only to loose their current annotations.

Possible Solutions:
- Allow project builders to completely disable/remove the Back button from the Classify page.
- Warn users that pressing the back button will delete their current annotation(s). Maybe something like [this](http://codepen.io/simensta/pres/0528889d386044c10b14bd25b4c3b820)?

**Comment by mschwamb** [comment]
@simensta I'd suggest changing the wording., especially if this wording/text shows on non-drawing projects as well.  I don't think volunteers know what is meant by annotations are. I think that's jargon the Zooniverse and research teams use, but isn't really known much outside of that. 

I'd suggest 'Going back will delete your work for the current task' or something along those lines

**Comment by eatyourgreens** [comment]
How about something like "Going back will clear your answers for this question."? Just in case 'task' isn't clear to the volunteers either.

**Comment by mschwamb** [comment]
I really like your text @eatyourgreens except for the word 'question'. Not all tasks in the workflow are questions sometimes they are directives like 'mark all the galaxy's bar'  I think 'task' covers  all scenarios, but likely other word choices too.

I'll have no complaints with whatever you and @simensta iterate and decide upon. Thanks for considering my opinion.

**Comment by eatyourgreens** [comment]
I'm happy with either version too, so whichever @simensta thinks is best. If volunteers do have trouble understanding the text, it's an easy thing to change.

**Comment by simensta** [comment]
@mschwamb, good point. I am thinking a combination of the suggestions above: "Going back will clear your work for the current task." I will update the PR momentarily.

**Comment by mschwamb** [comment]
@simensta I think that works well and is very clear.
