### ISSUE TITLE
Getting incorrect keyword suggestions in Western Shield subject comments

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2612]
When I get to comment on a subject directly from the classification, it suggests me wrong keywords for hashtag - they come from different project(s), not from Western Shield (for example red_duiker, blue_ford etc. but it doesn't suggest any keyword from Western Shield). When I enter a discussion from the Talk it suggests them correctly. I can make screenshots.

**Comment by mschwamb** [comment]
@parrish I just noticed the same thing but not from coming from then classification interface. It's the subject pages. If you're anywhere else you get the correct suggestions but not on the subject page itself. I tried from the classification interface and coming to a subject page from being in Talk first.

If you're in any discussion thread or note thread the hashtag suggestions are correct.  Screenshots below 

P4T subject page:

<img width="813" alt="screen shot 2016-05-19 at 12 41 21 pm" src="https://cloud.githubusercontent.com/assets/753325/15382754/aee5f0a6-1dbf-11e6-81ac-d4b89a66fa68.png">

<img width="857" alt="screen shot 2016-05-19 at 12 42 43 pm" src="https://cloud.githubusercontent.com/assets/753325/15382788/ea4a4ff2-1dbf-11e6-8625-ddc4baea2072.png">

Talk notes thread:

<img width="1138" alt="screen shot 2016-05-19 at 12 42 56 pm" src="https://cloud.githubusercontent.com/assets/753325/15382765/bd9913f8-1dbf-11e6-9ad9-4ff904fb6622.png">'

<img width="818" alt="screen shot 2016-05-19 at 12 42 03 pm" src="https://cloud.githubusercontent.com/assets/753325/15382790/f133a5b6-1dbf-11e6-8c5c-c9f3698536d9.png">

**Comment by parrish** [comment]
Bug fix on the way.

**Comment by mschwamb** [comment]
Thanks @parrish

**Comment by yshish** [comment]
Thanks @parrish  The suggestions are working now and it does suggest keywords for the correct project, but I'm not sure whether it is supposed to work the way it is working..

As for the Western Shield project, when I start typing **#grey** (for "grey_kangaroo" keyword) it suggests me **#joey** on the first position and the one I am typing is listed under it. Why is it so? Shouldn't it rather offer me the one I am actually typing on the first position and then other ones, like "joey" which is often used together with that grey_kangaroo tag since "joey" is the word used for kangaroo and wallaby infants.

(The image I tested that on wasn't actually showing any kangaroos but birds so it couldn't even suggest joey based on someone else's tags.)

Screenshot:
![](https://lh3.googleusercontent.com/-W9WjnY0OlgY/V0GybZbH8YI/AAAAAAAAI7E/MSshjqaZ4UM7iApVOwEUSXq790TRuGiSQCCo/s0/ysh_2016-05-22_15-09-28.png)

**Comment by yshish** [comment]
When typing **#brush-ta** for "brush-tailed_possum", it suggests me **bird** instead. It changes for the correct keyword after typing one more letter - i. And I guess there will be much more cases where it behaves this odd way.

**Comment by parrish** [comment]
There's a threshold on "similarity" in the search that I can tune.  I'll play around with it and see if we can adjust it a bit.

**Comment by parrish** [comment]
I've tuned it a bit.  The ranking is ordered by input similarity x distinct usages.  I think the usage component may be slightly high still, but it seems a bit more reasonable:

![grey](https://cloud.githubusercontent.com/assets/122990/15479744/4fdebffe-20e7-11e6-821f-4a53df9d82ad.gif)

![brush](https://cloud.githubusercontent.com/assets/122990/15479748/54790d8a-20e7-11e6-9d1e-dbd9f2b387d9.gif)

Very frequently used tags still pop up when it may be somewhat counterintuitive.  Let me know if this seems better.

**Comment by yshish** [comment]
I am sorry I don't really understand why it offers me different words than I am actually typing. 

When I start typing "bru.." then it should offer me "brush-tailed" on the first position rather than "bird" - those tags have nothing in common but the first letter. They have never been used in the same post/thread (as far as I know - and I think I've read every single comment which have been posted there since the launch). Don't you think so? 

Not sure how to understand the 'similarity x distinct usages' thing.

Moreover, I have just received an image to classify (Western Shield) which I was commenting on before. There was no hashtag yet and I wanted to put it there. I used the 'edit' function and started typing *#fox* but it was only suggesting me *#blue_ford*, *#blue-ford*, *#ford_blue*... and other variations of these two words, but no fox. None of the suggested keywords come from the Western Shield project either.

I am confused now what your intentions about the keyword suggestions were. Maybe I have just misunderstood its purpose but I am not very happy with the current function as it seems to be suggesting keywords which have nothing in common with the subject displayed on the image I am tagging 0:]

I would much more like if it was suggesting words I am actually typing and similar ones - like if I am typing *brush-tailed..* than it could offer me *#brush-tailed_possum* ass well as *#possum* and *#brush* *#tailed* *#possum* etc.

It would be cool if it was somehow preferring those which have been used in more cases (I consider them preferred to those which have been used few times only).

And one more suggestion: I would really appreciate if I could use the arrow-down key while typing to get into the offer with suggested keywords to choose from... It is not working for me at this moment (not sure whether it should have been) - I can only use mouse to get there.

**Comment by parrish** [comment]
The functionality we're going for is to find similar tags, rather than just matching the first characters.

Basically, we'd want '#green' to return '#green', '#blue-green', '#not-green', etc.

Also, we're returning results with the highest score, which is based on
  - how similar it is to other tags
    - e.g. '#green' is 100% similar to '#green', and about 55% similar to '#blue-green'
  - how many different users have used the tag (popularity)

This _should_ help form consensus between different variants like '#blue-green' vs '#blue_green' 

I'm still trying to adjust how those two factors combine to create the best set of results though.

I'll take a look at adding some keyboard controls for this too.

**Comment by yshish** [comment]
OK, I got it. Thanks for explainng.

**Comment by yshish** [comment]
I was just editing my post in WS by adding a hashtag. It was suggesting me "#possiblepulsars" and "#possible" after typing "#Brush-tailed_pos" instead of the "#Brush-tailed_possum". Definitely not from WS project. 

This happens only when editing.

Hope this is the correct place to report that, although the issue is closed.

**Comment by parrish** [comment]
I've got a fix in #2784.

It's probably best to create a new issue for things like this, it's less likely to get lost in the shuffle.
