### ISSUE TITLE
if you're on upload white list to have the front end note that on the subject upload page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2614]
I believe I'm now on the upload white list which means I have no cap on the subjects I can upload as I'm vetted by the Zooniverse team and have had to have my subject limit cap upped for legitimate reasons several times. Currently it still says in the subject set uploader that I have a limit of 50,000 subjects. It would be good, if the front end could check if someone was on the white list and then not mention the cap. 

@camallen please correct if I'm wrong on any of this.

**Comment by camallen** [comment]
Sounds right - would you like to modify the code [here](https://github.com/zooniverse/Panoptes-Front-End/blob/fe4df3ca7b1186b82e2286f75f77f0c865872ff6/app/pages/lab/subject-set.cjsx#L134) to fix it? Perhaps something like, using the `upload_whitelist` attribute of the user as a switch on the message:
``` javascript
 "allowance of " + (if user.upload_whitelist then 'Unlimited' else user.max_subjects) + ". Your uploaded subject count is the tally of all subjects (including those deleted) that your account has uploaded through the project builder or Zooniverse api."
```

**Comment by mschwamb** [comment]
@camallen theoretically yes if it's just copying and past the ruby/javascript/coffeescript? in the parenthesis and adding it in with a "+" to the string. I'm not setup to run a version of panoptes so I can't actually run a version of panoptes locally. Pretty much small edits mainly text I restrict myself to. This seems straightforward enough that if you're happy with that I'll make your recommended change as a PR.

**Comment by camallen** [comment]
You can make code and text modifications and test them on your computer. 

Running `npm start` from the front end repo will launch the app and it'll run against the staging server by default (no need to run panoptes). 

See https://github.com/zooniverse/Panoptes-Front-End/blob/master/README.md#development for details

**Comment by mschwamb** [comment]
Thanks @camallen . I'll try when I have a moment.
