### ISSUE TITLE
Project Editor mysteriously completely fails with no warning.

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2623]
@brian-c @alexbfree @amyrebecca do you have any idea what's going on here? Basically the project builder workflow page just completely disappeared. They've tried creating new workflows but get no tools.

![screen shot 2016-05-20 at 10 52 43](https://cloud.githubusercontent.com/assets/6217406/15424177/1d4af1d6-1e79-11e6-836d-d2868752877a.png)

**Comment by brian-c** [comment]
Please add brian-c as a collaborator.

**Comment by brian-c** [comment]
Not sure if this made it back: "Small Rodent" is probably missing from the characteristics CSV.

**Comment by srallen** [comment]
@mcbouslog I think this is related to #2686, so I'll assign this to you.

**Comment by aliburchard** [comment]
I am so excited about #2686!

**Comment by aliburchard** [comment]
I'm going to say that this is closed for now with @mcbouslog's error reporting!
