### ISSUE TITLE
after updates to about pages blue owner text on team page is unreadable under the grey

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2626]
The new about project page and tabs look great. I noticed on the team page that the light blue on the light grey is impossible to read on the owner tag. Maybe the color can be darkened a bit? cc @wgranger

<img width="1127" alt="screen shot 2016-05-21 at 7 34 29 am" src="https://cloud.githubusercontent.com/assets/753325/15444958/018250d2-1f2a-11e6-9ed6-d1ef327df26b.png">

**Comment by jwbmartin** [comment]
Changing it now with @srallen
