### ISSUE TITLE
Visualize workflow truncates first letter of task names

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2628]
When you look at a visualization of a workflow, you see the task names at the top of each box, minus the first letter of the workflow name. For example, this workflow has task names 'badimage', 'snow', and 'flowers'.

![workflow_1-1](https://cloud.githubusercontent.com/assets/1066340/15482646/c72a1a42-20fe-11e6-90e2-b0c65c246c8a.png)

BTW, I **love** the workflow visualizer. Thanks so much!

**Comment by CKrawczyk** [comment]
Ah, I think I know what is causing this.  Could you add me as a collaborator (zooniverse ID cmk24) so I can debug.

**Comment by mkosmala** [comment]
@CKrawczyk Done

**Comment by CKrawczyk** [comment]
For PFE created projects the task keys are "T1", "T2", etc... so I just chopped off the first letter to get the task number.  Now that I know this is not always the case, the PR above removes this truncation and shows the full task key.

**Comment by mkosmala** [comment]
Sounds like a good solution. But it's not live yet? I still see truncated names...
