### ISSUE TITLE
Add ability to reshuffle the tutorial cards

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2629]
My collaborator just misunderstood how to replace an image in the tutorial and in the project we're building . He hit the x thinking that would delete the image (re-reading the help text I can see where he might have gotten confused). Since it was the 3rd step of out 7, I now need to add a new step and move all the tutorial text down by one by copying and pasting and then reupload the images. It would be nice for situations like this or when you're in development that you could move the different cards in the tutorial into a different order.

**Comment by eatyourgreens** [comment]
I'm not 100% certain but I think you can drag the tutorial steps up and down to change the order.

**Comment by eatyourgreens** [comment]
On second thoughts, I might be confusing the tutorial and the field guide. It would be good if the UI were consistent here.

**Comment by mschwamb** [comment]
Yeah there's no drag and sort in the tutorial at least not in Firefox. I don't have access tom the field guide, but it would be a good feature to add.

**Comment by srallen** [comment]
I'll take a look at what the field guide has implemented and if it looks quick to do, I'll try to get a PR in soon.
