### ISSUE TITLE
View current manifest or subject list for given subject set

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#263]
After uploading a subject set, there doesn't seem to be any way to view or explore the uploaded manifest. I think this is really important, especially for project builders who will be appending to the a given subject set over time. They need to be able to check the manifest for, say, accidental duplication, among other things.

**Comment by vrooje** [comment]
Totally agreed! Manifest with, say, links to images for subjects would be
really helpful.

**Comment by twhyntie** [comment]
:+1: Assuming you append to a subject set by uploading a new manifest listing the new subjects, this is going to be pretty important to avoid book-keeping headaches.

**Comment by vrooje** [comment]
Is this the issue transferred from Zooniverse/Panoptes/#777 ?

If so it might be useful to know that the manifest itself apparently doesn't get saved during a subject upload. That is, a subject db that a manifest can be pulled from obviously gets saved somewhere, but the document you upload doesn't. Panoptes uses it to associate your subjects with images and metadata, and ignores any rows in the manifest csv that it doesn't have images for. @edpaget explained this to me the other day and it was really helpful; for example, I can upload a large subject set in batches *without* having to create a sub-manifest each time (I just upload the whole thing).

This does make it more important to have a downloadable manifest of *actual* subjects used, though.

**Comment by aliburchard** [comment]
Whoa, I didn't realize that the manifest didn't save. What happens (@edpaget) then if you have a manifest of, say, 100 images. You upload 1-20 in one go, and then come back and upload 20-100 the second time. You've now uploaded subject #20 twice, but it only has one record on the manifest.  Is it duplicated in the subject set?

And yes, I think it's really critical that the project builders can see a record of uploaded subjects so that they can effectively manage (and trouble shoot) their data. @brian-c can we add some sort of "view/check  uploaded subjects" functionality into the subject uploader?

**Comment by edpaget** [comment]
The manifest never touches the API. If you create a subject twice we don't have a way keep track of that. I suppose we could hash images and use that to deduplicate, but that would be a super low priority feature for me.

**Comment by camallen** [comment]
I agree with @edpaget here. I think a better UI for uploading subjects with some visual feedback about what is getting uploaded would alleviate the issue. 

Long term adding a digest / hash to compare a manifest (with the digest) and uploaded subject media could be super useful for the UI.

**Comment by brian-c** [comment]
Depends on zooniverse/Panoptes#809.

**Comment by chrissnyder** [comment]
Looks like work was done on this issue. @aliburchard Closing, but reopen if you disagree.
