### ISSUE TITLE
Did something change that caused all tutorials to be checkmarked on projects in each workflow?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2630]
I noticed an oddity. I have a project in development and I had explicitly set which tutorial and then today when making edits to the help window I saw that on both workflows both tutorial sections had both tutorial choices selected. Odd thing is that in the classification interfaces the correct tutorials were showing. 

The new thing I noticed is that there is now an option to select a default workflow in the project builder. Not sure if this important or not, but thought I should mention it.

**Comment by srallen** [comment]
@mschwamb could you send a screenshot and let me know the workflow and tutorial ids (or just make sure those are visible in the screenshot)? This might just be a UI bug.

The default workflow option got merged in with #2622

**Comment by mschwamb** [comment]
I haven't looked at this workflow in about a week as I was waiting for subject images. I didn't take a screenshot when both checkmarks are selected (sorry!), but here's the workflow ids and tutorial ids

Tutorial 39 and 44 and workflows 1818 and 1833  if that helps . I have checked the correct ones before I wrote the ticket up.

**Comment by srallen** [comment]
Yes, that helps. Thanks. I can try to see if I can replicate what you described.

**Comment by mschwamb** [comment]
It might be a weird quirk if you already have two workflows and more than one tutorial when the feature got rolled out, so feel free to close whenever if you can't replicate

**Comment by srallen** [comment]
I wasn't able to replicate this, so I'll close, but do reopen if you see any more oddities.
