### ISSUE TITLE
Workflow visualizations missing for Season Spotter Image Marking

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2632]
For Season Spotter Questions, I can get nice visualizations from the Project Builder. But for Season Spotter Image Marking, I just get a blank page: 
https://www.zooniverse.org/lab/348/workflow/177/visualize

**Comment by CKrawczyk** [comment]
If you could add me as a collaborator for this project (zooniverse ID cmk24) I will see what is going on.

**Comment by mkosmala** [comment]
@CKrawczyk Done

**Comment by CKrawczyk** [comment]
One of the drawing tool choices does not have `details` defined, typically this is an empty array if there are no sub-tasks.  The PR should fix this issue.
