### ISSUE TITLE
project builder broken - build a new workflow, your workflow doesn't execute skips straight to the classification summary

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2635]
I set up a new  inactive workflow in Comet Hunters to start copying over what I made in a separate demo project builder website in prep for launching it live next week or so. I have the exact same steps in as the demo site that works and now I get straight to the end of the summary. It doesn't show my first question.A first task is set in the project builder. This is workflow 1949 in project 724

Here's what I get when I go to test the workflow
<img width="1189" alt="screen shot 2016-05-26 at 10 47 31 am" src="https://cloud.githubusercontent.com/assets/753325/15562197/c7449bb4-232f-11e6-9c41-12d8fffa7621.png">

Looking at the comment for the latest PR merged @brian-c and @eatyourgreens  maybe removing the default task  caused this?

I saw someone else reported this on Zooniverse Talk as well so I think there's a bug that was just recently introduced

**Comment by mschwamb** [comment]
Would be helpful if I included the Zooniverse Talk post as well. Here you go: https://www.zooniverse.org/talk/18/56806?comment=112495

**Comment by eatyourgreens** [comment]
Looks like the first task in the workflow isn't being set automatically. I tried creating a new workflow and I had to set the first task from the drop down menu by hand. 

There should be a fix for this by the end of today.

**Comment by mschwamb** [comment]
@eatyourgreens it looks like that's set for me or is it that it looks like it is but it's really not in the UI?
<img width="1159" alt="screen shot 2016-05-26 at 5 48 35 pm" src="https://cloud.githubusercontent.com/assets/753325/15570782/570b9bf0-236a-11e6-9421-6a1807da81c1.png">

**Comment by mschwamb** [comment]
Okay, now I get what you say.  if I select the other question and then reselected the first question 'Review the two observations' under First task it works for me too. Thanks for looking into this @eatyourgreens

**Comment by eatyourgreens** [comment]
@mschwamb yeah, that's the bug. It looks like it's selected, but it isn't really. Hence the start of the workflow isn't wired up in Coleman's visualiser. 

If I can figure out where that first task gets set, I'll get a fix out.

**Comment by brian-c** [comment]
This should be handled here:

https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/workflow.cjsx#L491-L492

Not sure why that isn't doing it. Will also investigate.

**Comment by eatyourgreens** [comment]
@brian-c in my test workflow, `workflow.first_task` was set to `init` but the key on my first task was `T0`. Does the default value need to be changed for new workflows?

**Comment by brian-c** [comment]
Yes, good catch. That PR will fix it.
