### ISSUE TITLE
Gravity Spy Geordi Integration Tasks for Will

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2646]
- [x] Implement missing events/review events that might need update per Syracuse reqs (see green/yellow [here](https://docs.google.com/document/d/1TTNgzAQbhYH9kn3mqcy0p_UBRIzFG3CgPxcXpTVv3Nk/edit#) ) 
- [x] Remove all non-Gravity Spy related events from the geordi-integration branch & PR - but keep it in another branch
- [x] Ensure we always pass a projectToken. Use "zooHome" or "zooTalk" or similar for areas that have no project slug
- [x] Update Geordi client constructor calls to not set project
- [x] Add methods to Geordi client to setProjectToken and setWorkflowId and call these where appropriate (respectively especially where changing project, loading subject in classifier, etc) (optionally, using Jim's refactor idea)
- [x] Add a limit so that ALL PFE Geordi logging only happens for Gravity Spy Project ID. 
- [x] Add integration tests to Geordi Client per Sarah's suggestion.
- [x] Address any remaining comments in PR that affect Events relating to Gravity Spy

**Comment by wgranger** [comment]
Note: logging happens for the Gravity Spy Project ID, but it also happens for the more general zooTalk and zooHome for all users.
