### ISSUE TITLE
Post-Gravity Spy Geordi Integration Tasks for Alex

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2648]
Not to be done until after #2646 and #2647 
- [ ] Geordi Server to store workflow ID as its own column. Then notify Will
- [ ] Create ticket to move PFE's Geordi integration code to panoptes-javascript-client
- [ ] Create ticket to create project preferences for Geordi.
- [ ] Create ticket and discuss with ops about Geordi periodic archiving approach/CSV exports per project for researchers.
- [ ] Conduct final QA against requirements (Full list not just gravity spy) once everything else is done and prior to merge.

**Comment by srallen** [comment]
Closing since I have no idea what still needs to be done here and we can open separate new issues if we find work that needs to be done.
