### ISSUE TITLE
Why is the Subject Image button in Talk, but not in Classify?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2654]
In Talk, there's a Subject Image button under the subject that allows volunteers to see the subject at full size. But this button doesn't exist in the Classify interface. Is this an intentional decision? We have volunteers longing to have the Subject Image button also appear in the Classify interface, and I don't know what to tell them. Can it be added there?

![subjectimagebutton](https://cloud.githubusercontent.com/assets/1066340/15746277/d7c245f8-28a3-11e6-812c-65947c230d13.png)

**Comment by mschwamb** [comment]
For my projects,  giving volunteers the subject image in a larger form in essence giving zoom would give another variable I'd have to try to control for in analysis, but some volunteers on my projects had asked for an ability to zoom in after they reviewed it on Talk  and the larger subject view button was the solution that Alex W decided to implement.

**Comment by srallen** [comment]
This is intentional design.

**Comment by mkosmala** [comment]
That's fine, but I will point out it has made some of my volunteers upset.
