### ISSUE TITLE
can make an inactive workflow show up if you click classify if you have  check box ticked in workflow editor for default workflow

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2658]
While starting the process to turn on the HSC Comet Hunters workflow I came across this. I checked the box to make it the default workflow, but the workflow is still inactive and if you're not logged in and hit classify it took me this non-active workflow. 

Naively I thought that because the workflow was inactive the website would automatically switch to making another active workflow default when you hit classify. I think project owners will forget to unclick this checkmark if they have multiple workflows and switch the default workflow to inactive in the visablity page

**Comment by brian-c** [comment]
This is probably relevant to the workflow saved in the user's prefs too. Will have a look today.
