### ISSUE TITLE
Suggestion: The "get started" project list on zooniverse.org at the bottom could be dynamic

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2659]
I just noticed that the "get started" section at the bottom seems to never change, I assume it's hard coded.

![screenshot 2016-06-03 10 32 14](https://cloud.githubusercontent.com/assets/1473244/15774887/b25d28ea-2976-11e6-95bd-44a8b16d4a8b.png)

Perhaps we could take advantage of what we now have in the new project page, and have it show four projects from the "most in need of help" or "most recently launched" projects (or maybe 2 of each).

At least one of the current projects linked to is already out of data, so not a great place for people to start.

**Comment by srallen** [comment]
New home page design has been implemented. The new slideshow will be dynamic at a later point, but it's not a high priority.
