### ISSUE TITLE
removing the white space from project titles when creating the project url

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#266]
Currently the url address made for a created project keeps the white space in it  which causes issues when sharing the url. White space should be removed  

example:

Planet Four: CTX project I created has a url of:

http://demo.zooniverse.org/panoptes-front-end/#/projects/mschwamb/Planet Four: CTX

but you can't click on the line and get there because of the spaces.

**Comment by brian-c** [comment]
URLs discussed in #197.
