### ISSUE TITLE
Move tutorial from experimental tool to public tool

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#2661]
After review @chrislintott and I decided it works well and should be offered to everyone.

**Comment by mrniaboc** [comment]
@zooniverse/developers Who's up for pushing this through?

**Comment by aliburchard** [comment]
Yay! This is so ready for prime time.

**Comment by CKrawczyk** [comment]
+1 I have a summer student building some projects and this would be helpful
