### ISSUE TITLE
Move field guide from experimental tool to public tool

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#2662]
After review @chrislintott and I decided it works well and should be offered to everyone.

**Comment by mrniaboc** [comment]
@zooniverse/developers who's up for pushing this through?

**Comment by aliburchard** [comment]
yay! super, super excited about this.

**Comment by srallen** [comment]
Gonna reassign this to me. #2769 itself looks good, but there were a couple of related field guide issues I noticed that probably should be addressed before it's made public.

**Comment by srallen** [comment]
#2704 is still left to do and assigned to @mcbouslog
