### ISSUE TITLE
World Wide Telescope Adjustment

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#2676]
- **Adjust true center of cropped image**: Cropped chart is displayed slightly off center on WWT because of discrepancy between coordinate center and chart center.

- **Issue with axis values**: Classification will crash if axis value is placed inside chart rather than outside due to how the `filterBounds` function determines axes. Instructions should be given to the user/classifier to place annotation outside the chart. A try/catch should be added to handle errors. 

- **Account for Axes with Inconsistent Values**: Some axes list RA in hours, minutes, and seconds for one value, but not for all.

**Comment by trouille** [comment]
We may need to include the ability to use epoch (1950 or 2000) to get the correct placement of the image (i.e., this would be added to the question about marking the units and would need to be included in the code to tell the system which epoch the values are from):

see http://burro.case.edu/Academics/Astr306/Coords/coords.html
