### ISSUE TITLE
stats page now only shows one day of talk comments and classification numbers - no longer scrollable plot

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2678]
Tried this on firefox and chrome on mac

<img width="1116" alt="screen shot 2016-06-09 at 2 04 38 am" src="https://cloud.githubusercontent.com/assets/753325/15929195/40af4226-2de7-11e6-8c75-af0f2787e8b3.png">

See this on Comet Hunters and Planet Four: Terrains

**Comment by CKrawczyk** [comment]
Something odd happened to the stats API, @camallen is looking into it.

**Comment by srallen** [comment]
@CKrawczyk can this close?

**Comment by CKrawczyk** [comment]
Yep, this can close now.
