### ISSUE TITLE
a separate text box to input text for what you want a workflow's button on the front page to say

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#268]
Really minor, but I found it very confusing that the name of the workflow I created was the text that showed up on the button on the front page to enter the classification interface. 

I'd want the button to be 'get started' or 'explore now' but it would be nice to have something more descriptive under the workflow title in the workflow editor/interface builder especially if you have more than one work flow. I can imagine other science teams wanting to have shorthand to label their workflows if they have more than one but still have 'Mark Craters' as the button on the front page.

**Comment by mschwamb** [comment]
Looks like that might have been from a previous version of the demo site link I've gotten when I had started the build. Now it always says 'Get Started' if there's one workflow. It would be nice to customize that.

**Comment by mkosmala** [comment]
You will be able to specify whether all your workflows are combined into one button ("Get started!") or whether you allow users to choose workflows. (In which case, I agree that it would be nice to have separate button text.) See #189

**Comment by mschwamb** [comment]
Worth pointing out that the  front pages for the 30 current projects, have different text for that  the button to enter the classify interface  so I think it would be nice to give the ability that all the projects made with this don't have to be exactly the same if you have 1 workflow

**Comment by mschwamb** [comment]
Probably a moot point now, so closing since I opened it. People can reopen if they feel strongly about it.
