### ISSUE TITLE
New survey task CSV uploading behavior

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#2686]
New behavior should go something like:

- Use `type="file"` inputs to **select** (not automatically apply) choices, characteristics, confusions, and questions CSVs.
- Check for CSV-mismatch errors, e.g.:
  - Choice "Bear" has no line in the characteristics file.
  - No choice found for characteristic (or confusion, or question) for "Grizzly".
- Add an Upload button, disabled until at least choices and characteristics are selected.
- Display a warning if confusions or questions are not selected (these are optional).
- Clicking the Upload button:
  1. Clears out all existing workflow data except media
  2. Applys new data from the four CSVs

**Comment by mcbouslog** [comment]
mentioning @trouille

**Comment by mcbouslog** [comment]
so this is far from functioning still, but noting [staged branch here](https://survey-task-editor.pfe-preview.zooniverse.org/) for reference, will contact Ali and Laura via Slack for explanation and general concept in mind.

**Comment by mcbouslog** [comment]
<img width="513" alt="screen shot 2016-07-29 at 7 50 25 am" src="https://cloud.githubusercontent.com/assets/12118751/17248605/436a44f6-5561-11e6-91a7-e1087549bce4.png">
