### ISSUE TITLE
Automatic deploys usually fail

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#2688]
This has been fairly consistent since the webpack merge. Both install and build take a bit longer now, so I imagine Jenkins is timing out.

**Comment by astopy** [comment]
From the build logs it looks more like the deploy script is running out of memory and getting killed by the OS. Whether or not it has enough memory to run will depend on what else Jenkins happens to be doing at the time. Is there anything we can do to reduce its memory usage?

**Comment by astopy** [comment]
This should be fixed now.
