### ISSUE TITLE
Place/Ability to Create a Spotter's Guide

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#269]
The project I'm building refers to terms most people don't know. We'd want to have a Spotter's Guide Section somewhere so people can many examples of the features of Mars that we want them to identify more than we'd want in a help window.

The ability to have a  Spotters guide where you click a button and there could be a series of examples (like Planet Hunters 2 help button does) or Space Warps I think would be really useful for classifiers and science teams. 

If that's not possible, having a place to put that as a separate page with a tab on the navigation bar would be extremely useful. Right now the only page we could stick this info on is the FAQ editor, but  the content isn't really an FAQ  it would be a series of images and  and 2-3 word description.

**Comment by mkosmala** [comment]
I think the capability of having external sites that can have a 'tab' in the main interface would be useful in many cases. We would like, for example, to be able to link to a blog.

**Comment by chrissnyder** [comment]
We just added the capability to link to external sites. I imagine generic static pages will come at some point.

**Comment by mschwamb** [comment]
We  don't want to make a spotters guide on a separate website. The only workable option for the P4:Terrains for that  would to have a static spotters guide website on P4 which would require help from the development team.

would it be possible to add another page like the science and results tabs with the same markup interface?

**Comment by vrooje** [comment]
I agree the Spotter's Guide functionality will be enormously useful in the future.

For now perhaps the FAQ page could substitute?

**Comment by mschwamb** [comment]
closing since it's  being worked in #1768
