### ISSUE TITLE
When you upload an account profile avatar you have to reload the page to make it appear

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2691]
Happened with one of the Comet Hunters science team when they added an image as their avatar. Uploading was successful but it automatically refresh, so it looked like the image didn't upload. The person doing the photo uploading thought something had gone wrong.  Doing a browser refresh showed that the image had been uploaded. 

Related to #2317

**Comment by camallen** [comment]
> Uploading was successful but it automatically refresh

I assume this was meant to say didn't automatically refresh...This is a know issue on our media resource uploads and it's to do with the way we enable this via our storage provide int he API. A page refresh should get the correct resource, alternatively a request for the actual media resource would return the correct get media resource URL.

**Comment by mschwamb** [comment]
yep meant to say it didn't automatically refresh and show. So it looked like to the person that the upload had failed, and they came to show me. 

I knew what to do and told them to refresh the page, but to most people this looks like there is a bug/something is broken when the image they upload for the first time doesn't show in the box where they expect it to

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
