### ISSUE TITLE
Have tutorial reset scroll bar when you move on to the next slide in the tutorial

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2698]
I'm noticing this on the new Notes from Nature - The images  and text are very long that I have to scroll on my 13-inch screen but when I advance to the next stage of the tutorial I'm still at the bottom of tutorial scroll bar and need to scroll all the way up start reading and scroll down. Because my OS/browser hides the scroll bar for the first time it wasn't clear I wasn't at the top of the tutorial window

This was in latest version of mac firefox.  screen capture below:

![tutorial_scroll](https://cloud.githubusercontent.com/assets/753325/16128350/fe216914-3432-11e6-9cf0-01143ecd4790.gif)

**Comment by srallen** [comment]
Closed by #2703
