### ISSUE TITLE
Slightly scary authorization message when you log into new Notes from Nature for the first time

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2699]
I got the newsletter so I checked it out. When I logged in for the first time  fro the landing page, I put in my username and password, I got this slightly scary authorization message. Had I not known that y'all are awesome, I'd hit deny like I do on websites where I don't know what's going on and why it wants my info. You might want to make this message simpler. I'm not sure other people will understand what's meant by Public, Classification, User in this context

<img width="1114" alt="screen shot 2016-06-17 at 2 44 51 am" src="https://cloud.githubusercontent.com/assets/753325/16129267/c1306164-3436-11e6-844a-e9d4faf1d796.png">

**Comment by eatyourgreens** [comment]
Pinging @camallen He can sort this out.

**Comment by parrish** [comment]
Fixed now
