### ISSUE TITLE
code-like synatx mentioning 'webpack' flashes on the browser window when I log into new Notes from Nature

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2700]
This might be because of my slower connection to the East Coast AWS farm: When I log into the new Notes from Nature using the Login link on the landing page when I enter my username and password this white screen with some code-like syntax mentioning 'webpack' shows up for a brief moment. i thought I'd let you know since I don't know what it is and if it is exposing anything. Screen grab below. I'm using latest version of Firefox on mac

<img width="1122" alt="screen shot 2016-06-17 at 2 45 46 am" src="https://cloud.githubusercontent.com/assets/753325/16129441/56bb0752-3437-11e6-9a20-8fe01139b6e4.png">

**Comment by parrish** [comment]
This was fixed by zooniverse/notes-from-nature-landing#48
