### ISSUE TITLE
remove automatically generated field guide option

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2704]
When you enable field guide on a project, it generates an entry (and thus displays by default on every project page). Can we either 1) turn off the default entry or 2) enable users to "hide" the field guide until they want it displayed? (This second option is especially important for existing projects that are now adding field guides and don't want the field guides "live" until they are finished.)

**Comment by srallen** [comment]
@mcbouslog I'd like this to be done before #2769 is merged. Could you take a look when you're back?
