### ISSUE TITLE
Multiple images: default view

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#2708]
In the space warps demo https://www.zooniverse.org/lab/1434/workflow/960, we have multiple images and we let the user choose between flip book or separate image views.
When a new subject is loaded, we would like the default view to be the separate images rather than the flipbook - is it possible to add an option for builders to set which will be the default view?
If not, would someone be able to change this for SW?
Many thanks
Aprajita.

**Comment by eatyourgreens** [comment]
@aprajita Hi Aprajita, you can set the default view, in the project builder page for that workflow, using the drop-down menu under 'Multi-image options'. There should be an option for separate images.

**Comment by aprajita** [comment]
Thanks @eatyourgreens

Sorry, I wasn't clear in my original question. I've seen that option and have set it to let user decide between flipbook or multi-image, but what I was asking is whether the default view (i.e. the view when the users goes to a new subject) is the  multi-image view not the first frame of the sequence that is the delault in the "let the user choose" more. If I set this option to multi-image only then they aren't able to play the flipbook loop.

So I still want the feature of allow the user to choose but want the view when going to a new subject to be

![image](https://cloud.githubusercontent.com/assets/1917970/16227850/2d2986e4-37ab-11e6-91b5-f29614333403.png)

rather than
![image](https://cloud.githubusercontent.com/assets/1917970/16227863/3ece4a24-37ab-11e6-8f57-f8ddf637d35b.png)

- is implementing an option to set this in the workflow possible?

many thanks! aprajita.

**Comment by mrniaboc** [comment]
@eatyourgreens @brian-c I think this is something we should offer that would be fairly straight-forward to implement. Thoughts?

**Comment by srallen** [comment]
@aprajita did you want the side-by-side view to be default for all volunteers or only if a volunteer has selected that view for that volunteer?

**Comment by aprajita** [comment]
Default for all volunteers when they get a new subject but that they can
still choose the flip book mode if they wish.

Although I am not sure what the other option is, do you mean a volunteer
can say I always want to see side by side?
Thanks!

**Comment by srallen** [comment]
@aprajita the volunteer currently cannot set the side-by-side view as default, so we are asking for clarification if that is what your feature request is. The alternative is to have it be a project level setting or to leave as is.

**Comment by aprajita** [comment]
@srallen I hoped my posts on this thread communicate that we would like
volunteers to have the default view of side by side while retaining user
option to view the flip book mode.

I imagined this could be an additional option in the project builder where
the default view between side by side or flip book is selected by the
project team (not the volunteer) and the team can still select the option
to allow volunteers to toggle between the side-by-side and flip book modes.

I hope this clarifies the issue although I am not sure that I have.

**Comment by simoneduca** [comment]
Hi @aprajita, I'm about to start developing this and I'd like to make sure I've understood the requirement. So, you would like a new option for researchers to set the default subject view to multiple-image in the project builder - so that for any new subject served that the default view - _and_, at the same time, retaining the ability for volunteers to switch between multiple and single image view. Is that correct?
Also, I can't access the site at the url you gave in the first post of this thread. Mind sharing the correct one please?
Finally, I'm in Zootown, so feel free to pop in if I misunderstood your request.

**Comment by aprajita** [comment]
Hi @simoneduca 
thanks for looking into this. yes that sounds like what I meant.
i can add u as a collaborator if you send me your zooniverse ID
I'm on leave at the moment but may be in briefly this afternoon - i'll try to pop-by if i can
thanks!

**Comment by simoneduca** [comment]
Yes please, thanks. My username is "Simoneduca".

**Comment by eatyourgreens** [comment]
@simoneduca what we probably need here is to split the existing multi-image setting into two settings: 'default view' (flipbook or side-by-side) and 'enable switching' (true or false.) Then make sure that the changes are backward compatible so existing projects retain their settings.

**Comment by aprajita** [comment]
thank you @simoneduca & @eatyourgreens !
