### ISSUE TITLE
subject exports have duplicate subject_ids in different rows

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2709]
I'm working with GZBL data (project_id == 3) and the subject export has ~2x as many rows as there are subject_ids in the project. I think that's because I have several thousand subjects that are in multiple subject sets and multiple workflows, and the subject exporter is giving me one row per subject_id+workflow_id combination. Or per subject_id+subject_set_id combination; I can't tell which. Here's an excerpt from the subject export, sorted by subject_id (the unsorted row number is at the far left):
![screen shot 2016-06-20 at 5 47 16 pm](https://cloud.githubusercontent.com/assets/2357126/16214635/508f3972-370f-11e6-8cbf-68c69657e948.jpg)

The retired_in_workflow seems to have the info about all workflows in all rows, but the classifications_by_workflow isn't combining into a single list in the same way. This is not the intended behavior, correct?

**Comment by camallen** [comment]
This is just inconsistent reporting in the `retired_in_workflow` column. We report each subject link to the project subject_sets so this is why you are seeing multiple rows it should be uniq for subject_id : subject_set_id. 

You happy enough to have the `retired_in_workflow`report the correct workflow link here?

**Comment by vrooje** [comment]
Just to clarify, that would mean the `retired_in_workflow` column in the screenshot above would, for the above example where the subjects are retired in all workflows, be a duplicate of the `workflow_ids` column?

What I'd originally thought was that this should just be 2 rows, with the `workflow_ids`, `subject_set_id`, and `classifications_by_workflow` columns showing the combined info that's currently on separate rows. But thinking further that does potentially lose info about which subject_set_id was associated with the workflow, and that's why this is this way, right?

Sorry for thinking "out loud" here -- but, yes, if the `retired_in_workflow` column reflected only the ssid and workflow_id relevant to that row that would make it easier to combine these or keep them separate as needed. Thanks.

Is this documented anywhere yet on the project builder side @aliburchard ?

**Comment by camallen** [comment]
closing this here as it's a backend issue.
