### ISSUE TITLE
Talk side bar showing duplicate project names

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2711]
@parrish I just noticed this today

<img width="1076" alt="screen shot 2016-06-22 at 5 27 23 pm" src="https://cloud.githubusercontent.com/assets/753325/16261639/ea7ef654-389e-11e6-8e7d-3a32e99105d3.png">

**Comment by parrish** [comment]
Oh that's neat.  I'll take a look
