### ISSUE TITLE
Collections next button doesn't work anymore (can't peruse or advance through a collection)

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2713]
Getting the same issue in Firefox and Chrome if I try to hit the page 2 for a collection it doesn't advance to the new page. If I use the drop down menu I can move to page 2 and then the advance buttons work. 

Example: https://www.zooniverse.org/collections/mschwamb/requested-2016-hirise-targets
If you try and hit Next it doesn't work. 

@parrish is this something you can look at? This was fixed awhile back, not sure how it cropped up again

**Comment by parrish** [comment]
Not sure why this didn't close, but it was fixed by #2716

**Comment by alexbfree** [comment]
thanks @parrish , i think i meant to close it and forgot
