### ISSUE TITLE
Some of the next buttons on Talk not working anymore 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2715]
Something broke the next buttons on Talk in a few places. In the collection see 

Recents: https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/recents - The next button doesn't work 

Talk Search: https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/tags/spiders

Talk threads the next button is working

**Comment by mschwamb** [comment]
cc @parrish and @alexbfree  maybe related to #2712 and #2713

**Comment by alexbfree** [comment]
The reported is fixed, but I am reopening while we verify that our fix didn't break logging in Geordi for these clicks.

**Comment by alexbfree** [comment]
@wgranger see my comments in #2716 - any comments on what talk click data was supposed to be recorded?

**Comment by wgranger** [comment]
@alexbfree Concerning the `change-page` event, we are trying to capture whenever a user clicks to or selects another page. I think `first-page`, `next-page`, `previous-page`, `last-page` and `select-page` covered it all. This should be recorded regardless if in zooTalk or zooHome.

**Comment by alexbfree** [comment]
@wgranger : OK. For zooTalk we do not see `change-page` but we do see `talk-view` (with no additional data). See https://github.com/zooniverse/Panoptes-Front-End/pull/2716#issuecomment-228107096

Do you think this is a breakage/regression or just something we never fully implemented? If it's just something we never fully implemented, that's fine, we can close #2716 and fix it separately - but if there's a chance #2716 or another recent change broke it, we should fix it here.

I think it's probably just that we never implemented anything more than a basic `talk-view`. If you're not sure, let's go with that assumption - just thought I should check if you recalled anything about this.

**Comment by eatyourgreens** [comment]
@alexbfree `zooTalk` is posting `change-page` events. Here's an example I logged earlier today: https://github.com/zooniverse/Panoptes-Front-End/pull/2716#issuecomment-229336324

**Comment by alexbfree** [comment]
OK - now i understood your other comment @eatyourgreens i am piecing this together. As you saw, i had a screenshot where it was not coming through. Will re-test.

**Comment by alexbfree** [comment]
OK. Tests confirm this is now working. Closing ticket. Not sure why it wasn't working before but we are good now.
