### ISSUE TITLE
Can't log out or access profile -  Click on avatar and nothing happens

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2717]
Can click to log in but once logged in I can't log out nothing happens when I click the avatar. The account profile menu doesn't show up. Have checked in chrome and Firefox and get the same result

**Comment by mschwamb** [comment]
@alexbfree Geordi integrations seems to have broken this as well

**Comment by srallen** [comment]
Fixed by #2718
