### ISSUE TITLE
when you load the next page in the list collection have the brower autoscroll up 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2719]
Not sure if this is old or new due to the Geordi integration @alexbfree , but I think it might be new like the other issues I reported today.   If you advance through the list of collections (https://www.zooniverse.org/collections)  by selecting a page the scroll bar remains on the bottom and does reload to the top. At least in firefox it doesn't scroll back up

**Comment by srallen** [comment]
Related to #2762. Use [react-router-scroll](https://github.com/taion/react-router-scroll)

**Comment by alexbfree** [comment]
linking to #2852 and  #2868

**Comment by alexbfree** [comment]
Just confirming this is not related to Geordi integration. It's a general issue which we'll need to address in #2852

**Comment by mschwamb** [comment]
this looks to be fixed now so closing.
