### ISSUE TITLE
Link to project front page from project builder is broken

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2720]
The link to the front (public) page of a project from its "Project details" page in the project builder used to work, but today it doesn't seem to. It seems to be including all but the last character of the link to the project builder page itself in the link, i.e.:

https://www.zooniverse.org/lab/1050 
links to the project page
https://www.zooniverse.org/lab/105/projects/imperativespace/monitoring-waterholes

and

https://www.zooniverse.org/lab/4
links to
https://www.zooniverse.org/lab//projects/vrooje/kitteh-zoo

I thought this was inconsistent behavior not happening on every project until I realized it was only working on tabs I've had open for ages and haven't refreshed... so I think this must be recent.

**Comment by srallen** [comment]
I think I have an idea of what's going on. I'll take a look.
