### ISSUE TITLE
close metadata modal by pressing esc

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#2722]
The metadata modal should close when a user presses "esc". 
Reported in [Talk](https://www.zooniverse.org/projects/zooniverse/decoding-the-civil-war/talk/465/62194).

**Comment by brian-c** [comment]
I think we can just replace the `alert` with the one from `ModalFormDialog`. Will test tomorrow.

**Comment by simensta** [comment]
Sounds good. Thanks!
