### ISSUE TITLE
Missing Annotation Value in Exporter

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#2723]
Annotation column returns `"error":"task cannot be exported"` when requesting CSV from older project. This was apparent when requesting a classification and subject data export from an older project (Old Weather) that uses tools not found in the project builder.

**Comment by zwolf** [comment]
In addition to 'survey', there are a lot more non-standard tasks than I thought, especially in non-PFE projects.

**Comment by zwolf** [comment]
Issue moved to [zooniverse/Panoptes #1839](https://github.com/zooniverse/Panoptes/issues/1839) via [**ZenHub**](https://www.zenhub.com/)
