### ISSUE TITLE
Default avatar pointing to invalid asset path

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#2727]
![image](https://cloud.githubusercontent.com/assets/295329/16336302/360395f6-3a04-11e6-8a56-d7e815ebb60d.png)

From [here](https://github.com/zooniverse/Panoptes-Front-End/blob/cd4618544f7f470b7f84f834ed7c4f7ed6fea534/app/partials/avatar.cjsx#L3) looks like the lookup path is adding talk in there somwhere...

https://static.zooniverse.org/www.zooniverse.org/assets/simple-avatar.jpg
vs 
https://static.zooniverse.org/www.zooniverse.org/talk/assets/simple-avatar.jpg

**Comment by brian-c** [comment]
Most likely due to the react-router 2 upgrade. Will investigate this morning.

**Comment by eatyourgreens** [comment]
@brian-c I think it was just a leading . in the URL for the avatar.
