### ISSUE TITLE
Talk links on subject pages don't work anymore

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2729]
if you click on view discussion on https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/subjects/2170614 
 it tries to take you to https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/subjects/217061/projects/mschwamb/comet-hunters/talk/84/62215?comment=122204

@parrish and @alexbfree  perhaps this is related to the Geordi merge

**Comment by srallen** [comment]
I think this is similar to the broken link issue from yesterday. I'm taking a look right now.
