### ISSUE TITLE
Completely not obvious how to sign in anymore to any zooniverse panoptes projects because the sign in/register and sign out buttons are hidden and extra clicks to navigate after logging in

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2733]
Now the entire top navigation bar is a zoonvierse symbol. It's not obvious to new people how to sign up or for current volunteers how to sign in. it look me a second to know to click the zooniverse icon on the right which then zooms out to the view with the top bar. 

I don't think signin/sign out register and the project builder link shouldn't be hidden from view. we want to encourage people to sign in and access their profile. it wasn't obvious what to do. The Zooniverse icon doesn't look like a menu, it looks like it would take you to Zooniverse home. 

<img width="1152" alt="screen shot 2016-06-27 at 5 57 06 pm" src="https://cloud.githubusercontent.com/assets/753325/16375967/abf1c5b0-3c90-11e6-9c0d-03ab2cc6bac4.png">

then if you click the zooniverse symbol 

<img width="1151" alt="screen shot 2016-06-27 at 6 00 08 pm" src="https://cloud.githubusercontent.com/assets/753325/16376050/1539fbbe-3c91-11e6-9d86-e3f52c84b59f.png">

Also this means for people who don't have email notifications set for getting private messages they only see on login/logout  whether or not they have a new message. 

Also if you do log in, you have to click twice, to go anywhere on the project page, because the first click gets rid of the blue outline with the navigation bar which is annoying and not expected. Same thing on logout. You get logged out and the blue outline remains. 

cc @chrislintott @mrniaboc

**Comment by alexbfree** [comment]
i noticed that a "The Zooniverse" label was proposed, which might help a little bit. https://github.com/zooniverse/Panoptes-Front-End/pull/2730#issuecomment-228387736

The comment that sign in needs to be more visible makes sense though.

**Comment by marten** [comment]
Seconding this issue. I brought it up in Slack when this was first posted as GIFs there. We should keep the "sign in / register" or "User Name (NOTIFICATIONS ICON)" section in the bar next to the zoo logo at all times.

**Comment by marten** [comment]
Also, nobody will expect the rest of the menu to be behind that logo, logos pretty much always take you to the homepage. The logo should probably be a hamburger instead.

**Comment by mschwamb** [comment]
That would be a great solution @marten  and would address my concerns for not getting as many logged in classifications which is what I really care about.  

Although I think that no one would ever know to click the Zooniverse icon which means new volunteers would not know there's a Zoonvierse wide Talk. Honestly if the login buttons hadn't been hidden I wouldn't have even thought to click on the Zooniverse icon to get the Zooniverse level navigation bar.  I'm not sure what the reasoning for hiding it is, I would think you'd want to advertise on each project builder project that there is the project builder with the lab link. Maybe if the Zooniverse symbol had the symbol you get in mobile to indicate a menu it would be clearer?

**Comment by marten** [comment]
The reasoning was that there was a bunch of weird overlap: Zooniverse-wide "Talk" vs project "Talk", and Zooniverse-wide "Collections" vs project "Collections". This zoom-out behaviour makes it clearer that those links that appear are about something other than the project.

I also love how it makes the page be all about the project, and then Zooniverse is somewhere in the footer.

**Comment by mschwamb** [comment]
I guess  but with this new design most people will never click on the navigation particularly with the icon over to the right even with a hamburger (?). I would think less people will ever click those links even if there is a menu button. It's fine for me if the main issue in this ticket the login/register get addressed since my priority is my projects and getting logged in classifications , but I have a feeling less new volunteers people will know there exists a Zooniverse talk or a project builder and go to those links.

**Comment by brian-c** [comment]
For comparison, the new navigation is similar to what we did on older sites like https://www.galaxyzoo.org/. Maybe we just need a way to make sure it's visible on load.

**Comment by mschwamb** [comment]
@brian-c  the galaxy zoo one navigation by default stays down until you log in  (or at least it does for me) and then it hides or if you click the zooniverse icon. If it behaved more like that and was clearer what you to click to get back to the navigation bar, I'd be less concerned about losing logged-in classifications

**Comment by yshish** [comment]
I agree with @mschwamb's points. I understand the reasons for hiding the menu but I really think that user specifics (avatar/username, mailbox..) should be visible all the time without the need to click anywhere. (Think of users who share computer with others - they need to see who is currently signed in.) Please, bring back at least these ones.

**Comment by mschwamb** [comment]
@brian-c is there any chance of at least temporarily having a sign in/register button on next to the Zooniverse icon while the design is being tweaked by the graphic designed. I've had two newsletters go out, and I've noticed a drop in the number of logged-in users who appear when the newsletter have gone out in the past at similar times of day on both panoptes projects.

**Comment by brian-c** [comment]
@jwbmartin are you close to a solution? If not, should someone merge #2748?

**Comment by jwbmartin** [comment]
Sorry @brian-c I've been on vacay. Back next week.
