### ISSUE TITLE
Creating a new workflow for a live project

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#274]
This question came up in conversation with @chrislintott. Say you have a project that's live on the Zooniverse home page, and you want to create a new (additional) workflow. Should you just create a new project?

**Comment by camallen** [comment]
I think this should be fine to add to an existing project as all the counts and aggregation will be per workflow.

**Comment by aliburchard** [comment]
Sorry, I should clarify. I'm mostly thinking about how modifying a project works with the new project states articulated in #240. As I understand it, the project states/flags (Beta, Beta-approved, Launch, Launch-approved) apply to the project as a whole. Let's say a project has gone through the whole approval process and is now live on the Zooniverse and collecting classifications. While the project is live, the project owner realizes they want to add another workflow to the project. However, this new workflow needs to be vetted and tested before it can be displayed on the live project...

Would the project owner need to take their project off of ZooHome entirely (to "unlock" it and add a new workflow and then go through the approval process again)? [Sucky, as you lose momentum and your project just disappears!]

Or could they clone their existing project and add a new workflow? [Tricky. How do you deal with classifications made on the existing project vs. the new cloned version?]

Or do they just create a new, separate project for the new workflow? [e.g. Galaxy Zoo 1, 2, 3 with new generations of tasks...]

**Comment by camallen** [comment]
Right, got it. I don't think we should recommend they go through the approval process again and lose momentum. They could easily spin up a new project and create a new workflow and link the subject_sets to the new workflow (not sure this is in the UI). 

I don't think we should tell them to clone and have one project with 2 workflows and the other with one (nothing stopping them from doing this though). We should just recommend they run with 2 projects and the unique workflow for each.

All resulting classifications will be scoped to a project and they would have to manually merge them outside of Panotpes for their analysis.

**Comment by chrissnyder** [comment]
This might be outdated with all the updated project visibility work that was done recently. @camallen can you comment/close?

**Comment by camallen** [comment]
Backend issues should mostly have been dealt with by https://github.com/zooniverse/Panoptes/pull/946. This code ensures that when a user modifies a project that is in the live state the front end should warn the user that making changes is a bad idea, if the user proceeds the front end should set the live param to false along with any updates. The project will then end up with all `beta/launch  _approved` states revoked and `live == false`. 

The key above is that the front end warns the user and if the user proceeds then the live param is set to false to activate the state changes in the backend. 

I'm not sure what the state of the front end is but when a project is live you should not be able to add a workflow without being warned. If the user adds / modifies a workflow then the project should be updated with the `live=false` param as well. 

We could add some code that checks on the live state of a project when creating a workflow and will reject the request if a project is live and in and beta/launch approved state (non-approved live states will be ok). That would remove the onus on the front end syncing the correct state. If a user really wants to add a new workflow they have to consider that very carefully and consult with us.

**Comment by chrissnyder** [comment]
Given that any project that runs into this would have to ask us directly to be approved in the first place, I think we can punt the more general case to after soft launch.

**Comment by aliburchard** [comment]
I'd like to pick up the conversation about how to add functionality onto a live project. Perhaps a larger issue that involves having *parts* of a project be testing vs deployed, that extends beyond the scope of this issue, but flagging for discussion this week.

**Comment by simoneduca** [comment]
Outdated, closing.
