### ISSUE TITLE
Geordi logging issues

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#2742]
https://www.zooniverse.org/projects/birgus2/western-shield-camera-watch/talk/372/62590?comment=122563

2 fold issue (see above link for more details):
+ different envs should be contacting the correct servers
+ down geordi server seems to be raising an error (this should be caught)

**Comment by camallen** [comment]
@alexbfree looks like geordi client uses 2 params to configure the Geordi API url, first is server initialize param [here](https://github.com/zooniverse/geordi-client/blob/ef8c7a0ce4b53db9fdc0b5249981ea17f9ed9ddd/index.js#L48) that sets the env and then that is used to look up the the URL [here](https://github.com/zooniverse/geordi-client/blob/ef8c7a0ce4b53db9fdc0b5249981ea17f9ed9ddd/index.js#L88). 

Any reason not to just pass in the env param to setup the server URL instead of providing a URL that may fail a lookup if it doesn't have the correct key?

**Comment by alexbfree** [comment]
the linked PR #2749 fixes the issue with the wrong geordi server being used.

Error handling for Geordi down coming shortly.

**Comment by alexbfree** [comment]
The PR #2750 will ensure that Geordi fails gracefully. It is the responsibility of the user of the Geordi client's returned promise to decide what to do when Geordi throws an error, so have put handling into PFE. We have something similar in Serengeti's code that calls Geordi.

**Comment by eatyourgreens** [comment]
Hi, Geordi client already defines an `onerror` handler for the XHR request, and rejected promises don't interrupt JavaScript, so I'm a little confused here. 

The issue in the linked Talk thread is being caused by the broken links mentioned there, not Geordi.

**Comment by camallen** [comment]
The issue in talk is 2 fold:
1.  URL's were broken, that is fixed.
2. Geordi was reporting errors when the server was unavailable (recreate it by modifying the geordi host in /etc/hosts to something unreachable)
  + `vendor-2e5aed4….js:288 Uncaught (in promise) Error: Network Error(…)`

Seems geordi is raising on network error in the client [here](https://github.com/zooniverse/geordi-client/blob/ef8c7a0ce4b53db9fdc0b5249981ea17f9ed9ddd/index.js#L99) on these events...Basically I don't think PFE should be raising geordi errors when the server is down..

**Comment by eatyourgreens** [comment]
OK. For reference, graceful failure on errors is already built into the Geordi client, added here
https://github.com/zooniverse/geordi-client/pull/8/commits/44634a519a8c98d3fad9bf962ef9ba3d310e1edb
with a test for API errors here
https://github.com/zooniverse/geordi-client/blob/master/test/index.js#L17-L28

I'm worried that #2750 will make API errors, like `422 - Unprocessable entity` hard to debug by swallowing the error message.

**Comment by alexbfree** [comment]
@camallen on your point 2, that is exactly the scenario this PR #2750 addresses. I tested it and it successfully caught the network error with occasional logging to console instead. Do you have a testcase that still fails with this PR in place?

**Comment by alexbfree** [comment]
@eatyourgreens Do you have a suggestion? Given the frequency with which Geordi posts to the console, I thought that logging every single one while Geordi is down/unavailable would be unacceptable.... 
Should I perhaps make it so that suppression of console warnings only happens if env is production?

**Comment by eatyourgreens** [comment]
@alexbfree maybe throttle network errors but not errors from the API in the Geordi client?

By the way, the title of #2750 is a little misleading, nothing breaks if you don't have that catch there.

**Comment by camallen** [comment]
@alexbfree I'll defer here re errors / logging noise on the console.

**Comment by alexbfree** [comment]
@eatyourgreens could you define what you mean by throttle in this context?

**Comment by eatyourgreens** [comment]
@alexbfree maybe throttle network error reporting here https://github.com/zooniverse/geordi-client/blob/master/src/index.coffee#L84 but don't swallow API errors that are caught here https://github.com/zooniverse/geordi-client/blob/master/src/index.coffee#L84

I'm thinking that if you are, for example, inadvertently sending bad event data to the client then you probably want to see the HTTP error so that you can debug it.

**Comment by eatyourgreens** [comment]
I've added a test to the client, which I think covers the network error.
https://github.com/zooniverse/geordi-client/pull/10

**Comment by alexbfree** [comment]
noting that original reported issue "down geordi server seems to be raising an error (this should be caught)" has now been rejected. See discussion on closed PR #2750.
