### ISSUE TITLE
Image upload not clearing/reporting properly

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#2751]
If you try and upload images that are too large and you get the failure message you can then press the cross to cancel that upload attempt. When you then make your next attempt to upload images that are a suitable size, they work, but you also get the old failure message coming back  for the old images, even though you're not trying to upload them anymore.

**Comment by srallen** [comment]
@mrniaboc is this with the media upload or subject upload?
