### ISSUE TITLE
Collections have uneven sizes if name fills two lines

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2754]
It looks a bit odd to have variable size based on collection title

<img width="1053" alt="screen shot 2016-06-29 at 7 22 01 am" src="https://cloud.githubusercontent.com/assets/753325/16435693/669a31ce-3dca-11e6-9222-518213bea05a.png">

**Comment by jwbmartin** [comment]
I think this is an easy fix. Just have the title ellipses once it hits two lines. I'll see if someone has time to do it or if I can figure it out myself.

**Comment by brian-c** [comment]
> I think this is an easy fix. Just have the title ellipses once it hits two lines. I'll see if someone has time to do it or if I can figure it out myself.

I've got a pretty neat string-truncator component coming with the new homepage, I can pluck it out into a separate PR if that'd be useful to someone.

But my standard disclaimer applies here: design with the content you have, not the content you want. In this case what we have are user-defined strings of unknown length.

**Comment by mschwamb** [comment]
If you are going to truncate, I'd suggest giving two lines and then using the ellipses to keep the name on two lines

**Comment by srallen** [comment]
A fix for this is coming in with #2804

**Comment by srallen** [comment]
#2804 is now merged.
