### ISSUE TITLE
Show projects on your "labs" page if you are a collaborator

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#276]
Currently, only projects that you own appear in your lab page, which makes a shared building process trickier.

**Comment by vrooje** [comment]
+1

**Comment by aliburchard** [comment]
@brian-c any chance we could do this for the first release? I think it would be really really useful, and seems straightforward?

**Comment by edpaget** [comment]
@brian-c I'll add a backend option to filter on roles, so you'd do `?current_user_role=owner,collaborator`. Does that sound good?

**Comment by brian-c** [comment]
Sounds good, thanks.

**Comment by drphilmarshall** [comment]
This is still not available on the demo site, so I'm going to assume that it's not actually fixed (right?). So:

+1  

+1 from @aprajita whose project I am trying to edit

+1 from @anupreeta who needs to see the project we added her too with no explanation :-)

@aprajita, can you paste the URL of the project you just made into a reply, please? Thanks!

**Comment by aprajita** [comment]
we just made…

http://demo.zooniverse.org/panoptes-front-end/#/projects/Aprajita/FaceWarps
