### ISSUE TITLE
Bottom navigation bar Zooniverse links don't autoscroll back up to the top

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2762]
I noticed when you click on any of the navigation links on the bottom Zooniverse navigation bar they go to the right pages but the browser doesn't autoscroll up to the top of the page. You're at the bottom of the new page which makes it a bit hard if you're perusing 

Talking about this navigation bar
<img width="1141" alt="screen shot 2016-07-03 at 11 41 52 am" src="https://cloud.githubusercontent.com/assets/753325/16543688/cede81b6-4114-11e6-8233-29405f5c29de.png">

After clicking on the Contact Us on the bottom bar:

<img width="1150" alt="screen shot 2016-07-03 at 11 41 41 am" src="https://cloud.githubusercontent.com/assets/753325/16543690/e9d8fe6a-4114-11e6-9f7f-2564fadd0e3a.png">

or if you click on  policies on the bottom bar:
<img width="1157" alt="screen shot 2016-07-03 at 11 41 25 am" src="https://cloud.githubusercontent.com/assets/753325/16543694/fc2b6fe4-4114-11e6-9a60-9b2d2be48ac7.png">

**Comment by srallen** [comment]
`react-router-scroll` can be used to define behavior on route change: https://github.com/taion/react-router-scroll
