### ISSUE TITLE
Can't directly load project pages in lab

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#2767]
Going directly to one of my projects (e.g. https://www.zooniverse.org/lab/2731) now loads /lab/ instead.

**Comment by camallen** [comment]
yeah - this is terrible. I can't URL hack now in admin mode either. Is this related to the timing of the user authentication module redirecting me as i'm not authenticated, then showing me the labs reload page after the authentication happens?

**Comment by eatyourgreens** [comment]
Yeah, I think this check is always going to be true when the component first mounts
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/project.cjsx#L240

**Comment by eatyourgreens** [comment]
See #1809

**Comment by eatyourgreens** [comment]
@astopy @camallen there's a branch staged at https://fix-2767.pfe-preview.zooniverse.org/ with that `componentDidMount` method removed.

**Comment by astopy** [comment]
Cool, that seems to fix it.
