### ISSUE TITLE
Ability to pause and unpause subjects 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#277]
What happens if a science team puts in way more data than the classification rated can actually handle on then site and decide to switch tactics wanting to pause most of the live subjects except a small subset - ie Planet Four going for classifying full seasons during stargazing to targeting one region and classifying all the data for four seasons of it - switching to the new scheme meant pausing most of the season 1 data we uploaded

 currently you'd have to make a new subject set and merge the previous  classifications already in hand in processing. Is there any way/menu to pause and unpause subjects from the workflow editor?

**Comment by chrissnyder** [comment]
https://github.com/zooniverse/Panoptes thing. I don't know if the API supports pausing subject sets, but it would be worth addressing over there if this is important.

**Comment by edpaget** [comment]
This is already support on Panoptes. There is not a UI for it yet.

**Comment by mschwamb** [comment]
Got told to bring the discussion back here. 

My solution would be to do this with a manifest file type file.  You upload one for ones you want to 'retire' and for ones that you want to 'unretire'. That way it's not clicking through 10,000 check boxes.

**Comment by chrissnyder** [comment]
Apologies @mschwamb for the discussion-bouncing.

**Comment by simoneduca** [comment]
As far as I can see, a solution was reached on the backend here https://github.com/zooniverse/Panoptes/issues/982, but the frontend still hasn't got this feature. Would @camallen or @parrish mind confirming that the backend already support this?

**Comment by camallen** [comment]
we support the linking of subject sets and it's up to the project owner to setup the data in a way they can manage them. 

If owners need to retire their own data they can use the python client to do so. They could also move the subjects into new sets too if they didn't upload them in a manageable way the first time. 

Closing this as i think all the pieces are in play, feel free to reopen if we need better UI components to deal with this.
