### ISSUE TITLE
Need proper error message for landing on private project page

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2772]
If you go to a private project's landing page, you are met with an incomprehensible error message:
![screen shot 2016-07-08 at 11 10 39](https://cloud.githubusercontent.com/assets/6217406/16684647/2a02b3d6-44fe-11e6-903d-a738c3d0daa3.png)

We *really* need to say something like "you've arrived at a private project! If you are supposed to have access to this project, please email the project owner."

@brian-c this seems pretty straightforward - would you or someone be able to tweak this easily?

**Comment by mschwamb** [comment]
Duplicate already here #1792
