### ISSUE TITLE
User project preferences without user contributions

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#2777]
This is the anomalous behaviour from the UI, https://www.zooniverse.org/talk/17/65759

It seems [here](https://github.com/zooniverse/Panoptes-Front-End/blame/bcb1f1c93483514a56a41e88475fed763c12e952/app/pages/project/index.cjsx#L263) the project prefs are being created on project load? instead of by the backend when a classification is received. We either need a to provide better stats pages (hide / show, etc) and/or stop making them without a classification. 

Any ideas why we started making prefs without classifications and if we need them?

**Comment by eatyourgreens** [comment]
I think this is related to #2572 - setting a default workflow for a project. User prefs are probably also created when you complete a tutorial, regardless of whether you've classified on a project.

**Comment by brian-c** [comment]
Yep, @eatyourgreens got it.

I think the solution is to just filter out prefs with `activity_count: 0`.
