### ISSUE TITLE
Zoom in on selected part of a subject

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#278]
@camallen @eatyourgreens and I talked about this today. There seem to be a small number of projects where this is really fundamentally critical to the task (e.g. retinas), and many others where it's really helpful, if not critical (e.g. penguins, orchids, etc). 

Sounds like one complication is ensuring that marks made while zoomed in are returned in original coordinate space.

**Comment by camallen** [comment]
@eatyourgreens do you have time to work on this in the next week or so?

**Comment by brian-c** [comment]
Zoom is not in scope of first release.

**Comment by camallen** [comment]
@brian-c we will need this for the Retina project, which we plan to run as one of the first zooniverse projects after launch. 

Are you happy to have someone else work on it?

**Comment by brian-c** [comment]
Sure thing. Just want to warn that this involves completely rebuilding the subject viewer and classifier layout.

**Comment by mkosmala** [comment]
We were planning to do a pseudo-zoom for Season Spotter where we simply provided a link to the original image (on a non-Zooniverse site), since zoom was out-of-scope for release. But we need to be able to specify links (Markdown?) in the metadata... See #181  

If 'zoom' changes to be in-scope for release, I'd like to know.

**Comment by camallen** [comment]
@mkosmala don't count on it. Even if we do get developer effort it might be weeks after "launch" before it's available.

**Comment by eatyourgreens** [comment]
I've started the [scaleable-subject](/zooniverse/Panoptes-Front-End/tree/scaleable-subject) branch to work on this, rendering the subject as an SVG image so that we can crop and zoom by changing the SVG viewbox (like Science Gossip.)  I should have time to work on it this week.

Did you have any thoughts on how the UI would work for cropping? Draw a rectangle, and the image crops down to that rectangle when the rectangle is placed?

**Comment by aliburchard** [comment]
Awesome. I think we would want the user to draw the rectangle and then click "next" when they are ready to crop. That allows users to readjust the cropping area if necessary. As long as we specify in the help text that the cropping tool should be the only drawing tool in the task, I think that will be ok.

**Comment by mkosmala** [comment]
I'm a bit confused. Is the point to zoom into a portion of the image? If so, I'd think that zooming would be necessary for all sorts of questions and not a question in and of itself... Maybe I don't understand exactly what the goal is here. 

I think drawing a rectangle and redrawing works. You could also do a single click and redraw with that location as the center of a zoomed-in rectangle (of predetermined dimensions).

**Comment by eatyourgreens** [comment]
Hi @mkosmala, this is a tool to select part of an image, then crop and zoom the selected region. See the first couple of steps in this demo workflow: http://demo.zooniverse.org/retina/#/optic-nerve
Hope that makes things clearer!

**Comment by mkosmala** [comment]
Thanks, @eatyourgreens. Can you support both the way it works in the Retina demo you shared, as well as the way it works in Science Gossip? In Retina, the user draws a box and then by selecting next, the image zooms in for the next question. In Science Gossip, the user can zoom and unzoom while answering a question (without moving between questions). Looks like it might be fairly easy to support both types of zoom...

**Comment by aliburchard** [comment]
@mkosmala I can't speak to how easy it is to implement both types of zoom, but I can say I don't think either of these are going to be included into the project builder in time for first release. Sorry!

**Comment by ggdhines** [comment]
would it be possible to zoom with the mouse wheel? Just tried manuscript adventure and really need to be able to zoom in to transcribe and zoom out to move around the page.

**Comment by aliburchard** [comment]
closing, as this exists.
