### ISSUE TITLE
A way of removing the extra click for non-logged in users on the landing page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2787]
The new Zooniverse navigation header layout now reveals the zoom out with the Zooniverse navigation bar if you're not logged in the first time.  I really appreciate that panoptes front end now shows that  when you first get to the first project page to help get people to login  but  because of the  zoomout you have to click once to zoom in and hide the bar and the blue sides and then once to click Get Started!  I find that a bit weird and I think new people will find it weird when they try to click on the Get Started! button that it doesn't just go. As the goal is get people in fast who are checking out the site, is there something that can be done to make it one click?

What about removing the blue sides so it's just the top blue navigation bar appearing and disappearing, then it wouldn't be a zoomout, zoomin which might save the click?

**Comment by jwbmartin** [comment]
I'm not going to drop the border. It's received a lot of positive feedback and there are actual conceptual reasons why I chose to style the page in that way. But it is odd that you have to click "Get Started" twice to get to the Classification page. 

Hm, not sure who I should ping since Brian has left? @srallen ? @eatyourgreens ?

**Comment by srallen** [comment]
It's functionally acting like a modal when zoomed out... might just be a z-index that we could modify, but I'm not sure.

**Comment by eatyourgreens** [comment]
There's an overlay, `div.app-layout__main-overlay`, which blocks you from pressing the buttons but goes away after the first click.

**Comment by srallen** [comment]
Perhaps we should consider removing the overlay so folks who wish to classify in a project with the top level nav showing can choose to do so? Related to #2800

**Comment by eatyourgreens** [comment]
I just played around with removing it in the DOM inspector and personally, I found the site a lot easier to use without that annoying first click to activate the page.

I think that, as it stands, clicking to classify will still close the top menu though. So you won't be able to see your notifications while classifying.

**Comment by eatyourgreens** [comment]
@srallen I think it's as simple as deleting this div, right? https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/layout/index.jsx#L129-L137

**Comment by mschwamb** [comment]
@jwbmartin the border is fine if you want it on the edges. 

The only reason I'm suggesting getting rid of it on the sides when keeping the zooniverse navigation bar and account icons permanently  exposed is that the border causes the classification interface to show a smaller subject image. The main goal of these sites is to review and classify the image/data presented so from a science team perspective if there's a way to keep the image size the same before the border was added that would be my preference. 


Subject image when the border on the left and right aren't showing

<img width="494" alt="screen shot 2016-07-27 at 5 39 28 am" src="https://cloud.githubusercontent.com/assets/753325/17181721/c47770c4-53bc-11e6-834d-6c44e290c494.png">

same subject image when the border showing (it's slightly smaller)
<img width="464" alt="screen shot 2016-07-27 at 5 39 21 am" src="https://cloud.githubusercontent.com/assets/753325/17181741/d3c59a74-53bc-11e6-8ba5-99e54416635a.png">

**Comment by srallen** [comment]
@eatyourgreens Yep, that looks like it.

**Comment by mschwamb** [comment]
thanks!
