### ISSUE TITLE
Ellipse tool: What does rx,ry and angle refer to?

### ISSUE THREAD

**Issue by mwp-tj** [zooniverse/Panoptes-Front-End#2790]
For the panoptes ellipse tool attributes : rx, ry and angle, what reference frame is used to calculate these values?

Is rx the semi-major axis of the ellipse? How is this measured?
If rx is measured as the 'radius along the x-axis', how is it measured when the ellipse is rotated at some angle relative to the x axis (ex: 45 deg)?

In the code published on GITHUB, I noticed that ry=rx*DEFAULT_SQUISH (DEFAULT_SQUISH=0.5), this would make ry the smaller of the two by default. However, one can drag and make ry bigger than rx, in such cases how do you differentiate between the two?

Also, the angle used by this tool, is it measured from the 'x' axis counter-clockwise?

**Comment by brian-c** [comment]
> Also, the angle used by this tool, is it measured from the 'x' axis counter-clockwise?

Yep, I think that's the key. Size doesn't define the axis, relation to the `angle` does. Here's the description from the readme:

> **ellipse:** The `x` and `y` coordinate of the center of the ellipse, its radii `rx` and `ry`, and the angle of `rx` relative to the x axis in degrees (counterclockwise from 3:00).

**Comment by mwp-tj** [comment]
So if I'm understanding this correctly, the way these ellipses are defined follows these steps:
*An ellipse is drawn with `rx` and `ry`with `angle=0`
*The ellipse is then rotated with respect to the x axis to match the angle given

**Comment by brian-c** [comment]
Sounds right to me.
