### ISSUE TITLE
stats page dropdowns don't work

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#2797]
Looks like the react-router updated may have broke the dropdown lists on the stats page.

**Comment by mcbouslog** [comment]
https://www.zooniverse.org/projects/jukoch/pattern-perception/stats - works

https://www.zooniverse.org/projects/zooniverse/notes-from-nature/stats - breaks if try to use dropdowns after workflows have loaded (time periods dropdown works before dropdowns load)

**Comment by CKrawczyk** [comment]
Odd, I just tried this again today it the everything is working as expected.  Not really sure what was causing this.  Closing for now.
