### ISSUE TITLE
if you go to a subject page directly from a link posted in a talk post it shouldn't go to the zoomed out 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2798]
If you click on the links to the subject pages in a Talk post non-logged in, it switches back to the zoomed out menu. If you've dismissed the bar it should stay down I think if you're navigating within Talk

https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/213/68083?comment=130663

**Comment by MvGulik** [comment]
Short version: Consider making the user-login-action/state part permanently visible and available no matter what zoom-mode is used/active. (*that way zoomed-in can be made de unconditional default, problem solved no?*)

**Comment by jwbmartin** [comment]
@eatyourgreens is this similar to the issue we were talking about in Slack?

**Comment by eatyourgreens** [comment]
@mschwamb is this still a problem? I can't reproduce it, in an incognito window in Chrome. If I close the top bar, it stays closed when I click on links.

**Comment by mschwamb** [comment]
@eatyourgreens Looks like some of this was fixed.  The only place I see it still occurring, is if In click on the hasthag 'tail' hyperlink in the link I have above if I've closed the zooniverse bar before clicking on the  tail hyperlink.

**Comment by eatyourgreens** [comment]
Thanks @mschwamb I've just had this bug happen to me from a volunteer's profile page too.

If I click on any linked comment from https://www.zooniverse.org/users/cestmarrant the page layout zooms back out to show the main Zooniverse navigation.

**Comment by mschwamb** [comment]
@eatyourgreens this might also be related to what's being described in this thread [here](https://www.zooniverse.org/talk/17/83476).

**Comment by eatyourgreens** [comment]
This looks to be caused by some components using `<a>` where they should be using `<Link>` for internal links. The browser then reloads the whole page when the link is clicked, rather than using `pushState`, and the page zooms out because it's the first time you've visited the project during this new browsing session.

I've opened a branch to fix this, staged at https://fix-2798.pfe-preview.zooniverse.org/?env=production
