### ISSUE TITLE
Not clear how to get the Zooniverse level navigation bar and Account buttons back 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2800]
It's not apparent that the Zooniverse logo does anything to bring back the Zooniverse level navigation bar. So once you double click or login, I think it's not clear how to log out or get to the mailbox. I've been asked by other science team members, how to navigate to access those things.  See additional comments on this subject  in #2733

**Comment by srallen** [comment]
@jwbmartin One of things we did on Chimp and See with buttons that only use icons is add a tiny label below them, specifically the field guide and favorite button on the sides of the classifier. The favorite button also has a small pop up on hover when someone is signed out and the button is disabled to show a small "sign in or sign up to use this" type messaging. Could something like that be a solution here?
