### ISSUE TITLE
"Zooniverse Team" role label on Talk no longer centered under profile pic

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#2809]
![screen shot 2016-07-21 at 1 24 25 am](https://cloud.githubusercontent.com/assets/2357126/17016088/31bf7436-4ee2-11e6-9596-330a6dfb78d2.jpg)

I haven't been on Talk in a few days so I'm not sure how long this has been happening. I'm in Chrome 51.0.2704.103 (64-bit) for OS X.

**Comment by mschwamb** [comment]
Noticing the same thing as well.

**Comment by srallen** [comment]
I'll take a look at this today. I've been doing some work on the CSS here, but I didn't see this happen with my changes...

**Comment by mschwamb** [comment]
Thanks @srallen
