### ISSUE TITLE
Pop up interventions like Penguin Watch

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#2814]
This is a feature request I'm logging at the suggestion of @vrooje and @alexbfree, inspired by Seabird Watch https://www.zooniverse.org/projects/penguintom79/seabirdwatch. In this project you're asked to count all of the birds in an image, whereas in Penguin Watch (similar dataset) you're asked to click on as many as you can and when you've reached 30 a pop up appears saying 'You've done 30. Marvellous', or words to that effect. Could we have a pop up/intervention feature on the PB/PFE which enables research teams to give advice, tell someone how many times they've clicked on an image, etc?

**Comment by srallen** [comment]
Related to #2834. Specific hard coded messages are being worked on as initial test cases for PFE projects. This is a feature to come back to.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
