### ISSUE TITLE
Arrow Drawing Task

### ISSUE THREAD

**Issue by hughdickinson** [zooniverse/Panoptes-Front-End#2817]
It would be really useful to be have an arrow drawing tool to enable directionality of lines to be explicitly defined. Is this possible?

**Comment by camallen** [comment]
can't this already be determined by the order of the points in the classification as we record the order of points already? E.g. `[ point_1, point_2 ]` is a direction from 1 to 2.

**Comment by hughdickinson** [comment]
It can, but for the purposes of our project, the directionality is sufficiently important that it would be good to have a visual representation so that classifiers do not inadvertently draw the line in the wrong direction.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
