### ISSUE TITLE
Geordi logging for localhost development

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#2818]
I've been testing PFE locally on my dev machine without an env setting (just overriding the panoptes api url / app key) and i've noticed it's logging to geordi staging. 

Do we want to be logging to staging like this? I don't think so, in my mind logging to geordi should be disabled unless we are active on a known domain (*.zooniverse.org, etc). Thoughts?

**Comment by srallen** [comment]
It was probably useful for the initial development, but I agree that it's unlikely to be useful now and would be cluttering up the staging db.

**Comment by srallen** [comment]
@wgranger something to take a look at whenever you have time.

**Comment by camallen** [comment]
closing this, it's not important.
