### ISSUE TITLE
Allow multi-image subjects

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#282]
How do we build a project that has multi-image subjects (similar to Snapshot Serengeti)? @camallen mentioned that the metadata parser might already handle this?

My immediate use case is one of the projects targeted for the Panoptes launch. We're putting up a subset of Snapshot Serengeti photos and asking users specific questions that require them to "play" the sequence.

**Comment by brian-c** [comment]
Have you tried a manifest with multiple columns for files? This really should work already.

**Comment by aliburchard** [comment]
Oh wow! Thanks @brian-c - the manifest with multiple columns does work (I didn't know that existed).

Question though -- instead of having multiple columns, could we allow users to provide every image in its own row, but have a column that identifies "subject_id" to indicate that multiple images belong to a single subject? "Wide" data formats are generally bad practice, especially when there might be varying numbers   of columns (some subjects might have just one image, some might have 2, others 3).

**Comment by twhyntie** [comment]
Cool! I didn't know that either. How do you name the columns in the manifest to do this?

**Comment by brian-c** [comment]
Files are found by searching each row for a filename with a supported extension. Column headers are used only for display in a subject's metadata.

**Comment by twhyntie** [comment]
@brian-c Great, thanks. So that would solve @aliburchard's problem of variable number of images - just stick the (arbitrary number of) image filenames at the end of the row, like this:

```
id, date, filename
1, 2015-05-05, image_a.png
2, 2015-05-05, image_b.png, image_c.png, image_d.png
3, 2015-05-04, image_e.png, image_f.png
```

(i.e. there is no row/header validation performed that would throw an error/refuse the manifest in the event of a column number mismatch.)

**Comment by brian-c** [comment]
Yep, but right now those columns will still need headers, e.g. `id, date, filename1, filename2, filename3`. Fields can be left blank if there's no data to associate with them.

**Comment by twhyntie** [comment]
@brian-c Cool, so one would just need to know the maximum possible number of images for a given subject in a subject set and write the headers accordingly.

```
id, date, filename1, filename2, filename3, filename4, filename5
1, 2015-05-05, image_a.png
2, 2015-05-05, image_b.png, image_c.png, image_d.png
3, 2015-05-04, image_e.png, image_f.png
```

Thanks!

**Comment by twhyntie** [comment]
@aliburchard What do you think? I agree that wide data formats aren't great and adding lots of column headings wouldn't be ideal, but would this workaround do for the first release, given that it requires no extra coding? Are there any other benefits to the one-image-per-row manifest approach?

**Comment by aliburchard** [comment]
@twhyntie -- It might do for the first release. But I think it's a bad approach to data management, limits what you can do with multi-subject images, and opens up the door for bugs (e.g.  #289). I think that every image is its own entity, with its own pixel coordinates, metadata, etc, and a more robust structure would be to treat every image as its own entity and have the project builder specify whether subjects consist of single or multiple images.

**Comment by aliburchard** [comment]
Closing this issue but picking up a discussion re: multi-image functionality in: #394
