### ISSUE TITLE
UX for notifications in nav

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#2825]
Work with @jwbmartin to integrate her design and UX for notifications in the navbar. Possibly use an icon [like this](https://thenounproject.com/search/?q=notification&i=492155) next to the mail icon.

**Comment by mschwamb** [comment]
Please don't hide the notifications icon away from the project level. It's something that is used frequency by active talk volunteers ,the moderators, and the research teams to see if there is something on the project level talk that they have been mentioned in or updates to a thread they are following it gets updated with the notification count and currently tells the user there are new notifications.  

 If you hide the notifications button away at the top Zooniverse then someone has to always actively click the zooniverse navigation bar to see if they have project notifications and then no one will use it. 

Honestly having a notification icon, mailbox and login/logout button in the top right of the project level would be extremely helpful, and save the now multiple clicks that need to be done to go from logging in to classifying. see #2787 I'm still not sure why the account buttons had to be hidden in the zooniverse level and can't be like what github does and have them in the top right with the notifications.

**Comment by camallen** [comment]
Seconding @mschwamb concerns about the hidden navigation. As a site user i find it really strange that my personal area is hidden behind the project view. I'm totally in favour of just having the project view embedded all the time and have the top nav always visible, e.g.

![image](https://cloud.githubusercontent.com/assets/295329/17172285/327a76dc-53ec-11e6-920a-99f77536ce33.png)

**Comment by mschwamb** [comment]
agreeing with @camallen 100% on this. It's very clear the navigation of the Zooniverse level is different with the blue bar but is still visible in Cam's suggestion. Science team members have asked me how to log out as it wasn't obvious to hit the Zooniverse icon. Also now when you log in, it takes you a click after logging in to get back into then project mode, which is confusing and extra work for the user.

**Comment by srallen** [comment]
If anyone has a bit of time for this, feel free to also self-assign the issue.

**Comment by alexbfree** [comment]
related: https://github.com/zooniverse/Panoptes-Front-End/issues/2858

**Comment by mschwamb** [comment]
one note - there are two sets of notifications zoonvierse wide and project level so perhaps there 's one notifications icons (one on the Zooniverse bar) and one on the project bar?
