### ISSUE TITLE
Preview needed for minicourse

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Panoptes-Front-End#2826]
It would be great to preview the course without having to classify!

**Comment by srallen** [comment]
This feature will be useful for the tutorial too.

**Comment by denslowm** [comment]
I would like to add a Notes from Nature vote for being able to preview the course without having to classify. We are just starting to use the mini-course and this would be great to have.

**Comment by mcbouslog** [comment]
Also noting that adding ability to configure how often mini-course is prompted has been requested. This can become it's own issue if preferred.

**Comment by srallen** [comment]
@mcbouslog please make that its own issue. Which project is requesting this?

**Comment by denslowm** [comment]
Notes from Nature is also interested in the ability to configure how often mini-course is prompted. So +1 from our team.
