### ISSUE TITLE
Possible problem with multiple image flip books

### ISSUE THREAD

**Issue by hughdickinson** [zooniverse/Panoptes-Front-End#2827]
I'm seeing some inconsistent behaviour when trying to use the flip book feature for multiple images in the project builder. I uploaded all the files described in the attached manifest and the manifest itself (with the suffix changed to .csv). Sometimes a flip book is generated, but at other times only a single image appears. Perhaps there was an unreported issue uploading some of the images or the manifest is malformed in some way?

[manifest2.txt](https://github.com/zooniverse/Panoptes/files/385785/manifest2.txt)

**Comment by srallen** [comment]
The manifest looks ok. @hughdickinson did you use the project builder interface to upload the subjects or another tool?

**Comment by hughdickinson** [comment]
I used the project builder.

**Comment by itsravenous** [comment]
Sorry for the delayed response @hughdickinson, I've been away. Can you share a link to your project so I can investigate?

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
