### ISSUE TITLE
Make markdown guide linkable 

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2828]
There is a helpful guide to markdown that is available if you click on '?' from the project builder or talk (I can't actually find where that content is stored). 

Can we make this an actual page so we can actually give people links to the help text? It might also be good to have a prominent "how to markdown" link to the page, though there _is_ the '?' above the text boxes which might suffice.

**Comment by eatyourgreens** [comment]
#1517 has links to the markdown help files in PFE (one for the project builder and one for Talk?)

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
