### ISSUE TITLE
Home page is pushed up in IE11

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#2829]
This is due to a bug in the `.hero` class. `Flex` doesn't work well with the `min-height` property. Setting `height: 800px` is a quick fix, but there will likely be overflow in mobile or other viewports.

![screen shot 2016-07-26 at 4 08 18 pm](https://cloud.githubusercontent.com/assets/14099077/17178984/287993a2-53dd-11e6-93f6-0b0859ffe2cc.png)

**Comment by srallen** [comment]
@parrish, this appears to be an issue in IE11 on the new home page design too. [This might be a usable solution.](https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items)

**Comment by parrish** [comment]
Confirmed.  [This workaround](https://github.com/parrish/Panoptes-Front-End/blob/551ef9e543c9bc2c7118056614f4982b16dfca0e/css/home-not-logged-in.styl#L53-L56) will fix it.  Just wrap the `display: flex` element with a `display: flex; flex-direction: column` container.

**Comment by srallen** [comment]
New home page is deployed.

**Comment by parrish** [comment]
It actually needs to be fixed for the logged-in view as well.

![screen shot 2016-08-02 at 10 38 20 am](https://cloud.githubusercontent.com/assets/122990/17334840/5747ae34-589d-11e6-9516-a286d6a74c48.png)

**Comment by srallen** [comment]
Good catch. Thanks.
