### ISSUE TITLE
Description doesn't actually display the text entered

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#283]
I have saved my project updates and hard reloaded my browser. But as you can see, the text I've entered in the description is not reflected on the landing page...

![screen shot 2015-05-05 at 21 11 03](https://cloud.githubusercontent.com/assets/6217406/7481876/596b74c2-f36b-11e4-97bf-d6817b8eea2a.png)
![screen shot 2015-05-05 at 21 11 01](https://cloud.githubusercontent.com/assets/6217406/7481877/59709344-f36b-11e4-9bfe-c90f48f8db0e.png)

**Comment by aliburchard** [comment]
Okay, I renamed my project, and now the landing page has updated. Perhaps just a browser caching issue?

**Comment by camallen** [comment]
I think this is related to some cache get requests that should be fixed in a recent deploy. Is this still happening?

**Comment by aliburchard** [comment]
hmm, it's still happening. I might not be doing a hard reload right on Chrome?

**Comment by brian-c** [comment]
Latest deploy is still zooniverse/Panoptes@a669aaa8f5288d54d2f54c8ff4416e6825424e53, which doesn't include the new ETags handling.

**Comment by camallen** [comment]
@aliburchard latest deploy should be running now. Can you please check the caching issue?

**Comment by aliburchard** [comment]
Still happening.

**Comment by camallen** [comment]
It's a backend issue I'm looking into this. For what it's worth Firefox doesn't exhibit this issue.
