### ISSUE TITLE
Zooniverse toggle button rendering twice in Chrome

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#2830]
I don't know how I managed to trigger this, but the toggle button, top right, is rendering twice in the DOM in Chrome.

![image](https://cloud.githubusercontent.com/assets/59547/17179165/16670658-5410-11e6-975f-b5be9da5bc27.png)

**Comment by MvGulik** [comment]
Yea. Don't back-out from Zooniverse-talk, when you came from a Project-page.

... *End of Line* ...

**Comment by eatyourgreens** [comment]
I've been able to reproduce this by going from a project to Talk, then using the back button to get back to the project page.

**Comment by eatyourgreens** [comment]
![zoo button bug](https://cloud.githubusercontent.com/assets/59547/17219368/0b977162-54e3-11e6-8c37-2ab07de14d39.gif)

**Comment by parrish** [comment]
To clarify, this isn't a Chrome specific bug.
