### ISSUE TITLE
Space Warps: Instant feedback messages for training images

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#2834]
Hi @chrislintott @marten  

just putting the PFE feedback messaging in SpaceWarps into an issue.

Pop-up feedback is an essential and necessary part of SpaceWarps that improved the users experience & training, and therefore skill.

I've updated our workflow
https://www.zooniverse.org/projects/aprajita/swdemo/classify?reload=0&workflow=960
with a dataset that includes "training" images. 

I've provided feedback messages both for success and failure as part of the metadata (i.e. in the manifest)

The manifest has they keywords
subject_id  image_name_1    image_name_2    image_name_3        #Type   #X  #Y  #Tol    #F_Success  #F_Fail Provenance  Col Size-in-arcsec  #X2 #Y2 #Tol2

If "#Type" is SIM or DUD then these are training images

In the case of SIM training images any click within #x,#y +/- #Tol (or #x2,#y2 +/- #Tol2) would be a success, and no click in this region would be a fail.

For the DUD no click would be a success, and a click would be a fail

The feedback messages for each are in #F_Success and #F_Fail

I've split how we could handle the instant feedback as essential, desirable and optimal. If at least Essential could be implemented that would allow us to start.

ESSENTIAL
If there is a click anywhere in a subject that is a SIM or no click on a DUD triggers a success message. No click in a SIM and a click in a DUD triggers a fail message. 
The message appears anywhere in the interface.

DESIRABLE
If there is a click within #x,#y+/-#Tol in a subject that is a SIM or no click on a DUD triggers a success message. No click or a click ouside #x,#y+/-#Tol in a SIM and a click in a DUD triggers a fail message. 
The message appears anywhere in the interface.

OPTIMAL
If there is a click within #x,#y+/-#Tol in a subject that is a SIM or no click on a DUD triggers a success message. No click or a click outside #x,#y+/-#Tol in a SIM and a click in a DUD triggers a fail message. 
The pop-up message appears pointing towards #x,#y

OPTIMAL is most like SpaceWarpsI&II but ESSENTIAL or DESIRABLE would be fine for our initial planned searches that will be centred on a lensed target.

Note we are operating with the no confirmation page mode (so each subject only requires one screen before proceeding to the next subject. It might be that you prefer to put the message on the confirmation page rather than a pop-up window. If this is the case, this would only work if the confirmation page was only triggered if the subject is a training image (i.e. SIM or DUD) but not if it would mean having to go through a confirmation page for every subject.

@drphilmarshall @anupreeta27 - please add any comments I may have missed.

thanks, aprajita.

**Comment by trouille** [comment]
@aprajita Will the feedback messages be custom-written from subject to subject, or will all #F_Success #F_Fail be the same? 

If #F_Success #F_Fail will be the same for all subjects, it likely will make more sense to include a UI component in the Project Builder where research teams can input those messages. 

If the messages will differ, we'll need to find some other way than '#' to flag them. We use the '#' symbol in the metadata file to include information that only research teams see. We'd need to think of a different way to flag these as success/fail messages specific to this feedback functionality.

**Comment by camallen** [comment]
pinging @hughdickinson as he's been doing some work on this.

**Comment by trouille** [comment]
@marten @camallen : Two questions:

1) Is everything available and working on the back end for this to happen? Or is there work to be done there as well? 

2) When I was in Oxford, one of you mentioned that currently the gold standard feedback functionality was broken on the front end (see attached image). Any chance you know who was working on this previously? It would be good for the new PFE dev who will work on this to be able to talk with that person and know what was working and what's broken. 

<img width="619" alt="feedback" src="https://cloud.githubusercontent.com/assets/4975655/17300536/67c4fa98-57d8-11e6-92de-e80ae982fbcf.png">

**Comment by marten** [comment]
1) I'd prefer those texts to be in workflow_contents rather than subject metadata. If they need to change per subject, the subject metadata should still only contain a reference to a key in `workflow_contents.strings`. This keeps all translatable text together. However, that's just PFE work, backend doesn't care.

2) Pretty sure our stance was that that "Import" should go away completely. We have enough problems dealing with the annotation JSONs without expecting other people to be able to generate classifications that mimic the format correctly. 

I think we suggested that classifying in expert mode should be the way to go for this. We talked about optionally letting experts pick which subject to classify in expert mode.

**Comment by aprajita** [comment]
Hi all
sorry for not replying am on leave for a while but will send responses to
your questions on wed.
thanks
aprajita.

**Comment by srallen** [comment]
Summarizing the discussion with @camallen, @hughdickinson: For now, the messaging for sims and duds will be hard coded into a specific component to be used with the summary and the sim information used in comparing with the classification will be a part of the subject metadata.

**Comment by aprajita** [comment]
Thanks @srallen. The feedback messages will not be the same per subject so
can you clarify that hard coding means we provide a training subject name
with corresponding success and fail messages.

Sorry @trouille for not responding to your questions  yet will get to it
later.

Thanks
Aprajita.

**Comment by srallen** [comment]
@aprajita Our understanding is that the success message and the failure message is the same for all of the sims. We want to reduce redundancy and it's better fitting for the component that handles the message to contain it there rather than in subject metadata. If the message is unique to each subject, then metadata should be considered. Could you confirm that our understanding is correct?

**Comment by aprajita** [comment]
@srallen In the original Space Warps project we rotated a set of feedback messages for a training image if a particular type. Thus, we had groups of sims with similar messages and the old system picked a message from a set for a given type to make sure the user was seeing different messages (to alleviate boredom!) and mostly to learn something with each sim. 

After talking with @marten @camallen @mrniaboc, to continue to provide this in panoptes our understanding was that it would be best for us to to explicitly give a message per subject in the metadata. We thought this would be simplest and would not require the system to make any choices between messages while giving us the flexibility to provide feedback tailored to a particular training image type.

(In the current test data in the SWdemo workflow, I repeated the same messages owing to speed but this will not be the case for the actual data - perhaps this caused the confusion?)

I hope this clarifies what our request is but please let me know if not.

**Comment by srallen** [comment]
Yes, that clarifies this. @hughdickinson perhaps for now subject metadata may be the best place especially if we need to get this in place sooner than later. However, I think @marten brings up some good points and is something to consider for further iteration of this type of functionality.

**Comment by mschwamb** [comment]
We're looking for feedback on Comet Hunters where when we in the future put in simulated comets that there would be a message after classification that notifies then volunteer that they saw a sim like Planet Hunters/Planet Hunters 2 does.  If it's useful to hear another use case, the Comet Hunters team is happy to give input on the notifications feature.

**Comment by bruggsy** [comment]
Hi, jumping in because of this:

> Pretty sure our stance was that that "Import" should go away completely. We have enough problems dealing with the annotation JSONs without expecting other people to be able to generate classifications that mimic the format correctly.
> 
> I think we suggested that classifying in expert mode should be the way to go for this. We talked about optionally letting experts pick which subject to classify in expert mode.

Is this still broken? If so, is there a way other than expert mode to upload gold classifications? I looked in the API docs but there is no mention on how to specify an uploaded classification as 'gold'.

**Comment by camallen** [comment]
@bruggsy we're moving to known gold standard subjects having a metadata field to drive the UI feedback but we haven't figure out how this will work for all projects yet. 

You can get experts in your project to classify to create gold standard classification data for use in custom aggregation, etc right now if they have a owner, collab, expert role and they use the classify UI to enter "Gold Standard" mode (see image)..

<img width="246" alt="screen shot 2016-08-31 at 11 08 07" src="https://cloud.githubusercontent.com/assets/295329/18124701/49558b86-6f6b-11e6-83b1-4462f7ea3ea0.png">

**Comment by marten** [comment]
@srallen Could you update on where this is on the planning (days/weeks/months away?). 

And just to make sure: PFE should write into the classification metadata which feedback message is shown (when it shows any). Nero will be building on that to perform retirement and user skill tracking for Spacewarps.

**Comment by srallen** [comment]
I've been focused on finishing Gravity Spy features. @hughdickinson had #2840 PR in for the Space Warps gold standard feedback. There was some confusion a couple weeks ago about whether or not the message would be unique to each subject which was clarified in this issue. I think the functionality is close to being done in that PR. @hughdickinson Could you let us know what the status is of @2840? I'm not sure if the classification metadata requirement is done.

**Comment by aprajita** [comment]
@hughdickinson @srallen many thanks for updating on the status of this. What kind of timescale do you think SW feedback might be available on?
thanks

**Comment by srallen** [comment]
I'll check in with @eatyourgreens and @hughdickinson about it and get back to you asap.

**Comment by aprajita** [comment]
great - thanks @srallen

**Comment by srallen** [comment]
@aprajita I've updated the feedback feature in a new pull request: #3202. Please let myself and @eatyourgreens know when this needs to be merged in. It just needs a final review.

**Comment by aprajita** [comment]
Hi @srallen thanks so much for this. Can I look at the project builder for  https://space-warps-feedback.pfe-preview.zooniverse.org/ so I can see how this is setup. 

Also do the markers have a tolerance on the position?

Many thanks all!
Aprajita.

**Comment by srallen** [comment]
@aprajita Here is a test project setup to use the feedback feature: https://space-warps-feedback.pfe-preview.zooniverse.org/projects/hughdickinson/testing-metadata-based-feedback/classify

There is a method that calculates a tolerance, but since I didn't write this initially, then I'm not sure if it meets your requirements. This is the method: https://github.com/zooniverse/Panoptes-Front-End/pull/3202/files#diff-bb323db208a738c85e1ec0cb3f3b73b4R11

@hughdickinson may be able to answer any further questions about it.

**Comment by srallen** [comment]
Closing since #3202 is merged.

**Comment by aprajita** [comment]
hi @srallen - just saw that my message from last week was never posted - so am posting this now - sorry....

hi @srallen & @hughdickinson -  thanks 

I think the tolerance is OK - thanks for pointing me to the code

yep, i saw the test project but I wondered if it's possible to be a collaborator on @hughdickinson's SW feedback preview to see the implementation, and/or i could put in a SW test dataset and metadata to see if it's working as expected?

Many thanks!
aprajita.

**Comment by srallen** [comment]
@aprajita I can add you to the test project as a collaborator. What is your username on the site?

**Comment by aprajita** [comment]
thanks @srallen it's aprajita

**Comment by srallen** [comment]
@aprajita I've added your account as a collaborator. Let me know if you need anything else. If you need any changes, would you open a new issue for those? Thanks
