### ISSUE TITLE
The new zooniverse home page project suggestions links to the panoptes landing page for custom built Zooniverse projects

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2841]
Example galaxy zoo one goes to https://www.zooniverse.org/projects/zooniverse/galaxy-zoo . It should straight to Galaxy Zoo

<img width="1128" alt="screen shot 2016-08-01 at 8 50 06 am" src="https://cloud.githubusercontent.com/assets/753325/17305207/1098706e-57c5-11e6-89e2-c38b8e547f1b.png">

<img width="1113" alt="screen shot 2016-08-01 at 8 50 10 am" src="https://cloud.githubusercontent.com/assets/753325/17305223/1e05524e-57c5-11e6-942a-8426b5a5faa5.png">

**Comment by mschwamb** [comment]
All 4 suggested projects have this issue

**Comment by srallen** [comment]
Good catch. Should be able to have a fix up shortly.
