### ISSUE TITLE
New Zooniverse home page social media Twitter feed isn't up to date

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2842]
@parrish not sure if these goes here. There have been three new twitter posts in the past 6 days and they're not showing up on the Social Feed. Does it update daily?

**Comment by parrish** [comment]
Yeah, this was a stupid mistake on my part.  Fixed [here](https://github.com/zooniverse/Talk-Api/commit/adcc7720b1189886faf12c6ab66b121574a81f23).  Should be up in about an hour.
