### ISSUE TITLE
Add 'menu' to project nav zooniverse logo

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#2846]
Originally mentioned in [this comment](https://github.com/zooniverse/Panoptes-Front-End/pull/2831#issuecomment-236231882). Add 'menu' to zooniverse logo used in the project level navigation. Related to #2800

**Comment by jwbmartin** [comment]
Still trying to decide how best to tackle this situation so hold on

**Comment by camallen** [comment]
should we quickly try a couple of solutions and see what the users like?

**Comment by jwbmartin** [comment]
That's not a bad idea. Part of me is feeling like we should just substitute the zooniverse logo for just a regular ol' hamburger menu icon
![screen shot 2016-08-08 at 12 49 53 pm](https://cloud.githubusercontent.com/assets/14332849/17490060/aaa1e7c0-5d66-11e6-98cd-c800a0f7776a.png)
![screen shot 2016-08-08 at 12 49 59 pm](https://cloud.githubusercontent.com/assets/14332849/17490061/ac73104c-5d66-11e6-8f40-69e639d646e8.png)

**Comment by camallen** [comment]
personally makes sense to me (that icon means menu to me).

**Comment by jwbmartin** [comment]
Yeah it loses the original concept I had but, at this point, I haven't come up with any better options and I just don't care anymore.

**Comment by camallen** [comment]
Can you find someone states side to work on this for you? If you can't assign it to some dev's here and we'll try and get cracking on it tomorrow.

**Comment by jwbmartin** [comment]
@mcbouslog or @wgranger would you have time to deal with this?

**Comment by trouille** [comment]
@mcbouslog and @wgranger full today on a couple assignments. I've assigned @eatyourgreens to see if he or someone else in Oxford in their workday tomorrow can take it on. Otherwise we'll pick it up Tuesday morning Chicago time and find a person to go in and make the change.

**Comment by mschwamb** [comment]
@ jwbmartin I really like your screen grabs. If that's what's being implemented, I think it alleviates all of the concerns and issues I have recently raised about the zooniverse level navigation bar redesign.

**Comment by eatyourgreens** [comment]
Hamburger icon on projects is staged at https://fix-2846.pfe-preview.zooniverse.org/
I'm not sure if it's confusing on mobile, where the hamburger icon opens the main menu.

**Comment by camallen** [comment]
@eatyourgreens working for me when i'm viewing a project page (desktop only) but i think the behavior is a little inconsistent. When at zoo wide level i see all my data

**Comment by eatyourgreens** [comment]
So the Account Bar/Login Bar component should always be visible?
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/layout/site-nav.jsx#L228
I'll have a look.

**Comment by camallen** [comment]
sorry - need more coffee today. I guess re the code links, i think just hiding the main zoo wide links was the final aim but showing the user / notifications status is key (IMHO) to fixing this.

**Comment by eatyourgreens** [comment]
You can still tab to the main nav links when they're hidden too, so they've only been hidden visually, not actually removed from the UI. That's confusing.

**Comment by eatyourgreens** [comment]
@camallen I've updated staging so that the account bar is always visible. There's an annoying jump to the left when the icon changes from hamburger to Zoo logo, and mobile looks too crowded in my opinion. Otherwise should be good.

**Comment by jwbmartin** [comment]
Looking pretty good @eatyourgreens ! I feel that the username-notifications-hamburger menu should align with the rest of the nav bar when the Zooniverse top-level nav is collapsed and it's a little close to the right margin of the page so you might want to scooch everything in a little but.

**Comment by eatyourgreens** [comment]
@jwbmartin Yeah, there's a top margin somewhere which is throwing everything out of line. I'm also seeing an annoying jump to the left, when the top-level nav opens up, because the hamburger icon and the Zooniverse logo are different widths.

@wgranger I'm not sure what's going on with IE11 but I changed the styling on that icon to be consistent with the one that opens the mobile menu. That might have fixed it.

Removing the `Zooniverse` link from the top menu seems to fix the account bar wrapping on small screens, but pushes it over to the left on pages that don't use the new layout.

I've just staged those changes, so you can have a look.

**Comment by eatyourgreens** [comment]
@jwbmartin I've reduced the top margin on the project navigation: https://fix-2846.pfe-preview.zooniverse.org/projects/eatyourgreens/-project-testing-ground
