### ISSUE TITLE
infinate copy of page nav element on subject sets page on panoptes-staging

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#2849]
When developing on `localhost` using panoptes-staging I see the following when I go to the `subjects sets` page:

![subject_set_error](https://cloud.githubusercontent.com/assets/6557526/17361309/c80b196a-5967-11e6-83fa-ad17b65a75ed.gif)

This does not happen in production (as far as I can tell).

**Comment by eatyourgreens** [comment]
Does it also happen on `localhost` if you add `?env=production` to the URL?

**Comment by CKrawczyk** [comment]
Can't check that since adding `?end=production` means you can't log in and get to the project builder.

**Comment by CKrawczyk** [comment]
I just confirmed this only happens when I am connected via `localhost`, zooniverse.org and master.pfe-preview.zooniverse.org both work as intended.

**Comment by CKrawczyk** [comment]
OK, after pointing `local.zooniverse.org` to `127.0.0.1` in my `etc/hosts` file (thanks @camallen for this trick) the issues goes away.

**Comment by srallen** [comment]
I think it's a bug with the hot reloading with webpack.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
