### ISSUE TITLE
Everything in the manifest file showing up in the metadata while classifying - 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#285]
Under every subject when classifying now is a little white icon and if you click it it says metadata and appears to be spitting out everything that was in the manifest file which includes file name and In some cases ids that could be googled whie classifying. 

Example from the Galaxt Zoo 3D
![image](https://cloud.githubusercontent.com/assets/753325/7485693/80b2b26e-f3cc-11e4-8460-6cc91d96d59e.jpg)

The manga survey Galaxy ID is visible now to a classifier where likely you want to show that info on Talk 

The best example I have is Planet Hunters, if the star id was shown then people could google snd find out it is s planet candidate and they would be more likely to mark transits (even if there wasn't one in the section of data they were looking at) so I think there needs to be either the option to turn the metadata button off in the short term and the ability later to decide which columns in the manifest are showing by the  metadata button

**Comment by vrooje** [comment]
I think this is a good idea, in part because we don't want classifiers to be able to bias their classification due to available metadata, and also because we want to encourage clients to upload value-added metadata and that sometimes includes information that should be covered by the embargo period being discussed in Zooniverse/Panoptes#618 .

As a project builder I think I'd like to be able to specify that each column of my uploaded metadata is one of the states within {visible in Classify and Discuss, visible in Discuss, not visible} so that I can give enough information to classifiers, more to those discussing classifications, and publish additional value-added information only with the full catalog.

**Comment by mschwamb** [comment]
Any chance that a  toggle on or off check box to show metadata or not in the classification interface (or to show metadata after the classification is submitted) could be added as the simplest solution?  I understand if the answer is no.

**Comment by mschwamb** [comment]
hi @aliburchard 

 @chrislintott said I should inquire about the current status of the metadata displayed with you. For soft launch, science teams will still need to segregate data we want linked to our subjects that we don't want the public to see into a separate file? currently all the contents of the manifest file is presented in the metadata on the classification page. 

Thanks, 

~Meg

**Comment by mkosmala** [comment]
Just wanted to lend my support to this issue. I also need to be able to hide some metadata from users that I will need to match classifications back to my subjects.

How far in the future of "future plans" is this?

**Comment by mkosmala** [comment]
@aliburchard @chrislintott This is a major issue for us. We absolutely cannot have our file names showing up in the metadata as viewable to users. They contain the date and time and info about the pre-processing done on the image -- things that can affect user classifications. But we need to have the file names in the metadata or else we cannot link the classifications to the images. (I made this mistake in the beta.) Renaming all our files to exclude the date/time/processing info would be a nightmare in post-processing.

Surely there must be a quick fix to allow for making invisible certain metadata fields-- even if it's something as clunky as "make invisible all fields that begin with "xx".

**Comment by brian-c** [comment]
Headers in the manifest prefixed with "#" or "//" (like comments, basically) will no longer be displayed.

**Comment by mkosmala** [comment]
Sweet! Thanks.

**Comment by vrooje** [comment]
Awesome! Will update the Kitteh Zoo manifest so we have an example of it.

**Comment by chrislintott** [comment]
Should we add text to this effect on the upload page?

**Comment by vrooje** [comment]
I added an example to the lab how-to but not to the subject uploader. Should we link directly to the manifest description in the how-to from the subject uploader?
