### ISSUE TITLE
Generalized pagination solution

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#2852]
We should make sure all paginated resources that are returned from the API are properly paginated in the UI. This is related to #2819 and #2752. There's a [paginator component](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/lib/paginator.cjsx) in the Talk UI code that is used in parts of the site. There are other instances of pagination being written as needed like in [the project builder on the subject sets page](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/subject-set.cjsx#L93-L101).

A start of a [general reusable component](https://github.com/zooniverse-ui/pagerz) began in the old zooniverse-ui, but wasn't finished. We could finish this, consider using [one that is already built](https://github.com/AdeleD/react-paginate), or make sure we write pagination consistently as needed.

**Comment by alexbfree** [comment]
+1 to this. Pagination is something we shouldn't be reinventing!

**Comment by alexbfree** [comment]
Per #2868 , we should ensure that the generalized pagination solution correctly auto-scrolls to top of page (which currently happens for Talk pages, and project Talk pages, but not for collections, project collections, and lists of projects)

**Comment by srallen** [comment]
Adding scroll behavior middleware is a generalized solution needed for the router, not for pagination. See #2762. Scroll to top fixed in #2874

**Comment by srallen** [comment]
Paginator was generalized and moved into zooniverse/Zooniverse-React-Components
