### ISSUE TITLE
Add a "..." to project nav bar to stop it breaking onto two lines

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#2858]
Now that Notifications has been moved into the project bar, and the Collect menu option has been added in Projects too (#2804) , we have the problem that menus are starting to overflow onto two lines in project navs, for projects where custom links have been added:

![screenshot 2016-08-04 16 20 35](https://cloud.githubusercontent.com/assets/1473244/17407502/6bd1aaee-5a5f-11e6-8a2c-43c4d9793bee.png)

We also know there are at least two more things to come which would make it even longer:
- Search: https://github.com/zooniverse/Panoptes-Front-End/issues/2252
- Custom Pages: https://github.com/zooniverse/Panoptes-Front-End/issues/2247

I think there are two things we should do to solve this:
1. Make Notifications into an icon: I think this could be covered by #2825.
2. Add a "..." dropdown for all custom links (as with the Daily Zoo, Blog links on Zoo nav) and, when we add them, custom pages could go under here too.
3. When we add search, make it just an icon.

What do people think of this approach? Is that a good way to go? Discussed briefly with @parrish and he seemed to be in agreement.

(Also does anyone have time to do this? I am a bit overloaded with lots to squeeze in before my contract ends!)

**Comment by alexbfree** [comment]
Tagging @srallen @parrish @jwbmartin @eatyourgreens who may wish to add your thoughts!

**Comment by eatyourgreens** [comment]
Search should probably be under Talk, rather than top level, since you can't search across a project, only Talk content anyway.

Consistency with the top menu for external links sounds good to me. When the top menu moved those into a dropdown menu, there were some comments on Talk that this made those links difficult to find.

**Comment by srallen** [comment]
I agree re: search. Search is needed for Talk, not at a top level. Custom pages and outbound links could probably go under the dropdown. +1 for consistency. Ultimately, I think this is @jwbmartin's call, but we do need to consider for the effect of hiding links under dropdowns or at the site top nav (specifically an issue for notifications). Perhaps some google analytics or geordi tracking can help us determine this.

**Comment by eatyourgreens** [comment]
If search is useful at the top level, I would consider using `input[type=search]` rather than adding a link to the navigation.

**Comment by parrish** [comment]
I agree that search should be only in talk and that the notifications link being iconified will help.

That said, I'd punt on this issue until we verify the click activity on the dropdown -- I strongly suspect it's an unnoticed junk drawer on a menu.

**Comment by alexbfree** [comment]
Good point. I will take an action to make sure we have some geordi tracking on those links.

**Comment by alexbfree** [comment]
> Search should probably be under Talk, rather than top level, since you can't search across a project, only Talk content anyway.
@eatyourgreens this won't be true with the new Project Search per #2252. It will also pull back collections, a bit like the Ouroboros search.

**Comment by alexbfree** [comment]
Out of interest, let's say we find people are not clicking the "...", what are we going to do about it? We still need some means of having more links than you can fit on the line.. Might be good to start collecting ideas about what that might be... I'm not sure there are any great options in which case the question might be somewhat moot.

**Comment by jwbmartin** [comment]
I agree with @parrish and I would say let's pull the "Contact Us" out of About make a "Contact" link and add links to the blogs within that. It's pretty standard to throw contact info, social media, and blog links under one Contact link.

**Comment by parrish** [comment]
Pretty sure this was handled to everybody's satisfaction.  Happy to start a new issue if we want to pursue any other ideas.
