### ISSUE TITLE
Removing the bottom-most external link in the project builder does not trigger XHR

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes-Front-End#2859]
Weirdly, https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/project-details.cjsx#L69 does not seem to fire if removing the last link.

Steps to reproduce:
- In the project builder, create 3 external links called "one", "two" and "three"
- Refresh the page
- Remove "three" by clicking on the "X". This will remove the link from the DOM, but you will not see a "Loading" indicator at the top of the window.
- Refresh the page
- "Three" is there again.

Further weirdness:
- Remove "three". No loading indicator.
- Remove "two". You will see a loading indicator.
- Refresh
- Both "two" and "three" are gone.

**Comment by eatyourgreens** [comment]
Maybe `.save()` needs to be explicitly called after `project.update()` here https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/project-details.cjsx#L69

**Comment by srallen** [comment]
This could be a good candidate for removing the `AutoSave` wrapper and using an explicit modal dialog for creating the external link as described in #2895. Doing it this way would also resolve #3138

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
