### ISSUE TITLE
Having a more obvious place for the controls to make a project live (public/private)

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#286]
It appears that the private project checkbox is what actually hides a project while you're building it and then unchecking it launches it lives. it's stuck in the project details. I found that really confusing (I know the description is yet to be added underneath it) having it there since you're filling out the details about the project, it felt like I was checking a box to get it eventually listed on the Zooniverse panoptes home (not launching it live). I think it would be clearer there was a section on the left hand side as a button (along with the other beta, etc. states I think you're planning for these builds to go through) to make the project live/visible or private/invisible.

**Comment by chrissnyder** [comment]
Pretty sure this was addressed in the help text update (the API is down for me at the moment, making it difficult to double-check).

Closing, but do reopen if you disagree.
