### ISSUE TITLE
Show project background image in Facebook share

### ISSUE THREAD

**Issue by ghewson** [zooniverse/Panoptes-Front-End#2862]
I'm a citizen scientist, and I wanted to share on Facebook the great background image on [Understanding Animal Faces](https://www.zooniverse.org/projects/pszmhk/understanding-animal-faces) (with the possible side-benefit, of course, of getting some additional volunteers for the project). I'm afraid I abandoned the idea.

The only image shown in the Facebook preview was the [general Zooniverse background](https://zooniverse-static.s3.amazonaws.com/assets/opengraph.jpg). Facebook used to allow you to select from among all the images on a page which to display in a share. Now, though, it seems it will only display the image in an [OGP](http://ogp.me/) og:image metadata tag (or no image).

The problem I found isn't limited to Understanding Animal Faces. Firefox has a handy View Page Info tool available from the context menu of a secondary mouse click to see the metadata, and I looked at several projects with this. All the projects I looked at which are under the zooniverse.org domain (such as [Camera Catalogue](https://www.zooniverse.org/projects/panthera-research/camera-catalogue) or [Supernova Hunters](https://www.zooniverse.org/projects/dwright04/supernova-hunters)) have the same og:image tag, i.e., the general Zooniverse background. I'm not familiar with the Panoptes code, but [it seems to be hard-coded](https://github.com/zooniverse/Panoptes-Front-End/blob/master/views/index.ejs).

I propose that the image displayed in a Facebook share should be the project background image seen by users; that is, the og:image metadata should be the project's background image.

As well as the above projects, I looked at some others with their own URLs, not under zooniverse.org. Maybe some of the older projects aren't running with Panoptes, but I know (since they publicised it) that [Notes from Nature](https://www.notesfromnature.org) switched to Panoptes. None of these projects that I looked at have an og:image tag, and Facebook (at least in preview) consequently shows no image.

Incidentally, volunteers only see part of the [complete Understanding Animal Faces background image](https://panoptes-uploads.zooniverse.org/production/project_background/d0eef5ab-9bf3-4663-a12e-13ed52750792.jpeg), which is a pity. (I checked with Firefox and Google Chrome under Linux, with windows sized in portrait ratio and full-screen.) Should this be the subject of a bug report, or is it up to the project administrator to size the image appropriately?

**Comment by camallen** [comment]
hi @ghewson I agree that this would be nice and we're looking into this but it's not a high priority.

**Comment by srallen** [comment]
Doing this would require server side rendering as described in #3766 and is not easily implemented at this time.
