### ISSUE TITLE
User profile links are inconsistent within a project's Talk pages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#2866]
If you click on a username from this page, https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/talk/115 it will take you to a user profile page for that project https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/users/StarwatcherHB

On other Talk pages, the username links back to the top-level Zooniverse profile
https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/talk/115/74131
https://www.zooniverse.org/projects/alexbfree/computer-vision-serengeti/talk/recents

**Comment by alexbfree** [comment]
Thanks. the former behaviour is the correct one. must have missed some - will take a look.

**Comment by alexbfree** [comment]
Note from Jim:

https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/comment.cjsx#L176 https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/comment.cjsx#L135

Need to check for others.
