### ISSUE TITLE
Rotate Image Tool

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#2867]
Add the ability to rotate an image as a part of the Pan and Zoom component.

**Comment by jschell42** [comment]
there's a pan and zoom component? :)

**Comment by eatyourgreens** [comment]
@jschell42 it's available as an experimental feature. You can see it in action on [Decoding the Civil War](https://www.zooniverse.org/projects/zooniverse/decoding-the-civil-war) and [Notes from Nature](https://notesfromnature.org), and the javascript code is here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/pan-zoom.jsx
