### ISSUE TITLE
Make the whole collections preview on a Talk subject page a clickable link to the collections

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2869]
I find that I'm always trying to click on the image preview of the collection on a Talk subject page to get to the collection, but that's not the link. The hyperlink is the name of the collection. I think it would be helpful if you could also click on the image preview and it could take you to that specific collection as well.

I've highlighted in cyan what I mean:
on (https://www.zooniverse.org/projects/mschwamb/comet-hunters/talk/subjects/1290935)

<img width="760" alt="screen shot 2016-08-08 at 9 07 40 pm" src="https://cloud.githubusercontent.com/assets/753325/17507635/6f5ffada-5dac-11e6-858a-42efa586587f.png">

**Comment by alexbfree** [comment]
Good idea! There should be a clickable bounding area around the photos which you can click. the images themselves shouldn't link to the subjects. 

I might look at this while addressing #2251 which uses the same collection preview component.
