### ISSUE TITLE
Removing the back button if you only have one step in your workflow/ are you at step one of the workflow

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#287]
If you've got one task or multiple annotation tasks that you ask to performed at the same time in the workflow (like P4: CTX we're asking to check all that you see in one multiple choice question), and then the classifier moves to the next subject. The back button appears in the classification interface but is greyed out and you can't click on it, but I think that's confusing for classifiers.  (screen shot below)

If you have only one step in the workflow or on the first step of the workflow there is nothing to go back to, so can the button be removed and only appear if your workflow has multiple steps/ when you get to the second step of the workflow 

![screen shot 2015-05-06 at 1 50 10 pm](https://cloud.githubusercontent.com/assets/753325/7488072/fb146ba4-f3f6-11e4-959a-e24b8a39bbf0.png)

**Comment by mschwamb** [comment]
I Imagine at this point I've lost this argument (and thought I'd go back through and tidy the multitude of tickets I have removing things that are no longer relevant). @brian-c you want to close as this as will not fix?

**Comment by aliburchard** [comment]
Actually, I'm all for keeping this open in light of decisions for the skip classification summary. Check out https://www.zooniverse.org/projects/tedcheese/snapshots-at-sea/classify -- the "skip classification summary" is enabled, allowing users to get to talk by clicking "done & talk" instead of "done". But now there are three buttons: "back" (which is disabled and irrelevant), "Done", and "Done&Talk".

**Comment by camallen** [comment]
For what it's worth, i really liked the snapshots at sea interface for the fast task..i whipped through a bunch of subjects in no time.

**Comment by aliburchard** [comment]
Yeah - I'm loving not having a classification summary for it.

**Comment by mschwamb** [comment]
I think it depends on whether there's a need for Talk or not. My bet is if you looked at the Talk entries - Planet Four: Terrains might be higher rate of people entering  than Snapshots at Sea since it's a separate decision versus having to make it at submission.We don't need rapid classifications of P4: Terrains, but we do want to make sure we get people into Talk since that's been really productive for us on top of the classifications.  My bet is there's a very different behavior with Done and Done & Talk, versus submitting your classification and then being able to move on or discuss.

**Comment by mschwamb** [comment]
Since the greyed out back button is now gone from Planet Four: Terrains as well, I think this can be closed?

**Comment by mschwamb** [comment]
closing as this has been addressed
