### ISSUE TITLE
Have a Zooniverse wide notification that will not load 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2870]
<img width="1157" alt="screen shot 2016-08-08 at 9 11 56 pm" src="https://cloud.githubusercontent.com/assets/753325/17507704/de747dba-5dac-11e6-9d1f-017f78e90058.png">

**Comment by eatyourgreens** [comment]
My notifications are doing this too. The message that won't load is a test message from @simensta  on Sunday. Console log shows `TypeError: Cannot read property 'then' of undefined` so something is going wrong with a promise somewhere.

**Comment by mschwamb** [comment]
cc @parrish
