### ISSUE TITLE
Submenu looks odd on mobile

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#2873]
Ideally we should show this as a single list on mobile:

![img_0290](https://cloud.githubusercontent.com/assets/428423/17520293/1f8a1f18-5e47-11e6-80d9-d507c48b2d9f.jpg)

**Comment by astopy** [comment]
Note that the screenshot is from #2871 but it's the same in the deployed version.

**Comment by jwbmartin** [comment]
I agree and think that this could be easily fixed if we consider my suggestion in #2858
