### ISSUE TITLE
Done button changes name depending which answer to the multiple choice question you pick

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#288]
If you click the answer for anything other than the last choice of the multiple choice question (that requires only 1 answer be selected) you get 'next' and if you click the last choice it goes to 'done'. I think that will be confusing to volunteers

See the screen shots below. 

![screen shot 2015-05-06 at 2 05 14 pm](https://cloud.githubusercontent.com/assets/753325/7488205/5cb5c27a-f3f9-11e4-940b-36e6ae61f266.png)

![screen shot 2015-05-06 at 2 05 17 pm](https://cloud.githubusercontent.com/assets/753325/7488208/686ced50-f3f9-11e4-8bae-a2c6511c3173.png)

**Comment by mkosmala** [comment]
The 'done' button changes depending on what the next task is for that workflow. If that's the last task, the button changes to 'done'. If there's another task, it changes to 'next'. I'm not sure how you'd get around that except maybe to leave it as always 'next'. (But that may not be optimal either.)

**Comment by mschwamb** [comment]
@mksomala  That's not exactly what I'm describing. It's changing text on the same task/step in the work flow depending on what answer you pick for the question if the multiple choice question requires only one answers.  I think will be confusing to volunteers.

**Comment by mschwamb** [comment]
@mkosmala no, you're absolutely correct.  I just checked, so it's a feature not a bug. so I'll close the ticket.
