### ISSUE TITLE
Confused Pairs .csv

### ISSUE THREAD

**Issue by jschell42** [zooniverse/Panoptes-Front-End#2883]
Hi, wondering if it's possible to have more than one animal be in the "confused pair" category. So, coyote is often confused with wolf, domestic dog, etc, and have more than one show up. Each time I've tried this on project #2834, i've only been able to do one and having more seems to break the project. I do see this functionality on the Camera Catalogue project, so wondering if that was a custom build or if that's in the basic Project Builder survey tool. Thanks!

**Comment by aliburchard** [comment]
@jschell42 You can find instructions for this here: https://www.zooniverse.org/projects/aliburchard/cameratraptest/about/faq

and you can post building related questions on the talk board, either for cameratraptest or the general project builder talk boards at www.zooniverse.org/talk/18
