### ISSUE TITLE
Cloning markers when marking in multi-image per subjects

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#2888]
Hi there

In our SpaceWarps demo site, several early testers have found it confusing that if they place a marker in one image it doesn't appear in all three images shown (either in multiple image view or flip-book mode). 

In our case all images per subject contain exactly the same area, so in this case placing a marker somewhere in one of the images applies to all images and the testers would have found it useful and less confusing if this marker once made was shown in all images.

Is there scope to automatically show a marker placed in one image in all images for that subject?

I realise this won't work for projects where the individual images for a subject are not of the same area.

Thanks!
Aprajita.

**Comment by eatyourgreens** [comment]
I think this would break [Solar Stormwatch II](https://www.zooniverse.org/projects/lepnoir/solar-stormwatch-ii/classify), which relies on marking the individual frames separately.

**Comment by aprajita** [comment]
OK thanks @eatyourgreens 
Could a 'clone markers in all subject images' option in the project builder be a possibility?
Thanks.

**Comment by eatyourgreens** [comment]
Possibly. Looks like this check against the frame number here would have to be overridden, but in such a way that existing projects don't break: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/drawing/markings-renderer.cjsx#L46

**Comment by simoneduca** [comment]
@aprajita you should now be able to choose to clone the markers in the project builder.
![screen shot 2016-09-06 at 14 37 00](https://cloud.githubusercontent.com/assets/8989606/18275572/7b2c8744-743f-11e6-8c50-e850498728a8.png)

**Comment by aprajita** [comment]
Excellent - thanks @simoneduca
