### ISSUE TITLE
Project freezes repeatedly

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#289]
I've received 4 comments from collaborators about my WildebeestWatch project freezing after the drawing task. And, in fact, the below screenshot shows the screen after I've tried to draw a line, but now can't seem to end the line, go back, or do anything else.

![screen shot 2015-05-06 at 10 42 15](https://cloud.githubusercontent.com/assets/6217406/7490971/a6ee4e74-f3dc-11e4-851b-04ec5607467b.png)

I've just realized this probably has to do with trying to add drawing tasks when some subjects have multiple images in them...I can see why that's a feature not planned for first release (as you've got to tie pixels to unique image IDs instead of just the subject ID), but I think it's functionality to plan for in the future. And in the meanwhile, perhaps some warning when linking a workflow with drawing tasks to subject sets that have multiple files per subject? Perhaps relevant to the discussion re: manifest structure in #282

**Comment by camallen** [comment]
@aliburchard any chance to get the console output for debugging?

**Comment by aliburchard** [comment]
I've already navigated away and revised the workflow.... so I'm assuming not?

**Comment by aliburchard** [comment]
Project is now freezing at a different stage. On Wildebeest Watch, if I select the "wildebeesties" workflow, answer "yes" to "are there wildebeest," and "yes" to "are they moving," and then select the direction(s) that the beest is moving in, the "next" button *should* switch to "done" and I should be able to end the classification.

But that's not happening.

The console output is here:
![screen shot 2015-05-06 at 11 05 51](https://cloud.githubusercontent.com/assets/6217406/7491318/61a1ce3c-f3e0-11e4-8931-0a55d24a3a2b.png)

This task in the project builder is here:
![screen shot 2015-05-06 at 11 12 52](https://cloud.githubusercontent.com/assets/6217406/7491383/ed278ac8-f3e0-11e4-8a3e-971705a7c77e.png)

**Comment by brian-c** [comment]
Looking into this now.

**Comment by aliburchard** [comment]
I'm still getting this error

**Comment by aliburchard** [comment]
I should add that this only happens when I have moving wildebeest. If I proceed down the other side of the decision tree ("no wildebeest" or "not moving") then I get the "done" button and can submit the classification.

**Comment by brian-c** [comment]
@aliburchard I couldn't reproduce this anymore, but I also just did new deploy, so maybe my fix didn't go up when it was merged. Can you do a hard reload and try again? If you can still reproduce this, please record the exact steps you took (starting from page load).

**Comment by aliburchard** [comment]
I did a hard reload, but it's happening on my iEye project as well now. 

From http://demo.zooniverse.org/panoptes-front-end/#/projects/aliburchard/iEye/ >
NerveSpotter workflow > 
"Yes, completely" for "can you see a disk" > Next >
draw a rectangle using the "disk" tool > Next >
mark some points with the "nerve" tool > Next >
draw a polygon with the "cup" tool > Next >
...and nothing happens. It's the last task in the workflow, and is labeled as such in the workflow editor. 

It's the same "undefined" error as before.
![screen shot 2015-05-08 at 16 43 57](https://cloud.githubusercontent.com/assets/6217406/7539809/764dbd4c-f5a1-11e4-9dae-fdcd7d5a95fa.png)

**Comment by aliburchard** [comment]
I'm still getting this, as are my collaborators on the whale project. Now it's happening right away and the error reads: "Failed to load resource: the server responded with a status of 404 (Not Found)" 

[trying to upload screen shot but have crap internet on the train.]

**Comment by aliburchard** [comment]
Seems all better now.
