### ISSUE TITLE
Request: List of volunteer contributors/authors

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#2891]
Some older Zooniverse projects have a page that lists volunteers that contributed to particular project. I would like to properly acknowledge Panoptes volunteers in my publications, but I don't currently have a way to do so. Can we please have a volunteer contributors page (for those who opt-in obviously)?

**Comment by camallen** [comment]
We the information via the UserProjectPreferences. @mrniaboc what were the previous policies on publishing volunteer names? We can add a field to allow users to opt in/out to publish their names on a page like this too.

**Comment by mschwamb** [comment]
@camallen that entry is already asked for for Zooniverse registered users. The Real name entry. The explicit text associated with that is: 'We’ll use this to give you credit in scientific papers, posters, etc' and there was a previous version of that on Ouroboros. 

@mrniaboc can confirm My understanding was that previous policy was that the real name  entries were listed on projecturl/authors Example is the original planet hunters authors list: http://old.planethunters.org/authors

I'd like this features as well, as I'm slowly by steadily writing up a Planet Four: Terrains paper.

**Comment by camallen** [comment]
@mschwamb understood but should we explicitly ask people to opt (like emails) in to this or should we just credit people automatically?

**Comment by mschwamb** [comment]
@camallen the real name/publishable name is optional (though on the form you might want to add 'required' on the other fields so its more obvious)  Do you want me to put a separate ticket up?

<img width="645" alt="screen shot 2016-08-17 at 6 44 13 am" src="https://cloud.githubusercontent.com/assets/753325/17745112/5292c61c-6446-11e6-9462-136dc1183a7d.png">

 It doesn't have to be filled in  (and was the same way in the past) so people are already opting in by filling it out.  I've never had any issues with putting the published name up on the authors page. I think if the person filled out the option for a Real name then it's okay to use since it explicitly says we're using this field to give you credit for your work.

**Comment by mschwamb** [comment]
So I'm planning on submitting the Planet Four: Terrains paper at the end of the month. It would be great if I was able to add to the acknowledgements the url for an authors page like many of the Ourboros projects have. The authors page was a straightforward way to give credit for people's contributions to the project. I think having that ability on panoptes where on the results page it would be an authors page using Real name entry for Zooniverse registered users would be really handy.

**Comment by mschwamb** [comment]
It's frustrating that there's no way to give credit to volunteers for their effort like on Ouroboros projects with an authors page. There's an [authors page ](https://authors.galaxyzoo.org/authors.html)for every Galaxy Zoo iteration. I would really like to be able to give credit to the volunteers who contributed to the paper for my panoptes project. I know the dedicated volunteers get a lot out seeing their name. 

I've left a placeholder in my paper manuscript acknowledgement for this, but would need this feature by acceptance/publication.

**Comment by mkosmala** [comment]
+1 
In my paper last summer, I had to create a stand-alone authors page. In terms of keeping the volunteers engaged, this seems like a fairly simple thing to do. I say "fairly," though because there may need to be a manual approval step where someone reads through the names and makes sure there's nothing offensive, that people's emails aren't showing, etc. @chrislintott and I talked about this last week...

**Comment by mschwamb** [comment]
Looks like Galaxy Zoo just got around this issue by using the username, which I think is fine.

**Comment by vrooje** [comment]
+1 to this. It would be great to click a button on Lab to generate an Authors page that gets linked next to the Results page. Project collaborators don't have access to the Real Name field in the users database (it's not part of classification exports), so they can't create the list of credited users in the same format most previous projects use. This means I have to pester @mrniaboc for a static list each time, and that's not going to scale that well.

**Comment by mschwamb** [comment]
My proofs for my accepted paper are due in a few days and it's frustrating that on custom Zooniverse projects we can credit the volunteers but on panoptes it's not possible. Given the fact the Zooniverse asks for a publishable name, I'm not sure why this can't have authors pages for panoptes projects like Ourborous projects do.

**Comment by mschwamb** [comment]
If this is something that would be available later in the year, can someone please let me know what the url address might be so I can include it in my paper's acknowledgments. I had a spot reserved in the paper acknowledgements for this, but the proofs are due back in a few days so after that the journal won't let me make changes after that. I really want to find a way to acknowledge the volunteers individually.

**Comment by vrooje** [comment]
For Exoplanet Explorers I added a list to the end of the "team" page in the
About section. I had to clean out email addresses and so on manually, so
it's definitely not ideal, but it worked for the paper submission. Could
that work here? (I got the list of users from @mrniaboc.)

**Comment by mschwamb** [comment]
That's a patch and not a permanent solution,and it means I now become responsible for keeping that up to date.  If I can easily filter out '@', '.com', '.net','.edu' entries with python then this seems easy enough to implement in panoptes. I'd even take usernames if there is worry over publishable names.

**Comment by vrooje** [comment]
Just a note if you do end up using this workaround for the immediate need:
 - If people use asterisks, underscores etc in their names/usernames it will render as markdown, so you have to either remove those or write the whole list as preformatted... in the latter case you also have to manually insert line breaks into the list.
 - I had a hell of a time with Cyrillic characters in some text editors and even in Python. I think I ended up using TOPCAT with some manual workarounds to get past the way TOPCAT truncates strings when writing to an ascii file.

PS - congrats on the accepted paper!

**Comment by vrooje** [comment]
As a broader note, another reason to have this be a built-in feature is that it very strongly communicates to research teams that their volunteers are part of their team and helps set up the environment within which they all interact.

**Comment by eatyourgreens** [comment]
Bumping this because the account settings page is confusing volunteers. They fill out the real name because we say
> We'll use this to give you credit in scientific papers, posters etc
then they're confused when it isn't used (because `user.credited_name` is a private field in the API.)

**Comment by camallen** [comment]
seems to have crept in [via this commit](https://github.com/zooniverse/Panoptes-Front-End/pull/311/commits/8fae22ad3de2d12118d748d39e1a89a5f7566185). This should never have said that your credited name is public - we can make that information public but that change would lead to publishing personally identifiable information.

**Comment by mrniaboc** [comment]
For acknowledgement we should just have an autopopulated page showing the credited names of volunteers who have performed at least one classification. Just like the team page that automatically shows any collaborators. This means we're not giving data dumps that tie people's real names to their other information.

**Comment by mschwamb** [comment]
@mrniaboc that would be great. That's the solution I've been asking for.

**Comment by eatyourgreens** [comment]
@mschwamb this would require Zooniverse/Panoptes#2433 but your comment on that issue says you'd prefer to get the names of volunteers by hand, which seems impractical.

**Comment by mschwamb** [comment]
@eatyourgreens  only if I'm looking for one or two people's name. I'm saying there should be an automatic authors page, but if I need the usernames of two specific volunteers for authorship on a publication than that should be asking the Zooniverse team directly or another method. 
The reason being is that I believe  having people's publishable name added to the classification dumps (ie linked to usernames) would require me to have human study clearance. Currently Oxford has that clearance. Since researchers get username or a proxy for ip address (but no the ip address) I have no personal information about the volunteers and don't need that training or institutional clearance. If you link the published name with the user_id that might be deemed personal information and therefore mean I need to get the training.  Best to talk to @chrislintott since he's dealt with this for Planet Hunters many times and I'm sure other Zooniverse projects.

**Comment by eatyourgreens** [comment]
@mschwamb if you're going to generate a list of names automatically then you're going to need permission to get those names from the Panoptes API, which requires zooniverse/Panoptes#2433

**Comment by mschwamb** [comment]
@eatyourgreens  Why would as a project owner need to permission to access those names if they are displaying on the site like the team page. I don't understand how the project owner is involved in that?

**Comment by eatyourgreens** [comment]
@mschwamb the project owner would generate the page content in the project builder, so need permission to get the names from the API.

**Comment by vrooje** [comment]
I like the model @mrniaboc (and @mschwamb I think) seemed to be suggesting above, that each live project has an authors page auto-generated without the project owner needing to (or being able to) intervene.

**Comment by camallen** [comment]
@vrooje definitely agree we should have support for this as a batch job server side to create the page in the API (maybe a weekly schedule). 

That said there are use cases like SkyMapper (what @eatyourgreens is referring to) that want to credit specific users for ATel like reports so they need to get these names from the known user login via an API call.

**Comment by chrislintott** [comment]
Just a note that the general (page) solution seems like a good idea.

If we're implementing access to this information via API, we'll need specific controls for that as we could only turn it on for some project owners.

**Comment by vrooje** [comment]
Spurred by the need for an immediate solution to credit PRN volunteers, I wrote [`make_author_list.py`](https://github.com/zooniverse/Data-digging/blob/vrooje/example_scripts/make_author_list.py), which creates an author list in markdown after stripping various email-address characters. It can do so as normal text or as pre-formatted text for copy-pasting into a project Team or Results page. 

(A bit of detail that might be useful to others: I generated a list of users ranked in descending order of classification count using [`basic_project_stats.py`](https://github.com/zooniverse/Data-digging/blob/vrooje/example_scripts/basic_project_stats.py), which does this automatically, and sent that to @mrniaboc for matching up to `credited_name` values. That matched list came back in a different order than what I'd sent (alphabetical, I believe) and the info needed to re-order the way I wanted was gone from that file, so I also wrote [`match_user_lists.py`](https://github.com/zooniverse/Data-digging/blob/vrooje/example_scripts/match_user_lists.py), which just re-matches back into the desired order. Then I fed that into `make_author_list.py`, which will read from the `credited_name` or `real_name` if it exists, and username if it doesn't. *But* if you already have the list with credited names and in the order you want, you won't need anything but `make_author_list.py`.)

**Comment by mschwamb** [comment]
Missed the stalebot message. I think this is still needed. Re-opening for stalebot to close it again if needed.

**Comment by mrniaboc** [comment]
I was talking about this today and I still think it's a no brainer that we should auto-generate a contributor page like this.

**Comment by eatyourgreens** [comment]
Linked to zooniverse/Panoptes#2433.

**Comment by vrooje** [comment]
Update: during SGL 2018 I updated [`make_author_list.py`](https://github.com/zooniverse/Data-digging/blob/vrooje/example_scripts/make_author_list.py) to fetch the `credited_name` field from the API when making the author list. It works but it's pretty slow for a large list of users because it gets them one at a time (I haven't looked into whether the API can return a list all at once). And it still requires the project owner to fetch a list of users (e.g. from a classification export) and is a static list of users, not something that auto-updates.

**Comment by mrniaboc** [comment]
Just pinging to keep this alive as it's still very desirable.

**Comment by vrooje** [comment]
Perhaps this would make a good hack day project...

A related question is whether I can get a list of `credited_name` values from the API by passing a *list* of IDs or user names, instead of one at a time like I'm doing now -- and which is very slow.

**Comment by adammcmaster** [comment]
@vrooje Yes, you certainly can pass a list. If you install the next pre-release version of the python client you can do something like this, where I pass a `set` of users directly to the `User.where` method:

https://gist.github.com/adammcmaster/3f101fc50da68837bc08171d094b4556#file-get_credited_names-py-L8

Behind the scenes that will batch up the users into sensible-sized groups and make one combined API call for each group.
