### ISSUE TITLE
Replace AutoSave component with modal form

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#2895]
One of Brian's suggestions before he left: replace the AutoSave component in the project builder where appropriate with a modal form with an explicit save and cancel button and a place in the UI for error messaging. This would greatly improve the UI/UX for project builder. The field guide editor currently does this and can be looked as an example for implementation.

**Comment by mschwamb** [comment]
related to #581

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
