### ISSUE TITLE
Impossible to set the range of classification stats as needed. The page reloads and scrolls up before I finish the setting.

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2898]
When I click to change the range of Classification Stats graph the page reloads and scrolls up before I finish setting the range. It happens too soon, there is actually no time for setting the range as the page reloads and scrolls up immediately as the cursor starts moving even before it gets to the needed place and even before I release the pressed mouse button. It means that I don't see the cursor while setting the range of the graph and I don't know how much to move it to get the range I need.

I would expect it to let me finish the setting, and not start reloading before it is set (in case the reloading is necessary, is it?) And after it reloads it also should take me back to the graph I was setting up (as there are more of them on the stats page).

By *finish the setting* I mean after I release the pressed mouse button. Currently it happens while the button is still pressed.

Using Chromium 48.0.2564.82 on Ubuntu

**Comment by camallen** [comment]
@CKrawczyk thoughts?

**Comment by CKrawczyk** [comment]
It looks like the front-end now scrolls back to the top whenever the URL is changed, since the stats page updates the URL every time the range is set (to create a permalink to the selected range), it keeps scrolling up.  

I will look into this later this week unless somebody else gets to it sooner

**Comment by yshish** [comment]
Thanks!

**Comment by srallen** [comment]
@CKrawczyk I added react router scroll middleware to close the issues where this behavior was desirable (pagination). Check out its readme for writing a custom scroll handler so certain routes can be skipped: https://github.com/taion/react-router-scroll

**Comment by yshish** [comment]
It's working perfectly for me. Thanks! :)
