### ISSUE TITLE
Added subjects but had to log out and log back in for the interface to be able to access them

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#290]
Not sure if this a known bug or not. Also I don't know  if this the appropriate place to list this. I had added 2 more subjects to my set successfully and then went the classify interface and classified the subject previously uploaded a few days ago fine and then it complained there was no more subjects associated with the set. I had to log out and log back in and then the interface loaded the next new subject with no complaint.

**Comment by edpaget** [comment]
Yup this is related to https://github.com/zooniverse/Panoptes/issues/787
