### ISSUE TITLE
SETTINGS & COLLABORATORS links are broken for FAVORITES.

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#2906]
SETTINGS & COLLABORATORS links, in FAVORITES(_only_) collection's:

Are using:
`https://www.zooniverse.org/` **favorites** `/<user>/<favorite>/...`
`https://www.zooniverse.org/projects/zooniverse/<project>/` **favorites** `/<user>/<favorite>/...`

While they should be using:
`https://www.zooniverse.org/` **collections** `/<user>/<favorites-title>/...`
`https://www.zooniverse.org/projects/zooniverse/<project>/` **collections** `/<user>/<favorite>/...`

**Comment by alexbfree** [comment]
Thanks for reporting this, I will take a look.

**Comment by MvGulik** [comment]
@eatyourgreens: Thanks. :-)
