### ISSUE TITLE
hide the '!' for Talk metadata if the column head in the metadata file has a '!'

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2907]
With the new feature to have metadata that only shows in Talk it looks a bit weird when you view it to have the '!' If that could be removed from the string when displayed it would look nicer.  cc @parrish 

<img width="1153" alt="screen shot 2016-08-22 at 11 21 34 pm" src="https://cloud.githubusercontent.com/assets/753325/17886907/af1dafc8-68bf-11e6-9523-0db3c6ab73f7.png">

**Comment by mschwamb** [comment]
Thanks @parrish

**Comment by alexbfree** [comment]
How interesting, I didn't even know about that feature. Was it announced/documented anywhere?

**Comment by mschwamb** [comment]
@alexbfree it's new. It's now in the project builder help I added a PR request that got merged and #2904 addresses it in the other help documentation.
