### ISSUE TITLE
Tutorial persists if you press back button

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#2909]
I'm seeing project tutorials persisting when I go back on Chrome.

![image](https://cloud.githubusercontent.com/assets/5321335/17892946/a03adc5c-693b-11e6-9962-7b00ba33cf96.png)

**Comment by srallen** [comment]
Mini-courses should be checked for this bug too.

**Comment by wgranger** [comment]
Alternatively, you could pass the prop `required: false` to a Dialog component and this issue would be resolved. That would also allow a modal to close by hitting escape or clicking outside of it. However, in the past there has been some request to only allow a modal to close by hitting the X button. 

https://github.com/zooniverse/Panoptes-Front-End/issues/1967
