### ISSUE TITLE
Glossary page

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#2912]
We use a lot of terminology which isn't obvious to new users. Having a glossary would be super helpful.

**Comment by mschwamb** [comment]
@astopy  for project builders -  like what's a workflow, classification, metadata, subject,  API, etc? 

Happy to help with this if there's someone from the Zooniverse core team that can work with me on this. @astopy maybe we can come up with a list of terms and I can slowly come with definitions for you to review when I have a free time?

**Comment by alexbfree** [comment]
I think it's a great idea. It should be aimed at volunteers too not just project builder.
A few other terms that could be included: project, export, aggregation, annotation, marks, tools, tasks, gold standard, collection, favorites, favorites collection, user profile, project owner, research page, FAQ...

**Comment by astopy** [comment]
@mschwamb That'd be great if you can help with that.

I think we've got a fairly decent list of terms to start with there.

**Comment by mschwamb** [comment]
Yep. I'll assign myself and start a document. I'll aim to get a few done over September. @astopy if you can build the page with that content after I get a few terms defined, then I can add things as I get time going forward. Does that sound good? 

I'll post here when I've got some terms defined

**Comment by astopy** [comment]
Sure. I'm away from mid-September until early October, but I can look at building the page after I get back.

**Comment by mschwamb** [comment]
I  won't have terms before October so good timing.

**Comment by BNewing** [comment]
Hi Megan, I'd be happy to help with this too! Are you working on them in a google doc? Cam's just shown me how to create new pages too so should be able to help with getting it put up.

Where do you think would be the best place to put it? On the About section or somewhere in the Projects section?

**Comment by mschwamb** [comment]
Hi @BNewing  (feel free to call me Meg :-) ) - I haven't started but we could use a shared google doc. Although volunteers might sue this I think primarily it will be project builders so I'd maybe have a link under quick links https://www.zooniverse.org/lab or something like that

**Comment by BNewing** [comment]
Hi Meg :D feel free to call me Bev too! I've just set up a google doc which you can access here https://docs.google.com/document/d/1MoNHUNNaC6m1m60WAqMt-BnZOZWznk6YIzre68eF4J0/edit?usp=sharing I'll start defining the terms too :D

That sounds like a good place! Another thing I'm going to be working on is adding in a lot more documentation around building projects, and as part of that process I might restructure it to fit all the extra stuff I'm going to be adding in - into almost a wiki-type structure. But that's quite ambitious so will see how that goes!

**Comment by astopy** [comment]
@BNewing Just to note, I've edited your comment to remove the google docs link because anyone with the link can edit the document and these comments are public.

**Comment by BNewing** [comment]
Sorry Adam!! What is the best way of sharing the link or working collaboratively on the definitions? Creating the page in a branch and adding stuff to that?

**Comment by astopy** [comment]
No problem. The Google doc will work fine, I'd just send the link by email instead.

**Comment by mschwamb** [comment]
@BNewing  - Adam, Cam, Grant, Chris, etc have my email if you need it. I'm not on the slack channels.
