### ISSUE TITLE
Sub-task editor needs clear save function (or else to communicate that you just hit "x")

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2917]
I think adding sub tasks is a bit confusing at the moment, because it's not clear when a task has actually been added. I realize it uses the same auto-save as the rest of the editor, but since it's a pop-up, I keep finding myself hitting the "add task" button to close and save the new sub-task -- and of course, that simply adds _another_ sub-task.

![screen shot 2016-08-25 at 15 01 54](https://cloud.githubusercontent.com/assets/6217406/17972091/7cce209e-6ad5-11e6-9167-6e7fbfdb8bb9.png)

**note that the Ali UX request label was requested by Chris as an Ali-brain-dump, so take all this with a grain of salt.

**Comment by srallen** [comment]
Related to #2895

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
