### ISSUE TITLE
remove pop up on new project creation?

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#2918]
There's now a modal that asks project builders to enter a name and description when they click "new project." I find that this creates a barrier to entry because project builders suddenly get stuck on what to name their project and how to describe it, instead of just diving into the building.

**Comment by mschwamb** [comment]
I think that would be helpful to get people straight in

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
