### ISSUE TITLE
Category filters for the projects page to make it easier to search through for a project you're interested in

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#292]
This might be a symptom of the people making lots of projects to test things out, but it would be nice to have filters like Zooniverse home by subject when perusing the project, especially if this is launching with more projects than fit on one page.  I think then the builder of the project should specify the category from a set of options ie space, physics, humanities, physics, climate, etc like the way Zooniverse home does. You could for now use the same categories Zooniverse home has. Just a thought.

**Comment by mschwamb** [comment]
This was added to Future plans, but will all of the Zooniverse projects now listed, but  I'm finding it hard to go through the project lists to find the project I'm working on to even check what text shows up on the Zooniverse home listing. if there is time to add in category filters before switching this to the active Zooniverse homepage I think that would be really helpful from a volunteer perspective.

**Comment by chrissnyder** [comment]
Closing in favor of #701 and zooniverse/Panoptes#1034
