### ISSUE TITLE
Last visited project pictures don't load on https://www.zooniverse.org/ 

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#2921]
When I load https://www.zooniverse.org/ the four last visited project pictures don't show up. The browser console shows this error:

>Failed to load resource: the server responded with a status of 416 (Requested Range Not Satisfiable)

I tried load it signed in and then again after I signed out and signed in back again. The result was the same. 

I used incognito window in Chromium 48, Ubuntu.

**Comment by yshish** [comment]
Oops, that error message has probably nothing to do with that as it mentions this video link: https://www.zooniverse.org/assets/home-video.ogv 

But it shows also these two errors:

Failed to load resource: the server responded with a status of 401 (Unauthorized) https://www.zooniverse.org/oauth/token 

Failed to get bearer token  
vendor-beb57659d335131a9500.js:12

**Comment by camallen** [comment]
I think this has todo with projects that have been turned to private after you've beta tested them. We can do more filtering on this before we attempt to show the project cards.

**Comment by yshish** [comment]
Not sure how you mean that, the project pictures which didn't load for me are for Penguin Watch, Chimp&See, Science Gossip, Snapshot Serengeti. When I display my personal stats (the ribbon) all project pictures are there, even these four.

I've just tried to make a classification to Plankton portal and reload the Zooniverse home page. The PP was the only one which displayed there, but the three other project pictures didn't.

**Comment by camallen** [comment]
The last set of error messages are expected if you are signed out. 

How do you know which projects should be displayed if you can't see them....? Can you provide a screenshot perhaps?

**Comment by eatyourgreens** [comment]
Sounds like an error fetching the project avatars. Recent projects makes separate API calls for those. 

I did a couple of classifications for Science Gossip and the picture shows up on my phone.

**Comment by eatyourgreens** [comment]
![image](https://cloud.githubusercontent.com/assets/59547/18033514/4a754bda-6d1f-11e6-9efd-6d3f803c454f.png)

**Comment by yshish** [comment]
This is what I see - it displays the project names but not the pictures:

https://drive.google.com/file/d/0B3yzHuLZuyBnSEU5UDFvMWdDZ0U/view?usp=sharing

**Comment by eatyourgreens** [comment]
No project owner names there either, so I think `getDetails()` is failing in the Project Icon component. https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/project-icon.cjsx

**Comment by camallen** [comment]
@yshish any chance of a screenshot of the network console outputs? The project / owner name / avatar calls are some of the later ones on that page (try clearing the network console and reloading to get a fresh view).

**Comment by yshish** [comment]
Here you are:
https://drive.google.com/file/d/0B3yzHuLZuyBnLUx3c1RZSGExUTg/view?usp=sharing

**Comment by camallen** [comment]
Thanks ;) pretty close but can you provide the network logs instead of the straight console output? Feel free to just replace the link you've posted above... 

It's the network tab near the console in dev tools e.g. 
<img width="666" alt="screen shot 2016-08-28 at 15 43 59" src="https://cloud.githubusercontent.com/assets/295329/18034490/522f639e-6d36-11e6-9327-415f7f75f9cd.png">

**Comment by camallen** [comment]
Thanks for the network details @yshish it all looked fine. I've reproduced this by classifying on the chimp & see site and got this error `Uncaught (in promise) TypeError: Cannot read property 'href' of undefined(…)`

I think this is happening where the recent project is clashing with the featured projects (chimps is a featured project) and the data is being pulled out of the cache but it doesn't have a full api response as its using cards flag instead, see [here](https://github.com/zooniverse/Panoptes-Front-End/blob/0f01152191c87f37967ee90b4a9d8d37ac1e3775/app/pages/home-logged-in.cjsx#L93)

I think we should just migrate the latest projects to use the cards too and it'll be faster and won't clash with the featured ones. 

This is really important, we really should be checking the request params for the caching layer as this will break a lot of stuff down the line if we allow api responses to be customized per attributes, etc.

**Comment by srallen** [comment]
@wgranger can you check to make sure the new signed in version of the home page doesn't have the same caching issue?

**Comment by eatyourgreens** [comment]
#2882 updates Recent Projects to use the project cards API call, at the expense of losing the owner names from the cards.

**Comment by eatyourgreens** [comment]
@camallen could you raise an issue on [zooniverse/json-api-client](/zooniverse/json-api-client) about caching? I think the API client caches resources by type and ID. Maybe `projectCard` needs to be a distinct resource type from `projects`, otherwise the API client is going to expect the resources returned by that call to match the resources returned by any other `projects` request.

**Comment by wgranger** [comment]
@srallen I think we're good on the new signed in version. The cards flag isn't being used, so the resources should have full info.

**Comment by eatyourgreens** [comment]
@wgranger I don't know if this overlaps with what you've been doing but #2928 optimises those calls by loading in the avatars and owners when the projects are requested.

**Comment by srallen** [comment]
Ok, I'll look it over again. I only did a pass on the javascript yesterday, so I still need to review the CSS.

**Comment by srallen** [comment]
Just realized this is the issue about caching and not the signed in page PR... so my comment doesn't totally make sense.

**Comment by wgranger** [comment]
I believe this was fixed with #3124 . Both `RecentProjects` and `FeaturedProjects` are pulling the card resource, and there doesn't seem to be conflict with the project image. I'm going to close this unless there is any remaining issue.
