### ISSUE TITLE
are email notifications working?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2926]
I know the email system switched over to a new one. I noticed that I didn't get a email when I get mentioned in [this](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/29/82918?comment=156192) thread.  I pretty sure I didn't get an email and checked my trash and spam folders. Thought I'd mention it in case there was something hiccup with email notifications and the new email system. Maybe this is for @parrish ?

**Comment by camallen** [comment]
Looks like emails are being sent ok, @mschwamb can you please double check the email notification settings for your account?

**Comment by parrish** [comment]
Hmm... I found the notification.  It's marked as delivered.  Maybe check your spam folder?

**Comment by mschwamb** [comment]
Yep. checked my email settings first, but the scenario @parrish mentioned is what happened. I didn't realize that bit that if I've seen it on the notifications page and hit read, it wouldn't send the email the next day if you  don't have immediate non-read notifications. That might very well be me being stupid, but would it be a worth a note in email preferences section about that?
