### ISSUE TITLE
I can edit projects I don't have a role on

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#293]
If I put in a project's lab url (e.g. http://demo.zooniverse.org/panoptes-front-end/#/lab/<insert project num>) I can actually see the project editor. Doesn't save the changes, but I can see everything. Even though I'm not a collaborator on that project in any way.

**Comment by camallen** [comment]
So this is only for public projects (logged in & out) and you can't edit but you can view them in the lab. 

Seems the front end is requesting the project details without checking if the user is logged in and then if the user has any owner / collaborator roles on the project. This may actually be a feature for all public projects but in my mind this view should be disabled unless you have the owner / collaborator roles for the specified project via `/api/project_roles?project_id=X`

**Comment by brian-c** [comment]
See #270.
