### ISSUE TITLE
Different sizes to background image on landing page and classify page

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2935]
## Expected behavior

Same size for background image on landing page and classify page
## Current behavior

See [video](https://drive.google.com/file/d/0BzeL_TYT7IYPcHVxWkhMWXJQNXM/view?usp=sharing)  showing current behavior and how it's more zoomed in on landing page than on classify page
## Steps to replicate

Click between landing page and classify page on any PBBP project
## Additional information
- **Operating system:**
  I've only tested this on a Macbook pro 
- **Browser:**
  Chrome v 

52.0.2743.116

**Comment by trouille** [comment]
@eatyourgreens Tagging you in this just as a double check whether this is done on purpose for some reason that I'm not aware of. @srallen didn't think there was a deliberate reason this the way things currently work. She thought it might just be a difference in the css from one to the other, that we could fix.

**Comment by eatyourgreens** [comment]
Sorry, but I've watched that video five or six times and the background jpeg looks exactly the same size to me. I'm not sure what I'm supposed to be looking for.

Is it that the background is centred vertically, so the visible portion changes depending on the height of the classify page and your browser window?

**Comment by eatyourgreens** [comment]
Wait, I had a look at https://www.zooniverse.org/projects/zooniverse/arizona-batwatch/about/research and the background image is absolutely massive. No idea what's going on here but it might be related to the project pages now being rescaled to show/hide the Zooniverse navigation. That's just a guess, though.

**Comment by eatyourgreens** [comment]
The background is sized using `background-size:cover`
>A keyword that is the inverse of contain. Scales the image as large as possible and maintains image aspect ratio (image doesn't get squished). The image "covers" the entire width or height of the container. When the image and container have different dimensions, the image is clipped either left/right or top/bottom.
from https://developer.mozilla.org/en-US/docs/Web/CSS/background-size

So I guess the browser is scaling the image as per the spec?

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
