### ISSUE TITLE
Abiltiy to stay in expert mode for more than one classification

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#2939]
## Expected behavior

I should be able to do a session as an expert, so i can stay in expert mode until i choose to leave it. This would change the UI to make it clear that i am in said mode (think admin mode).
## Current behavior

I get kicked out of expert mode after each classification, this was a conscious decision to ensure users don't mark as expert all the time (and leave it on). We could look at session storage and UI components to signal that they are in expert mode instead of just dropping out after each time. 

Should we do this based on the fact it was a conscious decision, i think yes but it requires some thought about UI signaling the importance of this mode to a user.

**Comment by srallen** [comment]
I'm gonna add the design label to this for Jordan's input.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
