### ISSUE TITLE
Customize landing page

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#295]
Feel free to mark this 'Future plans', but I just want to have an open issue that formally requests more control over the look and feel of the landing page. Specifically, I think it's important to be able to have more than just plaintext on the page, including multiple text styles, text alignment, images, and hyperlinks. I think this could easily be accommodated with a new project parameter that renders in Markdown and is separate from 'description', which must be plaintext for other areas of the site.
(This is a continuation of the discussion in closed issue #233.)

As reference, here are the landing pages of the four most recent Zooniverse nature projects:
![floating_forests](https://cloud.githubusercontent.com/assets/1066340/7522550/e6f53cca-f4c3-11e4-8b4e-41f041702833.png)
![penguins](https://cloud.githubusercontent.com/assets/1066340/7522551/e6f7d732-f4c3-11e4-8f4f-f25e6f5e7aee.png)
![condors](https://cloud.githubusercontent.com/assets/1066340/7522552/e6f87dea-f4c3-11e4-8b17-e215b552d2e2.png)
![chimps](https://cloud.githubusercontent.com/assets/1066340/7522549/e6f41eda-f4c3-11e4-9bcf-d8e18ca8d9cd.png)

**Comment by aliburchard** [comment]
I agree with this wholeheartedly. At the very, very least, we need to be able to have a couple different styles of text on the landing page.

**Comment by aweiksnar** [comment]
@heathv should have authority on this one. 

IMO choosing from a few predefined wordpressey layout templates that look good would be ideal, but probably a longer term goal if we can launch with just one that looks great

**Comment by heathv** [comment]
+1 for @aweiksnar 

I definitely agree that templates will be the answer. How far down the road that is I don't know. The tricky bit is allowing a good degree of customization while maintaining the same degree of quality (Squarespace is a great example of this) among all projects.

**Comment by aliburchard** [comment]
I love the idea of templates. I think that for now, just the most basic basic ability to provide a "header" and "text" for the description would suffice, instead of all plain text:
![screen shot 2015-05-08 at 14 09 01](https://cloud.githubusercontent.com/assets/6217406/7536891/cf46c918-f58b-11e4-8d43-d7a7581197dc.png)

**Comment by simoneduca** [comment]
The idea of templates has been recently revived. Does anybody know at what stage we're with this? Perhaps @jwbmartin?

**Comment by jwbmartin** [comment]
@simoneduca it's been tabled for awhile but I should be getting back to this starting this week if I'm not mistaken.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
