### ISSUE TITLE
notifications button doesn't unfll after you've read all your notifications

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2951]
When you read your unread notifications the notifications icon stays filled which was confusing. If the page reloads or you navigate to zooniverse home and back then the icon unfills. If you stay within the project level since the page never reloads the icon stays filled which is confusing. Can you make the icon unfill when you hit the 'read' button.  Maybe for @parrish 

I tried this on Firefox on mac. 

I read my notifications and hit the button:

<img width="1144" alt="screen shot 2016-09-02 at 6 51 01 am" src="https://cloud.githubusercontent.com/assets/753325/18211656/81d418f4-70da-11e6-9e35-c5a1a7da4e62.png">

then I go to classify

<img width="1168" alt="screen shot 2016-09-02 at 6 50 52 am" src="https://cloud.githubusercontent.com/assets/753325/18211651/7cfcd58c-70da-11e6-8760-416062302142.png">

icon is still filled so it looks like I have notifications when In don't 

 Also a comment on the new suggested form for filling out a github issue for this repo. Maybe for @srallen ?  It's geared towards bug fixes, but I thought this was also a place for feature requests. I'm not sure how I would fill out the suggested form to ask for new features not available because there is no expected behavior. Where do feature requests go?

**Comment by parrish** [comment]
Yep, verified.  I'll have a think about how to fix this.

**Comment by mschwamb** [comment]
Thanks @parrish
