### ISSUE TITLE
Create classification data export filtered by subject set (front-end piece)

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2953]
_back-end coordination needed_
## Expected behavior

In Project Builder, Data Exports, can optionally filter classifications export .CSV by subject set. Possibly with dropdown, that sends subject set ID as param to back-end classification CSV creation end point.
## Current behavior

N/A
## Additional information

-Snapshot Wisconsin will need eventually

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
