### ISSUE TITLE
Create an experimental tool/feature that allows task answers to persist if go back to previous task(s)

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2956]
## Expected behavior
Clicking the Back button will not clear work for current task.

## Current behavior
Clicking the Back button will clear work for current task.

## Steps to replicate
any workflow with more than one task, or [this demo workflow](https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=1&workflow=2426)

**Comment by eatyourgreens** [comment]
Just a note that this breaks if you have branching questions in your workflow. 

I think @simensta is doing some work on this too.

**Comment by trouille** [comment]
This will be an experimental feature that will be turned on only for specific projects like Notes from Nature, which will benefit from this. 

Importantly -- this is not something that we want to turn on across all projects.

**Comment by mcbouslog** [comment]
see [zooniverse-readymade](https://github.com/zooniverse/zooniverse-readymade) and Penguin Watch.

**Comment by mcbouslog** [comment]
notes from initial discussion, subject to edit...
- initial scope limited to NfN use case - linear workflow with text, dropdown and combo tasks
- functionality toggled on project's admin page
- if click Back button, store answers
- have state that's a boolean for if going back and forth
- maybe create helper, with add/remove/edit/delete methods
- review Task Hooks (`app/classifier/index.cjsx`), possibly helpful
- clean-up answer storage on Next and Done
- see seenThisSession for possible reference

Steps Forward
- [ ] create branch with initial admin toggle, push up to allow collaboration
