### ISSUE TITLE
use subject metadata to pre-populate task answers

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2957]
## Expected behavior

Have subject set with mixed metadata, i.e. some subjects with country, state and county, some without. Workflow includes tasks that ask for country, state and county. If specific subject has metadata that matches task, that task is pre-populated (and disabled?) accordingly.
## Current behavior

N/A

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
