### ISSUE TITLE
add descriptive names to tutorials

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2959]
## Expected behavior

Add ability to add descriptive name to tutorial, so collaborators can differentiate between tutorials.
## Current behavior

Tutorials displayed by ID.

**Comment by srallen** [comment]
A `display_name` field needs to be added to the Tutorial resource. This is a back end issue first, then we can add the UI in the editor.

**Comment by trouille** [comment]
@zwolf @mcbouslog Wondering if this is something we could try to address in the latter half of the week. Wondering if it could be a smaller project to take on during PFE improvements week.

**Comment by zwolf** [comment]
Closed by https://github.com/zooniverse/Panoptes/pull/2085

**Comment by mcbouslog** [comment]
Thanks @zwolf! 

Reopening for UI piece.
