### ISSUE TITLE
add stat for registered volunteers participated in workflow

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#2960]
Panoptes question, putting here for Milestone/planning purposes.

Add stat for registered volunteers participated in workflow to workflow resource.

**Comment by trouille** [comment]
@CKrawczyk Is there a reason in your original making of the statistics pages that you didn't include this? Just wanting to check in to see if there might be something we're not thinking of here.

**Comment by CKrawczyk** [comment]
Could you clarify what you mean by this?  Do you mean showing how many classifications came from registered volunteers as opposed to unregistered ones?  If so, as long as the API allows for this type of query (not sure it does) is should be easy enough to add it.

**Comment by trouille** [comment]
<img width="1062" alt="screen shot 2016-09-06 at 5 18 13 pm" src="https://cloud.githubusercontent.com/assets/4975655/18293058/2cb3bc60-7456-11e6-9c51-17cf7564749c.png">

**Comment by CKrawczyk** [comment]
@camallen does the API have a way to get the number of registered users that have classified on a particular workflow (as opposed to the full project)?

**Comment by camallen** [comment]
Not currently but we can do.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
