### ISSUE TITLE
'done & Talk' button now showing for all projects even though the summary page is active and there is not supposed to be 'done & talk'

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2963]
Now all my projects have 'Done & Talk' and 'Talk'.   I think that less people enter Talk with 'Done & Talk' projects  because volunteers don't know what it means so they hit Done because they want to move on quickly. My understanding was that 'Done & Talk' and 'Done' was only going to be an opt-in feature for projects that wanted quick review where Talk wasn't improved and that a project owner could have the summary page and the option to have 'done' and then the summary page where it would be 'talk' and 'next' 

 By having the summary and seeing 'next' or 'talk' got more people in Planet Four: Terrains Talk then we ever got into Planet Four which effectively has the same thing as the 'done & Talk' and 'done'  By having the summary page I think I get way more people into Planet Four: Terrains talk. 

Is this a bug? or were all summary pages taken away?

**Comment by mschwamb** [comment]
Correction: There's actually still the summary page when I submit the 'done'. So it looks like a bug where now the 'done & Talk' shows on all projects. 

<img width="1154" alt="screen shot 2016-09-03 at 7 36 44 pm" src="https://cloud.githubusercontent.com/assets/753325/18229256/f891a3d8-720d-11e6-9adb-d094bb5e0dac.png">

<img width="1127" alt="screen shot 2016-09-03 at 7 36 50 pm" src="https://cloud.githubusercontent.com/assets/753325/18229258/fd4c0954-720d-11e6-8a2c-41a4b64b303a.png">

<img width="1127" alt="screen shot 2016-09-03 at 7 36 55 pm" src="https://cloud.githubusercontent.com/assets/753325/18229260/00007a4a-720e-11e6-8bff-e684387b6cc6.png">

Checked Chrome and Firefox on mac

**Comment by mschwamb** [comment]
Also if there's more than on step the back button is showing greyed out on the first step of the workflow. I'm pretty sure that was  hidden on the first step awhile ago but introduced back with this bug. 

<img width="1127" alt="screen shot 2016-09-04 at 11 21 36 am" src="https://cloud.githubusercontent.com/assets/753325/18233965/d08644fa-7291-11e6-8ae3-9de30b670a60.png">

**Comment by eatyourgreens** [comment]
I don't think we hid the Back button, but it looks to me as if the check for Gravity Spy gold standard subjects here is overriding the workflow configuration setting https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/index.cjsx#L172

Pinging @srallen for this one.

**Comment by mschwamb** [comment]
@eatyourgreens Brian hid the back button in a pull request a while back if you're on the first step.  I closed  #287 because he added it, but he didn't link the ticket in his PR.

**Comment by eatyourgreens** [comment]
@mschwamb I checked out #2189 and ran it on my mac. It disabled the back button, which showed as it does now, but didn't make it invisible.

I also had a quick look through the commit history since then, but didn't see any changes that hid the back button completely.

**Comment by mschwamb** [comment]
Thankss @eatyourgreens ,  I'm thinking of #2189 that back disappears if you only have one step and not remembering it correctly.
