### ISSUE TITLE
Field guide help text only shows when you create a field guide

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2964]
The field guide page is completely empty in the project builder. Not even a line explaining what a field guide is. I wouldn't know what this is and if I need it for my project. If you hit create the field guide help text shows. I think that should get moved to the top so it shows when a project builder goes to the page. Currently this help text is the only documentation of the field guide as it's not in the[ How-To](https://www.zooniverse.org/lab-how-to) documentation. Or maybe separate help text just for the top of the page is needed?

<img width="1113" alt="screen shot 2016-09-03 at 7 46 55 pm" src="https://cloud.githubusercontent.com/assets/753325/18229304/fccf7a86-720f-11e6-9b5f-adfa12530ab6.png">

<img width="1134" alt="screen shot 2016-09-03 at 7 46 47 pm" src="https://cloud.githubusercontent.com/assets/753325/18229305/0514bfbc-7210-11e6-9ba0-04c07be7dd86.png">

cc @srallen

**Comment by srallen** [comment]
I think it makes sense to move the first paragraph of that help section to the top as it explains what a field guide is and leave the second paragraph as a help for the editor once you've created one.

**Comment by mschwamb** [comment]
@srallen that sounds good to me.
