### ISSUE TITLE
Organizations: some way for the lead to implement decisions + input landing page content

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2969]
Whether through a new interface or an existing interface, some place for the Federation leadership to:
- [ ] add/revoke membership
- [ ] activate/deactivate federated project workflow(s)
- [ ] input content (background image, text, etc.) for the [federation's landing page](https://github.com/zooniverse/Panoptes-Front-End/issues/2970)

**Comment by chrislintott** [comment]
This should now be:
- [ ]  Add/revoke membership

- [ ] Have collaborator access to any project in the federation

- [ ] Input content for landing page (and other associated pages)

**Comment by mrniaboc** [comment]
Also, federation leaders should just be automatically made collaborators on all projects in the federation, right?

**Comment by mcbouslog** [comment]
I believe (and will triple-check) pfe-lab will only allow an org builder to add a project to an org that they're an owner or collaborator on, so the specific user who is both the collaborator in the project and the org will have the access necessary to not only add a project to an org, but also make edits to the project.

However, a different org collaborator may or may not have access to that same project that is now associated with the org. So while the current functionality accomplishes the goals stated, it doesn't automatically apply to all org collaborators.

**Comment by mcbouslog** [comment]
Threw this together for a demo, will change, but might be a helpful reference:
![screen shot 2017-08-02 at 2 26 22 pm](https://user-images.githubusercontent.com/12118751/28891001-a20f37f0-778e-11e7-964b-03c5aa66f3f3.png)

**Comment by mcbouslog** [comment]
From a different collaborator's view, who is also a collaborator on two but not one of the 3 affiliated projects:
![screen shot 2017-08-02 at 2 30 42 pm](https://user-images.githubusercontent.com/12118751/28891200-4ba1e920-778f-11e7-819a-cbde9eeee238.png)
That's an issue, I think we
- [ ] should show all affiliated projects regardless of user/collaborator's status with projects

Not sure if/how we should give all org collaborators collaborator access to all affiliated projects.
