### ISSUE TITLE
Organizations: public landing page

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2970]
## Expected behavior

A landing page from which a volunteer will access all ~~workflows~~ projects associated with the ~~Federated Project~~ Organization (e.g., Urban Wildlife Watch.org, Notes from Nature.org, etc.)

Current design: https://zooniverse.slack.com/files/beckyrother/F683P4SQ1/organization_page_-_talk.png

UPDATES TO DESIGN LINKED:
- introduction section won't need Read More button
- stats show Volunteers, Classifications, Subjects and Completed Subjects, not horizontal bar graph(s)
- bottom left teal section will be about page content
- bottom right section will list social media links and external URLs (like Blog)

(edited by JA 6/15/2017, MB various times)

**Comment by trouille** [comment]
Will be populated by info cards for each project in the federation, see https://github.com/zooniverse/Panoptes-Front-End/issues/2971

**Comment by jelliotartz** [comment]
![org-home-page](https://user-images.githubusercontent.com/12473119/27198168-b347477a-51d6-11e7-8627-99eb6cbb2942.png)

@beckyrother - nothing new here, just wanted to keep you aware that there's a specific issue for the organization landing page.

**Comment by jelliotartz** [comment]
Current state of progress staged [here](https://org-pages.pfe-preview.zooniverse.org/organizations/5)

**Comment by jelliotartz** [comment]
Next steps:
- [ ] Create demo org with projects in various states
- [ ] Organization avatar next to organization title
- [ ] Background Image behind title
- [ ] Project avatar on [project cards](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/partials/project-card.cjsx)
- [ ] remove space between stats/about & footer

**Comment by beckyrother** [comment]
Thanks James! I also made a little style guide: https://zooniverse.slack.com/files/beckyrother/F55KWSPQQ/organizations-style.pdf

**Comment by mcbouslog** [comment]
Projects have the Announcement Banner functionality, might this be something we'll want to implement for organizations?

**Comment by mcbouslog** [comment]
Initial organization landing page merged, closing this issue in favor of specific issues as needed.
