### ISSUE TITLE
Organizations: Populating a new project info card 

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#2971]
## Expected behavior

In the landing page for a Federation, each new project that is part of the Federation will have an info card (e.g., following the zooniverse.org/projects model of showing an info card associated with each project). 

Note: zooniverse.org/projects will not have a card for each project within a Federation. It will only have a single Federation card; e.g., a single Notes from Nature card. 

The card should have the following content:
- an image (i.e., like our Project avatar)
- rollover text (like our Project landing page message)

It is an open question whether the card should also link to 'About' content for that project (i.e., the research team, their research goals, etc.). If the 'About' content is not provided here, we need to make a decision on where that 'About' content should live. In the current NfN project, there is an 'i' in the lower-right that links to external About content for each project. We aren't constrained to this model, just pointing it out as an example.

The card should link directly to the Project's Classify page. Note: this is different from zooniverse.org/projects, which links to the Project's landing page. Here we want to minimize number of clicks to classification since volunteer is coming through the Federated Project landing page. 

When the Federated Projects owner switches the project to active within his/her owner interface, this card should appear on the Federated Projects landing page.

**Comment by chrislintott** [comment]
I think we're now having these cards linking directly to project pages for projects which are members of the federation, rather than directly to workflows.

**Comment by mcbouslog** [comment]
This issue touches on a few things that I'd like to separate to the related specific pages (i.e. org landing versus projects and orgs listings). Organization-Project visibility questions will get a new issue if needed. Closing, but feel free to re-open if prefer.
