### ISSUE TITLE
Resizing the notes and message board thread Talk  comment box so that it fits right below the previous comments

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#2973]
A version of this ticket was closed previously  with the response that a Talk design pass was being made and would address this issue. That was a while ago, so I've created a new ticket. 

example: hit reply in a [thread](https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/29/86792) like this

Full page capture when you hit reply and there are not enough comments to fill all the way down to the bottom edge of the left side bar:

![fireshot capture 25 - planet four_ t__ - https___www zooniverse org_project](https://cloud.githubusercontent.com/assets/753325/18259850/38b37d5c-7384-11e6-88b0-23257c6eead5.png)

What you see in your visible browser when you hit reply to the comment:

<img width="1145" alt="screen shot 2016-09-05 at 4 14 53 pm" src="https://cloud.githubusercontent.com/assets/753325/18260187/1ccfab9e-7387-11e6-9348-76b84dd57068.png">

same thing for: https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/10/85980?page=1&scrollToLastComment=true

<img width="1126" alt="screen shot 2016-09-05 at 4 25 28 pm" src="https://cloud.githubusercontent.com/assets/753325/18259971/69c06b66-7385-11e6-9337-5f26f9ce860d.png">

If there is any developer time in the future to resize the comment box so it fits in the space below the already published comments, I think it would be very welcomed by the Talk community. Replying on Talk thread is a commonly used feature, so it would be nice if one could see the full discussion or subject image rather than having this huge gap

This behavior happens in all browsers I tested (Chrome, fixfox, and safari for mac) 

cc @parrish

**Comment by MvGulik** [comment]
>resize the comment box so it fits in the space below the already published comments, I think it would be very welcomed by the Talk community.

Probably a bit less welcome by those that are on lower, than the default assumed normal, resolution.

A fix for this:
![image](https://cloud.githubusercontent.com/assets/666868/18282449/75e24d92-7461-11e6-8f03-9541b57a09b6.png)
![image](https://cloud.githubusercontent.com/assets/666868/18282523/c7f43672-7461-11e6-9b43-8013f15c8bd6.png)
Would probably fix this related low resolution complained.

**Comment by mschwamb** [comment]
The editing the comment box has much more grey area around it then the reply comment box which is what I'm talking about.

**Comment by mschwamb** [comment]
Now that I played wit resizing the box when you edit a comment, I get what you mean @MvGulik. I think you'll want to put in a separate ticket for the edit box resize issue

**Comment by MvGulik** [comment]
Currently the new-reply edit box still has some decent-width size. But this ticked would makes it the same size as the edit box, with potentially the same edit-field re-size issue as reported in ticket #2983.

**Comment by mschwamb** [comment]
@parrish any chance the text box could be made smaller to fit?  It would make the talk experience nicer, especially to be able to see the image I (and other researchers) are replying about.

**Comment by mschwamb** [comment]
@parrish if there's not going to be a design pass any time soon, is it possible to make the text box smaller so it fits right below and make it easier to see the rest of the comments and the subject image? thanks

**Comment by eatyourgreens** [comment]
@mschwamb something like this? 
![image](https://cloud.githubusercontent.com/assets/59547/22288530/175010c8-e2ef-11e6-8585-564d5d8fe578.png)

**Comment by mschwamb** [comment]
yes! @eatyourgreens  - that would be great. thanks!

**Comment by eatyourgreens** [comment]
@mschwamb See #3427 Staged here https://fix-2973.pfe-preview.zooniverse.org/projects/mschwamb/comet-hunters/talk/84/166594?comment=287366&env=production&page=1

**Comment by mschwamb** [comment]
Yep thanks. That's so much better. Adds a lot of polish and ease of seeing what's above on Talk. Thanks1  The only thing that didn't work for me was at the bottom of the thread 'Please sign in to contribute to the discussion'. That hyperlink didn't open the box to log in but not sure if that's because of a staging thing or because of this change. So you might want to check that. Otherwise that looks great

**Comment by eatyourgreens** [comment]
Thanks Meg. Noted in a comment on #3427. A result of me copying and pasting blocks of code without looking at what they do.

**Comment by mschwamb** [comment]
Thanks @eatyourgreens  I owe you a drink of your choice next time I see you
