### ISSUE TITLE
Setup Hound

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#2980]
Setup hound for ESLint/Airbnb react style guide as a pre-commit hook. Open for comment, but I think this will help us out.

**Comment by simoneduca** [comment]
How about something like this https://www.npmjs.com/package/pre-commit and then having Hound as well, checking the PR as normal?

**Comment by eatyourgreens** [comment]
We could add a pre-commit hook script to  the repo, and encourage people to add it to their local `git/hooks/pre-commit`.

Sounds like that npm package overwrites existing hooks, rather than appending to them.

**Comment by srallen** [comment]
Sorry, I meant pre-pull request, similar to the setup with the Panoptes repo. Though, pre-commit could be considered instead or in addition to.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
