### ISSUE TITLE
Can an owner and collaborator be editing the project at the same time? 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#299]
This came up in our project planning call.  It looks like we can be both logged in and accessing the workflow editor/project builder interface for our project at the same time. One person with collaborator status wants to edit the science justification page and I'm going to edit the FAQ. If we each hit save on the respective sections at different times does that cause any issues? Is there something that prevents two people from making edits on the project at the same time?

**Comment by camallen** [comment]
@mschwamb this is taken care of in the backend API. 

When the front end gets a resource we include a key repesenting that resource state at that time. This key is then included when submitting an update resource request. On update we then check that the submitted key matches the resource's current key match, if they don't then we reject the update. Code links [here](https://github.com/zooniverse/Panoptes/blob/1d48eaade15b5a4064348089086d8099d5a06f9c/lib/json_api_controller/precondition_check.rb#L22) and [here](https://github.com/zooniverse/Panoptes/blob/4c66b3087b5ca05a5ccd7068885019020ee945d4/lib/json_api_controller/updatable_resource.rb#L5).

**Comment by mschwamb** [comment]
Thanks. So that means the front-end user doesn't know the other person is on until the hit save after making changes? It doesn't work like wordpress where you get a pop-up saying someone else is editing and therefore you can't?

**Comment by chrissnyder** [comment]
Not impossible to imagine we'll add this, but I wouldn't expect it in the near future.

**Comment by mschwamb** [comment]
question answered so closing this.
