### ISSUE TITLE
Help Text for Front End

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#300]
@brian-c I've created a text document of suggested in-line help text. Would welcome suggestions from anyone who has used the project builder. Please note we are also planning on coming up with some sort of downloadable guidance material that walks project builders through the process in a bit more detail.

**Comment by brian-c** [comment]
This is fine, but please never commit directly to master.

How is this to be used? Should this be in Google Docs?

**Comment by aliburchard** [comment]
Doh! Sorry -- did I pull a Grant? (I thought the "adding file" button would issue some sort of request.)

And hm, yes, a Google Doc might be easier until we've finalized the text.

**Comment by camallen** [comment]
@aliburchard yeah, doing it in the main repo commits to master. You could have added the file to your fork and issued a PR.

**Comment by aweiksnar** [comment]
Maybe we should start a content section of the wiki?

**Comment by mschwamb** [comment]
@aliburchard  suggestion for help - I had to figure out the science and faq and other pages use markdown and not html.  I think somewhere it needs to explicitly say that since not all scientists use markdown and  link to a markdown primer.

**Comment by aliburchard** [comment]
@mschwamb good addition to the text. 

@brian-c I was envisioning this as the in-line text for the workflow editor (stemming from #202) -- text  either to appear in the boxes that people type or to be accessible via a little question mark box that people can click on). 

I'm still waiting for @chrislintott to edit/comment, but would welcome edits from everyone. I've now made it a google doc that anyone can add to here: https://docs.google.com/a/zooniverse.org/document/d/1UjKNvvNFXo-phWk51JUIq5xUw9bSI06SOkuiCtEkEnA/edit?usp=sharing

**Comment by vrooje** [comment]
I've added a bunch of text... hope it's helpful. I think we're basically going to need little question-mark-boxes all over the place.

Note in that doc there are still a few places that need clarifying, e.g., what exactly does the Tester role do?

**Comment by vrooje** [comment]
PS - there are points at which I just added advice, like "if you are asking users to rate something, give them an odd number of answers so there's a middle", warning them about overchoice, etc.; just continuing the theme of being opinionated. Hope that's the right thing to do.

**Comment by aliburchard** [comment]
@brian-c When do you need this text finalized so it can be added to the Front End before public launch? 

@vrooje -- we might want to put those details in a separate tutorial that more thoroughly walks folks through the building process and provides that sort of insight. But I also like the idea of having that guidance appear in the moment as well. 

@brian-c Would it be possible to implement this first round of help text this week so that we can see what it looks like and whether or not we should streamline/expand, and then provide revisions to the text for next week? Is that easy or is it too much work?

**Comment by mschwamb** [comment]
Also something I wanted to point out up from the perspective of someone who hasn't been at any of the development demonstrations for this, I'm having a hard time knowing what to call the thing actual interface part of the front-end that I use to make the project. I think it would help people who are trying to build projects if they knew what to call the lab space it if they had an issue. on the tab title it says 'Edit [insert project name]' and there's nothing positioned anywhere. I'm saying panoptes front end but isn't the whole thing the front-end not just the builder interface?  The url is http://demo.zooniverse.org/panoptes-front-end/#lab/[project id number]

**Comment by camallen** [comment]
Internally we're calling it the project builder.

**Comment by brian-c** [comment]
@aliburchard I'll start integrating these today so folks can see how they feel.

**Comment by brian-c** [comment]
I've got this branch deployed to http://demo.zooniverse.org/panoptes-front-end/help-text. **The layout is not finished.** I'm going to find/build a nice tooltip library to clean a lot of this up.

Could further work on the help text take place in separate issues?

**Comment by aliburchard** [comment]
Thanks for doing this, Brian. We'll revise the help text in separate issues and I'll close this down.
