### ISSUE TITLE
Zoo's Markdown, Footnote's & Reverence links.

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#3001]
Footnote and footnote-reverence links are generated on a **per post** base.
(ie:"#fn<1..N>" & "fnref<1..N>...".)
Resulting in the fact that (*on a displayed page*) the first post with footnotes effectively hijacks footnotes in other post on that page. (*generates bad HTML too as someone else pointed out.*)

Some test case on Zoo: https://www.zooniverse.org/talk/13/18624?comment=97706
*Contains useful information to get passed some other issue.*

And some test code, Just in case:
```
Reverences: (post1)
`[^rev1]` [^rev1].
`[^rev2]` [^rev2].
Footnotes:
[^rev1]: `[^rev1]`.
[^rev2]: `[^rev2]`.

Reverences: (post2)
`[^rev3]` [^rev3].
`[^rev4]` [^rev4].
Footnotes:
[^rev3]: `[^rev3]`.
[^rev4]: `[^rev4]`.
```
Used here - https://www.zooniverse.org/talk/13/18624?comment=164688 - btw.

**Comment by eatyourgreens** [comment]
We're using the `markdown-it` parser, with the [footnotes module](https://www.npmjs.com/package/markdown-it-footnote) to handle footnote links so I'm afraid changing the parser behaviour is probably outside the scope of this repository.

**Comment by MvGulik** [comment]
@parrish: As you seem to be the [markdown-api](https://github.com/zooniverse/markdown-api) guy.
Do you think there is a chance footnotes could be made to work for zoo-user/talk-posts ?
*by mixing in a post-id in the footnote-anchor-links perhaps.*

Or is there some change needed at the root source at ... (?) https://github.com/markdown-it/markdown-it-footnote

Or ... should I just forget about footnotes at Zoo-user-talk level, and close this ticket.

**Comment by parrish** [comment]
I don't see an issue with adding footnotes.  I'll look through the available libraries to find one that will work well.

That change should have a corresponding change to the MD help section in PFE too.

**Comment by parrish** [comment]
Ah, I misunderstood the issue at first.  I'm looking into it.

**Comment by parrish** [comment]
Looks like newer versions of the plugin have a [fix for this](https://github.com/markdown-it/markdown-it-footnote/blob/master/CHANGELOG.md) by specifying a `docId` for the renderer (it basically just prefixes the anchor id's).

It does require a version bump for markdown-it and the related libraries.  I'll see how easy that upgrade path is.

**Comment by MvGulik** [comment]
Thank you for looking into it.
\**crosses fingers*\*

**Comment by parrish** [comment]
There's a fix incoming in zooniverse/markdownz#42.  Definitely not an elegant fix, but it works.

**Comment by MvGulik** [comment]
I don't mind testing the outcome (*... if desired, that is.*), but don't know which test server I should pick for that. (*or more general, how to find the right one.*)

(*I did checked out one case, but there things seemed to have not really changed.*)

**Comment by srallen** [comment]
I bumped markdownz to version 4.1.5 for this.

**Comment by mschwamb** [comment]
@srallen is this supposed to be open? It was working earlier. I added in the help content for this so let me know if I should temporarily take it out so it doesn't show in the markdown help.

**Comment by srallen** [comment]
@mschwamb Nope, my mistake. It can close.
