### ISSUE TITLE
Marking tool task subtask now falls behind pop-up window (as does metadata info for subject preview)

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3006]
<img width="1099" alt="screen shot 2016-09-10 at 12 23 19 pm" src="https://cloud.githubusercontent.com/assets/4975655/18412340/6288f8de-7751-11e6-97dc-588099edcfb6.png">

## Expected behavior
In Project Editor, when clicking on 'subtask' for a marking tool, 'add a task' prompt should pop up the options somewhere we can access them.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
See attached screenshot

## Additional information

- **Operating system:**
macbook pro
- **Browser:**
both chrome & firefox

**Comment by trouille** [comment]
This must be related to the 'i' metadata pop-up hiding behind the image. In the attached image, I clicked on the 'i', but you don't see it because it's hiding behind the image. 

<img width="1098" alt="screen shot 2016-09-10 at 2 46 52 pm" src="https://cloud.githubusercontent.com/assets/4975655/18413156/8472d0a0-7765-11e6-9999-997de501b87e.png">

**Comment by trouille** [comment]
@simensta I originally assigned you in this, because I thought it had to do specifically with the marking subtask, which I know you'd worked on. But then in seeing the same thing happen with the subject preview, I see it's more general. Feel free to un-assign yourself or assign to other. Thanks!

**Comment by eatyourgreens** [comment]
Probably related to #2966

**Comment by simensta** [comment]
@trouille, I can take a look at this issue. Thanks for bringing it to my attention!
