### ISSUE TITLE
Organizations: copying templates

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3008]
This is not a required functionality, but it would make new members lives easier if they could copy an existing 'template workflow', 'template tutorial', and 'template field guide' and edit as needed. 

Note: For Notes from Nature this is a required functionality (for template workflows and tutorials), but we could find a solution for this outside of our more generalized Federated Projects effort.

**Comment by chrislintott** [comment]
Agreed to making this a more general separate piece - it would be useful even outside the federation concept.

**Comment by mcbouslog** [comment]
Closing.
Added note in https://github.com/orgs/zooniverse/projects/8.
Can convert note to issue when we're ready to work on in detail.
