### ISSUE TITLE
Text updates not always showing immediately/cookies not refreshing?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#301]
I don't know if this is easily fixable, but one of things the P4 team has encountered updating text on through the front-end editor is that you can't see the changes immediately. I presume this is something with cookies not refreshing. A few times people that things weren't updating because they'd hit save and then reload the project and not see the text. Depending on what webrowser if you opened another webrbowser you could see the updates

**Comment by camallen** [comment]
related to resource caching in the backend, https://github.com/zooniverse/Panoptes/pull/825

A fix is coming for it.
