### ISSUE TITLE
Can't choose which task is first?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#3015]
## Expected behavior
Would like to be able to choose which task is first in the Project Builder.

## Current behavior
In the Project Builder, the first task you create becomes "first". Then if you later decide you want a different "first" task, there doesn't seem to be a way to set another task as first. If you delete the one that is first, then the second one you created becomes the "first."

**Comment by CKrawczyk** [comment]
There is already a dropdown list for selecting the first task in the project builder:

![screen shot 2016-09-14 at 9 25 15 am](https://cloud.githubusercontent.com/assets/6557526/18505052/4bda73e2-7a5d-11e6-92b1-ed10fdf7d9db.png)

**Comment by mkosmala** [comment]
Yep, totally right. Not sure why I didn't see that. Thanks.
