### ISSUE TITLE
Feature request: Simplified "survey" task ("tagging" task)

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#3027]
I love the survey task. But I'd really like to be able to have a one-click version of it for when choices are easy and there is no follow-up question. For example, I want to show a subject made up of 30 images (1 per day for a month) and ask for the earliest day a particular event happens (e.g. flowers bloom, snow falls). The survey task allows me to easily provide the numbers 1 through 30 as choices. But volunteers have to then click the number and then confirm that click a second time (since I don't provide any additional information on the number "7", for example, nor do I ask a follow-up question).

The use cases stretch to any sort of simple tagging task. I show a picture and I want people to tag it with tags from a tag list that might have 10 to 50 tags. For example: tag these outdoor pictures with one or more of the following: "mountain", "tree", "street", "fence"... There's no need to explain what a tree or a mountain is and the extra classification click slows down the volunteers. 

Hopefully it's pretty easy to modify "survey" to make something suited for simple "tagging".

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
