### ISSUE TITLE
Requested: using a threshold to quantify pixels within a polygon

### ISSUE THREAD

**Issue by citscisean** [zooniverse/Panoptes-Front-End#3032]
## Expected behavior

I would love if there was a way to set a threshold for selecting pixels within a polygon that uses draw, and automatically quantify the pixels above (or below) the set threshold. There are a number of macros for this in ImageJ that already do this. I see two ways of setting the 1) threshold could be set by the project (globally) or 2) threshold set by the user. For my project, I would need a way to set the threshold (globally).  
## Current behavior

_Please include any error messages from the browser console and/or screenshots_
## Additional information

Here is an example from ImageJ: [http://occm.otago.ac.nz/resources/ImageJ-Thresholding.pdf]

Here is the way we are currently doing it outside of Zooniverse: [https://mail.google.com/mail/u/0/#search/astoehr%40butler.edu/1568f4a1219664e1?projector=1]
- **Operating system:**
- **Browser:**

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
