### ISSUE TITLE
Teeny Tiny Subject Image in IE11 Survey Tasks

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#3034]
Issue: In IE11, on certain projects with survey tasks, the subject image looks small. So very small.

![screen shot 2016-09-15 at 18 24 43](https://cloud.githubusercontent.com/assets/13952701/18560430/63626cec-7b73-11e6-8d17-ccc91c3732c9.png)

* Issue originally reported on https://www.zooniverse.org/projects/panthera-research/camera-catalogue/talk/447/91084?comment=169330&page=1
* This issue has thus far only been confirmed in Win7+IE11 for the Camera CATalogue project: https://www.zooniverse.org/projects/panthera-research/camera-catalogue/
* No issues on OSX+Chrome.

Analysis:
* It appears that removing `subject-container`'s `display: flex` fixes the issue in IE11. We'll need to confirm this, but yeah, it's likely flex-related.
* @eatyourgreens, you were right: IE11 + flex = [NO](https://www.youtube.com/watch?v=H07zYvkNYL8)

Status: Investigating

**Comment by srallen** [comment]
I feel like this had been fixed before, but maybe broken by some CSS that shouldn't have been changed? Yes, IE is very buggy with flex. I like using this as a reference: https://github.com/philipwalton/flexbugs

If you find a fix, could you leave a comment in the code and css that it's for IE?

**Comment by shaunanoordin** [comment]
Yosh, thanks @srallen . From the reports it seems like there was a change within the past 24-48 hours that borked the Classifier for IE11 (...and Chrome, in one person's case?) so that might be a clue.

That said, I'm seeing weird stuff on the Classifier that seems to have been there for a while, like this: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/subject-viewer.cjsx#L23

I'll mark any IE-specific fixes I find, probably with `//Yarr here thar be dragons`

**Comment by shaunanoordin** [comment]
Analysis Update:
* On IE11, there is no such issue with the Wildcam Gorongosa project.
![screen shot 2016-09-16 at 13 17 31](https://cloud.githubusercontent.com/assets/13952701/18585674/3c089cb4-7c10-11e6-846c-97463d37ea12.png)
* Nor with Snapshot Wisconsin
![screen shot 2016-09-16 at 13 21 42](https://cloud.githubusercontent.com/assets/13952701/18585756/bb686dfe-7c10-11e6-8497-b1b35efeeaed.png)
* So this means that there's something very very specific about Camera CATalogue that's making IE11 so very wonky.

I'll compare the three and see what's wrong in Camera CATalogue. Maybe it needs a CAT scan.

**Comment by eatyourgreens** [comment]
Could it be something to do with the sizes of the images that were uploaded for each project? I can't think of anything else that would be specific to a single project.

**Comment by shaunanoordin** [comment]
Alright I discovered what's going on but I need help understanding the "what" and possibly the "going on".

Analysis Update:
* The Camera CATalogue project has **four subject images**, and **three of them are empty**
* Examining the code in IE11, we see...
```
<div class="subject-container">
  <div data-reactid=".0.1.2.0.0.0.3.2.0.1.0:$frame-0"> ...subject image... </div>
  <div data-reactid=".0.1.2.0.0.0.3.2.0.1.0:$frame-entries"> ...nonsense filler and no image... </div>
  <div data-reactid=".0.1.2.0.0.0.3.2.0.1.0:$frame-keys"> ...nonsense filler and no image... </div>
  <div data-reactid=".0.1.2.0.0.0.3.2.0.1.0:$frame-values"> ...nonsense filler and no image... </div>
</div>
```
* Here's a screenshot with each `.subject-container > div` given a unique colour so you can see them:
![screen shot 2016-09-16 at 14 20 57](https://cloud.githubusercontent.com/assets/13952701/18587293/301075f4-7c19-11e6-92e7-6c1e01b4fb87.png)
* It's obvious now what's happening: **this isn't exactly a CSS issue, it's a subject-content issue.** In IE11, the 3 extra "empty" subject causes the `flex` rules to _shrink_ and line up the subjects in a row. And since there's only one _visible_ subject, it looks like it shrunk to 1/4 its proper size.
* Question: why is IE11 receiving 4 "subject images"?

But wait, there's more weirdness!

Further Weirdness
* In Chrome 53, there is only **one extra invisible subject.**
```
<div class="subject-container">
  <div data-reactid=".0.1.2.0.0.0.3.2.0.1.0:$frame-0"> ...subject image... </div>
  <div data-reactid=".0.1.2.0.0.0.3.2.0.1.0:$frame-values"> ...nonsense filler and no image... </div>
</div>
```
* Fortunately, Chrome's flex rules are smart enough to make the empty div a _0x0 sized element_, so you can barely see it... save for this tiny tiny pixel.
* However, in Firefox 48, there are **zero extra invisible subjects.**
```
<div class="subject-container">
  <div data-reactid=".0.1.2.0.0.0.3.2.0.1.0:$frame-0"> ...subject image... </div>
</div>
```
* Does anybody have any idea **why** this might happen?

Further Investigation:
I have two lines of thought that I want to explore.
1. I need to check out the project settings for Camera CATalogue and compare it with the "safe" projects like Gorongosa or Snapshot Wisconsin.
2. My guess is that somehow, there's deserialisation method (something akin to 'array.split()') called on the received Subject data that's gone horribly wrong, so in Firefox it deserialises properly into one image, in Chrome it chokes, and in IE11 it just asplodes. I'll need to explore the "subject-container" component.
