### ISSUE TITLE
Update response to publication submission

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#3039]
When I submitted publication information via Zooniverse's form here:
https://docs.google.com/forms/d/18jwLbtV_6M5HCM74xNFtFbiiszWAxpC5IGHaToYjeiw/viewform
(as requested on the Build a Project policies page), I got this response:
![pub-response](https://cloud.githubusercontent.com/assets/1066340/18589211/a3d2bf1e-7bf7-11e6-9ecf-79f21f944e21.png)
which made me sad, because rob is no longer at Zooniverse and I miss him. 

More to the point, I'm not sure my submission will be seen by anyone at the Zooniverse. (Will it?) And the dialog itself should be updated.

**Comment by eatyourgreens** [comment]
I'm pretty sure those forms are submitted to @mrniaboc now.

We miss Rob too 😞

**Comment by mrniaboc** [comment]
Changed to contact@zooniverse.org
