### ISSUE TITLE
help text box is too small and difficult to write in when writing more than two sentences 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#304]
For the P4 project we need to stick everything into the help because it appears there is no tutorial (is that correct?) and because there currently isn't a separate page we can create to be a spotters guide that is easily accessible from the classification interface.  

 I found that the help box position is really small and it's not very easy to enlarge if you need to upload images or write more than two sentences of text.

**Comment by aliburchard** [comment]
Yeah, this is really difficult to work with when trying to paste long urls for help images. Is there any way to allow this to expand?
