### ISSUE TITLE
survey tool required/not required questions may not be working correctly

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3046]
In https://www.zooniverse.org/projects/zooniverse/chicago-wildlife-watch-relaunch/classify, if you choose 'Bird', you're required to answer the 'wow' question, but the attached .csv files the researcher uploaded shows that they said this question should not be required. 

Is there a fix to this that's possible? 

## Additional information
[reecologyprojectforreview.zip](https://github.com/zooniverse/Panoptes-Front-End/files/477751/reecologyprojectforreview.zip)

- **Operating system:**
Mac 
- **Browser:**
Chrome

**Comment by trouille** [comment]
https://www.zooniverse.org/projects/zooniverse/chicago-wildlife-watch-relaunch/classify is in a beta test right now. Sept 28 is the hoped for date for the full launch of CWW. We need to fix this before full launch, or have me work with the research team to find another solution (for example, maybe just have that question not be an option for bird and any other animals that have no other questions asked).

**Comment by mcbouslog** [comment]
per convo - if question not required, can still click identify, generally review required settings
