### ISSUE TITLE
Remove transparency from zoomed-out project pages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#3047]
One of the moderators asks if we can remove the 90% opacity on zoomed-out Talk pages, to improve readability. https://www.zooniverse.org/talk/17/83476?comment=170868&page=1

Pinging @jwbmartin for a design opinion.

**Comment by jwbmartin** [comment]
Yeah we can get rid of it for Talk. It's mostly for the project so you are either focusing on the project or focusing on the menu.

**Comment by eatyourgreens** [comment]
Cool. I've pushed an update to the CSS that should fix this.
