### ISSUE TITLE
avatar icon not showing in firefox but showing in chrome

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#305]
I don't know if this happens when there isn't a temp avatar image but I noticed when I switched to test in chrome the blue and green striped avatar temp icon and that it doesn't show up on firefox.  Screenshots below (checked it out on other projects to make sure it wasn't just mine). Shows up in Safari as well. Just not in Firefox. 

Firefox:

![screen shot 2015-05-12 at 3 08 28 pm](https://cloud.githubusercontent.com/assets/753325/7581714/ecc4b880-f8b8-11e4-9010-8cfd1d381109.png)

Chrome:

![screen shot 2015-05-12 at 3 08 32 pm](https://cloud.githubusercontent.com/assets/753325/7581724/ff45f78a-f8b8-11e4-926e-78fb85dd9ca1.png)

**Comment by mkosmala** [comment]
It's worse. Whatever happened this week broke the links to my images. Previously we had a custom avatar that showed up (on Firefox and Chrome), as well as a background image. I'm not sure what the difference is between Firefox and Chrome where a non-existent avatar shows up in one but not the other.

**Comment by mschwamb** [comment]
Fixed with the previous pull request merged. So I'm closing the ticket since I initiated it.
