### ISSUE TITLE
Making it easy to find how to acknowledge the Zooniverse in publications

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3051]
This came up in discussions of redoing the Gemini webpages, and I thought of Zooniverse home. Researchers don't frequently go to Zooniverse home, but if we need to write a paper we will hopefully go and look how to reference or acknowledge the Zooniverse. 

The info is buried at the Policies page, and I'd have to read the whole thing to see if there is anything about publications. I think a separate Acknowledgements tab on the about page that repeats the acknowledgements info  and a link on the bottom navigation bar to it would be really helpful. It would make the information easy to find. 

[SALT](http://astronomers.salt.ac.za/data/acknowledgements/) does this: having a separate page for Acknowledgements and a link on the bottom navigation bar. 

@chrislintott and @mrniaboc  maybe this would be one for @BNewing ?

**Comment by BNewing** [comment]
I'd be happy to do this!

**Comment by mschwamb** [comment]
@BNewing probably good to confirm with @chrislintott and @mrniaboc first

**Comment by BNewing** [comment]
Would this go under 'About' or possibly under the Project Builder Documentation?

I only suggest there because I'm thinking of suggesting revamping that section a little - I was thinking of setting it like the About page and having the little tabs which all link to the various sections of the Documentation. This would make it a bit easier to navigate!

**Comment by mschwamb** [comment]
I think About. There's already a mention in the Project Builder Policies but this is buried if you need to search for it. I think you'll want to leave the repeat in the policies page because it's important and better to not have people click a link to see that there, but it's hard to find if you're coming back 6 months later and looking for how to acknowledge the Zooniverse. 

So I would stick it in About and then on the Lab Page have a link under Quick Links

**Comment by chrislintott** [comment]
This is a good idea - go ahead, Bev!

**Comment by mschwamb** [comment]
closed by #3194
