### ISSUE TITLE
Could we get the superscript and subscript added to the Markdown guide?

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#3056]
>Could we get the superscript and subscript added to the Markdown guide?
>(*https://www.zooniverse.org/talk/13/18624?comment=173811*)

Just in case.
https://docs.google.com/document/d/1I2KapyYtwY-ebRd8WLm0k_iw68Dkk4mViEJbIjsb19c/edit
(*picked up from talk in older #1517 issue*)

---

Slightly edited version:
**+**: seems done.
**-**: not mentioned.
**?**: not sure.
```
+	Bold
+	Italic
+	Bold Italic
?	Monospace
+	Strikethrough
+	Hyperlinks
+	Hyperlinks to different targets (new tab, new window, etc.)
-	Hyperlinks - optional tooltip.
+	Inline Images
+	Images-dimensions-setting (if we allow it?) (we’re good)
+	Quoted Text
-	Headers (all types)
+		Headers - default "# headers"
-		Headers - alternitive header1\n=== & header2\n---
+	Horizontal line
+	Bullet list
+	Numbered list
?	Headings
+	Code
-	Superscript/subscript
?	Line break
?	Em dash
-?	Backslash escapes
+	Zooniverse specific
+		Subject mentions or Project/subject mentions (we should decide)
+		User mentions
+		Group mentions (e.g. @team, @moderators, @researchers, etc)
+		Hashtags
```

---

Related file: see next comment.

**Comment by eatyourgreens** [comment]
I think this just needs some kind soul to edit the HTML in https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/partials/markdown-help.cjsx and submit a pull request.

If you feel confident to edit the HTML yourself, please do feel free to add in those changes.

**Comment by MvGulik** [comment]
My confidence level seems a bit low on this.
General low github feature experience and such. But will give it some more thought ... and additional reading.

**Comment by camallen** [comment]
this may be helpful, https://help.github.com/articles/editing-files-in-your-repository/

**Comment by eatyourgreens** [comment]
No problem. I'll also ping @mschwamb as she's been helping to update the guides when she has time.

**Comment by mschwamb** [comment]
@eatyourgreens can you give me the new markdown syntax for superscript and subscript

**Comment by MvGulik** [comment]
(*continues reading up on github stuff, ... if not needed directly needed for this case, its still something I like to explore and learn. :) *)

**Comment by MvGulik** [comment]
Examples:
`^superscrip^` :: ^superscrip^
`~subscript~` :: ~subscript~

Regular spaces are not supported by default/standaard/specs.
`^super scrip^` :: ^super scrip^
`~sub script~` :: ~sub script~

ie: escaped spaces should be used when needed.
`^super\ scrip^` :: ^super\ scrip^
`~sub\ script~` :: ~sub\ script~
(*fails here on github, but works fine in Zoo*.)

Full code dump
```
Examples:
`^superscrip^` :: ^superscrip^
`~subscript~` :: ~subscript~

Regular spaces are not supported by default/standaard/specs.
`^super scrip^` :: ^super scrip^
`~sub script~` :: ~sub script~

ie: escaped spaces should be used when needed.
`^super\ scrip^` :: ^super\ scrip^
`~sub\ script~` :: ~sub\ script~
```

**Comment by mschwamb** [comment]
@eatyourgreens  and @MvGulik I'm at a workshop today so I can edit the file and add the entries to the html table.

**Comment by mschwamb** [comment]
@eatyourgreens I'll assign you the PR if that's okay

**Comment by eatyourgreens** [comment]
Ok. I have to hold my hands up and admit I don't know Markdown, but I guess we just need a couple of new rows in the table with those subscript/superscript examples.
