### ISSUE TITLE
Usernames and avatar don't change on Talk front page when you switch from one Talk to another through the Talk side bar

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3067]
cc @parrish 

Here's P4: Terrains
<img width="1075" alt="screen shot 2016-09-25 at 10 33 41 am" src="https://cloud.githubusercontent.com/assets/753325/18818063/af1977f8-830b-11e6-801d-a17eacd53e6d.png">

and then I  went to Microscopy Masters through the Talk side bar  and it has the P4: T usernames and avatars from its front page listed in the Microscopy

<img width="1090" alt="screen shot 2016-09-25 at 10 33 30 am" src="https://cloud.githubusercontent.com/assets/753325/18818070/d2f666fe-830b-11e6-84e2-485a6b2972ba.png">
 Masters. I haven't ever posted on their talk.

**Comment by eatyourgreens** [comment]
Discussed on Fossil Finder Talk here, too: https://www.zooniverse.org/projects/adrianevans/fossil-finder/talk/50/89479
