### ISSUE TITLE
Zooniverse lab page looks garbled on iphone

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3068]
Not sure if this  on ipad but on my iphone (OS 10.0.2) I see that the Zooniverse lab page is all garbled.

![image1](https://cloud.githubusercontent.com/assets/753325/18823178/3916cbee-8353-11e6-8ac5-16450beb906e.PNG)

**Comment by mschwamb** [comment]
Other pages seem to be okay

**Comment by eatyourgreens** [comment]
Here's a screenshot from my phone (6+, 10.0.1)
![img_6514](https://cloud.githubusercontent.com/assets/59547/18828239/c1f93a16-83ce-11e6-9451-050d05ef6a7c.jpg)

I'm having a hard time reproducing this, but it could be an issue with the footer positioning.

**Comment by eatyourgreens** [comment]
Here's another screenshot from iOS 9.1 in the iOS simulator (I haven't upgraded XCode to iOS 10 yet.)
![image](https://cloud.githubusercontent.com/assets/59547/18828361/6ec78356-83cf-11e6-9ac7-c9d200e3cf6c.png)

**Comment by eatyourgreens** [comment]
Overlapping is present for screen widths of 375px and lower, but not at a screen width of 414px, so I'm going to guess that this is caused by a media query somewhere in the CSS files.
