### ISSUE TITLE
Error when uploading subjects

### ISSUE THREAD

**Issue by perry** [zooniverse/Panoptes-Front-End#307]
![](http://i.imgur.com/vQvBHgh.png)

The subjects are created, but the files do not exist.

cc @brian-c

**Comment by brian-c** [comment]
@edpaget any thoughts? That double-slash looks suspect.

**Comment by camallen** [comment]
@astopy what are the CORS settings on the panoptes-uploads bucket?

**Comment by astopy** [comment]
panoptes-uploads is in zooniverse-static, so the CORS should be the same as everything else, but it’s a separate CloudFront distribution and it currently doesn’t have OPTIONS, PUT, POST, PATCH, and DELETE enabled if that makes a difference.

**Comment by edpaget** [comment]
I'll look into the double slash, but it looks like the issue are the CORS settngs.

**Comment by edpaget** [comment]
Actually those are entirely the wrong urls. I'll look into why they're coming back. Those should be the signed urls to upload to zooniverse-static.
