### ISSUE TITLE
"Finished" banner does not appear on all subjects

### ISSUE THREAD

**Issue by ChristinaLocke** [zooniverse/Panoptes-Front-End#3077]
## Expected behavior
The most recent season of Snapshot Wisconsin ended this week; as reported on our [front page](https://www.zooniverse.org/projects/zooniverse/snapshot-wisconsin) 39,885 of 39,885 subjects have been retired and a green "Looks like this project is out of data" banner appeared. After a season ends, the "finished" banner is expected to appear on all subjects in the classification interface.
## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Currently, the "finished" banner appears on photos with animals in them, 
![animal](https://cloud.githubusercontent.com/assets/22479470/18884248/3528f6a6-84ac-11e6-8bba-185ebcbccbc2.jpg)

but not on "blank" photos (photos with no animals):
![blank](https://cloud.githubusercontent.com/assets/22479470/18884180/e6485e8c-84ab-11e6-87e6-2c03b4716dce.jpg)

A review of the classifications data shows that only blank photos were clicked on in the days following the end of the season.

## Steps to replicate
Click on "Classify" on the Snapshot Wisconsin [home page](https://www.zooniverse.org/projects/zooniverse/snapshot-wisconsin). Most of the subjects that come up will be blank and have no finished banner. You can refresh the page until you get a photo with an animal in it that has a "finished"  banner.

**Comment by camallen** [comment]
This is an api issue, i'm investigating.

**Comment by camallen** [comment]
Those subjects are retired, seems the api is not labelling them correctly, i've got a PR to fix this on the API (linked above).
