### ISSUE TITLE
No email for data exports?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#3084]
I requested classification exports for Season Spotter Questions and Season Spotter Image Marking. A day later (~24 hours), I can download the data from the Project Builder, but I never received emails saying that the data were ready like I used to. This is the first time I haven't received notifications of data being ready. Not sure what's changed (in the past few months).

**Comment by camallen** [comment]
@mkosmala sounds like an api issue re mailing, did you check your spam folder? Can you try again please?

**Comment by mkosmala** [comment]
@camallen Yep, checked spam. I'll try again now...

**Comment by srallen** [comment]
@mkosmala are you getting emails now?

**Comment by mkosmala** [comment]
Nope. Still not.

**Comment by trouille** [comment]
@mkosmala Are you getting emails now? We had a database issue back then, so I thought I'd check in again now to see if this is resolved. If yes, definitely feel free to close the issue. Thanks!

**Comment by mkosmala** [comment]
Still not, nope.

**Comment by mschwamb** [comment]
I'm having the same issue for Comet Hunters now, but I have no issue with Planet Four: Terrains. I opened a ticket on the backend https://github.com/zooniverse/Panoptes/issues/2104

**Comment by trouille** [comment]
@mkosmala Could you check once again? Thanks!

**Comment by mkosmala** [comment]
@trouille Doesn't seem to be working, still. I can get my data from the Project Builder site, but I don't get an email...

**Comment by wgranger** [comment]
@mkosmala I believe this is a backend issue, but if you add me as a collaborator for Season Spotter I can double check and see if there's anything fishy on the frontend. My Zooniverse name is wgranger.

**Comment by mkosmala** [comment]
@wgranger I've added you to Season Spotter Questions (project 347). If you want a project that has less data and so produces data exports more quickly, I've also added you to Season Spotter Jornada (project 2384).

**Comment by wgranger** [comment]
@mkosmala I'm getting back classification exports for both of those projects. Perhaps double check your email under your profile settings > email to make sure it's going to the correct address.

**Comment by mkosmala** [comment]
@wgranger Well *that* is interesting. Yep, I have an email account that I _thought_ was active. But it must have been deactivated several months ago -- probably in September at the beginning of the academic year. I wonder what other email I haven't been getting...

I updated my email address and am now waiting for a new data export.

**Comment by wgranger** [comment]
@mkosmala Sounds great. Just keep us updated if you have any problems. We'll close this issue soon if there are no outstanding issues.

**Comment by mkosmala** [comment]
So at least some part (and maybe all) of the problem was that my registered email address (which forwards to my main account) stopped working. I changed the email address and I now get email notifications fine.
