### ISSUE TITLE
Ability to add messages to specific subjects in the summary page?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3092]
We'd like to show simulated comet images on Comet Hunters that would be give us a detection efficiency for the project. With the number of simulations, we'd want to make sure it was clear to volunteers that these are simulated comets so  people don't think they found a comet when they didn't. Like on Planet Hunters, we'd like on the summary page if possible to have a message  that says this is a simulated comet with parameters of X, Y, Z. 

Previous known comet examples I marked by hand on Talk with a hashtag since it was small enough (only 40 subjects) but with a 1000 or 2000 simulated subjects this isn't practical. Is there a feature in  development or currently experimental that does something like this?

**Comment by mschwamb** [comment]
Note: if this is possible, we fully understand this feature might not exist yet and be a feature request.

**Comment by camallen** [comment]
@mschwamb this is a feature we're working on for some zoo sponsored projects. I don't think the final implementation detail has been figured out but a naive solution could use special subject metadata.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
