### ISSUE TITLE
Make hide previous marks public

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3102]
## Expected behavior

Hiding previous marks as a publicly available feature.
## Current behavior

Feature is hidden behind experimental tools. After looking at the code, I decide to track down the original discussion and Brian brought up some good questions (in #2408) that I think we should decide upon before making public. We may want to implement these changes:
- Should the checkbox be available on all tasks once there are marks on the image? I'd argue yes, because answering questions might be easier if you can see the original image. If so, let's move the `enableHidePrevMarks` property from the task to the workflow configuration. If not, we should take the checkbox out of the persistent hook and put it in the task itself.
- Should this be optional for the project owner? I'll argue no, because I think tasks should be consistent and familiar across projects.
- When does stuff get out from behind the experimental flag? We've had this feature on other projects. I don't think it's necessary here.
## Additional information
- **Operating system:**
- **Browser:**

**Comment by srallen** [comment]
I'd argue for making this a workflow configuration instead of the current implementation as a boolean property on the task. After thinking about it, I also think that it should just be enabled instead of optional.

**Comment by mrniaboc** [comment]
I don't really see a good argument against not just enabling it on all projects with a marking task.

**Comment by mrniaboc** [comment]
What I was trying to say above was yes, it should just be enabled as standard.

**Comment by mschwamb** [comment]
If you make it available to all projects you might want to look at where the checkmark/button is in the classification interface. . Currently on projects with it enabled you can't see there's a tutorial button as it gets pushed off 13 inch screens in many cases because it's an extra line added to the right side of the classification interface which bumps the tutorial even further below  (see #2562)

**Comment by srallen** [comment]
@jwbmartin do you have an idea on how to address @mschwamb's design question for the hide previous marks checkbox in the classifier?

**Comment by mschwamb** [comment]
@srallen @jwbmartin  one simple solution may be to put 'hide previous marks' under the subject image.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
