### ISSUE TITLE
Create and join user groups

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3121]
## Expected behavior

Create a UI for users to join user groups which generates a URL that can be sent out for users to join group.
## Current behavior

_Please include any error messages from the browser console and/or screenshots_
UI doesn't exist on PFE.

This is related to Intro2Astro, but we will generalize the use case for integration into PFE.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
