### ISSUE TITLE
See user group membership

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3123]
## Expected behavior

Add UI to user profile so user can see what groups they are a mamber of and possibly a button to leave group.
## Current behavior

_Please include any error messages from the browser console and/or screenshots_
PFE does not have UI in the user profile for user groups

Related to Intro2Astro, but generalizing for PFE.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
