### ISSUE TITLE
Classify page, Favorite icon, GUI stabilization.

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#3125]
I think the classification page intrinsically relies on having a smooth and stable UI.
The following might look like a minor thing, but getting rid of it would not be a bad thing.
(_will try to look into this one myself, ... but that could take some time._) 

Issue:
While the classification page is loading there is no favorite icon displayed yet. But when it becomes available, it changes the ui slightly.
The side effect in this case is the pushing-a-side of the subject-image/frames buttons. Although it is not much, it just enough, combined with the general timing of the change, to result in user (_me_) mis-clicks.
![image](https://cloud.githubusercontent.com/assets/666868/19345004/d62c5bbe-913c-11e6-8923-4b0bde89f08a.png)
(_note: uses locally adjusted css, which has no baring on this case (verified)._)

nts: _Problem seem to have two potential issues to be resolved. One being the delayed loading/activation of the fav.icon, But the initial vertical to horizontal alignment of the additional tool icons is probably a other one._

**Comment by camallen** [comment]
This is an issue of api request timing, i.e. the fav icon shows up after the fav collection request completes. We're looking into refactoring the architecture of how the classification page works and I am pretty sure a side effect of this refactor would be that all the api resources for required in the UI would be available during the render, thus the fav icon would show up on the initial page load.

**Comment by MvGulik** [comment]
>the fav icon shows up after the fav collection request completes

Aha, was not sure which delayed part might be in play.

>We're looking into refactoring the architecture of how the classification page works

Is that something currently in progress, or might a temporary simple fix (*if I can find one that is*) still be useful for the time being ?

**Comment by camallen** [comment]
It's in the pipeline but no ETA on it. 

It could certainly be useful, I'm not sure if it that component uses the PromiseRenderer though. If not then that component's render method could just add the icon in and update it after it the api req completes. If it does then it may not render till after the call completes anyway so may not be fixable :(

**Comment by MvGulik** [comment]
Roger.

>it may not render till after the call completes

Yea, something similar in nature crossed my mind.

Will take a look and see how far I get.
Its at least a other general zoo-code learning opportunity. :)

**Comment by MvGulik** [comment]
Closing in favor of:
>It's in the pipeline but no ETA on it.
