### ISSUE TITLE
URGENT: Background image and avatar disappeared

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#313]
Might be a front-end or a back-end issue, so including @camallen and @edpaget, as well as @brian-c:

Yesterday (or perhaps Monday), the background image and avatar from the Season Spotter projects disappeared. The images are hosted externally, and I'm hoping this problem means that arbitrary image uploads are in the works -- at least for avatars and background images. 

In any case, can whatever broke be fixed so that I can see an avatar and a background again? Or if there's new way to link to / upload avatars and background images, can you please let me know so that I can restore them. We are ready to run our beta test and are just waiting for these images to show up again.

**Comment by brian-c** [comment]
The back end changed how it handles these, and the new image picker is waiting on a couple merges.

What are the avatar and background image addresses? I can hardcode them into the branch I broke out for SS.

**Comment by edpaget** [comment]
@brian-c I migrated any existing images. They should be available by GETing the projects/whatever/background.

**Comment by brian-c** [comment]
`/api/project/405/avatar` is giving me a 500. Even if that worked, the change that makes it render isn't merged, and it'd be easier to hardcode it than keep track of a second master-ish branch.

**Comment by edpaget** [comment]
Ah whoops. I'll also make sure that returns a better error.

**Comment by mkosmala** [comment]
@brian-c The images are here:
background: https://raw.githubusercontent.com/mkosmala/SeasonSpotterLanding/gh-pages/projectimages/tamaracks_fall_RNC_cropped_1024x768.jpg
avatar: https://raw.githubusercontent.com/mkosmala/SeasonSpotterLanding/gh-pages/projectimages/SeasonSpotter_logo_small.png

Thanks!

**Comment by brian-c** [comment]
Should be all set @mkosmala.

**Comment by mkosmala** [comment]
Great, thanks, @brian-c !
