### ISSUE TITLE
Sub-task  box moves

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#3131]
When classifying using a sub-task pop-up box, such as the one on this project https://www.zooniverse.org/projects/hughdickinson/galaxy-nurseries/classify, the pop-up box moves when you select one of the options. 

It's a bit confusing and disorientating.

**Comment by camallen** [comment]
Also hovering over the back button inserts elemets to the dom and the background jumps around...this was unexpected.

**Comment by eatyourgreens** [comment]
@mrniaboc is this still an issue? Otherwise, I'll close this.
