### ISSUE TITLE
Cloning markers also clones Sub-task windows that need to be closed individually

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#3132]
## Expected behavior

In https://github.com/zooniverse/Panoptes-Front-End/issues/2888 cloned markers in multiple images was enabled - thanks! I've just noticed that if you have a drawing task with clone markers set- any sub-tasks also get cloned. I would expect that if the marker is cloned, the sub-task only appears once. 
## Current behavior

_Please include any error messages from the browser console and/or screenshots_
At the moment each cloned marker has a sub-task window that needs to be selected for each cloned marker
E.g. Here's a screen shot for Space Warps with cloned markers and a sub-task, each of the 3 sub-task menu's need to be clicked & as you can place more than one mark you can get as many sub-tasks menus as images open. While the category selected in one is replicated in the others - each menu needs closing individually with the 'OK' button.

![image](https://cloud.githubusercontent.com/assets/1917970/19441912/5d563d54-947f-11e6-8403-482fb0cdd6e9.png)

I think one 'OK' press should close all the sub-task menus open when markers are cloned.

In the case of multiple makers being made you get a set of new sub-task menus each time that replace the previous set. I think this may be OK for us in this current version of the project but may impact other projects.

I'm not sure what the best option to declutter/simplify this is but perhaps having only one sub-task menu open for cloned markers would work.
## Steps to replicate

Try the workflow on
https://www.zooniverse.org/projects/aprajita/swdemo/classify?reload=1&workflow=2629

if you select yes on the first question and then proceed to the marking the image you can replicate this.
## Additional information
- **Operating system:**
- **Browser:**

**Comment by simoneduca** [comment]
Hi @aprajita thanks for reporting this. @eatyourgreens has a fix and you can test here https://fix-3132.pfe-preview.zooniverse.org/. However, now it becomes really hard to edit a subtask, because you need to remember which marker you opened it with. It might be worth rethinking displaying multiple markers, if subtasks are necessary for your project.

**Comment by srallen** [comment]
@aprajita could you take a look at the staged link that @simoneduca mentioned above? Thanks!

**Comment by aprajita** [comment]
Hi @srallen  I did look at the stage link at the time, and i am sorry I forgot to post my response here.  I can't seem to see the fix anymore at that link, but I remember I understood @simoneduca's comments on the conflict between multiple markers and subtasks.  

When I go to that stages link, should I build a new project with multiple markers and subtasks to check this functionality again? The workflow I mentioned in my earlier post on this thread doesn't appear in the list of projects shown to me when I go to the staged link and login.

**Comment by srallen** [comment]
@aprajita I'm not sure what might have happened to the test project on our staging server since I wasn't initially working on the fix. If you can remember the name of the project or its id, I can check to see if it still exists in our db, but if not, then probably setting up a new test project and workflow is the best way to test and let us know if this is a sufficient fix.

**Comment by eatyourgreens** [comment]
That project might be on the production database, in which case appending `?env=production` to the staging URL should fix it.

**Comment by aprajita** [comment]
Hi 
thanks @eatyourgreens & @srallen 

I tried adding ?env=production and I can now see the demo site I referred to above on the staged link

If I go to https://fix-3132.pfe-preview.zooniverse.org/projects/aprajita/swdemo/classify
I see only one sub-task menu pops up so that makes it a lot clearer for cloned makers

So I think this looks good for cloned markers, and definitely agree that some thought needs to be put in (from the builder's side) as to whether multiple markers with sub-tasks enabled are needed.

Thanks again!
