### ISSUE TITLE
External links easy to mistakenly add

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3138]
## Expected behavior

UI less confusing so project builders don't accidentally add more external links than they intend.
## Current behavior

_Please include any error messages from the browser console and/or screenshots_
Currently the UI for adding an external link causes project builders to accidental click it thinking it's a save or confirm button. Instead this just makes another external link with the defaulted "example" text without them noticing.
## Additional information
- **Operating system:**
- **Browser:**

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
