### ISSUE TITLE
If you check the Allow Users To Flip Image Color and then uncheck after deciding you don't need it, the invert button doesn't go away in the classification interface

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3140]
I'm working on a new project and wanted to see the behavior of the invert feature and then decided I don't need it.

I checked the 'Allow Users To Flip Image Color' and then unchecked it after testing the workflow. Now the invert button won't disappear in the interface
 
project is 3219

**Comment by srallen** [comment]
@wgranger could you take a look at this since I think you did the initial development on it?

**Comment by wgranger** [comment]
Will do
