### ISSUE TITLE
Better feedback for failed email address changes

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#3142]
If the user tries to change their email address to one which is invalid (e.g. because the address is already used by another account), the only indication in the UI that there was an error is the red background here:

<img width="119" alt="screen shot 2016-10-20 at 11 10 25" src="https://cloud.githubusercontent.com/assets/428423/19555704/deabbc02-96b5-11e6-8437-91e9b4ad1914.png">

We should be displaying an error message to tell the user what happened and why.

**Comment by srallen** [comment]
Another one for #2895

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
