### ISSUE TITLE
Make the stats page show the correct completion percentage

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3145]
Both Comet Hunters and Planet Four: Terrains say they are at 100% completion. They're not, and I'm starting to get inquiries about why should people be giving their time if we don't need their classifications.  The problem since the stats page launched is that it counts the total classifications for the workflow divided by the total number of classifications needed to complete that workflow's active subject sets. So if you uncheck any subject set you get the wrong number. 

Now the API seems to return back the correct ratio of number of completed subjects in the linked subject sets to the total number of subjects linked to the subject set to complete. Is it possible just to use that ratio for the percent completion, it would be give a better idea of completion?

**Comment by camallen** [comment]
@mschwamb the UI is just presenting the completeness metric the api is returning see [here](https://github.com/zooniverse/Panoptes-Front-End/blob/f85e62323b52043f1e0bd2a2de875dbaf04aa6b5/app/pages/project/stats/stats.jsx#L290). 

I've got an API PR up to discuss just using the linked subjects / retired counts for calculating completeness https://github.com/zooniverse/Panoptes/pull/2012

**Comment by mschwamb** [comment]
@camallen thanks for that PR request is there a reason it's not showing a change on the stats page?

**Comment by camallen** [comment]
Yeah the deploy caused other issues and we rolled back last night. Scheduled for early next week now. 

You happy to close this for now so we don't forget it?
