### ISSUE TITLE
Should project status filter be a query param?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3152]
I've been reviewing #3085, which allows the user to filter the project list by status (active, out of data, finished). It does it by creating a new route for each status, with `active` being the index.

I'm going to merge it, as I don't particularly want to block the feature, but I feel like status should be a query parameter that defaults to `active`. What do people think?

```
// current
/projects/outofdata?discipline=arts&page=1

// query param version
/projects?discipline=arts&page=1&status=paused
```

**Comment by camallen** [comment]
@rogerhutchings i'm in favour of the query params. what is the existing convention in the codebase?

**Comment by rogerhutchings** [comment]
The other filter types all use query parameters

**Comment by rogerhutchings** [comment]
cc @simoneduca

**Comment by srallen** [comment]
I'm for it being a query param.

**Comment by marten** [comment]
👍

**Comment by rogerhutchings** [comment]
Thanks everyone!
