### ISSUE TITLE
Project Builder subject uploader skips image names favoring other fields

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#3154]
## Expected behavior

Subject uploader to identify image names in manifest
## Current behavior

Subject uploader sometimes skips over image name for values in a different field. This seems to only happen when there is an extension in the other field (e.g, .jpg). When this happens error message indicates that images from manifest are not found in the overall upload.
## Steps to replicate

I have example full manifests to for testing, but see example below.

Example 1 (functions as expected):
field name 1: imageName
value: 5785300f00cf7916168b64e4.jpg

field name 2: imageURL
## value: http://bisque.iplantcollaborative.org/image_service/image/00-6bEY7Cfq9rtDq8Jh5cA5x?resize=4000&format=jpeg

Example 2 (does NOT functions as expected):
field name 1: imageName
value: 57fbd8ce00cf79492f8b48b7.jpg

field name 2: imageURL
value: http://cdn.flmnh.ufl.edu/Herbarium/jpg/023/23158s1.jpg

In this case, the Project Builder looks for an image named 23158s1.jpg when the image uploaded is named 57fbd8ce00cf79492f8b48b7.jpg
## Additional information
- **Operating system:**
  Not related to OS
- **Browser:**
  Not related to OS

Assigned to @mcbouslog

**Comment by srallen** [comment]
@denslowm just to clarify where you saw this bug, was this in the project builder interface where you drag and drop the manifest and image files to upload or with the command line javascript subject uploader?

**Comment by mcbouslog** [comment]
This issue is when uploading subjects through the Project Builder.

**Comment by denslowm** [comment]
What Mark said it correct. 
I forgot to add that when I delete the imageURL column from the manifest in example 2 all works as expected.

I also have example images and manifests if those would help.

**Comment by denslowm** [comment]
Responding to the stale bot, I guess.

I have a work around now that I have learned to use the Panoptes CLI. However, I know that there are other users on our project that would still like to see this fixed. 

If it seems low priority given other tasks, we can close it it for now.
