### ISSUE TITLE
weird color differences where some boarders are blue on projects and and then Zooniverse site pages are teal

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3155]
This looks really odd that you get teal when you're on Zooniverse Talk:

<img width="1102" alt="screen shot 2016-10-25 at 6 50 24 am" src="https://cloud.githubusercontent.com/assets/753325/19695591/787b1a5e-9a7f-11e6-834b-ac9b37a3c527.png">

and get the blue that was there before then teal when you click to get the Zooniverse level navigation bar on a project page:

<img width="1117" alt="screen shot 2016-10-25 at 6 50 19 am" src="https://cloud.githubusercontent.com/assets/753325/19695619/9aef7d3c-9a7f-11e6-9b93-e06e0d27c1a1.png">

It looks really weird when you move to any of the Zooniverse navigation links to see the sudden jump in color

**Comment by mschwamb** [comment]
You can actually see the browser load the teal Zooniverse bar and then it loads the blue at least from my connection in Hawaii

**Comment by marten** [comment]
We might need to fly over to check why it's still blue in Hawaii :P

The footer is also still blue.

**Comment by mschwamb** [comment]
@marten excellent idea.

**Comment by mschwamb** [comment]
Same thing happens on profile pages. If it goes through the project level its teal (but still blue bottom header and zooniverse top navigation bar) and then on the zooniverse.org profile page the  teal is on the top but the blue is in the links:

https://www.zooniverse.org/users/mschwamb 
https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/users/mschwamb

**Comment by mschwamb** [comment]
I still seems really odd that the blue exists on the projects but teal is everywhere else and on Talk. Maybe this is one for @jwbmartin ?
