### ISSUE TITLE
Reducing the amount of empty space on Zooniverse home pages top bar 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3156]
It looks like you removed all the photos/graphics on Zooniverse home and instead have a solid color.

There's now a lot of empty space that on smaller screens you have to scroll through that could be reduced since there isn't an image you're currently displaying like before 

Could you just some of the empty white space so the page content comes up closer to the top of the pace 

<img width="1108" alt="screen shot 2016-10-25 at 6 56 50 am" src="https://cloud.githubusercontent.com/assets/753325/19695813/52acde74-9a80-11e6-851d-3f362205f8e1.png">

<img width="1095" alt="screen shot 2016-10-25 at 6 56 46 am" src="https://cloud.githubusercontent.com/assets/753325/19695812/52a591e6-9a80-11e6-8c57-a41224526b6c.png">

**Comment by BNewing** [comment]
Created a PR for this - can be seen [here](https://github.com/zooniverse/Panoptes-Front-End/pull/3168)

**Comment by mschwamb** [comment]
closed by #3168
