### ISSUE TITLE
No projects listed under paused or finished tabs on the projects page 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3157]
I saw there are now tabs for status on Zooniverse projects page, but retired projects are not showing up under finished or paused. Only active is filled. 

<img width="1078" alt="screen shot 2016-10-25 at 6 59 30 am" src="https://cloud.githubusercontent.com/assets/753325/19695890/9fad2b34-9a80-11e6-9047-ea4b2c62e4b8.png">

**Comment by marten** [comment]
Correct, the front end got deployed before we marked projects as such in the database. Which is a process we do until we add options for that into the project builder (which is on the todo list).

Hopefully tomorrow we'll mark stuff correctly.
