### ISSUE TITLE
Prevent users from hitting subject limit

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#316]
See zooniverse/Panoptes#835.

**Comment by chrissnyder** [comment]
I think this is outdated. Pinging @brian-c to be sure.

**Comment by brian-c** [comment]
There's no pre-upload "You're about to upload too many!" warning yet.

@edpaget is it safe to use `max_subjects` and `uploaded_subjects_count` to display this? My (user #3) `max_subjects` is 100, and my `uploaded_subjects_count` increases when I create subjects but doesn't decrease when I delete them.

**Comment by camallen** [comment]
@brian-c that counter should decrease if the subject gets permanently deleted. What is the end point you're using to delete the subject?

**Comment by simoneduca** [comment]
There's still isn't a pre-upload warning, but the issue it's been addressed by adding text stating the user's subjects limits. However, deleting subjects with the current UI doesn't reset the limit. @camallen sorry if that's been discussed before, but is that intended? Or does PFE need to hit a different endpoint (like you seem to hint in the post above)?

**Comment by camallen** [comment]
@simoneduca many times...we don't remove subjects we disable them, they only get removed permanently if they have not been classified nor discussed on talk. see https://github.com/zooniverse/Panoptes/pull/1983

**Comment by simoneduca** [comment]
Cool thanks.
