### ISSUE TITLE
Field Guide header color/framing to stand out against black backgrounds.

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3164]
Note: This is a low priority issue.

On projects w/ black backgrounds in particular, volunteers have posted asking if there's a better color choice/framing of the 'Field Guide' header. 

<img width="1034" alt="screen shot 2016-10-27 at 11 33 54 am" src="https://cloud.githubusercontent.com/assets/4975655/19776389/83c6d9e6-9c39-11e6-8eed-1dba9c3fa105.png">
<img width="1035" alt="screen shot 2016-10-27 at 11 33 48 am" src="https://cloud.githubusercontent.com/assets/4975655/19776390/83cc2d2e-9c39-11e6-97ca-c8aa7a3b6aab.png">

The two images showcase 1) a project with a black background and what the Field Guide looks like against it and 2) a project with a non-black background.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
