### ISSUE TITLE
On iPad - not able to copy or save an image

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3165]
## Expected behavior

Being able to copy/save an image (a subject) when classifying on an iPad.
## Current behavior

_Please include any error messages from the browser console and/or screenshots_
Not able to copy/save an image on an iPad. 
## Additional information
- **Operating system:**
- **Browser:**
  iPad 9.2.1 - Safari.

**Comment by srallen** [comment]
This is probably because of the SVG layer on top of the image. What is the goal? Why would you want to save a subject image on a tablet?

**Comment by trouille** [comment]
I posted this issue after receiving an email from the CWW lead based on a request from a longtime volunteer who had been classifying on the old Chicago Wildlife Watch and brought this up as a missing feature on the relaunched Chicago Wildlife Watch. I mistakenly thought it was just an iPad issue. 

Oroborous projects allow volunteers to save images (e.g., old ChicagoWildlifeWatch, Galaxy Zoo. etc.) within the classification interface while PFE projects don't. You can only save images once they're in Talk / within the Talk interface. When I posted this, I'd forgotten this is the way PFE projects work. 

I'll just let Mason (the CWW lead) know this and he'll follow up with the volunteer. And I'll close this issue.

**Comment by eatyourgreens** [comment]
Just to add I did a little bit of testing of this in Chrome this afternoon. As far as I can tell, right clicking on an SVG `<image>` tag doesn't give you an option to save the image from the context menu that pops up. This seems to be true whether or not the drawing tools are active and listening for mouse clicks.

Right clicking on a HTML `<img>` tag, which is what Talk uses, works just fine.
