### ISSUE TITLE
Getting a bigger subimage of the subject on the Talk search results when you search a hashtag. Current size is too small. 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3173]
It would help if the thumbnail was bigger like what you get for the Recent Comments to be able to quickly scan the subject and see if it has what you're looking for. I'm trying to find new targets locations from Talk before the seasonal campaign window ends and if I want to use the talk hashtag search I'd have to click on each subject to get a clearish picture.  There's 52 pages, so not something I'm going to do, but I would scroll through them if the thumbnail was bigger.

<img width="1097" alt="screen shot 2016-10-31 at 4 13 27 pm" src="https://cloud.githubusercontent.com/assets/753325/19877663/48908eea-9f85-11e6-9594-3784d4d43876.png">

Recent comments page:

<img width="1111" alt="screen shot 2016-10-31 at 4 16 32 pm" src="https://cloud.githubusercontent.com/assets/753325/19877679/71ea2b7a-9f85-11e6-9f48-5d4ec0db7c0a.png">

**Comment by MvGulik** [comment]
![image](https://cloud.githubusercontent.com/assets/666868/20238776/0710ac26-a8f3-11e6-9bfb-b5ba4f35eaf9.png)
Nice.
(*definitely need to get me a higher res screen*)
