### ISSUE TITLE
Subject Count Badge (zero case)

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#3176]
For empty collections it looks a bit out of place.
![image](https://cloud.githubusercontent.com/assets/666868/19904173/db5f336a-a071-11e6-85d3-4cd54c466f6b.png)

Alternatives that seem a bit better:
- keep badge, plus additional zero.
- ditch badge on an empty collection.
- (_other ?_)

@wgranger 
(+_thanks for adding the badges_)

**Comment by MvGulik** [comment]
Looking at the [related code](https://github.com/zooniverse/Panoptes-Front-End/pull/3160/files), it seems subjectCount, although its suppose to be a number [`subjectCount: React.PropTypes.number`](https://github.com/wgranger/Panoptes-Front-End/blob/52e3131d1a2b92dd8e927008a554277ad5ad1682/app/partials/collection-card.cjsx#L11), gets away with being `undefined` in an empty collection case.

If that's the case, the most direct fix seem to be to force `undefined` into zero.
 at the [`subjectCount={collection.links.subjects?.length}`](https://github.com/wgranger/Panoptes-Front-End/blob/52e3131d1a2b92dd8e927008a554277ad5ad1682/app/pages/collections/list.cjsx#L131) point.
ie: `subjectCount={collection.links.subjects?.length ? 0}` 

Although ... It seems more appropriate if the `subjectCount: React.PropTypes.number` part would take care of that.(*?:if that's even possible, that is. Which I don't know, as that part is to deep into ZooCode's dungeon's for me*)

*pushing suggested fix in a day or so.*

**Comment by srallen** [comment]
@wgranger the issue I found in #2979 with the counts on the collections cards is more general than just that branch. Could you follow up with @MvGulik about the fix?

**Comment by wgranger** [comment]
@MvGulik Yes, per your suggestion, this would work if we give `subjectCount` a default prop (if one isn't passed or given when the card is rendered). Giving a default prop of zero would probably fix this.

**Comment by MvGulik** [comment]
@wgranger, Roger.

While prepping for push I run into a problem. I can't used the "Reveal Subject Count Badge" file for that (*option is disabled*), but the master is not up-to date yet (one day older then the "Reveal Subject Count Badge" merge.)

Just wait until master-branch catches up ?
(*I'm kind new at GitHub's push and pull stuff.*)

**Comment by wgranger** [comment]
The master branch should be up to date. It looks like `collection-card.cjsx` has the `badge` functionality on master. I'd make sure you pulled the latest master before checking out a new branch to fix the issue. You can always paste the error message here if you still have an issue.

**Comment by srallen** [comment]
@MvGulik You'll want to configure another remote to point to the original zooniverse repo so you can either pull down the latest master and merge it or consider doing a rebase:
https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview

**Comment by MvGulik** [comment]
I think the master was updated while I was still experimenting and reading up on how to proceed.

Works too. :)
