### ISSUE TITLE
Chicago Wildlife Watch project card image is really pixelated

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3178]
Not sure if this should go here, but since the owner is the zooniverse account I thought maybe it does. The image on the project card for Chicago Wildlife Watch is really pixelated. Maybe a higher resolution image is needed? Feel free to close or mark as will not fix.

<img width="972" alt="screen shot 2016-11-01 at 3 48 49 pm" src="https://cloud.githubusercontent.com/assets/753325/19913926/dc6bd79e-a04a-11e6-878b-a868cb30da99.png">

**Comment by jwbmartin** [comment]
That is gross looking but it's also up to whoever is the owner of this project to fix it. @mcbouslog do you know anyone on Chicago Wildlife Watch?

**Comment by mcbouslog** [comment]
Unfortunately I don't, but I'm fairly certain @trouille does?

**Comment by mschwamb** [comment]
the project owner is the the zooniverse account

**Comment by jwbmartin** [comment]
@mcbouslog ok cool I thought maybe you worked on it

**Comment by srallen** [comment]
Gonna close this since we can't fix it. @trouille do you know who can be messaged about this? Thanks.

**Comment by trouille** [comment]
Hi all -- thanks for the heads up. I uploaded a higher res image.
