### ISSUE TITLE
Project classification interface won't load

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#318]
When I try to classify on my whale project, http://demo.zooniverse.org/panoptes-front-end/#/projects/aliburchard/WhaleTails/ , I get spinning circles of death. This happens on chrome, firefox, and safari.
![screen shot 2015-05-14 at 09 15 21](https://cloud.githubusercontent.com/assets/6217406/7628322/cfbf0abc-fa19-11e4-9244-74371f6e4324.png)

**Comment by camallen** [comment]
This is because the subjects don't exist on s3 due to the media URL bug that ed fixed in https://github.com/zooniverse/Panoptes/pull/832/. I suggest removing the problematic subject sets and the uploading data again.
