### ISSUE TITLE
Paused projects show up under active tab as well

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#3181]
For instance, check Season Spotter Image Making:

![screen shot 2016-11-02 at 16 38 39](https://cloud.githubusercontent.com/assets/8989606/19937938/020fda1a-a11b-11e6-9562-c202d4e88209.png)

![screen shot 2016-11-02 at 16 38 54](https://cloud.githubusercontent.com/assets/8989606/19937965/1425c098-a11b-11e6-990f-1031e2df290d.png)

**Comment by rogerhutchings** [comment]
Are these projects also returned in the `active` response from the API?

**Comment by rogerhutchings** [comment]
ref #3169

**Comment by simoneduca** [comment]
This is at least part of the problem https://github.com/zooniverse/Panoptes/pull/2027
In trying to answer your question, something odd has come up: although 49 projects are displayed, the api call returns only 19 (see screenshot)

![screen shot 2016-11-03 at 10 53 45](https://cloud.githubusercontent.com/assets/8989606/19963535/b68c8972-a1b4-11e6-820c-1d0de7908635.png)

That's still not quite correct because, e.g., "Pattern Perception" which should be paused is still fetched in the response. 
Not quite sure what's going on... I'll investigate.

**Comment by rogerhutchings** [comment]
Interesting - the paging param in the URL may not match the one in the API request... can you compare the two?

**Comment by simoneduca** [comment]
I don't see any difference, but I'm not sure I understand what you mean

**Comment by eatyourgreens** [comment]
Default page size on these requests is 20, I think, which is the number of projects you're getting back.

**Comment by simoneduca** [comment]
Ah... how do we get 49 displayed then?

**Comment by eatyourgreens** [comment]
I'm not sure I follow. There are 3 pages of results: 20, 20 and 9?

**Comment by simoneduca** [comment]
Of course, sorry my bad. Thanks, that explains why I get back 20, but not why the status filter isn't applied correctly.

**Comment by eatyourgreens** [comment]
Yeah, that's Panoptes ignoring the status value because the database only contains `paused` and `finished` at the moment. So `status=active` returns everything.

**Comment by simoneduca** [comment]
Cool, so zooniverse/Panoptes#2027 should sort that out.

**Comment by zwolf** [comment]
Yup, `?state=live` will now be interpreted by the API as `?live=true` (which was not previously filterable). This is purely a workaround to simplify queries until we can finish the state-based refactor of project statuses.

**Comment by simoneduca** [comment]
Paused projects are still visible under active tab https://add-status-to-query-params.pfe-preview.zooniverse.org

**Comment by simoneduca** [comment]
Fixed via https://github.com/zooniverse/Panoptes/pull/2028
