### ISSUE TITLE
Add Button on New Homepage to Change Background

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3187]
## Expected behavior
A user should be able to change the background of her or his homepage _from the landing page_ with the click of a button. This is similar to how some social media sites allow you to change the cover photo.

## Current behavior
The default background is a solid green color, and the user might not be aware that (s)he can change the wallpaper.

## Additional information
A similar component currently exists in the edit profile section.

**Comment by simoneduca** [comment]
I was thinking of showing a little dialog on hovering over the avatar, offering two options "Change your avatar" and "change your background", or something like that. Thoughts? @jwbmartin

**Comment by jwbmartin** [comment]
I was thinking of following Facebook on this one where hovering over the avatar will you give a dialog box to change avatar while hovering over an icon in the corner of the background image gives you a dialog box to change background. Are you tackling this one @simoneduca?

**Comment by simoneduca** [comment]
Yeah, should be quite straightforward. I like your suggestion.

**Comment by eatyourgreens** [comment]
Hover could be a problem for touchscreens, or anyone who can't use a mouse, so can we make the image an interactive element and also have interaction on focus?

**Comment by eatyourgreens** [comment]
Facebook has an invisible button that becomes visible when you tab to it, for example.
![image](https://cloud.githubusercontent.com/assets/59547/20186541/5c2eb266-a768-11e6-9edc-106671fc7927.png)

**Comment by simoneduca** [comment]
Sounds good.
