### ISSUE TITLE
Set up details box appears even though I don't have any sub-tasks

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#319]
I have two projects with drawing tasks. While in the classification interface, when I perform the drawing task, the "sub task" box pops up, even though it is empty...

![screen shot 2015-05-14 at 09 49 34](https://cloud.githubusercontent.com/assets/6217406/7628726/ad8a2e22-fa1e-11e4-87de-e8168d67719d.png)
![screen shot 2015-05-14 at 09 48 13](https://cloud.githubusercontent.com/assets/6217406/7628727/ad9e170c-fa1e-11e4-9f8f-149e3d81231d.png)

**Comment by brian-c** [comment]
This was fixed by #309.
