### ISSUE TITLE
Is updated projects section of new Zooniverse logged-in home pages promoting projects that are not Zooniverse-approved and possibly not finished projects to all Zooniverse accounts?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3191]
I noticed that on my Zooniverse logged-in home page, the updated projects is including the one I'm currently building and is not done, but it's public since I shared the link so the workshop where we started the project could see it. Planet Four: Ridges is not Zooniverse approved.  I can't tell if it is showing for me and only me because I own it, but I don't think it should be promoted to all of the Zooniverse logged-in users. I think only launched Zooniverse-approved projects should show up on this list because you know they are complete and ready to accept classifications. There's many reasons why a project owner during the building process may make a project public but not want all of the Zooniverse to know of its existence just yet. Also that was one of the perks  for going through the Zooniverse approved process, that you get promotion through the Zooniverse. 

If you're going to keep it like this, then I think there needs to be a warning on the visability page that making a project public will promote it on the logged-in Zooniverse homepage. 

<img width="299" alt="screen shot 2016-11-05 at 9 12 54 pm" src="https://cloud.githubusercontent.com/assets/753325/20035983/98848cfa-a39d-11e6-9e69-72059af6f84e.png">

**Comment by mschwamb** [comment]
I've now made the project private and that changed moved it the top of the updated projects list.

**Comment by mschwamb** [comment]
Also the project was in development not set to live.

**Comment by MvGulik** [comment]
No "Planet Four: Ridges" at this end.
![image](https://cloud.githubusercontent.com/assets/666868/20037102/177fe366-a41a-11e6-92ab-e9d7b824d960.png)
But as I don't see Gravity Spy in yours. Some user history seems to be in play here.

**Comment by mschwamb** [comment]
This should be clearer what shows up here. Even if a project is updated if it's not launched, say if someone was a beta tester, I don't think it should show up on this list since there are projects which are rejected during the review stage.

**Comment by srallen** [comment]
The updated projects a volunteer sees are the projects they have participated in sorted by the projects' `updated_at` date, so it's the same list as the projects that comprises a volunteer's circle ribbon around the avatar. 

There are many reasons why a project that is active may not be launched approved and a volunteer may want to see if the project they have participated in have been updated. There are projects that are used educationally and some that choose not to apply for launch approval, but are still doing research using the project builder.

**Comment by mschwamb** [comment]
Everything else on that news section is Zooniverse-wide so it was unclear to me that it was only showing projects I go to/favorite. Perhaps a modified title for that 'Updated Favorite Projects' or 'Participated Project Updates' something along those lines. It was not clear that the Zooniverse wasn't broadcasting the top three most updated projects on their platform. 

 Part of the deal for being launch approved is that you get promotion in the Zooniverse to registered users so it seems to me that getting listed on the news section of the logged-in Zooniverse approved homepage should be restricted to Zooniverse-approved projects as this would count in the other promotion aspect of the policies page. Y'all might disagree with me on that.

**Comment by MvGulik** [comment]
'Participated Project Updates' seems the most clarifying text in this case.

Arguing that none officially launched project should not show up in that 'updated projects' list, while knowing that those listed project are user specific, sounds a bit strange to me.

From a project user point of view I would find it very strange if beta projects I participate in would not be included in that list, while knowing its specific to projects I'm active in. ... *in which case the 'Participated Project Updates' title would become somewhat ambiguous again.*

**Comment by srallen** [comment]
The rewording of the header to `Participated Project Updates` makes sense to me, however, I don't think we should change the filter on the projects at least for now. Maybe at least filter for only live projects? 

I'll submit a PR to update the header and will leave the issue open for now for any more discussion on the filter.

**Comment by mschwamb** [comment]
@srallen I think filtering to include live projects only makes sense.

**Comment by MvGulik** [comment]
I think the "promotion" argument is a bit strong, and a bit flawed too. As the users that see updated messages for none live projects (*presuming 'live' being interchangeable with 'launch approved'*) ... already know about those projects.

It also makes me wonder about the none live projects in the volunteer's projects circle. As I think the same 'promotion' argument could just as easily be applied on those too. ... The only significant difference to me here seems to be the display location of these different Zooniverse features.

Think that kinda raps is up for me.

**Comment by mschwamb** [comment]
@MvGulik 

live= accepting classifications that count toward retirement.  if you're not live the project is still in development and classifying doesn't count toward retirement of those subjects. 

launch approved= live project that gets Zooniverse approval and shows up on Zooniverse projects page.

So @srallen is suggesting that live (not only Zooniverse approved but all) should show up on this list and if the project is in development then it doesn't show up

**Comment by MvGulik** [comment]
@mschwamb 
Roger. Adjusted/Retracted previous message.

**Comment by mschwamb** [comment]
My main issues was resolved. So closing.
