### ISSUE TITLE
Collection cards are not the same length if the collection is private

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3192]
Not sure if this is as intended. If the collection is private the collection card gets longer than those of non-private collection cards 

<img width="1022" alt="screen shot 2016-11-05 at 9 51 40 pm" src="https://cloud.githubusercontent.com/assets/753325/20036137/0be0f990-a3a3-11e6-975c-195c3debb20a.png">

**Comment by mschwamb** [comment]
This was under the My Collections tab

**Comment by jwbmartin** [comment]
I feel like we could just add the lock symbol at the beginning or end of the Project card title. That should give a clear enough indication that that is a private collection.
