### ISSUE TITLE
Add a link to the signed-in home page in the user dropdown menu.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#3199]
or "Take me back to the ring of classifications!"

![screen shot 2016-11-08 at 15 33 40](https://cloud.githubusercontent.com/assets/8989606/20105247/cd75dc0c-a5c8-11e6-808c-bfb1b49c035d.png)

**Comment by jwbmartin** [comment]
hmmm I would say just call it Home or Zooniverse

**Comment by simoneduca** [comment]
Awwwlright then.
