### ISSUE TITLE
Can't add collaborators

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#320]
Not sure if this relates to backend issues (@camallen, @edpaget)? I can't add collaborators to a project I have just created.  Display below from both firefox and chrome.

![screen shot 2015-05-14 at 09 54 14](https://cloud.githubusercontent.com/assets/6217406/7628787/3b737b44-fa1f-11e4-8fad-3b4cc6408d36.png)

![screen shot 2015-05-14 at 09 54 50](https://cloud.githubusercontent.com/assets/6217406/7628797/577dac2e-fa1f-11e4-876b-4417c3eaefab.png)

**Comment by camallen** [comment]
this seems to be caused from a long query in the backend that's causing rails to run out of memory, investigating now.

**Comment by camallen** [comment]
Yeah this is a bug on the backend, it was enumerating all the users and generating an etag for each before even attempting to render the response. I'll open a PR to panoptes with a fix and some thoughts.

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/pull/840
