### ISSUE TITLE
Gravity Spy progress charts are all at 0

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3207]
https://www.zooniverse.org/projects/zooniverse/gravity-spy/stats

All the `completeness` values for each workflow seem to be at 0. I had a look at a couple of other projects, and they seem to be okay.

**Comment by CKrawczyk** [comment]
The `completeness` is based on the number of retired images for gravity spy, and it is using a custom retirement algorithm.  I am not entirely sure what method they are using for retirement aside from having `gold standard` subjects never retire.

**Comment by camallen** [comment]
pinging @trouille

**Comment by trouille** [comment]
Yes, definitely on our radar. I'll have Scott Coughlin post here to explain the setup and his upcoming plans for turning on retirement as we have new data flowing into the system (the new engineering run recently began). He's out sick yesterday/today, so it might take another day or two.

**Comment by scottcoughlin2014** [comment]
Hey All,

The custom retirement criteria works as follows.

There are three outcomes for every image on the website.

'G' - As noted never retired and there forever
'R' - If a thoughtful combination of human classification based on skill level and ML belief are above a certain threshold the image is decided to be of a particular class and is then moved from the subject set it is in that is and is linked to a work flow to a subject set labelled "Class" (R) which is linked to no workflow and will never be labelled again.
'M' - either too many people have labelled this image without consensus at which point it will move to more expert users for further analysis and clustering or enough people label it "None of the above" in which case the same thing happens.

Please do ask any questions but it will be hard to really track how many images have been "retired" through the custom workflow as far as on the site statistics is concerned I think. Lots of moving parts.

**Comment by camallen** [comment]
So you're not actually retiring data in a workflow, instead you are just promoting subjects up the chain to different workflows?

**Comment by scottcoughlin2014** [comment]
We only move data up the workflow is it gets a 'M' label. If it gets a 'R' in any workflow it's gone and retired

**Comment by camallen** [comment]
Are you ever actually calling the retire end point for that workflow / subject combo before pulling it? That would save our subject selector a reload and update the stats accordingly.

**Comment by scottcoughlin2014** [comment]
I did not know I can call the retire endpoint! I will do this!

**Comment by marten** [comment]
Sounds like they're actually removing subjects from sets when they get 'R'. I would suggest leaving them in the set, but calling the retire endpoint like @camallen said. If you remove them I think they'll still be ignored by the stats?

**Comment by srallen** [comment]
@scottcoughlin2014 Apologies I wasn't more clear about the existence of a specific retirement endpoint. The python client supports it in the workflow class. See here in the client code: https://github.com/zooniverse/panoptes-python-client/blob/master/panoptes_client/workflow.py#L11

**Comment by scottcoughlin2014** [comment]
ok I will keep them and deem them retired then! Thanks for the tips guys!

**Comment by srallen** [comment]
Closing. Gravity Spy team have implemented a script to call the retirement endpoint.
