### ISSUE TITLE
Project context collections settings and collaborators routes broken

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3227]
## Expected behavior
While viewing an owned collection in project context, I should be able to get to its setting or collaborators tab.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Routes for a collection's settings or collaborators tab in project context are broken and 404.

## Steps to replicate
Go to an owned collection while in a project context and go to the settings.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by MvGulik** [comment]
Only for Favorite-collections. See #2906

**Comment by eatyourgreens** [comment]
Looking through the [routes file](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/router.cjsx), I don't think Favourites are supposed to have settings or collaborators, and this must be a mistake that crept in when #2804 was merged.

**Comment by MvGulik** [comment]
Why block features that are working without any problems (*other than the related links pointing to the wrong path.*).

It would lock favorites to private only.

And will force users to empty there collection by deleting the collected subjects one by one.
Which I think is not particular user friendly.
ie: 
![image1](https://cloud.githubusercontent.com/assets/666868/20357279/99fe77f2-ac27-11e6-90f3-37f681b30ea0.png)
