### ISSUE TITLE
Search Bar Bug

### ISSUE THREAD

**Issue by jwbmartin** [zooniverse/Panoptes-Front-End#3228]
## Expected behavior
Should be able to search and go to project

## Current behavior
It goes back to home screen. I have a video of the behavior if you want to check it out

## Steps to replicate
Go to Project Page type something into the search bar and click on the result

- **Operating system:**
iOS 10.10.5

- **Browser:**
Chrome

**Comment by camallen** [comment]
@jwbmartin project search bar works fine for me on os x / android chrome.

**Comment by eatyourgreens** [comment]
@camallen try searching for Galaxy Zoo. 

@simoneduca this is the bug that I was showing you earlier. Fully qualified URLs can't be pushed to History.

**Comment by camallen** [comment]
Good call @eatyourgreens - this is only an issue for externally linked custom projects then. PFE projects seem to work fine but legacy / external ones like Galaxy Zoo / Annotate, etc fails to link properly.

**Comment by srallen** [comment]
I'm pretty sure this was working when we first merged the projects page update with the search bar so I think react router updates must have introduced a regression we missed.

**Comment by camallen** [comment]
Could be [the cards param](https://github.com/zooniverse/Panoptes-Front-End/blob/a9923e04aecf5c6581c31b38f36610f713eab1fd/app/pages/projects/project-filtering-interface.jsx#L55) i made @simoneduca add for faster responses. However I haven't tested the response differences on that.

**Comment by jwbmartin** [comment]
Thanks for looking into this, team!

**Comment by eatyourgreens** [comment]
@camallen there should be a warning in the console, saying that you can't pass a fully qualified URL to`History.push`. That's the bug I came across this afternoon.
