### ISSUE TITLE
Collection card subject count badge styling

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3229]
## Expected behavior
The badge shouldn't expand the container to be larger than it should be.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The badge styling needs revision so that it's not expanding the container and causing the background image to repeat:

<img width="229" alt="screen shot 2016-11-15 at 11 37 32 am" src="https://cloud.githubusercontent.com/assets/5016731/20316680/6d801ca8-ab28-11e6-9410-1d7e7251b700.png">

`position: absolute` would probably fix this.

## Additional information

- **Operating system:** OS X 10
- **Browser:** Chrome

**Comment by MvGulik** [comment]
Just exploring one html-css option.

Applied change (local test)
```
.collection-card {
    background-repeat: no-repeat;
    background-color: #fff;
}
```

Before:
![clipboard-3](https://cloud.githubusercontent.com/assets/666868/20401976/287a1a8a-acfb-11e6-875d-ddcd81a0a743.jpg)

After:
![clipboard-1](https://cloud.githubusercontent.com/assets/666868/20401977/287a47e4-acfb-11e6-9c35-cbe528788489.jpg)

*Note: The image parent container is the whole card/badge(?), which kinda disables the `Background-size: cover;` and vertical use of the `background-position: <hor> <ver>;` options.*
