### ISSUE TITLE
Project-Subject Mention in Talk. (exception)

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#3241]
If a `^S<subject_id>` subject link in Talk is preceded by a none blank character, The post in which the mention is used will not show up in the Mentioned list in the target subject-page.

*The subject link in this case is rendered as expected/active-link.*

**Comment by parrish** [comment]
The fix for this will not build the link without the separator.  e.g. `"Look at ^S123"` will work as expected, but `"That one (^S123)"` will not show as any kind of link.

**Comment by parrish** [comment]
Fixed by zooniverse/markdownz#50
