### ISSUE TITLE
Bottom navigation bar links for How to Build and Project Policies don't work quite right anymore

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3248]
Bottom navigation bar links for How-To and Policies need to be updated their going to weird places like an empty page or to the wrong place

How to Build a Project goes to https://www.zooniverse.org/help/lab-policies but no longer exists. It should be https://www.zooniverse.org/help

Project Policies currently goes to https://www.zooniverse.org/lab-policies but that should now be https://www.zooniverse.org/help/lab-policies

**Comment by MvGulik** [comment]
\+ Foother 'Education' link.

**Comment by MvGulik** [comment]
I 'might' try to push related fixed (*while playing with branches a bit*) ... after work.
