### ISSUE TITLE
tutorial shows at much lower hight and partially blocked (on smaller screens) if you come from landing page but not if you click on the tutorial button

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3249]
If you go from the landing page with the blue zooniverse navigation bar, 

<img width="1100" alt="screen shot 2016-11-19 at 9 41 20 am" src="https://cloud.githubusercontent.com/assets/753325/20458011/d70deb98-ae3c-11e6-9372-8853a096f518.png">

to the classification interface, the tutorial is really low on the page:

<img width="1110" alt="screen shot 2016-11-19 at 9 41 27 am" src="https://cloud.githubusercontent.com/assets/753325/20458014/f08b6d16-ae3c-11e6-8ff2-0583075f6fc4.png">

If I close the tutorial and reopen with the tutorial button, the tutorrial box shows up much higher and all of it is visible

<img width="1105" alt="screen shot 2016-11-19 at 9 41 34 am" src="https://cloud.githubusercontent.com/assets/753325/20458022/2ec476f4-ae3d-11e6-8b43-845be8b847a5.png">

Can the tutorial box always show up as it does when you hit the tutorial box when there is no blue Zooniverse navigation bar?

I'm using latest version of firefox on mac

**Comment by MvGulik** [comment]
Seems a bit of a timing thing.
Just reloading a classification page tends to give the same result. *But not always.*

###### _Local stuff: Chrome(49), Desktop, Windows(xp), 1024x768._

**Comment by mschwamb** [comment]
i think it's go to do with whether the interface is calculating height with the blue navigation bar or not

**Comment by MvGulik** [comment]
Waiting some time before opening the tutorial don't seem to matter. Same results.
Flipping the page between zoomed-out and zoomed-in also seem to have no effect.
(*Both after a page reload*)

Not properly updating or clearing some related var/setting seems more likely.

After the tutorial has been opened one time, its seems to keep opening at its proper location (*as long as that window/tab stays in the same session. ie: staying in the same domain and no reloading.*).

Think that's about as far as my observational debugging skills will go.

**Comment by MvGulik** [comment]
>i think it's go to do with whether the interface is calculating height with the blue navigation bar or not

Figured, after a nights sleep, that depending on how I read that, its more or less saying the same thing.
ie: ... has calculated ...

**Comment by wgranger** [comment]
This is happening on mobile as well, but to a much greater extent. I believe this is happening because the position of the modal is set in the reposition function of the dialog.js file (see modal-form repo under Zooniverse). The position gets set before the modal has all the content for its final size, so the `form.offsetHeight` is initially too short.

**Comment by wgranger** [comment]
Closed by modal form [PR ](https://github.com/zooniverse/modal-form/pull/23)

**Comment by srallen** [comment]
The modal-form will need more work to fix this.

**Comment by eatyourgreens** [comment]
Should be fixed by zooniverse/modal-form#28 (fingers crossed)
