### ISSUE TITLE
If you're not logged in and try to go to a workflow that is out of data you get an error 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3256]
This is happening for me in the Comet Hunters HSC search workflow. 

<img width="1104" alt="screen shot 2016-11-22 at 11 19 17 am" src="https://cloud.githubusercontent.com/assets/753325/20531737/a8e2e82a-b0a5-11e6-89e4-3425fc4a4978.png">

If I log in, I can access the HSC search workflow and see a retired image with the appropriate banner.

**Comment by mschwamb** [comment]
Comet Hunters has two workflows so perhaps this is only issue when there are multiple workflows.

**Comment by camallen** [comment]
@mschwamb we're on it and no it's all finished workflows right now. Any reason why that workflow is still active?

**Comment by mschwamb** [comment]
Because data is supposed to be going back onto the site in a few days, so it was easier to write an announcement then remove the workflow and change it off of being the default and bringing it back.

**Comment by camallen** [comment]
@mschwamb right, this bug should be fixed soon. 

Out of interest, did you know you can de-activate workflows via the visibilty tab in the project builder under "worfklow settings" and not affect the live / launch status of the project?

**Comment by mschwamb** [comment]
Yep. For a few days/a week or two it's easier to just leave it live.

**Comment by camallen** [comment]
Fixed now.
