### ISSUE TITLE
Email notification link doesn't load discussion and image on Talk

### ISSUE THREAD

**Issue by anhaltdepies** [zooniverse/Panoptes-Front-End#3259]
## Expected behavior
When a users receives a Talk Notification via email, typically clicking on the "View on talk" link will direct the user to the discussion on Talk. 

## Current behavior
Subject image and discussion does not appear for some users after clicking on the "View on talk" link within their email notification. 

![Imgur](http://i.imgur.com/i7yKGsM.jpg)

## Steps to replicate
Click on the "View on talk" link within an email notification. 

## Additional information
- **Operating system:**
Reported by users to occur in ubuntu 16.04.1 LTS, Windows 7
- **Browser:**
Reported by users to occur in Chrome, Mozilla Firefox

**Comment by MvGulik** [comment]
Fixed by: #3282
(_Not reproducible anymore_)

**Comment by mschwamb** [comment]
closing based on the comment above.
