### ISSUE TITLE
"@" symbol in URL and code block is being parsed as username tag. (Pulled from Talk)

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#3260]
[notes-from-nature post](https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/436/128432)
(*[zooniverse post](https://www.zooniverse.org/talk/17/130708)*)

It kinda makes sense that the conversion of the "@" symbol into a user link should skip URL parts and code blocks.

**Comment by parrish** [comment]
Thanks!

Once zooniverse/markdownz#50 is merged, I'll get a PR in to fix this.

https://fix-mention-parsing.pfe-preview.zooniverse.org/projects/zooniverse/notes-from-nature/talk/436/128432?env=production shows the behavior of proposed fix.

**Comment by parrish** [comment]
Fixed by zooniverse/markdownz#50
