### ISSUE TITLE
Collaborative Collection

### ISSUE THREAD

**Issue by jwbmartin** [zooniverse/Panoptes-Front-End#3263]
## Expected behavior
When you create a collaborative collection the collection should appear in all of the collaborators "My Collections" list. Perhaps it shows up with a small icon like http://fontawesome.io/icon/users/ similar to how private collections appear with a small lock icon to indicate private collections 

## Current behavior
It only appears in the creator of the collection list

## Steps to replicate
Make a collection. Add a buddy as a collaborator. Ask buddy to look at his/her collections. Not see it. Be confused.

**Comment by mschwamb** [comment]
duplicate issue - already in  summarized list of collection bugs in #1829

**Comment by mcbouslog** [comment]
by checking if `collection.links.collections_roles.length > 1` we can then add the group icon to collection card
