### ISSUE TITLE
Should projects you are a collaborator on show up in 'My Builds' part of Zooniverse home 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3264]
This came up with a new collaborator for the new project we're building. I'm the project owner and my collaborator tried to find the project under the 'My Builds' and it wasn't showing up since it seems to show only projects the account owns. Should all projects someone is a collaborator on show up on the new Zooniverse logged-in homepage?

**Comment by jwbmartin** [comment]
Yes I think that anything (projects or collections) that you are a collaborator on should show up under your profile as well.
