### ISSUE TITLE
Review of text

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Panoptes-Front-End#327]
I'd like to review the text on the whole site once it's done...

**Comment by DarrenMcRoy** [comment]
Hey Chris, this isn't mostly a first-draft dump of ideas, plenty of work to be done, but here's some of what I've written, and some of my ideas, so far. It's very far from "done," some of it is still being first-drafted, and some are just ideas for potential pages to have, but feel free to take a look:

https://docs.google.com/a/zooniverse.org/document/d/13sP5U4JRmewpJsNRoSfKt54KvYhiKcxzw3f5kyrUzAA/edit?usp=sharing

I'm particularly interested if anyone would like to add more questions to the "FAQ" portion. I'm happy to research and write out answers to them, but I'm curious of those who have been with the Zoo longer might be able to anticipate some more top-level questions that we could anticipate and address.

**Comment by vrooje** [comment]
I've made a start on some comments... will probably have more soon. @DarrenMcRoy I'm assuming this document contains the text that will go in for the first release? If so you might want to tag others you specifically want to comment this week so they'll see this even if they're not following all notifications for the repo.

**Comment by DarrenMcRoy** [comment]
Content has been sorted somewhat based on what is absolutely necessary for first release, what is done, what will be done for later iterations, etc.

Some content (green highlighted) is ready for a @chrislintott review, I think!

**Comment by DarrenMcRoy** [comment]
@mrniaboc Would you be able to please tackle the contact and social-media page content? You know all that stuff best. Can go in the same Zooniverse Home content doc.

**Comment by chrissnyder** [comment]
Text for first version of site done. Closing in favor of more piecemeal issues.
