### ISSUE TITLE
General UI issues in Project Builder

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3273]
- Headings, subheadings etc aren't consistent across pages.
- The 2 column layout for main content makes it hard to find things. If that makes pages too long, then we should be designing a better information architecture
- We show all the help text all the time, which makes the process quite noisy. We can toggle it, or provide tooltips instead.

Open for more suggestions...

**Comment by simoneduca** [comment]
Relevant to the 2 column design: I think Ali's suggestion is quite good. https://github.com/zooniverse/Panoptes-Front-End/issues/245

**Comment by CKrawczyk** [comment]
100% agree that the 2 column format is confusing, I just spent 5 mins looking for the "allow hiding marks" option because I expected it to be in the left column (with the rest of the workflow options) instead of the right column.
