### ISSUE TITLE
Zooniverse.org Projects won't load in IE11

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#3275]
## Issue Overview
Zooniverse.org projects - such as https://www.zooniverse.org/projects/mozerm/snow-spotter - won't load at all in Win7+IE11. No blatant error messages; you just get nothing. [Absolutely nothing.](https://www.youtube.com/watch?v=GB7mHxdHlRY)

## Expected behavior
* Go to https://www.zooniverse.org/projects/mozerm/snow-spotter or any Zooniverse.org project
* You should see this:
![screen shot 2016-11-24 at 15 00 47](https://cloud.githubusercontent.com/assets/13952701/20602824/d624fb54-b256-11e6-9e91-344c2cb68350.png)

## Current behavior / Steps to replicate
* Go to https://www.zooniverse.org/projects/mozerm/snow-spotter or any Zooniverse.org project
* You'll see this instead, forever:
![screen shot 2016-11-24 at 14 53 07](https://cloud.githubusercontent.com/assets/13952701/20602875/060bfd0e-b257-11e6-917b-3b67ee6d2f26.png)

## Additional information

- **Operating system:** Windows 7
- **Browser:** IE11
- Tested on two computers - a native Win 7 machine and a modern.ie replicant in Virtual Box.
- Tested with user logged in and logged out - there's no significant difference.
- Tested on zooniverse.org and localhost - same issues across both.

## Status
Investigations are ongoing, but any help is welcome. Issue is a riddle, wrapped in a mystery, inside an enigma, lightly coated with the breadcrumbs of ambiguity, and doused in the ketchup of confusion.

**Comment by rogerhutchings** [comment]
Did you write this issue before lunch?

**Comment by shaunanoordin** [comment]
Nope, in the late afternoon, but I ran out of snacks by then.

**Comment by shaunanoordin** [comment]
## Investigation Update
Error detected at https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/home.jsx#L65
`workflowAssignment={this.props.project.experimental_tools.includes('workflow assignment')}`

It turns out in IE11, `experimental_tools.includes` doesn't have `.includes()`.

A potential fix is to change that line to...
```
workflowAssignment={(this.props.project.experimental_tools.includes)
  ? this.props.project.experimental_tools.includes('workflow assignment')
  : false}
```

**Comment by eatyourgreens** [comment]
Should we change this to checking `Array.indexOf` instead?

**Comment by shaunanoordin** [comment]
The Polyfill solution in #3276 was a way more elegant method of solving this. Thanks @eatyourgreens !
