### ISSUE TITLE
Pan&zoom, Invert-image, image-mouse-clicks toggles pan&zoom off. (camera-catalogue)

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#3281]
Related page: [panthera-research/camera-catalogue/classify](https://www.zooniverse.org/projects/panthera-research/camera-catalogue/classify)

After using the invert-image option on the page, the pan&zoom feature will consistently toggle itself Off (*if On*) on mouse-click on the image (*blocking any further mouse related image panning*).
-- *Limited to the duration of the current classification subject.*
-- *Other pan&zoom inputs not effected.*

###### _Local stuff: Chrome(49), Desktop, Windows(xp), 1024x768._

**Comment by eatyourgreens** [comment]
Confirmed with Chrome on OSX: using the invert tool turns off the ability to drag the zoomed subject image.

As a workaround, until this is fixed, the cursor keys continue to work for panning around the zoomed image.
