### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by tingard** [zooniverse/Panoptes-Front-End#3288]
## Expected behaviour

`yarn install` should install all dependancies without error.

## Current behaviour

yarn install fails with message 

> "The engine "node" is incompatible with this module. Expected version ...
> Found incompatible module"

for `react-pullout` and `seven-ten`.

## Steps to replicate

- Fresh clone
- run `yarn install`

## Additional information

Yarn will run correctly if the flag `--ignore-engines` is specified.
I am testing on Mac OSX Sierra with node 6.9.1, yarn 0.17.9 and npm 3.10.8

## Proposed fix

Owners of react-pullout and seven ten update dependancies in package.json
As the code is working on the newer version of node (6.9.1) it seems the specified version of node is superfluous.

**Comment by parrish** [comment]
I don't have access to react-pullout though

**Comment by parrish** [comment]
Got access and updated it.  Should be good now
