### ISSUE TITLE
Survey values are weirdly processed in data exports

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#3290]
@mkosmala commented on [Wed Nov 30 2016](https://github.com/zooniverse/Panoptes/issues/2066)

Treeversity is a project that uses the survey tool. When I look at the data from the survey in the data exports, I see that the chosen values are all-caps versions of the original text with all spaces and vowels(!) removed. So, for example, the option "Leaf" becomes "LF" and the option "Autumn leaf color" becomes "TMNLFCLR". This is really unintuitive for project groups. I'm okay with dropping spaces, but please keep the vowels! It would also help to keep the original capitalization.

---

@camallen commented on [Wed Nov 30 2016](https://github.com/zooniverse/Panoptes/issues/2066#issuecomment-263919384)

@mkosmala what do the task survey key => values look like in the workflow? I think this is a vestige of the survey csv uploader setting those keys.

---

@mkosmala commented on [Wed Nov 30 2016](https://github.com/zooniverse/Panoptes/issues/2066#issuecomment-263921316)

@camallen The CSV that we upload doesn't have a key column. We have a name and a description. I'm sure something is converting names to (weird) keys, but I don't Panoptes well enough to know where. The Project Builder doesn't have anything other than names showing. I'm pulling a workflow export right now...
CC: @donnytree

---

@eatyourgreens commented on [Wed Nov 30 2016](https://github.com/zooniverse/Panoptes/issues/2066#issuecomment-263929123)

Looks like this is something that the survey task editor is doing in the front end here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/survey/editor.cjsx#L370

**Comment by mkosmala** [comment]
@eatyourgreens That's it! Drop vowels and white-space, then capitalize. So 
(1) Could someone rewrite that line for future projects? Even just not dropping vowels would be a big improvement.
(2) Is it possible to rename the IDs for project Treeversity?
