### ISSUE TITLE
Tutorial position indicator does not update

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/Panoptes-Front-End#3291]
## Expected behavior
The black dot below the images in pop-up tutorial should move to the right indicating where I am in the tutorial.
## Current behavior
The black dot does not move, but stays in the first spot (see attached images)

## Steps to replicate
Go to this project:
https://www.zooniverse.org/projects/mschwamb/planet-four-ridges
Click on "Get started" and then "Show tutorial"

## Additional information
- **Operating system:** Mac 10.11.6
- **Browser:** Safari 10.0.1, Firefox 50.0.1, Chrome 54.0.2840.98 (64-bit)

**Comment by mschwamb** [comment]
<img width="1065" alt="screen shot 2016-11-30 at 12 36 26 pm" src="https://cloud.githubusercontent.com/assets/753325/20774266/af32b124-b6f9-11e6-9859-18cb78c97262.png">

I'm on step two of the tutorial but the indicator black dot stays on the left most position
