### ISSUE TITLE
add dropdown task tests

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#3298]
add dropdown task tests

**Comment by eatyourgreens** [comment]
I've made a start on some basic tests for the dropdown task in #3440

**Comment by mcbouslog** [comment]
that's awesome! I'm hoping to help next week during one of our PFE improvement weeks.

I took some notes when you rewrote the dropdown task that I'll copy and paste into this issue for reference, though some items may not make sense, I haven't gone back through and edited yet...

**Comment by mcbouslog** [comment]
- [ ] initial annotation before any selection - all annotations `{option: false, value: null}`
- [ ] unanswered annotations after one selection - `{option: false, value: null}`
- [ ] only answer one dropdown when two dropdowns present (2nd not required), click Next/Done,  final annotation - includes unanswered annotations as `{option: false, value: null}`
- [ ] answer two or more, clear first dropdown - clears conditional dropdowns in UI
- [ ] answer two or more, clear first dropdown, annotations - all annotations `{option: false, value: null}`
- [ ] if enabled, answers (provided) persist
- [ ] if enabled, answers (custom) persist
- [ ] if disabled, answers don't persist
- [ ] custom answer in dropdown with options, annotation - ???
- [ ] custom answer in dropdown without options, annotation - ???
- [ ] can tab through

**Comment by eatyourgreens** [comment]
Cheers! Persisting data is out of scope for the task itself (I think that's handled by a higher-level component) but the task does need tests for state changes when there are linked menus. Maybe also tests for the individual component methods (eg. I'm not completely sure what [`getDisabledAttribute`](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/dropdown/index.cjsx#L130-L135) is supposed to do)?

**Comment by srallen** [comment]
Agree about persisting data. The class I wrote to handle that would in theory work with any of our task components, so should be tested independently.

**Comment by mcbouslog** [comment]
between initial tests added, additional tests added in #3484 and tests to be added in #3497 I think this issue can be closed, and if any new issues arise related to the dropdown task they can be new issues.
