### ISSUE TITLE
Removing the owner username from the project description listed on the projects page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#330]
On the project description the owner's username is listed. For the build I'm participating in, I own the project only  because I started the workflow but several other people contributed just as much to content and the decision tree design.. It seems there will be many projects built with several people contributing as collaborators on the built project which you can't give credit to in that project description.  

My suggestion would be to completely remove the username from the description box since all owners and collaborators are listed on the science page.

I might not be using the right terminology so I took a screen shot of what I'm talking about 
![screen shot 2015-05-09 at 10 14 27 am](https://cloud.githubusercontent.com/assets/753325/7640762/d90b611c-fab7-11e4-9be8-7a3384ed830e.png)

**Comment by chrissnyder** [comment]
I think I agree, however I haven't heard any other noise about this. If others bring up the issue, we can address this again.
