### ISSUE TITLE
Add average estimate for how long it takes for process of Zooniverse approval, beta test phase, and final approval to launch to Policies page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3303]
There's no information about what the average time it takes for a project to go from applying for Zooniverse approval moving on to beta and then launching as a Zooniverse review project  on the policies page where it describes the process. With a year of projects there's some estimate of how long it's currently taken and how frequently the Zooniverse sends out beta requests. Adding this information I think would be very helpful especially if typical times are 1 month timeline from applying for review for the beta test to occur. It might be helpful to give some kind of estimate so researchers know better what to expect out of the process.

**Comment by chrislintott** [comment]
Helen, could you add this?

**Comment by hrspiers** [comment]
Hi,

I've given the policies page a heavy edit and included approximate timings. I've pushed to PFE - am awaiting review before merging.

H
