### ISSUE TITLE
Missing/failed auto-append Page-setting to Talk-page URL. (last case it seems)

### ISSUE THREAD

**Issue by MvGulik** [zooniverse/Panoptes-Front-End#3305]
This seems to be the last case where a page-setting is not auto-added to a given Talk-related-URL.
(*Although I'm not sure about other links to talk-post coming from other none talk related locations.*)

This happens when the related post-linkup link is used/clicked.
(*Limited to Left-Mouse-Button/click action*)
![image](https://cloud.githubusercontent.com/assets/666868/20857861/8ecaa32e-b938-11e6-8469-c803bd9a33a7.png)

Although that link is not really intended to be used in this way, it is still an active link. And as such should probably also behave correctly. (*even if clicking on it would not do anything really useful, ... other than potentially showing/previewing how that page/post would be displayed when that post-link is used somewhere else.*)

###### _Local stuff: Chrome(49), Desktop, Windows(xp), 1024x768._

**Comment by eatyourgreens** [comment]
I'm not sure what the issue is here. Those permalinks for comments work for me: open Talk to the correct page and comment, page correctly when I navigate via the 'next' or 'previous' links.

What's the bug here, and how do we reproduce it?

**Comment by parrish** [comment]
Ah.  I understand.  The link behaves differently when clicking it in-page:

![link](https://cloud.githubusercontent.com/assets/122990/20897202/d8f5f21e-bae6-11e6-91f9-c1f5eb6311f3.gif)

**Comment by MvGulik** [comment]
*If there are any comments on how I could have made my first post more clear or readable. I don't mind hearing them.*

**Comment by parrish** [comment]
I didn't know what you meant by "page-setting is not auto-added" at first.  (That's actually just the app automatically changing the discussion page number if the comment specified in the url param is on a different page of the discussion.)

I always find gif demos to be helpful to illustrate behavior.  I use [LICEcap](http://www.cockos.com/licecap/) on Mac, but they have a windows version too.

**Comment by parrish** [comment]
As far as fixing this goes, @eatyourgreens any ideas why this link is behaving differently?

**Comment by eatyourgreens** [comment]
Is the bug here that the link scrolls back to the top of the page? Scrolling to the linked comment is handled by `componentDidMount`, but the `TalkDiscussion` component is already mounted here so that won't run.

Maybe `componentWillReceiveProps` needs to check for the presence of `page` in the parameters?

**Comment by MvGulik** [comment]
Closing as per "wontfix" tag.
