### ISSUE TITLE
Comet Hunters stats page reporting incorrect values for completion

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3313]
Says it is at 100% though we put new data on the site even before we announced we had new data and there were few classifications the stats page said the workflow was 100% complete. It's set to calculate from the classification counts.  I did the same thing on Planet Four: Terrains putting in new data and it does report back a correct value. P4: T has a single workflow. Comet Hunters has 2.

**Comment by mschwamb** [comment]
weird after the newsletter it looks like it reset. Maybe there is some threshold to trigger the count to get update.

**Comment by camallen** [comment]
@mschwamb it runs ~ every hour in the background. However https://github.com/zooniverse/Panoptes/issues/2049 proposes that it should depend on activity on the project.
