### ISSUE TITLE
Looks like stats page isn't updating 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3323]
Last update on plots was a few days ago on December 6th - just took the screenshot below - hitting the reset the plot range doesn't change anything

<img width="1068" alt="screen shot 2016-12-11 at 1 38 43 pm" src="https://cloud.githubusercontent.com/assets/753325/21084426/7d2eda70-bfa7-11e6-88ab-101fa81cc8ce.png">

cc @CKrawczyk

**Comment by CKrawczyk** [comment]
@camallen can you take a look at the stats server and see if it is logging data?

**Comment by camallen** [comment]
should be fixed by https://github.com/zooniverse/zoo-event-stats/pull/41

**Comment by mschwamb** [comment]
it's fixed, though I see a gap in the stats collected. Maybe there should be a note on https://status.zooniverse.org/?
