### ISSUE TITLE
Allow users to change their password

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#333]
Is there an endpoint? Putting `{users: {password: 'my new password'}}` returns a 422.

**Comment by edpaget** [comment]
Not through the API routes. It doesn't look like we set it up in the devise controller yet. I'll add that to my list for tomorrow.

**Comment by edpaget** [comment]
You can update passwords now. This is not an /api route so we can restrict domains allowed to do it, but making the following request should reset the password once zooniverse/Panoptes#861 is merged.

```json
PUT /users

{ 
  "user": {
     "password": "newpassword",
     "password_confirmation": "newpassword",
     "current_password": "oldpassword"
  }
}
```
