### ISSUE TITLE
not all collections are loading

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3335]
A lot of my collections are loading with the blank default zooniverse background and then if you click on those you can't access them. I've tried using the guest and fast staff internet connections at my office so I don't think it's a connection speed issue  issue.  

Also when you click on one of the empty collections it shows nothing. When I know there are subjects in that collection. See https://www.zooniverse.org/collections/mschwamb/planet-four-terrains-examples

<img width="1128" alt="screen shot 2016-12-13 at 2 48 29 pm" src="https://cloud.githubusercontent.com/assets/753325/21165409/4abecd78-c143-11e6-9d0d-5a317c6595e9.png">

and I get this on the logged-in Zooniverse home page

<img width="1107" alt="screen shot 2016-12-13 at 2 49 33 pm" src="https://cloud.githubusercontent.com/assets/753325/21165432/6ffa36ae-c143-11e6-81c6-6b989b97dfa0.png">

related to #3192 ?

**Comment by mschwamb** [comment]
If it helps, the only one that has a picture is the collection with a single image in it

**Comment by mschwamb** [comment]
Seeing the same behavior on the full [Zooniverse wide collections page](https://www.zooniverse.org/collections)

**Comment by MvGulik** [comment]
\**Wild guess/prediction: Not Panoptes-Front-End related.*\*

**Comment by camallen** [comment]
@mschwamb related to this, https://github.com/zooniverse/Panoptes/pull/2086 i should have a fix deployed soon.

**Comment by mschwamb** [comment]
Thanks @camallen. Still seeing it. Is the fix deployed?

**Comment by camallen** [comment]
@mschwamb should be all fixed now
