### ISSUE TITLE
add team member login to what's displayed in About/Team page list of team members

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#3337]
## Requested behavior (per [Talk comment](https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/438/144316?comment=251547))
add login to what's displayed in About/Team page list of team members, so a volunteer can mention a team member easily in Talk

similar to how a user is displayed next to their Talk comment

## Current behavior
About/Team page list of team members only shows `display_name`

**Comment by mschwamb** [comment]
actually that's if there is a display_name. if there is a username only it shows that. it's not consistent in showing both. it would be good if this also showed a link to the profile  - both those requests are in #2218

**Comment by mcbouslog** [comment]
thanks @mschwamb! I attempted to check if there was a similar issue; looks like I need to work on my GitHub searching skills! I'll close this issue, and focus on issue #2218 noted.
