### ISSUE TITLE
Lots of extra whitespace lines added when a Talk post is shown in a user's profile

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3341]
User profile page:

<img width="747" alt="screen shot 2016-12-16 at 11 56 30 am" src="https://cloud.githubusercontent.com/assets/753325/21276562/dc84bfc0-c386-11e6-9963-63f025be7b54.png">

Actual Talk post:

<img width="767" alt="screen shot 2016-12-16 at 11 56 23 am" src="https://cloud.githubusercontent.com/assets/753325/21276576/e8eb5f6c-c386-11e6-8df7-44dcc58609a3.png">

**Comment by eatyourgreens** [comment]
Caused by a vertical padding of 2.33em on paragraphs here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/css/owned-list-pages.styl#L26
Does anyone know why that was added, or what might break if it's removed?
