### ISSUE TITLE
Allow .cjsx Files to Import through Mocha

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3349]
## Expected behavior
`npm test` should work with jsx components that have cjsx imports. However, the compiler is unable to parse these imports. Our current compiler is coffee-script

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

## Steps to replicate
Create a spec that imports a component that in turn imports a cjsx file. 

## Additional information
coffee-react solved this problem initially, but the project has deprecated. 

- **Operating system:**
- **Browser:**

**Comment by srallen** [comment]
Fixed in #3428
