### ISSUE TITLE
Done button is unreadable (button box is same color as the text)

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#335]
![screen shot 2015-05-15 at 9 11 16 am](https://cloud.githubusercontent.com/assets/753325/7645160/6fcf560a-fae3-11e4-9487-c0e841d0d0d3.png)

**Comment by mschwamb** [comment]
Also it's hard to see the outline of the other buttons with the background color.

**Comment by brian-c** [comment]
Closed in #339.
