### ISSUE TITLE
Adding tags has bad UI and 422s if you add additional discipline tags.

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3356]
## Expected behavior
The UI in the lab for project tabs should display current tags in a way that makes it readable and also allows one to add additional discipline tags. Tags should probably display as a list without any non-human-readable data and not in the input. The tag `PUT` request should be formed correctly with strings in an array regardless if this is the first time or not.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The initial addition of discipline tags works. If you refresh the page, they show up in the Other Tags field with additional non-human readable data that shouldn't be there in the UI:
<img width="826" alt="screen shot 2016-12-21 at 11 32 36 am" src="https://cloud.githubusercontent.com/assets/5016731/21399478/7bd0de7c-c771-11e6-8617-1db553dde18e.png">

If you try to add another discipline tag, then it returns a 422. 

Additionally, one can select Space as a discipline, but displays in the other tag list as astronomy. This must be a discrepancy between front end UI and back end. 

## Steps to replicate
Described in current behavior.

## Additional information
N/A
- **Operating system:**
- **Browser:**

**Comment by parrish** [comment]
Are there any reasons why this shouldn't be a single tags input?  Pre-populated and autocompleted against the "Discipline" tags, but then also allowing freeform "Other" tags?

**Comment by srallen** [comment]
Not that I know of. I think the "Discipline" tags were added later and it may have been quicker to do what was done? I think the whole UI needs a redo and a single input makes sense to me.

**Comment by srallen** [comment]
Fixed by #3378
