### ISSUE TITLE
background image is moving up and down between classification interface and summary page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3372]
Oddly I don't see this on my other projects, but I notice that the background image moves up  when you get to the summary page. I found it a bit distracting. I think the background image should stay the same size between summary and not. Maybe it's the dimensions of the image? 

I took a screen capture so you can see what I mean. Look at the top of Pluto the tan orb behind the question  and answers. If you look at the top of Pluto compared to the top of the subject image, you see it moves up and down from when you're classifying to present with the summary page. 

![bug](https://cloud.githubusercontent.com/assets/753325/21717230/4a02e258-d3d5-11e6-84ce-9a1758fddcc5.gif)

I'm using this [background image](https://www.nasa.gov/sites/default/files/thumbnails/image/nh-pluto-charon-v2-10-1-15.jpg)

I'm using the latest version of firefox on macOS Sierra

**Comment by mschwamb** [comment]
I don't think I'm seeing things, when I put my thumb where the top of pluto is on the summary page, I can definitely see the shift.

**Comment by eatyourgreens** [comment]
The background image is sized according to the dimensions of the page, and the page height is just a little bit shorter for the summary than when the classification options are showing. I think this is the same bug as #2935.

**Comment by mschwamb** [comment]
@eatyourgreens   Yep. Looks related, though a larger fix. Would it be easy to make the summary page and classification interface the same height? At least the when classifying the background image would stay static and not be a source of eye strain/focus distraction. I noticed my eyes pulling each time I saw the summary.

**Comment by eatyourgreens** [comment]
@mschwamb I'm not sure. I notice it also on Comet Hunters, where the background image resizes when the number of answers to a question changes. A fixed background size would fix this, but page height is determined by viewport width eg. phone vs. tablet vs. desktop displays so I suspect this is not a quick design fix.
