### ISSUE TITLE
discipline tag entry disappeared and adding it back in, goes red in the project builder. other tags became garbled

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3381]
probably easiest to just show the screen shot from Planet Four: Ridges : 

<img width="1049" alt="screen shot 2017-01-09 at 1 50 22 pm" src="https://cloud.githubusercontent.com/assets/753325/21788548/6fb3d552-d673-11e6-86e9-0b3989e4deff.png">

This happened earlier last week, but I was able to add the tags back in. Is it because the project is in beta test?

**Comment by eatyourgreens** [comment]
Duplicate of #3566 I think.

**Comment by eatyourgreens** [comment]
I think this should have been fixed by #3378

**Comment by mschwamb** [comment]
Thanks @eatyourgreens - closing since it's a duplicate
