### ISSUE TITLE
Allow ability to search through projects in admin mode

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3387]
## Requested behavior
An admin should be able to search through all projects in admin mode while viewing "set project status." It's often difficult to find a project as you have to search through a long/paginated list.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Currently, there are around 24 projects per page, so it's not convenient to tab through multiple pages.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by srallen** [comment]
Search works using a query param in the url `?search=searchParameter`, so it works, but just needs to be added to the UI.
