### ISSUE TITLE
Freehand tools appear on all projects

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3388]
## Expected behavior
The freehand tools are currently experimental, so they should not appear as a drawing task for all projects unless turned on as an experimental feature.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
I chose a random project and was able to see freehand tools as a valid option for marking.

![screen shot 2017-01-12 at 2 58 27 pm](https://cloud.githubusercontent.com/assets/14099077/21908104/10e6e8cc-d8d8-11e6-8581-909d1641083b.png)

## Steps to replicate
Go to any workflow, choose a "draw" as your task, and check out your "type" under choices to the right.

## Additional information
I probably should've caught this in the PR review, but I'm just now noticing this after the tool has been merged.

- **Operating system:**
El Capitan
- **Browser:**
Chrome

**Comment by eatyourgreens** [comment]
Closed by #3389
