### ISSUE TITLE
Make recently discussed images on Talk shown on project landing page hyperlinks to talk subject pages

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3395]
It might be nice to make the Talk images that had recent comments links so people can see and go and click and directly see the discussion. It might be a useful feature that would be used by dedicated Talk volunteers 

<img width="1033" alt="screen shot 2017-01-15 at 7 49 01 am" src="https://cloud.githubusercontent.com/assets/753325/21965081/54b83666-dafc-11e6-87f8-5c729fa12af8.png">

**Comment by eatyourgreens** [comment]
Closed by #3663
