### ISSUE TITLE
Subject flagging needs a configuration UI

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes-Front-End#3396]
Setting `workflow.configuration.enable_subject_flags` to true will show a button on the classification page that enabled people to flag subjects as inappropriate.

This workflow configuration value currently cannot be set using the project builder. It should either be added to the admin section, or just be configurable in the lab pages so that any project owner can enable the flag button.

/cc @trouille @chrislintott

**Comment by trouille** [comment]
I think best to start with it in the admin section as an experimental tool until we use it in a few more projects.

**Comment by mcbouslog** [comment]
While testing I saw that after flagging a subject it was (as expected) not displayed again to be classified (to the same/flagging user, and was not displayed to a different user I use for testing).

I also saw in the subjects data export the subject flagged was retired, and in the classifications data export the metadata and subject_data fields had additional information related to the flagging.

What I'm not sure about is if/how we notify the project owner when a subject if flagged?
