### ISSUE TITLE
Confusing whether the background image and avatar get saved after initally uploading

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#341]
Thought I would bring this up since I and another science team member had exactly the same confusion independently when trying to upload background images.

 We were uploading trial images of the background and our first few times uploading  we're looking for save button or some confirmation message that tells you it's saved/successfully uploaded. It was unclear that the background image was saved without checking the website. Seeing the image in the box we were thinking like the text for the description and faq where you still have to hit save before it gets stored and shown on the project website.

**Comment by mkosmala** [comment]
I want to add to this. Once you've uploaded the images and gone off to make workflows, if you return to the "Project details" part of the project builder, the images no longer show up. I initially thought that maybe I hadn't yet uploaded them. But I had. There really needs to be some indication of whether the background image and avatar have already been set or not -- even better if you can see what they look like.

**Comment by aliburchard** [comment]
Agreed. I went through this circle a couple times when first building the projects before I realized that the images had saved.
