### ISSUE TITLE
Duplicates posts of Subject Notes Talk discussion boards - might be caused when the note is edited

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3410]
https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/668/162476
https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/668/162477
https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/668/162475

This is a super user from P4: Terrains posted on P4: Ridges so the person didn't likely post 3 times. 

Maybe something for @parrish ?

**Comment by mschwamb** [comment]
Seeing more of this crop up. Volunteer said they got "Cannot read property 'query' of null" so they hit submit multiple times on the post https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/668/163119?comment=281287 - can someone take a look?

**Comment by parrish** [comment]
Thanks Meg!  Fix is on the way.
