### ISSUE TITLE
ZooniverseTeam component used in Talk's init component

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3414]
## Expected behavior
I have no idea. It has probably been broken for a while since it appears to only be usable by admin accounts.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Found when updating `UserSearch` to use local component state and refs. It appears to use a helper in talk/lib to determine if the user is an admin, but even with admin mode checked on, I don't see this component rendered correctly in the DOM. 

We should determine what the intention of this component is and if we don't need it, then remove the cruft, otherwise it should fixed so it is usable.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by parrish** [comment]
It's basically an admin check for the zooniverse section.

It's used here and appears to be working.

https://www.zooniverse.org/talk 
<img width="319" alt="screen shot 2017-01-23 at 12 27 38 pm" src="https://cloud.githubusercontent.com/assets/122990/22217101/5a44d898-e167-11e6-897f-47697222dc0f.png">

Want to look at removing it?  It seems a bit silly

**Comment by srallen** [comment]
Huh, I guess my account isn't considered to be an admin or moderator in zooniverse talk. I don't see the moderator controls at all which is why it seemed broken to me. If we're not using it, then removing it sounds good. I can take a look at it.
