### ISSUE TITLE
Snapshot WI team page is incorrectly formatted in Windows

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3418]
## Expected behavior

<img width="1077" alt="screen shot 2017-01-20 at 4 04 00 pm" src="https://cloud.githubusercontent.com/assets/4975655/22167137/163ae64a-df2a-11e6-903d-6f8e6dbb241a.png">

This is the view on Mac-Chrome v55. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

<img width="1070" alt="screen shot 2017-01-20 at 4 02 05 pm" src="https://cloud.githubusercontent.com/assets/4975655/22167071/d0df0f72-df29-11e6-9ef1-b0cff251cb62.png">

This is the view on Windows Internet Explorer 11.

## Additional information

The research team used Markdown to create a table with their team member images and text. This is likely what's causing the issue. Other project team pages don't look this skewed. 

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
The photos are far too big, pushing the text over into the right column. They could fix this by uploading much smaller photos for the team page.

**Comment by trouille** [comment]
@eatyourgreens In the project builder, their code for that Team page section is as follows:

----------
# People #


## Christine Anhalt-Depies ##
|  |  |
| ---- | ---- |
| ![christine-anhalt-depies.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/c631730d-1664-4873-87d4-3760848519bd.jpeg =600x) | Christine Anhalt-Depies is a PhD student in the department of Forest and Wildlife Ecology at the University of Wisconsin-Madison. Her research focuses on understanding the educational and social outcomes of public participation in scientific research. |
----------



## John Clare ##
|  |  |
| ---- | ---- |
|  ![john-clare.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/f750a0a3-ec2a-4ff2-9c5a-733c6b0d5f9b.jpeg =800x) | John Clare is a PhD student in the department of Forest and Wildlife Ecology at University of Wisconsin-Madison. His primary interests involve understanding patterns in species distribution and abundance, with a particular focus on identifying limiting mechanisms and developing statistical techniques to address unique sampling problems. |
----------

## Susan Frett ##
|  |  |
| ---- | ---- |
| ![susan-frett.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/51923830-261b-4757-b035-330ae3227e16.jpeg =1200x) | Susan Frett is a natural resources educator for the Wisconsin Department of Natural Resources, with primary responsibilities including outreach using social media, volunteer recruitment and training. Her interest is in engaging citizens in nature and science based activities in order to help people develop a conservation ethic. Susan received her Bachelor’s degree in Environmental Science from the University of Iowa and her Master’s degree in Environmental Conservation from the University of Wisconsin-Madison. |
----------


## Christina Locke ##
|  |  |
| ---- | ---- |
| ![christina-locke.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/8dc0214b-67d3-404f-a184-833524202c86.jpeg =1000x) | Christina Locke is a research scientist for the Wisconsin Department of Natural Resources. She enjoys working at the intersection of science, policy, and outreach, and has particular interests in citizen science and GIS. Christina received her Bachelor's degree in biology from the University of Wisconsin-Eau Claire and her PhD in land use change and policy from the University of Wisconsin-Madison. |
----------


## Karl Martin ##
|  |  |
| ---- | ---- |
| ![karl-martin.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/3ce164e9-e3a2-4a96-b42f-4cc8b4e50c86.jpeg =1800x) | Karl Martin is the State Director for the Community, Natural Resource and Economic Development Program and an Assistant Dean with the University of Wisconsin Cooperative Extension. He is an adjunct Associate Professor at the University of Wisconsin-Madison’s Forest and Wildlife Ecology Department and recently served as the Wildlife and Forestry Research Section Chief at the Wisconsin Department of Natural Resources. Karl received his Bachelors degree in Wildlife Ecology at UW-Madison and his Masters and Doctorate degrees at Oregon State University. Karl’s research has focused on interaction of forest management and multi-scale wildlife habitat relationships. His current position focuses on the ‘Wisconsin Idea’ of taking the information and resources of the University to communities and citizens of the state. |
----------


## Aditya Singh ##
|  |  |
| ---- | ---- |
| ![aditya-singh.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/7affae21-793e-42c1-9e91-0afae0445627.jpeg =800x) | Aditya Singh is a post-doctoral scientist with the Department of Forest and Wildlife Ecology at the University of Wisconsin-Madison. He uses a combination of airborne and remotely sensed data to study the impacts of environmental change and disturbance on landscape-scale indicators of ecosystem health. |
----------


## Jennifer Stenglein ##
|  |  |
| ---- | ---- |
| ![jennifer-stenglein.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/2b9ecb6a-452b-425a-a7b8-6404bced1d81.jpeg =1000x) | Jennifer Stenglein is a quantitative wildlife research scientist with the Wisconsin Department of Natural Resources where she works on trail camera monitoring of Wisconsin’s wildlife. She is interested in getting students and the public involved in wildlife monitoring and using those data to understand spatial patterns and temporal trends in wildlife populations. |
----------


## Phil Townsend ##
|  |  |
| ---- | ---- |
| ![phil-townsend.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/627568bc-7fd4-4480-a58a-45749ad45db3.jpeg =1000x) | Phil Townsend is a professor of Forest & Wildlife Ecology at the University of Wisconsin. He is interested in how different components of ecosystems interact across landscapes, for example how nutrients and water affect vegetation, and then how patterns of vegetation processes affect insects and animals. He is particularly interested in how we can leverage a range of technologies including remote sensing to better understand ecosystems. |
----------


## Tim Van Deelen ##
|  |  |
| ---- | ---- |
| ![tim-van-deelen.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/a28f1500-72ae-46e8-9449-e8f6fa016fb3.jpeg =1000x) | Tim Van Deelen has been on the faculty at the UW-Madison since 2004. Tim’s research specializes in the applied management of wildlife with an emphasis on large mammals in Wisconsin and is a frequent collaborator with the Wisconsin DNR and the Apostle Islands National Lakeshore. Prior positions include working as the research specialist for deer in the Wisconsin Department of Natural Resources and as a Research Scientist for the Illinois Natural History Survey where he had a joint appointment with the University of Illinois at Urbana-Champaign. |
----------


## Ben Zuckerberg ##
|  |  |
| ---- | ---- |
| ![ben-zuckerberg.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/a7866c90-b955-4e8f-a001-e7a340ea78ce.jpeg =1000x) | Benjamin Zuckerberg is an assistant professor in the Department of Forest and Wildlife Ecology at the University of Wisconsin-Madison. His research focuses on how climate change and habitat loss impacts wildlife populations. He is a strong advocate for the role of the public in collecting biological data. Using the data from these “citizen science” programs, Ben has studied shifts in bird ranges and migration in response to a changing climate. |
----------
----------

# Organizations #

|  |  |
| ---- | ---- |
| ![dnr_pr.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/994c9f91-5848-400c-bf62-8a07ae46e8a9.jpeg =1000x) |  Members of the Snapshot Wisconsin team are scientists at the Wisconsin Department of Natural Resources (WDNR). With funding from the Wildlife and Sport Fish Restoration Program, the WDNR purchases trail cameras and provides ongoing support for the project. Along with partners and the public, the WDNR manages fish, wildlife, forests, parks, air and water resources while promoting a healthy, sustainable environment and a full range of outdoor opportunities.|

|  |  |
| ---- | ---- |
| ![UW Logo.png](https://panoptes-uploads.zooniverse.org/production/project_attached_image/ecb0893a-4e65-43cf-8949-31425a15a8e7.png =1100x) |  Members of the Snapshot Wisconsin team are ecologists at the University of Wisconsin Madison in the Department of Forest and Wildlife Ecology. UW-Madison is a public, land-grant institution founded in 1848 whose mission is to provide a learning environment in which faculty, staff and students can discover, examine critically, preserve and transmit the knowledge, wisdom and values that will help insure the survival of this and future generations and improve the quality of life for all.|

|  |  |
| ---- | ---- |
| ![UWEX.png](https://panoptes-uploads.zooniverse.org/production/project_attached_image/c37c8295-0fbb-4bba-bd39-933e96617465.png =500x) |  The University of Wisconsin Extension provides ongoing support for the project. UW Extension’s purpose is to connect people with the University of Wisconsin and engage with them in transforming lives and communities.|

|  |  |
| ---- | ---- |
| ![NASA.gif](https://panoptes-uploads.zooniverse.org/production/project_attached_image/ac3a2829-1524-4502-9b10-f075bd76c8d8.gif =700x) |  NASA provided partial funding for the first year of the project thought the Ecological Forecasting for Conservation and Natural Resource Management Program. The NASA Applied Sciences Program supports projects that enable uses of Earth observations in organizations' policy, business, and management decisions.|

|  |  |
| ---- | ---- |
| ![Adler Planetarium.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/6d12742a-99d5-49e3-9e9a-c6a602e1588c.jpeg =800x) |  The Adler Planetarium was founded in 1930 by Chicago business leader Max Adler. A recognized leader in public learning, the Adler inspires young people -particularly women and minorities - to pursue careers in science, technology, engineering, and math. Scientists, historians and educators at the museum inspire the next generation of explorers.|

|  |  |  |
| ---- | ---- | ---- |
|![WEEB.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/d57b01d6-c02e-4e44-9b43-ec22f566eea2.jpeg =600x) |  The Wisconsin Environmental Education Board and the Wisconsin Society of Science Teachers provided grants allowing for outreach and enrollment of Wisconsin educators to host trail cameras with their students. | ![WSST.jpg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/39f074b9-3db4-41b4-87b9-691e1ba792ee.jpeg =400x) |

----------
----------

**Comment by trouille** [comment]
BTW, @eatyourgreens I've added you as a collaborator on that project so you can see. 

Note -- this isn't a high priority.

**Comment by eatyourgreens** [comment]
Thanks @trouille, I'd thought IE was simply showing the jpeg at the uploaded size, but the [uploaded jpeg](https://panoptes-uploads.zooniverse.org/production/project_attached_image/c631730d-1664-4873-87d4-3760848519bd.jpeg) is only 386px wide, so I'm not sure why IE is enlarging it.

**Comment by eatyourgreens** [comment]
Maybe IE is enlarging it up to 600px, as set in the markdown? In Chrome it's rendered at around 150px wide.

**Comment by srallen** [comment]
Closing as this can be solved by uploading scaled down images.
