### ISSUE TITLE
no panoptes projects load for me getting TypeError: Cannot read property 'error' of null on Chrome and Firefox

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3424]
I don't think this is my internet connection. None of my projects load they come up with:

 TypeError: Cannot read property 'error' of null 

If I go to the Zooniverse projects page nothing is listed it says 'Sorry no projects'.

Is anyone else seeing the same thing? I have no problem getting to Ouroboros projects

**Comment by mschwamb** [comment]
cc @srallen

**Comment by srallen** [comment]
We had a service interruption with Panoptes that the front end didn't handle well. Panoptes is back up now, however, we need to improve on error messaging instead of just printing whatever is in the console.
