### ISSUE TITLE
Added a collaborator who's username doesn't exist in the user database

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#343]
Minor but I thought it was worth mentioning for future updates. I was able to add an account to my project's list of collaborators that didn't exist. I added my test account which has an account on the ouroboros username database but doesn't have a counterpart on the panoptes user database. I confirmed by trying to log in with the same password and couldn't on the panoptes site, and despite that it was showing up on the team list.  

I was able to successfully delete the entry .

**Comment by edpaget** [comment]
@mschwamb we've imported the old users into the Panoptes database now.

**Comment by camallen** [comment]
I just tested and it needs a better error message on the front end. The api responds with an empty user array via the `user?display_name=x` call:

![invalid_collab](https://cloud.githubusercontent.com/assets/295329/7658492/a12cd5c0-fb32-11e4-8da5-0eb9c783fc01.jpg)

**Comment by mschwamb** [comment]
except I couldn't log in without that account, but could on an ouroboros  project site i could. Just checked again.

Also how do you handle mergers. Like my panoptes account I made to make the site is the same name as my ouroboros. Do they merge or do i/you have to do something special to link them? Sorry if that was a problem.

**Comment by camallen** [comment]
@mschwamb they will merge on the login name, the details from the old system will overwrite your panoptes staging account.

**Comment by chrissnyder** [comment]
I suspect this had to do with a lot of the user migrations that went on. Do reopen if the problem has persisted.
