### ISSUE TITLE
hide Classifications: X/N if you are using retirement rate for completion progress on stats page 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3431]
I had some volunteers asking on Talk  how we were still showing data on P4: Ridges because the classification reported numbers on the stats page.  Classifications: 383,388 / 143,490 but the progress was 70% - This is because the beta test subject set isn't linked. I'm using retirement count for the progress bars.  

Can this Classifications: X/N entry hidden if we're using retirement rate so it doesn't confuse volunteers?

**Comment by CKrawczyk** [comment]
Can do.  Would it be better if only the "/N" part was removed, and the current count is kept, or if it the entire line is removed?

**Comment by mschwamb** [comment]
Well The N is the total classifications needed for the subject sets linked to be completed (with constant threshold for retirement), so I think that would be confusing if you left the label 'Classifications:' So I'd say just hide that line if you're doing status by subject retirement

**Comment by CKrawczyk** [comment]
OK, just a quick comparison, what way do you like better.

Line completely gone:
![no_classifications_number](https://cloud.githubusercontent.com/assets/6557526/22888284/04f57c20-f1fd-11e6-8224-56835811d03d.png)

Or just the "total needed" part gone (i.e. keep the number of classifications on the stats page):
![no_total_number](https://cloud.githubusercontent.com/assets/6557526/22888326/359e6332-f1fd-11e6-9d54-c9bc57ffbf72.png)

**Comment by mschwamb** [comment]
The top one I like better, because classifications is confusing if you've got 10,000 already and are 0% because you unchecked a subject set and checked a new one. Classifications I don't know by looking at it whether you mean all classifications or two collected for that subject set.
