### ISSUE TITLE
No error when Collection save fails

### ISSUE THREAD

**Issue by zwolf** [zooniverse/Panoptes-Front-End#3433]
## Expected behavior
An error should occur when you save a subject to a new collection with an identical slug.

## Current behavior
NOTHING AT ALL

## Steps to replicate
From the classifier, save a subject to a new collection that has the exact same name as an existing collection, including user name, such that the slugs will be identical. The request will 400, but there will be no feedback to the user.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by mschwamb** [comment]
I think this is already listed in #1829

**Comment by mschwamb** [comment]
related to #1129
