### ISSUE TITLE
Add a links to pop up login and register window to the 'you must be logged in to register'

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#344]
More based my own experience, but I've always asked for this on builds I'm involved in when windows pop-up ask for you to login to get those features since I think most people will miss the login/register in the top right corner, and  those projects tend to have higher numbers of registered/logged-in users, but more anecdotal evidence. So I think it would be useful if you could click from the box below and get the register and login windows when you try and favorite non-logged in. 

![screen shot 2015-05-16 at 2 14 32 am](https://cloud.githubusercontent.com/assets/753325/7659028/a6c05bee-fb71-11e4-9a63-2c943a8aaae7.png)

**Comment by brian-c** [comment]
@aweiksnar You can probably reuse partials/sign-in-prompt here
