### ISSUE TITLE
hashtags in Talk

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#3442]
@denslowm commented on [Mon Jul 11 2016](https://github.com/zooniverse/notes-from-nature-landing/issues/79)

This is really a larger Talk issue (not limited to NFN), so Mark can move it to the appropriate place. 

It is largely summarized here:
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/438/61853?comment=128262&page=1

The main issue is that a user can't search for a hashtag (e.g., #myhashtag) even though the search box indicates that you can. It is also unclear what is being returned when a user searches with the "#" removed (myhashtag). Is it all boards within a project or just the board that the user in currently in when searching?

**Comment by eatyourgreens** [comment]
Searching for a hashtag takes you to a list of all tagged subjects
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/tags/unclear

Is the issue here that the template is different there from the one used for search results?
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/search?query=unclear

**Comment by eatyourgreens** [comment]
Those two templates are [`app/talk/search.cjsx`](/zooniverse/Panoptes-Front-End/blob/master/app/talk/search.cjsx) and [`app/talk/tags.cjsx`](/zooniverse/Panoptes-Front-End/blob/master/app/talk/tags.cjsx)

**Comment by eatyourgreens** [comment]
Related to #3173 

The short answer to the different behaviour here seems to be that text search returns a list of Talk comments (each of which may or may not have a linked subject), each linked to the corresponding discussion page, but hashtag search returns a list of tagged subjects, each linked to the corresponding subject page.

So the difference between the two views is that you're looking at Comment resources vs. Subject resources, I think.

**Comment by eatyourgreens** [comment]
Note that you can search for a # character in comment text if you encode it as %23 in the URL query string eg. https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/search?query=%23unclear
