### ISSUE TITLE
Changes made in the lab do not always auto-save

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#3459]
## Expected behavior
Changing the text for a task should auto-save when focus leaves the text box.

## Current behavior
Changes are not always saved even though the "green" shadow indicates no errors happen.

## Steps to replicate
1. Create a new task for a workflow (e.g. a single task)
2. change any of the text on the task
3. refresh the page

## Additional information
There is a warning in the console about the `GenericTaskEditor` that may be related:
`Warning: GenericTaskEditor is changing a controlled input of type checkbox to be uncontrolled.`

- **Operating system:**
macOS 10.12.2
- **Browser:**
Firefox 51.0
Chrome 55.0.2883.95

**Comment by eatyourgreens** [comment]
Related: [an explanation of controlled components in React](https://facebook.github.io/react/docs/forms.html#controlled-components).

**Comment by srallen** [comment]
Related to #2895

**Comment by CKrawczyk** [comment]
Just a quick note, the same thing happens when using the python client directly on the API.  This is looking like a back-end issues.

**Comment by camallen** [comment]
fancy opening a backend issue with request / response URL's, status, body, etc?

**Comment by CKrawczyk** [comment]
Here is the backend issues for this: https://github.com/zooniverse/Panoptes/issues/2212
