### ISSUE TITLE
Make default frame number configurable for multiple frame subjects

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#3464]
## Expected behavior
Allow the default frame for the subject flipbook to be configured as a workflow preference eg. default to the 3rd frame out of 5.

## Current behavior
Subjects with multiple frames default to the first frame.

## Additional information
Should this setting be ignored when the flipbook frames are viewed side-by-side?

**Comment by chrislintott** [comment]
Assigned to Roger.

**Comment by rogerhutchings** [comment]
Should this also have any implications for annotation? e.g. you can only mark on one frame?

**Comment by rogerhutchings** [comment]
Just spoken to @hrspiers - subjects may contain a varying number of images, so I'm going to make this a subject-level property
