### ISSUE TITLE
Move Pan-Zoom from frame level to subject-level

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#3465]
Pan-Zoom is [implemented at the frame level](/zooniverse/Panoptes-Front-End/blob/master/app/components/frame-viewer.jsx#L63-L88), providing individual SVG viewbox settings for each frame in a subject.

There have been a couple of requests for consistent magnification across all frames of a subject, which would entail moving `PanZoom` up the component tree so that it wraps the subject, giving a single set of controls which pass down a single viewbox and zoom settings to all child frames.

## Questions
How should drag-and-drop interaction for frames be implemented at a subject level?

How should this behave when flipbook images are viewed side-by-side?

Should we allow for subjects where each frame image has a different aspect ratio?

**Comment by trouille** [comment]
https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/classify have made a similar request. Good to see this issue posted.

**Comment by mrniaboc** [comment]
+1 for this! There is a researcher at NASA who needs it and only has 6 months funding left.

**Comment by hrspiers** [comment]
Also +1 for this from me - Etch a Cell would like to see this too!

**Comment by tingard** [comment]
+1 from me, would be useful for my project on in-browser galaxy modelling as the way the subject is dynamically updated resets the zoom level whenever the model re-renders.

**Comment by eatyourgreens** [comment]
I think #4036 fixes this for the flipbook subject viewer. Side-by-side images still have their own individual zoom controls, though.
