### ISSUE TITLE
Linking subjects from a collection to a subject set

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3470]
Gravity Spy would like an interface to be able to add subject links to a subject set from a collection. The collection would be an identified set of candidate subjects for a new glitch class. Ideas to do this:

- A search box that searches against collection display name in subject set editor and a event handler that gets that collection and takes array subject ids and links it to subject set.
- Add interface to be able to parse through CSV of exist subject ids. Currently subject set editor only creates new subjects. 
- Done by python client using script. 

## Additional information

- **Operating system:**
- **Browser:**

**Comment by trouille** [comment]
@srallen Talking w/ Zach and thinking through how the Python client now allows Scotty to generate a list of subject IDs for a collection - I think it would be a good idea to wait on this (linking subjects from a collection to a subject set) functionality. Let's see how the Gravity Spy team uses the Python client to download the subject IDs for a collection and then the Python client again to add those subjects to a subject set.

Do I understand correctly that they won't need to generate a new manifest file -- that through the Python client you can just provide a list of subject IDs (of existing subjects) and create a new subject set that way, pulling on existing information about those subjects from within Panoptes?
