### ISSUE TITLE
Add more visual indication that a project is still in review

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#3481]
( See attached image )

**Avatar**
  Border: 3px #00979D;

**Label**
  font-family : Open Sans;
  font-weight : 300;
  font-size : 8px;
  letter-spacing : 0.25em;
  color : #00979D;

![screen shot 2017-02-14 at 10 17 15 am](https://cloud.githubusercontent.com/assets/1392130/22937812/5a2423a2-f29f-11e6-8efa-b78ef0891980.png)

**Comment by beckyrother** [comment]
Sorry, meant to include as well that we should add a Teal border around the page, like the Admin Mode border but solid.
Thank you!

**Comment by mschwamb** [comment]
#3404 is related to this. Looks like the banner at the bottom that says this project is not a Zooniverse approved project disappears when the project is in review.

**Comment by wgranger** [comment]
What shade teal are you thinking for the border? Putting a border around everything (footer and all) might be a bit tricky, but putting it around all project-specific content is pretty easy.

**Comment by beckyrother** [comment]
@wgranger Sorry, just saw this! Please use #007482 

Thanks!
