### ISSUE TITLE
Collection subject view UI

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3483]
## Expected behavior
Adding to a collection needs better design and discoverability. Should there be an interface on the collection view page separate from the button in the subject viewer?

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Currently the only way to add a subject to a collection is to use the button available in the subject viewer and it opens up a modal dialog to search for a collection/create a collection and then add the subject to it.

**Comment by srallen** [comment]
@beckyrother Feel free to ping me with questions about this.

**Comment by beckyrother** [comment]
@srallen Thanks! I've put it on the list. I'm starting with the Classify design for project builder projects, so this is a good thing to make note of.

**Comment by beckyrother** [comment]
@srallen Has this been resolved? It looks like there are new controls: 
![screen shot 2017-03-02 at 12 39 06 pm](https://cloud.githubusercontent.com/assets/1392130/23521586/3f1675a8-ff45-11e6-8005-abadcf73d907.png)

If yes, my one request is that there's a confirmation popup after the Delete button, in case that's clicked by accident.

**Comment by srallen** [comment]
@beckyrother No, it hasn't. I'm not sure which new controls you're seeing? The UI in question is the dialog that pops up when you click the button with the list icon. We've had feedback in the past that it's not very discoverable from the Gravity Spy team and since working with collections is an important part of the project's workflow, it will need some rethinking. Perhaps we can chat more in person about it on Monday?

**Comment by srallen** [comment]
Adding a note: the collection view should also include a subject total easily viewable.

**Comment by srallen** [comment]
Wireframe is in the design-thoughts channel on slack.

**Comment by srallen** [comment]
In #3600 we're fixing the query to include collections that the logged in user is a viewer on. When clicking to view that collection, it's not clear to me why I can see it when I do not own it. Perhaps there can be somewhere on the collection view a listing of the current logged in user's roles if that user is not the owner?

**Comment by mcbouslog** [comment]
If we can get the `active` styling to stay on the "Collect" project subnav item, see Issue #3612, might we want to omit the "< [PROJECT NAME] COLLECTIONS" heading? I don't have an opinion one way or the other, just wondering.

Also, and maybe related to above, thoughts on moving the "Select Images" button below the Collection subnav? When looking at Collection Settings or Collaborators it's not relevant, but that's ok, alternatively it can stay as is and be disabled in those views.
