### ISSUE TITLE
Suggestions to improve drawing tools

### ISSUE THREAD

**Issue by hrspiers** [zooniverse/Panoptes-Front-End#3491]
Feedback suggestions from the [beta test ](https://www.zooniverse.org/projects/h-spiers/drawing-tools-test) of Roger's drawing tools:

1. Improve speed
2. Provide eraser function
3. Feature to enable user to select multiple separate segments, then click a box to connect them into one long segment (specific to the Freehand Line Tool)
4. When the cursor is near a line, don't automatically switch from drawing to selection mode, so drawing can continue (specific to Freehand Line Tool

**Comment by rogerhutchings** [comment]
Another idea: for touch devices, put a larger circle around the drawing point so user's finger doesn't totally obscure the work
