### ISSUE TITLE
Refactor media fetch for tutorials, field guide, mini-course, etc

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3492]
## Expected behavior
Linked media for any tutorials or field guides should be fetched for once rather than each time they are opened.
 
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Field guide, tutorial, and mini-course fetches for media each time they're opened: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/tutorial.cjsx#L45-L55
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/mini-course.cjsx#L29-L39
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/potential-field-guide.cjsx#L33-L37

**Comment by simensta** [comment]
I am working on the field guide and @mcbouslog is working on the tutorial and the mini-course.

**Comment by mcbouslog** [comment]
@srallen and @simensta - I think we can close this issue?

**Comment by srallen** [comment]
Yep
