### ISSUE TITLE
Determine if subject is a favorite in subject queue request not per subject get

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3494]
## Expected behavior
For API optimization, request favorite status for each subject in the subject queue request and set local app state for subject queue. This would be similar to the already seen/seen this session functionality.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Currently the favorite collection and the check if a subject is a favorite is done in the `componentWillMount` lifecycle method of the favorite button component. This means the collection get request is done at least once per subject.

**Comment by camallen** [comment]
@srallen i was thinking about adding a `favourite: true` to the response body from the `/api/subjects?queue=true?workflow_id=X` route. This would be an optional value that the api could turn off if needed (it adds a cost to response times, etc) so if it's missing the front end could revert to normal lookup behaviour. How does that sound?

**Comment by srallen** [comment]
@camallen that works for me.

**Comment by marten** [comment]
How about if it's missing, that'll be because the backend deems it too much load, and the frontend just ignores it, rather than reverting to old behaviour?

That way PFE doesn't need to keep two code paths working and tested, and we don't end up being surprised by additional load elsewhere when we toggle a feature off in the backend.

**Comment by zwolf** [comment]
Closed by https://github.com/zooniverse/Panoptes/pull/2210

**Comment by camallen** [comment]
@zwolf does PFE now check the `subjects?queued=true` response to see if the favourite is set?

**Comment by eatyourgreens** [comment]
@camallen on staging for #3573 I'm seeing the `favorite` flag in the response for the classifier, but it isn't present on subjects in Talk or in collections, which also use the favourite button.
