### ISSUE TITLE
Infinite loop to also apply to Talk view of subject, not just classify view

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3499]
## Expected behavior

In a project like BackyardWorlds.org (zooniverse.org/lab/2416) that has set 'Flipbook play iterations' to infinite, the question is whether this can apply both to the classify page as well as when you see the subject in the Talk pages. Right now, it only is an infinite loop in the classify page. 

This is not a high priority need, but if it's an easy/quick fix that makes sense, that would be great. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Currently the infinite loop is not happening within the Talk pages for projects that specify it for the classify page. 

## Steps to replicate

See for example the subject in https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/666/181701. When you click play, it only loops for ~20 seconds. 

## Additional information
Note: I haven't checked this in Firefox, Safari, etc. Only in Chrome on a mac. 

- **Operating system:**
Mac 

- **Browser:**
Chrome

**Comment by eatyourgreens** [comment]
Infinite loop is a workflow preference, but Talk doesn't have workflows so it won't be set on Talk discussions.
