### ISSUE TITLE
Project avatars appear slightly blurred in chrome. 

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3501]
## Expected behavior

Non-blurred avatar images in Chrome. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

For Project Builder built projects, it appears that the avatar (the image in the upper-left that is uploaded as an 'avatar' in the Project Details tab of the Project Builder) is blurred slightly when viewing in Chrome. This does not appear to be the case in Firefox. 

See for example: https://www.zooniverse.org/projects/sweenkl/steller-watch in Chrome and then look at the same in Firefox. I haven't checked in safari or internet explorer. 

If you Zoom in when in Chrome, the avatar image will momentarily un-blur. 

I've also attached the avatar image that is uploaded into the Steller Watch project, in case that's useful.

![avatar_scaled](https://cloud.githubusercontent.com/assets/4975655/23079778/fe888fde-f513-11e6-9871-0df87b56c613.jpg)

- **Operating system:**
mac

- **Browser:**
chrome vs firefox

**Comment by beckyrother** [comment]
Hm yes, it looks better on Safari as well:

<img width="406" alt="steller_watch_ _zooniverse_and_steller_watch_ _zooniverse_and_steller_watch_ _zooniverse" src="https://cloud.githubusercontent.com/assets/1392130/23082557/78fa4810-f51f-11e6-8b0a-a63043a07b60.png">

This may be a question for @wgranger?

**Comment by eatyourgreens** [comment]
Looks like an artifact of the browser resizing a 200px jpeg down to 48px. It might be better to generate a 48px avatar on our image server, using the `Thumbnail` component in PFE.

**Comment by eatyourgreens** [comment]
Here's a thumbnail generated by our image server https://thumbnails.zooniverse.org/48x48/panoptes-uploads.zooniverse.org/production/project_avatar/bd08691b-ac50-4d07-a8f5-e8aa7f83641b.jpeg

**Comment by wgranger** [comment]
Hmm. Looks kinda grainy. I imagine the `Thumbnail` component would give that if you set the dimensions to 48x48?

**Comment by wgranger** [comment]
Oh wait a minute, it might look alright. Might get a PR up here in a sec using `Thumbnail`.

**Comment by wgranger** [comment]
Oops. Missed @eatyourgreens already made a PR.
