### ISSUE TITLE
Expert role not showing up correctly on science-case page

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#351]
Instead of showing "Expert" by various users on the science-case page I'm seeing "missing translation: en.projectroles.expert" instead.

![screen shot 2015-05-17 at 23 52 42](https://cloud.githubusercontent.com/assets/2357126/7672611/29dec5cc-fcf0-11e4-8004-43f3b6612cf4.jpg)

All the actual errors I see in the console are just about the fact that I don't have a project avatar or background, so that doesn't seem that helpful, sorry.

**Comment by vrooje** [comment]
@brian-c worth adding this to the first-release milestone? Or just after? Hopefully it's a small thing but it's highly visible.

**Comment by brian-c** [comment]
Yep, missed this, sorry!
