### ISSUE TITLE
completion bar doesn't update very quickly when you swap subject sets 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3518]
I've added subjects to P4: Ridges and several hours later the project still says 100% complete. Is there a way that changing subject sets could trigger a recalculation of the progress bar?

<img width="1125" alt="screen shot 2017-02-23 at 10 09 03 pm" src="https://cloud.githubusercontent.com/assets/753325/23295435/ba71526c-fa14-11e6-837b-267fea150e53.png">

**Comment by mschwamb** [comment]
@camallen might this be a backend issue?  nearly 12 hours later and my project still has 100% completed even thought that's not true and the subject sets have been swapped.

**Comment by camallen** [comment]
This is an API issue, the front end just displays the numbers from the API.

**Comment by mschwamb** [comment]
Thanks. I'll move to the backend
