### ISSUE TITLE
Some images in collections aren't displaying 

### ISSUE THREAD

**Issue by hrspiers** [zooniverse/Panoptes-Front-End#3519]
Some of the images in Collections aren't displaying properly, e.g.

![screen shot 2017-02-24 at 12 31 39](https://cloud.githubusercontent.com/assets/22645431/23303657/4900d552-fa8d-11e6-9f7f-ae33da5f2259.png)

**Comment by camallen** [comment]
URL for testing, network traffic looks ok but the UI con't show the collection subjects, no console output either...
https://www.zooniverse.org/collections/rednoserules/

**Comment by eatyourgreens** [comment]
See #3503 We turned these off the other day to reduce API traffic under load.

**Comment by camallen** [comment]
It's not the preview cards, when i click on that collection with 9 subjects i expect the ui to show me the subjects.

**Comment by eatyourgreens** [comment]
@camallen the collection name is '!!!' so the slug is being passed back as just `rednoserules/` with the punctuation removed.
```
created_at:"2016-08-26T02:09:07.427Z"
display_name:"!!!"
favorite:false
href:"/collections/16345"
id:"16345"
name:null
private:false
slug:"rednoserules/"
updated_at:"2016-08-26T02:09:07.427Z"
```

**Comment by camallen** [comment]
well - that is not a good. Looks like we'll have to do some display_name validations on collections and update the slugs. 

@eatyourgreens anyway we can fallback to just loading the collection by it's id as we have that data from the response?

**Comment by eatyourgreens** [comment]
Not easily, at least from a quick look at https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/router.cjsx#L126-L136

**Comment by eatyourgreens** [comment]
Here you go https://workaround-collection-slugs.pfe-preview.zooniverse.org/collections/rednoserules/16345?env=production
