### ISSUE TITLE
science-case page: what if it's not a science project?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#352]
Even if I leave the science page content-free when designing a project, it still appears as a tab (which I think is by design as that page is where the project team and roles show up). 

But not everyone will find a page called "Science" relevant (e.g. humanitarian projects), and I can't change the name of the tab.

I suspect this isn't a first-release issue but I'm just throwing it out there that we should broaden the label of this page, or allow users to change the tab text.

**Comment by mkosmala** [comment]
Related: the label "scientist" for project team members...

**Comment by brian-c** [comment]
Linking this to #354.

**Comment by DarrenMcRoy** [comment]
Can we rename the page to "Research" (seems to be the direction we are heading) and generally rename "Scientists" as "Project Team?" (Could also be "Researcher.")

**Comment by edpaget** [comment]
I'm fine with both those changes. Should they happen in the backend or just with the text displayed in the front end @brian-c ?

**Comment by brian-c** [comment]
I think just changing it on the front end will be fine for right now.

**Comment by VVH** [comment]
Hi all and @brian-c in particular. If changing the label is a quick thing to do, I would really appreciate it if the change could be made this week. I am teaching a digital humanities course with the project builder starting 20 July.

**Comment by edpaget** [comment]
The new Project Page resources these pull from now have a field for a custom title, so we could just change the ProjectBuilder page to start creating the page resource with the "Research" title and use that field in the UI.
