### ISSUE TITLE
Mini Course dialogs look like modal popups but aren't modal

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#3529]
## Expected behavior
Modal popups should trap keyboard focus and not allow other elements on the page to be focussed. Tab should cycle through controls within the modal element. Esc should close the popup and return focus to its original position when the modal opened.

## Current behavior
Focus remains where it was when the popup opens. Underlying links, buttons and inputs can be reached with the tab key.

The popup does not capture focus on opening. When it has focus, esc doesn't close it.

This behaviour is built in to the PFE Dialog component, so maybe mini course popups render using a different element?

## Steps to replicate
Try to navigate a mini course popup using the tab key and esc after it automatically opens.

## Additional information

- **Operating system:**
- **Browser:**
N/A

**Comment by wgranger** [comment]
Closing the modal with the escape key has come up before, and I can't recall the reason we aren't allowing this. However, tutorials and mini-courses are opened with the `modal-form` through `Dialog.alert`. Both are passed the prop `required: true`. If that is changed the `false`, the modals will close with the escape key. 

I'm not sure on the change of focus.

**Comment by camallen** [comment]
Some project owners are against it, mostly to ensure volunteers don't accidentally close it and can't get it back. I can see both points but really don't like that i can't press esc key, etc.

**Comment by eatyourgreens** [comment]
#3533 adds a component and some small changes which ensure proper modal behaviour for help popups, drawing subtasks, sign-in/registration and (hopefully) anything that uses the PFE `Dialog` component.

**Comment by srallen** [comment]
Re why the escape button is disabled for tutorials/mini-course: https://github.com/zooniverse/Panoptes-Front-End/issues/1935

It was a specific request, though, it does change expected behavior and remove accessibility.

**Comment by eatyourgreens** [comment]
I think that's compatible with #3533, because I made the default `onEscape` handler a null function.
