### ISSUE TITLE
"Multiple Choice" should be renamed

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#353]
"Multiple choice" to me means "there are multiple options for you to choose from", which is true even when the user is forced to pick one. I don't think I'm the only one who will be confused by this.

May I suggest changing the label for this open to something like "Multiple answers allowed"?

**Comment by mschwamb** [comment]
If it helps - As someone who didn't get a walk through from the development team on how to use the front end, I found that wording confusing.

**Comment by aliburchard** [comment]
agreed.

**Comment by twhyntie** [comment]
:+1: I wondered if this was a British phrasing thing :-)

"Multiple answers allowed" works for me.

**Comment by chrissnyder** [comment]
Looks to be addressed at some point. Closing.
