### ISSUE TITLE
Subject set upload error (TypeError: e.body is null)

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#3537]
## Expected behavior
No error notice if system indicates that subjects are ready to be uploaded.

## Current behavior
On occasion, I get the following error: TypeError: e.body is null

It is not clear why I get the error sometimes and other times not. Even when this error shows, it seems that subject do upload correctly. 

## Steps to replicate
I can supply example subjects. 
The uploaded subjects are here: https://www.zooniverse.org/lab/1558/subject-set/8540

## Additional information
What does this error mean?

- **Operating system:**
OS X 10.11.6
- **Browser:**
Firefox 51.0.1 (64-bit)

![panopteserror](https://cloud.githubusercontent.com/assets/2152565/23538148/50c4c496-ff8e-11e6-8ed2-48d2538e2121.jpg)

**Comment by camallen** [comment]
Pretty sure this is related to some api errors we saw last night with S3 storage layer. Seems we're 500'ing on the api and the UI is just spurting these back. Not sure the UI retires on this event but something to check into.
