### ISSUE TITLE
The term "citizen science" on Zooniverse

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#354]
I think we need to have a discussion about the degree, if any, to which we wish to continue to refer to ourselves as a "citizen science" portal as we're developing the new Zooniverse home page.

I understand that we are expanding into the humanities and beyond, and we don't want to sound exclusionary, but there are complications with jettisoning "citizen science" as a term altogether. There's that our administering body is called the Citizen Science Alliance, for one. If you Google "Zooniverse," the second result is Wikipedia calling us a "citizen science project" as the very title of the page (and the third is the CSA). And there's the fact that we don't really have an alternative term ("citizen research?"); anything that we try to replace it with will involve tracking fresh snow. That or we sort of have to "write around" the term, which is doable, but clunky.

Plus, "citizen science" as a brand has a lot of heft right now, doesn't it? It seems to be a major growth area with ever-increasing visibility. Removing ourselves completely from that term strikes me as potentially divorcing ourselves from the overall rise of citizen science that seems to be going on right now, and sacrificing a bit of the identity that we've built so far.

So, personally, I would be in favor of trying to keep the term around in some way. Maybe something like "citizen science and beyond;" I don't know. It's a thorny problem. "Citizen science and research," even, although that's a bit cumbersome.

However, I'm certainly willing to defer on this, especially if there are better ideas. Have others thought about this more? What's our current line on this? @whyte @mrniaboc @chrislintott @chrissnyder @vrooje 

(EDIT: This also affects if we refer to "scientists," "scientists and other researchers," or just "researchers," or some other term, when talking about project teams. I'm less attached to "scientists" as a term than I am to "citizen science," personally, although I do believe "you get to be a scientist!" has more appeal than "you get to be a researcher!", if only because of the slight romanticized concept of the "scientist" in the popular imagination.)

**Comment by whyte** [comment]
My concern is that very few people think of themselves as 'citizen scientists'. I think it's a terms that means something to us, to funding agencies and in academic literature, but very little to the actual volunteers. 

Also, it's getting to be just plain inaccurate. I'd personally prefer to see a couple of paragraphs somewhere that explains how we started off doing astronomy, then science and evolved to THIS, whatever THIS is.

**Comment by aweiksnar** [comment]
Perhaps we can have a secondary-page on the site where this topic is specifically addressed, in addition to how the term ends up being laced in the copy

**Comment by chrislintott** [comment]
I'm with Laura - I think the point is to avoid it on the more public facing pages. I think by the time we're talking about proposing projects and so on it's fine - but we don't want visitors to make the mental leap to thinking of themselves as doing 'citizen science' to choose to participate.

**Comment by whyte** [comment]
I personally like the idea of using the word 'volunteering' more. 62.6 million American's spent 7.7 billion hours volunteering last year - it's a concept people are comfortable with and makes them feel warm and fuzzy. We offer people the chance to volunteer from the comfort of their sofa in their pj's with a nice cup of tea. Also - we know that most participants like to 'help science', so I think it's just an extension of that.

I was also a big fan of the terms 'salaried' and 'non-salaried' scientists - but I think that is a bit too in the weeds for most casual visitors.

**Comment by vrooje** [comment]
I like the emphasis on volunteering, and people being able to immediately jump in to help a variety of important science, research and societal questions. <-- though I don't like that phrasing too much either.

I agree the History of the Zooniverse page is a good place to explain the evolution of this and why the term citizen science is used on the site sometimes. I'm wondering if the term "citizen science" is tied to us helping make some people more comfortable with science being a part of their daily lives, and whether dropping it nearly everywhere and using a more general term could actually harm that.

**Comment by vrooje** [comment]
Oh, forgot: explicitly adding @VVH @aliburchard too.

**Comment by mkosmala** [comment]
I'll just add that the term 'citizen' is a loaded one in the U.S. (immigration and non-documented statuses, etc.) and much debated within "citizen science" circles. I like the term "participatory" better, but it's a mouthful and kinda technical-sounding.

**Comment by DarrenMcRoy** [comment]
I've removed all references to "citizen science" from all current Zooniverse Home content.

**Comment by srallen** [comment]
Pinging @heathv about this since some of the home page designs include 'citizen science' at the moment.

**Comment by DarrenMcRoy** [comment]
We're using "people-powered research" as an acceptable substitute for the moment, for when a term is absolutely required.

**Comment by whyte** [comment]
For what it's worth I have always f**king loved the term people-powered research.

**Comment by DarrenMcRoy** [comment]
I think we have a good idea on our direction for this now!
