### ISSUE TITLE
Login blocked

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/Panoptes-Front-End#355]
As I'm using a password manager, I'm pretty sure that my password is correct. But I currently cannot login and the password reset still links to the zooniverse login management, which as I understand is not the same as for Panoptes.
Please advise if I should temporarily create a new account of which I have to be made owner again or if there's a hidden link to the new password reset management?
User name: michaelaye

**Comment by chrissnyder** [comment]
Pretty sure I have the same issue, whatever it is.

Username: chrissnyder

**Comment by edpaget** [comment]
@michaelaye we're looking into what caused this now. We just resynced the users info from the old Database. For the moment you can go here https://panoptes-staging.zooniverse.org/users/password/new to reset your password.

**Comment by michaelaye** [comment]
Worked, thanks.
