### ISSUE TITLE
Freehand drawing tools generate too much data

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3551]
The tools should:

- Debounce updates to the annotation
- Ensure there are no consecutive dupe coords

Fair play to @marten for accurately pointing the finger

**Comment by rogerhutchings** [comment]
We're still getting a lot of data. There are still some options:

- Round down from `n` decimal places
- Smooth out, e.g. by taking every other / 3rd / whatever classification
- Save each point as `[x,y]` instead of a hash, and store schema in classification metadata
- Use compression (thanks @astopy)

cc @camallen

**Comment by CKrawczyk** [comment]
For smoothing the data care should be taken that the Poly-freehand tools don't loose information when used in polygon mode (e.g. make sure the point removed is less than some "delta" from each point on either side).
