### ISSUE TITLE
metadata URL bug if there are '....' within the URL

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3555]
## Expected behavior

URLs within metadata for subjects should link properly. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Sometimes, but not always, if there are '....' within a URL in the metadata for the subject, the full URL isn't linked, so it becomes a broken link. A volunteer can instead copy/paste the whole line and get to the URL, but if they don't realize that and just click on the link, they think it's broken. 

This is a lower priority item, but if there's a quick fix, that'd be great to implement. 

Screenshots from https://www.zooniverse.org/projects/zooniverse/astronomy-rewind/classify for subjects with 'broken' URLs and a working URL example. 

I haven't looked at enough images to see if this trend holds up, but it seems that if there are 4 '....', then it breaks, but only '...' works? That might just be small number stats. 

![screen shot 2017-03-07 at 11 53 52 am](https://cloud.githubusercontent.com/assets/4975655/23670331/f7a7c230-032c-11e7-932f-0dec59484ecc.png)
![screen shot 2017-03-07 at 11 53 37 am](https://cloud.githubusercontent.com/assets/4975655/23670330/f7a7723a-032c-11e7-8e58-92834f6fc370.png)
![screen shot 2017-03-07 at 11 53 20 am](https://cloud.githubusercontent.com/assets/4975655/23670329/f7a754f8-032c-11e7-9cb5-58c93cff4e43.png)

## Additional information

- **Operating system:**
mac
- **Browser:**
chrome (haven't looked at other browsers)

**Comment by eatyourgreens** [comment]
URL matching in the metadata fields is handled by [linkify-it](/markdown-it/linkify-it/blob/master/lib/re.js#L59). From a quick look through that code,[ it supports `..` or `...`](/markdown-it/linkify-it/blob/master/lib/re.js#L59) (for commit ranges in github URLs) but not `....`.

**Comment by eatyourgreens** [comment]
Closing this as it's a bug in an external module.

**Comment by augustfly** [comment]
@chrislintott you had asked me to tag you on this closed issue with an upstream module per the astronomy rewind discussions.

**Comment by eatyourgreens** [comment]
There’s an open issue for this: markdown-it/linkify-it#66
