### ISSUE TITLE
Credits section is 40% of project login screen

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/Panoptes-Front-End#356]
See here:
https://www.dropbox.com/s/ggxgr1tkd7dhqot/Screenshot%202015-05-18%2017.27.09.png?dl=0

I don't think this looks that good, can the credits part be a lesser fraction of the project homepage?

OS: 10.10.3
Browser: Safari 8.0.5

**Comment by chrissnyder** [comment]
Design issue with the project landing page that is duplicative of others. Closing to consolidate.
