### ISSUE TITLE
Not relevant text shows on mouse over of the 'Visualize Workflow' Button

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3570]
A mouse over of the 'Visualize this workflow' has text appears that defines what a workflow is , which seems odd since none of the other buttons have that help text appear over hover over. 

It looks to be the first line of the help text in the workflow page, but it's odd to have it appear on the 'Visualize Workflow' button

**Comment by mschwamb** [comment]
![button_over](https://cloud.githubusercontent.com/assets/753325/23740107/24e3fe66-0446-11e7-8641-2d6377aa1911.gif)

Maybe @CKrawczyk had other text to go there?

**Comment by CKrawczyk** [comment]
I will take a look at this.

**Comment by CKrawczyk** [comment]
#3919 has removed the visualizer component (it will get a re-design and re-write at a later date), so this issues can be closed.
