### ISSUE TITLE
Subjects from a differnt project could show up in the "talk preview" on the landing page

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#3572]
## Expected behavior
Only subjects from a given project should show up in the "talk preview" on the landing page for a project.

## Current behavior
The code currently only looks for subject tags, so if a user cross-posts a subject from another project it can show up in this list.
![screen shot 2017-03-09 at 11 32 36 am](https://cloud.githubusercontent.com/assets/6557526/23748589/25b7679e-04bc-11e7-8af0-e43ea5618c75.png)

## Steps to replicate
Was seen on Backyard Worlds today: https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9
The center subject in the screenshot above is from Galaxy Zoo: 3D.

## Additional information
I am not really sure if this is a "feature" or a "bug"

**Comment by simoneduca** [comment]
Doesn't seem like a feature to me. Especially given the blurb on the right referring to them as belonging to the project. At least that's what I think it's doing.

**Comment by eatyourgreens** [comment]
Here's the comment that generated that image: https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/694/207411?comment=352825&page=1

You can mention any subject on any project, which I think is a feature.

**Comment by eatyourgreens** [comment]
@CKrawczyk mentioned on Slack that a possible fix would be to restrict the query that gets those three images, so that it only pulls from the Notes board for that project.
