### ISSUE TITLE
Subject images displaying out of order in flipbook in classify interface

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#3577]
## Expected behavior

When I upload a subject with multiple images using a manifest, I expect the order of images in the flipbook will be determined by the order of columns in the manifest, e.g.

[vrooje-test-subject-manifest.txt](https://github.com/zooniverse/Panoptes-Front-End/files/832141/vrooje-test-subject-manifest.txt)

(which I've edited from .csv to .txt so it will upload here) should load the subjects in order from 1-49 as in the file. 

## Current behavior

If I view [this subject](https://www.zooniverse.org/lab/4044/subject-set/8562) in the project builder subjects page, the order is fine. However, when I view it in [the classification interface](https://www.zooniverse.org/projects/zookeeper/hla-cleaner/classify?reload=0&workflow=3596), the subjects display out of order. (Note: there's also a [second subject set](https://www.zooniverse.org/lab/4044/subject-set/8537) in that workflow which also has 1 subject with 49 images that's showing the same behavior.)

## Steps to replicate

The [subject set](https://www.zooniverse.org/lab/4044/subject-set/8562) with the manifest attached is my replication of this, but it would be pretty easy to replicate on a new project.

## Additional information

This was discovered at a hack day when the project builder tried a 49-image subject. I'm not sure if it's replicable for smaller subjects?

- **Operating system:** OS X
- **Browser:** I'm using Chrome, not sure what the original project builder is using, but we've both replicated it.

**Comment by trouille** [comment]
Related to https://github.com/zooniverse/Panoptes-Front-End/issues/1177

**Comment by trouille** [comment]
The plan is to do the next PFE improvements week the week of April 17th. Flagged w/ lintott-trouille and note here to bring it up to the foreground.

**Comment by srallen** [comment]
This might possibly be a back end issue during subject upload and creation, FYI.

**Comment by eatyourgreens** [comment]
One way to test that might be to create subjects from the same manifest using the python client.

**Comment by srallen** [comment]
That's a good idea.

**Comment by eatyourgreens** [comment]
Looks like [`_findFilesInMetadata`](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/subject-set.cjsx#L318-L325) is the method that generates `subject.locations` from the CSV, so that would be the first place to look in the front-end.

**Comment by eatyourgreens** [comment]
`subject.locations` is an ordered array and `subject.metadata` is an unordered hash, so I think this is a different bug from #1177

**Comment by eatyourgreens** [comment]
I've just tried dragging the test manifest into the project builder. PFE generates the subject locations array in the correct order, so this isn't a problem with reading the CSV.

![A screenshot of the generated manifest, with the locations array listing the subject images in the correct order.](https://cloud.githubusercontent.com/assets/59547/24662684/b6be2d9a-194d-11e7-918f-372b68f91a5e.png)

**Comment by eatyourgreens** [comment]
Verified that this happens in the classifier, but not in the project builder, even though both render the subject using the `SubjectViewer` component.

If the workflow is set to show subject frames side-by-side, then they are still rendered out of order in the classifier.

**Comment by eatyourgreens** [comment]
Side note: rendering 49 subject images on a single web page will also pretty much lock up Chrome for a while too.

**Comment by eatyourgreens** [comment]
Here's the test subject in Talk: https://www.zooniverse.org/projects/zookeeper/hla-cleaner/talk/subjects/6532831

Displays fine there too, so this is clearly a classifier bug.

**Comment by eatyourgreens** [comment]
Ok, I've traced this down to the `subject.locations` array being returned in a different order from `/api/subjects/queued` (used by the classifier) than it is from `/api/subjects` (used by Talk.)

Pinging @marten as this is looking like a Panoptes issue.

**Comment by eatyourgreens** [comment]
Test URLs for this bug. Examine the subject in the network panel in each case. You may need to reload the classifier a few times to get the test subject.
https://flipbook-3577.pfe-preview.zooniverse.org/projects/zookeeper/hla-cleaner/talk/subjects/6532831?env=production
https://flipbook-3577.pfe-preview.zooniverse.org/projects/zookeeper/hla-cleaner/classify?env=production

**Comment by camallen** [comment]
thanks for doing the leg work on this @eatyourgreens - I've identified the bug and will respond on the panoptes issue.

**Comment by eatyourgreens** [comment]
Closing this and moving to zooniverse/Panoptes#2293
