### ISSUE TITLE
Maximum call stack size exceeded when submitting drwing classifictions after using the "hide previous marks" button

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#3581]
## Expected behavior
Submitting a classification after using the "hide previous marks"  ~for the freehand tool~ will work.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
When submitting a ~freehand~ drawing classification after the "hide previous marks" toggle is used causes a `Maximum call stack size exceeded` error in the console and the classification interface disappears from the screen.

## Steps to replicate
Use the ~freehand~ drawing tool ~to make a line~ and toggle the "hide previous marks" check box and try to submit the classification.  This is currently preventing some classifications for a live project: https://www.zooniverse.org/projects/klmasters/galaxy-zoo-3d/classify?workflow=3515

## Additional information
~This only happens when the click-and-draw part of the tool is used, if it is used as a poly tool the classification submits without issue~

~@rogerhutchings could this be caused by https://github.com/zooniverse/Panoptes-Front-End/pull/3562?~

- **Operating system:**
OSX
- **Browser:**
Tested in Firefox and Chrome

**Comment by eatyourgreens** [comment]
@CKrawczyk I'm unable to reproduce this in Chrome. Should I see an error once I draw a line of any length?

**Comment by CKrawczyk** [comment]
As long as there is any length "freehand" section to the final shape it gives me an error.

**Comment by eatyourgreens** [comment]
I've just submitted a classification with 2 freehand shapes of around 150 points each.

**Comment by CKrawczyk** [comment]
It only happens when the "hide previous marks" feature is used during the classification, odd.

**Comment by CKrawczyk** [comment]
This happens with all drawing tools when "hide previous marks" is used.  I updated the title of the issues to reflect this.

**Comment by CKrawczyk** [comment]
For reference here is the console for a classification made without the "hide marks" being checked followed by one that did.  It looks like the `created_at`, `href`, and `id` keys (added in this [callback](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/task-nav.jsx#L51-L72)) are missing from the failed classification, and the `_hideMarksBefore` key created by the "hide marks" toggle is included. Note the code that logs the classification is [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L268-L301).

![screen shot 2017-03-10 at 1 49 50 pm](https://cloud.githubusercontent.com/assets/6557526/23797595/8f5a9f86-0598-11e7-8d15-08aaf3c31e1a.png)

**Comment by eatyourgreens** [comment]
I've just reproduced this locally. There's an infinitely nested classification resource stored as `classification.0`.
