### ISSUE TITLE
Subjects maybe repeating for non-owner if logged in, but not for owner

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#359]
Hi,

This seems to be happening on Planet Four:Terrains.  @michaelaye can repeat through images he's classified but I can't. It also appearrd thst way for another P4 team member. Only difference is that I'm owner.

**Comment by michaelaye** [comment]
I have confirmed this for sure with a small 10 tiles subject set: I never stop getting images served, even so after 10 it should be finished.
But I just noticed something that might help to solve this bug (and it is a pretty serious bug, b/c like this we basically have the Citizens seeing everything endlessly): After the 10 images have been shown, no loading seems to appear, the tile is shown instantaneously after clicking the "Next" button.

**Comment by camallen** [comment]
This is intended behaviour @michaelaye, see #312 and https://github.com/zooniverse/Panoptes/issues/830#issuecomment-101290476. You will be warned in the front end that you've already seen this subject once #312 is finished.

**Comment by michaelaye** [comment]
but i hope that classifications are not recorded then? I don't want the Citizens to be able to work more than once on an item.

**Comment by edpaget** [comment]
@michaelaye classifications are recorded, but don't count towards subject retirement.

**Comment by camallen** [comment]
@edpaget duplicate anonymous classifications currently do count towards retirement. I raised this issue [here](https://github.com/zooniverse/Panoptes/pull/843) but it morphed into a discussion towards aggregation using IP's as a proxy for the same user. 

I think we can easily add a metadata field on the classification indicating it's already been classified by this volunteer for a previous session and not count towards retirement.

**Comment by mschwamb** [comment]
@camallen that would be helpful from my perspective as someone that is likely going to do some reduction of the raw data on my own, so having a metadata flag already say its a duplicate classification (because volunteer saw the same subject) would be helpful so I don't have to go through and unique and filter the database. We currently do that for P4.
