### ISSUE TITLE
Set default subject for collection

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3593]
## Expected behavior
A user should be able to set a default for their collection which is the subject that is then shown on the collections page.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Collections page just shows the first subject in the linked subjects array.

**Comment by beckyrother** [comment]
- [ ] Please add a button under the subject viewer that enables the user to set the image as the Cover Image:
<img width="968" alt="example" src="https://cloud.githubusercontent.com/assets/1392130/24674552/733ef722-1941-11e7-9397-32dacfb4b4e0.png">

- [ ] Add a button to the right of the new Select Images button, in the same style, that says "Discuss on Talk" This should share the collection on talk in the same default board as single subjects and have the same actions as sharing a single subject. 

- [ ] In Talk, the title of the collection should be preceded by "Collection:", and should also add a default "#collection" tag to the note (if possible). The cover image should appear in the same position as single subject images, with a "stack" of images behind it to imply that there are multiple images. I can provide an image for this if needed.
![collection-talk](https://cloud.githubusercontent.com/assets/1392130/24675052/5c376b70-1943-11e7-846c-a5bb7f01252b.jpg)

**Comment by srallen** [comment]
The collection talk feature will have to come at a later date since that will necessitate work on the Talk API. I'll open a new issue just for that part.
