### ISSUE TITLE
GZ3D: two tutorials load on first visit

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#3598]
## Expected behavior
Only the tutorial for the chosen workflow should load

## Current behavior
On starting a workflow for the first time, the default workflow tutorial loads behind the chosen workflow tutorial.

## Steps to replicate
Visit https://www.zooniverse.org/projects/klmasters/galaxy-zoo-3d while not logged in and choose the Bars or Spiral Arms workflow.

## Additional information
EDIT: Can still be reproduced in #3556

**Comment by eatyourgreens** [comment]
@srallen could the fix for this be as simple as indenting these lines into the `if` block? https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L91-L98

**Comment by srallen** [comment]
@eatyourgreens that appears like it might fix it. The tutorial or mini-course shouldn't attempt to load if we do not yet have the workflow. I'll take a look at #3599 to confirm.

**Comment by eatyourgreens** [comment]
@srallen moving it down the component hierarchy fixed, although I'm not 100% sure why. In `classify.cjsx`, `componentDidMount` runs with the default workflow, then `componentWillReceiveProps` runs with the selected workflow. I'm not sure if that's also buggy behaviour ie. should the workflow be null or undefined until one has been selected?

**Comment by srallen** [comment]
It may be because of the complicated mess of logic that is currently written to try to keep the workflow selection and fetch firing while it's still waiting on the user, the user prefs, etc: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/index.cjsx#L98-L107
And it's buggy and overly complicated.

I reworked this in #3556 somewhat which I think fixes the issue of those firing while waiting on the user and the user prefs, but it's only an incremental step which I'm not sure totally fixes it. The preferences listener is really oddly constructed and uses `forceUpdate`

**Comment by srallen** [comment]
@eatyourgreens Sorry, to answer your question, in #3556 the workflow is null while waiting on the project resources promises to finish, then the workflow is selected, fetched, and sets the state.

**Comment by eatyourgreens** [comment]
@srallen I was able to reproduce this bug in the #3556 branch too, so I'm not sure what's going on either.

**Comment by srallen** [comment]
I'll rebase #3556 once I merge #3599 and look into it there.

**Comment by srallen** [comment]
I've been looking at branching off of #3599 to fix the mini-course loading. Moving https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L315-L320 into the classifier index along with the minicourse fetch is causing some unexpected buggy behavior, the workflow is being fetched when the minicourse is shown and it's loading after less than 5 classifications.

**Comment by eatyourgreens** [comment]
@srallen I've pushed (and staged) an updated version in #3602 but I haven't yet tested to see if it has the buggy behaviour you describe.

**Comment by srallen** [comment]
@eatyourgreens the behavior I saw last night seems resolved. I think moving the listener and classification counting methods along with the method to determine if the mini-course should show fixed it.
