### ISSUE TITLE
Demo mode still enabled when navigating between projects

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3603]
## Expected behavior
Demo mode should disable when navigating between projects on the site.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Demo mode is still enabled when navigating between projects.

## Steps to replicate
I enabled admin mode to enable demo mode on a project to test to see if a bug had been resolved. I navigated away to the projects page and turned off admin mode and pulled up a another project. Demo mode was still enabled.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
I'm not sure this is a bug. If you turn on demo mode during a presentation, you probably don't want to submit classifications on any of the projects that you demonstrate.

**Comment by srallen** [comment]
@eatyourgreens that's a fair point. @mrniaboc is this how you use the demo mode in projects?

**Comment by srallen** [comment]
Closing as this is probably intended as a feature not a bug.
