### ISSUE TITLE
Add Featured Project section to home page

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#3605]
## Expected behavior
![home-feature](https://cloud.githubusercontent.com/assets/1392130/23961228/302a84c8-09a2-11e7-8e6e-04a2177bad54.jpg)

Please shorten the height of the video by about 200px and add this section below it. It should use the existing stylesheet (if this mockup is slightly off, please just use the stylesheet rather than matching the mockup exactly).  

The button should point to Planet Nine for the first week and the exoplanet project (with updated copy) for the second week. 

Happy to provide the Illustrator file if it would be beneficial.

**Comment by shaunanoordin** [comment]
Feature request acknowledged and actively being worked on.

## Feature Specs: New Featured Section on Home Page
Why: give focus to Stargazing Live project (and in future, any other project that needs focus)
What: a new "Featured Section" on Home Page that highlights hand-picked projects
Who: @beckyrother/des, @shaunanoordin/dev
When: Let's aim for an ETC of Wed 22 Mar

## Development Analysis
A few considerations to be made here:

1. (DEV) How will we select a "Featured Project"?
  * Most optimum approach would be to build a function into the PFE that allows admins to choose what's the Featured Project of the day/week/month.
  * However, that will require back-end resources and I don't believe we have any to spare at the moment.
  * A temporary, hardcoded section may be necessary. 
  * EDIT: apparently there's already a JSON config for this somewhere?
2. (DES) Regarding _"Please shorten the height of the video by about 200px"_ , the video is set in a CSS flex container that varies in height depending on window width, so achieving a flat reduction of size may be problematic.
  * I assume the goal is to make sure the "Featured Project" is one of the first things that a user sees when visiting the home page.
  * We may need to consider height in terms of fractions of viewport height or something... let me take a closer look at the CSS on Thu.
3. (DES) For consideration: what about _mobile view?_
  * (Same flex container issue, and in this case the video container takes the height of the viewscreen)
4. (DES) For consideration: what about the _logged in view?_

Tagging @eatyourgreens in for advice; your PFE expertise will be invaluable.
