### ISSUE TITLE
Should all collections and all favorites pages exist?

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3607]
@trouille @chrislintott This question has come come up in discussion while working on building out collections' features and UI for Gravity Spy this week. The pages in question:

https://www.zooniverse.org/collections
https://www.zooniverse.org/favorites

which show ALL zooniverse collections and ALL favorites on their respective pages, sorted by display name. No other functionality on these pages exist.

Do we know if our volunteers are using these pages? 
If not, is it because it's missing features?
If not, is it because they primarily use collections in project context and don't find this view helpful?

These pages are a bit heavy for the API and one suggestion is to remove them altogether especially if they are not used by the volunteers. We could restore them once a design/functionality pass is done.

**Comment by trouille** [comment]
@mrniaboc and @beckyrother Thought best to loop you into this question. Do you have a sense for this? 

Is there a way to know through the API how many collections include subjects from different projects? That could be one indicator of whether collections are used in a 'global' way currently, or if it's really confined to a specific project use.

**Comment by camallen** [comment]
@trouille we can run some queries to figure out how many people use collections this way. I know that in my birds collection each image is from a different project, https://www.zooniverse.org/collections/camallen/birds

**Comment by srallen** [comment]
I don't think those queries will necessarily answer the question I'm asking. I do think there are collections that have subjects added to them from various projects and volunteers use these. What I'm wondering is if volunteers are specifically using the `zooniverse.org/collection` or `zooniverse.org/favorites` pages because there's not much to do there but just browse through the paged response. We don't have search, filters, or sorts for those views and if I had to guess, volunteers are probably sharing their collections with others in the profile or project contexts. But this is just conjecture on my part. I don't think these pages should go away permanently, but maybe disable them until we have a chance to do a design and functionality pass on them?

**Comment by trouille** [comment]
I see what you mean. Google analytics can tell us about traffic to those URLs. GA is acting funky at the moment, so I'll try again after a call from 10-11 to pull up that info.

**Comment by camallen** [comment]
I personally don't think so unless we add decent discovery into it. Seems at least 1 volunteer thinks the same, https://www.zooniverse.org/talk/14/48817?comment=351130

**Comment by srallen** [comment]
That talk thread is getting at what I've been thinking. Volunteers aren't using it, but could or would if there were search, sorts, filters, etc.

**Comment by trouille** [comment]
GA for 'zooniverse.org/collections and zooniverse.org/collections/ from 1/17-3/16/17: https://docs.google.com/spreadsheets/d/1Q2uFasPtuZRk-vX0bvN_yW6nvin9aHTltLRQJaxA70Y/edit?usp=sharing

**Comment by srallen** [comment]
My follow up question to that is if those pages are being used as a way to get to 'My Collections' or 'My Favorites'? About 18% are leaving the site after going to the collections page (bounce+exit). The analytics for those who visit page 2 of all collections is 101 on that list, so it drops way off. People aren't going through the pagination. I think we'll need some data on what is being clicked on if anything when they visit, but my guess is that it's being used to get to the 'My Collections' link.
