### ISSUE TITLE
Closing a stubtask forces the subject to scroll to the top of the image

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#3613]
## Expected behavior
After completing a subtask (i.e., clicking or pressing enter on the "Ok" button), the subject image should not move. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
If an image extends outside the viewport through the workflow config `'configuration.image_layout':['no-max-height']`, when a subtask modal is closed, the image scrolls back to the top of the screen. 

## Steps to replicate
You can see this on [Decoding the Civil War](https://www.zooniverse.org/projects/zooniverse/decoding-the-civil-war/classify) transcription task. 
1. Scroll down to the bottom of the image
2. Draw a line, then close the subtask modal
3. The image will scroll back to the start.

## Additional information

- **Operating system:** Mac OS
- **Browser:** Chrome

**Comment by simensta** [comment]
@mcbouslog, this might be relevant for the Notes from Nature projects.

**Comment by simensta** [comment]
This issue may be related to changes made in PR #3533.

**Comment by eatyourgreens** [comment]
Yes, the popup remembers which element had keyboard focus when it opened, then restores focus to that element when it closes. In this case, it turns out that's the radio button for the line drawing tool, at the top of the subject, not the SVG line (which would maybe make more sense.) I'm not sure how we should handle this. Open to suggestions.

**Comment by simensta** [comment]
I think it makes more sense for the SVG element to hold focus before the modal opens and after the modal closes. Perhaps that can be addressed in #3369. In the meantime, I think #3617 is a good solution.
