### ISSUE TITLE
Keep "Going back will clear your work for the current task" messaging always visible in PFE classify

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#3620]
## Expected behavior
This message should always be visible in the PFE classify section, formatted as `small p`

## Current behavior
Currently, hovering over the Back button causes the message to appear, formatted like a button. 
https://www.dropbox.com/s/d9lel4mloizdaif/going-back.mov?dl=0

## Steps to replicate
Accidentally moving the mouse over the button causes it to flash for a second, making it look like the page is broken.

## Additional information

- **Operating system:** macOS Sierra 10.12.3
- **Browser:** Chrome

**Comment by camallen** [comment]
linked to https://github.com/zooniverse/Panoptes-Front-End/issues/3131#issuecomment-282258492

Much better than me hijacking another issue, thanks @beckyrother

**Comment by eatyourgreens** [comment]
Linked to #2611 (original discussion about adding a warning notice to the Back button.)

**Comment by eatyourgreens** [comment]
Whoever picks this up: the relevant code is in the classifier's [TaskNav component](/zooniverse/Panoptes-Front-End/blob/master/app/classifier/task-nav.jsx).
