### ISSUE TITLE
Paging broken in Inbox

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes-Front-End#3627]
## Expected behavior

Clicking "Next" should load the next page of messages.

## Current behavior

The URL changes to https://www.zooniverse.org/inbox?page=2, but the next page isn't loaded. The window just scrolls to the top and still has the first page loaded.

There aren't any errors or warnings in the console.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by simoneduca** [comment]
I had a look into this. I can reproduce and also I observed some further weird behaviour. During testing, I've noticed the next button of the paginator became enabled before hitting the page limit (10 by default). The logs show that the number of conversations returned by the Talk api is double the number of messages actually displayed. More evidence of this is that I had to archive a message _twice_ for getting rid of it. I'll keep looking.

**Comment by simoneduca** [comment]
Also I'm noticing the order of the messages is messed up. Testing 1 it's the oldest of the list and should be on page 1. The paging doesn't match with url either

![screen shot 2017-04-28 at 11 02 48](https://cloud.githubusercontent.com/assets/8989606/25524623/4b2073a4-2c03-11e7-8c86-91509a74f8f6.png)

**Comment by simoneduca** [comment]
That's very likely related to this https://www.zooniverse.org/talk/17/311244?comment=518019&page=1

**Comment by eatyourgreens** [comment]
I think that Talk discussion is a slightly different issue: when you click on one of those conversations, to read the full thread, the messages aren't always shown in chronological order.

**Comment by simoneduca** [comment]
I thought they are saying the order isn't chronological for neither messages nor threads.

**Comment by eatyourgreens** [comment]
Just conversation threads, I think.
>Several times in the past week or so, I've opened a private message thread, jumped to the end and noticed that the last message displayed was a message to me, when I was sure I'd replied to it. I scrolled up and found that my reply was shown prior to the message I replied to. I've just scrolled through several PM threads. In most, the messages are shown in the correct sequence, but in a few, two messages are transposed.

**Comment by simoneduca** [comment]
Mmm, what are they saying here then?

> The messages in my Inbox are listed in apparently random order (at least, I can't see a pattern. Recently active ones are not at either the top or bottom. They aren't sorted by user I'm communicating with, nor by thread title. I would prefer threads with the most recently posted message to be at the top. But the inbox sequence doesn't bother me much.
The jumbled sequence within a thread does bother me quite a lot.

**Comment by eatyourgreens** [comment]
I'm not seeing it on any of the discussions in my inbox. It sounds like it's rare, and hard to reproduce.
The [inbox conversation component uses default sort order](/zooniverse/Panoptes-Front-End/blob/master/app/talk/inbox-conversation.cjsx#L73), which I guess is by message ID.

**Comment by eatyourgreens** [comment]
That second quote is a different problem from the one that _am.zooni_ is describing, except for the last sentence.

**Comment by eatyourgreens** [comment]
[Conversations are sorted by `updated_at` descending](/zooniverse/Panoptes-Front-End/blob/master/app/talk/inbox.cjsx#L81-L86). Maybe that should be `created_at`?

**Comment by simoneduca** [comment]
OK, if I follow correctly, there are three things going:

1. paging is broken for threads.
2. order isn't chronological for threads.
3. order isn't chronological for messages within a thread.

This is issue is about 1, soI've crossed out the reference to the Talk thread, which instead is mainly about 2, with a reference to 3.

I'll open separate issue for 2 and wait to see more evidence of 3.

**Comment by eatyourgreens** [comment]
Looking into my inbox, `updated_at` is incorrect on the conversation resources, so I think the inbox order is also a problem with the Talk Rails app. Here's an example from one of my conversations. The 'updated at' and 'created at' times are the same, and match the time of the first message in the conversation.
```json
created_at: "2016-09-28T20:03:14.326Z"
href: "/conversations/1533"
id: "1533"
is_unread: false
links: {messages: ["5907", "5910", "5918", "5914", "5915", "5909", "5916"], users: ["149", "1342057"]}
moderatable_actions: ["report"]
participant_ids: [1342057, 149]
title: "Galaxy zoo forum index"
updated_at: "2016-09-28T20:03:14.334Z"
```

**Comment by eatyourgreens** [comment]
So, basically, a conversation never moves up to the top of the list (returned by the Talk API) when someone replies to you, as you'd expect.

**Comment by simoneduca** [comment]
That covers 3, in my list above, right?

**Comment by eatyourgreens** [comment]
Sort of: the bug is that conversation timestamps are never updated. They are sorted chronologically, but using the wrong date and time.
