### ISSUE TITLE
The combo task's summary should contain the summary for each inner componnet

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#3628]
## Expected behavior
The summary for a combo task should include more information.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The current summary is `X-task combo` where x is the number of tasks.

**Comment by eatyourgreens** [comment]
@CKrawczyk is this still an open issue?

**Comment by CKrawczyk** [comment]
This should have closed with the PR.
