### ISSUE TITLE
Can we speed up large worfklow task objects (NFN dropdowns)?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#3636]
## Expected behavior
Faster load / serializer times with smaller responses.

## Current behavior
Large workflow task objects (NFN dropdowns) are serialized from DB -> API -> client with json transformation along the way. Do we really need these to be in the database and serializing all the time? Could we serialize a url to a remote JSON file on s3 that we version accordingly instead?

Pinging @mcbouslog @eatyourgreens

**Comment by eatyourgreens** [comment]
Would Panoptes be responsible for updating the file on S3, or would the dropdown task editor in PFE generate a file that gets posted to S3 (similar to subject uploads I guess.)

**Comment by camallen** [comment]
I'm not sure but either seem doable.

**Comment by marten** [comment]
This feels like the wrong solution to me, making it harder to use for 99% of the users of the dropdowns.

The troublesome NFN dropdown suggests to me more that we need a task type to ask for country names. That way that specific task type can have the list baked in such a way that it's loaded on demand, but loaded from just the normal PFE S3 bucket, where it gets put during deployment.

**Comment by marten** [comment]
@eatyourgreens found that such a list already exists: https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/classifier/tasks/dropdown/presets. It's just that the task editor copies those lists into the task definition, instead of putting in a reference. 

I would vote that this ticket should work to putting in that reference, rather than doing lots of work to store parts of the workflow task definitions on S3.

**Comment by eatyourgreens** [comment]
Not so fast, stale-bot. I think this still needs fixing.

**Comment by mcbouslog** [comment]
Working on tests and ES6 refactor of dropdown related components now, still hope to address this issue.

**Comment by mcbouslog** [comment]
Notes from Apr. 3, 2018 #dev Slack (feel free to edit):
- react-select can request a list of options via http
- perhaps an auto-suggest pre-populated by previous classifications would work as well
- built one for OWD, Historical geographic data might be tricky, if place names have changed - 
https://github.com/zooniverse/operationwardiary/blob/master/app/lib/geocoder.coffee
