### ISSUE TITLE
Add messaging around unavailable end points

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#3638]
## Expected behavior
We're planning to disable some API end points for SGL (subject create / link to sets, etc) during SGL. The UI should be able to message to users (lab, etc) that some actions are temporarily unavailable, .g 503 HTTP status

It would be nice to have this in play before SGL. @mrniaboc we should message the project owners about this sort of behaviour ahead of time too.

## Current behavior
Cryptic Silent Failure

## Steps to replicate
Wait for the api to be down and use our site.

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Linked to #3637

**Comment by srallen** [comment]
Just noting, that at least for subject uploading, when testing flipper, that a useful error message is currently being reported in the UI:

<img width="371" alt="screen shot 2017-03-24 at 3 09 22 pm" src="https://cloud.githubusercontent.com/assets/5016731/24463568/b4768cf2-146c-11e7-857d-df17ccf68646.png">

**Comment by simoneduca** [comment]
There's a general need for better error messaging. Is this still required after SGL?

**Comment by srallen** [comment]
I'm gonna close this in favor of more specific issues about error message improvements.
