### ISSUE TITLE
Home page column layouts break in smaller windows

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#364]
Looks like the "about" graphics are laid out in CSS columns, so when there's only space for two columns the second item falls under the first.

![screen shot 2015-05-19 at 3 10 46 pm](https://cloud.githubusercontent.com/assets/464389/7713450/6f928ab0-fe3d-11e4-960f-bf824dd52953.png)

I bet there's a way to do this with flexbox so that the five things (three images, "+", and "=") will line up when there's enough space and break completely when there's not.

Possibly related: the featured projects break oddly:

![screen shot 2015-05-19 at 3 11 12 pm](https://cloud.githubusercontent.com/assets/464389/7713457/7a274d26-fe3d-11e4-9246-8d92c651838b.png)

**Comment by srallen** [comment]
I talked with @heathv about this this morning and the page design is being iterated on one more item based on some of the content coming, so I'm going to wait for the updated designs before fixing.
