### ISSUE TITLE
Workflow task for drawing full-bleed row shapes?

### ISSUE THREAD

**Issue by freen** [zooniverse/Panoptes-Front-End#3640]
I want to require volunteers to select full-bleed rows when drawing rectangles in two of my workflow tasks.

Does Panoptes Front-end support this, out of the box?

It would be just like drawing full-height "column rectangles" which have variable width, except I'd like the width to be constrained to the full width, and the height to be variable.

If this isn't supported, and I wish to custom code it, I'm assuming this would imply a fork & custom hosting of PFE, to add this shape to the existing workflow task toolset? Is this correct? Or is there a way of coding custom workflow tools, and integrating them into a hosted PFE project?

![screen shot 2017-03-23 at 8 52 25 am](https://cloud.githubusercontent.com/assets/1816457/24237542/fecb09f6-0fa6-11e7-85c8-074c159c1f8a.png)

**Comment by srallen** [comment]
@freen we currently do not have a drawing tool that functions in this way. If there is a need for it, we can certainly think about adding it in. Also, you are welcome to fork the repository, add it, and submit back a pull request for us to review. There is no need to custom host PFE, unless you have another reason to do that. 

You can take a look at the column rectangle tool as a model:
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/column-rectangle.cjsx

Just so you are aware, we are currently in the middle of migrating our codebase from coffeescript to ES6, so we'd prefer any new code to be written in ES6 with native classes.
