### ISSUE TITLE
Only render SVG surface for drawing tasks and workflows with pan and zoom

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#3642]
## Expected behavior
The SVG surface should only render for drawing tasks and workflows with pan and zoom enabled. Related to #3465. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The SVG surface is rendered for non-drawing tasks that do not have pan and zoom enabled.

## Steps to replicate
An example is [Snapshots at Sea](https://www.zooniverse.org/projects/tedcheese/snapshots-at-sea/classify).

## Additional information

- **Operating system:** 
- **Browser:**

**Comment by eatyourgreens** [comment]
Pretty sure this was closed by #3743
