### ISSUE TITLE
Manifests necessary for upload

### ISSUE THREAD

**Issue by rjsmethurst** [zooniverse/Panoptes-Front-End#366]
Current text for uploading images on a new project is: 

![image](https://cloud.githubusercontent.com/assets/5754386/7728163/5ceaa9ba-ff05-11e4-94e4-4afa7f3eaabc.png)

As a first time user I didn't understand that a manifest was **necessary** to upload any images. I thought the drag and drop wasn't working. Also it's not clear what a manifest necessarily is. Can we bulk out the wording of this to explain more what's needed to the less experienced user?

**Comment by vrooje** [comment]
Do you think the help text in #300 makes it clearer a manifest is necessary, or should there be additional text in the upload box too?

For example, it could say just after the bold sentence:
"The uploaded files must include a manifest and at least 1 subject image. [new paragraph]"

**Comment by chrissnyder** [comment]
Text has since changed and looks to address these concerns. @rjsmethurst reopen if you disagree.
