### ISSUE TITLE
on a 13-inch screen the featured project bit of the Zooniverse Home isn't visible 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3664]
In case the feedback is helpful, I pretty much missed there was a message about stargazing live on the logged in profile page. The only thing that pops up is featured project right at the end of the page on my 13-inch screen. 

<img width="1126" alt="screen shot 2017-03-28 at 11 42 42 am" src="https://cloud.githubusercontent.com/assets/753325/24428949/ca202926-13ab-11e7-8b41-9e68e28a17e4.png">

**Comment by srallen** [comment]
We can't really design for all screen sizes and resolutions, but maybe just a small visual indicator for scrolling might just be all that is needed.

@beckyrother perhaps a small arrow indicator somewhere to indicate you can scroll?

**Comment by beckyrother** [comment]
This is good feedback, thanks @mschwamb! 

@srallen that would work - maybe the down arrow from FontAwesome would work vertically centered in the blank space between "my collections" and the edge of the teal box?

**Comment by srallen** [comment]
@beckyrother FontAwesome would definitely work here. Do you want it to be a functional button of some kind? Perhaps a scroll to the next section of the page?

**Comment by beckyrother** [comment]
No, I think the arrow will be enough on its own. Since we can't plan for all screen sizes, I can see that functionality being more frustrating than helpful.
