### ISSUE TITLE
When you click on Scroll to Last Comment, it cuts off the top of the comment

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3665]
See when you go to https://www.zooniverse.org/projects/skymap/planet-9/talk/794/232008?page=1&scrollToLastComment=true for example 
You get this on Mac Firefox 

<img width="1104" alt="screen shot 2017-03-28 at 8 08 08 pm" src="https://cloud.githubusercontent.com/assets/753325/24440849/558e4a38-13f2-11e7-9edd-3aeff7ae189f.png">

**Comment by srallen** [comment]
Noting here that the discussion component is written to scroll to the bottom of itself instead of to the top of the last comment: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/discussion.cjsx#L163-L164
