### ISSUE TITLE
Modify AppStatus to Allow Mobile Webview

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3668]
## Expected behavior
Mobile webview should work properly on a native app.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The native webview component cannot identify the fetch function [here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/partials/app-status.jsx#L47), which causes the native app to continuously load in iOS.

## Steps to replicate
In the mobile app, select a project with a workflow that takes you the webview (as opposed to switching to Safari).

## Additional information
A mobile [issue](https://github.com/zooniverse/mobile/issues/104) has been opened, but the issue has been traced to the `AppStatus` component in PFE.

- **Operating system:**
- **Browser:**

**Comment by mcbouslog** [comment]
Also possibly LabStatus, though not sure it affects mobile, as it's only within the lab/Project Builder.

**Comment by shaunanoordin** [comment]
@wgranger Using `fetch` as a default and then `XMLHttpRequest` as a fallback sounds like a solid idea.

My only thought is that I'd first try `if (fetch && somehowCheckIfFetchIsValid()) { doFetchChain(); } else { doXHR(); } `

...instead of `try { doFetchChain(); } catch (err) { doXHR(); }`

...but only because the current `fetch()` chain has its own `.catch()` clause; I suspect if the `fetch()` effs up in native app, it might be caught by the chain's `.catch()` instead of the external `try{} catch() {}`

**Comment by shaunanoordin** [comment]
Alternatively, I see no harm in doing full rewrite to _only_ use the safer/more compatible XMLHttpRequest.

Side note: I agree with @mcbouslog that the LabStatus should be updated as well; the code's pretty much copy-paste except for the URL and className.

**Comment by robinschaaf** [comment]
Cool.  Will try that.  It's not being caught in the existing `.catch()`, I suspect because that's if the connection can't be made, not if the `fetch()` function entirely doesn't exist.

**Comment by wgranger** [comment]
@robinschaaf and I had discussed if it was necessary to alter LabStatus as well (since the mobile app likely won't be using it), but maybe it does make sense to make the change there for consistency since it's being brought up here.

**Comment by eatyourgreens** [comment]
https://github.com/github/fetch/issues/401 :( Would a polyfill work with React Native? PFE polyfills `window.fetch` to get around lack of browser support.

**Comment by robinschaaf** [comment]
Unfortunately I don't have much control over JS or really anything in WebView.  I can inject JS code (and attempted this) but it doesn't get injected until after the page has begun rendering which is too late in this case.  It does appear to be fixed in iOS 10.3 though :-(

**Comment by srallen** [comment]
I'd rather not revert back to only using XMLHttpRequest and would rather have the conditional since fetch is the current web spec. Could we leave a comment in the code about why we're doing this so we remember in the future that it's necessary for mobile webviews at the moment?

**Comment by robinschaaf** [comment]
Sure
