### ISSUE TITLE
Rewrite talk sidebar

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3669]
As a follow up to #3667:

> A better, long term solution would be to rewrite Talk to share single instances of the sidebar components. At the moment, each page component creates its own instance of ActiveUsers, which initialises with no stored data.

**Comment by eatyourgreens** [comment]
Adding to this that Stargazing Live last week found a problem with lists of comments implemented in multiple, slightly different ways rather than as a reusable `CommentList` component.

We could maybe expand this issue to generally refactoring Talk to DRY it up.

**Comment by eatyourgreens** [comment]
This still needs to be done.
