### ISSUE TITLE
Subject talk page does not show user role tag

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3677]
## Expected behavior
Role tag should appear under the username for the comment if applicable.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
![pasted image at 2017_03_29 22_09](https://cloud.githubusercontent.com/assets/5016731/24514725/e5642ad0-153a-11e7-9ac9-c572b57b9b33.png)
The `TalkDisplayRoles` component is expecting a roles prop. The talk roles are only being fetched in the `Discussion` component and the subject page is not a child of the `Discussion` component. Where these API calls are made needs to be refactored so all of the children are getting the data they are expecting. I suspect the roles on the subject page never worked rather than this being a regression that happened at some point.

## Steps to replicate
Go to any subject talk page that has comments made by someone that should have a role displayed (i.e. Zooniverse Team under my username)

**Comment by eatyourgreens** [comment]
I took roles out of the `Comment` component in #3505. Didn't realise it was being used here too. I'll get a PR up to fix it.

**Comment by srallen** [comment]
Oh I forgot that happened. I think we need some parent wrapper component handling common API calls as a long term fix.
