### ISSUE TITLE
track classifications that have been seen before

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#368]
Add a `seen_before` attribute to the classification metadata and set the value to true when a volunteer (anonymous & logged in) has seen a subject before. E.g.

```JSON
    "metadata": {
      "started_at": "2014-08-24T22:20:21Z",
      "finished_at": "2014-08-24T22:24:31Z",
      "user_agent": "cURL",
      "user_language": "es_MX",
      "workflow_version": "11.12",
      "seen_before": true
    }
```

**Comment by camallen** [comment]
Seems this isn't actually adding a `seen_before=true` key to the submitted classification metadata object. The aggregation engine is going to use this to ignore extra classifications from a single user.

![image](https://cloud.githubusercontent.com/assets/295329/8649655/32d205f4-2964-11e5-82c9-b2f1712fc4de.png)

**Comment by chrissnyder** [comment]
Why is this the front-end's responsibility? Shouldn't aggregation be able to select distinct classifications from each user and do this automatically?

**Comment by camallen** [comment]
Yeah it's debatable. We are tracking this state from selection and providing that state to the client for signaling to a user that they can choose to ignore this subject if they want. 

Providing this known classification state via metadata on the return trip is in my opinion a responsibility of the client since as the flag state in the UI may impact on the derived classification. It could be argued that the client is not responsible for providing this information (even though it has it) and subsequent aggregation would have to decide which classification a user submits to keep (most likely sorted by date). 

It could also speed up aggregation processing (@ggdhines ?) but that's not a direct client concern maybe a nice to have.

**Comment by ggdhines** [comment]
I'm fine with taking responsibility for looking for users who see the same subjects twice. There may be issues with how we deal with non-logged in users which is something I will need to look at in the future.

**Comment by chrissnyder** [comment]
Fair point re UI impact on the classification. Though that leads to a slippery slope recording a lot of ancillary state (width of browser window, screen brightness, science/field guide/help text available at the time).

**Comment by camallen** [comment]
Yeah it is the thin edge, for reference we do capture screen viewport values since #991. Also I'm not super concerned with this if you all feel it's not required. 

@ggdhines speak up now if you'd like this this flag set as per https://github.com/zooniverse/Panoptes/issues/1086. Also if there is any value as a proxy indicator in user behaviour analysis in the future. I.e. do users classify differently when they've previously seen a subject?

**Comment by ggdhines** [comment]
I should be able to determine if someone has seen an image before - a little bit of extra work for me but probably keeps things a lot simpler on the whole. So I am fine without this flag - as per future analysis - that kind of analysis should be doable even without the flag.

**Comment by camallen** [comment]
Current functionality is fine. Closing again as the linked panoptes issue is closed.

**Comment by mschwamb** [comment]
@camallen there will be some teams that do their own data reduction - it would be helpful if this tracked of at least trying to remove the ones are already known by the front end to be duplicate classifications. If it's already identified in the front end that there is a duplicate, as long as that identification is robust enough that having that information in the csv data dump would be useful for researchers when doing their own analysis separate from the aggregation algorithms being developed

**Comment by aliburchard** [comment]
I agree. I know @ggdhines doesn't need this tracked because he can figure it out in the aggregation scripts, but I think if it's a straightforward flag to add, it would help out a *log* for teams dealing with the raw data files.

**Comment by camallen** [comment]
@aliburchard @mschwamb would a `already_seen=true` flag in the metadata on any subsequeunt classifications work for you?

**Comment by camallen** [comment]
sorry - thought this was a panoptes issue, re-openning there.

**Comment by mschwamb** [comment]
@camallen I think that would be great if there could be that flag in the csv dump especially for quick reduction when there's many many classifications.

**Comment by aliburchard** [comment]
agreed - that flag in the classification data would work great.

**Comment by camallen** [comment]
please comment on the panoptes thread from now on.
