### ISSUE TITLE
Returning to Classify page after Talk presents users with previous classification summary

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#3680]
## Expected behavior
If a user presses the "Talk" button after finishing a classification, the user should be able to press "CLASSIFY", in the navigational header, and return to the classify page with a new subject.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
If a user presses "Talk" after finishing a classification and, then, uses the "CLASSIFY" link to return to the classification interface, the user is presented with the classification summary.

Pressing "Next" fetches a new subject, but any drawn marks remain and the summary remain.

## Steps to replicate
https://www.zooniverse.org/projects/zooniverse/decoding-the-civil-war/talk/465/226700?comment=408223

## Additional information

- **Operating system:** Mac OS
- **Browser:** Chrome

**Comment by simensta** [comment]
This is only an issue when the Hide Classification Summary is NOT enabled. For example, you can replicate the issue in [Decoding the Civil War](https://www.zooniverse.org/projects/zooniverse/decoding-the-civil-war) (classification summary provided), but not in [Mapping Change](https://www.zooniverse.org/projects/zooniverse/mapping-change/classify) (classification summary hidden).

**Comment by simensta** [comment]
I enabled the Hide Classification Summary feature for Decoding the Civil War, so you can no longer replicate the issue on that project.

**Comment by eatyourgreens** [comment]
Looks like [`completeClassification`](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/index.cjsx#L298) should always call `onCompleteAndLoadAnotherSubject`. Easy to fix, but we should wait until #3647 is merged, and fix it there to avoid rebasing problems.

**Comment by eatyourgreens** [comment]
On second thoughts, looking at that code, changing that might break Gravity Spy gold standards.

**Comment by eatyourgreens** [comment]
[Annotations are persisting on Milky Way Project](https://www.zooniverse.org/talk/17/248605?comment=414431) too, so that may be a separate bug.

**Comment by eatyourgreens** [comment]
Re. the Done & Talk button, there's a bug where `loadAnotherSubject` won't be called if [`saveClassification` isn't resolved](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/classify.cjsx#L232-L233) when the classify page unmounts.

**Comment by simensta** [comment]
Fixed by #3681.
