### ISSUE TITLE
Statistics page not removing workflows that were active but are now inactive

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3683]
## Expected behavior

Steller Watch PI brought up an interesting point that it would be useful to still be able to see the stats for workflows that were active, but are turned to inactive when their associated subject sets are completely retired. 

Could we find a way to keep those now inactive workflows showing within the stats page? Note: important will be to not show all 'inactive' workflows, since some projects will have inactive workflows that haven't had any classifications and so they won't want to clutter up the stats page with these non-interesting workflows. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Currently PFE is using an `active: true` filter on those workflow requests for stats

## Additional information

- **Operating system:**
- **Browser:**

**Comment by CKrawczyk** [comment]
I should be able to turn the "Statistic visibility" into a radio button the the visibility page of the lab, and let only that value determine what shows up on the stats page.  I will have to make sure it defaults to `off` for currently non-active workflows and `on` for active ones so it does not change the currently visible workflows.

**Comment by trouille** [comment]
@CKrawczyk That sounds like a good approach. What's your workload over the next couple weeks? Is this something you might be able to get to in that time period? If yes, could you give a broad ETA that I could share with Steller Watch? Thanks!

**Comment by CKrawczyk** [comment]
I can start in on it later this week (likely Friday), I don't expect it to take very long, so it should be ready early next week.
