### ISSUE TITLE
Hide export button if limiting is in effect

### ISSUE THREAD

**Issue by zwolf** [zooniverse/Panoptes-Front-End#3691]
Exports are rate limited to one of each per 24 hour period for non-admin users. Currently, there is no feedback to indicate that a user's request will be denied and that they shouldn't expect anything to happen. They see the "check your email" message, which is false.

A possible solution would be to look at the timestamp on the medium and if it's less than 24 hours old, do not show the export button at all and indicate that they have to wait to request another.

**Comment by srallen** [comment]
We should add a general message on the page about the rate limiting and I would suggest disabling the button rather than hiding.

**Comment by srallen** [comment]
@amyrebecca @jelliotartz I think this is resolved, but I'm not sure which PR this was resolved by. Could you comment and close this issue? Thanks.

**Comment by jelliotartz** [comment]
@amyrebecca did #3806 resolve this issue? I'm pretty sure it did, just want to double check with you before closing this issue.

**Comment by amyrebecca** [comment]
Yes. I'm closing the issue.

**Comment by amyrebecca** [comment]
No, #3806 was about workflow-specific classification exports. I don't remember which issue this one was but we worked on it around the same time.

**Comment by amyrebecca** [comment]
Actually this is really confusing because it looks like the actual commits on this issue WERE from working on #3806 but this issue SEEMS to be about all of the data dumps buttons, not just that specific one.

**Comment by jelliotartz** [comment]
Yeah, I'm not sure either. We also worked on #3800, but that deals specifically with the aggregation export button, and doesn't deal with rate limiting. I think #3800 and #3806 are the only 2 PRs we worked on that dealt with exports.

I'm going to close this issue, as we've now mentioned all PRs that we worked on that could be relevant to the issue, but feel free to reopen if necessary.
