### ISSUE TITLE
Change survey keys for Treeversity

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#3705]
The issue of dropping vowels (#3290) from survey keys was resolved for future projects. Can someone (@eatyourgreens @camallen ?) manually fix the keys for the Treeversity project?

**Comment by eatyourgreens** [comment]
@mkosmala do you still have the CSV files around, that were used to create the task? If so, I'd suggest uploading them again, which should force Panoptes to create the task again, on the workflow, with new keys.

**Comment by srallen** [comment]
Closing as this isn't really a PFE issue and a suggested way to fix to the data has been provided.
