### ISSUE TITLE
Project Talk Images are Awkward on Safari

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3707]
## Expected behavior
On a project landing page, subject images from talk should fill up their container.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Safari is not reading the `object-fit: cover` property that is registering in Chrome and Firefox. This causes the images to appear as below.
<img width="1090" alt="screen shot 2017-04-07 at 3 45 26 pm" src="https://cloud.githubusercontent.com/assets/14099077/24819322/bd4c9896-1ba9-11e7-9a10-e4bbccd2ce01.png">

## Steps to replicate
View [this](https://www.zooniverse.org/projects/mrniaboc/bash-the-bug) project in Safari (Bash the Bug).

## Additional information

- **Operating system:**
iOS
- **Browser:**
Safari

**Comment by srallen** [comment]
Use of `object-fit` should be removed. It only has partial support in safari and no support in IE/Edge: http://caniuse.com/#search=object-fit
