### ISSUE TITLE
Font-size Accessibility - overrides custom user settings

### ISSUE THREAD

**Issue by BNewing** [zooniverse/Panoptes-Front-End#3708]
## Expected behavior
When you alter the font size in the browser settings (in Chrome it's under advanced settings), you should see a change in the website font size to match what the user selected.

## Current behavior
This currently doesn't happen. It looks like it's because in the typography stylus file, the font-size is set as 15px/1.5 on the HTML. This overrides any custom browser settings that the user may have put in place for accessibility reasons. 

At work to combat this I've been setting this font-size on the html tag to 100%. This accepts user browser settings. I then assume that the browser will normally interpret that as 16px, and then set all the text element font-sizes as rems based on that (so 40px would be 2.5rems for example). This means that the same scale will be used even when a different base font size is used. I don't know if this is the best best practise, but it'd solve the issue.

## Steps to replicate
Go to the settings tab on Chrome, scroll down to 'advanced settings' and then 'Web Content'. Alter the browser standard font-size with the font-size drop down.

## Additional information
For more info on background of this issue, there is the 'font-size' section of this page here (roughly section 9):
http://webaim.org/techniques/fonts/

- **Operating system:**
OS Sierra
- **Browser:**
Chrome

**Comment by eatyourgreens** [comment]
:+1: this basically follows [Richard Rutter's advice for font-sizing](http://clagnut.com/blog/348/), updated to use rems since ems can be change size according to parent context.
