### ISSUE TITLE
Allow description header and text

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#371]
Allowing a description header and a description text field would allow projects to make effective landing pages without having to open up the customization conversation (#295). The description header would appear in large bold text (as a header1 or something) and the description text would be plain text that is the same text rendered elsewhere on the site. In the example below,  "Help map the wildebeest migration!" would be the header, and the rest would be the description that appears on the landing page and wherever else it's needed. 

![image](https://cloud.githubusercontent.com/assets/6217406/7746622/e9498ccc-ffab-11e4-8de0-5c59e7bb1b79.png)

**Comment by brian-c** [comment]
This is a design issue, The `description` field should not have been displayed on the landing page--my bad. Projects are free to have a big header and a little header in their `introduction`. @heathv, do you have time to draw up a new project landing page?

**Comment by alexbfree** [comment]
Maybe this is already covered elsewhere, but I just happened to click into here and thought I would add a suggestion: That body text and the footer text below it really need a big left and right margin to increase readability!

**Comment by heathv** [comment]
Used Snapshots at Sea in this mock-up, hopefully the changes aren't too wild. Line-lengths/text boxes should not exceed 800px. Also moved the description to a separate container. 

I was hoping to have an adobe extract link available to grab font sizes/colors/etc., but it seems the latest creative cloud update borked it.

![sloan-projects-062215](https://cloud.githubusercontent.com/assets/4551411/8290472/ddf0eedc-18e8-11e5-9922-2ef0f03816b0.jpg)

**Comment by aliburchard** [comment]
This design is beautiful, but I'm not sure it solves the Header/Subheader need or #687 . We still need space for a one-line description below "help scientists identify marine mammals" -- especially when we have multiple buttons. And that text needs to be more prominent than the stuff in the "introduction" in the section below. For example -- in wildebeest watch below, we need to provide enough information for people to make the choice between workflows. 
![screen shot 2015-06-24 at 14 49 12](https://cloud.githubusercontent.com/assets/6217406/8331429/30f568cc-1a80-11e5-9372-77a0b7a34edb.png)

**Comment by edpaget** [comment]
Sure @aliburchard I'll add field to store a something like that. What should it be called?

**Comment by edpaget** [comment]
Does 'Workflow Description' sound fine to you?

**Comment by edpaget** [comment]
Whoops still open until the other PR is merged

**Comment by aliburchard** [comment]
@edpaget sorry for the delay, yep, "workflow description" sounds good!
