### ISSUE TITLE
UI to stop marking of incorrect image

### ISSUE THREAD

**Issue by hrspiers** [zooniverse/Panoptes-Front-End#3719]
@rogerhutchings 

## Current behaviour
At the moment it is possible to draw on all 5 of the subjects contained in the flipbook in Etch a Cell. 

## Desired behaviour
For the current Etch a Cell project, the researchers only want users to mark the central flipbook image - it would be good to be able to alter settings to stop users being able to mark the other subjects.

**Comment by eatyourgreens** [comment]
#3713 might help here too.

**Comment by eatyourgreens** [comment]
Closing this because we implemented the default frame feature for subject slideshows.
