### ISSUE TITLE
ethics agreement feature

### ISSUE THREAD

**Issue by hrspiers** [zooniverse/Panoptes-Front-End#3721]
I've spoken to @rogerhutchings about this, but to make a note here...

We have a biomedical project in the pipeline called X-ray lab (https://www.zooniverse.org/projects/lesb20/x-ray-lab). The images in this study come from the Osteoarthritis Initiative, who have a condition that anyone with access to the images needs to agree to the Osteoarthritis Initiative's ethical use agreement.

At the moment, the project owners have a messy work around to stop users viewing the images prior to signing the ethical use agreement - users are directed to http://people.bath.ac.uk/ecp32/registration.php , a University of Bath hosted page, to sign the agreement. Users are then asked to provide their Zooniverse username at this point, and are then manually added by the project owners to a private version of the project of the same name (www.zooniverse.org/projects/lesb20/x-ray-lab-lets-go) to give them access to the study.

Note, two versions of the project have been created to do this - one with the url to the ethics agreement, the other a private project that users are given access to after agreeing to the ethics;
https://www.zooniverse.org/projects/lesb20/x-ray-lab
www.zooniverse.org/projects/lesb20/x-ray-lab-lets-go

We need some alternative to this - something like an 'Ethics pop up' that has to be signed by a volunteer before they can access the project workflow. This type of issue is likely to pop up again, so it's worth developing a solution.

**Comment by MvGulik** [comment]
Spotted on the oai.epi-ucsf.org website.
>Acceptance of the terms of the Data Use Agreement (**you must be logged on to view it**)

Interesting. I'll never have seen one of those before.

- Artificial inflation of the registered account number comes to mind.
- Seems the related document is just publicly available.
- - [https://oai.epi-ucsf.org/datarelease/docs/OAIDataUseAgreeClinical.pdf](https://oai.epi-ucsf.org/datarelease/docs/OAIDataUseAgreeClinical.pdf)
- - or if that fails: [web.archive.org](https://web.archive.org/web/20170415090303/https://oai.epi-ucsf.org/datarelease/docs/OAIDataUseAgreeClinical.pdf)
