### ISSUE TITLE
Survey task - same identification allowed multiple times

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#3727]
## Expected behavior
Identification should get updated if same animal is selected
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Two separate identifications are allowed when same animal is selected.
<img width="531" alt="screen shot 2017-04-13 at 17 02 29" src="https://cloud.githubusercontent.com/assets/8989606/25013348/27848f00-206b-11e7-9c89-cbacc05b3b4c.png">

## Steps to replicate
Select same animal from filter.

**Comment by trouille** [comment]
Possibly related. The Snapshot WI team would really like to not allow users to choose the same species twice. They get a lot of repeat species classifications in their results and aren't sure how to use them (i.e., deer chosen twice, with one saying there's 1 deer and the other saying there are two deer). Gravity Spy has made a similar request, though for them it's less essential/critical.

**Comment by eatyourgreens** [comment]
I think the `Choice` component needs to be updated to take the current annotation as a prop, rather than starting a fresh set of answers when it loads.

**Comment by srallen** [comment]
That's what we did for the port of the survey task for Wildcam Gorongosa: https://github.com/zooniverse/wildcam-gorongosa/blob/master/app/tasks/survey/choice.cjsx#L70

We also should make sure there aren't any survey task projects that actually do want multiple annotations per survey item. When the survey task was first designed, this was meant to be flexible for that use case. We may find, though, that no one uses it that way.
