### ISSUE TITLE
Interface for talk role assignment

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#373]
An interface where users with privileged control (moderator, admin, etc...) are able to assign other users to roles of power

**Comment by brian-c** [comment]
I strongly suggest we figure out how to integrate Talk roles with Panoptes roles, if not on the back end, at least on the front end. Talk is not a separate thing.

**Comment by chrislintott** [comment]
e.g Project owner assigning moderators.

**Comment by DarrenMcRoy** [comment]
Definitely the project owner should be able to convey roles; at the moment can only be done by staff/admins.

**Comment by parrish** [comment]
Just linking up issues: zooniverse/Panoptes#924

**Comment by edpaget** [comment]
https://github.com/zooniverse/Talk-Api/issues/38

**Comment by parrish** [comment]
By the way, zooniverse/Talk-Api@9f3e6f8 made roles publicly readable.
