### ISSUE TITLE
Project statistics page labels today's classifications as yesterday's classifications

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#3734]
## Expected behavior
Today's stats should be labeled with today's date. It appears that the dates are shifted by a day. Not sure how timezones complicate this labeling.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
On the project stats page, today's classifications are being labeled as yesterday's classifications.
<img width="195" alt="stats page on april 17th" src="https://cloud.githubusercontent.com/assets/7684729/25104356/960699c4-2385-11e7-98b0-f10e4952758d.png">

## Steps to replicate
See the project stats page.

## Additional information

- **Operating system:** Mac OS
- **Browser:** Chrome

**Comment by CKrawczyk** [comment]
I am not seeing this issue.  Note: I am in the GMT+1 timezone if that makes a difference.  

The timestamps are pulled off the stats server (e.g. https://stats.zooniverse.org/counts/classification/day) and converted to the local time/date using the [moment](https://momentjs.com/) package: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/stats/charts.jsx#L59-L64

**Comment by eatyourgreens** [comment]
I'm pretty sure @camallen recently updated the stats page to use UTC, rather than your browser's timezone.
