### ISSUE TITLE
when I got to the lab project details page discipline tag is empty and other tags are 1 letter

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3735]
I had filled in the discipline tag and the other other tags. It looks to still be filled in as Planet Four: Terrains is found under the space category on the projects page,but it shows up empty upon initial loading. I'm getting the same thing on Chrome and Firefox on mac. Sometimes if I reload I can get it back, but that's not  constant. I tried using my fast ethernet connection at work and get the same result for all three of my panoptes launched projects. 

<img width="1156" alt="screen shot 2017-04-17 at 10 57 47 am" src="https://cloud.githubusercontent.com/assets/753325/25104874/d87347bc-235d-11e7-96d0-d0562e49c0f1.png">

**Comment by eatyourgreens** [comment]
I get the same bug on a project I own. It's usually fixed by reloading the page, or browsing to another part of the project builder, then back to the project details. I've not been able to figure out why it's happening, other than that the API response for the tags seems to be inconsistent.

**Comment by mschwamb** [comment]
Sometimes its fixed if I reload the page, but I found more recently not always.

**Comment by mschwamb** [comment]
closing since more information now on #3897
