### ISSUE TITLE
Collections are not accessible if you are not logged in

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3736]
https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/collections/sam101502/36321

You get 'There was an error retrieving this collection.' if not logged in. The link works perfectly fine if logged in with my Zooniverse account. I'm using the latest version of mac Firefox 

It seems like non-logged in volunteers should be able to peruse public classifications or there needs to be better messaging.

**Comment by eatyourgreens** [comment]
The collection and roles are being successfully fetched from the API, but the error being thrown is `Cannot read property 'id' of null` in `canCollaborate()`, I think. So there's a bit of code somewhere that expects a logged-in user to be defined.

**Comment by srallen** [comment]
I'll check if this is an issue in #3688. We did some work there with the roles and it may already be an incoming fix.

**Comment by srallen** [comment]
Looks ok on the staged branch for #3688 and it will be merging today.

**Comment by srallen** [comment]
I think this is fixed now. Please reopen if there's still a question or issue.

**Comment by mschwamb** [comment]
It works for me not-logged in now so I think it is fixed . thanks
