### ISSUE TITLE
Color Picker for Drawing and Highlighting Tools

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#3744]
## Expected behavior
In the workflow editor, provide a color picker for drawing and highlighting tools to expand the color options. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
A tool can be assigned one of eight predetermined colors.

**Comment by CKrawczyk** [comment]
The issue of picking color-blind colors for Seabird Watch came up today. It would be nice if the drop-down presets were changed to a color-blind friendly color pallet (in addition to a custom color picker).
