### ISSUE TITLE
Update Collections Collaborator settings

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#3745]
## A few additions to the collaborator settings page
- Add the owner's username at the top of the list of collaborators, with "owner" checked and the other boxes disabled
- For other users, the checked option should be in bold
- Add an "are you sure?" modal when unchecking a user's box 

## Additional questions
How is the "Remove" button different from unchecking boxes? If it's not, please remove the button

**Comment by srallen** [comment]
Show roles on other collections and option to remove oneself.
