### ISSUE TITLE
Private messages out of sequence

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#3748]
## Expected behavior
Threads to be in chronological sequence, as I believe that this is the intended behavior. 

## Current behavior
Messages are out of sequence. For example, a message from April 25th shows up below a message from April 26th. 

I am happy to provide more information, but am hesitant to post a screen shot since I want to protect the privacy of our volunteers. I am the Project Manager for Notes from Nature, but I suspect this is not an issue specific to my project. 

## Steps to replicate
If someone wants to message me via Panoptes (@md68135) we can test this out more throughly. 

## Additional information
https://www.zooniverse.org/talk/17/311244?page=1&scrollToLastComment=true

- **Operating system:**
OS X 10.11.6

- **Browser:**
Chrome Version Version 58.0.3029.81 (64-bit)

Firefox 52.0.2 (64-bit)

**Comment by denslowm** [comment]
Perhaps this is a duplicate? See #3627

**Comment by simoneduca** [comment]
It is, thank you. Closing this one.

**Comment by eatyourgreens** [comment]
Re-opening because this is a different bug from #3627 

Also reported as zooniverse/Talk-Api#114 so feel free to close if it turns out to be a problem with the Talk API.
