### ISSUE TITLE
Can't deselect an answer to a single question, even if answer isn't required

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3753]
Found by @hughdickinson while testing #3725.

## Expected behavior

You should be able to deselect an answer to a single question while the `Required` flag is off.

## Current behavior

Answers act like radio buttons, so they cannot be deselected - so you commit to making _an_ answer, even if the subject is a known dud.

## Steps to replicate

1. Go to https://www.zooniverse.org/projects/drrogg/test-project
1. Start classifying
1. Try to deselect an answer

**Comment by eatyourgreens** [comment]
This is standard browser behaviour for radio buttons, so I'm not sure it's actually a bug.

**Comment by rogerhutchings** [comment]
That's the implementation though. The issue is that a question that doesn't need an answer is being forced to have one, and for workflows that use "no answer" as information, that's a bug because it would cause an erroneous classification :/

**Comment by eatyourgreens** [comment]
Thinking about it a bit further, I think HTML reset buttons will clear selected radio buttons, along with all other inputs in a form.

Another option would be to add 'None of the above' as an answer.

**Comment by eatyourgreens** [comment]
Info from MDN about the [reset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset) method.

[input[type=reset]](https://developer.mozilla.org/en/docs/Web/HTML/Element/input) might still be supported in browsers too.

**Comment by eatyourgreens** [comment]
[Simple test case](https://codepen.io/anon/pen/Kmqqeq) on codepen.

**Comment by rogerhutchings** [comment]
You can also achieve the same result by setting the annotation value to `null`

**Comment by rogerhutchings** [comment]
atm, in `single.jsx`:

```js
  handleChange(index, e) {
    if (e.target.checked) {
      let newAnnotation;
      if (this.props.annotation.value === index && !this.props.task.required) {
        newAnnotation = { value: null };
      } else {
        newAnnotation = { value: index };
      }
      this.props.onChange(Object.assign({}, this.props.annotation, newAnnotation));
    }
  }
```

**Comment by eatyourgreens** [comment]
What happens if you use the cursor keys to change the selected value?

**Comment by rogerhutchings** [comment]
It moves to the next value and selects it. I think in order to do deselection, moving focus would have to be decoupled from selecting an option, although that deviates from standard radio behaviour. The other alternative is using checkboxes instead.

**Comment by eatyourgreens** [comment]
Yeah, there's no keyboard shortcut defined for deselecting a radio button because you can't deselect radio buttons.

I'm curious how you'd get the change event to fire on a selected radio button without selecting another one. There's no interaction, keyboard or mouse, that deselects a radio input on its own.

**Comment by rogerhutchings** [comment]
Yeah, I found that while writing the tests. So there are two options:

- Add a `None of the above` for non-required questions (which I bet some people are doing already in required tasks), and I wouldn't be comfortable doing that without some feedback from researchers first;
- Change the underlying HTML to checkboxes

:/

**Comment by eatyourgreens** [comment]
I'd be in favour of pushing researchers to write better questions.

Changing to checkboxes allows for multiple selection, implicitly, and changes the keyboard interaction for the controls. Which means more code to then make the checkboxes act a bit like radio buttons, but radio buttons that don't quite behave the way they do elsewhere on the web.

The second option makes me nervous.

**Comment by eatyourgreens** [comment]
To clarify my first sentence: If your question is a single answer question, but not selecting an answer is also a valid answer, then you haven't actually got a single answer question any more.

**Comment by rogerhutchings** [comment]
Yeah - so the implication is "do we retire the `Required` checkbox for tasks"?

...might be outside the scope of this issue...

**Comment by eatyourgreens** [comment]
The `Required` checkbox is useful for drawing tasks and checkbox questions, and does stop you from accidentally submitting dud classifications.

The radio button task should really be for things like Yes/No questions where you have to pick an answer. On mobile, for Yes/No tasks, there's no option to not swipe right or left in order to continue.

We do also have a dropdown task that allows you to clear the selected answer, or proceed without selecting an answer.

**Comment by eatyourgreens** [comment]
Which is my long way of saying that I think radio button tasks should be `Required` by default.

**Comment by srallen** [comment]
I think I agree with requiring radio button tasks by default and with guiding project builders to build better tasks. There's ambiguity with allowing a null answer: is it an accidental submission or is it a meaningful answer? Making it required and guiding project builders to have an explicit "None of the above" as an answer is more clear on the intention.

**Comment by rogerhutchings** [comment]
We could go a step further and disable the `Required` checkbox for _single_ tasks, and therefore always requiring an answer (along with a help field suggesting a "None of the above" answer)? With all of the above, I can't think of a reason to keep it for this particular task.

**Comment by eatyourgreens** [comment]
FWIW the first question on penguinwatch.org is Yes/No with Yes selected by default. Reasoning being, people were accidentally pressing Done and null submits a no penguins classification. If they accidentally submit Yes, they can go back and correct their answer. 

I think that's another argument for forcing people to choose a definite answer before continuing.

**Comment by eatyourgreens** [comment]
Closing this because I don't think we should be rewriting standard browser behaviour for radio buttons.
