### ISSUE TITLE
Allow feedback in classifier to be shown in a specified subject frame

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3763]
For multi-frame subjects, you should be able to specify which frame drawing feedback will appear in.

cc #3725 @aprajita

**Comment by eatyourgreens** [comment]
Perhaps the summary should flip the subject to the default frame, if one is specified in the subject metadata.

**Comment by eatyourgreens** [comment]
NB this might be easier if we redesign the classifier component hierarchy so that the subject is a child of the task, not a sibling. That way, the task components can pass props down to the subject to change how it displays.

**Comment by eatyourgreens** [comment]
Linking this to #3858
