### ISSUE TITLE
Facebook: posted project URLs show up as zooniverse.org rather than project info

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3766]
## Expected behavior

This may be deliberate, in which case just let me know. But it seems that when you post a project URL on facebook, the assets that come up should be about that project, rather than the broad Zooniverse.org asset. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

![screen shot 2017-05-05 at 9 01 57 pm](https://cloud.githubusercontent.com/assets/4975655/25769064/60562ed4-31d6-11e7-8977-a703d13ab3ab.png)

## Steps to replicate

Post a comment in facebook that includes a project URL (e.g., arizonabatwatch.org). 

## Additional information

Ever since the girls were born, I very rarely use Facebook. The research lead for arizonabatwatch pointed out this behavior to me in a call yesterday. Just let me know if this is deliberately done this way. 

The Batwatch lead says that the same behavior occurs in emails for her (she uses Outlook). I haven't been able to replicate this (Adler outlook doesn't pop out URLs in this way), but here's the screenshot she shared with me. 

![email preview](https://cloud.githubusercontent.com/assets/4975655/25769099/1ff59004-31d7-11e7-827a-f60f8c0cc732.jpg)

Assigned @rogerhutchings only because you've done work with Zooniverse in facebook. Just post if would be good to reassign. 

- **Operating system:**
mac os 10.12.4

- **Browser:**
Chrome v58

**Comment by trouille** [comment]
Also pinging @mrniaboc as you may have opinions/experience with this.

**Comment by eatyourgreens** [comment]
Duplicate of #2107

Not specific to Facebook. You'll notice that the same preview shows on Slack posts too. It's a side effect of zooniverse.org only being one actual web page. Project 'pages' are actually views generated by JavaScript.

**Comment by rogerhutchings** [comment]
We might be able to override it with React Helmet - I'll give it a go.

**Comment by eatyourgreens** [comment]
Any solution would require us to publish a HTML page, or some other parsable resource, at the project URL. At present, those URLs resolve to https://www.zooniverse.org/index.html, which then downloads the PFE JavaScript to your browser, which then requests the project from the API and renders the appropriate project page.

Facebook's crawler (and the crawlers used by other web services) doesn't execute JavaScript in the pages that it downloads, so it just downloads that one HTML page for every URL we publish.

**Comment by trouille** [comment]
If I needed to fix this for just one project (i.e., arizonabatwatch.org = https://www.zooniverse.org/projects/zooniverse/arizona-batwatch/), would that be more feasible/less effort? Or would finding the simplest solution for just this one project URL be the same amount of work as finding a generalized solution for all? 

The context for this question is that we received NSF funding to help the arizona batwatch group launch their project. This is a final sticking point that really bothers the research lead. I'm wondering whether there's a simple solution in the context of just that project.

**Comment by eatyourgreens** [comment]
Sorry, but this is technically impossible with the current infrastructure, where PFE is a single page app.

**Comment by trouille** [comment]
OK, good to know. Thanks @eatyourgreens and @rogerhutchings for your responses. Helps in my ability to respond to the researcher.

**Comment by rogerhutchings** [comment]
related: #2862
