### ISSUE TITLE
Enable private boards

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#378]
- Moderators-only for v1.0, and then add an invitation system later
- Perhaps display them as a separate view so they do not get lost in the mix

**Comment by parrish** [comment]
Just a heads up, I overhauled the permissions in zooniverse/Talk-Api#37

If you run into any problems here, just reopen that issue.

**Comment by aweiksnar** [comment]
Looks like people are using private boards effectively
