### ISSUE TITLE
The browser's back button does not work after navigating to the /projects page

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#3784]
## Expected behavior
The browser's back button will always work regardless of what page you are on.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
When navigating to the `/projects` page the back button no longer works.

## Steps to replicate
1. Go to the signed out home page
2. Click "Get Started"
3. Click the browser's back button

## Additional information
It looks like the URL parameters are cleared when back is pressed, and then automatically re-set.

- **Operating system:**
OSX
- **Browser:**
Tested in Chrome and Firefox

**Comment by eatyourgreens** [comment]
Probably caused by the history update here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/projects/index.jsx#L68

**Comment by eatyourgreens** [comment]
Pinging @simoneduca who worked on this to filter projects by live status.

**Comment by eatyourgreens** [comment]
Playing around with this on my phone, whenever you enter the projects page, `/projects` is added twice to your history, instead of once.

**Comment by CKrawczyk** [comment]
I think changing that line from `browserHistory.push` to `browserHistory.replace` will solve the issue.

**Comment by eatyourgreens** [comment]
I think that will break the back button further by overwriting history when you use the Paused or Finished links.

**Comment by CKrawczyk** [comment]
Good point.

**Comment by eatyourgreens** [comment]
Confirmed that when you navigate to `/projects`, it redirects to `/projects?status=live`.

Pressing back takes you back to `/projects`, which immediately redirects you to `/projects?status=live`, and you can never leave the page 😱

**Comment by simoneduca** [comment]
Having a look now.

**Comment by eatyourgreens** [comment]
@simoneduca I tracked it down to a method called `checkURLForStatusFilter` so I've taken that out in #3787.

**Comment by simoneduca** [comment]
Cool, thanks! I wonder why Rog thought that was needed though... I seem to remember if status wasn't defined in the address, something strange happened. I can't reproduce that, so your PR is good. We'll see anyone yell afterwards.

**Comment by eatyourgreens** [comment]
All it was doing, as far as I could tell, was adding `class=active` to the selected button. Setting a default value in the `StatusLink` component does the same thing.
