### ISSUE TITLE
Workflow visualizer is broken for workflows that have tasks

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3785]
## Expected behavior
Workflow visualizer works for all kinds of workflows.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The visualizer only works for workflows that don't have defined tasks yet. For workflows with tasks, the page doesn't load and there are several type errors in the javascript console: `TypeError: Cannot read property '_currentElement' of null`

I'm not sure how long this has been broken and since we haven't had any complaints from project builders, we may want to think about if this feature is being used. I started to look through the code, but I'm not sure at which point it is breaking. @CKrawczyk if you have time to take a look, it may be more obvious to what is breaking.

## Steps to replicate
Browse to a workflow that has tasks in the lab. Click on the visualizer button. 

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
I had a quick look earlier, on a local copy of PFE, and the error is being thrown on line 257 of the `Task` component. From the error message, I would say that a require is returning an object instead of a React component.

**Comment by srallen** [comment]
That's the line where `<Resizable />` is being used and depends on `react-component-resizable` so maybe that dependency is broken.

**Comment by CKrawczyk** [comment]
To be honest this visualizer component could really use a refactor.  It was the very first thing I wrote in React, so there is quite a bit of "bad practices" going on within it.

Also parts of it are over complicated since my original idea was to have the visualizer also work (to a certain extent) as a workflow editor, i.e. being able to draw connections between tasks to set the workflow order.

**Comment by srallen** [comment]
@CKrawczyk considering this may have been broken for at least a little while and no one noticed, would you prefer that we just hide the button from the workflows editor page for now?

**Comment by eatyourgreens** [comment]
Fix for this bug is pretty small, by the way:
`Resizable = require('react-component-resizable').default`
