### ISSUE TITLE
If subject doesn't have any hashtags associated with it a 0 shows up on the subject page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3791]
If a subject has no talk hash tags associated with it on the talk page in the section where the associated hashtags with the subject image would be listed you see a 0. 

<img width="1107" alt="screen shot 2017-05-13 at 8 39 59 pm" src="https://cloud.githubusercontent.com/assets/753325/26031866/a05ce3da-381e-11e7-85cc-81614827103d.png">

a subject that already has tags associated with it:

<img width="1110" alt="screen shot 2017-05-13 at 8 40 22 pm" src="https://cloud.githubusercontent.com/assets/753325/26031875/e97879f8-381e-11e7-9f8b-74aae25a2aee.png">

**Comment by mschwamb** [comment]
The zero doesn't make sense, so I think it would be nice if someone made this fix at some point.

**Comment by eatyourgreens** [comment]
Looks like a good candidate for `help wanted`.
