### ISSUE TITLE
Populate talk sidebar with interesting content

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#380]
- Links to interesting discussions happening in zooniverse-wide talk
- Latest hashtags
- Any data available
- Dropdown menu, linking to other project talks

**Comment by parrish** [comment]
Worth mentioning a few endpoints to support this

##### [Popular tags by section](https://talk-staging.zooniverse.org/tags/popular?section=zooniverse&limit=5)

https://talk-staging.zooniverse.org/tags/popular?section=zooniverse&limit=5

    {
      "tags": [
        "testing12",
        "test",
        "tag",
        "mytag",
        "hashtag"
      ]
    }

------

##### [Activity by project channel subscriptions](https://notifications-staging.zooniverse.org/presence)

https://notifications-staging.zooniverse.org/presence

    [
      {
        "channel": "project:testing",
        "count": 1
      },
      {
        "channel": "zooniverse",
        "count": 1
      }
    ]

------

##### [Active user ids per channel](https://notifications-staging.zooniverse.org/active_users?channel=zooniverse)

https://notifications-staging.zooniverse.org/active_users?channel=zooniverse

    [
      "1",
      "2",
      "3"
    ]

**Comment by aweiksnar** [comment]
Sweet! Those look perfect

**Comment by alexbfree** [comment]
Another idea - how about most favourited subjects... or recently commented.

With the tags, can we make them click through to a search?

**Comment by aweiksnar** [comment]
Closing this up since we've got a handful of things in there, and then we can entertain requests as separate issues
