### ISSUE TITLE
Request for audio file (.mp3) subject support.

### ISSUE THREAD

**Issue by hughdickinson** [zooniverse/Panoptes-Front-End#3809]
## Expected behavior
The project builder and/or Python client will accept .mp3 format subjects and the subject viewer will "render" them appropriately using the HTML5 audio player.

## Current behavior
Not implemented.

**Comment by eatyourgreens** [comment]
Rendering audio files is a pretty small change. Just add an audio player component and register it for audio files in the [FileViewer](/zooniverse/Panoptes-Front-End/blob/master/app/components/file-viewer/index.jsx).

**Comment by mcartwright** [comment]
Hello, I am very much looking forward to this feature. I just wanted to add that it would be great if this supported the display of an image (e.g. a pre-computed spectrogram as in BatDetective and WhaleFM) along with the audio. Is that possible? Thanks!

**Comment by hughdickinson** [comment]
Reopened issue to include association of a spectrogram image with the audio track.

**Comment by trouille** [comment]
I’m trying to help Yunpeng Li (Oxford student) to upload .mp3 files (+ spectrograms, if possible) for his project: https://www.zooniverse.org/lab/4846

From
https://github.com/zooniverse/Panoptes-Front-End/pull/3863
and https://github.com/zooniverse/Panoptes-Front-End/pull/3878
and https://github.com/zooniverse/Panoptes/pull/2376
I had thought this meant that .mp3 were now accepted files. 

When I try to upload directly through the project builder (both in admin mode and not), I get this error:

![screen shot 2017-09-04 at 7 34 46 am](https://user-images.githubusercontent.com/4975655/30026717-c1b64c78-9143-11e7-8748-1732074b689a.png)
![screen shot 2017-09-04 at 7 34 24 am](https://user-images.githubusercontent.com/4975655/30026718-c1b66cd0-9143-11e7-9fd4-9855d856cf80.png)


When I try with panoptes-cli:

panoptes subject-set upload-subjects 14536 manifest.csv

I get the error:
Could not find any files in row:
1,Class0_1.mp3,0

This is a screenshot of the manifest. It's from https://drive.google.com/drive/folders/0Byt3YVnPxRRbR3RiM2ljdGRkcE0 - Yunpeng’s test data for this project; currently just the audio files (not the spectrograms as well yet). 

![screen shot 2017-09-04 at 7 37 46 am](https://user-images.githubusercontent.com/4975655/30026765-f4dfe78a-9143-11e7-828b-a6b5fcfd44d0.png)

When I try with the Panoptes Python Client and the script at [this link](https://drive.google.com/file/d/0BzeL_TYT7IYPTklzZU1qalROSXc/view?usp=sharing), I get the error:
panoptes_client.panoptes.PanoptesAPIException: Validation failed: Locations is invalid

(Note: I get these same errors if I try to upload .mp4s. I have no problem uploading .jpg or .gif using these routes). 

Also note: https://github.com/zooniverse/panoptes-subject-uploader works like a charm for .mp4s, but not for .mp3s. 

Tagging @hughdickinson and @eatyourgreens and @camallen

**Comment by eatyourgreens** [comment]
The subject page in PFE supports mp3, see [line 16 of the subject set page](/zooniverse/Panoptes-Front-End/blob/master/app/pages/lab/subject-set.cjsx#L16)

I don't know why Panoptes is rejecting the files in admin mode, but I'm not sure that this is a PFE issue.

**Comment by srallen** [comment]
I'm going to close this in favor of more specific issues. #4029 is about the MIME type issue in Chrome. Please open a separate issue for spectrogram support. MP3s are currently supported. It's easier for us to keep track of issues if they're kept separate. Thanks.
