### ISSUE TITLE
Wrong error message on username input during registration

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#3812]
## Expected behavior
According to the current error message, `.` and `,` should be allowed.

## Current behavior
![pasted image at 2017_05_18 05_50 pm](https://cloud.githubusercontent.com/assets/8989606/26215855/cb3c65d8-3bf9-11e7-8452-0567ee055618.png)

## Steps to replicate
Input username and type either `.` or `,`.

**Comment by rogerhutchings** [comment]
closed via #3813
