### ISSUE TITLE
Live Workflow statistics not showing

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#3815]
## Expected behavior
Statistics page should show information for all Live Workflows (ones with "Show on Stats Page" checked on the Visibility Project Builder page)

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

No statistics are shown. No error message, just a blank area where statistics are usually presented.

![statsissue](https://cloud.githubusercontent.com/assets/2152565/26248450/b75a3eda-3c5f-11e7-9930-c9b3d330f1a8.jpg)

## Steps to replicate
got to:
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/stats?_ga=2.149476598.1979556249.1495198868-301989501.1485808297

## Additional information

- **Operating system:**
OS X 10.11.6

- **Browser:**
Chrome Version 58.0.3029.110
FireFox 53.0.2

**Comment by camallen** [comment]
This is related to the ETC refactor work i did, i'll look into it.
