### ISSUE TITLE
Disabling volunteer ability to download video subjects

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3818]
## Expected behavior

Certain research teams would prefer not to showcase the ability to download their video subjects (e.g., Arizona Batwatch and their data providers from the Arizona mine). Can we allow research teams to disable the video download icon for their project?  

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

See the download icon in the lower right under the video. 
![screen shot 2017-05-19 at 3 00 31 pm](https://cloud.githubusercontent.com/assets/4975655/26264858/f58f189e-3ca3-11e7-82ae-83efbe88a37b.png)

## Additional information

- **Operating system:**
- **Browser:**

**Comment by trouille** [comment]
Note: a person can right-click on an image or video and download it. It may be that I should just have a follow up conversation with the research lead and let her know that that is just internet reality (that you can download subjects). I can do that. But wanted to ask the question here and see if there was a way to be responsive to this researcher's request to not showcase that you can download video subjects. Thanks!

**Comment by eatyourgreens** [comment]
Chrome should be making this optional in a future update. I don't think Firefox shows it at all. 

@stallen has a hack that she used on Chimp & See to hide this in current versions of Chrome.
