### ISSUE TITLE
Collections – adding multiple subjects to a collection causes an error message?

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#3821]
## Expected behavior
Select multiple subjects and add to an existing collection

## Current behavior
From [Talk](https://www.zooniverse.org/talk/14/295770?comment=559967):
>I observe that if I select all items on a screen to add to a collection, most recently I am getting an ugly message that an / some items are already part of the collection and the process fails. 1) I don't reckon the images are part of the collection so I think the error message is not true. 2) Maybe this message is being generated because the collection is already quite large. If I go through the images one at a time, they generally add to the collection okay. 3) If the images are part of the collection, couldn't the process be smart and assign to the collection the images not already added?

**Comment by camallen** [comment]
Ultimately this is an api issue, we ensure uniqueness of the subjects in the collection (imagine if we didn't and this use case of adding allowed it). We could skip this validation or strip it when adding but it adds overhead to the add action. 

Anyway we can signal that the image is already in the collection in the UI to avoid double submissions?

**Comment by srallen** [comment]
Yeah, I think this can be solved in the UI with improved error messaging and allow other subjects to continue to be added in the bulk action.
