### ISSUE TITLE
The Need For Speed: opt out of "end of classification" step?

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Panoptes-Front-End#383]
We'd like to emulate Space Warps' high speed classification system, which is basically a drawing workflow with no "end of classifications step". The link to the subject's Talk page would be available throughout the classification step, in order to enable one-click rejection of boring subjects. In a rare object search we want to be able to do something like:

Next! Next! Next! Next! Next! Next! Next! Next! Next! Ooh, click on that - now, Next! Next! Next! etc

cc: @aprajita, @anupreeta27

**Comment by aliburchard** [comment]
Going to close this as this is implemented with experimental "skip summary" feature. (With the acknowledgement that we do need a better long-term solution than the Done and the Done & Talk buttons)

**Comment by aprajita** [comment]
Hi @aliburchard thanks for this - where do I find the "skip summary" option in project builder? It doesn't appear as an option in the workflow.
thanks @aprajita

**Comment by aliburchard** [comment]
It's still experimental, so needs to be enabled by and admin. You can ping @mrniaboc or me with your project url and we can sort that out.

**Comment by aprajita** [comment]
thanks @aliburchard, I did send a message through slack to you both. Whenever @mrniaboc or you have a minute to implement that, that would be great - thanks very much!!
https://www.zooniverse.org/lab/1434/workflow/960 
I've added you both as collaborators in case that's needed to enable this.
