### ISSUE TITLE
Done & Talk button showing in TaskNav for GS feedback

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#3836]
cc @rogerhutchings 

## Expected behavior
Done & Talk only shows for the workflows with skip classification summaries setting and not for subjects that have custom feedback.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
<img width="528" alt="screen shot 2017-05-30 at 3 22 33 pm" src="https://cloud.githubusercontent.com/assets/5016731/26603823/d2f11ad2-454d-11e7-9512-94ed3ddad814.png">
Done & Talk button showing for the custom summary message. This should not be appearing because the click handler for this button will try to submit a classification if clicked. When this custom summary shows, the classification is already submitted.

Regression from #3824 fixing the regression introduced from the new feedback feature. 
I don't think this affects any other projects.

## Steps to replicate
Can be seen in this test project: https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/gravity-spy-gold-standard-notice-test-project/classify

## Additional information
We could try to fix this as is, but I don't think this is that straight forward since the task nav doesn't know the summary is showing. Tweaks to include the Gravity Spy configuration into the `disableTalk` variable in the task nav basically just broke it how it was before #3824. I'm thinking using the feedback store would be the only way to intelligently tell the nav when to show the Done & Talk button. With that in mind I'd prioritize getting Gravity Spy on to the new feedback feature rather than try to fix the nav to work with the project specific code written for GS.

**Comment by eatyourgreens** [comment]
Checking for `!completed` on [Line 170](/zooniverse/Panoptes-Front-End/blob/master/app/classifier/task-nav.jsx#L170) might be a quick fix for this too.

**Comment by srallen** [comment]
Doh! I missed that. I'll give that a try.
