### ISSUE TITLE
Survey task  editor doesn't reflect loaded and applied questions csv

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#3839]
## Expected behavior
When you load the questions csv into the survey task editor (and apply it), the text on the button changes from "Add Questions" to "Replace Questions" and the warning message that you're missing a questions file should disappear.

## Current behavior
I've loaded and applied a questions csv to https://www.zooniverse.org/lab/2980/workflows/4250. The button still reads "Add Questions" and I still receive a warning that I have no questions. Oddly, the questions do indeed display when testing out the task, it just seems that the survey editor does not reflect this. 
![screen shot 2017-06-01 at 9 53 50 am](https://cloud.githubusercontent.com/assets/6217406/26672462/2d996386-46b1-11e7-8c30-0ddae3286af4.png)

## Steps to replicate
Load a choices csv and a questions csv into a survey task.

## Additional information

- **Operating system:** OS 10.12.5
- **Browser:** Chrome

(@mcbouslog not sure if this goes to you or someone else. It's not urgent and the thing still works, but it is confusing.)

**Comment by mcbouslog** [comment]
I'll certainly take a look. Is this using the [SampleProject](https://drive.google.com/drive/folders/0BxNFAhD71pdXZ3BZdnd3QzdVU0k) CSVs? If not, could you share the CSVs you're using with me? Thanks,

**Comment by CKrawczyk** [comment]
Might be related to https://github.com/zooniverse/Panoptes-Front-End/issues/3746
