### ISSUE TITLE
Free text tool

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#384]
Hey @brian-c it would be great to have a free text tool. This would open up possibilities for all sorts of new projects and I think would be key to lots of disciplines in science, humanities and so on. If it were possible for this to be in place before July, that would be great. I'm teaching a workshop using Panoptes that month.

**Comment by mkosmala** [comment]
Seconded.

**Comment by srallen** [comment]
Free text tool exists now.
