### ISSUE TITLE
Combo task editor breaks if you delete tasks from the workflow

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#3840]
## Current behavior
I was struggling with trying to build a combo task and deleted all the tasks within this workflow: https://www.zooniverse.org/lab/2980/workflows/4236

Now when I click into the workflow from the builder, nothing displays:
![screen shot 2017-06-01 at 11 34 01 am](https://cloud.githubusercontent.com/assets/6217406/26676097/510b3274-46be-11e7-8e2e-1d6d107c8d1e.png)
![screen shot 2017-06-01 at 11 22 46 am](https://cloud.githubusercontent.com/assets/6217406/26676212/bcbb4504-46be-11e7-8a8f-ca700a14c2c6.png)

When I click out of that workflow (by clicking on "Workflows" on the left), the list of workflows reappears, but clicking on them does navigate into them. The items on the left hand menu-bar still work, and I can navigate there.

## Steps to replicate
@simoneduca and I have tried replicating the issue by deleting all tasks in other workflows, but can't seem to. The issue is still present in this particular workflow - happy to add anyone as a collab if you want to explore.

## Additional information

- **Operating system:** OS Sierra
- **Browser:** Chrome

**Comment by eatyourgreens** [comment]
From the error, [this line in the combo task](/zooniverse/Panoptes-Front-End/blob/41faaf9031d8caacff158d3c9ebf636890347e5b/app/classifier/tasks/combo/editor.cjsx#L36) is returning `TaskDescription` as undefined.

**Comment by simoneduca** [comment]
@eatyourgreens I've been failing to reproduce and to get `TaskDescription` to return `undefined`. Not sure what's going on.

**Comment by eatyourgreens** [comment]
@simoneduca have a look at that workflows contents in the network panel. Specifically `workflow.tasks`, I think.

Adding a check for undefined in that component method should at least allow you to debug this without the error, which crashes the project builder.

**Comment by simoneduca** [comment]
I've just reproduced it. Let me see if I can do it reliably and then I'll write a fix.

**Comment by simoneduca** [comment]
So, to reproduce the bug:
1. add any task
2. add a combo task
3. add the first task to the combo task
4. delete the first task
5. click on the combo task and the editor will crash

To fix this, I'll add a check following Jim's earlier suggestion.

**Comment by eatyourgreens** [comment]
I've updated the issue title to reflect the actual bug here.

**Comment by eatyourgreens** [comment]
I think the fix for this is to add a `componentWillReceiveProps` method that looks for changes in `props.workflow.tasks` and removes keys from `props.task.tasks` if they've been deleted from the workflow.

**Comment by simoneduca** [comment]
On it :)

**Comment by simoneduca** [comment]
@eatyourgreens I'm probably doing something wrong, but adding a check for removed tasks in `componentWillReceiveProps` doesn't seem to help https://github.com/zooniverse/Panoptes-Front-End/commit/daf2b9e24b5ec6dcbdcbaef9df4679b6fce5fd9e

**Comment by eatyourgreens** [comment]
@simoneduca that commit doesn't check the workflow to see if any tasks have been deleted.

I'm writing a test to reproduce the bug. Should be up shortly.
