### ISSUE TITLE
Add feedback support for other drawing tasks using test-shape-closeness

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#3844]
https://github.com/zooniverse/test-shape-closeness

**Comment by lcjohnso** [comment]
Hi @rogerhutchings --

Following up on your excellent work in PR https://github.com/zooniverse/Panoptes-Front-End/pull/3725, I'm very interested in feedback support for circle and ellipse marker types for use in star cluster finding projects (e.g., Andromeda Project).

Will extending feedback support to circle and ellipse marker types require `test-shape-closeness`? Point, circle, and ellipse markers are all compatible with the current `isWithinTolerance` function that is based on the marker center -- perhaps there is a quicker/easier way to add support for circles/ellipses than `test-shape-closeness`?

I'm happy with point-like representation of the success/failure marking (via feedback-point.jsx) for all three marker types with (x, y, r) set by (x, y, tol).

**Comment by srallen** [comment]
Commenting to keep this fresh. We'll still need to do this for feedback.
