### ISSUE TITLE
Site hangs on submit of Create Discussion

### ISSUE THREAD

**Issue by jelliotartz** [zooniverse/Panoptes-Front-End#3849]
## Expected behavior
Create a new discussion

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Site hangs after hitting `Create Discussion` button

screenshot:
<img width="1440" alt="create-discussion-hang" src="https://cloud.githubusercontent.com/assets/12473119/26728285/5f0ec0aa-476f-11e7-8fb3-38cd7ffe16bd.png">

## Steps to replicate
1. classify a subject
2. click "done"
3. click "talk"
4. click "start a new discussion"
5. enter "discussion title" and body text
6. click "create discussion"

## Additional information
First reported in Talk: https://www.zooniverse.org/talk/17/353455

- **Operating system:**
OS X 10.12.4

- **Browser:**
Chrome 58.0.3029.110

**Comment by eatyourgreens** [comment]
When I try this on a test project, that I own, the form also has radio buttons to select a discussion board
![Screenshot of the new discussion form, showing a radio button to select a board](https://cloud.githubusercontent.com/assets/59547/26729985/623f6044-47a7-11e7-9603-6dfe77f69efc.png)

**Comment by eatyourgreens** [comment]
No problems here [starting a new discussion for a subject](https://www.zooniverse.org/projects/hughdickinson/galaxy-nurseries/talk/935/354045?page=1&scrollToLastComment=true) but maybe you have to wait for that list of boards to come back from the API before you can submit the form?

**Comment by jelliotartz** [comment]
I don't see a list of boards on the project the issue came from - ie, no radio button like the one labeled `test` in your screenshot @eatyourgreens. Could that be part of the issue?

<img width="1440" alt="create-discussion-hang2" src="https://cloud.githubusercontent.com/assets/12473119/26734723/b3dab7be-4784-11e7-965f-c5e2992a0f74.png">

**Comment by eatyourgreens** [comment]
Could be. A new discussion would have to be posted to a board, so that's where I'd start looking to debug this.

**Comment by eatyourgreens** [comment]
I think the relevant code is the [`updateBoards` method](/zooniverse/Panoptes-Front-End/blob/master/app/talk/discussion-new-form.cjsx#L30-L38) in the `DiscussionNewForm` component.

**Comment by jelliotartz** [comment]
Thanks! I'm at Mozilla Global Sprint today, if it's a pressing issue that needs attention immediately, I'm happy to pass it on, otherwise I'm happy to take a stab at it on Monday.

**Comment by trouille** [comment]
Good to see this. Not a high priority for this week, but it's on the radar for the next maintenance week.
