### ISSUE TITLE
Space Warps Generalised Feedback Issues

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#3858]
## Expected behaviour

Generalised feedback messages expected to behave differently for
- SIM success & missed
  - appear at sim marker location
  - default messages overridden by metadata
  - with multiple images showing and clone markers on only expect one to contain feedback message

- DUD success & missed
  - would be nice to have a pop-up message like in SIM at the centre of the image for no marker placed (i.e. success), and at the location of the marker for missed SIMS. users will be expecting and probably would only register the same kind of message for duds as for sims especially for a fast 

## Current behaviour
- messages appear at strange locations
- both default and metadata messages appearing together
- dud messaging only in classification summary text, request pop-up messages for duds
- with clone marker on, all images show feedback, only one should be enough for this setup

![image](https://user-images.githubusercontent.com/1917970/26974704-75c5b646-4d14-11e7-9645-f5e399bdd2de.png)

## Steps to replicate
@rogerhutchings please try out workflow https://www.zooniverse.org/projects/aprajita/swdemo/classify?reload=0&workflow=4257

## Additional information

- **Operating system:**
mac os x yosemite v10.10.5
- **Browser:**
Chrome Version 58.0.3029.110 (64-bit)

**Comment by aprajita** [comment]
Hi there
would @rogerhutchings or anyone else (@srallen?)  have time to take a look at this please?
Many thanks
Aprajita.

**Comment by aprajita** [comment]
Here are a few more images of what feedback in the SW demo:

For sims/LEN types both default and metadata feedback is being displayed even though the PFE says that the metadata feedback overrides the defaults, and you have to input defaults when setting up the classification in the project builder.

The times when you see conflicts (i.e a default fail (lf) and a positive metadata message) arise when the default radius (a single value) differs from the varying radii in the metadata. Ensuring the defaults are overriden will sort out the problems.

Duds seem to work the right way but it would be nice if that was a pop-up message like the sim/LEN messages.


below are examples for LEN success (marker within tolerance), LEN fail (no marker or outside tolerance), DUD success (no marker placed) and DUD fail (marker placed anywhere)


**success sim (LEN)**
![image](https://user-images.githubusercontent.com/1917970/28820500-ca1e3d30-76a9-11e7-8874-8fcacf51be9d.png)
![image](https://user-images.githubusercontent.com/1917970/28820512-d35168b4-76a9-11e7-84a8-f61b8b84bb1f.png)

**failed sim (LEN)**
![image](https://user-images.githubusercontent.com/1917970/28820564-0b086bea-76aa-11e7-947b-dbfb51322299.png)


success dud
![image](https://user-images.githubusercontent.com/1917970/28820582-1bff10c0-76aa-11e7-9811-31a79ba6f3e4.png)

failure dud
![image](https://user-images.githubusercontent.com/1917970/28820603-2b218c36-76aa-11e7-900e-6d2c5fd34591.png)

**Comment by srallen** [comment]
@aprajita @rogerhutchings is on parental leave at the moment for six weeks, so the feedback feature is on pause at the moment. Thank you for sharing details on what needs following up and we'll get to it as soon as we can.

**Comment by simoneduca** [comment]
@aprajita I will be able to pick this up this week.

**Comment by simoneduca** [comment]
@aprajita apologies for the delay on this. I'm still working my way through what the code actually does, but I should be able to share some progress soon.

**Comment by simoneduca** [comment]
I'm tackling the wrong display positions of tooltips. 

1. The negative sims feedback object doesn't have any coordinates and I think that's why they're displaying in the incorrect position.
2. Sims metadata object does have coordinates, but the values seem wrong.

**Comment by aprajita** [comment]
OK thanks Simone.

i think the negative feedback position should default to the centre if no
marker has been placed, and be located at one of the markers if incorrect
marker(s) have been placed.

**Comment by simoneduca** [comment]
Unfortunately I can't replicate the behaviour of the metadata tooltip consistently. Sometimes it seems to be in the correct place, see screenshot.
Still looking for a solution for the SIMs feedback.
![screen shot 2017-08-16 at 11 32 11](https://user-images.githubusercontent.com/8989606/29359478-bd4d8c7c-8276-11e7-9e26-c77887909a4e.png)

**Comment by simoneduca** [comment]
@aprajita what would the correct position for a tooltip be?
- [ ] anywhere on the marker circle
- [ ] anywhere inside the marker circle area?
- [ ] on the spot where the marker was placed?

**Comment by simoneduca** [comment]
Sorry just answered my own question by going back to your first comment.

**Comment by aprajita** [comment]
Apologies for not replying sooner Simone. I was offline until today.

Was your question regarding at the location of the tooltip feedback for the
duds or for the sims/lenses?

Can i also discuss options for a better defined locus for the lensed
images. In the original space warps we had a mask (an image the same size
as the training image) hat was used to test if a marker was successful or
not. This mask has 0s where there was no image flux, and 1s where there
was. I discussed this a while back with marten and roger but not sure if we
could see a way this could be implemented. As the lensed images are rarely
circular the x,y,tol doesn't well describe the image locations. Do think
that there may be a way to use such a mask to check for success or failure
on  a training image?

Many thanks for looking into this.

Aprajita.

**Comment by simoneduca** [comment]
@aprajita either of them, I think. 

Re. your second question: I don't feel I know enough about SW to answer your question tbh, but it's worth opening a new issue about it - perhaps label it as 'enhancement' - and explain exactly what your suggestion is.
Apologies for not being more helpful.

**Comment by simoneduca** [comment]
Marten gave me a bit more background to your question about using a mask. Unfortunately, PFE can't do that yet and there's no current on plan on adding support for a second image.

**Comment by aprajita** [comment]
ok thanks simone

i think for the
sims/lenses
success or fail should appear at the location of the first correct mark
placed
fail, appear at the first x1,y1 image identified in the manifest with a
small offset so that the image can be seen

duds
success - no makrer placed - centre of image
fail - marker placed, location at the first marker placed

hope this is OK.

thanks!

**Comment by aprajita** [comment]
Thanks for asking marten simone

just to check, are only centres plus a tolerance in a radial sense the only
way to specify "good" regions for marker then, or can you specify
rectangles and/or ellipses too?

thanks

**Comment by simoneduca** [comment]
Rectangles and/or ellipses can be implemented. But I don't know when we'd be able to do that. Let me get back to you after I speak with @rogerhutchings

**Comment by aprajita** [comment]
OK great, thanks very much @simoneduca

**Comment by simoneduca** [comment]
@aprajita would you mind opening an issue, add the enhancement label to it and detail all your new requirements regarding the implementations of new shapes? That would help me to better plan any work needed. Thanks.

**Comment by simoneduca** [comment]
Also @aprajita regarding the current issue. Has anything changed in the workflow? I don't seem to be able to get feedback to display anymore.

**Comment by aprajita** [comment]
sure, no problem!

**Comment by aprajita** [comment]
i havent made any cahnges recently, let me  check and i'll get back to you.

**Comment by aprajita** [comment]
I don't see any feedback either. i havent changed the workflow and the feedback says it it still enabled.
https://www.zooniverse.org/lab/1434/workflows/4257

![image](https://user-images.githubusercontent.com/1917970/29560641-915e332e-872a-11e7-9fd5-48564f247a31.png)

**Comment by aprajita** [comment]
the training images are listed as LEN or DUD in the manifest
![image](https://user-images.githubusercontent.com/1917970/29561114-39e5f3c8-872c-11e7-9a0e-64c85fc66099.png)

**Comment by simoneduca** [comment]
I'm not sure what is going.

**Comment by aprajita** [comment]
ok, shall i start a new wrokflow and see if that works?

**Comment by simoneduca** [comment]
Let's try that.

**Comment by simoneduca** [comment]
Any joy @aprajita? I still can't see feedback.

**Comment by eatyourgreens** [comment]
I've had a look at the existing workflow. The feedback is there in the subject metadata, so the workflow is fine. Here's a screenshot where I've clicked in roughly the right place, according to the metadata numbers, but I haven't received a feedback message.

![Space Warps screenshot showing a subject with feedback metadata, but no feedback shown.](https://user-images.githubusercontent.com/59547/29625567-fd1cc202-8823-11e7-9837-c545bf84e91c.png)

Could the `if` statement added in #3993 have turned off feedback for all subjects?

**Comment by aprajita** [comment]
Sorry haven't had chance to do it yet, but will shortly.

**Comment by eatyourgreens** [comment]
Ignore my last comment. I can see feedback metadata on subjects at https://www.zooniverse.org/projects/aprajita/swdemo/classify too, but no feedback is showing up when I finish a classification.

So my best guess is that a recent change to PFE has somehow turned off the feedback messages. 😞

**Comment by aprajita** [comment]
hi @simoneduca 

I've made a new workflow where feedback shows up but it still shows the conflict between the defaults and the metadata feedback

here's a screen shot:
![image](https://user-images.githubusercontent.com/1917970/29627111-e83a9738-8828-11e7-965a-2377e378d84f.png)

There defaults are not being overridden by the presence of metadata it seems. Even if the defaults are not being overidden, It's also not clear why the LEN Fail message appears when the marker is well within the default tolerance.

Also I am confused by one of the options in the default feedback "No markings
Check this box if there should be no annotations on this feedback type (also known as a dud)."
There should be no annotations in the case of a success message for a dud, and marking for a fail, so I think this is confusing.
In the case of sim, no markings would be a fail, and markers in the wrong places would also be a fail so I am not sure this is a clear instruction on whether this box should be clicked or not.


Hope this helps!

Aprajita.
PS offline again for a while now.

**Comment by aprajita** [comment]
sorry here's the new workflow url
https://www.zooniverse.org/projects/aprajita/swdemo/classify?reload=0&workflow=4817

**Comment by srallen** [comment]
For that test workflow, I see that the subject metadata has two feedbacks defined: 
<img width="436" alt="screen shot 2017-08-24 at 3 09 55 pm" src="https://user-images.githubusercontent.com/5016731/29688861-605b19da-88de-11e7-9372-cc6c7722f85e.png">

I think the markers are working as they should, because there are two. The first has defined tolerance and coordinates, so the code knows how to evaluate success and failure. The second does not and will always fail and doesn't have a custom failure message, so the default one is used. 

It seems having both `feedback_1` and feedback_2` defined in the metadata is in error?

**Comment by aprajita** [comment]
oh gosh, i am so sorry i hadn't spotted this and inadvertelntly caused a lot of wrk. I coped the fedback_1 columns into _2 but forgot to empty the contents of the subtype and type. i wanted to try one exampel of having 2 possible locations for markers (subject_id 37) where satisfying either  or both feedback_1 or feedback_2 would trigger a success message.

I presume feedback_2_type being set to a value is what calls the feedback test so if this empty for some subjects it only considers feedback_1 - is that right?

so sorry again, am v embarrassed....

**Comment by eatyourgreens** [comment]
@srallen there are instructions on #3725 which say that `feedback_N` is supported, and that only `feedback_N_type` is required.

**Comment by eatyourgreens** [comment]
Also, those instructions on how to use feedback should probably be somewhere more useful than the description of a closed PR.

**Comment by aprajita** [comment]
Hi @simoneduca @srallen @eatyourgreens 
have reuplaoded these subjects with a new manifest that has the rogue #feedback_2_type keyword blanked for all but one subject.
the feedback displays as intended on those with feedback_1_type.

On image_37 that has 2 feedback's defined, as before the success message and the default message re shown, consistent with @srallen's advice. 

![image](https://user-images.githubusercontent.com/1917970/29930257-d4e37cb6-8e65-11e7-9685-bd34c3432ce7.png)

In the old SW,where multiple regions were defined, then just one mark within any of those windows would trigger the (single) success message for a subject. So any mark in any of the regions would be interpreted as a success.
 
I guess this is problematic for PFE feedback. I think it's OK to have independent messages provided we don't define too many "regions".  Or we might reconsider our instruction (e.g. mark the rightest lensed feature) might make it less confusing.

In the case that a region is missed you get the mixed feedback which makes sense (here it remains as the default as I haven't defined the message).

![image](https://user-images.githubusercontent.com/1917970/29930935-bdc72f6c-8e67-11e7-9252-f7706c938f17.png)

so this is as expected.

It would be helpful if only one of the side by side subject images showed the feedback rather than all three so if the user could elect which one or the default is the last one) then that would unclutter the displayed feedback.

not sure why the metadata feedback displays in a window larger than the text - there appears to to be no extra blank spaces int he csv manifest I made but will check again.

thanks very much
aprajita.

**Comment by simoneduca** [comment]
@aprajita just catching up on this. As far as I understand, the current behaviour is expected, so I'm closing this issue. I would ask you though to open a new one with the requests in your latest comment, thank you.

**Comment by aprajita** [comment]
Hi @simoneduca 

While the behaviour is a result of confusion about Feedback_N, i wouldn't say all the issues here are closed. My last post highlights and @eatyourgreens comments are also open that need some actio/clarification

I am away today but can comment more fully later.

If you want these put on a different issue please let me know.

Best wishes & thanks
Aprajita.

**Comment by simoneduca** [comment]
OK, I guess I'm confused. Would mind stating again which issues still need addressing?

**Comment by aprajita** [comment]
sorry simone, just saw that you asked me to open a new issue for the comments in my last post so i will do that

**Comment by eatyourgreens** [comment]
Any ideas why my [test mark](#issuecomment-324381526) didn't show a message for `feedback_1`? The coordinates look to be within the tolerance for the success message.

**Comment by aprajita** [comment]
@eatyourgreens do you get the same error on the new workflow?
https://www.zooniverse.org/projects/aprajita/swdemo/classify?reload=0&workflow=4817

**Comment by eatyourgreens** [comment]
Hi @aprajita I get a totally different bug on the new workflow. The feedback is there but off the top of the screen:
![Screen shot showing a completed classification, with feedback boxes off the top of the viewport.](https://user-images.githubusercontent.com/59547/30058846-9e654d9a-9234-11e7-8d76-0e9414c58ab1.png)

@simoneduca should the `feedback_1` message have shown up in my [original test](#issuecomment-324381526)? Should I open that as a new issue?

I can open a new issue about the position of the feedback messages, if that would be helpful. It's probably easier to keep discussion focussed to specific bugs, to track which have been fixed and which are still open.

**Comment by simoneduca** [comment]
I'm not sure @eatyourgreens. I would like to understand which issues need addressing though and issuing them separately would definitely be helpful. Perhaps @aprajita can help?

**Comment by aprajita** [comment]
have made a new issue #4022 on feedback message placement & formatting
@eatyourgreens linked #3763 on allowing the builder to specify which window the feedback should appear in

- linked dud feedback callout box 
- still have to think about whether we ask them to mark all lensed features or just the brightest ones

**Comment by eatyourgreens** [comment]
I've opened #4024 for the bug that I found, which I think @simoneduca also ran into.
