### ISSUE TITLE
Mark gold standard data when uploading

### ISSUE THREAD

**Issue by chrislintott** [zooniverse/Panoptes-Front-End#386]
(As an alternative to expert mode)

**Comment by simoneduca** [comment]
Not sure about this one. Has this sorted or is it outdated?

**Comment by srallen** [comment]
I think this can close as outdated. We're experimenting with labeling gold standard subjects in their metadata with Gravity Spy, but I think doing it that way is going to be a case by case basis for now and not a generalized solution.
