### ISSUE TITLE
Adding ability to make the results page be visible when the researcher desires it

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3864]
With the autosave feature if I start working on the results page it automatically gets made public and shows as I write it. It would be nice to be able to work on it without it being made public right away. Also if there's a press release, a researcher would want to have a results page likely but needs to make it visible when the embargo drop.s  Maybe there could be a check box to make it linked to the navigation bar on the site and otherwise available but only by directly access the url?

**Comment by mschwamb** [comment]
I need to have the results page live for the journal editor and copy editor to accept my paper proofs as I'm linking the dataset off of the results page. It would be really nice to not have to make a separate project to do the copy editing and formatting on it so that volunteers don't see a page in progress. Most other pages for a project you create while you're building the project before its launched. The results page is the only page that you write while the project is active, and if you have a press release you might want to not have it accessible from the menu bar until the embargo lifts.

**Comment by mschwamb** [comment]
I still think this would be really useful. Otherwise people can see as you're making that page. Especially useful feature if you have a press release coming out. I'm not sure why this is considered stale. I put this ticket in in June.

**Comment by eatyourgreens** [comment]
This is a zooniverse/Panoptes issue. At the moment, there's no concept of a draft page in the database.
