### ISSUE TITLE
Default play subject set for a workflow

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#387]
Provide a mechanism to copy a default set of images to a workflow for testing / playground work. The "I Fancy Cats" project has a public set of CC licensed images for this http://demo.zooniverse.org/panoptes-front-end/#/projects/brooke/I%20Fancy%20Cats/science-case

The backend should already support this via linking the subject_set to the worfklow, [docs](http://docs.panoptes.apiary.io/#reference/workflows/update-subject-set-links/update-subject-sets).

The specified project will have to be recreated in the production system for use there.

**Comment by brian-c** [comment]
To clarify: we want a button on the workflow editor to add a link a pre-made subject set of pictures of cats?

**Comment by camallen** [comment]
Yep. 

@chrislintott are you happy for the set of cat images from Brooke's project to be used as a default subject set that project builders can play around with?

**Comment by aliburchard** [comment]
@camallen @brian-c the plan is to use the kitteh zoo subject set as the default subject set. As soon as that's available, I'll rewrite the tutorial to reflect that.

**Comment by camallen** [comment]
Related to https://github.com/zooniverse/Panoptes/issues/907.

So it seems the front end is linking the subject set via the project [here](https://github.com/zooniverse/Panoptes-Front-End/blob/a98b0e753477c148a89102e5401304133949aaa3/app/pages/lab/workflow.cjsx#L198) and not the workflow. 

I've opened and issue in panoptes to fix this for the project route, https://github.com/zooniverse/Panoptes/issues/954

**Comment by brian-c** [comment]
Is following @edpaget's not in zooniverse/Panoptes#907 not the right action? Link to the project to copy, then link the copy to the workflow?

**Comment by camallen** [comment]
It's copying the subject set but not the associated set_member_subjects. I've implemented it on the workflow only currently. I'll add it to the project as well via #954.

The UI is linking the subejct set to a workflow so I think the workflows route is more appropriate in this instance anyway.
