### ISSUE TITLE
Project Page Subject Images on Mobile

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3871]
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
On mobile, the project images from talk look a bit overwhelming on a small mobile screen when they take up so much space in a column.

![screen shot 2017-06-15 at 10 41 11 am](https://user-images.githubusercontent.com/14099077/27189511-3296c304-51b7-11e7-9464-6486efee82f4.png)

## Steps to replicate
Visit any project landing age.

## Additional information
This issue came up a while ago, but I just found a pretty simple CSS solution for it. I was thinking the following looks nice, but I can also try putting one image on a row along with the "join in" button.

![screen shot 2017-06-15 at 10 42 41 am](https://user-images.githubusercontent.com/14099077/27189626-92d4d594-51b7-11e7-998d-11259b4c2e61.png)

@beckyrother thoughts?
- **Operating system:**
- **Browser:**

**Comment by beckyrother** [comment]
I love this! Let's do it.

**Comment by wgranger** [comment]
Cool. Also, noticing projects with more square (as opposed to rectangle images) look as so. It's still an improvement. 

![screen shot 2017-06-15 at 10 46 22 am](https://user-images.githubusercontent.com/14099077/27189763-f6be6d04-51b7-11e7-90f0-9eb386386c86.png)

**Comment by wgranger** [comment]
I'll have a PR up momentarily.

**Comment by beckyrother** [comment]
Excellent, I like that the Join In button is closer to the top. Good call!
