### ISSUE TITLE
Hidden buttons in Zooniverse on IE

### ISSUE THREAD

**Issue by jenzhao42** [zooniverse/Panoptes-Front-End#3877]
## Expected behavior
Play, Info, Favorite, Collection buttons should show up underneath image.

## Current behavior
Buttons are hidden from view under the picture - see screenshot for more details. You can click the Play/other buttons by hovering over where it *should* be but new Zooniverse volunteers wouldn't know that.
![screenshot 2017-06-19 17 15 02](https://user-images.githubusercontent.com/20244651/27306246-ecbc9124-5512-11e7-8c47-a3fbe3db320d.png)

## Steps to replicate
Go to https://www.zooniverse.org/projects/birgus2/western-shield-camera-watch/classify and try to look for any of the buttons below the image.

## Additional information

- **Operating system: Windows 7**
- **Browser: Internet Explorer 11**

**Comment by camallen** [comment]
Thanks for the bug report @jenzhao42 - we'll look into it.
