### ISSUE TITLE
"Loading" text at the top of the screen causes everything to jump around

### ISSUE THREAD

**Issue by willettk** [zooniverse/Panoptes-Front-End#389]
When going from subject to subject, the word ```LOADING``` pops intermittently near the top left corner of the page. It makes the text jump up and down as you go from subject to subject, and leaves the webpage scrolled a few percent of the way down, even if you started at the top when clicking on "Done". 

Can it be changed so that the ```LOADING``` text doesn't affect the placement of other elements on the page? It's a moderate annoyance if you're trying to settle in for more than a couple classifications at one go.

**Comment by edpaget** [comment]
I think this was fixed by the new top bar loading spinner.

**Comment by aweiksnar** [comment]
I'm still seeing this, but just placed a PR to fix #836
