### ISSUE TITLE
Video viewer in Talk: speed control buttons not all accessible

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3895]
## Expected behavior

In the classify page, you can access the 0.25x, 0.5x, and 1x speed controls under the video viewer. This is great. 

When you view the same subject in Talk, you can no longer access the 0.25x. See attached images. 
![screen shot 2017-06-26 at 4 15 39 pm](https://user-images.githubusercontent.com/4975655/27560725-e0b0d034-5a8a-11e7-96e3-abc686faead5.png)
![screen shot 2017-06-26 at 4 14 36 pm](https://user-images.githubusercontent.com/4975655/27560726-e0bcbaa2-5a8a-11e7-89b4-e47e03f8f25f.png)

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

## Additional information

- **Operating system:**
Macbook air

- **Browser:**
Chrome Version 58.0.3029.

**Comment by beckyrother** [comment]
Please increase the height of the subject viewer so these extra controls don't get cut off. It would be great to be able to update this before Arizona BatWatch's new beta comes out next week.

@srallen Tagging you because I'm not sure who would be best to take care of this.

**Comment by srallen** [comment]
I have a fix incoming soon, but want to test to make sure I'm not breaking styling for other projects on talk first. Should have a PR up tomorrow some time.

**Comment by eatyourgreens** [comment]
I think this broke when [I fixed the button positions](/zooniverse/Panoptes-Front-End/pull/3781#issuecomment-300509265) for @beckyrother so check that that layout bug doesn't regress.

**Comment by srallen** [comment]
@eatyourgreens thanks for the heads up. I've taken a look and the issue is that the subject tools area didn't have any defined position or display styles defined for Talk, so when the video speed controls were made position: absolute, the subject tools were no longer positioned correctly on Talk. I'll get a PR up in a moment, but I don't think there'll be any regressions with the classifier styling.
