### ISSUE TITLE
discipline tag is missing (although its actually set ) and other tags cut to 1 letter 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3897]
P4: Ridges 
<img width="1091" alt="screen shot 2017-06-27 at 11 37 02 am" src="https://user-images.githubusercontent.com/753325/27568600-b1ddb274-5b2d-11e7-8c19-76397a1b24f1.png">

Comet Hunters 
<img width="1127" alt="screen shot 2017-06-27 at 11 38 58 am" src="https://user-images.githubusercontent.com/753325/27568574-87509c9c-5b2d-11e7-8b77-c339e0086a4f.png">

reloading it doesn't fix things. 

The discipline tag is set since the projects are showing in the space category on the Zooniverse projects page.

**Comment by camallen** [comment]
I can't reproduce this, on either chrome / firefox, with and without zoom. Anyone?

<img width="667" alt="screen shot 2017-06-27 at 08 35 19" src="https://user-images.githubusercontent.com/295329/27576032-8af69780-5b13-11e7-97f3-8d59cc2e52b1.png">

**Comment by eatyourgreens** [comment]
Duplicate of #3735

Seems to be a bug where the API sometimes returns tags as strings, but the front-end expects an array with the tag name in `tag[0]`

**Comment by mschwamb** [comment]
Could it be related to the fact I'm in a far place from the AWS servers? I'm currently in Japan and the other times when I was either in Taiwan or Hawaii?

**Comment by eatyourgreens** [comment]
Probably not. I get the same behaviour on the Oxford Physics network. When it happens, I'm seeing the tags come back from the API as strings, but they should be arrays. If `tag` is a string, then `tag[0]` returns the first character in javascript.

**Comment by eatyourgreens** [comment]
@camallen Here's what I see for https://www.zooniverse.org/lab/396, including `project.tags` in the debugger. The code is expecting those tags to be objects or arrays, so perhaps a bug in the project serialisation?

![Screenshot of the project editor, including project.tags in the debugger](https://user-images.githubusercontent.com/59547/27583083-2687d580-5b2b-11e7-8c50-441b7ea05423.png)

**Comment by camallen** [comment]
the network tab reveals something weird going on with the tags, seems they are serializing more data than needed.

<img width="644" alt="screen shot 2017-06-27 at 11 27 45" src="https://user-images.githubusercontent.com/295329/27583255-af4b9f3c-5b2b-11e7-8ee9-695be99ff6c5.png">

**Comment by eatyourgreens** [comment]
@camallen Any idea why you're getting arrays but @mschwamb and me are getting strings back from the API?

**Comment by camallen** [comment]
nope... :(

**Comment by eatyourgreens** [comment]
Turns out to be a bug in the Panoptes API: zooniverse/Panoptes#2375

**Comment by mschwamb** [comment]
Thanks for fixing this. Closing the ticket
