### ISSUE TITLE
Zooniverse team talk roles display twice

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#3898]
## Expected behavior
Only display the team talk roles once even if member of admin / team.

## Current behavior
Same role name is displayed twice, one for admin and one for team.

![image](https://user-images.githubusercontent.com/295329/27575879-0dd4baca-5b13-11e7-8556-ea764a758499.png)

## Steps to replicate
Check my comment [here](https://www.zooniverse.org/projects/panthera-research/camera-catalogue/talk/447/313052?comment=634548&page=3)

## Additional information
This role code [here](https://github.com/zooniverse/Panoptes-Front-End/blob/67ddfa2ed9ae42f3a0c0f6f5fe76d73bb919f9a1/app/talk/lib/display-roles.cjsx#L12
) seems to be the culprit.

**Comment by mcbouslog** [comment]
And Researcher

![screen shot 2017-07-07 at 10 51 59 am](https://user-images.githubusercontent.com/12118751/27965795-8213e2c0-6302-11e7-9fce-b353e4655de4.png)

**Comment by mschwamb** [comment]
if it's helpful it's not happening on older projects. On my projects, I still see the title showing up one. I'm not sure what the difference is.

**Comment by eatyourgreens** [comment]
Doesn't happen for me, either, but it does happen for @camallen and @trouille so it might be related to roles on individual Zooniverse accounts.

**Comment by camallen** [comment]
Turns out i have both team & admin zooniverse section roles for some reason, both created 2015 & 2016. The researcher one is probably owner and scientist together.

**Comment by mschwamb** [comment]
So it looks like the owner is immune, but happening on P4 Ridges for one of the other researchers who is a collaborator on the project. See [here](https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/633/398509?comment=668288)

**Comment by mschwamb** [comment]
The owner and moderator roles seem immune to this issue.

**Comment by mschwamb** [comment]
appears to happen to every role but owner and moderator. Owner and moderator only have one label show.

**Comment by mschwamb** [comment]
This is still happening. I know this pretty minor, but in my opinion it makes it look the Talk doesn't work correctly when it goes and its great system. If this is an easy fix, could someone take a look? 

<img width="744" alt="screen shot 2017-12-05 at 12 01 19 pm" src="https://user-images.githubusercontent.com/753325/33633203-1263237c-d9b4-11e7-9203-547055c96183.png">

**Comment by mschwamb** [comment]
This is still happening. It's been more than 6 months since this bug was identified. I understand it's cosmetic, but I think it gives the perception that the platform is buggy.   Since the duplicate role tag doesn't just show up in the discussion page only, it shows' up on the talk front page too.  


<img width="715" alt="screen shot 2018-01-09 at 12 50 49 am" src="https://user-images.githubusercontent.com/753325/34706709-33a58046-f4d7-11e7-8828-a3ad5aeb46a1.png">

**Comment by dwright04** [comment]
This is also happening for @lfortson in Muon Hunters 2.0 talk.

Lucy is listed as a Collaborator, Expert and Researcher on the project and appears with two Researcher tags in talk.

![screen shot 2018-02-15 at 12 20 19 pm](https://user-images.githubusercontent.com/7902164/36273966-e1a9a082-124b-11e8-94d8-7a24409f3100.png)

**Comment by eatyourgreens** [comment]
I've traced this back to #992. The team and admin roles are both displayed as 'Zooniverse Team', leading to duplication if you have both roles. Similarly, the owner role is displayed as 'Researcher' on Talk, leading to duplicate listings for Researcher if you're the project owner.

**Comment by eatyourgreens** [comment]
In the case of www.zooniverse.org/users/lkerber on P4 Ridges, this is happening because they have the roles of 'admin' and 'scientist', but both of those roles are displayed as 'Researcher'.

![DOM screen capture, showing lkerber's roles as admin and scientist in the CSS classes.](https://user-images.githubusercontent.com/59547/36313444-726d9c58-1329-11e8-9dae-fdd017a6e34c.png)

**Comment by mschwamb** [comment]
@eatyourgreens  In case it's helpful, I  don't have duplicate role labels on Talk and I'm a project owner. For P4: Ridges I have only one researcher label. See [this](https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/667/543301?comment=908461) 

Also yes, I have lkerber as collaborator and researcher, and she does have two labels.
