### ISSUE TITLE
Cloning workflows only copies some properties

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#3901]
## Expected behavior
When I clone a workflow, the nero_config should be copied to the new workflow.

## Current behavior
When I clone a workflow, the nero_config isn't copied to the new workflow

## Steps to replicate
Clone a workflow, using the small copy button to the right of the workflow name

## Additional information
Relevant lines of source code here:
https://github.com/zooniverse/Panoptes-Front-End/blob/4e5ce008b903033c09db718574396c2124f438b2/app/pages/lab/workflow-create-form.cjsx#L26-L33

- **Operating system:**
Not OS-dependent

- **Browser:**
Not browser-dependent

**Comment by camallen** [comment]
Adding a note that the API supports workflow cloning but has a bug https://github.com/zooniverse/Panoptes/issues/2031. I argued that it should be an API action originally but the bug was a blocker.

**Comment by amyrebecca** [comment]
It's also worth asking whether the nero_config OUGHT to be copied, since presumably you're going to change the workflow in ways that may or may not break the automation.

**Comment by srallen** [comment]
@amyrebecca did the configs get moved to caesar? Can this issue be closed?

**Comment by amyrebecca** [comment]
It hasn't been moved yet. I thought there was an issue that I could link but apparently it hadn't been created yet. We were previously roadblocked by needing authentication, but marten has fixed that. The relevant github issue is zooniverse/caesar#104

**Comment by srallen** [comment]
Ok thanks!

**Comment by amyrebecca** [comment]
I'm glad you mentioned it--this stuff should all be in github, not just in my head! :)

**Comment by srallen** [comment]
Closing because config will be handled by Caesar entirely (including UI). In the event that a workflow is "cloned," then its caesar configuration will have to be setup for the new workflow regardless.
