### ISSUE TITLE
Implenting a pop-up already seen message as an interrupt

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#391]
I got the already seen orange banner on an image. 

![screen shot 2015-05-23 at 1 17 11 pm](https://cloud.githubusercontent.com/assets/753325/7782521/22f97e38-014f-11e5-8163-1b4c8997e518.png)

 I'm not sure volunteers are going to understand what that means. I think just like there is now an active interrupt to ask people to sign in, a pop up would  be better here in addition to the little 'already seen' orange banner, so we can direct people back to zooniverse home and get them  to start on a different project. I think with just the orange banner some people will keep classifying, and we want to not waste their time. 

Something along the lines of:

'Thanks for your help, but you're seeing an image you've already classified before. It looks like we're out of data for this project, but not to worry there is plenty of other projects in the Zooniverse that need your help. Click here to get started'

and have that show up like every 3 (or 5) classifications . If you close the message then you can keep classifying the repeat images.

**Comment by chrissnyder** [comment]
100% agree with Meg here, but tagging as future plans as the current solution works for now.

**Comment by mschwamb** [comment]
Being addressed in #1050
