### ISSUE TITLE
Uploading 9,000 subjects - any other way than drag and drop?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#392]
We're going to be uploading on the order of 9,000 subjects and in the current system we either have to drag and drop all of them or highlight them in the file finder if you click on the upload text box. That's a bit cumbersome when you have thousands of subjects.  Is there any plan or option that the file uploader could be pointed to a directory and it would upload everything that is in the directory?

**Comment by edpaget** [comment]
I'm don't think we'll have anything in the next few days, but you can look at either @mkosmala's script https://github.com/mkosmala/PanoptesScripts/blob/master/panoptesPythonAPI.py#L449-L484 or @brian-c's utility https://github.com/zooniverse/panoptes-subject-uploader to see if either works for you. 

Since subject creation just happens through an HTTP interface, that's documented [here](http://docs.panoptes.apiary.io/#reference/subjects/subject-collection/create-a-subject) you're welcome to make a small script to upload subjects .

**Comment by mschwamb** [comment]
Thanks @edpaget. We'll try that or just deal with the webform, but some sort of project builder solution in the future would be helpful especially for science teams where playing with the API directly wouldn't be doable.

**Comment by vrooje** [comment]
As a band-aid solution, putting all (and only) the subjects into a folder, then doing a select-all in the folder makes the drag-and-drop easier. 

Have never tried to upload 9,000 subjects at a time, though, so I may be missing something.

**Comment by mschwamb** [comment]
Yes, but that's fine for soft launch but that get's harder when it's 120,000 subjects.

**Comment by chrissnyder** [comment]
I think it's unlikely the web interface will ever scale to ten of thousands of subjects and that alternative tooling would need to be built to support that level of subject ingestion. Closing this, but if someone disagrees, do re-open.

**Comment by camallen** [comment]
For reference, @brian-c built this for stargazing. I don't think it's out of date and should work out of the box. https://github.com/zooniverse/panoptes-subject-uploader I can provide some other code to create batches from manifest files on request.

**Comment by brian-c** [comment]
I think I ended up building some stargazing-specific bits into that tool, but it's a start.

**Comment by mschwamb** [comment]
Yeah, I think just having something  down the line even if it just generates a script that talks to the backend api and uploads them one by one would help in the future. my project had 20,000 subjects. We were allowed to have @camallen do the upload, other projects won't be as lucky. I think there are teams where pointing and clicking in a  project builder will be what they're comfortable with. Asking them to download a code for github and run it might be difficult.

**Comment by mkosmala** [comment]
I've already written a Python script to upload an arbitrary number of subjects to the back-end. Would be relatively simple to make it generalizable. I'll put it on my things-to-do-in-July list and then link back to this issue when it's ready.
