### ISSUE TITLE
Researcher label showing twice in Talk

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#3922]
## Expected behavior
Researcher label shows once

## Current behavior
Researcher label shows twice

![screen shot 2017-07-07 at 10 51 59 am](https://user-images.githubusercontent.com/12118751/27965795-8213e2c0-6302-11e7-9fce-b353e4655de4.png)

https://www.zooniverse.org/projects/zooniverse/notes-from-nature/talk/484/388084

If user roles for project include collaborator and scientist the "Researcher" label shows twice.

**Comment by eatyourgreens** [comment]
You can also see this on Talk for the zoo team role. https://www.zooniverse.org/talk/16/388005?comment=648833&page=1
![A comment from Laura Trouille, showing the Zooniverse Team role twice.](https://user-images.githubusercontent.com/59547/27966435-25681dd6-6337-11e7-8d3c-415c9c8e4f26.png)

**Comment by mschwamb** [comment]
duplicate of #3898

**Comment by mcbouslog** [comment]
Closing due to duplicate
