### ISSUE TITLE
Horizontal scroll in project tutorial

### ISSUE THREAD

**Issue by miclaraia** [zooniverse/Panoptes-Front-End#3923]
## Expected behavior
Horizontal scroll would swipe to next/previous page in the project tutorial

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Horizontal scroll shows all the views in the tutorial overlapping:
![screenshot from 2017-07-09 00-34-28](https://user-images.githubusercontent.com/10344353/27989938-a504d1e4-643e-11e7-9cec-481b9f7565e9.png)

## Steps to replicate
Go to [Radio Meteor Zoo](https://www.zooniverse.org/projects/zooniverse/radio-meteor-zoo/classify) and open project tutorial. Try scrolling horizontally in project tutorial window.

## Additional information

- **Operating system:**
Ubuntu 17.04 with i3 as window manager

- **Browser:**
Using Chrome 59.0.3071.8
Could not reproduce effect on Firefox

**Comment by camallen** [comment]
Works fine in chrome (Version 59.0.3071.109 (Official Build) (64-bit)) for me on Ubuntu 16.04
