### ISSUE TITLE
Is there a way to get a table of contents on an about page  like the markdown on the glossary has?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#3924]
I want to have a table of contents so people can quickly go to ether  the P4T results tables or the list of volunteer names  on the results page.  I'm using the results page to link the supplemental data files and also display the publishable names of the P4T volunteers. 

I tried following the markdown listed on the [glossary](https://www.zooniverse.org/help/glossary) to make different sections, but it doesn't seem to work on the about pages for P4T.  Is it possible to make this work? Maybe I had it formatted incorrectly or maybe it's not supported in the project builder pages?

**Comment by eatyourgreens** [comment]
Could you post the markdown that you tried? I can't see why it wouldn't work on the project pages if it works elsewhere.

**Comment by eatyourgreens** [comment]
[Here's a talk comment](https://www.zooniverse.org/talk/13/18624?comment=184093) where I tested out the table-of-contents markdown after we added it.

**Comment by mschwamb** [comment]
Thanks @eatyourgreens I thik I missed the toc bit. It's not in the markdown help. Maybe it should get added in. I'm trying it now

**Comment by mschwamb** [comment]
So it kind works but I have to have H1 or H2. 

I just want to have under  a link for 'Planet Four: Terrains Data Release 1' under  the H2 'Planet Four: Terrains Data and Community Page'

`##` Planet Four: Terrains Data and Community Page
`----------`
`[[toc]]`

`***`
`####` This page allows anyone to download the data files associated with Planet Four: Terrains papers. Planet Four: Terrains is described in Schwamb et al. (in press). Anyone making use of Planet Four: Terrains data should cite this paper in any resulting publications as well as the appropriate data release paper.

`***`
`###` Planet Four: Terrains Data Release 1 
`**Planet` Four: Terrains – Discovery of araneiforms outside of the South Polar layered deposits (2017)**


It would be nice if I could control the header size.  I was trying this:


'[General Terms](#general-terms)'  like what's in here, but it doesn't seem to work

So spending more time on it, I got it but I have to remove then ':'

The following works: 

`[PlanetFour Terrains Data Release 1](#planet-four-terrains-data-release-1)'

**Comment by mschwamb** [comment]
closing since sorted
