### ISSUE TITLE
Publications page update

### ISSUE THREAD

**Issue by hrspiers** [zooniverse/Panoptes-Front-End#3927]
There are new publications to add to the publications page.

The new publications to be added are shown in white in the following document (the ones that have already been added are shown in grey):

https://docs.google.com/spreadsheets/d/1NZ31aVPiQag5V3-zY9tIP2x2WPXFEf9dLIIHBSHkx3M/edit#gid=0

Thanks,
Helen

**Comment by trouille** [comment]
A few more to add

http://iopscience.iop.org/article/10.3847/2041-8213/aa7200/meta

http://scholarspace.manoa.hawaii.edu/handle/10125/41159

Bahaadini, S., N. Rohani, S. Coughlin, M. Zevin, V. Kalogera, & A. Katsaggelos. (2017). “Deep Multi-view Models for Glitch Classification.” In 42nd IEEE International Conference on Acoustics, Speech, and Signal Processing: March 5th-9th 2017, New Orleans, USA.

https://jcom.sissa.it/author/alycia-crall

Campbell, H., R. Cartier, M. Smith, J. Anderson, C. Inserra, C. Lintott, G. Miller, C. Allen, B Carstensen, G. Hines, A. McMaster, E. Paget, K Maguire, S. J. Smartt, K. W. Smith, M. Sullivan, S. Valenti, O. Yaron, D. Young, I. Manulis, D. Wright, K. Chambers, H. Flewelling, M. Huber, E. Magnier, J. Tonry, C. Waters, R.J. Wainscoat. (2015). “ATel #7254: PESSTO spectroscopic classification of optical transients.” In The Astronomer’s Telegram. Consulted December 1, 2016. Available http://www.astronomerstelegram.org/?read=7254

**Comment by camallen** [comment]
change Kuchner et al 2017 link to ApJL - http://iopscience.iop.org/article/10.3847/2041-8213/aa7200/meta citation instead

**Comment by mschwamb** [comment]
I can't see the doc, I don't have access. I think for Kuchner et al you might want to also link to  http://adsabs.harvard.edu/cgi-bin/bib_query?arXiv:1705.02919 because it has the free pre-print version that the volunteer can access
