### ISSUE TITLE
Error linking subject sets

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#393]
I've just created a new workflow ("How many each way")  on an existing project (http://demo.zooniverse.org/panoptes-front-end/#/projects/aliburchard/WildebeestWatch) 

. I forgot to link to a subject set and went to classify. I received the "Error: No subjects available for workflow 1128" I went back to the builder and linked to an existing subject set that works for all the other workflows ("full 100"). I hard reloaded but am still getting the same error when I try to classify on this project for this workflow. All other workflows are fine.

![screen shot 2015-05-23 at 06 19 03](https://cloud.githubusercontent.com/assets/6217406/7783783/feb14bfe-0113-11e5-82e4-ca7f84273b06.png)

**Comment by aliburchard** [comment]
As a follow up, I waited about 10 minutes, unlinked, then relinked, and waited some more, and then things worked. If it's just a slow process to link to the subjects, then we should put up some warning text somewhere, or perhaps make a more informative error message saying "THis will take a little while, please do X"

**Comment by vrooje** [comment]
I think this may have been repeated by @aprajita, who reported this issue to me on a test project, but by the time I'd been added to the repo to try and look into it, the subjects were linking fine.
