### ISSUE TITLE
Cannot view publications page on localhost/staging

### ISSUE THREAD

**Issue by mariamsaeedi** [zooniverse/Panoptes-Front-End#3931]
## Expected behavior
When opening publications page you should be able to view the publications

## Current behavior
If you go to https://www.zooniverse.org/about/publications you see the publications all good however on localhost3735/about/publications you are unable to view them and receive an error message of: `slug is undefined`

## Steps to replicate
Go to the publications page on your local host, you should see the loading symbol spinning forever and you can also see the error messages in your console

## Additional information
1. You can actually view the working publications page without errors on your local host by adding ?env=production - there appears to be a problem between staging and production.

2. The publications-page.cjsx document loads only a selection of the publications during staging compared to production which loads the entire collection of publications. When viewing the publications page in staging it expects to see these few publications however it is receiving a different type of information from publications.js which feeds it more data than has currently been defined in publications-page.cjsx 

```
  //In app/pages/about/publications-page.cjsx, this receives a different set of data depending on whether we're on staging or production
  loadProjects: ->
    apiClient.type('projects').get(slug: @projectSlugs(), cards: true).then (projects) =>
      projectMap = { }
      projectMap[project.slug] = project for project in projects
      @setState projects: projectMap
```

```
//In app/pages/about/publications-page.cjsx 's render(), this fails because the expected list of projects (based on app/lib/publications.js) is different from production and staging.
  {for projectListing in projects
    project = @state.projects[projectListing.slug]
    <div key={projectListing.name or project.slug}>
```

**Comment by camallen** [comment]
A few options on this I think:
+ Build projects that match the expected slugs in staging so the setup mi
+ Put a conditional test on the project existence when rendering
+ Add a UI message about this page working differently on staging than production so we don't have to read this issue every time :)
