### ISSUE TITLE
How does marking/aggregation work for multi-image subjects

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#394]
@ggdhines and anyone who knows how the marks are being stored: you can mark on a multi image subject (e.g. http://demo.zooniverse.org/panoptes-front-end/#/projects/aliburchard/WildebeestWatch/classify?workflow=1128). How does that work? What's actually reported? What about when the images in a given subject don't have the same pixel dimensions?

**Comment by chrissnyder** [comment]
Sort of a duplicate of https://github.com/zooniverse/Panoptes-Front-End/issues/525, closing to consolidate discussion.
