### ISSUE TITLE
Metadata with Periods Breaks Subject Uploader

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#3941]
## Expected behavior
Manifests should recognize uploaded subjects by name.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Metadata containing periods confuses the uploader into thinking there are more subjects than rows.

## Steps to replicate
Find a manifest with periods in a field. Try uploading corresponding subjects with the manifest.

## Additional information
I think this is an issue with the regex in the subject uploader.

- **Operating system:**
- **Browser:**
Chrome

**Comment by srallen** [comment]
@wgranger were you using admin mode when this happened?

**Comment by srallen** [comment]
Closing as this was likely in admin mode. The regex to identify subjects when in admin mode basically looks for a period and any three to four characters after it which means it can incorrectly identify things in the metadata as subjects when they're not. The way around this is to turn admin mode off before you try to upload.
