### ISSUE TITLE
Automatically stop playing of multi-image subjects after 3 loops

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#395]
Right now the play button runs through the images until you click stop. If you try to scroll up the screen to, say, access links that are out of view, it automatically scrolls backdown. Also, you have to automatically stop it if you want to mark on the subjects.

Can we have it automatically loop a couple of times like in Snapshot Serengeti and then stop? (And in time for first release?) I've got a workflow that requires marking on multi image subjects and this would make that workflow infinitely easier.

**Comment by chrissnyder** [comment]
Tagging as bug because I don't know why cycling through images would override scroll behavior.
