### ISSUE TITLE
Survey task remembers annotation values across subjects

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#3950]
Bug introduced by #3947 I think.
## Expected behavior
The Choice component should not have any answers selected for any identification choice for a new subject.

## Current behavior
Identify an animal in a survey task, answering any required questions for that choice.
Move on to a new subject.
Select the same choice again and the choice component will open with your answers from the previous subject still selected.

I had a quick look through the survey task code, but nothing obvious jumps out at me to tell me why it is remembering answers like this.

_Please include any error messages from the browser console and/or screenshots_

## Steps to replicate
See above.

## Additional information

- **Operating system:**
OSX
- **Browser:**
Chrome

**Comment by aliburchard** [comment]
😍
