### ISSUE TITLE
Allow unsubscribe form submission if checkValidity isn't supported

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#3969]
## Expected behavior

The user should be able to submit the unsubscribe form even if their browser doesn't support email validation.

## Current behavior

Form submission is only enabled if the [email address is valid](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/unsubscribe.cjsx#L21)

## Additional information

- **Operating system:**
- **Browser:**

**Comment by simoneduca** [comment]
I could do with some help in clarifying what this component is actually doing:
1. Although the text says "[we'll unsubscribe you from all our email lists](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/unsubscribe.cjsx#L53)", the UI about the Talk is not clear. I understand they're radio buttons and they have to be selected, but I have no idea whether I was unsubscribed or not from Talk.
2. I don't know how to trigger [this line](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/unsubscribe.cjsx#L44). Loading the page with `processed` in the url query doesn't do anything. What is processed @camallen?

**Comment by eatyourgreens** [comment]
The query parameter should show the success message, according to that code. 
https://www.zooniverse.org/unsubscribe?processed=something

**Comment by simoneduca** [comment]
When is it supposed to do that though? This is what is rendered on success
<img width="634" alt="screen shot 2017-08-02 at 19 25 15" src="https://user-images.githubusercontent.com/8989606/28888423-6d5079fa-77b8-11e7-8d94-e78743f21cb7.png">
and the url is just https://www.zooniverse.org/unsubscribe

**Comment by simoneduca** [comment]
Following from list above:

3. I can unsubscribe also when I'm logged out, which doesn't seem right. That is possible because the input doesn't do any check whatsoever, which it means I can unsubscribe any other user if I know their email. Also not right.

Suggestion: this feature should be available only when logged in _and_ the email address to unsubscribed should be displayed from `user.email` in a readonly field. This way we could avoid inappropriate use.

**Comment by astopy** [comment]
We have to allow users to unsubscribe themselves even if they can't log in. I agree that it sucks that this is basically completely open, but the solution would be to modify this in the backend to send a one-click unsubscribe link/token to the user if they're not logged in. I don't know if we'll be able to set that up any time soon (@camallen?)

**Comment by eatyourgreens** [comment]
Can we keep the discussion here focused on the original bug? Other problems can be opened as their own issues.

**Comment by simoneduca** [comment]
@astopy I just had a convo on @camallen and all is good.

**Comment by simoneduca** [comment]
@eatyourgreens it wasn't clear to me what the expected functionality was, so it seemed legitimate asking the above questions and making those suggestions.

**Comment by camallen** [comment]
@astopy we already have that method (unique unsubscribe token per user). Previously we couldn't put it into the email with JISC. If we send emails direclty from panoptes we do include this way to unsubscribe (no need for form submission) and the component that @simoneduca is converting handles the UI aspect of this success acknowledgement.
