### ISSUE TITLE
Add keyboard "esc" to close help pop up

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#397]
Is this at all do-able quickly/easily? Hitting esc to close a pop up menu seems so intuitive and speeds up the classification process, instead of having to navigate over to the little x in the corner...

**Comment by chrissnyder** [comment]
Related to https://github.com/zooniverse/Panoptes-Front-End/pull/486, not able to do easy because dialogs are being used for things other than just a quick information dump, i.e., closing the subject upload dialog box cancels the subject upload.

**Comment by simoneduca** [comment]
Closing as not easily done, at least until dialogs get some love.

**Comment by eatyourgreens** [comment]
@simoneduca I added escape to close dialogs here https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/dialog.cjsx#L31-L32
but I'm not sure if the help popup uses that component.

**Comment by simoneduca** [comment]
I realised I'm actually not sure which one is the help pop up. Is it the one you get by clicking on the "?" here?
![screen shot 2016-11-08 at 16 33 44](https://cloud.githubusercontent.com/assets/8989606/20107716/6a2aa5e8-a5d1-11e6-8202-a794eab721a9.png)

If it is, then, yes, it uses the same component, but ESC doesn't seem to work.

**Comment by eatyourgreens** [comment]
I think this issue refers to 'Need some help?' on the classification page, which does use the `Dialog` component. The help popup can't receive focus, though, so it isn't focussed when it opens, so it can't detect the `esc` key being pressed.
https://github.com/zooniverse/Panoptes-Front-End/commit/fdda07141435dc6a6c0fbeb4664e554a25fdcbff

The solution might be to focus the close button when the dialog opens. It's slightly complicated by the close button being in a different component to the dialog component.
