### ISSUE TITLE
zooniverse.org/projects and how to include organizations and projects in an organization

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#3977]
Organization cards will have slightly different visual treatment to project cards:
![projects page](https://cloud.githubusercontent.com/assets/1392130/25638536/5b3e52d0-2f4e-11e7-90d2-e9a0e531f066.png)

related to #3971, #3025

**Comment by mcbouslog** [comment]
Per conversation with Laura T. and Chris L. an org card will show in list of Active projects and related projects will not show.

There will be no Organizations sub-section (to the right of Finished).

Eventually allowing an org builder to enable related projects to show individually and the org card not show might be considered, but not initially.

**Comment by camallen** [comment]
@mcbouslog just noting that they are two different API resources and will this require 2 api calls, 1 each to fetch the launched orgs & projects?

**Comment by mcbouslog** [comment]
@camallen - yes, and that's a great point. 2 api calls every time a user lands on https://www.zooniverse.org/projects is far from ideal. Could there be a solution where 1 api call would return launched projects (cards) and listed organizations?

**Comment by srallen** [comment]
Is there a reason why we're going back to a merged view? I thought we decided on the separate tab for the reason of having simpler API calls.

**Comment by camallen** [comment]
@srallen - So did I. 

@mcbouslog not really they are 2 seperate resources (though we could do something i guess). If we don't support a custom end point api side, then I'd leave it as just 2 api calls if the merged view is what is required, the UI may update in a staggered way based the resolve time of the 2 Promises.

**Comment by mcbouslog** [comment]
With organizations like Galaxy Zoo, Africa Wildlife Watch and Notes from Nature in mind that will have closely related projects and projects that may go active and inactive (though a few active projects associated with an org would always be required) I think we're picturing the organization as the constant that routes interested volunteers to the related projects that are live.

So I think @chrislintott, @trouille and I were thinking a merged view (excluding org related projects) on the [main active listing](https://www.zooniverse.org/projects) would be a better volunteer experience so a volunteer isn't choosing between closely related projects that want to be grouped.

Or to put differently, the main listing showing cards of:

Cairo Geniza, <sup>1</sup>Etosha Wildlife Watch, <sup>1</sup>Amoseli Wildlife Watch, <sup>2</sup>Galaxy Zoo, <sup>3</sup>Fantastic Ferns, Bash the Bug, <sup>3</sup>Ant Plants, <sup>2</sup>Galaxy Zoo: Hubble, Colorado Corridors, <sup>1</sup>Lake Manyara Wildlife Watch,<sup>2</sup>Galaxy Zoo: CANDELS, etc...

would be a less preferable experience for a volunteer than what we think would be the more preferable experience of:

Cairo Geniza, <sup>1</sup>Africa Wildlife Watch, <sup>2</sup>Galaxy Zoo, Bash the Bug, <sup>3</sup>Notes from Nature, Colorado Corridors, etc...

@chrislintott or @trouille please correct or add if you'd like.
To all, this is of course open to discussion, these were just our recent thoughts.

Mentioning @beckyrother. I think what I've mentioned is consistent with the design at the top of the issue as it specifically relates to the Active tab, but let us know, and just wanted to make sure you're apprised of the conversation.

It sounds like the main issue here is the technical cost of 2 API calls to the API and to front-end load time vs an arguably preferable volunteer experience on the main active listing?

I think we can solve clunky displaying of the two responses with `Promise.all` and organizations should be small sized resources, hopefully would make that call less painful.

**Comment by camallen** [comment]
I'm not too worried about the API calls (we should make them fast) and looks like `Promise.all` solves the stagger resolve issue. Nice work.

**Comment by mcbouslog** [comment]
Noting thoughts subject to change - possibly utilize a project's status attribute to not show on main project listing if linked to org. Maybe when a project is linked to an org, it's status is changed to 'organization'. Further review is needed to see how changing a project from development to live (`project.live` = true/false) effects `project.status`.

**Comment by mcbouslog** [comment]
Per discussion with a NfN researcher there's a good argument that an org may want Active, Paused and Finished tabs similar to zooniverse.org/projects, in which case `project.status` should stay as is and not be used to filter out projects affiliated with an organization from showing on zooniverse.org/projects.

**Comment by mcbouslog** [comment]
Closing in favor of user feedback and general `/projects` redesign (https://github.com/orgs/zooniverse/projects/4#card-6495644).
