### ISSUE TITLE
Ability to download the metadata of the subjects 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#398]
The csv file output provides the classifications, but if I want the metadata associated with the subjects, I would need to unique the classification csv file which can be slow with millions of classifications.  It would be nice if it's possible to have an option to download separately the metadata associated with the subjects stored for the project in a csv file.

**Comment by mschwamb** [comment]
I should mention on reason for this is that there have been cases where I've downloaded on previous projects a subset of the subjects to review by hand. Only the metadata csv would have the url links to the saved subjects, that info isn't in the classification csv file

**Comment by mkosmala** [comment]
@mschwamb This makes a lot of sense -- especially for big projects. However, it requires the end-user to be able to do a JOIN (or equivalent) of two tables if they want the subject metadata (or even subject identity) for each classification. Is Zooniverse going to assume that level of technical ability on the part of the science teams? I imagine that there will be plenty of small projects with minimal technical expertise on the part of the project building teams.

Maybe what makes sense is that if teams want **raw** classifications, they get the two files (one for the classifications and one for the subjects). But if they want aggregated data, they just get one joined file (which won't require a UNIQUE on the subject metadata anyway, since presumably there will just be one row per subject).

@aliburchard thoughts? Who else should weigh in?

**Comment by camallen** [comment]
@mkosmala aggregated data won't come from the raw classification data dumps. it'll be a different export. We will most likely add the subject ids / names and workflow id / name into the aggregation. 

@ggdhines what does a current aggregation json doc look like?

**Comment by ggdhines** [comment]
@camallen pretty flexible but the basic format is something like {subject_id:1, workflow_id:1,task:"init",tool:0,aggregation: text, created_at: timestamp}

**Comment by mkosmala** [comment]
@camallen, right; I realize the aggregation data will be rather processed. The question is, @ggdhines, will it include subject metadata?

**Comment by ggdhines** [comment]
@mkosmala think that would be reasonable

**Comment by aliburchard** [comment]
I think Margaret’s suggestion makes sense. It will require us splitting up the data into two tables behind the scenes (which is trivial, but I don’t know where it falls on the priority list). Any user who wants the raw classification data to run their own aggregation algorithms will be savvy enough to join two tables.
----------------------------------------------
Alexandra Swanson, Ph.D.
Ecology & Citizen Science Postdoc
The Zooniverse
University of Oxford

**Comment by mschwamb** [comment]
What you described @aliburchard  is my interpretation of  @camallen  [ticket](https://github.com/zooniverse/Panoptes/issues/886) open in reply to when I opened the ticket, though the issue hasn't closed yet so the feature hasn't been implemented yet.

**Comment by camallen** [comment]
@mschwamb - FYI, the classification dump now contains each classifications associated subject metadata and the retired status of the image for it's workflow. It's may not include all the subjects, depending on what's been classified.

**Comment by mschwamb** [comment]
On 6/15/15 2:16 AM, Campbell Allen wrote:
>
> @mschwamb <https://github.com/mschwamb> - FYI, the classification dump 
> now contains each classifications associated subject metadata and the 
> retired status of the image for it's workflow. It's may not include 
> all the subjects, depending on what's been classified.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zooniverse/Panoptes-Front-End/issues/398#issuecomment-111988587>.
>
Okay thanks, but from experience that isn't completely helpful. It means 
I have unique the subject list to get metdata on the all subjects 
classified. It's been my on-going frustration with the csv data dumps 
that I have to ask or now make using the MongoDB dumps.

the problem ks if I wasn't the person who uploaded the subjects, I don't 
have the number of subjects or info on all of them, which is important 
when a team decides to change tactics or if I want to calculate 
completion counts because all I have is the info related to the subjects 
classified. It means that the team has either have to internally keep 
that information around and handy (but you still won't know the 
Zooniverse subject id for the image). So I still would like to see a 
separate metadata file so I can calculate how many subjects say from a 
given region on Mars have been calculated. With the csv classification 
dump, I wouldn't be able to do that.

**Comment by mkosmala** [comment]
+1

**Comment by chrissnyder** [comment]
Don't know what to do here. Pinging @chrislintott

**Comment by mschwamb** [comment]
This now exists
