### ISSUE TITLE
add functionality to use data from manifest directly in workflow

### ISSUE THREAD

**Issue by ed-hawkins** [zooniverse/Panoptes-Front-End#3980]
## Expected behavior
It would be useful to be able to take information from the manifest for each task and use it, e.g.:
(a) as part of the task, e.g. in the 'main text' area so that the question is slightly changed for each task.
(b) to add default values into the answer text area (e.g. like Orchid Observers) which can be approved or edited.
There are probably other useful features that could be unlocked by enabling such flexibility.

**Comment by eatyourgreens** [comment]
Bumping this because Liz just asked about it in the Oxford Zooniverse Slack.

**Comment by eatyourgreens** [comment]
>(a) as part of the task, e.g. in the 'main text' area so that the question is slightly changed for each task.

This could be achieved with [Liquid templates](https://shopify.github.io/liquid/basics/introduction/#objects), or custom markdown.

```nunjucks
{# Task question as written in the project builder. #}
Is this the log for {{ subject.metadata.location }}?

{# Task question as seen by volunteers. #}
Is this the log for Liverpool?
```

For example, GitHub Docs uses [Liquid and Markdow](https://docs.github.com/en/contributing/writing-for-github-docs/using-markdown-and-liquid-in-github-docs)n to interpolate variables into formatted text.
