### ISSUE TITLE
Polygon tool restricting where points can be placed

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#3983]
## Expected behavior

Polygon tool allowing concave shapes to be drawn. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Polygon tool doesn't allow points to be placed within certain spaces central to the form being drawn (i.e., concave spaces). Is this deliberate? 

## Steps to replicate

from https://www.zooniverse.org/projects/ghthomas/bright-bird
![2 polygon issues](https://user-images.githubusercontent.com/4975655/29232382-f5c4fb40-7eb0-11e7-92c2-913f8d5aa0a6.gif)

## Additional information

- **Operating system:**
- **Browser:**

MacOS Siera, Chrome v60

**Comment by eatyourgreens** [comment]
I don't think this is intentional. It might be a side effect of the polygon being draggable, overriding mouse events inside the shape.

As a workaround, until we figure out how to fix this, you can drag the points of a completed polygon shape into new positions.

**Comment by simoneduca** [comment]
@trouille I can't access the project you linked to. Has it been deleted?

**Comment by trouille** [comment]
it's been renamed to https://www.zooniverse.org/projects/ghthomas/project-plumage

I didn't know it had been renamed, but by going to https://www.zooniverse.org/admin and putting in ghthomas into manage users, I was able to find his new project name.

**Comment by simoneduca** [comment]
Thanks @trouille

**Comment by simoneduca** [comment]
@eatyourgreens I've tried [disabling the draggable module](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/polygon.cjsx#L71) and the issue still persists.
I've also tried to check if somehow the click event doesn't fire when the polygon isn't complete, but the [method that checks marks are inside the boundaries](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/delete-if-out-of-bounds.coffee#L11) still fires properly. So that also seems unlikely as a cause of the issue.

**Comment by eatyourgreens** [comment]
Doesn't the [Draggable component](/zooniverse/Panoptes-Front-End/blob/master/app/lib/draggable.cjsx) still capture mouse events, even if disabled? Have you tried removing it completely?

**Comment by eatyourgreens** [comment]
Maybe clicking inside a drawing tool calls the [`onSelect`](/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/drawing/markings-renderer.cjsx#L80) handler?

**Comment by simoneduca** [comment]
@eatyourgreens thanks for the pointer, but I'm afraid I'm none the wiser regarding `onSelect`. I take that's not supposed to happen. Sorry I'm not familiar with the drawing tools.

**Comment by eatyourgreens** [comment]
I don't think it should happen once the mark is selected and you are drawing. The solution is probably going to be something along the lines of using `pointer-events: none` to ignore mouse events on the polyline element if the polygon isn't complete.

**Comment by eatyourgreens** [comment]
If you have multiple marks, `onSelect` gets called when you click on a mark to select it for drawing.

**Comment by simoneduca** [comment]
Adding `pointer-events: none` to `polyline` while `@props.mark._inProgress` or when `@props.mark.closed` prevents to finish the polygon at all, because no event is firing.

**Comment by eatyourgreens** [comment]
#3875 might be worth looking at.

**Comment by eatyourgreens** [comment]
Looking at the [pointer events docs](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) on MDN, `visibleStroke` or `fill` might work. I don't think the polygon gets filled until it's complete.

**Comment by eatyourgreens** [comment]
Sorry, I meant `painted`, not `fill`.

**Comment by simoneduca** [comment]
Yeah, `painted` is what we want, thank you! PR on its way.

**Comment by hallba** [comment]
Is it known when this fix will be put into the production site? I can still replicate this issue when placing points in my project

**Comment by simoneduca** [comment]
@hallba The PR intended to fix this issue has been merged into production and published already. Which project are you talking about? I can't reproduce the bug anymore, so can please send me the steps to replicate it? Thanks.

**Comment by hallba** [comment]
https://www.zooniverse.org/projects/hallben/send-in-the-clones

I'm still building it but so you can reproduce I've switched from ellipses (which work) to polygons. All the documentation (i.e. tutorial) references ellipses which I'll fall back to unless I can get polygons to work

**Comment by simoneduca** [comment]
I'm able to draw concave shapes. Perhaps you need to delete your browser cache? Which browser are you using?
<img width="151" alt="screen shot 2017-11-19 at 20 55 59" src="https://user-images.githubusercontent.com/8989606/32995444-40c35218-cd6c-11e7-8b14-f99dad5abf4d.png">

**Comment by hallba** [comment]
Sorry for being unclear. I can draw polygons, but when I go to the next step I can't add points within the polygon. I'm not sure how it could be a browser cache issue as I've only started trying this today.

I'm using the latest chrome on win10

**Comment by simoneduca** [comment]
The behaviour you're talking about seems to be a different issue from this one. Would you mind opening a new issue, describing your situation? Thank you.

**Comment by tlalka** [comment]
I also tested the Galaxy Zoo: 3D spiral arm tool, and the Galaxy Builder spiral arm tool and they both have the same problem. 

Neither of those tools allow moving points around after they are placed, so there is no work around for Galaxy Builder, but for Galaxy Zoo: 3D you can use the right click to free-hand the concave sections.
