### ISSUE TITLE
Non-logged-in home page – limit width of content

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#3986]
At very wide screen sizes, the content stretches so far as to be illegible. **Please limit the width of the content to 1440px.** Background color when the viewport is wider than the content should be #D1D5D8 (new color)

Also, please make the "zooniverse works" section just one column.

**Comment by wgranger** [comment]
Hey. Could you provide a bit more info on this, maybe a screenshot? Does width of content mean the entire page? 

Also, the background color should change once wider than 1440px?

**Comment by beckyrother** [comment]
Sorry, I'll mock something up. 

This started because of the two-column layout in "zooniverse works", so if it's possible to start with that and at least limit the width of that div to max-width 50% : 
![zooniverse](https://user-images.githubusercontent.com/1392130/29369816-480778ae-8269-11e7-81ba-6ae5f21a7beb.png)

**Comment by wgranger** [comment]
Ok. This makes sense. It seems the issue is mainly with text being displayed on one or two lines. 

I'm still not sure about the background color. Changing the background to that section above, for example, makes the "classifications so far..." text illegible.

**Comment by beckyrother** [comment]
Ok. Here's what I was talking about re: the background. Please don't hate me, I should have done something for wide screen sizes when I was actually working on this. 
None of this is urgent, so please don't feel like you need to take care of it right away.

![home-wide](https://user-images.githubusercontent.com/1392130/29371749-cc356f82-826e-11e7-8c02-033283a13f4c.png)
