### ISSUE TITLE
SubjectViewer images black (Firefox 55+, Ubuntu & Mint)

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes-Front-End#3989]
## Expected behavior

Subject images load and display on the screen.

## Current behavior

![screenshot-2017-8-16 zooniverse](https://user-images.githubusercontent.com/277/29357122-5c4acf3c-826e-11e7-935b-a3afbafe17ce.png)

## Steps to replicate

* Visit https://www.zooniverse.org/projects/dwright04/supernova-hunters/classify
* See that images are black
* Drag an image, see that it did load them
* Resize the browser window, see that images appear
* Reload, change any CSS in the inspector, see that images appear

## Additional information

- https://www.zooniverse.org/talk/17/419463?comment=699320&page=1
- **Operating system:** Ubuntu 17.04, Linux Mint
- **Browser:** Firefox 55.0.1, Firefox 57 Nightly

**Comment by mschwamb** [comment]
getting the same thing in Mac 55.0.2 (64-bit) for Planet Four: Terrains and Planet Four: Ridges but Comet Hunters looks okay.

**Comment by eatyourgreens** [comment]
Caused by the black CSS background on the subject. See #3995

Seems to be a Firefox rendering bug. Moving the background colour to a different element doesn't fix it.
