### ISSUE TITLE
Ability to specify who the data export csv file gets sent to

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#399]
Right now when you click the download the data export button, it goes to everyone associated with the project.  I think it should only go to the user who's requesting it, rather than everybody such that you're not spamming the science team if you request the data dump a few times.

**Comment by vrooje** [comment]
Does it go to everyone associated, or just the collaborators?

**Comment by mschwamb** [comment]
I don't have anyone else linked in other than on the collaborator setting.
