### ISSUE TITLE
Stats link hidden on Arizona BatWatch

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#3990]
The link to the stats page is almost completely hidden by the example images at https://www.zooniverse.org/projects/zooniverse/arizona-batwatch.

Browser: Chrome 54.0.2840.100
OS: Ubuntu

The problem does not exist in Firefox.

**Comment by srallen** [comment]
This seems specific to Ubuntu as I'm not seeing the issue on Mac OS X. So, whoever takes a look at this will need to debug on Ubuntu or use a VM.

**Comment by mcbouslog** [comment]
I think https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/home/project-home.jsx#L46 needs to be changed to 240px to be consistent with [the `project-home-page__talk-image` class max-height](https://github.com/zooniverse/Panoptes-Front-End/blob/master/css/project-page.styl#L299)?

[staged branch and demo proj here](https://project-home-video.pfe-preview.zooniverse.org/projects/markb-panoptes/bats-and-videos)
![screen shot 2017-08-16 at 12 35 08 pm](https://user-images.githubusercontent.com/12118751/29376807-680e96b2-827f-11e7-8f06-caf68c7091f2.png)


[vs the same proj on master here](https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/bats-and-videos)
![screen shot 2017-08-16 at 12 33 21 pm](https://user-images.githubusercontent.com/12118751/29376743-2e08d6e4-827f-11e7-8339-414ccd26e723.png)
