### ISSUE TITLE
Optimize home page media assets

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#3994]
## Expected behavior
The site doesn't weigh ~10MB on the home page.  
## Current behavior
Some of the home-* images are big, ranging from 781KB to 564KB. Also the featured project image is 239KB. These can all be resized / optimized for the view port.

## Steps to replicate
Open dev tools, turn off caching and look at the network requests for Img assets. 
The reason i was surprised was the cost / weight of data on our logged out home page -
 https://whatdoesmysitecost.com/test/170822_HC_6e97d744f72cdfc2b6439a51c8418afc#usdCost

We should check all our assets are optimized (both size / format / quality) to reduce any network overhead on our site. This should apply for any new PR's that add media assets to the site.

**Comment by simoneduca** [comment]
From https://tools.pingdom.com/#!/etvrvM/zooniverse.org
![screen shot 2017-08-23 at 11 07 16](https://user-images.githubusercontent.com/8989606/29610808-4b8bc360-87f3-11e7-85b1-34e1ec2686b7.png)
Clearly the video size is quite problematic. Can we compress that?
Re. images, couldn't we enforce a max size and automate it with some library, e.g. imageMagik, which we [already used](https://github.com/zooniverse/static-crop) or [tinify](https://github.com/tinify/tinify-nodejs).

**Comment by eatyourgreens** [comment]
Images should be compressed with the [Thumbnail component](/zooniverse/Panoptes-Front-End/blob/master/app/components/thumbnail.jsx), if they aren't already.

We should also ensure that the video doesn't load if you are logged in.

**Comment by camallen** [comment]
the video is 'normally' streamed in the browser (check your dev tools). That said if we can shrink it that would be grand :) It doesn't render on mobile apparently (detects view port size from memory).

![image](https://user-images.githubusercontent.com/295329/29612574-d0bcf3f0-87f9-11e7-8a06-7268a8a06e43.png)

is there a build tool component to optimize images? I am not sure if it can resize the image to the max size we need. This is something we as devs should be aware of and doing our utmost to optimize for our own requirements and checking in code reviews.

**Comment by eatyourgreens** [comment]
Webpack has image optimisation tools, but the Thumbnail component I linked too will also compress our images server-side (and cache the compressed image.)

**Comment by eatyourgreens** [comment]
@camallen I've just checked: one of the steps already in the npm build process is asset optimisation. These particular images are maybe just too large, in pixel size.

**Comment by camallen** [comment]
Interesting, I can't see it anywhere. I checked the webpack config and publisssh. Can you send a link? 

If we can't get that media asset optimization plugin working then i guess we have to do it manually.

**Comment by eatyourgreens** [comment]
@camallen run a build with npm. The last stage, before copying files to S3, is asset optimisation. 

As I said above,  the solution here is to render those images at a more reasonable size with the Thumbnail component.

**Comment by camallen** [comment]
Right - this is what i saw:

<img width="971" alt="screen shot 2017-08-24 at 10 31 56" src="https://user-images.githubusercontent.com/295329/29659901-8cfe4a7e-88b7-11e7-9a93-b5adbc2e6512.png">


I think that is just webpack emitting the matches image assets from https://github.com/zooniverse/Panoptes-Front-End/blob/65207df3b215976f2c076e0158a7021ae350cdde/webpack.build.js#L95 that uses https://github.com/webpack-contrib/file-loader. 

I don't think that does any image optimizations as per https://webpack.github.io/docs/optimization.html, right?

**Comment by camallen** [comment]
Is the plan to rewrite all the static image assets to use the thumbnail server with a computed h.w ?

**Comment by eatyourgreens** [comment]
That's not a bad idea. In theory, `Thumbnail` should take the same attributes as `img` so it might just be a case of replacing HTML `img` tags with React `Thumbnail` components.
