### ISSUE TITLE
Adding ability to easily identify whether the classification is logged in or non-logged in & adding the  Zooniverse ascii username to the csv database dump

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#400]
I downloaded the csv file generated from my project's classifications. I found a few things missing or confusing as someone who will analyze the classifications in part from the raw data. 

There's no easy way that I can I can identify non-logged in volunteer classifications from logged in classifications. Is it if the user id number is negative? It would be nice for a clearer way to show that in the csv file. 

Also I think the actual ascii  Zooniverse username should  be in the csv file. If a volunteer reports a problem like duplicate classifications logged in without the already seen flag, I would have no way to check their classifications because I don't have the key between user id number and Zooniverse username. I've used this in the past with Planet Four and Planet Hunters.

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes/issues/878
