### ISSUE TITLE
slider task state issues

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#4003]
## Expected behavior
clicking up or down arrows in number input increases/decreases value by task step amount

## Current behavior
takes two clicks to increase/decrease value by task step amount, and if click combination of ups/downs input displays value different than `annotation.value`

## Steps to replicate
https://www.zooniverse.org/projects/achmorrison/steelpan-vibrations/classify

Steps here added by @camallen
1. from the number input, use up / down arrows to verify step functionality works as expected (currently a 0.5 step)
0. use your mouse to drag / click around on the slider to change the value while using up / down to step
0. observe step over and step back values being unexpected. 
    + i press up (right) / down (left) and numbers change with strange steps, e.g.
    +  up only results in 4,6,5,7
    +  down 6,8,5,7
0. check submitted annotation differs from the UI value (only happens when the slider is whack)

**Comment by eatyourgreens** [comment]
I can't reproduce this on the dev classifier (Chrome on OSX.) Increasing/decreasing the value of the number input, either with the buttons or the up/down cursor keys, updates the slider and the annotation value.

**Comment by camallen** [comment]
This is the behaviour i can reproduce on Chrome osx and ubuntu 

![slider_bug](https://user-images.githubusercontent.com/295329/29712221-a1e44338-8990-11e7-9f69-069d45db75c5.gif)
