### ISSUE TITLE
help button box opens with scroll not at the top of the content

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4006]
In Firefox and Chrome (latest versions on Mac OS X)  I get that the helpbox is down scrolled all the not at the top, but a few scrolls down. Would it be possible to have the help box open with the scroll bar set to the top? I tried three projects - one was with Chrome the other two were with Firefox  - screenshots below of what pops up right after clicking on the help button. 

<img width="1082" alt="screen shot 2017-08-25 at 8 29 26 am" src="https://user-images.githubusercontent.com/753325/29731843-cdd8f93e-8981-11e7-875c-11b7c53895f2.png">
<img width="1144" alt="screen shot 2017-08-25 at 10 39 18 am" src="https://user-images.githubusercontent.com/753325/29731842-cdd5eabe-8981-11e7-8326-8c09b7a66e64.png">
<img width="1108" alt="screen shot 2017-08-25 at 8 20 56 am" src="https://user-images.githubusercontent.com/753325/29731841-cdd5c5fc-8981-11e7-9b5c-2627fcf7265e.png">

**Comment by eatyourgreens** [comment]
The browser is scrolling down to bring the Close button into view. #4013 should fix it but has the annoying side effect that you can't then scroll the help page up and down with the up/down cursor keys.

**Comment by mschwamb** [comment]
would a better option be to get rid of the close button to allow the up and down cursor functionality? People can hit the x on the top to get rid of it (or does that stop keyboard only uses from exiting?)

**Comment by eatyourgreens** [comment]
#4006 switches dialog boxes to use the close button at the top by default. I think I originally added the close button at the bottom to make closing the help box easier on phones, where scrolling back to the top is a pain. Removing it wouldn't fix scrolling via the keyboard, so I'm tempted to leave it.

I get the impression these popup boxes weren't really designed to hold large amounts of scrolling content. Have you considered adding a field guide to show the examples that are currently in the task help?

**Comment by mschwamb** [comment]
@eatyourgreens I found the field guide is too much for the help content and that the help box was better given the decision tree format.
