### ISSUE TITLE
User links from troubleshooting board are incorrect

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#4016]
## Expected behavior
User links from the boards should resolve to the correct url.

## Current behavior
https://www.zooniverse.org/talk/17/429669?comment=716032
User links resolve to https://www.zooniverse.org/projects/undefined/users/astopy

## Steps to replicate
see the details in https://www.zooniverse.org/talk/17/429669?comment=716032

**Comment by eatyourgreens** [comment]
Just adding that the correct URL in this case would be something like https://www.zooniverse.org/users/camallen

It took me a while to find the broken links. They are in the comment summaries in the discussion list.

**Comment by eatyourgreens** [comment]
Actual bug is that `baseLink` is being incorrectly constructed in `LatestCommentLink`: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/talk/latest-comment-link.cjsx#L73-L75
