### ISSUE TITLE
SpaceWarps Demo: Odd feedback placement & formatting

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4022]
some issues raised in #3858

## Expected behavior
Expect to see feedback callout shapes sized to suit the length of the (wrapped) text.
@simoneduca had something like this
![image](https://user-images.githubusercontent.com/1917970/30084160-2873910a-9289-11e7-888f-a048e4ba457a.png)
seems ok

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
@eatyourgreens & I have seen feedback that is
(1) at the wrong position  
(2) the box is too large (lots of blank space follows the message for both metadata feedback and the default feedback)
such that not all of the feedback message (or none of the feedback message) can be read

![image](https://user-images.githubusercontent.com/1917970/30084286-b046851a-9289-11e7-9d58-aac90930d281.png)
![image](https://user-images.githubusercontent.com/1917970/30084293-ba5bd5d2-9289-11e7-996b-31ec673d93f6.png)

## Steps to replicate
Try out 
https://www.zooniverse.org/projects/aprajita/swdemo/classify?reload=0&workflow=4817

## Additional information

- **Operating system:**
Mac OS X 10.10.5 (14F1808)
- **Browser:**
Chrome
Version 60.0.3112.113 (Official Build) (64-bit)

**Comment by srallen** [comment]
Feedback is going to be worked on again soon. Keeping open in case it's relevant.

**Comment by eatyourgreens** [comment]
This refers to an older version of feedback, so it can close.
