### ISSUE TITLE
SpaceWarps Demo Feedback: Trigger success message for any marker place

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4023]
## Expected behavior
Dud success or fail message for training source to appear in a green or red callout.

## Current behavior
![image](https://user-images.githubusercontent.com/1917970/30084700-5fd2e57c-928b-11e7-9df9-d35ef3acd240.png)

## Steps to replicate
try https://www.zooniverse.org/projects/aprajita/swdemo/classify?reload=0&workflow=4817

**Comment by eatyourgreens** [comment]
Just noting that I've actually missed seeing the feedback message here, because I was expecting it to appear in a coloured box. I think a consistent UI for feedback is very important.

**Comment by eatyourgreens** [comment]
@simoneduca @rogerhutchings would it be difficult to alter feedback so that everything uses the SVG notification box, with a default position either in the centre of the subject, or in the middle at the top?

**Comment by simoneduca** [comment]
It shouldn't be. One can specifiy where the feedback should be displayed. Currently, the feedback for DUDs is displayed as a summary https://github.com/zooniverse/Panoptes-Front-End/blob/fix-sw-feedback/app/classifier/feedback/process-feedback-drawing.js#L20

**Comment by eatyourgreens** [comment]
Great, and does that work for feedback on the single question task too?

**Comment by simoneduca** [comment]
I don't think so. It's set to `summary` regardless https://github.com/zooniverse/Panoptes-Front-End/blob/fix-sw-feedback/app/classifier/feedback/process-feedback-single.js#L16

**Comment by eatyourgreens** [comment]
I think it's important that the interface is consistent here, so drawing feedback and question task feedback should render the same way.

**Comment by simoneduca** [comment]
I agree. I think that is already down as a nice to have in the PR checklist.

**Comment by rogerhutchings** [comment]
Fair enough with moving the feedback message out of the summary. I think I thought it made sense at the time as question tasks don't have any coordinate data associated with them.

**Comment by aprajita** [comment]
the old SW feedback had consistent popups for duds & lens/sims. for duds the message just needs to appear at a nominal position for success (i.e. no marker placed) and at the location of the first mark for a fail (i.e. a marker placed on anywhere on a dud). thanks

**Comment by srallen** [comment]
Feedback will be worked on again soon. Keeping open in case it is relevant.

**Comment by eatyourgreens** [comment]
Feedback displays after the task now, rather than during, so this can close too.
