### ISSUE TITLE
Manually set MIME type for audio subjects being uploaded in project builder

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4029]
## Expected behavior
That the subject created has the correct MIME type of `audio/mpeg` if it's an audio subject.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Chrome uses `audio/mp3` which is non-standard and not recognized by Rails as a MIME type.

## Steps to replicate
Try to use the project builder to upload an mp3 subject. It fails Rails validation. 

## Additional information
Perhaps the code for subject uploading should set the MIME time somewhere in this bit of code: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/partials/subject-uploader.cjsx#L55-L56

Known Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=227004
MP3 MIME type doesn't exist in standard: http://www.iana.org/assignments/media-types/media-types.xhtml#audio

Related to zooniverse/Panoptes#2458

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Just to complicate this, `file -I somefile.mp3` on OSX returns the MIME type as `audio/x-wav` instead of `audio/mpeg`.

**Comment by srallen** [comment]
I noted that in an issue with the python client, too. I think we need to decide if we want to handle this client side or server side. Initial thought was for the client to handle fixing this before the POST to create a subject, but looks like there's some discussion about a server side fix in the associated Panoptes issue.

**Comment by eatyourgreens** [comment]
I played around a bit more with the files that @trouille is trying to upload. They are `audio/x-wav` but other mp3 files report `audio/mpeg`. I'm now wondering if there is an encoding issue with those particular files, and if we should add `x-wav` (if we don't support it already.)

That won't help with the Chrome bug, but it might help with the python client.
