### ISSUE TITLE
Not showing multiple WWT buttons in Safari when volunteer has transcribed multiple figures on the page

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#4033]
In Chrome, you see multiple WWT buttons when you've transcribed multiple figures w/ sky coordinates. 

https://drive.google.com/file/d/0BzeL_TYT7IYPcC03V29hel9jTFU/view?usp=sharing

In Safari, on the other hand, you only see a single WWT button. 

![unnamed](https://user-images.githubusercontent.com/4975655/30291700-48bffc68-96f9-11e7-9569-da7daf7d180a.png)

**Comment by wgranger** [comment]
Tested again on staging and production. This appears to have been resolved and is working as expected on Chrome and Safari browsers.
