### ISSUE TITLE
Pan-and-zoom resets when switching or playing through frames

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#4034]
## Expected behavior
I'm not sure this is expected from a code perspective, but if I've got a multi-frame subject and I use pan and zoom to zoom in on one frame, I expect that switching to the other frame will keep the same zoom/pan.

## Current behavior
Playing through frames or manually switching frames resets the pan-and-zoom tool to the default. It doesn't preserve the zoom in the original frame; if I zoom in frame 1, then switch to frame 2 (where the zoom level resets), then switch back to frame 1, the zoom doesn't go back to the modified version.

## Steps to replicate
I'm seeing this in the latest [PRN project](https://www.zooniverse.org/projects/vrooje/planetary-response-network-and-rescue-global-caribbean-storms-2017/classify).

## Additional information
I'm not sure this is quite the same as #3465 ? Even if the zoom was never intended to be subject-wide, it seems like the zoom level not being remembered from frame to frame is a bug.

- **Operating system:**
OS X 10.11.6

- **Browser:**
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by eatyourgreens** [comment]
I think this is a different bug to #3465 but the solution is probably the same.
