### ISSUE TITLE
keyboard select box appears to be suggesting people should go to next image and not to talk

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4035]
The selection box for keyboard short cuts is highly noticable in chrome and safari for the classification summary. To me this appears to be encouraging a response which is to not explore Talk especially for new users. I think the default should go to the Talk button to encourage people to explore Talk. For P4: Terrains the summary page has been useful for encouraging people to explore Talk more so than the design and setup on the Next and Talk  buttons on Planet Four. 

<img width="1077" alt="screen shot 2017-09-11 at 6 18 13 pm" src="https://user-images.githubusercontent.com/753325/30307972-c7161b96-971d-11e7-9a1e-847354496921.png">

**Comment by eatyourgreens** [comment]
I had a look back through the code history, and that change was added in 499eddc, in April 2016.

Given that it's been present for almost 18 months, and that the classifier is being redesigned and rebuilt, I'm inclined to close this.

**Comment by mschwamb** [comment]
I probably mentioned that then, and the ticket was closed. I see the box around the next button less since it shows up as white dashed in firefox. I was classifying in Chrome and it popped out more so that's why I put the ticket it.  I'll close it.
