### ISSUE TITLE
Re-adding an object to a collection doesn't seem to work

### ISSUE THREAD

**Issue by crowston** [zooniverse/Panoptes-Front-End#4039]
## Expected behavior
An object added and then deleted from a collection can be added back to the collection. 
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Error message: "There are no subjects to add or subjects are already added to My collection."
## Steps to replicate
Add an object to a collection from its talk page. Delete it from the collection (in another page). Add it back again. (In Gravity Spy).

## Additional information

- **Operating system:**
Mac OS X
- **Browser:**
Firefox.

**Comment by srallen** [comment]
Likely race condition, cache, or state that is out of sync.

**Comment by eatyourgreens** [comment]
I think this was fixed by #4250.
