### ISSUE TITLE
Don't let an admin accidentally make a default workflow inactive

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4041]
## Expected behavior
Either don't allow a default workflow to be made inactive in the admin UI or remove it as default when made inactive. Current behavior in the project builder UI is to remove it as default.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Admin UI allows admins to make any workflows active or inactive at will. This can break a project if the default workflow is made inactive.

**Comment by srallen** [comment]
We probably shouldn't allow admins to make default workflows inactive because we should be in conversation with the project owner and collaborators.

**Comment by srallen** [comment]
Alternatively we could warn the admin user what this change will do and ask for confirmation.

**Comment by simoneduca** [comment]
How do you feel about combining both your suggestions: having a check that prevents a default workflow to be made inactive and if whenever that happens an alert would say something like "You can't make a default workflow inactive. Perhaps you could change default workflow first."

**Comment by srallen** [comment]
@simoneduca We can definitely think about what the best UI is for that and I think folks who use the Admin interface the most often should weigh in. Perhaps @mrniaboc would have a preference. 

Also, I think this is going to be on deck for @jelliotartz to tackle in the next week or so. Thanks.

**Comment by mrniaboc** [comment]
I'm generally in favour of admins having as much power as possible, but being super responsible with it. Admins should never change something that will have a major effect on the project without consulting the owner first, but they should be able to do everything the own can.

**Comment by jelliotartz** [comment]
Unless anyone objects, I'll create an alert to display if an admin user attempts to make the default workflow for a project inactive, but will continue to allow this functionality to exist, if the admin user confirms that they want to do it. Happy to consider alternatives if others weigh in :)
