### ISSUE TITLE
Registered volunteer count on home page is low

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#4043]
According to @mrniaboc we have 1,678,753 registered volunteers; the home page shows a lower number. 

Also, please add more space between the number and "REGISTERED VOLUNTEERS" 

![zooniverse](https://user-images.githubusercontent.com/1392130/30438499-fa3bd914-9936-11e7-9251-3e575ef96504.png)

**Comment by camallen** [comment]
seems it gets it from panoptes API https://github.com/zooniverse/Panoptes-Front-End/blob/0f01b973e8d22b814bed4afdcebaa1e8382fedaa/app/pages/home-not-logged-in.jsx#L53

and the api only returns non-ouroboros users for some reason https://github.com/zooniverse/Panoptes/blob/df1c5aef7fba501a73ae3bef5b494afe124b5558/app/models/user.rb#L103

**Comment by camallen** [comment]
I think this deserves it's own end point that has a stored counter that is eventually consistent. Otherwise it's doing a count table scan all the time on a large table and that is expensive db side.

**Comment by eatyourgreens** [comment]
Regarding the styling, looks like this is all marked up in the HTML as headings, even though it isn't actually a heading for the section that follows.
