### ISSUE TITLE
data export by workflow modal not showing all workflows

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#4049]
## Expected behavior
When requesting a data export by workflow, all workflows should be available to be selected.

## Current behavior
NfN has over 100 workflows, only the first 100 are options. "Butterfly_Hummingbird Moths" is over the 100 threshold, and not available for selection.

## Steps to replicate
[link to NfN lab/data-exports](https://www.zooniverse.org/lab/1558/data-exports)
note "Butterfly_Hummingbird Moths" is not available

related to #3904 (# 6)

## Solution
pagination

**Comment by eatyourgreens** [comment]
Could workflows be filtered by name, using something like `react-select`? That would be much better UX than paging through the list to find your workflow (assuming you know the name.)

Filtering might have to be implemented client-side, with a set of paged API queries that fetch all workflows to set up the initial options.

**Comment by srallen** [comment]
A UI like that is proposed to handle the subject set list on the workflow edit page, so I like that idea in this case too. I think we'll have to handle filtering client-side because I doubt fuzzy search is setup for workflows on the API and users would have to know the exact workflow name to get a result if we used the API. 

This might be a good opportunity to try out `react-autosuggest` instead of `react-select`, too.

**Comment by eatyourgreens** [comment]
Sounds good to me. By the way, Panoptes has some sort of text search set up for subject set metadata. It's used to find sets by artist name on https://anno.tate.org.uk/#!/artists. I don't know if that's of any use for the subject set page too? I'd been vaguely thinking about using it to select subjects by borough, or year, from a library of Diagnosis London subject sets, if we went down the route of turning DL into a library of material that could be used in other projects.

**Comment by camallen** [comment]
we can add partial text search for workflows api side if you need them, probably using any_word (https://github.com/Casecommons/pg_search#any_word) or prefixes (https://github.com/Casecommons/pg_search#prefix-postgresql-84-and-newer-only) depending on the use case.

**Comment by srallen** [comment]
Thinking about this some more, we'll still want some sort of pagination for the list of workflows that have exports already requested.

**Comment by mcbouslog** [comment]
Still relevant.

**Comment by mcbouslog** [comment]
Closed via #4370
