### ISSUE TITLE
playthrough of multi-image subjects: a little fast?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#405]
When I click play on a multi-image subject it feels to me like the images cycle a bit too quickly for at least some research cases. 

Example: I've got a set of subjects with (image, inverted_image) apiece, and when I press play it's fast enough that it's 

- unpleasant, to the point where I wondered if I need to put a seizure trigger warning up; and
- hard to get a sense of either image before the next one pops up.

Possibly a longer-term feature might be the ability to tune the play timing for each subject set; but for now I wonder if it could be slowed down just a bit, which I suspect is possible without sacrificing a sense of motion for projects where that's the objective.

**Comment by chrissnyder** [comment]
Tagging as enhancement only because it feels like there is tension here between projects which require the fast swapping to get a sense of motion and those with other purposes for multiple images per subject.
