### ISSUE TITLE
Suggested unknown state for subject's favorite collection status

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4051]
## Expected behavior
Some kind of error/unknown state for the favorites button. Should consult with @beckyrother about design.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Suggested off of Talk: https://www.zooniverse.org/talk/17/439534

**Comment by beckyrother** [comment]
@srallen just trying to understand a use case for this. 

Current behavior is:
• Not added to favorites / no action: grey outline heart
• Added to favorites: Red heart

Suggesting adding another state for when it's not know if the subject is in a favorite – when does this happen?

A grey filled-in heart makes sense to me in that case.

**Comment by srallen** [comment]
@beckyrother If I'm understanding it correctly, it's basically an error state. We have to request from the API to find out if the subject is in the favorites condition. If that request fails somehow because of an interruption of internet service or some other condition, then it's not accurate to have the unfilled heart (the user might think it's unfavorited and try to favorite it), but we also do not know definitively if it is in the collection.

**Comment by beckyrother** [comment]
Got it 👍  

Let's do a grey filled-in heart.

**Comment by eatyourgreens** [comment]
@srallen @beckyrother when collections and Talk pages load, we can't test whether each subject is in your favourites. So their status is undetermined until you click the favourite button.

**Comment by srallen** [comment]
@eatyourgreens oh right that was one of the optimizations for SGL. It used to request on mount, but it was moved to the click handler. The unknown state (grey filled-in) should be then until the button is clicked?

**Comment by eatyourgreens** [comment]
Yes. Clicking it should be able to add a favourite but probably not delete one. 

We should take care that the button doesn't look like it's been disabled.

**Comment by beckyrother** [comment]
Good point @eatyourgreens. Keeping the hover state blue should help make sure it's still clear that it's clickable.
