### ISSUE TITLE
Classifier fails to load when UPP workflow was deleted

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#4056]
## Expected behavior
If the workflow I was previously classifying on has actually been deleted, I should be redirected to whatever workflow is currently set as the default, or else a random workflow if no default is set.

## Current behavior
The classifier fails to load, probably because the API returns a 404 for deleted workflows, as opposed to the 200 that it returns for deactivated workflows. @srallen points out this section of code: https://github.com/zooniverse/Panoptes-Front-
End/blob/master/app/pages/project/index.cjsx#L234

## Steps to replicate
1. Create a dummy workflow
2. Classify in that workflow
3. Delete that workflow
4. Attempt to classify in that project after the workflow is deleted

## Additional information
Here is what happens when you request a deleted workflow with the API client:
![screen shot 2017-09-21 at 10 33 48 am](https://user-images.githubusercontent.com/8491638/30705197-6dbd928c-9eba-11e7-930f-260946a18074.png)
![screen shot 2017-09-21 at 10 33 29 am](https://user-images.githubusercontent.com/8491638/30705196-6db5234a-9eba-11e7-88ed-6a68623fa2d7.png)

- **Operating system:** All
- **Browser:** All

**Comment by srallen** [comment]
The catch for the promise should check for a 404 error code and if it is 404, similarly remove the workflow ID from the UPP and attempt the workflow selection again.

We also need to make sure that if a project builder deletes a workflow that it is removed from the project config as default if the workflow is currently set as default.

**Comment by srallen** [comment]
I'm looking at this today and I even left a TO DO comment about this, so apparently at some point I did think about this. Hah!

https://github.com/zooniverse/Panoptes-Front-End/blob/4a6719f3acbcbd175e655eb730e39e13c8bea2c6/app/pages/project/index.cjsx#L220
