### ISSUE TITLE
"Get invovled" front page button

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#406]
On the new production "preview" site the main button text is misspelled.

**Comment by srallen** [comment]
This was fixed in a PR late last week that was merged in. You can see it on [demo] (http://demo.zooniverse.org/panoptes-front-end/#/), but it looks like the latest merge hasn't been pushed up to the preview site. I would presume it'll get there eventually.

**Comment by vrooje** [comment]
Cool, thanks, I'll keep an eye on it!

**Comment by vrooje** [comment]
Yep, fixed.
