### ISSUE TITLE
workflow editor: new task buttons should be more obvious

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#407]
The "Add task" buttons are really small compared to the other buttons, and formatted differently too. During demos of the project builder it doesn't seem clear to others that these are the main buttons to start with when designing workflows. I think they need reworking in format to draw more attention to them.

**Comment by vrooje** [comment]
Unsure whether to tag @brian-c or @heathv (or both) for this and #408...

**Comment by aliburchard** [comment]
yes please!

**Comment by chrissnyder** [comment]
Going to dump this into https://github.com/zooniverse/Panoptes-Front-End/issues/245 as well, as it's all pretty much design critiques of the workflow builder.
