### ISSUE TITLE
Allow project owner of Zooniverse approved projects  to set the paused or finished status in the project builder

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4071]
Currently only the Zooniverse core team can set this for a project so most projects that are out of data don't ever go to the paused section. Like P4: Ridges has been out of data for months and it shows on the active page.  Same thing with Snapshots at Sea. I have a message up on the project, but it seems like I should be able to in the visibility tab if the project is Zooniverse approved. Another option would be if the out of data message shows to automatically put the project's status to paused. Though I think it would be easier without Zooniverse interaction for a project owner to end a project and change its status to finished.

**Comment by camallen** [comment]
@mschwamb https://github.com/zooniverse/Panoptes/issues/2365 automatically moving projects around would be the best way. Please comment on the backend issue.
