### ISSUE TITLE
SW Demo - classification not recording

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4078]
## Expected behavior
The SW Demo workflows have 'hide classification summaries selected so the classification window should show the "done" and "done & talk" buttons

## Current behavior
Only a 'done' button is available and classification summaries are shown in the next window (see images below)
However, the more key problem is that the classification is not being recorded in the database (see notes below)
Also one can go through the images indefinitely, no 'already seen' flag is shown (this used to happen quickly for this small test set of 16 subjects)
![image](https://user-images.githubusercontent.com/1917970/31176761-dbcc7706-a90b-11e7-9f8f-16e9c32341ec.png)
![image](https://user-images.githubusercontent.com/1917970/31176785-f6c5745e-a90b-11e7-94aa-a594bbcfe800.png)

## Steps to replicate
Launch workflow
https://www.zooniverse.org/projects/aprajita/swdemo/classify?reload=0&workflow=4817

## Additional information
Hi @simoneduca, when trying out the project with @marten today, he noticed that no classification have been recorded since 22 Sept, and "FeedbackMessage"(?) was persistently False in the classifications made before this date.  We both tried to make classifications at the time, some new ones did appear but any training subject with the feedback message shown as the second image above was not recorded, only the non-training subjects were recorded.
 
I think the 2 main points are
- classification summaries are being shown even though this is set to "hide"
- classifications on training images are not being recorded

Not sure what has changed, as I think this workflow used to behave as expected.

- **Operating system:**
OS X 10.10.5

- **Browser:**
Chrome Version 61.0.3163.91 (Official Build) (64-bit)

**Comment by eatyourgreens** [comment]
From a very quick look, [`this.props.completeClassification`](/zooniverse/Panoptes-Front-End/blob/master/app/classifier/task-nav.jsx#L92) is undefined in the handler for the Done button.

**Comment by eatyourgreens** [comment]
Missing an `block` around [line 170 of the classifier](/zooniverse/Panoptes-Front-End/blob/master/app/classifier/classifier.jsx#L169-L171), I think, @rogerhutchings @simoneduca

**Comment by eatyourgreens** [comment]
Could this be related to [my comments on #3769](/zooniverse/Panoptes-Front-End/pull/3769#issuecomment-303356757)? The `isFeedbackActive` logic in the task nav component is different from the logic in the classifier.

**Comment by eatyourgreens** [comment]
NB. feedback on a subject overrides the hide summaries option, which means you can spot the training subjects, since they don't show the Done & Talk button at the end of the classification.

**Comment by aprajita** [comment]
hi @eatyourgreens i'm pretty sure that when i used this previously with
hide summaries and feedback on, i saw 2 buttons 'done' & 'done & talk' for
all subjects whether training or not so it wasn't possible to identify
training images when classifying.

**Comment by eatyourgreens** [comment]
@aprajita that changed in #3769

**Comment by aprajita** [comment]
hi @eatyourgreens i requested for SW to remove the classification summary step as it unnecessarily slows down the classifications. is  #3769 saying that we have to have classification summaries on if we want to show feedback? as you say the training images are an easy spot due to lack of done&talk button, so can both training w feedback & non-training subjects be presented with the same buttons? thanks

**Comment by eatyourgreens** [comment]
Hi @aprajita my understanding of feedback is that if you link your volunteers straight to Talk from the subject, they'll miss the feedback step when they follow that link.

**Comment by aprajita** [comment]
hi @eatyourgreens thanks for explaining that. I've been thinking about how to make training & non-training images look the same, and was wondering whether the following might be possible. For training subjects could the interface be told to show both done&talk and done buttons (as with the normal subjects) but the Done&Talk button does the same thing as the Done button in that it goes for the classification summary page where the feedback is shown and then the options of Talk & Next are visible? This would mean training images wouldn't look any different to the test subjects. Thanks.

**Comment by marten** [comment]
I think that would be confusing to our users.

**Comment by aprajita** [comment]
I think it's much more confusing for the users to see 'done' on one subject, and 'done'+'done&talk' on another, e.g. like we were confused yesterday morning :-)

having the buttons at least look the same on the main classification page the irrespective of subject type would be more consistent. To the user, they just get the feedback before going on to the next subject or going to talk, and can still talk if they want to from the feedback+classification summary page.

Flagging up to the user that this is training image  by the existing difference will I suspect effect the reliability on our classifications and skill assessment, in which case it's better to run the project without feedback at all.

**Comment by marten** [comment]
Having a button that looks indistinguishable from the normal one but doesn't do what it says and what it normally does is really confusing. I think we might need to accept that a workflow can't have hide-classification-summaries enable for any subject if it also does feedback.

**Comment by aprajita** [comment]
OK, but this would only be for ~1:10 subjects though.

If we have to show classification summary pages (that we find confusing and
delaying for a 1 question task), then SW can't run with feedback, which is
a real pity as we think this adds great value to the project in multiple
ways including learning and engagement.

i'll have another think...

**Comment by marten** [comment]
Yeah I really do see the issue. I just don't think that having the Done and Talk button behave inconsistently is the way to go, and if we had to leave the code as-is I'd rather we choose either summaries enabled or feedback enabled. But I'm totally open for any other suggestions, especially since I heard the feedback might also be getting a visual change?

**Comment by aprajita** [comment]
Sure, I understand what you're saying too. Perhaps someone else has another idea?

**Comment by rogerhutchings** [comment]
Just an idea, but what about having feedback display instantaneously? So whenever a user clicks on a known object, you get the popup, which can then be dismissed. The classification summary step is ... sidestepped, and it also solves the problem of having to show multiple feedback messages at the end, since you'd see them as you go along.

This would only work for positive feedback, mind - if you missed something, you'd still need a step at the end to show any known objects.

**Comment by aprajita** [comment]
Hi @rogerhutchings I was thinking about something like that too, but wasn't sure how duds and negative feedback would be handled. This instantaneous pop-up feedback is what we had for the original SW.

For LENS  success & DUD fail messages and instantaneous feedback pop-up would work.
For LENS fail and DUD success the lack of a mark would need to trigger the message, so when the done or done&talk button is pressed, but then that goes back to the confusing step marten mentioned.

**Comment by eatyourgreens** [comment]
One reason that this might be confusing is that 'Done & Talk' isn't a button, but a link to Talk that has been styled to look like a button.

One alternative would be to change that link to an actual button, then write new code for its behaviour on click/enter. The downside of this is that it affects all projects that skip the summary, it's more work to code behaviour that the browser handles natively for links and it's potentially more open to introducing bugs. Also, I'm not completely sure what should happen with feedback: you click Done & Talk, you see the feedback, (something as yet to be specified happens) and the page changes to Talk.

**Comment by eatyourgreens** [comment]
@aprajita how did the original SW handle duds, or expected marks that hadn't been drawn?

**Comment by aprajita** [comment]
>  Also, I'm not completely sure what should happen with feedback: you click Done & Talk, you see the feedback, (something as yet to be specified happens) and the page changes to Talk.

I was thinking the 'done&talk' for trainings would go to the classification summary (as done) where the feedback whether positive or negative is shown, and the standard 'talk'+'next' buttons are available 

> @aprajita how did the original SW handle duds, or expected marks that hadn't been drawn?

I was about to look up the source code for this - I'll report back when I've found it (will be later this evening).

thanks all for your advice & help with this

**Comment by srallen** [comment]
We had a similar issue with Gravity Spy. Gravity Spy is using a very early version of feedback using subject metadata, but also has classification summaries disabled. For the subjects that do have feedback, the message appears as a summary. We decided to have Done and Done & Talk appear for all subjects and to not change functionality of the buttons. The risk is that for a gold standard subject, a volunteer could in theory hit Done & Talk and miss the feedback message. The researchers decided that having this risk was better than having an easy to figure out UI change that indicated the subject was a gold standard subject. 

I don't think this is the long term solution and I think the classifier redesign @beckyrother is working on has a good solution. The task area shouldn't have any links to Talk at all. With @beckyrother's design of the recently classified subjects viewable below the main classification area, a volunteer can go to Talk using that instead. 

Of course, it's going to be some time before we implement this though.

**Comment by beckyrother** [comment]
Hi, thanks for mentioning me @srallen. Hopefully this won't be an issue for much longer as we roll out the classification redesign. (I'm the Zooniverse designer.)

Just want to reiterate that labeling a button one thing and having it do another thing is confusing to users and potentially harmful to your project, as users get frustrated and leave to never come back. As UX designers, we strive to find the clearest possible solution to a problem, and mislabeling buttons is never that.

I like @rogerhutchings's idea as an intermediary until the redesign launches. Since a modal saying you're correct would only show once in a while, it would need very clear language what it is and why it's showing up.

**Comment by eatyourgreens** [comment]
That reminds me: #4031 adds a really simply view showing your recent classifications, linked through to the Talk page for each subject.

**Comment by aprajita** [comment]
the experienced SW users are aware what feedback is and we take great care
in explaining the process and the features when communicating with them.
Instant feedback is key element of keeping them engaged as they don't need
to wait for project scientists to reply on talk, i'm not sure what "it
would need very clear language what it is and why it's showing up." means
but I assure you we think very carefully about writing all our background
information and feedback messages to make the project and feedback clear
and not misleading

as i said @rogerhutching's suggestion is what we had in the original SW but
I discounted form suggesting that yesterday as it's not clear it works in
PFE, particularly as LENS fail and DUD success (that require no click)
would not be triggered at least in the current setup.

The suggestion I made for making 'done&talk' and 'done' to go to the
classification summary where the feedback is currently being displayed for
training images only (so 1:10 subjects) was a suggestion for the current
setup, because I didn't know pop-ups were possible in PFE and there was the
issue of LENS fails and DUD success where no click is made. The suggestion
I made seemed like the only way to get training images presented in a
consistent way with standard subjects, and all feedback displayed whether
they are failures or successes.  If the feedback can be done in another way
then that's good for me.

I think @srallen's point that keep done+done&talk for all images at the
risk of some feedback being missed, as was done for gravtiyspy, is what I
had thought we could live with too, if no other solution is possible. And
I'd prefer that over having the training images being shown without the
done&talk button and therefore easily recognisable. This would also be
preferable to users not getting any feedback on DUD successes or LENS fails
that may not be possible with on-click feedback on training images as
@rogerhutchings suggested.

Anyway, i'll try to locate the relevant bits of the original SW code and
hope to paste that here later tonight.

thanks for all your input & comments.

**Comment by aprajita** [comment]
Hi All

As the original SW is out of subjects, I can't verify the actions below but pls correct me if I'm wrong, it's still possible to view the tutorial 
- the subjects were presented as the images below, the action button was next, deliberately chosen so that the classification stream has the impression that it's quick to move onto the next subject (most subjects viewed would have nothing of interest apart) 
- as soon as the user clicks in the image the next button becomes finished making that would be pressed at the end of marking any features of interest for both training and standard subjects
- for the tutorial, the feedback loop is triggered as soon as the user makes a mark either success or fail depending on the check with the mask. 
- for the training images, I believe 'onFinish' corresponds to pressing the Finish marking button (is that right??), this effectively allows the feedback checks using isLensMarked & nAnnotations to be made and the corresponding message to be displayed whether dud or sim, so not instant as I thought I remembered
- for normal subjects clicking on 'finished marking' would go to the next subject

I guess the training image step above is analogous to having a classification summary shown in PFE if the subject type is training. So no all that different from PFE after all, but please do correct me if I am wrong, originally I thought feedback occurred onAnnotation but I think that's wrong.

As the 'talk' button was always available in this version of SW, there was no issue on how to direct people to talk for non-training subjects that would be the case in PFE without classification summaries. But it had the disadvantage that people could visit talk before making their classifications if I remember correctly.

anyway here are the links:
the original SW code is on github
https://github.com/zooniverse/Lens-Zoo/blob/old-master/app/controllers/classifier.coffee

the feedback check starts at:
https://github.com/zooniverse/Lens-Zoo/blob/88df4bdf5ef4969903bb9f1a8b6ee127e3f5fc21/app/controllers/classifier.coffee#L653

createfeedback is in https://github.com/zooniverse/Lens-Zoo/blob/old-master/app/lib/create_feedback.coffee
    

    
    onFinish: (e) =>
      e.preventDefault()
    
      # Hide remove all button
      @removeAllEl.removeClass('show')
    
       if @isTrainingSubject
        if @feedbackShown
          @tutorial?.end()
          @submit(e)
          return
      
        @feedbackShown = true
      
        # Get the training type (e.g. lens or empty)
        training = @classification.subject.metadata.training[0]
        trainingType = training.type
      
        if trainingType in ['lensing cluster', 'lensed quasar', 'lensed galaxy']
        
          # Get the location for the dialog
          x = (training.x + 30) / @subjectDimension
          y = 1 - (training.y / @subjectDimension)
        
          # Check if any annotation over lens
          for index, annotation of @annotations
            @isLensMarked = @checkImageMask(annotation.x, annotation.y)
            break if @isLensMarked is true
        
          if @isLensMarked is true
            # Lens was marked
            @tutorial = @createSimulationFoundFeedback(e, trainingType, x, y)
          else if @isLensMarked in [false, 254]
            # Lens was missed
            @tutorial = @createSimulationMissedFeedback(e, trainingType, x, y)
          else
            # User's machine triggers errors when checking pixel mask, so move on to the next subject
            @submit(e)
      
        else if trainingType is 'empty'
        
          # Count the number of annotations
          nAnnotations = _.keys(@annotations).length
        
          @tutorial = if nAnnotations > 0 then @createDudMissedFeedback(e) else @createDudFoundFeedback(e)


![image](https://user-images.githubusercontent.com/1917970/31273328-0a11dd9c-aa86-11e7-8727-5906f81c7951.png)
![image](https://user-images.githubusercontent.com/1917970/31273332-11f1fca4-aa86-11e7-9749-f14414f63372.png)

**Comment by aprajita** [comment]
Hi all
Was any of what I posted from the original SW code useful?
Thanks Aprajita.

**Comment by aprajita** [comment]
Hi again

I guess the old SW stuff wasn't very useful so shall we go ahead for SW with done & done&talk on all subjects as done with gravity spy?

Thanks
aprajita.

**Comment by rogerhutchings** [comment]
I'm rewriting the front end code to use modals for all feedback. This way, we don't run into any problems with popup locations, and we can interrupt the current user task (whatever that is) to show feedback, which sidesteps the "Done and Talk" problem.

**Comment by aprajita** [comment]
Hi @rogerhutchings thanks for letting me know. sounds like a good approach although i had to read-up what a modal is ;-)
Will these be able to work for a DUD success or failed LENS when no marker is placed?
Thanks very much!
aprajita.
