### ISSUE TITLE
Error saving favourites

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#4088]
[From a user on Talk](https://www.zooniverse.org/talk/17/450930?comment=753964&page=1):

> I can't save favourites for Camera Catalogue when I press the favourite icon. This has been happening for about a week. Before this there was no problem. The moderator suggested I contact this talk site.

I'm not able to reproduce this with Firefox on macOS. Someone with access to Windows should give it a try. @eatyourgreens also suggested that it could be something to do with the number of subjects favourited by the user, so that's something else to investigate.

## Additional information

Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by eatyourgreens** [comment]
Favourites are created by [adding a link to the collection resource](/zooniverse/Panoptes-Front-End/blob/master/app/collections/favorites-button.jsx#L64), so I wondered if that runs into problems when the links array becomes large.

**Comment by simoneduca** [comment]
Browser reported by user: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0

**Comment by simoneduca** [comment]
I can't reproduce on FF either. I've asked the user on the thread if it's still an issue. If it is, I'll try Jim's suggestion.

**Comment by simoneduca** [comment]
No reply from the user yet. I still can't reproduce the issue. I've tried to add a favourite in a project with no previous fav subjects, deleted the collection and then try again without noticing anything odd.
Still, the [relevant code](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/collections/favorites-button.jsx#L54) _does_ seem to be incorrect, as it doesn't check for the uniqueness of the favourite collection. Uniqueness of the fav collection is per project and, although not currently enforced, is an API requirement. I'm not sure how to go about that.

**Comment by simoneduca** [comment]
It's worth noticing that [trying to fetch any existing fav collection](https://github.com/zooniverse/Panoptes-Front-End/blob/bdfc2c049c473b2864b1eb069f4db30f4ca34b81/app/collections/favorites-button.jsx#L53) returns a 200 status with an empty collection array.

**Comment by eatyourgreens** [comment]
@simone if you try adding a subject to an existing favourites collection, but simulate an error from the API in the promise chain, I think the code will happily give you two favourites collections for that project, which a volunteer had reported as a bug on Talk. I don't have the link but they had ended up with something like 3 favourites collections for a project that they contribute too.

Looking back through the conversation on this issue, that's a different bug from the one that's been reported here.

**Comment by simoneduca** [comment]
Also passing any of a project's property in the fetch a call other than `id` still returns a 200 status.

**Comment by simoneduca** [comment]
> Looking back through the conversation on this issue, that's a different bug from the one that's been reported here.

That seems to explain both mine and James' confusion.
I'm failing to simulate an error. Short of go offline and try to mess the parameters in the fetch call I don't know what to do. Any advice @eatyourgreens? thank you.

**Comment by eatyourgreens** [comment]
```
e = new Error('A fake API error');
e.status = 422;
throw e;
```

**Comment by eatyourgreens** [comment]
>It's worth noticing that trying to fetch any existing fav collection returns a 200 status with an empty collection array.

That's a bug. If a favourites collection exists, it should be returned in the API response and used. A new one should only be created if one doesn't exist.

**Comment by simoneduca** [comment]
Sorry, no. That was poor wording from me. My English still breaks sometimes. I meant that when no fav collection exists, an empty array is returned.

**Comment by eatyourgreens** [comment]
If there's an API error does
```
createFavourites().then(favourites => …).catch(error => …);
```
catch the error, or does the `then` block get executed regardless?

**Comment by simoneduca** [comment]
It gets executed regardless. See with your suggested fake error:
<img width="529" alt="screen shot 2017-12-04 at 12 44 42" src="https://user-images.githubusercontent.com/8989606/33553521-00d4bb48-d8f1-11e7-8a7b-db8ee7a1d827.png">

**Comment by simoneduca** [comment]
But I'm still not managing to create more than one fav collection per project.

**Comment by camallen** [comment]
@simoneduca this seems like a bug, https://github.com/zooniverse/Panoptes-Front-End/issues/4088#issuecomment-348947385

We should just invert the problem and ensure the api / db enforces uniqueness of favourite collections per project. @simoneduca happy to pair with you on this.

**Comment by astopy** [comment]
Closing since no one could reproduce this and the user never did reply.
