### ISSUE TITLE
org landing details section follow-up

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#4089]
this is issue is specific to the sections below the organization affiliated project cards section.

- [x] stats section functionality
- [x] about section clean-up
- [x] links section functionality
- [x] researcher quote, cycle through projects' researcher quotes

see PR #4037 
continuation of Issue #2970

**Comment by beckyrother** [comment]
Looks great! Thanks Mark!

**Comment by beckyrother** [comment]
Re: your Slack question about quotes – Let's cycle through the project quotes, possibly with a link to each project from that researcher's name. So every time the page reloads it displays a random quote.
