### ISSUE TITLE
Panoptes preview: getting 403 when uploading avatars/images

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#409]
On the non-demo site, tried uploading an avatar image to my own account, then a project avatar and background. Got a 403 each time. 

![screen shot 2015-05-25 at 22 55 30](https://cloud.githubusercontent.com/assets/2357126/7802603/36fcd536-0331-11e5-939d-6a7136bb6fc7.jpg)

**Comment by aliburchard** [comment]
Me too!! Why is this happening??

**Comment by edpaget** [comment]
I know what's up with this sorry. It'll be fixed shortly.

**Comment by edpaget** [comment]
This should be fixed now. You may have to log out and back in.
