### ISSUE TITLE
Brand guidelines / Press page

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4091]
## Expected behavior
It's been suggested to create a Press / Brand guidelines page for press and researchers. This should include basic style guide information and resources like the Zooniverse logo that can be used for print or web.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
We only have the github Brand repo, but this isn't a great place to point people just looking for information.

cc @beckyrother

**Comment by beckyrother** [comment]
This is a hack day project, right? I need to spend some time creating a style guide that's suitable for the public.

**Comment by srallen** [comment]
Yeah this can definitely be done on a hack day or during a maintenance week.
