### ISSUE TITLE
Percent complete disagreement between pages

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#4093]
On Treeversity (https://www.zooniverse.org/projects/friedmaw/treeversity), we see 0% and 1% done on the front page and stats page respectively:

![image](https://user-images.githubusercontent.com/1066340/31517781-011557ac-af6b-11e7-8414-74720221a67e.png)

![image](https://user-images.githubusercontent.com/1066340/31517835-1c9b4716-af6b-11e7-9084-cca8f20de3f5.png)

**Comment by camallen** [comment]
@mkosmala the project completeness metric can differ from the workflow metric as explained here, https://www.zooniverse.org/talk/17/323668?comment=547712.

That workflow is set to use the classifications count over the subject space for completeness metric. The project metric is retired subjects ratio instead.

**Comment by mkosmala** [comment]
I see. I think it would be better if the project completeness bar were done as number of classifications. The number of subjects done is already in the lower right corner. And it's sad to say that with almost 2000 classifications, the project is 0% done. We want to encourage the volunteers!

**Comment by camallen** [comment]
@mkosmala - the backend completeness metric was the original version and now we can reflect on the workflow config to change this behaviour. Please comment on the linked panoptes api issue instead.
