### ISSUE TITLE
Drawing sub-task does not display correctly when using flip-book for multiple subjects and cloning markers

### ISSUE THREAD

**Issue by tingard** [zooniverse/Panoptes-Front-End#4094]
## Expected behavior
You should be able to open the sub-task from whatever frame in the flip-book you are on, when workflow has chosen to enable cloning markers in all frames. 

## Current behaviour
Sub-tasks only open on the flip-book panel which they were create on.

## Steps to replicate
Set `workflow.configuration.multi_image_clone_markers = true` in dev classifier config.

Go to `/dev/classifier`, "Draw Stuff", draw Circle on one subject and switch to next.
SVG shape is correctly visible and can be selected and moved, but sub-tasks will not display.

## Additional information
Tested on MacOS Sierra 10.12.6, Chrome 61.0.3163.100 (Official Build) (64-bit)

**Comment by eatyourgreens** [comment]
Linked to #3132.

**Comment by tingard** [comment]
This will probably become relevant again soon.
