### ISSUE TITLE
Issue uploading audio/image subjects

### ISSUE THREAD

**Issue by anaelisa24** [zooniverse/Panoptes-Front-End#4097]
## Expected behavior
I should be able to upload from python code subjects that include both image (spectrograms) and audio.  
## Current behavior
However, they get uploaded as empty subjects. I was able to upload audio files from the project builder in Firefox (couldn't do it using Chrome), but the project builder does not allow us to upload both image and sound together for one subject. Also, we need it to work through coding.

The code used now is 
subject.add_location({'audio/mp3': ('/Users/.../0a0625f4dba80e60e7bb4e37114f744f.mp3')})
subject.add_location({'image/png': ('/Users/.../0a0625f4dba80e60e7bb4e37114f744f.png')})

This adds both mp3 (also tried using audio/mpeg as format) file and image as one subject (I can see them in the project builder) but they come empty.

## Additional information

- **Operating system:** MacOS Sierra version 10.12.6
- **Browser:** Google Chrome and Firefox

**Comment by camallen** [comment]
Hi @anaelisa24 

Don't add the mime type in as this stipulates the media resource is hosted externally by you. Instead can you try and add the local media resources normally using `add_location`, e.g.
```
subject.add_location('/Users/.../0a0625f4dba80e60e7bb4e37114f744f.mp3')
subject.add_location('/Users/.../0a0625f4dba80e60e7bb4e37114f744f.png')
# add metadata if you need
subject.metadata['my_id'] = 'meta'
...
subject.save
```

**Comment by anaelisa24** [comment]
I run the following code for the png file and it works, but when using it with the mp3 file it won't work. Code:

subject.add_location('/Users/.../0a0625f4dba80e60e7bb4e37114f744f.mp3')
subject.metadata['image_id'] = 1
subject.metadata['image_title'] = 'Audio 1'
subject.save()
subject_set.add(subject)

The message error I get is PanoptesAPIException: Validation failed: Locations is invalid

**Comment by camallen** [comment]
can you run `file -I your_file_name.mp3` on that file and paste the resulting information? 

Looks like the mime type might be incorrectly detected, this issue has more details https://github.com/zooniverse/Panoptes/issues/2458#issuecomment-328888232

**Comment by anaelisa24** [comment]
This is what I get audio/mpeg; charset=binary

**Comment by anaelisa24** [comment]
I went through the other issue before posting here and it's how I figured out that using Firefox I could upload the files through the Project Builder. However, for our project it won't be enough to upload using the project builder only. We need it to work using the python client.

**Comment by eatyourgreens** [comment]
Hi @anaelisa24 the Project Builder does allow you to upload more than one file per subject. The files have to be listed in a manifest CSV file, which you then drag into the project builder. There are instructions for creating a manifest at the very bottom of the [Project Builder help page](https://www.zooniverse.org/help/). I think @yli has successfully used this approach to set up his audio project.

Chrome has a bug which prevents it from correctly identifying mp3 files, but the manifest should work in Firefox.

**Comment by anaelisa24** [comment]
Well, I haven't been able to upload the manifest through either of them. But I need this to work using python. And that isn't working. It gives the PanoptesAPIException: Validation failed: Locations is invalid error.

**Comment by eatyourgreens** [comment]
I've sent @li-yp a private message on [Zooniverse](https://www.zooniverse.org/users/yli). He has successfully uploaded audio files for a project, so perhaps he can see something that's missing from your code.

**Comment by li-yp** [comment]
Hi @anaelisa24 , I definitely have seen the locations is invalid error before, when I tried to use the Panoptes frontend for uploading audio files. It is also not working with Chrome as @eatyourgreens said. I don't have any problems uploading audio files with Firefox though. 

I am also able to upload multiple files per subject using the Project Builder with Firefox. One sample manifest file looks like this:

subject_id     !audio_name     !image_name
1                    a.mp3                  a.png

Hope this helps.

**Comment by anaelisa24** [comment]
Hi @li-yp, for some reason I’m not able to upload the files through the manifest file either. The problem is, for the purpose of pur project, we need it to work with the Panoptes frontend. I am able to upload audio files using Firefox but without a manifest. With the manifest it tells me that the subjects found are not ready to upload because it can’t find the files, even though they are in the same folder as the manifest.

**Comment by eatyourgreens** [comment]
@anaelisa24 could you post an example of your manifest? Just the first two or three lines should be sufficient.

**Comment by anaelisa24** [comment]
This is the file

![screen shot 2017-10-18 at 12 30 51 pm](https://user-images.githubusercontent.com/32212520/31730542-3b6a81f4-b400-11e7-9328-c89123ad8c3b.png)

This is the response

![screen shot 2017-10-18 at 12 31 32 pm](https://user-images.githubusercontent.com/32212520/31730565-4e23d1ce-b400-11e7-8e5a-73009aba12c2.png)

**Comment by li-yp** [comment]
@anaelisa24 I was never able to upload audio files using the Panoptes frontend, let alone uploading both audio file and figure in one subject. Luckily for me, uploading using Firefox is sufficient.

**Comment by anaelisa24** [comment]
@li-yp can you see any reason why my manifest file is not working?

**Comment by li-yp** [comment]
@anaelisa24 I don't see any issue with the manifest. But my experience is limited and @eatyourgreens will have the verdict. It also seems that there is some media type recognition issue in the frontend. But again I am not very sure about this.

**Comment by srallen** [comment]
@anaelisa24 could you share a sample subject, an image file and audio file set, with us for debugging?

**Comment by anaelisa24** [comment]
This zipfile has one subject (image and audio)

[Archive.zip](https://github.com/zooniverse/Panoptes-Front-End/files/1398885/Archive.zip)

**Comment by eatyourgreens** [comment]
Thanks @anaelisa24 I am able to reproduce the same error when I try to upload a manifest for those test files.

My manifest is very simple:
```csv
ID, image, audio
1, 20d135f0f28185b84a4cf7aa51f29500.png, 20d135f0f28185b84a4cf7aa51f29500.mp3
```

![Screenshot of the uploader after parsing the manifest, reporting that both subject files are missing.](https://user-images.githubusercontent.com/59547/31819144-3f7869d4-b593-11e7-8a9a-ae0c6983a224.png)

**Comment by eatyourgreens** [comment]
Thanks for taking the time to look at this @li-yp. Like you, I can see nothing wrong with the manifest and am baffled as to why the files are not found. I'm running OSX 10.11.6.

My only guess is that there is some issue with the filenames not being recognised, but I don't know why that would be.

**Comment by eatyourgreens** [comment]
My only suggestion at this point would be to upload the manifest using the [python command line client](/zooniverse/panoptes-cli), and see if that gives the same error.

**Comment by eatyourgreens** [comment]
I'm unable to upload photos from the manifest for the demo Kitteh Zoo project either, so I think this is a more general problem than being unable to upload mp3 files.

![Screenshot showing Kitteh Zoo subject files listed as not found in the uploader.](https://user-images.githubusercontent.com/59547/31826042-daa560ca-b5ab-11e7-89fe-0c84204e1d48.png)

**Comment by anaelisa24** [comment]
I will definitely try to upload the subjects with the manifest through the python client. But if that doesn't solve the problem, we run out of options.

**Comment by eatyourgreens** [comment]
@anaelisa24 It turns out I misunderstood the instructions for the file uploader in the project builder.

If I select all the files that I want to upload (image, audio and manifest) it works for me in Firefox.
![screenshot showing all files correctly selected for upload in the project builder.](https://user-images.githubusercontent.com/59547/31827807-6a4d0a76-b5b0-11e7-8ffc-a20b4ee9a6b3.png)

Previously, I was just selecting the manifest file and assuming that the code would automatically find the image and audio files, which is what the python CLI tool does.

**Comment by camallen** [comment]
@anaelisa24 make sure you have the latest code, install from github as per https://github.com/zooniverse/panoptes-python-client#installation

Also if uploading via the python client you we have a dependency on libmagic, make sure this is installed. I'm going to try to reproduce your code on the test data to using my python client.

**Comment by camallen** [comment]
@anaelisa24 i've just got it working with the latest python client (install via git) and libmagic. Without libmagic you'll get the locations invalid error.

If you are on a mac `brew install libmagic` (other operating systems are available). My code was the same as yours:
```
# add a new multi image subject
subject_set=SubjectSet.find(SUBJECT_SET_ID)
project = Project.find(PROJECT_ID)
subject = Subject()
subject.links.project = project
subject.add_location('mp3_data/20d135f0f28185b84a4cf7aa51f29500.mp3')
subject.add_location('mp3_data/20d135f0f28185b84a4cf7aa51f29500.png')
subject.metadata['image_id'] = 1
subject.metadata['image_title'] = 'test png / mp3 upload'
subject.save()
subject_set.add(subject)
```

This should get your working from python :)

**Comment by anaelisa24** [comment]
Yes! Got it working now! Thanks so much!
