### ISSUE TITLE
Workflow version numbers seem a little big

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#410]
Just wanted to make sure this isn't a bug... I think the numbers are increasing correctly but they just seem really huge.

![screen shot 2015-05-26 at 01 07 48](https://cloud.githubusercontent.com/assets/2357126/7803297/b805fbe6-0343-11e5-9ee5-3d18b950be37.jpg)

**Comment by aliburchard** [comment]
Yeah - this has also been raised as a question by some users...

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes/issues/883
