### ISSUE TITLE
Panoptes preview site: getting 401 when trying to delete a subject set

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#411]
![screen shot 2015-05-26 at 11 49 47](https://cloud.githubusercontent.com/assets/2357126/7810842/77532dee-039d-11e5-9763-30f9e8eb6cf2.jpg)

**Comment by vrooje** [comment]
Hmm, hang on, I reloaded the page and all was fine. Timeout, maybe?

**Comment by aliburchard** [comment]
This is working for me now -- Brooke - is this fixed for you?

**Comment by chrissnyder** [comment]
Same comment as https://github.com/zooniverse/Panoptes-Front-End/issues/429 @vrooje @aliburchard
