### ISSUE TITLE
Possible pagination bug in the project team list

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#4111]
## Expected behavior
All added team members should appear in the list.

## Current behavior
There's a limited number of team members appearing in the list - the list is longer than the text on the About page. Neither me (yshish) nor AvastMH are displayed there although we both have been added as moderators in Seabird Watch project but there may be even more project members missing: https://www.zooniverse.org/projects/penguintom79/seabirdwatch/about/team

## Steps to replicate
Click on the link above?

## Additional information
It seems to be a problem with pagination. 
Also, it would be great to have us displayed in the list before the launch (today 8pm - Oxford time) ;)

- **Operating system:**
Ubuntu

- **Browser:**
Chromium

@eatyourgreens Please, could you check that? Thanks! :)

**Comment by srallen** [comment]
@yshish thanks for bringing this to our attention. The fix for this will be up before airing.
