### ISSUE TITLE
add both image and audio to examples on surveys

### ISSUE THREAD

**Issue by anaelisa24** [zooniverse/Panoptes-Front-End#4115]
## Expected behavior
We would like to upload as examples of sounds in our survey task the spectrogram with its corresponding sound. By now all we can show is an image, but for our project, we would like for our users to be able to test different sounds so they can make sure they are selecting the right answers.

## Current behavior
Only images are shown in the survey
## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
This has come up for Gravity Spy too.
