### ISSUE TITLE
Drawing tool focus interacting oddly with the subject image.

### ISSUE THREAD

**Issue by simensta** [zooniverse/Panoptes-Front-End#4123]
## Expected behavior
The drawing tools should be able to hold focus without distorting or moving the image. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
[Volunteers are reporting the following](https://www.zooniverse.org/projects/zooniverse/decoding-the-civil-war/talk/465/463612?comment=773823):
- "the rectangle pushes the text to be transcribed out of the way"
- "also scrolling off"
- "Entire page scrolls (jerks) down to show the entire page header."

## Additional information

- **Operating system:** Windows _(I need to confirm)_
- **Browser:** Chrome, FireFox

**Comment by mcbouslog** [comment]
Here's a GIF of the page jumping:
![test1](https://user-images.githubusercontent.com/12118751/32118045-fb86c1b6-bb15-11e7-9a04-9c7913e6a9bf.gif)
Apologies as I tested on DCW, but did not scroll down and add lines.
I think it's related to [the `@root.focus()` here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/root.cjsx#L52).
Can we send focus to the place where we've clicked?

**Comment by mcbouslog** [comment]
mentioning @eatyourgreens
