### ISSUE TITLE
##Current Behavior

### ISSUE THREAD

**Issue by marckuchner** [zooniverse/Panoptes-Front-End#4129]
## Current behavior
_Please include any error messages from the browser console and/or screenshots_

## Additional information

- **Operating system:**
- **Browser:**

**Comment by marckuchner** [comment]
Dear Zooniverse,

One of my advanced users sent this complaint about Backyard Worlds: Planet 9.

Marc

__________
---------- Forwarded message ----------
From: vinod thakur <vthakur303@gmail.com>
Date: Tue, Oct 31, 2017 at 11:52 AM
Subject: Persistent problem of Flipbooks are not functioning properly
To: backyardworlds <backyardworlds@googlegroups.com>


Since Oct 26/27 flipbooks have not been functioning properly when I zoom in 
They flip to the upper left corner after one mark is put on the page (on cellphone )

**Comment by astopy** [comment]
@marckuchner Could you find out if this is still a problem? #4267 may have fixed it.

**Comment by eatyourgreens** [comment]
I think this was fixed by #4125, back in October.

**Comment by astopy** [comment]
Ok, I'll just close this for now and we can reopen if it's still an issue.
