### ISSUE TITLE
Creating a collection in a project context gets the wrong project id

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4139]
## Expected behavior
The collection create form within the project context should use the project id of the project you're in the context of. The collection create form should probably include in its UI a message that the collection will be linked to the project you're viewing.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Viewing a collection in a project context means the collection is linked to that project. Usually you'd expect all the subjects in that collection to be from that project, but we do not validate this. Any subject from any project can be linked to a collection. Consider this collection that is linked and being viewed within the project context:
https://master.pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats/collections/wgranger-test/test-collect

It contains subjects from other projects. If you click the collection manager button, the collection create form is using the project id presumably from the default subject.

**Comment by srallen** [comment]
Related to this issue is that project ids, likely from the default subject, are being used outside of the project context too for the form: https://master.pfe-preview.zooniverse.org/collections/zootester1/hello-cats

If you're creating a collection outside of a project context, it should not be linked to any project.

**Comment by srallen** [comment]
@jelliotartz could you take a look at this while working on implementing the description field for the form?

**Comment by jelliotartz** [comment]
Sure, no problem! :)

**Comment by jelliotartz** [comment]
I've been working on isolating specific issues that are problematic regarding collections and projects, and have a few questions:

Scenario 1:
A user is on a collection page that is not in a project context. They click the CollectionsManagerIcon on a subject, to create a new collection. Should this new collection get the project context from that subject's project?

if yes, follow up: what if user selects multiple subjects, from different projects?

Scenario 2:
A user is in a collection that is in a project context (let's call it Collection A, in Project B). User selects 2 subjects from Collection A, but they are NOT subjects from Project B, and wants to create a new collection. Should the new collection be linked to Project B?

follow up: what if both subjects are from the same (separate) project? Link to that project? what if they are not?

**Comment by eatyourgreens** [comment]
> Should this new collection get the project context from that subject's project?
Subjects can belong to more than one project too, just to make this more complicated. In practice, I don't think anyone has yet used this feature of Panoptes. A practical, but still theoretical, use case might be two projects sharing a subject set within the same organisation.

**Comment by camallen** [comment]
Good point about subject re-use @eatyourgreens. To clarify a subject has an uploading ("owning") project in it's resource response (project_id). I don't think you can rely on this to gaurantee the context a subject was collected in tough as Jim outlined.

**Comment by srallen** [comment]
I don't think this should be overthought. A subject can belong to more than one project or collection, but I'm going to guess that the expectation is that if you're in a project context, either by classifying, using talk, or looking at collections in a project context, that any new collection made would be linked to that project. If you aren't in a project context, then the collection is not linked to a project. Right now the behavior in a project context is that the new collections are being linked to the project that the default subject belongs to which just seems incorrect and unexpected to me. I don't think an individual subject should determine the collection's project linking at all.

**Comment by camallen** [comment]
> Right now the behavior in a project any context is that the new collections are being linked to the project that the default subject belongs to which just seems incorrect and unexpected to me. I don't think an individual subject should determine the collection's project linking at all.

Agree - the context of the collection should determine the project links to the collection on create. If there is no project context (how would this happen in the UI?) then we don't link it to a project i guess.

**Comment by srallen** [comment]
Collections can be browsed here too: https://www.zooniverse.org/collections or from a user's profile (like https://www.zooniverse.org/collections/srallen) which is outside of any project context. Most volunteers don't use this route, however, because we don't have any sorts, filters, searches, etc present in the UI to make it useful.

**Comment by camallen** [comment]
cool cool, i can't create a collection from there can i?

**Comment by srallen** [comment]
No, not from the collections list view, but you can select a collection to view its subject and each subject has the button to add to an existing collection or to create a new one starting with that subject.

**Comment by camallen** [comment]
good to know :) thanks for the feedback and sorry to take this off topic.

**Comment by mcbouslog** [comment]
it looks like there are two ways to create a collection - 1) through collection manager icon in the lower right of the subject viewer or 2) through the Add to Collection button that shows once you've selected one or many subjects from within a collection, and it's inconsistently passing a project to the collections create form.

for example, here's a Bug collection within a Bug project 1781: https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/calbug-bee-flies/collections/markb-panoptes/bugs

within this collection are two plant images added from a different Plant project 1789.

A. creating a new collection, from within the Bug project, via the Add to Collection button 2) creates a new collection linked to the Bug project, regardless of subject owning project. - cool

B. creating a new collection, from within the Bug project, via the subject viewer icon 1) creates a new collection linked to the Plant project (subject's owning project). - not cool, [should be fixed here](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/collections/show-list.cjsx#L38) to link to Bug project. and Bug project is not necessarily the originating collection's linked project, but the project context

C. creating a new collection, from within from the user's collections, via the Add to Collection button 2) creates a new collection unlinked to any project. - cool

D. creating a new collection, from within from the user's collections, via the icon 1) creates a new collection linked to the Plant project 1789 (subject's owning project). - not cool, should not link any project to new collection

So I think how project is getting passed around when creating a collection via the icon in the subject viewer needs to be the focus here? Without breaking how it works within the classifier of course.

**Comment by eatyourgreens** [comment]
@mcbouslog does creating a new collection work from the Recents page?
https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/calbug-bee-flies/recents

I never checked that when I set it up.

**Comment by eatyourgreens** [comment]
From memory, the project context is passed to that collections button via the subject viewer, so that's probably where things are going wrong.

**Comment by srallen** [comment]
> So I think how project is getting passed around when creating a collection via the icon in the subject viewer needs to be the focus here? Without breaking how it works within the classifier of course.

Yep

**Comment by mcbouslog** [comment]
@eatyourgreens - yep new collections work from recents

**Comment by eatyourgreens** [comment]
@mcbouslog Great! The Recents view actually [fakes a Subject resource](/zooniverse/Panoptes-Front-End/blob/master/app/pages/profile/recents.jsx#L41-L44) so I wasn't sure if that would still work. Looking at the code there, `project` is passed into the Subject Viewer as a prop in its own right.

**Comment by jelliotartz** [comment]
Fixed via #4146, so closing this issue.
