### ISSUE TITLE
Registering for a Zooniverse Account Don't Have a Sign Up for Being a Beta Tester

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#415]
Hiya, 
This might be something already decided internally, but I noticed that the register pop-up box doesn't have an option to sign up to be a beta tester. Maybe that's being done differently now, but I thought I'd mention it.

**Comment by mschwamb** [comment]
Should mention what I'm referring to from the  Ouroboros signup box. It says 'I would like to receive notices with opportunities to test and provide feedback on unreleased Zooniverse projects.' - Maybe that was just about getting newsletters and not beta tests?

**Comment by chrislintott** [comment]
Nice catch - @mrniaboc I assume this is still needed?

**Comment by mrniaboc** [comment]
Yes, it would be good to have that option present. That way we can keep the beta list fresh.

**Comment by mschwamb** [comment]
@chrislintott  Should this get labeled as for first release?  The preview site doesn't have an option for signing up to participate in betas?

**Comment by camallen** [comment]
@brian-c the backend now allows the beta_email_communication field to be set on signup and user updates since https://github.com/zooniverse/Panoptes/pull/948
