### ISSUE TITLE
One you select a tutorial for your workflow there is no way to unselect and not have a tutorial

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4155]
I tried unclicking but it doesn't work (in my case I do want the tutorial), but if someone was trying out a tutorial while building a project and then decided they didn't want a tutorial there's no way to uncheck it. There should be a button or something for no-tutorial if you decide later to not have on. 

<img width="507" alt="screen shot 2017-11-13 at 9 03 21 pm" src="https://user-images.githubusercontent.com/753325/32767305-e14c96dc-c8b6-11e7-98e7-63d5f20ad7fa.png">

**Comment by eatyourgreens** [comment]
Solution here is to add a radio button for a `No tutorial` option.

**Comment by eatyourgreens** [comment]
Should be fixed by #4169
