### ISSUE TITLE
Points cannot be added within a previously placed polygon

### ISSUE THREAD

**Issue by hallba** [zooniverse/Panoptes-Front-End#4165]
## Expected behavior

The workflow consists of first drawing a polygon, then placing points within the polygon.

https://www.zooniverse.org/projects/hallben/send-in-the-clones

## Current behavior

Points cannot be placed within polygons. If an ellipse is used instead of a polygon, points can be placed successfully.

## Steps to replicate

Run the workflow in https://www.zooniverse.org/projects/hallben/send-in-the-clones

## Additional information

- **Operating system:**
Win10
- **Browser:**
Chrome

**Comment by eatyourgreens** [comment]
Caused by #4076, I think.

**Comment by simoneduca** [comment]
I'll have a look.

**Comment by eatyourgreens** [comment]
Hopefully fixed by #4171
