### ISSUE TITLE
API token used for Talk-API not refreshed correctly in all cases

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes-Front-End#4179]
I think the token used for API calls to talk.zooniverse.org does not get refreshed when it's expired, unless you actually go to Talk. This causes an issue when you have an old tab open, and go from anywhere but Talk over to your private messages. At this point, it seems that PFE keeps using the expired token to make the API call to https://talk.zooniverse.org/conversations. This causes the Talk-API to reject the request with an HTTP 401 status.

This 401 status in turn is not handled correctly by PFE, which just assumes that this means you have no private messages, rather than showing an error message.

## Expected behavior

Clicking on "Messages (1)" lists my private messages, with one conversation marked as unread.

And secondarily, any authentication errors should be messaged accordingly to the user, rather than assuming an empty response body.

## Current behavior

The page I get to when I click on "Messages (1)" tells me I don't have any messages.

![image](https://user-images.githubusercontent.com/277/33217609-80b59cba-d130-11e7-8360-eccc9ff29fa1.png)

The console explains what's going on:

![image](https://user-images.githubusercontent.com/277/33217870-f157e3e6-d131-11e7-90a8-81a523fa149e.png)

Refreshing the page once here loads the messages correctly.

## Steps to replicate

* Open zooniverse.org
* Wait for a long time until your OAuth token expires
* Click messages

**Comment by eatyourgreens** [comment]
The [Talk client](/zooniverse/panoptes-javascript-client/blob/master/lib/talk-client.js) seems to be missing the [`beforeEveryRequest`](/zooniverse/panoptes-javascript-client/blob/fddfedc06e91c3961a07e5c2a637d1f5011bd537/lib/api-client.js#L10-L13) hook that's used in the Panoptes client.
