### ISSUE TITLE
Allow the tester role to be able to access inactive workflows

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4180]
I was told to repost this as a front-end issue since the API is capable of doing this. I wanted to test out with a small group of users our new workflow, but apparently the tester role can't see a inactive workflow even with the direct link.

Can it be changed to allow testers to access inactive workflows via the direct url. It would be great for beta testing of new workflows or future upgrades to a project.

Note this is for P4: Ridges. I thought the tester role would have access to an inactive workflow just like the tester role can see a private project.

**Comment by mcbouslog** [comment]
I think @denslowm may be interested in this functionality as well

**Comment by eatyourgreens** [comment]
I intend to add tests for this in #4181

**Comment by denslowm** [comment]
I agree that this would be very useful. Said another way, it isn't clear what the current Tester role does at the present time.

**Comment by eatyourgreens** [comment]
Added in #4181 if anyone has time to check over that PR and merge it.
