### ISSUE TITLE
data export .csv issues

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#421]
The generated .csv output classification file has some problems. 
In my manifest.csv I included a unique object ID number as well as the jpeg image name. The output.csv file ("subject_data" header) has all of my object ID numbers rounded to the nearest 100. Additionally, there were "&" characters in the jpeg file name and these were written out as "\u0026" in the output.csv file.

**Comment by camallen** [comment]
Can you please give an example of the incorrect output vs what you expected? I.e. What did you original object ID numbers look like?

**Comment by melaniebeck** [comment]
Incorrect                       What I expected
588848899891200400 588848899891200431
587725774528840100 587725774528840122
588848900998824200 588848900998824150

**Comment by brian-c** [comment]
Probably relevant: [Number.MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER).

I wonder if quoting the value in the CSV would be enough to tell the parser not to interpret it as an integer.
