### ISSUE TITLE
Put links to the panoptes command line tools and panoptes client for python in the lab

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4217]
The panoptes command line interface is exactly what I've needed for awhile. The only way I know about it was the blog. The python client I knew about via suggestions from the developers. If I was a new project owner, I'm not sure how I would know about these tools. 

I think there are few places like the subject set upload page, where having links or text to tell people they don't necessarily have to use the web interface would be useful. I still create the subject set on the web and now upload via the command line interface.

**Comment by mschwamb** [comment]
@astopy would this be appropriate to add to the subjects uploading page 'When uploading large numbers of subjects, we recommend using our [Panoptes command line interface](https://github.com/zooniverse/panoptes-cli#installation) or our [Panoptes Client package for Python](http://panoptes-python-client.readthedocs.io/en/v1.0/) rather than the web portal. '  After the **We strongly recommend uploading subjects in batches of 500 - 1,000 at a time.**

<img width="920" alt="screen shot 2018-01-09 at 1 47 41 am" src="https://user-images.githubusercontent.com/753325/34708184-799d472a-f4df-11e7-8b83-c8b4a6494913.png">

If so, I think I can make a pull request with the change

**Comment by astopy** [comment]
Yeah, I'd be in favour of adding that.
