### ISSUE TITLE
Changes to email settings page

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#4220]
Move the "Get email updates from the Projects you classify on" tick box option to be directly above the "Project email preferences" section so people realise they can choose to get emails from specific projects and not from others.

Remove the 'Project' header from the 'Project email preferences section'. It's in the wrong place and isn't really useful.

**Comment by simoneduca** [comment]
I think I made those changes, so I'll take this on.

**Comment by simoneduca** [comment]
@mrniaboc this page has recently been converted to JS. Just to clarify @mrniaboc, were the changes you're suggesting already in place before the conversion or you just suggesting them regardless? Either way they seem reasonable to me.

**Comment by mrniaboc** [comment]
There was a discussion on slack a week or so ago, and Jim asked me to write
up proposed changes in an issue.

**Comment by simoneduca** [comment]
OK, I'm happy to pick this up, if @eatyourgreens is ok with it.

**Comment by simoneduca** [comment]
>directly above the "Project email preferences"
@mrniaboc do you mean above the title of the section or below the title but above the list of projects?

**Comment by simoneduca** [comment]
Never mind, got it.
@camallen if `Get email updates from the Projects you classify on` is _not_ checked, can I still select project individually and get updates?
The UI is not clear about this at all and the answer to that question would help me making it better, cheers.

**Comment by marten** [comment]
Yes. The wording for that should have been (and would ideally be changed to) "subscribe to email updates when you first classify on a project". Unticking the box does not unsubscribe you from any of the projects. /cc @camallen

**Comment by simoneduca** [comment]
The fix to this is dependent on some backend work. @marten or @camallen, any update?

**Comment by camallen** [comment]
@simoneduca see https://github.com/zooniverse/Panoptes/pull/2644
