### ISSUE TITLE
 Adding active info to the workflows page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4221]
Now that there is the workflows page, it seems like having info on which ones are active and the ability to turn them on and off might be now better to have on the workflows page rather than on the visibility page

Workflows page

<img width="897" alt="screen shot 2017-12-11 at 11 53 55 pm" src="https://user-images.githubusercontent.com/753325/33868996-665f79e2-ded4-11e7-90b0-f3ab2588b15c.png">

Part of the Visibility page

<img width="879" alt="screen shot 2017-12-12 at 12 36 04 am" src="https://user-images.githubusercontent.com/753325/33869014-87878f6a-ded4-11e7-8e7f-ce9c819ab30e.png">

**Comment by mschwamb** [comment]
The added completion is nice. I think adding which workflows are active to this area would be really helpful

<img width="1189" alt="screen shot 2018-01-30 at 8 33 43 pm" src="https://user-images.githubusercontent.com/753325/35608380-fb184f56-05fc-11e8-9fd2-ad30caa48dc2.png">

**Comment by simoneduca** [comment]
@mschwamb I'm planning to move the relevant part on the visibility section on the workflow page. So that should take already care of the active bit as it wouldn't make sense to have it there as well in the list. It might look a bit odd to have two separate tables on the same page. I'll open a PR and discuss there.

**Comment by mschwamb** [comment]
sounds good

**Comment by simoneduca** [comment]
@mschwamb you can test latest changes here https://workflows-page.pfe-preview.zooniverse.org/

**Comment by mschwamb** [comment]
Looks good. I'd add the help text about the active/not active from the viability page to the workflow page. 

I'd suggest moving everything about the workflows from the visibility page and put it on the workflow page. Then the visibility page is for the overall project again.
