### ISSUE TITLE
Active Participant count stays at 0 even though there are logged in users

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4228]
I'm not sure if this is a front-end or a back-end issue. 

One of the P4: Ridges volunteers noticed this. If you're logged in and on talk it says there are zero active users on the account. I can confirm it's happening across multiple projects. 

<img width="1030" alt="screen shot 2017-12-13 at 9 39 54 pm" src="https://user-images.githubusercontent.com/753325/33972972-595d2be2-e04e-11e7-96ee-a0ae44c6b904.png">

<img width="1048" alt="screen shot 2017-12-13 at 9 42 31 pm" src="https://user-images.githubusercontent.com/753325/33973018-8c6893a0-e04e-11e7-988d-d127513f4da3.png">

**Comment by camallen** [comment]
@mschwamb this is a backend issue with our notifications system. I'm looking into it.
