### ISSUE TITLE
Images don't retire?

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#424]
I had set the Subject Retirement classification count to 10 for my project but when I downloaded the data,  some images had been classified upwards of 30 times.

**Comment by edpaget** [comment]
You're project has to be in a 'Live' state for objects to retire. I think we're still implementing the interface for setting your project state.

**Comment by melaniebeck** [comment]
Aaah! I got it. Thanks, sorry about that.

**Comment by edpaget** [comment]
Yeah we just figured people wouldn't want subjects to retire while they were still testing their project out.
