### ISSUE TITLE
Repeat Images while logged in

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#425]
While classifying as a logged in user, I would come across an image I'd already classified. After classifying it again, the site would crash (I sort of mentioned this in #402 but I didn't understand the real problem then). I logged out, then logged back in. I would get the same image again only this time the site didn't seem to recognize that I'd already classified it and it didn't crash. Until it came up a 4th time -- then it would crash again. This cycle continued indefinitely.

After I looked at the output data, I saw that I had classified the same image upwards of a dozen times.

**Comment by rjsmethurst** [comment]
This just happened to me as well. On the beta test of the Bars Project. I get the same 10 images on repeat. It tells me that though - with a handy little red ribbon telling me "Already Seen" - but I know there's ~380 images uploaded. I was logged in too. This happened to me yesterday first time and then again today. Same 10 images if I remember right. This is a pretty big bug... @edpaget did you get anywhere with it?

**Comment by camallen** [comment]
Yep - i've figured this bug out, it was appending a list of id's without using a set function so dups crept in. Hope to have a PR in soon.
