### ISSUE TITLE
Choosing a random image?

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#426]
I uploaded a rather large sample of images (~6000, and maybe that was the problem itself?). They seemed to upload just fine and were all listed on the Subject Sets page. However, when classifying (while not logged in) I would get repeats extremely frequently. I know repeats are expected when not logged in, but at what rate? With 6000 images to choose from, it seems unlikely to get 10 repeats in a row and yet, that's what I experienced, as did other members of our group.

**Comment by chrislintott** [comment]
Hi Melanie - was this today, or a while back? 

C

**Comment by melaniebeck** [comment]
Monday was the last time I tried. I just didn't get a chance to report it sooner. My bad on that account. I'm actually uploading the same set of 6000 to the New and Improved site as we speak.

**Comment by melaniebeck** [comment]
Okay -- It just happened again on the new site. I received 8 repeats in a row while logged in. I've classified ~100 out of ~1000.

**Comment by vrooje** [comment]
Is that 8 of the same subject in a row?

When I was doing this months ago I was repeating the same ~10 subjects over and over in sequence. Is it like that?

**Comment by melaniebeck** [comment]
No, it was 8 "unique" repeat subjects in succession. It hasn't happened again today -- just that once this morning.

**Comment by vrooje** [comment]
yikes. It's pretty important this doesn't happen to users.

**Comment by edpaget** [comment]
Yup I'm working on it.
