### ISSUE TITLE
Update Marked dependency

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#4260]
<img width="764" alt="screen shot 2018-01-05 at 10 59 12" src="https://user-images.githubusercontent.com/8989606/34606500-8f35455e-f207-11e7-9fcc-611fa7fad439.png">

**Comment by eatyourgreens** [comment]
Is this staged anywhere?

**Comment by simoneduca** [comment]
Marked is used by [Docco](https://github.com/jashkenas/docco/blob/master/package.json#L17), which is used by iced-coffeescript, which is used by our publisssh script.

**Comment by simoneduca** [comment]
I've bugged Docco's maintainer asking to update `Marked`.

**Comment by eatyourgreens** [comment]
You could edit `package.lock.json` to bump the version, I guess. Manually editing the lock file might be a terrible idea, though.

You could also upgrade [zooniverse/publisssh](/zooniverse/publisssh) so that it no longer depends on Docco, or marked. That might be more effort than it's worth, however.

**Comment by simoneduca** [comment]
How would I remove Docco from the dependencies, given that it's used by iced coffeescript?

**Comment by eatyourgreens** [comment]
Update publisssh so that it doesn't use iced coffeescript eg. convert it to javascript and drop coffeescript completely.

**Comment by eatyourgreens** [comment]
Alternatively, we could drop publisssh completely and use some other utility to deploy to S3.

**Comment by srallen** [comment]
I think we should either rewrite publisssh to use ES7 or drop it entirely. I don't think it's worth trying to get folks to update the marked dependency.

**Comment by eatyourgreens** [comment]
Docco has open issues going back over a year, so I agree that we should drop it, by dropping coffeescript (or publisssh entirely.)

**Comment by simoneduca** [comment]
Sounds good to me.

**Comment by simoneduca** [comment]
This might be an alternative to rewrite publisssh https://www.npmjs.com/package/s3
Seems to accomplish the same stuff

**Comment by srallen** [comment]
I'm not sure how actively maintained that is. It has a lot of open issues and PRs and the last one merged was a year ago.
