### ISSUE TITLE
Email project preferences aren't updated correctly

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#4263]
## Expected behavior
stop/start receiving emails when checkbox is un/ticked

## Current behavior
preferences are updated for the wrong project, because the order of projects and project preferences aren't matching.

## Steps to replicate
https://www.zooniverse.org/talk/17/507628

**Comment by mcbouslog** [comment]
Maybe [here](https://github.com/zooniverse/Panoptes-Front-End/pull/4229/files#diff-e74d3989af05624f48402183ca02e52eR72) in ProjectPreferences the index from `filterPrefs().map((projectPreference, i)` doesn't always coincide on the line below with the same project from `projects[i]`, but it does get a project, so things get crossed. Not sure.

**Comment by eatyourgreens** [comment]
I think you have found the bug @mcbouslog. The code doesn’t guarantee that `project[i]` is the project for `projectPreferences[i]`. The name should be found by looking up the project ID linked to the preference or vice versa.

**Comment by mcbouslog** [comment]
I think I have a fix, trying to update tests as well...

**Comment by eatyourgreens** [comment]
The deleted line 85 had the correct lookup for the project name. This PR deletes the bug fix and reinstates the original, broken name.

**Comment by mcbouslog** [comment]
the following appears to help:
```
function ProjectPreferences({ projects, projectPreferences, onChange }) {
  let projectsDictionary;
  if (projects.length > 0) {
    projectsDictionary = projects.reduce((accum, item) => {
      const newAccum = accum;
      newAccum[item.id] = item;
      return newAccum;
    }, {});
  }

  return (
    <tbody>
      {projectPreferences.map((pref, i) => {
        if (projectsDictionary[pref.links.project]) {
          return (
            <tr key={pref.id}>
              <td>
                <input
                  id={pref.id}
                  type="checkbox"
                  name="email_communication"
                  checked={pref.email_communication}
                  onChange={e => onChange(i, e)}
                />
              </td>
              <td>
                <label htmlFor={pref.id}>
                  {projectsDictionary[pref.links.project].display_name}
                </label>
              </td>
            </tr>
          );
        } else {
          return null;
        }
      })}
    </tbody>
  );
}
```

also, adding a 3rd project preference and reversing the order of the project preferences got the tests to fail, but I'm having trouble fixing the tests.

I added branch https://github.com/zooniverse/Panoptes-Front-End/compare/fix-project-email, but mistakenly created it from branch `layout-email-settings`, so I'm not sure how best to proceed.

**Comment by simoneduca** [comment]
I can have a look at the tests tomorrow, thanks @mcbouslog!

**Comment by eatyourgreens** [comment]
There’s already a dictionary, called `projectNames`, in the code so I don’t think a new dictionary is needed here.

**Comment by eatyourgreens** [comment]
@mcbouslog uses the correct array index, which will fix the bug in his screenshot. Do his changes filter the project list correctly @simoneduca? Your original code passed the array through a filter called `filterPrefs`.

**Comment by eatyourgreens** [comment]
The tests were still assuming that the `projects` array maps directly to `projectPreferences`. Good catch by @mcbouslog in updating the tests to change that.

#4354 updates the tests so that they don't rely on array indexes.
