### ISSUE TITLE
Feedback modal shown twice

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#4292]
## Expected behavior
Clicking "ok" in feedback modal dismisses modal.

## Current behavior
After initial click of "ok" in feedback modal, the same modal is shown. Modal is dismissed after second click of "ok."

## Steps to replicate
https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/feedback-testing-mb/classify?reload=0&workflow=3133

**Comment by eatyourgreens** [comment]
I'm only seeing the feedback once when I try this out.

**Comment by mcbouslog** [comment]
Yep, me too! A subsequent PR may have fixed the issue. Thanks,

**Comment by eatyourgreens** [comment]
It might be worth checking on #4295. That's the change that we merged, then later reverted because it broke the combo task.

**Comment by mcbouslog** [comment]
Ah yes, actually that staged branch does show the feedback modal twice. I'll make a comment in the PR.

**Comment by eatyourgreens** [comment]
It's because `checkFeedback()` is called when the classification completes, then again when annotation state changes and #4295 fixes some cases where annotation changes didn't update classifier state.
