### ISSUE TITLE
Return back an error if can't get a data export

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4293]
if you try and request an export twice in 24 hours, there is no message saying you're not actually getting an export. It just says 'Processing your request' on the front end data exports page. If there's an error or it can't send the export, the front end should let you know.

**Comment by mschwamb** [comment]
Or at least an email saying that your request can't be made and an export can be requested in X hours.

**Comment by camallen** [comment]
pinging @PmasonFF for his feedback regarding timing constraints on this.

@mschwamb it's a little tricker than it seems, we accept the request at the API but block the dump from running in our background workers. So signalling from the API means running the check there. Something we could look at doing for sure. Also we could look at the email, i'm not 100% sure we can queue another job when one is rate limited but i'll have a look. If we can, we could send an email notifying the requester that it was blocked.

**Comment by srallen** [comment]
The front end reports exactly what we get back from the API, so I think this is a back-end issue. Could this be reopened there?
