### ISSUE TITLE
Hide previous marks not working since #4277

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#4296]
Related to changes in #4277 - the hide previous marks are not working.

## Expected behavior
Hide previous marks should hid current drawing tasks annotations on the subject viewer.
## Current behavior
Hide previous marks does not hide any drawing annotations but can remove them entirely.

## Steps to replicate

Goto https://classification-update.pfe-preview.zooniverse.org/projects/penguintom79/seabirdwatch/classify and draw some marks then try to use hide previous marks checkbox

## Additional information
Related to the change listener PR in #4277.

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Fixed in #4295
