### ISSUE TITLE
Navigating to new project from notifications via talk doesn't update project

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#4297]
## Expected behavior
1. Open notifications from a project's home
2. Open a talk link for a different project
3. Click on "classify" and get the new project's workflow

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
when hitting "classify", the workflow doesn't change and the old one is displayed: note the seabirdwatch vs project-plumage mismatch in the screenshot.

<img width="1226" alt="screen shot 2018-01-16 at 15 20 34" src="https://user-images.githubusercontent.com/8989606/34996266-ff75ec2a-fad0-11e7-91ee-de1b410a7d54.png">

## Steps to replicate
1. Open notifications from a project's home
2. Open a talk link for a different project
3. Click on "classify"

## Additional information
This might be an issue with the workflow selection component not passing the workflow correctly down the tree.

**Comment by eatyourgreens** [comment]
I _think_ the fix for this might be to update the workflow, in the workflow selection component, when `props.project` changes.

**Comment by eatyourgreens** [comment]
Not sure about that because this bug doesn't occur if you navigate between projects from Talk.
