### ISSUE TITLE
Front End status

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#43]
@brian-c What's the status of the front end? @chrislintott told me yesterday that there's a big update yesterday/today. When can we start playing with it? Thanks.

**Comment by mkosmala** [comment]
Thanks, @brian-c. So where do I go to see the volunteer view?

**Comment by mkosmala** [comment]
@brian-c Never mind; I found the volunteer view. It would be nice to have a link to it immediately after creating the project.

**Comment by brian-c** [comment]
Yep, the design side of this isn't done yet. It'll be more obvious.

**Comment by mkosmala** [comment]
@brian-c Do you have a to-do list somewhere for the front end? I don't want to create needless issues for things you're already planning on doing, but haven't yet gotten to.

**Comment by brian-c** [comment]
I've been keeping #78 updated as a general status page
