### ISSUE TITLE
Signal *not* to make all workflows inactive when a project is finished.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#4303]
A few projects have done that. The result is a broken classify page. Some text in the lab should warn builders not make all workflow inactive.
In addition, it would be useful to automatically move a project to "paused" or "finished" when all data is retired.

**Comment by simoneduca** [comment]
I'm thinking of adding a section at the top of the lab's workflows page with three radio buttons corresponding to project status: active, paused and finished. Along with some text inviting researchers to switch to paused or finished when all data is retired. Does that seem as sensible place for that functionality? @beckyrother thoughts?

**Comment by beckyrother** [comment]
Can you screenshot the place where you mean? Just want to be sure I'm clear about this.

**Comment by simoneduca** [comment]
Oops, sorry I thought I did that already, but clearly not!
<img width="970" alt="screen shot 2018-01-18 at 14 16 41" src="https://user-images.githubusercontent.com/8989606/35106919-7a67d1fe-fc67-11e7-88be-15c9b899929e.png">

**Comment by srallen** [comment]
I don't think they should be radio buttons since we want the API automatically setting this state. Also, the workflow status and reasonably should be moved from the visibility page to the workflows page, see zooniverse/Panoptes-Front-End#4221

**Comment by beckyrother** [comment]
Is the problem that project owners aren't able to find the status of their workflows when they're set by the API?

**Comment by srallen** [comment]
The issue isn't necessarily the workflow state, but the overall project state of either active, paused, or finished. These states are manually set by us in the database at the moment, but should automatically be set based one the completeness calculation for each active workflow. We don't really want to let projects set these states on their own because it's an indication of whether or not there are still any subjects left to be classified and I'm not sure how projects would easily determine this without doing a lot of manual math unnecessarily. See zooniverse/Panoptes#2365

We should definitely communicate the current project state in the lab somewhere if it's not. What is happening is a few projects have inactivated all their workflows while they're in the paused state which breaks the classifier and we don't want them to do that. We always want the classifier to work even if all the subjects are retired. Projects sometimes are used for demos or educational purposes.

**Comment by simoneduca** [comment]
@sarah I agree with moving anything workflow related under the workflow page.
>should automatically be set based one the completeness calculation for each active workflow.
I had a chat with Marten earlier about this and it's very hard to do, i.e. they haven't figured out how to do it yet.
I agree that's probably the best solution (once it's viable) but perhaps, in the interim, we could allow projects to set status on their own only when all subjects are retired.

>We should definitely communicate the current project state in the lab somewhere if it's not. What is happening is a few projects have inactivated all their workflows while they're in the paused state which breaks the classifier and we don't want them to do that. We always want the classifier to work even if all the subjects are retired. Projects sometimes are used for demos or educational purposes.
Precisely. Except for the bit about being paused. I don't think Identifying NZ animals was paused and still the classifier was broken.

**Comment by simoneduca** [comment]
@beckyrother just adding some text is certainly the quickest patch to this. Although it should probably also say not to make the workflow inactive, which what the problem is.

**Comment by beckyrother** [comment]
What if next to each workflow was a small label that described what state each was in: 
![untitled](https://user-images.githubusercontent.com/1392130/35108288-c913b43c-fc38-11e7-8074-6ba1984fc254.png)

and add a message at the top explaining what each state means, how the label got there (if we do it manually, we should say that and to contact@ us to change it), and that they don't need to deactivate a workflow if it's already paused.

**Comment by simoneduca** [comment]
I like the idea of adding more info on the workflow list in general. But I think workflow status and project status are two separate things.

**Comment by srallen** [comment]
We could display the completeness metric?

**Comment by beckyrother** [comment]
Sorry I guess I didn't realize there was a difference. Completedness metric is a good idea @srallen

**Comment by simoneduca** [comment]
@srallen do you mean this?
<img width="1120" alt="screen shot 2018-01-18 at 16 54 22" src="https://user-images.githubusercontent.com/8989606/35110265-482a850c-fc70-11e7-9bb3-5cb747cfe540.png">
It might be nice, but I don't follow how it would help with the issue of making all workflows inactive.

**Comment by srallen** [comment]
No, that's the overall project completeness which is calculated from the active workflow completeness. Workflow completeness is used on the stats page: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/stats/stats.jsx#L233

What I think is that there should be a statement on the visibility page (or moved to the workflows page along with the settings where it's more appropriate) saying to not make all the workflows inactive, even if they are all completed at the moment and why. Having the percentage stat of completeness for each workflow would be helpful here so the project owner doesn't have to go the stats page to see.

**Comment by beckyrother** [comment]
Completely agree @srallen. Anything having to do with workflows should be on the workflows page.

**Comment by beckyrother** [comment]
If we move the workflow visibility settings to the Workflow page, let's also add a link `Project Visibility` that goes to the Visibility page.

**Comment by simoneduca** [comment]
That sounds all good to me. Thanks both. Oh, @srallen where does that percentage actually show up on the site?

**Comment by srallen** [comment]
On the projects stats page: https://www.zooniverse.org/projects/ghthomas/project-plumage/stats

The percentage per workflow comes from the workflow's completeness.

**Comment by simoneduca** [comment]
OK thanks. Sorry, I've only just caught up with the latest exchange on Slack about this. And I'm confused now. It looks like there is a case for moving the radio buttons to the lab, which I like. But also adding some text saying
>to not make all the workflows inactive, even if they are all completed at the moment and why.
I'm going to start adding those two things.

**Comment by simoneduca** [comment]
It's been agreed to display the completeness metric and add a comment saying to not inactivate all workflows if they’re all at 100%.

**Comment by mschwamb** [comment]
Some of this conversation is echoed in previous ticket #4221 in case you want to close that previous ticket
