### ISSUE TITLE
username input uses shouldn't be case-sensitive

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#431]
In the new login and the collaborators area of the project builder, you have to input usernames in the correct case or the request doesn't work. Not sure whether this is an intended feature or not but it is probably going to confuse a lot of people... I've seen it twice so far just with our initial users.

**Comment by edpaget** [comment]
This is a backend issue zooniverse/Panoptes#901

**Comment by vrooje** [comment]
oops! sorry :)
