### ISSUE TITLE
Avatar and Background Boxes look funny

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes-Front-End#432]
I don't know if it's just my browser or the window size, but they're really oddly sized on my screen. 

Firefox 38 on Debian Sid
![screenshot from 2015-05-28 12 41 13](https://cloud.githubusercontent.com/assets/108177/7866759/10769b1a-0537-11e5-986b-59e35d66a20c.png)

**Comment by aliburchard** [comment]
I get that too!

**Comment by melaniebeck** [comment]
Same here

**Comment by chrissnyder** [comment]
Sorry @srallen, reassigning to you.
