### ISSUE TITLE
Comments on Modal Feedback

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4320]
Hi @rogerhutchings 

Thanks for the new modal feedback. It works well. We have a few comments and suggestions that I list below, please let me know what you think.

**Missing done & talk button**
For **dud training images**, only a "done" button rather than "done"+"done&talk" buttons are shown making it obvious which are dud. I thought with the model feedback it was possible for the buttons to be consistent for all subjects whether they are training images or not.
Is it possible to make the buttons the same for every subject whether training or not? 
(note this only happens for dud training images)

![image](https://user-images.githubusercontent.com/1917970/35433820-afc761a0-027c-11e8-8eba-1f288cd112ae.png)

**"Next" button appearance**
Also for **dud training subjects** only, once the feedback window comes up a "Nex"t button appears - that doesn't happen for any other subject type. If we still had done & done+talk as with the other subjects, the need for the next button would be eliminated
![image](https://user-images.githubusercontent.com/1917970/35433840-c1d216d8-027c-11e8-8b5d-d6a97c36961b.png)

**Bug with "Next" button**
@anupreeta27 also found that after clicking the sole "done" button on a dud training image (let's call this subject 0), if she used the keyboard "enter" rather than mouse input (when the "Next" button is highlighted) the classification proceeds to the next image (subject 1) but the feedback message window remains active. This means that the next served subject (subject 1) is shown but with the feedback of the previous message overlaid on top (as it wasn't clicked away). The feedback window can only be removed by clicking "ok" in the feedback window, which causes the next subject (subject 2) to be loaded, thereby missing classification on subject 1. 
 
subject 0
![image](https://user-images.githubusercontent.com/1917970/35433891-f57c5b06-027c-11e8-9e5b-330ce69301d0.png)

subject 1: this is the outcome of when "enter" is pressed before the feedback button is closed
![image](https://user-images.githubusercontent.com/1917970/35433996-6a9420c2-027d-11e8-9acb-0f18f199ca29.png)
 the next image (subject 1) is shown with the previous feedback message (of subject 0) overlaid.

In this case "done" is not highlighted and cannot be actioned with a keyboard click and neither a mouse button press, so the only option is to press "ok" on the feedback window that then advances to the next subject (subject 2), so no classification is recorded for subject 1.

If you could remove the appearance of the "Next" button (& have "done"+"Done&talk"buttons) would this remove this bug?

**Training feedback for success and fail**
The feedback window showing the "radius" of success is quite large, and the pan/zoom controls appear below rather than alongside the images (see below).
Would it be possible to add an option for the builder to toggle whether the image (with radial markup) is shown or not? For SpaceWarps we would prefer the feedback messages to the be the same for both duds and sims (i.e. text only).

![image](https://user-images.githubusercontent.com/1917970/35434155-067ad72e-027e-11e8-8d4f-d0f4942b0aa7.png)

**Cosmetic suggestions:**

- Please could you move the button that actions closing of the feedback window to the **top right** of the window rather than the bottom? It would make it more obvious and mean less scrolling.

- Is it possible to make the closing button (preferably top right) say "Next" or  "X" (or "OK" if you prefer), and could the text be in bold face and larger font and/or the button have a different background colour so that it's more obvious

**Other**
Anu also found that after she had seen all the images and started seeing the already seen label, the last 10 images were repeatedly cycled through, @trouille is this expected behaviour for the classification stream?

## Additional information

- **OS X 10.10.5:**
- **Chrome Version 63.0.3239.132 (Official Build) (64-bit):**

**Comment by eatyourgreens** [comment]
I think #4321 will address some of the concerns raised here. You can try it out on @mcbouslog's test project: https://modal-feedback.pfe-preview.zooniverse.org/projects/markb-panoptes/feedback-testing-mb/

By the way @rogerhutchings is now on parental leave until early March.

**Comment by aprajita** [comment]
OK, thanks very much @eatyourgreens !!

**Comment by aprajita** [comment]
Hi @eatyourgreens 
just wanted to say that `i think not all of the issues here are covered by #4321 - so i am not sure what the overall status is and I hope this issue remains open and my comments can be considered. 

I have also noted that the way the dud feedback was implemented previously was behaving as I expected but now I am getting a fail message when I haven' clicked (which should trigger a success message). Before I change the rule, I just wanted to check if something has changed in the dud feedback mode causing this or is this a bug?
thanks

**Comment by eatyourgreens** [comment]
Hi @aprajita I'm not sure what the overall status of feedback is either. It's difficult to tell what has been done and what still needs to be fixed for this issue. It would helpful if you could list what still remains to be done, or close this issue and open separate issues for each thing that isn't working properly.

I'm having trouble figuring out how feedback rules are implemented in the code, so you might have to wait until @rogerhutchings comes back from leave. I do know that Roger completely rewrote the code for the current version, which would explain why duds changed.

**Comment by aprajita** [comment]
Hi @eatyourgreens many thanks for the update, that's helpful. I'll try to distill these into separate items  then.  

I'll also see if I can understand (and make changes to the workflow implementation) why duds are behaving differently to before. 
thanks.

**Comment by eatyourgreens** [comment]
Thanks @aprajita It looks like there is also a `feedback` label so that we can group these issues together in one place. https://github.com/zooniverse/Panoptes-Front-End/labels/feedback

**Comment by aprajita** [comment]
OK, thanks @eatyourgreens!

**Comment by eatyourgreens** [comment]
By the way, @mcbouslog was trying out feedback a while ago, and found it didn't work as expected. So I would not be surprised if there are still bugs in the code that interprets the feedback rules.

**Comment by eatyourgreens** [comment]
On the test project https://master.pfe-preview.zooniverse.org/projects/rogerhutchings/feedback-test I can only get 'You found a dud!' if I add a point to a dud subject, then delete it again. Definitely a bug.

**Comment by rogerhutchings** [comment]
@aprajita these issues should have been addressed now - can you let me know if we can close them?

**Comment by aprajita** [comment]
Hi there

I think all are closed, apart from 

> Anu also found that after she had seen all the images and started seeing the already seen label, the last 10 images were repeatedly cycled through, @trouille is this expected behaviour for the classification stream?

is this expected behaviour when classifiers are out of subjects?

Thanks
Aprajita.

**Comment by aprajita** [comment]
Hi @rogerhutchings @eatyourgreens 
One more question from the list above, if we do want to enable the subject viewer in the feedback, is it possible to resolve the issues with the pan & zoom buttons appearing on the line below? i.e. Can the subject panels be shown without the buttons so there aren't the extra grey lines? Thanks

If this can't be resolved we will run without the subject viewer.

![image](https://user-images.githubusercontent.com/1917970/38208448-00e980b2-36a9-11e8-8340-8bc6fe5575de.png)

**Comment by aprajita** [comment]
closed as open issues copied to new issues #4508 #4509
