### ISSUE TITLE
Arrow keys don't change single task's selected answer in Firefox

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#4351]
## Expected behavior
When classifying a `single` task a selected answer has focus the arrow keys should change the selected answer in Firefox.  This works as expected in Chrome and Safari.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The `tab` key must be used to change the selected answer.

## Steps to replicate
In Firefox ppen the dev-classifier, press `tab` once (so the first answer is in focus), press `down`.

## Additional information

- **Operating system:**
OSX 10.13.3
- **Browser:**
Firefox 58.0.1

**Comment by eatyourgreens** [comment]
Those radio buttons don’t have a `name` attribute, so Firefox doesn’t know that they’re grouped.
