### ISSUE TITLE
PFE wrongly assumes that all apps need a `#`

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#4358]
## Expected behavior
Being redirected to the correct page
## Current behavior
User sees the home page (host address), regardless of what the fragment identifier specifies. E.g. https://www.antislaverymanuscripts.org/#/classify just brings up the site homepage.

## Steps to replicate

1. Go to https://www.antislaverymanuscripts.org
2. Click on the project's talk link
3. Click on the classify link

## Additional information
The culprit is this [line of code](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/components/ProjectNavbar/helpers/getProjectLinks.js#L50), which wrongly assumes that all apps need a `#`.

##Suggestion to fix this

1. Remove `#` from the line above.
2. Add `#`, or `#!` for our angular apps, to the project's `redirect` field as needed.

**Comment by eatyourgreens** [comment]
Protip: Github lets you quote code directly in your issues. Here's that line of code: https://github.com/zooniverse/Panoptes-Front-End/blob/5e80550403d6025fbbee69fa0a9043b5565bfbcd/app/pages/project/components/ProjectNavbar/helpers/getProjectLinks.js#L50

**Comment by simoneduca** [comment]
Just realised the link above is for the new navbar.
Here's the code for the current navbar https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/project-navbar.jsx#L118

**Comment by eatyourgreens** [comment]
Odd that any existing hash in `project.redirect` is stripped out.
