### ISSUE TITLE
Trouble uploading subject set

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#436]
When uploading a second subject set to my project, the pop-up box shows that images area being uploaded but never seems to complete the process and hangs here (I've tried four times now with the same results):
![screenshot from 2015-05-28 23 08 26](https://cloud.githubusercontent.com/assets/7946684/7876300/3d54ae1c-058f-11e5-9886-d19abd2020c3.png)

I've tried clicking the X and refreshing the screen. I've tried waiting for ten minutes and refreshing the screen again. I've tried logging out and then back in again.

**Comment by camallen** [comment]
I'm pretty sure this is related to the limit of 1000 subjects per user. 

@brian-c, @edpaget perhaps we need to check how many subjects a user can upload before attempting to create subjects in the backend. Perhaps GET `/user/subject_limits` for a logged in user to get a count of subjects and the users current limit?

@melaniebeck - in future try uploading in smaller batches as well. You don't need to modify the manifest as it compares selected files to the manifest and skips any that aren't selected.

**Comment by edpaget** [comment]
@camallen we should probably add it to the user serializer, maybe only visible to the uploading user https://github.com/zooniverse/Panoptes/blob/master/app/serializers/user_serializer.rb#L6-L8

**Comment by camallen** [comment]
@edpaget much better idea!

**Comment by camallen** [comment]
@melaniebeck we just bumped the subject limit, do you want to try again? 

Also out of interest how many subjects do you want to upload in total for this project (both now and long term).

**Comment by melaniebeck** [comment]
Ah! I see! That makes sense. Thanks for the clarification. 
My original sample is ~6000 images. I've been putting them up in smaller ~1500 image chunks. Wednesday I successfully uploaded a sample of 1330 images (to preview panoptes) so I didn't realize there was a cap. I will make the chunks smaller.

**Comment by camallen** [comment]
@melaniebeck - I don't think the limit was setup on wed.

**Comment by melaniebeck** [comment]
I just tried to upload 1000 and it's still not working. I'll try smaller.

**Comment by melaniebeck** [comment]
I can't upload 4. Just hangs on that screen.

**Comment by camallen** [comment]
@brian-c ?

**Comment by edpaget** [comment]
@melaniebeck can you try again and when it fails open Chrome's console by pressing Command + Option + J (or going to the Chrome Menu then More Tools then JavaScript Console) and take a screenshot of that? It should show an errors happening there.

**Comment by brian-c** [comment]
I've got it on my list to display subject creation errors. Thought this was in already. Sorry.

**Comment by melaniebeck** [comment]
![screenshot from 2015-05-29 09 47 46](https://cloud.githubusercontent.com/assets/7946684/7885130/d31acadc-05e7-11e5-8c29-9f1d51b624a5.png)

**Comment by camallen** [comment]
expired login session perhaps? Can you please try and logout and login again.

**Comment by edpaget** [comment]
Nope it looks like the subject limit didn't change on Production. Just need to bump it to 10k

**Comment by camallen** [comment]
@melaniebeck subject limit has been bumped for real this time (my bad). Can you please try again?

**Comment by melaniebeck** [comment]
Worked with a < 1000 sample. Trying it with the sample of 1670 now.

**Comment by melaniebeck** [comment]
Larger sample worked too!

**Comment by camallen** [comment]
@melaniebeck great news, feel free to close the issue if you think it's resolved.
