### ISSUE TITLE
Cannot check the "Project has at least one active workflow" box in the project builder.

### ISSUE THREAD

**Issue by dwright04** [zooniverse/Panoptes-Front-End#4360]
## Expected behaviour
The project builder should recognise that an active workflow is linked to the project under the  Visibility menu.

## Current behaviour
I am trying to prepare Muon Hunters 2.0 for beta launch but cannot click the "Apply for review" button under the Visibility menu.  I cannot check the "Project has at least one active workflow" box despite having one active workflow linked.

![screen shot 2018-02-15 at 09 34 26](https://user-images.githubusercontent.com/7902164/36265579-22e8a83e-1235-11e8-90f1-443a4d02eb86.png)

![screen shot 2018-02-15 at 09 34 45](https://user-images.githubusercontent.com/7902164/36265594-2b8f2fe4-1235-11e8-8fd9-612f2482d40a.png)

## Additional information
The project has a subject set with 100 subjects:

![screen shot 2018-02-15 at 09 35 06](https://user-images.githubusercontent.com/7902164/36265948-fd5cd210-1235-11e8-8321-5f9201c007ad.png)

![screen shot 2018-02-15 at 09 54 00](https://user-images.githubusercontent.com/7902164/36266027-2e1f9504-1236-11e8-858b-fb836066db60.png)

The project has an FAQ:

![screen shot 2018-02-15 at 09 35 56](https://user-images.githubusercontent.com/7902164/36266107-59318b94-1236-11e8-959a-1b8652ef426e.png)

- **Operating system:**
OSX 10.11.6 

- **Browser:**
Chrome 64.0.3282.140

**Comment by simoneduca** [comment]
Hi Darryl, what project is this?

**Comment by simoneduca** [comment]
This might be related to the changes I recently made to that page. Let me have a look. How urgent is this?

**Comment by eatyourgreens** [comment]
That checkbox is set if `workflow.active` exists for at least one workflow.
https://github.com/zooniverse/Panoptes-Front-End/blob/5e80550403d6025fbbee69fa0a9043b5565bfbcd/app/pages/lab/apply-for-beta-form.jsx#L11-L15

@simoneduca is the workflows form setting that flag when you check the Active box?

**Comment by srallen** [comment]
The the apply for beta form in the visibility component is relying on workflows in the state, but since that all got moved, the state is always an empty array: https://github.com/zooniverse/Panoptes-Front-End/blob/5e80550403d6025fbbee69fa0a9043b5565bfbcd/app/pages/lab/visibility.cjsx#L24

**Comment by srallen** [comment]
Projects now have `activeWorkflows` serialized in its links, so the validation could just be checking the length of that array. We don't need to request for workflows for this to work.

**Comment by dwright04** [comment]
We are launching the beta test today.  If the project can still be launched without having to click the "Apply for review" button or if there is a work around then that works for me.  Beyond that you guys probably have a better idea of the urgency.
