### ISSUE TITLE
Explore Project menu hides all project links if you're an admin and logged in or if your project is an organization and has an external link

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4371]
Because of having the lab link on the navigation bar for admins, now means I now lose the ability to easily click on the project Talk link like any other logged in user.  When I log in the  navigation bar contents disappears to an 'explore project' menu bar button. I expect like many science team members like myself  click on talk after navigating to the site almost immediately. Having two external links and two social media icons isn't unreasonable and shouldn't force the interface into the mobile screen menu when I'm using a desktop computer. Now I have two clicks to get  to any other part of the Planet Four:Terrains website. since I have to click on the 'explore project' navigation bar each time. The lab link should be removed if a better solution can't be found.  Could the lab link be a small gear icon or could the collections pages which aren't used very often on any of my past 5 projects be removed from the main navigation page? I go to Talk more than I go to the internal lab page. Having a direct link to the lab page was helpful, but  not at the cost of losing all my other icons because I have two external links. 

Also the same thing happens for all of the Snapshot Safari projects non-logged in because of the link back to the organization page, so new people would likely miss there's a talk at all (same thing happens in landscape mode on my iPad air).

Screenshots are below.

Planet Four: Terrains when I'm logged in:

<img width="1153" alt="iobcghnibckdecmi" src="https://user-images.githubusercontent.com/753325/36460298-dc82917c-165b-11e8-9b0f-0800fa8a819b.png">

What it looks like when I'm not logged in (what every other logged in account sees):
<img width="1174" alt="pieciejenefhgfeh" src="https://user-images.githubusercontent.com/753325/36460321-f5b6c276-165b-11e8-98cc-bcaedadddc29.png">

old header version you can see the edge of the Zooniverse footer. The new header pushes things down such that the done button is at the bottom of my 13 inch screen:

<img width="1169" alt="mofdifdckffnmhid" src="https://user-images.githubusercontent.com/753325/36460331-02b96a50-165c-11e8-9b98-de5a6e10d99f.png">

<img width="1233" alt="ibgapgkcnmnknohl" src="https://user-images.githubusercontent.com/753325/36460347-0cadb962-165c-11e8-863a-989550f92a5f.png">

![ilfafbppkdncmfdn](https://user-images.githubusercontent.com/753325/36460358-14ca4c64-165c-11e8-9d5d-176a6ae6a682.png)

**Comment by beckyrother** [comment]
Hi @mschwamb, thanks for your email and for opening this issue. We've heard this feedback from a few project owners and volunteers today, so we'll be looking into an update which may solve this issue. 

I did want to expand on the reasoning behind some of these changes. First, the space for the actual classification task (part of the update to come) has been carefully measured to fit within the height of the average browser window (643 px, according to analytics data). When a user scrolls down to fit the classification task in their browser window, the _page will not move_ when they submit a classification, so there should not be a lot of scrolling at all. Also, you'll notice that the image researchers chose for the background of the project has been moved to the background of the nav bar. (A future PR will remove the background from the project itself and replace it with a clean #EDF0F4 to enhance readability of both the question and the subject image.) (There will also be a dark theme for images which are a similar color to #EDF0F4 like the Planet Four: Ridges images.) Additionally, the increased height opens up the space and feels less cramped and more "designed".

This update is one of many as we gradually update the classify section, so we ask for patience and trust moving forward. We're in that awkward in-between stage now, but I promise it will be for the best.

Please feel free to email me directly, becky@zooniverse.org, or respond here if there is additional feedback or other questions I haven't addressed.

**Comment by mschwamb** [comment]
@beckyrother I get why, you're making the changes, probably but instead of the awkward in-between- stage maybe a better option to launch the full design. In the full design is the landing page background going to be blurred on the navigation bar? Currently I can't look at P4: Ridges without my glasses on because of the eye strain. Even with them on, I'm getting the start of headaches. My eyes are trying to adjust for the blurred image, because my brain can tell its out of focus. Not as much of a problem of Comet Hunters, since it's a smoother background, my brain isn't able to interpret what it should be.  Currently to look a talk, I need to click the link and then hide the navigation bar. 

More important for me is not losing those links on the navigation bar and have the same navigation bar as possible to what volunteers see, one reason is for screenshots  for papers and presentations, but also making it easy for a project owner to navigate. 

From my experience, people are frequently going to the collections and recents very often, that they could be combine under a tab menu that would free up space. Also the lab link you could be an icon off to the side to help.  

I had asked for the direct link since I was having to click several times to from my project, to the zooniverse lab link to then select my project, with the current navigation bar and going to 'Explore project' when logged I have as many clicks so worth getting rid of it, it would stop the 'Explore project' menu showing up if one has 2 social media links and 2 external links for their project.

**Comment by beckyrother** [comment]
@mschwamb This is good feedback, thank you! We're working this morning on some updates to address a few of these concerns. 

We've discussed folding just a few links into a tab, but hiding a feature because it's not used much dooms that feature to even less use. To avoid that, we're looking for alternative ways to make sure all links are visible. Keep in mind as well that some projects do use Collections and Recents quite extensively.

**Comment by srallen** [comment]
External links have been moved into their own UI module. CSS refactoring including removing the max-width for the navbar container means is very unlikely projects will collapse into the dropdown menu on desktop.
