### ISSUE TITLE
Broken private message inbox paging buttons

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#4391]
## Expected behavior
Pressing buttons to move between pages on my inbox should move me to those pages. 

## Current behavior
Paging inconsistently fires (correctly?) and doesn't update the page URL param correctly for each button press.

## Steps to replicate
Go to https://www.zooniverse.org/inbox and press the page buttons down the bottom. 

## Additional information
Seems to be broken paging buttons, affects all browsers.

**Comment by simoneduca** [comment]
Possible duplicate of this https://github.com/zooniverse/Panoptes-Front-End/issues/3627?

**Comment by camallen** [comment]
yep - it's a dup, i should have looked first.
