### ISSUE TITLE
Add featured project toggle to admin page

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4394]
## Expected behavior
Featured project is now a property on the project resource. See https://github.com/zooniverse/Panoptes/pull/2602

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Admin page doesn't have this toggle yet.

**Comment by mrniaboc** [comment]
Heavy +1 to this! I'd like to switch the featured project to The Plastic Tide for British Science Week starting tomorrow. It would be amazing if I could do this myself from the admin page!

**Comment by simoneduca** [comment]
I'll have a go.
