### ISSUE TITLE
Bezier curve tool placement commands

### ISSUE THREAD

**Issue by nskuza** [zooniverse/Panoptes-Front-End#4399]
## Expected behavior
The Bezier curve tool currently doesn't allow for the user to stop placing a curve by right clicking.

## Current behavior
The curve tool only allows placement when the user closes the points along the curve or if the user selects an entirely new option. 

![capture](https://user-images.githubusercontent.com/36749509/36638367-bf453258-19b8-11e8-9848-34d34fad44c0.PNG)

## Steps to replicate
I do not have access to the source code but I imagine there is a function allowing for the placement of the curves. It simply requires the additional option for placement. 

## Additional information
I have reason to believe the code was copied via one of the shape tools which is why it allows for the curve to be placed once the points are closed. The first image (above) is showing the curve while you are still placing points. The second shows the curve concluding placement once the points have been closed. This function makes the curves completely useless for our project.

![capture2](https://user-images.githubusercontent.com/36749509/36638368-c427d758-19b8-11e8-8e0d-e1fc1241e644.PNG)

- **Operating system:**
- **Browser:**

**Comment by rogerhutchings** [comment]
The source for this tool is in https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools/poly-curve.cjsx

**Comment by eatyourgreens** [comment]
@nskuza We have a set of freehand line-drawing tools, which should be available soon. See #4421.

[Etch-A-Cell](https://www.zooniverse.org/projects/h-spiers/etch-a-cell) is an example of a project that uses freehand line drawing. Would that be more appropriate for your project?

**Comment by nskuza** [comment]
I would prefer to not use freehand drawing tools. The specific mathematical description of a Bezier curve is useful to us in more ways than one. I understand that we could fit curves to the drawn lines but that seems to be an unnecessary step since the curve tool is so close to working. From looking at the code that @rogerhutchings shared it appears lines 41-46 (see attached image) is where the issue arises. It will only complete the curve if the user closes the curve as a polygon which defeats the purpose of it being a Bezier curve in the first place. If the user can complete the curve by right clicking that will make it much easier to use. We already have code to extract data we need, we simply need the tool to be more intuitive. 

![codesnippet1](https://user-images.githubusercontent.com/36749509/37049883-f943272c-2137-11e8-91cd-965b847640d7.PNG)

**Comment by tlalka** [comment]
My project has the exact same problem. We are drawing the spiral arms of galaxies, but the bezier curve does not allow points to be drawn inside the auto-completed shape. We need auto_close to be set to false, but the changes nskuza lists would work for us too. We've got a programmer on our team who could change this tool, we just don't know the conventions for this. 

For example, would it be better to just change this code, or create two separate "bezier shape" and "bezier curve" tools? One that auto completes and one that doesn't

**Comment by nskuza** [comment]
Hello tlalka. Can you let me know the name of the project you are developing or perhaps the researchers affiliated with the project? I know several individuals involved with galaxy centered Zooniverse projects and I was curious to know more about how you plan on developing the Bezier tool. If we could get in touch that would be great.

**Comment by tlalka** [comment]
The project is "Spiral Graph" and our head researcher is Patrick Treuthardt. If you look at some of the freehand tools, they allow a curve to be completed by clicking on the last point you made, instead of clicking on the first point and closing the shape. You can test this behavior out at https://freehand-tools.pfe-preview.zooniverse.org by making and account and project. It wouldn't be to hard to apply this behavior to the bezier tool, since the code is pretty much already written in some of the freehand tools

**Comment by nskuza** [comment]
Our project is "Solar Flare Forensics" and the head researcher is Lindsay
Glesener. We are aware of that behavior with the freehand tool. Zooniverse
sent us a whole demo on it hoping we would bite and go with it for our
project. They invited us to suggest edits to the Bezier code which they
would then approve but we currently don't have anyone familiar with
Javascript. We aren't willing to dedicate the time to learn at this point
so until we get funding to hire a programmer we are dead in the water. Once
we have that funding they indicated that we could take over full
development of the tool.

On a side note you should know that we have discovered some additional
problems with the Bezier tool. For example, when you use more than two
points it creates a quadratic curve connecting each pair rather than
allowing the creation of a cubic or quartic parametric function. This is
undesirable for what we intend to use it for. There are a smattering of
other issues I won't bore you with but suffice to say it isn't as simple of
a fix as it may seem.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by eatyourgreens** [comment]
I think the bezier curve tool is based on the curve drawing tools used in software like Adobe Illustrator. As you note, those tools generate composite quadratic curves. The bezier tool is in use by the [Milky Way Project](https://www.zooniverse.org/projects/povich/milky-way-project), to mark bow shocks. If you need higher order bezier curves, I'd suggest developing a new tool, in order to avoid breaking the bow shock tool for MWP.
