### ISSUE TITLE
SnapshotSerengeti.org redirect needed, however need to keep the authors page

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#4408]
Need snapshotSerengeti.org to redirect to:
https://www.zooniverse.org/projects/zooniverse/snapshot-serengeti

However, https://www.snapshotserengeti.org/#/authors is referenced in articles and gets hundred+ hits each month, so we need this to remain as is. 

Adam's suggestion:
I'd suggest either updating the site to have a landing page that links to the new project, keeping the rest basically the same, or update the site to redirect the home page to the new project with Javascript (which wouldn't affect the authors page).

**Comment by trouille** [comment]
Note: https://www.snapshotserengeti.org/#/data was also a concern, but it gets no traffic, no articles reference the URL, and the research team has already taken the relevant information from that site and moved it into the About section of snapshotSafari.org.

**Comment by mcbouslog** [comment]
Should https://www.snapshotserengeti.org/#/classify redirect to https://www.zooniverse.org/projects/zooniverse/snapshot-serengeti as well? Additionally, I could remove Classify as a nav option, but the url would still redirect.

Should we delay the redirect and add a message to the home page?

**Comment by mcbouslog** [comment]
staged changes:

- /#/about: https://preview.zooniverse.org/serengeti/#/about
- root (redirects): https://preview.zooniverse.org/serengeti
- /#/home (redirects): https://preview.zooniverse.org/serengeti/#/home

**Comment by mcbouslog** [comment]
I think the following staging link behavior is what's desired, let me know what you think:

- root (should redirect, hard to tell but heading changed to "Redirecting to the live Snapshot Serengeti..."): https://preview.zooniverse.org/serengeti/
- #/home (same as above): https://preview.zooniverse.org/serengeti/#/home
- #/authors: https://preview.zooniverse.org/serengeti/#/authors
- #/data (should redirect to new project results page): https://preview.zooniverse.org/serengeti/#/data

**Comment by mcbouslog** [comment]
Closing in favor of [Snapshot Serengeti Issue 159](https://github.com/zooniverse/Serengeti/issues/159).
