### ISSUE TITLE
Repeat every 19th image while logged in

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#441]
I've counted through a three cycles of this now. I may be off by one -- it might be 18 or 20 images before the repeat but I'm pretty sure it's 19.

**Comment by melaniebeck** [comment]
Nope, it's 20. I get 19 new images and the 20th is a repeat every time.

**Comment by melaniebeck** [comment]
When it repeats, the repeat image is from exactly 10 images prior.

**Comment by edpaget** [comment]
Is your project private? Would you mind linking me to it or adding me so I could see if I can replicate?

**Comment by melaniebeck** [comment]
It's public: http://preview.zooniverse.org/panoptes/#/projects/highzgal/gz2redo-take2

**Comment by edpaget** [comment]
This should be fixed once the next deploy finishes.

**Comment by brian-c** [comment]
Just deployed to preview.
