### ISSUE TITLE
Failure feedback message displayed for dud subjects

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4410]
https://master.pfe-preview.zooniverse.org/projects/rogerhutchings/feedback-test (point-based feedback workflow)

## Expected behavior
If I click Done on a dud subject, without drawing a mark, I should be told 'You found a dud.'

## Current behavior
If I click Done, I get the failure message 'It was actually a dud :(' or 'Actually it was a dud.'

If I draw a point, then delete it again, I get the success message.

**Comment by eatyourgreens** [comment]
@aprajita I think this is this the same feedback bug that you mentioned in the comments on #4320.

**Comment by aprajita** [comment]
yes - thanks @eatyourgreens, although  i got slightly different failure messages for when i didn't place a marker on a dud compared to when i did. I wonder if it's the messages that are wrong but that doesn't explain the SW demo behaviour. 
![image](https://user-images.githubusercontent.com/1917970/36845117-5b696036-1d4d-11e8-98c0-f189fe8ceca7.png)

**Comment by eatyourgreens** [comment]
@aprajita I think there are two different duds on that test workflow, with different messages.

**Comment by aprajita** [comment]
Ah yes - sorry.

**Comment by eatyourgreens** [comment]
I've traced this as far as `success: true` not being set on the dud subject's feedback rule, if I press Done without updating the current annotation first. Beyond that, I'm currently lost trying to figure out when the rule should be updated during the classification lifecycle.

**Comment by eatyourgreens** [comment]
I _think_ I've tracked down the bug. When a new subject loads, `actions.feedback.update` is called before `actions.feedback.init`, so the active feedback rules are out of sync with the subject. Drawing a point fires `actions.feedback.update`, so this bug only shows up for subjects that don't require any action to be taken.
