### ISSUE TITLE
Dev server response timing out

### ISSUE THREAD

**Issue by miclaraia** [zooniverse/Panoptes-Front-End#4414]
Running the webpack server locally and trying to connect to it from my phone over LAN. Node appears to be aborting the connection after 5 seconds, which isn't long enough for the ~20MB main.js file to be sent to my phone. Couldn't find an easy way to change the timeout, and I'm not too familiar with how node works.

Tried [this](https://github.com/expressjs/timeout) but the connection continued to timeout after 5 seconds.

**Comment by srallen** [comment]
@miclaraia you could change `localhost` to you local IP on the LAN on this line and it should work by then using that ip address and port 3735 on the browser on your phone:

https://github.com/zooniverse/Panoptes-Front-End/blob/84d6539b46b3a8c9cbeb02085c4ab4e852ffb8aa/dev-server.js#L34

If it still doesn't work, could you let us know what OS you're running the local dev server on as well as the browser. Thanks.

**Comment by miclaraia** [comment]
Yep, I had the bind address set to '0.0.0.0'. I had the server running on my laptop, and debugging it by trying to connect to it from a desktop computer. Both computers are running ubuntu 17.10, and I was trying to load the site on chrome.

If I watch the network in chrome's developer console I can see the main.js file starting to load, and then aborting after 5 seconds. I've noticed the same issue if I'm running the server on the same machine as the browser, and it's just taking a while to load, the connection is terminated after 5 seconds. 

If I connected my laptop via ethernet to the local network then the main.js would be fully received by the other computer's browser, and the page then loads successfully.

**Comment by srallen** [comment]
I'm not sure what might be happening here. It might be a wifi issue? It seemed to load ok and in a reasonable time over wifi on mobile Safari after I set the IP address for the dev server.

**Comment by srallen** [comment]
We might want to consider moving to webpack's dev server rather than running our own custom express server config.

**Comment by miclaraia** [comment]
Yeah, my router at home isn't very powerful, you might have to throttle download speeds to reproduce this behavior. It only happens when a resource takes more than 5 seconds to transfer

I don't think the wifi network is the root cause of this. My wifi is just a slow enough network to exacerbate the symptom. Otherwise it wouldn't have also happened when I was loading via localhost (server and client on the same machine).

**Comment by srallen** [comment]
Yeah, 20 MB is huge for a JS file, but this is in development, so we aren't really worried about optimization typically. We're having to support a lot of libraries that we hope not to in the future, just because we're in the middle of migrating from coffeescript to modern javascript for instance. 

You could try running `npm run serve-static` to get the build file to be optimized. It will use the production build configuration and the `static-server.js` express server, however, you'll lose things like useful source maps and it'll all be minified/uglified.

**Comment by srallen** [comment]
One other suggestion, if this is in an effort to test browsers, then virtualization is a close enough way to do that. You can use Virtualbox to install free dev versions of Windows from Microsoft to test IE or Edge or certain Android OS versions. Chrome dev tools or Firefox dev tools have good mobile emulators as well as XCode from Apple for iOS. 

Also, we recently setup a free Browserstack account, so you can ask one of us to use the virtualizer on that web app to test something out in a PR.
