### ISSUE TITLE
Optimise freehand drawing tools annotation payload

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#4423]
Currently, the freehand drawing tools store annotations in this format:

```
[
	{
		x: 123,
		y: 456
	},
	{
		x: 789,
		y: 123
	}
]
```

@camallen has proposed changing them to store points in this format:

```
[
	[123, 456],
	[789, 123]
]
```

The tools will also need to document the schema used.

This issue is currently blocking #4421

**Comment by camallen** [comment]
I don't have any strong preferences for the schema. The main points it should address:
1. is that it is self documenting or has the schema references for re-use
0. results in smaller annotation payloads
    + remove duplication of schema definition
    + keep less points (up to a max) while still maintaining desired output resolution
    + can tool allow customization of how often a point is recorded?

**Comment by camallen** [comment]
Is there a way to add a new tool with a new data format and leave the current one as is and still usable for existing projects?

**Comment by eatyourgreens** [comment]
Good question. I’ve been wondering if I can make changes to an existing task’s annotation payload, or will that break exports, aggregation etc. that use the existing task format. 

Without versioning, I think the only way to do it is to write a totally new task/tool.

**Comment by eatyourgreens** [comment]
Is this being held up because it would break Etch A Cell?

**Comment by rogerhutchings** [comment]
No, I've been focused on rewrite stuff and should have unassigned myself. It would break Etch A Cell though - @hrspiers, would the EAC team be fazed by us changing the exported data structure?

**Comment by eatyourgreens** [comment]
Other tools, like the ellipse, simply dump the SVG attributes and expect consumers to know how to parse them, so that might not be such a daft idea.

**Comment by camallen** [comment]
@rogerhutchings @srallen can we revisit this in the rebuild? It still causes issues server side.

**Comment by srallen** [comment]
Yeah, definitely, however, I think switching to using the SVG path string, if that's what other drawing tools are doing would probably be a simple fix and make the current tool API more consistent. The issue is that we have to give the projects using the tool a heads up? I think there are projects that are still getting this tool enabled too, so either we should stop doing that if it goes into the rewrite, or do this fix.

**Comment by eatyourgreens** [comment]
There’s at least one project asking on Talk if they can use the freehand drawing tools.
