### ISSUE TITLE
Interactive User Promotion is broken in UI

### ISSUE THREAD

**Issue by amyrebecca** [zooniverse/Panoptes-Front-End#4428]
## Expected behavior
When the user's assigned `workflow_id` is changed to one that doesn't match their `selected_workflow_id` in Panoptes, this change should eventually be reflected in the client-side state.

## Current behavior
The change is never reflected in the client-side state, and in fact the user isn't offered to change workflows until they either reload the page or start a new session.

## Steps to replicate
Use the python client, ruby client, or a caesar rule to change a user's assigned workflow while classifying. Watch the `props` of the `ProjectClassifyPage` component and note that `settings.workflow_id` is never updated, nor is `state.promptWorkflowAssignmentDialog` ever set to true. Note that reloading the page causes the prompt to be displayed immediately. Note that changing `preferences.settings.workflow_id` in a parent of this component DOES cause the correct state update to occur.

## Additional information
Sarah suggests that this update had been performed by one of the `ChangeListener`s in the app and that when it was removed, this side effect was no longer produced. If this is the case, then it's likely this bug has existed for several months. Users of Gravity Spy had reported that the initial promotion was not coming up properly any more but are all eventually getting promoted through new sessions, page reloads, etc. Since we built on this client-side functionality for Snapshot Wisconsin, this behavior is also broken there.

- **Operating system:**
Not an OS-related bug

- **Browser:**
Not a browser bug

**Comment by amyrebecca** [comment]
@marten had at one point made a PR #4116 to replace Sugar, which would be a good candidate for this fix, but I believe it went through pusher which costs us money. The PR was eventually abandoned. We need some kind of mechanism for either polling periodically to get updates to the UPP or receiving notifications when a UPP has changed so that the UI can be updated.

**Comment by amyrebecca** [comment]
To clarify, Sugar currently provides this kind of functionality for notifications and for project completion status but was also written in Coffeescript years ago by someone that is no longer on-staff so it isn't an ideal place to put new code.

**Comment by marten** [comment]
No, Comms started as a hackday project. It's a Sugar-like thing written in Elixir, since Phoenix provides pretty much all we want out of the box, including a JS client library. We tried putting it up on Swarm, but didn't have enough time to get websockets working there. If it's a priority, I'm sure we can try deploying the backend again and get #4116 updated (or write a new one like it).

**Comment by srallen** [comment]
Ok, I wanted to check in in case there was a plan that I was unaware of. Sounds like Sugar is best for the immediate fix.

**Comment by srallen** [comment]
FWIW, Panoptes could be setup to broadcast to Sugar with the UPP settings is updated and PFE could subscribe to it. I'll open an issue for Panoptes.

**Comment by amyrebecca** [comment]
This seems like the sanest solution to me. Shouldn't take that much extra developer time on the front-end once those updates are coming through Sugar to start consuming them.

**Comment by srallen** [comment]
Closed by #4451. If we move to Sugar for the notification, should be a separate new issue.
