### ISSUE TITLE
Survey responses (summarized) from Season Spotter beta

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#443]
@brian-c @mrniaboc @DarrenMcRoy @aliburchard @chrislintott 
I know y'all are super busy with launching Panoptes, so I'm making this an issue you can refer back to later. But it might be helpful in guiding responses back from Panoptes beta.

We had 41 survey responses to our beta test, which is great, but it's a lot to go through. So I thought I'd summarize the Panoptes-related feedback from responses (as opposed to the feedback specific to Season Spotter). In order of most serious/frequent:

1. Overall, there were a lot of vague, but generally **positive comments about the look and feel of the interface**. People thought it looked "clean" and was intuitive and easy to use. 

1. **Drawing tasks were noted by many people to be very difficult.** In particular, the drawing tools were seen as being "clumsy" and unintuitive. Several requested a tutorial specifically about how to use the drawing tools. We used the **ellipse tool** and the **polygon tool** in Season Spotter. (We also used the point tool, but there were no negative comments about it.) Here are the specifics:
  1. Users on **mobile devices** couldn't use the drawing tools at all, or only with great difficulty
  2. Users had trouble **switching from one tool to another** (we asked them to circle different things with different colors) (*"Even though I switched plant types, the first lines of the new plant continued in the old color before switching, and then I couldn't find a way to erase the erroneous lines."*, *"I would find it helpful if the shape tools used to mark different plants could be labeled better."*)
  3. Users had trouble **erasing mistakes**. One indicated that when small circles were made, the 'x' to delete the shape wasn't available.
  4. For the **polygon tool, users didn't realize they needed to click multiple times** (*"I couldn't figure out how to draw around an area. It would just mark one place and count that as one plant."*, *"It was also a bit hard at first to understand how the tool to draw the shapes works -- I though[t] I should be holding down the mouse and drawing around the shape all at once, rather than clicking on various points around the shape."*)
  5. Drawing **polygons near one another** proved problematic (*"drawing adjacent polygons became a bit tricky, and I had trouble completing one polygon. It ended up becoming two."*, *"its difficult to mark very close lines as they jump to other points"*)
  * One user was so frustrated by the drawing tools, that she requested we call her to discuss: *"Draw a shape for different foliage is a UI DISASTER – I can’t see what was selected.  When I select a new type of thing to outline, I am still working with the prior one; it's all connected.  the new one does not populate.  the outline does not display after pulling it.  call me to discuss +1 303 [redacted]"*

2. There was an overwhelming request for a **'zoom'** and many additional comments that images were 'too small'. (This might be partially in response to me shrinking images so that the questions don't bounce from the side of the image to the bottom of the image. But it's also because people want to be able to see the image at higher resolution.) I'm wondering how much things vary depending on screen size; I don't have a lot of screens to test on. And I still don't have a good feel for what size images I should provide as a project creator. This sort of feedback makes me think I should upload full-size images, so people with big screens can get high resolution (and those with small screens can "zoom in" manually).

3. There was **overwhelming appreciation for the "Need Some Help" button**. (Note that I put "Need Some Help" on almost every question, and provided quite a bit of content.)

4. Help images did not fully display for some people. Note that I'm using images hosted off-site. I think this makes a good case for making sure **arbitrary image uploads** are supported for avatar, background, and help.

5. A couple comments about the **classification summary page** (when a user finishes a classification). One person was surprised to not be able to go back and change answers when presented with the summary. Another just thought it looked odd.

6. One person lamented not being able to use the **keyboard arrow keys** to navigate multiple choice questions

7. Users generally didn't know about the **metadata button**. Many of them asked for location info for our photos as a nice extra to have. That information is in the metadata, though, indicating that they never saw the metadata button -- or at least never tried clicking it. A few people did, however.

**Comment by DarrenMcRoy** [comment]
Thanks for this, @vrooje -- Just a couple thoughts.

2 - Is there a reason that we can't use a drawing tool similar to what we use on Floating Forests to select kelp beds? That tool has always worked fairly smoothly and seems to be self-explanatory. It also offers unlimited free-draw... no shape restrictions or anything.

3 - This has been an overwhelmingly common response to many of our existing projects, and I should have brought it up a long time ago with regard to Panoptes. People really want to be able to zoom, and to zoom effectively. We see this on practically every project, from Higgs Hunters (where it was defended by the science team as a scientific even-the-playing-field decision) to animal projects and even Asteroid Zoo. Even if it won't show higher resolution (although awesome if it can), there are so many projects where you just wish you could see stuff a little closer up, especially when you're looking for small changes, or something way off in the distance. I agree with your thoughts about uploading as large of an image as possible and enabling zooming of some sort whenever possible. I would highly recommend we have some type of zoom function, maybe Google Maps style?

4 - This is good news! The more help people feel like they are getting, the easier it is to overcome the fear threshold. We should never have too many options for giving people assistance. :-)

7 - A subset of users are definitely interested in using their keyboards when possible. It is sometimes faster than using a mouse. Might be worth looking into. Sunspotter, for instance, it has been pointed out, would go even faster if you could just press "f" for "right image" and "d" for "left image."

**Comment by mkosmala** [comment]
2. I would love to see something similar to Floating Forests for a draw tool. Agreed that it is intuitive. But I don't think "free draw" is "in scope" for first release. @brian-c, right?
2. Also, one issue is multiple drawing tools within one "question". It doesn't always seem to work right to switch between tools.
7. Seems like keyboard would be simple for the multiple-choice questions. I'll open an issue for it.

**Comment by brian-c** [comment]
A free drawing tool is marked first-release (#198). @simensta are you still going to be working on this?

**Comment by mkosmala** [comment]
Oooh! Keep me in the loop on the free drawing tool. I'll integrate it into Season Spotter as soon as it's ready.

**Comment by DarrenMcRoy** [comment]
Also, one other thing that occurred to me: We're doing some testing on this with iPads/tablets, right?

Bugs with tablets have plagued several Ouroborous projects for some time now. I'd like to make sure that users get a chance to test Panoptes stuff extensively on tablets. :-)

**Comment by mkosmala** [comment]
@DarrenMcRoy Drawing tools did not work well on tablets in our beta, at least for some users.

**Comment by chrissnyder** [comment]
This is a pretty dense single issue, but leaving it up cause its also important to stay visible. Tagging as "first release" only so we know to look at this feedback as well and decide to take action or not.

**Comment by mkosmala** [comment]
@chrissnyder Would you like me to split it out into separate issues referencing back to this one, and then close this issue?

**Comment by chrissnyder** [comment]
I'd greatly appreciate it. I think a fair amount of it was already been issued up (keyboard shortcuts #453, zoom #278, etc) but additional points, especially surrounding the drawing tools, warrants additional attention.

**Comment by mkosmala** [comment]
This issue has been separated out into component issues and will now be closed.

**Comment by edpaget** [comment]
Thanks so much :+1:
