### ISSUE TITLE
Feedback messages: Optional image display, different location of 'ok' button

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4430]
## Expected behavior
Training subjects (sims or lenses, not duds) 
I would expect the message to show green circles 
but also see below as I requested a change to make this optional in additional information

## Current behavior
the feedback shows a red circle that i thought was reserved for fail messages or is this the new behaviour
![image](https://user-images.githubusercontent.com/1917970/36994922-83db2fda-20aa-11e8-8a67-05df28662e65.png)

## Steps to replicate
G1-G25 are training subjects yielding a success if a marker is placed in the field.

## Additional information
Requested feature: in a previous issue we requested that
- the preview of the classification images with location of the success radius should be optional to be selected by the builder (it doesn't work well with the tiles of the SW images, see above the controls are plotted below and the whole thing isn't necessary as we are interpreting any click on a training subject as a success)
- the placement of the OK button is annoying as one has to scroll a lot from the position of the next button. for a fast look programme like SW this would be a cause of frustration for users. It would be much better if the 'ok' button was in the top right of the feedback window, or the bottom right if it's just a text message without the image e.g. even for the text only dud success the ok button should appear on the right.
![image](https://user-images.githubusercontent.com/1917970/36996142-effa306e-20ad-11e8-8e19-27e58044c98e.png)

PS @trouille @rogerhutchings I will paste other feedback comments into other separate issues - thanks
- **Operating system:**
- **Browser:**

**Comment by rogerhutchings** [comment]
@aprajita can you review to see if this is working for you now?

**Comment by aprajita** [comment]
Yes it is! Thanks very much!
It's much faster to get through images with the button on he other side, and to not have the image viewer.

BTW for projects where they do want to have the image viewer on, will it always be shown with the image buttons plotted below as it was with our test images?
