### ISSUE TITLE
Don't let project owners set inactive workflows as default

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4431]
## Expected behavior
Prevent all cases of making inactive workflows default
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
In the project builder UI, we only prevent this from happening if the project is live. It seems some project builders may be either purposely setting the projects back to development and making the switch or possibly accidentally doing this via the python client. 

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Closed by #4798.
