### ISSUE TITLE
Feedback: subject/feedback mismatch, possible solutions hold subject or change feedback button from 'ok' to 'next'?

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4433]
## Expected behavior
Feedback message appears on top of the subject it refers to

## Current behavior
for any training image whether success or fail the done button loads the next image **before** the feedback message/modal for the subject it corresponds to is shown

e.g. for the subject here (training dud) 
![image](https://user-images.githubusercontent.com/1917970/37184574-e51c09aa-2333-11e8-8136-5f26a4e46ee0.png)

the corresponding feedback message for this training subject appears overlaid on the next subject
![image](https://user-images.githubusercontent.com/1917970/37184584-eef88e12-2333-11e8-82ce-e1859b0ca325.png)

Potential consequences after returning to the classification screen after pressing OK is that the user thinks the subject shown is the one they just did and proceeds to pressing done, thus missing a classification (I found a couple of times, i didn't recall the image i viewed and I automatically went to done after clicking ok without noticing the underlying image had changed).

This gets even more confusing if that next image is also a training image and no marker placed triggers another feedback message.

Possible remedies:

- For training images done on the screen produces the feedback message but the loading of the next image is triggered by pressing the ok button on the modal feedback message. From earlier issues where we discussed something similar, I realise this isn't something you are comfortable with since the done button then has a different action for training images (to feedback) than non-training (to next subject). I understand that perspective but to me this seems like a reasonable solution to hold the current subject or delay the next subject until the button in the feedback window is pressed  if possible.

- If this isn't possible, I wonder if changing 'ok' to 'next' in the feedback modal is more likely to avoid people skipping he subject - perhaps this is something we can test in the beta or with our smaller team of initial testers/collaborators.

## Steps to replicate
Classify any training image.

## Additional information
FAO: @trouille @rogerhutchings 

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
This is actually the same bug as #4434. Feedback should interrupt the current action (loading the next workflow task, navigating to Talk, loading a new subject) then resume that action when the modal closes. 

This might require me to finish off the work I started on the classification lifecycle, while @rogerhutchings was away.

Also, in workflows with more than one task, we should check what happens when you press Back. I think the current setup might fire off feedback whenever the task changes, going forwards or backwards through the workflow.

**Comment by aprajita** [comment]
ok thanks @eatyourgreens 
@trouille asked me to flag up issues on the new feedback, hence the new issues.

**Comment by eatyourgreens** [comment]
This should have been fixed by #4450.

**Comment by rogerhutchings** [comment]
@aprajita can you review to see if this is working for you now?

**Comment by aprajita** [comment]
ys, i think so, it all seems to be working great.
thanks so much @eatyourgreens & @rogerhutchings
