### ISSUE TITLE
Feedback: Missed classifications with Done&Talk

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4434]
## Expected behavior
For training subjects (duds or lenses) I expect to see the feedback success or fail window whether I go to done or done&talk...
 
## Current behavior
![image](https://user-images.githubusercontent.com/1917970/37185580-e64cbc70-2338-11e8-93cf-a96e313467c8.png)

... but done&Talk takes me to the talk page without delivering the feedback message.
Returning from talk takes me to the next subject so i never see what the feedback message. 

In the older (non-modal) version of the feedback, this was a risk for duds but not for other training subjects. We thought the risk of losing some dud classifications wasn't ideal but we could live it. Indeed i think roger mentioned that this was a motivation to move to modal feedback that would solve this, but now the risk to miss classifications is for all training images and that seems to be a much larger. See discussion in closed issue [#4078](https://github.com/zooniverse/Panoptes-Front-End/issues/4078) 

given the done&talk button as fa as i understand doesn't register a done but is a link to talk, i am unsure how to remedy this without enabling the classification summary screen which we wanted to avoid.

## Steps to replicate
press done & talk in any training image

## Additional information
FAO @trouille @rogerhutchings 

- **Operating system:**
- **Browser:**

**Comment by aprajita** [comment]
i believe classifications will be missed for any subject not just training subjects - is that right or are the marks recorded in the database when done&talk is pressed?

**Comment by eatyourgreens** [comment]
Same bug as #4433 I think. Feedback should hijack the link to Talk and only follow it after you close the modal.

**Comment by eatyourgreens** [comment]
This should have been fixed by #4450.

**Comment by rogerhutchings** [comment]
@aprajita can you review to see if this is working for you now?

**Comment by aprajita** [comment]
Yes,it is! thanks very much. 
There's just my own human error pressing done immediately after closing the modal automatically without checking that the image is actually different. But i think that's just going to be done once or twice for most users, and then you get used to not making the mistake again.
