### ISSUE TITLE
Volunteer reporting that seeing 'finished' /'already seen' banner with subjects in a loop

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4435]
From the P4: Ridges project: This is one of the super users so they could have gone through the full set, but not sure why the images are looping

> Hi Meg,
Yesterday I started to get "Already Seen" banners. No new images, just 4 or 5 with the banner, repeating in a loop. Thinking it might be a glitch I logged off and tried again today. The exact same thing is happening, with the same images. I thought I still had 1300+ images to classify, but if I've really finished why don't I get that banner? Thank you.
Edit: March 7. The situation continues exactly the same.

**Comment by mschwamb** [comment]
Link to the Talk post: 

https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/667/539667?comment=940869

**Comment by eatyourgreens** [comment]
@camallen Is this Panoptes bug with the subject queue for a specific user ID? If it was a bug in PFE, it wouldn’t persist across different browser sessions and refreshing the page would clear it.

**Comment by camallen** [comment]
Might be they have classified the available data as a power user, though the project counters point to an issue with the selector service. 

FYI - we do serialize the `retired, already_seen, finished_workflow, favorite` fields for each subject  the queued subject request response. The UI doesn't use the `finished_workflow` field which indicates both the workflow is 100% complete or the user has completed all the non-retired available data. 

I'll have a look today if i get time while travelling.

**Comment by camallen** [comment]
It looks like this is now working based on the talk post. Please re-open if it's still an issue.
