### ISSUE TITLE
Add more checks before allowing beta application

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#4448]
@mrniaboc would like the following things to be checked before we let a project owner apply for beta status:

- [ ] Check that more than one Talk board is set up
- [ ] Check for tutorial
- [ ] Check for help text
- [ ] Check the team page has content
- [ ] Check the research page has content (I think we may already do this?)
- [ ] Check for researcher quote
- [ ] Check for background image and avatar

I'm rewriting the beta validation section at the moment to break out the code and make adding these checks easier, so I'll get that merged before adding new code.

**Comment by mschwamb** [comment]
Thought I would give my perspective as a project owner on a few panoptes projects:

A tutorial should not be required to be apply for beta.  Planet Four: Terrains would fail that test. It launched before a tutorial was even available and we already have a published science paper.  Some projects a simple help would might be sufficient with just help content or a site guide. I am sure there are other types of projects that might be successful with just a help box content. 

Also for Comet Hunters, I don't have a researcher quote setup. A researcher quote, I don't think should not be required to apply to beta. It's really cosmetic and the front end is setup, to handle not having one.

**Comment by mrniaboc** [comment]
I agree with Meg on both of these points. My dream would be fore people to
think about how to build their workflows and tasks in a way so simple they
don't need a tutorial. I shouldn't have added it to this list, sorry.
