### ISSUE TITLE
Create Notes board when creating a new project

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#4449]
At the moment, when a new project is created, we give people the option of creating a Notes board, saying it's "strongly recommended". We could just create it as part of the new project process.

Is there any reason we shouldn't do this?

cc @mrniaboc

**Comment by mrniaboc** [comment]
I really think we should just create the Notes board automatically, and
maybe allow the Project Owner to change the name of it?

**Comment by mrniaboc** [comment]
What about just switching the current functionality then? Allowing them to
disable the Notes board if required.

**Comment by camallen** [comment]
I just checked and we can delete the auto-created boards for the very few projects that won't use them. As you were gentlemen, carry on.
