### ISSUE TITLE
Project Lab Navbar: Custom Link Appears Modified

### ISSUE THREAD

**Issue by RustyPanda** [zooniverse/Panoptes-Front-End#4456]
## Expected behavior
Adding a project navbar link via Lab 'Project Details' page adds exactly that link

## Current behavior
Within the Galaxy Zoo project:
The text 'Blog' and url 'https://blog.galaxyzoo.org/' create a link on the project navbar to 
'https://blog.galaxyzoo.org/?_ga=2.20329649.843077535.1520851415-464488961.1507208045'

Note that this link does open the blog correctly - but I would like to check this is expected behaviour

## Steps to replicate
Add the above text and url to the Galaxy Zoo project on Panoptes

## Additional information

- **Operating system:**
Mac OSX
- **Browser:**
Firefox

**Comment by eatyourgreens** [comment]
That’s Google Analytics tracking clicks on external links.
