### ISSUE TITLE
Send data dump to requestor only, not all collaborators.

### ISSUE THREAD

**Issue by willettk** [zooniverse/Panoptes-Front-End#446]
When I request a CSV data dump via email, it gets sent to all collaborators on the project. Can we change that to only the person who requested it? I can foresee people being annoyed if you're on a large collaboration and someone requests data dumps every hour. @melaniebeck

**Comment by camallen** [comment]
@willettk how about an option to mail collaborators as well (default false)?

**Comment by willettk** [comment]
Good idea! - might be the easiest way to share recent data. Fine by me, as
long as the default is false.

**Comment by mschwamb** [comment]
See #399 as well
