### ISSUE TITLE
survey task breaks when navigating within project

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#4464]
## Expected behavior
Anytime I'm on the classify interface with a survey task the survey task should load.

## Current behavior
If I go to classify in a project with a survey task, then click the link to Talk, then click back to Classify, the survey selection table is missing. e.g.:

![screen shot 2018-03-16 at 3 39 04 pm](https://user-images.githubusercontent.com/2357126/37547770-d71d8ab0-2930-11e8-85ef-85f415e6f476.jpg)

 becomes

![screen shot 2018-03-16 at 3 39 29 pm](https://user-images.githubusercontent.com/2357126/37547782-e10cc644-2930-11e8-99d1-18fdc9364437.jpg)

after clicking Talk, then clicking Classify again.

## Steps to replicate
I saw this report on [Wildwatch Kenya Talk](https://www.zooniverse.org/projects/sandiegozooglobal/wildwatch-kenya/talk/952/576331?comment=956029) and then replicated it on a [different project](https://www.zooniverse.org/projects/vrooje/galaxy-zoo-workflow-tests/classify) I'm working on that also has a survey task.

The users on WWK noticed it when the invert button was added to the classification interface, but it's unclear whether that's related (I don't have to use the button to get the behavior to occur).

## Additional information

- **Operating system:** OS X, plus whatever the WWK users were using
- **Browser:** Chrome Version 63.0.3239.132 + unsure what others are using

**Comment by srallen** [comment]
I am able to replicate this, but there aren't any errors in the console, so it isn't obvious why the survey isn't re-rendering.

**Comment by eatyourgreens** [comment]
I’ve been able to reproduce this with a drawing task. I think it’s caused by changes in classifier state that were introduced in #4450.
