### ISSUE TITLE
Can't set featured project.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#4466]
## Expected behavior
Being able to set a new feature ject, with no errors, even when one is already set.

## Current behavior
<img width="594" alt="screen shot 2018-03-19 at 11 58 25" src="https://user-images.githubusercontent.com/8989606/37594415-ef34097e-2b6c-11e8-9550-cc7639da1c7d.png">

## Steps to replicate
Try to set a new feature ject.

**Comment by camallen** [comment]
@simoneduca the API only allows 1 featured project at a time. The previous one will have to be unset before the new project can be set to be featured.

**Comment by simoneduca** [comment]
@camallen I think the issue is not that. I do that [here](https://github.com/zooniverse/Panoptes-Front-End/pull/4477/files#diff-64155b1c6bf79c2446c9802affb774b4R135).
