### ISSUE TITLE
workflow with recursive question pre-populates with previous annotation

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#4469]
## Expected behavior
https://www.zooniverse.org/projects/sroosa/roll-the-credits
in Demo mode, pretend there is single complete credit block with 4 names
after entering 3rd name, question task - "Is there another name in this credit block?" Y/N, if Y...
expect empty text inputs

## Current behavior
https://www.zooniverse.org/projects/sroosa/roll-the-credits
in Demo mode, pretend there is single complete credit block with 4 names
after entering 3rd name, question task - "Is there another name in this credit block?" Y/N, if Y...
inputs filled with 3rd name, even if change annotation doesn't save

## Steps to replicate
see https://www.zooniverse.org/lab/4836/workflows/5085
^ workflow has many combo tasks, possible improper/recursive/corrupt references?

recreated in staging: 
- classify https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-2-mb/classify?workflow=3172
- lab https://master.pfe-preview.zooniverse.org/lab/1775/workflows/3172

sane workflow with same problem:
- classify https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/test-project-2-mb/classify?workflow=3173
- lab https://master.pfe-preview.zooniverse.org/lab/1775/workflows/3173

likely due to #4450, mentioning @eatyourgreens

**Comment by mcbouslog** [comment]
This workflow is crazy.

**Comment by eatyourgreens** [comment]
I think this is caused by #4440, which assumed each task would have one annotation. I didn’t consider recursive workflows. It might be worth reverting #4450 and #4440 if this is breaking live projects, and we’ll think of a different way to fix feedback.

**Comment by mcbouslog** [comment]
^ agreed, might be best to revert. I recognize if we're going to revert, the sooner the better, but I was going to try to fix more this evening (after 9pm CST), though I have no particular fix in mind, so understand if best to revert asap. Thoughts on revert timing (asap vs if can't fix by ___)?

**Comment by eatyourgreens** [comment]
I think the annotation code should be using `lodash/findLastIndex` where it’s currently using `lodash/findIndex`. That might be worth trying for a quick fix.

**Comment by eatyourgreens** [comment]
If that doesn’t work then #4440 should be reverted.

**Comment by mcbouslog** [comment]
I think that does it, I've swapped out `findIndex` for `findLastIndex` in `classifier.jsx` and `task.jsx`. PR incoming, though haven't gone through PR checklist yet...
