### ISSUE TITLE
Stuck with the order you created marking tools in the project builder  

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4472]
You can swap order of workflows and steps in a tutorial, but once I create a drawing tool marker I cannot  swap the order of the choices even if the project is still in development stage. 
<img width="1134" alt="screen shot 2018-03-20 at 1 39 09 pm" src="https://user-images.githubusercontent.com/753325/37657946-41e1efba-2c44-11e8-9463-56332c1d2fe3.png">

Currently I'd have to delete the maker type and create a new one in the correct place I wanted to have it show up in the list of drawing tools in the project's classification interface. In this example image above, I'm talking about moving blotch to be before fan in the classification interface. 

Perhaps the same way you can order workflows can be employed here.

**Comment by mschwamb** [comment]
This is pretty annoying that I have to delete the top marking tool if I want to change the order of the tools in the classification interface.

**Comment by eatyourgreens** [comment]
I think this will involve rewriting the choices section of the task editor:
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/generic-editor.cjsx#L100-L260

There might be plans to rewrite that editor as part of [zooniverse/pfe-lab](https://github.com/zooniverse/pfe-lab).

**Comment by srallen** [comment]
Yes, I'd like to minimize work on the current lab to critical bug fixes. New features should go into the lab app so we can begin porting over the project builder half, but I doubt anyone has time right now for that. Maybe early next year at the earliest?

**Comment by mschwamb** [comment]
So should I put this ticket in the pfelab issues?

**Comment by srallen** [comment]
You're welcome to open issues on that repository, but as I said, I'm not sure when it'll be addressed.
