### ISSUE TITLE
Should the Explore Project dropdown menu support the cursor keys?

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4479]
## Expected behavior
Whenever I open the Explore Project menu with the enter key, I instinctively press the up and down keys to navigate the menu.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Up and down keys scroll the browser window, even if the menu is open. Compare this with the user profile menu, where the cursor keys navigate the menu items.

## Steps to replicate
Find a project that uses the Explore Project dropdown menu, and open the menu from keyboard.

**Comment by beckyrother** [comment]
Agreed, this makes sense. 👍
