### ISSUE TITLE
Include desired recipients in classification exports create

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes-Front-End#448]
After zooniverse/Panoptes#916 is done. You'll need to specify recipients for the classification exports notification email. Basically you just include their ids in the metadata hash you can pass to that endpoint. 

``` json
{
    "media": {
        "content_type": "text/csv",
        "metadata": {
            "recipients": [1,2,3]
        }
    }
}
```

Thinking more the requesting user could probably just be included by default by the backend, too.

**Comment by chrissnyder** [comment]
Export works now, but could potentially add an interface to specify who we want to send it to.
