### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by Kryokina** [zooniverse/Panoptes-Front-End#4489]
## Expected behavior
npm start is supposed to run with NodeJS in a Terminal window once npm has been installed.  Once running, the npm start command is supposed to load a webserver running your local version of the front-end at http://localhost:3735.  With npm start, I am supposed to be able to test locally a change to the GitHub Panoptes Front End code.
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Even though npm has been successfully installed, I still receive a bunch of errors when running npm start.  Below is a copy of the debug log, in case that will help:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@4.6.1
3 info using node@v8.9.4
4 verbose config Skipping project config: /Users/mnsguest/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle mnsguest@1.0.0~prestart: mnsguest@1.0.0
7 silly lifecycle mnsguest@1.0.0~prestart: no script for prestart, continuing
8 info lifecycle mnsguest@1.0.0~start: mnsguest@1.0.0
9 verbose lifecycle mnsguest@1.0.0~start: unsafe-perm in lifecycle true
10 verbose lifecycle mnsguest@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mnsguest/node_modules/.bin:/Users/mnsguest/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin
11 verbose lifecycle mnsguest@1.0.0~start: CWD: /Users/mnsguest
12 silly lifecycle mnsguest@1.0.0~start: Args: [ '-c',
12 silly lifecycle   '/Users/mnsguest/Downloads/Panoptes-Front-End-master/app/main.cjsx' ]
13 silly lifecycle mnsguest@1.0.0~start: Returned: code: 2  signal: null
14 info lifecycle mnsguest@1.0.0~start: Failed to exec start script
15 verbose stack Error: mnsguest@1.0.0 start: `/Users/mnsguest/Downloads/Panoptes-Front-End-master/app/main.cjsx`
15 verbose stack Exit status 2
15 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
15 verbose stack     at emitTwo (events.js:126:13)
15 verbose stack     at EventEmitter.emit (events.js:214:7)
15 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
15 verbose stack     at emitTwo (events.js:126:13)
15 verbose stack     at ChildProcess.emit (events.js:214:7)
15 verbose stack     at maybeClose (internal/child_process.js:925:16)
15 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
16 verbose pkgid mnsguest@1.0.0
17 verbose cwd /Users/mnsguest/Documents/Emilys_Folder
18 verbose Darwin 15.6.0
19 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
20 verbose node v8.9.4
21 verbose npm  v4.6.1
22 error code ELIFECYCLE
23 error errno 2
24 error mnsguest@1.0.0 start: `/Users/mnsguest/Downloads/Panoptes-Front-End-master/app/main.cjsx`
24 error Exit status 2
25 error Failed at the mnsguest@1.0.0 start script.
25 error This is probably not a problem with npm. There is likely additional logging output above.
26 verbose exit [ 2, true ]

## Steps to replicate
Run npm install successfully in a Terminal window.  Then, type npm start in the Terminal window.
## Additional information

- **Operating System:** OS X El Capitan version 10.11.6
- **Browser:** Firefox 59

**Comment by simoneduca** [comment]
After installing npm, you're supposed to [install all the necessary libraries by running `npm install`](https://github.com/zooniverse/Panoptes-Front-End#development) in your terminal.
If you've done that already, then try [refreshing your dependencies by running `rm -rf ./node_modules && npm install`](https://github.com/zooniverse/Panoptes-Front-End#it-doesnt-run).

**Comment by srallen** [comment]
@Kryokina could you try updated npm itself? Our package.json lists npm version 5 as the minimum required. This can be done by running `npm i -g npm`

**Comment by Kryokina** [comment]
I tried using all the commands you gave me @simoneduca @srallen .  I'm still receiving errors when I try npm start.

**Comment by Kryokina** [comment]
@camallen or anyone else, do you know what might be the solution to npm if everything is updated?

**Comment by Kryokina** [comment]
Update: I've tried a few different things.  First, I ran through these commands:
$ npm install -g create-react-native-app
$ create-react-native-app my-app
$ cd my-app/
$ npm start
npm start gives me code ELIFECYCLE, errno 1.  Then, when I go back out from the my-app folder with $ cd .., npm start gives me code ELIFECYCLE, errno 2.  Then, I tried the same four commands on a fresh new Mac computer, and I still got code ELIFECYCLE, errno 1, but when I used $ cd .., I got code ENOENT, errno -2.

Hope this helps someone help me solve my problem!  I'm seriously missing something here.  :/

**Comment by srallen** [comment]
`create-react-native-app` is a command line interface (CLI) tool for starting greenfield react native projects which run on Android or iOS. I'm not sure why the newly created apps using this CLI weren't working for you. Did you run `npm install` to install dependencies before running `npm start`? Regardless, it shouldn't be needed here since this is not a react-native project. 

Given that you've also opened #4495, are you trying to run the app after you've edited code? Perhaps this is why it is failing to start.

For this issue just to get this project running please do the following:
- Confirm that you have at least node version 8 and npm version 5 running.
  - check by using `node -v` and `npm -v` on the command line
- use `git clone` and the appropriate url from github depending on how you have authentication setup to clone this respository
- cd into the cloned repository folder
- run `npm install` to install the dependencies
- run `npm start` without modifying any code

If the above steps are successful, then you know the issue is with modifications to the code you may have made. Some of the component files are written in coffeescript and coffeescript is white-space significant. This can be a common cause of compiling errors.

If it is unsuccessful after cloning a fresh copy, after you've confirmed the correct node and npm versions are installed, and after the dependencies are installed with npm install, then I would suggest making sure that there isn't anything wrong with your node setup. Did you install node via homebrew or nvm?

**Comment by Kryokina** [comment]
@srallen I have the correct versions of npm and node.  git clone doesn't work with this link: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/drawing-tools.  Also, I have tried modifying the start script, and that changes the results I'm getting. I'm still having errors, but I wonder if they're because I'm not sure what to put in the package.json start script.

**Comment by camallen** [comment]
@Kryokina 
> git clone doesn't work with this link:

You need to clone the whole repository not just one file. A repository and git is an all or nothing thing. Please try cloning a fresh copy of the repository again in a new directory, e.g (assuming os x / linux). 
+ `cd ~ # change to your home directory`
+ `mkdir zooniverse_code # make a new dir for the zooniverse code`
+ `cd zooniverse_code # change to that zooniverse code directory`
+ `git clone https://github.com/zooniverse/Panoptes-Front-End.git` or if using ssh `git clone git@github.com:zooniverse/Panoptes-Front-End.git # clone the PFE repo in one go`
+ `cd Panoptes-Front-End # change to the PFE directory where the code lives`
+ `npm install # install the PFE dependencies via npm`
+ `npm start # run the start script in package.json` https://github.com/zooniverse/Panoptes-Front-End/blob/2321383d52cb492ec28d9e6c7ecf64eaac86117d/package.json#L124 

please report back here and do please tell us what OS (operating system) and the node and npm version as well by running `node -v` and `npm -v` on your command line. This is important to help us debug the issue.

**Comment by Kryokina** [comment]
@camallen Thank you so much!  Your step-by-step instructions were super helpful!  npm start is finally doing something instead of returning errors!  And for your information, node -v is v8.9.4 and npm -v is 5.8.0 and I have Mac OS X El Capitan version 10.11.6.  Thanks again!

**Comment by camallen** [comment]
🎉excellent news - do feel free to ask for more help here if you need.

**Comment by Kryokina** [comment]
@camallen For some reason, npm start is not working again.  I even went through all your steps again, but nothing seemed to solve the errors.

**Comment by Kryokina** [comment]
I got npm start to work by reverting to an older version (5.6.0 instead of 5.8.0), but I don't know how to use it.  Any guidance on how I can use it to test locally a change to the GitHub Panoptes Front End code?

**Comment by Kryokina** [comment]
@eatyourgreens Thank you so much!  It seems to have some bugs, but the url in the npm README.md file (http://localhost:3735/projects?env=production) worked a lot better.  I still can't sign in though, but I suppose this was intended.  Thanks again for your help!  :)

**Comment by eatyourgreens** [comment]
The production server won’t let you sign in from localhost, but you can access our staging server from http://localhost:3735 if you need to test anything that requires authentication.

**Comment by Kryokina** [comment]
Actually, my co-worker described the issue better here: https://github.com/zooniverse/Panoptes-Front-End/issues/4641.

**Comment by Kryokina** [comment]
@eatyourgreens Unfortunately, localhost:3735 still won't let me sign in to test our unpublished project.  :(

**Comment by srallen** [comment]
Authentication for production user accounts will fail when running the site locally for development. You'll see a CORS error. What @eatyourgreens is saying is that you have to register an account with our staging API and use that to authenticate when developing locally. Does your project exist only on production? You may also need to setup a parallel staging version of the project too.

**Comment by Kryokina** [comment]
@srallen Ok, thanks so much!  Registration through the staging API worked well.  Also, do you know how we can gain access to experimental tools for our project?  We want to see if we can use a tool similar to the Spiral Arm Tool in the Galaxy Builder project, and we noticed that the experimental freehandSegmentLine tool seems to be what the Spiral Arm Tool is based on.  Thanks!
