### ISSUE TITLE
Dropdown nav menu doesn't close on phone screens

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4491]
## Expected behavior
After navigating to a new page, the menu should close.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
After navigating from Talk to Classify, the menu stays open, obscuring the subject.
![screenshot from Snapshot Serengeti, showing the nav menu in front of the subject photo.](https://user-images.githubusercontent.com/59547/38088478-dde68aea-3353-11e8-932c-12db66f2d29d.png)

## Steps to replicate
Open the menu from a project Talk, on your phone, and select Classify.

## Additional information

- **Operating system:** iOS 11
- **Browser:** Safari

**Comment by simoneduca** [comment]
The code LGTM, but just wanted to try replicating the issue. Have you staged it at all?

**Comment by eatyourgreens** [comment]
The link should be in the PR: #4497

**Comment by simoneduca** [comment]
Sorry I just realised that 🤦‍♂️
