### ISSUE TITLE
Running Edited GitHub Code on My Project Instead of All Projects

### ISSUE THREAD

**Issue by Kryokina** [zooniverse/Panoptes-Front-End#4495]
Once I can get npm start to run to test the code locally to ensure it works successfully, how will I upload the code to run it solely on our project instead of applying it to all projects on Zooniverse?  The only change I'm trying to make is turning off the dashed line on the bezier tool.

@camallen

**Comment by camallen** [comment]
Are you running your own API or using our API? I.e. do you build your project using our API (https://www.zooniverse.org/lab) but want to point your modified code at your lab project?

If you are using our API, you'll need to deploy your application to a web server or run it locally on your machine. Once that is done you can load the code via the URL of your webserver and test your project. Note if you are running your code locally by default PFE will hit the staging API, you'll need to add they query param `?env=production` to find your project.

Also signin will have issues as you are running our PFE code against our API and we lock down cross domain requests to authorised domains.

If you are not using our API then it's more complicated and you have to modify the underlying javascript api client. I can provide details if you need them.

**Comment by srallen** [comment]
Question answered.
