### ISSUE TITLE
project tutorial button shouldn't be showing on the classification summary page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4507]
This looks like a side effect of the changes to the classification interface. When you've submitted the classification and the summary shows the  tutorial button remains (but the other help button disappears). I think this is confusing. Can the tutorial button be hidden as before when the project summary shows? @beckyrother 

<img width="1100" alt="screen shot 2018-04-06 at 6 36 40 am" src="https://user-images.githubusercontent.com/753325/38433272-eec45406-3965-11e8-8926-f15081abc9f6.png">

**Comment by beckyrother** [comment]
Hi @mschwamb, this button has actually always been on this screen – maybe it's just more visible against the light background. We're working on completing the dark theme so it'll be less noticeable soon.

**Comment by mschwamb** [comment]
@beckyrother perhaps that why I notice it or it was further below.  Should that button be on that screen, if it's the summary of the classification?
