### ISSUE TITLE
subject linking still breaking

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#451]
Apologies if this is a duplicate; I couldn't find the issue about it.

A science team I'm working with is still getting "No subjects available for workflow" errors, even after waiting several minutes after linking the subject set to the workflow. Is this still an expected issue for now?

![screen shot 2015-06-01 at 8 33 42 am](https://cloud.githubusercontent.com/assets/6217406/7916763/cf8eac74-087d-11e5-89d0-52c318640332.png)

**Comment by camallen** [comment]
I know what this error is. Is this on demo?

**Comment by aliburchard** [comment]
It's specifically happening on the preview site (haven't checked on demo since we moved over).

**Comment by camallen** [comment]
Should be fixed now, checking with the user again.

**Comment by aliburchard** [comment]
seems fixed. I'll re-open if it crops up again.
