### ISSUE TITLE
The last comment link for Talk threads, no longer goes to the correct position (scrolls too far)

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4515]
This might be related to the change of the header size. If I click on the link on the Talk boards for the most recent post in a thread, the thread is loaded,but now webpage is scrolled to after the last post so there's nothing on the screen and you need to scroll up:

example: going to this https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/780/585919?page=1&scrollToLastComment=true 

<img width="1095" alt="screen shot 2018-04-14 at 8 41 16 pm" src="https://user-images.githubusercontent.com/753325/38775746-5a088fe6-4025-11e8-84c7-09891b87264f.png">

Previous it would have the top of the latest post as the top of the screen, where now it's the bottom of the post. 

It doesn't seem to be everything for example:  https://www.zooniverse.org/projects/mschwamb/planet-four-terrains/talk/8/548468?page=1&scrollToLastComment=true

that seems to work fine.

**Comment by mschwamb** [comment]
Experiencing this  in Firefox. I haven't checked the other browsers

**Comment by eatyourgreens** [comment]
Those links scroll to the bottom of the page. I'm not sure why the code is set to do that, but it looks like it's been that way for a long time. #4515 updates the discussion page to scroll to the last comment when `scrollToLastComment` is in the URL.

**Comment by mschwamb** [comment]
Thanks @eatyourgreens
