### ISSUE TITLE
History of the Zooniverse - who can help?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#452]
(NOTE: THIS ISN'T PLANNED FOR FIRST LAUNCH AND SHOULD BE LOWER PRIORITY TO THINGS THAT ARE!)

The next ZooHome page that I'd like to work on would be a History of the Zooniverse page... nothing too in-depth, maybe 6-7 grafs.

However, as more of a newcomer than most, I could use some help putting that together, from some folks who have been around longer than I. Would anyone be willing to volunteer to assist with the background information for this? Perhaps with finding some old images that might go well with it, too?

Thanks!

**Comment by chrislintott** [comment]
Perhaps you could base this on the blog?
