### ISSUE TITLE
Field Guide: Comments from SW-HSC Beta

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4532]
I think I saw the field guide is being redesigned so maybe these are solved by that...?

I am going to issue each found "bug" here but feel free to separate.

@trouille bringing these to your attention

## Current behavior
**(a) Chrome Mac OS X: Field guide tab not visible**
scroll bar overplotted on tiny field guide tab, barely visible, people reporting they can't see it
![image](https://user-images.githubusercontent.com/1917970/38969726-9c056bfa-4389-11e8-8841-2bd57ab8c1a2.png)

**(b) go back '<' not obvious**
some users are reporting that it's not easy to see the "<" button to return to the main screen - is  possible to make this more obvious somehow?
![image](https://user-images.githubusercontent.com/1917970/38969902-62089732-438a-11e8-9628-e0c1db29d85b.png)

**(c) Field guide doesn't open in firefox 59.0.2 (mac osx 10)**

**(d) Flickering field guide window** 
some users are reporting that the pop-up FG "shimmers' or flickers, I dont see this mslf on the FG but do see it on the tutorial window. Movie in this pptx
[FlickeringTutorialSmall.pptx](https://github.com/zooniverse/Panoptes-Front-End/files/1927012/FlickeringTutorialSmall.pptx)

**Comment by aprajita** [comment]
@trouille is anyone able to look at these? thanks

**Comment by trouille** [comment]
Related to #4592

**Comment by beckyrother** [comment]
@aprajita these will indeed be solved by the classify redesign. 

Point (d) from your list above may be related to #4592 – the scroll bar gets in the way of the button. Closing this issue as it's being addressed other places.
