### ISSUE TITLE
Copied marks can be edited inside feedback modal

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#4535]
Related to #4524 

## Expected behavior

Marks shown in the feedback modal should be deselected and unmovable.

## Current behavior

The most recent mark is selected, and other marks can be selected, moved, deleted etc. This doesn't affect the marks on the subject, or the submitted classification

## Steps to replicate

Open a project with feedback enabled, and mark up a subject with feedback and with `hide subject viewer in feedback` disabled.

**Comment by eatyourgreens** [comment]
I'm not quite sure how to fix this, but this is happening because marks for the current task are always editable, and you haven't moved on to the next step in the workflow yet when feedback is checked.

**Comment by eatyourgreens** [comment]
Wait, setting 'panEnabled=true' on the viewer seems to turn off the ability to draw/edit marks.
