### ISSUE TITLE
SW-HSC Demo Talk&Discuss freezes browser

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4549]
## Current behavior
A user reports that: When I hit talk and discuss, nothing happens but my browser freezes and I have to refresh. I'm using Firefox on Linux (Firefox 47.0 and Ubuntu 4.8.2)

**Comment by eatyourgreens** [comment]
Firefox 47 is very old. The latest version is 59. Have they tried updating Firefox to see if that fixes the problem?

**Comment by aprajita** [comment]
will ask - thanks.
