### ISSUE TITLE
Projects disappeared?

### ISSUE THREAD

**Issue by melaniebeck** [zooniverse/Panoptes-Front-End#456]
Was a big change implemented? "The Lab" button no longer appears at the top near the user name and my project no longer appears on the Projects page (it was a public project).

**Comment by melaniebeck** [comment]
Sorry -- I found where the project is but I still can't find where I can download the data. It's as though I no longer have access to The Lab entirely and can only classify on the project I created.

**Comment by brian-c** [comment]
The lab link has been removed temporarily. It's still available at `http://preview.zooniverse.org/panoptes/#/lab`.

**Comment by melaniebeck** [comment]
Thanks, Brian
