### ISSUE TITLE
Gold standard button not responsive

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#4564]
See video showing buggy behavior. 
In Chrome v65 on mac os high sierra

Initially reported by Chicago Wildlife Watch researcher 

https://drive.google.com/file/d/1YZnMwuIDqYaztxA8BAQgo4GrLYccPcuo/view?usp=sharing

This is lower priority, but perhaps an easy fix?

**Comment by eatyourgreens** [comment]
I think this checkbox relied on the classification change listener, which we've removed from the classifier. The classifier doesn't re-render, now, when the classification is changed.
