### ISSUE TITLE
Canvas viewer does not resize properly on mobile

### ISSUE THREAD

**Issue by tingard** [zooniverse/Panoptes-Front-End#4568]
## Expected behavior
On talk, canvas viewer shrinks to fit inside page

## Current behavior
Does not shrink (due to overwriting its size css for rendering purposes)

Can be seen here (on mobile)

https://www.zooniverse.org/projects/tingard/galaxy-builder/talk/1222/612520?page=1&scrollToLastComment=true

**Comment by chrislintott** [comment]
In the long run, probably resolved by building separate facility for complex projects on mobile.
