### ISSUE TITLE
Out-of-bounds marks can be submitted in a completed classification

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4579]
## Expected behavior
Drawing tasks that lie outside the subject image area should be automatically detected and deleted.

## Current behavior
Marks that are created by a mouseup/touchend event outside the subject image are deleted. However, if the mouseup/touchend event that creates the mark is inside the subject, the mark is not deleted, even if its final (x,y) coordinates lie outside the subject area.

## Steps to replicate
Draw a point and drag it quickly upwards to fling it outside the subject. Lift your finger (or lift the mouse button) while still inside the subject. It's possible for the subject to end up outside the image area, but the mark is not deleted and remains in the submitted classification.

## Additional information

- **Operating system:** n/a
- **Browser:** n/a

**Comment by eatyourgreens** [comment]
This was originally discovered on Space Warps but applies to any point drawing task. It's easy to trigger by accident when scrolling up and down on a phone screen. Once the new mark is placed outside the subject area, it cannot be deleted and must be submitted as a classification.

**Comment by mschwamb** [comment]
If the tool is an ellipse will this remove the mark if the center of the ellipse is out of bounds but other parts of it are on the subject image?  We found in P4 that if part of the marking was within the subject image, they were attempting to cover the fan/blotch as best as they could. If those marks were removed we'd be losing significant information.

**Comment by eatyourgreens** [comment]
@mschwamb the PFE code currently checks the position of any newly created marks and deletes them if they are outside the subject. The call to `deleteIfOutOfBounds` here happens when you finish creating a new mark:
https://github.com/zooniverse/Panoptes-Front-End/blob/470907d321d2e8ed596a3a9c15bff6e8adbd966c/app/classifier/drawing-tools/full-height-line.cjsx#L41

**Comment by mschwamb** [comment]
@eatyourgreens thanks

**Comment by eatyourgreens** [comment]
Related: #2323 #2125
