### ISSUE TITLE
Migrating over P4: Terrains from Demo to Preview site?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#458]
@chrislintott said that sometime soon that P4: Terrains could be migrated from the demo to preview site, and that we should stop making changes to the P4: Terrains project on the demo site in preparation. Is this still happening?Or do we need to rebuild it from scratch on the preview site?

Also my account and Michael Aye's on the preview site don't have access to the project builder, so I can't recreate it. Is it possible to get access again?

We'd like to be able to get back to making changes so we can try and finish the project in time for your timeline for launch. 

Any help or reply would be much appreciated. 

Thanks, 

~Meg

**Comment by camallen** [comment]
@mschwamb - i'm doing this today.

**Comment by mschwamb** [comment]
On 6/2/15 8:33 PM, Campbell Allen wrote:
>
> @mschwamb <https://github.com/mschwamb> - i'm doing this today.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/zooniverse/Panoptes-Front-End/issues/458#issuecomment-107938274>.
>
Thanks @camallen

**Comment by camallen** [comment]
@mschwamb - i ran out of time today. It's first thing on my list tomorrow.

**Comment by mschwamb** [comment]
Thanks @camallen for letting me know. Very much appreciated.  We had a team telecon this morning,so  I updated them on the status. Thanks very much for the replies.

**Comment by camallen** [comment]
@mschwamb your project is now migrated, you can access it via the lab link http://preview.zooniverse.org/panoptes/#/lab or via a listing of http://preview.zooniverse.org/panoptes/#/projects?approved=false&beta=false

Note: we didn't migrate any subject sets and data or collaborators, you'll need to set all this up again. Please reopen this issue if there are any problems.

**Comment by mschwamb** [comment]
Thanks @camallen
