### ISSUE TITLE
Switch to dark theme and the multiple choice options no longer get highlighted on hover 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4584]
<img width="1120" alt="screen shot 2018-05-01 at 11 36 06 pm" src="https://user-images.githubusercontent.com/753325/39516408-970d036a-4d98-11e8-8a24-09399920f45c.png">

On Firefox 59.0.2 when I switch to the dark theme the multiple choice buttons no longer get highlight on hover

<img width="1120" alt="screen shot 2018-05-01 at 11 36 06 pm" src="https://user-images.githubusercontent.com/753325/39516542-ebcb53ca-4d98-11e8-9888-4b11dc0d30c1.png">

<img width="1095" alt="screen shot 2018-05-01 at 11 40 22 pm" src="https://user-images.githubusercontent.com/753325/39516588-14c9fae2-4d99-11e8-9e38-2e72dd3afb5a.png">

Same choice hovered on. Wasn't clear I had selected anything in the dark/grey theme

**Comment by eatyourgreens** [comment]
I'm seeing the dark theme change to a noticeably lighter border on hover/focus. When I select an answer, that answer is highlighted in green. There's clear visual indication of which element is active both when I use a mouse and when I use the keyboard to answer the question. This is in Chrome on OSX.

**Comment by eatyourgreens** [comment]
Same results in Firefox using both a mouse and the keyboard to answer the question. The border changes to indicate which answer is currently active in the dark theme.

**Comment by mschwamb** [comment]
@eatyourgreens yes the border changes, but these seems odd to me that one version does this by color and the other by putting the box.. I would expect it the behavior would be the same just different colors

**Comment by marten** [comment]
@eatyourgreens The label tag has a background gradient in hover state, but only in the light theme. In the dark theme there is no background defined so it doesn't highlight via CSS, just gets the browser-supplied border around it.

**Comment by eatyourgreens** [comment]
There's a change in border colour on hover or focus in the code, and I'm seeing it on the site in both Firefox and Chrome. I haven't looked in Safari or Edge.
https://github.com/zooniverse/Panoptes-Front-End/blob/9db56cba2c6cd0cf54a12fa79ac9e539e9474eeb/app/classifier/tasks/components/TaskInputField/TaskInputField.jsx#L34-L46

**Comment by marten** [comment]
Yeah, but for light mode there's a gradient, https://github.com/zooniverse/Panoptes-Front-End/blob/9db56cba2c6cd0cf54a12fa79ac9e539e9474eeb/app/classifier/tasks/components/TaskInputField/TaskInputField.jsx#L37

For dark mode there is just a flat background : https://github.com/zooniverse/Panoptes-Front-End/blob/9db56cba2c6cd0cf54a12fa79ac9e539e9474eeb/app/classifier/tasks/components/TaskInputField/TaskInputField.jsx#L36
But that background is the same one as used in the non-hover state: https://github.com/zooniverse/Panoptes-Front-End/blob/9db56cba2c6cd0cf54a12fa79ac9e539e9474eeb/app/classifier/tasks/components/TaskInputField/TaskInputField.jsx#L15

Which means that in light mode you see a background color change on hover/focus, but in dark mode you don't have that. Do we have something similar to the teal gradient for dark mode?

**Comment by eatyourgreens** [comment]
I know, but this is how @beckyrother has designed the dark theme and I personally think the design works.

**Comment by mschwamb** [comment]
I would say as someone trying to figure out how stuff works. I find it hard that the color theme has different behaviors. It works, but I definitely found that confusing. Maybe feedback for @beckyrother, maybe not.

**Comment by mschwamb** [comment]
As someone on the outside if you launch a feature live on panoptes projects it should be finished not testing if it is functional. Maybe you mean these are small added things at the end when the bulk design is done, but I'm still confused why not roll out the rest of the interface change in one go and be beta testing while it is in progress.

**Comment by eatyourgreens** [comment]
Personally, I’ve been preferring the dark theme because the gradient background is highly distracting and gets in my way on the light theme. It’s a matter of personal taste really.

**Comment by eatyourgreens** [comment]
Panoptes Front-End has always been a work in progress. I don’t think there’s been any point at which we could say it’s done. Development on PFE has been more a series of continuous, incremental changes since it first launched.
