### ISSUE TITLE
Tutorial image now are overflowing the tutorial box

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4585]
<img width="1124" alt="screen shot 2018-05-01 at 11 42 33 pm" src="https://user-images.githubusercontent.com/753325/39516696-6b211290-4d99-11e8-9db6-5f60f1b19688.png">

This didn't used to happen before whatever design change was recently implemented. I don't know how I would be be able to resize or fix it. It's happening on all my panoptes projects with tutorials

**Comment by eatyourgreens** [comment]
This might be a side-effect of #4506, which fixed slow download times caused by oversized tutorial images. From the screenshot, it looks like it's triggered on smallish screens.

@mschwamb is this also Firefox, or does it happen in Chrome too?

**Comment by eatyourgreens** [comment]
You're right, there's a max-width of 400px on the tutorial slide, but the image can be larger.

**Comment by mschwamb** [comment]
Happening in Chrome too.
