### ISSUE TITLE
When a task is not a question, should the title still say question?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4586]
There's different terminology going on in the classification interface now. The help button text has always been 'Do you need help with this task?' Now the tab between the task and the tutorial says 'Question'. That makes sense if you're asking a question in a decision tree but not in a drawing task. See below. 

<img width="1078" alt="screen shot 2018-05-01 at 11 56 48 pm" src="https://user-images.githubusercontent.com/753325/39517388-67e8b07c-4d9b-11e8-8863-4b815414f8b3.png">

instead of 'question' should this be 'task'. It seems confusing to me to use different words for the same thing in the classification interface.

**Comment by beckyrother** [comment]
Good point Meg. Should it just say "Classify" to be consistent with the buttons from the project home page @srallen @mschwamb ?

**Comment by mschwamb** [comment]
Maybe, it would be better than Question I think. But further down in most interfaces is the  'do you need help with this task?' so maybe Task is better/more consistent messaging. If you go with 'classify' then you have a verb tab and a noun tab; I don't know if that's odd or not.

**Comment by beckyrother** [comment]
Task works for me. @srallen would you mind making this change?
