### ISSUE TITLE
'Going back will clear your work for the current task' oddly formatted  in the classification interface in Firefox

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4587]
When I hover in firefox I get this: 

<img width="1094" alt="screen shot 2018-05-02 at 12 08 13 am" src="https://user-images.githubusercontent.com/753325/39517942-1ba2566c-4d9d-11e8-9d66-9e4f743acdb5.png">

It looks fine in Chrome 

<img width="1280" alt="screen shot 2018-05-02 at 12 10 18 am" src="https://user-images.githubusercontent.com/753325/39518040-628f78ca-4d9d-11e8-8d52-ffad224dffa1.png">

**Comment by eatyourgreens** [comment]
I think this is fixed in #4581.

**Comment by srallen** [comment]
Yes, it's fixed in that PR. I'll tag this as being closed when it merges.
