### ISSUE TITLE
Should the 'question' label be in the classification interface top if the project doesn't have a tutorial?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4589]
<img width="1025" alt="screen shot 2018-05-02 at 12 14 18 am" src="https://user-images.githubusercontent.com/753325/39518454-b4f08356-4d9e-11e8-9de2-70e131fa106b.png">

For Planet Four: Terrains there is no tutorial. It launched before there was a tutorial. I think it looks a bit odd to have question at the top and then the actual prompt for the user. If there is no tutorial perhaps we could save the vertical space and not include 'Question' at the top?

**Comment by srallen** [comment]
It's been noted to disable the tutorial button rather than hide it if there isn't a tutorial in #4570. Whether or not to remove the tab buttons is a design question for @beckyrother

**Comment by marten** [comment]
I just had a look and there's only 5 live projects without tutorials. All of them seem to be from before we added the tutorial as a feature. @mschwamb would it be an idea to move some of the "Need some help with this task" content over to a tutorial for your project?

**Comment by mschwamb** [comment]
I don't think all future projects will need tutorials, definitely not all Ouroboros projects did if I recall correctly. Given tutorials are optional, I think it would be better to have a decision on what the look should be for projects without a tutorial should look like and whether to have the tab motif.  I figured I'd bring it up since it might not be on the radar given most projects too. To me it looks odd since there isn't another tab, but that's my opinion.

**Comment by srallen** [comment]
The tutorial tab won't be hidden in a future update.

**Comment by mschwamb** [comment]
@srallen so  do you mean tutorials are mandatory then?  or just the tab/button will appear differently somewhere else

**Comment by srallen** [comment]
No, the button will just be disabled if a tutorial isn't available instead of hidden.

**Comment by beckyrother** [comment]
Tutorials are not mandatory, but the vast majority of projects take advantage of the ability to use one. Marten mentioned above that only 5 projects don't have a tutorial, so this does not apply to most projects on Zooniverse. Unfortunately we can't design for every use case, so we go with the majority.

**Comment by vrooje** [comment]
I think we should invert this question -- not tailoring our design to what most projects do, but using the design to motivate project owners to use features we think are important. Having the tutorial tab always present but grayed-out if there just isn't one makes a subtle judgment that something is missing if there isn't a tutorial. Personally I think that's a message we *should* be sending.

**Comment by srallen** [comment]
Closed by #4599
