### ISSUE TITLE
Can't click on field guide in Firefox brings up scroll bar 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4592]
Seems to not happen in Chrome. In Firefox if I try and click on the Field Guide it brings up the scroll bar

<img width="1051" alt="screen shot 2018-05-02 at 12 41 30 am" src="https://user-images.githubusercontent.com/753325/39519329-06525140-4da2-11e8-8e34-5ac08faa45fc.png">

**Comment by eatyourgreens** [comment]
Apparently the field guide has always had this problem with the scrollbars in Firefox, because it's up against the edge of the window. I'll look to see if anyone else has reported it, and merge the issues if so.

**Comment by srallen** [comment]
I think Karla is slightly smaller than OpenSans and that did get set as the default so that it was consistently used across project pages with the update. The scroll bar has always been an issue in OS X and Firefox, Chrome, and Safari, but the button itself might have been just so slightly larger previously.

**Comment by mschwamb** [comment]
would it be possible to make the site guide box a tad bigger?

**Comment by srallen** [comment]
@mschwamb Will you let me know if it's easier to toggle the field guide in this staged branch? Thanks!
https://fix-4592.pfe-preview.zooniverse.org/projects?env=production

**Comment by mschwamb** [comment]
Sorry for the delay, dealing with earthquakes caused by the Kilauea eruption . It works better. If it was a smidge better it would work a bit better, I have to be all the way on the left edge for my mouse to click it, but it is better than before.

**Comment by beckyrother** [comment]
@srallen while we're taking a look at this, can we add 0.5em more padding to the top and bottom, remove the border-radius, and add a `solid thin #ebebeb` border around the box?

![space_warps_-_hsc_ _classify_ _zooniverse](https://user-images.githubusercontent.com/1392130/39769895-1912f9fe-52b3-11e8-9bfb-acc48ce9c107.png)
