### ISSUE TITLE
Field Guide is Showing on Talk, Collections, and About Pages

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4593]
I don't believe it was this way before the interface design changes so this is why I'm putting it in as a github ticket in case it is a bug. Feel free to close if this is as intended. 

The site guides are showing on Talk and the About pages and all other project pages but the landing page. It seems confusing to have the site guide showing with the about page or Talk. At least I didn't know what it was there. 

<img width="1046" alt="screen shot 2018-05-02 at 12 51 20 am" src="https://user-images.githubusercontent.com/753325/39519568-fd80a782-4da2-11e8-9c7f-ad4b3c181820.png">

<img width="1048" alt="screen shot 2018-05-02 at 12 51 14 am" src="https://user-images.githubusercontent.com/753325/39519586-17eed0ee-4da3-11e8-96fe-2faef123dca3.png">

<img width="1052" alt="screen shot 2018-05-02 at 12 48 21 am" src="https://user-images.githubusercontent.com/753325/39519600-2268743a-4da3-11e8-83b0-2dbddea08c78.png">

**Comment by eatyourgreens** [comment]
Hi Meg, the field guide has been shown on every project page (except the home page) sonce it was first added to PFE. We did once change it so that it was only on the Classify page. Volunteers asked us to restore it immediately, because they refer to it from Talk and Collections.
