### ISSUE TITLE
Survey task list is out of order 

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#4596]
## Expected behavior
Should be in alphabetical order

## Current behavior
From Colorado Corridors:
![0](https://user-images.githubusercontent.com/1392130/39583801-88828f58-4eb6-11e8-9d6f-586c7592bf87.jpg)

**Comment by eatyourgreens** [comment]
Survey task choice order is set by the project owners when they upload the choices list. Is this the order they set when they created the task?

**Comment by srallen** [comment]
The `choicesOrder` for this task:
```
0: "BADGER"
1: "BEAR"
2: "BIRD"
3: "BOBCAT"
4: "CHIPMUNKSQUIRREL"
5: "COYOTE"
6: "DEER"
7: "DOGDOMESTIC"
8: "ELK"
9: "FOXGRAY"
10: "FOXRED"
11: "HUMAN"
12: "LYNX"
13: "MARMOT"
14: "MARTEN"
15: "MOOSE"
16: "MOUNTAINLION"
17: "OPOSSUM"
18: "PORCUPINE"
19: "RABBITHARE"
20: "RACCOON"
21: "RODENT"
22: "SKUNKSPOTTED"
23: "SKUNKSTRIPED"
24: "WEASEL"
25: "NOTHINGHERE"
```

**Comment by beckyrother** [comment]
It's apparently a new thing that's happening after the font change. Here's the message I got from the researcher:

> One of our volunteers recently notified us that the alphabetization of our species list is sometimes showing up a little wonky (see attached screen shot). Do you know if there is there a setting we can change to get the species back in alphabetical order? If it helps, our project name is Colorado Corridors Project. Thanks in advance for any advice you can give!

**Comment by srallen** [comment]
Since the survey task redesign is coming up next, let's put off a robust fix.
