### ISSUE TITLE
Where are user groups live on the front end?

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#46]
Where will user groups be on the front end? Will I see group projects in "my" account? How will user groups work?

**Comment by mkosmala** [comment]
As a related thing, we also need to be able to share projects. Have you thought about how that will fit?
(Sharing either directly or via a user group would be necessary for me and @rcheng3 to work together on our project. The sooner the better.)

**Comment by srallen** [comment]
Related to #3121, #3122, and #3123.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
