### ISSUE TITLE
New PW: Some marks disappear when that part of image is panned away from the screen

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#4607]
## Expected behavior
When I mark a group of penguins and pan away to mark another group, I expect to find the placed marks exactly where I left them. Also, I expect the mark count to stay on the same number and not start decreasing while panning.

## Current behavior
After marking a group of penguins while panning away to mark another group, I see the mark count decreasing and after panning back to the first group I've marked already, I find out some marks are gone. Especially when zoomed in, especially when the marks are near an image edge.

Screenshot made after panning the image away with 30 adult marks placed all over the image - you can see the count is now saying 19 adults only:
![ysh_2018-05-05_13-44-28](https://user-images.githubusercontent.com/7211888/39662962-c1702158-506a-11e8-9293-d546f8bdd29d.png)

## Steps to replicate
The best way to test is to just go along the left image edge and place marks in a row along the edge randomly. Then to pan away to the right side without zooming and watching the total mark count. If nothing happens, then zooming in usually makes them do so. And sometimes even all marks disappear.

## Additional information
Quite annoying to figure out that after you had marked several hundred of distant penguins and after panning back and finding some of them unmarked you marked them all again... and again... and then to find the total mark count showing much less than before. 
Also, I haven't found a way to mark penguins standing along the edge, when zoomed in.

- **Operating system:**
Linux x86_64
- **Browser:**
Chromium 63

**Comment by yshish** [comment]
The same problem seems to be happening on SeabirdWatch: 
https://www.zooniverse.org/projects/penguintom79/seabirdwatch/talk/1162/620781?comment=1037116&page=1

**Comment by yshish** [comment]
@camallen @eatyourgreens Not sure who to call, have you noticed this one? I find it pretty serious...

**Comment by srallen** [comment]
@yshish It's being looked at this morning (US time). It's a bank holiday in the UK today.

**Comment by yshish** [comment]
@srallen Great. Thank you, I didn't know about the UK holiday.
