### ISSUE TITLE
Limit the amount of subjects a user can upload in a batch?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#461]
Linked to https://github.com/zooniverse/Panoptes/issues/672 

Just ran some tests with @vrooje and the `subject_set#update_links` end point took ~7s for a 450 subject batch and ~15s for an 900 batch. This will lock up our API nodes pretty quickly as more people start building project and uploading subjects. @edpaget thoughts on Puma under MRI on this?

I think we should we add a hard limit to the amount of subjects the front-end allows to be uploaded in any single attempt, I think 500 is reasonable at the moment and we can scale it up/down if needed.

Thoughts?

**Comment by chrissnyder** [comment]
Is this were done sequentially rather than in batch, would that be better/worse/no different?

**Comment by camallen** [comment]
Sequential batches with a slight back-off would be ok. Batching just limits the number of recordst to create via the `update_links` end_point so it'll be a faster request/response cycle.

**Comment by chrissnyder** [comment]
Was this solved with https://github.com/zooniverse/Panoptes/issues/672? @camallen can you confirm and close if so?

**Comment by camallen** [comment]
I load tested the update_links with 500 subjects and reduce the time to ~200ms on staging. I haven't finished testing to figure out if this is a linear function with more subjects but i suspect there are components that will be linear, the links update should be pretty quick. I really need to test if with 10K to see how well it works, I plan on doing this with the P4 Terrains data. 

For reference, there is another issue at play which is session timeouts for large data uploads. We ran into this for stargazing and reducing batch sizes via this https://github.com/zooniverse/panoptes-subject-uploader which ensured the session was valid for every batch. 

I'm going to close this issue and will re-open if needed.
