### ISSUE TITLE
Test This Workflow in Project Lab Not Rendering: Workflow 6810

### ISSUE THREAD

**Issue by scottcoughlin2014** [zooniverse/Panoptes-Front-End#4612]
## Expected behavior
When I click `Test this workflow` button o project lab normally it looks the workflow no problem

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
now when I click `test this workflow` for `Workflow=6810` It gets caught on 

`Loading classifier...` on the screen

## Steps to replicate
If you go to https://www.zooniverse.org/lab/6040/workflows/6810 you should be able to click `test this workflow`, I would be happy to add someone as a collaborator if necessary.

## Additional information
```
Error: getAllLinked: resource and link not specified
main-b0cd84f1305ca19ed440.js:1:31085
TypeError: r is undefined[Learn More]
main-b0cd84f1305ca19ed440.js:1:510704
TypeError: r is undefined[Learn More]
main-b0cd84f1305ca19ed440.js:1:510704
```

- **Operating system:**
OS X High Sierra

- **Browser:**

Mozilla Firefox Quantum 59.0.2

**Comment by mcbouslog** [comment]
Not entirely sure this will fix the issue, but if you set the `workflow.first_task` attribute to `"T0"` does it help?

**Comment by scottcoughlin2014** [comment]
Dang! That did it! @mcbouslog  thanks a lot!

**Comment by scottcoughlin2014** [comment]
I guess I will close!

**Comment by mcbouslog** [comment]
Oh sweet, no prob!

**Comment by srallen** [comment]
The classifier should be able to handle this more gracefully. Thanks @mcbouslog
