### ISSUE TITLE
project looks like it has a tutorial when it doesn't

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4627]
P4: Terrains doesn't have a tutorial and it looks like it does now. When you got to classify, there is a tutorial tab. It has a slightly greyer text then projects that have tutorials. Most people aren't participating in lots of Zooniverse projects so I don't think they'll notice this subtle difference. I didn't.  I think they'll try and click it. The only way you know the tutorial tab doesn't work is the symbol that appears when hovering over. 

<img width="1105" alt="screen shot 2018-05-17 at 6 38 16 am" src="https://user-images.githubusercontent.com/753325/40193630-8ee47ed6-59a3-11e8-95ce-fdb2c64d089e.png">

To me it now looks like P4: Terrains  has a broken feature since there's a button that looks like you can click on it, but it doesn't work. Even if it is a small number of projects without tutorials, it shouldn't look like my project has a broken feature or a missing feature.  There are also past Zooniverse projects without tutorials like sunspotter.  In our case, tutorials didn't exist when panoptes launched, but given the results, we don't need one. 

It seems like it would be very easy to not have the tutorial tab appear if the project doesn't have a tutorial. The field guide tab doesn't appear greyed out if a project doesn't have a field guide. It should be the same as these are both optional features.

**Comment by beckyrother** [comment]
As we talked about in #4589, the majority of our projects have tutorials so we won't be addressing this. @vrooje put it really well – these tutorials are good resources for volunteers, so we want to encourage our project owners and researchers to take advantage of these tools.

**Comment by vrooje** [comment]
This is a perfect example of what I was referring to in #4589. I think the user seeing the greyed-out button and thinking there's supposed to be a tutorial is the interpretation we *want*, because it motivates project owners to use tutorials (which we know are generally helpful). If this were a more typical case and you were a less experienced project owner I'd suggest that even just using the tutorial to give a 2-sentence project motivation and point to Talk and the task-specific help material would be beneficial. As it is I think your answer to the user was fine.

**Comment by mschwamb** [comment]
There's been no notification to project owners, so I'm confused how the policy on tutorials has changed. Perhaps @chrislintott can clarify?

**Comment by vrooje** [comment]
I'd say "the policy hasn't changed", but that would imply there is one. I'm not aware of any rules, just recommendations. Tutorials aren't required, but they're usually a good idea.

**Comment by srallen** [comment]
The redesign work for the tutorials and field guides aren't done yet. The field guide button and UI will change too.

**Comment by beckyrother** [comment]
Our policy on taking advantage of the tools we offer to research teams and volunteers has not changed. This is a case in which we need to consider our very limited design and development resources and make a judgement call whether the needs of a very small minority take precedent over the needs of the rest of the projects on the site. 

With regards to changing the behavior of the tutorial, the tutorial will always be a modal when the user first arrives at the project. Feedback from a survey I sent last year revealed that volunteers weren't able to easily find the help they needed on a project, so making this tutorial button more prominent seeks to solve that issue.

**Comment by beckyrother** [comment]
To follow up on what Sarah said, we'll make sure project owners have ample time to make sure field guide content fits within new field guide design.

**Comment by beckyrother** [comment]
@mschwamb Some project owners use the tutorial to provide a basic introduction to the project and lay out some of the project's goals in one or two slides, just like a "welcome to [project name], thanks for helping!" kind of thing. That might be a quick way to solve this.
