### ISSUE TITLE
Project builder: subject viewer doesn't always show images

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#463]
I've seen this a few times now after I've loaded new subjects into a subject set.

When the subject upload is finished and I go to view an individual subject from the subject set page, it doesn't quite load correctly. 

The first subject I try to view will either (if 1 image per subject) load the image and then immediately replace/overlay it with the green-blue stripey placeholder image, *or* (2 images per subject) it will successfully load one image, but the second image just shows the placeholder. (I've only loaded subjects with 1 or 2 images thus far.) Once the placeholder image comes up it doesn't go away once I switch back to the image that had successfully loaded. So I have no idea if e.g. the play/pause buttons work.

Any subsequent subject I try to review just hangs on the image load with the little loading animation. When I refresh the page this starts over again.

I can view the metadata just fine at all times.

I noticed this originally with the cat project (30 subjects) but as it was just after we'd moved to preview I figured I'd wait to see if it went away. Alas.

**Comment by mschwamb** [comment]
Yep - I  just reproduced the exact same issue. The fix that seemed to get the backend to recognize there were new subjects and read it successfully was to log out then log back in and then hit refresh in the browser in that order.

**Comment by brian-c** [comment]
I can reproduce this. On it now.
