### ISSUE TITLE
occassionally abc stargazing live classification interface switches from done and talk to having a classification summary

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4634]
The behavior of the project is to have a 'Done & talk' and 'Done' button, but I'm noticing after a certain number of clicks, after hitting done, the classification summary pops up . I'm using the latest version of firefox on the latest mac os. This has happened twice.

<img width="1133" alt="screen shot 2018-05-22 at 7 04 42 am" src="https://user-images.githubusercontent.com/753325/40367612-b4e20240-5d8e-11e8-9da7-41b1a07d8ae7.png">

but the interface should never bring me to that page because it is setup to skip the classification summary

<img width="1139" alt="screen shot 2018-05-22 at 7 07 28 am" src="https://user-images.githubusercontent.com/753325/40367678-d638ea4e-5d8e-11e8-8533-0acaffc51359.png">

**Comment by eatyourgreens** [comment]
The summary is shown in place of the task when `classification.completed` is true.
https://github.com/zooniverse/Panoptes-Front-End/blob/bb743f46d3aadb264b231e94936ba17a361e136e/app/classifier/classifier.jsx#L370-L392

I guess there's a case where that happens (the classification is finished) but the task area renders before the new subject has loaded.
