### ISSUE TITLE
"ERROR: Cannot create container" Invalid Volume Specification

### ISSUE THREAD

**Issue by tlalka** [zooniverse/Panoptes-Front-End#4636]
I followed the installation instructions for Panoptes-Front-End with Docker,  but running either "docker-compose run --service-ports dev npm" or "docker-compose run dev npm run stag" results in the error "ERROR: Cannot create container for service dev: invalid volume specification: '/host_mnt/src:rw'"

I could run "docker-compose run **-v some_volume** --service-ports dev npm", but I don't know what volume would be appropriate for "some_volume"

Here is the full log including the build step:
PS C:\Users\tlalka\Documents\Panoptes-Front-End> docker-compose build
WARNING: The AWS_REGION variable is not set. Defaulting to a blank string.
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The AWS_SESSION_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECURITY_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The PWD variable is not set. Defaulting to a blank string.
Building dev
Step 1/5 : FROM zooniverse/panoptes-front-end:deps
 ---> 08be7d0a6f71
Step 2/5 : ADD package.json /src/
 ---> Using cache
 ---> 46a0406bcac1
Step 3/5 : ADD package-lock.json /src/
 ---> Using cache
 ---> 064a90a651bb
Step 4/5 : RUN npm install --unsafe-perm
 ---> Using cache
 ---> b64f2f22b2df
Step 5/5 : ADD . /src/
 ---> aee0b79e7355
Successfully built aee0b79e7355
Successfully tagged panoptes-front-end_dev:latest
PS C:\Users\username\Documents\Panoptes-Front-End> docker-compose run --service-ports dev npm sta
rt
WARNING: The AWS_REGION variable is not set. Defaulting to a blank string.
WARNING: The AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECRET_ACCESS_KEY variable is not set. Defaulting to a blank string.
WARNING: The AWS_SESSION_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The AWS_SECURITY_TOKEN variable is not set. Defaulting to a blank string.
WARNING: The PWD variable is not set. Defaulting to a blank string.
ERROR: Cannot create container for service dev: invalid volume specification: '/host_mnt/src:rw'

I am on windows, and none of this seems to work for windows, so I may just start over on a mac

**Comment by astopy** [comment]
I don't have a Windows machine I can test this on, but I think you might need to set the `COMPOSE_CONVERT_WINDOWS_PATHS` environment variable before you run docker-compose:

```
set COMPOSE_CONVERT_WINDOWS_PATHS=1
```

**Comment by tlalka** [comment]
I tried the following commands in a fresh shell, but unfortunately it didn't help. The error message is still the same. 

set COMPOSE_CONVERT_WINDOWS_PATHS=1
docker-compose build
docker-compose run --service-ports dev npm start

**Comment by astopy** [comment]
Could you let me know which versions of docker and docker-compose you have? (By running `docker version` and `docker-compose version`)

**Comment by tlalka** [comment]
Docker is 18.03.1 and Compose is 1.21.1

These are the same versions I'm using on Mac, and it works there

**Comment by srallen** [comment]
What version of Windows are you running? The docs say it only works on Windows 10 with Hyper-V enabled: https://docs.docker.com/docker-for-windows/install/

**Comment by tlalka** [comment]
Windows 10 and I enabled virtualization/Hyper-V. I've got it working on the mac in my office, I'm just wondering if anyone has got the current build working in Windows. If it's just me having this issue. I may try in on a different Windows computer, if I can get a hold of one, to confirm that is is something specific to this computer.

**Comment by srallen** [comment]
I have access to Windows 10 machine with Docker installed, but I'm not sure when I can get to testing this out. I haven't tried this docker build before on it, but I have gotten other unrelated docker builds working.
