### ISSUE TITLE
Accessing the Spiral Arm tool

### ISSUE THREAD

**Issue by tlalka** [zooniverse/Panoptes-Front-End#4641]
I'm working on a project where we map the arms of spiral galaxies to determine the size of the SMBH in their center. The project is called "Spiral Graph". 

The issue is that the polygon tool auto-completes its shapes, and the bezier tool does not allow you to make concave shapes, lines that overlap, and also tries to autocomplete the shape. 

I was wondering how we could get access to the spiral arm tool that Galaxy Builder uses. It also does not allow convex shapes, but I think it is caused by the same problem the polygon tool had, which was fixed in #4076. So we could probably fix that pretty quickly. 

Thanks!

**Comment by eatyourgreens** [comment]
Hi there. I've enabled a couple of experimental features on the Spiral Graph project: the freehand line drawing tools, and the ability to persist annotations so that drawings aren't lost when the back button is pressed.

**Comment by tlalka** [comment]
The freehand segment tool seems to be broken on the full site (it works fine on the freehand-tools branch). It gives your cursor a little stop sign after you let go of the mouse after your first click. This means you can't draw any segments or continue the line. 

Sorry for the phone picture, but the icon doesn't appear in screen-shots.

![20180529_111336](https://user-images.githubusercontent.com/19802621/40668094-a3f5c072-6331-11e8-9880-e332e0c94df2.jpg)

**Comment by srallen** [comment]
@tlalka it's best to let us know about a new bug in a new issue ticket and fill out the information in the template there so we can keep better track of it. Thanks!

**Comment by tlalka** [comment]
I'll go ahead and do that right now
