### ISSUE TITLE
Back button warning overlaps mini course link

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4647]
The back button warning overlaps the mini-course link, on those projects that have a mini-course and more than one task.
![Screenshot showing the back button warning text partially overlaid on the mini-course link text.](https://user-images.githubusercontent.com/59547/40485257-f30bd514-5f55-11e8-9524-a62612ef7a17.png)

## Steps to replicate
Hover, or focus, the back button on a project that has a mini-course.

**Comment by beckyrother** [comment]
I agree, and it would be great if on hover it didn't push other content down; it can be disconcerting if the warning is triggered and very quickly disappears again. @srallen that's a great idea, maybe it can use some more design before implementing. I'll post an invision link asap
