### ISSUE TITLE
Workflow unexpectedly changes when classifying with two tabs on different workflows

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#4648]
## Expected behavior
The loaded workflow on each tab stays the same as the one originally selected.

## Current behavior
The workflow from one loaded tab can leak into the other tab and rewire the interface.

## Steps to replicate
I've been using CameraCatalogue workflows for testing, https://www.zooniverse.org/projects/panthera-research/camera-catalogue
  + 1st South Africa (2647)
  + 2nd Empty or Not(4403)
 
1. Open up the "empty or not" workflow in 1 tab
0. Open up the SA workflow in other tab
0. Classify 5 times on the "empty or not" workflow and watch the UI change after submitting the 5th.

It should now have reloaded the SA workflow from the in place of the "empty or not" workflow.

## Additional information
Initially reported by https://www.zooniverse.org/users/ekaylor

- **Operating system:**
I believe all
- **Browser:**
I believe all

**Comment by eatyourgreens** [comment]
We store the current workflow with the user, so this is expected behaviour.

**Comment by eatyourgreens** [comment]
Going to Talk and back to Classify (in the project nav) doesn't change the workflow. To change the workflow, you have to leave the project and return, so that project preferences are reloaded.

**Comment by camallen** [comment]
I seem to be able to do this after classifying exactly 5 images on the 2nd workflow.

**Comment by camallen** [comment]
I've updated instructions for reproducing in the original post.

**Comment by srallen** [comment]
The changes made in #4451 to fix a bug related to workflow promotion may be causing the unexpected workflow change. This should be updated to only happen for projects with workflow promotion enabled.

**Comment by eatyourgreens** [comment]
I was going to ask on #4635 about removing the preferences change listener, and associated methods, from the top level project component, because they didn't seem to be doing anything.
