### ISSUE TITLE
"freehand segment line" tool broken in master branch

### ISSUE THREAD

**Issue by tlalka** [zooniverse/Panoptes-Front-End#4656]
My project uses the "freehand segment line" tool, which we have enabled on the website. It's supposed to make a freehand line when you hold the mouse down, and make a segmented line when you click point by point. This behavior works on the "freehand-tools" branch and build found at "https://freehand-tools.pfe-preview.zooniverse.org/"

Currently, the tool stops working after you release your first click. It changed your mouse cursor into a little stop sign, and will not let you put down a segment point or start a new free-hand segment. It will let you click on the end of your own segment and close the line. 

Sorry for the phone picture, but the mouse cursor doesn't show up in a screen shot.
![20180529_111336](https://user-images.githubusercontent.com/19802621/40668954-c8f79114-6333-11e8-9d46-e71966e0ce63.jpg)

![20180529_113728](https://user-images.githubusercontent.com/19802621/40669378-d10ccd28-6334-11e8-8c97-29ff4eeb4e63.jpg)

You can re-create this error by attempting to click twice while using the "freehand segment line" tool

This error occurs both on a Windows using Chrome, and a Mac using Safari

**Comment by tlalka** [comment]
I went back and checked, and you're right!
If you set a maximum, even if the maximum is 0, this error occurs on both the main and free-line branch. Minimums seem to be fine though

**Comment by eatyourgreens** [comment]
I think the bug is in the render method for the `MarkingInitialiser` component. `canMakeMarks` is evaluated on each render so it can change from true to false while you're in the middle of drawing a mark. https://github.com/zooniverse/Panoptes-Front-End/blob/c81db8a6b6d881826339dad57a8a883448bb3236/app/classifier/tasks/drawing/marking-initializer.cjsx#L22-L29

**Comment by eatyourgreens** [comment]
This is the same bug as the one described in #4674.
