### ISSUE TITLE
Tutorial width doesn't match content

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4659]
## Expected behavior
Tutorial widths should automatically adjust to wrap content

## Current behavior
Tutorials always render at 400px wide, even when the content is narrower. Hidden tutorial slides are partially revealed to the side of the tutorial popup.
![The Galaxy Zoo tutorial, showing other sides just visible on the right.](https://user-images.githubusercontent.com/59547/40715445-7d6caa52-63fd-11e8-96d0-3dcfba29b98e.png)

## Steps to replicate
Open the tutorial on a project with no images on the first tutorial slide, such as Galaxy Zoo.

Further information available in #4652.

**Comment by denslowm** [comment]
One possible issue of note. We (Notes from Nature) have some URL links in our tutorials that aren't getting wrapped. 
Are they supposed to? I am open to formatting them via Markdown as well, but I'm not sure if that's possible.
Here is an example: 
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=6014&_ga=2.184423526.1576714224.1528666194-301989501.1485808297
See the last page of the Tutorial there.

**Comment by srallen** [comment]
@denslowm that'll be a separate styling issue of the anchor tag within the markdown. Could you open a new issue for it?

**Comment by denslowm** [comment]
Done. Thanks.
