### ISSUE TITLE
Drawing subtask no longer receives focus when it opens

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4666]
## Expected behavior
Drawing subtasks should receive focus when they open, and retain focus until the popup closes.

## Current behavior
Tab navigation is broken when a drawing subtask opens. I can't continue classifying from the keyboard until I use a mouse to focus the subtask popup. After the subtask dialog opens, focus remains with the drawing tool that opened it.

## Steps to replicate
Open up the rating subtask for the catface drawing task in I Fancy Cats and try to choose a rating using only the keyboard.

I think this might have been broken by #4610 or by the upgrade to React 16.

**Comment by srallen** [comment]
I can take a look at this now that I finally have tests working again. I had been planning on writing tests and adding the light and dark themes to this.

**Comment by eatyourgreens** [comment]
I'm not sure, but it might have been broken by React 16. I think autofocus is working for the task component, but the drawing tool's focus method is being run again and stealing focus from the dialog.

The solution is probably to remove tabindex/focusable from the drawing tool while the details form is open.

**Comment by eatyourgreens** [comment]
Tabbing through the drawing subtask modal, when it has focus, is also broken. If I tab into a set of radio buttons, the first button is focussed regardless of which button is actually selected.
