### ISSUE TITLE
Drawing feedback sometimes shows even though no mark was drawn

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4668]
## Expected behavior
Space Warps drawing feedback should only show after you've made a mark on the subject.

## Current behavior
You can sometimes get the feedback message for a mark without placing a mark.

From an email to contact@zoo:
>Twice over the past 2-3 days, I click “Done” after reviewing the 4 images and I get a pop up saying that what I clicked on was not a gravitational lens. The only thing I clicked on was the Done button.

## Steps to replicate
I'm not entirely sure how to replicate this because I don't know what the conditions are that trigger it.

**Comment by eatyourgreens** [comment]
This might be related to #4634, with the classifier getting into an unexpected state at the end of a classification, so that feedback is not reset.

**Comment by aprajita** [comment]
@eatyourgreens not sure if you see this as the issue is closed but ElisabethB reported she got one of these mismatched messages for 21094190. this is a training image (dud) from subject set 20749. Els didn't mark it but got a fail message. We checked the feedback rule it says that it follows '2' which is the dud rule and where the success message is not set in the manifest so should revert to the default success message for no click ("Good call: there are no lensed features in this field").

**Comment by aprajita** [comment]
apologies - just the one Adam posted on the slack channel that i thought was from this week, but just realised this was May 29th. So I guess this is fixed as you mentioned. I have asked people on talk to let me know if this has happened since #4670 was implemented. sorry for the confusion.

**Comment by eatyourgreens** [comment]
No worries. I'm not 100% sure that #4670 fixed it, because I'm not completely sure what's causing it in the first place.

**Comment by aprajita** [comment]
:-) will post on #4670 if i get any more reports on talk...

**Comment by aprajita** [comment]
just tried this myself and got this after ~40 images when i placed no marker...

![image](https://user-images.githubusercontent.com/1917970/41407703-24179c6a-6fc8-11e8-9e3a-7e5d1ae26449.png)

https://www.zooniverse.org/projects/aprajita/space-warps-hsc/talk/subjects/21101215

this is another Dud training images, perhaps it's something to do with the dud feedback strategy although i can't see anything obviously wrong. If i use the dud feedback strategy then no mark should trigger a success and a mark a failure message - right?

![image](https://user-images.githubusercontent.com/1917970/41407838-8ffff274-6fc8-11e8-858c-b2d96cc6a663.png)

**Comment by eatyourgreens** [comment]
I'm not really sure how feedback works but I've assigned this to @rogerhutchings.

**Comment by eatyourgreens** [comment]
@aprajita when this happened to you for subject 21101215, was the classification submitted for the correct subject? If feedback was shown for the wrong subject, I'm wondering if the classification was wrong too.

**Comment by aprajita** [comment]
@eatyourgreens not sure but requested a classification export this morning. Once I get it i can check (if this is included in it otherwise will have to wait until tomorrow). thanks

**Comment by eatyourgreens** [comment]
@rogerhutchings I _think_ there might be a bug where `updateFeedback` isn't being called, or is called at the wrong time, if the user takes no action to update the default annotation. If I'm right, that would result in the feedback state being set for a different annotation than the one that's submitted with the classification.

**Comment by rogerhutchings** [comment]
That sounds about right - what I think is happening is that [this line](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/classifier.jsx#L203) is happening before the annotations object is reset, as:

1. The issue is being reported on subject load, and
2. This is the only place where `updateFeedback()` is called without being a callback to `setState`.

It's not immediately obvious when the annotations get reset on subject load, but it shouldn't take long to find out.

**Comment by eatyourgreens** [comment]
I've started adding tests for feedback in #4699. At the moment `loadSubject` is stubbed out there, so it only checks that feedback updates when the annotations array is updated.

**Comment by eatyourgreens** [comment]
Looking through the tests, annotations get reset when the new classification loads. The first task should call `updateAnnotations` after it mounts and creates the first annotation.

**Comment by eatyourgreens** [comment]
@rogerhutchings looking at the code, should `updateFeedback` be called with a task key, or a task annotation, as an argument? It looks like it only updates feedback for a single task.

**Comment by aprajita** [comment]
The classification i made on 21101215 has a tag 0 which means i think that i didn't place a marker and so the classification seem right but the feedback message wrong...

**Comment by eatyourgreens** [comment]
@rogerhutchings I think you're onto something about the code that runs on subject load. I've updated the tests in #4699 to load a mock subject and feedback is updated when I don't expect it. The tests don't seem to put the component into an unexpected state, though.

**Comment by eatyourgreens** [comment]
@aprajita thanks! Sounds like feedback is being shown for a different annotation than the one in the current classification. You say you hadn't placed a marker on any of the previous subjects either? I think that rules out this bug being caused by an old annotation being passed to the feedback rules.

**Comment by aprajita** [comment]
hi @eatyourgreens yes that's right the preceding classification had no markers placed either.

**Comment by aprajita** [comment]
BTW the moderators have said they haven't had this problem for a while so perhaps #4670 did something and not sure what i did to trigger it.
