### ISSUE TITLE
no labs icon/link associated with my account

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#467]
I can access the labs url if I type it in and then see my project, but it's not showing up on the project list. 

Also the only wan I can access the lab is if I manually type the url. The link on the Zooniverse home page is gone for me. Is that a permissions thing with my account (mschwamb)?

screenshot of the preview zooniverse home when I log in

![screen shot 2015-06-03 at 9 59 53 pm](https://cloud.githubusercontent.com/assets/753325/7961844/938aa7b2-0a3c-11e5-9117-4857ff78b5bf.png)

Thanks, 

~Meg

**Comment by camallen** [comment]
@mschwamb - we've temporarily disabled links to the Lab. Also only approved beta projects are listed on the home page, use this link to access: http://preview.zooniverse.org/panoptes/#/projects?approved=false&beta=false

**Comment by mschwamb** [comment]
Thanks.
