### ISSUE TITLE
project page goes completely blank if no workflows active

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#4673]
## Expected behavior

If a project has no active workflows, it should throw an error but it shouldn't break the entire project.

## Current behavior

Jean Tate reported that she couldn't load https://www.zooniverse.org/projects/ngc3314/zoogems with two web browsers (Chrome, Firefox), on two different OSs (Win7, MacOS), project ID 5997. I found the same on Chrome/OS X. Specifically, the project started to load and then the page went blank. The console gave a "no active workflows" error:

![screen shot 2018-06-03 at 11 17 57 pm](https://user-images.githubusercontent.com/2357126/40901606-cda313cc-6785-11e8-8e2c-ba064bf7f2b7.jpg)

Activating one of the workflows fixed it, but I remember it failing more gracefully in the past, I think?

## Steps to replicate

Deactivate all workflows on a project, then try to view the project

## Additional information

- **Operating system:** Windows 7, Mac OS X
- **Browser:** Chrome, Firefox

**Comment by eatyourgreens** [comment]
This is new behaviour in React 16. An error now crashes the page unless caught and handled. 

> As of React 16, errors that were not caught by any error boundary will result in unmounting of the whole React component tree.
https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html

**Comment by eatyourgreens** [comment]
Fixed by #4672.
