### ISSUE TITLE
Main progress bar should be based on classifications, not retired subjects.

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#4676]
I receive regular queries from project owners wondering why their project progress bar is showing 0% completion even though they've had thousands of classifications, and worrying that this is discouraging their volunteers. I agree with them, and then have to explain it's non-linear as it's based on retirement rather than classifications.

I really do believe that it should be based on classifications and that a non-linear progress bar is very poor UX.

**Comment by camallen** [comment]
this is an API issue, the status bar uses the completeness metric straight from the API - closing in favour of https://github.com/zooniverse/Panoptes/issues/2492.

@mrniaboc please comment on the api issue.
