### ISSUE TITLE
Landing page stats update - exclude never retire subjects

### ISSUE THREAD

**Issue by aprajita** [zooniverse/Panoptes-Front-End#4679]
## Expected behavior
Stats should exclude any subjects set to 'never retire'

## Current behavior
included all active sets, even if they will never be retired

## Steps to replicate
visit https://www.zooniverse.org/projects/aprajita/space-warps-hsc

![image](https://user-images.githubusercontent.com/1917970/41095606-d01f6fee-6a49-11e8-80af-c38f49166db6.png)

includes 19748 training subjects so will never be 100% complete

caused a large misunderstanding during science friday week causing many users to only get the already seen flag and multiple classifications on the same images.

thanks!

**Comment by camallen** [comment]
@aprajita this is an API issue, the UI just shows the data the API returns. Could you please file the bug at https://github.com/zooniverse/Panoptes/issues

**Comment by aprajita** [comment]
thanks
