### ISSUE TITLE
Add client UTC offset to classification metadata

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#468]
See https://github.com/zooniverse/Panoptes/pull/929

It's be nice to have the utc timestamps for the classification annotations as well as the client timezone in the classification metadata.

**Comment by brian-c** [comment]
Any particular format? `((new Date).getTimezoneOffset() / 60).toString()` is `"5"` in Chicago right now.

**Comment by camallen** [comment]
I was thinking number of seconds but I don't think it really matters. It should be consistent.
