### ISSUE TITLE
styling issue of the anchor tag within the markdown (wrapping text in tutorial)

### ISSUE THREAD

**Issue by denslowm** [zooniverse/Panoptes-Front-End#4691]
## Expected behavior
Be able to wrap URL text to fit within tutorial window

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

text does not get wrapped (see link below)

## Steps to replicate
see: 
https://www.zooniverse.org/projects/zooniverse/notes-from-nature/classify?reload=1&workflow=6014&_ga=2.184423526.1576714224.1528666194-301989501.1485808297

See the last page of the Tutorial there.

## Additional information
Some further discussion here: #4659 

- **Operating system:**
OS X 10.11.6

- **Browser:**
Chrome

**Comment by eatyourgreens** [comment]
Some of the links in that tutorial are missing whitespace before the URL. Other than that, you are probably at the mercy of the browser’s internal rules for wrapping URLs. 

I’d recommend adding link text, instead of using the bare URLs for the links: `[link text](URL)`.

**Comment by eatyourgreens** [comment]
Closing this because the browser is rendering those URLs correctly. They're just very long strings that don't fit in the width of the tutorial.
