### ISSUE TITLE
Marks disappear on iOS

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes-Front-End#4693]
## Expected behavior

Tapping should add a marker and that marker should stay there.

## Current behaviour

The marker is immediately deleted.

Here's what happens on iPhone:

![iphone](https://user-images.githubusercontent.com/428423/41349913-45f3159a-6f09-11e8-9f16-47561a4f66a2.gif)

And the same on iPad:

![ipad](https://user-images.githubusercontent.com/428423/41349918-4ae5a518-6f09-11e8-93e8-5e535288ed17.gif)

## Steps to replicate

Tap the subject image quickly and the marker will be drawn then immediately be deleted. Tap and hold for a second (so that the magnifier appears or so that you can move the marker) and it will not be deleted.

@eatyourgreens was not able to reproduce this on his phone, but it happens on both my iPhone 6 and my iPad mini, both logged in and not logged in.

## Additional information

- **Operating system:** iOS 11.4
- **Browser:** Safari

**Comment by eatyourgreens** [comment]
I think the code that causes this is [DeleteButton.destroyTool](https://github.com/zooniverse/Panoptes-Front-End/blob/c52965c51b3f67d48cbe4f8598fe8acc4d953727/app/classifier/drawing-tools/delete-button.cjsx#L39-L41) but I'm not sure how it's being called here.

**Comment by eatyourgreens** [comment]
The other method that's probably being invoked here is [MarkingsRenderer.handleDestroy](https://github.com/zooniverse/Panoptes-Front-End/blob/3b8f4370e8b27c53a7591e38911b41375329ae25/app/classifier/tasks/drawing/markings-renderer.cjsx#L133-L145).
