### ISSUE TITLE
Language translation

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#472]
What's the status of language translation on the front end?

**Comment by chrissnyder** [comment]
Not possible yet.

**Comment by chrissnyder** [comment]
Related to https://github.com/zooniverse/Panoptes-Front-End/issues/1265

**Comment by eatyourgreens** [comment]
This will be fixed by #4019

**Comment by eatyourgreens** [comment]
Coming soon. An email went out to Galaxy Zoo translators yesterday.
