### ISSUE TITLE
Typing in the lab workflow help text box causes linked resources to load via API

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#4720]
## Expected behavior
Typing in the workflow’s help text should not reload the linked subject set and tutorial resources .

## Current behavior
Every time i type in a workflow’s help text box the lab page fires of requests to get the linked subject sets and the tutorials resources.

## Steps to replicate
Goto lab workflows page, open up network console, start typing in the help text box and see requests firing on key events.

## Additional information
![linked_resource_reqs_on_text_change](https://user-images.githubusercontent.com/295329/42046746-6ff9875e-7af6-11e8-9c38-b04e7d8bc429.gif)

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
I saw this same bug yesterday while checking/unchecking the Persist Annotations box, which updates `workflow.configuration`. I think it's being triggered by any updated on that page, although I haven't had time to look any further into it.
