### ISSUE TITLE
tutorials_completed_at in UPP is storing a bunch of nulls

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4721]
## Expected behavior
Storing time stamps

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
<img width="701" alt="screen shot 2018-06-28 at 3 16 47 pm" src="https://user-images.githubusercontent.com/5016731/42058531-5949a8d2-7ae6-11e8-8d69-d082b3120ea0.png">

## Additional information
Likely introduced with the react-swipe removal and refactor to ES6

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Looks like `tutorials_completed_at` has been converted to an array, padded with nulls. Could this be a browser bug?

I'm seeing an object, as expected, in a staging project on Chrome with the latest master.
![Screenshot of the dev console, showing preferences.tutorials_completed_at as an object, keyed by tutorial ID.](https://user-images.githubusercontent.com/59547/42090977-72bb5f3a-7b9b-11e8-8b02-b121e04cb12f.png)

**Comment by eatyourgreens** [comment]
This might be a bug in the client. If I'm reading this code correctly, undefined values are set to empty arrays if the next key is a number eg. `'preferences.tutorials_completed_at.1'` is assumed to refer to index 1 in an array.
https://github.com/zooniverse/json-api-client/blob/1a2433b28464ca37854774586d5133ebaf0be60e/src/model.coffee#L38-L41
`tutorials_completed_at` works around this by setting the default value to `{}` before calling `update`, but maybe that has failed here?

**Comment by srallen** [comment]
I saw this in the UPP of the tester account in zooniverse/caesar#358 and wanted to make note of it, but didn't have any time to debug at all yesterday. I think you're on the right track with it being an undefined value and the client is doing this. The timestamp value shouldn't be undefined to begin with regardless if a user is logged in or not. So I think we're seeing a bug in the ES6 converted tutorial as well.

**Comment by eatyourgreens** [comment]
This will happen the first time someone participates in a project. I'm not seeing it because my tutorial preferences already existed. If `preferences.tutorials_completed_at === undefined`, the null check won't catch that and the client will set it to an array because it has numerical keys.
