### ISSUE TITLE
Copy template project

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#4725]
MVP for https://github.com/zooniverse/rfc/issues/34.

Create client side copy template functionality, similar to workflow copy, limited to:
1. create new project with original project's description, "copy of " + display_name (or similar), configuration, experimental_tools, introduction, primary_language, tags, urls, and workflow_description attributes, if defined
2. create copies of original project's active workflows, link new copied workflows to new project
3. create copies of original project's pages, link new copied pages to new project
4. create copies of original project's field guide, link new copied field guide to new project
5. create copies of original project's tutorials, link new copied tutorials to new project
6. create copies of original project's translations, link new copied translations to new project

Initially, we can manually set a new property in a project's configuration to note it can be copied, and only then show the option to copy the project.

Happy to list aspects punting on for future iterations and temporary work-arounds if useful.

Mentioning @zwolf, @camallen, @eatyourgreens and @trouille. Please feel free to edit this initial comment as you see fit for clarity.

**Comment by eatyourgreens** [comment]
Translations will need to be copied for each resource in steps 1–5.

**Comment by eatyourgreens** [comment]
Is there a reason this should be done in javascript, rather than having Panoptes copy the database records in Postgres and making that available as an API call (or set of API calls)?

If Panoptes takes care of copying the records, then the front-end really just boils down to deciding what the UI should be for project owners. A big button saying 'Clone project' that triggers some simple questions like what name to give the new project, and which linked resources to include with the copy?

**Comment by eatyourgreens** [comment]
Worth remembering that project display name is localised, so 'New Project Name' might need translations too. Looking at Galaxy Zoo in the project builder, I think translators are mostly leaving the project name in its original language.

**Comment by eatyourgreens** [comment]
Sorry, one more question. Why should we do this in PFE and not in the lab app? My impression was that the project builder was being gradually migrated over to the lab app anyway.

**Comment by zwolf** [comment]
Fundamentally, this is creating "copy project template" functionality and not a true project clone. This has to do with the funding left on the grant, the complexity of deep cloning projects, and our existing functionality. Workflows are copied in PFE in this exact way. Projects will get a flag somewhere to indicate that they're "copyable" or that they're "templates" or similar and the button will only exist if they are.

This could be done on the API side. The API would use the same logic as the front end to create new objects and copy only the relevant data from the existing resources before saving. The number of API calls that this functionality would introduce is not worth worrying about, as this would be used infrequently. Besides, there's lower hanging fruit for that kind of optimization in the lab (see https://github.com/zooniverse/Panoptes-Front-End/issues/4720).

No one seems to feel particularly strongly about it one way or the other, so @mcbouslog and I talked it out earlier and decided to go with this method. If you (or @camallen) actually do, then let us know why and we can go from there.

**Comment by trouille** [comment]
Hi all - please best to pause on the comments in this thread and wait for the zoom call that you'll have early next week that Mark is setting up. It'll be easiest/most clear to talk directly and hear the pros and cons on both sides and make a decision that way. Thanks! Mark, please post here when you have the time set.

**Comment by eatyourgreens** [comment]
For copying resources in the front-end, how about updating the client's Resource API so we can do something like:
```javascript
let newResource;
existingResource
  .copy()
  .then( resource => newResource = resource);
```

`Resource.copy()` could call Panoptes to get a new resource, or handle the copying in JS. The details would be hidden from PFE (which doesn't care how you copy a project.)

**Comment by mcbouslog** [comment]
Reposting link to zooniverse/rfc#34.
Panoptes bulk-copying completed with https://github.com/zooniverse/Panoptes/pull/2861.
PFE piece remains open.

**Comment by eatyourgreens** [comment]
@mcbouslog will this require changes to [zooniverse/json-api-client](/zooniverse/json-api-client) to handle posting to the `/copy` endpoint?

**Comment by mcbouslog** [comment]
I think it would. Though unless there's an immediate need, this'll likely get added to the new panoptes-js/frontend-monorepo which has it's own related issue - https://github.com/zooniverse/front-end-monorepo/issues/72. So I'll close this for now, with the RFC and FEM issue taking precedent, but we can re-open this if need be.
