### ISSUE TITLE
Notifications don't update when you have unread messages

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4727]
## Expected behavior
When I have unread messages in a project I participate in, I should be notified in the top-level navigation bar.

## Current behavior
From Talk:
>Hello Zooniverse team: is anyone looking into this problem? Beginning Friday 29 June, when you have unread notifications, the "notifications" link/icon in the Zooniverse menu bar is no longer highlighted an no longer shows the number of unread messages when you are on Zooniverse Talk or Zooniverse Projects, although these indicators of unread messages still appear when you are on in-Project pages. Is this an intentional change that we just have to live with, or did a bug creep in? I would really like to have the former consistent behavior across all pages on the site reinstated.
>** or maybe beginning thursday 28th

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Noting that the cause of this seems to be a null query parameter `section=` in the API request to get unread messages. #4728 removes the section parameter from the query if it isn't defined.

**Comment by yshish** [comment]
I'm still experiencing that, no notification when someone replies to my posts on a Talk. 
Not sure it will help but here's a screenshot of my browser console made at the moment when I came to Zooniverse, after receiving an email notification about a mentioning of my user name in a post reply on Zooniverse Talk:
![screenshot_2018-07-07_16-55-59](https://user-images.githubusercontent.com/7211888/42412177-6bdd30ae-8207-11e8-94f1-6cf39483f8b4.png)
(Using Chromium on latest Ubuntu)

**Comment by yshish** [comment]
(I have just received a personal message via Zooniverse and I did receive the notification for messages, but not for the project Talk replies.)

**Comment by yshish** [comment]
Hah, after 25 minutes, I suddenly did get 2 notifications displayed in the top-nav bar. (I think it is the first time in ages that happened.) Anyway, I reloaded the Zooniverse main page without either clicking on the notifications or visiting the project Talk via email, but when the page reloaded, the number of notifications displayed 1 (instead of 2). It doesn't make sense, does it? And after another reload, the notifications display no number at all.

**Comment by eatyourgreens** [comment]
I think this is still a problem. There’s a discussion on Talk about problems with notifications. https://www.zooniverse.org/talk/17/735435

**Comment by camallen** [comment]
What was the reasoning to mark notifications as read when the component unmounts / pages through the notifications? 
https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/pages/notifications/notification-section.jsx#L61
https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/pages/notifications/notification-section.jsx#L275

I may not have read those notifications instead navigated away and back and i'll have lost the first and last ones. Also if i page around just looking at notifications they will be marked as read too. I think these are come of the issues as described on talk. 

It is confusing to me that we are just marking notifications as read just by navigating around.

**Comment by mcbouslog** [comment]
Ok there are a few things going on I think we can change that might be preferable. I'm not sure how to keep this from getting unorganized, maybe splitting these up into separate issues if we agree.

1. notifications count in header - if in a project, [the unread count will be specific to that project](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/lib/notifications-counter.js#L50) (excluding other projects and zooniverse notifications). I think the header notifications count should be for all notifications and remain for all notifications regardless of project context?

generally, the notifications page and TalkAPI mark things as delivered/read aggressively.
- I think the Talk API [updates notifications as delivered](https://github.com/zooniverse/Talk-Api/blob/master/app/mailers/notification_mailer.rb#L57-L59) [after emailing the user](https://github.com/zooniverse/Talk-Api/blob/master/app/mailers/notification_mailer.rb#L9)
- the notifications page marks [notifications as delivered if they were ever visible](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/notifications/notification-section.jsx#L59-L64) as you paged through your notifications

2. we can keep notifications as `delivered: false` even after a related email is sent by removing related code from TalkAPI

3. we can keep notifications as `delivered: false` regardless of if shown on PFE notifications pages (see @camallen's [comment](https://github.com/zooniverse/Panoptes-Front-End/issues/4727#issuecomment-428864577)) 

on the notifications page, notifications may appear duplicated. for example, if you started a discussion, then are mentioned in a later comment, you'll see the same new comment twice in your notifications, but what you're actually seeing is one new notification for being mentioned and one for a comment in a discussion you're subscribed to.

4. I'm not sure exactly how, but we sort of have info in the notification resource to distinguish, so maybe we should show that the notifications are for different reasons even though they're from the same comment?

**Comment by mcbouslog** [comment]
I'm going to tag @beckyrother in regards to [the previous comment](https://github.com/zooniverse/Panoptes-Front-End/issues/4727#issuecomment-430413527), would like your input

**Comment by mcbouslog** [comment]
I think depending on one's notification email settings a notification might show as unread in the header or notifications page for a few minutes (email instantaneously), a day (email daily) or for a  week then (kind of surprisingly?) show as read because of the Talk API email worker behavior.

I didn't realize this until yet more precious few not gray hairs turned gray =\.

**Comment by camallen** [comment]
Thanks @mcbouslog for doing some great investigation work on how this is working. 

I think the main issue at play is the that the notifications `delivered` attribute is being used two distinct cases: 
1. API side it is used to [avoid sending multiple notification emails](https://github.com/zooniverse/Talk-Api/blob/1c200bee04cad1dba41de12ac7282877af820df2/app/workers/notification_email_worker.rb#L24)
0. Client side to determine what is unread in each [notification section](https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/pages/notifications/notification-section.jsx#L107-L108) component *AND* the top nav bar via the [notifications counter](https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/lib/notifications-counter.js#L59-L62)

Any time that an email gets sent for a notification then it's delivered status is set to true and thus won't count towards any unread counts in the UI. 

Also note that the talk api may not send emails immediately as this depends on how the user has configured talk notification emails. Any 'non-immediate' notifications at the moment count towards the unread counts shown in the UI.

I think the Talk API should add a new `read` attribute to support the two distinct use cases, especially around [marking notifications as read](https://github.com/zooniverse/Talk-Api/blob/e1c4dc7651d5b514456551903f77bc4f9a3c0667/app/controllers/notifications_controller.rb#L8).

**Comment by mcbouslog** [comment]
yes! thank you @camallen very well put, and I agree.

I can create a related issue in the Talk API.

In the short term I think it would still be helpful to:
1. remove the code in PFE that marks notifications as delivered [if shown on the notifications page](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/notifications/notification-section.jsx#L59-L64)
2. change the notifications count in the header so it reflects all undelivered notifications regardless of project context

**Comment by eatyourgreens** [comment]
Some simple tests for the unread count in the notification components would be useful too.

**Comment by beckyrother** [comment]
Thanks for tagging me @mcbouslog. Agreed – the **number in the header should stay the same** regardless of where you are in the site. Contextual notifications like this would be extremely confusing when they occur in a global element like the header, as it wouldn't be immediately apparent why the number changes.

**Comment by denslowm** [comment]
There has been some activity on the Talk thread related to this. Please check this before closing. Thank you.

**Comment by yshish** [comment]
Well, I have never even started properly getting notification for anything. Not for replies, not for mentioning, not for receiving private messages. I have just tested that again to make sure. It always says 'You have no notifications...' So please, don't close it yet.

**Comment by mcbouslog** [comment]
Yes we'll keep this open!
