### ISSUE TITLE
Back button causes clearing of all bounding boxes

### ISSUE THREAD

**Issue by Keessie** [zooniverse/Panoptes-Front-End#4736]
I have a labelling task, where the contributor is asked to draw bounding boxes on a single screenshot in several steps, each for a seperate class. For each class the amount of bounding boxes can reach up to 40.

## Expected behavior
If the contributor wants to go back to revise one object, all previously labelled particles should stay in the cache, unless a "clear" button is pressed.

## Current behavior
Currently, all bounding boxes get cleared, causing that the contributor has to re-do part of his work. This demotivates the contributor to correct mistakes.

## Steps to replicate
https://www.zooniverse.org/projects/keesvanoeveren/grogol-pilot/

label some stuff in part 1 to 3, and then press back a couple of times until you are back step 1. Step 2 and 3 bounding boxes will be gone.

Using Chrome

**Comment by eatyourgreens** [comment]
Hi, this is, in fact, expected behaviour for the drawing tools but there is an option to override it in workflow settings. I've added that option to your project.

**Comment by Keessie** [comment]
Thanks for the help!
