### ISSUE TITLE
Truncation in text tasks

### ISSUE THREAD

**Issue by chris1010010** [zooniverse/Panoptes-Front-End#4751]
## Expected behavior
- User enters text in text area and presses Done
- The entered text is shown in the classification summary

## Current behavior
- User enters text and _very quickly_ presses done: text missing or truncated in summary (and database)
- User enters text and, _after a second or longer_, presses done: full text is shown in summary

## Steps to replicate
- Enter text and without delay press done
- The timespan between entering and pressing done is the deciding factor. If entering each character slowly and pressing done quickly leads to truncation. Entering the whole text quickly and pressing done immediately after leads to empty result.
- Slower Internet connections might make the problem more pronounced

## Additional information
See screen capture:
[Screen capture](https://www.dropbox.com/s/2ikbvxoq3qqcla3/TruncationTest.mp4?dl=0)

We could also reproduce this reliably using the workflow classification export (tested on various systems in different text entry speeds).
Had a look at "Panoptes-Front-End-master\app\classifier\tasks\text\...", but am not familiar enough with React to track down this problem. Perhaps something to do with the onChange of the text area and synchronization with the Done button.

- **Operating system:** Tested on Windows and Android
- **Browser:** Tested with Chrome and Firefox

**Comment by marten** [comment]
This is very peculiar, I can definitely reproduce this. I would've thought that all the event handlers would fire in sequence, with the onClick therefore being at the end of the sequence after all the onChange handlers have been processed.

**Comment by marten** [comment]
Ah, the issue will be that updating the actual classification annotation is debounced: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/text/index.cjsx#L137 and therefore it's possible to send before the final debounced update of the annotation happens.

**Comment by srallen** [comment]
#4481 suggests performance reasons. If I'm remembering correctly some of the transcription projects that use the combo task had severe performance issues before the debounce was added. We can try adjusting the debounce, but I don't think it'd be a good idea to entirely remove them all. Perhaps removing it from onBlur or adding a disabled state for classification submission while the debounce is in process.

**Comment by srallen** [comment]
#4743 is in progress, so the fix can be rolled into it. Adding an onBlur handler that doesn't debounce seems to handle it, however, we should confirm this isn't adding the performance issue that debouncing the annotation update in onChange fixed.

**Comment by eatyourgreens** [comment]
`updateAnnotation` is called on unMount. 🤔

**Comment by eatyourgreens** [comment]
There’s also a WIP PR to rewrite the text task. #4743.

**Comment by eatyourgreens** [comment]
Oh wait, the component will probably unmount after the classification is submitted.
