### ISSUE TITLE
Trying to move through the pages of not beta not public projects and link to second+ pages doesn't work

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#476]
I was trying to scroll through the pages of http://preview.zooniverse.org/panoptes/#/projects?approved=false&beta=false to find my project. When you click on the page 2 link  it takes you to a page that says 'no projects found'. Looks like because the direct url  (http://preview.zooniverse.org/panoptes/#/projects?page=2) it brings you to doesn't have the right flags in it.

You can seen in the screen grab that the  http://preview.zooniverse.org/panoptes/#/projects?approved=false&beta=false  page does have a list of 3 pages, but click on 2 and 3 and you get the error I describe above.

![screen shot 2015-06-04 at 9 33 17 am](https://cloud.githubusercontent.com/assets/753325/7975656/fc9ceb6e-0aa2-11e5-8cd7-ade050f25f1b.png)

**Comment by brian-c** [comment]
The `?approved=false&beta=false` params are just a workaround for right now. You'll have to add the page manually: `?approved=false&beta=false&page=2`.

Your project should still be available directly from the Lab page at `#/lab`.

**Comment by mschwamb** [comment]
okay. thanks
