### ISSUE TITLE
Revised in-line help text

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#478]
@srallen thanks for this! I've updated the in-line help text here: https://docs.google.com/a/zooniverse.org/document/d/12dm1T4ciUAYROoA1Qsy4nfoETcIVBJUKGxksbnMoTdw/edit?usp=sharing

It's currently only deployed on http://demo.zooniverse.org/panoptes-front-end/help-text/#/lab -- not sure where plans stand for implementing on preview/incorporating design (@brian-c)?

**Comment by srallen** [comment]
@aliburchard, I updated the help text and manually deployed to http://demo.zooniverse.org/panoptes-front-end/help-text/#/lab. Let me know if any other changes are needed. I'll leave this issue open for now since you have questions for @brian-c.
