### ISSUE TITLE
Analytics for adler.zooniverse.org are missing

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#4780]
## Expected behavior
Looking to track visitor data from the touch table and Adler visitors; analytics do not find anything.

## Current behavior
https://analytics.google.com/analytics/web/?hl=en&pli=1#/report/content-pages/a1224199w25826018p97262563/explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.zooniverse.org~2F%3Fsource=adler/

<img width="1156" alt="analytics" src="https://user-images.githubusercontent.com/1392130/43796198-34ebd4e2-9a49-11e8-86dd-bcb15a1b4a7c.png">

This will help us understand if we're meeting one of our major learning goals for the touch table project.

**Comment by eatyourgreens** [comment]
Should this be on the repo for the touch table code?

**Comment by beckyrother** [comment]
adler.zooniverse.org currently redirects to https://www.zooniverse.org/?source=adler. We also use that url on Adler visitor wristbands, which is why this is in PFE

(The data won't be completely accurate, but with ≤10 unique/month at the last time I checked, I'm not too worried about it)

**Comment by eatyourgreens** [comment]
It sounds like it should be recorded by GA. I’m not sure how to debug it.

**Comment by beckyrother** [comment]
Alternate question: would it be possible to create another page specifically for the touch table with GA built in? These analytics will be important for evaluation. This might be a @wgranger question?

**Comment by beckyrother** [comment]
Sorry, this will be from people's phones – either the QR code or a url they type in after doing the touch table experience. I'm just interested in if people choose to move from the touch table to a mobile / later-desktop experience.

**Comment by wgranger** [comment]
The way I understand this is there will be an intermediary page on PFE where users are directed from the touch table. If that's the case, yes, we can track users activity on that page and send it to GA. However, if this intermediary page is contained within PFE, it will keep logging to that PFE GA location. 

It seems messy, if it's even possible, to try to log to another GA location just for that page, but I can understand why that would be clean for reporting purposes.

Are you also wanting to track through GA whenever a user visits https://www.zooniverse.org/?source=adler? Sorry if I didn't understand that from the initial comments.

**Comment by beckyrother** [comment]
@wgranger let's just talk about this tomorrow morning.

**Comment by trouille** [comment]
https://analytics.google.com/analytics/web/?hl=en&pli=1#/report/content-pages/a1224199w25826018p97262563/_u.date00=20170601&_u.date01=20180826&explorer-table.plotKeys=%5B%5D&_r.drilldown=analytics.pagePath:www.zooniverse.org~2F%3Fsource=adler/

Perhaps this is helpful^ .

**Comment by wgranger** [comment]
I've looked into this a bit more. Not sure why the site isn't showing up under page views, but I have been able to get the source=adler query to show more hits when I search for it as a session query.

https://analytics.google.com/analytics/web/?hl=en&pli=1#/my-reports/er5FnjDSRyiTMrLx7ZgaJw/a1224199w25826018p97262563/_u.date00=20180801&_u.date01=20180828&559-table.filter=source=adler&559-table.plotKeys=%5B%5D&559-table-dataTable.sortColumnName=analytics.pagePath&559-table-dataTable.sortDescending=true/

![screen shot 2018-08-28 at 10 22 51 am](https://user-images.githubusercontent.com/14099077/44733052-5ad7f780-aaac-11e8-9bf9-b50dd12d0506.png)

**Comment by beckyrother** [comment]
Would it be possible to eventually set up another redirect link that goes directly to galaxyzoo.org and can be touch-table specific, so we can track just the visits from the touch table? 

I'm currently using adler.zooniverse.org since I knew it was working and had analytics built in, but eventually we'll need to separate the two so we can get clean data (as opposed to the 5-10 visits from the wristbands and theater promotions).

**Comment by wgranger** [comment]
It depends on what the redirect would look like. Are you thinking galaxyzoo.org/?source=adler, or something of the sort? Or would this be the QR code from the touchtable?
