### ISSUE TITLE
Inactive workflows shouldn't be able to be set as default workflows

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#4789]
Just ran into this problem when trying a new beta project. They had deactivated the default workflow and left two others active. No classifications were loading. Presumably because the inactive workflow was still set as the default?

**Comment by eatyourgreens** [comment]
Duplicate of #4431?

**Comment by mrniaboc** [comment]
Yes. Sorry :(

**Comment by eatyourgreens** [comment]
I think PELIcams have got this problem too. https://www.zooniverse.org/projects/jaimibutler/pelicams/talk/1914/713926?comment=1189223
