### ISSUE TITLE
Subject drag and drop of images/metadata unresponsive

### ISSUE THREAD

**Issue by AdrianEvans** [zooniverse/Panoptes-Front-End#479]
cross-posting from panoptes since the url I'm using is panoptes-front-end

Just created an account and a new project and can't seem to upload images and metadata to a subject. Perhaps I'm doing it wrong. It just doesn't do anything at all (the cursor does change to the state usually associated with the location being an acceptable spot to drop files).

This is on win 8.1 using latest chrome - same issue occurs using explorer 11

csv content is:

file,area,location
DSC03210_01.jpg,1,1
DSC03210_02.jpg,1,2
DSC03210_03.jpg,1,3
DSC03210_04.jpg,1,4
DSC03210_05.jpg,1,5
DSC03210_06.jpg,1,6
DSC03210_07.jpg,1,7
DSC03210_08.jpg,1,8

first two example images.

![dsc03210_01](https://cloud.githubusercontent.com/assets/10448680/7982093/fa4a0b86-0aab-11e5-9f87-f88ba6b173da.jpg)
![dsc03210_02](https://cloud.githubusercontent.com/assets/10448680/7982092/fa48de5a-0aab-11e5-9063-8c92d7bee889.jpg)

**Comment by camallen** [comment]
Linked to https://github.com/zooniverse/Panoptes/issues/931

**Comment by twhyntie** [comment]
And [#191](https://github.com/zooniverse/Panoptes-Front-End/issues/191) - I still can't upload subject sets via WIndows (7, but I guess the problem is the same) with _any_ browser.

I've been using Firefox in Linux (Xubuntu 14.04) to do subject uploads for now (which, by the way, is working very well!).

**Comment by mrniaboc** [comment]
Berris could not upload files as a subject set either. We tried for a while and could not do it on his machine, but it was fine on mine (Ubuntu 15.04). He's using Windows 8.1. Tried Chrome and IE.

**Comment by AdrianEvans** [comment]
can confirm ability to interact with subject upload system using ubuntu 14.1 using firefox

**Comment by AdrianEvans** [comment]
wonder if the cause is the mime type specified for csv "text/csv" in the input accept attribute - see
http://stackoverflow.com/questions/7076042/what-mime-type-should-i-use-for-csv

can we add

**Comment by twhyntie** [comment]
_Update_:

* I can now upload subjects in Windows 7, Firefox via the dialog box (woohoo!);
* It still doesn't work with Windows 7, Chrome - it's not recognising the `.csv` manifest file in the dialog box.
