### ISSUE TITLE
New subject set validation

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#480]
Better feedback message when trying to create a subject set with same name as existing one would improve UX.

**Comment by camallen** [comment]
@simoneduca can you provide a screen shot and steps to reproduce?

**Comment by simoneduca** [comment]
@camallen there you go. (This is one way of triggering the validation message)

1. Add a new subject set; don't edit or save.
2. Click on New Subject Set button.

![screen shot 2015-06-04 at 11 28 16](https://cloud.githubusercontent.com/assets/8989606/7982196/fc445f9e-0aac-11e5-8302-43a076073889.png)

Perhaps disabling the New Subject Set button while the current subject's form hasn't been saved would help.
