### ISSUE TITLE
handleInputChange silently converts array and object values to strings

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#4801]
https://github.com/zooniverse/Panoptes-Front-End/blob/09cc8f46d34b2a6dbf413b14b3fa935232ab5052/app/lib/handle-input-change.coffee#L21-L24

`DOMPurify.sanitize` silently converts `value` to a string, breaking `resource.update(changes)` when value is an array or an object.

This broke the project builder tag inputs in #4799.

**Comment by srallen** [comment]
I like the extra layer of protection using `DOMPurify` gives, but obviously should only be used where needed. I think the solution should be to refactor the tag input to not use this abstracted out event handler (and eventually others should be too).

**Comment by eatyourgreens** [comment]
There might be other components that are passing objects (or arrays) to `handleInputChange` eg. the workflow task editors in the project builder.
