### ISSUE TITLE
Subject set upload replaces name input with default text if not saved

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#481]
@brian-c Steps to reproduce:
1. Click New Subject Set button
2. Name it, but don't save the name.
3. Select the files to upload and click upload.
4. Once the upload is complete, the name input is replaced with the default 'Untitled Subject Set'.

**Comment by vrooje** [comment]
Yeah I've seen this multiple times too when I forget to save the name before uploading subjects.

**Comment by chrissnyder** [comment]
Fixed by https://github.com/zooniverse/Panoptes-Front-End/pull/543
