### ISSUE TITLE
On closing modal window showing upload limit errors, page becomes unresponsive.

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Panoptes-Front-End#482]
To reproduce:

1. Upload subject set when you've reached the upload limit.

![screen shot 2015-06-04 at 14 12 17](https://cloud.githubusercontent.com/assets/8989606/7984840/e3280f12-0ac3-11e5-9874-494d9dd6f408.png)
2. Close the modal window.
3. Console shows something is undefined and can't get its length property value.

![screen shot 2015-06-04 at 14 16 43](https://cloud.githubusercontent.com/assets/8989606/7984961/f35b1072-0ac4-11e5-8bc9-d1e05b70f9a2.png)

**Comment by chrissnyder** [comment]
@simoneduca Can you confirm this is fixed and close if so?

**Comment by simoneduca** [comment]
@chrissnyder I can't reproduce step 1 anymore. Did you lift the limit?

**Comment by brian-c** [comment]
This should have been closed with #487, but I guess closing from PR comments doesn't work, sorry.

@simoneduca I believe the limit was upped to 1,000 or 10,000. Display of this number could still be better.
