### ISSUE TITLE
Playable gifs no longer working on Gravity Spy

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#4821]
## Expected behavior
Playable/looping gifs should work.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Gravity Spy uses example gifs to show the sequence of a glitch event in the choice examples. These no longer work. Likely due to the thumbnail service. 

## Additional information
Example gif from Gravity Spy: 
![Gravity Spy animated gif](https://static.zooniverse.org/panoptes-uploads.zooniverse.org/production/workflow_attached_image/67f5354d-23e3-40d7-96e4-5b769569b6b6.gif)

Same file passed through the nginx thumbnail service: 
![Same file after processing by the thumbnail service](https://thumbnails.zooniverse.org/500x999/panoptes-uploads.zooniverse.org/production/workflow_attached_image/67f5354d-23e3-40d7-96e4-5b769569b6b6.gif)

- **Operating system:**
- **Browser:**

**Comment by srallen** [comment]
This is in the survey task choice example images. I'm not sure if it's setup to support video. We'll have to test it out.

**Comment by eatyourgreens** [comment]
There's an issue, from Manatee Chat (I think), to add audio/video survey choices. I'll dig it out.

**Comment by eatyourgreens** [comment]
#4115 The front-end code would be very simple to implement in the Choice component but the survey task would have to support uploading the example files and I don't know if it restricts the upload MIME type at the moment.

**Comment by eatyourgreens** [comment]
Short term, the Thumbnail component can also be modified to ignore GIFs and pass those URLs through unchanged.

**Comment by eatyourgreens** [comment]
For the audio projects, where they want to show an image and an audio file together, I wondered if we could reuse the subject viewer for the Choice examples, with the subject ID of an example subject being passed in to the component for each choice. I'm not sure how that would work in practice though.

**Comment by eatyourgreens** [comment]
A very quick fix for this issue would be to modify `Thumbnail.getThumbnailSrc` so that it returns the unmodified `src` if the extension is `.gif`.
https://github.com/zooniverse/Panoptes-Front-End/blob/82370132286a3687de3afcf076dc30adde8e5e9e/app/components/thumbnail.jsx#L73-L80
