### ISSUE TITLE
Can't submit classifications for survey task that requires at least 1 identification

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#4822]
## Expected behavior
I can press done or done and talk to submit a classification

## Current behavior
I can't press done or done and talk after identifying 1 class from the survey tool.

## Steps to replicate
Visit https://www.zooniverse.org/projects/thegalaxyonorionsbelt/are-we-alone-in-the-zooniverse/classify?reload=0&workflow=7536

Ensure that the workflow has "require at least 1 identification setting" enabled - https://www.zooniverse.org/lab/7111/workflows/7536

Try and submit a classification.

## Additional information

- **Operating system:**
- **Browser:** FF, Chrome, Safari

**Comment by CKrawczyk** [comment]
The `required` check is looking at the length of the current annotation: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/tasks/survey/index.cjsx#L35

It looks like this object is not updated when a selection is made on the survey task:
![screen shot 2018-08-24 at 3 24 30 pm](https://user-images.githubusercontent.com/6557526/44590219-8ad48180-a7b2-11e8-928f-100afcc7d4dd.png)

This is preventing the task from being marked as "complete".
