### ISSUE TITLE
Duplicate subject counts after new subject upload

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#485]
I'm uploading a subject set that has 7849 subjects, each with 2 images. I'm doing this in batches of ~500 at a time. 

Today I've noticed that the subject counts are off. Example: I added 456 subjects with manifest and images, and started the download:
![screen shot 2015-06-04 at 15 37 51](https://cloud.githubusercontent.com/assets/2357126/7986826/d0e1de42-0ad1-11e5-9bb4-3b38b8c8dd8a.jpg)

Then after the upload is finished, this is what displays:
![screen shot 2015-06-04 at 15 44 09](https://cloud.githubusercontent.com/assets/2357126/7986841/eac53fb6-0ad1-11e5-94e5-f79c1b2cac91.jpg)

So the number of subjects it says it has added is twice the number of subjects it has actually added (the subject count in smaller font at the bottom is correct), but equal to the number of images it has added.

I'm pretty certain this wasn't happening a couple of days ago when I first started uploading batches of this.

**Comment by camallen** [comment]
Just to clarify each subject has 2 images right? Sounds like a reporting error on the front end. It should be uploading 456 subjects with 912 media locations.

**Comment by vrooje** [comment]
Yes, each subject has 2 issues in this project.
