### ISSUE TITLE
Allow project builders to make drawing tasks "required"

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#488]
Questions can be required. I think drawing tasks should be able to be set as required as well. Right now it's hard to explain why only questions can be required. If there's an instance where there is nothing to draw, then project builders can set required = false -- but on all of the drawing tasks I've made, I've made them contingent on the critter being there, so I want to require them.

**Comment by chrissnyder** [comment]
I 100% agree that we need this, but I don't think we need for the imminent soft launch.

Can (and should) be a high-priority issue afterwards though. 

Happy to debate further

**Comment by aliburchard** [comment]
Fair enough. I don't think it's absolutely critical if it slows down the launch, but I do think it's really important.

**Comment by chrislintott** [comment]
I think we should make this very high priority - if not before then immediately after launch

On Jun 18, 2015, at 6:16 AM, aliburchard <notifications@github.com<mailto:notifications@github.com>> wrote:


Fair enough. I don't think it's absolutely critical if it slows down the launch, but I do think it's really important.

**Comment by aliburchard** [comment]
@chrissnyder @brian-c I think this should be Sprint 1 - please feel free to disagree.

**Comment by chrissnyder** [comment]
Removing the PFE Sprint 1 label because that doesn't make sense anymore. Likely will tackle this in the not-too-distant future anyway.

**Comment by brian-c** [comment]
I've got a plan for checking required-ness across tasks. I'll plug it in as soon as the survey task is done.

**Comment by aliburchard** [comment]
@brian-c how is this coming along? And is it possible to merge it with the highly requested "set min/max # markings per task" in #1564 ? This keeps cropping up as an issue across projects we're building, and would also help *enormously* with aggregation. Would it be possible to bump this up the priority list after tutorials but before the next big fancy addition?

**Comment by brian-c** [comment]
At least one mark can now be required for drawing tasks. Closing this, will comment on #1564.

**Comment by aliburchard** [comment]
Yay!! Thank you!
