### ISSUE TITLE
social media links on the project front page with a form to fill in on the project builder 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#489]
low priority - if science teams are going to be encouraged to communicate their project's happenings and results with social media it would be nice if you could enter those links in the project builder and the twitter icon, g+ icon, and facebook icon would appear on the front page of the site. I think explicitly having those text boxes to fill in in the project builder would encourage project teams to set up such accounts.

**Comment by mschwamb** [comment]
@mrniaboc @jwbmartin with the update of the project landing page maybe this could be considered as well and added in to the design. The Zooniverse icons are present, but a project has no place to advertise they have social media account with the known icons.  A place to put nicely generated icons for social media accounts associated with the project and the front end having a place to fill in those entries would be helpful.

**Comment by wgranger** [comment]
On further inspection on this, it looks like Brian partially added functionality to have social media icons appear in a project's external links, but only if a label isn't given, which seems odd.

**Comment by beckyrother** [comment]
In Project Builder / Project Details, add a section under External Links called Social Links. List out every possibility:
![screen_shot_2017-06-27_at_10 05 54_am_360](https://user-images.githubusercontent.com/1392130/27595431-4a0cb560-5b22-11e7-80d6-13facf8428a2.png)
...in a similar style to the external links form fields. Add instructions that if the field is left blank it will not be visible on the project landing page. Don't use icons for the form fields, use words.
