### ISSUE TITLE
preview mode for markup text boxes 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#490]
low priority - but I noticed that I'm already up to version 43 on the project builder version of the workflow because of the edits to the help. I make an edit in format and then want to see what it will look like. Usually I've made a typo and mistake and have to switch back between refreshing the tab with the project in it to see the help box and the tab with the project builder. I found this to be a slow process because of the extra steps to refresh the browser and then click on the help button.

It would be nice if any of the markup text boxes like the help, project description, science, faq, results pages could have a preview tab that could show the text formatted like github does. 

Fully understand this is a wish list item, but I thought I'd include here in case it can be added to the lsit of longer term upgrade suggestions

**Comment by brian-c** [comment]
This actually exists, it's just not exposed anywhere due to parallel development of Talk's inputs around the same time.

@aweiksnar what do you think of combining these?

**Comment by aweiksnar** [comment]
Yeah a single format for rendering markdown would be cool. Exporting the markedown-it config and then sharing a markdown preview might be composable enough to start building unified editing options

**Comment by mschwamb** [comment]
cool. it would be a really nice feature I think  since most of the back and forth between the project website and the project builder is for formatting and text edits

**Comment by mschwamb** [comment]
another thought if all this functionality is already sitting in the new Talk and can be exported over to the project builder. Not everyone will know markup. Talk was nice because it has the buttons to autogenerate the code bit of the markup. Not all scientists will know markup. It would be nice if those autogenerate buttons could be included in those text boxes in the project builder (low in the queue, but I think it would help a lot for less code experienced teams trying to build a site).
