### ISSUE TITLE
Redirecting of the old Penguin Watch classification to the new PW stopped working

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#4903]
## Expected behavior
When someone visits Penguin Watch using the old system link www.penguinwatch.org or click on the blue 'Return to classifying' button or through the old classification link: https://www.penguinwatch.org/#/classify, the page should redirect the user to the new Panoptes version: https://www.zooniverse.org/projects/penguintom79/penguin-watch/classify automatically.

## Current behavior
Using the old project link www.penguinwatch.org does redirect to the new PW page but going from the old Talk https://talk.penguinwatch.org/ changes the URL to https://www.zooniverse.org/classify and says: ":(  Not found". The same results when using the old system classification link https://www.penguinwatch.org/#/classify

## Steps to replicate
Go to https://talk.penguinwatch.org/ and click on the blue button 'Return to classifying' (top right corner). Then see what happens. (Or just use this link: https://www.penguinwatch.org/#/classify)

## Screenshot of the results: 
Together with a browser console errors...
![ysh_screenshot_2018-09-16_14-19-54_bad_redirection](https://user-images.githubusercontent.com/7211888/45596507-0f36b080-b9bd-11e8-8335-5d96e73ac8fb.png)

- **Operating system:**
Ubuntu
- **Browser:**
Chromium 69
Firefox 62

It was definitely working on Thursday just after Cam made the redirection changes. I tested that and confirmed. Not sure I was using the old system links anytime later though.

**Comment by yshish** [comment]
@camallen

**Comment by yshish** [comment]
Still not working for me. Is that expected?

**Comment by eatyourgreens** [comment]
This change hasn't gone live yet. Give it 30 minutes or so.
