### ISSUE TITLE
Image shadow/mirrored on combined .png+.mp3 subject set

### ISSUE THREAD

**Issue by monadnoc** [zooniverse/Panoptes-Front-End#4906]
@trouille
## Expected behavior
Uploading .png+.mp3 is expected to maintain normal opacity of the original .png files.
## Current behavior
_Please include any error messages from the browser console and/or screenshots_
The uploaded .png+.mp3 shows shadowing/mirror of the png, as if the white background were semi-transparent. As in https://www.zooniverse.org/projects/vivitang/earthquake-detective/classify; also, please see attachment for a screenshot.
![overview](https://user-images.githubusercontent.com/41121628/45640477-66e62200-ba78-11e8-9927-4238e71bae45.png)

## Steps to replicate
An example subject set is on Box https://northwestern.box.com/s/dnloutyfj2z2r4m4uixgs8b7tp99tf60. Let me know if you cannot access it.
## Additional information
The .png files are generated and saved with matplotlib (plt.savefig).

The .png files uploaded on their own (without the .mp3 file) show an opaque (white) background with no shadow/mirrored image.
- **Operating system:**
Windows, Linux, Mac
- **Browser:**
Firefox, Edge, Chrome, Brave

**Comment by srallen** [comment]
We don't support pngs for the spectrogram player at the moment. Could you try processing a couple of them as jpg?

**Comment by monadnoc** [comment]
Re-uploaded a couple test subject sets with a .jpg image instead. The transparency/shadow persists.

The images were made with matplotlib (pyplot.savefig). Wondering if this is an issue with pyplot, I tested manually specifying `"facecolor='w'"` (white), but this showed no improvement. Manually saving the original .png images as .jpg with MSPaint (and re-saving the pyplot .jpg as a .jpg with MSPaint, for good measure) also showed no improvement.

The below image shows the unwanted behavior with the .jpg + .mp3 subject set (can be found [here](https://www.zooniverse.org/projects/vivitang/earthquake-detective/classify) for now).

Thanks for your assistance

![still_transparency_with_jpg](https://user-images.githubusercontent.com/41121628/46119242-b8f11b00-c1cf-11e8-808e-4a8a631e0ff9.jpg)

**Comment by eatyourgreens** [comment]
Reading back through the conversation on #4055 this is a hack that was added for projects that use the drawing tools with audio subjects. The drawing layer isn't guaranteed to line up with underlying subject image. It can't be removed without breaking projects that ask you to draw shapes on top of spectrograms.

[Manatee Chat](https://www.zooniverse.org/projects/cetalingua/manatee-chat/classify) has PNG images that line up properly, so the issue might be white space at the top or bottom of the PNG charts.

**Comment by monadnoc** [comment]
Uploading with Panoptes-CLI appears to eliminate the layering issue seen in the manual uploads. Not sure why this is, don't have time to test, but would first try different browsers manually uploading vs. the Panoptes-CLI; another culprit might be the .csv manifest in manual uploads vs `subject.metadata.update(metadata)` written for the our Panoptes-CLI code.

For now, I will mark this as closed.

**Comment by monadnoc** [comment]
@trouille

This bug is now limiting the functionality of our project. 

We cannot upload a dataset with Panoptes-CLI (needed as workaround to this issue) while keeping feedback for question-type tasks  functioning. Since feedback for question-type tasks is still in testing (right?) solving this image layering issue with manual audio+image uploads may be more straightforward than opening a new issue.

To reiterate what has been tried:
-multiple image formats (.jpg, .Tiff, .png)
-multiple browsers and OSs
-resizing image (generated with matplotlib) to try to build/eliminate white space on top as @eatyourgreens suggested
-explicitly defining facecolor as 'white' in matplotlib before exploring
-generating a test .jpg file with MS Paint (+ resaving the original image file as .jpg with MS Paint)
-creating new workflows
-creating new subject sets

What else can be tested to move this issue towards a close so that we can manually upload '.jpg + .mp3's (needed to implement project feedback with question-type tasks) without this artefact?

**Comment by eatyourgreens** [comment]
Looking at the different workflows on your project, it looks like this bug shows up for subjects where `subject.locations` looks like this:
```
[
    {  'image/png': 'https://panoptes-uploads.zooniverse.org/production/subject_location/a46d70f2-6ea6-401d-8d21-e5a5748c03ca.png' },
    {'audio/mpeg': 'https://panoptes-uploads.zooniverse.org/production/subject_location/78dcb784-3b90-4f4a-85b5-812183a30980.mpga'}
]
```
but not for subjects where `subject.locations` looks like this:
```
[
    {'audio/mpeg': 'https://panoptes-uploads.zooniverse.org/production/subject_location/15015863-db29-48e7-b724-08d6cb7c0ced.mpga'},
    {'image/png': 'https://panoptes-uploads.zooniverse.org/production/subject_location/97cb2ac5-cbfc-4a6b-b6ba-1c620c858d1c.png'}
]
```

A simple workaround might be to upload your subjects with the audio file before the image file in the manifest.

I'm afraid I don't think this bug can be fixed in the current classifier, but we are working on a new version of the classifier which should have better support for audio subjects like these.

**Comment by eatyourgreens** [comment]
>We cannot upload a dataset with Panoptes-CLI (needed as workaround to this issue) while keeping feedback for question-type tasks functioning.

I'm a little confused by this. I think feedback is specified per-subject in the manifest CSV, and the CLI tools use the same CSV manifests that the web uploader uses. The CLI is under active development, but the web uploader is not, so I'd expect the project builder to be behind the python tools in terms of functionality here.

**Comment by viviantang33** [comment]
Hi, 
Our team tried to re-upload figures, audio files and feedback for the practice workflow via Panoptes. There is no showdowing figures but also no "feedback" anymore. We debug our code several times but have no idea what's going. Is it possible that the 'beta testing' we have been activated on for feedback rules for question-type evaluations is not supported with metadata assignments or something like that? I opened a new workflow ("Practice: E vs T) (https://www.zooniverse.org/lab/6465/workflows/8086) to test the feedback function. Here is the link of the subject set I have created: https://www.zooniverse.org/lab/6465/subject-sets/60760. These are the screenshots for the feedback function in the new workflow, 
<img width="523" alt="screen shot 2018-10-26 at 11 58 55 am" src="https://user-images.githubusercontent.com/29933220/48221472-d7623e80-e357-11e8-832f-c21460262642.png">
<img width="1010" alt="screen shot 2018-10-26 at 11 58 20 am" src="https://user-images.githubusercontent.com/29933220/48221483-da5d2f00-e357-11e8-8aaa-725dc85c6d4d.png">
I also attached the manifest.csv file.
[manifest.csv.zip](https://github.com/zooniverse/Panoptes-Front-End/files/2563203/manifest.csv.zip)

**Comment by trouille** [comment]
@viviantang33 Could you do a quick test and upload just the png files with feedback (i.e. do the same as you've done, just not include the mp3 files)? That'll help us in trouble shooting. Thanks!

**Comment by mcbouslog** [comment]
Forgot to mention @viviantang33, unsure of GitHub notification settings, so adding this comment incase didn't see the above.

**Comment by eatyourgreens** [comment]
@mcbouslog this issue is closed, and was for a different bug. I moved the feedback ID bug to #5058. Your comments here might not get noticed because of the issue being closed. I'm not sure.
