### ISSUE TITLE
PFE potentially submits multiple copies of a Classification

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#4911]
## Bug Report

It is currently possible for PFE to submit multiple copies of the same Classification. There are multiple ways this bug can occur, but this report focuses on the confirmed, replicable issue that relies on **network/time out/latency errors.**

### Analysis

In PFE, when a Classification is submitted, it is added to a "submission queue". If a Classification isn't successfully submitted the first time, it's then _re-submitted_ when a _new Classification_ is submitted and the queue processed again.

However, the re-submission logic doesn't account for what happens when the initial Classification submission _doesn't fail,_ but just takes _a long time to process._

### Analysis - Example Scenario

- User submits Classification A (attempt 1) to PFE, then proceeds to the next Subject.
  - However, Classification A (attempt 1) takes a long time to resolve, possibly due to network latency or a slow API response.
- User submits Classification B to PFE.
  - PFE notes that Classification A (attempt 1) hasn't succeeded or failed (i.e. it's still being sent, with a status of 'pending')
  - Hence, PFE attempts to re-submit Classification A (attempt 2) along with Classification B.
- After a while, _all three_ submissions resolve successfully.
  - Classification A (attempt 1) resolves with a 201.
  - Classification B resolves with a 201.
  - Classification A (attempt 2) resolves with a 201.
- Now, PFE has _two copies_ of Classification A, and one copy of Classification B.

Note that, in this scenario, the two copies of Classification A have the same **metadata** and **annotations,** but different classification IDs.

### Steps to Replicate

This testing setup uses localhost (staging), OSX+Chrome, and an [example Project](https://pfe-preview.zooniverse.org/projects/darkeshard/transformers/classify?reload=0&workflow=3272) with a small subject set and simple text field workflow. This test uses Chrome's dev tools to simulate a slow network or a laggy response from the API.

Note: before I test, I run through the project and make one "filler" classification for each Subject. This ensures that each Subject image is cached in my browser, so Chrome's simulated network lag _only affects the API calls._

Testing steps:
- Open the example Project's Classification page.
- Open Chrome Dev Tools (Cmd+I on OSX) to simulate network lag/slow API response times.
  - Go to the Performance tab, click on Network dropdown, and select/create a custom Network Throttling Profile with some significant latency, e.g. 30 or 60 seconds.
- Switch the Chrome Dev Tool window to Network to monitor Classification submissions (i.e. POSTs to the `/classifications` API endpoint)
- Submit the first Classification with some easily identifiable annotation (e.g. "Hello this is Classification A"`)
  - You should see the first POST to `/classifications`, and it should be in progress (status: pending)
  - Quickly move to the next step while that POST is in progress.
- Submit the second Classification with easily identifiable annotations. (e.g. "G'day this is Classification B")
  - You should now see _three_ POSTs to `/classifications`, all in progress (status: pending)
  - Two of these POSTS should be for Classification A, and the other for Classification B.
- Wait a while (i.e. however long you set the latency to be) for all three POSTs to resolve.
  - You should now see _three_ 201 responses (resources created) for your _two_ Classification submissions.
- Download the Project's Classification exports to confirm that Classification A was received twice.

I'll post my test results separately to avoid cluttering this post further.

### Status
Issue identified, but solution is still pending.

Warning: this analysis does not exclude other scenarios where duplicate Classifications are found, esp. if those Classifications have slightly different metadata (e.g. the known case where `metadata.finished_at` of two potentially duplicate Classifications are off by a microsecond.)

Tagging @camallen for the initial problem report, and @rogerhutchings for sanity checking/counter thoughts on the PFE queue.

**Comment by shaunanoordin** [comment]
### Supplementary Material 1: Screenshots

![screen shot 2018-09-19 at 15 22 24 a](https://user-images.githubusercontent.com/13952701/45761638-8a4dd000-bc24-11e8-8fc7-28584b1b16e2.png)
_Screenshot 1: immediately after the second Classification is submitted._

![screen shot 2018-09-19 at 15 25 46](https://user-images.githubusercontent.com/13952701/45761728-b23d3380-bc24-11e8-8f68-31e7ebd9b522.png)
_Screenshot 2: 60 seconds after the second Classification is submitted_

In the screenshots above, we can see that there are _three_ POSTs to `/classifications`, and it's noted that the second and third were sent while the first was still pending a response.

### Supplementary Material 2: A Cavalcade of Duplicates

It's possible to go really nuts and create a cascade of duplicates, as unresolved Classifications _keep stacking for each new submission._ If we submit _five_ Classifications _before_ the first submission fully resolves, we can get 5 copies of Classification A, 4 copies of Classification B, 3 copies of Classification C, etc.

Attached: [example Classification CSV export for example Project](https://github.com/zooniverse/Panoptes-Front-End/files/2397612/transformers-classifications.txt)

Note the last 15 rows, which correspond to my five Classification submissions.

### Supplementary Notes

While the Chrome Dev Tools are sufficient for illustrating the basic problem, is there a way to replicate a slow response on the API backend itself? Curious to know for future testing.

**Comment by camallen** [comment]
@shaunanoordin we can run a test API with a delay in the classification submissions if you like, this would simulate the issue without impacting on the rest of the app. 

Could the same simulation come about by putting in a delay before processing the promise handler on classification save? 
https://github.com/zooniverse/Panoptes-Front-End/blob/b911e973bc5bafb8f634b7ee4c18d0f555bb6a59/app/lib/classification-queue.js#L48

**Comment by shaunanoordin** [comment]
> we can run a test API with a delay in the classification submissions if you like, this would simulate the issue without impacting on the rest of the app.

Sweet, thanks! It's good to know that's an option.

> Could the same simulation come about by putting in a delay before processing the promise handler on classification save?

Sure can, adding some artificial delay right after the `.save()` call seems consistent with the logic of the problem. Anything that delays the execution of the "remove this successful/failed Classification from the queue" bits should trigger the duplicate entries.

**Comment by eatyourgreens** [comment]
The underlying cause of this bug is that classifications are kept in local storage until the save promise resolves. If the classification queue is flushed multiple times before a given classification save resolves, that classification will be read from local storage and sent to Panoptes each time.

#4923 fixes this by clearing local storage before saving classifications, then adding failed classifications back to the stored queue.
