### ISSUE TITLE
very difficult to draw fans that have same starting point but are in different directions with the fan tool

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#4912]
Feedback after further playing around with the new  fan tool for P4:

The new fan tool for P4 has an issue that will need a solution before we can launch the new P4 We have not too infrequent cases where fans have the same vent but are blown by the wind in different directions

On the Ouroboros P4 the x to remove the fan was in the center of the marker. The panoptes version has the x at the end of the fan. So now if you try and make a fan at the same starting point. You either need to move off the x or draw the fan somewhere else and move it into position. We want to encourage people to draw fans with the same origin point, since this is one of the science drivers for P4 to look at whether the wind is changing over a HiRISE monitoring season. 

Can the 'x' to delete a fan be moved in the fan tool be moved somewhere from the starting tip? 

![Uploading fan_tool.gif…]()

**Comment by mschwamb** [comment]
I thought a  screen grab might be helpful:

![fan_tool](https://user-images.githubusercontent.com/753325/45849414-add94f00-bce6-11e8-88d3-801c049a0f15.gif)

**Comment by eatyourgreens** [comment]
Fixed by #4916. You can try out the change here: https://fan-tool.pfe-preview.zooniverse.org/dev/classifier

The delete button can't be clicked for very small fans, because the drag handlers for the shape get in the way. I don't know if this will be a problem for P4.
![Screenshot showing the delete button overlapping the drag handlers for very small fans.](https://user-images.githubusercontent.com/59547/45959487-ec864680-c011-11e8-842f-44b10e02b9a7.png)

**Comment by mschwamb** [comment]
Moving the 'x' to that spot makes it hard to see where to draw the fan to. I noticed that for the ellipses and rectangles the x is now outside the shape. Could that be done for the fan tool ? 

<img width="994" alt="screen shot 2018-09-24 at 5 04 56 am" src="https://user-images.githubusercontent.com/753325/45997700-2ff5aa80-c03c-11e8-8a9d-2fe9e4b05ae1.png">

**Comment by eatyourgreens** [comment]
Sure. It was outside the shape originally, by 20 pixels, but I moved it to the centre because that's apparently where it is on the original P4.
