### ISSUE TITLE
not showing the subject id in the pop up window for the new talk collections button

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#493]
There's a new button, which I'm assuming is so you can directly add the subject to a talk collection. It reveals the subject name which I'm presuming will be visible on the talk pages. 

![screen shot 2015-06-05 at 2 44 41 pm](https://cloud.githubusercontent.com/assets/753325/8000216/a4dc3fe2-0b92-11e5-8ac1-54bbd6917b7d.png)

If the new Talk works like the old Talk with  pages dedicated to a subject and a search functionality, this allows the volunteer to go to Talk and see people's comments before they submit their classification which could bias the classification. No identifying information about the subject name should be shown before the classification is submitted, so that a volunteer can't be biased by discussion on Talk or by being able to google and find more about the subject.The best example I have is from Planet Hunters. If people know there was a planet around the star from the talk discussion, they'd more be more likely to mark a transit in the section of light curve they were looking at for that star even if that specific piece didn't have a transit. 

If the subject name does need to be included, can this Talk collection button appear after the classification has been submitted?

**Comment by mschwamb** [comment]
Now that talk was implemented on the preview system I was able to look at the Talk for a subject I was sent in the classification interface before finishing my classification because of the subject id being listed in the talk collection button.

I clicked on the collections button in the interface

![screen shot 2015-06-12 at 1 39 23 pm](https://cloud.githubusercontent.com/assets/753325/8141847/645827ca-1109-11e5-9174-f43d3e9af38a.png)

then manually typed in the Talk url and if there were comments or additional metadata I would have had access to it before submitting my classification

![screen shot 2015-06-12 at 1 40 00 pm](https://cloud.githubusercontent.com/assets/753325/8141867/a92c0538-1109-11e5-8d9b-963d62ccffdd.png)


Also I was able to add the subject to a Talk collection before finishing my classification and now the button in the interface for talk collections shows I added it to a spiders collection

![screen shot 2015-06-12 at 1 50 01 pm](https://cloud.githubusercontent.com/assets/753325/8141927/83b0a4f2-110a-11e5-99f9-1ae8c427210e.png)


This is a significant problem for getting any science out these projects. If someone sees that a volunteer added the subject in my case to a spiders collection, they are going to be significantly more likely to click on the spiders button even if that person who made the collection is wrong. So now I've  completely lost my classifications being independent of Talk.  Currently the wisdom of crowds only works when volunteers opinions are isolated. On a data reduction side both of these issues makes it incredibly difficult to say that none/or the vast majority of volunteers didn't do this, and I presume when that button is clicked is not stored in the database?

 The Zooniverse's NEMO lab project I think was aimed at trying to look at if it could overcome this, but this is why all Zooniverse projects to date do not reveal the subject id until the classification is submitted.  

Adding the subject to a Talk collection should only be a feature after the classification is submitted.

**Comment by mschwamb** [comment]
This shouldn't be future plans. This actually causes problems with data reduction because volunteers can be biased by Talk or other outside data and there is no way to identify if that happens. The subject id should not be listed anywhere in the classification interface. This why it's never listed on other Zooniverse projects before classifications are submitted.

**Comment by edpaget** [comment]
I'm reworking that dialogue anyway and I'll remove it.

**Comment by mschwamb** [comment]
A huge thank you @edpaget
