### ISSUE TITLE
Add admin behaviour via admin flag on client requests

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#494]
Zoo admin users will need a way to enter "admin mode" via the front end that will add admin flag to client requests (see below). It will be able to use the "/api/me" after https://github.com/zooniverse/Panoptes/issues/947.

Panoptes allows admin behaviour for an admin user if the [admin flag is set on a request](https://github.com/zooniverse/Panoptes/blob/aeeb92b18250c2b04dbc578cc3010de1624041b4/app/controllers/api/api_controller.rb#L85). If the flag is set and the user is not an admin it will not have the proper access rights as per [here](https://github.com/zooniverse/Panoptes/blob/aeeb92b18250c2b04dbc578cc3010de1624041b4/app/models/api_user.rb#L24).

**Comment by camallen** [comment]
@chrissnyder @brian-c - I need to upload more than 10K subjects via the API for some projects and it relies on this admin flag feature, is this more than an hours worth of work? If so i'll modify the backend to work a different way until this is ready.

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes-Front-End/commit/cb1dfd99c95df6c09d171a6dc5f473a4054c82e7
