### ISSUE TITLE
Add new Planet Four and Disk Detective papers to publications page

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes-Front-End#4965]
Noted on talk: https://www.zooniverse.org/talk/449/753847 

There are a couple of new papers to add. I'll try to take care of this next week.

**Comment by wgranger** [comment]
I can take care of this today if I can have access to the [Zooniverse Publications](https://docs.google.com/forms/d/e/1FAIpQLSdbAKVT2tGs1WfBqWNrMekFE5lL4ZuMnWlwJuCuNM33QO2ZYg/viewform) submissions, or I can refer to the talk post if we think that's accurate.

**Comment by adammcmaster** [comment]
Closing this as @hrspiers has been adding publications (#5017 and #5024)
