### ISSUE TITLE
Ignore leading whitespace in metadata field names

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes-Front-End#4967]
Currently, if I call a metadata field something like ` !name` it doesn't get hidden in the classifier. It's very easy for people to accidentally add a leading space when they create their manifest, and multiple times we've corrected people's metadata for them to remove the spaces. 

It would be easier if PFE stripped leading spaces from the names before deciding whether or not to hide the fields.

**Comment by eatyourgreens** [comment]
Relevant code is here, I think. https://github.com/zooniverse/Panoptes-Front-End/blob/f1efdf4061c7d875ee444da83d0aa50486eb3792/app/components/subject-viewer.cjsx#L289-L306

**Comment by eatyourgreens** [comment]
For completeness, the metadata keys should be cleaned up when a new manifest is read too. https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/pages/lab/subject-set.cjsx#L306-L311
