### ISSUE TITLE
Feedback for workflows only appears on primary (*) workflow, silent on other workflows

### ISSUE THREAD

**Issue by monadnoc** [zooniverse/Panoptes-Front-End#4985]
@mcbouslog 
## Expected behavior
Feedback functionality should work for multiple workflows on the same project.
## Current behavior
Feedback functionality only works on the primary workflow (the workflow with an * next to it in the workflow list; that is, the workflow that is activated when the 'classify' tab is activated from a top of a project).

## Steps to replicate
See https://www.zooniverse.org/projects/vivitang/earthquake-detective/classify for a functioning example of feedback on question-type classification.
See https://www.zooniverse.org/projects/vivitang/earthquake-detective/classify?reload=0&workflow=7317 ('Tutorial: Earthquake vs. Tremor') for example of non-functioning feedback on question-type classification.
See https://drive.google.com/drive/u/1/folders/1pmo_RlLz_xVDnuICZp47bKRRDlyEzPpd?ogsrc=32 for an example subject set uploaded for the functioning/non-functioning feedback on question-type classification.

## Additional information
It is unclear whether this omission in feedback is limited to workflows with question-type classifications (as has been tested for the report of this bug) or feedback on all classification tasks in non-primary workflows.

- **Operating system:**
Windows, Mac
- **Browser:**
Firefox, Chrome, Edge

**Comment by eatyourgreens** [comment]
There aren't any feedback rules listed for workflow 7317 (https://www.zooniverse.org/lab/6465/workflows/7317) If you add some feedback rules to that workflow, it should start working.

**Comment by monadnoc** [comment]
Good eye. Thanks for the quick response
