### ISSUE TITLE
Metadata is presented in a random order

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#4992]
I've just found out that metadata is presented in a pseudo-random order in the classification interface, not in the order of metadata columns in the manifest file. 

It's obviously not a gigantic problems, but it would be nice for project owners to be able to order their metadata. Example is the new TESS project where the researchers would like to present all the stellar properties together first, but they are being shown randomly interspersed among the other metadata.

**Comment by eatyourgreens** [comment]
Duplicate of #1177. PFE does preserve the manifest order when creating subjects, but key/value hashes are unordered so I guess the order is lost between saving to Panoptes and retrieving the subject again. Changing that would involve some changes to how subject metadata is represented in Panoptes.
