### ISSUE TITLE
Would you like the "panoptes" package name on npm?

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#4998]
Hello Zooniverse, I hope you're all well! I just got a request for the "panoptes" package name on npm, which we'd stopped using for some reason and I still have (sorry!). Let me know if you'd like to hold on to it, or else I'll pass it on.

**Comment by rogerhutchings** [comment]
Hello @brian-c, hope you're well too! We'd like to hang on to it, if that's cool.

**Comment by brian-c** [comment]
Handed off to "zooniverse-user". Take care!
