### ISSUE TITLE
Change formatting so that check boxes on the project details isn't squished and hard to read

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#502]
The text and description for the two check boxes on the project details page is squished and formatted in a vertical column. I've checked only in Chrome and Firefox, but it occurs in both. It would be good if it could be formatted horizontal to make it easier to view. 

![screen shot 2015-06-06 at 12 34 16 pm](https://cloud.githubusercontent.com/assets/753325/8021768/3e6ce54c-0c49-11e5-8e4b-20c46c2edcdb.png)

**Comment by chrissnyder** [comment]
Related to https://github.com/zooniverse/Panoptes-Front-End/pull/509

**Comment by chrissnyder** [comment]
Same problem as #432
