### ISSUE TITLE
Refreshing the page changes the workflow for anonymous users

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5025]
## Expected behavior
If I'm not logged in, refreshing the page should reload the workflow I'm currently working on.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Reloading the classify page loads the default workflow, regardless of which workflow I was actually working on.

## Additional information
We could probably fix this by saving the current workflow in session storage. It wouldn't be remembered across browser sessions, but that's probably not so important if people aren't logged in.

- **Operating system:** N/A
- **Browser:** N/A

**Comment by eatyourgreens** [comment]
Saving the workflow to session storage here, then checking session storage on load, would probably fix this. https://github.com/zooniverse/Panoptes-Front-End/blob/42424c48d0353d5e42887a0938bfffb8216e58c8/app/redux/ducks/classify.js#L320-L325

**Comment by srallen** [comment]
Just noting here that I'm concerned that this is adding another workflow selection strategy and we would need to decide where in the order of strategies this would fall. Should this be done before loading workflow by query param? A part of me sees this not as a bug but rather as a means to encourage users to register instead.

**Comment by eatyourgreens** [comment]
The problem is we frequently tell people to refresh the page if they want to try classifying a different subject, and that's broken if you aren't logged in.

**Comment by srallen** [comment]
Maybe we can add a 'skip this subject' button instead?

**Comment by eatyourgreens** [comment]
I’m an idiot. We could solve this by having workflows linked by ID in the Classify page URL.
