### ISSUE TITLE
Add scientists/team publishable names to the science page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#503]
A low priority suggestion - for the science page, I think it's important to also list the publishable name of the team/researchers/scientists, not just their Zooniverse username. If there isn't going to be text form to do that, can the publishable name the person entered for their Zooniverse account be listed?

**Comment by mkosmala** [comment]
According to @edpaget on #223, there is going to be a more freeform page for team member info. Is this going to be a page/tab in addition to the 'science' page? 

I want to echo @mschwamb above, but I think it's a high-priority item. The volunteers deserve to know who is affiliated with the projects! In the meantime, I'm just tacking on Markdown to the bottom of my science page explaining all the team members. But it's an ugly solution. I'd much prefer a separate page/tab -- freeform is fine with me.

**Comment by edpaget** [comment]
@mkosmala @mschwamb When we finish up #557 you'll be able to set a different display_name that can be your full name or whatever that will be shown in places like the Science Page in addition to your short name that's used for @-mentions. Similar to how Twitter works.

**Comment by mschwamb** [comment]
@edpaget  that doesn't solve acknowledging the places we work at.  It would be good though on the science page if affiliation can be listed if the person has one. Every academic institute I've been at wants to have some credit for the projects I've helped created, and that's been through acknowledging that I'm at a specific place. Currently there is no way to do that. 

Changing my display name doesn't tell people I'm actually at a research institution. I think it gives the volunteer some more info when they decide to try a project. I think  people who are not scientists/researches.etc should be  allowed to make projects, but it might be worth the volunteers being able to decide if they want to work on the project being be able to see that information and decide

**Comment by DarrenMcRoy** [comment]
(Just wanted to say, very glad that we have that system of display names and @-mention-names.)

**Comment by edpaget** [comment]
@mschwamb sure that sounds like a different issue though.

**Comment by mschwamb** [comment]
@edpaget I can open a separate one for institute lables

**Comment by mkosmala** [comment]
@edpaget But is there going to be a 'people' page/tab in addition to the 'science' page? I'm with @mschwamb, but I'll go further: I want affiliation, but I also would like to be able have additional information. Look what Zooniverse's team page:
https://www.zooniverse.org/team
Would you really be happy with just a list of real names on that site?

**Comment by edpaget** [comment]
@mkosmala my plan is to add support for arbitrary markdown pages on a project. You can add whatever you want with whatever title you want.

Also there are going to be user profiles (with controllable visibility) you can add further information about yourself to.  

At the moment feel free to add whatever you want to any of the pages you have. You can put literally whatever content you want on them.

**Comment by mkosmala** [comment]
@edpaget Okay, thanks. Yeah, I was planning to put info about the team on the 'science' page. It might be a little crowded that way, but will work for now. Looking forward to your arbitrary markdown pages.

**Comment by chrissnyder** [comment]
Looks like the immediate concern here was addressed and the broader request will be added later. Closing for tidiness.
