### ISSUE TITLE
Video speed buttons are blocked on survey projects

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5041]
## Expected behaviour
The playback speed radio buttons should always be accessible.

## Current behaviour
_Please include any error messages from the browser console and/or screenshots_
Annotations for survey tasks are positioned over the video playback controls.
![Screenshot of battling birds, showing 3 bird IDs blocking the playback controls.](https://user-images.githubusercontent.com/59547/47996773-881ad480-e0f1-11e8-8bd6-8c4033ec0857.png)

## Additional information
Also reported on Talk here: https://www.zooniverse.org/talk/18/774521

- **Operating system:** n/a
- **Browser:** n/a

**Comment by eatyourgreens** [comment]
Depending on when we plan to migrate survey projects to the new classifier, this might be better solved in that repo.

**Comment by srallen** [comment]
The CSS parts of the redesign could happen with the survey task now like we did with the radio and checkbox inputs, which can just be copied over when ready.
