### ISSUE TITLE
Talk links to zooniverse.org won't open in a new tab

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5044]
## Expected behavior
 Markdown like `[zooniverse](+tab+https://www.zooniverse.org)` should create a link to zooniverse.org that opens in a new tab.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Links that point to the same origin as the calling page are overridden and opened in the same tab.

## Steps to replicate
See this Talk discussion https://www.zooniverse.org/talk/18/557175?comment=1293649

## Additional information

- **Operating system:**
- **Browser:**

**Comment by shaunanoordin** [comment]
To be clear:
- links in `talk.zooniverse.org` to _external URLs_ work correctly, if you add `+tab+` to the markdown link.
  - e.g. `[It's Cthulhu!](+tab+https://en.wikipedia.org/wiki/Cthulhu)` opens in a new window/tab
- links in `talk.zooniverse.org` to _zooniverse.org_ links always open in the same window/tab.
  - e.g. `[It's cuddly cats!](+tab+https://pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats)` doesn't open in a new window/tab as expected.

I've created a test thread here: [https://pfe-preview.zooniverse.org/talk/38/317](https://pfe-preview.zooniverse.org/talk/38/317)

The generated HTML _does_ contain the `_blank` target, but something's overriding the standard interaction (onClick?) behaviour.

```
//Generated HTML:
<a href="https://pfe-preview.zooniverse.org/projects/brooke/i-fancy-cats" target="_blank">It's cuddly cats!</a>
```

This has been tested on OSX+Chrome.
