### ISSUE TITLE
Unable to link a chapter from FAQs using table of content

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#5080]
## Expected behavior
I used the table of content style for the new Penguin Watch FAQs.
When I want to link a specific chapter, I click on the heading in the list that appears at the top of the FAQs and the URL changes from X to Y:

X:
https://www.zooniverse.org/projects/penguintom79/penguin-watch/about/faq

Y:
https://www.zooniverse.org/projects/penguintom79/penguin-watch/about/faq#5.-other-objects%2C-unlisted-animals

I expect the Y link to take me directly to the linked FAQs chapter (chapter **n. 5 - Other objects, unlisted animals**)

## Current behavior

When I use the Y link in a discussion and click on it again, it won't take me to the linked FAQ chapter but it shows me just the regular FAQs page instead (so the results are the same for both X and Y links). 

I don't want to believe that is a supposed behaviour. If so, how can I get the link to a specific FAQ chapter?

Thanks!

## Steps to replicate
Click on the X link (above) and then click on the Y link (just below the X one). See what happens.

## Additional information

- **Operating system:** Ubuntu
- **Browser:** Chromium 70

**Comment by yshish** [comment]
@camallen please, can you tell whether it is supposed to work or not? Thanks.

**Comment by srallen** [comment]
@yshish unfortunately the standard named anchor behavior won't work with the current routing setup we have with the app. We are working on rebuilding much of the app, so we will keep this in mind as an improvement to make.

**Comment by yshish** [comment]
@srallen Oh, OK. Thank you.

**Comment by srallen** [comment]
@yshish Just for transparency, we using a really old version of react-router with the current site and it'd be a big effort to update the version (and I'm not sure if the latest version even fixes this) versus us planning on making sure this works with the rebuilt app. The rebuilt app will use server-side rendering which will solve several issues that have to do with initial load and preview with links (so on social media the preview is the actual project) and it might fix this issue too. We'll have to test that.

Here's a blog post that describes the problem: https://medium.com/@gajus/making-the-anchor-links-work-in-spa-applications-618ba2c6954a
