### ISSUE TITLE
Control multi-image iteration speed

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5092]
## Requested behavior
User can control speed that multi-image subject iterates through frames.
Maybe set options (similar to video playback), maybe slider.

## Current behavior
I believe [this code](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/components/subject-viewer.cjsx#L52-L53):
```
playFrameDuration: 667
playIterations: 3
```

**Comment by eatyourgreens** [comment]
I think this could also be covered by #4706: adding subject viewer config options, which then act as default settings for the workflows in the classifier, or just as the viewer settings in Talk.

From memory, the Talk API doesn't allow for per-project configuration of Talk, but subject viewer options could be stored in the Panoptes project configuration, which is arbitrary JSON data.

With that set up, this issue would then just be a case of making the frame duration an editable property, within reasonable limits.

**Comment by eatyourgreens** [comment]
For this particular issue, see also [WCAG 2.2.2](https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html)
>For any auto-updating information that (1) starts automatically and (2) is presented in parallel with other content, there is a mechanism for the user to pause, stop, or hide it or to control the frequency of the update unless the auto-updating is part of an activity where it is essential.
