### ISSUE TITLE
Keyboard shortcuts to cycle through multi-image subject frames

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5093]
## Requested behavior
Cycle through multi-image subject frames with keyboard shortcuts (without having to get focus to carousel indicators).

## Current behavior
If focus on carousel indicators can use arrow keys to cycle through frames.

**Comment by eatyourgreens** [comment]
Should classifier feature requests be opened in [zooniverse/front-end-monorepo](/zooniverse/front-end-monorepo)? The old classifier should be getting bug fixes, but not new features.
