### ISSUE TITLE
Add invert button to Talk subject viewer

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5094]
## Requested behavior
Add invert button to Talk subject viewer.

## Current behavior
Subjects viewed within Talk do not have the invert button.

**Comment by eatyourgreens** [comment]
Duplicate of #4706, I think.

**Comment by eatyourgreens** [comment]
Also request for survey projects here: https://www.zooniverse.org/talk/17/610656?comment=1311667
