### ISSUE TITLE
Fix long link styling in subject metadata

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5095]
## Expected behavior
Link to appear readable, within modal.

## Current behavior
https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/subjects/13772456
Link doesn't wrap.

**Comment by eatyourgreens** [comment]
This has been requested before by NfN. We can’t control how browsers wrap URLs but I pointed out to Michael that the solution would be to add link text to their Markdown links in metadata. I’ll dig up the original PFE discussion.

**Comment by eatyourgreens** [comment]
See https://github.com/zooniverse/Panoptes-Front-End/issues/4691#issuecomment-396664168

That discussion was for tutorials, but the problem is the same: long URL strings that the browser won't wrap.

**Comment by mcbouslog** [comment]
per https://github.com/zooniverse/Panoptes-Front-End/issues/4691#issuecomment-396664168:
"I’d recommend adding link text, instead of using the bare URLs for the links: [link text](URL)."

**Comment by mcbouslog** [comment]
Could adding the `word-break: break-all` styling be an option?

**Comment by eatyourgreens** [comment]
It’s definitely worth trying. The exact wrapping might vary depending on which characters are in a URL.

**Comment by eatyourgreens** [comment]
That branch looks good on my phone, by the way.
