### ISSUE TITLE
Can't preview subject_set images getting broken-link 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#510]
When I click on any of the subjects in the beta_test set to preview them in the  Planet Four: Terrains project builder I get the following below. I'm using the latest version of firefox (I haven't tested it in other browsers)

![screen shot 2015-06-08 at 11 47 36 am](https://cloud.githubusercontent.com/assets/753325/8046174/86ff3c92-0dd4-11e5-9746-d1711c149100.png)

**Comment by chrissnyder** [comment]
@mschwamb I can't replicate this issue. Is this still happening?

**Comment by mschwamb** [comment]
yep still happening - it's on the subject set where we have almost 2000 subjects loaded

**Comment by mschwamb** [comment]
Interestingly it depends on what subject I select. I didn't upload the subject set if that helps.

**Comment by chrissnyder** [comment]
Could you add user "bumishness" as a collaborator on the project so I can take a look?

**Comment by mschwamb** [comment]
yes

**Comment by chrissnyder** [comment]
Looks like the subject images files exist, but are length 0. Failed upload perhaps?

@edpaget Not sure what the takeaway from this is. Doesn't feel like the front-end is the place to check for this, i.e. it should assume that if a subject is returned with an image, the image should exist.

**Comment by edpaget** [comment]
It seems like the uploader should catch failed errors to s3 and delete the subject right?

**Comment by mschwamb** [comment]
btw there was no warning or anything that an image failed to upload. it was a fairly large but some of them did upload because I could select the subject set

**Comment by chrissnyder** [comment]
Ah, for some reason I wasn't thinking of the subjects being created on the front-end. Yes, in that case, the front-end should definitely catch those errors. I'll work on this a bit today.

**Comment by mschwamb** [comment]
@chrissnyder so I noticed the same thing is happening for the formal beta test subjects. The images are showing on the site so they must be somewhere showing but I can't see the preview like with this set. So it this issue really solved?

**Comment by mschwamb** [comment]
Weird it works trying it again 5 minutes later - maybe slow connection to Asia?

**Comment by chrissnyder** [comment]
Perhaps. If the image are showing in the interface, then that's a much weirder case, as this location isn't doing anything differently.

The original problem was one of failed uploads, which my PR should've solved.

If this does occur again, especially with fresh subject sets uploaded through the web UI, that'll be cause to investigate again.
