### ISSUE TITLE
Multi-Workflow Bug - Wrong resources when user selects Workflow

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#5108]
## Major Bug
On a project with multiple Workflows, it's possible that when a user selects a specific Workflow, they are instead given the resources (Subjects, questions, etc) for the wrong Workflow.

For example, in the [Southern Weather Discovery](https://www.zooniverse.org/projects/drewdeepsouth/southern-weather-discovery) project, a user might click on "Sea Pressure" workflow in the Project home page, but see images and questions from the "Sea Temperature" instead.

The trigger for this error is currently quite random, and is hard to replicate. This error was discovered by @mrniaboc today, 29 Nov 2018, on the Southern Weather Discovery project.

Tagging @eatyourgreens, @simensta, and @mcbouslog for dev debugging power.

### Analysis / Notes

The issue may stem from how PFE sometimes fetches *multiple workflows* at a time, and whichever fetch request resolves first (or last?) gets served to the user, instead of the workflow that the user requested. Due to the race condition where we have no idea which fetch request was resolved, we might get a mix-and-match of questions.

Notes:
- A user being delivered the wrong workflow is one problem, but the bigger issue is when a user receives a mismatch of Workflow questions and Subject images.
  - In the SWD project, we've seen situations where the Subject image shows "Sea Pressure", the task area asks "Sea Temperature" questions, and the resulting Classification is tagged with the "Sea Pressure" workflow ID - rendering the answer invalid.
  ![image](https://user-images.githubusercontent.com/13952701/49240871-33bbf980-f3fe-11e8-92e3-402c22ec8a99.png)
  _Screenshot of one such mismatch, captured by Grant._

### Replicating the Bug

This bug has been noted to most likely occur in **incognito windows** (notably using OSX+Chrome70), we're not sure why yet.

Conditions Required:
- The Zooniverse Project must have multiple workflows.
  - presumably, _no default workflow_ can be set. (This needs to be tested as a control variable.)
- The Project must allow users to select their workflow.
- The User('s web browser) must be in incognito mode - specifically, in a _fresh new incognito window._

Replication Steps:
1. open a new incognito window (recommended: Chrome. Make sure Network tab is open)
2. go to the [Multi-Workflow Bug Debugger](https://master.pfe-preview.zooniverse.org/projects/darkeshard/multi-workflow-bug-debugger-1) project
3. at the home page, click on the "Nature" workflow
4. EXPECTED: you should see a "Nature" image to classify, with a "Nature" question
5. ACTUAL: you see a "Tech" image to classify, with a "Tech" question
6. if (5) doesn't happen, close the window and restart the process, or restart the process and flip the script and try clicking on the "Tech" workflow until you see the "Nature" workflow instead. I'm sorry, but the trigger for this is **so goddamn random** but you should see at least one error after 3-4 tries.

If you have the Network tab open, then you'll see that when (if) the error occurs at (5), you will see that there are requests to TWO workflows simultaneously.

![screen shot 2018-11-29 at 17 57 41](https://user-images.githubusercontent.com/13952701/49241649-5a7b2f80-f400-11e8-90a6-1747f2e99450.png)
_The Classifier showing a "Tech" image and "Tech" question, despite the user clicking on the "Nature" workflow._

In the screenshot above, note how the Network simultaneously picks up calls to `https://panoptes-staging.zooniverse.org/api/workflows/3294` (Nature) and `https://panoptes-staging.zooniverse.org/api/workflows/3295` (Tech) - there's a GET and an OPTION call for each, so you'll `3294` twice and `3295` twice.

These double Workflow requests should _not_ happen, of course.

### Status
This is a major bug. ☠️ Our main concern is that with this bug, users may inadvertently submit answers to the wrong questions, which may screw up the research data.

While front-end debugging efforts are focused on identifying where/how the multi-workflow bug triggers and preventing further "problem answers", there will be corresponding effort to figure out a way to retroactively spot these "problem answers" in the back-end.

Note: this issue may be affected/alleviated by PR #5107

**Comment by shaunanoordin** [comment]
## Troubleshooting Update

PR #5107 might fix this issue!

When testing the Multi-Workflow Bug Debugger project on the PR branch - https://pr-5107.pfe-preview.zooniverse.org/projects/darkeshard/multi-workflow-bug-debugger-1 - I have been unable to replicate the problem where multiple workflows are simultaneously requested by the Classifier.

@mcbouslog has reported similar positive results when testing on https://with-workflow-bug-2018-11-29-1500utc.pfe-preview.zooniverse.org/projects/markb-panoptes/workflow-translation-project

@simensta has reported similar positive results when testing on SCOTUS notes.

**Comment by mcbouslog** [comment]
staged a version of PFE with bug @ https://with-workflow-bug-2018-11-29-1500utc.pfe-preview.zooniverse.org/

**Comment by eatyourgreens** [comment]
Noting that the actual bug here is a mismatch between the loaded translation and workflow.

**Comment by eatyourgreens** [comment]
Sorry, I didn’t read the description properly. The issue described here is actually a variation on  #5025 and is fixed by #5107. 

When the classify page loads, workflow selection runs and should check the store for an existing workflow for the project before loading a random workflow by default. If a user is present, it should load the last workflow they worked on, stored in their project preferences.

**Comment by eatyourgreens** [comment]
Noting here that a robust fix for this and #5025 would be to address workflows by ID in the Classify page URL.
