### ISSUE TITLE
Talk subject viewer mirror workflow Flipbook Play iterations

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5109]
## Expected behavior
Workflow with multiple images' Flipbook Play Iterations setting will be mirrored in related Talk subject post. 

## Current behavior
Talk subject Flipbook Play iteration stops at 3 (defaultProp).

## Steps to replicate
lab/workflow: https://www.zooniverse.org/lab/2416/workflows/8285
project/talk/subject: https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/666/801555

Specific subset of #4706, related to #5094.

**Comment by srallen** [comment]
I don't think we can do this without a major refactoring of Talk. Talk is unaware of workflows and their configurations. There are several tools for the subject viewer that don't work on Talk because of this.

**Comment by eatyourgreens** [comment]
My suggestion in #4706 is to configure default subject viewer behaviour on the project config, since Talk doesn't have per-project config either.
