### ISSUE TITLE
Projects potentially impacted by 11/29/18 bug detected - active projects w/ 2+ workflows 

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5110]
## Current behavior
_Please include any error messages from the browser console and/or screenshots_

## Additional information

- **Operating system:**
- **Browser:**

**Comment by trouille** [comment]
https://www.zooniverse.org/projects/dataliberation/1961-census

**Comment by trouille** [comment]
Note: a few like https://www.zooniverse.org/projects/yli/humbug have two workflows where one is a training and the other is the real one. Maybe the fact that the training workflow has a really restricted number of subjects could be helpful?

**Comment by mcbouslog** [comment]
for both bugs discussed Nov. 29th, I think the project would also need:
- `configuration: user_chooses_workflow: true`

If this is specific to the mismatched translation bug (as opposed to #5025 or #5108) I think the project would also need to have:
- 2 active workflows with matching translation keys

**Comment by mcbouslog** [comment]
working on a Google Sheet to track notes on how the workflows in the projects listed above compare: https://docs.google.com/spreadsheets/d/13KeacPMoPIWi8UWGrQDLIl3PVQ9-NnmAyZTj-u43IhU/edit?usp=sharing (accessible to Zooniverse members)

**Comment by eatyourgreens** [comment]
>the wrong workflow&subject&translation bug (#5025 or #5108)

That bug is just workflow selection's `getSelectedWorkflow` method choosing a random workflow if you aren't logged in, since there's no stored user preferences to get the workflow ID from.

**Comment by mrniaboc** [comment]
Has anyone been able to recreate the issue of mixed-up workflow text and subjects yet?

I need to know:

1) Have the changes that have been made fixed these bugs?
2) What is the time period these bugs would have been affecting projects?
3) Exactly which projects have been affected.

Sorry if I'm repeating myself and asking you to repeat stuff too. I'm finding it hard to keep up with where we are at now, but really soon I will have to send an explanation and apology to the affected teams. before I do this I really want to have all the facts in hand as we will most likely be asking some people to discount a large chunk of their data.

**Comment by eatyourgreens** [comment]
@mcbouslog did you get anywhere with figuring out which projects have been affected?

The earliest report I've seen on Talk abut people getting questions that don't match the subject is Wikiscripta Neerlandica in October: https://www.zooniverse.org/talk/17/770909

Given that this is a translations bug, for any given project it could date back to whenever the English language translation for that project was set up in Panoptes.

**Comment by eatyourgreens** [comment]
If this bug wasn't introduced by translations, then it might have been introduced by the addition of subject queue interventions.
https://github.com/zooniverse/Panoptes-Front-End/pull/4797
https://github.com/zooniverse/Panoptes-Front-End/pull/4781

**Comment by srallen** [comment]
> That bug is just workflow selection's getSelectedWorkflow method choosing a random workflow if you aren't logged in, since there's no stored user preferences to get the workflow ID from, and no workflow ID in the URL.

Why isn't there a UPP store for signed out users since the initial refactor to not use the panoptes-javascript-client as a data store?

**Comment by srallen** [comment]
The bug for the wrong workflow for the signed out user would've been introduced with https://github.com/zooniverse/Panoptes-Front-End/pull/5035

I think with my brief interaction with that PR I misunderstood what was happening because I didn't do a through read through. What I thought was happening was that there was a preferences redux store being added to be used for all users. This is what I've done with the rewrite: https://github.com/zooniverse/front-end-monorepo/blob/master/packages/lib-classifier/src/store/UserProjectPreferencesStore.js

I think we should try to stay consistent in strategy between what's happening on PFE and the rewrite. PFE should at this point only be getting critical bug fixes; Are there any recent refactors that aren't essential to recent new features like interventions that can just simply be reverted? The way UPP used to work with workflow selection did known minor bugs, but it worked.

**Comment by eatyourgreens** [comment]
Signed-out users use the stored workflow. We just need to wait for the workflow to load and the store to update before running workflow selection. Otherwise, we have two sets of API requests being fired again.

**Comment by eatyourgreens** [comment]
This bug was first reported back when UPP was still in use. I've commented on the other issue.

**Comment by srallen** [comment]
The bug that the wrong workflow is loaded for signed out users on click of the home page buttons? Could you link to the report?

**Comment by eatyourgreens** [comment]
The bug where the workflow selection component made almost simultaneous requests for more than one workflow, and the responses came back in an unpredictable order.

**Comment by srallen** [comment]
Ok, separate from the signed out user one. I'll make sure to keep my comments in the separate issues. I still need to catch up on this one too.

**Comment by eatyourgreens** [comment]
It just occurred to me, that bug would also have affected signed-out users, because they had a UPP back then too. I think it was reported on a project that was still in testing, so they didn't have any anonymous users at that point.

**Comment by wgranger** [comment]
@trouille  Custom projects would not be affected by this as it is a PFE-related bug.

**Comment by eatyourgreens** [comment]
Scribes uses the translations API for Arabic/Hebrew/English versions but, I'm assuming, has its own code to validate the task translations against the workflow. Or maybe only has one workflow?

**Comment by srallen** [comment]
Closing as the potentially effected projects now have a flag in their classification exports.
