### ISSUE TITLE
Incorrect use of project_id query param on get /subjects

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#512]
Project Id param on cellect / queued subject selection end point can cause and empty set of subjects to be returned. A subject has the uploading project stored on it to trace the original uploader. Adding the project_id for a copied subject set (Kittehs) causes filtering on the subject project id field to exclude the queued subjects.

https://github.com/zooniverse/Panoptes-Front-End/blob/bd1b4dfbd42dbaeeb5c8ce8d266f1b67eb15e3c0/app/pages/project/classify.cjsx#L141

The only query params that should be included on a sort are the subject_set_id (for grouping) and the workflow_id. I'm going to add a filter to remove extraneous query params on the backend as well.

**Comment by brian-c** [comment]
I've never specified a subject_set, I thought leaving it out implied a random one for the workflow. Is that required now?

**Comment by camallen** [comment]
It's required if the workflow is grouped, otherwise it's not. See discussion [here](https://github.com/zooniverse/Panoptes/pull/747) under the outdated diff for details.

**Comment by edpaget** [comment]
Closed by #514
