### ISSUE TITLE
Why two get-subject-location functions?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#5139]
why are there 2 `get-subject-location(s)` files? One if coffee-script the other javascript
Seems like they are both still used but supply similar functionality?

<img width="609" alt="screenshot 2018-12-11 at 14 25 48" src="https://user-images.githubusercontent.com/295329/49806941-d8b8c980-fd50-11e8-828b-4d06c6bceaa2.png">

+ https://github.com/zooniverse/Panoptes-Front-End/blob/20701a319e00922f33c954786f0140e42bc7eaee/app/lib/get-subject-locations.js
+ https://github.com/zooniverse/Panoptes-Front-End/blob/20701a319e00922f33c954786f0140e42bc7eaee/app/lib/get-subject-location.coffee

**Comment by srallen** [comment]
It looks like to me that the js version is a conversion of the original coffeescript and we just forgot to delete the coffeescript version?

**Comment by eatyourgreens** [comment]
I think one returns a single subject location and the other returns multiple locations. I haven't looked at them in a while, though.
