### ISSUE TITLE
GS mode displayed in a project where not supposed to

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#5149]
## Expected behavior
I should only be able to see the gold standard mode in projects where it is set up.

## Current behavior
After working on real GS classifications in WesternShield CW, I went to the Zooniverse home page, displayed my most recent projects and chose Invader ID, went to the classification page and did a couple of classifications when I realized I'm still in the GS mode although it shouldn't be possible for that project.

Then I opened the Invader ID project in a new browser tab to see whether it will be there. But no GS mode was available for me there any more.

## Additional information
It happened while working on a Lenovo Yoga 10 (tablet)
- **Operating system:** Android
- **Browser:** Chrome (latest version)
(not a device I usually work on while classifying)

Screenshots:
![screenshot_2018-12-12-18-20-15](https://user-images.githubusercontent.com/7211888/49887740-6671e300-fe3d-11e8-9ed2-37d9529ae372.png)
![screenshot_2018-12-12-18-16-23](https://user-images.githubusercontent.com/7211888/49887746-68d43d00-fe3d-11e8-9ff7-82200bda9418.png)

**Comment by yshish** [comment]
I am able to replicate that on different projects where I don't do GS. (As you can see in the screenshot of the linked issue.)

It looks like I cannot display a browser console on tablet browsers. Or is there a way?

**Comment by camallen** [comment]
If a user does submit a GS marked classification for a project they are not setup on, the API will reject their classification with a bad_request (HTTP 400 response - https://httpstatuses.com/400).

I'm not sure if the front end will eventually give up trying to submit the classification on this response or if it'll try indefinitely. Thoughts?
https://github.com/zooniverse/Panoptes-Front-End/blob/8ef454ee4ebd030e9efbdd39c4a9ac717e5ed27d/app/lib/classification-queue.js#L67

Relevant API code:
https://github.com/zooniverse/Panoptes/blob/2b1e23182adb5e9b19994d4c24d020cdc6121fb2/app/models/concerns/classification_validator.rb#L12

https://github.com/zooniverse/Panoptes/blob/54da959c35eb5e20406b16abf57b0d7e62f53418/app/controllers/api/api_controller.rb#L19

https://github.com/zooniverse/Panoptes/blob/4cfe0e6e8bf7b3edd98490416caedb116207753a/app/controllers/concerns/json_api_responses.rb#L41

**Comment by camallen** [comment]
Not recorded at all by the look of that subject ID :cry:

**Comment by yshish** [comment]
Oh, what a shame. Thanks for looking at the subject. 
Happy we're aware of that bug and can make sure to disable the GS before classifying in other projects.
