### ISSUE TITLE
Hide previous marks crashing when signing out on classify page

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#5162]
## Expected behavior
The hide previous marks toggle shouldn't throw and crash the app. Does this really need to make this call to update annotations on unmount or at all?

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

I signed out while on the classify page and got:
`Uncaught TypeError: Cannot read property 'update' of null`

It's throwing on line 221 in the classify duck. The hide previous marks toggle is calling to update the annotations on unmount.

## Steps to replicate
You can replicate on my test project: https://master.pfe-preview.zooniverse.org/projects/srallen086/sgl-tester

1. Sign in if not already. 
2. Select "freeline tool test not required" workflow and load the classify page. 
3. Sign out

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Hide Previous Marks was originally stored as an underscored property on the classificiation. It would be great if someone could find the time to rewrite it so that it doesn't use either the classification or annotations to persist across components.

**Comment by eatyourgreens** [comment]
I'm a little confused by the bug report, though. That line toggles gold standard classifications.
https://github.com/zooniverse/Panoptes-Front-End/blob/7eb2125d7f966f87cc84be913d7706975817a5d7/app/redux/ducks/classify.js#L218-L223

**Comment by srallen** [comment]
Whoops! That is a typo. It's line 211, not 221. I should not be lazy and use the permalinks. This is what the stack trace was leading to:

https://github.com/zooniverse/Panoptes-Front-End/blob/8094513fa05210c331b4d55d5008e0366764d244/app/redux/ducks/classify.js#L209-L213

Being called from line 23 here:

https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/classifier/tasks/drawing/hide-previous-marks-toggle.jsx#L19-L24

It's throwing because `classification` is undefined?

**Comment by eatyourgreens** [comment]
Probably. I guess that's preserving the component state when you leave the classifier and come back, but logging out (I assume) clears the classification anyway.

From what I remember, Hide Previous Marks preserves state between the subject viewer and the task components by saving its current state on the classification. I think that dates back to when the classification was a global var on the window object, so it was used as a permanent store.
