### ISSUE TITLE
Workflow selection can select workflows twice on error

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5165]
https://github.com/zooniverse/Panoptes-Front-End/blob/8094513fa05210c331b4d55d5008e0366764d244/app/pages/project/workflow-selection.jsx#L94-L110
Workflow selection catches 404 errors from Panoptes, clears inactive workflows and runs selection again. Once the catch block has run, the following `then` block is run with the workflow undefined (since the catch block doesn't return anything.) If the passed workflow is undefined, the `then` block also clears inactive workflows and runs selection again.
https://github.com/zooniverse/Panoptes-Front-End/blob/8094513fa05210c331b4d55d5008e0366764d244/app/pages/project/workflow-selection.jsx#L113-L136

This could lead to a situation, as we've seen recently, where two different workflows are requested almost simultaneously, leading to problems.

In practice, I don't think the first catch block ever runs since we can't get a 404 error from a valid workflow, and `isValidWorkflow` must be true before we make the API request.

However, I think this code is confusing and easy to misunderstand, and should be fixed at some point.

**Comment by srallen** [comment]
I think this was necessary at one point, but became cruft when id validation code was added before the request is made.

**Comment by eatyourgreens** [comment]
If this is removed completely, then inactive workflows won't reset preferences at all.

**Comment by srallen** [comment]
Sorry, I meant the first catch block is cruft because there's now validation happening before the request is being made.

**Comment by eatyourgreens** [comment]
I guess we want to catch errors in case Panoptes is down, or something else happens. Looking at the code again, if the workflow is valid but Panoptes is down, then the request will error, the catch block will run and set an error in component state, then the next then block will run with workflow undefined and prefs will be reset even though they are valid. I think that could be a bug. Moving the catch block might fix that, or maybe reworking the if block. I'm not sure.

**Comment by srallen** [comment]
It could have more precise handling and check for specific http error codes. >=500 could just display an error message and not attempt again. >=400 could clear prefs and attempt again.

**Comment by eatyourgreens** [comment]
True, but the second then block won't have the error status, since the error's been handled at that point, so the case where the error has been caught but there's no workflow maybe needs thought.

Maybe the logic should be if there's a valid workflow then make a request and catch errors, else reset prefs and retry, rather than `Promise.resolve(null)` for invalid workflows.

**Comment by eatyourgreens** [comment]
I've been thinking about this a bit to try and get the promise chain right in #5124, so that it can also be used by workflow selection, but I'm not confident that I understand what the workflow selection code is doing when I read through it.

**Comment by eatyourgreens** [comment]
I've accidentally deleted `preferences.settings.workflow_id` for Gravity Spy and now find I'm stuck on level 1. It's possible to pass an active workflow ID to `clearInactiveWorkflow` here and delete that preference, since it clears any matching workflow ID without checking if it's inactive.
https://github.com/zooniverse/Panoptes-Front-End/blob/8094513fa05210c331b4d55d5008e0366764d244/app/pages/project/workflow-selection.jsx#L161-L175

I think this would be a rare(?) bug, but it would happen in the case where `isValidWorkflow` is true but `workflow` is undefined. Maybe for API errors where the status is something other than 404.

Based on my experience, the symptoms would be volunteers finding themselves stuck on level 1 and unable to advance to level 2. They' would probably have seen the promotion dialog, but when they clicked it to advance, a server error caused PFE to delete the project set workflow by mistake.
