### ISSUE TITLE
Several clicks of 'take me to new workflow' to close modal

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#5188]
## Expected behavior
Clicking 'take me to new workflow' should only be needed once. It should load the workflow that is stored in `settings.workflow_id` in the user's project preferences.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
If I'm classifying on level 1, clear the subject queue, and get prompted to try the level I'm promoted to, then it takes several clicks of 'take me to the new workflow' to get the modal to clear. The classifier appears to be loading slowly behind the modal. The only issue in the console I see is:

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.`

Which traces to: 
https://github.com/zooniverse/Panoptes-Front-End/blob/860e7624fb19c711dcd47d0bbbea490b8ce3164a/app/components/subject-viewer.cjsx#L229

And it's not being properly cleared on timeout. 

I'm also seeing the modal open several times, so it's not the same modal that I'm clicking to proceed on multiple times:

![screen shot 2019-01-07 at 11 24 08 am](https://user-images.githubusercontent.com/5016731/50783067-6237ba80-126f-11e9-977c-196d736ff362.png)

I didn't see this in previous testing of the recent changes to workflow selection, so I'm not sure why this has started up. 

## Steps to replicate
Using Gravity Spy to test: https://master.pfe-preview.zooniverse.org/projects/zooniverse/gravity-spy?env=production with a user that is promoted.

Or my test project: 
https://master.pfe-preview.zooniverse.org/projects/srallen086/workflow-assignment-testing
Start with the beginner workflow and promote your user to workflow id `2334` (journey) and when the subject queue is next clear while classifying on the beginner workflow, you'll be prompted to try the new workflow. 

## Additional information

- **Operating system:**
- **Browser:**

**Comment by eatyourgreens** [comment]
Workflow assignment is checked on every component props/state change, if there's a user logged in.
https://github.com/zooniverse/Panoptes-Front-End/blob/45ad6c8e0eca74da5eb927bf365f70b10b6addad/app/pages/project/classify.jsx#L85-L87

I guess that could lead to multiple prompts opening. Should it be reacting to preference changes instead?

**Comment by srallen** [comment]
Yeah, it might be evaluating true to display multiple times in the lifecycle. I'm just surprised it wasn't happening when this initial change happened, so I'm suspecting something more might be at play here.

**Comment by eatyourgreens** [comment]
I guess `componentDidUpdate` should check that `preferences.settings.workflow_id` has changed, or that `state.promptWorkflowAssignmentDialog` is false, before running `shouldWorkflowAssignmentPrompt`.

I can't remember, but maybe it was triggered by `componentWillReceiveProps` before, so wouldn't run on state change. At the moment, I think it might run more than once if component updates happen while the API request is still loading. In which case, I'd expect to see that happen when Panoptes is being slow.

**Comment by eatyourgreens** [comment]
#5186 changes the redux action so that the classifier state, and associated props, only changes after the workflow API request completes. That might help stop `componentDidUpdate` running while we're still waiting for a workflow to load.

**Comment by srallen** [comment]
Yes, it used to be triggered in `componentWillReceiveProps`. I'll take a look at #5186 today.
