### ISSUE TITLE
Option to auto-generate simple manifest file?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#519]
It occurred to me that having to generate a CSV file could be a real barrier for some users of the project builder - especially when we consider classroom usage... I realise this is a "nice to have", but why don't we add a check box "generate manifest automatically" which would create a simple one-column CSV with the filenames only, as uploaded?

**Comment by aliburchard** [comment]
Something like this would be great. I've already received numerous comments from other researchers that generating a list of filenames is prohibitive for a lot of folks. An alternative (perhaps stopgap) would be to provide researchers with links to instructions on how to do this from the command line. When I was first getting started working in terminal, that would have been the jump-start (and confidence-builder) I needed to start learning this stuff.

**Comment by mkosmala** [comment]
Adding my two cents here. I was about to open an issue called "manifests shouldn't be required". Especially when people are just trying out the project builder, there's no need to require a text file. @alexbfree has it exactly right: allow people to upload pictures and auto-create a manifest with just the file name.
