### ISSUE TITLE
Adding 'questions.csv' to survey task fails

### ISSUE THREAD

**Issue by marco-willi** [zooniverse/Panoptes-Front-End#5208]
## Expected behavior

Accepting 'questions.csv' in project builder when adding the required csv files to the 'Data' box for a survey task. 

![image](https://user-images.githubusercontent.com/19252323/51419765-ade14280-1b52-11e9-913b-08a10ebafae5.png)

## Current behavior

After uploading the 'questions.csv' using the button 'Add questions' there are several error messages, depending on how many questions there are (it seems there is one pair of error messages for each question). For the official 'questions.csv' provided by Zooniverse there are the following errors: 

![image](https://user-images.githubusercontent.com/19252323/51419773-bd608b80-1b52-11e9-8590-070a4fbd6b03.png)

I have observed that for a file with one question the number of possible "Answers" influences whether the file is accepted or not.

This file works:
```
Question,Multiple,Required,Answers,Include,Exclude
How many?,N,Y,1;2;3;4;5;6,,Nothing
```

This file fails:
```
Question,Multiple,Required,Answers,Include,Exclude
How many?,N,Y,1;2;3;4;5;6;7,,Nothing
```
## Steps to replicate

1. Create a new workflow
2. Add a survey task
3. Download Zooniverse sample data [Zooniverse_Sample_Data_GD](https://drive.google.com/drive/u/1/folders/0BxNFAhD71pdXUUg2bUVlRVpMUG8)
4. Add the official files for choices, characteristics, confused pairs, and questions to the task
5. Error message

[Example workflow](https://www.zooniverse.org/lab/5124/workflows/8701)

## Additional information

- **Operating system:** Windows
- **Browser:** Opera / IE (I think)

**Comment by marco-willi** [comment]
Hi @srallen, Just wanted to ask what the timeline for resolving this bug (if indeed a bug and no user error) might be? It would be good to have a rough estimate (days, weeks, months) in order to plan the release of our new Snapshot Safari projects. Since we currently are unable to create new survey-tasks this issue prevents us from moving forward. Thanks a lot for your help!

**Comment by srallen** [comment]
@marco-willi I'll take a closer look today. Hopefully it is a straight forward and quick fix, but once I determine exactly what the issue is, I can better respond about a time estimate.

**Comment by srallen** [comment]
@marco-willi the fix is now deployed. Thanks for letting us know about it

**Comment by marco-willi** [comment]
@srallen Fantastic! Thanks a lot for the quick fix.
