### ISSUE TITLE
handling markings in multiple frames

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes-Front-End#521]
a marking JSON object lists the frame that the marking was made. However, in Ali's project (http://preview.zooniverse.org/panoptes/#/projects/aliburchard/wildebeest-watch/classify?workflow=6) a marking made in one frame automatically shows up in an other. If this is going to always be the case that I won't worry about the frame id when clustering markings. I think this is the best way of handling and don't even know if Panoptes allows for independent marking between frames. Any objections?

**Comment by aliburchard** [comment]
I think this is fine for now. I think that allowing different marks for different frames would be really cool and enable some really cool science -- but is definitely not something in scope right now (as far as I'm aware). I think for now, marks in multiple frames can just ignore the frame. 

FWIW, the only reason I use the marking tools is to get the count of wildebeest in each direction -- I don't actually care where the points are. There's just essentially no other way to ask "multiple questions" in the interface at the moment.

**Comment by srallen** [comment]
Not sure if this is still applicable, but closing since it's so old.
