### ISSUE TITLE
Responsiveness issues

### ISSUE THREAD

**Issue by lancesnider** [zooniverse/Panoptes-Front-End#5225]
I did a little survey of site responsiveness and here are the issues I've found. 

- [ ] Hamburger menu gets cut off
- [ ] The `Discover, teach, learn` block image isn't right aligned
- [ ] ~~Footer columns alignment~~ This one's getting handled in Monorepo
- [x] `hero-nav` menus broken https://github.com/zooniverse/Panoptes-Front-End/pull/5233
- [ ] Collections hero nav is Coffescript and broken
- [ ] Publications tags lose their order
- [ ] Publications margin
- [ ] Zooniverse talk items get cut off

## Hamburger menu gets cut off

https://www.zooniverse.org/

Chrome on Android

When you click the hamburger menu, half the menu is off the screen. You can scroll to the right to see it. 

<img src="https://user-images.githubusercontent.com/3202211/51685743-01251c00-1fbd-11e9-8a60-2efce8a75256.png" width="200"/>
<img src="https://user-images.githubusercontent.com/3202211/51685493-69bfc900-1fbc-11e9-8702-b556a7041ce3.png" width="200"/>

## The `Discover, teach, learn` block image isn't right aligned

https://www.zooniverse.org/

At certain sizes the image goes to the second line, but doesn't butt up to the right of the screen, making it look broken. 
<img width="371" alt="screen shot 2019-01-24 at 9 48 22 am" src="https://user-images.githubusercontent.com/3202211/51685920-5a8d4b00-1fbd-11e9-9d5d-2680de419bf6.png">

## Footer columns and alignment

https://www.zooniverse.org/

On mobile the footer goes from 3 to 2 columns, but rather than splitting the items evenly, the 3rd column just bumps to its own row. The social links should also align with something. 

<img width="238" alt="screen shot 2019-01-24 at 9 50 28 am" src="https://user-images.githubusercontent.com/3202211/51686000-80b2eb00-1fbd-11e9-8f51-a3534eba6e03.png">

## `About` submenu breaks on mobile

https://www.zooniverse.org/about

On small screens the submenu goes to 2 lines breaking the `Our team` link into 2 lines. 

<img width="265" alt="screen shot 2019-01-24 at 9 52 23 am" src="https://user-images.githubusercontent.com/3202211/51686140-cec7ee80-1fbd-11e9-9e70-46f5b5a816e5.png">

## `Get involved` submenu breaks on mobile

You have the same issue on this submenu: https://www.zooniverse.org/get-involved/education

<img width="267" alt="screen shot 2019-01-24 at 9 59 02 am" src="https://user-images.githubusercontent.com/3202211/51686653-c15f3400-1fbe-11e9-8912-6ff130393e47.png">

## Publications tags lose their order

https://www.zooniverse.org/about/publications

At 400px the tags stop being listed as a column

 
![screen capture on 2019-01-24 at 10-00-40](https://user-images.githubusercontent.com/3202211/51686799-1438eb80-1fbf-11e9-8a64-e453f324e65a.gif)

## Publications margin

https://www.zooniverse.org/about/publications

This is a pretty minor thing, but the left margin is much smaller than the right: 

<img width="200" alt="screen shot 2019-01-24 at 9 54 55 am" src="https://user-images.githubusercontent.com/3202211/51686334-33834900-1fbe-11e9-8c7a-544c5a667979.png">

## Zooniverse talk items get cut off

https://www.zooniverse.org/talk

The right column gets cut off and each item ends up with a horizontal scroll

<img width="216" alt="screen shot 2019-01-24 at 9 57 59 am" src="https://user-images.githubusercontent.com/3202211/51686541-8ceb7800-1fbe-11e9-9215-d7a0cccf6648.png">

**Comment by eatyourgreens** [comment]
The social media icons in the footer aren't announce by VoiceOver, either.

**Comment by srallen** [comment]
We could replace it with the footer in the shared components library once we publish that.

**Comment by lancesnider** [comment]
Unless there are objections, I'm going to kick off fixing the submenus in the 5 places where `hero-nav` shows up.

**Comment by srallen** [comment]
@lancesnider Thank you for your contributions. We definitely appreciate any fixes contributed. We're currently in the middle of breaking this main monolith app apart into smaller libraries and apps (see [zooniverse/front-end-monorepo)](https://github.com/zooniverse/front-end-monorepo/) so some components like the footer will be replaced soon by a rewritten one that should have better responsiveness. However, not everything will be replaced in one go. In general, I'd suggest to ask in the issue if something is still needed before committing a fix, as you've done here, since we might be already working on a solution in the other repository.

Thanks, again!

**Comment by lancesnider** [comment]
That's great to hear that this is getting broken into smaller bits! I'll close that PR and be sure to make an issue first. :)

**Comment by lancesnider** [comment]
@srallen Want me to try to fix the main nav that's getting cut off on Android Chrome?

**Comment by srallen** [comment]
@lancesnider We're working on a redo of the main header in our monorepo as well. Maybe the Talk issue? Though that's also gonna be in coffeescript. We have a few other help-wanted labeled issues that have opened up in the past few days that could be resolved. Thanks!
