### ISSUE TITLE
Transfer project ownership - how to handle redirects?

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#5230]
We've got a request to transfer the ownership of a launched project. When we transfer ownership we change the URL the project is available on and break the old links. 

We can handle redirect requests of full page requests at the nginx layer which is fine. I assume old talk links in comments will cause a full page refresh. Do we allow relative links in markdown? Will PFE have any old internal links that will need custom react router support? If so what's the best way of supporting these?

**Comment by eatyourgreens** [comment]
Links on Talk don't refresh the page if the link origin is the same as the window origin.
https://github.com/zooniverse/Panoptes-Front-End/blob/6efe226301a0857d8e22f878ff6c1e8785b10047/app/components/wrapped-markdown.jsx#L17-L25

**Comment by marten** [comment]
Why would an old talk link cause a full page refresh? Doesn't the frontend router just handle anything on zooniverse.org clientside?

**Comment by camallen** [comment]
So they looks like this will have to be internally handled in the router? 

> If so what's the best way of supporting these?

Any ideas on how to support this?

**Comment by eatyourgreens** [comment]
Talk links don't use the router, though. They're just HTML links rendered from Markdown. 🤔 

The redirect might have to be handled in that code snippet I posted above, where same-origin links are interrupted and cancelled.

**Comment by eatyourgreens** [comment]
Anything else is rendered dynamically from the project slug, no? So will change when the project slug in the database updates. Markdown content's the only place where we store the link destination in a string.

**Comment by camallen** [comment]
> Anything else is rendered dynamically from the project slug, no?

My understanding is yes but i was asking for clarity from more sources before assuming it'll work properly.

So adding a function to that either injects the redirect path or leaves the link as a full page refresh to the `wrapped-markdown.jsx` component should enable us to transfer ownership correctly.

**Comment by eatyourgreens** [comment]
I think scrap that `WrappedMarkdown` component rather than make it more complex, and potentially introduce another bug into the handling of Talk links. All links from Talk would then be HTML links, firing off GET requests that could be redirected on the server.

**Comment by camallen** [comment]
that sounds like a reasonable and sensible solution 🎉  it also simplifies recording and configuring an automatic ownership redirection system long term. Thanks for the help and advice on this.

**Comment by eatyourgreens** [comment]
The only downside I can think of is logging you back in (and resetting the Redux store) when you follow any links from Talk eg. if I link from one comment to another comment or discussion on the same project. It might not be a big deal but would need checking.

**Comment by eatyourgreens** [comment]
Classifications in progress, pending interventions, feedback and locale I think. Eg. resetting the language back to English on refresh would happen for projects that use multiple languages. There's a query parameter that can fix that, but it would need to be added to links in the code.

**Comment by marten** [comment]
That sounds okay to me. If we want to keep any of those, we should really be keeping them in localstorage instead so that they also persist across reloads or "open-in-new-tab"s etc.

**Comment by eatyourgreens** [comment]
There might be increased API traffic if the project hits `subjects/queued` on each page load. We usually advise people to refresh the classifier in order to clear seen subjects, but that request might happen on any project page load. I'm not sure.

**Comment by eatyourgreens** [comment]
Losing incomplete classifications is probably the only blocker to removing that `WrappedMarkdown` component from Talk. We can't waste volunteers' time by throwing their annotations away when they click a link.

I'd vote against naively persisting classifier state to local storage for two reasons:
 - it persists the classification and workflow across tabs, causing problems if you try to open two projects in different tabs.
 - it prevents you from requesting a new subject by reloading the page.
