### ISSUE TITLE
Remove 'Gill Sans' and 'Open Sans' from font list

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#5237]
https://github.com/zooniverse/Panoptes-Front-End/blob/5f3109368ccdb5604c05880a801a9c411cc95ec4/css/typography.styl#L1-L3

These aren't needed – only Karla and Arial.

**Comment by eatyourgreens** [comment]
A quick search in Github found this line too, although it doesn't look like a valid font declaration anyway (values aren't quoted.)
https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/css/secondary-page.styl#L68-L69

**Comment by beckyrother** [comment]
Yuck! Can those be removed as well and changed to "Karla" just in case?

**Comment by eatyourgreens** [comment]
Are we using Oswald? It's downloaded every time you visit the site.
https://github.com/zooniverse/Panoptes-Front-End/blob/229d11d73a973a9e2279a36bb0c16db5016a23ae/views/index.ejs#L7-L10

**Comment by srallen** [comment]
Oswald appears to be used in some of the home page css, whether it's _actually_ used, I don't know.

**Comment by beckyrother** [comment]
Yes, Oswald is used on both the logged in and not-logged-in versions of the home page – it's the taller sans-serif labels for 'featured project' and 'welcome to the zooniverse'
