### ISSUE TITLE
Infinite loop in SizeMe crashes classify page

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5239]
Reported on Talk: https://www.zooniverse.org/talk/17/867156?comment=1437667

A volunteer is unable to classify on Cedar Creek Eyes on the Wild because the classify page crashes PFE, but only when they are logged in. The full error is [maximum update depth exceeded](https://reactjs.org/docs/error-decoder.html/?invariant=185) in SizeMe, which would point to an infinite loop constantly attempting to set state.

**Comment by srallen** [comment]
I think this was closed by #5240?

**Comment by eatyourgreens** [comment]
Still happening, but the error boundary in the project page container (#5235) catches it and at least allows the classifier to render. https://www.zooniverse.org/talk/17/867156?comment=1438739

**Comment by eatyourgreens** [comment]
If the cause of this is that the project nav is re-rendering, causing SizeMe to re-render, which then causes the nav to re-render etc. then using [`React.PureComponent`](https://reactjs.org/docs/react-api.html#reactpurecomponent) instead of `React.Component` might fix it.
