### ISSUE TITLE
Change data export download link

### ISSUE THREAD

**Issue by adammcmaster** [zooniverse/Panoptes-Front-End#5241]
It's not obvious to people that the timestamp is a link to download the latest export. The link should be reworded.

**Comment by camallen** [comment]
I think this is the relevant location in the code, basically change the timestamp to have a better prefix or name completely. https://github.com/zooniverse/Panoptes-Front-End/blob/75aa496698e41246203646b22b9b9d0e02d5845f/app/partials/data-export-button.cjsx#L57
