### ISSUE TITLE
Update Open Graph Metadata Tags for Social Media Linking+Sharing

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Panoptes-Front-End#5249]
The template HTML for Panoptes projects constructed with the Project Builder all use the same general Zooniverse Open Graph (og) tags that are used by Facebook and Twitter to construct nice looking images+links on their timelines / feeds.

## Current behavior

The default Zooniverse values for these tags are pretty uninteresting, leading to non-specific visuals for links to projects (here, for [Local Group Cluster Search](https://www.zooniverse.org/projects/lcjohnso/local-group-cluster-search)):

`<meta property="og:type" content="website" />
<meta property="og:title" content="Zooniverse" />
<meta property="og:description" content="The Zooniverse is the world’s largest and most popular platform for people-powered research." />`
 
<img width="604" alt="twittercard_old" src="https://user-images.githubusercontent.com/2006101/52231790-737ce280-2880-11e9-9765-2fbc0d263600.png">

## Proposed behavior

Project-specific Customized tags: 
1. og:title = Project Name
2. og:description = Project Description
3. og:image = Project Avatar
4. Optional -- og:image:width & og:image:height = sensible size for avatar (200x200)

Here's an example created automatically by WordPress for a Planet Four blog post, but the specifics here are just used to show an example of an attractive card: 
`<meta property="og:title" content="6 Earth Years of Planet Four" /><meta property="og:description" content="Happy Birthday Planet Four. This month marks 6 years of Planet Four. We couldn&#8217;t do any of this without the Planet Four volunteer community.  Thank you for all of your help and contributions.…" /><meta property="og:image" content="http://1.gravatar.com/blavatar/37f000fbf9d4d38c9fb242a24af25556?s=200&amp;ts=1549308161" /><meta property="og:image:width" content="200" /><meta property="og:image:height" content="200" />`

<img width="617" alt="twittercard_blog" src="https://user-images.githubusercontent.com/2006101/52232435-239f1b00-2882-11e9-916c-8a84daa44fb4.png">

### Relevant Links
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup
https://developers.facebook.com/docs/sharing/webmasters/

**Comment by eatyourgreens** [comment]
Hi Cliff, there’s only one page for the Zooniverse site, hence the generic metadata. The projects are generated by JavaScript in the browser, rather than having their own pages.

**Comment by lcjohnso** [comment]
Bummer.  Fair enough -- I'll go ahead and close.

**Comment by camallen** [comment]
@lcjohnso letting you know that this should be helped by the new site / classifier rebuild as we can generate custom page for each project. Feel free to post the issue on that repo https://github.com/zooniverse/front-end-monorepo

**Comment by lcjohnso** [comment]
Will do -- thanks @camallen !

**Comment by lcjohnso** [comment]
Note: this enhancement is added to the rewrite front-end-monorepo in Issue https://github.com/zooniverse/front-end-monorepo/issues/425 and PR https://github.com/zooniverse/front-end-monorepo/pull/467

I've submitted PR https://github.com/zooniverse/Panoptes-Front-End/pull/5425 to partially address this in PFE by adding a logo to the existing Zooniverse-wide card.
