### ISSUE TITLE
Various ZooHome css tweaks

### ISSUE THREAD

**Issue by heathv** [zooniverse/Panoptes-Front-End#526]
#### Nav bar
- [ ] More evident once you scroll down, but everything in the nav bar container needs to a bump vertically about 5px 

#### Hero
- [ ] Remove the letter-spacing from the "People-Powered Research" line
- [ ] Add a pixel or two to the line-height on that paragraph below said line
- [ ] That whole block needs to be *optically*-centered vertically. Basically just moved vertical about 100px

#### Blurbs n Such
- [ ] for the alternating zebra stripe color use #E8E8E8
- [ ] Add some extra padding to the top of the "Get Started on a project!" section

**Comment by srallen** [comment]
@heathv, whenever you have a chance, could you send me updated gifs with the new zebra stripe background color when you have a chance? Thanks!

**Comment by heathv** [comment]
@srallen sent!
