### ISSUE TITLE
is there a way to play videos from the project inline like the youtube videos do?

### ISSUE THREAD

**Issue by mimiarandjelovic** [zooniverse/Panoptes-Front-End#5267]
## Expected behavior
For youtube videos, when linked a video player shows up in the discussion so you can watch the video but this doesn't seem to happen for other videos. What we would like is that a video player shows up in subject discussion when a video is linked from within the project - this works for the first subject video (that's automatically created) but not subsequent videos

## Current behavior
when you try to link to a video from within the project all that comes up is a link to the video but no video player
but the youtube videos play inline nicely
eg:
@ [ youtube ] ( https://www.youtube.com/watch?v=cjC94EhAs00 ) - turns into a nice video in the subject discussion
@ [ 29669563 ] ( https://www.zooniverse.org/projects/sassydumbledore/miniproject-chimp-id-validation/talk/2201/880034 ) - just turns into hyperlinked @29669563
![image](https://user-images.githubusercontent.com/17277871/52429695-dda5b980-2b04-11e9-8870-3165370e53d4.png)

## Additional information
We basically are trying to figure out how to replicate these lists we curate on chimpandsee on the old   ##platform that we use for chimpanzee identification eg: https://talk.chimpandsee.org/#/boards/BCP000000v/discussions/DCP0001vsz

we were thinking that if the videos can be embedded in the lists then maybe we can avoid getting the image stills and using those as we had done in the past.

Many thanks.

- **Operating system: Windows 10 enterprise**
- **Browser: Google Chrome Version 59.0.3071.86 (Official Build) (64-bit)**

**Comment by eatyourgreens** [comment]
Talk does allow subjects to be embedded in posts, but there are no clear instructions as to how to do it. I've replied on the linked Talk discussion with an example. It took me some trial-and-error to figure out how it works, though.
