### ISSUE TITLE
Recent classification video thumbnail fail

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#5269]
## Expected behavior
The Recent page should show my latest classifications done in the project together with image/video thumbnails.
The video thumbnails are supposed to be playable on the Recents page, and they should display the speed option buttons.

## Current behavior
Here's a screenshot of what I get on the new C&S we're just 'building' where we classify videos:
https://panoptes-uploads.zooniverse.org/production/project_attached_image/f9b5b3cc-2222-4d10-8d80-02bfdf815b9b.png
The only thumbnail I see is an older classification. The others that failed loading come from today.
All four video files are m4a file types despite of the 'unknown file type' label over the three of them.
I have no troubles displaying my Recents on Battling Birds (video ones) or in other projects but here.
Also, you can notice the only loaded thumbnail in my screenshot is displayed as an image and not as a video thumbnail. Why is that so?
This is what my Recents look like on Battling birds:
https://panoptes-uploads.zooniverse.org/production/project_attached_image/811eb66e-62ba-421b-8567-764512eafd3a.png
These are playable videos - you can even choose what speed to play it with (out of the box though).

- **Operating system:**  Ubuntu
- **Browser:** Chromium 71

**Comment by eatyourgreens** [comment]
Hi @yshish do you have links to those subjects, so that we can take a look?

**Comment by yshish** [comment]
Hi @eatyourgreens Do you mean those with 'unknown file type' label? Yes, here they are:

https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see-updated/talk/subjects/28297112
https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see-updated/talk/subjects/28297087
https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see-updated/talk/subjects/28297103

**Comment by eatyourgreens** [comment]
Thanks! I can see the video on the subject pages but I don't see thumbnails for those subjects either. Eg. neither of the subjects here shows a thumbnail for me (Chrome on MacOS Mojave): https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see-updated/talk/tags/human

**Comment by eatyourgreens** [comment]
The videos are `.m4v` files but I think our code might expect `.mp4`. That could be the problem.

**Comment by yshish** [comment]
OK. But m4v is a supported file type so it shouldn't make problems. 

The project lab says: "You can add files here to use in your project’s content. ... Files can be any of: .jpg, .jpeg, .png, .gif, .svg, .mp3, .mp4, .m4v"

**Comment by eatyourgreens** [comment]
Looking through the code, it seems to specify `mp4`. 😞 
https://github.com/zooniverse/Panoptes-Front-End/search?q=mp4&unscoped_q=mp4

**Comment by yshish** [comment]
When I click on one of those subject and look at the metadata, it shows the file name as: "pinkswamp_C4_pinkswamp_vid13_509982_690650_20140505_PICT0003_30.m4a" 

m4a x m4v - isn't that a problem?

**Comment by yshish** [comment]
And it is not only a problem of the Recent classifications. We don't see any vid. thumbnails on the Talk. Here is what the search results look like: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see-updated/talk/tags/human

**Comment by eatyourgreens** [comment]
That's the same link I posted?

**Comment by eatyourgreens** [comment]
Videos don't show up on the project home page either (in the '2 people are talking…' box.)
https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see-updated

This is fixable, but not by me right now I'm afraid. It requires going through the code and changing all those bits that specifically refer to `mp4`. 😳

**Comment by eatyourgreens** [comment]
I've made a start on this in #5270 but probably don't have time to do much more at the moment.

**Comment by yshish** [comment]
> That's the same link I posted?

Oh, yes, the same. Sorry, I missed that comment somehow.

> This is fixable, but not by me right now I'm afraid. It requires going through the code and changing all those bits that specifically refer to `mp4`.

NP. Thanks a lot for looking at this! Let's hope it won't ruin our plans much. ;)

**Comment by eatyourgreens** [comment]
Do take a look at the preview link I posted on #5270: https://github.com/zooniverse/Panoptes-Front-End/pull/5270#issuecomment-462735043

I don't think that catches every place that we display video, but it might be enough to fix video for Talk, Recents and the project home page.

**Comment by yshish** [comment]
Cool. Thanks, it seems good.
 
I tried to display my Recent classifications under that link, and all but one thumbnails were displayed correctly. The last one still shows the 'Unknown file type' label (this one: https://pr-5270.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see-updated/talk/subjects/29410905 )

It doesn't let me see it anymore, saying I don't have a permission (and it doesn't accept my login).

**Comment by eatyourgreens** [comment]
Hmmm. Here's the full link for that subject on the staging server. https://pr-5270.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see-updated/talk/subjects/29410905?env=production

I see that @trouille is the contact on Talk. If this requires more in-depth work, then I'd recommend asking her if she can find someone to work on it.

**Comment by eatyourgreens** [comment]
Here's what I see on the Recents page.
![Screenshot of the Recents page showing 3 video subjects.](https://user-images.githubusercontent.com/59547/52638784-9d5e8680-2eca-11e9-934f-11f1046ac93c.png)

**Comment by yshish** [comment]
Here's mine 
![screenshot_2019-02-12_14-39-57_preview](https://user-images.githubusercontent.com/7211888/52639298-3b0a8380-2ed4-11e9-9461-fc5adafb26aa.png)

Thanks!

**Comment by trouille** [comment]
@yshish Are you creating the subjects or is Colleen? I have an email thread going with Colleen and Mimi about subject upload, etc. If it's Colleen, can I continue the conversation in that email thread and add you to see if Colleen can update to creating mp4 format files instead? Thanks!

**Comment by yshish** [comment]
@trouille Colleen is most likely the one creating subjects. Please, continue the conversation with her and Mimi. I have just noticed the videos don't show up properly and started the issue here. Not sure Colleen has read my message already. Thanks!
