### ISSUE TITLE
Error adding roles to project

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#527]
Simone added me as a collaborator and then got an error message saying 'not allowed to create this role' or something like that. When we refreshed I did show up as a collaborator but this isn't intuitive.

![](https://s3.amazonaws.com/uploads.hipchat.com/41383/2199940/pTGpMLygcFQiDGy/Screen%20Shot%202015-06-11%20at%2010.10.50.png)

**Comment by edpaget** [comment]
Yeah this is due to talk not being available on the preview.zooniverse.org version of the site yet.

**Comment by mschwamb** [comment]
In case this is helpful - Looks like Talk is available on the preview site  (maybe without comment feature live yet?), and I got the same error/behavior adding Cam as a collaborator to the project. It spat out the error message as above but did add Cam after I did a browser refresh his username showed up on the collaborators list.

**Comment by edpaget** [comment]
This is fixed now.

**Comment by karenlmasters** [comment]
Huh - I've been seeing this behaviour today adding collaborators to "Galaxy Zoo for Schools Outreach".

**Comment by edpaget** [comment]
On the preview.zooniverse.org site? Did you create the project recently?
