### ISSUE TITLE
Interventions subject metadata is visible in UI

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#5277]
https://github.com/zooniverse/Panoptes-Front-End/blob/adebee3e88554afe006cf329f522ff6da6d7078b/app/redux/ducks/interventions.js#L57

Playing around with subject task allocation interventions and I'm wondering why we add the visible `intervention: true` metadata field to subjects? 

<img width="812" alt="screenshot 2019-02-18 at 06 03 49" src="https://user-images.githubusercontent.com/295329/52950214-108d5000-3344-11e9-987f-5000e66dfefd.png">

**Comment by eatyourgreens** [comment]
So that researchers can track interventions? https://github.com/zooniverse/Panoptes-Front-End/pull/4797/commits/c03abd2367cb00fe3e8d042e41a1b35e88c493ab

**Comment by camallen** [comment]
I see you are using the subject metadata to proxy the provenance of the subject (intervention vs normal), that seems slightly odd but i can see why.

Should the user see this `intervention: true` in the subject metadata in the UI?

**Comment by eatyourgreens** [comment]
:shrug: I can't remember, to be honest. Do you remember from reviewing this?

**Comment by camallen** [comment]
I missed this in review...I don't think this metadata overloading should be visible in the UI. It should be prefixed '#' to hide this data from UI.

**Comment by eatyourgreens** [comment]
Yeah, but do you remember why that flag is there in the first place? I'd assume it's used by the classification to log that there was an intervention, but I don't see anything that updates classifications for subject interventions.

There is a test that makes sure it's set by interventions. 🤔

**Comment by camallen** [comment]
Isn't the classification metadata updated when submitting a new classification? https://github.com/zooniverse/Panoptes-Front-End/blob/adebee3e88554afe006cf329f522ff6da6d7078b/app/redux/ducks/classify.js#L49

Also should this be a `source: source` key? https://github.com/zooniverse/Panoptes-Front-End/blob/adebee3e88554afe006cf329f522ff6da6d7078b/app/redux/ducks/classify.js#L59

**Comment by eatyourgreens** [comment]
Oh maybe that's it. It's used to record the source the subject was taken from.

Sorry, I don't understand your second question. Are you asking about [ES6 property shorthand](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Property_definitions)?

**Comment by eatyourgreens** [comment]
To be honest, after the classification has been updated, the subject metadata key can be deleted as it's not needed any more.

**Comment by camallen** [comment]
> Sorry, I don't understand your second question. Are you asking about ES6 property shorthand

I am, that's nice to know. 

> To be honest, after the classification has been updated, the subject metadata key can be deleted as it's not needed any more.

I think we should not present any extra metadata that might confuse the user.

**Comment by eatyourgreens** [comment]
I haven't looked at the Panoptes JS client in a while but I think `subject.update({ 'metadata.intervention': undefined })` will delete that flag.

**Comment by eatyourgreens** [comment]
Noting for posterity that the `subject.metadata.intervention` flag is there so that PFE can record the source of each subject when it pops a subject off the queue and creates a new classification.
