### ISSUE TITLE
Auto-suggest of names in roles is buggy

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#528]
When you select a name in the drop down the suggestions don't disappear right away if you're using a mouse. So the list then obscures the roles.

**Comment by edpaget** [comment]
So the user search lets you select mutliple people, so I'm not sure it's a good idea to defocus it after you select the first name. It should automatically close if you hit 'esc' or click anywhere out side the search box.

**Comment by camallen** [comment]
It loses focus if you use a keyboard to select a user and press enter.

**Comment by eatyourgreens** [comment]
Reopening this since I've reverted react-select to 0.4.9

**Comment by camallen** [comment]
@eatyourgreens i think this was fixed by #1076
