### ISSUE TITLE
Fix multi-image buttons when smaller width

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5286]
Multi-image subjects on small screens have a lot of buttons (and now a slider) which appears quite cluttered on a small screen.

See:
- https://www.zooniverse.org/projects/y-dot-liefting/snapshot-hoge-veluwe/talk/subjects/29834853
- https://www.zooniverse.org/projects/marckuchner/backyard-worlds-planet-9/talk/666/187696

**Comment by eatyourgreens** [comment]
![Screenshot of a Snapshot Karoo subject on a phone, showing the cluttered subject buttons. ](https://user-images.githubusercontent.com/59547/53920344-c2c35800-4064-11e9-9e32-6238f8bcb330.png)
