### ISSUE TITLE
Tutorial text out of sync between project builder form and classify view

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Panoptes-Front-End#5299]
## Expected behavior
The selected tutorial for a workflow should show the text and media on tutorial form page of project builder when the tutorial is display via the classify page.

## Current behavior
There is a mismatch between text shown on tutorial input page and the output shown on classify page (for web interface) during tutorial.  Currently observed for project=8749, workflow=9813, tutorial=2169.

## Additional information
Potentially Relevant Notes: 1) Tutorial media is in sync; only the text is out of sync.  2) This workflow is mobile enabled, and the tutorial is accurately in sync on the app; no issues there and continues to update with further edits. 3) I rearranged the tutorial steps at one point during editing, and that's *possibly* when I lost sync (but not sure).

**Comment by lcjohnso** [comment]
Screenshots

Input:
![tut_input](https://user-images.githubusercontent.com/2006101/54977277-cf9fe100-4f6a-11e9-8624-33b10b77f0cf.png)

Output:
![tut_output](https://user-images.githubusercontent.com/2006101/54977278-cf9fe100-4f6a-11e9-8454-587654d8f16f.png)

**Comment by camallen** [comment]
@lcjohnso this is an API issue - we've had problems syncing the content to the translations system. 

The good news is we've identified the issue and aim to get it fixed by the afternoon GMT. Hopefully you wake up to a fix :)
