### ISSUE TITLE
Annotating marks

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#53]
Will there be the ability to annotate a drawing mark? That is, if a user clicks somewhere on an image, can I then ask a question about that mark?

In particular, we'd like users to be able to do things mark trees in autumn images and then select what color the leaves are (e.g. "yellow", "orange", "red", etc.). 

I realize we could do something like have a tool in the tools array for each option, so it would look like "mark red trees", "mark orange trees", "mark yellow trees", etc. but that might look cumbersome if we have many options.

**Comment by brian-c** [comment]
Implemented. Described in #70, docs to come, example here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/mock-data.coffee#L26-L40
