### ISSUE TITLE
already seen label goes across the subject while classification is not complete 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#530]
On manuscript adventure (http://preview.zooniverse.org/panoptes/#/projects/simoneduca/manuscript-adventure) when I classify during the decision tree it shows the already see label across the image . I don't see this behavior on the whale project or galaxy zoo bars

![screen shot 2015-06-11 at 2 32 37 am](https://cloud.githubusercontent.com/assets/753325/8107109/8dae2aa2-0fe2-11e5-83db-4f12c8067d72.png)

**Comment by camallen** [comment]
@mschwamb this is a feature, we know let the user know that they have previously classified on a subject. The subject set is small in the Manuscript adventure so when you've finished all the subjects for a workflow we return a new set of subjects but mark them as seen.

**Comment by mschwamb** [comment]
Okay. I was aware of that, but in this case I hadn't classified on the project before only 2 images.  It showed up during the classification moved from one step to another, so that's why I mentioned it.

**Comment by camallen** [comment]
Ah sorry. So does the already seen show up after you click "Done" on the transition to the next subject?

**Comment by mschwamb** [comment]
Okay I think I maybe figured it out. It's if I classified in one subject in one of the workflows then  I think when I'm in another workflow it pops up the already classified banner, when in reality i didn't classify that image in that workflow. Not sure if there's a solution for that.

**Comment by brian-c** [comment]
That's probably from the list kept on the front end, which just stores subject IDs after classification. I'll switch it to workflow ID + subject ID.

@camallen does the back end already tracks subjects by workflow?

**Comment by camallen** [comment]
@brian-c yep we track which worklow a user sees the subject for.
