### ISSUE TITLE
Can't enable new translation in the Project Builder

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#5302]
There is a Portuguese translation for this project https://www.zooniverse.org/projects/catedraunesco/plant-letters, however the tick-box to enable it in the 'Translations' tab of the project builder is missing. Perhaps because Portuguese is not set up in PFE yet?

![image](https://user-images.githubusercontent.com/5321335/55171915-2119bd00-5171-11e9-9f6c-2c508f8259a6.png)

**Comment by eatyourgreens** [comment]
Portugese is listed as an available language here.
https://github.com/zooniverse/Panoptes-Front-End/blob/a124018cbbe8589ec8befe67d61b2257b244f250/app/constants/languageMenu.js#L1-L18
