### ISSUE TITLE
Talk url param to start subject video at certain fram

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#5307]
## Expected behavior
To be able to share a subject Talk page link for a video with url params to start the video at a certain frame similar to Youtube functionality.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
We don't currently support this, but it is of interest for the C&S project as they migrate to Panoptes. See: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see-miniproject-draconian-kerfuffle/talk/2254/941361?comment=1566515

**Comment by eatyourgreens** [comment]
Should we move feature requests over to the rewrite? Then support this in the new subject viewer?

**Comment by srallen** [comment]
This is specifically a Talk feature request as we don't need to support this for the classifier subject viewer itself, only the Talk version for the subject Talk page. I don't think we'll be rewriting Talk anytime soon, unfortunately, so it made sense to log the request here.
