### ISSUE TITLE
Make Talk page more visually appealing by adding images, improving layout, etc

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#531]
The current talk page is neat and functional, but quite plain. I know we had feedback in surveys etc that people found the old Talk rather bland - in some ways the new one is even more so. I think we should improve the layout to delineate things in a more interesting way (maybe more colours than just grey?) 
Also including recently classified subject thumbnails, as per the old talk, would go a long way to improving this. Also user avatars on the front page maybe?

**Comment by aweiksnar** [comment]
Going to summon lord @heathv  here

**Comment by chrissnyder** [comment]
Milestoning this as first release as some design work does need to be done. Let's leave the larger discussion of how to make it more engaging til later.

**Comment by alexbfree** [comment]
@chrissnyder Is "first release" milestone corresponding to what we are releasing this week? or is that something later...?

**Comment by DarrenMcRoy** [comment]
I've been ready to warn people that they are looking at, at best, an alpha version of Talk. But anything we can do to make it look less like raw HTML would be hugely appreciated. :-)

**Comment by aweiksnar** [comment]
I'm doing an overhaul of talk css today. It will look much better than it does by the end of the day.

**Comment by alexbfree** [comment]
Hurrah @aweiksnar ! Great to hear!

**Comment by chrissnyder** [comment]
Closed by #788
