### ISSUE TITLE
Text with diacritic marks displays with mixed fonts

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5314]
## Expected behavior
Text should display consistently, regardless of language.

## Current behavior
Some characters with diacritic marks are displayed in Open Sans. This screenshot shows a block of text from Whales as Individuals which is rendered in a mixture of Karla and Open Sans. There is a clear difference in character size between the two fonts.
_Please include any error messages from the browser console and/or screenshots_
![Screenshot showing Whales as Indivduals in Czech, with text displayed in Karla and Open Sans.](https://user-images.githubusercontent.com/59547/55481916-50ba4080-561b-11e9-8ab9-e99e303db074.png)

**Comment by beckyrother** [comment]
@yshish Hi! We've opened this issue after you pointed out that our brand font doesn't include support for diacritics and the fallback is not ideal. We're removing those fallbacks to just use Arial or generic sans-serif; is this more legible? 
![image](https://user-images.githubusercontent.com/1392130/55488709-2e61fc00-55f6-11e9-8c4c-1243658713f3.png)
Karla is the official Zooniverse primary brand font so I'd prefer to not remove it.

**Comment by yshish** [comment]
@beckyrother I'm so sorry I missed your reply completely! Well, the current font with diacritics is not as easily readable especially when the text parts are longer, f.e. "čeština' language here: https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/about/faq (or the content of pages like About, Field Guide, C&S Tutorials of the currently inactive Trotters/Monkey workflows, etc.).

If you want to keep the Karla font for languages using diacritic, people will be able to read the texts but the letters with diacritics will 'catch' their eyes. 

I guess at this time there are not many Czech volunteers, and so this language version will be mainly used by my little students & their parents. But there may be other languages with diacritics I can't speak for.

**Comment by beckyrother** [comment]
Thanks @yshish ! I'll open another issue for those pages. This is really helpful; as a non-Czech speaker I don't often switch to that language option. Thanks for all your help!

**Comment by yshish** [comment]
Letters with diacritics are still not displaying correctly. Please don't close.

**Comment by srallen** [comment]
@yshish Here's the C&S about page that will use Arial instead of Karla when you switch to Czech: https://pr-5575.pfe-preview.zooniverse.org/projects/sassydumbledore/chimp-and-see/about/faq?env=production

Is this better?

**Comment by yshish** [comment]
@srallen yes, Arial works perfect, it supports all the marks we use in Czech.
