### ISSUE TITLE
Make talk more "alive" by showing recent activity, activity of other users

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#532]
Talk is the one place where users can feel part of a community. One way that would really help achieve this is by visualizing (hopefully in a live-update/AJAX way) current user activity, not just on talk, but classifying as well.

e.g. look at [Heimdall](http://heimdall.zooniverse.org/) for inspiration, or externally, look at Facebook or Spotify, each of which have a feed of recent user activity.

One idea would be to flash up a box when something interesting happens - a subject is fully classified and retired, an interesting animal/galaxy/etc is found, a new question is asked, a subject is favourited. The box should have a link to a subject and/or user as well so that the user can explore. 

At the least, we should show recently commented-upon subjects by other users, as old Talk does.

A technique like this could also encourage engagement by making the user feel part of something - tell them how many other users are working on their project (if it's a big number) - or across Zooniverse. 
Something like the classification/active users counters as seen on Snapshot Supernova, would be awesome.

**Comment by srallen** [comment]
@alexbfree, I believe the user profile is intended to have a public facing activity feed. A feed component may be a good candidate for a reusable component.
