### ISSUE TITLE
"Cannot read property 'label' of undefined"

### ISSUE THREAD

**Issue by VVH** [zooniverse/Panoptes-Front-End#5327]
Classifying on https://www.zooniverse.org/projects/shuebner729/snapshot-madikwe, chose Wildebeest for classification and then saw this error message: 

There was an error retrieving project shuebner729/snapshot-madikwe.

Cannot read property 'label' of undefined

    in t
    in div
    in t
    in l
    in Connect(l)
    in div
    in div
    in t
    in div
    in t
    in styled.div
    in t
    in div
    in t
    in Connect(t)
    in div
    in ClassifierWrapper
    in Connect(ClassifierWrapper)
    in div
    in t
    in Connect(t)
    in n
    in Connect(n)
    in Unknown
    in div
    in t
    in l
    in Connect(l)
    in div
    in t
    in Connect(t)
    in div
    in div
    in div
    in Unknown
    in div
    in PanoptesApp
    in RouterContext
    in t
    in Router
    in o

**Comment by eatyourgreens** [comment]
Probably a misspelt animal name in the survey task somewhere, but it looks like the project owners fixed it over the weekend.
