### ISSUE TITLE
Multiple slider sub-tasks don't maintain set ranges

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5328]
## Expected behavior
Slider subtasks maintain set ranges.

## Current behavior
per https://www.zooniverse.org/talk/18/963488?comment=1591397:
"I'm trying to add multiple sliders as sub-tasks to a main workflow task so volunteers can enter a date value. However, changes made to the parameters of one slider affect all the others. So, for example, I set the first slider up as running from 0-31 in steps of 1 (0 to account for no day value) for the day slider. Then I add another slider to capture month, change the parameters to 0-12, but then the first slider also gets set to 0-12. Is this a bug? I should add that the sliders can all be set separately when testing out the project, it's just the initial set up which is the problem."

## Steps to replicate
I'll populate with more info asap, or feel free to edit this initial comment as necessary.

**Comment by ral104** [comment]
Have set up multiple sliders as sub-tasks in operation war diary and they are working fine now. Thanks.

**Comment by mcbouslog** [comment]
That's great, thanks for updating @ral104.
