### ISSUE TITLE
Create issues for Talk requirements from Big Ol Talk spreadsheet

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#533]
It seems like there are a lot of requirements that came from the Talk survey and which were classified as High or Very High in the [Big Ol Talk spreadsheet](https://docs.google.com/spreadsheets/d/1cuYZgUmzz1KXcDwZ0LCUql88hqJjjbrisRB6tyDcqJc/edit#gid=0) which are not in Talk yet. I guess some of these may already be planned but I wanted to make sure we don't forget any of these. 
For example, permalinks, saved searches/live collections, etc

**Comment by aweiksnar** [comment]
@DarrenMcRoy

**Comment by chrissnyder** [comment]
Too large an issue, closing for more specific issues where appropriate.
