### ISSUE TITLE
Intervention messages may not present in the UI

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#5337]
It seems there is a race condition with message events and the redux action, specifically if:

1. Intervention message is sent / received after a classification has been sent and the UI is on the summary screen
0. Press Next subject button and the intervention message is wiped. 

Could the intervention message be wiped in another classifier event or after display? 
https://github.com/zooniverse/Panoptes-Front-End/blob/6169d2b3fd5936b7d53e8818a2026f4d01ffef70/app/redux/ducks/classify.js#L193

Redux dev tools helped massively debugging this.

**Comment by eatyourgreens** [comment]
Maybe have a `CLEAR_INTERVENTION` action that can be fired from the Next button (if there's an intervention), so that clearing the intervention isn't tied directly to loading the next subject.

**Comment by eatyourgreens** [comment]
I think [an Effect hook](https://reactjs.org/docs/hooks-overview.html) could be added to [the Intervention component](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/components/Intervention/Intervention.jsx), that cleans up the stored intervention when the component unmounts. That would be safer than cleaning up the intervention on subject change.
