### ISSUE TITLE
no images loading on P4: Ridges if you've finished all the live data

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#5339]
I'm not sure if this is a front end or backend issue so I'm posting this hear:

> @fnogal

> May 12th 2019, 4:07 am

> @mschwamb Hi Meg I've reached the end of the current image set but, instead of getting an image with the "Already Seen" banner, neither the image nor the banner are shown and I get a small rectangle with endlessly spinning circles. Reloading does not cure it. I'm reporting this as it might be a Zooniverse abnormal behavior.

https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/667/876422?comment=1642322

I've also got another report of it in a private message.

**Comment by camallen** [comment]
I couldn't replicate this issue, https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/667/876422?comment=1649552

Closing for now, please re-open if needed.

**Comment by mschwamb** [comment]
@camallen  I'm now getting the same behavior. 

<img width="1107" alt="Screen Shot 2019-05-25 at 1 36 58 PM" src="https://user-images.githubusercontent.com/753325/58375618-a364fa00-7ef2-11e9-9a8b-472560ddabfa.png">


Maybe it's an image that didn't actually get uploaded. I used the panoptes command line client? No way for me to tell though how to fix this. 

Other volunteers are reporting a similar behavior in the classification interface. See [this](https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/667/1008183)

**Comment by mschwamb** [comment]
So it looks like an issue with the image upload. I used the command line tools. Is there a way I can get the size of the images on S3 to find the bad one. I imagine the bad one is the one that doesn't match the others in file size?

**Comment by camallen** [comment]
If you've got the image files you uploaded handy locally you look there quickly to identify the problem image. 

Failing that you can grab a subjects export and filter on the currently linked data, then run head requests against s3 to get the file size. 

https://stackoverflow.com/questions/3910071/check-file-size-on-s3-without-downloading

**Comment by mschwamb** [comment]
I have the images locally. They are fine in size. I did an ls -lrth and they all show as 470K.  So the images are fine.  It's what's stored in amazon. 

I don't understand anything in the stackoverflow link so on my own I'm not going to be able to do this. I'm happy to help, but asking me to figure out S3 on my own is tough. I do want  to understand what happened and make sure volunteers to get images.  I guess an option is dong an wget of the subject images and watch it get stuck?

I did have one of the uploads hang with the command line tool. I took it as one of the other crashes that I normally see but it didn't return back with an error the process was hung in the terminal, so I did have to kill that terminal. I took it to be the same kind of crash as I normally see.

 I upload in 200 subject chunks and usually 1 to 3 of 10-14 uploads I do has crashes. Either I have to close my laptop before it finishes or it crashes (might be work wifi or something else). I don't normally report stuff  anymore because most of my tickets have gotten closed by stalebot  without any comment. With the ticket being closed by an automated script without any comment from a person, without any more context it seemed like a waste of my time to put in any github issues so that's why I didn't report the odd hang on the command line client. If it's useful I can add a github issue in that repo as well.

**Comment by camallen** [comment]
> I upload in 200 subject chunks and usually 1 to 3 of 10-14 uploads I do has interrupts/crashes. Either I have to close my laptop before it finishes or it crashes (might be work wifi or something else). I don't normally report stuff anymore because most of my tickets have gotten closed by stalebot without any comment. With the ticket being closed by an automated script without any comment from a person, without any more context it seemed like a waste of my time to put in any github issues so that's why I didn't report the odd hang on the command line client. If it's useful I can add a github issue in that repo as well.

Up to you if you want to report these issues but note that it's incredibly hard to debug these client side issues as they are normally network related between the client and S3 and our API. Some users have issues, others don't. Try to avoid uploading over wifi if you can and make sure you are on reliable internet connections.

> I don't understand anything in the stackoverflow link so on my own I'm not going to be able to do this. I'm happy to help, but asking me to figure out S3 on my own is tough. I do want to understand what happened and make sure volunteers to get images. 

> I guess an option is dong an wget of the subject images and watch it get stuck?

That SO link basically says do that, just with a HEAD request instead of downloading the data. E.g. 
```
SUBJECT_URL=https://panoptes-uploads.zooniverse.org/production/subject_location/c9f8b23f-74a2-4004-a869-75eb2b78979c.png
curl -sI $SUBJECT_URL | grep 'content-length:'
# returns 
content-length: 481455
curl -sI $SUBJECT_URL | grep 'content-length:' | cut -d' ' -f2
# returns 481455
```
So you could have a bash script to loop over a list of image urls https://stackoverflow.com/questions/9865866/pipe-output-of-cat-to-curl-to-download-a-list-of-files

```
# url_head_test.txt
https://panoptes-uploads.zooniverse.org/production/subject_location/c9f8b23f-74a2-4004-a869-75eb2b78979c.png
https://panoptes-uploads.zooniverse.org/production/subject_location/fd93fc44-6d77-453d-ba24-279abf718cc0.png
```
And then iterate over them and get some data on them.
```
cat url_head_test.txt | xargs curl -sI | grep 'content-length:' | cut -d' ' -f2
```

A simple way to do this would write the content length for each URL to a single list of file sizes. This should have the same number of lines as the original URL list and in theory any 0 length rows would match the line number in the url file. Make sense?

**Comment by mschwamb** [comment]
Yes, this makes more sense to me. I will try this over the weekend

**Comment by mschwamb** [comment]
It took me a better longer to get to this;

It's this one https://www.zooniverse.org/projects/mschwamb/planet-four-ridges/talk/subjects/32828344

Should I delete the subject?  Or can I (or with help) replace the image/upload the image and reset the classification count?

**Comment by camallen** [comment]
It's probably easier to unlink it from your current set and upload a new one tbh, though if you have a good reason we can help add an image to it. 

Have you checked if it already has classifications? If so it might be hard to untangle the data for retirement / reduction later on if we replace the failed image.

**Comment by mschwamb** [comment]
I've removed the bad subject from my subject set. I use the list of subjects to pick out the valid classifications so this should be okay given the replacement has a different subject ID. 

Thanks for the help
