### ISSUE TITLE
Broken links in Talk search results

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#534]
The comment links and hashtag links in Talk search results don't work, and generate errors.

see e.g. http://demo.zooniverse.org/panoptes-front-end/#/talk/search?query=test and click a comment or hashtag.

**Comment by aweiksnar** [comment]
Hashtag links https://github.com/zooniverse/Panoptes-Front-End/commit/e5ea71b9af56e22ed9582490872ede192dfad38e and comment links  https://github.com/zooniverse/Panoptes-Front-End/commit/4c791578925096c2367185fe4f5f953a353b0358 in search results should be working now. Re-open if you disagree. Going to open a separate issue for markdown links
