### ISSUE TITLE
Changing already seen and finished flags to more meaningful messages

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#5340]
The [issues with 'already seen' and 'retired' flags on Planet Four: Ridges, ](https://github.com/zooniverse/Panoptes-Front-End/issues/5339) highlights the continuing issue that folks don't know what those terms means. They think that classifying images they already see is helpful or don't understand how they could be really not seeing new images if the site is not at 100% but the flag is saying 'already seen'. It's a mix of new and super users who are having trouble understanding what these terms are.

**Comment by rogerhutchings** [comment]
cc https://github.com/zooniverse/front-end-monorepo/pull/622

**Comment by srallen** [comment]
@mschwamb we won't be updating the existing classifier except for critical bug fixes. There is a new design for more meaningful banners in the new classifier. You can preview you that here: https://fe-project.preview.zooniverse.org/projects/brooke/i-fancy-cats/classify?env=staging (Please note that this is still in active development and not everything is done)

In case you don't see the banner on that example project, then there are screenshots and gifs in the above linked PR. We also have plans for a prompt with other workflow (if applicable) or project suggestions too.
