### ISSUE TITLE
Dialog for adding to collection shakes on-screen

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#5355]
## Expected behavior

When I'm in the classify interface and click "add to collection" the dialog box that pops up should stay in the same place on the screen.

## Current behavior

The add-to-collection box wiggles on screen, rapidly, as though it can't decide if its location starts at a given pixel or a pixel right next to it. It's actually pretty disconcerting - I replicated it once and then had to stop because it was making me slightly nauseous!

I uploaded a .mov screencap of it [here](https://zooniverse.slack.com/files/U055FLCB2/FJT2E67MF/collections_box_wiggle.mov) - I don't think an animated gif is going to do this justice as it's very rapid. 

## Steps to replicate

Go to a project's classify interface (I was on Galaxy Zoo). Start classifying a subject, click on the icon to add to a collection.

## Additional information

- **Operating system:** MAC OS X 10.14
- **Browser:** Chrome Version 73.0.3683.86 (Official Build) (64-bit)

**Comment by vrooje** [comment]
Update: this only happens at one specific zoom level so actually there's a pretty easy workaround. Unsure if I should close this myself?

**Comment by eatyourgreens** [comment]
I think it's a bug in [zooniverse/modal-form](https://www.github.com/zooniverse/modal-form), which we probably can't fix.

**Comment by eatyourgreens** [comment]
This is fixed in the new classifier (see [Planet Hunters TESS](https://www.zooniverse.org/projects/nora-dot-eisner/planet-hunters-tess/classify)) so I'm going to close it here.
