### ISSUE TITLE
Cannot mark as read notifications for a project I am left the team of

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#5356]
I am no longer involved in Planet Hunters:TESS and took myself all the project by unclicking the check box in the project builder. Now the at team notifications I still had unread can't be read or go away initially. I tried to click on 'mark as read' and they continued to persist in my notifications until I logged out. When I logged back in, my notifications still says there are 3 new notifications even though there is no PH TESS section in my notifications and nothing else is unread.

**Comment by camallen** [comment]
I can see you have 3 unread moderation reports for the PH:Tess project, however the notifications you received as a group (moderator, etc) from the PH Tess project should still be linked to your user account, not the role you had on that project.

Do you have a PH:Tess drop down section on https://www.zooniverse.org/notifications or is it missing entirely?

**Comment by mschwamb** [comment]
Once I logged out and logged back in the PH: TESS section disappeared. When it was available, clicking on the mark as read button link didn't do anything
