### ISSUE TITLE
Support DMs, @mentions and 'follows' to help build community between users

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#536]
In order to encourage more collaboration/community building than we have experienced on past talk, we should implement features that let users interact with each other directly - especially @ mentions (which should click through to a user profile) but also 1:1 messages, and the ability to follow what posts, collections, favourites, another user does - which should show up on your homepage or sidebar per #380 or #532

**Comment by DarrenMcRoy** [comment]
I mean, we have mentions and DMs on the current Talk, the mentions just don't do very much. I assume that DMs are still a feature on the new Talk; they're rather critical!

Mentions would be tied into the notifications system and the personal feed. It's important, of course, that all user names (not display names) be restricted to asinglelineofcharacters or else the @ will not work, as it doesn't on the current Talk for names with spaces.

Following a user is an interesting idea...
