### ISSUE TITLE
Dropdown appears to have difficulty with '0' as an option

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5362]
## Expected behavior

Expect to see '0' if choose '0' in a dropdown.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Instead, when you choose '0' in, for example, https://www.zooniverse.org/projects/brbcornell/prothonotary-warbler/classify?reload=0&workflow=11219, it is left blank. All other options selected show up without difficulty. 

## Additional information

- **Operating system:**
Macbook pro Mojave v 10.14.3
- **Browser:**
Chrome v74

**Comment by trouille** [comment]
Note: as a workaround I can recommend the researcher to use the word 'zero', but wanted to flag this. I.e., this is not a priority if it's not an easy fix.

**Comment by eatyourgreens** [comment]
Is this a bug in the rather old version of [react-select](https://github.com/JedWatson/react-select) that we're using? From memory, upgrading is not straightforward or we'd have done it.
https://github.com/zooniverse/Panoptes-Front-End/blob/affb4a11c863973f3d1b0cb0e13edc82698cafe6/package.json#L37

**Comment by eatyourgreens** [comment]
It could also be a bug in our code if `selectedOptions[i].value` evaluates to false here, since 0 is false in JavaScript.
https://github.com/zooniverse/Panoptes-Front-End/blob/affb4a11c863973f3d1b0cb0e13edc82698cafe6/app/classifier/tasks/dropdown/index.jsx#L217-L219

**Comment by srallen** [comment]
Nope, upgrading react-select I think means basically a rewrite of the components that use it and I think if we do that we might as well rewrite it using Grommet and put it in the new components lib or classifier.

**Comment by eatyourgreens** [comment]
I don't think it's a bug in `react-select`. I think it's our code assuming that the annotation value will be truthy if set.

**Comment by eatyourgreens** [comment]
I think I've confirmed this by changing one of the tests to mock an annotation with value 0, instead of 3.
```
1) DropdownTask:static methods
       should be complete if required and answered with provided option:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true
      
      at Context.equal (app/classifier/tasks/dropdown/index.spec.js:67:12)
```

**Comment by eatyourgreens** [comment]
The `isComplete` check also assumes that the dropdown value will be truthy if set, so this bug probably needs a separate test.

**Comment by trouille** [comment]
@mcbouslog Just touching base on this. Should I recommend the researcher use 'zero' as a word, or is there a solution you see from discussion above that would be a small effort to implement? If it's more than a few hours, I'll recommend she use 'zero'.

**Comment by mcbouslog** [comment]
I'll add one more test to PR #5363 and I think we'll be good to go.
