### ISSUE TITLE
Search box functionality is unclear / Improve search UX

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#537]
At the moment it's not clear that the search box is a search box. Needs some styling improvement to delineate it. Also the placeholder should be something other than "test" and should disappear when you click in. Consider auto-complete search terms. Consider auto-updating of results as you type (like Google)

**Comment by aweiksnar** [comment]
Search box styling and placeholder text improved in https://github.com/zooniverse/Panoptes-Front-End/pull/544. I'll also keep auto-complete in mind for the future as well!
