### ISSUE TITLE
Show object-specific comments/tweets distinct from the discussion boards

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#538]
Are we planning to have a separate Twitter-like feed of comments on the current subject, like we do on current Talk? Are we going to delineate the boards into "the objects" and other types of boards, like on old Talk? Not sure what is already planned - feel free to close issue if already in plan/addressed! Relates to #377

**Comment by aweiksnar** [comment]
The plan for the new build was to try and merge the two places to comment on objects into one. I've setup [this](http://demo.zooniverse.org/panoptes-front-end/#/projects/alex-panoptes/test-proj/talk/subjects/35734) page for #377,  which should link users to existing discussions mentioning objects, or let them start a new discussion about an object

**Comment by aweiksnar** [comment]
Closed via https://github.com/zooniverse/Panoptes-Front-End/issues/377
