### ISSUE TITLE
Galaxy Zoo Project Avatar Missing

### ISSUE THREAD

**Issue by mwalmsley** [zooniverse/Panoptes-Front-End#5413]
## Expected behavior

The Galaxy Zoo project avatar exists and is visible

## Current behavior

The Galaxy Zoo avatar disappeared sometime this afternoon UK time. It's missing on the project page, organisation page https://www.zooniverse.org/organizations/zookeeper/galaxy-zoo, and labs [screenshot below].

This happened once previously, perhaps six months ago or so. On that occasion, I simply re-uploaded it. This time, I'll leave it missing for now to help debug. P

![image](https://user-images.githubusercontent.com/7740526/59791786-c2289780-92ca-11e9-9d49-051fffa158f7.png)

## Steps to replicate

No user actions were taken, to the best of my knowledge. I believe myself [and recently, Will] are the only people who ever touch the GZ labs page. I made no changes today.

## Additional information

Issue appears across platforms. I am using Firefox [latest]. Also reported by Hugh Dickinson on Chrome.

**Comment by hughdickinson** [comment]
Also missing on Desktop Safari (Version 12.1.1 (14607.2.6.1.1))

**Comment by lcjohnso** [comment]
Sorry -- I didn't realize there was an issue up to investigate this, so I went ahead and fixed the problem by uploading a new avatar via the project builder.  Apologies, but that's why the problem is fixed (not currently reproducible).
