### ISSUE TITLE
About/Team Updates, June 2019

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Panoptes-Front-End#5417]
Add new bios+photos to team page:
- Cliff Johnson
- Chelsea Troy
- Molly Simon

Move people from team to alumni:
- Marten Veldthuis
- Noah Malmed

Images and Bio info for each new team member will be added as comments below.

**Comment by lcjohnso** [comment]
### New Bio: Cliff Johnson
*Name and Title* = Cliff Johnson, Postdoctoral Fellow
*Twitter Handle* = lcjohnso
*Bio Text* = Cliff Johnson is a postdoctoral fellow jointly-appointed at the Adler Planetarium and the Center for Interdisciplinary Exploration and Research in Astrophysics (CIERA) at Northwestern University. As an astronomer, he is a longtime Zooniverse collaborator as science lead for the Andromeda Project and currently leads the Local Group Cluster Search project.  Cliff joined the Zooniverse team at the Adler in May 2019.

*Image*:
![lcj_headshot_crop-bw](https://user-images.githubusercontent.com/2006101/59866818-204c8d80-9352-11e9-8fcc-5676aa100fdf.jpg)

**Comment by rogerhutchings** [comment]
(is this a good opportunity to move all this stuff over to the cms, by the way?)

**Comment by snblickhan** [comment]
Name and Title = Samantha Blickhan, Humanities Lead

Bio Text = Samantha Blickhan is a postdoctoral fellow at the Adler Planetarium, leading humanities research efforts for the Zooniverse. Likes music notation, old books, and memento mori.

**Comment by srallen** [comment]
> (is this a good opportunity to move all this stuff over to the cms, by the way?)

Yep, it could be, but not sure where it's gonna fit in the priorities yet and I don't want to necessarily delay adding folks to our team page for it.

**Comment by beckyrother** [comment]
Name and title – Becky Rother, Designer (please remove my Twitter link)
Bio – Becky Rother joined the Zooniverse team at the Adler in 2017, leading design efforts across the Zooniverse and beyond. She enjoys live music and pictures of other people's pets.

![becky-2018-square-bw](https://user-images.githubusercontent.com/1392130/59874340-a1f8e700-9363-11e9-9d91-b31bc3a7217e.jpg)

**Comment by mollysimon** [comment]
Name and Title = Molly Simon, Education Postdoctoral Fellow
Bio Text = Molly Simon is a postdoctoral fellow at the Adler Planetarium leading the development, assessment, and implementation efforts of new curricular material for classroom.zooniverse.org. In her spare time, Molly enjoys exploring reading non-fiction, hanging out with her dog "Mr. T" and trying out new restaurants. 
![IMG_1539](https://user-images.githubusercontent.com/51889441/59878788-cc9c6d00-936e-11e9-8ec6-e7f83348f140.jpg)

**Comment by rogerhutchings** [comment]
@lcjohnso i've pretty much finished that page and am just adding people, so hold off on tackling any pfe edits

**Comment by beckyrother** [comment]
@rogerhutchings do you need a black and white version of Sam's image? Happy to make that real fast

**Comment by rogerhutchings** [comment]
https://css-tricks.com/snippets/css/monotone-image-css/ <3

**Comment by beckyrother** [comment]
Excellent 💯

**Comment by karenlmasters** [comment]
Related to this, Brooke and I need our affiliations updating (I'm at Haverford now not Portsmouth, and Brooke is at Lancaster - so I think we can remove "California"). 

Also Melanie Beck (Minnesota) should be moved to Alumni.

**Comment by rogerhutchings** [comment]
@lcjohnso the new page is live - can you check over the content in contentful and make any changes needed to test it out? (e.g. I don't have any details for Chelsea)

**Comment by chelseatroy** [comment]
![headshot](https://user-images.githubusercontent.com/5744164/60128855-42327f80-9759-11e9-9408-554ab606e45a.jpg)

Name and Title = Chelsea Troy, Software Engineer
Find me at = chelseatroy.com
Bio Text = Chelsea Troy is a software engineer and data scientist currently focused on The Zooniverse's citizen science mobile app. When she isn't writing code, she is lifting weights, enjoying the outdoors, or writing about tech at chelseatroy.com.

**Comment by lcjohnso** [comment]
@rogerhutchings -- content looks good!  Code needs were met via PR https://github.com/zooniverse/front-end-monorepo/pull/944.

I'm keeping this issue open until final edits/updates are made, but I will take care of that via Contentful.

**Comment by karenlmasters** [comment]
Looks good - except you still have me at Portsmouth. I'm at Haverford now. :)

**Comment by lcjohnso** [comment]
Good to go - updates are complete (for now)!  Closing.
