### ISSUE TITLE
Combo with single or multiple task focus issue

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#5419]
## Expected behavior
focus is on first task input

## Current behavior
combo task with any task, then single or multiple question initially focused on question task (instead of first task input as expected)

## Steps to replicate
- production (second step): https://www.zooniverse.org/projects/md68135/notes-from-nature-capturing-californias-flowers/classify?reload=1&workflow=11379
- staging: https://master.pfe-preview.zooniverse.org/projects/markb-panoptes/focus-testing-project/classify?reload=0&workflow=3345

**Comment by eatyourgreens** [comment]
This is deliberate. There was concern that focusing an answer would bias classifications.

**Comment by eatyourgreens** [comment]
Oops, wrong button. Questions grab focus on mount and override the autofocus attribute.

**Comment by mcbouslog** [comment]
this issue is just at the general task level, not options/answers as I think you're referring to and I recall as well, I think, PR incoming and I think will make more sense...
