### ISSUE TITLE
Add a German translation

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5452]
Chimp and See would like to publish their project in German, so German language translations are needed in this file:
https://github.com/zooniverse/Panoptes-Front-End/blob/ae5d4c70b59445a09f3138ab2eeadc1c112d2fb0/app/locales/de.js

**Comment by trouille** [comment]
@eatyourgreens I've reached out to Chimp&See to find out if someone in their team can provide the needed translations. I'm anticipating yes. Could you provide instructions on how they should provide those translations? Do they do it in a separate word document and then provide that to us and a dev inserts it in the right spot?

**Comment by eatyourgreens** [comment]
@trouille I believe that when Variable Star Zoo worked with Grant to add Spanish, they just opened a PR with the translation. See #4779.

**Comment by AnLand** [comment]
I can help with the German translation.

**Comment by eatyourgreens** [comment]
@AnLand GitHub has an editor built in, so you should be able to edit the translation in your browser.
https://help.github.com/en/articles/editing-files-in-another-users-repository

The address of the German language file is https://github.com/zooniverse/Panoptes-Front-End/edit/master/app/locales/de.js 

There's a lot of information in that file but don't feel like you have to translation every single part of the web site. I would concentrate on translating the single words and short phrases. Thanks for offering to help, and let us know if you have any questions.

In case they are useful, here are two other translations that were submitted by volunteers (so you can see which strings were translated.)
Spanish: https://github.com/zooniverse/Panoptes-Front-End/pull/4779
Czech: https://github.com/zooniverse/Panoptes-Front-End/pull/5305

**Comment by AnLand** [comment]
I provided a commit with major parts translated into German here: https://github.com/zooniverse/Panoptes-Front-End/pull/5460. The missing parts (and catching any typos) will be provided in few days. I used the Czech translation to identify the parts that needs to be translated.
