### ISSUE TITLE
Add a French translation

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5457]
Add a French translation for PFE so that Chimp and See can be published in French.
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/locales/fr.js

**Comment by trouille** [comment]
Have a potential French translator who will post here once they've decided which route they prefer for providing a translation.

**Comment by gabocks** [comment]
Hey there!  I am ready for french translation.

**Comment by gabocks** [comment]
Hey there! I am ready for french translation.

**Comment by eatyourgreens** [comment]
@gabocks Can you edit this file and translate the short phrases to French, using the editor that's built-in to the GitHub web site?
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/locales/fr.js

GitHub has some help for getting started with the editor. Hopefully, it is straightforward.
https://help.github.com/en/articles/editing-files-in-another-users-repository

Don't worry about translating all of it: most will not be relevant to the Chimp & See project. You can check Anja's changes in #5460 for the German translation to see what to translate.

Thanks again for offering to help and please do post here if you have any questions.

**Comment by trouille** [comment]
@gabocks Could you update here? Thanks!

**Comment by gabocks** [comment]
@trouille I did a first translation till line 265 I think, had no time to continue since then. I dont completely understand how github works, so I am not sure where it is.

**Comment by eatyourgreens** [comment]
Hi @gabocks your work is on your github account here: https://github.com/gabocks/Panoptes-Front-End/tree/patch-1

There's should be a button that says something like 'open new pull request'. If you click that, there's be a form you can fill out to submit the translation to us.

**Comment by gabocks** [comment]
Ok, is it worth it to do it now? or rather wait until I've done more?

**Comment by trouille** [comment]
I'd keep going. Currently you're our only French translator working on this particular piece. If you can post here a sense for when you'll have time to do more and potentially complete it, that would be helpful. But not a problem if it will take some time. We just really appreciate your help.

**Comment by gabocks** [comment]
Hey
So I've created a first pull request. I've made another commit with the rest of the translation necessary for Chimp&See, but I dont know how to get all this together. Any help is welcome.

**Comment by AnLand** [comment]
Hi! There is another Chimp&See volunteer who would be interested to help with the French translations. She doesn't know github, but I can explain the basics and see how she would like to work - provided that help is still needed.

**Comment by gabocks** [comment]
Hey!

The parts between 260 and 977 still need to be done (as well as a re-read of my translation). I am happy to get help.

Cheers
Gaelle

**Comment by Orohena** [comment]
Hi there !

My name is Flavie, I'm French and ready to help with translation :)
I will just need some time to understand how this work.
It's funny, since yesterday I started to learn Python ! I have the feeling it will help me get less scared of github :)

**Comment by Orohena** [comment]
Hi all,
just to let you know that I went around github and I understand how it works now so let me know when/how I can start here just to make sure I don't want overwrite what Gaelle did. Also Gaelle, I guess we will have to make sure we don't translate the same lines?

**Comment by AnLand** [comment]
Hi! Despite merging the first part of the French translation into the master document, it isn't displayed anywhere where I would expect a translation into French (because it is translated in the merged part). I searched a bit and found that the counterpart registration for French here https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/pages/project/index.jsx (lines 20+) seems to be missing. I have no idea whether that's the problem, but it's my best guess at the moment. I edited the file and created a PR here https://github.com/zooniverse/Panoptes-Front-End/pull/5492 (in case that's indeed the problem).

**Comment by Orohena** [comment]
Hi all,
just to let you know, especially Gaelle (@gabocks) that I am starting today the translation from line 260.
If you want to translate too, let me know so we can divide the work (or work on the same file if it is possible).

**Comment by Orohena** [comment]
Hi all, 
I have done the translation from line 259-260 to the end.
I created a pull request, it's named "Update fr.js" and it is #5505 
I hope it's all good but any way it will be minor changes and we can still do it later I guess.

Have a nice day !

**Comment by AnLand** [comment]
I think this issue is solved with @Orohena providing the rest of the French translation in addition to @gabocks work. Thank you so much! It can be closed now.

**Comment by srallen** [comment]
Thanks all!
