### ISSUE TITLE
How do you add/remove  gold standard status or talk moderator status to project owner? Owner no longer showing up in collaborator list

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#548]
So on the preview site for the project I own, I no longer see myself listed. How does one add expert status to myself or remove the ability to moderate Talk for the project?

This is what I currently see in the latest version of Firefox 

![screen shot 2015-06-12 at 1 32 58 pm](https://cloud.githubusercontent.com/assets/753325/8141767/ccd4c4ae-1107-11e5-96ed-98b50f96abe2.png)

**Comment by edpaget** [comment]
If you're an owner you are already an expert and a talk moderator. It would be good to add the owner back to this list though (and maybe remove the checkbox for owner for non-owner collaborators since you can't make them owner anyway).

**Comment by mschwamb** [comment]
I actually don't want to be a talk moderator. On the projects I'm involved typically I give up mod status and let the volunteer moderators handle  it, so it would be good to be able to opt out those extras if possible.

**Comment by edpaget** [comment]
You have to be a Talk Admin for your project's Talk to add Talk Moderators, owners are automatically admins (otherwise no one could add more Admins or Moderators). Being an admin gives you all the abilities of a moderator,  but not necessarily the "Moderator" flair in Talk. So I don't think it makes sense to be able to 'opt-out' of those settings.

**Comment by mschwamb** [comment]
if it doesn't give the 'moderator' tag on Talk, then that's fine with me.

**Comment by mschwamb** [comment]
I did find the owner check box confusing for the other collaborators and moderators.

**Comment by mschwamb** [comment]
@aliburchard  should there be an text explanation that the owner has all of these powers and can't remove those roles from themselves?
