### ISSUE TITLE
Add Japanese Translation

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5487]
Mitsuko of the Japan Agency for Marine-Earth Science and Technology  has offered to provide a Japanese translation. In service of his project https://www.zooniverse.org/lab/9625/workflows/11574 and everyone's use. 

Instructions: Please edit this file and translate the short phrases to Japanese, using the editor that's built-in to the GitHub web site:
https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/locales/ja.js

GitHub has some help for getting started with the editor. Hopefully, it is straightforward.
https://help.github.com/en/articles/editing-files-in-another-users-repository

Thanks again for offering to help and please do post here if you have any questions.

**Comment by Llyria1988** [comment]
Hi, Laura

 I sincerely appreciate you and your hard works!

 Mitsuko

**Comment by trouille** [comment]
Posting an important comment from @Llyria1988 from contact@zooniverse.org:

<< Just an offer for the translation page, when I switch language English to Japanese on my project, I  will see "日本人” on the upper right.
"日本人" means "Japanese People", so I think it's better to change it to "日本語（Japanese language）”. >>

@eatyourgreens Do you know how to make this change? Thanks!

**Comment by srallen** [comment]
@trouille the line to be updated is here:

https://github.com/zooniverse/Panoptes-Front-End/blob/e4b14ceeeda0d80d4215ae1388b6d87a17b98e7a/app/constants/languageMenu.js#L11

**Comment by eatyourgreens** [comment]
I’m still on holiday, I’m afraid.
