### ISSUE TITLE
when you click on an external link added by the External links interface weird text added at the end of the url

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#549]
Tested by trying different urls and the same thing repeats (at least on Firefox)

this text '?_ga=1.265338380.2075271546.1430920663' is at the end of the url string 

So when I click on the P4: Terrains blog link I get this (it still gets to the site okay though)

![screen shot 2015-06-12 at 4 54 05 pm](https://cloud.githubusercontent.com/assets/753325/8142756/58ac111e-1124-11e5-930e-905b1baee2dc.png)

**Comment by edpaget** [comment]
This is just our Google Analytics info. It won't affect external sites loading.

**Comment by mschwamb** [comment]
okay. thanks
