### ISSUE TITLE
Adding custom dimension to capture seconds in Google Analytics

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5491]
Recommendation from Corey Jackson and Scotty Coughlin (two research leads on Gravity Spy; Corey is a crowdsource research postdoc at UC-Berkeley). They realized that while Google Analytics provides (for a given event) date - hour - minute directly, it does not include second:

Zooniverse should add a custom dimension in our code to capture seconds: https://stackoverflow.com/questions/40418529/google-analytics-how-to-add-seconds-to-dimension

**Comment by trouille** [comment]
Note - this isn't a time-sensitive request. It would be good to do this this Fall, so that we start collecting these 'seconds' data for future analyses, to make the GAnalytics most useful.

**Comment by trouille** [comment]
@amyrebecca Is there any knowledge transfer around this that we should be thinking about before your last day?

**Comment by amyrebecca** [comment]
I'm happy to sit down with Will in case there are any questions I can answer about the implementation in general. About this request in particular, I would think really hard about whether it's a good idea to try to force GA to collect data at a finer time grain than it's designed for; it's hard for me to imagine that we have events that require that precise an ordering. Clock skew is likely to make this useless and the volume of data can be hard to digest. From the article:

>> Even if we are able to create this dimension the Analytics Reporting API only reports data in aggregate and as such the finest grain reporting would be minute

**Comment by lcjohnso** [comment]
This enhancement still has value, so removing stale tag.
