### ISSUE TITLE
Feedback images missing for most subjects

### ISSUE THREAD

**Issue by NicoAdams** [zooniverse/Panoptes-Front-End#5496]
## Expected behavior

When the feedback is shown, a modal should pop up containing the feedback image. (In the case of Clump Scout, the subject should pop up with added circles at the locations of known clumps. Shown below.)

![image](https://user-images.githubusercontent.com/2320544/63542411-ed577f00-c4e5-11e9-8539-775b6cac9dd4.png)

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

The modal pops up with the correct message, but no image appears. This is true in MOST cases -- approximately 1 in 5 subjects appears with an image.

![image](https://user-images.githubusercontent.com/2320544/63542071-14fa1780-c4e5-11e9-9453-b8f845c83213.png)

## Steps to replicate

Discovered on the Clump Scout project
https://www.zooniverse.org/projects/hughdickinson/galaxy-zoo-clump-scout/classify
- Classify a training subject
    - To see a training subject, you must begin classifying subjects using a new user account. 
- Press "Done". The feedback modal should appear
- In most (~4 out of 5) cases, the feedback text will be correct, but the image will be missing

**Subject IDs for subjects with this issue:** 
"Clump Scout Training Set (#76900)"
728236891928
165631340795
178515676461

**Subject IDs for subjects WITHOUT this issue:** 
"Clump Scout Training Set (#76900)"
235507100612
309890192287

## Additional information

- **Operating system:** Windows 10
- **Browser:** Google Chrome.

**Comment by mcbouslog** [comment]
Thank you for reporting @NicoAdams!

It appears feedback rule 1 has `hideSubjectViewer: true`. This can be toggled to false by temporarily setting the project to development mode, editing the workflow task's feedback rules accordingly (clicking related feedback rule, unchecking Hide Subject Viewer), then setting back to live.

Mentioning @hughdickinson, or I see you're a project collaborator, let me know if you'd like me to go ahead and make that change.

**Comment by srallen** [comment]
Thanks @mcbouslog! Just a note on the above, I believe you can just set the workflow to inactive and edit the task feedback, rather than set the whole project back to development, then set the workflow back to active.

**Comment by NicoAdams** [comment]
@mcbouslog Thanks for taking a look! Glad it was simple to diagnose. At the moment, feedback rules are handled locally rather than through the project builder, but otherwise this should be a simple fix.
