### ISSUE TITLE
Translations 403 response: No primary language version exists for project_page

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#5497]
Working on project translations for AmazonCam Tambopata:

## Expected behavior
When a page with the original English text exists for a project (f.e. Field Guide, Results, FAQ) I should be able to see it displayed and be able to translate it in the Translations. 
Here's a direct link to one of these pages on the project:
https://www.zooniverse.org/projects/rainforestexpeditions/amazoncam-tambopata/about/results
Here's the same page in the translations: https://translations.zooniverse.org/#/project/3040/project_page/4592

## Current behavior
When I click on either Field Guide or Results or FAQ pages in the Translations, I always get 403 response from server on a blank page saying _"No primary language version exists for project_page"_  So there's no way to translate the text for these pages.
Screenshot for the Results page in Translations:
![ysh_Screenshot_2019-08-24_10-58-19](https://user-images.githubusercontent.com/7211888/63639175-b07bbb80-c690-11e9-978a-b06122bd589f.png)

## Steps to replicate
Go to Translations and open Field Guide, Results and FAQ pages - see what happens.

## Additional information
I tried change the language but didn't help. 

- **Operating system and browser:**
Happens on Ubuntu Chromium and also on Android Chrome - both with the same bad results.

@eatyourgreens

**Comment by yshish** [comment]
Or does it belong under https://github.com/zooniverse/pandora/issues ?? If so, please, could you move it? Thank you.

**Comment by eatyourgreens** [comment]
This is a bug in https://github.com/zooniverse/Panoptes. The English translations should be created automatically whenever the project owner saves a change in the project builder.

A workaround would be to ask the project owner to go into the project builder and save those pages again. That should also fix the Field Guide. Maybe make a small change to each one, then delete the change, just to force Panoptes to save new versions of those resources.

**Comment by yshish** [comment]
Thanks. I contacted the AmazonCam team. Sadly, no one is available for the next few weeks to make the required steps :/
