### ISSUE TITLE
Talk sidebar showing Private projects in dropdown menus

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#551]
Example: from http://preview.zooniverse.org/panoptes/#/projects/vrooje/galaxy-zoo-bar-lengths/talk I can access http://preview.zooniverse.org/panoptes/#/projects/vrooje/galaxy-zoo-merger-free-black-holes/talk - but that project is private and it should not show up as an option at all.

**Comment by camallen** [comment]
@vrooje you sure that's not this old project, http://preview.zooniverse.org/panoptes/#/projects/zooniverse/galaxy-zoo-mergers

**Comment by edpaget** [comment]
Were you logged in?

**Comment by vrooje** [comment]
It wasn't the old GZ Mergers project -- this is the list that showed up for me and it includes both:

![screen shot 2015-06-22 at 17 11 57](https://cloud.githubusercontent.com/assets/2357126/8286529/063c7dd4-1902-11e5-9f20-56fe53317fcb.jpg)

However, I *was* logged in and when I tried it in an incognito window that private project didn't appear. Oops. I should have checked that before; sorry.

**Comment by edpaget** [comment]
Cool. This is expected behaviour then. That project's route will return all the private projects you can see.
