### ISSUE TITLE
Home Page – new featured projects 

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#5519]
## Expected behavior
Since Shax World is coming to an end, let's take this opportunity to replace all of the featured projects on the non-logged-in home page.

## Current behavior
![image](https://user-images.githubusercontent.com/1392130/66058311-c4bc9f00-e4ff-11e9-9db7-bd58d1d49507.png)

## New projects:
- [ ] Notes from Nature
- [ ] Planet Hunters
- [ ] Etch a Cell
- [ ] Anti-Slavery Manuscripts

**Comment by beckyrother** [comment]
Notes from Nature:
![NfN-bg](https://user-images.githubusercontent.com/1392130/66077934-a61dce80-e526-11e9-827c-b17521470f70.jpeg)

Planet Hunters:
![PH-bg](https://user-images.githubusercontent.com/1392130/66078001-c057ac80-e526-11e9-830a-91a11d300af7.jpg)

Etch a Cell:
![EaC-bg](https://user-images.githubusercontent.com/1392130/66078062-e5e4b600-e526-11e9-911e-e0fc848a822e.png)

ASM (This is a square image, lmk if a rectangle would be better):
![Twitter Profile Photo 2](https://user-images.githubusercontent.com/1392130/66078172-1f1d2600-e527-11e9-82f6-84c6464208fc.png)

**Comment by mrniaboc** [comment]
This would be great to update! It make the site look outdated and dead if there are finished projects on the home page.
