### ISSUE TITLE
Talk sidebar: users should only see projects they've classified on?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#552]
On the Talk sidebar where you can jump to a different project, should we only show the projects the user has classified on? As we grow this might get to be a very long list which could be overwhelming for newcomers.

Maybe this is already a feature -- I suspect not but I've done basically every project so I wouldn't be able to tell.

**Comment by aweiksnar** [comment]
Right now it's just a list of 20 projects. I believe the original intent was to try and get users exploring new projects, but if people find it more useful as a list of ones they have participated in perhaps we should change up the list

**Comment by DarrenMcRoy** [comment]
I think this list should be customizable by the user, a la Reddit subreddits, and how I assume your "feed" will work.

You're default subscribed to the ZooTalk, but you can add quicklinks to Talks that you visit often.

**Comment by aweiksnar** [comment]
I believe that endpoint is limited to 20 projects at a time

**Comment by aweiksnar** [comment]
I had it showing only projects that users have classified in, but for most people that was a very small number. Right now it will show all panoptes projects without a redirect setup. This seems to be a sensible list, but happy to revisit on the next talk design update / when that project list grows in size

**Comment by DarrenMcRoy** [comment]
Hey @aweiksnar -- two issues I can see.

First, the list takes almost 15 seconds to load! (Except for Zooniverse Talk link.) Anything we can do about that?

Second, WildCam Gorongosa and AnnoTate are not listed.

**Comment by aweiksnar** [comment]
@DarrenMcRoy 
- The projects route is slow. It's a known issue in the api and not something I can address on the frontend, and also unrelated to this issue.
- WildCam Gorongosa and AnnoTate both have redirects setup, so are not expected to be in that list. 
- The crux of this issue was the length of the project list in the sidebar and that has been addressed.

**Comment by DarrenMcRoy** [comment]
WildCam and AnnoTate may have redirects, but they're both active Panoptes Talks (WildCam in particular!)

This list appears on both of those Talks, so right now it's possible to go in one direction but not another. I know this issue has been extremely annoying, but is it really not possible to include those two projects as well? It's still an incomplete list at the moment, and it's missing our most popular Panoptes project! (that being WildCam)

**Comment by aweiksnar** [comment]
@DarrenMcRoy I agree that those projects are important, but again, this particular issue has been addressed. Integrating non-PFE projects into the sidebar is something different, and certainly  will happen when project filtering / sorting is improved. Please ping me on slack if you would like to chat more about ways to populate that projects list.
