### ISSUE TITLE
Category labels don't display correctly in AmazonCam project

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#5530]
## Expected behavior
When I go to the classification interface I am supposed to see animal species labels for categories in the task window.

## Current behavior
When I go to the [classification](https://www.zooniverse.org/projects/rainforestexpeditions/amazoncam-tambopata/classify), this is what I see instead:
![ysh_2019-10-18_21-22-21](https://user-images.githubusercontent.com/7211888/67122186-85739b00-f1ed-11e9-8a4a-5ae1c54d40e5.jpg)

## Steps to replicate
Just go to the classification.

## Additional information

- **Operating system:** Ubuntu, Linux
- **Browser:** Chromium 77

**Comment by yshish** [comment]
Clicked on a random category and got this:

![ysh_2019-10-18_21-26-22](https://user-images.githubusercontent.com/7211888/67122441-1cd8ee00-f1ee-11e9-8fa4-adfae3fad10b.jpg)

**Comment by srallen** [comment]
Yeah, I'm wondering if it's a translations issue. Those are the string paths for the labels and that is what is in the response for the label itself, so the front end app is displaying what it's getting. I see the workflow was last updated today, so something may have gone wrong in an update.

**Comment by yshish** [comment]
I've just checked out the [Translations/workflow](https://translations.zooniverse.org/#/project/3040/workflow/2485) and the latest workflow update actually helped to display all the missing text parts there (yay! the translation problem's solved). What a shame it also broke the labels.

**Comment by camallen** [comment]
This was me trying to update the 'missing' translation data for the workflow. I've fixed the underlying data in the API and it's now working again. Please do check it and report back if there are still issues.

Thanks for reporting @yshish - apologies for breaking the project :(

**Comment by yshish** [comment]
NP. I really appreciate your trying to help, Cam! Thank you. Glad it is back to normal :)
