### ISSUE TITLE
Drawing tools are difficult to can't be resized or adjusted at all on mobile devices

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#5536]
Reviewing the feedback from the Planet Four beta we find a pattern with tablet and mobile devices. The feedback is that the volunteers couldn't complete the task or found it difficult or not possible at all to resize the drawing tools. 
Here's the comments received from those that said they were using Android or Apple mobile device:

> Make more mobile friendly.; Very difficult to place markers on my phone. Much better on desktop with mouse amd full screen. Unable to effectively use on Android mobile.

> Using a mouse or stylus to interface with the images. With this sort of task, one needs to be able to deal with the features quickly: at a pace more-compatible with the cerebral response.' My finger hid what I was trying to define. Also, the size of the finger rendered fine adjustment of the relatively-tiny images almost impossible. I only attempted two photographs before becoming tense and fatigued. Using a stylus would have made the task MUCH easier/ working on a larger screen, with more-enlarged images, would have rendered the task more-manageable

> Didnt seem to work

I used my iphone and ipad to classify and took videos of my interactions/movements. You can find them [here](https://www.dropbox.com/s/gn74k4ti1mgk7eh/img_6209.mov?dl=0) and [here](https://www.dropbox.com/s/35raxpnnri0fm4i/video%20oct%2025%2C%209%2018%2019%20am.mov?dl=0). I had the same issues as reported above and couldn't resize the marking shapes most of the time I tried to. 

The old Planet Four had a mobile version and the adjustment handles for the marking tools were as big as the (x) is is on the shape now to allow people to grab them and adjust the size. I think the handles need to be made bigger on the mobile versions to make drawing at least possible on mobile.

**Comment by eatyourgreens** [comment]
Out of interest, Meg, did anyone report that tapping on the screen created two marks instead of one (see #5527.)

#5537 multiplies the touch size for the drag handles by 2.5 on small screens.

**Comment by mschwamb** [comment]
No. There were only 4 or 5 people using Mobile. I never got that behavior when I was trying it out if that's helpful.

**Comment by eatyourgreens** [comment]
Thanks! That is helpful. We fixed it on Monday, but it would have been mostly triggered on Android phones and tablets. Maybe also Windows 10 touchscreen laptops like the Microsoft Surface. @shaunanoordin has a pretty detailed write-up in #5527. iOS 12 and earlier didn't support the feature that caused the bug, so only iOS 13 would have been affected for iPhones/iPads.

**Comment by mschwamb** [comment]
I might still have 10 on my ipad, so I'm updating it now

**Comment by eatyourgreens** [comment]
Re. using a stylus, I don't have one to hand but the code should work fine with a Surface Pen, or an Apple pen on an iPad.

**Comment by mschwamb** [comment]
@eatyourgreens the ios13 introduced the screen sliding up and down as you're trying to draw. I lumped it into this ticket.  if you look at the video on the iphone drawing I linked about, you can see the behavior. Updating my ipad to iOs13 it now has that issue as well.

**Comment by eatyourgreens** [comment]
See #5411 for the window scrolling when you drag it on touchscreens.
