### ISSUE TITLE
Survey task: Done button isn't active after selecting "nothing there"

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#5542]
This was brought to our attention via a [ticket](https://zooniverse.freshdesk.com/a/tickets/1554)

## Expected behavior
On a survey task, the done button should be active after selecting a tag.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Currently, on the [Sagehen project](https://www.zooniverse.org/projects/gtitcomb/sagehen-mammal-quest/classify), the done button will remain disabled when the "nothing there" task is selected and identified.

## Additional information
The user experiencing this issue was using an iPad, so it could be an issue with how pointer/touch events are now handled on iOS.

- **Operating system:** iOS 13.2
- **Browser:**

**Comment by eatyourgreens** [comment]
I've checked this out quickly on iOS 11, 12 and 13. I can click 'Nothing Here', then 'Identify', then 'Done' without any problems.

**Comment by eatyourgreens** [comment]
Browserstack tests on actual devices. I tried an iPad pro with 11 and 12, then iPad pro with 13 in the XCode simulator.

**Comment by wgranger** [comment]
The user was quite adamant about the issue existing, as opposed to overlooking the "identify" button to make the done button active. I'll keep it open in the meantime with the knowledge that this error might be resolved with the classifier rewrite if we're unable to replicate it on our end.

**Comment by eatyourgreens** [comment]
I'm going to close this. We can re-open if it comes up again.
