### ISSUE TITLE
Remove ZooTeach from education page

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#5549]
We really need to remove the link to ZooTeach from here https://www.zooniverse.org/get-involved/education. 

We get a solid amount of email to contact@ about this.

**Comment by shaunanoordin** [comment]
Which parts specifically need to be removed? The whole page, or only paragraphs with the word ZooTeach?

![Screen Shot 2019-11-08 at 14 59 58](https://user-images.githubusercontent.com/13952701/68486156-74400c00-0238-11ea-93fa-f7f488bf47fc.png)

**Comment by mollysimon** [comment]
The paragraphs on ZooTeach should be removed, as none of the links appear to be in working condition anymore. You can instead, link https://classroom.zooniverse.org/#/ using some of the same phrasing e.g. Instructors and volunteers alike can access a variety of educational resources on the Zooniverse Classrooms platform (link). The ASTRO 101 materials are currently targeted towards introductory college-level students, and we are currently working to expand our curricular materials to additional projects on the Zooniverse platform. 

Something like that...but start linking to classroom.zooniverse and not too ZooTeach. So in the 'Keep up with the latest Zooniverse educational efforts' sentence, replace ZooTeach with the classrooms URL
