### ISSUE TITLE
General Chinese Translations

### ISSUE THREAD

**Issue by wgranger** [zooniverse/Panoptes-Front-End#5550]
Add Chinese translations. We now have Chinese translations (Traditional and Simplified) for general menu buttons and other items on PFE. You can find these translations attached to [a Freshdesk ticket](https://zooniverse.freshdesk.com/a/tickets/1631).

**Comment by shaunanoordin** [comment]
I'm taking a peek at this PR now. Base of comparison is this project - https://www.zooniverse.org/projects/ankeney/natural-history-and-chinese-painting - which already has English, simple Chinese, and traditional Chinese (Taiwanese) language translations at the project level.
