### ISSUE TITLE
Show feedback after classification submission

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#5584]
## Expected behavior
The feedback modal should only appear after classification submission. This is not an issue for all projects, but will be for projects that need reliance on user weighting. If a user is given feedback immediately, there's no reason to think they won't go back immediately to change their answers before submission. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Feedback modal appears after hitting next on the task. This was discovered in reviewing #5553 using this test workflow: https://pr-5553.pfe-preview.zooniverse.org/projects/chrismrp/radio-galaxy-zoo-lofar/classify?reload=0&workflow=12686?env=production

**Comment by hughdickinson** [comment]
Just a comment that in the particular project you refer to, displaying feedback after the task (not the whole classification) is actually the desired behaviour. Maybe this could be made an optional behaviour?

**Comment by eatyourgreens** [comment]
Maybe remove the check for feedback here?
https://github.com/zooniverse/Panoptes-Front-End/blob/c70d28ef189c81093e426701f98373d148b85fb5/app/classifier/classifier.jsx#L222-L232

**Comment by srallen** [comment]
> Just a comment that in the particular project you refer to, displaying feedback after the task (not the whole classification) is actually the desired behaviour. Maybe this could be made an optional behaviour?

Thanks for clarifying. It sounds like it will need to be configurable perhaps defaulting to show after classification submission.
