### ISSUE TITLE
[RFC] Support multiple default tolerances

### ISSUE THREAD

**Issue by srallen** [zooniverse/Panoptes-Front-End#5585]
## Expected behavior
The lab interface for setting up feedback may need to be variable depending on the strategy type and have multiple inputs for default tolerances.

## Current behavior
_Please include any error messages from the browser console and/or screenshots_
Currently, the new point in ellipse strategy falls back to behave like the radial strategy. See https://github.com/zooniverse/Panoptes-Front-End/pull/5553 for original implementation and discussion.

**Comment by eatyourgreens** [comment]
I'm pretty sure (not 100%) that you can define an editor component for each strategy, if your strategy needs an editor that's different from the default.

**Comment by eatyourgreens** [comment]
Yeah, just export your own custom lab component here, rather than the default.
https://github.com/zooniverse/Panoptes-Front-End/blob/c70d28ef189c81093e426701f98373d148b85fb5/app/features/feedback/shared/strategies/drawing/pointInEllipse/index.js#L6-L13

**Comment by eatyourgreens** [comment]
Can I close this since it's already supported?

**Comment by srallen** [comment]
No, supporting the possibility of customization isn't the same as deciding if we do want to allow customization. The way that it was initially implemented in #5553 wasn't a good approach, but we can still consider a better alternative.

**Comment by eatyourgreens** [comment]
The feedback readme clearly explains how to customise the project builder, and it's already in use to give different project builder editors for the question and drawing strategies.

**Comment by srallen** [comment]
This is still something to consider (maybe for support in the new classifier).
