### ISSUE TITLE
[RFC] Rationalizing config

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#5586]
While working on PFE over the weekend for a 1715 Labs project, I noticed that there's a a non-trivial amount of code that deals with environment-specific features (such as the app status messages), hardcoded URLs to assets, and similar that make the project difficult to configure or run in other environments.

I'm going to end up doing this anyway, so is there any appetite for PRs to try and tame this a bit? I'm thinking of adding [dotenv](https://www.npmjs.com/package/dotenv) and some sensible default env files for development, staging and production

**Comment by eatyourgreens** [comment]
Sounds good to me. Do you have a sense of how big the changes might be or what might break? I vaguely remember Marten running into this problem. I'll try to find his PR.

**Comment by eatyourgreens** [comment]
The changes in #4349 might be relevant here.

**Comment by rogerhutchings** [comment]
Unfortunately, it doesn't in this case, as it's still leaning on the rest of the codebase.

Some context: the original requirement was for an on-premises version of PFE that didn't make any external calls. The app status component, for example, has URLs hardcoded in based on environment; a better approach would be to pass in that URL as config at build time, and do nothing if it isn't set.

Theoretically, nothing should break; it's more about bringing config together in one place, and adding sensible fallbacks (mostly do nothing) where an option is missing.
