### ISSUE TITLE
Running on a single VM - connecting to Panoptes

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#56]
Hi,

I recently asked about running **Panoptes** on a single VM (no docker etc.) over on the `Zooniverse/Panoptes` repo:

<https://github.com/zooniverse/Panoptes/issues/422>

With help (thanks!) I got it running (I think), and would now like to access it via a local version of **Panoptes-Front-End**. This runs out of the box for me on <http://127.0.0.1:3735> following the instructions in the `README.md` - which is great - but of course it loads up (what I assume are) the remote projects.

So, is there a simple way of configuring the local **Panoptes-Front-End** to find my local **Panoptes** instance, all on the same VM?

Thanks again, @twhyntie

**Comment by brian-c** [comment]
You can set a custom host and application ID in your environment:

```
PANOPTES_API_HOST="http://localhost:3000"; PANOPTES_API_APPLICATION="ABC123"`; npm start
```

**Comment by twhyntie** [comment]
Hi @brian-c,

Thanks - this didn't quite work for me (I might have been doing something wrong with the single quotation mark after `"ABC123"` in the above?) but pointed me in the right direction - I changed `DEFAULT_ENV` to `development` in `app/api/config.coffee`, which seems to set those environment variables. Anyway, I now get a blank <http://127.0.0.1:3735/#/projects> page (as expected - no projects in my local Panoptes - as opposed to the projects in staging) and I can see my some oauth interaction on my local Panoptes when I try to sign in on the Panoptes-Front-End (which it looks like I can debug now).

Thanks again, @twhyntie

PS: I didn't realise the staged version was live, in that anyone can sign in and create project - which I have with `CERN@school test 001` - and then, better still, access that through my local Panoptes-Front-End too. This helps a great deal - thanks!
