### ISSUE TITLE
How to be sure changes are saved?

### ISSUE THREAD

**Issue by karenlmasters** [zooniverse/Panoptes-Front-End#560]
I'm making some edits today, and I am worrying that they are not saved. I get that they are actually autosaved, but some sort of confirmation of that visually on the page would be great. :)

**Comment by aliburchard** [comment]
+1 -- I often want to move on to another page or another task for edits, but my changes haven't been saved and I lose them.  I wind up waiting an extra 10 seconds or so just to make sure -- which doesn't sound like much, but I find myself wanting to be able to manually hit "save" and move on quicker.
