### ISSUE TITLE
Changing the default spread angle of the fan tool for Planet Four

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#5604]
The default spread for the fan tool on panoptes is 30 degrees, We found in the P4 beta test that this is causing problems in the sense that people are adjusting it the spread of the fan tool.  This is because 30 degrees spread is  near the peak of the fan distribution observed in the P4 catalog. The original default value was 5 degrees spread on the original Ouroboros P4.  Can the default spread be changed to 5 degrees. 

P4 catalog spread:

![catalog_spread](https://user-images.githubusercontent.com/753325/71780219-add29080-2fb7-11ea-8841-0667e80bfd64.png)

There is a peak at 5 degrees the default value but that's very tiny features the wider distribution is the one to look at. 

The disribution of fan spreads from P4 panotpes beta test from the two interfaces:

![spread](https://user-images.githubusercontent.com/753325/71780242-0144de80-2fb8-11ea-9216-27510bf98b0b.png)

We think the spike at 30 is saying people aren't adjusting the fan tool spread because it looks close enough the average value. We think we're losing information about areal coverage and having a small value like 5 degrees would help get people to fit the fan shape more accurately. 

Would you be able to make the change or if other groups are using the fan tool can a P4 clone version be generated with a 5 degree default spread? We think once this is done, P4 will very close to launching on panoptes 

cc @eatyourgreens @lcjohnso

**Comment by eatyourgreens** [comment]
Hi Meg, #5605 changes the initial spread angle to 5º. Here's a link to P4 using the code on that branch: https://pr-5605.pfe-preview.zooniverse.org/projects/mschwamb/planet-four/classify?env=production

My concern is that when the spread is smaller than the size of the drag handles, it's hard to adjust the shape of the fan, particularly on a touch screen.

**Comment by mschwamb** [comment]
Thanks. I see your point, @eatyourgreens . Going larger in spread but not as larger at 20 or 30 degrees would help I think. Can I look at 10 degrees and 15 degree spreads in a branch? I think classifying a few images  and with your  input @eatyourgreens, we can settle on a good value.

**Comment by eatyourgreens** [comment]
Hi Meg, #5605 makes the default fan angle configurable in the project builder, so you can try those angles out yourself. You should be able to edit the spread angle by editing the fan tool in the workflows at: https://pr-5605.pfe-preview.zooniverse.org/lab/5110/workflows?env=production

**Comment by mschwamb** [comment]
If the spread can be made 10 degrees, I'm fine with the spread not being editable. We have to do 1 more beta test for formal launch approval. Once the spread is changed I can look at the final beta test statisitcs and see if it needs to be increased to 15 degrees.

**Comment by eatyourgreens** [comment]
Out of interest, Meg, (and not related to this issue) does your classification distribution have this big spike at all viewport sizes? I was wondering if there's a bias where the fan spread is hard to adjust on small screens, or on touch screens.

**Comment by mschwamb** [comment]
Most people are using laptops/desktops with P4 because of the drawing tools are all hard to use in mobile. Fingers aren't as precise as what you can do with the touchpad, so I don't think it's too much an issue of viewport.

**Comment by mschwamb** [comment]
I haven't specifically checked viewport, but given we only got  a few reports when the mobile had the scroll bar moving when one tried to draw bug in the  new iOS release, my thinking is that the spread issue is viewport independent.  I can check in our final beta test before launch once the spread is adjusted
