### ISSUE TITLE
Polish translation not working for all buttons

### ISSUE THREAD

**Issue by ErikOsinga** [zooniverse/Panoptes-Front-End#5634]
## Expected behavior
Buttons such as ABOUT, CLASSIFY, TALK, COLLECT, RECENTS are translated to Polish when switching to the polish language. They are translated for different languages (e.g., Dutch).

## Current behavior
Buttons are not translated

## Steps to replicate
Add ?language=pl to the end of the link or activate a Polish version

## Additional information
Is there any way to fix this?

- **Operating system:**
- **Browser:**
any

**Comment by eatyourgreens** [comment]
Hi there! The fix would be to add a Polish locale to [`app/locales`](https://github.com/zooniverse/Panoptes-Front-End/tree/master/app/locales). If you're comfortable opening a pull request on GitHub, then the solution would be to copy one of the existing locales to a new file named `app/locales/pl.js`, then add Polish translations to the contents of that file.

**Comment by eatyourgreens** [comment]
Closed by #5635.
