### ISSUE TITLE
React warning for classifier/subject-viewer

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#564]
Probably nothing serious, but React dev tools throw this warning in the console for the SubjectViewer
`Warning: SubjectViewer is accessing getDOMNode or findDOMNode inside its render(). render() should be a pure function of props and state. It should never access something that requires stale data from the previous render, such as refs. Move this logic to componentDidMount and componentDidUpdate instead.`

I might have fixed this in #529

**Comment by chrissnyder** [comment]
Could you isolate the problem from your PR and send a separate PR with just the fix? I'm hesitant to mess with the subject viewer  too much so close to launch.

**Comment by eatyourgreens** [comment]
Sure, no problem.

**Comment by eatyourgreens** [comment]
Closed by #597
