### ISSUE TITLE
Species label block speed options for video subjects with survey task

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#5663]
If you have a survey task with video subjects, the identified species labels below the subject block the speed settings for the video:

![image](https://user-images.githubusercontent.com/5321335/77658570-c75bf680-6f6e-11ea-96d1-1148eaf8afbe.png)

Example project: https://www.zooniverse.org/projects/victorav/the-koster-seafloor-observatory/classify

**Comment by eatyourgreens** [comment]
Duplicate of #5041, which I'll re-open.
