### ISSUE TITLE
Register modal: Move the Privacy Policy tick box to directly above the Register button

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#5665]
## Expected behavior
Following a conversation in #design-thoughts – new users were having trouble creating an account because the Privacy Policy tick box had not been ticked. Moving that required box closer to the button might help people find it quicker.

**Comment by srallen** [comment]
@wgranger this is a pretty small change. Do you have time early this week to do this? Thanks!
