### ISSUE TITLE
Very confusing if an image is favorited or not

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#567]
The heart is filled all the time for me and gets unfilled when you click to 'favorite' . I find that confusing. Shouldn't it be the other way? Also once you click on it, there's nothing that actually tells you what that action does. I think for previous Zooniverse volunteers they will know what to do, but new science teams and volunteers won't really know or use that button as is.

**Comment by edpaget** [comment]
This has been fixed.
