### ISSUE TITLE
does not claim credit for work prior to login

### ISSUE THREAD

**Issue by jmichael2497** [zooniverse/Panoptes-Front-End#5670]
## Expected behavior
anything done in the current browser session tab can and should be included in items tracked after sign up or sign in, plenty of other sites do this (it encourages sign up and sign in, too).

## Current behavior
was curiously poking around the promoted tuberculosis strain antibiotic resistance project, going through maybe ten or so, finally clicked the dancing little "You should sign in!".

finished inspecting the open data and privacy policy (to make sure crowd sourced research data is open sourced to benefit the crowds that generated it as well).

registered and was disappointed to find my count at 0. went through another dozen to verify the count started after registration. also tested logout, run through a few tasks, and sign in, verified stats counter did not change from work during logout, despite doing all this in the same browser session tab in use.

## Steps to replicate
work a few entries, register (or sign in), see profile stats counter stays at 0.

## Additional information

- W10 pro 1909
- Firefox 68.6.0 esr private browsing window mode

**Comment by eatyourgreens** [comment]
I think this would require changes in https://github.com/zooniverse/Panoptes to allow for retrospectively modifying completed classifications after registration. I'm not sure if we should allow for edits to completed classifications.

**Comment by eatyourgreens** [comment]
Alternatively, we queue classifications in the browser but don't post to the API until you either a) log in or b) end the session. I'm not sure how we detect b for classifications from shared computers eg. classrooms and libraries. Perhaps submit the classification queue in batches eg. every 10 classifications but that still leaves the problem of what to do if you (not logged-in) get up and leave the browser with a waiting queue of, say, 6 classifications unsent.

**Comment by jmichael2497** [comment]
a conundrum, though not too important in the grand scheme, i guess.

i just found it interesting to notice allowing entries not associated with a person at all, since internet experience suggests that usually leads to trolling and in this case questionable quality, but that's what double and triple checks are for.

(and trolling happens even when associated with an "identity" anyway 🤷🏽‍♂️)
