### ISSUE TITLE
iPad on Safari: choice buttons don’t always turn blue when tapped

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#5673]
## Expected behavior
Survey task: selected classification turns teal to indicated selection

## Current behavior
From [Talk](https://www.zooniverse.org/talk/17/1303355): When classifying images on Snapshot Safari using an iPad Pro running (appropriately?) the Safari browser, the choice buttons don’t always turn blue when tapped. Sometimes you get a slight darkening of the grey. Usually, however, the software has registered the tap and when choices have been made in all the fields the selected buttons will turn blue. This behaviour doesn’t inspire confidence that you have made the right choices. Also a little disconcerting is spurious colours appearing on species buttons you haven’t chosen.

## Steps to replicate
I couldn't replicate this on desktop Safari, might just be an iPad issue?

**Comment by eatyourgreens** [comment]
iOS puts buttons and links in the hover state when tapped. I think that’s what’s happening here. I’ve identified an Eland, but touched Tortoise while scrolling the screen to see the photo. 
![Screenshot of choices on an iPhone, with Eland and Tortoise highlighted. ](https://user-images.githubusercontent.com/59547/78407622-2c61bd00-75fd-11ea-95b2-e3b02f42b73d.png)

**Comment by eatyourgreens** [comment]
On second thoughts, I think Stuart might mean the blue answers to the questions for an individual choice. They seem to work for me on iOS 13. 
![Screenshot of the questions for an identified animal, with answers shown in blue.](https://user-images.githubusercontent.com/59547/78511025-52b86180-7791-11ea-8428-9beebec1115e.png)
