### ISSUE TITLE
Adding institution science team works at/is affiliated to science page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#568]
It would be good though on the science page if affiliation for the science team and collaborators can be listed if the person has one. Every academic institute I've been at wants to have some credit for the projects I've helped created, and that's been through acknowledging that I'm at a specific place. Currently there is no way to do that. 

Changing my display name doesn't tell people I'm actually at a research institution. I think it gives the volunteer some more info when they decide to try a project. I think people who are not scientists/researches.etc should be allowed to make projects, but it might be worth the volunteers being able to decide if they want to work on the project being be able to see that information and decide

**Comment by edpaget** [comment]
Can this not be handled by including their names in the project text somehow? I'm curious why this needs to be an explicit feature.

**Comment by mschwamb** [comment]
I agree with you @edpaget if there was an explicit team section like custom made Zooniverse projects where you could stick a bio. Then I could add the name I use in the research community and add institution

But where? There's a science description,  a FAQ, and results. The only place I'm even mentioned is the side bar of the science page. If there was a team section then yes this would be sorted, but it appears to me the way you are sorted team is the science page right hand side menu called Team.

![screen shot 2015-06-17 at 7 06 57 am](https://cloud.githubusercontent.com/assets/753325/8196551/915f58ec-14bf-11e5-91a1-1fda76007fcf.png)

**Comment by camallen** [comment]
I'm thinking we should support this as a markdown page. The "project#team_members" field is not being used so i think we should modify it to be a text field and add it to the front end for editing / display.

**Comment by mschwamb** [comment]
Closing this since its in #1947
