### ISSUE TITLE
Use the correct Zooniverse logo in link preview

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/Panoptes-Front-End#5695]
![image](https://user-images.githubusercontent.com/1392130/80509345-e7e8e900-893e-11ea-950f-0444f1f6b78a.png)

This logo is out of date. Please switch with https://github.com/zooniverse/Brand/blob/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-black.png

**Comment by lcjohnso** [comment]
On it -- I was the one who set this up as a hack day project.  All I need to do is swap the asset on S3.  Thanks for the ping, @beckyrother!

**Comment by beckyrother** [comment]
Looks great on the link you sent on Slack! Thanks for jumping on this so quickly @lcjohnso !

**Comment by lcjohnso** [comment]
Swapped logo file on S3 for one based on current brand asset, but with increased padding and square dimensions for Twitter compatibility.

**Comment by beckyrother** [comment]
All style assets can be found on the Brand repo here: https://github.com/zooniverse/Brand/tree/master/style%20guide/logos
