### ISSUE TITLE
auto-save keeps deleting changes

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#571]
The timing of the autosave is such that it often seems to override my last 15 seconds of work. I'll add a new task, for example, but then the autosave kicks in to save the text I've just changed in the help text, and my new task is deleted.

Also -- I found the ability to *not* save changes to a workflow to be incredibly useful, as I often started to rewrite a task and then changed my mind. Now I don't have the option to change my mind, as any changes are saved before I really have a chance to think about them.

**Comment by brian-c** [comment]
Saving from one field should definitely not delete work from another. Can you write out some steps to reproduce?

I am getting an issue where the cursor moves to the end of its input after save sometimes. I'll look into that.

Not auto saving is what gave us the confusing behavior of sometimes having to press the save button and sometimes not. We won't be able to handle this nicely without major changes to the layer between the front end and the API.

**Comment by karenlmasters** [comment]
I had this problem, and then Cam helped me realise I wasn't actually logged in - even though it looked like I was.

**Comment by brian-c** [comment]
@camallen is the session timing out without refreshing the token?

**Comment by camallen** [comment]
@brian-c the default session is 2 weeks, during that time you can convert the cookie (session) into a doorkeeper token. That token is then valid for however long is returned on the token response, 2 hours be [default](https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-Token-Expiration#access-token).

You can then use the refresh token workflow to get a refresh token (see above link) apparently that doesn't expire. Or just get a new one using the default mechanism we have of converting a devise session to a token, that technique will fail after 2 weeks though.

**Comment by brian-c** [comment]
#796 should fix this. Reopen if there are still problems.
