### ISSUE TITLE
How do I create new discussion boards for a project?

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#574]
Related to [#570](https://github.com/zooniverse/Panoptes-Front-End/issues/570), perhaps, but given that the boards aren't created by default - how do I create them? I can't see anywhere in the Project Builder or _Discuss_ page in my project for creating them.

**Comment by chrissnyder** [comment]
They are created from the Discuss page on your project. There should be a set of moderator controls where you can add boards and such.

Definitely agree the default state could use work. Also integrating features like this into the project builder  sounds like a good idea.

**Comment by aweiksnar** [comment]
Similiar to https://github.com/zooniverse/Panoptes-Front-End/issues/570. Improvements to the empty state of project talks will be coming soon, and hopefully resolve both of these!

**Comment by twhyntie** [comment]
The _Moderator Controls_ button has now appeared - it wasn't showing up before - and I can now create boards and add team members. Thanks!
