### ISSUE TITLE
Admin is unable to unban a user via UI

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Panoptes-Front-End#5758]
## Expected behavior

Unticking the "Ban user" checkbox on the "Manage Users" Admin page should unban a user.

## Current behavior

Ban is not removed when checkbox is unticked.  Instead, the state (banned=True) remains the same and the autosave feature in the UI highlights the "Ban user" text in red to denote failed update.

## Current workaround

Use the Rails console to manually set `user.banned = false`

**Comment by lcjohnso** [comment]
Following up after Moderation Zoominar (1 July 2020): the inability to unban from the Admin UI may be more of a feature than a bug.  Case to consider, even if unlikely: current behavior prevents users unbanning themselves using cracked admin credentials.

Another relevant argument: the number if cases where unbanning is desired is low (most banned users are spam or sockpuppet accounts).  Requiring console intervention for rare cases likely represents appropriate investment of dev effort: don't spend time on rare or uncommon occurrence when fix may require more time than leaving current behavior and workaround in place.

@srallen and others -- feel free to close with #wontfix if you deem appropriate.

**Comment by camallen** [comment]
This is happening as the API is rejecting a missing value for the `banned` attribute. Instead if the UI posted `'banned': false'` this would be fixed. 

FWIW the unbanning use case makes sense to me in case we accidentally ban someone or want to re-instate their account.

**Comment by lcjohnso** [comment]
Reopening.

**Comment by lcjohnso** [comment]
This behavior does not appear to occur anymore -- closing.
