### ISSUE TITLE
Add Zooniverse Ribbon to User Avatar

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#577]
Definitely think this isn't a first-release target but I'm mentioning it now anyway.

I think a user's [Zooniverse ribbon](https://www.zooniverse.org/me) should show up underneath their avatar when they post on Talk. Not with numbers of classifications or even what each color means, but just a ribbon of proportional-area colors. The ribbon doesn't rank users or provide a hierarchy, but it still gives information about how a volunteer uses the Zooniverse and it's very different from role labels.

**Comment by DarrenMcRoy** [comment]
I 100% agree with this, although I think we may want it displayed in a way that spans the entire width of the post, otherwise it will be very jammed and may look meaningless after the fourth or fifth project.

Also, it should be opt-out. Not everyone will want this info displayed. :-)

**Comment by vrooje** [comment]
I'm not sure I agree it should be opt out. I do agree the display might get tricky but if the avatars are e.g. 50 pixels across then I think it's okay to have 2% total classifications be 1 pixel width assigned to a project.

**Comment by DarrenMcRoy** [comment]
I, for instance, would not want mine displayed.

There are some projects that I do much more than others, even in my spare time, and some projects I've barely touched except to familiarize myself with them. It would be fairly important, given my role to support all project communities, to have evidence of naked personal favoritism accompanying my every post. :-)

**Comment by vrooje** [comment]
The case of Zoo Team members is a special case and perhaps instead of the
ribbon a same-size "Zooniverse Team" banner could be used. But I think
that's different from the general case.
