### ISSUE TITLE
Unknown error, no projects loading 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#5771]
I'm getting an odd error when trying to go a Zooniverse project page, so I thought I should post it here. 

<img width="1312" alt="Screen Shot 2020-07-21 at 11 27 43 PM" src="https://user-images.githubusercontent.com/753325/88113546-e29be300-cba9-11ea-9b2b-5bce0ac1e6e1.png">

When you go to the Zooniverse main project page, I get the site saying there are no projects. 

<img width="1230" alt="Screen Shot 2020-07-21 at 11 27 13 PM" src="https://user-images.githubusercontent.com/753325/88113569-f0516880-cba9-11ea-8791-ebcf1a4cc340.png">

Not sure if this a scheduled outage or something known. I haven't seen any messages on the Zooniverse social media accounts.

**Comment by lcjohnso** [comment]
Hi @mschwamb -- The site is experiencing an outage.  Please see https://status.zooniverse.org/ for updates.
