### ISSUE TITLE
Do we have the option for universal "Zooniverse Team" role label on Talk?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#578]
I've found it very useful when members of the Zooniverse staff, especially myself, carry a tag of "ZOONIVERSE TEAM" that applies to all Talks. It's much clearer than "Admin" or such.

This feature was not in the current talk, but was hacked specially to allow for myself and other staff to have that tag.

Is this feature in the new Talk yet?

**Comment by aweiksnar** [comment]
I'm working on role displays right now and will definitely add that if it's possible

**Comment by DarrenMcRoy** [comment]
Please do!
