### ISSUE TITLE
Classify page scrolls to top after user clicks 'Done' in Chrome

### ISSUE THREAD

**Issue by sktw** [zooniverse/Panoptes-Front-End#5781]
This [issue](https://www.zooniverse.org/talk/17/1533848) has been raised on the Zooniverse Troubleshooting forum.

I think that this issue is related to element focus as suggested by @srallen, but not due to the browser scrolling to a newly focused element. Instead, it seems that Chrome, or at least the latest version, scrolls to keep the *currently* focused element in view if the position of that element changes. Firefox (for example) doesn't seem to do this.

When the user clicks 'Done', the app updates the page for the next classification, resulting in a number of separate modifications to the DOM. One modification in particular removes all of the questions (the div with class `coverable-task-container` becomes empty). This results in the 'Done' button, which still has focus, jumping up to the top of the task container. If necessary, Chrome scrolls up to keep the button in view.

I've tested this in Rainfall Rescue and American WWI Burial Cards, and both show this behaviour.

## Steps to reproduce

- Navigate to classify page.
- In the developer tools set a DOM change breakpoint (subtree modifications) on the body element.
- Click 'Done', and step through the DOM modifications in the debugger.

**Comment by srallen** [comment]
@sktw thanks for your contribution. Using Chrome dev tools, you can setup an live expression to monitor which element currently has active focus: https://developers.google.com/web/tools/chrome-devtools/console/live-expressions

Any button that is clicked will receive focus as part of the click event, however, we also manually control focus when the new subject loads and as you observed, the task area re-renders with the start of the workflow. The exact element in the task area that receives focus depends on the task. So for Rainfall Rescue, the first text input is focused. 

The browser by default will scroll if `focus()` is called on an element which is not in view. What's happening in Chrome is that scroll is happening even both the Done button and the soon to be focused element is still in view:

![chrome-scroll](https://user-images.githubusercontent.com/5016731/90648437-20b71180-e1ff-11ea-987c-7cd5915ce219.gif)

The same in Firefox, as observed, does not scroll:
![firefox-focus](https://user-images.githubusercontent.com/5016731/90648900-b652a100-e1ff-11ea-9636-01f787dd9502.gif)

The scroll behavior on the focus event can be controlled by passing in a parameter (described here: https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/focus). So I have a local copy pulled down and I find and replace all instances of `focus()` being called with `focus({ preventScroll: true })` and we would expect Chrome to not scroll on the focus event.

With the scroll behavior disabled in Chrome:
![chrome-still-scrolls](https://user-images.githubusercontent.com/5016731/90651026-337f1580-e202-11ea-895c-a7dc7927de67.gif)

With scroll disabled in Firefox:
![firefox-scroll-disabled](https://user-images.githubusercontent.com/5016731/90651064-3d087d80-e202-11ea-9bbf-d9f466f51bb1.gif)

So, we're left with the question of why does Chrome scroll with focus scroll disabled. 

I've tried your suggestion using the DOM change breakpoint on the body element and I do observe the stepped through changes as you describe. Your hunch seems like the right one, so I've googled around some again and FINALLY someone is talking about this: https://www.reddit.com/r/chrome/comments/i98sta/has_scroll_anchoring_behavior_changed_for_focused/

I've added `overflow-anchor: none;` to the container element of the task navigation area, and I think this gets us back the behavior previous to Chrome v84. I'm going to push up a staged branch for you and the other volunteers who've reported this to try. Thanks again!

**Comment by eatyourgreens** [comment]
We use the `autofocus` attribute to change the focus for question tasks, so you could also try removing that to see if it's triggering this bug. `focus()` is only called during drawing tasks (from memory.) Hardcoding `autoFocus` to `false` would remove it in React, I think.

**Comment by srallen** [comment]
> focus() is only called during drawing tasks (from memory.)

It's called for question tasks, text tasks, and dropdown task.

**Comment by srallen** [comment]
@sktw here is a staged branch to try out: https://pr-5784.pfe-preview.zooniverse.org/?env=production

**Comment by sktw** [comment]
The fix works - when stepping through the DOM modifications as before, the page doesn't scroll when the questions are removed, and only scrolls when focus is set on the first input, as intended. Useful to know that this behaviour can be controlled with css - thanks.

**Comment by srallen** [comment]
@sktw thanks again for your contribution. We've merged the CSS change and it should be available on production in a few minutes.
