### ISSUE TITLE
Japanese language translations for the Classify page

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5802]
Sent in by Michiharu Hyogo, a translator for Disk Detective.

>In this image, you can see a red circle drawn for each of those words that can not be translated with our normal procedure and I have written a number right next to these circles.
So, what I would like to ask you is would it be possible to replace each of those words inside the circles into Japanese?
I list those Japanese words to be replaced here.
If, for example, it says 2. "分類する", then can you replace this word (分類する) with a one already inside a red circle which is located right next to where it says 2?(on the actual site)

1. ”プロジェクト概要"
2. "分類する"
3. "トークページ"
4. "コレクション"
5."タスク"
6."チュートリアル"
7. "フィールドガイド" (Please watch out for this one very carefully. Can you see the character "ー" within this word? Since this word is written vertically on the DD site, this "－" character also becomes vertical, like " | ". Does it make sense? )
![Screenshot of Disk Detective mapping parts of the interface to the translations provided.](https://user-images.githubusercontent.com/59547/92715029-d71c9b00-f354-11ea-882b-082eddda26e1.png)

**Comment by lcjohnso** [comment]
Note: I'm following up as part of that [Freshdesk ticket](https://zooniverse.freshdesk.com/a/tickets/5228) to see whether they would be willing to create a wider Japanese translation of Zooniverse platform content.
