### ISSUE TITLE
High severity security vulnerability in papaparse

### ISSUE THREAD

**Issue by nciemniak** [zooniverse/Panoptes-Front-End#5805]
- Relevant security alert: https://github.com/zooniverse/Panoptes-Front-End/network/alert/package.json/papaparse/open
- Dependabot version bump PR: https://github.com/zooniverse/Panoptes-Front-End/pull/5794

`papaparse` is a CSV parser for javascript. More information available at [npm package page](https://www.npmjs.com/package/papaparse).

**Comment by eatyourgreens** [comment]
Closed by #5794.
