### ISSUE TITLE
Field Guide: background opacity not 100%

### ISSUE THREAD

**Issue by ErikOstlund** [zooniverse/Panoptes-Front-End#5811]
**Package** `lib-classifier`

**Describe the bug**
When the Field Guide is open, the background opacity appears to be less than 100% which means users can see items behind the Field Guide such as Menu items and Task component items.
![image](https://user-images.githubusercontent.com/9533007/93135309-baa79800-f69f-11ea-88ca-71362245574d.png)

**To Reproduce**
1. Go into any project
2. Click on 'Get Started' or 'Classify' from the top menu
3. Click on the 'Field Guide' tab (on the right side of the screen)
4. See issue

**Expected behavior**
I expect to see no transparency within the Field Guide. When the Field Guide is open, users should not be able to see UI items that are directly behind/under.

**Suggestion**
Ensure background colors of the Field Guide are at 100% opacity.

**Comment by ErikOstlund** [comment]
@beckyrother Is the background of the Field Guide intentionally transparent (slightly)? Is this a bug?

**Comment by beckyrother** [comment]
Oh strange! Not sure why that would be. You're welcome to fix, thank you!
