### ISSUE TITLE
Potential focus issue impacting line drawing tool, invert button

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Panoptes-Front-End#5813]
Reported via Talk (link to thread [here](https://www.zooniverse.org/projects/benjamin-dot-richards/oceaneyes/talk/2723/1623797?comment=2635982&page=1)): user cannot invert image, and whenever they try to use the workflow's line drawing tool, the Pan&Zoom toggle from cursor to pan mode.  User uploaded a video of the problem in action -- see [here (Dropbox)](https://www.dropbox.com/sh/u3849ha4m05kmga/AACW3kwDccYJwDB0D7qp_ywFa?dl=0).

## Expected behavior
User clicks on subject image to start drawing a line with a line tool.  User clicks the invert image button to alter the appearance of the subject image.

## Current behavior
Using Chrome 85 on Windows 10, the user clicks on subject image, and the UI appears to select / try to drag the subject image and the Pan&Zoom tool toggles from cursor to pan mode.  Also, the user clicks the invert image button and nothing happens.

## Steps to replicate
I was not able to reproduce this behavior on Browserstack using Chrome 85 on Windows 10 mode.

**Comment by yshish** [comment]
Today (for the first time) I've experienced the same troubles in Plankton Portal - I always use the invert button for all images as I cannot recognize plankton on white background properly and the zoom tool is necessary for recognizing tiny organisms and seeing details. But when I'm in the invert mode, the zoom tool and placing marks into the image doesn't work. When I switch the colours back to the original I am allowed to zoom in and place marks. But when I switch back using the 'invert' button, all marks disappear and the image appears zoomed out. I tried reloading the page but it didn't help. I cannot work on the project with that bug. :(

Using Chromium 91 on Ubuntu (all up to date). Let me know if you wanted me to test it on other browsers or under Win.

**Comment by yshish** [comment]
Screenshot what it looks like (including browser console error list) - all the tools seem clickable but nothing happens after clicking on them.
Even when I try place a mark within the image and click on the invert button to get back to the original colours, the mark isn't there. It only works when I'm in the original colour mode (white background).
![Screenshot_2021-07-14_11-22-15](https://user-images.githubusercontent.com/7211888/125597941-e0f43fd2-074b-44ec-8239-806006d14bce.png)

**Comment by eatyourgreens** [comment]
I can reproduce that same bug on another project: [OceanEyes](https://www.zooniverse.org/projects/benjamin-dot-richards/oceaneyes/classify). Zoom in and draw a line, then press invert. All zoom transforms are removed and the drawn line vanishes. Turn invert off and the zoomed-in image is restored, with my drawn line.

Could be related to the changes I made to the invert button, the other day, in #5985.

**Comment by eatyourgreens** [comment]
Hi @yshish and apologies: that was my fault. I made some changes to add the Invert button to the new Galaxy Zoo: Weird and Wonderful project but those changes had unexpected side effects on other projects. Plankton Portal should be fixed now.

**Comment by yshish** [comment]
@eatyourgreens NP. I can confirm it is working now. Thanks for the quick fix! :1st_place_medal:
