### ISSUE TITLE
Tutorial tab in PB only shows 20 tutorials max

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#5823]
In the tutorial tab of the project builder you can only view/edit up to 20 tutorials max. This isn't (shouldn't be) an issue for many projects, but it does affect at least one launched project - see https://www.zooniverse.org/lab/8361/tutorial

The order of the tutorials displayed also seems to be somewhat random.

**Comment by srallen** [comment]
I think the last time this came up we decided to `wontfix` because if a project has more than 20 workflows, then they should seriously consider breaking out into more than one project and possibly use an organization.

**Comment by srallen** [comment]
@mrniaboc is it ok this closes as `wontfix`?

**Comment by mrniaboc** [comment]
Sure thing!

**Comment by eatyourgreens** [comment]
>The order of the tutorials displayed also seems to be somewhat random.

I think the default sort order changed when we upgraded Postgres somewhere along the way. Setting it back to sort by ID descending (newest tutorials first) should be possible.
