### ISSUE TITLE
[minor bug] Project Builder - cannot create new Subject Set, "Validation failed: Display name has already been taken"

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#5837]
## Minor Functionality Bug - Project Builder

Original report and solution: https://zooniverse.freshdesk.com/a/tickets/6002
Apparently a repeat of #1923

User reported that they cannot create a new Subject Set on the project editor. Turns out there's a small bug in the project builder with an easy workaround.

**Issue:**
- user goes to the Subject Set management page - e.g. https://www.zooniverse.org/lab/XYZ/subject-sets
- user clicks on the (create) "New Subject Set" button
  - Expected: a new Subject Set resource is created.
  - Actual: failure, and error message: _"Validation failed: Display name has already been taken"_

**Analysis:**
- When a new Subject Set is created, it's created with the default name of "Untitled subject set"
- However, if the project **already has an empty Subject Set named "Untitled subject set",** it fails.
- The new Subject Set can't be created, because _Subject Set names need to be unique._

**Solution:**
- Delete the empty Subject Set titled "Untitled subject set".
- Alternatively, rename the Subject Set to absolutely anything else.

### Status

Minor issue, easy workaround.

I'm closing this issue immediately since it's only here for documentation for future devs to find... but if someone wants to take on a more permanent solution (i.e. unique-ified Subject Set names, e.g. _"Untitled Subject Set 2020-11-10 21:24"_ ) please re-open this.

**Comment by eatyourgreens** [comment]
See also #5701. 

It looks like the default set name is set here: https://github.com/zooniverse/Panoptes-Front-End/blob/21cf42485929a62938112d5e2d4bca1a6702b00e/app/pages/lab/subject-sets-container.jsx#L5
