### ISSUE TITLE
Project Builder data export crashes with an uncaught error

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5848]
## Expected behavior
The data export page should load for any project.

## Current behavior
The data export page for I Fancy Cats dies with an uncaught error, which crashes the whole project builder in the browser.
https://master.pfe-preview.zooniverse.org/lab/335/data-exports
```
Uncaught TypeError: Cannot read property 'state' of null
```

**Comment by shaunanoordin** [comment]
Code changes look legit, `exported?.metadata` is straightforward and sensible check to add. Let me run some quick tests
