### ISSUE TITLE
URGENT: http://preview.zooniverse.org/panoptes/#/ down?

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#585]
Hi,

Is http://preview.zooniverse.org/panoptes/#/ down? I can't log in and my projects aren't showing up.

Thanks, Tom

**Comment by camallen** [comment]
@twhyntie - yep this was a breaking change on the backend. I'm working on it.

**Comment by twhyntie** [comment]
Cool, thanks.

**Comment by camallen** [comment]
@twhyntie - Seems there are breaking changes in the front end too, might be a while before we get this back online. pinging @brian-c

**Comment by camallen** [comment]
For what it's worth logging in reset some cached responses with the missing login field.

**Comment by camallen** [comment]
@twhyntie - I'm pretty sure it's all back online now. Can you check and close this issue if you're happy.

**Comment by brian-c** [comment]
I'm messing with it, unsuccessfully. My user login field is coming back null. That's breaking things.

Signed out I think it's okay.

**Comment by camallen** [comment]
@brian-c just migrated you manually, login field should be set now.

**Comment by twhyntie** [comment]
@camallen working for me now - thanks!
