### ISSUE TITLE
audio subjects having an overlay in Talk - is this expected or a bug? 

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5854]
Note: not a priority effort, but noting for reference if there's work on audio subjects in the future. 

## Expected behavior

The audio subject's image is the same between the classify page and the Talk page view. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

See https://www.zooniverse.org/projects/lydiakatsis/forest-sounds/talk/3495/1725038 vs https://www.zooniverse.org/projects/lydiakatsis/forest-sounds/classify

Is there a reason in Talk there's an overlay on part of the subject image? The subject still plays the audio, which is key, but it's helpful to see the full subject image as well. Will be good to know what's the reason for the semi-transparent overlay. 

## Additional information

- **Operating system:**
Mac Air. MacOS Majave v10.14.6
- **Browser:**
Chrome Version 87.0.4280.67

**Comment by eatyourgreens** [comment]
The classifier uses SVG's `<image>` element. Talk uses HTML `<img>` to display subjects, which causes the scaling problem here, where the image does not fill the same area as the SVG progress bar used by the audio player.

**Comment by trouille** [comment]
Thanks for giving that context/information -- helpful to know where the difference is coming from. I shared w/ the Forest Sounds research team and they responded, "That's ok about the images in Talk - its not critical, I just thought I'd point it out.". Further confirmation that it's not pressing/critical. In our next iteration on Talk, we'll have this on the radar.
