### ISSUE TITLE
Future request - allow pngs instead of just jpegs for media library

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#586]
low in the queue - but my understanding is that pngs can have transparent backgrounds, where as most jpegs don't. All the media library images were converted to jepgs so they had dark backgrounds where before as a png would have allowed the background through. it would be nice in the future if png would be supported. 

In the png version I had the background showing through in the jpeg version it's back in those areas

![](https://panoptes-uploads.zooniverse.org/production/project_attached_image/d954d1bf-3702-4770-b204-6b3ad3b08c9f.jpeg)

**Comment by brian-c** [comment]
Tied in with #655.

**Comment by mschwamb** [comment]
@brian-c does this mean the media library supports pngs now?

**Comment by brian-c** [comment]
Yes indeed.

**Comment by mschwamb** [comment]
sweet. thanks
