### ISSUE TITLE
Set up FEM redirect for Engaging Crowds RMG project

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#5861]
https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service should show the FEM view of the project instead of PFE (just like PH-TESS).

**Comment by zwolf** [comment]
Updated the FD config to pass the project root and classify pages to the FEM app.

**Comment by eatyourgreens** [comment]
I’ll need to update the routing config in PFE too.

**Comment by eatyourgreens** [comment]
https://github.com/zooniverse/Panoptes-Front-End/blob/16e15bf117ba2e2ccf2a63255f039474380107fe/app/router.cjsx#L152-L153

**Comment by eatyourgreens** [comment]
We’ll also need to support URLs like this, which aren’t supported at the moment. https://www.zooniverse.org/projects/msalmon/hms-nhs-the-nautical-health-service/classify/workflow/16926/subject-set/82738
