### ISSUE TITLE
Thumbnails not showing up in survey task on chimpandsee.org, snapshotsafari.org, etc.

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5867]
Note - posting this issue during the holidays. We'll take a look as a team after the holiday break (e.g., post Jan 4, 2021).

## Expected behavior

When viewing a workflow like the Snapshot Grumeti survey task workflow on https://www.zooniverse.org/projects/meredithspalmer/snapshot-grumeti, expect to see the thumbnail images when you filter to a small enough number of choices. Similarly, expect to see the thumbnails on the survey task Species ID workflow of https://www.zooniverse.org/projects/sassydumbledore/chimp-and-see/classify. Similar for GravitySpy.org. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

Currently the survey task is not showing thumbnail images of the options to choose from as expected. 

See 
<img width="1302" alt="Screen Shot 2020-12-23 at 8 10 43 PM" src="https://user-images.githubusercontent.com/4975655/103051091-93444f00-455b-11eb-937a-0798dc3cd866.png"> and 
<img width="1258" alt="Screen Shot 2020-12-23 at 8 15 27 PM" src="https://user-images.githubusercontent.com/4975655/103051107-9d664d80-455b-11eb-9250-53e48658aa76.png">

## Steps to replicate

Visit GravitySpy.org and go to level 1. 

## Additional information

- **Operating system:**

MacAir macOS mojave, version 10.14.6

- **Browser:**
Same behavior on both chrome (Version 87.0.4280.88 ) and Safari (Version 14.0.2).

**Comment by eatyourgreens** [comment]
Probably related to those images now being served from Azure.

**Comment by eatyourgreens** [comment]
Here's an example of one of the broken URLs (from Chimp & See.) It's returning a `415: unsupported media type` response.
https://thumbnails.zooniverse.org/500x500/panoptes-uploads.zooniverse.org/production/workflow_attached_image/e2b07978-979c-4f43-bbd6-72b1179abdbc.jpeg

**Comment by eatyourgreens** [comment]
This URL works, so it looks like the problem is the `/production` in the path.
https://thumbnails.zooniverse.org/500x500/panoptes-uploads.zooniverse.org/workflow_attached_image/e2b07978-979c-4f43-bbd6-72b1179abdbc.jpeg

**Comment by srallen** [comment]
The thumbnails failing might be interfering with the survey task. See #5869
