### ISSUE TITLE
Add translation for Field Guide label in pop-out view

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/Panoptes-Front-End#5886]
Simliar to https://github.com/zooniverse/Panoptes-Front-End/pull/5706, a project team highlighted that the "Field Guide" label that appears at the top of the pop-out view/frame for the Field Guide is not translated.  

Request: register this instance of "Field Guide" in the locale files to make it translatable. Here is the relevant code where that text element is located:
https://github.com/zooniverse/Panoptes-Front-End/blob/4ef5acdeec5fb9124eb12935b9cca24651b642a4/app/pages/project/field-guide.cjsx#L100

Note: we can use the existing project.fieldGuide locale entry (e.g., [here](https://github.com/zooniverse/Panoptes-Front-End/blob/4ef5acdeec5fb9124eb12935b9cca24651b642a4/app/locales/fr.js#L53)) to populate the locale-specific translations, where available.

**Comment by eatyourgreens** [comment]
Hi Cliff, just double checking. The translation that’s needed here is the same text that’s used for the pull-out tab on the right of the window here?

![Screenshot of Every Name Counts, showing the German label for the field guide.](https://user-images.githubusercontent.com/59547/107124920-7a3ef580-689e-11eb-93a0-81908b3582f5.jpeg)

**Comment by lcjohnso** [comment]
@eatyourgreens -- Yes, that's correct!  The existing project.fieldGuide translation is [L53](https://github.com/zooniverse/Panoptes-Front-End/blob/0d12952ef344427b6e906de338ea4eabcd6e1a97/app/locales/de.js#L53) in the German locale file (de.js), same as it is in the French locale file (fr.js).
