### ISSUE TITLE
Create set of Zooniverse-wide Talk boards

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes-Front-End#589]
I'm assuming this needs to be done by the zooniverse user.

@DarrenMcRoy Thoughts on what those boards should be? Something like Chat, Science, Education, and Help maybe?

**Comment by DarrenMcRoy** [comment]
Just making sure... we mean "boards for the Zooniverse Talk/Zooniverse Discuss," not #570 -- right?

**Comment by chrissnyder** [comment]
Correct.

**Comment by DarrenMcRoy** [comment]
I'd start with these five:

*Chat* – Talk about anything and everything here!

*Zooniverse* – For all discussion about the Zooniverse as a whole.

*People-Powered Research* – Chat about people-powered research, including citizen science, collaboration, open research, crowdsourcing, etc.

*Education* – Everything on using Zooniverse and ZooTeach in the classroom and as an educational tool.

*Technical Support* – Having issues with Zooniverse outside of a specific project? Let us know.

Thoughts? Thanks!

**Comment by aweiksnar** [comment]
@DarrenMcRoy From that list I'd vote to change *Technical Support* to *Troubleshooting* or *Q & A* or something along that realm. In my mind tech support is something that comes strictly from a company delivering a service, whereas troubleshooting/Q &A/something-else may promote more answers from peers

**Comment by DarrenMcRoy** [comment]
I like "Troubleshooting," then. :+1:

**Comment by DarrenMcRoy** [comment]
One more that I thought of:

*Project Building*  – Setting up your own project? Talk about Zooniverse's Project Builder here.
