### ISSUE TITLE
Minimum & maximum number of allowed drawn polygons should be respected

### ISSUE THREAD

**Issue by tingard** [zooniverse/Panoptes-Front-End#5923]
## Expected behaviour
When creating a polygon drawing workflow, when a maximum allowed number of polygons is provided, a volunteer should be allowed to place up to and including that maximum number.

## Current behaviour
The final polygon cannot be continued and completed beyond the initial marking (i.e. after placing the first point)

## Steps to replicate
- Set up a drawing tool project
- Define a single polygon tool
- Set Max to 2
- Test the workflow and attempt to draw 2 polygons

 Example workflow 18128:
![image](https://user-images.githubusercontent.com/11770176/112974189-17edcd00-914a-11eb-8c89-8f4b5494ccad.png)

What's not shown in the image is that the "not allowed" cursor is displayed and that it's impossible to continue to place polygon points.

Not a massive problem at the moment, but perhaps something to be aware of!

**Comment by eatyourgreens** [comment]
Same bug as #4674, I think. This is fixed in the new classifier.

**Comment by tingard** [comment]
Ah good spot - apologies for not checking first

**Comment by eatyourgreens** [comment]
No worries. This is a long-standing bug that's been reported by a few project owners.
