### ISSUE TITLE
Bugs with the workflow copying button in the project builder

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5960]
This is a follow on from #4733 to list properties that are missed or incorrectly copied when copying a workflow.

- `workflow.steps` is missed for transcription task workflows.
- `workflow.prioritized` is missed for workflows using sequential subject selection.
- `workflow.grouped` is missed for workflows using grouped subject selection.
-  `workflow.primary_language` is incorrectly set to the user's current locale, rather than the primary language of the original workflow. That should also be the same as the primary language of the parent project.

**Comment by eatyourgreens** [comment]
We can fix these in the lab function that copies workflows, but long-term it would be better to use the API to copy workflows.
https://github.com/zooniverse/Panoptes-Front-End/blob/45399f3267f45fa1d67d5bcd162b4050ed11e5ac/app/pages/lab/workflow-create-form.cjsx#L27-L34

**Comment by lcjohnso** [comment]
Great to see the `primary_language` catch here: that explains #5822
