### ISSUE TITLE
NestQuestGo Organization landing page not loading for windows machine (could be an unsupported browser; not sure)

### ISSUE THREAD

**Issue by trouille** [zooniverse/Panoptes-Front-End#5964]
## Expected behavior

https://www.zooniverse.org/organizations/brbcornell/nest-quest-go should load as expected. 

## Current behavior
_Please include any error messages from the browser console and/or screenshots_

https://www.zooniverse.org/organizations/brbcornell/nest-quest-go loads as expected for MacOS with Chrome and Safari supported browser versions.

A participant emailed me with the following screenshot on their windows machine (but wouldn't provide their browser version; so it may be that this is an issue with old browser that we no longer support). 

![image](https://user-images.githubusercontent.com/4975655/120506451-8c7ffa80-c38b-11eb-855b-385daa473eec.png)

## Additional information

- **Operating system:**
- Windows

- **Browser:**
- Unknown

**Comment by eatyourgreens** [comment]
That error message is the Panoptes client's generic response when it can't parse the response.
https://github.com/zooniverse/panoptes-javascript-client/blob/59c34ba4a38c8a38a841cedd4dd259032875f0e9/lib/api-client.js#L35-L40

**Comment by srallen** [comment]
We should ask for the exact URL the user is putting into the browser's location bar as well.

**Comment by trouille** [comment]
Another participant emailed with the same error, but for https://www.zooniverse.org/projects/benjamin-dot-richards/oceaneyes

In seeing their email addresses, they're both Verizon. So I've reached out to Verizon IT to see if something is going on at their end. I'm going to close this for now, since my sense is it's going to be something to do with Verizon. I'll reopen if it's not.
