### ISSUE TITLE
this.restartTimer is not a function

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#5982]
The `ActiveUsers` component sets a 60s timer when it mounts. Open Talk and wait 60s for that timer to run, and you'll see this error thrown in the console.

`TypeError: this.restartTimer is not a function`
![Screenshot of the browser dev console. showing that error being thrown on the Talk home page.](https://user-images.githubusercontent.com/59547/124786568-ba82cc80-df3f-11eb-8935-3ff836066b4a.png)

The error is thrown on line 75 here, in the `ActiveUsers` component.
https://github.com/zooniverse/Panoptes-Front-End/blob/f08ad305a2e36b5812dac026cb4325e52e780aeb/app/talk/active-users.jsx#L74-L79

Right now, that error is causing our CI tests to fail on all PRs, because they wait 60s for the timer to finish running.

**Comment by eatyourgreens** [comment]
If I fix the function binding locally, the tests run without error but never exit. They get stuck in a loop of constantly starting new timers when each timer expires.

**Comment by camallen** [comment]
I believe this was fixed by #5981 - feel free to reopen if not.
