### ISSUE TITLE
csv exports and spam folders

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#600]
Have just discovered that the csv exports I've requested have been put by my email provider into my spam folder. Of course, by the time I figured this out the links had expired.

I will request another one, but more generally is it possible to:

  - increase the expiration time to something longer than an hour? (That was perfect for our Nepal project but for most projects I expect exports will happen less frequently.)
  - add a note to the front end that the user should add no-reply@zooniverse.org to their address book to prevent mistaken IDs as spam? (Or similar...)

**Comment by camallen** [comment]
@vrooje you should be able to download the last generated one from the link following the `Request new data export` button. If you want a fresher version then just press the button.

That email address is what we send all zoo emails with. I think there's another reason why it's being detected as spam. Was this gmail?

https://support.google.com/mail/answer/81126

**Comment by vrooje** [comment]
It wasn't; it was Yahoo!. I marked it as not-spam and the next one came through fine.

Clicking the link where the "[time elapsed] ago" text is to get the latest copy: forehead slap moment. Despite the fact that dates and times are often used as links to originals on Facebook, Twitter, etc., I still don't find this intuitive. We should definitely point that out in the how-to docs!

**Comment by astopy** [comment]
@vrooje Can you email me the full headers from one of the messages which was marked as spam?
