### ISSUE TITLE
'Unknown file type' for some Black Hole Hunters subjects

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#6002]
I'm not sure if these were test subjects, but a couple of my Black Hole Hunters recents show up as 'unknown file type' errors.

![Screenshot of my recent classifications, showing two Unknown FIle Type errors in the subject previews.](https://user-images.githubusercontent.com/59547/130645265-b71f1c90-0b11-4ff4-a480-08e6e2a67f0a.png)

Links for those subjects are:
https://www.zooniverse.org/projects/hughdickinson/superwasp-black-hole-hunters/talk/subjects/63959766
https://www.zooniverse.org/projects/hughdickinson/superwasp-black-hole-hunters/talk/subjects/63959771

**Comment by hughdickinson** [comment]
Thanks for the heads-up. The subjects should all have jpeg counterparts for talk etc, but clearly these don't! I'll try to work out why. Might well be that they were part of an old set of subjects for testing.

**Comment by eatyourgreens** [comment]
I think they both came up while I was classifying today (I'm not 100% sure) so they might be in the set that's live at the moment.

**Comment by hughdickinson** [comment]
Found the offending subjects and replaced them, so the subjects you found will either not be fixed themselves or cease to exist at some point. Tried adding another location with the Panoptes Python client but there's a bug/feature that stops that approach from working.

**Comment by eatyourgreens** [comment]
Sounds good. Those two subjects have classifications now, so they won’t be deleted. I don’t think they’ll be shown to anyone else, though, if they aren’t linked to a subject set any more.
