### ISSUE TITLE
Updating pt.js

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#6005]
A P4 translator has completed translating the pt.js file that had incomplete translations. Here's the updated file now fully translated https://www.dropbox.com/s/cd3z7x88kvq0aso/pt.js?dl=0

**Comment by lcjohnso** [comment]
Hi @mschwamb -- Could you have your translator take a look at this staging version of the platform (https://pr-6006.pfe-preview.zooniverse.org/?env=production&language=pt -- with language specific query params) and let us know if everything looks OK?

**Comment by lcjohnso** [comment]
Hi @mschwamb -- This new translation is ready to go.  Unless you or your translator have further feedback / comments, I'll plan to merge the update this week (Wednesday?).

**Comment by mschwamb** [comment]
The font used in Zooniverse does not include the lowercase c-cedil (ç)  It  always shows it as upper case.  Not pretty.

Workflow initial page:

    "DO YOU NEED HELP WITH THIS PAGE"  pop-up window:
        Untranslated button "CLOSE"

Workflow's 2nd window

    Untranslated button "MORE" 
    Untranslated text "Your classification"

**Comment by lcjohnso** [comment]
@mschwamb -- I don't think I'm seeing the same issue with the lowercase c-cedil (ç).  e.g., here's the top of the Planet Four about page where I see a few lowercase c-cedil characters:
<img width="884" alt="Screen Shot 2021-09-15 at 12 58 53 PM" src="https://user-images.githubusercontent.com/2006101/133485337-026a5631-9256-4a56-8b2b-1f8fb1e5c7e0.png">

As for the other items you noted -- unfortunately, I don't think these elements are currently translatable (i.e., they're likely hardcoded).  I'll follow-up with the front end team about these at a later date, but won't let these missing elements hold up the merge / correction of this PR.

**Comment by mschwamb** [comment]
Okay. Then merge away I think. Thanks.
