### ISSUE TITLE
username case sensitivity in project urls

### ISSUE THREAD

**Issue by drphilmarshall** [zooniverse/Panoptes-Front-End#604]
Here's a bug for you:

This link takes you to the SpaceWarpsRings demo that we are trying to impress some customers with:

http://demo.zooniverse.org/panoptes-front-end/#/projects/aprajita/spacewarpsrings

However, in my "build a project" page, when I click "view" on the Space Warps Rings project, I am pointed to this  link, which does not work:

http://demo.zooniverse.org/panoptes-front-end/#/projects/Aprajita/spacewarpsrings

    Error: Couldn't find project Aprajita/spacewarpsrings

I guess the code should lower-case this URL before using it?

**Comment by camallen** [comment]
WIll be fixed by this, https://github.com/zooniverse/Panoptes/pull/998

**Comment by drphilmarshall** [comment]
Splendid, thanks @camallen. Looks like a pretty pervasive error - for example, when I click the "Get Started" button the on Space Warps Rings landing page, I get a broken link. Try it:

http://demo.zooniverse.org/panoptes-front-end/#/projects/aprajita/spacewarpsrings

**Comment by edpaget** [comment]
@camallen's change should fix both of those.

**Comment by drphilmarshall** [comment]
Yep! Thanks @camallen :-)
