### ISSUE TITLE
science page help text refers to externally hosting images instead of the media uploader

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#605]
'This page is for you to describe your research motivations and goals to the volunteers. Feel free to add detail, but try to avoid jargon. This page renders markdown, so you can format it and add images (externally hosted for now) and links. The site will show your team members with their profile pictures and roles to the side of the text.' Should be changed to mention the media uploader.

**Comment by mschwamb** [comment]
@chrissnyder  I think this should be first release. There's now the media uploader, but the help contact is not updated in the project builder

**Comment by mschwamb** [comment]
@aliburchard I think this also needs updating in the project builder too?

**Comment by aliburchard** [comment]
Agreed -- on the Science Page, change "(externally hosted for now)" to "via the Media Library" 

Not sure who is making these changes atm - maybe @chrissnyder or @srallen who have updated help text previously.
