### ISSUE TITLE
Should the collections tab show up if  you're not logged in?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#606]
Here's what you get if you're non-logged in 

![screen shot 2015-06-19 at 3 58 35 am](https://cloud.githubusercontent.com/assets/753325/8240896/7c7c44f6-1638-11e5-8416-3e709af33ff6.png)

Since you can't collect anything without a registered account, should this tab only be visible if you're logged in with your zooniverse id?

**Comment by edpaget** [comment]
Collections can be public. At the moment the front end is creating all collections as private which means you won't see any ones but your own on that page. 

For example see the test server where I've created one public collection: http://demo.zooniverse.org/panoptes-front-end/#/collections

**Comment by mschwamb** [comment]
Should there be a line  for non-logged in users to say that they'll need to log-in to create collections?

**Comment by edpaget** [comment]
There could be, but currently you don't create collections from that page.

**Comment by mschwamb** [comment]
okay. thanks . Though on the demo site when I log in you're public collection and my collections are mixed together which is kind of confusing to me at least, but that could just be me. Cool about public collections though. Sounds like a neat  feature

![screen shot 2015-06-19 at 4 20 36 am](https://cloud.githubusercontent.com/assets/753325/8241210/95bbadd8-163a-11e5-8f32-54c9df85cd28.png)
