### ISSUE TITLE
Adding project name to the the collections when displayed in the Collections Tab

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#607]
Since there are multiple projects showing wildebeest and galaxies from looking at the front card of the collection it's unclear what project they might belong to. I think it would be helpful if project name could be listed as well. 

![screen shot 2015-06-19 at 3 58 22 am](https://cloud.githubusercontent.com/assets/753325/8241024/5402c51c-1639-11e5-88e6-ce59ff77c8ea.png)

**Comment by edpaget** [comment]
I'm planning to add a sort by project option and improve how the favourite collections work, but yeah they should include the project name.

**Comment by mschwamb** [comment]
sounds great. Looks like a cool feature

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
