### ISSUE TITLE
If you navigate from a project with talk boards to one that doesn't using the project talk side bar then the old project's boards stay with new project's background

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#613]
If you use the project Talk side bar to move to a project's talk without discussion boards, it leaves the previous projects boards in place 

see screenshots below:

I made this boards and threads for P4: Terrains:

![screen shot 2015-06-19 at 6 05 51 am](https://cloud.githubusercontent.com/assets/753325/8243411/692c32c4-1649-11e5-9ccc-634ae19b643f.png)

Switched to Kitteh Zoo and the same P4: Terrains boards show

![screen shot 2015-06-19 at 6 05 37 am](https://cloud.githubusercontent.com/assets/753325/8243425/806d8f28-1649-11e5-861b-a8f6cd3c9e2e.png)

Same thing if I go to Snapshots at Sea

![screen shot 2015-06-19 at 6 05 27 am](https://cloud.githubusercontent.com/assets/753325/8243436/900d743e-1649-11e5-9a6a-bffc5fb49277.png)

**Comment by mschwamb** [comment]
I was on Firefox 38.0.5

**Comment by aweiksnar** [comment]
@mschwamb I've sent a PR that'll fix this issue. Out of curiosity, do you find the project linking in the sidebar to be useful? or is there anything else that you wish was in the side-bar?

**Comment by mschwamb** [comment]
Thanks. 

If I had two projects in the new system, then I think that could by handy to jump from one to the other without having to navigate urls especially since they're now very long zoonvierse.org/owername/blahblah/talk. I know there's a level of superuser that moves out of the classification interface to just talk and those people will I think find that handy if their participating in more than one project or want to jump to and from the larger zoonvierse talk. I think I saw that most used  hashtags get listed in that sidebar. 

I really did like in both 1.0 and 2.0 being able to see who was online and persuing that projects Talk. It shows up on the side bar on Talk 2.0, but I'm not sure what the rest of the Talk feedback taken over the last year felt about that.

**Comment by aweiksnar** [comment]
Cool, maybe I'll make it more tailored to a user's personal project list then. Putting recents projects in there (like it is now) could perhaps get people checking out new project talks, but maybe there's a better way to accomplish that. 

Also, I'll definitely make sure :hash: tags are in there

**Comment by mschwamb** [comment]
Maybe put recently classified up top with the Zooniverse wide one and then a line and the other projects?
