### ISSUE TITLE
Password reset via http://preview.zooniverse.org/panoptes/#/reset-password returns Error:{}

### ISSUE THREAD

**Issue by twhyntie** [zooniverse/Panoptes-Front-End#616]
Myself and a few of our team are trying to reset passwords on the preview site via http://preview.zooniverse.org/panoptes/#/reset-password and it's returning:

_Error:{}_

To the right of the **Submit** button.

(The account I am trying with is **twhyntie_lsc**.)

Is this expected at the moment?

Thanks, Tom

**Comment by camallen** [comment]
@twhyntie - I can't see a user account for that name on the preview site, it is however on the demo site. Looks like you created it specifically on panoptes. 

You can use your main zooniverse.org account now (it should be ported correctly, ping back if not). If you don't have a zoo wide account then create one via https://www.zooniverse.org/signup and let me know your account name and i'll port it over.

@brian-c getting a 422 via that json call means the email didn't match any known.

**Comment by twhyntie** [comment]
@camallen Cool, thanks. Re. the account that is indeed the case. No further action required for the accounts, but an error message to the effect of "Email address not found" would be super handy (don't know if needed by tomorrow though...).
