### ISSUE TITLE
can't access profile or signout button from project builder in Firefox

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#617]
low in the queue, but I thought I'd mention this quirk. If you're in the project builder if you try to click on the window for your profile or the signout button you can't. I move my mouse over my avatar and the window appears. But as I my move my mouse down to  select from the menu it disappears. 

I'm using Firefox 38.0.5 . It's not an issue is Safari or Chrome

**Comment by brian-c** [comment]
Can't reproduce; I believe this was fixed when the z-index of the header changed.

**Comment by mschwamb** [comment]
yep fixed now
