### ISSUE TITLE
Sign in and register cutoff on Chrome

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#618]
Not sure if anyone else is seeing this, but on my Chrome 43.0.2357.124 (64-bit) sign in and register are cut off . It's not a window resizing issue. I tried to adjust the width and nothing changed. 

![screen shot 2015-06-19 at 5 37 07 pm](https://cloud.githubusercontent.com/assets/753325/8250932/9b8ee278-16aa-11e5-92ae-1d22bcdaaa2e.png)

**Comment by srallen** [comment]
@mschwamb, I saw this and have a fix in PR #622
