### ISSUE TITLE
Warning - couldn’t find deployed commit in master

### ISSUE THREAD

**Issue by mbiesiad** [zooniverse/Panoptes-Front-End#6180]
## Expected behavior
It's fixed, not displayed to user.

## Current behavior
Warning message is displayed: `Weird: couldn’t find deployed commit in master`

## Steps to replicate
1. Open browser and DevTools (Console)
2.  Go to: https://www.zooniverse.org/projects
3. Check Console

## Additional information
Operating system: Windows
Browser: Chromium based

Screenshot:
![image](https://user-images.githubusercontent.com/18367606/192109007-72d38032-531f-41b1-9682-32e120eab144.png)

Best wishes,

**Comment by eatyourgreens** [comment]
This should have been fixed by #6196.
