### ISSUE TITLE
Uncaught (in promise) TypeError 

### ISSUE THREAD

**Issue by mbiesiad** [zooniverse/Panoptes-Front-End#6181]
## Expected behavior
It's secure for mentioned case and appropriate handled.

## Current behavior
`Uncaught (in promise) TypeError` occurs with `zooniverse.org`.

## Steps to replicate
1. Open browser and DevTools
2. Go to: https://www.zooniverse.org/ and https://www.zooniverse.org/projects
3. Check Console

## Additional information
Operating system: Windows
Browser: Chromium based

Screenshot:
![image](https://user-images.githubusercontent.com/18367606/192109717-c6586926-8c46-466b-b247-91499d6efcd9.png)

Best wishes,

**Comment by eatyourgreens** [comment]
Closed by #6196, I think.
