### ISSUE TITLE
Security - Mixed Content HTTP/HTTPS

### ISSUE THREAD

**Issue by mbiesiad** [zooniverse/Panoptes-Front-End#6186]
## Expected behavior
It's fixed and secure for mentioned case.

## Current behavior
Warning about Mixed Content (HTTP/HTTPS) is displayed.

## Steps to replicate
1. Open Chrome and DevTools
2. Go to: https://www.zooniverse.org/projects/zookeeper/galaxy-zoo/talk/1269/1766180?comment=3986202&page=32
3. Take a look at Console

## Additional information
Operating system: Windows
Browser: Chromium based

Screenshots:
![image](https://user-images.githubusercontent.com/18367606/192115143-012c2f97-2444-49ed-b63f-bcd12167e470.png)

![image](https://user-images.githubusercontent.com/18367606/192115173-e616063a-ad8f-4b80-b0f2-736f035b7812.png)

Best wishes,

**Comment by eatyourgreens** [comment]
I'm not sure we can do much about this. Someone has posted a Talk comment with an embedded HTTP URL for an image, which will trigger a warning since the page uses HTTPS. We could perhaps require HTTPS URLs in Talk comments.

**Comment by camallen** [comment]
we could require https URLs but not all web links run over the https protocol version. I think we need to accept the risk of user generated non secure protocol links here instead of forcing folks to provide secure links (which may not exist).

**Comment by camallen** [comment]
closing for now to keep this tidy but happy to keep the discussion going.
