### ISSUE TITLE
helpbox link weridness - goes to link but leaves up help box for internal webpages 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#620]
low in the queue, but I noticed a few projects are doing this- ie adding links to the help box.

 In the help box if there's a link that's internal to the site, then if you click it takes you there but while leaving the help box open. Not sure if it's possible to have the page open up in a new tab or if there's a way in markup to trigger that or a way that when you click the link the helpbox would disappear. 

Screenshot below - clicked on the science page link, and it brought up the science page while leaving the helpbox up

![screen shot 2015-06-19 at 6 25 28 pm](https://cloud.githubusercontent.com/assets/753325/8251670/0b840936-16b1-11e5-8215-a463aa6cc64d.png)

same behavior in chrome and firefox - haven't tried safari

**Comment by CKrawczyk** [comment]
To open link in a new tab you need to add `target="_blank"` to the html anchor tag. Markdown has not have a specific command for this, but you can enter the link as pure html like so:

```html
<a href="http://example.com/" target="_blank">Hello, world!</a>
```

**Comment by mschwamb** [comment]
thanks  @CKrawczyk  except it appears  html is not supported in this flavor of markdown so the above doesn't work. it just shows all the html on the helpbox when I copy it in

**Comment by aliburchard** [comment]
I've also got a few projects that have requested having links in the help pop-up that open in a new window, if there is any workaround that works...

**Comment by mschwamb** [comment]
Closing since the issue is  being actively sorted in #946
