### ISSUE TITLE
Workflow Editor - Task's 'Required' checkbox may incorrectly appear checked, when required=undefined

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#6214]
## Project Builder Bug

Affects: Workflow Editor -> Task Editor
Freshdesk Ticket: [13976](https://zooniverse.freshdesk.com/a/tickets/13976)

When a WF has multiple (single question) Tasks - and some Tasks are required but others not - the Task editor may incorrectly display an _un-required Task as required..._ **IF** the user had previously looked at a required Task.

(i.e. the "Required" checkbox becomes visually "locked" to true/checked/enabled, after you click on a  required Task)

...but then again, this may **only** affect older Workflows, which still have data set like `myTask.required = "true"` (string) instead of `myTask.required = true` (boolean)

### Analysis

The problem only occurs one way; you HAVE to select the required Task first, then select an un-required Task. This triggers two errors/warnings on the console:

_Received the string `true` for the boolean attribute `checked`. Although this works, it will not work as expected if you pass the string "false". Did you mean checked={true}_

and

_A component is changing a controlled input to be uncontrolled. This is likely caused by the value changing from a defined to undefined, which should not happen._

The first error is more pertinent, and kudos to Jim for spotting that discrepancy when I shared the Workflow resource JSON earlier.

I do think the "incorrect data type" problem is just causing the "locked Required checkbox" state, because I can't replicate the problem with newly created Workflows (new WFs use `task.required=true` (boolean) instead of a string)

Attached videos: in **pt1,** I select the T4 task. The 'required' checkbox is false.
https://user-images.githubusercontent.com/13952701/195670312-23ac3a7f-5418-44dd-9831-998a6cee8dc3.mov

In **pt2,** I select the T1 (required) task first, then the T4 task. The 'required' checkbox incorrectly shows as true.
https://user-images.githubusercontent.com/13952701/195670371-5fb27c59-aa8c-4943-917b-97d86a8e1ce5.mov

### Status

This is a bug affecting live projects, but only older WFs. Priority level = ⁉️ 

Quick fix for project owners (untested): go into your old Workflows. For each Required Task, click on the checkbox to un-check it, then click it again to enable it. The task should now use `task.required=true` (boolean)

Project Builder fix: maybe see if I can add a filter/adapter that turns old "true" values to true when the project owner looks at the Task 🤔 

I'm not sure if we need to go through the DB and find all older Worflows that use `task.required="true"` (string) and manually change them to the correct value

**Comment by eatyourgreens** [comment]
[React Forms](https://reactjs.org/docs/forms.html#controlled-components) describes controlled components.

**Comment by eatyourgreens** [comment]
If `task.required` is undefined, the checkbox may just show the last value that was set. 

Worse, if the value is set to “false”, which is truthy, the checkbox might show as ticked. 

Either way, project teams think an answer is required when it isn’t, leading to invalid classifications.

**Comment by shaunanoordin** [comment]
### Additional Notes

From Slack:

> Jim: On that workflow’s T4, task.required is undefined.
> Cliff: How is the property being set to undefined?

When a new single question Task is created, it defaults to `required=undefined`.

When that Task then has its .required value enabled, then disabled, it will correctly have `required=false`

Interestingly, a new text Task is created with required=false by default. I haven't checked the other Tasks.

> If `task.required` is undefined, the checkbox may just show the last value that was set.

This is basically correct, albeit with some oddness.

I tested this by setting up `T0.required=TRUE, T1.required=undefined T2.required=false` . Changing between the 3 tasks, T1 would always show TRUE.

When I flipped this to `T0.required=false, T1.required=undefined T2.required=TRUE` resulted in T1 always showing FALSE.

Strangely, T1's "required" checkbox seems to lock to whichever true/false value appears first. (Note that T0 always shows first when the Workflow editor loads)

**Comment by shaunanoordin** [comment]
## Issue Update

⚠️ Ah monkey nuts, this additional testing has proven that the issue will still affect **newer** Workflows, so I need to remove that +"only affects older WFs"_ qualifier

Previously, I was only able to replicate the problem when `task.required="true"` (string). Upon carefully revising my testing method (i.e. refresh the Project Builder page after making changes!), I can now replicate the problem even when `task.required=true` (boolean)

### Status

- I'm renaming the issue to _"Task's 'Required' checkbox may incorrectly appear as checked, when task.required= **undefined** "_ since this seems to be the core problem.
- I now think that the project builder needs a fix, medium priority at least. I'm going to look into this first thing tomorrow.

On the TODO docket:
- [ ] Single Question Task must have `required=false` by default, not `required=undefined`
- [ ] Required Checkbox should always show `required=undefined` as un-checked. (As per Jim's suggestion, will look into keying the checkbox to the Task, so the component just re-mounts on Task change.)

Do note that, as Jim pointed out on Slack:
> Setting defaults in the code would fix new workflow tasks, but not existing tasks in Panoptes.

This issue may require further follow up on the database side of things.

**Comment by eatyourgreens** [comment]
Here, the checkbox should probably use `value`, not `checked` (see the React Forms link above) and the value should default to `false`. 

https://github.com/zooniverse/Panoptes-Front-End/blob/86268223e8a4ddd7a652d16e74d60ff41822bf2f/app/classifier/tasks/generic-editor.cjsx#L92

You can also set `defaultValue` on React inputs, but I don’t know if that’s allowed on controlled inputs. I think it sets the default for an uncontrolled input.

**Comment by eatyourgreens** [comment]
That ‘required’ checkbox will probably need changing in each individual task editor component. Each task defines an Editor form to be used by the project builder.

**Comment by eatyourgreens** [comment]
One way to quickly add a default value to an object is to use the rest spread operator. 

```js
const taskWithDefault = {
  required: false,
  …task
}
```

Then pass down the new object into the task editor in the project builder.
