### ISSUE TITLE
Update on zh-cn.js

### ISSUE THREAD

**Issue by SiminTong** [zooniverse/Panoptes-Front-End#6218]
Following please find some minor corrections/updates on [zh-cn.js translation](https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/locales/zh-cn.js):

- line 23-38: classifier: {
    back: '返回',
    backButtonWarning: 'Going back will clear your work for the current task.',
    close: '关闭',
    continue: 继续',
    detailsSubTaskFormSubmitButton: 'OK',
    done: '完成',
    doneAndTalk: '完成 讨论',
    dontShowMinicourse: 'Do not show mini-course in the future',
    letsGo: 让我们开始吧！',
    next: '下一个',
    optOut: 'Opt out',
    taskTabs: {
      taskTab: '任务',
      tutorialTab: '教程'
    },

- line 57-67:fieldGuide: '文本教程',
    about: {
      header: '关于',
      nav: {
        research: '研究项目',
        results: '结果',
        faq: '常见问题',
        education: '教育',
        team: '研究团队',
      }
    },

- line 80-85: classifyPage: {
      dark: '深色',
      light: '浅色',
      title: '分类',
      themeToggle: '切换至 %(theme)s 主题'
    },

- line 98-100: zero: '位用户正在讨论 **%(title)s**.',
        one: '**1** 位用户正在讨论 **%(title)s**.',
        other: '**%(count)s** 位用户正在讨论 **%(title)s**.'

- line 102:  joinIn: '加入', 
- line 199-208: signIn: {
    title: '登录/注册',
    withZooniverse: '通过星系动物园账号登录',
    whyHaveAccount: '登录的志愿者们可以追踪他们的工作，并在任何相关结果的发表中得到致谢。',
    signIn: '登录',
    register: '注册',
    orThirdParty: '或通过第三方账号登录',
    withFacebook: '通过脸书（Facebook）账号登录',
    withGoogle: '通过谷歌（Google）账号登录'
  },

**Comment by shaunanoordin** [comment]
@SiminTong Thank you for opening this issue!

I'm happy to make these changes you've suggested, but out of curiosity, have you considered opening a [Pull Request?](https://github.com/zooniverse/Panoptes-Front-End/pulls) The changes you've suggested are already very easy to adapt into a PR.

**Comment by shaunanoordin** [comment]
I've created #6244 to address the recommendations from this issue. 👍
