### ISSUE TITLE
Unsuccessful Sign-in Attempt Doesn't Show Error Message

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/Panoptes-Front-End#6236]
## Expected behavior
Attempting to sign-in to https://www.zooniverse.org with an incorrect password or username should display a helpful error message in the sign-in modal. 

## Current behavior
A sign-in attempt with incorrect password causes the sign-in modal to close without indication of an error. This behavior was reported in Freshdesk tickets [one](https://zooniverse.freshdesk.com/a/tickets/14295) and [two](https://zooniverse.freshdesk.com/a/tickets/14286).

## Steps to replicate
Use any browser:
1. Open https://www.zooniverse.org
2. Sign-out if you're signed in
3. Open the sign-in modal
4. Input a correct username with an incorrect password
5. The modal simply closes 

## Additional information

NOT solved by https://github.com/zooniverse/panoptes-javascript-client/pull/175

**Comment by goplayoutside3** [comment]
I tried reverting panoptes-javascript-client's [PR 164](https://github.com/zooniverse/panoptes-javascript-client/pull/164) via https://github.com/zooniverse/panoptes-javascript-client/tree/revert-164, but that didn't solve this bug. It's perhaps unrelated to changes in error handling.

**Comment by eatyourgreens** [comment]
This is the handler that runs when you sign in. 
https://github.com/zooniverse/Panoptes-Front-End/blob/2627c7d1a5d77e0d6995d9232b3e6680a747964d/app/partials/sign-in-form.cjsx#L85-L97

**Comment by eatyourgreens** [comment]
This line will be fixed by  https://github.com/zooniverse/panoptes-javascript-client/pull/175, but I don't think that's the problem here.
https://github.com/zooniverse/Panoptes-Front-End/blob/2627c7d1a5d77e0d6995d9232b3e6680a747964d/app/partials/sign-in-form.cjsx#L59

**Comment by eatyourgreens** [comment]
This is a bug in `panoptes-client`, which isn't returning login errors to the downstream app. Compare the error handler for `auth.signIn` here:
https://github.com/zooniverse/panoptes-javascript-client/blob/49a56f44a636c9bafb47c2855487d525f7d61a70/lib/auth.js#L227-L230

with the error handler for `auth.register` here:
https://github.com/zooniverse/panoptes-javascript-client/blob/49a56f44a636c9bafb47c2855487d525f7d61a70/lib/auth.js#L151-L154

**Comment by eatyourgreens** [comment]
Fixed by https://github.com/zooniverse/panoptes-javascript-client/pull/178.

<img width="831" alt="Screenshot of the login box showing a 'Username or password incorrect' message in red." src="https://user-images.githubusercontent.com/59547/199706527-f977f294-d80f-40ec-962d-9250864482c0.png">

**Comment by eatyourgreens** [comment]
@goplayoutside3 I can fix this bug by reverting https://github.com/zooniverse/panoptes-javascript-client/pull/164 locally. The error message appears, as expected, if `auth.signIn` throws an error when the login fails.

I think you might have forgotten to push your changes when you were testing. The `revert-164` branch still includes the changes from https://github.com/zooniverse/panoptes-javascript-client/pull/164.
https://github.com/zooniverse/panoptes-javascript-client/blob/1eeeab1fb716ff93297090b872252f4c2297732a/lib/api-client.js#L42-L44

**Comment by goplayoutside3** [comment]
You're right! https://github.com/zooniverse/panoptes-javascript-client/pull/178 looks good though.

**Comment by eatyourgreens** [comment]
Fixed by #6240.
