### ISSUE TITLE
if I click the most recent talk post link it brings me to the post but in Zooniverse wide talk

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#629]
related to the previous issue maybe of the navigation side bar

If I click on the link to the most recent talk discussion (We're in a beta test for my project so there are some talk comments), it takes you the message but everything including the address changes to Zooniverse wide talk 

![screen shot 2015-06-20 at 2 42 43 pm](https://cloud.githubusercontent.com/assets/753325/8266313/f74b8476-175a-11e5-86a9-c4b26e7a9991.png)

**Comment by mschwamb** [comment]
@aweiksnar this might need also need a a fix if possible if launch is tomorrow (it's tomorrow?)

**Comment by aweiksnar** [comment]
Yep, I'll definitely have this in today
