### ISSUE TITLE
Can't log in with saved password from Apple keychain

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/Panoptes-Front-End#630]
Safari 7.1 on Mavericks. If I use my saved username/password from the keychain, the sign-in button doesn't activate, and the enter key won't submit the login form.
![panoptes-signin-bug](https://cloud.githubusercontent.com/assets/59547/8280577/729779a6-18d6-11e5-940c-160b41f20247.jpg)

**Comment by chrissnyder** [comment]
See https://github.com/facebook/react/issues/1159

Solution seems to be to just pull from the DOM nodes on submit and not locking the sign in button?

**Comment by edpaget** [comment]
Some users have emailed to complain they're running into this.

**Comment by simoneduca** [comment]
I can't reproduce this on Safari. @eatyourgreens can you?

**Comment by eatyourgreens** [comment]
Seems to be fixed in the latest Safari.
