### ISSUE TITLE
Survey Task filter icons are missing src

### ISSUE THREAD

**Issue by goplayoutside3** [zooniverse/Panoptes-Front-End#6305]
## Current behavior
When viewing the survey task for any project, the icons corresponding to each filter such as colors or pattern are missing a src.

<img width="300" alt="filters" src="https://user-images.githubusercontent.com/23665803/211375908-b511e205-73a9-432b-8968-d1f0052a6789.png">

## Expected behavior

Filter buttons should not have a missing img src.

## Steps to replicate

Go to a survey task project such as [Wildwatch Burrowing Owl](https://www.zooniverse.org/projects/sandiegozooglobal/wildwatch-burrowing-owl/classify), and click on a filter category.

## Additional information

- **Operating system:**: MacOS
- **Browser:**: Brave or Safari

**Comment by eatyourgreens** [comment]
Confirmed on staging too. Are the missing images SVG?
https://master.pfe-preview.zooniverse.org/projects/sandiegozooglobal/wildwatch-burrowing-owl/classify

**Comment by eatyourgreens** [comment]
I've moved the `production-release` tag back before the Webpack 5 commit.

**Comment by eatyourgreens** [comment]
Webpack 5 is staged so that we can test it on https://master.pfe=preview.zooniverse.org

**Comment by eatyourgreens** [comment]
Filter images are still broken when I look at them in production, so these were also broken in Webpack 4 builds.

**Comment by eatyourgreens** [comment]
Filter images work for Snapshot Serengeti. 

- Webpack 4 build: https://www.zooniverse.org/projects/zooniverse/snapshot-serengeti/classify
- Webpack 5 build: https://master.PFE-preview.zooniverse.org/projects/zooniverse/snapshot-serengeti/classify

**Comment by eatyourgreens** [comment]
@goplayoutside3 Is this a problem with the Burrowing Owls project, rather than the survey task?

**Comment by goplayoutside3** [comment]
Good point! I had assumed the SVGs were standardized by the Zooniverse team, but for instance Burrowing Owl's filter buttons are blank on [frontend.preview](https://frontend.preview.zooniverse.org/projects/sandiegozooglobal/wildwatch-burrowing-owl/classify/workflow/21141) as well. And [Wildwatch Kenya](https://www.zooniverse.org/projects/sandiegozooglobal/wildwatch-kenya/classify) loads without a problem on PFE.

Will follow-up by looking into Burrowing Owl's lab.
