### ISSUE TITLE
Registration Form should mention username/password restrictions

### ISSUE THREAD

**Issue by edpaget** [zooniverse/Panoptes-Front-End#631]
It should note that usernames can't have spaces and some special characters and that passwords need to be at least 8 characters.

**Comment by ggdhines** [comment]
we should give an actual error as well if someone tries to create a username/password that doesn't satisfy these constraints

**Comment by DarrenMcRoy** [comment]
Let me know if you need content for this, or if you can just adapt the stuff that I wrote for the username transition page.
