### ISSUE TITLE
Undefined content in all email notifications

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#6352]
## Expected behavior
When an email notification came we used to be able to read the content directly in the email.

## Current behavior
Now the email only says 'Undefined'. So we have to visit the Talk page to see the content. Happens for any Talk posts, including private messages.

## Steps to replicate
Set to receive email notifications immediately for all cases, then mention yourself in a Talk comment using @ and your username.  :) Open your email and instead of the post content you will only get 'Undefined'.

## Additional information

Happens to other users as well. f.e. https://www.zooniverse.org/talk/17/2758935?comment=4517972

**Comment by eatyourgreens** [comment]
Thanks for letting us know. This was a side effect of a fix for missing Twitter emoji in Talk posts, and should be fixed now in https://github.com/zooniverse/markdown-api.
