### ISSUE TITLE
Remove all demo and non-certified projects from project list

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#636]
I know @chrislintott said to wait on posting all of the issues @alexbfree reported, but it reminded me that @chrissnyder actually asked me to put this particular one up before:

We need to clear out the displayed project list to go back to only certified projects. We also need to make sure that new projects don't appear automatically in that list... ? Because they need to be certified before they get on that list, right?

**Comment by brian-c** [comment]
@camallen this query is just going to be `launch_approved=true`, right? Or are we also including beta_approved projects for now?

**Comment by DarrenMcRoy** [comment]
I'd like to eventually have a separate page for beta projects, but I definitely don't want them indistinguishable alongside certified ones.

**Comment by camallen** [comment]
@brian-c just setting this up now. Yeah it'll be the fully launched ones so all our current zoo projects and the ones we've just beta'd.

**Comment by camallen** [comment]
@brian-c should be all there now. If anyone sees retired projects listed, let me know and i'll remove them.

**Comment by DarrenMcRoy** [comment]
@camallen @brian-c A few more need to be pulled:

Whale FM
Andromeda Project
Space Warps
What's the Score? (probably?)

**Comment by mschwamb** [comment]
Planet Four: Terrains just went through beta and we'll be going when this goes live too. Can we get added to the list of projects. We're currently still in development mode (since we were mode in beta). Do we need to switch to live to move to the project home page?  I've got email approval from @mrniaboc that the projecet can join the soft launch

**Comment by edpaget** [comment]
Yup I'll toggle the switches.

**Comment by mschwamb** [comment]
Cool. Thanks @edpaget.  We still need to do the data upload and might make some minor tweaks on text, and add in the spotters' guide link, and the subject upload for launch.

**Comment by mschwamb** [comment]
I don't know the exact timeline for launch is - @edpaget changes to the workflow should be done, if you want to toggle what needs to be toggled for P4: Terrains to make it live that should be okay now. We're just waiting up subject upload which @camallen is helping with

**Comment by mschwamb** [comment]
This ticket is closed,  but I don't see Planet Four: Terrains up there. Is that because we're waiting for stuff to be pushed live to the site? Sorry I want to make sure we're not left behind in case this ticket was close prematurely. (cc @edpaget @chrissnyder)

**Comment by edpaget** [comment]
Nope I will make sure it's settings are correct before we go Live.

**Comment by mschwamb** [comment]
Thanks @edpaget
