### ISSUE TITLE
Existing zoo projects have 2 splash pages

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#637]
I click on the milky way project on panoptes projects and end up on a panoptes splash page that says click here to goto the actual project.

http://preview.zooniverse.org/panoptes/#/projects/zooniverse/milky-way-project

I think the original card should just link directly to the existing project. @mrniaboc ?

**Comment by DarrenMcRoy** [comment]
I was told this was the reason I was suppose to upload all those background images, but, yes, if there's a way to have it just directly link, I would highly prefer that.

**Comment by chrissnyder** [comment]
Sorry, that was just me solving the immediate problem rather than looking for a better solution. I'd also be for simply linking directly from the project card.

**Comment by brian-c** [comment]
This is an easy change, but we'll still need to set up the basics to support the Talk page.

**Comment by mrniaboc** [comment]
100% link directly. There is no reason for two landing pages. Just makes people angry and they will leave.

**Comment by DarrenMcRoy** [comment]
Will people be using the new Talk for old projects? Will this be supported right away? Do we have a plan to stop using the current Talk system for those projects?
