### ISSUE TITLE
Where should Kitteh Zoo live?

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#638]
Kitteh Zoo needs to be somewhere, but I don't think the main list of active projects is the place for it. Can we put it somewhere in the project builder section?

**Comment by DarrenMcRoy** [comment]
I feel like we need a project list for beta projects as well. Would it go there, perhaps?

**Comment by edpaget** [comment]
This doesn't seem like a blocking issue to me.

**Comment by chrislintott** [comment]
@edpaget We're going to need a beta page sooner rather than later. But not right at launch.

**Comment by vrooje** [comment]
If Kitteh Zoo is visible on the home page, what will happen to it once the retirement limit (currently at 999) is reached for all 30 subjects?

**Comment by edpaget** [comment]
We won't set it to live. So it won't count towards retirement.

**Comment by chrissnyder** [comment]
Covered by #806 and will be visible soon as @srallen merges her branch.
