### ISSUE TITLE
Unable to edit my own Talk posts

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#6380]
## Expected behavior
After editing my post on the Talk and hitting the *Update comment* button, the comment should be updated.

## Current behavior
When I click on the *Update comment* button, it keeps loading but the post won't get updated.

Screenshots with browser console errors:
The original post where I realized it (Western Shield Camera Watch):
![ysh_Screenshot_2023-01-23_21-32-56](https://user-images.githubusercontent.com/7211888/214145091-feac31fa-c693-4bb1-a4f9-02b0bf7c9a6a.png)

Second attempt to edit the same post from a different browser tab after I noticed it doesn't work:
![ysh_Screenshot_2023-01-23_21-34-22](https://user-images.githubusercontent.com/7211888/214145109-94210999-be47-4f25-bcc6-9e7239419cbb.png)

Tried in a different project (Plankton Portal), editing an older comment of mine, got even more errors in the browser console:
![ysh_Screenshot_2023-01-23_21-42-05](https://user-images.githubusercontent.com/7211888/214145769-21671c17-7228-4d5e-b9ce-c0b2e66f7b92.png)

## Steps to replicate
Happened in the WesternShield Camera Watch project Talk, and then in Plankton Portal. But I guess it will happen in others too. 
Make a comment, after submitting click on the Edit button and then hit the Update comment. See what happens.

## Additional information

- **Operating system:** Ubuntu, Linux
- **Browser:** Chrome 109
- (edit:) user Amperima says it works on her phone. So I tried to edit something on my phone but without a success.

**Comment by mcbouslog** [comment]
Thank you @yshish for reporting!

I think related to #6381 , fixed* with #6382 . (* additional follow-up / fix needed to panoptes-javascript-client v5.0.0 and above).

**Comment by yshish** [comment]
It seems to be working again.

**Comment by eatyourgreens** [comment]
Fixed in https://github.com/zooniverse/json-api-client/pull/84
