### ISSUE TITLE
Subject sets not loading

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/Panoptes-Front-End#6381]
## Expected behavior
Loading a subject set should show list of subjects in the subject set.

## Current behavior
Blank page, in console - `TypeError: o.get is not a function`

## Steps to replicate
- starting from list of subject sets - https://www.zooniverse.org/lab/4312/subject-sets
- click any subject set
- should show list of subjects in the subject set, but shows blank page

**Comment by goplayoutside3** [comment]
Caused by release of panoptes-javascript-client v5.0 after https://github.com/zooniverse/panoptes-javascript-client/pull/187.

**Comment by eatyourgreens** [comment]
Fixed in https://github.com/zooniverse/json-api-client/pull/84
