### ISSUE TITLE
Incorrect Tutorial displaying on workflow

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/Panoptes-Front-End#6400]
## Current behavior
Original message from project team via the project's private Talk board:
>We're having an issue where the tutorial selected in our workflow isn't the one displaying to users. The Find the Names (Manuscript)** workflow has Tutorial [6402](https://www.zooniverse.org/projects/douglassday/transcribe-shadd-cary/talk/tags/6402) - Find The Names selected. However, Tutorial [6381](https://www.zooniverse.org/projects/douglassday/transcribe-shadd-cary/talk/tags/6381) - Transcription Tutorial 01 is what seems to appear instead. We'd hoped it was a testing issue only, but based on feedback from testers, it shows up in live mode as well. While testing, we tried removing and reselecting the tutorial multiple times, but with no success.

## Replicated once, currently behaving as expected but took several tries
I did encounter some weird behaviors while on the lab page -- It initially showed up as being set to 6402 in the lab workflow page ([workflow 23348](https://www.zooniverse.org/lab/19864/workflows/23348)), but that wasn't reflected on the live project for the workflow in question (red flag no. 1). So I changed that workflow's Tutorial settings to "No tutorial" but it didn't immediately update on the live site (red flag no. 2), and then when I refreshed the Project Builder page, it came up as being set to the incorrect Tutorial [6381](https://www.zooniverse.org/projects/douglassday/transcribe-shadd-cary/talk/tags/6381) (red flag no. 3!). I then changed it to Tutorial 6402 and it seemed to properly reset.

## Additional information
Possibly related to issue zooniverse/panoptes#4104 (seems like changes aren't being saved in the lab? or at least another example of changes in the lab not being reflected on PFE projects)

**Comment by eatyourgreens** [comment]
Is there a link to 'the project in question' so that we can see the tutorial? That would be really helpful for debugging this.

**Comment by eatyourgreens** [comment]
My initial reaction to the symptoms described here is that maybe either the network requests were slow to resolve or Panoptes was having problems and was slow to update after receiving a request. I'd be tempted to try debugging it with network throttling enabled, to simulate a slow API.

**Comment by eatyourgreens** [comment]
More than one tutorial can be linked to a workflow here, in which case only the first tutorial will be shown by the radio buttons. That might be the bug. The code assumes that only one tutorial is ever linked to a workflow but that restriction is not enforced. 
https://github.com/zooniverse/Panoptes-Front-End/blob/d03a048af205a7a33d4855d0a9edc56e9debf246/app/pages/lab/workflow-components/tutorials.jsx#L19

**Comment by mcbouslog** [comment]
Here's a staging workflow with two tutorials linked to the workflow - https://master.pfe-preview.zooniverse.org/lab/1775/workflows/3276?env=staging. It's tricky to see that two are linked, easiest way I could manage is by finding https://panoptes-staging.zooniverse.org/api/tutorials?http_cache=true&admin=true&workflow_id=3276&page_size=100 in network tab, looking at preview shows array of the two linked tutorials.

**Comment by eatyourgreens** [comment]
>We could check if there's more than one workflowTutorials and unlink all but one, but there's no way to tell which one should remain.

In this particular widget, the one that should remain is the value of the radio button group.

**Comment by eatyourgreens** [comment]
I can’t remember if this component has tests either, but it seems like it should be possible to mock up a workflow with two tutorials in the tests. 

I’m still not sure if two linked tutorials of the same type is a bug in Panoptes.
