### ISSUE TITLE
Shape disappears on "back"

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#644]
If I draw a shape (I drew an ellipse) and then click "back" to go to the previous question, when I return to the drawing question, my shape (ellipse) is gone. And if I go to the end of that workflow, I can see that the shape was not recorded.

**Comment by brian-c** [comment]
For what it's worth, this is as intended.

**Comment by mkosmala** [comment]
@brian-c What?! Why?

**Comment by mkosmala** [comment]
I see that this happens with questions, too. But my guess is that when people go back, they want to fix an earlier question, but not abandon the questions they've done so far.
...
Oh. But. If it's a branched workflow. Hmm. I see....

**Comment by chrissnyder** [comment]
Sounds like some additional conversation is necessary here, so punting development on this for a bit.
