### ISSUE TITLE
Switching polygon drawing tools mid-shape

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#647]
I have a question with multiple polygon drawing tools. If I start to draw a red polygon, but then switch to an orange polygon, the orange tool gets highlighted, but I continue drawing in red. When I finish that red polygon, my next polygon is orange. This is a little unintuitive, and we had some feedback from our beta about this (see #443). 

Perhaps it would be better to cancel drawing a polygon if the user switches tools mid-shape. I think this would align with intuition better.

**Comment by chrissnyder** [comment]
Fixed at some point.
