### ISSUE TITLE
Hard to delete small drawing objects

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#649]
This is feedback from our Season Spotter beta (see #443). When small shapes are drawn (e.g. ellipse tool), the "X" to delete them gets hidden behind one of the handles and is very difficult to click. This problem seems to be exacerbated on small screens like mobile devices.

**Comment by mkosmala** [comment]
Related #296

**Comment by chrissnyder** [comment]
I think there's a lot of thing's we could improve on in mobile, but that's for another day.

@brian-c Does seem to be a case to enforce that drag handles and the delete button are kept reasonably separate, even on small marks. At a certain point, this of course breaks down regardless.

This also might be again a problem of messaging? Requiring volunteers to make very small marks seems prone to failure and inaccurate data, and should generally be avoided.

**Comment by mkosmala** [comment]
We can't know ahead of time how large the area to be marked is. So some areas will be large and some areas might be small. While we don't require users to mark small areas, we can't prevent them from doing so!
