### ISSUE TITLE
Different pages need different titles

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#65]
Maybe just set `document.title` on `componentDidMount`, but also see what https://github.com/gaearon/react-document-title buys.

**Comment by aweiksnar** [comment]
A mixin might work well for this?
```coffeescript
DocumentTitle =
  componentDidMount: ->
    title = switch typeof @documentTitle
      when 'string' then @documentTitle
      when 'function' then @documentTitle()
      else
        "Panoptes"
    document.title = title

```

**Comment by brian-c** [comment]
Eh, I'd be fine with just defining `componentDidMount: -> document.title = 'Whatever'` on page components.

What would be cool is something that integrates with the router so nested components can define nested segments in the title like "Zooniverse > Galaxy Zoo > Classify". This isn't worth thinking about too hard though.

**Comment by brian-c** [comment]
Nope, you're right, we need a mixin. A component needs to keep track of where it put its piece of the title, and when it unmounts it needs to remove it.

I think the thing in the commit above will work, but I'm going to play with it a bit more.
