### ISSUE TITLE
Polygon drawing tool unintuitve and unfriendly

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#650]
This is probably the biggest negative comment we got in our Season Spotter beta (see #443). Users had a lot of difficulty figuring out how to use the polygon tool. In particular, they didn't realize they had to click multiple times. 

> I couldn't figure out how to draw around an area. It would just mark one place and count that as one plant.

and

> It was also a bit hard at first to understand how the tool to draw the shapes works -- I though[t] I should be holding down the mouse and drawing around the shape all at once, rather than clicking on various points around the shape.

I admit that it took me a little while to figure out how to use it myself. I'm not sure it's obvious how to finish a shape either (although having both double-click and click-on-the-original-vertex is good).

One user specifically asked for a tutorial on how to use the polygon tool!

**Comment by aliburchard** [comment]
Agreed. This is the biggest complaint I've received from folks exploring the projects as well.

**Comment by chrissnyder** [comment]
I don't think the functionality is the problem here, as I think the tool works quite well. The issue is it isn't communicated how to use it anywhere.

@brian-c Thoughts on messaging tool functionality? Some would be pretty dumb (to draw a line, just... draw a line), but this might also solve issues like #926 as well.

**Comment by mkosmala** [comment]
A tool should be intuitive; it shouldn't need explanation. My guess is that the polygon tool does not work like people think it should, and so the learning curve is too steep. 

I've been trying out polygon tools in other software (Microsoft desktop software, drawing programs) to figure out what people might be used to. One thing that might help is that when the user draws that first point, have a floating line (dotted or not) between that point and the user's cursor/pointer/arrow. That indicates that a line will be drawn when the next click is made. This appears to be standard practice across the software I've looked at.

**Comment by aliburchard** [comment]
I agree that a tool should be intuitive -- and that employing strategies currently used by other platforms is a good way to do that. I really  like the idea of having a dotted line appear between the set point and your cursor.
