### ISSUE TITLE
Metadata button needs flashiness

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#651]
In our Season Spotter beta (#443), we asked if there was anything the users wanted to see. Many of them requested having metadata about the location of our images. However, that data is included in our metadata and can be seen when users click the metadata button. I think what this means is that a large fraction of beta users never noticed the metadata button -- and note that these are Zooniverse regulars. I think there should be some thought in directing some visual attention to the metadata button. (Maybe have the word "metadata" appear when the user hovers over the button?)

**Comment by tfmorris** [comment]
A bulleted list icon might be more recognizable than the current grid icon.  I thought it was going to take me to some type of gridded image display.

**Comment by vrooje** [comment]
@edpaget Suggests in #1182 that text-only buttons could work. That sounds okay too, though I don't think "metadata" will mean anything to the average volunteer.

**Comment by edpaget** [comment]
I was thinking 'View Additional Data' and 'Add to Collection'

**Comment by edpaget** [comment]
Opinions on text vs icons @brian-c @heathv @chrissnyder ?

**Comment by brian-c** [comment]
Maybe I'd go with an "i"-in-a-circle icon with a "More information" tooltip.

**Comment by mkosmala** [comment]
I like @brian-c's "i"dea. My two cents.

**Comment by chrissnyder** [comment]
Highly prefer text over icons in all cases, unless it's a pervasive internet-wide meme. I personally think icons only add confusion and are an additional language users need to learn. For examples, the favorites icon I'm OK with, but the others should really be text in my opinion.

**Comment by eatyourgreens** [comment]
We could add `aria-label='More information'` to the button (for screenreaders) and expose the label as a tooltip for sighted users?

**Comment by edpaget** [comment]
We also need a better button for collections re: #1182. I like text labels better too.

**Comment by vrooje** [comment]
Note: if we use text labels, we'll have to translate them too when projects are translated.

Not saying we shouldn't use text labels; just pointing this out.

**Comment by mkosmala** [comment]
I agree with @chrissnyder about not making people learn new icons. For the metadata button, the information "i" is universal and makes sense, in my opinion.
http://tinyurl.com/infoipix

**Comment by aliburchard** [comment]
agreed on not making people learn new icons; I really like the  "information i" suggestion because i think it's about as universal as a <3
