### ISSUE TITLE
Can't view Favorites from Project page, if not logged in

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/Panoptes-Front-End#6515]
## Bug

If you're _not logged in_ and then go to (any Project) -> Collect -> Favorites -> (any Favorites), the page will crash with the error: `Cannot read properties of null (reading 'id')`

- Example URL: https://www.zooniverse.org/projects/penguintom79/penguin-watch/collections/mary2021/favorites-penguintom79-penguin-watch

Expectation:
- You should be able to view a Favorites/Favourites collection from the Project page _without having to log in._

Notes:
- If you access the Favorites from the Project page while you're _logged in,_ it works fine.
- If you access the Favorites from the _User_ page while you're _not logged in,_ it also works fine. Example: https://www.zooniverse.org/collections/mary2021/favorites-penguintom79-penguin-watch
- If you access a _Collection_ from the Project page while not logged in, it also also works fine. (???) Example: https://www.zooniverse.org/projects/penguintom79/penguin-watch/collections/chescamartin/08-09-21-2nd-week (How... how is this different?)

### Status

No volunteer has filed a complaint yet, and the affected functionality doesn't seem major. I'm marking this as a low-priority bug for now.

**Comment by eatyourgreens** [comment]
I think Favourites are private by default. The collection owner may need to go into collection settings and make sure it is set to public, before sharing a link.

**Comment by eatyourgreens** [comment]
`props.user.id` will crash when there’s no logged-in user. 🤦🏻‍♂️
