### ISSUE TITLE
future request - more functionality in the publications page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#654]
I can't add status to my github issues, but for future plans - a few of the existing projects link to the publications page - so making a ticket to eventually add the functionality the previous projects page had to the new one. Mainly being able to sort by project in the url address and being able to link to see which projects have a paper on the list when you click on the subgroup (space, climate)

**Comment by alexbfree** [comment]
I'm going to take a look at this for the specific scenario of wanting to link to a specific project's publications via a unique URL. That may not address everything mentioned here, so i will probably leave it open after I've done that. But will update again here after getting into the code.

**Comment by mschwamb** [comment]
Thanks @alexbfree. I think that's a good chunk of what I was asking for. 

 The other bit is that it would be nice to have on the side menu once you've clicked space to get the list of projects as a links so you can jump down to the project and see the publication list rather than having to search the publications page to find the relevant project's place on the publications page.

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
