### ISSUE TITLE
some of the project plackards are pixelated on panoptes Zooniverse home

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#655]
- chimp&see, Higgs hunters, Chicago Wildlife Watch, Orchid Observers, Science Gossip - the image is too pixelated at the current resolution being used compared to other project plackards like Planet Hunters and Galaxy Zoo 

![screen shot 2015-06-23 at 4 09 56 am](https://cloud.githubusercontent.com/assets/753325/8291699/cc069738-195d-11e5-8e13-037360dcc5f6.png)

![screen shot 2015-06-23 at 4 11 30 am](https://cloud.githubusercontent.com/assets/753325/8291733/ff04d848-195d-11e5-97d0-5c0c1f2be2bc.png)

**Comment by DarrenMcRoy** [comment]
All of these assets were pulled off of the current Zooniverse home thumbnails.

Are the new thumbnails slightly larger, or with different dimensions?

**Comment by brian-c** [comment]
The uploader automatically scales down images above a certain file size. I think it's 50 KB. I'll see if I can get the images it generates looking better, or else I'll remove the auto-resize and just have it reject images that are too big.

**Comment by DarrenMcRoy** [comment]
@brian-c Not sure if that's quite the problem. The Penguin Watch thumbnail, for instance, is horribly pixellated, but the file I uploaded is just 28kb:

![pw_av](https://cloud.githubusercontent.com/assets/8987864/8293662/ad24681a-18fc-11e5-8ef8-c9f08f63474a.jpg)

I'm thinking it might be more of a sizing/stretching issue. What are the dimensions on the area where the new avatars go?

**Comment by brian-c** [comment]
@DarrenMcRoy and I did some more digging on this, it was actually an issue of pulling tiny tiny images from the current Zoo Home.
