### ISSUE TITLE
Moderater labels not showing up on Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#659]
Person is listed on the science page as moderator, it's not showing up on Talk. I haven't asked if they have moderator abilities like see menus to create boards. See the linked thread below. The author is a moderator and its not showing that's the case. 

http://preview.zooniverse.org/panoptes/#/projects/mschwamb/planet-four-terrains/talk/8/86

**Comment by edpaget** [comment]
@mschwamb did you make this person recently? Can you try removing their moderator role on the collaborator page and readding them?

**Comment by mschwamb** [comment]
@edpaget I added them last week because we supposed to beta then. Removing and adding them appeared to work. thanks.

**Comment by edpaget** [comment]
Roles may be inconsistent since we supported setting them before Production Talk was actually setup. Sorry about that.
