### ISSUE TITLE
lableing Zooniverse Talk and the project Talks 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#661]
A small low priority suggestion. I think it's a bit confusing what's Zooniverse Talk and what's project talk. I'd suggest changing the Talk! on the Zooniverse wide one to 'Zooniverse Talk' and on the project pages if they could say projectname Talk in the same place it would reinforce their the same thing. The only place on the project talks does it actually say that the thing is called Talk is the side bar.

![screen shot 2015-06-23 at 6 57 23 am](https://cloud.githubusercontent.com/assets/753325/8295237/4926b2ea-1975-11e5-90c3-751a2548724b.png)

![screen shot 2015-06-23 at 6 57 39 am](https://cloud.githubusercontent.com/assets/753325/8295239/51a945cc-1975-11e5-8e80-84b2c47f29c7.png)

**Comment by aweiksnar** [comment]
Related to #185

**Comment by edpaget** [comment]
Duplicate
