### ISSUE TITLE
Adding project descriptions to the Zooniverse panoptes home page?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#662]
low priority -  On the new home page listing projects, you can't really tell what each project is about.  You have some inking for the name and the picture, but I liked the project descriptions from  old Zooniverse home tied with the picture and the project name. 

It appeared earlier in a version of the front page cards that there is a space for adding a project  description. I think adding those back in for launched projects would be really helpful for new volunteers pursuing.

**Comment by DarrenMcRoy** [comment]
Is there some reason that we don't have descriptions?

I agree that it seems fairly important. Otherwise it's just a blind click on a project without knowing anything about it.

**Comment by vrooje** [comment]
Yeah, I think this is probably a reasonably high priority among those issues that aren't bugs.

**Comment by DarrenMcRoy** [comment]
Marking this as first-release because it seems very important to me... ?

**Comment by mschwamb** [comment]
If it's helpful to know (though you might already know) - a few of the project descriptions are getting cutoff see Disk Detective, Orchid Observers, Floating Forests ,Asteroid Zoo in Firefox on a 13 inch screen

**Comment by DarrenMcRoy** [comment]
I'm about to start a new issue for styling the descriptions better. :-)
