### ISSUE TITLE
scroll bar of help not working in IE 11 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#665]
There are a few reports in the Planet Four: Terrains beta test that the help didn't scroll. I can't tell what OS or browser they were on. I'm guessing from the frequency it's IE, but there is one solid report where the person gives the browser and version

'The help texts did not scroll with Internet Explorer 11, only the beginning of help text window was visible.'

**Comment by DarrenMcRoy** [comment]
We had a problem like this in Chimp & See as well; I think @srallen fixed it? https://github.com/zooniverse/Chimp-Zoo/issues/55

There are still some reports of issues with that particular scroll bar, though. https://github.com/zooniverse/Chimp-Zoo/issues/70
