### ISSUE TITLE
reduce the padding between navigation links to help prevent moving to a new line when adding a blog link

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#666]
low in the queue, but if possible is there any chance to reduce the padding just a scosh for the top project navigation bar.  We added a link to the Spotter's Guide, but adding that text plus Blog pushed the Blog text onto a newline 
 
![screen shot 2015-06-23 at 2 10 35 pm](https://cloud.githubusercontent.com/assets/753325/8299962/18ff927a-19b2-11e5-99d9-a4836503bd2c.png)

**Comment by chrissnyder** [comment]
Related to #371.

Not sure reducing the padding is the right solution here. You'll run into the same problem after adding one more link, or if a person's screen is a bit smaller.

**Comment by edpaget** [comment]
Maybe a collapsible menu?

**Comment by mschwamb** [comment]
@chrissnyder @edpaget is there a quick solution to launch? I'd hate to remove the education section, but I don't know what else I move and I can't think of a shorter name for the spotter's guide - Any suggestions?

**Comment by edpaget** [comment]
Why not just 'Guide'?

**Comment by mschwamb** [comment]
touché - that seems to fit with the blog on the upper line - I'll have the same issue if we add a results page, but that's for another day.

**Comment by mschwamb** [comment]
@chrissnyder  - this is still a problem if I add a results page in - it means there really is almost not space for any external links. so should this be reopened?
