### ISSUE TITLE
can't access profile or signout if menu crosses a navigation bar link

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#667]
Currently the sign out/profile menu covers the Spotter's Guide link when it comes down. When that happens you can't mouse over onto the  signout/profile menu

![screen shot 2015-06-23 at 2 20 25 pm](https://cloud.githubusercontent.com/assets/753325/8300232/fa213b12-19b4-11e5-83b1-f70f23ec7ef2.png)

When I mouse over it keeps going to the Spotter's guide link and not to profile

**Comment by mschwamb** [comment]
@chrissnyder this is still happening for my on Firefox - is this change live?

**Comment by chrissnyder** [comment]
Not deployed to preview.zooniverse.org yet. Fixed on http://demo.zooniverse.org/panoptes-front-end
