### ISSUE TITLE
Workflow editor discussion

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#68]
@chrislintott:

@aliburchard  and I had a sit-down over the workflow tasks editing interface. Here's what we came up with.

The workflow editor is primarily a **task** list.

To add a task to the list a menu pops up and you can choose the task's **type**.

Tasks types are **question**, **marking** and **camera trap survey**.

The question task editor lets you define a **question**, whether it's **single**- or **multiple**-choice, and a list of **answers**.

An answer in a single-choice question task can optionally point to another task.

The marking task editor lets you define an **instruction** ("Draw an ellipse around every bear") and a list of **tools**.

The marking tool editor lets you define a **label**, a **type**, a **color**, and a list of **details**.

(Currently the types we have are point, line, rectangle, irregular polygon, and ellipse.)

The details editor lets you define a **question**, whether it's **single**- or **multiple**-choice, and a list of **answers**.

Marking tool details are essentially questions with answers (like Penguins's "other" option) associated with each mark.

Camera trap survey editor is a great big beast of a thing and we're going to ask @heathv to take a stab at it. We have a call set up for next Tuesday.

Tasks in the list will be reorderable (probably with up/down buttons first, drag-and-drop to come). Tasks are followed in order, unless a single-choice question task's chosen answer points somewhere else.

**Comment by mkosmala** [comment]
Please tag @rcheng3 in these conversations. Rebecca, follow this issue.

**Comment by twhyntie** [comment]
@brian-c This sounds *awesome* - thanks!

Quick question - will the workflow creator be able to upload a small image to accompany each of the answers for a given question, like with the galaxy shape questions (disk, bulge, etc.)?

**Comment by rcheng3** [comment]
May I suggest to add one more question task: "slider" with tooltip (0-100)?

**Comment by mkosmala** [comment]
@brian-c Do you think a slider would be reasonably easy to implement as a tool for the first round?

**Comment by brian-c** [comment]
Not in scope, unfortunately. Would "1-10", "11-20", etc. choices work?

**Comment by mkosmala** [comment]
Okay, add it to future tools requested. Multiple choice will have to do.
