### ISSUE TITLE
Places for beta, paused, out-of-data, completed projects?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#680]
Have we discussed at all having lists of projects on Zooniverse Home for projects that might not involve immediate contribution to research, and segregating such projects from the main list?

Projects that are out of data, like Seafloor Explorer, Cell Slider, and Snapshot Serengeti...

Completed/paused projects like Andromeda, Space Warps?

Beta projects might go in a separate list, too... ?

In my mind, maybe the projects page has a series of tabs, for "active/certified," "paused," "retired," etc. So that we're not advertising projects where that are in the "education-only" state alongside ones that really need help.

Thoughts?

**Comment by edpaget** [comment]
I totally agree. We could have 'Active', 'Beta', 'Retired' links along the projects page hero for now.

**Comment by chrissnyder** [comment]
Same task as #701
