### ISSUE TITLE
What is the intended style of the avatars?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#681]
Ran into a slight disconnect when trying to work with @brian-c to fix the avatar-pixellation issue...

What exactly are the project avatars supposed to look like? When I uploaded them, I just used the assets from the current Zooniverse Home, which are rectangular and depict a picture related to the project. Like this:

![card-388421f83d6be5dc20dfcbaf9dd78145](https://cloud.githubusercontent.com/assets/8987864/8315990/c44c30be-19b9-11e5-832f-e8e4da8f9dbe.jpg)

However, these rectangles have translated poorly to the new Home, where the spaces for avatars are square.

Was the intent that we use the Zooniverse O-style logos instead, which ARE square? These... ?

![crater](https://cloud.githubusercontent.com/assets/8987864/8315862/0f17a1ce-19b9-11e5-89b0-bf55a0c355d4.jpg)

If so, the homepage will sort of look like a sea of O's, rather like Heimdall does. Is that a good design ethos? @heathv ... ?

If so, then we will need to make sure that every project has an "O." Including any new ones from users. Or else ones that don't have the O design will stick out weirdly, right?

If we're not using the O's, however, then we may need to crop an all-new set of square avatars, one for every project, to fix #655.

Which was the intention?

**Comment by heathv** [comment]
For the cards it would ideally be a crop on the uploaded image. If its a Zooniverse® project you'll likely see a cropped view of the traditional avatar. If it's a non-zooniverse projects, it'll be whatever they upload. I'm not too worried about a sea of logo marks.

**Comment by DarrenMcRoy** [comment]
My concern with the O-vs.-non-O, as it often is, is with "other-ing" any project we don't create ourselves. We want to push the idea that you can create a project with the Project Builder that is just as good as one we would make for you, right? But I feel like having our builds get fancy logos on the home page, when others don't, creates a stratification effect that diminishes non-Zoo-built projects.

Perhaps this could be resolved later on by eventually uploading more neutral avatars for our home-built projects when we're not under a time crunch?

I'm happy to upload all the O's as the new avatars; would only take an hour or so. There are a few projects that don't have O's, though, so either we create O's for them, or there will be a few projects that really stick out weirdly in the design, the way CWW does on Heimdall (http://heimdall.zooniverse.org/)

So, anyway, if you want me to upload all the O logos over the ones that are currently up there, I can probably do that later tonight. Should I?

**Comment by DarrenMcRoy** [comment]
For a test, I uploaded a couple of the O logos to http://preview.zooniverse.org/panoptes/#/projects...

They crop off the bottom (not a square space), which can make them look a bit odd (the penguins are barely visible, for instance.)

Also, projects that I don't have an O logo for include Old Weather, Chicago Wildlife Watch, Ancient Lives, Solar Stormwatch... maybe a couple others?

**Comment by mschwamb** [comment]
If it helps avatars are stored at https://github.com/zooniverse/Brand/tree/master/projects 

Though if you go to avatars then P4: Terrains has a slight problem in that we're using the P4 avatar since we wanted to keep a single project branding . Not sure if we could then get a slight spin on the P4 avatar for Terrains.

**Comment by aliburchard** [comment]
I like the idea of using the Zooniverse avatars for custom Zooniverse projects. I *love* our avatars in general, and am always disappointed that they don't feature more prominently on the site. Many Zooniverse visitors don't even realize we have avatars for projects, which always makes me sad.

**Comment by camallen** [comment]
I agree with @aliburchard - using our avatars also visually distinguishes the projects that we build.

**Comment by DarrenMcRoy** [comment]
I still feel that, if we want to encourage people to use the project builder, we don't *want* to visually distinguish our custom builds. We want to make it seem like you can get something just as good out of the builder as you could by taking up two months of our dev time, right? So that people are encouraged to do the former, and not try for the latter?

However, it seems I'm standing alone on principle with this, and time is short, so I'll go ahead and upload those, at least for now. :-) Could we at least get it so that the rectangular crop takes from the middle of the image, not the top? The ones I've uploaded so far look a little awful because their bottoms are cut off. @camallen @brian-c ...?

**Comment by alexbfree** [comment]
For what it's worth I agree with you Darren. I wonder if a compromise might be to have a generic Zooniverse O for those projects that lack their own Zooniverse O logo?

**Comment by mschwamb** [comment]
Could y'all let me know when a decision is made what that means for P4:Terrains?

If you use avatars for custom builds and require a image placard for project builder projects then I need to go back to the rest P4 team and have them pick an image quickly.

 If you allow custom builds to use an avatar if they want or earn it and you're using avatars for custom builds, then P4's will be duplicated. On such short notice,I'm not sure if it's possible then for us to get a tweak/twist (color change or something) on P4 avatar for P4: Terrains (a question maybe for @heathv ?)?

Thanks

**Comment by DarrenMcRoy** [comment]
Uploaded all of the O logos, at least for now.

@mschwamb -- pick whatever image you like for Terrains, I guess, for now. We can revisit this later, but as far as first release, let's just have *something* up.

**Comment by mschwamb** [comment]
@DarrenMcRoy I see projects that have O avatars that you don't have up there with O avatars like ancient lives and moon zoo.  Are they all pushed live to the preview site?  If so, I can help you grab them and send them to you if that helps.

**Comment by DarrenMcRoy** [comment]
@mschwamb #741

**Comment by DarrenMcRoy** [comment]
... Hm! I was actually partially wrong about that one. Give me a sec...

**Comment by DarrenMcRoy** [comment]
Fixed that.
