### ISSUE TITLE
Is there a way of linking a project subpage without the full url?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#685]
A quick question 

In the help box I have a link to the FAQ, but that address will change presumably from when a project goes live and when preview.zoonvierse.org goes to zooniverse.org.

Is there anyway to avoid having to explicitly write the whole url for http://preview.zooniverse.org/panoptes/#/projects/mschwamb/planet-four-terrains/science-case to put a link for the science case in the FAQ, etc?

Thanks

**Comment by mschwamb** [comment]
If not, do you know what the final launch urls will be so I can include them now?

**Comment by brian-c** [comment]
Your link should be fine with just the "#" and everything after it.

**Comment by mschwamb** [comment]
That worked. Thanks.
