### ISSUE TITLE
Buttons for multiple workflows are pretty ugly

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#687]
When you create multiple workflows for a project, the buttons on the landing page are stuck together and look pretty bad.

**Comment by twhyntie** [comment]
:+1:

**Comment by camallen** [comment]
Excuse the highjack here, happy to open a new issue. The button view came up in discussion with @aliburchard for projects that allow users to select the workflow they want to work on. 

Some sort of nice formatting  need a tag line to inform the user about what the workflow tasks require and why they are interesting. E.g. http://mkosmala.github.io/SeasonSpotterLanding/

**Comment by edpaget** [comment]
This is be taken care of as part of #371

**Comment by aliburchard** [comment]
I don't actually think this is necessarily solved by #371 -- not as it's currently specified, anyway.
