### ISSUE TITLE
Blue banner doesn't look great - neither do the get started buttons

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#688]
The blue banner used on the /projects and /about pages is the exact colour you get if you highlight a section of a page in your browser, so looks quite weird. I really like the dimmed/opaque effect on the main landing page, and suggest sticking with this theme throughout.

**Comment by alexbfree** [comment]
I would also add a related comment; the blue buttons that say "Get Started" on each project don't look great either... Looks rather like a bootstrap template or auto-generated button... might look better with a two-tone effect, a shadow, a gradient and/or removal of bold.

**Comment by DarrenMcRoy** [comment]
I agree with these. The blue has really been throwing me off. The dimmed effect on the landing page looks much better.

**Comment by aliburchard** [comment]
Agreed with all the above.

**Comment by alexbfree** [comment]
Regarding the buttons, here is the current button:
![current button](https://cloud.githubusercontent.com/assets/1473244/8331700/9c4da052-1a81-11e5-9d5d-870495b30282.png)

Here's a slightly improved version: 2px line, 2px shadow, and a light blue background.

![better version?](https://cloud.githubusercontent.com/assets/1473244/8331721/b3affa92-1a81-11e5-985b-196a6d2078b7.png)

Looks good on hover too:
![hover with shadow](https://cloud.githubusercontent.com/assets/1473244/8331734/bbddbd80-1a81-11e5-94fb-6260f9501ddd.png)

**Comment by edpaget** [comment]
I think the flat buttons look at lot better than ones with gradients or shadows.

**Comment by mrniaboc** [comment]
All for flat design

**Comment by alexbfree** [comment]
OK but even if we don't add shadows, how about at least giving it some colour? white on white is weird... and i think the button border is too thick.

**Comment by DarrenMcRoy** [comment]
Assigning to @heathv to see if we can switch from the blue banner to the dimmed one?

**Comment by DarrenMcRoy** [comment]
I'm still very much hoping that we can change the banner...

**Comment by chrissnyder** [comment]
Not now, no.

**Comment by chrissnyder** [comment]
Antiquated, as resource card design has already changed a bit.

I'm biased against these sort of meta design issues because I don't see an obvious path to close this issue. I also think we need to be careful about not designing by committee, which this issue is dangerously close to being.

**Comment by mrniaboc** [comment]
I agree. The only reason I felt this case was an exception was because it
has potential to confuse visitors to the site.
