### ISSUE TITLE
CORS Errors

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#69]
CORS errors on the project/classify page

**Comment by edpaget** [comment]
This seems like it might be a Panoptes issue. What kind of errors are you seeing?

**Comment by aweiksnar** [comment]
Firefox

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://panoptes-staging.zooniverse.org/api/projects/14. This can be fixed by moving the resource to the same domain or enabling CORS.`

Chrome

`XMLHttpRequest cannot load https://panoptes-staging.zooniverse.org/api/projects?page=1. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3735' is therefore not allowed access. The response had HTTP status code 500.`

want me to reopen in Panoptes?

**Comment by edpaget** [comment]
Sure can you also post the headers you do get back from Panoptes?
