### ISSUE TITLE
Adding text that you can click and open a file finder/browser for all the areas that say drag and drop

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#690]
low in the queue 

One thing I noticed was that you can click and then move to the directory you have things rather than drag and drop if you click on the grey boxes for file uploads which is my preferred method versus the suggested drag and drop. I'm not sure other people will know they can do that.

Maybe there should be text to say you can click and find your file as an alternative.

I'm not sure if any of the above made sense.  But I'm referring to this:
![screen shot 2015-06-24 at 6 05 26 pm](https://cloud.githubusercontent.com/assets/753325/8327563/f00208ea-1a9b-11e5-8ce4-791f6df34d47.png)
![screen shot 2015-06-24 at 6 05 15 pm](https://cloud.githubusercontent.com/assets/753325/8327566/f66649bc-1a9b-11e5-8660-bb78dc4d6e35.png)

**Comment by aliburchard** [comment]
Yup. We should revise that text to say something like:
"Drag and drop images here or click select with your file explorer"
