### ISSUE TITLE
Formatting needed on "Loading" on all pages

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#695]
The Loading text is left-justified, lacks padding.
Maybe centralize, with padding, and add a spinning Zooniverse O gif during loading?
Remove grey background too and consider font colour.

![Loading example](https://cloud.githubusercontent.com/assets/1473244/8331333/7b85146a-1a7f-11e5-9b4e-9a4f7b78b930.png)

**Comment by chrissnyder** [comment]
Fixed at some point.
