### ISSUE TITLE
Enforce size limit for subjects

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#696]
I just got an email from a science trying to upload 6MB images. I think we should decide on a size limit for subjects uploaded through the project builder (and add help text with "suggested size" and "maximum size"). Talking to @camallen and @mrniaboc it sounds like 400kb should be a decent max size for standard projects, though curious what @vrooje @mschwamb are uploading currently.

**Comment by mschwamb** [comment]
471kb  it appears if my ls -lrth is spitting up the correct values

**Comment by chrissnyder** [comment]
@brian-c Do we do anything clever with uploaded images, or are they "as-is"?

@edpaget Any thoughts on enforcing image sizes?

**Comment by brian-c** [comment]
Subject imagess aren't modified in any way. There's no max size, but this'd be easy to catch up front.

**Comment by edpaget** [comment]
We could use the PresignedPosts objects on S3 instead of our current PUTs and then specify a size range for objects.

**Comment by chrissnyder** [comment]
Not compatible in that it would take more than changing the PUT to POST?

**Comment by edpaget** [comment]
I'm not sure I haven't used this particular s3 feature before. I'll try to bang something out. Would be useful for other image upload areas too.

**Comment by edpaget** [comment]
It looks like using the PresignedPost involved much more than changing out the URL.

**Comment by edpaget** [comment]
@chrissnyder are you okay with this just being enforced through the Front-End? I'll probably set limits around 600kb

**Comment by chrissnyder** [comment]
Sounds fine to me.
