### ISSUE TITLE
Update the Team page

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#697]
- Victoria's image is broken
- Marten Veldthuis needs adding

**Comment by marten** [comment]
Victoria's image was just fixed in #689

**Comment by alexbfree** [comment]
OK guess it's not deployed yet! Leaving this open to add your entry.

**Comment by srallen** [comment]
I'm catching up from being out the past couple of days, but I should be able to add Marten's bio and image sometime today, too.
