### ISSUE TITLE
Add a presence for Daily Zooniverse - and the zooniverse blog(s)

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#698]
Maybe both in top bar, and on the landing page and/or project page.

As a reminder, here's what we did in the old site:
![Daily Zooniverse flash](https://cloud.githubusercontent.com/assets/1473244/8332021/72de5a2a-1a83-11e5-81d8-6fd6ab9b676e.png)

the text is a link

**Comment by mschwamb** [comment]
What about the Zooniverse blog as well ?

**Comment by alexbfree** [comment]
Yes we should link to http://blog.zooniverse.org/
We should add a list of blogs for the projects too e.g. 
http://blog.oldweather.org/
http://blog.snapshotserengeti.org/
etc
(currently these are not so obvious from old zoo home - something we can improve upon)

**Comment by aliburchard** [comment]
I'd vote for a daily zoo presence that is prettier than the old banner (sorry @mrniaboc)

**Comment by mrniaboc** [comment]
The DZ should be linked somewhere, yes!

@aliburchard Don't apologise to me, apologise to @heathv!

**Comment by heathv** [comment]
Hah, it *is* a bit goofy. But yes, I will get thinking on a way to integrate blog items and updates into the home page.

**Comment by chrislintott** [comment]
What about a top level link from the main page that just links to daily.zooniverse.org or to blog.zooniverse.org?

**Comment by heathv** [comment]
Sounds good to me for the short term. I'll still plan for a dedicated area on the home page.

**Comment by edpaget** [comment]
Closed by #785
