### ISSUE TITLE
Initial UX Planning

### ISSUE THREAD

**Issue by heathv** [zooniverse/Panoptes-Front-End#7]
[Here is a link](https://www.dropbox.com/s/t1qgkj2uxdp1e8g/sloan-ux-flowdiag-objects.pdf) to an initial UX planning document. 

This document gives the gist of how the new Zooniverse environment could flow together. The main aspect to take away is where Talk might live, as that seems to be holding up dev decisions. Its similar to the way it is now in that there are still individual Talks, but in this setup I have them being connected through a central "Talk Summary" page. Anyway, more details in the PDF.

I'll go into more detail and answer any questions on Mondays Sloan call. These are pretty loose, but I don't want to make any hard and fast decisions this early on.

**Comment by brian-c** [comment]
Moved to zooniverse/Panoptes-Design
