### ISSUE TITLE
Front-End requirements for leaf project

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#70]
It's now mid-January and the volunteer Front-End still looks very rudimentary. I know there's a lot of stuff going on behind the scenes, but I wanted to give you an idea of what @rcheng3 and I are expecting of the interface. In particular, I care much more about the volunteer front-end than the science team front-end. I can always code our implementation directly to the back-end, if necessary, but we need our volunteers to have a seamless, beautiful, happy experience.

We are hoping to start our alpha testing at the start of February and be doing beta testing during February for an early March launch.

For the volunteer front end, we need to be able to:

- [ ] Collaborate on projects. We can do this either by having one person create and own the project and allow the other permission to edit it. Or by having User Groups implemented. It doesn't matter to me, but @rcheng3 and I must be able to work together.

- [ ] Do masking. @camallen suggests in zooniverse/Panoptes#429 a two-image subject set, which we can create, such that one image (masked) is shown in 'classify' and the other (not masked) is shown in 'talk'. Does that work? I'd prefer a more elegant solution, but we can get by this way if necessary.

- [ ] Have images be a nice size by default; right now they are too tall, requiring scrolling down to see the "next" button.

- [ ] Have volunteers have a choice of workflows: we need to have an initial title screen where allow the volunteer to select from a few different workflows, in much the way that Notes from Nature allows people to choose a collection to work on or OldWeather allows people to choose a ship to work on. 

- [ ] Have a workflow where additional questions are asked based on marking tools. For example, if someone marks a tree as having non-green leaves, we want to ask whether the leaves are yellow, orange, red, or brown.

- [ ] Have just-in-time help/tutorial/guide.

- [ ] Supply a URL for each subject as metadata such that the volunteer could click somewhere and go to that URL during classification. (This is our hack for doing magnification.)

- [ ] Support keyboard shortcuts.

**Comment by mkosmala** [comment]
Can someone let me know if these requirements are going to be supported? And what the hoped for timeline is? It's February now, but the volunteer interface isn't functional enough to do alpha testing.

**Comment by brian-c** [comment]
Collaboration features are a future feature, but not an immediate priority.

Masking will not be available in version 1. Cam's workaround will have to do for now.

Images are sized to fill the space available on the screen, but they shouldn't be taller than the screen. If that's happening please open an issue.

Choosing workflows, per-mark subquestions, and inline help and metadata are in the works.

Shortcuts would be cool, but not a current priority. The site should be navigable by keyboard as is.

The classification interface should be finished up in the next two weeks.

**Comment by mkosmala** [comment]
Great, thanks!

**Comment by brian-c** [comment]
Per-mark tasks and per-task inline help have been implemented. I'll update docs on the main zooniverse/Panoptes repo soon, but the short version is:

* Each task in a workflow can have a `help` key mapped to a string of Markdown-formatted text that'll pop up if the user clicks the "Need a hand?" (proper design to come) button during that task. Example here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/mock-data.coffee#L16-L20

* Each tool in a drawing task can have a `details` key mapped to an array of task description objects. "single"- and "multiple"-type tasks are the only ones that work for now. Calculating the position of the details popup needs some work still. Example here: https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/classifier/mock-data.coffee#L26-L40
