### ISSUE TITLE
Improve pagination and navigation in project list

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#703]
There are a few problems with the current project list, in particular showing where you are, and how you navigate it:

Firstly, the message at the top
![showing 20](https://cloud.githubusercontent.com/assets/1473244/8332731/599d1840-1a87-11e5-9db0-3cbdbe5b54be.png)
* This gives no indication that there is more than one page, unless you scroll down. Could change it to "1 to 20 of 34" with a little Next page logo
* The wording is odd. Makes it sound like search results - which is not we want for the project list. We should give the impression this is a curated catalog, not the results of a search.

Secondly, the buttons at the bottom:
![buttons](https://cloud.githubusercontent.com/assets/1473244/8332782/960540aa-1a87-11e5-8360-c46384e55d53.png)
* These are tiny and hard to click. They look unstyled. They should be much bigger, and need some colour/styling/formatting.
* How will this handle large numbers of pages? Shouldn't we have previous/next and/or first/last buttons too. Are there "..."s when there are lots of pages?
* There is no indication of the current page. There should be a difference between the current page and the other pages.
* Are these even the right way to go? Pagination is dying out... Wouldn't an AJAX infiniscroll technique a la Tumblr be preferable?

**Comment by srallen** [comment]
@alexbfree, @heathv's original design for this page used a "Show more" button at the bottom to load more like an infinite scroll rather than pagination and then the number at the top would update too. I just hadn't gotten to it yet. I agree that an infinite scroll type page is better, but am not sure if it is necessary to get done for the soft launch. At least, the pagination buttons should be styled.

**Comment by alexbfree** [comment]
Thanks Sara for addressing my comments. Definitely looks a lot better! (though I would consider changing the word "found" for something like "projects" so it looks less like search results).

I agree infiniscroll is not a short term priority, maybe @chrissnyder this could be reopened and added to the post-soft-launch UI/UX list? Or maybe implementing infiniscroll per heath's design is already covered elsewhere?
