### ISSUE TITLE
Project email communcation check box

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#705]
Settings page is missing the project_email_communication check box

![missing_pec_field](https://cloud.githubusercontent.com/assets/295329/8333430/b154a7bc-1a8a-11e5-9d61-7f214a7d019e.png)

**Comment by chrissnyder** [comment]
Is this different than the settings available at http://preview.zooniverse.org/panoptes/#/settings?

**Comment by camallen** [comment]
yep - a true project_email_communication will automatically subscribe you to any project you classify on.

**Comment by DarrenMcRoy** [comment]
Uh, side note... How "you're" name will appear? Your name. Can we please fix that? :-)

**Comment by chrissnyder** [comment]
Was closed in https://github.com/zooniverse/Panoptes-Front-End/pull/739
