### ISSUE TITLE
Improve menu & footer UX

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#706]
Right now there are a few odd things about navigation between pages:
* The header and footer use a different hierarchy (e.g. Collections comes under Discover in the footer, but is its own section in the header). We should give each page a consistent home.
* Since there is no dropdown submenu in the header, it's not obvious that if you are looking for an About page or publications page you have to look under Learn. 
* Could we maybe add some breadcrumbs so that your current location is clear wherever you are?
* Some pages don't have a location in the header hierarchy (e.g. Privacy)

**Comment by chrissnyder** [comment]
Too broad, let's focus issues a bit more.
