### ISSUE TITLE
"New to Zooniverse" page

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#708]
A page for people who are new to the Zooniverse was planned for first-release when we drafted up the content. Text here:

https://docs.google.com/document/d/13sP5U4JRmewpJsNRoSfKt54KvYhiKcxzw3f5kyrUzAA/edit

Probably requires some design and an algorithm for the "random project" selector, but this was a popular idea when I drafted it out... everyone seemed to like it. Could be a future-plans thing, but it was originally slated for first-release. Thoughts?

**Comment by simoneduca** [comment]
This has been addressed in various form, closing.
