### ISSUE TITLE
Remove graphical artifact below project list

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#709]
On Chrome, OSX I am seeing a one-line pixel artifact below the project list:

![artifact](https://cloud.githubusercontent.com/assets/1473244/8333550/6bc4c85c-1a8b-11e5-822e-d147023258d5.png)

**Comment by srallen** [comment]
Got a PR in to fix this, but just FYI, this is a Chrome bug: https://code.google.com/p/chromium/issues/detail?id=297782
