### ISSUE TITLE
Volunteer front-end view customization

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#71]
I assume that we'll be able to do some customization to what the project looks likes to volunteers. (Otherwise, all Panoptes projects will look blandly similar.) Here's what we'd like to be able to change:
- [ ] Background color and/or image
- [ ] Project logo
- [ ] Font size (and maybe the font itself?) for the questions
- [ ] Image size; our images are of different sizes and we may want to have them appear so in the volunteer view
- [ ] Drawing questions need to look better. It would be great to be able to associate a small image/icon with each tool. 
- [ ] Present metadata about subjects during classification
- [ ] Suggestion: have the "back" and "next" buttons be directly under the question, rather than inline with the bottom of the image. People don't want to have to move the cursor back and forth such large distances. Or at least make this customizable.

**Comment by mkosmala** [comment]
Can someone please let me know if these customizations will be supported? And if so, along what timeline? Thanks.

**Comment by brian-c** [comment]
Sorry nobody's responded.

The background image and logo will be customizable.

Drawing tools' labels will be rendered as Markdown. We don't have arbitrary image uploading yet (zooniverse/Panoptes#443), but embedding external images will be a stop gap.

Some metadata will be available during classification. Not sure how to handle this yet.

I should be able to tackle these this week. The other requests you had are not in the works at the moment, sorry.
