### ISSUE TITLE
bad markings

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/Panoptes-Front-End#712]
in the image below red dots represent individual markings in Ali's wildebeest project. There is one red dot that is outside of the image. This is actually pretty common. I will filter such markings out but this may result in lost data (as opposed to preventing people from making such bad markings in the first place).
FYI - no idea about those 3 markings on the left hand side
![markings464574](https://cloud.githubusercontent.com/assets/6626461/8334425/d358be48-1a8f-11e5-8788-e46865956075.jpg)

**Comment by camallen** [comment]
@ggdhines could be related to mobile device? I've found it hard to remove marks and they don't always mark where i clicked. Can you check that annotation against the user agent?

**Comment by ggdhines** [comment]
"user_agent": "Mozilla/5.0 (Linux; Android 5.0.1; SAMSUNG-SGH-I337 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.93 Mobile Safari/537.36"
pretty sure that means a mobile

**Comment by aliburchard** [comment]
@ggdhines probably related to the fact that the wildebeest moves across the screen as you move across frames. I've asked folks to mark while in the first frame, but only specify it in the help text. Do we record which frame markings are made in?

**Comment by aliburchard** [comment]
oh, wait. I have no idea how there is a marking outside the image. but the three to the left of the wilde are because of the three frames.

**Comment by srallen** [comment]
Work has been done on a mobile app and we're gonna hide the aggregation button.
