### ISSUE TITLE
Talk lists incorrect username for comment replies quoted

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#713]
Not sure if this is just a feature of what's live of Talk now, but I thought I'd mention this since I saw it - 

If you reply to a comment someone made to a post in a thread, it quotes the right text but lists the user as the author of the first post in the thread not the actual person who wrote it

![screen shot 2015-06-24 at 11 52 02 pm](https://cloud.githubusercontent.com/assets/753325/8334777/53c2982e-1acc-11e5-824c-636201554de2.png)

I replied - it says mschwamb as the volunteer quoted, but I'm the author of the improvements thread that these posts are in

![screen shot 2015-06-24 at 11 52 09 pm](https://cloud.githubusercontent.com/assets/753325/8334795/714c7b4e-1acc-11e5-9c83-e075508b9070.png)

**Comment by aweiksnar** [comment]
I'm going to remove the reply feature for first release, since the current way of handling it doesn't seem great

**Comment by mschwamb** [comment]
If it counts, I thought it was fine other than the username issue.

**Comment by aweiksnar** [comment]
Ah ok sweet, I added that feature a while back and still feel like it needs polish. I'll fix up the username issue and see how things look!

**Comment by mschwamb** [comment]
I'm sure there could be tweaks to make it look a bit nicer, but I think it works just fine for launch if you're worried about it being useful.

**Comment by aweiksnar** [comment]
OK cool. I was thinking people could just use block-quotes directly since that is all replies do. But if I get the username issue sorted by the end of the day I'll leave it in
