### ISSUE TITLE
 Unlimited Character Entry in Password Confirmation Field on Reset Password Page

### ISSUE THREAD

**Issue by AeleSahithi** [zooniverse/Panoptes-Front-End#7139]
**Description:**

encountering an issue on the Zooniverse website (https://www.zooniverse.org/reset-password) while trying to reset password. The problem arises when entering the new password and confirming it.

**Steps to Reproduce:**
1. Navigate to the [Zooniverse reset password page](https://www.zooniverse.org/reset-password).
2. Enter a new password in the "New Password" field.
3. In the "Confirm Password" field, there is no limit to the number of characters that can be entered.

**Expected Behavior:**
The "Confirm Password" field should have the same character limit as the "New Password" field to prevent mismatched entries and potential user errors.

**Actual Behavior:**
The "Confirm Password" field allows an unlimited number of characters to be entered, which can lead to inconsistencies and issues with password confirmation.

**Screenshots:**
[image](https://github.com/zooniverse/Panoptes-Front-End/assets/170074947/f955895f-e5da-4f26-9de7-414d304aed2b)

**Comment by goplayoutside3** [comment]
Hi @AeleSahithi, thank you for the detailed Issue. The Confirm Password and New Password fields on the Reset Password page need to match regardless of character length. This is not a change we'll implement now.

I'm going to close this Issue for now, but please let me know if you encounter any problems with resetting your password in the future.
