### ISSUE TITLE
Does not work on iOS 5

### ISSUE THREAD

**Issue by marten** [zooniverse/Panoptes-Front-End#719]
Not sure how far back iOS is supposed to be supported, but on iOS 5 is fails with a completely useless "undefined is not a function" error, as well as a slightly more interesting "can't find variable: _enqueueMicrotask".

I'll hook the iPad up to my mac later tonight if it's supposed to work, in order to get some form of a stack trace.

Tried this using Brooke's cats project.

**Comment by brian-c** [comment]
Not worried about iOS 5 (8 is current, 9 is in beta), but it should at least show the "you browser is too old" message. Does it not?

**Comment by marten** [comment]
All you see is a white page.
