### ISSUE TITLE
Left-right choices

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#72]
For our leaf project, we need to ask some questions about pairs of images. @chrislintott couldn't promise paired subjects by the time we want to launch, so we agreed that one solution is for us to create single-image subjects that are actually pairs of images glued together. The simplest way to do this is to present the double-framed image and ask "left" or "right". But I know too many people who mess up "left" and "right" regularly to feel real happy with this solution.

The more elegant solution is to have people click on the image they want to choose. Is this easily supportable? At simplest, it could be an implementation of the drawing tool: "put a mark on the image you choose". And then we the science-team calculate which image has been chosen after the fact. 

It would be more awesome to actually have a box appear around the half of the image chosen. (We can guarantee that the subject will always be of two equally sized images.)

We're also going to need to support "left/right/both/neither" choices...

Thoughts?

**Comment by aliburchard** [comment]
@mkosmala @brian-c This sounds like it could be done as a standard marking task, paired with a short decision tree (which are being supported with the project building tools). You can ask a question that has "both, neither, one-or-the-other" and then if the answer is "one-or-the-other" you can click (mark a point or have your users manually draw a box, but that seems silly) on that side.

**Comment by mkosmala** [comment]
That's a reasonable way to do it. 

I would love it if a box appeared around the chosen image rather than a mark splotched on it. But I'll take what I can get. :smiley:
