### ISSUE TITLE
Remove 'collect' tab

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#720]
I think the 'collect' tab should be removed from the main top bar tabs. It doesn't seem  like the right place for it, and you see it in 'profile' anyway.

At the very list it should be hidden for users who are not signed in.

**Comment by edpaget** [comment]
Why? Collections are public and integral part of how discoveries are made in the Zooniverse.

**Comment by DarrenMcRoy** [comment]
Because collections should be integrated into your profile. Why have a different place for them?

**Comment by edpaget** [comment]
Sure your collections are in your profile, but what if you want to browser other people's collections? What if you'd like to search them? They should definitely be a top-level thing.

**Comment by DarrenMcRoy** [comment]
Aren't collections more of a project-by-project thing, though? You won't be searching across all Zooniverse collections. I think, just across an individual project's.

And I don't think that collections can include subjects from different projects (can they? should they?)

I agree with Grant. It seems odd to me to have them as a tab on the front page. I don't even know what would appear there in an empty state, for a newcomer?

**Comment by mrniaboc** [comment]
Don't you think Talk is the right place for them? Rather than having Talk and Collect as main tabs?

**Comment by edpaget** [comment]
Nope Collections can be cross-project or restricted to one Project,; Users can create new Subject Sets for a Project from a Collection; and Users can collaborate on a Collection, just like they would for a Project.

Collections can be public, so a newcomer would see the 20 most recently modified public collections on that page.

**Comment by DarrenMcRoy** [comment]
Well I do like that there are collaborative collections. That was highly requested.

**Comment by mrniaboc** [comment]
Hmmm, I didn't realise collections were gonna be cross-project. That changes everything

**Comment by chrissnyder** [comment]
Initial concern addressed. There still might be functionality/messaging issues with the page, but those can be separate issues.
