### ISSUE TITLE
Change 'Discover' to 'Projects'

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#723]
Change 'Discover' tab in top bar to say 'Projects'. Discover is not intuitive.

**Comment by DarrenMcRoy** [comment]
I also don't like "Learn" for the About page and Publications; also not intuitive. But I think the designers had a bit thing with trying to use just verbs?

**Comment by mrniaboc** [comment]
These changes should also be reflected in the footer.

**Comment by DarrenMcRoy** [comment]
If there's some compelling reason why we tried to use all these verbs, I'd like to hear it. Because I agree with Grant. The existing labels just don't work well.

**Comment by edpaget** [comment]
Is this based on Feedback from users? 

I think these labels are great and unless we're actually getting people saying they're confused by them I don't know why we'd change them.

**Comment by mrniaboc** [comment]
No, this is based on me and @chrislintott going through the copy on the site and changing things we really don't like. 

I don't mind 'Discover' as much, but Learn' makes very little sense for what's in there. 'About' would be much better.

**Comment by DarrenMcRoy** [comment]
It's not based on feedback from users, but you do have both of your communications guys saying it's confusing and unintuitive. :-) And, apparently, @chrislintott as well.
