### ISSUE TITLE
Reduce the description width and increase its line spacing and bottom margin on project page

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#725]
In short, this looks bad: 

![bad](https://cloud.githubusercontent.com/assets/1473244/8336908/af857f00-1a9f-11e5-80cf-a3f8fc5d7d8f.png)

this doesn't:
![good](https://cloud.githubusercontent.com/assets/1473244/8336915/bd4f2820-1a9f-11e5-8de9-2f61670c24ac.png)

**Comment by edpaget** [comment]
This already happened it's not deployed to the preview.zooniverse.org site yet.

**Comment by edpaget** [comment]
See #718
