### ISSUE TITLE
Link tiles need to display avatars as squares

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#728]
Pertaining to #655 and #681 --

All avatars that are uploaded are automatically cropped to be squares.

But currently, the link tiles display as rectangles, meaning that it is literally impossible to have your image fit properly.

This needs to be resolved in one direction or the other. :-)

**Comment by DarrenMcRoy** [comment]
(These tiles also need descriptions, as per #662.)

**Comment by srallen** [comment]
This is fixed.
