### ISSUE TITLE
Tool for moderators (?) to highlight posts for research teams

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#731]
We've talked about this before, but I think it's actually one of the best things that we can do with the new Talk: have a tool (perhaps just for moderators?) to flag posts for researchers' attention.

The numbers one and two problems that scientists have with engagement on Talk are: 1. finding the time to respond to volunteers, and 2. knowing where their limited time is best spend responding. Directing their attention to the most important posts is huge; I've had countless requests for some such tool.

Obviously, a future plan, but a fairly important one... ask any researcher, they'll tell you that they want this!

**Comment by aliburchard** [comment]
Yes!!! This researcher agrees.

**Comment by aweiksnar** [comment]
Closed with group mentions in #1549
