### ISSUE TITLE
Add something to collect tab empty-state?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#740]
Right now, the Collect tab returns nothing but a very sad "No Collections Found."

Following up on #720, if we are going to have this very prominent tab on our first release, should we have it do something? If the infrastructure for it is still being built out, maybe it should be added in a later deploy. Or can we put something there now?

**Comment by edpaget** [comment]
We should make our own collections. I'm going to have a better collection create interface done tonight, and we can set some up tomorrow.
