### ISSUE TITLE
A few projects don't have O icons

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#741]
Chicago Wildlife Watch, Old Weather, Ancient Lives, and Galaxy Zoo: Bar Lengths all lack proper Zoo-O icons. (So does Moon Zoo, but we're closing it as soon as Grant and I can; our attention has been on this launch.)

Meg also expressed concerns about Planet Four: Terrains not having an avatar.

Probably a future-plans thing and pretty darn low-priority, but those projects do stand out oddly in the project list.

**Comment by DarrenMcRoy** [comment]
Whoops, my bad. Okay, so the only projects without formal O avatars are CWW and GZ:BL.

@mrniaboc I don't suppose we could whip something up? The huge "CHICAGO WILDLIFE WATCH" does look a little disorienting among all the O's. :-)

**Comment by mschwamb** [comment]
Also P4: Terrains though we might try to grayscale the P4 avatar as a last minute fix (not sure it will look pretty)

**Comment by chrislintott** [comment]
Wildebeest and Whale Tails too.

**Comment by aliburchard** [comment]
Wildebeest is a spin-off of snapshot serengeti, so i'd happily have a slightly altered SS logo, but am happy with whatever for now.

**Comment by mschwamb** [comment]
That would be great if we could get a modified avatar at some point if it's possible - I think @michaelaye had some ideas/thought on  a P4: Terrains spin on the P4 logo

**Comment by mrniaboc** [comment]
This is a conversation that @heathv should be involved in

**Comment by heathv** [comment]
Certainly sounds doable.

**Comment by DarrenMcRoy** [comment]
Added the CWW one and sent the Terrains one to @mschwamb.

**Comment by mschwamb** [comment]
@DarrenMcRoy   I've sent the P4T avatar for the P4 team for their feedback. , but I don't think  this issue should be closed. There should be 3 more avatars for project launching from the project builder:  GZ Bars, Wildebeest and Whale Tails from my reading of @chrislintott's reply to my comment. Are those avatars in progress? 

cc @heathv

**Comment by mrniaboc** [comment]
@heathv @DarrenMcRoy I'm sure I saw thee CWW avatar somewhere, but can't find it now. Can you please point me to it?

**Comment by heathv** [comment]
@mrniaboc CWW and Terrains avatar are now in the [brand repo](https://github.com/zooniverse/Brand/tree/master/projects).

**Comment by chrissnyder** [comment]
Let me interject here and say that I don't think we should be getting into the practice of creating custom avatars for projects built on the project builder.

The way I understand these projects is that they are created by and for their various science teams, independent of Zooniverse involvement. In the short term, I can understand promoting all of through our usual channels as we want to get people using the site so we know what people really need to build great projects.

I think one of those features is design, and building a site that is both effective and pleasant when using science-team provided imagery. Continuing to add custom avatar designs done in-house is just punting this until later.

Yes, I understand that Whales, Bars, Terrains, and Wildebeests put up with a lot during the launch. Yes, I think we can and should support them as our launch set of projects. No, I don't think we should create custom avatars.

**Comment by michaelaye** [comment]
I agree and would like to point out that for Terrains we were not requesting it but were more like a punching ball floating back and forth while your internal decision process could not decide if our avatar should be with or without the Zooniverse logo. I seriously could not have cared less but went along with whatever you guys think it's best for the site. 
Great job everybody, I think this will be a huge thing!

**Comment by vrooje** [comment]
Just a quick post as this is now closed, but to say that I agree with @chrissnyder. Perhaps a logo could be a bonus for projects that become Zooniverse Projects, but that's as far as I'd go and I'm not even convinced that is required.

If it's decided to design a Zoo logo for GZ Bars, then obviously I wouldn't turn that down (!), but it's not necessary. And especially in this time when we want to encourage external teams to build their own projects I think it's good to have some non-Zoo logos on the front page.

**Comment by mschwamb** [comment]
Again, as I wrote in email what do y'all want me to do the Terrains avatar with  Zooniverse logo that I got sent by @DarrenMcRoy . 

My understanding from this thread's previous comments and @chrislintott comment was that it was decided these 4 projects were getting avatars eventually. 

Sounds like from @chrissnyder there is disagreement. Is the decision changing again?

Can someone tell me what's decided soon, we're doing a PR in the coming weeks and should have whatever is going to be the permanent avatar in place by then.

**Comment by mrniaboc** [comment]
If we are not to create avatars for approved projects, then we should
remove all of the avatars from the site. Otherwise the breakdown is
arbitrary.

**Comment by DarrenMcRoy** [comment]
I strongly agree with @mrniaboc, though for different reasons. I don't want to make projects that we built look different somehow from ones built with the project builder. We've also gotten some Talk feedback that all the O's look confusing. I really like those avatars in concept, but I don't think the front page is the best place for them to all be next to each other. I think we should eventually just make all of the avatars be images of the things that are being researched... a galaxy, a penguin, an exoplanet, the LHC, etc... as it was on the old Zoo home.

However, I want to emphasize that this is *really* low on my priority list, below the huge number of other bugs/problems/enhancements in this repo that I think are doing much more to impede group research, project selection, and discussion... ?

**Comment by mschwamb** [comment]
We're doing a press release for Planet Four: Terrains, it would be good if possible to know if we can use the avatar  in promotion or not that is likely going out before the end of the month.
