### ISSUE TITLE
Format the timestamp in the Default Project name for the project builder

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#745]
![project names](https://cloud.githubusercontent.com/assets/1473244/8342103/bf0c9a72-1ac1-11e5-8d5f-2cd5467ac84d.png)

Currently the default project timestamp seems to be in javascript format.
Can we change it to something like 2015-05-27 15:07 (remove the T and lose everything below 1s)

**Comment by alexbfree** [comment]
Also could we improve the formatting of this list (centralise it, add more padding, maybe a background or something?)

**Comment by edpaget** [comment]
The name needs to be something 100% unique for the owner, and is something people presumably will change right away. 

Agree about the formatting though.
