### ISSUE TITLE
When your inbox is empty, it should help you figure out how to send messages.

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#748]
Maybe have a sentence explaining how to send a message, or what messages are. Or some feature to find people to message....?

![inbox](https://cloud.githubusercontent.com/assets/1473244/8342340/4084be4e-1ac3-11e5-8cea-d292d49dff78.png)

**Comment by vrooje** [comment]
Just a "New Message" link right below the sentence?

This is pretty important.

**Comment by aweiksnar** [comment]
We should totally call the new inbox Z-Mail

**Comment by DarrenMcRoy** [comment]
No joke, that would actually be fantastic branding and I would be all for it.

**Comment by aweiksnar** [comment]
On it

**Comment by heathv** [comment]
Zombies ruined anything "Z-_____" for me.

**Comment by aweiksnar** [comment]
@heathv Ghosts ruined Gmail for me : (

**Comment by rogerhutchings** [comment]
Fire ruined Hotmail for me :/
