### ISSUE TITLE
Hide "feed" and "stats" in profiles

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#749]
Instead of just being empty and looking broken, could we add a note in people's profiles, under the Feed and Stats tabs, something like:

This feature is in development and will be added soon.
Please stay tuned to Zooniverse Talk for updates!

![screen shot 2015-06-24 at 4 52 04 pm](https://cloud.githubusercontent.com/assets/8987864/8342408/7cc6f8a4-1a91-11e5-98b8-3414223206db.png)

![screen shot 2015-06-24 at 4 52 12 pm](https://cloud.githubusercontent.com/assets/8987864/8342413/805a80c6-1a91-11e5-9063-838bf0e20100.png)

**Comment by chrissnyder** [comment]
I strongly dislike "under construction" pages. If there is nothing we plan on putting here for launch, we should just remove the pages entirely.

My reason for saying so is I don't want to get into the habit of promising specific features when we have no timeline for when we might deliver them. We might decide to deliver them next week, or next month, or change our minds entirely and never deliver them. Committing ourselves to a certain course of action in the eyes of our community rightly sets up expectations that we will see those commitments through. I would rather avoid committing to specific features than have to backtrack later.

**Comment by DarrenMcRoy** [comment]
I would also be perfectly fine with just deleting them until we have something to put there, but would that be a problem for you, @edpaget --?

**Comment by chrislintott** [comment]
Agreed with @chrissnyder

**Comment by mrniaboc** [comment]
I think it would be much better to have a placeholder message saying this is coming, rather than removes all users' personal stats out of the blue with no sign whether they're coming back or not.

**Comment by DarrenMcRoy** [comment]
@camallen and @edpaget say they are certain that stats are coming, for what that's worth.

We could delete the "feed" and placeholder the "stats?"

**Comment by mrniaboc** [comment]
What will be shown on the 'feed' exactly?

**Comment by camallen** [comment]
For stats, some data has been migrated and will be whilst the system is live, i think we should just check if the data exists, show it if it's there and if not show a message about the data being migrated soon. 

Stats activity counts (ala the old zoo home ribbon data) is via this end point, http://docs.panoptes.apiary.io/#reference/projectpreference/projectpreference-collection/list-all-projectpreferences

**Comment by DarrenMcRoy** [comment]
@mrniaboc As I understand it, the "feed" is the long-term holy grail of having a place where all the most relevant information to you--talk posts, replies, direct messages, announcements, project updates--flows. The same way Facebook's feed and Twitter's timeline gives you the most important stuff to you. It should, theoretically, be the place where everybody will want to check first when they arrive at Zooniverse in the morning/afternoon.

But I don't know how much has gone towards building the infrastructure for that yet. It seems very, very complicated?

**Comment by mrniaboc** [comment]
In that case I would be in favour of hiding it now, since it sound slike
there's probably a bit of work to be done on it.

**Comment by srallen** [comment]
The Feed page isn't totally blank. If you view someone else's profile while logged in, you will see the private message form. Since no other content exists for the feed yet, where should the private message form live? Additionally, what should be the page that people land on when they visit their profile link? If we hide both feed and stats, then the profile link should hide since the other links for messages, collections, and settings are separate routes and links.
