### ISSUE TITLE
Deploy to demo on push to master

### ISSUE THREAD

**Issue by brian-c** [zooniverse/Panoptes-Front-End#75]
Clone the repo and run `npm install && npm run stage` when master changes.

**Comment by brian-c** [comment]
Additionally, it would be really good to start making this available at the same domain as the API (panoptes-staging.zooniverse.org for now). Are non-API requests going to be proxied to an S3 bucket?

**Comment by camallen** [comment]
Originally we were going to relaunch zooniverse.org after rebuilding into PFE. We can't do this so...

Could we get away with just a stargazing live specific url in the meantime, http://supernova.zooniverse.org/. The last supernova one was http://supernova.galaxyzoo.org/

OR should be just use 'something'.zooniverse.org/supernova ?

**Comment by brian-c** [comment]
The project is going to exist in the app frame of the PFE, so its path will be something like #/projects/Zooniverse/Supernovae. I know @chrislintott is going to want something TV-friendly like http://www.supernovastopwatch.org (cool name right?) redirecting to the project, so maybe we could put it somewhere like **http://new.zooniverse.org/#/projects/Zooniverse/Supernovae** to indicate that this will be the new Zooniverse?

**Comment by astopy** [comment]
Forgot to close this when I set up the automatic deployment. Discussion of domain names, etc. to continue elsewhere.
