### ISSUE TITLE
Change central-Talk header from "Talk!" to "Zooniverse Talk."

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#750]
Can we change the name of the central talk from "Talk!" to "Zooniverse Talk"?

http://preview.zooniverse.org/panoptes/#/talk

**Comment by chrissnyder** [comment]
I thought this was already discussed in https://github.com/zooniverse/Panoptes-Front-End/issues/185 and seemed to decide on just "Talk"?

**Comment by DarrenMcRoy** [comment]
For the main page, yeah, but when you actually arrive here:

http://preview.zooniverse.org/panoptes/#/talk

It certainly shouldn't be "Talk!" in any case... is there a reason it can't say Zooniverse Talk there (above the search bar) so that it's clear which one you're on?

**Comment by chrissnyder** [comment]
Ah, good point.

Other ideas rather than just repeating a header? The navigation link above is highlighted, so the user's location is already communicated somewhere. Or it could be just "Zooniverse Talk", not too fussed either way.

**Comment by DarrenMcRoy** [comment]
I still like having an umbrella that makes it clear you're in the central Talk. Won't that same area say "Floating Forests Talk" if you're in the Floating Forests Talk? :-)

**Comment by chrissnyder** [comment]
Doesn't say anything on project Talks, see http://preview.zooniverse.org/panoptes/#/projects/mschwamb/planet-four-terrains/talk

**Comment by DarrenMcRoy** [comment]
Hm. Well, in that case, maybe we could remove that text altogether.

But I'd still be in favor of having "Zooniverse Talk" there, if only because it's an entirely new concept for our community.
