### ISSUE TITLE
Front page column alignment issue

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/Panoptes-Front-End#752]
Columns 2 and 4 are not in line with columns 1 and 3. See screenshot.
https://www.dropbox.com/s/9qzmmke87269igd/Screenshot%202015-06-24%2017.01.53.png?dl=0
Browser: Safari 8.0.5 on OSX 10.10.3

**Comment by chrissnyder** [comment]
We just updated a lot of the styling of the project page. Could you check again at http://preview.zooniverse.org/panoptes/#/projects and confirm this is still happening?

**Comment by michaelaye** [comment]
all good now.
