### ISSUE TITLE
Latest tags all link to main search

### ISSUE THREAD

**Issue by aweiksnar** [zooniverse/Panoptes-Front-End#754]
Same as #727 but different spot :pensive:

**Comment by chrissnyder** [comment]
Is this a problem with the search page or the way the tags are parsed?

**Comment by aweiksnar** [comment]
Nope I just had those all direct at the zoo talk before the project-talk-search page existed and forgot to point them at the new page since they don't show up on most pages in dev mode. It's a quick fix I'll have up in a few
