### ISSUE TITLE
new bio request for about page

### ISSUE THREAD

**Issue by lfortson** [zooniverse/Panoptes-Front-End#757]
(Chris S. told me the best place to put this was on an issue here :-) )

My bio text is WAY outdated.  Could some kind person please upload the following:

Lucy Fortson, University of Minnesota Zooniverse Director (@lucyfortson)
Associate Professor of Physics and Astronomy at the University of Minnesota. One of the Zooniverse
co-founders, she helps with project wrangling (aka management) and strategic planning while trying
to squeeze a bit of galaxy evolution science in. 

Thanks!
Lucy

**Comment by lfortson** [comment]
Oops! The text "University of Minnesota" in front of Zooniverse Director as I originally had it is pretty important! Otherwise it looks like I'm the director of the entire Zooniverse!!  Can someone please make that change? Thanks!!  Lucy

**Comment by aweiksnar** [comment]
On it

**Comment by lfortson** [comment]
Thanks guys!! Wouldn't want Chris L to think I was staging a coup :-)

**Comment by mschwamb** [comment]
I just noticed that it looks like this got lost in a recent merge

**Comment by mschwamb** [comment]
nevermind - needed to refresh my browser.. Sorry!
