### ISSUE TITLE
Add a length/character limit to Descriptions

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#758]
With regards to #756 -- whatever size the project cards end up being to accommodate whatever size font we go for, we should limit the Descriptions field in Panoptes to a length that will fit on that card, yes?

That or create a "..." cutoff if it goes too long.

**Comment by chrissnyder** [comment]
Punting because the only project that will show up in the list at the moment are ones we've approved.

**Comment by DarrenMcRoy** [comment]
Good call.

**Comment by mschwamb** [comment]
A note to say all 4 projects for launch now fit the limit (P4:T was a little over - that's been fixed)

**Comment by edpaget** [comment]
Closed for zooniverse/Panoptes#1043
