### ISSUE TITLE
Posted a comment on Talk and it doesn't show

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#759]
Can't always reproduce this. Saw it once and thought I made a mistake, but one of my Talk moderators has seen this happen a few times 

'
Hi Meg. Thanks for update. Just posted two comments on two different discussions. Pressed 'Submit' and got the 'submitted successfully' message in blue, but my comments aren't there! I've moved to other pages and returned, but no show. I've refreshed page, again no show.' 

@aweiksnar is that because you've been making updates?

**Comment by mschwamb** [comment]
Actually none of posts are now showing up - did something change - am I using the correct site still preview.zooniverse.org/.... ?

**Comment by aweiksnar** [comment]
Yeah something is up, I'll look into the cause of this. Thanks for posting the issue.  Must have happened this afternoon because I was commenting fine today

**Comment by mschwamb** [comment]
Also can't add a collaborator or a subject set in the project builder so this might all be related #764 #763 #765

**Comment by mschwamb** [comment]
I'm up on all day (on the other side of the world) so if you someone extra accounts/eyeballs for testing let me know. 

Sounds like there's something system wide pretty much nothing that was working 2 hours or so ago is working now

**Comment by mschwamb** [comment]
If it helps, it's not just P4. I tried to post on Galaxy Zoo bar same thing -

**Comment by aweiksnar** [comment]
This was due to a version update in the client lib https://github.com/zooniverse/json-api-client. Will be up and going again once that is bumped to the previous version

**Comment by mschwamb** [comment]
if you want to let me know when it should be all good and the change should be live. I can try it out. Currently still having issues. Can't make a new project,add collaborators,etc

**Comment by aweiksnar** [comment]
Hey @mschwamb, can you give it a test and let me know? I just left a comment on Planet Four Terrains successfully so it should be back up and running

**Comment by mschwamb** [comment]
yeppers - so I'll close this. I'll check everything else.

**Comment by aweiksnar** [comment]
Great! thanks for testing that out!

**Comment by mschwamb** [comment]
No problem. Looks like everything else works phew! Let me know if you want to go through and push the buttons on Talk and report anything funky

**Comment by aweiksnar** [comment]
OK will do!

**Comment by mschwamb** [comment]
should be if you want me to do that - but figure you got the point (hard to type with two taped fingers... boring story)
