### ISSUE TITLE
New landing page design of project builder project hides the project introduction

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#761]
On my 13 inch macbook pro on firefox, the project description is now well below the viewing window that I'd have to scroll to see it, but if I was new to the site I wouldn't know to scroll down
![screen shot 2015-06-25 at 8 13 57 am](https://cloud.githubusercontent.com/assets/753325/8344285/42f188f2-1b12-11e5-8034-d27e47120d92.png)

I only know to scroll because of the old design to see the description

![screen shot 2015-06-25 at 8 10 44 am](https://cloud.githubusercontent.com/assets/753325/8344289/508dbb52-1b12-11e5-925a-55af13a205ac.png)

Maybe the description can be brought up a bit so people can see it. I think the description helps because we have no tutorials to introduce the projects 

Love the new design though

**Comment by mschwamb** [comment]
@mrniaboc and @aliburchard  do you agree? otherwise you have to look at the help to know the purpose if you didn't know there was more text.

**Comment by alexbfree** [comment]
I agree this is a problem.

The following CSS changes will fix it:
* Change ".project-home-page .call-to-action-container" min-height to 400px
* Change ".project-home-page hr" margins to 0px in all directions
* Change ".project-home-page .description" top margin to 0px (but keep bottom margin of 40px)

Then you get something like this on a MacBook Air 1440x900 screen:
![fixed CSS screenshot](https://cloud.githubusercontent.com/assets/1473244/8350311/379e84be-1b1c-11e5-8a64-4ee8b2cbacf4.png)

**Comment by aliburchard** [comment]
I agree -- I really like the look, but want that extra text visible at first glance.

**Comment by chrissnyder** [comment]
Disagree this is a problem. I think people are going to scroll regardless of whether or not they see anything below because that's what you do on a web page.

No matter how small you make it, it will always be too large for some screen sizes.

How it looks on my 13" MBA:

![](http://i.imgur.com/nAPNz4n.png)

**Comment by mschwamb** [comment]
i disagree that people will scroll - their intuition is going to hit the button I think -  is their some compromise on design where we could at least get the text back. I think it provides context needed since their are no introductory tutorials that the new design doesn't give since their's no inkling on the landing page that there's text below ?

**Comment by edpaget** [comment]
Should we have to make sure the text is visible on a phone screen?

**Comment by mrniaboc** [comment]
I think it's looks good, and I see the whole thing on my 13" screen without
having to scroll. I also agree with Chris S that people tend to scroll down
on webpages even if there is a call to action button at the top.

**Comment by mschwamb** [comment]
majority rules and y'all see the text, so I'll close the issue.

**Comment by alexbfree** [comment]
FWIW @mschwamb I agree with you, and I see the issue too. 

BTW, Google Analytics tells us that lots of our users have short screens...
![analytics](https://cloud.githubusercontent.com/assets/1473244/8354632/73815e82-1b41-11e5-810c-4d3354a2a1f5.png)

I don't agree that most people scroll, but since 768px is the most common screen height, maybe it's best left as is.

**Comment by mschwamb** [comment]
Okay. Sounds like I should reopen so people can keep discussing

**Comment by chrislintott** [comment]
@alexbfree I just edited your comment so you're not posting our analytics data in a public forum.
