### ISSUE TITLE
Talk sidebar needs purging

### ISSUE THREAD

**Issue by lfortson** [zooniverse/Panoptes-Front-End#762]
the Talk sidebar on the "Talk" page from Zooniverse home has a list of random projects in it;
this needs to be purged and updated with all relevant projects.

**Comment by DarrenMcRoy** [comment]
Only one should be P4: Terrains, right?

**Comment by mschwamb** [comment]
Isn't GZ: bars and a few of the ecology projects launching,  and the projects listed on the front page (maybe P4: Terrains could get listed there too?) 

But yes P4: Terrains team is ready to go with Talk and Talk moderators set up and waiting

**Comment by mschwamb** [comment]
not sure if this feasible in the time frame, but when you're on a project talk it would be nice if Zoonivese Talk showed up in the list
