### ISSUE TITLE
seeing duplicate subjects and their not marked as duplicates on live project

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#764]
I switched P4: Terrains to live (maybe that doesn't do anything), but I'm seeing the same images over and over again - it's still not showing because of the beta test and approval requirement that @edpaget is going to toggle is that causing this issue

subject 483990 is an example of one I've seen multiple times

I switched to a new subject set, and now keep seeing the exact same images over and over

Is this something to do with the statuses?

**Comment by mschwamb** [comment]
It's not a problem if I'm a logged out volunteer - something about being logged in it keeps repeating the same images

**Comment by mschwamb** [comment]
basically looks like the same images on repeat even though the subject set has 5000 subjects

**Comment by edpaget** [comment]
Have you recently removed any subjects from your project?

**Comment by mschwamb** [comment]
No - just added

**Comment by mschwamb** [comment]
I did switch one set off and put the one @camallen loaded up. if i switch to the beta test set I have no issues

**Comment by mschwamb** [comment]
@edpaget I just tried to add you as a collaborator to the project but it returns back an error

**Comment by edpaget** [comment]
Thanks. I can find out info from checking the database. I'm looking into what's up now.

**Comment by mschwamb** [comment]
Thanks Ed. Also might be related, but I can't make a subject set either. Also no comments are showing up in talk.

**Comment by mschwamb** [comment]
Appreciate you looking at this so late in the evening @edpaget

**Comment by edpaget** [comment]
Can you refresh your page or login/out your user token may have just expired.

**Comment by mschwamb** [comment]
No - tried that earlier - just logged in one separate browser on Chrome rather than Firefox and still can't add you to a project as collaborator. Also logged in with a testing account and got the same result

**Comment by mschwamb** [comment]
Seems like these all happened at the same time #759 #763 #765

**Comment by mschwamb** [comment]
Looks to be fixed so I'll close and reopen if it reappears

**Comment by edpaget** [comment]
:fireworks:
