### ISSUE TITLE
"choose workflow" button doesn't work

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#771]
My two worfklows always show up as options on the landing page, whether or not that box is checked.
![screen shot 2015-06-25 at 10 45 54](https://cloud.githubusercontent.com/assets/6217406/8351751/7fbcad7e-1b27-11e5-8d44-784912b3d77e.png)

![screen shot 2015-06-25 at 10 50 43](https://cloud.githubusercontent.com/assets/6217406/8351831/0b52963c-1b28-11e5-84d7-02a01917a093.png)

**Comment by chrissnyder** [comment]
Might have to do with https://github.com/zooniverse/Panoptes/issues/1017?

**Comment by camallen** [comment]
@aliburchard can you please try again?

**Comment by aliburchard** [comment]
fixed!
