### ISSUE TITLE
Can't close Help pop-up if scrollbar used to scroll to top of pop-up

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#773]
On [GZ Bars](http://preview.zooniverse.org/panoptes/#/projects/vrooje/galaxy-zoo-bar-lengths/classify) I'm finding that I can replicate an issue with not being able to close the help text pop-up. If I scroll to the bottom of the help and then all the way back up, the "X" to close stops working, and if I click there I end up clicking on whatever is under that button (project builder in my case). The link loads under the pop-up, which doesn't close. So I end up with a screen that looks like:

![screen shot 2015-06-25 at 12 23 24](https://cloud.githubusercontent.com/assets/2357126/8353399/57f400ae-1b35-11e5-8d2e-3ec57449aaa3.jpg)

The only way I can get the pop-up to go away is to refresh the page, which means I lose the classification I had been working on (the same subject reloads, but I have to start over).

**Comment by mschwamb** [comment]
related to  #753

**Comment by vrooje** [comment]
Oops, sorry, missed that.

**Comment by vrooje** [comment]
I just got this again. With the pop-up scrolled to the top I was highlighting "build a project" underneath the X. I scrolled it down and I was able to close it. I'll let you know if I can repeat it.

**Comment by vrooje** [comment]
Yep, repeated.

**Comment by brian-c** [comment]
I can't reproduce this. What browser? Have you cleared your cache?

**Comment by vrooje** [comment]
Chrome - haven't cleared it in a while, so will try.

**Comment by vrooje** [comment]
Must have been caching - it seems fine now. Thanks.
