### ISSUE TITLE
"showing 20 found" makes no sence

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#774]
On the projects list page, this statement doesn't really make sense as it's not a search that has been performed. Would be better to replace with "showing [X] of [N] projects"

**Comment by aweiksnar** [comment]
#703

**Comment by DarrenMcRoy** [comment]
I think we have this marked as near-term polish in #703.

**Comment by mrniaboc** [comment]
Sorry!
