### ISSUE TITLE
Fix Firefox issue with low-slung letters being cut off

### ISSUE THREAD

**Issue by chrissnyder** [zooniverse/Panoptes-Front-End#777]
- Related to #756 
- Since the only projects that will appear in the project list at the moment are ours, we should truncate the description text to ensure it fits within the space provided.

**Comment by DarrenMcRoy** [comment]
All descriptions are rewritten and all fit. The only remaining niggle is that the bottom of the fourth line is being cut-off for low-slung letters:

![screen shot 2015-06-25 at 9 32 47 am](https://cloud.githubusercontent.com/assets/8987864/8356979/0d66b1f6-1b1e-11e5-83e2-7bf94109ae90.png)

@srallen may be able to fix by decreasing the margin around the "Get Started" button?

**Comment by DarrenMcRoy** [comment]
Identified as just a Firefox issue. Can pull from first-release.
