### ISSUE TITLE
Posts not showing up on Talk again

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#791]
@aweiksnar is this the same thing as  #759 popping up again?

**Comment by aweiksnar** [comment]
@mschwamb I was just able to comment successfully, Is this still coming up?

**Comment by mschwamb** [comment]
yes. it's back now. Though the moderators reported having the same issue  so it was occurring on more than 1 account. I'm not sure what changed.

**Comment by aweiksnar** [comment]
Ah ok I'm not sure what deploys have happened today, but if this becomes an ongoing thing then please reopen
