### ISSUE TITLE
researcher orange text hard to read on Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#792]
low in the queue but I find the Researcher orange (like that the color is different from moderators) is a bit too bright and hard to see the text - not sure if anyone else agrees  maybe it could be a cooler color like green or blue instead? Or maybe it's the text size?

Screen Shot 2015-06-26 at 1.13.52 AM

**Comment by aweiksnar** [comment]
I chatted with @heathv about this and it sounds like we're going to remove colors from role displays in talk and use white text on grey background for all roles

**Comment by DarrenMcRoy** [comment]
This is fine for now; let's revisit colors for roles in the long run. It's very useful for identifying a user's role at a quick glance. I imagine we will get feedback about it. :-)
