### ISSUE TITLE
On pages with a the blue banner - Can't x out of register screen &  top of the box is behind blue bar

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#793]
At least on Firefox 38.0.5 on Mac the register box goes behind the blue banner if it exists like on the Zooniverse Talk page

![screen shot 2015-06-26 at 1 41 21 am](https://cloud.githubusercontent.com/assets/753325/8361248/943dc152-1ba4-11e5-98c6-43dc52af1a2d.png)

**Comment by mschwamb** [comment]
Also on pages like the projects page where it sits above the blue banner - the x to close is unresponsive (I'm not sure if the previous fix that is currently live on the preview site or not) 

![screen shot 2015-06-26 at 1 44 05 am](https://cloud.githubusercontent.com/assets/753325/8361301/e6773e08-1ba4-11e5-85ef-fe787a4cf330.png)

**Comment by brian-c** [comment]
Fixed in #775.
