### ISSUE TITLE
issues selecting a display name

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#798]
display name on profile updated but the autosaver showed up red if I write Meg but okay if I write Meg Schwamb or mschwamb

Is this because someone else has the display name Meg?

It wasn't clear to me what was happening with the red, but on the top right bar where the profile picture is, it did change the text to Meg

**Comment by mschwamb** [comment]
Also looks like if it's red color then the change isn't propagated elsewhere

**Comment by edpaget** [comment]
Yeah red means it failed. It'd be cool to have some sort of error message.

**Comment by mschwamb** [comment]
Yeah - like that name is already taken or something would be helpful 

It would be good if it didn't rewrite the white text by the avatar as well since it looked like it worked when it didn't. My only clue was on Talk where it was still showing mschwamb
