### ISSUE TITLE
feature all four project builder projects on the front page?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#799]
a thought and low in the queue - if there's only four project builder projects launching with the new system, with three showing on the front page, would it be worth showing the 4th (I think that would be P4: Terrains) so the science teams feel treated equally and their projects are promoted equally? 

I'm on the 4th team so this is a bit self serving. I also get design, feasibility, and higher ranked things matter more right now.  Also if there's more than 4 projects launching this suggestion makes no sense.

**Comment by chrissnyder** [comment]
As far as I'm aware, there are the 4 projects and unless someone says otherwise, I think this is a good idea. Adding shortly.
