### ISSUE TITLE
permissions wrong on the contact us google form

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#800]
The google form on the contact page is saying that 'This form can only be viewed by users in the owner's organization.' when I click on the link  cc @mrniaboc @DarrenMcRoy

**Comment by mrniaboc** [comment]
@mschwamb Which link is doing this?

**Comment by DarrenMcRoy** [comment]
I know which it is. it's the proposal contact I set up earlier today. I forgot to switch it over so that anyone could enter responses into the form. I will take care of it as soon as I get home. :-)

**Comment by mrniaboc** [comment]
Thanks @DarrenMcRoy. Can you share the original doc with me too please?
