### ISSUE TITLE
How to Build a Project doc needs a page

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#806]
It's just a Google doc just now (https://docs.google.com/document/d/1EpiOJFMGFzIq34NXkRvsO8-Hixl4MzxvwPm0_aiF9xo/edit#heading=h.gjdgxs), but in the near-term we should make a proper page for this.

**Comment by srallen** [comment]
@mrniaboc, I started working on building a page for this. I'm seeing some comments in the google doc, could you let me know if the content is ready to go or if it is still being edited? Thanks!

**Comment by aliburchard** [comment]
@mrniaboc @srallen I've resolved the comments (@mrniaboc - the only real lingering one was adding a pointer to later in the document where readers can get more details on the subjects and manifests.)

There are a number of places where we say ("you can get more details in the Details-workflows section") or something similar. Worth perhaps providing links that automatically scroll you to that location in the doc? (Not urgently...)

**Comment by srallen** [comment]
@mrniaboc, @aliburchard:  I've setup a page for the how-to documentation and deployed it to staging for now since I thought you'd like to see it before did a PR: http://demo.zooniverse.org/panoptes-front-end/how-to-page/#/lab-how-to

I made a minor change to the text under Getting Started so I could make a nice link to the Project Builder landing page instead of paste in a URL. Let me know where I should add anchor tags or make any other changes.

**Comment by mrniaboc** [comment]
That looks great, but do you think you would be able to make the
screenshots larger? They should be quite high res in the Google document.

**Comment by srallen** [comment]
I've redone the images. Just FYI, you can't export images out of a Google doc directly. I had to download the document - initially I tried docx which is where I got the compressed versions. This time I grabbed it as a HTML doc with a separate image folder and that worked.

I also updated the project link per Brooke's note in the Google doc. Is there anything else that needs to change?

**Comment by vrooje** [comment]
Should we take out the URLs in the screenshots? Or am I being paranoid?

**Comment by vrooje** [comment]
Also, 2 things:

  - On the demo.zoo site, the link to the Kitteh Folder is broken (should be absolute, not relative).
  - This doc now needs updating in some parts, e.g. the "private project" tickbox has been replaced with the Visibility page.
