### ISSUE TITLE
can't set project live?

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#811]
Trying to set wildebeest live again after making last minute science team changes: 

![screen shot 2015-06-25 at 23 45 40](https://cloud.githubusercontent.com/assets/6217406/8367297/a52d1b12-1b94-11e5-8624-3cf70d6336ea.png)

**Comment by camallen** [comment]
@aliburchard can you hard reload the page?

**Comment by aliburchard** [comment]
seems to be fixed
