### ISSUE TITLE
Can't edit the title of a Talk thread

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#813]
There currently appears to be no way to edit the title of a thread that you start in Talk.

![screen shot 2015-06-25 at 6 51 03 pm](https://cloud.githubusercontent.com/assets/8987864/8368060/293ec326-1b6b-11e5-900b-ee0fe4a4dc80.png)

Can edit the post, not the thread title?

**Comment by chrissnyder** [comment]
Not sure this is a bad thing. Allowing the discussion thread owner to change the title could very easily lead to confusion. If we had more bookkeeping on the site (like here on Github) then I could see the argument.

**Comment by DarrenMcRoy** [comment]
I would argue for more functionality over less. This has always been possible in the current Talk and has never really led to problems...

**Comment by aweiksnar** [comment]
This is already in place. Just click the moderator controls button and there will be a form to edit it

**Comment by DarrenMcRoy** [comment]
Yep, ordinary folks should be able to, too, I think. We have that now?

**Comment by aweiksnar** [comment]
Not currently, only mods can edit that right now

**Comment by DarrenMcRoy** [comment]
Okay; let's talk tomorrow about maybe updating that. Not necessary to launch obviously. :-)

**Comment by mschwamb** [comment]
What about for typos? Previous versions of Talk lets person who started the thread to edit the title. I think it would be helpful especially for myself who is always riddled with typos even after reading 10 times.

**Comment by parrish** [comment]
I could go either way.  I can always add the permission now and figure out if we want to expose it later.

**Comment by DarrenMcRoy** [comment]
I think that we should do this. Talked with @chrissnyder and @aweiksnar about this yesterday and we agreed that we should. This functionality existed in the last Talk and has never, to my knowledge, caused any sort of problem. If it did, we could revisit, but it's never been an issue, so right now it's just a missing functionality that our users are used to having.

**Comment by chrissnyder** [comment]
Bit of a clarification that I don't really have a strong opinion here either way. I'd defer to those who use the system more frequently than I do.
