### ISSUE TITLE
very long workflow text overlaps the right-side options

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#816]
The bars project has "Default" text before each question, so the workflow text is really long. This leads to this UI behavior:

![screen shot 2015-06-26 at 02 10 20](https://cloud.githubusercontent.com/assets/2357126/8368950/c005bbe6-1ba9-11e5-8742-a42e0ec81263.jpg)

(The question showing isn't the longest question in the workflow.)

I don't think the answer is to truncate the question text in the drop-down menu, as the "Default" text means all my questions start with the same thing. Can there be line breaks in each option?

**Comment by chrissnyder** [comment]
Per-se isn't a bug, but I think something needs to be done here. Whether we limit the length of the workflow text, or simply apply `overflow: hidden`
