### ISSUE TITLE
Not being able to switch or add subjects sets on a live project without making it not live

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#824]
Not for launch, but I just noticed that I can't switch subject sets once a project is live. That seems problematic that you have to take a project down temporarily to add a subject set? Thought I'd mention it in case it's any issue for another of the other live projects

**Comment by chrissnyder** [comment]
Yea, @aliburchard brought up a similar issue on adding subject sets to/from workflows. Definite thing to fix.

**Comment by vrooje** [comment]
Linking this to zooniverse/Panoptes#1021

**Comment by chrissnyder** [comment]
Labeling this as Sprint 1, but nothing really to do on it on the FE. As soon as zooniverse/Panoptes#1021 is closed, we can close this.

**Comment by chrissnyder** [comment]
Moving this to Future Plans, pending zooniverse/Panoptes#1021

**Comment by vrooje** [comment]
Apparently zooniverse/Panoptes#1021 is done, so now all that's left is front-end mods?

**Comment by srallen** [comment]
Project owners on live projects can now manage a workflow's activeness and can make a workflow inactive to add new subject sets.
