### ISSUE TITLE
Auto-generated collection name funky, can't change

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#827]
I've favourited 1 image so far, but when I went to check out my collections, it pops up as "favorites (6)" (and /favorites-6 in the url). I can open the collection settings and click in the name box to change the name, but can't actually edit the name.

Even if the 6 referred to the number of images in my favorites collection (it doesn't), it's a bit weird in the name of the collection itself.
![screen shot 2015-06-26 at 08 17 30](https://cloud.githubusercontent.com/assets/6217406/8372547/14827470-1bdc-11e5-8e36-9cd752f1ea85.png)

**Comment by aliburchard** [comment]
OKay, also weird -- I went back to check the collection-settings, and it looks like I was able to delete *one* of the parentheses, even though editing in the collection name doesn't appear to work.

![screen shot 2015-06-26 at 08 20 20](https://cloud.githubusercontent.com/assets/6217406/8372579/59fd44c6-1bdc-11e5-9ee0-7f76ca484abd.png)

**Comment by mschwamb** [comment]
having the same issue expect one or two letter got added on the end when I tried to rename a collection I just made
