### ISSUE TITLE
Should collections on creation be default public ?  - currently set to private by default and have to uncheck to make public

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#828]
I think by default we would want to make collection creation have public visibility so that volunteers and science teams can see them and peruse them like the previous way collections worked. I think the added feature of hiding a collection should be an opt in where you have to check the box

I think will tend to leave the default, and there will be more private than public collections potentially.

![screen shot 2015-06-26 at 5 08 45 pm](https://cloud.githubusercontent.com/assets/753325/8374199/1dfaebd2-1c26-11e5-91e1-13dda11440a8.png)

**Comment by mschwamb** [comment]
This might be a discussion for @mrniaboc and @DarrenMcRoy

**Comment by mrniaboc** [comment]
I feel they should be public by default.

**Comment by vrooje** [comment]
Me too.

**Comment by DarrenMcRoy** [comment]
Agree!
