### ISSUE TITLE
typo on the publications google form

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#833]
@mrniaboc @DarrenMcRoy  low priority but since I noticed it, I thought I'd mention it. There's a typo on the publiciations [google form](https://docs.google.com/forms/d/18jwLbtV_6M5HCM74xNFtFbiiszWAxpC5IGHaToYjeiw/viewform) 

 'Articles accepted for publication but not yet publish are also fine.'

publish --> published

**Comment by DarrenMcRoy** [comment]
I don't think I have editing rights to this document. @mrniaboc -- is this something you created? Could you please share it with me, and/or make this edit?

**Comment by vrooje** [comment]
If we're changing the publications form there's some other fields I'd like to add for stats aggregation & reporting later... but we can chat about that offline.

**Comment by mrniaboc** [comment]
Typo fixed. Thanks Meg. Brooke, I'll chat you you offline about other changes.
