### ISSUE TITLE
Talk: a moderator reports smilies not showing up in Chrome

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#835]
http://preview.zooniverse.org/panoptes/#/projects/vrooje/galaxy-zoo-bar-lengths/talk/21/94

We seem to be using the same version of Chrome -- except PC (her, I think) vs Mac (me) -- and I can see them.

**Comment by edpaget** [comment]
Emoji aren't [supported in Windows Chrome](http://caniemoji.com/windows/) we could use something like [this](https://github.com/twitter/twemoji) or hold tight because support is supposed to be coming soon.

**Comment by DarrenMcRoy** [comment]
This bugged a lot of people upon launch today. If we can get in a workaround, that'd be awesome. :-)
