### ISSUE TITLE
Clicking your own name goes to your inbox, and the Back button breaks

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#837]
It looks like clicking someone's name in Talk currently takes them to the page where you can send that person a DM.

Clicking on your own name, however, goes to your inbox, and then the Back button on your browser can't get you out of that inbox.

I assume this will eventually change once profiles are more fleshed-out, but for now, can we at least make the back button get you back out?

**Comment by srallen** [comment]
@DarrenMcRoy, the redirects are in place since the user profile didn't have any content yet. I have a PR to fix the back button issue.
