### ISSUE TITLE
"Build a Project" name in top tab... ?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#840]
As we've gotten away from the "everything in the top bar needs to be active verbs" theme, I'm wondering about "Build a Project" as well.

Mostly because it's also where you would *manage* projects that are already active -- seems counter-intuitive to click "build a project" to get to the place where you go to manage your active projects.

Could it be renamed as "Project Builder" or something? It seems a little more reasonable to me that you return to the Project Builder to manage the projects you've built.

Thoughts? Other suggestions? Or feel free to tell me I'm being frivolous.

**Comment by chrissnyder** [comment]
I think this one is a bit too in the weeds. Let's look at this again when we tackle general top-level navigation.
