### ISSUE TITLE
Add button to clone workflows within (or across) projects

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#841]
Just needed to do this for whales to make a subtle change for different subject sets. Think it would be really useful for projects in general.

**Comment by ezzjcw** [comment]
I would like to be able to do this too. At the moment I am doing it all manually. I feel greedy asking for it, but do you plan to add a clone/duplicate workflow button to Panoptes?

**Comment by camallen** [comment]
This just needs a button to wire it up as the api already offers it, http://docs.panoptes.apiary.io/#reference/projects/project-create-links/add-a-link

> Workflow and Subjects added in this way will be copied and their id will be returned as part of the complete Project representation response.

**Comment by srallen** [comment]
This is done.
