### ISSUE TITLE
Talk sidebar should display Zooniverse Talk, no unreleased projects, and first option should be null/neutral

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#842]
The Talk sidebar dropdown probably shouldn't display projects that don't appear on the main page yet, right? It's showing Whales, Wildebeest, and Bar Lengths, right now, none of which appear to be formally active.

It should also have a link to the Zooniverse Talk... in fact, that should probably be the top link.

Better yet, it could look something like this:

*Select a Talk to jump to*
Zooniverse Talk
Planet Four: Terrains

where the first option is always automatically displayed, and is a greyed-out, italic null that goes nowhere

Currently, you can't jump to Whale as Individuals, the top option, unless you land on the Talk page with one of the others already displaying (if that makes sense).

**Comment by aweiksnar** [comment]
Not sure I agree on adding zooniverse talk since it's always in the top nav

**Comment by DarrenMcRoy** [comment]
I could take it or leave it, but my argument would be that it's a new feature we are trying to push pretty hard right now. It might be an excellent awareness builder for people who are just starting to use the new system.

Plus, right now we don't have so much to put there. We could put it there now, and pull it out once there are more projects?

**Comment by mschwamb** [comment]
If it helps I kept trying to go to Zoonivese talk through the navigator tab a few times while I was moving around projects. with the navigator bar

**Comment by DarrenMcRoy** [comment]
What happened here? It looks like something got merged, but maybe one branch got pulled?

**Comment by lfortson** [comment]
I would agree that the Zooniverse talk should appear on the navigator side bar even if its already at the top nav. 

But reiterating Darren's earlier comments in this issue - what definitely needs to be fixed:
1. can't go to the Talk for the project that is the default project on the sidebar (currently whales)
2. the sidebar should list all live projects at launch

**Comment by mschwamb** [comment]
There seems to be some confusion re: avatars and live projects (#741) which also matters for this issue. My understanding is 4 projects are launching from the project builder and those 4 projects are indeed showing up in the project builder. So I don't think  there is anything on that list that needs to be removed from that side list. 

I also can't get to the first whale one (top of the list when I click). All other works fine from the the navigator bar.

**Comment by DarrenMcRoy** [comment]
I don't know if GZ Bars, Wildebeest and Whale Tails are going to be live on the main page right at launch. If they aren't--they aren't there on the main page right now--then they shouldn't be in the sidebar (and don't need avatars). Once they are added, they should.

It seems like there's general agreement that the default for the sidebar should be nothing, something like "Select a Talk to jump to," and that it should include the Zooniverse Talk (probably at the top), and that it should include all live projects.

**Comment by mschwamb** [comment]
I believe the teams just made them non-public to make tweaks to the subject sets since there's some extra time before launch. Those 4 projects are showing at the bottom of the new Zoo home. See @chrislintott 's comment in #741 - Before things get removed that shouldn't  @DarrenMcRoy  maybe you should check with @chrislintott, @chrissnyder , and @mrniaboc about what projects are being launched

**Comment by vrooje** [comment]
I finished updating the subjects and help text for GZ Bars on Friday and the project is both public and live. I don't plan on making any more changes except to update the FAQ as needed once the project is receiving classifications and questions on Talk. 

@aliburchard can confirm if the same is true for Wildebeest and Whale Tails.

**Comment by vrooje** [comment]
Also, the inconsistency with where the projects are and aren't displaying is a known bug (#815).

**Comment by DarrenMcRoy** [comment]
Okay, so, I was wrong about those other three projects not being included in launch. All of them should be there.

Right now, I figure the best way for it to look would be alphabetical, so:

*Select a Talk to jump to*
Zooniverse Talk
Galaxy Zoo: Bars
Planet Four: Terrains
Whales as Individuals
Wildebeest Watch

Sound good?

**Comment by DarrenMcRoy** [comment]
It now also should include both Season Spotter projects. And I still strongly feel that, for discoverability purposes, it is still very beneficial to have the Zooniverse Talk in that sidebar. I know that we need to make it customizable, eventually, but for now let's not shortchange certain projects!

@aweiksnar it should be really fast to add the two Season Spotter projects and the Zooniverse Talk to that sidebar?

**Comment by aweiksnar** [comment]
Closed in #1604
