### ISSUE TITLE
Ability to move threads in Talk

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#843]
Currently not an option that I can see.

Merging threads will be an enhancement for later (mods like that), but we should have thread-moving capability sooner rather than later, especially if it's not too tricky?

**Comment by vrooje** [comment]
+1 to this and I wouldn't say it's really an enhancement -- it's more important than that. It's one of the important features and it allows the moderators to actually moderate.

**Comment by chrislintott** [comment]
@chrissnyder I'd say this was an important one.
