### ISSUE TITLE
Question - what's a Featured image on Talk?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#854]
@aweiksnar The P4T moderators were asking. Currently if you click you see images from Snapshot Supernova. What does that feature do? Thanks.

**Comment by aweiksnar** [comment]
It just makes an explicit connection between your comment and the subject. For example, when you start a new discussion from the subject page, it sets your comment as featuring that image and then it shows up in that list of comments below the subject

**Comment by mschwamb** [comment]
okay. thanks. So why are the only image you can choose from images from Snapshot Supernova? How would a moderator or researcher change that?

**Comment by DarrenMcRoy** [comment]
Oh, yeah, we should definitely fix that. In fact, images from Supernova shouldn't be showing up at all.

**Comment by vrooje** [comment]
I'm also getting subjects from Kitteh Zoo as options when I've started a comment directly from the GZ Bars classification interface.

I find this very confusing. First, if I've come to Talk via the button associated with the end of a classification, an image is already "featured" and if I accidentally change it I can't easily change it back unless I know the subject ID (or know to read it from the URL). 

Second, I've just tried three posts with three different featured images, and I have no idea where they went. I can't seem to find them on project Talks or on Zoo Talk.

Third, featured posts in Ouroboros Talk have a very different meaning, so those migrating over may have a hard time with this. I think of "featured" as "special" in some way, i.e. highlighted, whereas this is more "linked" to me. I think it's very easy to get the wrong idea about what adding a "featured image" does and there's no help text to correct it.

**Comment by DarrenMcRoy** [comment]
Featured image suggestions should really only come from the project you're working on. @aweiksnar -- can we set that as a parameter?

**Comment by aweiksnar** [comment]
Yeah right now the subject search just pulls a users recents as the default state. I'll work on improving this

**Comment by vrooje** [comment]
Suggest we also change the naming from "featured image" to "linked image". cc @chrislintott

**Comment by mschwamb** [comment]
Maybe I should open another ticket, but all of my featured images that show up when I click the button are still from stargazing even though I've classified plenty on Planet Four:Terrains so might be a bug

**Comment by DarrenMcRoy** [comment]
I still think "featured image" is fine, but I imagine that making the suggested images work properly is still an item?

**Comment by vrooje** [comment]
This use of "featured" is really different from not only our previous Talk version, but from the usual way that word is used across the web. I feel really strongly about this.

**Comment by aweiksnar** [comment]
Yeah I really like the 'linked image' naming suggestion. Going to update that text once this issue is all sorted

**Comment by DarrenMcRoy** [comment]
Fair enough. I accede. :-)

**Comment by edpaget** [comment]
Is this closed by https://github.com/zooniverse/Panoptes-Front-End/pull/1235?

**Comment by DarrenMcRoy** [comment]
I would say so.
