### ISSUE TITLE
Can't add zookeeper or DZM to a collection - says users don't exist 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#856]
Not sure why but they don't show up in the search.  Says users don't exist. @vrooje does though and was added with no problem. Is this something to do the with the displayname?  Maybe I'm doing something wrong?

**Comment by DarrenMcRoy** [comment]
Is this still the case, @mschwamb ... One thing has changed.

**Comment by mschwamb** [comment]
I'm not sure what's 'changed'...., but yes it's still the case. Both usernames don't show up in the search

**Comment by edpaget** [comment]
Moving to zooniverse/Panoptes/issues/1034
