### ISSUE TITLE
Adding ability to add hashtags to mark a collection

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#858]
I think you should be able to add a hashtag to a collection in case you want to flag for a science team or anyone else. You can do this in the version on Ouroboros  Talk. 

I've asked volunteers in the past to  hashtag their collections that were related to a specific feature/process on Mars or were thought to have planet candidates on Planet Hunters and I was able to ask the development team to pull out the subjects  ids for subjects in those marked collections. 

It would be nice to be able to do the same here. I think this functionality could come in handy

**Comment by mschwamb** [comment]
I wanted to bring this suggestion back up. The Talk button button in collection is still greyed out, but I'm not sure that functionality needs to get added.  I've noticed is that most people don't have conversations about collections with the previous Talks, but they do add hashtags  to get the research team's attention about specific finds. Especially if the collections are going to be linked eventually from the subject pages, then I'd suggest dropped the Talk tab and just add one more field associated with collections for hashtags to be added.

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
