### ISSUE TITLE
Username search broken for adding collaborators to collections and in the project builder 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#859]
Same as  #856 but since I started it with a different name and this is wider I thought best to make a separate ticket. 

Something changed in the search to add users. Now Zookeeper and DZM don't show up. It looks like it's not returning the full list. 

This happens on the project builder if I want to add a collaborator and to the collections. 

Here's what is returned in the search for zookeeper. Everybody else but the actual 
username shows up. 

Same thing for my username, same thing for DZM. Vrooje shows up just fine. 

![screen shot 2015-06-28 at 6 54 29 am](https://cloud.githubusercontent.com/assets/753325/8394281/f32da06e-1d62-11e5-80c3-51493498f92d.png)

![screen shot 2015-06-28 at 6 54 23 am](https://cloud.githubusercontent.com/assets/753325/8394287/0a9b99b8-1d63-11e5-9039-26cf8472575a.png)

![screen shot 2015-06-28 at 6 55 41 am](https://cloud.githubusercontent.com/assets/753325/8394285/fdca7f88-1d62-11e5-907b-cb754696863f.png)

![screen shot 2015-06-28 at 6 58 51 am](https://cloud.githubusercontent.com/assets/753325/8394294/3a6cfeca-1d63-11e5-8133-308944893cd8.png)

![screen shot 2015-06-28 at 6 54 12 am](https://cloud.githubusercontent.com/assets/753325/8394304/5688474a-1d63-11e5-92e3-3d16a48f50b0.png)

**Comment by edpaget** [comment]
Moving to zooniverse/Panoptes/issues/1034
