### ISSUE TITLE
Adding a link to the panoptes github repo to the contact us page to direct people who have questions/issues with the project builder?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#860]
Question for @chrislintott & @mrniaboc - Should the [Contact Us](http://preview.zooniverse.org/panoptes/#/about/contact)  page also have a mention of if you have issues or trouble with the project builder to use github issues? I noticed that the only place it mentions what to do is in the [Project Builder Policies] (http://preview.zooniverse.org/panoptes/#/lab-policies)

**Comment by chrissnyder** [comment]
Don't think this is necessary. People seem to have found it, link or not.

I would love to more holistically think about how we solicit help and contributions from both the community and science teams, but that's a much broader topic.
