### ISSUE TITLE
Mentioning the 10,000 subject limit on the subject uploader in the project builder and in the how to build a project doc

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#861]
Question for @mrniaboc, @vrooje, @aliburchard and @chrislintott 

I was reading the project building policies and saw it says that projects are being limited to 10,000 subjects and that you should contact if you have more that you want to go in. This is the first and only time it's mentioned. I think this should be more prominent. Maybe in the subject uploader help text and in the how to build a project doc?

**Comment by edpaget** [comment]
I think @brian-c  was planning to inform the user of the limits as part of https://github.com/zooniverse/Panoptes-Front-End/issues/316.

**Comment by mschwamb** [comment]
Okay, but I think this should also be in the help documentation. Rather than just something that shows up once you've made your subjects. Like I currently have 20,000 subjects. I'm sure I'll get special permission since I have a reasoning for why we want that many, but I think it would be good if it was explicit in the rest of the help docs/content
