### ISSUE TITLE
when you delete a subject set you remain on its page and it stays in the side list until a browser refresh

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#862]
low priority but something I noticed - I deleted a large subject set and when I did it deleted fine and reported at the bottom of the page  a 0 with a greyed out delete button, but it was still saying all the info of the page before I hit delete, so it wasn't clear it was removed until I refreshed the browser and then the page was gone and not linked on the subset set index. 

Not sure if there's a way to delete a subject set and move to a different page in the project builder by default and a refresh of the page so you can see your subject set was deleted

**Comment by chrissnyder** [comment]
This looks to have been taken care of at some point. Reopen if you disagree @mschwamb

**Comment by mschwamb** [comment]
I deleted the kitteh subject set with no problem. thanks
