### ISSUE TITLE
Getting 'stuck' in Talk after hitting talk instead of next subject  from the interface 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#863]
I noticed you become a bit stuck in project Talk if you hit the talk button from the classification interface after the classification is submitted from the options to Talk or move on to the next subject. Since Talk opens up in the same browser,  I think it would be helpful if there was a 'Return to Classifying' button somewhere in Talk to make explicit how to get back. This feature existed in both version 1.0 and 2.0 of Talk 

Another option might be to also make the browser open up a new tab with Talk so you can make your comment and x out to go back to classifying tab.

**Comment by DarrenMcRoy** [comment]
Oof, I strongly agree. "Return to Classifying" has been a critical feature in the past, one I've made great use of. Can we work that back in, @aweiksnar and @parrish (since @parrish built it first two times)?

**Comment by aweiksnar** [comment]
You can click on the classify tab to return to classifying. Adding another button here would be functionally the same as that button and also live in the same location on the page

**Comment by DarrenMcRoy** [comment]
That's a good point, @aweiksnar . Let's see if people generally realize that, and can work with it.

If not, we may have to have a duplicate button somewhere.

**Comment by edpaget** [comment]
@mschwamb @mkosmala what doesn't work about the 'Classify' tab at the top near the 'Talk' tab?

**Comment by DarrenMcRoy** [comment]
At least from my perspective: it's not where people expect it to be based on past Zoo experience (which isn't necessarily a reason to change; just saying), and it's not quite as clear as "return to classifying" is at conveying that it drops you right back to where you were beforehand.

**Comment by mkosmala** [comment]
@edpaget What @DarrenMcRoy said. In my (personal) experience -- and from what users on Talk have said -- people are clicking the "back" button in their browsers to go back to classifying. 

It would be nice to have an all-in-one "submit this comment and return to classifying" button. But not sure if that's doable.

**Comment by mschwamb** [comment]
what about doing what was  in Planet Hunters 1.0 have Talk open in a separate tab?

**Comment by edpaget** [comment]
I don't think any of that's necessary though. You can move back and forth between the Classify and Talk tabs within a project either by clicking on them or using the Back/Forward buttons on a project without losing any state on either section. 

I do agree it'd be nice to be able to make comments from within the classification task ala War Diaries or PlanetHunters 2.0. Otherwise I think we can just wait and people will become used to the Tabbed interface.

**Comment by vrooje** [comment]
I suspect many people will never realize they can click Classify to go "back", unless it is explicitly pointed out to them.

**Comment by DarrenMcRoy** [comment]
I really feel more with Brooke on this one. I know that the tab is there, but it just doesn't feel that obvious from a flow perspective. In this case, they aren't clicking a tab to *go* to Talk, so it's unclear that they should click a tab to leave it.

I know we abhor duplicate-function buttons, but if it saves people pain... ?

**Comment by edpaget** [comment]
I really think this is just because we are used to a particular way of doing things. Let's revisit in a month and see if it still feels weird or if people are still having trouble.

**Comment by vrooje** [comment]
I could see an in-between solution like:

if subject notes thread is loaded from classification-then-subject-page, display banner across top of thread for 15 seconds that says 'Thanks for your comment! This is our discussion area, Talk. To return to classification, you can click the "Classify" tab at any time.'

**Comment by chrissnyder** [comment]
Agree with @edpaget. Punting this until a lot of design work has been done on Talk, which may impact how we approach this.
