### ISSUE TITLE
hashtags don't seem to work/link properly in notes Talk board

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#864]
I added a hashtag in a notes board discussion and it's not showing up on the side navigation bar and when I click it, it says there is no items matched in the search. 

http://preview.zooniverse.org/panoptes/#/projects/mschwamb/planet-four-terrains/talk/29/150?page=1&comment=246

**Comment by mschwamb** [comment]
so slightly more complicated - #channelnetwork has an issue but something shorter like #zigzag or #spld works fine from notes

**Comment by aweiksnar** [comment]
@mschwamb The #channelnetwork tag looks to be working ok for me. Resolved?

**Comment by mschwamb** [comment]
It didn't work as of last week, when I tried it last, but it is working today. Thanks
