### ISSUE TITLE
Appearing as "researcher" on projects I'm not a "researcher" on

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#866]
I am a collaborator on whale tails but not listed as a researcher. When I post to the Whales talk forum, the tag "researcher" appears below my name. This seems misleading, as I know absolutely nothing about whales and am not a researcher on that project. 

I am not sure if I appear as researcher because I am a researcher on other projects or because there is a bug in the labels. Either way, I think this should be addressed.

![screen shot 2015-06-29 at 10 11 30](https://cloud.githubusercontent.com/assets/6217406/8404763/8a170b16-1e47-11e5-8eaa-fef895b679ff.png)

**Comment by camallen** [comment]
related to https://github.com/zooniverse/Panoptes-Front-End/issues/817#issuecomment-115745283

**Comment by chrissnyder** [comment]
Closing in favor of #817
