### ISSUE TITLE
Talk: "Add your Comment" button needs highlighting

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#867]
On Talk, I keep missing the "Add your Comment" button and scrolling down to look for the usual blindingly obvious button (e.g., "Submit new issue" here). 

Suggest better highlighting of this button to draw the mouse.

Also suggest lowercase "c" on "comment".

**Comment by DarrenMcRoy** [comment]
I agree with this. That's an important button, and should stand out, the same way that the Comment button here on GitHub is highlighted green.
