### ISSUE TITLE
Search not finding subjects that are named in existing talk board

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#868]
I made a comment about a subject on whales. The subject ID shows up on the talk board. But if I search for that subject ID, nothing shows up.
![screen shot 2015-06-29 at 10 27 04](https://cloud.githubusercontent.com/assets/6217406/8405025/8ae063d8-1e49-11e5-988f-f7726d7cde7d.png)
![screen shot 2015-06-29 at 10 26 35](https://cloud.githubusercontent.com/assets/6217406/8405028/8ff5cef8-1e49-11e5-85ab-451baedbb6b2.png)

**Comment by chrissnyder** [comment]
Not sure what the intended behavior is for subject ID searching. @parrish ?

**Comment by parrish** [comment]
As intended, subjects aren't indexed.  The only attribute you could even search for is by id, which basically isn't a search.  On the other hand, I could also pack the subject id into the content field indexed by comments -- comments about the subject would show up for queries of the subject id

**Comment by parrish** [comment]
Yep.  I'll go ahead and do that:
![screen shot 2015-06-30 at 12 27 52 pm](https://cloud.githubusercontent.com/assets/122990/8437245/7d00ce4e-1f23-11e5-9242-ce6a56422113.png)
