### ISSUE TITLE
Allow metadata file in subject set uploader

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#869]
When creating a new subject set in the front end, it'd be really useful to be able to add an optional `metadata.json` file and have the contents added to the set's metadata property.

**Comment by twhyntie** [comment]
@rogerhutchings If I've understood correctly this is already possible using the `manifest.csv` file used when uploading the subject set. I'm not sure if the docs are up-to-date yet, but the `csv` file can look like:

```
id,latitute,longitude,filename
01,51.234322,0.367279,my_subject.png
```

and `id`, `latitude` and `longitude` will be added to the subject's metadata, viewable when you press the metadata button on the subject's page (there's a separate issue/discussion in [#285](https://github.com/zooniverse/Panoptes-Front-End/issues/285) about that though...).

Is that what you meant? Cheers, Tom

**Comment by rogerhutchings** [comment]
Not quite @twhyntie - I'm talking about `subject_set` level metadata as well, not `subject`
