### ISSUE TITLE
Problem linking subjects

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#87]
Not sure if this should be here in in zooniverse/Panoptes issues, but since Panoptes has been rebooted, I get an error when creating a project:

Here is an example of the outputs:
    Saving project
    Saved project
    Saving subject set
    Saved subject set
    Saving workflow
    Saved workflow
    Saving subject coweeta_2013_10_01_120134.jpg
    Saving subject coweeta_2013_10_31_120136.jpg
    Saving subject coweeta_2013_11_09_120134.jpg
    Saving subject coweeta_2013_11_30_120134.jpg
    Saved subject coweeta_2013_10_01_120134.jpg
    Uploading coweeta_2013_10_01_120134.jpg
    Saved subject coweeta_2013_10_31_120136.jpg
    Uploading coweeta_2013_10_31_120136.jpg
    Saved subject coweeta_2013_11_09_120134.jpg
    Uploading coweeta_2013_11_09_120134.jpg
    Saved subject coweeta_2013_11_30_120134.jpg
    Uploading coweeta_2013_11_30_120134.jpg
    Linking 4 subjects to subject set
    Uploaded coweeta_2013_10_01_120134.jpg
    <b>Error: Failed to link 4 subjects!</b>
    Uploaded coweeta_2013_10_31_120136.jpg
    Uploaded coweeta_2013_11_30_120134.jpg
    Uploaded coweeta_2013_11_09_120134.jpg

**Comment by chrissnyder** [comment]
Referenced issue is closed, so I'm going to assume this is taken care of.
