### ISSUE TITLE
Remove "create discussion" from Notes board

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#872]
It should not be possible to create a new discussion in the Notes board, because said board should be reserved entirely for subject threads. Having anything else able to go there would be confusing and counterproductive.

**Comment by aweiksnar** [comment]
Is there consensus that this is desired? Thoughts on instead of removing the new discussion form completely, replacing it with a note like "This board is reserved for subject discussions. New discussions can be added from the individual Subject page"

**Comment by DarrenMcRoy** [comment]
There is absolutely no reason to have a way to create a discussion on the Notes board. That board is a repository for subject threads, nothing more.

However, I do like the idea of replacing it with some text so that people don't wonder why they can't post there. How about:

*This board is reserved for automatically generated subject discussions. You can start a new discussion in a different board, or from an individual subject page.*

**Comment by aweiksnar** [comment]
That'd work for me. My reason for commenting here is that although that board has distinct purpose, it is currently presented to users in the same fashion as the others, so they will be expecting consistency

**Comment by DarrenMcRoy** [comment]
:+1:

**Comment by mschwamb** [comment]
I'm agnostic. No is posting prolifically in there who's making a separate post outside of the subject page, so I think intuitively people have gotten that the other boards are for more detailed targeted discussions. If someone wanted to post their discussion in there, I'd say it's up to the mods to move it.

**Comment by mschwamb** [comment]
Either way   have strong opinions on  the suggested text from @DarrenMcRoy . I think it makes sense to someone who really knows Talk, but makes completely no sense to a new/most volunteers. What's an 'automatically generated' post? I'm not sure that's clear to someone or tells them  how to get their post in this thread (ie making a comment on the subject page). 

I think the current 'General comment threads about individual subjects' is a much clearer description for the board and once you're posted a few times you see where you thread has gone. So maybe I do lean a bit towards leaving it as is.

**Comment by mschwamb** [comment]
Apologies,  I totally missed the part about the subject pages in @DarrenMcRoy's comment the first read (sorry) , but I still don't like the 'automatically generated' bit. Anyway, I'm not sure this is needed, but won't comment more on it.
