### ISSUE TITLE
Most recent post link doesn't go to the most recent post

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#873]
The front page of Talk, when showing recent threads, displays not the name of the most recent person to post, but instead the name of the person who started the thread.

![screen shot 2015-06-29 at 1 09 01 pm](https://cloud.githubusercontent.com/assets/8987864/8414840/3734a20a-1e60-11e5-842a-30b8f0077065.png)

when you can see that Chris' post was actually from a long time back, and the most recent posts were mine and Janet's

![screen shot 2015-06-29 at 1 10 37 pm](https://cloud.githubusercontent.com/assets/8987864/8414860/4dcf75da-1e60-11e5-9dbb-e6b1bff9a1cc.png)

**Comment by DarrenMcRoy** [comment]
This is actually really high-priority, along with #874.

It's impossible to see anything actually really *happening* on the boards right now. :-)

**Comment by aweiksnar** [comment]
Working on this now

**Comment by mschwamb** [comment]
If when you click it can go straight to the updated post as well that would be a huge help

**Comment by DarrenMcRoy** [comment]
Reopening because the link currently goes to the top of a discussion, not to the most recent post.

**Comment by DarrenMcRoy** [comment]
Additionally, the most recent post isn't always displaying properly.

For instance, as I write, the Troubleshooting board displays yshish as having left the most recent post about 30 minutes ago:

![screen shot 2015-07-01 at 10 58 19 am](https://cloud.githubusercontent.com/assets/8987864/8459122/ab9396d4-1fe0-11e5-829a-f22dd6f8486c.png)

when it was actually me:

![screen shot 2015-07-01 at 11 00 39 am](https://cloud.githubusercontent.com/assets/8987864/8459126/b0d61fb8-1fe0-11e5-89ec-218220e5a8b4.png)

**Comment by DarrenMcRoy** [comment]
@aweiksnar I know you thought https://github.com/zooniverse/Panoptes-Front-End/pull/927 would close this, but it doesn't. Right now, it's displaying the username of someone who posted yesterday, four comments back.

![screen shot 2015-07-02 at 12 06 41 pm](https://cloud.githubusercontent.com/assets/8987864/8482977/ed121fea-20b2-11e5-96c4-29995c46915d.png)

![screen shot 2015-07-02 at 12 06 54 pm](https://cloud.githubusercontent.com/assets/8987864/8482980/f0613e56-20b2-11e5-90ed-27441cb0b7c9.png)

The caching is still buggy, I guess?

**Comment by aweiksnar** [comment]
@DarrenMcRoy I closed PR #927, meaning that it has not been merged yet, but this is still on my radar and I will re-open that PR when it's ready

**Comment by DarrenMcRoy** [comment]
Unfortunately, I have to reopen this. It's still not accurately representing the username of the person who posted the most recent comment.

For instance, I just posted a comment in the Zooniverse Talk Feedback thread, but the top-level item for the board still cites Els:

![screen shot 2015-07-09 at 7 23 27 am](https://cloud.githubusercontent.com/assets/8987864/8594933/8ba1d116-260b-11e5-94f5-886d6d9bb5ed.png)

![screen shot 2015-07-09 at 7 24 38 am](https://cloud.githubusercontent.com/assets/8987864/8594942/97cfa940-260b-11e5-921b-76aa6e8d19c1.png)

Or on the Troubleshooting board:

![screen shot 2015-07-09 at 7 26 23 am](https://cloud.githubusercontent.com/assets/8987864/8594967/df831952-260b-11e5-939d-5e99774d8cd6.png)

![screen shot 2015-07-09 at 7 27 05 am](https://cloud.githubusercontent.com/assets/8987864/8594971/eec4d95a-260b-11e5-9b74-79e1ad7d052b.png)

Still something buggy there. The times and links are correct, but the usernames still aren't.

**Comment by mschwamb** [comment]
Also I updated a thread on Zooniverse Talk and it's not  showing as the most recent thread on the front page, still staying that a stickied thread is the most recent updated thread.

**Comment by mschwamb** [comment]
I should mention it wasn't an edit, it was a new post I added, and still stays that 'Zooniverse Talk feedback' is the most recently updated thread

**Comment by DarrenMcRoy** [comment]
I'm closing #929 as a general duplicate of this, but it's worth referring back to for more examples of this behavior.

It's really, really important that the "most recent post" feature work properly.

**Comment by DarrenMcRoy** [comment]
After the last PR, clicking the most-recent-post link now always goes to the bottom of the first page, not to the most recent post (which might be on, say, the 13th page.) Still needs patching... @aweiksnar

**Comment by DarrenMcRoy** [comment]
In addition, although info on the front page seems now to be correctly updating name each most-recent poster, the info in the list of discussions is not:

![screen shot 2015-07-20 at 4 12 23 pm](https://cloud.githubusercontent.com/assets/8987864/8787518/4279f4da-2efa-11e5-9802-de678939b901.png)
![screen shot 2015-07-20 at 4 12 33 pm](https://cloud.githubusercontent.com/assets/8987864/8787522/45779930-2efa-11e5-8b5d-0d6b6534bcdf.png)

Still naming the wrong most-recent poster.

**Comment by mschwamb** [comment]
@aweiksnar I think if you can get to the linking to last post on the last page working again when you click the name of the thread first that would be a huge help - thanks

**Comment by chrissnyder** [comment]
Is this a function of how fast the most recent post is being checked after making a new post? Or is your example still broke after some time has past?

Is the discussions list the only place left that this behavior exists? So for example, the following URLs are not necessarily up to date? Are there any other places?

https://www.zooniverse.org/#/talk/13
https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/10

**Comment by DarrenMcRoy** [comment]
Okay, it looks like the most-recent poster thing is fixed, or fixed itself. It's displaying properly now.

The only problem now is that they always redirect to the bottom of the first page of comments, not the bottom of the last page of comments (where the most recent post would be).

**Comment by aweiksnar** [comment]
I just did some debugging and believe the first page issue may have to do with api sorting differences in dev/prod. I'm going to put an issue up on the api repo and see what @parrish thinks

**Comment by mschwamb** [comment]
I noticed the temp work around is if you click on the time stamp  the '8 hours ago' bit it does take you to the last thread - not sure if this helps but I thought I'd mention it

**Comment by DarrenMcRoy** [comment]
Are you sure, @mschwamb ? This doesn't work for me. Clicking on the '10 hours ago" takes me to the bottom of the first page, still.

There's a PR in to fix this, I think.

**Comment by aweiksnar** [comment]
Yeah, PR #1167 will point those links to the correct pages

**Comment by mschwamb** [comment]
Apparently I was imagining things! sorry

**Comment by yshish** [comment]
It was actually working for a while yesterday but then something has been
changed and since that it take us to the bottom of the 1st page.

2015-07-22 3:53 GMT+02:00 Meg Schwamb <notifications@github.com>:

**Comment by aweiksnar** [comment]
closed via #1167 
:( Sorry this issue took so long to get sorted!

**Comment by mschwamb** [comment]
All working for me. Sometimes what looks trivial can be super complicated to fix. Thanks for the persistence in tracking the bug down.
