### ISSUE TITLE
Zooniverse logo not showing anywhere on the top bar, but the location is still a link to Zooniverse.org 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#875]
weird bug - I don't see the Zooniverse logo on the top in Mac Firefox, but if I click all the way on the left where it used to be it takes me zooniverse.org  - I'm clicking exactly where the icon was on the preview site

![screen shot 2015-06-30 at 2 40 34 am](https://cloud.githubusercontent.com/assets/753325/8415491/ac8e14f2-1ed1-11e5-83c4-5ad61cc43d4b.png)

**Comment by aliburchard** [comment]
fwiw, this doesn't seem to happen in chrome on mac osx.

**Comment by brian-c** [comment]
Have you tried disabling any extensions?

**Comment by mschwamb** [comment]
I don't have any extensions running in firefox

**Comment by mschwamb** [comment]
Just checked the preview site again and I can see the logo there.

**Comment by edpaget** [comment]
It may just be a caching issue with CloudFront. The distribution server nearest to you may not be up-to-date yet.

**Comment by mschwamb** [comment]
Okay cool. I'll close the issue. Probably the case since I love on the other side of the world.

**Comment by brian-c** [comment]
Eh, it's kinda weird because that's an inline SVG, not an `<image...`. Something to keep an eye on at least.

**Comment by mschwamb** [comment]
It just appeared for me.. I guess just slow for the image to migrate to Taiwan?

**Comment by edpaget** [comment]
The tubez are too full.
