### ISSUE TITLE
Only see Zooniverse-wide public collections if I'm not logged in

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#879]
When not logged in I can find all public collection (currently only the one I made):
![screen shot 2015-06-30 at 3 23 53 am](https://cloud.githubusercontent.com/assets/753325/8416327/90449c20-1ed7-11e5-9030-91bbab6ead4d.png)

When I log in, it's default to my collections and no way to see other public collections

![screen shot 2015-06-30 at 3 24 32 am](https://cloud.githubusercontent.com/assets/753325/8416344/ab222fd0-1ed7-11e5-9e4e-64aed7261eab.png)

**Comment by mschwamb** [comment]
If it helps - 

So slightly different behavior now that there are more collections - you see the collections but with yours too (including ones that appear private I think). 
Not signed in
![screen shot 2015-06-30 at 11 07 13 am](https://cloud.githubusercontent.com/assets/753325/8423210/65be77c8-1f18-11e5-87b8-0495625a91c5.png)

signed in

![screen shot 2015-06-30 at 11 09 27 am](https://cloud.githubusercontent.com/assets/753325/8423219/99a6815c-1f18-11e5-8d1b-bc048b1807fe.png)

![screen shot 2015-06-30 at 11 07 35 am](https://cloud.githubusercontent.com/assets/753325/8423222/a525d9e2-1f18-11e5-858c-f6917b88a111.png)

**Comment by chrissnyder** [comment]
I think I misunderstood this issue when I read it two weeks ago. Is the concern that that top level collections page at https://www.zooniverse.org/#/collections is different depending upon if you are logged in or not?

If so, I'm not sure I'm convinced this is an issue. As it stands, it could be thought of as a "Viewable Collections" page, which naturally includes your own collections if logged in.

It could be a "Public Collections" page, where everything is explicitly public, but I don't have a feel if that would be more or less intuitive than the above.

Doesn't help we named the page "All Collections" which isn't strictly accurate in either scenario.

**Comment by mschwamb** [comment]
This might help - firstly if you hit collections it shows my private collections combined with all the zooniverse collections Zooniverse wide - so it shows 55 collections if I'm logged in and hit collections and if I'm not logged in 53 - I think that's confusing to any user  will wonder why would their private collections show with all the Zooniverse wide ones

**Comment by mschwamb** [comment]
Maybe this behavior is happening when switch between the too states. I clicked on my collections and then back to collections and it now says there are 64 collections when it previously said there were 55. So there's something buggy with what it's displaying

**Comment by edpaget** [comment]
@chrissnyder it doesn't looks like like the the the collection is count is updating when it's reloaded on user login.

I also don't think it's an issue to have your collections in the main page when you're logged in.

**Comment by mschwamb** [comment]
What I find confusing is you list the favorites there, but you don't actually show those in the collections. So I was confusing thinking everyone can see them, but it looks like they can't because when I log out I can't see it. That's I guess what I'm suggesting by taken out or made clearer.

**Comment by edpaget** [comment]
I definitely think we should leave all the collections a user is allowed to see on that page (because they'll also see private collections they are a collaborator or viewer for), but we could mark them as private.

**Comment by mschwamb** [comment]
But I find it weird that my private collections all show on the same page with everyone else's public collection, but that's only for me. I saw that originally and was like wait did I make that public and then had to check. A tag/label for public private would help there. 

Weird thing is favorites are public, but don't show zooniverse wide I believe.  So not sure if that's a third category or not.

**Comment by edpaget** [comment]
Nah favorites are being created as private by default.

**Comment by mschwamb** [comment]
My favorites all say their public when I look at the settings (not sure if that's because they were created earlier when some projects were in beta) , but pretty sure they're not showing (but the pagination is broke on the collection pages).

**Comment by eatyourgreens** [comment]
@mschwamb I've got an open issue about the pagination: #1006

**Comment by edpaget** [comment]
@mschwamb it looks like I messed up, and collections weren't correctly reporting their privacy status on the settings page. That's going to be fixed by https://github.com/zooniverse/Panoptes/pull/1123
