### ISSUE TITLE
Projects not listed

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#88]
I've created a new project ("Project 2015-01-30") and it says "saved" at the end of the project creation workflow. But then the project does not show up in my list of projects. 

Possibly related, I can't see *any* projects when I click the "Projects" banner at the top of screen. 

These things have only been true since Panoptes rebooted.

**Comment by edpaget** [comment]
It think both this and #87 will be resolved by https://github.com/zooniverse/Panoptes/pull/467

**Comment by camallen** [comment]
@mkosmala - yep this is fixed in https://github.com/zooniverse/Panoptes/pull/467. The private field wasn't being set and the finder scopes looked for a value on these.

**Comment by edpaget** [comment]
The patch to fix this is deploying now.

**Comment by brian-c** [comment]
See #111
