### ISSUE TITLE
a bit confusing when renaming a collection

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#881]
minor but you have to click somewhere off the page to get the autosaver to engage when renaming/edit the name of a collection. That was a bit confusing to me. Maybe there should be a save button instead of the autosaver

**Comment by chrissnyder** [comment]
It does autosave if you don't change your input after a couple seconds. Could be messaged better certainly.

**Comment by chrissnyder** [comment]
Not certain where to place this, as it's general feedback on the AutoSave component.

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
