### ISSUE TITLE
Hide the Talk link in collections until that's functional

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#885]
There's a Talk greyed out link showing when you click on a collection. I presume it's for Talk integration. One of the P4T moderators mentioned it was a bit confusing, since it didn't work. Maybe remove the Talk link/mention until that's implemented? 

![screen shot 2015-06-30 at 5 25 14 am](https://cloud.githubusercontent.com/assets/753325/8418891/7baf9de4-1ee8-11e5-9d34-d685ba849bf7.png)

**Comment by edpaget** [comment]
I fail to see how it's confusing considering it doesn't do anything. It'll be active when that feature is ready.
