### ISSUE TITLE
Add a jump to last page icon on Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#887]
You have to click on the menu and select the page, it would be really nice if you could quickly jump to the end of the conversation or maybe something like is currently on Talk 2.0 - right now it's a few clicks to jump to the last page of a discussion

![screen shot 2015-06-30 at 5 34 28 am](https://cloud.githubusercontent.com/assets/753325/8419092/dbb703fc-1ee9-11e5-9c83-22c4840bab3e.png)

**Comment by vrooje** [comment]
+1

**Comment by DarrenMcRoy** [comment]
Also related to #873 and #874. It's important to be able to leap quickly to the end of a thread!

**Comment by aliburchard** [comment]
+1
