### ISSUE TITLE
Having the talk sidebar show up everywhere in Talk 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#892]
low in the queue, but this might be a simple adjustment so I'm suggesting it now - For helping promote hashtags, I was wondering if the side bar you see on the front Talk page could be everywhere  in Talk so that when you're in a discussion you can see the most popular hashtags like you can on Talk 2.0. Also would help with fast transitions between project Talks

![screen shot 2015-06-30 at 11 30 01 am](https://cloud.githubusercontent.com/assets/753325/8423415/69486108-1f1b-11e5-9ee0-a53483c2067d.png)

compared to

![screen shot 2015-06-30 at 11 36 37 am](https://cloud.githubusercontent.com/assets/753325/8423482/5450762c-1f1c-11e5-8754-bd02366a865e.png)

**Comment by aliburchard** [comment]
I really like this suggestion. I think what's been bugging me in the new talk is feeling a bit isolated or trapped inside of a thread or comment.

**Comment by vrooje** [comment]
Agreed.
