### ISSUE TITLE
UI weirdnesses on user Customize Profile page

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#894]
- For the avatar / background, there are no instructions on what to do other than 'Drop an image here', and the text gets hidden once an image is in there;
- There's no information on what images are okay or not (I was thinking sizes, more than content);
- There's no button to clear an existing avatar / background;
- If you upload an image, then click on the image area, then click cancel, you get an infinite loading animation (someone should try to duplicate this though)

**Comment by brian-c** [comment]
A clear button can be added when zooniverse/Panoptes#1060 is resolved.

**Comment by yshish** [comment]
- If you upload an image, then click on the image area, then click
   cancel, you get an infinite loading animation (someone should try to
   duplicate this though)

I had the the infinite loading animation while trying to replace the
current image with a new one.

2015-06-30 10:51 GMT+02:00 Roger Hutchings <notifications@github.com>:

**Comment by chrissnyder** [comment]
Most of the original concerns were addressed, closing this is favor of a more atomic issue.
