### ISSUE TITLE
Home page assets not loading over HTTPS

### ISSUE THREAD

**Issue by astopy** [zooniverse/Panoptes-Front-End#895]
![screen shot 2015-06-30 at 11 35 24](https://cloud.githubusercontent.com/assets/428423/8429100/59ad050e-1f1c-11e5-991c-19a156f849b7.png)

**Comment by edpaget** [comment]
Is this due to the [nginx proxy](https://github.com/zooniverse/static/blob/master/nginx-proxy.conf#L9)?

**Comment by astopy** [comment]
Ah, well spotted. This is probably due to line 7 in that file.
