### ISSUE TITLE
Ellipse drawing tool enhancement

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#904]
The ellipse drawing tool would work better for some projects if its axes had to be horizontal and vertical. This would mean less fiddling to get the ellipse right. As one beta-tester of ours noted, it shouldn't take 3 motions to circle a tree. (One to place, one to size, one to rotate.) For Season Spotter, an ellipse that was forced to be a horizontal or vertical one would be better. This could be accomplished by having a check-box in the project builder to force such a horizontal-vertical ellipse tool.

**Comment by vrooje** [comment]
Can we have something analogous, but the other way, for the rectangle tool? A free-angle rectangle tool would be really useful in humanitarian projects where buildings are mostly boxy but streets aren't always aligned with the image.
