### ISSUE TITLE
Can't add collaborator that is known to exist

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#907]
I have two Zooniverse accounts. One is 'kosmala', which I created long ago on the original Zooniverse site and migrated to the new platform today. The other is 'mkosmala', which I created within this past year, while working on Panoptes; I migrated that one to the new platform today, also. 

When I create a project under the username 'mkosmala', I cannot find 'kosmala' to add as a collaborator. That name just doesn't show up, even if I type it in its entirety. I CAN do the reverse: if I am logged in as 'kosmala', I can add 'mkosmala' as a collaborator.

**Comment by mschwamb** [comment]
Giving a heads up, that I reported this for collections a few days ago - @edpaget moved it to panoptes - The ticket is [here](https://github.com/zooniverse/Panoptes/issues/1034)

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes/pull/1075?
