### ISSUE TITLE
Project Tabs

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#91]
On the current front-end design, the project tabs at the top of the screen are:
* Science
* Status
* Team
* Classify
* Talk

Are we going to be able to define our own tabs? We would like to also have:
* Blog
* Education
* Authors (or perhaps this can go on the Science tab. But basically, we want a place to announce results, publications, and volunteers who have helped -- which is different from the "science case" information, and perhaps needs its own tab.)

**Comment by brian-c** [comment]
@chrislintott @aliburchard Thoughts on this?

**Comment by aliburchard** [comment]
I think it would be good to have the tabs Margaret suggests. Blogging is one of the things that we (the zooniverse) make a big deal about as important to the success of the project -- so it feels a bit silly to not have a way to support that. I realise that we won't be managing the blogs on panoptes projects, but perhaps there is a way to still make it feel integrated into the project?

Same with Authors. Given that we ask science teams to credit classifiers, we should give them a way to do that.

**Comment by brian-c** [comment]
Opened issues on the back end for blog and education pages.

Maybe instead of a "Team" page, the roles are listed on the main Talk page for the project (since that's where they're most important) and we replace the Team page with "Results", which would be a place to link to papers and list their authors.

**Comment by mkosmala** [comment]
I think "Team" needs to still be on the main non-Talk part of the site, as only a fraction of users use Talk. What about combining "Team" with "Science", as is already done for Snapshot Serengeti, where it's simply called "About". In other words, "this is the science, and here's who we are" make sense to put together. And then, yes, replace "Team" with "Results".

**Comment by brian-c** [comment]
Split these into
* #112
* #113
* #114
* #115
