### ISSUE TITLE
Talk "Firehose" viewing

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#911]
The board-organized default view of Talk is very useful, but one of the most-used features on both old Talks is the ability to see the fire hose: all recent posts (with snippets of their content / thumbnails of linked images if possible) in reverse chronological order.

This is one of the most important views of Talk; it gives it a sense of activity (if there is any at all) and also makes it easier for regular users to keep up meaningful conversations, and for moderators to keep an eye on things.

I'd love to see this streaming by in a box on the main Talk (project or Zoo) page, with a link to click to a full page with more posts/details. In the short term I'd be happy with a link to a separate page that I can reload as needed.

Tagging @chrislintott @aliburchard @mrniaboc @DarrenMcRoy as well.

**Comment by DarrenMcRoy** [comment]
Duplicate of #726 -- no?

**Comment by vrooje** [comment]
Ah! Yes, I searched for the wrong thing. I'll close this and we should post on that instead. Still think this is a high priority.
