### ISSUE TITLE
Talk subject page should list what collections a subject is in and what hashtags have been used to refer to it

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#914]
The ability to see the collections and hashtags plus the conversations associated with a subject was something I use frequently on Talk 2.0 and in Talk 1.0 I found this immensely useful on Talk 2.0 and used this frequently especially for a project I had a summer student do last year. I could see what the collection name was and then navigate to the collection

Right now at  https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/subjects/483893
it only shows the discussions 

having something like this from version 2.0 I think is one of the things that makes Talk incredibly power but  is currently missing in the panoptes version

![screen shot 2015-07-01 at 5 53 39 am](https://cloud.githubusercontent.com/assets/753325/8443056/d9b27768-1fb5-11e5-923b-75555703133a.png)

**Comment by DarrenMcRoy** [comment]
Closing as consolidated into #1271.
