### ISSUE TITLE
hover text wrong

### ISSUE THREAD

**Issue by michaelaye** [zooniverse/Panoptes-Front-End#915]
Just noticed on the Old Weather project that the hover text for the MilkyWay Project says "MoonZoo":

![screenshot 2015-06-30 16 13 03](https://cloud.githubusercontent.com/assets/69774/8443373/5bc55496-1f43-11e5-8a76-bd117569bc1a.png)

**Comment by chrissnyder** [comment]
Old Weather is being rebuilt, so it's unlikely we'll ever get around to fixing this.
