### ISSUE TITLE
Adding a link to the subject pages from the notes discussions

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#916]
The discussion page is keeping an index of all discussions started from clicking talk in the interface. Currently in the notes threads you only see that conversation, so there's no way to know there are other discussions. It would be helpful if there's a way to get back to the subjects page - perhaps making the title of the subject into a link

The only way currently to see the subjects page is to manually type it
Being able to access the subject page from a link from a discussion  would allow science teams to quickly see all the discussions going on about a subject

![screen shot 2015-07-01 at 10 45 56 am](https://cloud.githubusercontent.com/assets/753325/8446523/7767b158-1fde-11e5-9f06-4ee11a8284e5.png)

**Comment by aweiksnar** [comment]
For some reason github doesn't include this issue when filtering by sprint names, so I missed it in the first one. Going to move to PFE Sprint 2

**Comment by DarrenMcRoy** [comment]
This should also happen any time you place a featured image. Pretty much any time an image is mentioned, really.
