### ISSUE TITLE
Can't remove user roles from project visibility

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#920]
Unchecking a user role doesn't remove the actual role from the backend (reload page it's still there). Looks like no request if firing on the uncheck event. Related to autosave?

**Comment by chrissnyder** [comment]
Can't reproduce this. Looks to be correctly adding/removing roles here, doing PUTs to Panoptes and POST/DELETEs to Talk.

**Comment by camallen** [comment]
I can add fine, removing doesn't fire the PUT to panoptes. Try adding a role refresh page then removing it and to verify via page refresh. My new roles are still there even after clearing the check box.

Also got a 401 POSTing to talk when creating a new role.
