### ISSUE TITLE
Quoting a reply doesn't clear when you've submitted the comment

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#922]
Have just written a reply to another post, and once the comment was posted the new-post box still had the previous comment loaded in as a quote:

![screen shot 2015-07-01 at 14 38 23](https://cloud.githubusercontent.com/assets/2357126/8455796/1d7e56e4-1fff-11e5-9a0b-19380e0f7778.jpg)

This should clear after the post is successfully submitted.

**Comment by DarrenMcRoy** [comment]
Also irksome to me, and should be fixed, although I eventually hope for more reply functionality in general (see #888)

**Comment by vrooje** [comment]
Update to this: even if I don't submit the comment this doesn't clear, and if I click "Remove reply" and then go to another page of the same discussion, the same quoted post shows up again in the comment box.

**Comment by aweiksnar** [comment]
closed in #1428
