### ISSUE TITLE
Display basic project stats in the project builder

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#924]
It would be great to be able to see even just very basic stats somewhere in the project builder: number of unique users/sessions, number of classifications, etc.

I think this should be a separate page we could add functionality to eventually, but for now it could just be a couple of numbers in the data export section of the Project Details, before the "Request new classification export" button.

**Comment by mschwamb** [comment]
FWIW, I love the status page that exists per project for Ouroboros and check it every day to see how much data is left, whether a newsletter should be sent out, etc. Having something like that in the future would be really useful

**Comment by chrissnyder** [comment]
Added on the main page in https://github.com/zooniverse/Panoptes-Front-End/commit/8e593e1ac4a12a2471eb0d7a2b76897e95b42e62, closing.

That said, we'll definitely be adding more in-depth stats closer to what the Ouroboros status pages offered.
