### ISSUE TITLE
Some project avatars missing on Publications page

### ISSUE THREAD

**Issue by willettk** [zooniverse/Panoptes-Front-End#925]
Missing the avatars for many of the projects, including:

- GZ: Supernova
- Ice Hunters
- Andromeda Project
- SpaceWarps
- Snapshot Supernova
- WhaleFM

GZ: Supernova and Ice Hunters don't have bespoke logos, but the rest should be in https://github.com/zooniverse/Brand

**Comment by DarrenMcRoy** [comment]
Assuming these are pulling from the "avatar" field, I can add these.

**Comment by srallen** [comment]
Yes, they are fetching the project avatars.

**Comment by DarrenMcRoy** [comment]
I added the four that we have, but we still need something for GZ: Supernova and Ice Hunters.

@heathv , without needing to make entirely new avatars for finished projects, are there any images we could use for GZ: Supernova and Ice Hunters?

**Comment by willettk** [comment]
We used to just use the generic Zooniverse logo (white on blue).

**Comment by DarrenMcRoy** [comment]
I'm fine with that, too. Does someone have that asset for me?

**Comment by heathv** [comment]
[Here is a link to that avatar in brand repo.](https://github.com/zooniverse/Brand/blob/master/zooniverse.org/avatar.jpg)

**Comment by DarrenMcRoy** [comment]
Generics added for GZ:S and IH.
