### ISSUE TITLE
Ellipse drawing tool usability

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#926]
In talking with colleagues today, I realized why the ellipse drawing tool is so unintuitive for many users (myself included). It's based on the idea that you click the center of the ellipse and then pull outwards, which might be very reasonable for (some) astronomy projects. However, most users are accustomed to desktop software that draws ellipses by clicking a corner of the circumscribed box and then dragging to the other corner. I think this tool would become much more usable if you switched the way the tool is drawn to the circumscribed-box method -- or at least allow the project builder to specify which of the two drawing methods makes sense for their project. (Also see related issue #904.)

**Comment by vrooje** [comment]
I know it's standard in the world of graphics programs, but I actually hate the circumscribed-box method because it's nearly impossible to draw it precisely the first time. I found the from-center method weird the first time and so did everyone else I've shown it to, but I got used to it quickly.

**Comment by mkosmala** [comment]
@vrooje You know, I find it quite intuitive on astro projects where it's relatively clear where the center is. But with really blobby things like trees, it feels quite clumsy.

**Comment by brianaharder** [comment]
Another method for drawing circles/ellipses is for the first click to be a point on the circumference, and the drag-release is the major axis.  I find drawing circles this way to be more accurate than the circumscribed-box in all cases, and more accurate than the from-center when there's no obvious center, ie, craters, trees..

**Comment by vrooje** [comment]
If I'm understanding that description correctly I think it's similar to what the MWP used, right?

That was more intuitive but for ellipses it nearly always meant an adjustment to get the minor axis correct, so it made it a 2-click-and-drag tool, minimum.

**Comment by brian-c** [comment]
Dragging out from the center is what we've done on every project so far. It works fine. People who don't get it the first time will get it the second time. Let's not overthink this.

**Comment by mkosmala** [comment]
@brianaharder That sounds good, too. Would be worth trying out something like that.

@vrooje The problem is that the current ellipse tool is so free-form that it takes 3 clicks to get a decent ellipse in Season Spotter. First you place your cursor where you think the center might be. Then you drag out an ellipse. You always have to resize the minor axis the ellipse after that. And you might have to re-orient the direction of the major axis. Then you very often have to re-locate the center -- because it's not obvious where the center of trees are. 

@brian-c "It works fine." I respectfully disagree that it works fine for all yet-to-be-created projects. It's not just that people "don't get it". It's that it's a burden -- too many clicks. I am not making this up out of thin air; it's from our beta feedback. We will very likely abandon the ellipse tool for our launch.

**Comment by vrooje** [comment]
@mkosmala Would you be okay with my trying out season spotter? I'm having trouble visualizing what you mean and I want to understand this. I don't think I have a link to the project though.

**Comment by mkosmala** [comment]
@vrooje Certainly. You'll want to go here. Not all workflows include ellipses, so you might need to do a few subjects before you get to one that does.
http://demo.zooniverse.org/seasons/#/projects/mkosmala/Season%20Spotter%20DETAILS%20Beta1/classify

**Comment by vrooje** [comment]
Thanks! 

Okay, I've tried a few now. I see how the ellipse tool will usually need an adjustment even if you get the center right because the axis ratio is fixed when the tool is initially drawn.

Though, I don't really understand how you won't still have to adjust an ellipse drawn from a circumscribed box, because that relies on a symmetry too and if you can't find the center you won't get that right either. It seemed from my relatively few clicks that the bigger problem is trying to sort out where one tree ends and another begins? A tool change won't fix that.

![screen shot 2015-07-03 at 11 15 40](https://cloud.githubusercontent.com/assets/2357126/8497710/4325898e-2177-11e5-8bc4-e27697f9bce9.jpg)

Then again, I might have been doing it wrong.

**Comment by vrooje** [comment]
PS - I found the image shift workflow pleasantly easy and strangely satisfying.
