### ISSUE TITLE
summary of last post on a board doesn't update if a new thread?

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#929]
I've just updated a board on GZ Bars Talk with 2 posts: 1 in thread A, which already existed and is sticky, and 1 in thread B which I created (made the first post) and is not sticky. I updated thread A first, and then thread B most recently.

When I go back to the main project Talk page, the thread under the board title that's the "most recently updated" shows as thread A when it should be thread B. 

(Note: I mentioned the sticky thing in case it matters, but it doesn't seem to.)

**Comment by mschwamb** [comment]
Having a similar . The post in the sticky thread isn't  updating, but the one in notes for me did.  I updated in the Introduce Yourself thread under Chat and also in Notes. The one in Notes shows on the Talk board list, but not the Chat one. 

![screen shot 2015-07-02 at 7 00 19 am](https://cloud.githubusercontent.com/assets/753325/8466761/c51c0f3e-2088-11e5-8f50-70533bf1baa4.png)

**Comment by DarrenMcRoy** [comment]
Seems like this is a definite issue as far as getting the "recent" display working properly. @aweiksnar ? Level 1 sprint?

**Comment by DarrenMcRoy** [comment]
Closing as this issue is generally covered by #873.
