### ISSUE TITLE
Parsing error for simple manifest files

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#930]
For manifest files with just the file name, you get a warning saying "1 parse errors": "Row : Unable to auto-detect delimiting character; defaulted to ','" 

This is not user-friendly. There shouldn't be an error message here.

Here's my manifest, BTW:

```
name
canadaOBS_2013_03_01_153127.jpg
```

**Comment by chrissnyder** [comment]
This use case is generally taken care of by the auto-manifest now, yea?

Not defending the site throwing an error in that case, just clarifying purpose.
