### ISSUE TITLE
Duplicate project enhancement

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#931]
It would be nice if I could duplicate my project in the project builder. That way I could experiment with some stuff without worrying about putting everything back the way I found it if the experiment didn't work out well.

**Comment by vrooje** [comment]
Or possibly the ability to revert to a previous state, to prevent burgeoning dead-weight duplicates?

**Comment by mkosmala** [comment]
I'd like to duplicate, so I can create two similar projects and then show them to my collaborators so they can choose which version they prefer.
