### ISSUE TITLE
Cannot reply to existing PM conversations

### ISSUE THREAD

**Issue by brianaharder** [zooniverse/Panoptes-Front-End#932]
I can't reply to PMs sent to me, or send followup to conversations I started.  I can send new messages.  

I have received a reply from another user earlier today, so this may have broken with a recent update.  

Ubuntu 14.10, on an up to date Chrome and Firefox.

**Comment by DarrenMcRoy** [comment]
This was reported to me as well... you can't currently send a PM to someone if you were the last person to send a PM in the conversation.

**Comment by yshish** [comment]
It was actually a message between me and her. I'm not able to reply to her
message now however she was the last who wrote me. I just have to create a
new message thread. Should it has been fixed already?

2015-07-01 21:16 GMT+02:00 Chris Snyder <notifications@github.com>:

**Comment by chrissnyder** [comment]
This should be fixed as of about an hour ago. Are you still having the
problem after refreshing the page?

**Comment by yshish** [comment]
I'm sorry but it's not working for me :(

(using Firefox 38 on Ubuntu)

**Comment by brianaharder** [comment]
Not working here either.  I made a test account to send/receive messages.
After the initial message sent from the inbox, neither sender or recipient
can add to the conversation.

**Comment by mschwamb** [comment]
Should have checked - having the same exact issue if I use the inbox mail gui - could send the message if I started a new conversation. This happened a few minutes ago

**Comment by DarrenMcRoy** [comment]
So, I was able to send a second message in an ongoing conversation, but the new message appeared *above* the old one:

message from user
my second reply
my first reply

**Comment by brianaharder** [comment]
Looks like this is all functioning correctly now.
