### ISSUE TITLE
Tasks default to "questions" that need to be deleted for "drawing" workflows

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#934]
When I create a new workflow in the project builder, the default first task is a "question". However, if I want my first task to be "drawing", the initial untitled and unpopulated "question" task remains and I have to manually delete it. This is rather annoying. Please auto-delete the first "question" task if it hasn't been modified from the default when the user chooses to start with a "drawing" task.

**Comment by aliburchard** [comment]
Agreed. Not urgent or critical, but would really improve the user experience.

**Comment by aliburchard** [comment]
I'd actually prefer that NO task is automatically created -- I'm finding this consistently confusing for project builders.

**Comment by mrniaboc** [comment]
I got totally caught out by this during a live demo when I wanted to add an initial drawing task.

**Comment by aliburchard** [comment]
@brian-c could we please just not have any task created by default? I know there is another issue floating around somewhere to this effect - I've seen it trip up a lot of new project builders.

**Comment by aliburchard** [comment]
@brian-c is the backend is in place to make this happen? If so, could we please remove that default task? Would really really make my day.

**Comment by brian-c** [comment]
Looks like it. On my radar now.

**Comment by aliburchard** [comment]
❤️ 🎈 🎆 THANK YOU!!!!
