### ISSUE TITLE
Workflow order on landing page

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#935]
If you allow users to choose which workflow to work on, it would be nice to be able to specify the order in which they appear on the project landing page. Right now they appear to be in random order -- not even the order in which I created the workflows or alphabetical order or anything.

**Comment by chrissnyder** [comment]
If I had to guess, I'd say it was ordered by "last_updated_at".

I agree a predictable/controllable order would be preferred.

**Comment by aliburchard** [comment]
This would be incredibly useful. At one point I really wanted to reorder the display of workflows on wildebeest watch, but had no idea how. @chrissnyder I don't think it's ordered by last update, as my wildebeest workflows remain in the same order (which, @mkosmala happens to be in the order I created them in).

**Comment by tedcheese** [comment]
Our project https://www.zooniverse.org/projects/tedcheese/snapshots-at-sea/ has the same issue. It doesn't seem that the last edited lists on top, rather they jump around a bit at random

**Comment by edpaget** [comment]
I'll add support for this in the backend, someone will need to update it on the front-end.

**Comment by aliburchard** [comment]
Thanks!

**Comment by srallen** [comment]
Workflow orders can be modified for the project home page.
