### ISSUE TITLE
Making the Talk message gui under your inbox the one that shows up when you click on a user profile

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#937]
low in the queue - with the tiny box size and such it would be nice if the mail gui that's in the inbox page shows up when you click on a username

what shows when you click on the username

![screen shot 2015-07-02 at 6 47 35 am](https://cloud.githubusercontent.com/assets/753325/8466789/2278221c-2089-11e5-8b31-baa8ee06eb3b.png)

what shows up under the inbox

![screen shot 2015-07-02 at 6 47 30 am](https://cloud.githubusercontent.com/assets/753325/8466793/2bd16ab2-2089-11e5-8224-bedee263facc.png)

**Comment by aweiksnar** [comment]
Closed in #1199 - That page now has the cleaner looking comment-style markdown box
