### ISSUE TITLE
can't reply to a private Talk message 

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#939]
I wrote the message, hit the send button and nothing happens.

**Comment by mschwamb** [comment]
I'm using Firefox 38.0.05 on mac

**Comment by mschwamb** [comment]
Sending worked if I clicked on the username and wrote a new message to the user using the private message gui on the users profile page (not the one in my inbox)

**Comment by yshish** [comment]
#932

**Comment by mschwamb** [comment]
closing since this is a duplicate and the original has been reopened.
