### ISSUE TITLE
Page count & nav should appear at the top of the thread display too

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#943]
Often I click on a post in Talk and want to go to another page without having to scroll to the bottom. Mirroring the page navigation at the top of the post displays as well as at the bottom would be really useful.

**Comment by DarrenMcRoy** [comment]
I agree 100% with this, as does yshish -- https://www.zooniverse.org/#/talk/14/114?page=7&comment=685
