### ISSUE TITLE
Display users who are currently online

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#945]
This was *overwhelmingly* mentioned by the first crop of users to arrive on the new Talk.

They say it feels "lonely" without knowing/being able to see other users who are online.

Probably future plans, but I would be loath to discount the number one thing mentioned by our power users.

It would be nice if such a system showed both "users on Talk" and "users on current Talk." It would also be nice if it were a bit more reliable than the system on the last Talk, which could be spotty.

**Comment by aweiksnar** [comment]
@parrish Is the notifications/active_users endpoint ready to develop against?

**Comment by parrish** [comment]
Until we integrate the notifications client, it'll always be empty

**Comment by vrooje** [comment]
Just a quick note to say I agree with Darren that this will make a huge difference to the user experience once this does come online.

**Comment by chrissnyder** [comment]
Closed via https://github.com/zooniverse/Panoptes-Front-End/pull/996

**Comment by parrish** [comment]
Just to chime in on this.  An "Active User" on a project is a user that is either in Talk or on the project pages (including classification).
