### ISSUE TITLE
Would like to open links in a new window

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#946]
From what I've read (http://stackoverflow.com/questions/4425198/markdown-target-blank), Markdown doesn't directly support the opening of hyperlinks in a new window. However, the Markdown in Panoptes also doesn't support HTML, which would allow me to open in a new window. Can we have a solution that will allow for links to open in new windows, please?

**Comment by vrooje** [comment]
I'd like this to be the default behavior (for external links) as well.

**Comment by aliburchard** [comment]
+1 for this (especially as default behavior).

**Comment by mschwamb** [comment]
related to #620

**Comment by AdrianEvans** [comment]
I think this default behaviour idea should be implemented fairly quickly and is a much easier fix than changing the markdown scheme. Currently every-time somebody clicks a link they are taken away from the website. It's putting me off putting link onto pages to provide a wider research context or additional help. I don't want these things to be at the detriment to keeping people engaged with classification.

**Comment by aliburchard** [comment]
We get this request from  a lot of project builders and volunteers. *We* know that you can open in a new tab by right clicking the link, but the vast majority of people don't know that, think that hard about it, or want to have to make that extra step. I think doing this by default would be really helpful.

**Comment by chrislintott** [comment]
@edpaget @aweiksnar What say you?

**Comment by edpaget** [comment]
I don't think there's a good way to make it defualt behaviour given the markdown library we use. We can add an extension to our version of markdown so that something like `!![aasdfasdf](https://google.com)` adds the `target="_blank"`.

**Comment by aweiksnar** [comment]
@edpaget I'll look into making an extension to markdown-it, similiar to this https://github.com/leff/markdown-it-named-headers, it'd just add the target="_blank" to `a` tags

**Comment by edpaget** [comment]
Didn't realize that would be possible. Do we actually want to do that? I'd rather it be an optional thing than have every single link in every markdown element do that.

**Comment by aweiksnar** [comment]
Toggle-able on a per-link basis would be ideal. It'd have to be a modified syntax to give that level of control though. Maybe something like `[My Link](+tab+http://www.mylink.com)` could work

**Comment by edpaget** [comment]
Yeah I was suggesting the double bang at the front. But am fine with whichever.

**Comment by aweiksnar** [comment]
Ok cool, I'll see if I can put this together and we can figure out syntax later

**Comment by aweiksnar** [comment]
@edpaget I sent a PR to markdownz for this. Open for syntax suggestions there, but it's much easier to work with existing markdown tokens than to parse new ones, so I went with the url prefix. Both are possible; if you feel strongly just let me know

**Comment by AdrianEvans** [comment]
@aweiksnar - great - do you have a markdown code example of how to use this (or will they just go to target_blank by default)?

**Comment by aweiksnar** [comment]
It'll be `[Your Link)(+tab+http://www.yoururl.com)` once the the next markdownz version is deployed. I'll close this up when it's ready to use, and update the markdown help text

**Comment by edpaget** [comment]
The new version is on npm now. It should get deployed soon.
