### ISSUE TITLE
Project owners should be able to set sticky discussions for project talk

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#947]
If a user asks a really good question in my project's "help" board, or if I want to add a frequently asked question in the "help" board, I should be able to set certain threads as sticky in my project's talk. I don't see a way to do this.

**Comment by aweiksnar** [comment]
You should be able to toggle the 'sticky' label in a discussion's moderator controls

**Comment by vrooje** [comment]
Yeah, if you click on the thread and then go into the moderator controls (which is at the top of the post but easy to miss) it should be there -- don't forget to click Update (also easy to miss).

**Comment by aliburchard** [comment]
Ah, okay, that works.
