### ISSUE TITLE
Handle 500+ error codes

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#950]
In the project builder I see:
![upload_error](https://cloud.githubusercontent.com/assets/1066340/8484901/2b3a19ac-20c8-11e5-8004-8e85478ce456.png)

As a project builder, what am I supposed to make of this? What should I do?

**Comment by edpaget** [comment]
That's because that wasn't a recoverable error. We should say something like "Something horrible happened please sit tight", when 500 error codes happen.

**Comment by chrissnyder** [comment]
For what it's worth, it should already graceful fail when this happens https://github.com/zooniverse/Panoptes-Front-End/blob/master/app/api/client.coffee#L26-L27

If it doesn't, then either something else is going on, or that code just doesn't work.

**Comment by edpaget** [comment]
If it was an nginx or elb error page it might have a declared doctype... We could just look at the response status instead.
