### ISSUE TITLE
Zooniverse painfully slow after Z-wide email

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#951]
So slow I can't even use it. Just sayin'.

**Comment by DarrenMcRoy** [comment]
I think that the API is having massive issues. I think @camallen and @edpaget are on it?

**Comment by camallen** [comment]
@mkosmala yeah - we had autoscaling troubles with AWS. Should be good now, re-open if not.

**Comment by mkosmala** [comment]
Yup. Much better. Good job, guys.
