### ISSUE TITLE
Talk posts being dropped?

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#954]
I didn't see this in as a ticket. A few PFT volunteers have mentioned that they tried posting and get the success message and then the message isn't there. Also saw a few on the Zooniverse Talk so not sure if that has been solved yet

See this example from a few days ago

https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/8/120?page=1&comment=279

I've also had this behavior happen a few days ago, but haven't seen it repeat for me.

**Comment by vrooje** [comment]
Have had this too -- some GZB users mentioned it and it happened to me this morning. It seems to only be when you're commenting on a subject from the classification link, not when you're posting from the main Talk interface.

**Comment by camallen** [comment]
Looks like Object Comments POSTS from the classification link are 422'ing on the server.
> Completed 422 Unprocessable Entity in 77ms

**Comment by mschwamb** [comment]
I just noticed someone reporting this for a non-object thread in main Zooniverse Talk [here](https://www.zooniverse.org/#/talk/16/279?page=1&comment=692) while I was checking out the discussion. Maybe it's the same issue but different cause as the classification link object comments issue?

**Comment by chrissnyder** [comment]
I can't replicate non-object comments having problems. Maybe an isolated incident? If it's repeatable somewhere, that would be extremely useful in finding the cause.

**Comment by mschwamb** [comment]
I'll keep an eye out on P4T Talk for a repeat of the same non-object issue and open a ticket if I see it

**Comment by yshish** [comment]
https://www.zooniverse.org/#/projects/tedcheese/whales-as-individuals/talk/31/336 I succeeded in posting an object comment.

**Comment by yshish** [comment]
Sorry, it still happening. My object comment has just been lost but it said that it submitted successfully.

**Comment by mschwamb** [comment]
If it helps - I just made a [comment](https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/29/349?page=1&comment=919) on P4: Terrains no problem on the first attempt from the classification interface. Race condition?

**Comment by yshish** [comment]
In most cases it doesn't work for me. I succeeded only twice. Does this help you anyhow? https://lh3.googleusercontent.com/-wKJONT9qI2E/VZmZFABgyuI/AAAAAAAAIFY/-lPZo21LxI4/s0/ysh_2015-07-05_22-49.jpg

**Comment by camallen** [comment]
@mrniaboc can we reproduce this? If so this should get re-opened.

**Comment by mrniaboc** [comment]
I tried on all 4 new projects and it worked fine for me. This of course does not mean that's the case for everyone!
