### ISSUE TITLE
We need a 'delete account' option

### ISSUE THREAD

**Issue by mrniaboc** [zooniverse/Panoptes-Front-End#956]
There is no option for people to delete there account at the moment. This is making some volunteers send me angry emails.

@chrissnyder Should this go in the sprint?

**Comment by mrniaboc** [comment]
Possibly related to #5

**Comment by chrissnyder** [comment]
Did we have one before on the old site? I'd like to not add anything to this sprint, could this wait a month or so?

**Comment by chrislintott** [comment]
See the discussion on the Privacy page about account deletion. We’ve always handled these manually.

**Comment by mrniaboc** [comment]
In this case we need to add some text on the /settings page that states this, with an email to contact us.

**Comment by chrissnyder** [comment]
Cool with just leaving this on the privacy page.
