### ISSUE TITLE
Switching pages on the "Projects" tab should reset the scroll postion to the top of the page

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/Panoptes-Front-End#957]
Similar to https://github.com/zooniverse/Panoptes-Front-End/issues/906 when you switch pages on the "Project" tab the scroll position does not reset to the top of the page.

**Comment by mschwamb** [comment]
@CKrawczyk I think this is fixed. Can you confirm?

**Comment by CKrawczyk** [comment]
Yep, this was fixed at some point.
