### ISSUE TITLE
Update logged in user profile via PUT requires 'If-Unmodified-Since' header

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#96]
When updating my user profile the PUT requires the precondition header 'If-Unmodified-Since'.

**Comment by brian-c** [comment]
This is handled automatically. If the client isn't sending it, the client never got a "Last-Modified" header with the user resource (probably on sign-in).

Profile editing will be redirected to Zooniverse Home for Stargazing.

**Comment by camallen** [comment]
Cool - i'll fix this in panoptes then.

**Comment by camallen** [comment]
https://github.com/zooniverse/Panoptes/issues/516
