### ISSUE TITLE
Extra functionality for custom projects

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/Panoptes-Front-End#960]
Related to zooniverse/Panoptes#1067, as discussed with @camallen 

We need some extra features for projects that use a custom front end:

- Checkbox to state the project has a custom front end
- Disabling the classification interface (and its associated routes)
- Allow linking back to a custom URL from Talk
- Possibly a simple project page with a link to the external URL

@perry, @simoneduca, can you think of any other requirements?

**Comment by perry** [comment]
A simple key/value interface for the metadata object on workflows and subject sets, à la Heroku.

![](http://i.imgur.com/LxqbjkX.gif)

**Comment by perry** [comment]
Perhaps thats not really restricted to custom projects, but it will certainly help as they will almost certainly always require custom data fields.

**Comment by camallen** [comment]
@rogerhutchings - this will be taken care of by setting the project redirect field combined with a non-migrated flag. Also as per https://github.com/zooniverse/Panoptes/issues/1067 this functionality is already in place.

Finally project's already has a customizable configuration hash it's in the docs http://docs.panoptes.apiary.io/#reference/projects

**Comment by chrissnyder** [comment]
The project has a configuration hash, but not workflows/subject sets. For PFE projects, it doesn't really matter, but for custom projects, it's very useful to be able to do stuff like adding descriptions or images onto subject sets.

It would also allow us to extend our workflow selection from just a simple button with a name to something more appealing, like http://www.notesfromnature.org/#/archives (disregarding design issues on NfN).

That said, I don't think it's a priority at the moment, and the current in development Panoptes projects will just have to deal (Ancient Lives, Old Weather, AnnoTate, and Mammoth Bats).

**Comment by camallen** [comment]
Subject sets have a metadata hash [already](https://github.com/zooniverse/Panoptes/blob/7f60495e844b934ace76a29d953ac795abc5648f/db/schema.rb#L220) workflows don't. 

Yeah agree - having the ability to customize workflows could be nice, if anyone needs it please open up a new issue.
