### ISSUE TITLE
Why is this user's avatar not working?

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#967]
https://www.zooniverse.org/#/talk/13/102?page=1&comment=283

What's with the error message where this user's avatar should be?

**Comment by Capella05** [comment]
That is Janet Jaguar - didn't her 'new' user account (JanetPrime) get 'merged' with her original one. There were several posts about it in a different thread.

**Comment by vrooje** [comment]
Yes, I think this is a known one for that user.

However, I did just see a broken avatar image (but broken in a different way) for another user's posts:
https://www.zooniverse.org/#/talk/14/114?page=8

![screen shot 2015-07-04 at 14 15 53](https://cloud.githubusercontent.com/assets/2357126/8508028/3c17cafe-2257-11e5-9470-77544e1686e8.jpg)

**Comment by camallen** [comment]
@vrooje that user's avatar url is set but there is no data associated with it, perhaps a failed upload? If they set the avatar again it should fix this.

**Comment by DarrenMcRoy** [comment]
Here is another user whose avatar is not working:

https://www.zooniverse.org/#/talk/13/103?page=1&comment=927

![screen shot 2015-07-06 at 9 07 46 am](https://cloud.githubusercontent.com/assets/8987864/8524077/80af8f22-23be-11e5-9dd4-4de957bfe3a0.png)

Any thoughts?

**Comment by DarrenMcRoy** [comment]
And here's another, with some coding as well.

![screen shot 2015-07-07 at 9 21 23 am](https://cloud.githubusercontent.com/assets/8987864/8548320/c708c710-2489-11e5-828d-4c573b5a91cf.png)

**Comment by edpaget** [comment]
Is the solution for this issue to just replace not found avatars with the default avatar?

**Comment by DarrenMcRoy** [comment]
I am perfectly happy with that, although I'm still curious why these avatars failed to upload in the first place. But most of all, I'd like visually broken elements not to be visible. :+1:

**Comment by mschwamb** [comment]
I've re-opened rather than make a new ticket - this issue just showed up on Planet Four Terrains : Talk 

![screen shot 2015-08-14 at 12 27 08 pm](https://cloud.githubusercontent.com/assets/753325/9267418/34bd3092-4281-11e5-9680-212131c0b833.png)

https://www.zooniverse.org/#/projects/mschwamb/planet-four-terrains/talk/29/1878?comment=3988

Post was made by a volunteer a day ago, so this seems like a new behavior.

**Comment by camallen** [comment]
completely different issue here as the error messaging suggest, the api isn't respoding that the user exists on the index routes, api issue https://github.com/zooniverse/Panoptes/issues/1268.
