### ISSUE TITLE
can't manage which projects you're signed up to get newsletters for if the project is on Ouroboros

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#968]
Low in the queue, but thought I'd add this as a ticket since I noticed it -

![screen shot 2015-07-04 at 11 17 56 am](https://cloud.githubusercontent.com/assets/753325/8506274/cc7d800c-223e-11e5-8eef-750736f90084.png)

I've cut off the part for other projects that aren't launched built on panoptes that I've tried out. Only a panoptes project shows. That might be confusing whether or not you get a Bat Detective newsletter, since those projects on the old system don't show here, and when you click on profile on those Ouroboros projects it takes you to new Zooniverse home

**Comment by camallen** [comment]
@mschwamb - this is a data migration issue that we're working on and should be fixed when the data gets migrated. Please reopen if this is still not fixed in a week or so.

**Comment by mschwamb** [comment]
Will do. Might be worth putting a note so volunteers know that if they check in the meantime.
