### ISSUE TITLE
Collecting images/creating collections doesn't work properly (Whales as indi.)

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#969]
Yesterday, I marked one image with heart icon to collect as Favourite. 
Then I created a new collection and call it *Questions / Answers* and added there one image I commented.

Today I marked another image with heart but accidentally clicked twice on the icon. I expected to see the image twice in the Favourite collection but the image was actually missing there. I tried to add it again and reloaded the page but without success.
Moreover, the *Question / Answers* collection is missing there too - I can't see it under My collections. While typing its name to search the collection, it says *No results found*.

Is it supposed to be working or not yet?

**Comment by chrissnyder** [comment]
The collections interface still needs work, but this should be working.

Looking at your collections list (https://www.zooniverse.org/#/collections/yshish) I can only see created one.

Does logging in/out change what you see on that link at all?

Clicking one on the favorite icon adds it, clicking it again removes it. So that's expected behavior, though it can be communicate better. Related to #972

**Comment by yshish** [comment]
Thanks, Chris.

Yes, signing in/out changes what I see under My collections. I created the WOW (visible publicly) one today when I was experimenting with them. But the one I mentioned yesterday seems to be lost completely. 

This is what I see as my collections (signed in):
https://lh3.googleusercontent.com/-iIGcsLjOzL8/VZhDpi4kFsI/AAAAAAAAIEo/m_w4xjrwq3w/s0/ysh_2015-07-04_17-36-20.jpg
(I don't understand why there are two *Favorites* collections and what the *(11)* means.) I didn't created any collection called Favorites!) But all the images collected in both of them were collected using the heart icon.

And this is what the first *Favorites(11)* looks like when I open it..
https://lh3.googleusercontent.com/-cjOPyby4wf8/VZhDp3Rx1LI/AAAAAAAAIEs/2VKSdnEc78c/s0/ysh_2015-07-04_17-36-42.jpg

Maybe an important part, when I tried clicking on the heart icon again today, it changed its colour to red which it yesterday didn't (strange!). Yesterday, it didn't display whether the image has been collected or not anyhow.

Hope this is helpful. But at least, it definitely works better today.

**Comment by vrooje** [comment]
I'm having problems with collections too, specifically adding images to existing collections.

When I click to add a subject to a collection, my existing collections don't come up in the search box.

![screen shot 2015-07-14 at 16 47 41](https://cloud.githubusercontent.com/assets/2357126/8677642/1c8c1868-2a48-11e5-8f10-82fe85bf5342.jpg)

When I search for a collection I know exists, it doesn't come up in the search box.

![screen shot 2015-07-14 at 16 02 10](https://cloud.githubusercontent.com/assets/2357126/8677650/2be5bd5a-2a48-11e5-96cc-e7eb8446aedc.jpg)

If I delete the search text I've entered, *then* my existing collections will come up below the search box.

![screen shot 2015-07-14 at 16 02 00](https://cloud.githubusercontent.com/assets/2357126/8677656/3721f788-2a48-11e5-8e28-bacb176d515e.jpg)

But only if the search box is blank... afterwards I still can't get my collections to come up in a search.

I've repeated this several times on different subjects and sometimes waited for a long time to see if my collections would come up on their own before I've typed-then-deleted anything, and it doesn't happen.

**Comment by vrooje** [comment]
Update: the add-to-collections box from Talk is now not bringing up my collections under any circumstances. Even if I manually type in the name it seems to not find it and not add the object.

**Comment by chrissnyder** [comment]
Related to https://github.com/zooniverse/Panoptes-Front-End/issues/1130 I think

**Comment by parrish** [comment]
Consolidated to a milestone.  Summary: #1829
