### ISSUE TITLE
Advise on Logos

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/Panoptes-Front-End#97]
@chrislintott, @ttfnrob: So, when we create our logo, should we 
A) incorporate the Zooniverse logo, as is done for current projects
B) avoid incorporating the Zooniverse logo, because this is the new Panoptes world and future Panoptes projects might not really be *associated* with Zooniverse in quite the same way
C) Zooniverse doesn't care either way

I ask because if we're modeling the new make-your-own-project Panoptes, folks might copy what we do logo-wise in terms of incorporating the Zooniverse logo.

@brian-c: Are there any front-end constraints on our logo? Should it be square? Have particular non-square dimensions? Can it be a circle, oval, or weird other shape? Approximately what size will it show up?

**Comment by ttfnrob** [comment]
I think B makes the most sense. This isn't 'our' project as you say. Also
if we ask people to incorporate the Zooniverse logo then we'll end up will
a thousand different messy versions of it after a time :)

You're that this sets a precedent though, so @brian-c @chrislintott -
thoughts?

**Comment by brian-c** [comment]
I'd say B. Maybe "sponsored" (or whatever we call them) projects can incorporate a Zooniverse logo somehow, or maybe they'll get a little badge or something, but I don't think anybody but us should be using our logo.

We're really just talking about project avatars here. They'll always be square. PNG or JPEG. We'll probably limit the size to 50K max. They'll be shown 20 at a time in some places, and that's a whole extra megabyte to download.

I think the largest they'll show up will be on the projects page, where they can be about 600px. That's pretty big; maybe that design needs a re-think, @heathv?

**Comment by rcheng3** [comment]
"powered by" or "sponsored by" will be good. Will there be a place in creating new project to upload the project logo - then there will be an automatic layout incorporated the "sponsored by Zooniverse" logo?
Just a thought.
