### ISSUE TITLE
Can't read/post comments to images from collections nor figure out their ID number

### ISSUE THREAD

**Issue by yshish** [zooniverse/Panoptes-Front-End#974]
It should be possible to access images directly from collections and to be able to see the comments/discussions. I'd like to be able to get to all the answers to my questions this way (I'm used to create collections for my questions for the scientists and then go back to them when in doubts how to classify). There is no way to see my last posts at this moment since the Profile page doesn't display them any more (or not yet?) 

Please, consider giving such data back to the Profile page. 
Thanks.
And being able to read image ID numbers in the collection would be very helpful too.

*Not sure whether it is a duplicate of #898 or another problem*

**Comment by chrissnyder** [comment]
Related to #971

**Comment by chrissnyder** [comment]
I think this was closed in https://github.com/zooniverse/Panoptes-Front-End/issues/898. Please yell if I misread your issue!
