### ISSUE TITLE
Suggestion: let Talk users decide how many posts per page

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#975]
On the Talk boards, 5 posts per page is really low. I think it should be 10 at minimum, but really I think there should be an option for a user to choose between 5 and a large number, like 100 (which would be more useful when a project is really busy).

**Comment by DarrenMcRoy** [comment]
I think this would be a really nice and helpful feature as well. Five posts is definitely too few.

**Comment by parrish** [comment]
Closed by #1386
