### ISSUE TITLE
Confusing that messages and settings links on the profile page of another user takes you to your settings and inbox

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#977]
When you click on a user's profile it the settings link takes you to your user settings and messages takes you to your messages. I find that very confusing since those links are 'on' someone else's profile page

Maybe the messages link should take you back to the message gui for to write a message if you were navigating someone else like looking at their collections and the setting link be removed 

![screen shot 2015-07-05 at 9 32 18 am](https://cloud.githubusercontent.com/assets/753325/8509941/d7d92ff4-22f8-11e5-8bd1-d79dc234dedc.png)

**Comment by aweiksnar** [comment]
Closing this up, Since settings is now on a distinct page
