### ISSUE TITLE
Mobile browsing

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#98]
Have just tried the demo project but only had my phone at the time. Project loaded fine in Safari/iPhone/iOS 7, but only the subject image and headers were visible on the screen at the default zoom, even in landscape mode. Zooming out worked fine and then I classified happily (it's a question tree project so I couldn't test marking tasks). 

Haven't tried the iPad yet.

No idea how important this is at this stage, but just noting it.

**Comment by chrissnyder** [comment]
Old issue, but definitely there are a fair number of problems with the mobile experience.

Closing only because I think if we left open every mobile issue at this point, the list is going to get even more crowded. Will change course when we start focusing on that.
