### ISSUE TITLE
Subjects didn't upload properly but the entries on the front end still got created but says 0 subjects uploaded

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#980]
Making a marking interface for my summer student. The images didn't upload properly, but the front end still created entries that I could delete, but not view images from while saying 0 subjects were created. 

The front end shouldn't create an entry if the image isn't successful I think. 

![screen shot 2015-07-06 at 3 44 13 pm](https://cloud.githubusercontent.com/assets/753325/8517822/1e7c8a1a-23f7-11e5-9271-6bd6a428d1b1.png)

**Comment by chrissnyder** [comment]
We added an additional check for the uploading part awhile ago.

Subject count a dupe of #1128 so consolidating there.
