### ISSUE TITLE
Subject exists and show in the classification interface but can't be previewed under the subject set project builder page

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#981]
I'm making a project for my summer student to mark boulders in Planet Four images (thanks for making a create toolset!) so it's a private project at the moment. I had trouble uploading images. Finally got it work, but they're not showing up in the preview on the project builder but the images are showing up in the project classification interface. 

![screen shot 2015-07-06 at 4 05 07 pm](https://cloud.githubusercontent.com/assets/753325/8518024/e3aff83e-23f8-11e5-8217-5d3610268296.png)

same image showing in the interface

![screen shot 2015-07-06 at 4 04 53 pm](https://cloud.githubusercontent.com/assets/753325/8518033/edcd8b74-23f8-11e5-96cb-3a246bad6121.png)

@chrissnyder since you were looking at this the last time I added you to the project - let me know if I should make it public for other people to take a look

**Comment by mschwamb** [comment]
Actually can't add you @chrissnyder since the search doesn't return bumishness  says it's not a username.

**Comment by mschwamb** [comment]
It's project 264 if that helps

**Comment by camallen** [comment]
@mschwamb I'll check it out if you add me to your project.

**Comment by mschwamb** [comment]
Thanks. You're added now - search showed your username just fine.

**Comment by camallen** [comment]
@mschwamb I'm pretty sure this is due to the subject uploader using the PUT url's instead of switching to the GET url's to view the subjects. After successfully finishing uploading the project builder should either not allow subjet views or refresh the subject set to get the correct representation of the linked subjects.

@mschwamb you can fix this just by reload the page or going to another link and back to the subject set (if that fails try a reload on the subject set).

**Comment by mschwamb** [comment]
Thanks @camallen for the help

I tried going to another page in the project builder and back and that hadn't fixed it earlier. 

A refresh of the browser  as you suggested did make the images appear. 

It would be good if it was able to show the subject images after upload since I think a lot of people will try and check to make sure it uploaded without a browser refresh.

**Comment by camallen** [comment]
Agreed, it's a matter of switching the internal state to have the different URL representations.

**Comment by mschwamb** [comment]
Still happening and reported again in #2272

**Comment by jelliotartz** [comment]
Closing as this has not received comments or action for over a year.
