### ISSUE TITLE
not allowing an owner to add someone to a project without specifying their role

### ISSUE THREAD

**Issue by mschwamb** [zooniverse/Panoptes-Front-End#982]
I was adding Cam to a project I built today and accidentally hit enter without including a role. The front end displayed him as added without any check marks. Should the front end return back an error if that happens or prevent you from adding someone without a role checked?

**Comment by chrissnyder** [comment]
Eh, I'm pretty indifferent here. I don't know why somebody would add a user without a role, but I also don't feel it's broken behavior to let them.

**Comment by mschwamb** [comment]
Fine to label as don't fix or close. No strong opinions. It looked like a bug to me, but I tend to be in the don't let your users do stupid things if they can be avoided, so I'd remind them to select a role, but if the development thinks its fine to add people without roles than that's fine too.

**Comment by parrish** [comment]
Yep, going to wontfix this.
