### ISSUE TITLE
Fails to add tester role to project collaborator on talk

### ISSUE THREAD

**Issue by camallen** [zooniverse/Panoptes-Front-End#983]
When testing #942 i noticed that when I add the 'tester' role a POST to talk to add roles fails with a 422. Might be related to the talk string / integer id's thing https://github.com/zooniverse/Talk-Api/pull/46.

![screen shot 2015-07-06 at 09 50 33](https://cloud.githubusercontent.com/assets/295329/8518718/c8dd8618-23c4-11e5-93ac-fb16eb6eee94.png)

**Comment by aweiksnar** [comment]
closed via https://github.com/zooniverse/Talk-Api/pull/46
