### ISSUE TITLE
View comments/posts made by given user

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#993]
On Talk 2.0, when you click on a user name, you see their collections, your message history, and also whatever posts/comments they've made. This makes it really easy for science teams to review volunteers for potential moderators. 

Can we add this into new Talk?

**Comment by DarrenMcRoy** [comment]
I certainly hope so. +1

**Comment by aweiksnar** [comment]
- Closed via #1018
