### ISSUE TITLE
Getting stuck in "Search"

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/Panoptes-Front-End#994]
If you search for something from your project's talk page (e.g. https://www.zooniverse.org/#/projects/aliburchard/wildebeest-watch/talk)  and get "no results" then you get stuck with nothing to click on to "clear" the search. Even if you refresh the page or clear the text out of the search box, you still just see "no results found."

You *can* click on project "Talk" but it seems sort of round about and unintuitive instead of being able to clear the search filters.

**Comment by mschwamb** [comment]
What about simply adding a 'Return to  Discussion Boards' button next to the search box if you make a search?
