### ISSUE TITLE
Notifying envelope should be more prominent and have a number

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Panoptes-Front-End#995]
The envelope that shows that you have a new PM (or, hopefully, anything, in the long run) should:

a.: be more prominent... the white filler is very easy to overlook, when the base state is a white outline. Maybe a bright color?
b.: include a number telling you how many notifications you have.

**Comment by chrissnyder** [comment]
+1

I think we should just rip off other groups and use the symbol that has become synonymous with notifications: the red bubble in the upper right with a number.

**Comment by vrooje** [comment]
+1 to this Issue, +1 to Chris' reply.

**Comment by aweiksnar** [comment]
Going to close up via #1309 . The messages count isn't in the designs, but will probably be added when the notifications feed includes than the inbox
