### ISSUE TITLE
Line tool: "X" should be hidden when line is actively being drawn/edited

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Panoptes-Front-End#997]
[Suggestion](https://www.zooniverse.org/#/talk/18/108) from an external project builder that I completely agree with: the big "X" in the middle of the line tool shouldn't show up when you are either drawing the line or actively editing it. The X makes it very hard to precisely draw short lines.

**Comment by rogerhutchings** [comment]
The X is now located off to one side, and moves to the other side if the line end point is in the other direction.
