### ISSUE TITLE
UX issue: When replying to an early part of comment thread, focus should scroll to or highlight the reply box

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Panoptes-Front-End#999]
[deleted]

**Comment by alexbfree** [comment]
@camallen advised me that the avatar errors are not relevant to this issue so the above network errors can be ignored.

On reflection this seems to be a UX bug. When you click reply, the screen should bring the newly created reply box into focus, using a scrollTo or modal.

At the moment it feels like nothing happens because the reply box appears off screen (if you click reply on an early part of a thread near the top of page)

**Comment by alexbfree** [comment]
Also I would add, the UX when you actually post a comment could really be improved... the buttons feel very unstyled, and when you hit submit the confirmation appears in a strange place with not much styling. It seemed to jump unexpectedly after posting too.

**Comment by mschwamb** [comment]
This would be very good to have implemented soon. Also worth noting Talk 2.0 does this behavior so volunteers from other projects will be expecting this behaviro

**Comment by DarrenMcRoy** [comment]
I'd like a general overhaul of how replying works, as per #888. The current system makes extensive discussion ugly and cumbersome.

**Comment by mschwamb** [comment]
@aweiksnar and @chrissnyder - is there a possibility to add this to Sprint 2?
